### ISSUE TITLE
Enable alternative soil water models to be implemented

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1002]
Currently SoilWat is the only model that will work.  Need a SoilWater Interface and an example of an alternative model

**Comment by zur003** [comment]
As far as alternative models go, I coded a model to Andrew's specification as SoilWater2 in C# in "classic" APSIM, which should port easily to ApsimX. And what about SWIM?

**Comment by HamishBrownPFR** [comment]
That would quality as an alternative.  With the interface working now, you would just need to have the alternative model implement the ISoilWater interface and then in can be dropped onto the soil to replace SoilWater
