### ISSUE TITLE
SoilWater needs a major refactor and speed up.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#1005]
We also want to make separate small classes for each soil water process so that an individual process can be swapped for a different implementation.

We also need to remove the excessive creating of arrays. This is causing the garbage collector to continually pause a running simulation to clean up the allocated arrays.

**Comment by hol353** [comment]
New water balance model:

This is very close to being complete. Jenkins runs all sims without error. There are major diffs in the stats in the AgPasture validation and minor diffs in all other files. I have already fixed one bug to do with the calculation of coverTotSum (Line 222 of EvaporationModel) that helped with the AgPasture sims, probably because there are multiple plant canopies. I suspect there are more cover bugs in the new water balance model that need fixing.

To test, uncomment the converter999 at the bottom of Converter.cs

**Comment by hol353** [comment]
Simulations for some of the bigger diffs in stats are:
wheat - Lincoln2015Nit250IrrFull
sugarcane - 13 Kunia 1991_93 H73_6110 P
soybean - all soilwater - Sutherland2017SowEarly
maize - HustWt - Lincoln2012NitLowIrrFull
Barley - spikewt - MCPD09_10CultBoomaNit0IrrNil

**Comment by hol430** [comment]
@hol353 I'm getting null errors whenever I open a file. The errors are handled internally, so it's not a critical problem or anything, but it slows things down a bit. Looks like it occurs when we copy properties from the official WaterBalance json inside the OnCreated method of ModelCollectionFromResource. Is this supposed to happen?

![image](https://user-images.githubusercontent.com/36427516/76817812-9cc3bc80-684f-11ea-90be-a119f91368ab.png)

**Comment by hol353** [comment]
That's right I'd forgotten about that. Last week I couldn't find a way around the throwing of exceptions in this code. For WaterBalance we need to copy the parameters from the resource. Problem is that the model isn't initialised properly at that point. This is a common problem with many of our models. Perhaps we need to put a whole bunch of if statements protecting the calls to WaterTableModel.Depth property, evaporationModel etc. A bit ugly. Any suggestions?

**Comment by hol430** [comment]
I guess adding null checks is probably the way to go.

**Comment by hol430** [comment]
Actually - can't we ignore those properties with an xmlignore or jsonignore attribute?
