### ISSUE TITLE
A potential bug in FillingRateFunction.cs

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#1011]
In Line 21 of `FillingRateFunction.cs` , a `NumberFunction` is defined and used in the `Value`. 

   IFunction NumberFunction = null;

However, there are no `NumberFunction` in the wheat model for `DMDemandFunction` of organ `Grain`, instead of `GrainNumer` defined. I believe APSIMX used the `NumberFunction` in the organ `Grain`. This code could cause strange behaviour if `NumberFunction` and `GrainNumber use the different values. 

I suggest to modify `NumberFunction` into `GrainNumber` in `FillingRateFunction.cs`, but not sure whether this change will cause any conflict to other models.

**Comment by HamishBrownPFR** [comment]
I see your point but there is a reason for it being the way it is.
- GrainNumberFunction is what is used to parameterise the grain number model
- ReproductiveOrgan.GrainNumber is a property that is assigned GrainNumberFunction.Value each day and is mainly there for reporting.
- FillingRateFunction also needs to know the number of organs it is filling and in this case it references GrainNumberFunction.  This is inserted as a function to allow flexibility in how and where it is used.  If we hard coded GrainNumber into FillingRateFunction then it reduces the flexibility of where it can be used.  The cost is it is possible to introduce odd behavior into the model, as you point out, so caution is needed.

**Comment by HamishBrownPFR** [comment]
Hi @byzheng Are you happy with this response.  I am not sure I have fully understood your issue.  If not respond.  If so please close the issue
.

**Comment by byzheng** [comment]
@HamishBrownPFR Thanks for your explanation.
