### ISSUE TITLE
Remove the need for models to derive from Model class

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#1047]
I need to be able to have models that aren't derived from base classes. For example, the Soil class is used extensively by many applications outside of APSIM. I don't want to have to bring in the assembly Models.dll just to use the soil classes. 

Instead, the plan is to wrap models in a 'ModelWrapper' class. The parent/child relationship will be in 'ModelWrapper' class rather than in Model.cs. The user interface and APSIM next generation infrastructure will work with ModelWrappers. 

This is going to require a lot of changes and so will take quite a while.

**Comment by hol430** [comment]
@hol353 How does using a model wrapper class help with this problem? You'll still have the problem that ModelWrapper, like Model, is defined in Models.exe, which people will have to import if they want to get at this info.

**Comment by hol353** [comment]
Yes I'm not sure anymore. I don't think we can remove the need for a Models base class. I'm closing this issue.
