### ISSUE TITLE
APSIM is slow

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1053]
APSIM is very slow to run an experiment or group of runs.  On my machine, the simulations seem to finish but APSIM takes a very long time to do some post-processing.  In many ways, the post processing seems longer than the simulations themselves.

**Comment by zur003** [comment]
As far as I can tell, this is a problem with Serialization/Deserialization. Recent changes seem to have made it much worse.

**Comment by zur003** [comment]
I've submitted a pull request on APSIM.Shared that tries to address this. Now it needs someone to test and commit.

**Comment by HamishBrownPFR** [comment]
I am finding APSIM very slow recently also.  @zur003 Not sure what you mean that you have submitted a pull request to APSIM.shared.  The comit process is different for APSIMX (where a pull request is necessary via a remote branch) and APSIM.shared (where you just push directly from your local branch into the master).  Just looking at Source tree now.  It appears the change you made to APSIM.shared yesterday is in the master.  I will pull this and see if it has speed things up for me

**Comment by HamishBrownPFR** [comment]
@zur003 Yes, it is noticeably faster at starting up simulations after clicking run now.  

@hut104 has this change sped things up for you??

**Comment by zur003** [comment]
Sorry, I wasn't (and am still not) quite clear about the appropriate procedure for committing changes to APSIM.Shared. I didn't know I could push directly into the master, and I'm not sure that it's even desirable for me to do so, since a bit of prior "peer review" is usually a good idea. @hol353 - can you clarify how this is intended to work, and is there any possibility of improving the commit mechanism?

**Comment by hol353** [comment]
The process is the same as for ApsimX. Submit a pull request and I'll have a look at it. Jenkins doesn't run though - that is one difference. You shouldn't be able to commit and push directly to the master branch on APSIM.Shared.

**Comment by HamishBrownPFR** [comment]
Now I'm confused, this is different to how we discussed it in Toowoomba and I don't think it is consistent with the way I have APSIM.shared set up.  Likely I have got APSIM.shared set up wrong.  Currently I have cloned it dirrectly onto my computer so if I change anything the only place I can push it is back to the master.  To do a pull request don't you have to have the repository forked onto a remote branch which you can push changes to and request them to be pulled into the master from there.  Should we be forking APSIM.shared also?

**Comment by hol353** [comment]
The process should probably be that developers fork the APSIM.Shared repo and then create a branch and raise pull requests as per ApsimX. Reduces confusion due to different processes.

**Comment by HamishBrownPFR** [comment]
Agreed.  Is there any way to enforce that structure?  That is not what I am currently doing.  With the APSIMX repository we can't push dirrect to the Master, has to be merged in via pull request.   Should it be the same for APSIM.Shared.

**Comment by hol353** [comment]
I've changed the repo so that only Admins can push direct to Master. Hamish, you are an admin though so it'll stop others but not you.

**Comment by zur003** [comment]
@hut104 - Can this issue now be closed?

**Comment by hut104** [comment]
I'm not sure if I have been testing your code but the tip revision takes the same time to run the wheat prototype test set on my tablet pc and my 32 core workstation.
There seems to be something particular to my machine. even a simple experiment from that test which has two Sims takes a long time.
We may need Dean and Justin to diagnose.
Neil

Sent with AquaMail for Android
http://www.aqua-mail.com

On 24 August 2016 9:36:22 AM Eric Zurcher <notifications@github.com> wrote:

@hut104<https://github.com/hut104> - Can this issue now be closed?

-
