### ISSUE TITLE
Zadok stage not available in scripts

### ISSUE THREAD

**Issue by fai04d** [APSIMInitiative/ApsimX#1071]
Zadok.Stage is able to be reported, but is unable to be used in scripts.

**Comment by hol353** [comment]
Manager scripts are compiled by .net and need to behave like a proper c# class. They can only access variables via public properties or fields. The wheat model doesn't have a public property or field for zadok. 

The report model has some 'smart' code in there that breaks down the variable name into it's components separated by period characters and then tries to find each component. This is why report works and manager doesn't.

Work around in manager: link directly to Zadok e.g.

[Link] Zadok zadokStage = null;

**Comment by fai04d** [comment]
Manager link did not work as there's no link in the code. Adding a link to Zadok in Plant15.

**Comment by fai04d** [comment]
I've had another request to use Zadok stage number.  A user wants to use it to modify RUE during run time. It would be good to be able to modify the model with a Zadok based interpolator, but at least being able to grab the value in a script would be good.

I haven't been able to get the linking working. An example would be good if it is in fact working.

**Comment by hol353** [comment]
Make sure the manager script is NOT under a folder. Folders will change the scoping and so it may not work if manager is under a manager folder. Put the manager script directly under the paddock and try having a link like this:
[Link] Zadok zadokStage = null;

Should work.

**Comment by fai04d** [comment]
Nope. Used the Wheat example, but it still can't link. Full code of the script below:

```C#
using System;
using Models.Core;
using Models.PMF.OldPlant;
using Models.Soils;
using Models.Utilities;
using APSIM.Shared.Utilities;

namespace Models
{
	[Serializable]
	public class Script : Model
	{
		[Link] Clock Clock;
		[Link] Fertiliser Fertiliser;
		[Link] Summary Summary;
		[Link] Plant15 Wheat;
		[Link] Soil Soil;
		[Link] Zadok zadokStage = null;
		
		[EventSubscribe("Commencing")]
		private void OnSimulationCommencing(object sender, EventArgs e)
		{
		}
		
		[EventSubscribe("DoManagement")]
		private void OnDoManagement(object sender, EventArgs e)
		{
		}
	}
}
```

And here's the simulation tree:
![image](https://cloud.githubusercontent.com/assets/11882275/22007638/037d0ae0-dcc0-11e6-8b2a-a6d962303b8f.png)

And the error:
`[ZadokRUE]: The type or namespace name 'Zadok' could not be found (are you missing a using directive or an assembly reference?). Line number: 18
`

**Comment by hol353** [comment]
Ahh the error helps. Looks like you're missing a using statement for Zadok. Find out what c# namespace Zadok is in and add a using statement to the top of your script.

**Comment by fai04d** [comment]
Thanks, that was it. I'll add the script to the toolbox then close this with the push.
