### ISSUE TITLE
Externalise SWIM ksat and theta functions

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1075]
@fai04d @hut104  @hol353 

For #1057 I need to values of ksat and theta and SWIM provides nice functions to calculate these from the standard information in the soil water node.  

I am thinking to move these functions into a separate class.  The code is currently in APSIMX in Models\Soils\SWIM.cs but I am not sure if this code is doing anything in APSIMX at the moment and I am not sure what your plans @fai04d are with connecting the new SWIM to parameters in APSIMX.  Anyone got any thoughts on how this should be done or if anything else is in track here

**Comment by fai04d** [comment]
I'm still trying to get the thing to give me the right numbers. I don't believe that code you've referenced is in use. We haven't decided how we'll integrate the new SWIM; will we allow other models to interface with the whole code base directly, or use data classes to pass information around? We'll keep the need to make variables visible in mind.

**Comment by HamishBrownPFR** [comment]
OK, I will just pull the bits I need out into a seperate class for the time being and integrate it into MultiPoreWater to provide a use case.  We can change this around if a better way becomes aparent
