### ISSUE TITLE
Unable to use variable created in one manager script in another script

### ISSUE THREAD

**Issue by hor198** [APSIMInitiative/ApsimX#1081]
Tried linking to another script using 
[Link] Script _Scriptname_;
doesn't work

**Comment by hol430** [comment]
The problem here seems to be the same as in #2603, in that we have multiple Script classes within the Models namespace. Is there a reason that we name all of our manager scripts `Script`?

**Comment by hol353** [comment]
Not really. What do you suggest?

**Comment by hol430** [comment]
Closing this now, as this does actually appear to be possible:

```csharp
DateTime date = (DateTime)Apsim.Get(this, "[OtherManagerScript].Script.DateVariable");
```
