### ISSUE TITLE
Mouse-scroll in folders with 5+ graphs zooms AND scrolls

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#1082]
When in a folder showing 5 or more graphs and hovering over one of the graphs, mouse scolling will do both zooming the hovered graph and scrolling up/down the page.

Before scrolling:
![before-scroll](https://cloud.githubusercontent.com/assets/17924125/17997133/0a0727d4-6b6d-11e6-9c21-820a8b7501f7.jpg)

After scrolling:
![after-scroll](https://cloud.githubusercontent.com/assets/17924125/17997136/1085b350-6b6d-11e6-9a08-c3912413583d.jpg)

I am not sure how to improve/solve this. The scroll-to-zoom is very useful, as is the normal scroll, but both at the same time is nothing you ever want.

**Comment by zur003** [comment]
This works a bit better in the Gtk# version of the user interface.

**Comment by hol430** [comment]
After some testing, it appears that in the current version, the effects of scrolling depend on where the mouse cursor is - you can either zoom or scroll, but not both at the same time.

@wolfgang-boku I know you said the other day that you haven't been using a recent version of APSIM, so I'm going to assume that this was either fixed sometime in the last 18 months, or, like Eric said, was never really an issue in the Gtk# UI.
