### ISSUE TITLE
Reinstate option to export datastore to text files

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#1089]
Very useful to be able to diff .db files. Need to avoid memory full errors for very large .db files.

**Comment by zur003** [comment]
I think it would be good to put up a message box letting the user know whether this operation succeeded, and where the files were written. Ditto for exporting to Excel. Currently the only feedback the user receives is a glimpse of the wait cursor.

**Comment by hol353** [comment]
It should already show a wait cursor. I don't like message boxes but it should write to the status window where the files were written. Reopening...
