### ISSUE TITLE
UI location for entering k at DUL

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1126]
@hol353 @hut104 @fai04d  I have recently moved the code for fitting moisture and k curves out of SWIM into a separate class called Hydraulic properties and have made it so the parameter kDUL can be set for each layer (rather than a single value for the profile) as it was previously.  Currently these values are entered in a grid on the HydraulicProperties view (See below).  I feel like these should probably be along side ksat parameters but don't want to move them into the Water tab (where Ksat is currently) without discussing with you guys.  Should I just leave there parameters where they are or should they be moved onto the Water node?

![image](https://cloud.githubusercontent.com/assets/7295858/18235963/3950ecfe-7375-11e6-8677-a95aa6f103e0.png)

**Comment by hut104** [comment]
These properties (ie the suction and conductivity at DUL) are really only specific to SWIM and it’s way of specifying properties.  They are not standard measures and so probably should not go in the water tab.  The water tab is used for several soil database applications.  We probably don’t want to affect those packages.
I’d suggest leaving them in the hydraulic properties tab.  They will need another overhaul when we get the new version of SWIM into APSIMx anyway.

Neil.

**Comment by HamishBrownPFR** [comment]
Cool, happy with that
