### ISSUE TITLE
Redesign of the APSIM Test system

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1133]
The initial APSIM test system is functional, but needs to be enhanced to capture lessons from recent use.  A list of requirements will need to be developed ASAP.  These enhancements will need to be implemented prior to major refactoring works within SoilN or Soilwat as changes could impact on any or all tests within the APSIM test set.

**Comment by hut104** [comment]
Some requirements

1) Tests need to be evaluated across the test set, not on a file basis as currently.
2) A "dashboard" approach would allow the tester to see at a glance which tests have past or failed across the entire test set.
3)  Perhaps just allow a "show at a glance" approach - ie just show the tests that failed.  We should allow showing of all results, but once it gets big, you only want to see what failed.
4) The storage of stats within version control through the simulations themselves seemed like a good idea.  This allows for easy determination of status for any particular release or version of a file etc.  However, it is not necessarily easy to determine what tests have failed where when changes to code may influence tests across the test set.  Perhaps a database of test results is required.
5) Following on from previous requirement, the database of test results should be seen as an important outcome in itself.  In future, these stats about our stats may become important data for understanding our processes.  So we need to be able to follow how they have changed over time.
6) It would be good if stats could even be generated for individual groups of data (e.g. could we show goodness of fit for wheat model in various regions)
7) Stats need to be enhanced to explain how much of the variation is captured due to differences in environment vs management.  e.g. we currently may have a model with a great fit overall because we have wet and dry sites, but capturing next to no N response within sites.
8) Stats acceptance needs to be closely integrated into the test process (GIT/Jenkins) if possible.  The current system of having to run simulations on our PC, accept tests and commit apsimx files is too time consuming and prone to error.
9) It would be good if a model developer could graph goodness-of-fit (e.g. RMSE, NSE) over time for a given variable.
10) The test process needs to create reports for the AI reference panel, but also for the web site.  e.g. as for issue 9, it would be good if the Wheat doco, or the wheat model page on apsim.info, could include a graph of key metrics over time (e.g. NSE for yield over time) to show how model improvement is going.

**Comment by hut104** [comment]
Note that this issue is similar to one raised by Hamish #799

**Comment by hol353** [comment]
Completed here: http://www.apsim.info/APSIM.PerformanceTests.Portal/
