### ISSUE TITLE
Add "Run On Cluster"

### ISSUE THREAD

**Issue by mcauliffer** [APSIMInitiative/ApsimX#1137]
Add in an option to run simulations on a cluster (current sim(s) or directory of sims, as per classic). Initially this will use the Microsoft Azure platform that we are testing with Microsoft but will be intended to be extensible for other cluster types (Amazon, google, condor?)
At this stage it is planned to target the GTK version with the assumption it will become the standard interface.

**Comment by sno036** [comment]
@hol430 Bug crept into the run on cluster.

Before pointing to the licence files:
**Tools Directory not found: C:\Program Files\APSIM2018.03.02.1632\Bin\tools" before pointing it to the licence file**







The argument must not be empty string.
                      Parameter name: accountName
                         at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpty(String paramName, String value)
                         at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor(String accountName, String keyValue, String keyName)
                         at UserInterface.Presenters.NewAzureJobPresenter.GetCredentials(Object sender, EventArgs e)
                         at UserInterface.Presenters.NewAzureJobPresenter.Attach(Object model, Object view, ExplorerPresenter explorerPresenter)
                         at UserInterface.Presenters.ExplorerPresenter.ShowInRightHandPanel(Object model, String viewName, String presenterName)

**Comment by hol430** [comment]
Is this the first time that you've tried using this via an installed version of Apsim?

**Comment by sno036** [comment]
Yes.  The version run from VS crashed so I tried that.  Just thought – I didn’t update Shared.  Just done that now and rebuilt everything and got the same error message.



The argument must not be empty string.
                      Parameter name: accountName
                         at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpty(String paramName, String value) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\Util\CommonUtility.cs:line 142
                         at Microsoft.WindowsAzure.Storage.Auth.StorageCredentials..ctor(String accountName, String keyValue) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Auth\StorageCredentials.cs:line 139
                         at UserInterface.Presenters.NewAzureJobPresenter.GetCredentials(Object sender, EventArgs e) in C:\Work\ApsimX\ApsimNG\Presenters\NewAzureJobPresenter.cs:line 650
                         at UserInterface.Presenters.NewAzureJobPresenter.Attach(Object model, Object view, ExplorerPresenter explorerPresenter) in C:\Work\ApsimX\ApsimNG\Presenters\NewAzureJobPresenter.cs:line 45
                         at UserInterface.Presenters.ExplorerPresenter.ShowInRightHandPanel(Object model, String viewName, String presenterName) in C:\Work\ApsimX\ApsimNG\Presenters\ExplorerPresenter.cs:line 647

**Comment by hol430** [comment]
There appear to be 2 problems here. The first is that the tools directory is not included in the installed version of Apsim. @zur003 is there anything special I need to do with this directory to have it installed?
 I've included the directory in source control, but that's it.

The second problem is to do with where the credentials are saved. I think I've isolated the issue and will try to get a fix out this morning, after a bit of testing.

**Comment by zur003** [comment]
Are these tools cross-platform or Windows-only? In either case, the InnoSetup configuration will need to be modified to include them in the Windows distribution. If they're cross-platform, then the scripts for building the Linux and OS X installers will need to be updated as well.

**Comment by hol430** [comment]
They don't actually get run on the local machine - they get uploaded to Azure. That said, the Azure functionality will not run on Unix machines - a check is made against the user's OS, and if it isn't Windows, the job submission/viewer (and associated Azure dlls) will not be loaded. So to answer your question, these tools are only needed on Windows installations.

**Comment by hol353** [comment]
It would be better if they were cross platform. What is needed to get them to run on LINUX and OSX?

**Comment by hol430** [comment]
I believe the dlls don't run on Linux - my memory could be faulty however. I will see if I can test this. 

I haven't been able to test on OSX because I don't have a Mac handy, but I'm guessing we'll have the same problem.

**Comment by zur003** [comment]
I haven't looked into how all this is implemented, but the Tools folder does include some Windows executables (7za, CMail, and wget) and a number of .cmd scriptsl. The executables all appear to have Linux / OS X counterparts, but the installers should probably flag them as prerequisites. The scripts will need to be re-written for sh or bash. AzCopy and the .dlls are all .Net assemblies; with luck, Mono can cope with them, but that will require testing.

**Comment by hol430** [comment]
That should all be doable - I'll see what I can do once I fix this credentials issue.

Should this - porting Azure functionality to Unix - be its own issue, or is it okay to hijack this one?

**Comment by hol353** [comment]
There hasn't been a 'resolved' against this issue so keep using the same issue.

**Comment by hol430** [comment]
Val, this pull request should fix your issue. I can't be certain though, as I don't have any valid credentials to test with. 

Eric I don't know that the contents of the tools directory actually need to be modified for compatibility with other OSs. None of these files actually get run on the user's machine - they just get uploaded to Azure, and are run there. 

After some testing, it seems that mono Mono is able to load the Azure .dll files, but I can't actually do much testing without valid credentials. Might be worth signing up for a free Azure trial account to test this sort of thing, even if it only lasts 30 days.

**Comment by hol353** [comment]
Yes, sign up for some credentials. Eventually I think we'll buy some time.

**Comment by sno036** [comment]
Is anyone else having trouble attaching files?  Will send by Slack.  The Maize example will go up to Azure but will not run.

**Comment by hol430** [comment]
Did any model files get submitted? You can check this by re-submitting the job and checking the 'save model files' check box (you will also need to specify a directory to save them to).

**Comment by sno036** [comment]
Nothing was saved to the directory nominated

**Comment by hol430** [comment]
I am able to start running the Maize example on Azure if I run from the 'simulations' folder (the top level node). I will look into why this is necessary, but it's a bit of a moot point for now, because I still run into an error anyway. I believe this error may be caused by an the compute node not having .NET 4.6 installed. 

Are you able to check if this is installed?

**Comment by sno036** [comment]
@mcauliffer - are you able to assist here?

**Comment by mcauliffer** [comment]
Yeah, it's using 4.5.51650 on the "standard_d5_v2" VM that we're currently using. I'll talk to Susan from Microsoft and see if it's possible for them to update .Net the VM image, otherwise we may need to see if we can install it each time a node spins up (costing us some compute time). I suppose another alternative would be to downgrade ApsimX to .Net 4.5 and forego the nice succinct job completion api call, but I assume it's just a matter of time before we need to go to 4.6 so that would just be a stalling tactic. Will let you know what Susan says.

**Comment by hol430** [comment]
Should the Run on cloud option still say "Under development (DO NOT USE)"? Users won't be able to use it without credentials anyway.

**Comment by sno036** [comment]
Good point.  Can remove the text.  I should have information about how to get a sub next week

**Comment by hol430** [comment]
@sno036 this pull request should fix your issue.
