### ISSUE TITLE
UI crash when entering numbers into grid cell in PMF XYpairs view

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1139]
entering data into any grid cell (the ones I have tried anyway, causes instant crash of UI.  
![image](https://cloud.githubusercontent.com/assets/7295858/18297265/690ef708-7503-11e6-99a6-a17054a5f968.png)

In Debug it breaks as shown below.  The problem is comming because the data object is empty 

![image](https://cloud.githubusercontent.com/assets/7295858/18297310/acff631c-7503-11e6-84cd-16fb81a307a7.png)

**Comment by zur003** [comment]
Actually the data object is NOT empty. But it doesn't hold a column named "Y" - the column name is actually "Y\r\n()". I think there may be something here that I broke with some recent changes in the way Units logic is handled. I hope to have a fix shortly...
