### ISSUE TITLE
SQLite error running current revision

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1159]
I cannot run anything in APSIM X.  Have deleted everything and pulled down a completely fresh version and doing right-click run or F5 of simulations that should be Ok (e.g. examples) results either in no action at all or an error saying the SQLite is not open.  See attached screenshot from a debugger run.  Any suggestions?  Thanks, Val

![capture](https://cloud.githubusercontent.com/assets/12176269/18457361/43c9e9aa-79ac-11e6-9c55-142fce6247ce.JPG)

**Comment by zur003** [comment]
Interesting problem. Are you running on 32-bit or 64-bit Windows? The "BadImageFormatException" suggests a possible mismatch between 32- and 64-bit. But that shouldn't happen, since UserInterface.exe should always run as 32-bit...

**Comment by sno036** [comment]
I'm running Windows 64 bit.  Windows 7 Professional.  I last used APSIM X (and it didn't have any issues) last week on 5, maybe 6, September.

**Comment by zur003** [comment]
I can confirm that I see exactly that behaviour, with that error, if I compile UserInterface.exe to run as a 64-bit application. However, the build you "pulled down" should have been built with the "Prefer 32-bit" option set, which instructs the application to run as 32-bit on all platforms. I'm also running on Windows 7, 64-bit, but I see no problems with the current version.

**Comment by sno036** [comment]
![capture](https://cloud.githubusercontent.com/assets/12176269/18459906/79d549da-79c1-11e6-9d15-fcd5739216ed.JPG)

Just ferretted around in the properties of UserInterface and found that the "Prefer 32-bit" was not checked (screen shot attached).  I checked it, built it and it ran fine (as you suggest above!).  

I don't think that I changed this????? so ???

Thanks - as ever! - Eric.

**Comment by zur003** [comment]
The way this stuff gets handled changed slightly with the move to version 4.5 of the .Net frameworks. Looks like I might not have had all the settings right in all configurations when making that change. It may be that the Prefer 32-bit flags wasn't set for debug configurations. I will check, and correct if necessary.

**Comment by zur003** [comment]
Yeah. Mea culpa. The flags wasn't set for Debug builds. A fix is on its way.
