### ISSUE TITLE
Model finding wrong value from xml

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1162]
I have just found a bug in the wheat model where DMRetranslocationFactor in the stem (marked 2 in the screen shot below) was finding the value for StructuralFraction because one of its sub functions was also called DMRetranslocationFactor (marked 1 in the screen shot).  This is easily fixed by renaming the offending function.  However, I am worried that there are other cases of this unnoticed in the code.  We have had this problem before and I thought we had solved it but don't recall for certain.

We have fixed this problem in the build now so attach a pre-fix apsimX file for reproduction of the problem.
![image](https://cloud.githubusercontent.com/assets/7295858/18494972/10a64286-7a6e-11e6-974e-3000b8348020.png)

**Comment by HamishBrownPFR** [comment]
Can't attach .apsimx files.  the problem is present in Prototypes/WheatValidation.apsimx in  commit 6ea2c5a444488e6b0170eecd3e94d7fa4a6eccc2 and earlier.

**Comment by HamishBrownPFR** [comment]
@hol353 I would like to be certain there are not more of these problems in the wheat model.  Is there any way of including a test or exception for this?

**Comment by HamishBrownPFR** [comment]
@hol353 Hi Dean.  Sorry to have to bug you on this but Neil and I are keen to get the wheat model up for review at the next reference panel and want to be certain we haven't got any more of these issues in the wheat model.  Will you get a chance to look at this some time soon?

**Comment by hol353** [comment]
Will try and look into this today or tomorrow.
