### ISSUE TITLE
Remove Photoperiod from Crop models

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1172]
@hut104 Should crops have their own photoperiod calculation or should they just get this from the met object.  Only reason I can think why it should be in plant is if different plants have a different twilight angle for perceiving photoperiod.  However, I can't think of an example where we have used anything other than -6.  Is there any reason to keep this here?
![image](https://cloud.githubusercontent.com/assets/7295858/18570611/8ce48bb8-7bff-11e6-8f52-d4de0e49e949.png)

**Comment by hut104** [comment]
Soterios uses a different sun angle for soybean and I think the old sunflower model did as well.

**Comment by HamishBrownPFR** [comment]
OK, we will leave it there,
