### ISSUE TITLE
Refactoring of Chicory test set

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1186]
We are moving to an approach where the validation and sensibility tests are in the one APSIMX file for a given crop - this helps with the documentation.
The chicory model has this, but there are two files and it is not clear which file is the correct version.

Currently, when we are refactoring the crop code we need to manually edit both these files so that they are maintained.  It would save time if we could get these back to one file.

**Comment by hut104** [comment]
@rcichota How are we going with this one?  Do you want me to have a go at cleaning this up?

**Comment by rcichota** [comment]
I don't know how the two simulation are still there, I thought that I had combined them and deleted the sensibility one on my previous pull request. This was a couple of weeks back. Sorry for not checking this up.

**Comment by hut104** [comment]
?All good.

I was just going through the list closing all my leftover issues that were cluttering the system and I noticed this one still there.

I'll leave it with you.

Neil.

________________________________
