### ISSUE TITLE
Move around in intelisence box in Report object using up and down arrow keys

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#119]
Intelisence in the report properties tab is really good but it is anoying how you have to type to get things started them move to the mouse to select things.  Would be nicer if we could use the up and down arrow keys to move the selection within this box.

**Comment by hol353** [comment]
Is this still a problem? If from the manager or report I type '[maize].' the intelisense comes up and I can use the up/down arrows fine without having to use the mouse.

**Comment by HamishBrownPFR** [comment]
This is working properly now.
