### ISSUE TITLE
Length property of root class needs fixing

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1197]
The Length property of ZoneState has several problems.

1) it needs renaming as it is the total root length
2) It is the sum of root length densities currently rather than total root length (ie it is the sum of mm/mm^3) which makes no sense.  Each layers RLD should be multiplied by layer thickness when summing.

I had suggested removing this entirely by having a public property which is the root length (mm/mm^2) vector.

**Comment by HamishBrownPFR** [comment]
Is it even used for anything?  I have got a feeling I put it in there when I was trying a few different things simulating potato N uptake but never did it properly.  Could just be deleted?

**Comment by hut104** [comment]
I thought I tried deleting it some time back but had issues.  We could try that first.

**Comment by rcichota** [comment]
I was checking how the plants uptake parameters were defined and found out that Potato uses the Root.Length in the function defining MaxDailyUptake. A search on APSIM folder show that it is used in two potato simulations as well as on Grapevine prototype, so it seems that if these are changed appropriately, than the Length can be deleted
