### ISSUE TITLE
Please read this if you compile your own copy of ApsimX

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#1218]
We are about to transition from the Windows.Forms GUI to a Gtk# GUI for ApsimX (see issue #626). If you intend to compile ApsimX (as most of us will from time to time), there are a couple of things you will need to do first:

1) You will need to install GtkSharp for Windows. You can get an installer by going to [http://www.mono-project.com/download/](http://www.mono-project.com/download/), and clicking on the "Download Gtk#" button. This will install a number of DLLs; the folder holding those DLLs should be added to your PATH environment variable (by default, the folder will be \Program Files (x86)\GtkSharp\2.12. bin).

2) There are 3 other DLLs that you need to obtain which are not a standard part of Gtk# and are not available via NuGet. These are: Mono.TextEditor.dll, Xwt.dll and webkit-sharp.dll. I have packaged these into an archive available [on Bob.apsim.info](http://bob.apsim.info/files/Assemblies.7z). These files should be extracted into the ApsimX\ApsimNG\Assemblies folder.

There are a few other things to note:
- If you want to design user interface elements for the Gtk# GUI, you may want to obtain a copy of Glade. I obtained my copy from [http://ftp.gnome.org/pub/GNOME/binaries/win32/glade/3.8/glade-3-8-5-installer.exe](http://ftp.gnome.org/pub/GNOME/binaries/win32/glade/3.8/glade-3-8-5-installer.exe). There is currently no Gtk# designer that integrates with Visual Studio.
- If you normally just do an "upgrade" to obtain a new copy of ApsimX, you probably don't need to worry about this. We will be putting together an installer that will "just work" (in theory).
- There are versions of the Gtk# libraries available on NuGet. Don't be tempted to install them (at least not at this time). The NuGet libraries install Gtk 3, but the ApsimX builds are targetting Gtk 2. Don't try to use both at once.

**Comment by zur003** [comment]
Your attention, please. I'm hoping commit some changes early next week that will allow the ApsimNG GUI to work nicely on Macs, but doing so will mean that you will need to have yet another assembly, not available via NuGet, available on your build machines. I've added this assembly, MonoMac.dll, to those already in
[http://bob.apsim.info/files/Assemblies.7z](http://bob.apsim.info/files/Assemblies.7z). As mentioned above, you will need to get a fresh copy of this and extract it into your ApsimX\ApsimNG\Assemblies folder.

**Comment by hol353** [comment]
@zur003 Can we close this one?

**Comment by zur003** [comment]
Yes, I think it can be closed as an Issue, but you should nag me to write some proper documentation about compiling the GUI.

**Comment by hol353** [comment]
There is already some doco here: https://apsimnextgeneration.netlify.com/development/contribute/1-compile/

Do we need more?

**Comment by zur003** [comment]
Yes, I think we need a bit more about installing the Gtk# libraries, but the netlify pages are where that information belongs.
