### ISSUE TITLE
Incorrect NFixation parameters for Oats_AutumnForage in SCRUM

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1225]
The settings for N fixation for Oats_AutumnForage seem to infer a high N fixation potential.  This should be a zero N fixation potential.

**Comment by ric394** [comment]
@hut104 @hol353 Is this still relevant? Couldn't find anything for Oats_AutumnForage.

**Comment by par456** [comment]
Old issue that is no longer relevant. Open a new issue if it is still occuring.
