### ISSUE TITLE
Problems with upgrading APSIM Next Generation

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1226]
When installing apsim Next Gen I found that
1) I get an error when it uninstalls, reinstalls, and then tries to run the UserInterface.exe - it always says that the exe is missing
2) If I install version 1166 I get the error above, but then when I go back to the updater I see a version 1187 to install.  If I install that version, and go back to upgrade I then see that the latest version to install is 1166 again.  If I then install 1166 it then says I can install 1187..... and so on.

**Comment by hol353** [comment]
This from Phil S:
![image002](https://cloud.githubusercontent.com/assets/1943827/18854963/63d50cd4-8492-11e6-873b-833e778041db.jpg)

**Comment by zur003** [comment]
And why are none of the builds since 21 September showing up?
