### ISSUE TITLE
Solution rebuilds every time APSIM is started from VS.

### ISSUE THREAD

**Issue by fai04d** [APSIMInitiative/ApsimX#1253]
Every time you hit the Start button in VS (or press F5) the entire solution rebuilds even if nothing has changed since the last start. This slows debugging considerably as you have to wait about 40 seconds for the build to complete.

The issue seems to be related to CopyLocal: 
1>Project 'Models' is not up to date. CopyLocal reference source 'C:\apsimxtest\packages\ExcelDataReader.2.1.2.3\lib\net45\Excel.dll' is more recent than 'C:\apsimxtest\Bin\Excel.dll'.

Copying the DLL manually just results in another DLL giving the same issue. Have the dependencies been rearranged or something like that?

**Comment by hol353** [comment]
It isn't a problem for me. If I do repeated builds it is virtually instantaneous and says:
========== Build: 0 succeeded, 0 failed, 9 up-to-date, 0 skipped ==========

**Comment by jbrider** [comment]
Mine is slow, but not 40 seconds...
1>------ Build started: Project: Models, Configuration: Debug Any CPU ------
1>  Models -> D:\Projects\ApsimX\Bin\Models.exe
2>------ Build started: Project: Importer, Configuration: Debug Any CPU ------
2>  Importer -> D:\Projects\ApsimX\Models\Bin\Importer.exe
3>------ Build started: Project: UserInterface, Configuration: Debug Any CPU ------
3>  UserInterface -> D:\Projects\ApsimX\Bin\UserInterface.exe
========== Build: 3 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========

Greg's is much slower - didn't put a watch on it, but it's output is different again..
1>------ Build started: Project: Models, Configuration: Debug x86 ------
2>------ Build started: Project: SWIMFrame, Configuration: Debug x86 ------
2>  SWIMFrame -> D:\Apsim\ApsimX\Bin\SWIMFrame.exe
1>  Models -> D:\Apsim\ApsimX\Bin\Models.exe
3>------ Build started: Project: Importer, Configuration: Debug x86 ------
3>  Importer -> D:\Apsim\ApsimX\Models\Bin\Importer.exe
4>------ Build started: Project: UserInterface, Configuration: Debug x86 ------
5>------ Build started: Project: ApsimNG, Configuration: Debug x86 ------
4>  UserInterface -> D:\Apsim\ApsimX\Bin\UserInterface.exe
6>------ Build started: Project: UnitTests, Configuration: Debug x86 ------
6>  UnitTests -> D:\Apsim\ApsimX\Tests\UnitTests\bin\Debug\UnitTests.dll
5>D:\Apsim\ApsimX\ApsimNG\Views\ExplorerView.cs(209,45,209,63): warning CS0067: The event 'ExplorerView.ShortcutKeyPressed' is never used
5>D:\Apsim\ApsimX\ApsimNG\Views\GridView.cs(38,57,38,68): warning CS0067: The event 'GridView.ButtonClick' is never used
5>  ApsimNG -> D:\Apsim\ApsimX\Bin\ApsimNG.exe
========== Build: 6 succeeded, 0 failed, 3 up-to-date, 0 skipped ==========

I didn't see any references to CopyLocal on either machine - is that coming up through the build output Justin?

**Comment by hol353** [comment]
Since I did a pull, it is a problem for me as well. This indicate the problem has surfaced recently i.e. last few weeks. Someone want to have a look into it? Jason?

**Comment by jbrider** [comment]
I won't get a chance until after next week, but will have a look then if it doesn't annoy someone enough to fix it sooner.

**Comment by fai04d** [comment]
To see the CopyLocal reference you need to turn on Diagnostic Debugging.

Tools > Options > Build and Run > MSBuild project build output verbosity, then in the output tab, select Build.

I've tried this on my laptop and desktop and with a new clone. Shaun is also getting it. I agree with Dean that's it happened somewhat recently, but I'm not sure what's caused it.

**Comment by jbrider** [comment]
I removed the excel dll error by deleting the file from the Bin folder.
Then I got an error about MathNet.Numerics which was referenced from UserInterface.csproj but not in the nuget config file. Deleting the reference appears to have worked on my machine.

**Comment by fai04d** [comment]
Hasn't had an effect on mine. Steps above cause same issue. Maybe there's something wrong with my local config.

**Comment by fai04d** [comment]
Tried it on my home machine; same problem.

**Comment by fai04d** [comment]
Setting CopyLoocal = False in the Models project for the Excel and MathNet libraries resolves the issue, but I don't know exactly how this affects DLL output so I'm not going to commit the changes.

**Comment by jbrider** [comment]
Did you try cleaning out the packages folder and the bin folder manually?
I think I tried that initially and it removed the excel message which produced the MathNet message which had a version issue.

**Comment by fai04d** [comment]
Yeah wiped the whole lot. Even cloned a new repo. Still had the same problem. Only setting the above parameter worked so far. Shaun is having the same problem.

**Comment by hol353** [comment]
Mine is now fine following Jasons patch.
