### ISSUE TITLE
Product Registration Page shows "Server Error"

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#1275]
When clicking on the link on https://www.apsim.info/ in the "APSIM Next Generation" section, the redirect leads to https://www.apsim.info/Products/ProductRegistration.aspx which shows the following:
![server-error](https://cloud.githubusercontent.com/assets/17924125/19551876/b5378944-96ad-11e6-9bb4-9d5c5b1ed3dd.jpg)

However, the link at https://www.apsim.info/Products/Downloads.aspx redirecting to https://www.apsim.info/APSIM.Registration.Portal/Main.aspx works

**Comment by hol353** [comment]
This has now been fixed.

**Comment by wolfgang-boku** [comment]
Does not seem to work now, I still get the same Error (tried different browsers and incognito mode).

**Comment by hol353** [comment]
I fixed this link in yellow:
![image](https://cloud.githubusercontent.com/assets/1943827/19630010/1cd0adb4-99c5-11e6-992e-1affe2320d1f.png)
 You must be referring to a different link. Can you post a screen shot?

**Comment by fai04d** [comment]
I'm running a link checker over the site now. It's already found a number of bad links. I'll fix them up.

**Comment by wolfgang-boku** [comment]
Dean, yes I was referring to the link you highlighted. It still leads to https://www.apsim.info/Products/ProductRegistration.aspx which shows the described error.
I think the problem is not the link, but that the target URL simply does not exist.

It seems to me that the correct address is https://www.apsim.info/APSIM.Registration.Portal/Main.aspx

**Comment by fai04d** [comment]
I've fixed that link; it changed when we moved to the new web service and wasn't updated on that page.
