### ISSUE TITLE
ApsimX downloaded via Website is other (buggy) version than via Upgrade

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#1276]
Right now, the download on the website (via Product Registration) is version 1271 (which is buggy - Graphs do not work), while the upgrade within ApsimX says 1253 is the newest version (and does not show 1271).

**Comment by hol353** [comment]
This has now been fixed. The web site should download 1253. 1271 shouldn't be released yet.
