### ISSUE TITLE
Adding new graphs not working

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1280]
I have been trying to add some graphs to a simulation using the menu > add model > garph > series options.  The Graph and Series objects appear in the UI OK and the report tables appear in the drop down lists alright but the x and y lists are empty.  Also the series view is coming up with x2 and y2 boxes which only ever happens when things arn't working.  I have tried addeding graphs in lots of simulations to test and it doesn't seem to be working anywhere.  If you copy a graph in a simulation that already has graphs it seems to work but if you have a simulation file with no graphs and try to copy one into that file the same problem occurs.  

![image](https://cloud.githubusercontent.com/assets/7295858/19709328/1d26a732-9b82-11e6-9906-49dfb8c523bf.png)

**Comment by junqi108** [comment]
In the plant IDE existing xy pair graphs works fine, however, when you add a new xy pair function or copy an existing xy pair function, the graph on the view does not update to reflect the values in the properties gird. 
![image](https://cloud.githubusercontent.com/assets/13222562/19709535/b6e8b652-9b83-11e6-8294-c4c2b03514a2.png)

**Comment by junqi108** [comment]
Thanks very much, Hol.
