### ISSUE TITLE
All UI tables and input screens should show units

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#130]
The importance of units was brought to light during our APSIM workshop in Iowa where folk are having to convert between metric and imperial units.  Many tables or features in the APSIM UI have numbers without units.  e.g. in the graphing component.  Units should be shown EVERYWHERE.  Perhaps the units tag should be mandatory in all apsim script objects and on all APSIM variables.

**Comment by junqi108** [comment]
Would be very nice to show units in the user interface to reduce the confusion. For the moment, although you can use units tag in the source code, they are not displayed in the user interface. I added some units in the user interface in my grapevine model.
