### ISSUE TITLE
Graphs not discriminating factor levels properly

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1303]
They only seem to find the first treatment and put the rest as ?  The same is happening in the potato validation
![image](https://cloud.githubusercontent.com/assets/7295858/19838913/a3fa3918-9f3d-11e6-8101-146a3bfa3735.png)

**Comment by rcichota** [comment]
I also noticed that the option "Include series name in legend" is not working either. This happened after updating ApsimX this weekend.
Also, I am having issues with graphs that have more than two series, some of them are not showing at all (no legend nor graph), this is for graphs made in the past (noticed that in the Chicory). If I delete that series and add it again, all seem to work fine

**Comment by rcichota** [comment]
The option to plot cumulative values has also stopped working, no values are shown when this option is ticked. I also noticed that loading the graphs (changing between graphs for example) takes a lot of time (more than it did last week). And editing them, especially typing an axis title, is so slow that is quite unbelievable. No matter how you type, letters only appear one every second or two...
