### ISSUE TITLE
Problem with ApsimX install on clean machine

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#1320]
One of our users can install ApsimX OK but cannot run the user interface. It works fine on my development machine but I can reproduce the problem on a VM that has never had APSIM on it before. The old UserInterface.exe works fine. The ApsimNG.exe does not. Missing files?

@zur003  Can you please look into it?

**Comment by zur003** [comment]
Yeah, there's probably a missing DLL. The problem will be working out just what it is. I did test the installer on what I thought was a reasonably clean VM and didn't have any problems, but I must have overlooked something. I don't suppose there are any helpful error messages?

**Comment by hol353** [comment]
No helpful error message. Just a windows dialog box saying the application has crashed.

**Comment by zur003** [comment]
The good news is I can reproduce this. Looks like a number of the Gtk# DLLs are not being included - now I have to work out just why....
