### ISSUE TITLE
Position graph tool tips in readable position

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#133]
The tool tips on the graph are handy but on the right hand side of the graph the disappear off the side of the screen.  Can they be positioned so they are always on screen rather that always to the right of the pointer.

**Comment by hol353** [comment]
I can't fix this one. It is a bug somewhere deep inside of OxyPlot. The work around is to pan the graph with the right mouse button down and then click on the graph point.
