### ISSUE TITLE
GTK UI - Increase font sizes on graphs as per standard UI

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1333]

**Comment by zur003** [comment]
To my eye, the font sizes appear the same, but the font weights are different (axis labelling in bold on the Windows.Forms version, but not with Gtk#). If there's more to it than that, could you attach some screen captures showing the problem?

**Comment by hut104** [comment]
![image](https://cloud.githubusercontent.com/assets/11881178/19991928/850ccafc-a285-11e6-8005-9d0a6a7709af.png)

**Comment by hut104** [comment]
Try with a smaller sample

![image](https://cloud.githubusercontent.com/assets/11881178/19991947/ae8dd1d2-a285-11e6-8367-6b582999e14e.png)
