### ISSUE TITLE
GTK UI - Font sizes are too small in general

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1335]
Fonts as smaller in treeview, property view, and just about everywhere.  Can we get them back to the standard UI size?

**Comment by zur003** [comment]
Sure, if you really want to.  Edit the file {APSIM install directory}\etc\gtk-2.0\gtkrc. In this file, there is a section starting with "style "msw-default" (at line 20). Add a new line in this section reading 

font_name="'segoe ui' 9"

(Or insert any other font and size you like, for that matter). 
The resulting snippet should look something like this:
...
style "msw-default"
{
  font_name="'segoe ui' 9"
  GtkWidget::interior-focus = 1
  GtkOptionMenu::indicator-size = { 9, 5 }
  GtkOptionMenu::indicator-spacing = { 7, 5, 2, 2 }
  GtkSpinButton::shadow-type = in
...

Save the file and restart the GUI.
