### ISSUE TITLE
GTK UI - Home page should include the file paths below the filename as per standard UI

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1336]

**Comment by zur003** [comment]
Full paths pop up when you mouse over.  Is that inadequate?

**Comment by hut104** [comment]
I think Dean designed the current UI to follow normal designs used in Windows Apps etc now that have the icon, with the file name on the right, with the path directly below that.  The Office Suite do this for example.  It's somewhat of a modern design.  We were trying to follow the ways things like Windows 10 are going.

**Comment by hut104** [comment]
Note that Dean also has the file path in a grey text
