### ISSUE TITLE
Phenology class includes an unused link to thermaltime function

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1379]
remove it

**Comment by hol353** [comment]
It is referenced by a manager script in FieldPeaValidation.apsimx and Potato.apsimx and PotatoValidation.apsimx.

**Comment by hol430** [comment]
This thermaltime function is now used in phenology, camp, and emergingphase. Can this issue be closed?

**Comment by hut104** [comment]
Perhaps close this, and I can refactor things later to remove this.
