### ISSUE TITLE
Graphs: Vary Marker Type does not work

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#1382]
Since the latest upgrade (maybe before), varying the marker type in eg. bar charts does not work anymore.

Now (vary marker does NOT work):
![apsim-no-marker-variation](https://cloud.githubusercontent.com/assets/17924125/20526104/e03f8c20-b0c2-11e6-8710-aa6278f50990.jpg)

Before (works):

![apsim-vary-marker-ok](https://cloud.githubusercontent.com/assets/17924125/20526096/d92c98b0-b0c2-11e6-904a-8225bd171ce8.jpg)

Edit: Varying line type does also not work.

**Comment by hol353** [comment]
Vary by marker type seems to work for me:
![image](https://cloud.githubusercontent.com/assets/1943827/21031445/44694bbc-bdef-11e6-8384-a93f1ace2098.png)

I wonder if the problem is that you have SimulationID as the X variable. This isn't a good idea I suspect.

**Comment by wolfgang-boku** [comment]
I had SimulationID as X variable only because SimulationName did not work in an older version.

With the newest version 1367 (and SimulationName as X) I still have the same issue.

![apsimxvarymarkertype](https://cloud.githubusercontent.com/assets/17924125/21051622/8046d9d8-be21-11e6-8c89-233f7db53111.jpg)
