### ISSUE TITLE
Remove APSIM2016.10.27.1163 from upgrade list

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#1384]
Since I am having problems with the graphs in the most recent version of ApsimX (1334), I installed it again and upgraded to an earlier version, which does not start at all: APSIM2016.10.27.1163
I installed it on 2 different machines (both Windows 10, 64bit), with the same effect.
Please remove it from the upgrade list.

Edit: The same goes for 1303

**Comment by hol353** [comment]
This happened at the time when we were modifying the build system. These few builds slipped through our checking processes. We can't easily take out the installs that don't work unfortunately. This shouldn't happen again.
