### ISSUE TITLE
Can we compile manager with debug symbols?

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#139]
This would give an error with a line number at run time.

**Comment by zur003** [comment]
This is almost trivial to do, but the necessary change needs to be made in APSIM.Shared, not ApsimX.
 I've made that change, and issued a pull request, but merging of the APSIMShared code requires a bit of manual intervention. Is there a better way?

**Comment by hol353** [comment]
I've merged your pull request. Next time someone does a pull request on the ApsimX repo, this change to APSIM.Shared should be used. Not ideal but it'll work for now.
