### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#1390]
The UI is buggy and shows strange artifacts, eg. not showing the expand/collapse +/- signs next to folders and nodes.
I have ApsimX on two machines, where only one has the described issues (Windows 10, 64 bit, fresh install; Lenovo T460s). The other works fine (also Windows 10, 64 bit; HP EliteBook 8540w).

I checked two versions of ApsimX: 1329 and 1320. Below some screenshots.

![apsim_ui-bugs1](https://cloud.githubusercontent.com/assets/17924125/20555131/a2e901e6-b160-11e6-8988-858a39171604.jpg)
![apsim_ui-bugs2](https://cloud.githubusercontent.com/assets/17924125/20555132/a2f8d152-b160-11e6-8a2d-e98719687e91.jpg)
![apsim_ui-bugs3](https://cloud.githubusercontent.com/assets/17924125/20555133/a2fc97e2-b160-11e6-98a6-e78e236932a9.jpg)

**Comment by zur003** [comment]
I saw this same problem today on one of Enli Wang's computers (also 64-bit Windows 10).

**Comment by zur003** [comment]
This appears to be a problem when Hi-DPI displays are used. As a temporary work-around, try setting the environment variable GDK_SCALE=1. 
If someone can test this "fix", I'd appreciate knowing whether it works.

**Comment by wolfgang-boku** [comment]
@zur003 Thanks, this works for me. However, the font and symbol size is very small, working in this setting is hardly possible.

**Comment by zur003** [comment]
I've done a bit more investigation, and this appears to be a bug in the Gtk# distribution we've been using. The problem arises with high DPI displays on Windows 10. I'm attempting to "fix" this by reverting to slightly earlier versions of libgdk-win32-2.0-0.dll and libgtk-win32-2.0-0.dll in the ApsimX distribution.

It looks like a case of the set of changes needed for full support of hi-dpi displays being only partially implemented. With the older versions of Gtk#, Windows automatically did basic expansion of the application windows, which works but leaves text looking a bit "blurry". The Gtk people have been trying to improve this, but only got half-way there: fonts are now scaled correctly to render more sharply, but other bits of layout are being positioned incorrectly.
