### ISSUE TITLE
Accept csv weather files

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#1415]
Creating the space-separated column-width-fixed (.met) weather files is regularly causing problems. Why does Apsim not accept the widely used and accepted (and much more fail safe) csv format (and extension)?

In addition, Apsim could to the calculation which is currently done in the separate program tav_amp.

**Comment by zur003** [comment]
ApsimX already accepts CSV format weather files, although it requires that they have the file extension ".csv". Tav and amp are calculated automatically, but one problem remains: there is no mechanism for specifying the geographical location of the site. Longitude doesn't matter except for mapping purposes, but latitude is needed for daylength calculations. 

I think what's actually needed here is:
1. In the file selection dialog, .csv should be included as a known "file type", so the user is aware that the option exists.
2. If a .csv file is used, the user interface needs to provide a mechanism for the user to enter the latitude and longitude of the site.

**Comment by wolfgang-boku** [comment]
Those are good suggestions I think.

In addition, a short documentation on which criteria the csv file needs to fulfill (separators, quote text or not). I actually did not manage to convert my .met weather files to a .csv which ApsimX accepts ("invalid number of lines" error although that is not the case).

**Comment by hol353** [comment]
Simplest is something like:
latitude, -27.0
longitude, 148.0
tav, 10.0
amp, 15.3
Date, MaxT, MinT, Radn, Rain
2017-01-01, 23, 22, 15, 0
2017-01-02, 22, 25, 17, 0
...

**Comment by hol430** [comment]
That's not consistent with the official [RFC 4180 csv format](https://tools.ietf.org/html/rfc4180) though:

> Each line should contain the same number of fields throughout the file.

More importantly, most csv parsers will not be able to parse a file which looks like this. Meaning you can't (easily) open and edit your file in R, python, excel, etc.

**Comment by hol353** [comment]
Yes you're correct. Perhaps it wasn't a good suggestion. I don't like any of the other suggestions though except maybe having columns for latitude, longitude, tav, amp.

**Comment by hol430** [comment]
Yeah I don't know if there is a good solution to this. The longitude column option is the only reasonable one I can think of but it seems very wasteful, although in practice the performance impact is probably negligible.

We wouldn't need tav or amp - these are calculated automatically in next gen. Do we need longitude?

**Comment by wolfgang-boku** [comment]
I'd suggest to get rid of all non-date dependent variables in the met file (ie lat, long, tav, amp). They can easily be manually input in the GUI

**Comment by hol353** [comment]
The non-date dependent variables need to be stored somewhere. We have many users who don't use the GUI.

tav and amp are supposed to be long-term averages. If the weather file is only one season then APSIM will be calculating a short-term average. In this situation, the user should really be putting in the long term average and not relying on APSIM to calculate it. Most users don't do this though.

**Comment by wolfgang-boku** [comment]
In this case, I'd rather use an extra, simple txt file for tav, amp, lat, long and have a csv met file that fulfills all requirements for automated reading (eg. in R), as @hol430 suggested previously.
