### ISSUE TITLE
Warnings for incorrect soil properties

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1418]
I had an experiment where SAT > total porosity.  It created millions of warnings and a DB file that was about 1GB.  That caused APSIM to run out of memory.
Really, the error doesn't need to be echoed endlessly, in fact, it could simply be changed to a fatal error.

**Comment by rcichota** [comment]
I had a similar issues in the past, and agree with Neil that a fatal error would be best. However the calculation of porosity using the default particle density value could cause problems. Volcanic soils for instance can have different values and thus the calculation of porosity would be wrong and a fatal error would be annoying. Wouldn't it be better then to have particle density as a input in the 'Analysis' node of soil?? It could be read as optional...

**Comment by hut104** [comment]
I think the idea of a particle density that is an input is OK.  I know that I have worked with people who have used slightly different values and that did make some work difficult.  However, I wouldn't make it optional.  I think we are moving toward avoiding such as much as possible.

**Comment by hol430** [comment]
@hut104 @hol353 In #4188 I've changed SoilWat to throw a fatal instead of giving these errors. Unfortunately, we're now getting hundreds of errors on Jenkins. Do we want to take the time to fix all of these soils or should I change this back to a warning, but only show one warning per simulation?

**Comment by hol430** [comment]
Not sure why this is closed because we're not finished yet
