### ISSUE TITLE
Mortality of total stem in structure model

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#142]
In structure model (Structure.cs), plant population mortality reduces the plant population and total stem population.

Here I copy parts of source codes in the Structure.cs

	//Reduce plant population incase of mortality
	if (PlantMortality != null)
	{
		double DeltaPopn = Plant.Population * PlantMortality.Value;
		Plant.Population -= DeltaPopn;
		TotalStemPopn -= DeltaPopn;
		ProportionPlantMortality = PlantMortality.Value;
	}

`TotalStemPopn` is only reduced by the `DeltaPopn` which is the reduction of main stems. In this case, we assume only main stem is death which is caused by plant  mortality.

I believe the correct assumption is whole plant will be dead for plant mortality. So my proposed change is 

	TotalStemPopn -= DeltaPopn * TotalStemPopn / Plant.Population;

The number of branching (or tiller) in each plant is calculated first (`TotalStemPopn / Plant.Population`), then calculated the change of total stem.

@HamishBrownPFR Let me know if you have different thoughts.

**Comment by HamishBrownPFR** [comment]
Yes you are correct.

So far this plant mortality function has only been applied in Kale (which was done in Plant2 and not in APSIMX yet) which is a non-branching crop.  So implementing the change you suggest will not affect the current crop that uses that chunk of code and will make it correct for branching crops also.
