### ISSUE TITLE
Oil Palm Doco needs work

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1457]
The Oil Palm documentation seems to need some work as the PDF doesn't seem to look right.

**Comment by zur003** [comment]
The main issue here is that the auto-documentation generator uses the contents of Memo objects when generating the PDF, but does so in a naive way. The MemoText field of a Memo is in Markdown format, but no attempt is being made to convert the Markdown tags into corresponding RTF. This results in a range of problems: non-ASCII characters aren't being handled correctly, and paragraph boundaries are being lost. Any attempt to use **bold** or _italics_ will also give unintended results.

There is some open-source code for converting Markdown into MigraDoc/PDF (e.g., at https://github.com/benfoster/MigraDoc.Extensions) that we should be able to incorporate to make this work better.

**Comment by zur003** [comment]
Hmmm. I wasn't quite correct about that. It's _trying_ to convert the Markdown, but not getting everything right. There is a problem with ANSI vs. UTF-8, and it's also not converting \r\n into new paragraphs correctly.

**Comment by hol430** [comment]
Closing this issue now, as this seems to be working well on Ubuntu.
