### ISSUE TITLE
Upgrade version has no description

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1459]
APSIM upgrading seems to work now.  I've downloaded and installed my fixes from yesterday

Note however this strange tip revision on the system – it has no description.

![screenshot](https://cloud.githubusercontent.com/assets/11881178/22233897/996ae296-e23f-11e6-8227-5252d8d8248d.jpg)

**Comment by zur003** [comment]
I've issued a pull request on APSIM.Builds that I think will fix this problem. Can you check and merge if OK, @hol353?

**Comment by hol353** [comment]
Done. I've also published the updated service so hopefully this problem goes away. Interested to know why there is a build issue number = 0 in the database.
