### ISSUE TITLE
Need to consolidate Supply and Demand functions in organs

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#1464]
The functions computing supply and demand for both DM and N need consolidating, each organ has different versions (mostly doing exactly the same by coded a bit differently), some use different variable with same meaning, and a few may have errors.
- The main issue with Supply is not making explicit the components that are zero, and lacking uniformity;
- For Demand, non-explicit zeros and non-uniformity are also there, but goes beyond with the use of variables that could lead to errors in the future (this is the case of using PotentialDMAllocation to compute StructuralNDemand for GenericOrgan. PotentialDMAllocation equal PotentialStructuralDMAllocation + PotentialMetabolicDMAllocation, with the second being zero - no this is not an error currently, but might cause issues in the future. we should be using simply PotentialStructuralDMAllocation).
The lack of uniformity is worse for the case of N; the use of local variables in different ways and the placing of brackets seem to have introduced errors comparing the logic between GenericOrgan, SimpleLeaf, and root. The boiled-down versions below (note brackets placements in the first and second and the doubling of StructuralDemand in the third):
NonStructuralDemand = Math.Max(0.0, MaximumNConc.Value * (Live.Wt + PotentialStructuralDMAllocation + PotentialMetabolicDMAllocation) - Live.N - StructuralDemand);
NonStructuralDemand = Math.Max(0.0, MaximumNConc.Value * (Live.Wt + PotentialStructuralDMAllocation + PotentialMetabolicDMAllocation) - Live.N) - StructuralDemand;
NonStructuralDemand = Math.Max(0.0, MaximumNConc.Value * (Live.Wt + PotentialStructuralDMAllocation + PotentialMetabolicDMAllocation) - Live.N - StructuralDemand - StructuralDemand)

**Comment by ric394** [comment]
This very old. Closing. If this is still an issue, please feel free to comment.
