### ISSUE TITLE
Develop a forage plantain model

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#1468]
Plantain (Plantago lanceolata) is an herbaceous perennial plant with a broad distribution in grasslands of the temperate world. It consists of a rosette of basal narrow leaves from which one or more flowering stalks sprout in summer.  Since the 1990's it has been selected and used as a forage crop in New Zealand and its use is increasing worldwide. Plantain can be grown in pure or mixed swards, growing in a wide range of soil types, and it does not requires high fertility.
Given increasing use of forage plantain in farming systems, there is demand for an APSIM model that is able to simulate its growth and regrowth after harvest.  It is one of the forage crops considered in a New Zealand study with the objective of reducing N losses from grazing systems by manipulating the mix of forages grown, thus influencing N and water usage as well as animal diet.

**Comment by zur003** [comment]
Maybe this should be called a "Plantago" model, to ensure it's not mistaken for a "Musa" model.

**Comment by rcichota** [comment]
It's a fair point. I do think the naming is quite unfortunate.  However, all literature and most common names in english only use plantain (also ribwort plantain or english plantain - always with plantain). Using 'plantago' would be he equivalent of calling the other plantain as 'musa'. Only a few people would know what they are...

**Comment by hol353** [comment]
Let's leave it as it is.
