### ISSUE TITLE
"Upgrade" in APSIM2017.02.01.1433 causes a crash

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1477]
Also happened in a version from about 23 January.  It quickly flicks up a window and then crashes the pop up and the APSIM instance.

**Comment by zur003** [comment]
Is this still occurring? Toowoomba had a power outage yesterday, so it might be a problem that shows up when the list of upgrades can't be downloaded...

**Comment by sno036** [comment]
It happened earlier this week on the 23 Jan version.  I got a new installation earlier today and tried it again so submitted the bug.  It does not get to any list of upgrades – crashes first I guess.  Is it a URL that I can try independently of the UI in case it is a firewall issue or something?
