### ISSUE TITLE
Filtering plots

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1480]
APSIM2017.02.01.1433.  There seems to be an issue with filtering data in this version.  When I clicked on the small help button beside the filter it took me to the help (which was useful) but then when I returned to the UI I had this strange cursor - sort of a right angle with a "+" in it.  It wouldn't let me effectively click anywhere - any click opened another instance of the help page.  Eventually I got it to go away and get a plot.

Does the filter work for Date?  I couldn't get the example in the help to work.

**Comment by zur003** [comment]
The cursor you describe sounds like the Gtk "drag" cursor - not sure where that would have come from.

The Help examples work, but only if things are set up correctly. Note the bit of help that says "All column names need to be in square brackets and must be in the table specified by 'Data Source'." I suspect that although you may have [Clock].Today as a reporting variable, you probably don't have '[Clock].Today.Year', but it must be there if you want the examples to work.

**Comment by hol430** [comment]
Closing this now, as these filters still seem to work, and the documentation does say that you need to report specific outputs in order for the filters to work.
