### ISSUE TITLE
ApsimX crashes if click anywhere while Report loads

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#1503]
When Report is clicked, it starts loading. If it's a large report (eg. for long-term simulations), loading takes quite some time. When clicking on any node while the Report has not finished loading, Apsim simply crashes without further notice.

**Comment by zur003** [comment]
Unfortunately, the Gtk# grid does take a long time to load, and I haven't found any way to improve that. However, the crash should be avoidable. Expect a pull request shortly.
