### ISSUE TITLE
Undo/Redo not working correctly

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#1508]
The undo and redo mechanism doesn't seem to be working correctly, especially in the Gtk# GUI. Click on these buttons long enough, and it can crash the application.

**Comment by wolfgang-boku** [comment]
I can confirm this.
E.g. when accidentally deleting/changing something in a Manager Script, "undo" should be able to undo this, but does not.

**Comment by zur003** [comment]
Also just noticed that changing the selected met file cannot be "undone".

**Comment by zur003** [comment]
The original problem was fixed, I think. I suspect there are still problems with undo/redo in some areas - I'm pretty sure it doesn't always do quite what I expect, but I haven't had it crash recently. It's probably best to close this issue, and create new ones when those problems reveal themselves.

**Comment by hol430** [comment]
Yes, it sometimes surprises me too. The ability to undo navigation between nodes is also something I find a bid odd. 

I've changed "working on" to "resolves" in my pull request, so this issue will be closed when that gets merged.
