### ISSUE TITLE
Simplify the doxygen interface

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#152]
Response the Dean's request during last meeting in Brisbane. I tried to simplify the doxygen interface, See here for an example: http://byzheng.github.io/ApsimX/Documentation/html/. Please let me know if you have any thoughts, then I can continue work on the interface or send a pull request.

**Comment by hol353** [comment]
This is a huge improvement. Send a pull request and I'll merge it in. I'll also update the www.apsim.info site.
