### ISSUE TITLE
Use array variables as factor levels

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1528]
I want to set up an experiment with DUL as factor levels (as shown below).  Currently the parser turns each array member into a factor level
![image](https://cloud.githubusercontent.com/assets/7295858/23390164/461dbc00-fdd1-11e6-8d48-e683ccd6f3c3.png)

**Comment by hol353** [comment]
I will implement this using the exact same syntax as your image above. Pull request running now...

**Comment by peter-devoil** [comment]
Is this syntax still working? 

<img width="1261" height="122" alt="Image" src="https://github.com/user-attachments/assets/0ee1dd46-e17d-48a3-b450-1617c9e84109" />

I'm getting an error now: ` The input string '{200' was not in a correct format.`

**Comment by ric394** [comment]
I believe you can just remove the brackets.
