### ISSUE TITLE
Simulation log not cleared between runs of model

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#1536]
The simulation log in Summary File does not clear between simulation runs such that Summary.Writes duplicate from individual simulations

**Comment by hol353** [comment]
I cannot reproduce this problem. Can you describe exactly how I could reproduce this behaviour?

**Comment by lie112** [comment]
I can’t run my code at present as we’re having git merge issues…. But this is the problem
In my code  I have

              [Link]
              ISummary Summary = null;

Then if needed I wrote to Summary such as

              Summary.WriteWarning(this, String.Format("No labour filter details provided for feeding activity ({0}). Assuming any labour type can be used", this.Name));


When I run the simulation the summary output has all the Report information boxes at the top and then in the summary log it will have this message if reported. It also has the Simulation finished successfully, and one other message. But the log is never cleared (or it must sometimes, but I don’t know when). But, rather the log is a repeat of the messages generated over the last series of simulations. This is all I am doing. Running the simulation again (right click the top of the tree and select Run Simulation) will append the new simulations messages to the end of the log. I don’t usually use F5 as I got out of the habit when it used to take two presses to run the simulation.

Regards,
Adam

**Comment by zur003** [comment]
I've been able to reproduce the problem, although I have trouble reproducing it consistently. For whatever reason, it appears the "Messages" table in the database isn't always being cleared when it should. Once you get into this mode, it seems to keep happening. It's oddly unpredictable, though. Will continue to examine this.

**Comment by zur003** [comment]
Ahh, now I see. Suppose you have an apsimx file with a single simulation, like Wheat.apsimx in Examples. If you run the model using the popup menu by right-clicking on "Wheat", all is well. However, if you run the model through right-clicking on "Simulations", you get the "messages are appended" behaviour. The inconsistency I was seeing was my own inconsistency in how I was running the simulation.
