### ISSUE TITLE
Creation of New SoilNutrient Model

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1540]
A new model will be created with the aim to replace the soilN model in the longer term.  It will provide a capacity to model C and N cycling, initially, with P and K cycling to be added later.  It will be developed using approaches developed for PMF.

**Comment by jbrider** [comment]
refer to #3522

**Comment by hut104** [comment]
@sarahcleary This now ready for review. I suggest Dr Valerie Snow (@sno036 ) as a potential reviewer.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please note this for discussion in next meeting.  If you have any comments or recommendations for reviewers, please provide these here prior to this meeting.

**Comment by sarahcleary** [comment]
@hut104 - as part of the review process, can you please provide a few sentences which will be used as part of the communications (news article/ResearchGate update) when ready for release?

**Comment by sarahcleary** [comment]
@hut104 - as per request above - can you please provide a few sentences which will be used as part of the communications (news article/ResearchGate update)?  Once I've received this, we can commence the review process. The review will (or likely to) be conducted by @sno036 and @Keith-Pembleton

**Comment by sarahcleary** [comment]
@hol353 - please note action from last RP meeting - to discuss 'news release" paragraph with @hut104

**Comment by hut104** [comment]
The Nutrient model replaces the Soil Nitrogen model within APSIM.  The model is developed using similar infrastructure to that used in the crop models so that soil nutrient pools and fluxes can be described using the APSIM user interface.  This should allow further development of the model by non-programmers and automation of soil nutrient model documentation.  
The initial implementation reproduces the science within the APSIM Soil Nitrogen model.  Enhancements, such as the incorporation of published approaches for BioChar, can be added in a relatively simple manner in later releases.
The model has also been designed to assist the addition of other soil nutrients to the same modelling framework.  For example, P cycling could be added to reproduce the SoilP model functionality with APSIM Classic.

**Comment by sarahcleary** [comment]
Thanks @hut104.  
@Keith-Pembleton and @sno036 - as discussed, this model is now ready for review.  As a trial, we are using the proposed process - solely via GitHub.  Please refer to the Reviewer's Instructions and commence review: http://www.apsim.info/Documentation/TechnicalandDevelopment/ReviewersInstructions.aspx
Please let me know if these Instructions need to be amended in anyway.

**Comment by sno036** [comment]
Hi @hut104  - I have done a small comparison with a simple simulation of a cutting trial with AgPasture comparing Nutrient and SoilNitrogen and there is some weirdness going on with differring production, differing responses to fertiliser and a bizarre spike in no3 and minn that crashes on 7 Jan. Possibly there is something wrong with the comparison I've set up so see the zipfile attached.


![image](https://user-images.githubusercontent.com/12176269/65658168-a4619000-e07a-11e9-9a3f-077aa19eec07.png)

![image](https://user-images.githubusercontent.com/12176269/65657784-07522780-e079-11e9-9940-c2aa86056c64.png)

![image](https://user-images.githubusercontent.com/12176269/65657791-0f11cc00-e079-11e9-851f-2acd556244d4.png)

[NutrientAgPastureV1.zip](https://github.com/APSIMInitiative/ApsimX/files/3655852/NutrientAgPastureV1.zip)

**Comment by hol353** [comment]
@hut104 Can you respond to this please?

**Comment by sarahcleary** [comment]
@hut104 - have you responded to this?

**Comment by hut104** [comment]
Sorry, I’ve been travelling and in workshops.  I will try to resolve these before the end of the year.

**Comment by sarahcleary** [comment]
@hut104 - any update?

**Comment by hut104** [comment]
No progress.  All efforts have been on other issues causing severe defects within the system unfortunately.

**Comment by sarahcleary** [comment]
@hut104 - any update?

**Comment by sarahcleary** [comment]
@hut104 - any update?

**Comment by hut104** [comment]
Hope to complete during code sprint in NZ early March

**Comment by hut104** [comment]
Hi @sno036 
This has been fixed.  It was related to PlantAvailableNO3 and PlantAvailableNH4.  


> Hi @hut104 - I have done a small comparison with a simple simulation of a cutting trial with AgPasture comparing Nutrient and SoilNitrogen and there is some weirdness going on with differring production, differing responses to fertiliser and a bizarre spike in no3 and minn that crashes on 7 Jan. Possibly there is something wrong with the comparison I've set up so see the zipfile attached.
> 
> ![image](https://user-images.githubusercontent.com/12176269/65658312-43868780-e07b-11e9-87a1-be77f6e46590.png)
> 
> ![image](https://user-images.githubusercontent.com/12176269/65658302-38335c00-e07b-11e9-8d30-73bdbc1e4630.png)
> 
> [NutrientAgPastureV1.zip](https://github.com/APSIMInitiative/ApsimX/files/3655852/NutrientAgPastureV1.zip)

**Comment by sarahcleary** [comment]
@sno036 and/or @hut104 - what is the next step?

**Comment by sarahcleary** [comment]
@sno036 - this is with you now?

**Comment by JJguri** [comment]
I am trying to test the ability of the Nutrient model to predict different N scenarios using the sugarcane NG example (200 kgN/year in a 2000 mm/year environment). 
I got N in biomass through two outputs ([Sugarcane].plant_n_tot and [Sugarcane].biomass_n), which is the difference between them? root_n?. 
Then I got NO3 leaching and Nmineral through  [Soil].SoilWater.LeachNO3 and [Nutrient].MineralN, respectively. Overall, NO3 was 40 times lower than N in biomass. 
I am trying to close the N cycle counting for N pools in runoff and losses to the atmosphere. For N2O or Natm I used [Nutrient].N2Oatm and [Nutrient].Natm but these pools are always equal to 0. I did not find a way to count for N pools in runoff yet. Do you know how can I make the model sensible to N losses to the atmosphere and runoff? @hut104  @sno036

**Comment by sarahcleary** [comment]
ACTION from last RP Meeting: @sno036 to rerun the test. If this is positive, then fully approved.  @sno036 - is this ready for approval/release?  
@hut104, @Keith-Pembleton - question above from @JJguri
