### ISSUE TITLE
Tillage does not work

### ISSUE THREAD

**Issue by fainges** [APSIMInitiative/ApsimX#1542]
Attempting to use tillage throws a null reference error. The model does not fill the TillageTypes list. Attempting to manually enter the list into the XML doesn't work either as the model just overwrites it with an empty list.

**Comment by hol353** [comment]
Neil and I have decided to create a Tillage class that looks after implement types and allow drag and drop tillage types in the GUI. This tillage class would then talk to surface organic matter and soil water classes.

In the mean time, use the Incorporate method of SurfaceOrganicMatter model.

**Comment by hol353** [comment]
To do tillage, use the Incorporate method or SurfaceOrganicMatter model. Closing this very old issue.
