### ISSUE TITLE
Should be able to view summary files from any of a set of simulations

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#1574]
After running a set of simulations, like WheatValidation, it should be possible to get a Summary of any individual run.

**Comment by hol353** [comment]
If you go to 'Summary' in the base simulation under an Experiment, you should get a drop down list that allows you to view the summary for a given simulation.

**Comment by zur003** [comment]
Putting a Summary under the base simulation of an Experiment offers the drop-down list, but selecting from the list seems to have no effect. (That appears to be a problem in the Gtk GUI only - I will look into it.)

With the WheatValidation, there are multiple experiments. It would be nice if a Summary under the top Simulations object could let you choose _any_ simulation from _any_ experiment. Or for that matter, if a Summary under the SE Queensland folder would allow selection of summaries of any of the simulations under it. We allow Summary object to be placed in these locations, but currently they do nothing useful.
