### ISSUE TITLE
Regression Stats on graphs are missing

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1577]
The regression stats on graphs give stats for NSE, ME and MAE but the second line of stats are missing.

**Comment by zur003** [comment]
I'm not seeing the problem. However, I have noticed that putting the legend in the top left will obscure much of the regression information. Can you provide an example screenshot?

**Comment by hut104** [comment]
![image](https://cloud.githubusercontent.com/assets/11881178/24175724/8375dd80-0ee3-11e7-9296-bc1d596d405d.png)
Note that RSR and RMSD are missing

**Comment by zur003** [comment]
I see it differently. Although the plots look the same, our stats look different (e.g., you have n=345, I have n=195). And I have values for RSR and RMSD

![harvestbiomass](https://cloud.githubusercontent.com/assets/11879340/24176181/906135ac-0eee-11e7-92fe-4f5daa84d306.png)
