### ISSUE TITLE
New Chickpea model

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#158]
The APSIM Chickpea model has been developed from the original APSIM Classic Chickpea model described by Robertson et al (2002) using the Plant Modelling Framework of Brown et al (2014).

Functionally, it remains a HI model that partitions N to grain (via target N concentration) and root nodules, simulating N fixation. Efforts to model phenology intend to represent field observable characteristics such as buds, that are in turn precursors to flowers.

The work is mostly being undertaken by Allan Peake and should be presented for review in early 2021.

**Comment by hut104** [comment]
Happy for this, but the work is mostly being undertaken by Allan Peake, who may or may not be on GitHub.

**Comment by sarahcleary** [comment]
@hut104 - just following up the concept note.  For background, please refer to https://github.com/APSIMInitiative/ReferencePanel/issues/57#issue-595681585
