### ISSUE TITLE
Better weather file reading

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#16]
1) Can we allow tabs in met files?  People keep making that mistake.
2) Can we just allow xlsx met files?  Save an extra step

**Comment by zur003** [comment]
1) Tabs appear to be supported. Is there more that needs to be done?
2) What assumptions could be made about the layout of the .xlsx (or .xls?) file? Will there be a "header" area? Presumably there would be, or a different mechanism would be needed for specifying things like latitude.

**Comment by hol353** [comment]
1) Neil H. reported that in a training workshop tabs were causing a problem. Perhaps it was something else.
2) Yes, there would be a header section. Perhaps keyword = value, all in one cell? For the data, perhaps column headings with bracketed units, all in one cell rather than having a units row. That way users can easily filter data without having to worry about the units row getting in the way.
