### ISSUE TITLE
Icons in list

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#1601]
It would be nice to have icons for the models and functions show up in the list on the right pane when choosing a model or function.

**Comment by zur003** [comment]
Also, we now have a LOT of functions, and the Add Model view is displaying all of them, making the basic models hard to find. If no one objects, I will remove functions from the Add Model presenter (since they have their own Add Function presenter).

**Comment by hol353** [comment]
Happy to move the functions out of Add Model.

**Comment by hol353** [comment]
Yeah probably a good idea although I think we can get rid of the standard toolbox. No one uses it. I guess we'll still be keeping a management toolbox though.
