### ISSUE TITLE
Develop a multi purpose HTML view presenter to allow components to show some description

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#1618]
A 'generic' HTML view presenter would be useful for components that need to display usage information or summarised doco about themselves. They would just need to proved a formatted HTML string from a property.

**Comment by lie112** [comment]
This new addition has mucked up all CLEM presenters by adding the description at top (see image 1)

There are a few options available here

- I can write code to ignore this for all CLEM models
- I could apply the CLEM wrapper presenter (model, description and version) to every model in APSIM. If no HelpUri attribute has been supplied the help link will not be displayed. Likewise the version attribute. The part from summary tab down is actually the next presenter and would be replaced with the required presenter (see image 2)

![image](https://user-images.githubusercontent.com/19215637/70113115-0ad2e200-16ac-11ea-9c6d-f341b736caa2.png)
Image 1

![image](https://user-images.githubusercontent.com/19215637/70113286-c1cf5d80-16ac-11ea-89c8-a565f3997ac8.png)
Image 2

**Comment by hol430** [comment]
Does the clem description component use a html view or a label? Or something else entirely?

**Comment by lie112** [comment]
The Model wrapper presenter uses labels that scale or disappear if not needed.
It takes the top strip of the right explorer view and places the defined presenter and view (in model attributes) in the lower pane, thus wrapping the expected presenter and view
The link to help (if HelpUri provided) is a button if needed.
There are three labels

1. The model type (namespace). At present this is only From Models.CLEM downwards
2. The description in the discription attribute. We could add the summary if no description. May need to limit size with "..." if truncated
3. Version number. This is the latest component version number (also an attribute)

A help button appears if a Help Uri has also been provided as an attribute. Therefore in CLEM there is a direct link form every component to the online help system

At present I have just wrapped the ShowDescriptionInRightHandPanel in an if statement that only fires if not a CLEM component to maintain the current functionality for everyone else (Pulled in next CLEM request)

**Comment by hol430** [comment]
@lie112 what is the status on this one? From what I can see, the clem views are no longer showing this extra description panel.

**Comment by lie112** [comment]
It's fixed. I recall I added a workaround, but must have missed resolving this issue.
