### ISSUE TITLE
Issues with PAW - GtK version

### ISSUE THREAD

**Issue by ekhaembah** [APSIMInitiative/ApsimX#1635]
Soil water showing a value of zero for PAW across layers. Please see attachment.
![apsimx_water](https://cloud.githubusercontent.com/assets/12144731/24778243/ad237736-1b7d-11e7-8491-bd6d3fc0848b.PNG)

**Comment by HamishBrownPFR** [comment]
That could be a bug in the mapping that I have been working on recently, I will take a look at that first.

**Comment by hol353** [comment]
It could also be that XF = 0 for all layers. I think this will give a zero PAWC as well. Unfortunately, I can't see XF in the screenshot.

**Comment by hol353** [comment]
Closing this as it doesn't seem to be a problem. If you see this again, please reopen.
