### ISSUE TITLE
Error when using Plant and Plant15 models in the same simulation

### ISSUE THREAD

**Issue by fai04d** [APSIMInitiative/ApsimX#1641]
In GerminatingPhase.cs there are these lines:

```c#
            if (Plant != null)
                SowDepth = Plant.SowingData.Depth;  
            if (Plant15 != null)
                SowDepth = Plant15.SowingData.Depth;
```

Since both models are in there one ends up erroring as the model that is not currently being sown has a null SowingData structure. I tried to get around this by changing it an if/else which fixes it, but then causes further errors down the line.

**Comment by hol353** [comment]
Plant15 has now been removed from APSIM Next Gen.
