### ISSUE TITLE
New GUI cannot run a single simulation from the experiment node

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1649]
In the old APSIMx GUI one could right click on an individual simulation listed in Experiment View and choose run and it would only run that simulation.  I think it could also support multiple selection.
The control should also be a multi-select list box as well.

**Comment by zur003** [comment]
I've submitted a fix (#1703) for the running of a single simulation, but am leaving this open until multiple selection is implemented.

**Comment by hol353** [comment]
Hi Eric

Can you stick a 'Do not merge' label on the pull request. I'm trialing using GitHub labels for this sort of thing.

Dean

On 6/06/2017 10:21:14 AM, Eric Zurcher <notifications@github.com> wrote:

I've submitted a fix (#1703<https://github.com/APSIMInitiative/ApsimX/pull/1703>) for the running of a single simulation, but am leaving this open until multiple selection is implemented.
