### ISSUE TITLE
Add Option to "Downgrade"

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#1652]
To maintain compatibility it is sometimes necessary to use and older version. A "downgrade" button, or just the option to select older versions in the upgrade-menu, would be useful.

Edit: I just found that the Debian version shows older versions in the upgrade menu, although the text still says "newer versions are listed below". I haven't tried if such a downgrade works.

**Comment by zur003** [comment]
If you currently have the most recent version installed, "downgrading" does not work. An attempt to downgrade to an earlier version gives an error message of "Index was outside the bounds of the array". Attempting to "View detail" of an earlier version makes the program crash.
