### ISSUE TITLE
Case different between Fertiliser and Irrigation

### ISSUE THREAD

**Issue by fai04d** [APSIMInitiative/ApsimX#1653]
When applying irrigation via the operations manager, the apply command is lower-case 'apply'. When applying fertiliser, the command is upper-case 'Apply'. Using the wrong case will generate an error. This can be very confusing as both model will generally be used together in operations. Suggest changing them to both use the same case.

**Comment by zur003** [comment]
Can you provide an example? As far as I can see, both should be using "Apply".

**Comment by hol353** [comment]
@fai04d Eric is right. Both should be uppercase. Can you close this issue if it isn't a problem anymore.
