### ISSUE TITLE
Should simulations be saved when the user selects 'run'?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1657]
This would be consistent with classic and might reduce frustration while the interface is becoming more stable.

**Comment by fai04d** [comment]
Simulations do save when they are run. Are you experiencing different behaviour?

**Comment by sno036** [comment]
Mostly it saves before running but often when the simulation crashes the unfortunate user finds that the save didn’t happen. ☹

**Comment by wolfgang-boku** [comment]
I have experienced the same problem on Ubuntu.

**Comment by hol430** [comment]
@sno036 @wolfgang-boku Are you still experiencing this behaviour? I have not been able to reproduce it.

I don't know what the code looked like when you reported this issue, but as it is now, nothing ~~will~~ should be run if the file fails to save.

**Comment by wolfgang-boku** [comment]
Sorry, I can't comment on that. Haven't been working with recent ApsimX versions.

**Comment by hol430** [comment]
Fair enough. I will close this issue, but if anyone does still experience this behaviour, just re-open this issue (or create a new one).
