### ISSUE TITLE
Setting yes/no values in Factor components

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1658]
The attached simulation crashes (screen grab attached) and it very much appears to be because of the lines in the Factors component:
          [AutomaticFertiliser].Script.AllowFertiliser = yes
          [AutomaticIrrigation].Script.allowIrrigation = yes
What I am trying to do is to use Experiment | Factors | Factor to turn irrigation and fertiliser on and off.  The lines in the manager scripts controlling these are:
		[Description("Turn fertiliser applications on? ")] 		public yesnoType AllowFertiliser { get; set; }
		[Description("Turn irrigation on?")] 		public answerType allowIrrigation { get; set; }
For the values to set I have tried plain old yes, 'yes' and "yes" but they all cause a crash.

![capture](https://cloud.githubusercontent.com/assets/12176269/25834557/df77d854-34cc-11e7-81f6-57af5c02bc9a.JPG)

[VariousCompeting2.zip](https://github.com/APSIMInitiative/ApsimX/files/985515/VariousCompeting2.zip)

**Comment by zur003** [comment]
I've submitted a fix that will allow enumerated types to be handled correctly. However, in this example, I should point out that it would have been possible to use the standard Boolean type (and assign true or false) rather than defining a new yesnoType.
