### ISSUE TITLE
GtK interface bugs. 

### ISSUE THREAD

**Issue by ekhaembah** [APSIMInitiative/ApsimX#1723]
1. Unable to change units in initial soil N model
2. Cannot copy and paste from spread sheet to grid cells

**Comment by zur003** [comment]
You should already be able to change units in the SoilN module. Right-click on a column in the body of the table (not the header), and you should get a popup menu allowing you to, among other things, changes units when that's appropriate (e.g., ppm vs kg/ha).

**Comment by hol353** [comment]
@zur003 r.e. copy and paste, people often want to copy one or more column of numbers from EXCEL into the grid and vise versa. Can we enable this as well rather than have the grid select the entire row?

**Comment by zur003** [comment]
Not easily, at least not for copying. The control that we're using for grids in the Gtk version doesn't allow selection of columns; only rows. Pasting should be OK, though. If you paste a 3 x 4 block of cells, it should paste as expected, starting from the current cell and working to the right and down.

**Comment by hol430** [comment]
Both of the issues initially reported in this thread are resolved. Do we still want the ability to copy a subset of columns from a GridView into, say, Excel?

**Comment by hol353** [comment]
Go ahead and close the issue. We can't copy a subset of cells. GTK grid control doesn't work that way.
