### ISSUE TITLE
Detailed descriptions can be too long for the user interface

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#1726]
The "Description" attribute of properties is sometimes overly long when used in the context of the user interface. For example, SWCON currently has the description: "Fractional amount of water above DUL that can drain under gravity per day (SWCON) (/d)". That's all useful information, but it's rather long when used as a column header in a table. Further, in the SoilWater input views, the units attribute is also added automatically, so the header ends up with "(/d) (/d)" at the end.

I'd welcome discussion about the best way to address these problems. As a starter, I'd suggest that units of measurement not be included in the Description attribute, but be provided only in the Units attribute; having it in both is just redundant. I think it might also be useful to have a "ShortDescription" (or "Label") attribute, and a "LongDescription" attribute, The short version could be used in the column headers of the GUI, and perhaps the long version could be displayed when the user requests to see it.  For example, the header might just read "SWCON", but the user would be able to see the longer, detailed description by some mechanism (perhaps by mouse over, or perhaps from a popup-menu item)

Any comments?

**Comment by her123** [comment]
Sounds like a good plan to me.

**Comment by hol353** [comment]
We could use the <summary> elements instead of a [Description] tag. These can be read from Models.xml in the bin directory. The [Description] tag is also used to detect which properties should be displayed in the GUI. Perhaps we create a new tag to replace Description and call it [ShowInUserInterface] or something like that. 

This resolves the same text being in [Description] and in <summary> - duplicate text. I agree units should be in the [Units] tag.

**Comment by hol353** [comment]
Hmmm. Looks like my comment has the summary XML elements stripped by GitHub.

**Comment by hol430** [comment]
We now have a caption attribute, a description attribute, and a `<summary />` xml documentation tag. One of these needs to be used for the variable name in the property presenter, and another of these needs to be used as a tooltip. I've implemented the tooltip on my branch - it shows up when you mouseover a cell in a property presenter or profile grid.

The question is, do we want to use `<summary />` tag or `[Description]` attribute for the tooltip? In most classes throughout the codebase, none of the properties have a `[Caption]` attribute, so we would be better off using `[Description]` for the variable name and `<summary />` for the tooltip. However, if we stick to using `[Caption]` for the variable name and `[Description]` for the tooltip, we wouldn't need to read the Models.xml file. Not that it's particularly slow. I'm not sure which way to go with this one.

**Comment by jbrider** [comment]
Could we call it [Tooltip] as that would be clear what it's for?
I'll bet if asked what's the difference between [Caption] and [Description]
the answer won't be one is for variable names and one is for tooltips.

**Comment by hol430** [comment]
Yeah good thinking - and that will be an easy enough change to make.

**Comment by lie112** [comment]
Sounds good. I don't think we should use <Summary> as it can often have multiple lines of details. I have some [Descriptions] that I always thought were too long for the variable name column, but are perfect for a tooltip. I will ensure the units are set properly in CLEM to avoid the duplication problem. A [Label] or [ShortName] would be easier to understand than [Caption]. The system should revert back to using description as it does now if no value is provided for the short version to maintain backward compatibility.

My other thought was to simply use the property name as there has usually be thought put into keeping it short but explaining the property. If a [Description] is available it then makes a valuable tooltip to describe the property. I can see the [Caption] will often be set to something like the property name with spaces added and no camel case.

**Comment by hol430** [comment]
Yeah in my mind the main advantage of using a [Label] attribute would be to allow for spaces in the variable name shown in the gui. Good thoughts about [Description] attribute - I think I'll use that for the tooltip and that way the `<summary>` tag can be more developer-oriented information. Do we want to expose both in the autodocs?

**Comment by hol353** [comment]
Ok lets go with:

- [Tooltip] - This is only used by the GUI when you mouse over something. Not used by AutoDoc.
- [Description] - This isn't changed - It is only used by the GUI PropertyPresenter to display the variable name in the first column of the grid view. Not used by AutoDoc.
- The summary tag is only used by the AutoDoc and Intellisense.

**Comment by rcichota** [comment]
One extra suggestion, I've seen somewhere in the internet (probably part of Microsoft coding standards), Use the 'summary' tag to give a good but concise description of your property or method, Use the 'remarks' tag to add more details, like assumptions, references, etc...

**Comment by hol430** [comment]
The remarks section is currently ignored by the autodocs - should we change this?

**Comment by hol353** [comment]
Like @rcichota says above the summary tags should be concise. I think the auto-docs should use the remarks tag instead of the summary tag when a remarks tag exists. We should then manually go and migrate the long summary tags to remarks tags.

**Comment by rcichota** [comment]
Should we use one instead of the other or use both? I always try to add a concise description in 'summary', then add the details using 'remarks'. Standard Microsoft is that only 'summary' is used in intellisense, but both in autodoc...
