### ISSUE TITLE
Need to fix locale issues so that .apsimx file can be opened and run under different locales

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#1755]

**Comment by hol430** [comment]
@hol353 @zur003 What is our policy regarding culture/locale? I'm currently doing some work on the object/string conversion utilities and am not sure what to aim for.

Do we want *everything* to use the invariant culture? (This would mean that all dates in the gui would appear as mm/dd/yyyy.) Do we want to use current culture in the gui and invariant culture when (de)serializing? Or some other strategy?

**Comment by hol353** [comment]
Current culture in the GUI. Dates serialised as yyyy-mm-dd. Is that invariant culture?

**Comment by hol430** [comment]
No, invariant culture is mm/dd/yyyyThh:mm:ss (it includes the time component as well). I guess it doesn't matter terribly as long as it's consistent. I guess we need to be careful if we change how it's serialized in case it affects people who use scripts to create apsimx files.

**Comment by zur003** [comment]
I agree with Dean about what we have as a goal: use the current culture in the GUI, but standardize everything in the back end as "invariant culture", modified to use Australian date format. Getting that to actually work in practice will be a challenge.

**Comment by hol430** [comment]
Apsim actually appears to be working quite well for me now on my German windows (or rather, it's no worse than it is on windows in an Australian locale). Unless you guys are aware of any outstanding locale issues, I would be happy to close this and open new issues for any specific locale-related issues we encounter.

**Comment by hol353** [comment]
So on German windows are dates in the GUI (e.g. propertypresenter and operations) in German format?

**Comment by hol430** [comment]
Yep, and numbers use commas as the decimal separator and period as the thousands separator.

**Comment by hol353** [comment]
Sounds good. Closing this issue.
