### ISSUE TITLE
Is filtering on Date working in graphs?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1767]
Is the filtering on date (e.g. [Clock.Today] = #1995-12-31# in the documentation) working?  I tried many nuances on it and wasn't able to get it to work.  Eventually got [Clock.Today.Month] IN (12, 1) to do what I needed but date would have been nice.  Or perhaps I was doing something wrong.

**Comment by hol353** [comment]
I've updated the doco - it was wrong. Try:

[Clock.Today]>='1996-01-01'
