### ISSUE TITLE
GTK UI - Drag copies a node but does not add it to the tree

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1777]
If you drag an experiment in the tree, it is supposed to make a copy at the drop point.  The copy is not drawn in the tree.  However, if you drag, then save and reopen you find that the copy is there.  It must be being copied but not drawn in the tree.

**Comment by zur003** [comment]
Works OK for me. Anyone else seeing this problem?

**Comment by wolfgang-boku** [comment]
see also https://github.com/APSIMInitiative/ApsimX/issues/822
