### ISSUE TITLE
GTK UI - clicking twice on icon in the tree opens text for editing

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1778]
Clicking on the icon should not open the text for editing.  In standard windows clicking on the icon does not open the text for editing.
If you select something to drag it often opens the text for editing and you can drag something that is also highlighted for editing at the same time.  This should never happen.

**Comment by zur003** [comment]
This should now be fixed. The fix was added with #1784. Please close this issue if you're happy with the new behaviour.

**Comment by zur003** [comment]
Resolves #1778

Actually, I lie. 1778 has already been resolved, but associating this pull request with it lets me close this issue and avoid opening a second (trivial) one.
