### ISSUE TITLE
Layer Structure component doesn't seem to do anthing

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1785]
I put a layer structure component into a simulation and it didn't seem to do anything.
The numbers appeared in the simulation  UI but the summary file did not report initialisation using that structure.

**Comment by hol430** [comment]
What is a layer structure component? Is this still an issue?

**Comment by hol353** [comment]
A LayerStructure component should be dropped on a soil. When the simulation is run, it then modifies the soil layer structure to match the user entered layer structure.

**Comment by hol430** [comment]
Closing this. LayerStructure is working as far as I can tell.

![image](https://user-images.githubusercontent.com/36427516/97128351-d5355c80-1787-11eb-8472-6ad2d3cca86a.png)
