### ISSUE TITLE
autodocumentation not picking up all items in validation

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#1796]
Typically each plant model has a validation folder containing simulations, experiments, and/or folders with their own simulations and experiments.  each of these used to be picked up as an item when generating the auto-documentation, but now only folders are being picked up.  This can make the documentation quite confusing.  I had to change the structure of the validation folder for chicory (adding several folders) so that the auto-documentation was readable.

**Comment by hol353** [comment]
This should now be fixed in my latest merged pull request. You can now control what gets included in the PDF.
