### ISSUE TITLE
Autodocumentation - merging lines from hard-coded documentation

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#1801]
When the auto-documentation uses hard-coded information (declared using <summary>) and there are multiple lines, these are merged without a space (any existing is trimmed out). So, when the text is multi-line, a few words are being merged or a punctuation mark is followed by a word without spaces.
The PMF organs (GenericOrgan.cs, etc) are examples of this issue

**Comment by hol353** [comment]
Same as #1948
