### ISSUE TITLE
PMF wheat returning NaN when ReadyForHarvesting

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#1806]
A few simulations in WheatValidation.apsimx perform their harvest when the phenological phase becomes ReadyForHarvesting, these simulations are sending NaN values to SurfaceOrganicMatter and from there is goes to SoilNitrogen (many simulations use Ripening, which causes no issues).  The return of NaN doesn't cause a fatal error but makes the remaining of the simulation useless (as this occurs on harvest it is close to the end of the simulation so it went unseen).  
I noticed this when I added a check in SoilNitrogen, so it would only compute decomposition if there are residues (so I was testing for residues amount > 0). This made SoilNitrogen insensitive to NaN and it returned zeroes instead of continuing a chain of NaN, this resulted in the WheatValidation tests to fail. All simulations that use ReadyForHarvesting have this issue (I was testing LincolnCPTOtane and SDtrial). I did not go too deep to identify the cause of this, but it seems some biomass is being zeroed at that phase and this leads to a division by zero (which in .Net is valid, retuning infinity). The flow on then results in NaN.  
I have commented out the test in SoilNitrogen so that it would pass all the tests, but I would like to reinstate it after this is sorted out in Wheat/PMF.
I guess we need to be careful when coding and maybe we need to add some checks to try to pick this things up.  Because both infinity and NaN are valid numbers in .net, the calculations may go on without crashing and not being noticed. This may result in unexpected/unwanted results...
@hol353 @HamishBrownPFR @hut104

**Comment by hol430** [comment]
@rcichota do you remember where you added your check to SoilNitrogen? I'll have a look into this if it's still happening, I just need a starting point where I can see a nan somewhere.

**Comment by ric394** [comment]
This very old. Closing. If this is still an issue, please feel free to comment.
