### ISSUE TITLE
Fix bugs in PMF phenology

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#181]
1. Phenology class was not adding the fraction of progress through a phase to the Phenology.Stage variable on the first day inside each phase.  Needs minor change to fix this.  It will affect model results as a number of things are functions of Phenology.Stage however the effect should be minor as this value will only change on days when phases change

2. Phenology class would only allow progress through one stage per day. Have changed so if short phases take less than the days Tt to complete the model will pass through unlimited phases each day.  This will probably not affect any current PMF models but was causing problems in MCSP (prototype)

**Comment by HamishBrownPFR** [comment]
There is some considerable collateral damage as a result of this bug in the wheat model.  

Fix 1 above means we now never have a zadok value of 90 because stage doesn't pause at integer values for the day they occur.

Fix 2 above means there is now a logic test in leaf expansion which is never true (see screen shot below) because the emergence_to_end_juvenile phase is 1oCd long so now it passes from emergence to end of juvenile on the same day. 
![image](https://cloud.githubusercontent.com/assets/7295858/8441921/9b2e047a-1fcf-11e5-8303-f191161da247.png)

Both of these are easy enough to fix but there are some fundamentals we need to agree on before I proceed or halt any further changes.  

2. Do we want the Stage variable to return integer values on the days it passes from one phase to the next or do we want it to include the progress through the phase that occurs on that day to be added into the Stage number reported at the end of that day. 

1.  Do we want to constrain the model so that it will only pass through a maximum of 1 phenological stage per day.  This is how the code currently works and it means each stage is stopped on for at least one day which makes logical tests that do things on particular stages robust.  However, this causes problems (which is why I am wanting to make this fix) because on situations where short phases occur the thermal time accumulations get screwed up.  For example in the current implementation of the model if the wheat emerges on a particular day and there is 15 oCd left over to pass the next phase, this is all passed to the next phase which only needs 1oCd, so the short phases are accumulating more  thermal time than they should.  So when you sum thermal time accumulated over a number of phases it exceeds the sum of the thermal time targets for these phases.  This causes problems in the implementation of functions that want to use thermal time accumulation relative to targets.

**Comment by HamishBrownPFR** [comment]
Problem 1 can be fixed in the wheat model by matching on CurrentStageName = Maturity which will return the same day as Zadok stage = 90 was

Problem 2 can be fixed by changing the 1oCd phases to accumulated days rather than thermal time so they always pop up for a day as they currently do.  To make the OnDayOf test robust we will need to alter it so it returns true for all stages that were passed in a day not just the stage that the model settled on at the end of the day.

**Comment by hut104** [comment]
I'm happy with any of the suggestions.
The endjuv phase thing in wheat is only there because of history.  In the old old old wheat model you had to have a juvenile phase - but CERES wheat didn't.  So we had to make it as small as possible.  So I'm even happy for us to remove the phase.
I'm also happy to have things reference either Zadok 92 (I think that's harvest ripe) or use CurrentStageName as suggested.  
There are only a small number of users of the wheat model in APSIM2015 and so I think any collatoral damage would be minor.  I'm happy for us to make things more elegant and accurate now.  Best to remove baggage (like the juvenile phase) now rather than later.

**Comment by HamishBrownPFR** [comment]
The only problem with removing the juvenile phase is it will move every thing forward by a day.  I will do this and see what sort of effect it has on the validation
