### ISSUE TITLE
Grape Vine Model

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1822]
Perennial fruit crops are less adaptable to climate than annual crops 
because they are kept for many
years after establishment leaving fewer opportunities to alter genetics 
and management. However, no
formal perennial fruit model has been developed in APSIM to help make 
strategic decisions when
establishing and managing these. To this end, we used grapevine Vitis 
Vinifera L. as a model plant to
develop a perennial fruit crop model in APSIM next generation.

A series of developments was undertaken to adapt the APSIM source code 
to simulate perennial woody
plants by Junqi Zhu, @HamishBrownPFR, @hut104 and @hol353. The model was 
built
to simulate the phenology, (strip) light interception, canopy 
development, carbon allocation, carbon
storage and remobilisation, and yield formation of grapevine as a model 
perennial crop. It
includes the following features:

1. A vine and inter-row strip configuration to represent the vineyard 
setup. Currently inter-row
planting was represented by a generic plant model ‘Slurp’. The ‘Slurp’ 
model simply takes up
water and nitrogen, but does not predict crop growth or yields. We 
forced its leaf area index to
follow a sensible growth pattern under the vineyard management in 
Marlborough New Zealand
(NZ) with periodic mowing events.

2. An adapted strip light interception model triggered automatically by 
the strip setup.

3. A new carbon allocation method to allocate the carbohydrate 
simultaneously based on sink
strength as well as sink priority.

4. A yield module that uses the pre- and post-flowering weather 
conditions in previous season along
with current season weather and carbon status to determine bunch number 
per shoot, berry
number per bunch and potential berry size.

5. An adapted phenology model that starts from endodormancy of the bud 
instead of emergence
and resets to endodormancy by a management method (pruning) in winter to 
capture the
perennial behaviour.

6. Flexibility in adapting to a different training system by controlling 
the bud number per vine,
canopy height, canopy width and depth as inputs.

**Comment by sarahcleary** [comment]
@HamishBrownPFR - just following up the concept note.  For background, please refer to https://github.com/APSIMInitiative/ReferencePanel/issues/57#issue-595681585

**Comment by junqi108** [comment]
@APSIMInitiative/reference-panel 
With a final push this week we (@HamishBrownPFR  @junqi108 @ed2014 @rcichota) have got the Grape Vine model to a state that we think is suitable for release. The bulk of the work for this has been logged against #1822 and we will close that issue and move the validation set from prototypes into UnderReview.
The Grape vine model is built in PMF and some new functionality was introduced to facilitate its completion, most notably a alternative arbitration approach that partitions structural and non-structural fractions simultaneously. It contains phenology that goes from dormancy through vegetative and reproductive growth and back to dormancy each year. Its predictions of Berry yield integrate climate and management factors that accumulate effects over a 18 month period prior to each harvest. As well as predicting the usual yield, water and N uptake, it also has functions to predict berry composition that influence wine quality.
All of the validation experiments are set up as multi zone strip row simulations with a row growing grapevines and an alley growing grass simulated with SLURP.
The validation currently only covers New Zealand Data sets and the parameterization of cultivars only covers cultivars relevant to NZ. There are more important grape growing regions around the world and ultimately the model should include validation from Australia, Americas and Europe. However, we the model itself is sufficiently complete to justify Release which will help to facilitate further testing and improvement.

**Comment by sarahcleary** [comment]
@HamishBrownPFR - any suggestion for reviewers?

**Comment by peter-devoil** [comment]
[Potential reviewer](https://researchers.uq.edu.au/researcher/10599).

**Comment by yashvirchauhan** [comment]
How about Neil White or Some one in the south Victor Sadras? I guess it is more about reviewing if science is correct?

**Comment by hol353** [comment]
It ideally has to be someone who has used APSIM Next Gen and who has graph physiology knowledge.

**Comment by Keith-Pembleton** [comment]
I think we will struggle to get someone with both grape and ASPIM next gen experience.  Can we split it up and have someone review it from software perspective and then another person reviewing it from a vine physiology perspective?

**Comment by yashvirchauhan** [comment]
Can we have a system of (provisional) release (eg Grape-P or Grape-D) as they do for genome and confirm later when more people have found that draft is accurate enough or missing components have been added or revised and the model's robustness has been tested in wider environments?  Given there would be fewer people who would have required knowledge of APSIM NextG it may be an option to consider in the interim. A post scrip lettering would suggest simulations need to be accepted with caution. Just a thought.

**Comment by hol353** [comment]
> an we split it up and have someone review it from software perspective and then another person reviewing it from a vine physiology perspective?

I don't know how you can review the physiology of a model without looking at the model design/processes and running it to make sure it does sensible things. Both of these things require you to run APSIM Next Gen.

**Comment by sarahcleary** [comment]
@yashvirchauhan - I understand the desire to be able to provide a model for use, especially with the difficulty with finding suitable reviewers, but my feeling is if we do this, we will never get around to reviewing models formally.  We have enough of an issue with developers having capacity (as in the project which the model has been developed has finished) once the reviewers return with suggestions, if we postpone this process, a model may never be accepted.  Assuming I've understood your suggestion correctly.

**Comment by HamishBrownPFR** [comment]
No model is ever finished but we need to make a decision at some arbitrary point that it is working well enough to be used by others.  This is release.  No model will every work perfectly in all situations so it doesn't matter how much effort has gone into building and testing a model, users should always be cautious and do some testing in the specific situations they wish to use the model.  So it would be difficult to determine when a model moves from provisional release to full release.  We provide a validation set with a released model so users can assess how much testing has already been done and determine if more is needed for their situation.
I think we need to stick with the current release system where the requirements are that the model represents current science well, integrates properly with the APSIM system, has some validation and some documentation.  This makes the model available to new users which can facilitate additional improvements and makes clear where the model is at currently.  The continuous release system means it is easy to make incremental improvements to released models at any time after release.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - is it possible to make a decision via GitHub on reviewers (or ones I can approach to see if they are willing/have capacity)?  I note we have our Strategy Session next week - and at this stage, we are looking at only a 3 hour session, so should be able to discuss this at the beginning/end of the meeting.

**Comment by hut104** [comment]
[grapevine (1).pdf](https://github.com/APSIMInitiative/ApsimX/files/6418570/grapevine.1.pdf)
Comments in the attached file

**Comment by junqi108** [comment]
> [grapevine (1).pdf](https://github.com/APSIMInitiative/ApsimX/files/6418570/grapevine.1.pdf)
> Comments in the attached file

thanks Neil

**Comment by junqi108** [comment]
@APSIMInitiative/reference-panel 
## Work required for Model to be accepted into Release
** Preamble require a bit more information with cautions/caveats for new users
** Tidy up documentation based on Neil's comments
** Run the entire model for a 20 year period to ensure stability 
** Undertake Sensibility tests for water stress responses and any other factors without validation data
** Check integration works by simulating sheep in the vineyard.  Ensure the sheep each leaves not roots.  
** Put irrigation into simulations

**Comment by sarahcleary** [comment]
[Introduction of APSIM grapevine model.pdf](https://github.com/APSIMInitiative/ApsimX/files/6424818/Introduction.of.APSIM.grapevine.model.pdf)

**Comment by sno036** [comment]
Thanks @junqi108. I hope you found the review process helpful (rather than inquisitorial!). Thanks for all the effort that you put into the presentation!

Just to clarify (this may be what you intended of course) ..

** Put irrigation into simulations - means turn on the possibility of water stress but add irrigation to the simulations that should have irrigation (so that the lack of water stress is for the right reason). Hopefully this will not need a whole recalibration but if so better now than later on!

** Undertake Sensibility tests for water stress responses and any other factors without validation data - I think this will be important for this model as it is such a complex production system alongside this being such a novel/new model (its not just another row crop!). It would be good here to 'throw the book' at the model with sensibility tests here. Lots of factors and in relatively small steps/levels where possible so that patterns with the factor can be seen. There may be insensible patterns that you find from this. If they occur and they prompt a fix for something overlooked then great. If there is an odd response that can't be explained, for me, I don't think this would inhibit the model going into release but would be a caution added to the preamble that the pattern was counter intuitive, may indicate a flaw but there is no data and/or resources with which to improve the model at this time so use with caution.

**Comment by Keith-Pembleton** [comment]
@junqi108 also need to add a test simulation proving that the crop can be eaten by stock.
