### ISSUE TITLE
Console output for stats tests on Jenkins not reporting properly

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#183]
The stats test console output from Jenkins gives NA rather that True or False so it is not possible to work out which tests have failed.

From Jenkins
![image](https://cloud.githubusercontent.com/assets/7295858/8399300/41768798-1e5f-11e5-8adb-634bc7a0a8bf.png)

Run locally

![image](https://cloud.githubusercontent.com/assets/7295858/8399303/4f6cb6d8-1e5f-11e5-8536-e1f83d02d50a.png)

**Comment by hol353** [comment]
I always thought that NA was OK i.e. not applicable. Your real errors are down the bottom of your Jenkins run. Might need to get Justin involved.

**Comment by zur003** [comment]
To me it looks like a problem running the Wheat validation:
....
[1] 0.1099999999999 seconds
[1] Skipping test found in UnitTests directory.
[1] Skipping test found in UnitTests directory.
[1] ./Tests/Wheat/WheatValidation.apsimx
[1] Could not find table Simulations
Error in sqliteExecStatement(con, statement, bind.data) : 
  RS-DBI driver: (error in statement: no such table: TimeSeriesStats)
<simpleError in sqliteReadTable(conn, name, ...): could not find table TimeSeriesStats>
[1] Could not find table Simulations
Error in sqliteExecStatement(con, statement, bind.data) : 
  RS-DBI driver: (error in statement: no such table: TimeSeriesStats)
<simpleError in sqliteReadTable(conn, name, ...): could not find table TimeSeriesStats>
[1] Could not find table Simulations
Error in sqliteExecStatement(con, statement, bind.data) :

**Comment by HamishBrownPFR** [comment]
I don't think NA means OK because there are simulations that fail the tests on my computer so they should be failing on Jenkins also.

**Comment by fai04d** [comment]
The tests should return TRUE or FALSE. NA's generally mean there's missing data. I'd say Eric is right; it doesn't look like wheat ran. I'll look into it.

**Comment by HamishBrownPFR** [comment]
It is the wheat causing the error, I get the same problem when I run it on my computer.  It is not creating the ObservedPredicted report table but I can't work out why.

The NA issue is a concern

**Comment by fai04d** [comment]
Minor memory fail on my part. NA's are allowed. There are instances, especially where the 'test all' option is used that some combinations of tests will not exist or are invalid which will appear as NA in the test results and these are expected. The NA's you're seeing are a symptom, not the problem. I've spoken to Dean and we're going to try and think of a replacement for the R tests soon.

I'll still look into what's causing your simulation to fail.

**Comment by HamishBrownPFR** [comment]
Thanks Justin.  We need these tests to clearly show which ones have failed so we can work out where the problems are that need fixing.

**Comment by fai04d** [comment]
The problem seems to be related to the fact that Wheat.Zadok.Stage is now returning 100 for HarvestRipe instead of 90. Since the PredictedObserved table is looking for a Stage value of 90 in both tables it returns 0 rows.

**Comment by HamishBrownPFR** [comment]
OK, that will be related to the changes I have made.  I will investigate further.

Thanks

**Comment by hol353** [comment]
Closing. I've created an issue for a new testing system #215
