### ISSUE TITLE
Fodderbeet 

### ISSUE THREAD

**Issue by ekhaembah** [APSIMInitiative/ApsimX#1845]
New issue number request for a new branch

**Comment by hol353** [comment]
@HamishBrownPFR @RobZys I've run the fodderbeet validation and had a look at the auto-doc

- I can't find an example simulation. This will be needed before release.
- The auto-doc (which is now on the web for under review models https://apsimnextgeneration.netlify.com/modeldocumentation/) needs some work. Looks like it is documenting some of the simulations and there are a lot of graphs. Need to only have the important graphs. For example, see screen shot below:

![image](https://user-images.githubusercontent.com/1943827/58768156-06811b80-85da-11e9-9200-884a97781265.png)

**Comment by HamishBrownPFR** [comment]
Closing this because it duplicates #78
