### ISSUE TITLE
Create a new auto-documentation engine where models document themselves.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#187]

**Comment by hol353** [comment]
There is a problem with single author papers in the in-text citations.
Doesn't find all in-text citations in Soil Arbitrator model documentation.
Extra dots are being put into reference section
Not in alphabetical order.
Books need to add publisher and city.
Italics the journal.
Make the reader tolerant of \r\n characters.
Change to handle multiple citations in-text.
Can't do superscripts and subscripts from ///<summary> code documentation.
Crashes if PDF is open by another process.
In SoilArbitrator documentation the folder SplitPopulations should be nested in Simple Intercrop Test folder.
Memo is eating white space.
Graph captions are not appearing in the documentation.

**Comment by zur003** [comment]
Dean, are you intending to also use the PDFSharp/MigraDoc software to format and/or display the run Summary file? I might have some time to work on that next week when I'm in Melbourne, if you haven't already started work on it.

**Comment by hol353** [comment]
Wasn't my intention but now that you mention it, its not a bad idea. We'll need to sort out the cross platform issues first though and get pdfsharp running under mono.
