### ISSUE TITLE
Drop Down For Cultivars in Sowing Rules etc

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1870]
Users are starting to have trouble selecting cultivars in sowing rules etc because they don't know which ones exist.  There is a risk that users will insert incorrect names, or misspell them, and the simulation will fail.

Perhaps we need a UI element to provide a list of cultivars with the  cultivar descriptions also available so that people can see more information about that cultivar.  Many cultivars have memo fields explaining the origin of the cultivar and its basic characteristics.

**Comment by HamishBrownPFR** [comment]
There is already something that does this.  See PotatoPlantandHarvest rule in the Prototypes/Potato/PotatoValidation.apsimx
There is a drop down on cultivar that is created by putting the highlighted tag above the cultivar variable in the script  
![image](https://user-images.githubusercontent.com/7295858/29339332-d4e827f6-826d-11e7-8770-2bc4b6bd7c97.png)
![image](https://user-images.githubusercontent.com/7295858/29339385-18db5640-826e-11e7-81db-2c3e4b5f178e.png)

**Comment by hut104** [comment]
OK, that's really good.
So I guess this issue may have two parts then.
1) To add this capability to the example and validation files etc so that users have this ability in the simulations that they are currently adapting for their purposes.
2) Perhaps we can think of a way to get the cultivar information available in the existing capability so that the info in the memo's for each cultivar can be accessed in the GUI.

**Comment by zur003** [comment]
@hut104  It should be possible to display a tooltip with cultivar details (if provided) when the user mouses over a cultivar in the list, provided that information is reasonably concise.

**Comment by zur003** [comment]
I don't recall having a specific plan, although that was 2 years ago, and a lot of brain cell have died since then.

**Comment by zur003** [comment]
Ah, there is a way. It involves setting the ComboBox used by the CellRendererCombo to display through a SetCellData Function. That function indirectly receives information about a TreeView which is used to draw this list, and it's possible to instruct the list TreeView to use a column in its TreeModel as a tooltip column. A rather deep nesting of various Gtk controls, but it works. So where do we find the detailed cultivar information?

**Comment by hol430** [comment]
Well Neil mentioned above that many cultivars contain a memo child with documentation. So I guess the detailed info can come from there, if the memo exists.

**Comment by zur003** [comment]
OK. What, if anything, should happen with cultivar aliases?
