### ISSUE TITLE
Potential failure in SimpleLeaf.cs

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#19]
From Bangyou (2015-03-12):

Function "CoverGreen" in the SimpleLeaf.cs using CoverFunction or ExtinctionCoefficientFunction to calculate green cover. Both "CoverFunction" and "ExtinctionCoefficientFunction" are optional. "CoverGreen" only checks whether "CoverFunction" exists. 

Program will fail if both "CoverFunction" and "ExtinctionCoefficientFunction" don't exist in the model. 

       public double CoverGreen
        {
            get
            {
                if (CoverFunction == null)
                    return 1.0 - Math.Exp((-1 * ExtinctionCoefficientFunction.Value) * LAI);
                return Math.Min(Math.Max(CoverFunction.Value, 0), 1);
            }
        }
 
 
        [Link(IsOptional = true)]
        IFunction CoverFunction = null;
 
        [Link(IsOptional = true)]
        IFunction ExtinctionCoefficientFunction = null;

**Comment by hol353** [comment]
Bangyou, how about you put a fix for this.

**Comment by byzheng** [comment]
I will fix this.
