### ISSUE TITLE
Leaf.FW and Wheat.WaterSupplyDemandRatio used interchangeably in the wheat model

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1910]
Chose one or other and use it thourgh out.  This is probably an issue throughout the plant models

**Comment by HamishBrownPFR** [comment]
This is a problem in the oat model also.  Solution needs to be implemented over all models.

**Comment by ric394** [comment]
This very old. Closing. If this is still an issue, please feel free to comment.
