### ISSUE TITLE
GTK GUI: Can't rename a node in the tree by clicking on it and then clicking on it again.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#1919]
Double click works but not click and click again i.e. we want it to be like windows explorer renaming.

**Comment by zur003** [comment]
Well, if that's what you really, really want... Personally I find the "click to rename" thing a bit annoying.

Also remember that these Windows conventions may seem a bit odd on OSX and Linux (and vice-versa).

So basically you want renaming if you single-click on the node that's already selected, right? Should double-clicks also enable renaming, or should that do something else (or maybe nothing at all)?

**Comment by hol353** [comment]
Most Windows users are used to it and expect it to work that way. Old APSIM also works that way so I think we need to implement it. We don't need double click to do anything though.
