### ISSUE TITLE
We should try to maintain cross-platform capabilities

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#194]
I just attempted to build and run ApsimX on Ubuntu with Mono, and came across several bits of code that were not written with cross-platform capabilities in mind (e.g., hard-coding of '\' as a path separator). These should be eliminated. Also, the PDFSharp stuff may need a bit of tinkering to work well on Linux platforms; see http://forum.pdfsharp.net/viewtopic.php?f=4&t=1206 for a discussion of this.

**Comment by hol353** [comment]
Agreed re the cross platform bits. I wasn't aware that PDFSharp wouldn't work on Ubuntu. We'll have to look into it.

**Comment by zur003** [comment]
OK. I got PDFSharp to work on Ubuntu using the patches available from https://github.com/tpokorra/openpetragit/tree/master/csharp/ThirdParty/PDFSharp. It doesn't render terribly well - I think it has trouble working out the font metrics - but at least it produces a result rather than crashing.

**Comment by hol353** [comment]
Closing. Addition specific improvements to how PDFSharp works on MONO can be made under a new issue.
