### ISSUE TITLE
White space between characters for Doc in class summary tags

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#1948]
Writing doc in the summary tag of the text string.  When ever we have a line break in the summary the doco doesn't put a space between the word on the end of the line and the start of the next line
![image](https://user-images.githubusercontent.com/7295858/29849146-0297b9da-8d79-11e7-9401-69f15d908fcc.png)
![image](https://user-images.githubusercontent.com/7295858/29849249-a2b4a860-8d79-11e7-8f34-48c1fe4890b8.png)

**Comment by rcichota** [comment]
I have noticed this too, see issue #1801
