### ISSUE TITLE
UI for weather component is unstable when changing met file

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1978]
I find that the weather ui has issues when changing the weather file.  It often goes off "thinking", and often inserts the wrong file path to the selected met file name.  I find that it starts to work again if you run the simulation and then go back to the met ui.

**Comment by hol353** [comment]
OK This is caused by the hack in ViewBase.cs:

///// <summary>
        ///// Works around weird Windows bug.
        ///// See https://connect.microsoft.com/VisualStudio/feedback/details/525070/openfiledialog-show-part-of-file-name-in-win7
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="args"></param>
        private static void WindowsWorkaround(object sender, EventArgs args)
        {
            FileDialog dialog = timer.Tag as FileDialog;
            if (dialog != null)
            {
                SendKeys.SendWait("{HOME}");
                SendKeys.SendWait("^(a)");
                SendKeys.Flush();
                (sender as Timer).Stop();
            }
        }

Can we disable this hack and then set the file open dialog box file name to null e.g.

dialog.FileName = null;

rather than:

dialog.FileName = Path.GetFileName(initialPath);
