### ISSUE TITLE
Unstable report ui

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1980]
When typing in new output variables into the report ui several of us in our workshop found that the GUI would crash if a new output is typed and the user then hits enter.  You seem to be able to avoid the crash if you hit save instead of hitting enter.

**Comment by hol430** [comment]
@hut104 Is this still an issue? I have not been able to reproduce this.

**Comment by hut104** [comment]
I’m assuming that the workshop was the one which involved Hamish visiting Toowoomba. I am not sure that I have seen this issue in a while.
