### ISSUE TITLE
Potential bug when StructuralFraction is not a constent value

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#1993]
I can understand the logic behind of this line of code about `theoreticalMaximumDM`. However, the logic is only correct when `StructuralFraction` is a constent value, otherwise the theoretical maximum DM could be under- or over-estimated depending on the dynamic of `StructuralFraction`. In theory, modeller can write any types of functions for `StructuralFraction`.

Not sure how to fix it. But we can check whether `StructuralFraction'  is a constant value and fix it later. 

https://github.com/APSIMInitiative/ApsimX/blob/fcba475154255d0fed50a950f3a03a327a01b3db/Models/Plant/Organs/GenericOrgan.cs#L283

**Comment by HamishBrownPFR** [comment]
Hi @byzheng .  I am not sure I understand the problem.  theoreticalMaximumDM can go up or down as StructuralFractionChanges.  If StructuralFraction increases so does the theoreticalMaximumDM and demandedDM increases.  If StructuralFraction goes down theoreticalMaximumDM can become less than baseAllocated but this is constrained to a minimum of zero so should not cause errors.  If StructuralFraction decreases then demandedDM may become zero for a time until StructuralWt increases to a value where theoreticalMaximumDM exceeds base allocated again.

**Comment by byzheng** [comment]
Hi @HamishBrownPFR  The StemStorageDemand would be an example for this problem. 

https://github.com/APSIMInitiative/ApsimX/blob/fcba475154255d0fed50a950f3a03a327a01b3db/Models/Plant/Organs/GenericOrgan.cs#L283

The code above supposes to calculate the theoretical weight of an organ at the start of this day throught the structural weight and fraction. In theory, the method is correct when the structural fraction is not changed during growth season. 

In the example of stem, the StructuralFraction is changed from 0.7 into 0.05 at Stage 5 (FlagLeaf). After flag leaf, the structural weight of stem is divided a small number (0.05, instead of 0.7), then theoreticalMaximumDM becomes a big value, then big demand of Storage (See figure below). 


![image](https://user-images.githubusercontent.com/1657381/30254353-9f458388-96da-11e7-8f9e-61a210ad808b.png)


The spike doesn't change structural fraction, so demand looks reasonable (http://byzheng.github.io/APSIM-Wheat-Doc/_book/cha-spike.html)

**Comment by HamishBrownPFR** [comment]
So why is that a problem?  In some cases you would want to see a big increase in sink capacity of an organ at a certian stage.  If you don't want it to increase it so much then you wouldn't increase the value of StructuralFraction so much.  There is no need to change the code to prevent this.

**Comment by byzheng** [comment]
@HamishBrownPFR  You may be right. I will think about more, test it and post here if I find any more questions.
