### ISSUE TITLE
Reduce the amount of memory that APSIM uses

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#1999]
There are two parts to this.

1. Considerable memory is being used by keeping all outputs in memory until all simulations have completed. Then they get written to the .db file.
2. All simulations are created up front. This consumes a lot of memory for very large jobs.

**Comment by josharp22** [comment]
Hi Dean
Just tested your recent commit on a big simulation. 3675 of the 3675 simulations in a large factorial ran without any problems when saved locally (crashed at 2151 when saved on a network drive). Thank you very much for fixing this, will make a huge difference :-)
Cheers
Jo

**Comment by zur003** [comment]
@hol353 - found a small bug arising from your database changes. If you have PredictedObserved components in your model, the very first time you select one of them in the GUI, you get the error message "no such table: _Simulations". Arises at line 570 in DataStore.cs, I think. Can't quite work out what's going on here.

**Comment by hol353** [comment]
I'll look into it.

**Comment by zur003** [comment]
Looks like a threading issue. FileName is null one moment and non-null the next...

**Comment by hol353** [comment]
Hmmm How can I reliably reproduce the problem? Seems OK to me.

**Comment by zur003** [comment]
Open Prototypes\Potato\Potato.apsimx. Open the DataStore node, select NodeAppearance. I then see the message appear at the bottom of screen. If running in the IDE, I can set a breakpoint on line 74. This line should be reached only in FileName is null, but when things stop at the breakpoint, FileName has been set (and the error message does not appear). That sounds like a threading issue, but I don't see any extra threads, unless maybe Gtk is doing something weird. Haven't tried this with the Windows.Forms GUI.

**Comment by hol353** [comment]
I still can't see what you're seeing. If potato.db exists, I get no error at all. If potato.db does not exist I get a series of exceptions which are trapped and so get no error at bottom of screen in GUI. Are you sure it is line 74 of DataStore.cs?  Have you pulled from APSIM.Shared? Have you run potato to see if that fixes the problem?

**Comment by zur003** [comment]
Potato.db exists, but does not contain a _Simulations table (but it does have a Simulations table). Is the problem that it's an "old" database? I also see the problem if I open the "Standard toolbox", and select PredictedObserved (under Data store and analysis models).

I see the same issue when using the Windows.Forms GUI.

I also see weirdness in the debugger that I don't understand. The FileName of the DataStore is being set, but I can't work out where, so perhaps it's during deserialisation?

**Comment by zur003** [comment]
Curiouser and curiouser. When I attempt to run the Potato simulation, at the end I get an SQLiteException: no such table: _Simulations

**Comment by zur003** [comment]
Hhmmm. Getting rid of the old potato.db seems to solve the problem.

**Comment by hol353** [comment]
If you run APSIM by right clicking on the very top node in the tree ('Simulations') do you still get the problem. APSIMFileConverter.cs is supposed to convert old table names (e.g. Simulations, Messages, InitialConditions) into new names (_Simulations, _Messages, _InitialConditions)

**Comment by zur003** [comment]
If I just restore the old Potato.db, I still have a problem. Likely because my Potato.apsimx was updated by a pull from github, rather than by me loading it into the GUI. So I now have an updated .apsimx file but and old .db file, apparently. 

Do you see the problem if you select PredictedObserved in the Standard Toolbox (that's actually where I first noticed it)?

**Comment by hol353** [comment]
Yes I see the problem from standard tool box. 

A pull from GitHub shouldn't have updated your potato.apsimx file. I was careful to not include any .apsimx files in my pull request.

I'll investigate these two issues on Monday.

**Comment by zur003** [comment]
I think I understand now. Two different problems were presenting the same symptom. The "potato" problem was due to having an out-of-date database (and an up-to-date .apsimx; see your commit of 13 Sept 12:52). The problem with the Standard Toolbox is different - there is no filename for the database created by the PredictedObserved object, as it is unattached to a simulation. With no filename, sqlite creates a private, temporary database. That would be fine, except after adding tables in lines 526-529 of DataStore.cs, the database is closed, then reopened to get the "readonly" setting right. Closing the temporary results in its destruction, so the reopened version lacks the requisite tables.

**Comment by zur003** [comment]
I'm not sure when this started, but units in report tables are showing up with two sets of parentheses, as in "((g/m^2))".

**Comment by zur003** [comment]
@hol353 I am finding that running the wheat validation simulations result in a very long wait at the end, apparently while values are written to the database. I think this can be remedied by slightly modifying the way database transactions are used.

**Comment by zur003** [comment]
Ugh. I had a look at memory usage in VS and also via AQTime. There's a lot that's not begin garbage collected when it should; models remain in memory even when they've been "closed" in the GUI. I'm not sure why. This is going to take a bit of analysis.

**Comment by hol353** [comment]
Closing this. Neil's 32 core computer is able to run 10000 simulations from a single .apsimx file producing a 3Gb .db file.
