### ISSUE TITLE
Writing database tables should be faster

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2018]
In many cases, run times seem to be limited by database write times. This is most notable when running large sets (like the wheat validation simulations), where the wait time after all simulations have nominally completed can be quite long. There is definitely scope for improvement here.

**Comment by hol353** [comment]
Yes, I'm working on something now that normalises rows into well formed tables that are much quicker to write to the .db. Hopefully commit something today (if it works)

**Comment by zur003** [comment]
I've got a few things in mind as well. How can we co-ordinate and not get in each other's way?

**Comment by hol353** [comment]
Not sure. Hopefully I commit something by lunch time. Do I go first?

**Comment by zur003** [comment]
I have a change I'd like to make in APSIM.Shared that's ready to go. Probably won't interfere with your stuff. Can I do that now, then wait for your changes?

**Comment by hol353** [comment]
My stuff is now merged. I probably won't get any more done on this now until October as I'm on leave for the last week in September.

**Comment by hol353** [comment]
The next thing I would probably do would be to write more rows in one go to the .db. Currently the WriteDBWorker method goes and finds a set of tables for a simulation that have been 'completed'. This means that it writes a simulation at a time. I would probably reverse that and get the WriteRow method to store the rows by table rather than simulation so that the WriteDBWorker thread can write as many rows from a single table as possible.

**Comment by hol353** [comment]
OK. This is a placeholder for me for when I get back from leave. 

Here's where I got to on this:
https://github.com/hol353/ApsimX/tree/NewJobManager

Feel free to pull from this branch and have a go at getting it working. 

It seems **much** faster (almost twice as fast) running on Neil's 32 core computer when using multi-process run mode from GUI (F6). It seems to work OK when running from GUI by normal run mode (F5). It may also pass Jenkins. When running using the multi process run option from the GUI (F6) it doesn't run every simulation correctly. For example, the wheat validation doesn't correctly run 'YarrabahCreek' simulation. It starts but doesn't finish and doesn't throw an exception - at least not one that gets written to the '_Messages' table. The .db file created by Neil's computer is here:

https://www.dropbox.com/s/6vp5che1y1qa8at/Wheat.db?dl=0
