### ISSUE TITLE
Need better user feedback of simulation run status

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2023]
Currently if the user runs a single long simulation (e.g., the Wheat example), there is no real indication of simulation progress. The user may sit waiting for a minute or more with no clear indication that anything is happening.
Also, if the user Stops the current simulation run, there is no feedback that the simulations have actually been stopped.

**Comment by hol430** [comment]
@zur003 Is this still an issue? I just ran the wheat example, and the progress bar and status text both seemed to update regularly. Stopping the simulation also gave me feedback almost immediately.

**Comment by zur003** [comment]
What we have currently in place works reasonably well when there are multiple simulations (although see Issue #2196). I was thinking about the situation where there is a single, but large and slow, simulation. We can track the progress of completed simulations, but we don't track progress within a simulation, so if that single simulation takes a long time to run, the user gets no feedback on its progress. I think we had this in APSIM Classic, but it was hard to get right. Maybe we don't really need it.

**Comment by hol430** [comment]
How did it work in APSIM Classic? Did you have a secondary progress bar for the simulation currently being run, or did you just factor the progress of each simulation into the overall progress of the experiment?

A simple solution might be to make the progress bar 'pulse' like a windows forms progress bar - it shows a static percentage, but every few seconds you see a burst of lighter colour propagate through the progress bar. I don't know if this is possible with a Gtk progress bar though - the pulse function certainly does not do this.

**Comment by zur003** [comment]
If I recall correctly, APSIM Classis factored the progress of each simulation into the overall progress indication. Simulation progress was determined by querying the current date of the simulation clock and comparing with the simulation start and end dates, but it can be difficult to get this information back to the GUI.
