### ISSUE TITLE
Report enum value as string in reports

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#2038]
Is it possible to have a default .ToString() when reporting enums so values are reported and not left blank? I can't see there is a way to add the .ToString() in the report creation, so it probably needs to be in the code.

**Comment by zur003** [comment]
@hol353 - I have a pull request to fix this in APSIM.Shared.

**Comment by hol353** [comment]
Resolves via a change to APSIM.Shared

**Comment by lie112** [comment]
Should this now report the string of an enum in reports? My reports present the integer value of the enum and not the string value at present.

**Comment by hol430** [comment]
Looks like this has resurfaced. I'll fix and add a test so it doesn't happen again.
