### ISSUE TITLE
Stage is not changed in a specified day before Flag Leaf for wheat model

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2056]
I have tested a few simulations for wheat model in Gatton with different sowing dates (from May to July).

The output always has the same Stage in two days (4 and 5 days before Stage Flag Leaf). See red dots in the figure below for an example.  

Tracking down to class `LeafAppearancePhase`, but didn't notice any strange things.

![image](https://user-images.githubusercontent.com/1657381/31374369-fea39ec4-ade0-11e7-8797-3fbd07f4ea7b.png)

**Comment by byzheng** [comment]
Some further information about this issue. I noticed this issue when I plot an area figure for dry weight in all organs by stage.

![image](https://user-images.githubusercontent.com/1657381/31746814-a3b1a43e-b4ac-11e7-86e6-71ef8a1085d1.png)

**Comment by ric394** [comment]
This very old. Closing. If this is still an issue, please feel free to comment.
