### ISSUE TITLE
Two different GUIs is one too many

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2059]
For some time now, we've had both a Window.Forms GUI and a Gtk# GUI. This is a maintenance headache. There no longer seems to be a good reason to continue maintaining the Windows.Forms GUI, so if there are no objections, it will be killed.

**Comment by rcichota** [comment]
Hi Eric, are all the bits and pieces need to run GTK now included in APSIM or the user still need to install a few libraries? I generally use the windows UI, so when I saw you raising this issue I tried to run the GTK UI, but it creashes on me ( I have a new computer so I did not install any of those libraries..)

**Comment by zur003** [comment]
@rcichota 
If you're using an "installed" Apsim, it should "just work". If you're building ApsimX yourself, you will need to copy the Bin and lib folders found in DeploymentSupport\Windows into your main ApsimX folder. You may find that you also need to delete older versions of Gtk# from your global assembly cache.

I realise that's a bit inconvenient, but it's part of the price we pay for having a GUI that runs across multiple platforms.

**Comment by rcichota** [comment]
I am building myself. I copied the files and all seem to work now. Thanks. And it is not really any inconvinient to have to copy, the only caveat is one has to know what. Fingers crossed we can go for only one version and simplify this things.
