### ISSUE TITLE
Develop a white clover model (PMF)

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#2069]
White clover (Trifolium repens) is herbaceous perennial plant of the Fabaceae family.  It is native of Europe and central Asia, but now is spread worldwide, being recognised as the most important forage legume in temperate zones. White clover provides high quality feed for animals and is tolerant of grazing and trampling.  It is typically used in mixed swards, alongside grasses, in which it improves feed quality and it can supply N to the system through biological N fixation. The plants are short, with stems functioning as stolons from which petioles with three leaves and flower stalks grow.  Roots are generally shallow and also grow from the stolon nodes.
The objective here is to develop a basic white clover model using the plant modelling framework (PMF). In this project the focus in on describing the general growth pattern of monoculture, as well as the re-growth after cut/grazing and including N balance.  As PMF uses MicroClimate and SoilArbitrator to manage resource access, it should be readily possible to develop simulations with multiple species.  While developing the White Clover model, the need for it to be used in mixed swards simulations will be taken in consideration as much as possible.  However for fully testing this, a grass model is needed (none is currently available in PMF, although AgPasture may be an alternative).

**Comment by rcichota** [comment]
@sarahcleary 
I am finally ready to cal the review of WhiteClover to a finish. I have finally got around to re-trace some to the steps taken during the review, eliminate some of the junk and align the simulation with new json format. All this was completed this week and Dean has merged into the main branch.
A lot of small modifications where done along the way to comply with the reviewers comments, which centred mostly on the documentation itself. Several of the changes are/will be useful for other models too.  The flow of the text, the ranking of items, the exposure of information about organs and parameters have been all improved, some of the graphs are still too cluttered, but this is something Dean at al, are looking into. I have also added a few more comments about the outcomes of the validation, but kept this to  minimum, as the amount of data was fairly limited it is difficult to point out why some of the results are not that good or more definite directions in which the model could be improved.  There is some work on going for red clover and diverse pastures that may help improving some of the biomass/N allocation which I think is not quite right in the white clover model. This will include some sensitivity analyses too.
I hope this is sufficient an answer to the review, but let me know if I need to expand further on any point.

**Comment by sarahcleary** [comment]
thanks @rcichota 
@APSIMInitiative/reference-panel - please note @rcichota's comments above.  Please review and provide any feedback prior to the RP meeting on the 21/5,  
thanks
Sarah.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - confirmed for merging in RP meeting.  @rcichota - please release and work with Dean

**Comment by sarahcleary** [comment]
Closing issue, released 28/5/19
