### ISSUE TITLE
Experiment Object not writing simulation names properly when only one variable is replaced by a factor node

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#207]
When working properly the experiment object will give something that looks like this

![image](https://cloud.githubusercontent.com/assets/7295858/8739087/5c517e6c-2c8b-11e5-843f-c3cedc7b0ca1.png)

In this case the factor nodes are replacing more than one variable e.g

![image](https://cloud.githubusercontent.com/assets/7295858/8739105/980f3548-2c8b-11e5-87bd-3ff6a587327d.png)

However, if we remove the 2nd line (it is not needed because it is changing a variable to the same value and was only put there to get round this bug) like so

![image](https://cloud.githubusercontent.com/assets/7295858/8739133/de00d606-2c8b-11e5-824a-74b34941950e.png)

The simulation names look like this
![image](https://cloud.githubusercontent.com/assets/7295858/8739146/02a33af8-2c8c-11e5-8977-47930882e660.png)

The value for the variable has been appended to the end of the simulation name.

This is not a big issue for the simulation I am using the show the bug but in some simulations the variable that is being overwritten has some characters that are cause simulations to go haywire.

**Comment by zur003** [comment]
I think the problem is with the code block in lines 91-101 of Models\Factor.cs, but I don't understand the intent of this code well enough to be sure the "fix" I have in mind is correct.

**Comment by hol353** [comment]
Try your fix and see what happens?
