### ISSUE TITLE
Potential pitfall with PredictedObserved

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2074]
There is a potential source of confusion when comparing predicted and observed data, which Philip Smethurst (L&W) recently encountered. Philip noticed that much of his observed data was not appearing in the PredictedObserved table. Data were being matched on Clock.Today, as would commonly be the case. Everything looked fine, but it turned out that many of his Observed data had Clock.Today values which included a time-of-day component, along with the date. This wasn't visible in Excel, as the cell formatting was set to show only the date, but it meant that the comparisons of Clock.Today with predicted values were failing, because they were off by a few hours.

I don't know that this qualifies as a "bug", but it is a non-obvious problem that others may encounter.

**Comment by HamishBrownPFR** [comment]
I have been caught by this before too.

Would be good to reformat dates of imported files to the same format that APSIM writes to the report tabels so they always match

**Comment by hol353** [comment]
Probably need to get APSIM (Excel importer) to strip off the time component of dates when reading from EXCEL.

**Comment by zur003** [comment]
Ok. Although it's a bit of a hack, and may cause us grief in the future if we ever work with sub-day time steps, it's probably worth it to avoid a common and non-obvious trap.
