### ISSUE TITLE
Can we swamp "Data" and "Properties" panels in Report module?

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2081]
In the report module of ApsimNG.exe, two panels are presented (i.e. "Data" and "Properties"). It is slow to load the whole table in the "Data" panel if there is a big table. However, we are interested to change the "Properties" in most of cases. So it will speed up to avoid load whole Data table before selecting Properties panel.

**Comment by zur003** [comment]
That sounds reasonable. There is another thing we may want to consider. Currently the Properties tab shows the reporting variables and frequency for the current report (as selected in the left panel tree) only, but the Data tab allows any report in the simulation to be viewed. This is probably OK, but can feel a bit inconsistent. Perhaps we should allow report (table) selection only when viewing the DataStore as a whole?
