### ISSUE TITLE
Copy the full path to any nodes in a model

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2087]
For the report and documentation purpose, I always write names of a node in the model, e.g. `'Wheat.Leaf.CohortParameters.LeafSizeShapeParameter` through copying and pasting all parent names of LeafSizeShapeParameter. 

It will be very useful to add a new item in the context menu (right click) to each node to generate the full path of this node and copy to system pasteboard.

**Comment by hol430** [comment]
@byzheng Do you want to copy the full path to the node, right from the top level node in the file?

e.g. in the wheat example, you might get the path 
Wheat.Simulations.Validation.SE Queensland.APS26.APS26NRate160WaterWet.paddock.Wheat.Leaf.CohortParameters.LeafSizeShapeParameter

Is this what you had in mind?

**Comment by byzheng** [comment]
Yes I would like to have a function to copy the full path to the node. It will be useful to add ".Value()" if the node is a function.
