### ISSUE TITLE
Gtk# user interface has memory leaks

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2089]
It appears that some elements in the Gtk# user interface are not being garbage collected correctly, and as a result memory consumption keeps gradually increasing. This appears to be more of a bug in the Gtk# logic than in our code, but we may be able to find some workarounds.

**Comment by zur003** [comment]
Just for the record, some of the problems I was seeing were the consequence of using an older gtk-sharp.dll, which I was using for testing purposes. The newer versions (including the one packaged with the installer) fix a lot of these problems. I'm nonetheless making code changes to be a bit more thorough about all of this.

**Comment by hol430** [comment]
Closing this as we can open new issues for specific instances of this problem as we find them.
