### ISSUE TITLE
White regions when mouse overs ApsimNG.exe

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2094]
#2093 fixed this bug of #2080. But there is a new bug. Step to reproduce this bug.

* In the left tree panel, select any element. 
* The element region becomes white when mouse over it. 
* The element keeps white when mouse overs out the element from bottom to up,  is back to normal when mouse overs out the element from top to bottom

**Comment by zur003** [comment]
I have not been able to reproduce this problem. Is anyone else seeing this?

**Comment by byzheng** [comment]
@zur003 FYI: I have tested it under Windows 7 (laptop and VM), Window 2008 Server (VM).

**Comment by byzheng** [comment]
@zur003 This bug disappeared after I copied all files from DeploymentSupport\Windows\Bin to Bin folder. It may be better to move these dlls into Bin as the ApsimNG.exe is the standard interface now. 

I have spent the two days to figuring out the dlls caused lots of problems in the interface.

**Comment by zur003** [comment]
They are not in the Bin folder because they are of use only with the Windows builds. It is much simpler to create installers for Linux and OS X if we can add everything in the Bin folder as part of these distribution, and not have to specifically exclude files that are of use only on Windows.
