### ISSUE TITLE
Can we increase the number of decimal digits in soil and water viewers?

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2095]
Currently only two decimal digits show in the soil and water viewers. Sometimes it is confusing if there are more decimal digits in the raw data and similar values. 

See example below. The actual values of AirDry are 0.052 and 0.046 for third and forth layers, but show as 0.05 in the table, and plot as the actual values. 

It will be better to show at least three/four decimals in the table.

![image](https://user-images.githubusercontent.com/1657381/31871206-080e8bda-b7f6-11e7-916b-652cb66ab738.png)

**Comment by zur003** [comment]
That's easy to change, but it raises the question of whether we should be looking at this more generally. Should we provide a mechanism for the user to indicate the amount of precision they want? If so, where should this appear in the GUI, and how should that value be stored? Currently, precision settings are applied to the grid as a whole; should it be possible to vary the precision of each column separately?

**Comment by hol430** [comment]
@hol353 @zur003 do we have any preferences to how we resolve this one? I've had a few users ask about this feature. I guess the real questions here are:

1. How do we specify precision?
Simplest option here is probably to add something to the grid context menu
2. Should changing the precision be persistent between clicking on a different nodes and/or between restarts of apsim?

Out of curiosity - how did this work in old apsim?

**Comment by byzheng** [comment]
We could simple show two valid digits in this case, e.g. 0.052 and 0.046 (0.05 is only one valid digit).

**Comment by hol430** [comment]
I think in a lot of cases, people want the ability to choose the number of digits shown.

**Comment by zur003** [comment]
And there's always the question of whether to allow selection of the number of places to the right (or left, I suppose) of the decimal point, or the number of significant digits. It the underlying value is 0.012345, does indicating "3 digits" mean we should see 0.012 or 0.0123?

**Comment by hol430** [comment]
True - I guess we could use the term significant figures to be less ambiguous. Or we go the whole hog and prompt the user for a printf-style format string.

**Comment by hol353** [comment]
Closing as this is very old. We currently show 3 decimal places for water values.
