### ISSUE TITLE
Shortcut `Cancel` is not working in the search windows of Report

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2100]
In the Properties of Report node, Shortcut `Cancel` cannot remove the search windows which need to click Cancel button by mouse. It will be convenient to have this shortcut.

**Comment by hol430** [comment]
@byzheng By "Shortcut Cancel cannot remove the search windows" do you refer to the escape button on the keyboard?

**Comment by byzheng** [comment]
Yes

⁣Sent from BlueMail ​
