### ISSUE TITLE
OrganArbitrator.FN has very big values

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2104]
Wheat.Arbitrator.FN (OrganArbitrator class) has very big values (see figure below) which is caused by the small values of N.TotalPlantDemand.

![image](https://user-images.githubusercontent.com/1657381/31965692-7038d2fa-b94b-11e7-8961-ea165880fc75.png)

**Comment by hol353** [comment]
@byzheng Is this still an issue or can we close it?

**Comment by byzheng** [comment]
Can close it now
