### ISSUE TITLE
NULL error in the storate

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2107]
After I pull the latest version of source codes from repository, I cannot run any simulations with an error message in the storage (see below). After check out my working branch, all simulations are working. 

The same problem is happening in my laptop and VM with Windows 7 system.

Have any ideas how to fix it?

![error](https://user-images.githubusercontent.com/1657381/32022109-c19b974a-ba18-11e7-8de0-0410537fd3c5.png)

**Comment by byzheng** [comment]
Have figure out this problem. I have missed one variable "DMConversionEfficiencyFunction" in Leaf model which is fixed in the Justin's branch. This error message shows in the summary, but doesn't show in the status bar. It will be better to show all message in the status bar  or stop program when this error is happening.

**Comment by hol430** [comment]
Looks like this issue has been fixed at some point. The function in your example appears to no longer exist. What's more, if I create a new function in its place, subscribing to the "Completed" event, and throw an exception, the exception is correctly displayed in the status bar. 

I'm going to close this issue, but if you do notice any errors not being displayed in the status bar, please do open an issue so we can fix it.
