### ISSUE TITLE
Treeview icon resource folder

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#2111]
Before we port CLEM with a large number of UI TreeView icons to GTK I was wondering if we could add a folder structure under the ApsimNG\Resources\TreeViewImages folder to add the model namespace without "Model." as subdirectories. So the CLEM treeview images from CLEM models (e.g. Models.CLEM.Activities.RuminantActivityBreed.cs) will be stored in a separate directory ApsimNG\Resources\TreeViewImages\CLEM\ruminantActivityBreed.png (with or without the .Activties level). This can be accessed when adding the images in the code using the models full namespace and will help keep the images folders tidy and ordered and manageable.

**Comment by hol353** [comment]
Yes, I'm happy with this. Are you going to make the changes to the GUI to enable this? 

I'd prefer not to have an IF statement somewhere looking to see if CLEM is running and if so load the images from a different folder in the resources. I'm not sure how we do this.

**Comment by zur003** [comment]
If you look at the GetNodeDescription function in ExplorerPresenter.cs, you'll find the logic that constructs the resource name for the various treeview images. If the various CLEM models are all placed in a Models.CLEM namespace, then it should be almost trivial to adjust the resource path accordingly. It probably wouldn't be a bad idea to do the same for PMF  model (these models already live in a Model.PMF namespace). Better yet, just do this for everything - have the structure within the resources\treeviewimages folder completely parallel the namespace structure of the models.

**Comment by lie112** [comment]
I didn’t want to make the changes as I wasn’t sure what current icons related to what models and it was quite a change in resource folder locations to implement. I assumed this change would benefit all models and the folder readability of APSIMx as a whole. My philosophy at present is not to touch anything that may influence others without passing it by you guys or requesting the changes. I could see in the code that it was a simple, quick change to the folder location based upon the namespace. I am currently coming up to speed with GTK+ and Glade and will reproduce our simple CLEM presenter wrapper as a first task. This is a CLEM based presenter with an IF statement, but I will write it so it can be used by all models if you want to integrate it. Alternatively, I would incorporate it above the RightHand ViewHolder in the Explorer view and have it respond to attributes if provided for the model class..

**Comment by lie112** [comment]
I have made these changes and will push them when we rebrand CLEM and I add all our icon resources. I added code to default to the current system so backward compatible.

**Comment by lie112** [comment]
I had to make some additional changes to the ListBoxView in “public string[] Values” to allow this structure to be used in the Add Model window. To do this I had to pass FullName to the Values array to give the namespace. It all works, but I am not sure what the poslastSlash is handling. Is it only model names that get passed to this array or is it used for other list box displays? I have checked whether val starts with “Model.” To decide if a model was passed and handled appropriately.

**Comment by zur003** [comment]
ListBoxView is used in a couple of different contexts - it's intended as a fairly generic mechanism for displaying a list of items with associated icons. It's used in the Add Model and Add Function views, and is also used in the main view to display the list of most-recently-used files. The posLastSlash test is a way of seeing whether the listed item is a (qualified) filename. Your proposed change should be fine.

**Comment by lie112** [comment]
Di is keen that the current version of CLEM is incorporated with APSIMx development. When this happens the two new changes with the GUI will be implemented. These are written so that everyone can use them.

(a) Anyone will be able to place their treeview icon images in sub a folder under APSIMNG/Resources/TreeViewImages/[Model name from namespace] . If they remain in the TreeViewImages folder this will continue to work as the default.

(b) Anyone will have access to the CLEM style wrapper around the right hand pane of the explorer. This reports the Model name, description and help link URI at the top of the pane with the specified presenter below. This will only be implemented if the user has added a [Description()] attribute to their model otherwise the default right hand Presenter will be supplied. The help link will only be displayed if a [HelpUri] attribute is provided with the model. I don't think this will affect anyone, but does offer this functionality to anyone who wants it.

I will learn how to pull an issue and push the changes back to APSIMx
