### ISSUE TITLE
Root length?

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2114]
No sure about the actual meaning of root length in the source code. So I guess it is the total length of root system. However, the length is calculated as the `Sum` of length density which doesn't make sense to me. 

```
MathUtilities.Sum(LengthDensity)
```

`Root.Length` can be directly calculated through 

```
Live.Wt * SpecificRootLength.Value()
```

@HamishBrownPFR  If you can check/confirm it, I will submit a pull request later.

**Comment by byzheng** [comment]
@HamishBrownPFR Could you have a look at this issue?

**Comment by HamishBrownPFR** [comment]
That variable is not used in the source code and I am not sure what it is supposed to represent or used for.  Suggest removing it.
