### ISSUE TITLE
Switch function

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2118]
Do we have a switch function? 

In the case of photosynthesis, we have three models now (RUE, SPASS, DCaPS). I would like to put three models into wheat for testing purposes. Users might like to have three models too. 

Now I have to change the node name into "Photosynthesis" every time. It will be better to add a switch function to allow easily to switch into another model, which can also set in cultivar parameters.

**Comment by HamishBrownPFR** [comment]
For testing, put the different photosynthesis models in as factors in an experiment.

**Comment by byzheng** [comment]
Thanks @HamishBrownPFR  No sure how to do it. Do you have an example?

**Comment by HamishBrownPFR** [comment]
Not currently but could put something together

**Comment by HamishBrownPFR** [comment]
This is how you would do it (see shot below).  In theory this should work but currently it throws an error because it can't find [Wheat.Leaf.Photosynthesis].  If this is something you will need to do we might need to ask @hol353 to have a look at it to see why it is not working.

**Comment by hol353** [comment]
Put the square brackets around just Wheat?

**Comment by byzheng** [comment]
@HamishBrownPFR Thanks. Do you forget to add screenshot?

**Comment by HamishBrownPFR** [comment]
Sorry, I did forget to add the screen shot.  I will email you the file.  It works if you just put [Photosynthesis] as the model to replace.  The find method looks through all models in the simulation and there is a risk it will find another model called Photosynthesis if for a example a manager script is named Photosynthesis.  So be careful with this.  @hol353 is it possible to have duplicated model names or does the UI prevent this somehow?
![image](https://user-images.githubusercontent.com/7295858/32248770-97cf0df2-beeb-11e7-870b-5e3f13f6b723.png)

**Comment by hol353** [comment]
Yes it is possible to have duplicated model names. In fact we rely on this feature. Organs often have child models / functions with the same name as other organs (e.g. MinimumNConc).

To minimise the risk that the wrong function will be found, the parent model (RUE?) could use a [ChildLink] rather than a [Link]. If not using links, then do an Apsim.Child(...) rather than Apsim.Find(...)

**Comment by byzheng** [comment]
@HamishBrownPFR @hol353  Thanks for your help. I can test two photosynthesis models now. 

For the customised wheat model, I have to place it under the "Field" node. It is not working under the Replacements. It may be a bug to find the model. I attached my apsimx file for an example. The two simulations have the same results. 

[PlantModelFactors.zip](https://github.com/APSIMInitiative/ApsimX/files/1436399/PlantModelFactors.zip)
