### ISSUE TITLE
In plot, line type and marker type are not working when colour is x

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2119]
In plot, line type and marker type are working fine when colour is set as fixed colour, but only show different colour when Colour is varied by a factor.

For example, 

![image](https://user-images.githubusercontent.com/1657381/32153122-47051614-bd74-11e7-8bf3-32c3e02c0733.png)

**Comment by zur003** [comment]
It appears to me that the problem occurs when Marker type and Color are both set to vary by the same thing. Only one of the characteristics is varied as expected.
