### ISSUE TITLE
Error in showing map

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2122]
An error message is obtained when adding a new map model. Looks like the Google map doesn't the embed browser.

![image](https://user-images.githubusercontent.com/1657381/32153645-9884c78e-bd77-11e7-9515-a052d5bb7221.png)

**Comment by byzheng** [comment]
PS: It is not security to add Google API key into source codes and put in the public.

**Comment by zur003** [comment]
You can thank Microsoft for this one. When using the embedded web browser on Windows, it defaults to emulating version 7 of IE. The Google Maps API no longer supports this version of the browser, and will give the script error that you are seeing. Fortunately, there is a workaround, which the ApsimX installer uses. It is possible to set values in the registry that instruct Windows to emulate a specific version of IE within a named application. Using the Regedit export format, the needed registry entries are as follows:

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION]
"ApsimNG.exe"=dword:00002af8
"ApsimNG.vshost.exe"=dword:00002af8

This instructs Windows to use IE 11 emulation (the value 0x00002af8 is 11000 in decimal notation) when the web browser is embedded within an application named either ApsimNG.exe or ApsimNG.vshost.exe (the latter being the name used when debugging under the IDE). 

Note that for "normal" uses, these values are written to the registry by the installer. If you've never run the installer, as may be the case with developers who build everything from source, those entries won't be present. You will need to add them manually.

You may be wondering why ApsimNG.exe itself doesn't just add the appropriate registry entry programmatically before invoking the embedded browser. This would be a better approach, but unfortunately writing those registry keys requires administrator privileges. The installer handles privilege elevation automatically, but it would be difficult (and probably undesirable) to do so within ApsimNG.exe, especially as some users may not even have the appropriate privileges.

Regarding the API key, the one currently being used is a generic, unrestricted key, and is being used as advised by Google for applications during development and testing (see https://developers.google.com/maps/documentation/javascript/get-api-key). To move beyond that would, I think, require that we set up an account with Google as a registered customer, and allow ourselves to be billed if the number of associated map downloads exceeds 25,000 within a day. I'm not convinced that we really need this (yet).

**Comment by byzheng** [comment]
@zur003 Thanks. It is working after I edit my registry. Instead of Google Map, we can use some alternative, e.g. leaflet and openlayer. The js library provides flexible of maps.

**Comment by byzheng** [comment]
Support browsers of leaflet  (http://leafletjs.com/) 


Browser Support

Desktop
Chrome
Firefox
Safari 5+
Opera 12+
IE 7–11

**Comment by zur003** [comment]
Mapping now uses leaflet, so this issue can probably be closed.
