### ISSUE TITLE
In PLANT calculate reallocation before retranslocation?

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2138]
@HamishBrownPFR In the nitrogen supply function, is it more logical to calculate reallocation before retranslocation? As `nitrogenSupply.Retranslocation` removes `nitrogenSupply.Reallocation` although there are no impact for current wheat model ( `senescenceRate` equals to zero).
 
https://github.com/APSIMInitiative/ApsimX/blob/871830c04d39f368ac450d33aa55237d54e2653f/Models/Plant/Organs/GenericOrgan.cs#L298-L304

**Comment by HamishBrownPFR** [comment]
Yep, this is intended.  The plant first uses material that would otherwise be lost to senescence, this includes non-structural material that would be in senesced material and may have been reallocated if the material were not going to senesce

**Comment by byzheng** [comment]
Hi @HamishBrownPFR Thanks for your explanation. I am more confusing now. I can understand your logic, but cannot understand the codes. 

The codes in the LeafCohort.cs are easily to follow. The NReallocationSupply is firstly calculated for senescence fraction, then NRetranslocationSupply is calculated through subtracting NReallocationSupply. 

Should we use the similar way in the GenericOrgan?

https://github.com/APSIMInitiative/ApsimX/blob/871830c04d39f368ac450d33aa55237d54e2653f/Models/Plant/Organs/LeafCohort.cs#L862-L871

**Comment by HamishBrownPFR** [comment]
I haven't had a chance to check this it detail but I suspect you are correct.  I don't think we have ever put senescence into a generic organ so have not checked these calculations carefully.

**Comment by byzheng** [comment]
Thanks. Agree with you. no senescence in the generic organ. But would be better to fix it.

Two more questions about the N supply for LeafCohort and GenericOrgan. This figure below is my current understanding of nitrogen in PMF. 

![image](https://user-images.githubusercontent.com/1657381/32462965-0b4af7f6-c387-11e7-94e7-2c63c9fd42a1.png)

Question 1: In the LeafCohort, the nitrogen retranslocation supply is calculated like this:
https://github.com/APSIMInitiative/ApsimX/blob/871830c04d39f368ac450d33aa55237d54e2653f/Models/Plant/Organs/LeafCohort.cs#L866-L869

Should it be corrected with this way? As LeafStartMetabolicNRetranslocationSupply  and LeafStartStorageNRetranslocationSupply  will be below zero if NRetranslocationFactor is much smaller than NReallocationFactor with codes above. 

```cs
LeafStartMetabolicNRetranslocationSupply   = liveBiomass.MetabolicN * (1 - SenescedFrac ) * NRetranslocationFactor 
LeafStartStorageNRetranslocationSupply   = liveBiomass.StorageN * (1 - SenescedFrac ) * NRetranslocationFactor 
```

Question 2: In the GenericOrgan, I don't understand why "limited to ensure Nconc does not go below MinimumNConc" in the Storage component. The minimum N concentration should be contained in the Structural component. 

https://github.com/APSIMInitiative/ApsimX/blob/871830c04d39f368ac450d33aa55237d54e2653f/Models/Plant/Organs/GenericOrgan.cs#L297

**Comment by HamishBrownPFR** [comment]
The correction you suggest to LeafCohort is sensible.

I am not certain why the labileN for generic organ is done like that but it does seem strange given allocation of N to structural should maintain min N conc.  Try changing it and see what happens.  There may be a reason for doing that but I don't recall.
