### ISSUE TITLE
Irrigation parameters could have default values settable outside Apply

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#2140]
The Apply method in Irrigation has one mandatory parameter (Amount) and several optional ones (depth = 0.0, efficiency = 1.0, willRunoff = false, duration = 1). This is simple and flexible in general, but it means that if any of the optional values were to change, they need to be given in the Apply command. This can make these a bit verbose (in case, for example, of a long list in a Schedulle where 'efficiency' is always 0.8), but also limits the ability to use a independent manager to change some of these (for example, to change the 'efficiency' once or twice during a simulation due to change in equipment).
A simple solution to this would be to add explicit default values for the optional parameters, and enable them to be set during the simulation, but not using the Apply method.

**Comment by rcichota** [comment]
Hi Dean, I was having a better look at the irrigation code and noticed that it doesn't have all the functionality (or bihaviour) of the model in Classic (I am of course ignoring the auto-irrigation bits, but the issue I raised here is one of the things it was possible and is not anymore) and there a couple of bugs. The bugs (or "bugs") are:
- The IrrigationApplied value (output) is not multiplied by Efficiency, though the Efficiency value is used for the actual amount irrigated (change in the soil). I think this may create a problem in the future. In Classic there were two variables (irrigation_applied, with actual value, and irrigation_tot, without considering Efficiency). I intend to do the same in ApsimX, or there is any reason to do it different?
- The Duration has units of 'hours' and a default value of one. In Classic the duration was one day, which should be used here too. Currently this value is not really used (SWIM requires it), but it will hopefully soon. I can correct that, but what is the time unit I should use (in classic it was minutes)?
- The behaviour I am concerned with is that in the past there were default values for the "Apply" parameters (Duration, Depth, Efficiency), this could be overwritten but only for one event, reverting after that, now if the user changes any parameter in one Apply event, that value is valid for any subsequent event. I favour the old way, which implies adding those variable in the code. But I want to check with you if this is OK?  @hol353

**Comment by hol353** [comment]
I'm happy to go with all your suggestions above and make the irrigation model work like APSIM Classic. Less confusion for users migrating to APSIMX. 

Use the same unit and default for duration as in Classic.

I also favour the old way where the arguments to Apply didn't 'stick' but reverted in the same way as Classic.

**Comment by HamishBrownPFR** [comment]
Hi @rcichota.  WEIRDO uses the irrigation duration and currently expects a value of hours.
