### ISSUE TITLE
Root nitrogen contents and concentration

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2148]
In the wheat model, the minimum and maximum nitrogen concentrations of root are set as 0.01 during whole season. So I should expect the nitrogen concentration keeps constant. However, the root nitrogen concentrations increase from 0.01 at stage 3 to 0.0144 at stage 4  in the Live and Total pools (See figure below).

![image](https://user-images.githubusercontent.com/1657381/32592204-769795b2-c56e-11e7-8ca0-f12683ec064f.png)

**Comment by ric394** [comment]
This very old. Closing. If this is still an issue, please feel free to comment.
