### ISSUE TITLE
Implement a new testing strategy for ApsimX

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#215]
The current test suite is slow and is external to ApsimX (i.e. it uses R and runs on Jenkins).
What is needed is for the model developer to easily run the tests in the user interface.

DESCRIPTION
The plan is for ApsimX 'models' to test themselves. To this end a ITestable interface has been created with a single Test method:

        /// <summary>Run tests. Should throw an exception if the test fails.</summary>
        void Test();

Any model in ApsimX can choose to implement this method and write test code. Then every time the user performs a run, the infrastructure (Simulations.cs) will find all models that implement the ITestable interface, call the method in each and report any errors to the user interface message pane at the bottom of the screen.

As a first step, the Regression model (under Graph Series) calculates predicted / observed stats that can be tested against a known baseline. The plan is for Regression.cs to implement the ITestable interface and compare the current regression stats against the known good ones. Perhaps the baseline stats should be stored in the .apsimx file so that we don't need to commit any .db files to GIT.

The regression model can then display the current and baseline stats in it's View and provide a button for accepting the current stats as the new baseline stats (see image below). If this approach works, then we can do the same for TimeSeriesStats. Perhaps we also need a new 'model' to be created that can compare a column in the table against a known good set of column values.

![image](https://cloud.githubusercontent.com/assets/1943827/8791334/b459d5aa-2f9c-11e5-95f6-d5a002674a07.png)

**Comment by hol353** [comment]
This will get around issue #183

**Comment by HamishBrownPFR** [comment]
As part of this we need a concerted to make sure tests are set up for all the models in the build.  I have just made some changes to some core PMF functionality (RUE) model.  It ran clean on Jenkens but there are a number of PMF models in prototypes that don't have tests in them so I am unsure if they have changed or not.

**Comment by HamishBrownPFR** [comment]
This could be closed now?
