### ISSUE TITLE
Can we export csv/txt file using models.exe?

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2152]
In the previous version, model.exe can directly export a csv file. It seems the current version only store the db file.

I prefer to directly export a csv/txt file as I am using condor and R to run models.exe. There are too many depended R packages if I need to use RSQLite to read db file. 

Do I miss anything here?

**Comment by hol430** [comment]
@byzheng @hol353  What sort of syntax would we want to use for this? 
Do we want some sort of unix-style option, such as:

````Models.exe -x "data.csv" "myfile.apsimx"````

Or did you have something else in mind?

**Comment by byzheng** [comment]
@hol430  I prefer to to use unix-style as you suggested.

**Comment by byzheng** [comment]
@hol430 It seems this feature is not working as expected.

**Comment by hol430** [comment]
What about this feature is not working? Is the .csv file not being generated? Are the results in the .csv file incorrect? Is the simulation not finishing correctly? Has this always been broken, or has it broken recently?

**Comment by zur003** [comment]
Maybe it's a documentation problem? Looking at the patch, it appears the command line syntax to invoke the feature is /csv, not the -x discussed above.

**Comment by byzheng** [comment]
@zur003 Yes I am trying to use -x "filename" to generate a csv file. @hol430 Sorry I should look carefully the help commands of models.exe.

**Comment by byzheng** [comment]
It might be helpful to update the help information of Models.exe with more explanation of arguments. It is confusing for information start with `System.Exception:`.

**Comment by hol430** [comment]
Ok - I probably should have added a comment here when I made the pull request to say I didn't end up going with that syntax.

**Comment by hol430** [comment]
> It might be helpful to update the help information of Models.exe with more explanation of arguments. It is confusing for information start with System.Exception:.

Yes, that's a good suggestion - it does obscure the actual help info a bit. I will create a separate issue for this.
