### ISSUE TITLE
Simulations with multiple zones not working

### ISSUE THREAD

**Issue by josharp22** [APSIMInitiative/ApsimX#2195]
@hol353 
Hi Dean
I have reduced the number of zones (to around 200) in a simulation file. It takes 36 mins to run and the Data Base file does not save properly/is irretrievable. It used to run with about 600-800 zones and outputs would save. Here is the example simulation: https://github.com/PlantandFoodResearch/MVI-FarmModelling/blob/master/Study_Farms/1RitchieOtane/Sim1%20(2).apsimx
@HamishBrownPFR suggested there may be a communication issue?
Cheers
Jo

**Comment by josharp22** [comment]
@hol353 @HamishBrownPFR 
Hi Dean
Further to that, if I run the same simulation (200ish zones) without a crop model, i.e. fallow not maize, it takes about 2 mins and the outputs are saved and can be queried. 
Cheers
Jo

**Comment by hol430** [comment]
@josharp22 Is this issue solved now that APSIM has been moved to 64-bit? If so this issue should be closed.
