### ISSUE TITLE
UI crahses if you click on a graph while simulations are running

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2209]

**Comment by zur003** [comment]
I haven't been able to reproduce this (though I haven't tried all that many options). Can you give a little more detail about how to trigger the problem?

**Comment by hol430** [comment]
I've been able to reproduce this by running the wheat example and quickly attempting to open the combined results folder. I get an unhandled AccessViolationException, which I'm guessing is what Hamish was getting as well.

**Comment by AllanPeake** [comment]
+1 ....this also happens when I run a simulation from one folder, then I go to click on another folder of sims to try and do something else. Occurring in the Oats versions I'm working in.

**Comment by HamishBrownPFR** [comment]
This still occurs although I haven't been able to work out exactly what combination of events cause it.   Sometimes you can click about all the graphs and it doesn't crash.  Other times it does.
