### ISSUE TITLE
UI report some notion of progress

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#221]
I am currently running a big experiment with 1000 simulations and I have no idea how many are completed nor how long it will take to finish (so I have some time to log issues).  Would be useful to have a progress bar or a count of completed simulations to show how far through big runs are.

**Comment by zur003** [comment]
Should be possible. I'm thinking one possibility might be to create a "SimulationsPresenter" that normally has nothing visible, but displays a progress bar (or bars; possibly one for each active job and an overall one?) when the simulations are running.

**Comment by hol353** [comment]
What about a simple progress bar down the bottom in the status bar. On the right?

**Comment by zur003** [comment]
Is there a way to re-open an issue after it has been closed? The commit for fixing this has a bug which is causing single-simulation runs to crash the GUI.

**Comment by hol353** [comment]
Eric, always open a new issue. Don't reopen this one.
