### ISSUE TITLE
Fail to enter the debug mode and build the user interface

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#2230]
Hi there: 
I encountered a problem that I can succeed in build the solution, but fail to enter the debug mode and build the user interface.  I have tried just to use the source code just pull from the Master. Here is the error message, I do not know whether anybody has met the same issues before or not. 
build is success:
========== Build: 6 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
debug (F5) failed:
Exception thrown: 'System.Exception' in Models.exe
The program '[7700] Models.exe' has exited with code 1 (0x1).

'Models.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Models.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\ApsimX\Bin\Models.exe'. Symbols loaded.
'Models.exe' (CLR v4.0.30319: Models.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Models.exe' (CLR v4.0.30319: Models.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Models.exe' (CLR v4.0.30319: Models.exe): Loaded 'C:\ApsimX\Bin\APSIM.Shared.dll'. Symbols loaded.

visual studio version:
Microsoft Visual Studio Community 2017 
Version 15.5.3
VisualStudio.15.Release/15.5.3+27130.2020
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA457
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA457
Microsoft Visual C# 2017

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Thanks very much in advance. 
yours junqi

**Comment by junqi108** [comment]
thanks very much, Eric. I will have a try.

**Comment by junqi108** [comment]
I have copied all the contents of DeploymentSupport\Windows\Bin into ApsimX\Bin and copied the libwimp.dll into ApsimX\lib\gtk-2.0\2.10.0\engines\libwimp.dll. however, this did not solve the issue. 
The error seems from the Main method where returned args length is zero. Maybe to do with the address, but it was OK 1 month ago. 

  public static int Main(string[] args)
        {
            string tempFolder = Path.Combine(Path.GetTempPath(), "ApsimX");
            Directory.CreateDirectory(tempFolder);
            Environment.SetEnvironmentVariable("TMP", tempFolder, EnvironmentVariableTarget.Process);
            AppDomain.CurrentDomain.AssemblyResolve += new ResolveEventHandler(Manager.ResolveManagerAssembliesEventHandler);

            int exitCode = 0;
            try
            {
                string fileName = null;

                // Extract file name from command line arguments.
                if (args.Length >= 1)
                    fileName = args[0];

                if (args.Length < 1 || args.Length > 4)
                    throw new Exception("Usage: ApsimX ApsimXFileSpec [/Recurse] [/SingleThreaded] [/RunTests]");

**Comment by junqi108** [comment]
Hi I have tried to delete all the local files and branch, and re-pulled the Apsimx and Apsim.shared repository from the Master. However, I could not build the solution anymore. See the following errors. I do not know what I did wrong. 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\APSIM.Shared\bin\Debug\APSIM.Shared.dll' could not be found	Models	C:\ApsimX\Models\CSC	1	Active
Error	CS0006	Metadata file 'C:\APSIM.Shared\bin\Debug\APSIM.Shared.dll' could not be found	Importer	C:\ApsimX\Models\Importer\CSC	1	Active
Error	CS0006	Metadata file 'C:\ApsimX\Bin\Models.exe' could not be found	Importer	C:\ApsimX\Models\Importer\CSC	1	Active
Error	CS0006	Metadata file 'C:\APSIM.Shared\bin\Debug\APSIM.Shared.dll' could not be found	ApsimNG	C:\ApsimX\ApsimNG\CSC	1	Active
Error	CS0006	Metadata file 'C:\ApsimX\Models\Bin\Importer.exe' could not be found	ApsimNG	C:\ApsimX\ApsimNG\CSC	1	Active
Error	CS0006	Metadata file 'C:\ApsimX\Bin\Models.exe' could not be found	ApsimNG	C:\ApsimX\ApsimNG\CSC	1	Active
Error	CS0006	Metadata file 'C:\APSIM.Shared\bin\Debug\APSIM.Shared.dll' could not be found	SWIMFrame	C:\ApsimX\SWIMFrame\CSC	1	Active
Error	CS0006	Metadata file 'C:\APSIM.Shared\bin\Debug\APSIM.Shared.dll' could not be found	APSIMRunner	C:\ApsimX\APSIMRunner\CSC	1	Active
Error	CS0006	Metadata file 'C:\ApsimX\Bin\Models.exe' could not be found	APSIMRunner	C:\ApsimX\APSIMRunner\CSC	1	Active
Error	CS0006	Metadata file 'C:\APSIM.Shared\bin\Debug\APSIM.Shared.dll' could not be found	UnitTests	C:\ApsimX\Tests\UnitTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\ApsimX\Bin\ApsimNG.exe' could not be found	UnitTests	C:\ApsimX\Tests\UnitTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\ApsimX\Models\Bin\Importer.exe' could not be found	UnitTests	C:\ApsimX\Tests\UnitTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\ApsimX\Bin\Models.exe' could not be found	UnitTests	C:\ApsimX\Tests\UnitTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\ApsimX\Bin\SWIMFrame.exe' could not be found	UnitTests	C:\ApsimX\Tests\UnitTests\CSC	1	Active
Error	CS0246	The type or namespace name 'DocumentFormat' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	17	Active
Error	CS0246	The type or namespace name 'DocumentFormat' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	18	Active
Error	CS0246	The type or namespace name 'Excel' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	20	Active
Error	CS0246	The type or namespace name 'SpreadsheetDocument' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	46	Active
Error	CS0103	The name 'SpreadsheetDocument' does not exist in the current context	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	46	Active
Error	CS0246	The type or namespace name 'Sheets' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	48	Active
Error	CS0246	The type or namespace name 'Sheet' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	49	Active
Error	CS1579	foreach statement cannot operate on variables of type 'Sheets' because 'Sheets' does not contain a public definition for 'GetEnumerator'	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	49	Active
Error	CS0246	The type or namespace name 'IExcelDataReader' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	78	Active
Error	CS0103	The name 'ExcelReaderFactory' does not exist in the current context	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	78	Active
Warning		Could not resolve this reference. Could not locate the assembly "DocumentFormat.OpenXml, Version=2.5.5631.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	APSIM.Shared

**Comment by junqi108** [comment]
Has made some progress in fixed the errors by moving the installed files into the source code. However, still has problems with the ExcelUtilities.cs. Any suggestion on how to fix this? Thanks very much in advance. junqi 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'DocumentFormat' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	17	Active
Error	CS0246	The type or namespace name 'DocumentFormat' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	18	Active
Error	CS0246	The type or namespace name 'Excel' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	20	Active
Error	CS0246	The type or namespace name 'SpreadsheetDocument' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	46	Active
Error	CS0103	The name 'SpreadsheetDocument' does not exist in the current context	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	46	Active
Error	CS0246	The type or namespace name 'Sheets' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	48	Active
Error	CS0246	The type or namespace name 'Sheet' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	49	Active
Error	CS1579	foreach statement cannot operate on variables of type 'Sheets' because 'Sheets' does not contain a public definition for 'GetEnumerator'	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	49	Active
Error	CS0246	The type or namespace name 'IExcelDataReader' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	78	Active
Error	CS0103	The name 'ExcelReaderFactory' does not exist in the current context	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	78	Active

**Comment by junqi108** [comment]
I have installed ExcelDataReader and ExcelDataReader.DataSet, but why still can not find the IExcelDataReader. Can anyone give some suggestion on this?

Error	CS0246	The type or namespace name 'IExcelDataReader' could not be found (are you missing a using directive or an assembly reference?)	APSIM.Shared	C:\APSIM.Shared\Utilities\ExcelUtilities.cs	81	Active

 IExcelDataReader excelReader = ExcelReaderFactory.CreateOpenXmlReader(stream);

**Comment by junqi108** [comment]
Seems change using excel into using excelReader works. but still has problems with Model.vshost.exe.

**Comment by junqi108** [comment]
solved. Few files need to be move around, and need to set the ApsimNG as the default compile file.

**Comment by HamishBrownPFR** [comment]
Hi @junqi108 

There is an issue set up to cover the development of the grape vine model, #1822.  Use it for your pull requests that relate to its development.  It will stay open until the reference panel have approved the model for release.  This issue should be closed now if it is solved.
