### ISSUE TITLE
Refactor soil class

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#2245]
In Soil.cs, everytime a model calls any of the properties e.g. LL15, DUL, SAT, the property is checked to see if the layer structure is correct and maps the variable into the correct layer structure if necessary. This means that properties are duplicated. Currently there is a LL15 in Soil.cs (which provides mapped values) and there is an LL15 in SoilWater.cs. I don't like this duplication.

Instead, a better approach would be to have code somewhere (soil.cs?) to map all variables at the start of the simulation. That means that models can call LL15 in SoilWater.cs and expect to get the correct mapped versions.

**Comment by hol353** [comment]
This refactor effort has now broadened to a general refactor the soil.cs and it's child models.
![image](https://user-images.githubusercontent.com/1943827/63064344-025f6b80-bf44-11e9-8651-47bdeb09855b.png)
The left hand side is the input side, the view that the user sees in the GUI. We are suggesting to rename child nodes of soil as per image and move properties from sample into other nodes eg NO3 and NH4 goes into a 'Chemistry' node. We want to migrate to having properties only specified in one place.  Variables on the input side are to be concentrations (ppm for nitrogen, volumetric for water variables)

The right hand side shows variables available during a model run. All child models except Initial will be removed from the simulation. All variables will be only available in one set of mass based units (kgha for nitrogen, mm for water). A unit specification functionality will be available in REPORT to convert units for output. All variables will be on a standard layer structure.

**Comment by zur003** [comment]
At the moment, particle size distribution (which I happen to need for G-Range) falls under "Analysis", but it doesn't seem appropriate to move that to "Chemistry". Where will these values be placed?

I suppose there's a distinction between values that will routinely change during the course of a simulation (water, C, N, and other elements), and relatively "fixed" properties like DUL and LL15, but even these latter could change in the context of an erosion or pedogenesis model.

**Comment by hol353** [comment]
Particle size numbers will probably stay under Analysis / Chemistry. Perhaps we need a better name.

We are still debating what goes in Initial. Perhaps all variables, even ones that normally don't change e.g. LL15.

**Comment by rcichota** [comment]
I think it will be great to have soil properties and initial status clearly defined and separated from model specific parameters, a question I have is whether both will be under the soil node or the soil will only contain properties+initial status and models will be outside. My interpretion of Dean's comments above is that models only will not even appear in the GUI. If that is right, how will we deal with choices like SoilNitrogen versus SoilNutrient or SoilWater versus SWIM? and their specific parameters?

**Comment by rcichota** [comment]
I'm also concerned with, and want to better understand, how the changes in mapping properties to layers will affect the capability to change soil properties and parameters, including the layer structure during simulations. This is an important issue when describing process like erosion, as pointed by @zur003, and for our attempts to simulate soil compaction and tillage (the aspects that change soil physics). I agree that having multiple copies is not good, but I would like to keep/enhance Apsim's capability to dynamic change soil properties.

**Comment by rcichota** [comment]
My suggestion for organizing the soil data:
 >Home node:
     - Soil name, location, etc, also maybe slope, CurveNumber, etc.
 + PhysicalProperties:
     - Layers, texture, rocks, hydraulic properties, bulk density, particle density, etc.
 + ChemicalProperties:
     - Layers, CEC, pH, Al, etc;
 + OrganicMatter:
     - Layers, OC, CN, FOM, FInert, etc;
 + InitialStatus:
     - Layers, NO3, NH4, SW, Temperature(?), etc;

I'd suggest adding particle density as an input property by layer (this could have the default value of 2.65, but the user should be able to add values if available - this is a source of many 'annoying' warning massages as often our values here in NZ are higher than the default. Still it is good to have the messages, so to capture truly spurious values).
I also suggest renaming 'root' to FOM, or explicitly FreshOrganicMatter, in the OrganicMatter node. The term root is misleading as it generally represents only dead root as well as surface residues that were incorporated via tillage, etc...

**Comment by hol353** [comment]
- Models will still be under a soil - nothing changed there.
- Mapping of layers to different layer structures remains unchanged. It just happens once rather than on the fly.
- I like the name 'PhysicalProperties' instead of Hydro. Perhaps don't need the Properties suffix. I'll run it past Neil and Hamish.
- The idea is that during a simulation run, Initial will be created with all variables. Each of the variables will also be in one of the 'input' nodes under soil that the user interface reads/writes
- Yes it would be good to have some way of identifying the mandatory parameters.

**Comment by zur003** [comment]
For G-Range, I've been using data for soil particle size distribution (sand, silt, clay and rock). With a bit of re-factoring, I can probably get by with just clay, although only if I don't use the pedotransfer functions of G-Range itself. I think particle size distribution has sufficiently general utility (e.g., almost certainly needed in erosion models) that the full PSD spectrum should be retained.

**Comment by hol353** [comment]
Ok. I'll add sand and silt back.
