### ISSUE TITLE
We would like a way to generate .apsimx files for all experiments / factors from the GUI

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#2286]
This would be useful to send simulations to a cluster. This is from David J.

**Comment by dholzworth** [comment]
@hol353 How should this functionality be accessible? Via a right click from a simulation node?

**Comment by hol353** [comment]
Maybe right click on a "Simulations" model and it gives the option to "Generate .apsimx files". Right click on a "Folder" and it does the same for everything under a folder. Right click on an "Experiment" and it generates .apsimx files for just that Experiment.
