### ISSUE TITLE
Grid view could use a description panel

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#2298]
The panel for the property presenter/grid view would be more functional if it included a html panel in the lower section to contain some doco for people entering in property values.

**Comment by zur003** [comment]
Some of the recent modifications for CLEM now enable this sort of thing. If the Model being presented is given a Description attribute, a heading with the Model name and its description is placed above the grid. There's also provision for added a URI to obtain more information.
@hol353 - have you had a chance to look at this? If so, are you happy enough with the "look and feel" that we should start using it for models outside CLEM?

**Comment by hol353** [comment]
I think the look and feel is good. Yes we could start using these outside of CLEM.

**Comment by hol353** [comment]
I can't figure out how to make this work. Can someone enlighten me?

**Comment by hol430** [comment]
@hol353 we now have a description panel in the property presenter. Can this be closed?
