### ISSUE TITLE
Auto doc for wheat missing stuff

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2309]
For example, the Leaf description only has a few things and fits in a single page, there should be stack of stuff docummented in there.

**Comment by zur003** [comment]
Auto-documentation generally seems to be pretty broken at the moment. I was hoping to take a look at the problem described in issue #2261 for maize, but the PDF I'm producing only has two rather non-useful lines of text.

**Comment by hol353** [comment]
Fixed in #2385
