### ISSUE TITLE
impossible to display summary file

### ISSUE THREAD

**Issue by morelju** [APSIMInitiative/ApsimX#2318]
as for example with attached image:
![summary_file](https://user-images.githubusercontent.com/19703973/36385365-a767cac6-1592-11e8-8502-01004f477de4.jpg)

**Comment by zur003** [comment]
Could you also attach a copy of your .apsimx file?

**Comment by morelju** [comment]
Here is the .apsimx file and corresponding .met file.
[summary_file.zip](https://github.com/APSIMInitiative/ApsimX/files/1739509/summary_file.zip)

**Comment by zur003** [comment]
That's odd. It works fine for me, and the call where the error is thrown is intended to be independent of culture, so I don't know what could be going wrong. Can anyone else replicate the problem?
![image](https://user-images.githubusercontent.com/11879340/36459668-cdacae46-1708-11e8-946d-630ba4ad2773.png)

**Comment by hol430** [comment]
I don't get any issues either - it displays fine for me.

**Comment by hol353** [comment]
Same for me. Maybe it is fixed.

**Comment by zur003** [comment]
It could conceivably be a locale settings problem, although that shouldn't be happening.
@morelju - If you are still seeing this problem, are you using any "unusual" settings for language and/or numeric formatting?

**Comment by morelju** [comment]
I am using a Swedish computer, maybe this has something to do with the
error ? What kind of information would you need?

Le 21 févr. 2018 5:21 AM, "Eric Zurcher" <notifications@github.com> a
écrit :

It could conceivably be a locale settings problem, although that shouldn't
be happening.
@morelju <https://github.com/morelju> - If you are still seeing this
problem, are you using any "unusual" settings for language and/or numeric
formatting?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/APSIMInitiative/ApsimX/issues/2318#issuecomment-367209100>,
or mute the thread

**Comment by zur003** [comment]
Hmm. Hard to say. Could you perhaps attach the .db file generated when you run the simulation?

**Comment by morelju** [comment]
Here is the .db file.
I've been doing some tests with other simulations (the wheat example), and the summary file is correctly displayed...

[summary_file_db.zip](https://github.com/APSIMInitiative/ApsimX/files/1746957/summary_file_db.zip)

**Comment by zur003** [comment]
OK, I think I see the problem. It seems to be a combination of quirks in SQLite and .NET's support for Swedish. "NaN" values are, I think, stored by SQLite as strings, but the representation used by ,NET for NaN on Swedish systems is strange (see https://stackoverflow.com/questions/47082984/why-the-strange-representation-of-nan-in-sverige-swedish-clr-4-0). 
So that's where the problem lies. Now we need to find a way to fix it...
