### ISSUE TITLE
N data is not all showing up in Maize validation

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2336]
n = 6 for n variables

**Comment by hol430** [comment]
Looks like if there is a problem here, it's with the MaizeObservations.xlsx. The PredictedObserved table is matching on Maize.Phenology.CurrentStageName. If you look in the observed file, there are only 6 rows which have both a Maize.AboveGround.N and a Maize.Phenology.CurrentStageName. So I think apsim is actually doing the right thing here.

**Comment by ric394** [comment]
This very old. Closing. If this is still an issue, please feel free to comment.
