### ISSUE TITLE
Cannot run an individual simulation from an experiment

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2344]
Previously it has been possible to run an individual simulation, or multiple selected simulations, from the experiment view.  This is no longer possible.
We need to be able to select simulations and run that subset of simulations within an experiment.

**Comment by hol430** [comment]
Are you talking about running specific combinations of factors? Because if so, that should be possible. This setup ran only a single simulation:
![test](https://user-images.githubusercontent.com/36427516/36763058-1cf1d2d8-1c72-11e8-9f94-a67e7603899c.PNG)

You can enable/disable simulations via the enable/disable buttons on the right.

**Comment by hol430** [comment]
Also @hut104 is this the same issue as #1649?

**Comment by hol353** [comment]
I've closed issue #1649 - same. For this issue can we have the old behaviour i.e. right click on a simulation in the experiment view to get a  popup menu with "Run" on it.

**Comment by hol430** [comment]
By a simulation, do you mean one of the rows in the table that shows up when you click on an experiment node?

**Comment by hol353** [comment]
Yes, each row is a simulation that can be run.

**Comment by hol430** [comment]
Ok. Do you want anything else in the context menu apart from an option to run the simulation?

**Comment by hol353** [comment]
Just run will do for now.

**Comment by hol430** [comment]
Currently, the user is allowed to select multiple simulations at once (to make it easier to enable/disable simulations in bulk); should they be able to select several simulations, right click, select run, and have Apsim run all of the selected simulations?

They can already do this by enabling/disabling the simulations, and then running it via F5, but it might be nice to be able to do it all from the factor table.

**Comment by hol353** [comment]
Multi selection would be good. I know they can do it via enable/disable but this would be another, perhaps easier way if they just want to temporarily run some sims. 

By factor table I assume you mean experiment table.
