### ISSUE TITLE
Wheat Biomass Stats Include Many Zero Predicted Values

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2360]
The stats for wheat biomass say that RMSE is over 6t/ha.  This is because the PvsO stats include 0 predicted biomass for harvest dates because the crop biomass is removed prior to reporting.
The reporting for trials should be moved to the start of the day so that biomass,lai,even soil water, occurs before management such as harvesting or irrigation.

**Comment by hut104** [comment]
Note that the same issue is seen in the Barley model validation

**Comment by hol430** [comment]
This appears to be fixed.
