### ISSUE TITLE
Turn all functions into array functions. Needed for nutrient and soil modelling

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#2366]

**Comment by hol430** [comment]
What does this mean? Has it been implemented?

**Comment by hol353** [comment]
Currently IFunction returns a double (in the Value method). The thought was to have an IArrayFunction that returns an array of doubles instead. I tried doing this but had many problems with not being able to mix and match IFunction with IArrayFunction instances. In the end it was too hard. Closing...
