### ISSUE TITLE
Renaming of duplicate names is difficult

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2374]
If you accidentally have two simulations of the same name (e.g. copy folders of simulations) you cannot run any simulation in the file.  you can try to rename one of the duplicates to remove the problem, but the UI renames both and so you still have a problem.

**Comment by hol430** [comment]
@hut104 I'm having trouble reproducing this. Renaming simulations with identical names appears to work correctly for me when the simulations' apsim paths* are different. 

When their apsim paths are the same (which as far as I know is only possible if you open the apsimx file in a text editor), the first simulation (the one higher up in the tree structure) gets renamed. This is definitely a bug, but I'm not getting the same results as you (where it renames both). 

Do you have a sample apsimx file which exhibits this behaviour?

*By apsim path I mean the path of the simulation within the apsimx file structure - e.g. Simulations.Validation.Australia.CoffsHarbour.CoffsHarbour

**Comment by hol430** [comment]
Closing as fixed.
