### ISSUE TITLE
Clock View is difficult to use

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2394]
The view for clock allows the user to change the start and end date.  If the user selects a date, a pop-up calendar control is provided.  However, it is difficult to select a date even by clicking on it.  Furthermore, it may be easier for a user to enter the date directly via the keyboard, however the UI does not allow the user to easily enter a date as text.

**Comment by zur003** [comment]
Yes, I admit the Gtk Calendar widget isn't all that great to use.

The UI does allow the text to be edited as text, although getting there is a bit obscure. When you select a date for editing, you get a Gtk calendar dialog. If you close that dialog without making any changes to the date, the field will open for text editing. If you have made changes, those changes will simply be applied, and you won't go into text-editing mode.

**Comment by hol353** [comment]
Is it possible to have the cell remain editable, even after opening the calendar widget. This would allow users to either edit or use the calendar widget.

**Comment by hol430** [comment]
Should the cell be in 'edit mode' as soon as the calendar appears, or would you prefer to have the calendar take focus, with the ability to click on the cell to initiate a manual (keyboard) edit?

**Comment by hut104** [comment]
Personally, I would probably prefer edit mode on entry.  I find the calendar clunky for most uses as you need to change more than just the day of month.  You often need to change day, month and year, and so edit mode would be the fastest.
