### ISSUE TITLE
A generic grid to make the entry of data that is tabular easier

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2399]
Item from the CSIRO-AgResearch "StockInAPSIM" workshop in December 2017.

**Comment by hol353** [comment]
Hmmm. OK. Probably need a bit more info. We already have a generic grid that allows users to enter data in a tabular fashion.

**Comment by rcichota** [comment]
Maybe is the fact that the current grid is quite limited (no column selection for example)?

**Comment by hol430** [comment]
Several people have said that the ability to select an individual cell (or cells) without selecting the rest of the row would be useful. @sno036 is that what this issue refers to?
