### ISSUE TITLE
Add a "category" type item in Manager UI grid rows as a visual separator

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2401]
Item from the CSIRO-AgResearch "StockInAPSIM" workshop in December 2017.

**Comment by lie112** [comment]
CLEM development is currently adding categories and sub-categories to a wrapper for the property grid. This will allow large lists of properties to be grouped in a left hand tree (like explorer) that when clicked will display the filtered list of parameters. I'm not sure if this is what was required.

**Comment by hol353** [comment]
Should have said resolves in that last pull request.

**Comment by zur003** [comment]
I've got a couple of minor enhancements coming - perhaps will mark as resolved then.

**Comment by hol353** [comment]
There is a bug where the category text in

[Separator("some text")]

isn't being shown on the separator line. Instead it uses the description of the declaration immediately below the Separator attribute.
