### ISSUE TITLE
Misleading Gtk errors are appearing in build logs

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2405]
When Jenkins does a build, one of the steps in the Create Installation phase involves the creation of model documentation. Although the documentation is generated, an error is reported which looks like this:
 
(ApsimNG:4652): Gtk-CRITICAL **: gtk_main_quit: assertion 'main_loops != NULL' failed

This looks serious, although it really isn't. Still, it should be eliminated, as it is a distraction from real problems when they do occur.

**Comment by hol353** [comment]
We're also getting these 'errors' in the unit tests on jenkins.
