### ISSUE TITLE
root biomass only dies in plantzone but not in zone 2 

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#2408]
![image](https://user-images.githubusercontent.com/13222562/37010798-1a02629c-2152-11e8-9afb-27b33b8200ba.png)

root biomass only dies in plantzone but not in zone 2. the simulation was trying to make the root biomass decrease, either by water stress, maintenance respiration, and less partitioning. however, the root biomass in zone 2 does not be affected. 
this may be linked with DoRemoveBiomass remove function. 
/// <summary>Removes biomass from root layers when harvest, graze or cut events are called.</summary>
        /// <param name="biomassRemoveType">Name of event that triggered this biomass remove call.</param>
        /// <param name="removal">The fractions of biomass to remove</param>
        public void DoRemoveBiomass(string biomassRemoveType, OrganBiomassRemovalType removal)
        {
            biomassRemovalModel.RemoveBiomassToSoil(biomassRemoveType, removal, PlantZone.LayerLive, PlantZone.LayerDead, Removed, Detached);
        }

**Comment by ric394** [comment]
This very old. 
Closing. 
If this is still an issue, please feel free to comment.
