### ISSUE TITLE
Redesign Micromet Canopy Layers 

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2414]
Micromet is an important and powerful model in Next Gen.  However, it has the assumption that green and dead leaves are mixed within the canopy.  This causes issues with photosynthesis late in the season.  The layers are currently configured in Micromet - this should be done in the crop models.
Micromet could/should also be re-coded to keep track of LAI and LAIdead rather than LAI and LAI tot to make calculations simpler if live and dead canopy layers are established.
Finally, a bit of refactoring work will be required after more than a decade of maintenance of the model across 3 languages.

**Comment by ric394** [comment]
This very old. 
Closing. 
If this is still an issue, please feel free to comment.
