### ISSUE TITLE
Need to remove leaves from Leaf when defoliating

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2421]
Add removeNodeNumber argument into BiomassRemove type and make leaf use this to remove cohorts when defoliated

**Comment by HamishBrownPFR** [comment]
Not resolved by last pull request

**Comment by HamishBrownPFR** [comment]
There is a problem in the calculation of DeadLeafNo.  I have traced this back to some problem with apex number zeroing after defoliation.  Need to get my head around the intent of the apex code before I can finish this off.

**Comment by ric394** [comment]
This very old. 
Closing. 
If this is still an issue, please feel free to comment.
