### ISSUE TITLE
Simulations are saved even when user says don't

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#2461]
If a simulations is open (say from the Prototypes folder) and the user expand a few of the nodes, perhaps copies a manager spcript, etc. (no changes actually made to the simulation) then choses to close the simulation, a window will pop up asking whether to save any changes in the simulation. No matter what answer is given, any 'changes' will be saved.  These changes are basically inconsequent: the version of the xmlSchema (line 2) and few minors things like replacing tabs with spaces, but also incluse model parameters that have been added after the simualtion was initially saved (I noticed CarbonConcentration in plant organs recently).  This is not a bug per se, but it is annoying as it makes SourceTree see uncommitted changes when in reallity you only wanted to have a look at a given simulation...

**Comment by hol430** [comment]
When you tell Apsim to open a file, Apsim will read your file and 'update' it - which, as you said, is basically inconsequential - it changes the xml schema, swaps spaces for tabs, etc. This update is then saved to the file on disk.

On the other hand, if you open an example, Apsim will perform the update (to the deserialised simulations in memory) but will not save any changes to the file. So as a temporary measure, you could click 'Open an Example' and then navigate to the prototypes folder to open whatever it is that you don't want to modify. 

I do agree though that this behaviour is unexpected and not ideal. My suggestion is that we either:
 - Make it obvious somehow that the file will immediately be modified (perhaps via some sort of warning or tooltip). We could even ask for confirmation before opening a file located under the ApsimX directory, if the file would be modified.
or
 - Not save these changes (to disk) upon opening the file at all

@hol353 what is your preference here?

> No matter what answer is given, any 'changes' will be saved.

I have not been able to reproduce this - if I make any changes to a file (e.g. copying manager script as you suggested), then they do not get saved if I choose not to save the file.

**Comment by rcichota** [comment]
Thanks @hol430 
What I meant by "No matter what answer is given, any 'changes' will be saved". It what you discuss earlier. The 'updates' changes are saved even if the user says no (and I now see why this is, as explained by you). So ignere this bit.
I still think that the 'updates' should not be automatic as this is counter-intuitive...

**Comment by hol353** [comment]
This one is tricky. The .apsimx file will sometimes need to be converted to a new version (converter.cs does this). This isn't optional.

I suspect the real problem though is that by deserialising the .apsimx file to memory objects and then serialising back to XML when you click save (or exit) causes inconsequential changes that always triggers the 'file has changed - do you want to save' box. We could do a more sensible comparison of the XML to look for real changes but this would be very slow. Another, better, way would be to introduce a mechanism that keeps track of when something is changed by the user, perhaps by using the undo/redo mechanism. If there is a command in the undo/redo list then something has changed.

**Comment by hol430** [comment]
Part of the problem is that the user isn't given a choice - these inconsequential changes are saved to the file immmediately upon opening the file, without asking for confirmation (unless you clicked on 'open an example'). 

Is it feasible to simply keep the .apsimx files under examples, validation, etc. up to date?

**Comment by hol353** [comment]
Not feasible to keep examples/validation up to date. New file versions are added all the time.

The problem is that the converter is assumed to always change the file when often it doesn't. We should change the converter to report whether it did actually change the file and combine this with the undo/redo list to detect if a file needs to be saved.

**Comment by rcichota** [comment]
Why don't these chages are made in the main repository. Not when the user/developer opens it.
 I got across this issue when I open a simulation just to have a quick look at how it did sowing. I closed it and got the message asking whether I want to save, I said no, but of course it did (the updates). Then I had sourcetree saying there were changes on that sim file to be commited/pushed. 
So as these changes are inconsequential, why not do these updates during tests and in the main repo, so when we pull there will be no need to do any update

**Comment by hol353** [comment]
Because it will mean Jenkins will have to do a commit to update the examples/tests. I don't really want to do this. Better to fix the problem as I outline above and get the GUI to not ask about saving and NOT save inconsequential changes when they aren't needed.

**Comment by rcichota** [comment]
Yeah I realised that it would be cumbersome to have Jenkins doing it. It would also mean an increase in traffic when pulling, as there could be changes to a lot more files...
