### ISSUE TITLE
Very slow simulation completion

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2464]
APSIM is running simulations all right but seems to be sitting for a long time once all the simulations are complete before the complete message is written.  I presume it is dealing with the datastore in this time.

Currently I am running the LUDF2015_16 experiment in the New Zealand folder of the Barley validation.  It has 5 simulations which all run pretty quickly but then it hangs for 40-50 seconds before completing.

**Comment by HamishBrownPFR** [comment]
i am finding this behaviour is variable.  Small simulations it is not a problem but it seems worst for validation sets.  This problem seems to be most acute with the Oats.apsimx validation set in the prototypes.

**Comment by hut104** [comment]
I'm having a fair amount of trouble with this whilst trying to work on the Barley model validation.  I can run a small 3 simulation experiment in only a few seconds, but it then takes much longer to complete and return control back to me.

**Comment by HamishBrownPFR** [comment]
This issue seems to be resolved now
