### ISSUE TITLE
SurfaceOrganicMatter property Type should have a drop down list

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2467]
I think i am correct in say that the Type of surface OM entered on the SurfaceOrganicMatter model view has to correspond to a specified type.  Therefor there should be a dropdown list for this property allowing you to select from the types available
![image](https://user-images.githubusercontent.com/7295858/37436734-4d90f10c-284e-11e8-85ef-dc75c499af1a.png)

**Comment by hol430** [comment]
Is there a list somewhere of valid types for this property?

**Comment by zur003** [comment]
I think it ultimately comes out of the ResideTypes.xml, embedded as a resource in Models.exe. This is used to populate a ResidueTypes list within the SurfaceOrganicMatter model.
