### ISSUE TITLE
Map in doco not showing all points

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2470]
Can we fix the map so it shows NZ for the wheat doco.
![image](https://user-images.githubusercontent.com/7295858/37490410-746ef01a-28ff-11e8-985b-900951abbdcf.png)

**Comment by junqi108** [comment]
very nice feature that can site on maps^-^

**Comment by zur003** [comment]
At the moment, the maps created for documentation always have a size of 500 x 500 pixels. This, coupled with the fixed steps inherent in tiled mapping, means that a "world" map is going to have trouble showing the whole globe - either Alaska or New Zealand will be chopped off in a map like that shown above. We can't do much about the mapping steps, I think, but we could give the user some control over the dimensions of maps used in the documentation. We could probably provide a mechanism to allow the user to interactively resize their Apsim map window until they get the size they want, then save those dimensions and apply them during the generation of auto-documentation.

**Comment by zur003** [comment]
There are a number of other things connected with the maps that could be improved. The current Google maps display includes a "full screen" control, which is not very useful in our context. It should be removed. Street view is probably not very useful either. However, it may be useful to display the scale control, but that's currently not displayed.
