### ISSUE TITLE
Add version number to autodocumentation

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#2473]
Some users want to see the ApsimX version string in the auto-generated documentation.

**Comment by hol430** [comment]
@zur003 My ApsimX version number is currently 0.0.0.0 (although the build date is correct). Is this intentional?

**Comment by zur003** [comment]
Yes, it is. We can't really embed all the version information into the source we commit, as the date changes, and the build number portion comes from Github. The build procedure on Jenkins plugins in the version number for release builds. This can be a bit of a nuisance, but can also be a useful reminder that you're using a "home-brew" version, and not a released one.

**Comment by hol430** [comment]
Ok, that makes sense, thanks.
