### ISSUE TITLE
Slow drawing of view for simulations and "simulations" node

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2484]
It appears that the view for simulations, and the root node (ie"Simulations") now inserts the autodocumentation for the entire contents of these things.  This takes a significant amount of time and makes using the UI difficult at times.  Furthermore, it redraws this UI when you run a simulation or all simulations from the root node, thus increasing execution time.  Furthermore again, the text within it is not overly useful.  I am not sure it has been designed for this purpose.
Is there a reason why we are doing this?  Can this be turned off?  I'm not sure about the background to this.

**Comment by zur003** [comment]
This attempt to auto-document the root node is also causing problems with the Standard Toolbox. If you open it up and select the root Standard toolbox node, you get a NullReferenceException.

**Comment by hol430** [comment]
What is the intended behaviour here? Is there some other information that could be displayed instead of the autodocumentation?
