### ISSUE TITLE
Intellisence not working properly in report

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2490]
A number of child functions are not showing up.  For example below, if I type [Maize]. I would expect the Phenology class to be in the list but it is not.  If you remove the square brackets from around Maize intellisence works properly but the squares need to be there for the report to work
![image](https://user-images.githubusercontent.com/7295858/37693676-2f85e794-2d26-11e8-97b1-f207eccf56ce.png)

**Comment by hol430** [comment]
Interestingly, I appear to be getting the opposite results; If I type `[Maize].` I get the intellisense popup (which includes phenology):

![intellisense1](https://user-images.githubusercontent.com/36427516/37887160-978df8aa-3103-11e8-860d-96abed1ae164.PNG)

If I remove the square brackets and type Maize. I don't even get the intellisense popup - no auto completion suggestions are found.

Are you still observing the same results on the latest version of Apsim?

**Comment by HamishBrownPFR** [comment]
No, I am not seeing this problem on current master, I will close this issue
