### ISSUE TITLE
Maize Doco not up to date

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2496]
The Maize Doco at http://www.apsim.info/APSIM.Builds.Service/Builds.svc/GetDocumentationHTML is not the same as the Maize doco I get if I create documentation from the master on my own computer.  Specifically, I added a BBCH stage model to phenology which Dean merged in yesterday.   This shows up in the Doco I generate when I am on master (see image below) but is not in the online doco for maize accessed at the above address.

![image](https://user-images.githubusercontent.com/7295858/37790822-708ea806-2e6c-11e8-8041-31aea42b4267.png)

This is how it looks from the above url

![image](https://user-images.githubusercontent.com/7295858/37790865-8bf42b48-2e6c-11e8-8672-af194c0d82bc.png)

**Comment by hol430** [comment]
The current maize docs on the website seem to have this section. I suspect this may have been a symptom of #2478 - I had a pull request that was merged within a minute of your BBCH model pull request.

**Comment by HamishBrownPFR** [comment]
Thanks @hol430.  I have checked and can confirm the maize doco is now up to date.  Closing this issue
