### ISSUE TITLE
User interface crashes when grid columns are clicked

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2509]
In the most recent build (APSIM 2018.4.3.1775), clicking on the column header of a grid causes the application to crash and close. This seems to be true for all "grid" contexts.

**Comment by hol430** [comment]
I have tested a number of grids but have been unable to reproduce this. Is there a speicifc grid which doesn't work for you? Do you do anything in particular before clicking on the column header?

**Comment by zur003** [comment]
Try it with the shift key held down. I may have had caps-lock on earlier.
