### ISSUE TITLE
Command line usage message is hard to read

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#2528]
The actual message here is obscured a bit by the exception information which (in this case) we don't really need to see.

> System.Exception: Usage: ApsimX ApsimXFileSpec [/Recurse] [/SingleThreaded] [/RunTests] [/Csv]
 > at Models.Program.Main(String[] args) in C:\Users\hol430\Documents\ApsimX\Models\Main.cs:line 51

**Comment by byzheng** [comment]
Should we add a more argument `/h` or `/help` to show help information in details as most of windows application?

**Comment by hol430** [comment]
You can already access the help by just running Models.exe without providing any arguments.

That said, a help option might be useful for someone who has not run APSIM from the command line before. I believe `/?` is the convention on Windows.

**Comment by byzheng** [comment]
My ideas are 

using `Models.exe` to show 
 
      Usage: Models ApsimXFileSpec [/Recurse] [/SingleThreaded] [/RunTests] [/Csv]

using `Models.exe /?` to show 

     Usage: Models ApsimXFileSpec [/Recurse] [/SingleThreaded] [/RunTests] [/Csv]
     ApsimXFileSpec: The absolute and relative path to an apsimx file, ...
    /Recurse: ...
    /SingleThreaded: ...
    /RunTests: ...
    /Csv: Export all reports into csv files.

    Example: ...

Can add more description information for each argument.
