### ISSUE TITLE
SCUM reference problem

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#256]
I was about to post a message entitled SPAM problem but I thought that might be filtered to junk so decided to change the name of SPAM (formerly MCSP) to SCUM (Simple Crop Uptake Model).

Anyway.  I am trying to reorder the model to get the docummentation and am having a problem with the model not finding a variable reference.  It is the variable references highlighted below referencing the sigmoid functions also highlighted below.  For some reason the expression evaluator can't find functions that are present under [Stover].  If I point these references at any other function in [Stover] the evaluator can't find them.  If I move them up the the same level as [Stover] it finds them fine.  The variable references in Stover to functions in other classes (e.g Product, Root or Phenology) are working, References in other classes to functions in Stover are working and references in other classes to functions within the same class are working.  It is just references to functions from stover to other functions within stover that arn't working.

Any ideas.  

pull https://github.com/PlantandFoodResearch/ApsimX/tree/MCSP_%23166 and run 
https://github.com/PlantandFoodResearch/ApsimX/blob/MCSP_%23166/Prototypes/MCSP/MCSP.apsimx if you want to debug 

![image](https://cloud.githubusercontent.com/assets/7295858/9373780/5bdb83b6-4742-11e5-8cb8-834457dc9d6f.png)

**Comment by HamishBrownPFR** [comment]
Just realized the that the screen shot and branch reference have the sigmoid functions at the plant level so it is working.  I want to move these functions into Stover but the expression evaluator can't find them if I do.  Yes I did change the address in the variable reference function so it was looking for them in Stover.

**Comment by HamishBrownPFR** [comment]
I think it is a problem with the sigmoid function as when I replace the variable reference with the sigmoid function it is referencing it throws an error

**Comment by HamishBrownPFR** [comment]
No, I take that back.  It is a variable reference inside the sigmoid function that is causing the error, same error as the other, can't find the function being referenced.  there is something going wrong the variable references inside [Stover]

**Comment by hol353** [comment]
I can't seem to reproduce any error message. The simulation 'SCUMTestBase' runs fine. In the debugger the BiomassAtMaturity is returning a value when variable name is 'TotalBiomassAtMaturity'.

What am I doing wrong?

**Comment by HamishBrownPFR** [comment]
I suspect the version you are working with is one where I have moved the sigmoid functions back up to the plant level to get it working.  If so move them into the Stover organ and see if you can get the references to work.

**Comment by hol353** [comment]
I moved TotalBiomassAtStartReproductive sigmoid function from top level Plant into Stover (SimpleLeaf). I left the variable references alone ([TotalBiomassAtStartReproductive].Value). The simulation still ran without error. The debugger reported values of 143.xxx

Still can't reproduce the problem.

**Comment by HamishBrownPFR** [comment]
But that shouldn't work should it?  I thought the class in the square brackets as a top level class so if the function class we want to reference is in leaf is should be [Stover].TotalBiomassAtStartReproductive.Value

That is how I have done it on all the other organs and it works.  (See below).  Is the pattern different on a leaf organ for some reason?

![image](https://cloud.githubusercontent.com/assets/7295858/9397732/ccc00708-47f3-11e5-963f-14feb34186cc.png)

**Comment by HamishBrownPFR** [comment]
if you use [Stover].TotalBiomassAtStartReproductive.Value as the reference do you get an error

**Comment by hol353** [comment]
You have more than one Stover in your SCUM file. There is a Subtract function called Stover. It is finding this.

The square brackets tells the engine to look for that type that is in scope. Scoping rules here:
https://www.apsim.info/Documentation/ApsimX/Design/ModelFramework/Modelscope.aspx

**Comment by HamishBrownPFR** [comment]
Ok got it.  The variable references where inside a function called Stover that was on the Stover organ so the find didn't get back up to the top level before it found a Stover function to start looking in.

Thanks for your help with this.

Hamish
