### ISSUE TITLE
Usability request - add a button to go to the start of the simulation log in the summary file viewer

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2563]
It can take a while to find the start of the simulation log after all the initialization information dump.  Would it be feasible to add a button to get to the start of the log part?  Or land the user there as a default would be even better.

**Comment by zur003** [comment]
That would be feasible. The summary file is HTML, so we could assign an ID to the start of the log section, and set up a link to that.

**Comment by sno036** [comment]
Beautiful thanks!
