### ISSUE TITLE
Please add Automatic Irrigation

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#2564]
This functionality is required for APSIM NextGen.

Functionality should be similar to that of old APSIM but should be specifiable for user-selected number of soil layers, and relate to the fraction of PAW compared to PAWC over the specified depth layers. PAW should be derived from CLL, not LL15. Fraction is also user specified.

'Allocation' should be retained as a maximum amount of mm water added, for a given cropping season.

'Efficiency' should be retained - user specified, and related to allocation such that unapplied water (lost through inefficiency) is removed from the 'allocation' limit.

A growth stage turn-on/shut-off function should be added so that users can limit auto-irrigation to specified zadok-stage ranges and prevent irrigation after harvest (or at unrealistically early stages) in multi-year simulations.

**Comment by zur003** [comment]
This was the same as #2609, which has been closed. Now closing this as well.
