### ISSUE TITLE
Can drop-down lists in grids be improved?

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2567]
I recently made a change to have the allowable residue types appear in a drop-down list when editing SurfaceOrganicMatter properties. While this "works", the Gtk CellRendererCombo that is begin used has some limitiations. For example, it does not allow the user to "search" for an entry by typing in the beginning letters. This means a lot of manual scrolling when the user wants to switch between "barley" and "wheat". Also, once the associated Combo box has been opened, the user must use the mouse to move away from it, as key strokes aren't being handled. 
The "search" problem is a Gtk issue, as its ComboBoxes don't offer this capability. We could try using Gtk EntryCompletion objects, but I think this would potentially allow the user to enter invalid values. I don't really know what the best solution would be.

**Comment by hol430** [comment]
Yeah, another problem with the grid drop downs is that it's not obvious which cells contain drop downs and which contain regular text inputs (as Hamish pointed out in #2491). As far as I know, the drop down doesn't become visible until the cell goes into 'edit mode', and even then, the user has to click again to expand the drop down, which is not really the behaviour that we want at all. 

Perhaps the answer is to use another widget - or to create our own which does the job.

**Comment by hol430** [comment]
This is fixed by the new property UI, which doesn't use a gridview.
