### ISSUE TITLE
Stock.  Problem with buying lactating cows without calves

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2591]
@her123 
If I buy cows that are lactating and with 0 young specified, they nevertheless arrive with a calf at foot but .. those calves cannot then be weaned (the instruction is ignored (at least if it is on the same day they are bought) and then the cows cannot be dried off.  

If I buy cows in late pregnancy I can wean the calves and then dry off the cows.

**Comment by her123** [comment]
Currently the stock component assumes that if cows are lactating or pregnant they will have at least one young/foetus. However they can be weaned on the same day they are bought and then calves sold.

**Comment by sno036** [comment]
@her123  - should we close this?

**Comment by her123** [comment]
I think so.
