### ISSUE TITLE
SurfaceOrganicMatter needs to implement IRemovableBiomass

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2596]
So that it can be consumed by Stock

**Comment by hol353** [comment]
I have changed SurfaceOrganicMatter to implement IRemovableBiomass. However stock requires some changes. It is currently looking for models that implement IPlant when it should probably look for models that implement IRemovableBiomass. I will leave this change to @her123.

**Comment by sno036** [comment]
Done already
