### ISSUE TITLE
Stock needs improvement to be aware of (i.e. calculate) non-grazable DM

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2597]
Used to be a feature of the pasture model in AusFarm and now needs some sort of implementation in Stock.  Be aware that no grazable will be different by animal type (sheep v cows).  
@her123

**Comment by sno036** [comment]
Circulate to Di M. and Val Snow for comment before implementation.

**Comment by her123** [comment]
Non grazeable pasture < 400kg/ha is now implemented in Stock. Still need implement the height ratio consideration.

**Comment by her123** [comment]
AgPasture still requires investigation as it seems to throw an error when too much biomass is removed.

**Comment by rcichota** [comment]
Just poking in, beware of what type of biomass, or what organs, you're using to compute what can be grazed. It is tempting to use AboveGround biomass, but some parts (e.g. stolons in clover) cannot be grazed (or only a small fraction of it can be)
