### ISSUE TITLE
There is no way to rewind phenology when plants at or beyond the leafappearancephase phase

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2599]
Needed to have crops respond to grazing.  Is already sorted for all other phases.

**Comment by HamishBrownPFR** [comment]
It makes no sense from a physiology point of view to rewind phenology in a leaf appearance phase.  By this stage the crop is comitted to reproductive development and there is no rewinding of that.  It is possible leaf removal will slow development

**Comment by HamishBrownPFR** [comment]
I am making these comments from a annual crop perspective, it would be different for perennial plants where removal of reproductive stems puts the crop back to vegetative in which case a leaf appearance phase (as it is currently written) is not appropriate for a perennial crop.
