### ISSUE TITLE
Manager component in one paddock is affecting all paddocks

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2603]
Dean has an example that he will attach

**Comment by hol353** [comment]
I first noticed it in the attached .apsimx file. I put manager logic in paddock 2 sowing rule to rewind phenology and nothing happened. I moved the script to paddock 1 sowing rule and it worked. Not sure what caused it but has serious consequences if it is a bug.

[grazing_wheat(9.5.18).zip](https://github.com/APSIMInitiative/ApsimX/files/1993928/grazing_wheat.9.5.18.zip)

**Comment by hol353** [comment]
OK I finally, partially, worked out the problem. We are breaking .NET naming rules with our manager scripts. All our manager scripts are class Script in the Models namespace. This is OK until we do a clone (binary serialise/deserialise). When this happens, the serialisation engine seems to choose the first assembly it can find that has the 'right' code. It seems that if the script c# is close to an existing assembly then it chooses that assembly. In the attached .apsimx, it chooses the wrong temporary assembly for SowingRule2. It chooses SowingRule assembly even though the script for the 2 manager files is different. I'm not sure how to fix this yet. A brute force way is to recompile all manager scripts after cloning.
