### ISSUE TITLE
Infinite loop in DoApexCalculations

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#2612]
There is a For loop which reduces the value of apex number in Leaf.cs (whenever this value has been reduced in Structure). The apex number is trecked in Leaf as a list (**apexGroupSize**); the problem seem to be that the loop ignores the first item of taht list, so when trying to reduce the value and only the first item contains something, then the loop is never exited...

**Comment by junqi108** [comment]
I trapped in this loop before ^-^
