### ISSUE TITLE
Upgrade functionality is broken

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#2629]
Upgrade functionality appears to be broken on Windows builds. Attempts to write to the registration database return a HTTP 404 not found error code. This causes the upgrade operation to be aborted.

**Comment by zur003** [comment]
Even worse on Ubuntu Linux. Kills the application.

**Comment by zur003** [comment]
This appears to be related to the switch from http to https about a month ago. I find that using http to call the Registration service appears to still work OK, but using https fails with the 404 error. I haven't looked into this too thoroughly, but https://serverfault.com/questions/776390/iis-7-wcf-webservices-giving-404-error-over-https suggests that it may be a problem with web.config on the service. Could someone with access to www.apsim.info look into this?

**Comment by hol430** [comment]
Upgrading is now working once again, but I would like to fix the crash on Linux. Seems to occur when we try to display the error message dialog. I will look into it when I get the chance.

**Comment by hol430** [comment]
Closing now, as this should be fixed by #3007

**Comment by hol430** [comment]
Opening, as this seems to be broken again. A bug in the HTMLView causes this to fail, as the license can't be displayed.
