### ISSUE TITLE
Not easy to change initial water content in the GUI

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2644]
It is hard to change the initial water content in the InitialWater node. The second input cannot be changed or jump to another values. The first input has to be changed using the arrows in the right.

![image](https://user-images.githubusercontent.com/1657381/40822432-70de4f80-65af-11e8-83ea-f280de112ca2.png)

**Comment by zur003** [comment]
There's another problem: If the user specifies the initial water by specifying the depth of wet soil, there's no way to go back to specifying by fraction of PAWC.
