### ISSUE TITLE
Magic calculation for water demand in the RUE model 

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2645]
There are some magic calculations in the RUE model. To reproduce my problem, I have created three simulations with three different version of RUE model. The base simulation is set up with water limited conditions.

* RUE: The raw RUE model in the release
* RUENoStress: All stress factors are changed to constant with value 1
* CustomRUE: The same algorithm is created with multiple and minimum functions in the GUI

If you look at the second panel of WaterDemand, the water demand CustomRUE model is really tiny compared with other two models, even when the fixation supply is the same between RUE and CustomRUE before 60 DAS. 

The only difference between RUE and CustomRUE are all codes in RUEModel.cs are not called. It seems there are some magic calculation about water demand in the RUE model. 

However, I cannot find any codes related with water demand in the RUEModel.cs. Any tips will be really helpful.

![image](https://user-images.githubusercontent.com/1657381/40824819-d9fef3b2-65b8-11e8-9dde-b5059ffcaafc.png)

The apsimx and met files are attached to reproduce my problem. 

[photosynthesis-waterdemand.zip](https://github.com/APSIMInitiative/ApsimX/files/2061294/photosynthesis-waterdemand.zip)

**Comment by byzheng** [comment]
I have narrowed down this problem to `VariableReference`. Model references to three variables in Photosynthesis, i.e.  `[Leaf].Photosynthesis.FT.Value()`, `[Leaf].Photosynthesis.FN.Value()` and `[Leaf].Photosynthesis.FVPD.Value()`. In the `CustomRUE` model, the three variables are missing, but program doesn't give any error messages. I guess the C# return a small value (close to zero), then cause the tiny water demand. 

It might be a bug in the `VariableReference` class which should throw out an error message if the variable reference is not found. It might be only related with Leaf.Photosynthesis in the test simulation.

**Comment by ric394** [comment]
Unable to test example file. If this still an issue, please make another issue.
