### ISSUE TITLE
Plant model raises exception in dry climates.

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2653]
The following problem has been noted by Dr. Zhigan Zhao:

After I successfully compiled the apsim next gen, I met an error when running it for scenarios (I am running wheat scenarios for a few sites across wheatbelt, e.g. Temora, Young, Griffith etc.). The error only happened for certain sites like Griffith which climate was too dry. Could you please check whether it is a bug in the source codes? Thanks very much.
![temp1](https://user-images.githubusercontent.com/11879340/40901232-ae6e31a2-6812-11e8-8fc1-62751a0bcbf4.png)
![temp2](https://user-images.githubusercontent.com/11879340/40901248-ba52e526-6812-11e8-8fd3-0eb7f566e0d0.png)

Best regards,
Zhigan

**Comment by HamishBrownPFR** [comment]
We will need the .apsimx and .met files to debug that

**Comment by zur003** [comment]
Zhigan's files are attached. Interestingly, when I run with a build based on the latest source, I get a different error from the one Zhigan reported - I see the exception "There are not enough apex to remove from plant." When I run using build 2018.4.30.2550, the run appears to freeze after 2 of the 3 simulations have run.



[Zhigan.zip](https://github.com/APSIMInitiative/ApsimX/files/2070300/Zhigan.zip)

**Comment by hol430** [comment]
I suspect this may be related to #2613 - there used to be a loop that was sometimes infinite, right near where this exception has been thrown.

**Comment by zur003** [comment]
The original issue seems to have been resolved. The "not enough apex" exception, if a problem, should be entered as a new Issue.
