### ISSUE TITLE
Could use better Markdown documentation

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2655]
The Apsim Next Gen "Memo" documentation at https://www.apsim.info/Documentation/APSIM(nextgeneration)/Memo.aspx does not accurately reflect the Markdown implementation we are using. For example, strike-through is not supported, and code blocks should be delimited with ~~~ rather than ```. This should be modified to better reflect what we actually provide.

It might be even better if we had a help dialog or something similar accessible from within the application

**Comment by hol430** [comment]
I didn't even know we had documentation on the apsim.info site. A lot of it looks out of date - the compile instructions in particular. The coding style guidelines also seem in some parts to be at odds with those on the netlify site. 

Perhaps it would be better to move all of the documentation to the netlify site, so that we don't have to remember to update both sites whenever we modify the documentation.

**Comment by zur003** [comment]
I got to that page via a link from the Netlify site (see the Model Documentation section - the Memo model).

Yes, the documentation really should be on the Netlify site, as much as possible.

I'm thinking we should have some decent documentation for Memo on the site, then add a help button in the GUI's MemoView that will open a browser window (either internal or external - not sure which is better) to display that documentation. There are probably other places where that sort of on-line help might be handy for users.

**Comment by zur003** [comment]
I've found there are a number of bits of Markdown that render correctly on-screen (that is, as HTML), but don't convert correctly when auto-generating documentation (as PDF). The conversion from HTML to PDF isn't quite as robust as it might be. That's not a trivial problem, but I think we can do better. Also, the Markdown lines are trimmed before processing, but leading tabs and spaces often have meaning in Markdown. Other bits include lack of support for blockquotes, and treating all <code> elements (which should just trigger a shift to a monospace font) in a way that would be more appropriate for <pre> elements.
