### ISSUE TITLE
Make the user interface scalable so that all the font sizes can be scaled

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#2666]
The whole user interface needs to scale

**Comment by zur003** [comment]
It's not easy to do this on the fly. However, on Windows you can change the font size by editing the .gtkrc file in the Bin directory. This normally sets the font as "Segoe UI 10.5".  You can change the 10.5 to 12 or 15 or whatever, save the file, then restart the GUI to apply the new font size.
Note that this will affect only the font size - the size of icons and so on will not be affected, so it's not truly "zooming" the display.

**Comment by zur003** [comment]
Oddly, setting a new font size in .gtkrc works OK for most things, but doesn't seem to affect the size of text on Buttons (and the various button descendants). This may be a bug in Windows Gtk.

**Comment by zur003** [comment]
For anyone wanting to test the changes that were just merged, the base font size can be changed by going to the "Home tab", holding down the control key, and scrolling up or down with the mouse wheel. Changes in font size persist across runs of the application. I probably should extend this to use ctrl-+, ctrl-- and ctrl-0 as well, to cater for anyone who may not have a mouse wheel.

In the longer term, we should have a settings dialog of some sort. The current arrangements are not particularly intuitive.

Note that this will adjust the font size of most things, but not all. In particular, material rendered in an embedded web browser (e.g., SummaryFile) and those using the TextEditor widget (e.g., Scripts and Reports) will not be modified.

**Comment by hol430** [comment]
This could be an issue with my mouse setup, but I need to scroll quite quickly to actually change the scaling. Unfortunately, this means that fine control over the scaling is difficult, as I shoot right past a 'good' size and go to something more extreme than what I want.

**Comment by zur003** [comment]
Going to close this for now, as this has been "fixed". If we want a separate "Settings" dialog, that can be opened as a new issue.
