### ISSUE TITLE
Dropdowns in Manager scripts

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2679]
Can we have a simple (!) method to deliver data from a drop-down that the user will select from the UI of a Manager script?  Would ideally cover strings, doubles, integers, Booleans.  Thanks, Val

**Comment by hol430** [comment]
This should be able to handle spaces in strings as well.

**Comment by hol430** [comment]
Some examples on how to use this feature would probably be useful. Where do they belong?
