### ISSUE TITLE
duplicate variable not reported (clock.today)

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#2684]
In old APSIM I sometimes report clock.today twice in the output file - so I don't have to scroll left and right from variables outputted at the RHS of the output file to see what date they fall on. But it isn't being duplicated in the output report in NextGen.

**Comment by hol430** [comment]
Not sure if this is a bug or a feature - I think the real issue here is the same as in #607

**Comment by AllanPeake** [comment]
I’m not entirely sure  - I haven’t figured out how to use the column filter yet to see if that could do the job for me either. When you have a minute, feel free to swing by my office and I’ll show you on my machine just so we are clear

A

**Comment by rcichota** [comment]
The column filter is a great feature and preserves the date column, however it is not intuitive to use (or to trigger). It would be great if it were to respond to an "ENTER" or have a button somewhere to actually trigger it after the keyword is typed. Currently one has to click in the data table to trigger it...

**Comment by AllanPeake** [comment]
It would be great if we could simply select multiple column headings to be selected in the filter. The filter only allows one column to be preserved when normally I am interested in 2 or more (e.g. ep, es, esw())

**Comment by hol430** [comment]
The column filter will now update when you press enter.

With regards to filtering multiple columns, what sort of syntax do we want to use? This is how I have set it up on my branch:

![columnfilter](https://user-images.githubusercontent.com/36427516/45126547-315b5200-b1b7-11e8-922c-3587bc9d45b7.PNG)

I'm open to suggestions.

**Comment by hol353** [comment]
How about comma separated list of names rather than semicolon?

**Comment by hol430** [comment]
Sure. Do you think allowing regular expressions would be useful?

**Comment by hol353** [comment]
Probably not. Our users don't get regular expressions.

**Comment by hol430** [comment]
Ok. And to go back to the original issue, do we want to allow reporting of duplicate variables? I feel like with a better filter, you may not need to.

**Comment by hol353** [comment]
Don't need to allow reporting of duplicate variables. In Next Gen clock.Today should always be visible because of locked columns.
