### ISSUE TITLE
Report model intelisence not finding PMF components

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#269]
The intelisence menu in the report properties tab is not listing all PMF classes.  Organs, Phenology are missing.  The same problem occurs in manager scripts

**Comment by zur003** [comment]
I don't really understand much about how the PMF is organised, but isn't this basically a question of whether members of the current object are defined as properties (that is, with get and set accessors) or as fields? If they are properties, they will be listed, but fields will not.
