### ISSUE TITLE
Develop a Red Clover model (PMF)

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#2694]
Red clover (Trifolium pratense) is a large-leaved herbaceous perennial plant of the Fabaceae family. It is native of native to Europe, Western Asia, and northwest Africa; it can now be found in many parts of the world. Red clover is widely grown as a fodder crop or green manure, although it can be used for herbal tea and also grows wild in swards in sub-tropical and temperature climates.  It produced high quality feed for animals and can also fix N through symbiotic relation with N-fixing bacteria.  The plants vary in height from 20 to 80cm with semi-erect stems, the leaves are alternate trifoliate and the petioles are 1-4cm long.  The flowers heads are dark pink or red and are pollinated especially by bumble bees.  Red clover has deep taproot which makes it tolerant to drought, it is also more tolerant to root weevil than white clover. 
The objective here is to develop a basic red clover model using the plant modelling framework (PMF). In this project the focus in on describing the general growth pattern of monoculture, as well as the re-growth after cut/grazing and including N balance. As PMF uses MicroClimate and SoilArbitrator to manage resource access, it should be readily possible to develop simulations with multiple species. While developing the model, the need for it to be used in mixed swards simulations will be taken in consideration as much as possible, however this is not a priority initially.

**Comment by JJguri** [comment]
I cannot create the documentation file for the entire simulation. The following error appeared:

System.IndexOutOfRangeException: There is no row at position 88.
   at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   at Models.Tests.Test(Boolean accept, Boolean GUIrun)
   at Models.Tests.Document(List`1 tags, Int32 headingLevel, Int32 indent)
   at Models.Core.AutoDocumentation.ParseTextForTags(String stringToParse, IModel model, List`1 tags, Int32 headingLevel, Int32 indent, Boolean documentAllChildren, Boolean doNotTrim)
   at Models.Core.AutoDocumentation.DocumentModelSummary(IModel model, List`1 tags, Int32 headingLevel, Int32 indent, Boolean documentAllChildren)
   at Models.Core.AutoDocumentation.DocumentModel(IModel model, List`1 tags, Int32 headingLevel, Int32 indent, Boolean documentAllChildren, Boolean force)
   at Models.Core.AutoDocumentation.ParseTextForTags(String stringToParse, IModel model, List`1 tags, Int32 headingLevel, Int32 indent, Boolean documentAllChildren, Boolean doNotTrim)
   at Models.Core.AutoDocumentation.DocumentModelSummary(IModel model, List`1 tags, Int32 headingLevel, Int32 indent, Boolean documentAllChildren)
   at Models.Core.AutoDocumentation.DocumentModel(IModel model, List`1 tags, Int32 headingLevel, Int32 indent, Boolean documentAllChildren, Boolean force)
   at UserInterface.Commands.ExportNodeCommand.DoExportPDF(String modelNameToExport)
   at UserInterface.Commands.ExportNodeCommand.Do(CommandHistory commandHistory)
   at UserInterface.CommandHistory.Add(ICommand command, Boolean execute)
   at UserInterface.Presenters.ContextMenu.CreateDocumentation(Object sender, EventArgs e)

[RedClover.zip](https://github.com/APSIMInitiative/ApsimX/files/3343632/RedClover.zip)

**Comment by rcichota** [comment]
@JJguri 
I fixed the issue preventing the creation of documentation. I should have tested that earlier, although I am not sure why it only breaks the documentation, not the tests. The problem was that there were 'tests' with variables that did not have an observed value (because I use an old excel template).

**Comment by sarahcleary** [comment]
Please find @JJguri's review attached
[Recommendations - comments Red Clover model.docx](https://github.com/APSIMInitiative/ApsimX/files/3416032/Recommendations.-.comments.Red.Clover.model.docx)
[20190626-APSIM_ReviewersReport_RedClover.docx](https://github.com/APSIMInitiative/ApsimX/files/3416034/20190626-APSIM_ReviewersReport_RedClover.docx)

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please review Reviewer's Report attached.

**Comment by rcichota** [comment]
@sarahcleary 
I believe I have finished reviewing the red clover model. Most of the comments were around improving documentation and providing commentary which I've done in the pull request open. As I did not change the model itself, it should go green once Jenkins finished with it, but I will keep an eye for unexpected issues. Other than that I have replied to the reviewer's comments in the attached file. Please let me know if that is all expected at this point. Cheers.
[Reply to reviewer recommendations-RedCloverModel.docx](https://github.com/APSIMInitiative/ApsimX/files/3548029/Reply.to.reviewer.recommendations-RedCloverModel.docx)

**Comment by JJguri** [comment]
@sarahcleary
I have read the response to the model development revision and I am more than happy with the answers.

**Comment by sarahcleary** [comment]
thanks @rcichota and @JJguri.  We have an RP meeting on Friday, so I anticipate the model being put into release post this meeting.  
@rcichota - are you able to provide me with a few lines I an use as a news article?
@MarkLieffering - has noted he is happy with the review and amendments and will not be providing any further input.
@APSIMInitiative/reference-panel - please note the above.

**Comment by sarahcleary** [comment]
As per - https://github.com/APSIMInitiative/ApsimX/pull/4147#issuecomment-528650041.
Ready for release

**Comment by sarahcleary** [comment]
@rcichota - can you please push this into release when you have a chance.  Once complete, please comment and close this issue.

**Comment by sarahcleary** [comment]
@rcichota - is this now in release?

**Comment by sno036** [comment]
@rcichota is on holiday and did not have time to move everything into release before he went away. @hol353 and I might be able to do this if all it is amounts to moving files.

**Comment by JJguri** [comment]
I have two issues:

1- I am using the red clover defoliation manager to set up a forage sorghum simulation. I want to specify only the date of grazing or cut and the fraction harvested (0-1). Following the instructions in the red clover script, I am using the following script in a defoliation schedule module but it is not working:

`2005-02-12 [DefoliationManager].Script.Defoliate(plantName: "Sorghum", fractionHarvestable: 1)`

2- I need to report the cumulative harvested biomass from all grazing /cut events during the growing season. How could I report that in the HarvestReport?

Here is the simulation (look at SimulationName 380074_Che8_sna)
[other versions.zip](https://github.com/APSIMInitiative/ApsimX/files/5172395/other.versions.zip)

**Comment by hol430** [comment]
Hmm, where did you get the instructions from? I just opened up the redclover example and couldn't see any instructions. I would guess that the instructions you were looking at were out of date, because the defoliate function has 4 arguments (none of them are plantName). An example invocation from the redclover example file:

```
2016-11-11 [DefoliationManager].Script.Defoliate(defoliationType: "Cut", amountDM: 40, amountType: "ResidualDM", duration: 1)
```

**Comment by JJguri** [comment]
I just applied the instructions from lines 564-591. Please see another simulation using the same script here. 
Please check SimulationName 'crop7'. In this situation, the crop was harvested 100%, so I want to be able to reduce the biomass until 0 kg/ha after the first grazing/cut.
[Sorgo.zip](https://github.com/APSIMInitiative/ApsimX/files/5172887/Sorgo.zip)

**Comment by hol430** [comment]
Yeah the crop7 simulation in Sorghum_V6_Australia also doesn't run for me, I get the same error as in 380074_Che8_sna. The function harvestableSwardBiomass on lines 564-591 doesn't seem to do anything by itself as far as I can tell, it just seems to compute the amount of biomass available to be harvested (I think). It's also a private function so it can't be called from operations, although I guess that can be changed easily enough.

Maybe @rcichota can comment on the intended way of defoliating based on a fraction rather than an absolute amount

**Comment by JJguri** [comment]
Initially, I used the following code to keep only 500 kg/ha as remaining biomass: 
```powershell
2005-02-12 [DefoliationManager].Script.Defoliate(defoliationType: "Cut", amountDM: 50, amountType: "ResidualDM", duration: 1)
```
It is running but it is'not working appropriately due to it keeps more than 500 kg/ha. Due to that I just used 
```powershell
2005-02-12 [DefoliationManager].Script.Defoliate(plantName: "Sorghum", fractionHarvestable: 1)
```

**Comment by rcichota** [comment]
Hi @JJguri 
I'm just having a look at this, the method you calling (Defoliate) expects four parameters (defoliationType, amountDM: amountType, duration) and thus will not work if you change them without changing the code. That method does trigger a series of other functions, including the one you're trying to invoke (called setRemoveFraction), but this is private and I meant it to be used that way. Of course the code could be changed to make it available (or the functionality you want. Let me try a couple of things here to see if I can replicate what you want...

**Comment by JJguri** [comment]
Thanks @rcichota 
Basically:
1- I want to specify only the date of grazing or cut and the fraction harvested (0-1). It is because some treatments were heavily grazed, i.e. 0 remanent biomass.
2- I need to report the cumulative harvested biomass from all grazing /cut events during the growing season in the HarvestReport.

**Comment by rcichota** [comment]
Hi @JJguri,
I've checked the manager you're using and noticed a couple of "semi-bugs" in there. They were left because they did not affect the work then, but limit a bit what can be done with that code. They were responsible for the "bad" results you mention when using the standard use (i.e. trying to remove all biomass and not being able to). I have fixed that (namely: make sure all biomass can be removed and limit removal tests to aboveground organs), this should enable you to do most of what you said you wanted, but not use a fraction to remove as a parameter. So I added that option to the code. Hopefully the examples in the attached smulation are self-explanatory, but get back if something is not ok. I will see if I can upate the RedClover example later on...
I also added to the attached simulation a auxReport script that does the reporting you wanted to do. I thought that it was better to have it outside the DefoliationManager so it is clearer. There could be a way to do that using the Report itself, but I am not well versed on it to know whether and how...

[extractSim-Crop7.zip](https://github.com/APSIMInitiative/ApsimX/files/5181031/extractSim-Crop7.zip)

**Comment by JJguri** [comment]
Hi @rcichota,
Thanks for this. In terms of the defoliation manager, the updated version works really well for our purposes. I just found that using the AuxReport manager for some experiments the `AcumCropYield` is 0 for some reason. Please see below for Residue0 and Fraction10. However, when you look at the dailyReport you can see the yield values for those experiments. 
![Untitled](https://user-images.githubusercontent.com/41041705/92433820-7b7dd080-f1e1-11ea-87e1-59100c857339.jpg)

**Comment by rcichota** [comment]
Hi @JJguri 
Sorry, I should have noticed that (I even had a graph plotting those outputs). It turned out the problem was still in the DefoliationManager (and a bit on Sorghum itself). The zeroes were there because of an assumption when summing up the amounts harvested from each organ (I had originally assumed no one would remove 100% of biomass, so I use biomass as a check for crop isAlive, my bad). After changing that, the manager captured appropriately the changes in biomass (harvested) for all cases. However, upon checking the values I noticed something else was wrong. The biomass pre-harvest was smaller than the biomass post-harvest plus amount defoliated (according to the DefoliationManager). This exposed a 'flaw' in my manager and a 'quirk' in Sorghum. To better explain (I hope) why this happened, I recap  the logic I use in my defoliation managers (pardon me if you had already deduced that from the code):
When a cut is triggered the code checks what is the total biomass aboveground (PreHarvestDM), then decides on the amount or fraction of biomass to remove and then sends the command to the plant. It then checks what is the new aboveground biomass (PostHarvestDM), the output DefoliatedWt is the difference between the pre- and post-harvest biomass. Because of the way PMF works, this doesn't necessarily means the amount harvested, it includes both an amount removed (harvested) from the plant and an amount returned to residues (wastage-ish). The balance between the two can vary for each organ. So, my code goes over each organ and collects the amount actually harvested (this is the output HarvestedWt). Finally the manager code computes how much of this amount harvest material is removed off field (RemovedWt) and the remaining is returned (as residue or dung/urine). The 'flaw' in my code is that it was not considering roots (I think that either roots were not originally harvestable or all plant model had their default removal for root set to zero). It turns out Sorghum does have non-zero values for biomass removal or roots. I think this 'quirk' in the model is actually a bug. For instance when using a Harvest() command 100% of roots are transferred to residues, most crops leave this as part of an EndCrop() command usually used in tandem. More worryingly, if the command used is Cut() then 80% of roots are actually removed off field (harvested!), the remaining is left in the plant...
I've changed the manager code to set the removal fractions to all below ground organs to zero, so all should be good here (check attached simulation). But I think it would be good to have those default removal checked out (not sure who is the person looking after Sorghum). See below the current setup for roots:
![image](https://user-images.githubusercontent.com/12175986/92531688-eb906300-f282-11ea-8d4f-0a5ab3e6b2d8.png)
[extractSim-Crop7.zip](https://github.com/APSIMInitiative/ApsimX/files/5191281/extractSim-Crop7.zip)

**Comment by jbrider** [comment]
@rcichota @JJguri I am looking after sorghum. We haven't done any validation on biomass removal in Nextgen as yet. Hoping it's not too far away now. Feel free to make the changes and commit.

**Comment by rcichota** [comment]
Hi @jbrider and @JJguri 
I wonder if this a problem more widespread than just sorghum. When developing new plant models we tend (I know I did) to adapt an existing one or copy/paste parts of it, some of which may have 'default' parameters that are not really appropriate for the new plant. I found difficult to think about what would be the best default parameters for the BiomassRemovalDefaults, as one have to do this for each organ and for each type of removal. I did try to put some sensible values, but was quite tedious, and I wonder how many people do a copy/paste and overlook it later on... And I doubt very much that most reviewers would pick up something out of place.  I see no easy solution, but maybe someone can come up with some test, or we create some recommendation for developers/reviewers to check these... Or maybe it is too hard to capture this type of thing and we have fix it as problems arise...
(adding @HamishBrownPFR, @hol430 and @hol353 to widen the visibility of this 'issue')

**Comment by JJguri** [comment]
Hi @rcichota thanks for this. We are now finishing the sims. I'll update once this work will be published. @jbrider how will be the best way to cite the actual sorghum model in a paper?

**Comment by hol430** [comment]
@jbrider fyi as part of #5650 I've updated the sorghum biomass removal defaults to what hopefully constitutes some more sensible values (copied from maize).

**Comment by jbrider** [comment]
@JJguri there is some information about this on the apsim.info website.
https://www.apsim.info/apsim-model/apsim-citation-and-acknowledgment/
I'm not sure about referencing a particular model - someone with more academic experience might want to comment on that?
@hut104 @HamishBrownPFR

**Comment by JJguri** [comment]
> @JJguri there is some information about this on the apsim.info website.
> https://www.apsim.info/apsim-model/apsim-citation-and-acknowledgment/
> I'm not sure about referencing a particular model - someone with more academic experience might want to comment on that?
> @hut104 @HamishBrownPFR

thanks @jbrider. I know about the apsim reference.  I was just thinking because it is an `under review` model.
