### ISSUE TITLE
duplicate lines of Operations code being ignored for same operation

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#2706]
One of the sugar validation sims inadvertently had an identical operation line repeated three times (an irrigation event). NextGen would ignore the repeats and only apply one of the irrigations, whereas APSIM7.10 applied all three. Not even sure this is a fault - could be advantageous to leave as is? 

When I changed one of the irrigation numbers it applied only the final operation out of the three - so it is only applying one irrigation per date which could be a problem in some instances.

**Comment by hol430** [comment]
@hol353 is this a bug or a feature?

**Comment by zur003** [comment]
@hol353 has indicated that this is a bug

**Comment by zur003** [comment]
The problem was not in Operations, but in Soil Water, which was handling only a single irrigation event per day.

**Comment by zur003** [comment]
The fix for this issue leads to changed results for some of the Performance Tests (specifically SCRUM and Maize validations), as there were days on which two irrigation operations occurred. Prior to the fix, only the last irrigation operation was actually being applied.
