### ISSUE TITLE
Grid copy and paste seems to be broken

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2707]
Attempts to paste into a grid cause ApsimX to crash. The problem appears to be a null reference exception. This should be fixed, and we should also have a more robust exception handling mechanism, to try to handle just failures more gracefully (and ideally without data loss).

**Comment by hol430** [comment]
I just attempted to copy some cells out of and back into a soil water grid and got an argument exception. Not sure if that's a different problem or just a different symptom of the same problem.

**Comment by zur003** [comment]
Looks like it's not a problem with all grids. The original problem was with a grid for the xy matrix of an XYPairs function.

**Comment by hol430** [comment]
What is the preferred method of dealing with an exception thrown in a view? Currently, most views seem to swallow any exceptions thrown in methods which are not called by a presenter. What I've done in the past in this situation is loop through the view owners until I get to the MainView and then call `ShowMessage()`.
