### ISSUE TITLE
Attempting to drag "Constant" function crashes the GUI

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2721]
You cannot drag the "Constant" function.

**Comment by hol430** [comment]
This seems to work fine for me. I opened the egrandis prototype and successfully dragged .Simulations.Replacements.Eucalyptus.Phenology.Juvenile.ThermalTime to .Simulations.Replacements.Eucalyptus.Phenology.Juvenile.

**Comment by zur003** [comment]
Only the "Constant" function has a problem. I have a fix at hand. (Just for your interest, it is searching for a class named "Constant", and finding a "wrong" class with that name.)

**Comment by zur003** [comment]
The original fix corrected the dragging problem, but broke using double-clicks to select functions.
