### ISSUE TITLE
On OS X, empty grids appear as black holes.

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2727]
When running on OS X, selecting the DataStore component displays a black window until a table has been selected. This is a bit jarring, and can easily be fixed.

**Comment by hol353** [comment]
@zur003  I've reopened this issue. The fix in this issue has broken grids on Windows. No data is being shown in the DataStore or Report grid. I'll post a pull request that undoes Eric's pull request.

**Comment by hol353** [comment]
My pull request has a resolves so this issue will be closed again. Feel free to reopen and refix the problem.

**Comment by hol430** [comment]
Does this mean that grids are broken on OSX once again?

**Comment by hol353** [comment]
Yep.

**Comment by zur003** [comment]
@hol353 - Are you sure there was a problem on Windows? It looked OK to me. 
![2018-07-03_9-45-00](https://user-images.githubusercontent.com/11879340/42191384-02d880e0-7ea6-11e8-939b-0de1369d7593.png)

**Comment by hol430** [comment]
I had a quick check this morning, and if I recall correctly, I think it was good until I emptied the data store and re-ran the simulation. The report grid was then empty.

**Comment by hol353** [comment]
Still broken. No data on the right in your image above. See this screen shot. There should be data in the yellow circle.
![image](https://user-images.githubusercontent.com/1943827/42242001-d62af816-7f4f-11e8-9256-7679ef2e38ee.png)

**Comment by hol353** [comment]
Need this fixed urgently. It is holding us up.

**Comment by zur003** [comment]
Re-opening, as I'd like to refactor the fix a bit more.
