### ISSUE TITLE
Implement a biomass removal interface for all PMF organs

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#273]
Currently the amount of biomass that is removed by a organ is hard wired in.  Need to be able to send remove fractions with harvest and cut method calls.

**Comment by hol353** [comment]
In Pull request #277 you have manager code like:

//Harvest with manager specified removal fractions
ManagerRemovalData[0].FractionRemoved = 0.3;
ManagerRemovalData[1].FractionRemoved = 0.1;
ManagerRemovalData[0].FractionToResidue = 0.3;
ManagerRemovalData[1].FractionToResidue = 0.7;
MCSP.Harvest(ManagerRemovalData);

Having an array of biomass removals (one for each organ) assumes the order in this manager script exactly matches the order of organs in the plant. Also, you can't tell by looking at the script which fraction relates to which organ. Is there a better way to do this?

**Comment by HamishBrownPFR** [comment]
I am hoping there is a better way as this is not really satisfactory.  Is there a way of finding array positions based on a name rather than number?  The other option is to send text strings from the manager like "Leaf.FractionRemoved = 0.6" and pass them into the appropriate location in the source code.  This would be better for users as you wouldn't have to construct the ManagerRemovalData object in manager script either.

**Comment by hol353** [comment]
We could create a new class (say RemovalFractions) to contain the array of ManagerRemovalData objects. This class could have methods:

void SetFractionRemoved(string organName, double fraction);
void SetFractionToResidue(string organName, double fraction);

called from manager:

RemovalFractions removals = new RemovalFractions();
removals.SetFractionRemoved("leaf", 0.1);
removes.SetFractionToResidue("leaf", 0.6);
...

and then pass this into Harvest. Is this better?

**Comment by HamishBrownPFR** [comment]
Looks better, I will try it and see how it works.

**Comment by HamishBrownPFR** [comment]
Where do I put the RemovalFractions class so it is accessible in the manager.  Do I have to construct it in the manager or can I put it somewhere in the source code

**Comment by HamishBrownPFR** [comment]
Don't worry, I have worked it out

**Comment by HamishBrownPFR** [comment]
Have pushed some changes up that do it the way you suggested.  Is tidier I think so thanks for the suggestion.

The only problem I have had is with the constructor on the RemovalFractions class.  If I have the constructor operational it throws errors when I open simulations in the UI.  I have got around this by putting a setup method in the class which creates a set of OrganBiomassRemoveFraction clases the same size as the number of organs and gives each an organ name.  However this requires and extra line of code to be called when making the Removals object in the manager script.  ie the highlighted line of code could be done away with if I could get the constructor working properly.

![image](https://cloud.githubusercontent.com/assets/7295858/9537774/d490b9bc-4d90-11e5-8b9f-aac1ff16cbde.png)
