### ISSUE TITLE
Ability to select crop type in manger scripts appears to be broken

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2739]
At one time, it was possible for the user to select a plant species (e.g., as a target for sowing or harvesting), by using the construct:

        [Description("Crop")]
        public IPlant Crop { get; set; }
        
This no longer seems to be working correctly. The "Properties" tab, this correctly shows a drop-down list of available species (although, somewhat confusingly, the list shows the "short" name of the crop, but the grid is populated with a fully-qualified name). However, when the script is run, the value for "Crop" is not assigned - it remains null, and references to its members raise exceptions.

**Comment by zur003** [comment]
Seems to be a problem with absolute paths. We may start with a path of something like .Simulations.Wheat.Field.Wheat. That's fine when the ApsimX file loads, but at run time, we no longer have a Simulations object at the root - the Simulation (Wheat, in this case) is the root.  I'm going to submit a pull request that will fix the immediate problem, but I think there's a bigger issue here that needs more thought. @hol353 , what do you think?

**Comment by hol353** [comment]
Yes this is a bit of a mess. We could make the .Simulations.Wheat.Field.Wheat work by parenting running simulations to the root simulations object. I would then like to get rid of the square brackets e.g. [Wheat]. This is confusing users and causes errors when there are two wheat objects.  REPORT does this a lot. Perhaps we just make report variables relative to the Zone that REPORT is located in and then do away with square brackets all together. Also, if we want to address a parent object we should use some other syntax e.g. 2 dots or something like that. I'd like a path syntax that is predictable and well documented, something that we don't have now.
