### ISSUE TITLE
Improve Datastore database performance

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#2821]
Add Firebird support.
Generalise database interface.

**Comment by zur003** [comment]
Firebird will require some refactoring of the database structure. Firebird has a 31 character limit on the length of field names, so column names like Wheat.Phenology.CurrentStageName aren't going to work. We will probably need a new table that associates a field identifier with a field name.

**Comment by hol430** [comment]
@her123 Can this issue be closed?

**Comment by zur003** [comment]
The Firebird support has not been maintained, and bits no longer work (for example, PagedDataProvider uses "rowid",which is specific to SQLite, and is not available in Firebird). Firebird support is probably worth fixing, and some parts of the existing code can be simplified. For example, the previous 31 character limit on field names is now 63 characters (or perhaps that's 63 UTF-8 encoded bytes). That's long enough to cope with things like "Wheat.Phenology.CurrentPhase.Name" without all the hoop-jumping I introduced in #3780, which should greatly simplify things.
