### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#284]
Can't seem to drag and drop components in the IU

**Comment by hol353** [comment]
Which components can't be dragged and dropped. I tightened up the drag and drop quite a lot about a week ago.

**Comment by HamishBrownPFR** [comment]
Stuff inside the factors node.  Can't drop a simulation onto the experiment.  Cant drop factor nodes onto the factor node or onto other factors.  Can't drop graphs any where
