### ISSUE TITLE
column for gravimetric water data?

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#2841]
Could we please add a column adjacent to the volumetric data that allows us to record gravimetric data?
In my opinion:
- the gravimetric column should be on the left of the two.
- changing either of the columns should change the other (by referencing to BD of the soil file of course)
- if the initial nitrogen/water node is then moved to a different soil, gravimetric should stay the same and VWC should change.

**Comment by rcichota** [comment]
hmm this could be interesting. However instead of adding a column, maybe it would be simpler to just make it a change of units, the same way as one can add NO3 in kg/ha or ppm and switch between them...

**Comment by zur003** [comment]
The ability to switch SW units from volumetric to gravimetric is already in the IntialN view.

**Comment by AllanPeake** [comment]
It’s about having both sets of data available at the same time. Not necessarily a high priority feature but would be useful sometimes

**Comment by hol430** [comment]
After discussion with @hut104 and @hol353 we will not be implementing this feature in the interests of keeping things simple and consistent. The relevant code for toggling the units here has long since been stripped out so I am going to go ahead and close this issue.
