### ISSUE TITLE
ability to copy/paste arrays in soil init water/nitrogen nodes

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#2842]
Would be nice if we could copy and paste either single or multiple columns of data between these nodes - would also be nice to be able to pull the data from a spreadsheet or old apsim file array as well

**Comment by hol430** [comment]
Copy/paste for a range of cells should be possible if you update your Apsim installation.

**Comment by hol430** [comment]
Closing this now, as this feature is available as of version 2018.8.21.2953.

The behaviour should be similar to Excel. Click on the top-left cell to copy, shift-click on the bottom-right cell to copy, hit ctrl+c to copy, then ctrl+v to paste.
