### ISSUE TITLE
Rationalise phenological event testing

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2850]
IsAlive, IsGerminated and IsEmerged and not sufficiently general to work well with perennial models

**Comment by rcichota** [comment]
It would be good to have the IsAlive (and the phenological phases  - and/or stages) being well defined when the plant is not yet sown and when it has been killed/harvested.  I did not check today, but I recollect these were not been reset....

**Comment by HamishBrownPFR** [comment]
This issue has been dealt to with recent phenology refactor
