### ISSUE TITLE
Change the different types of links to be a single [Link] attribute

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#2863]
Currently we have [Link], [LinkByPath], [ScopedLinkByName], [ScopedLink], [ChildLink], [ChildLinkByName], [ParentLink]. I think we need a single [Link] class with perhaps an enum argument e.g.

[Link(type=LinkType.Path, path="xyz")]
[Link(type=LinkType.Scoped, name="xyz")]
[Link(type=LinkType.Child, name="xyz")]
[Link(type=LinkType.Parent, name="xyz")]

**Comment by hol353** [comment]
@hol430  How about you have a go at this. It will involve writing a converter because all manager scripts in .apsimx files may need to be upgraded.

**Comment by hol430** [comment]
Will do

**Comment by hol430** [comment]
As part of this, do we want to remove optional links entirely?

**Comment by hol353** [comment]
Eventually yes but there are too many still in existence.
