### ISSUE TITLE
Vary graph properties by series

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2865]
Currently if you have multiple series on a graph you need to go through and choose which color/marker/line you want each to be each to be.
It would be really handy if we could select "VaryBySeries" in the properties options for each series and the graph increments the property for each subsequent series.
This will help to avoid the issue in the picture below where is someone refactors graph the series all end up looking the same. 
![image](https://user-images.githubusercontent.com/7295858/43557752-4c0bbac2-965a-11e8-8480-8b2fd84e9567.png)

**Comment by hol430** [comment]
Was this working until recently, or has this always been an issue?

**Comment by hol353** [comment]
This is a new feature request. Assign it to me.

**Comment by pre078** [comment]
I can't seem to get it working after testing with several different sets of data. I have put a filter on each of the multiple series children then change the Colour to "Vary by Graph Series"; then it doesn't show.
 (ie. X = Date, Y = Weight, Filter -> UID = 4 etc. for multiple series children; 
or  X = Date, Y = Amt, Filter -> Resource = "Maize stover" etc.

**Comment by hol430** [comment]
Can you upload your .apsimx and .met file?
