### ISSUE TITLE
Add option to suppress summary file messages with fertiliser is applied or irrigation applied

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2900]
At present there is no way (that I know of!) to turn them off and the summary file can get so clogged with these messages that it is nearly impossible to see the important stuff.  Can an option to suppress the messages be added to the Irrigation and Fertiliser components?

**Comment by hol430** [comment]
@sno036 I've added an optional boolean argument to the `Irrigation.Apply()` and `Fertiliser.Apply()` methods called `doOutput`. If set to true, these methods will write output to the summary file. If set to false, these methods will not write to the summary file. The default value is true, so if you don't specify a value for `doOutput`, these methods will write to the summary file.

![test](https://user-images.githubusercontent.com/36427516/44012369-f5c8cad2-9f01-11e8-8190-669099da9c05.PNG)
