### ISSUE TITLE
Make the Stock.Buy event use type rather than "sex"

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2902]
At present Stock.Buy requires a "sex" field that contains descriptors like "ewe", "steer" but these are converted into **types** "Empty" for any female, "Male" for entire males including cryptos and "Castrated" for castrated males.  It would make the maintenance and usability of Manager scripts much more robust if they could directly specify **type** rather than sex.

@her123

**Comment by her123** [comment]
Implement a Buy function that uses AnimalType field rather than Sex. The suitable values would be Mature female, Immature Female etc. These are common to either sheep or cattle. Use an enumerated type rather than a string.
