### ISSUE TITLE
Chicory grazing and FractionToRemove

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2905]
Hi Rogerio, @rcichota 

The attached simulation is Chicory grazed with the Stock component.  All runs well if the no grazing window is implemented ("Implement a no-grazing window? (tick for yes):") but if this is unticked then a grazing on 30 October is triggering an error:

                throw new Exception("The sum of FractionToResidue and FractionToRemove for " + Parent.Name
                                    + " is greater than one for live biomass.  Had this exception not been triggered, the biomass for "
                                    + Name + " would go negative");

You will see from the settings in the component that the stock exit the simulation when above ground biomass is > 1900 kg DM /ha at the start of the day.  They can only eat about 250 kg DM /ha (I have converted from g/m2 to kg/ha) in a day so they should not be trying to consume more than is there.

Suggestions?

Thanks, Val

[PlantainGrazing_RemoveBiomassError.zip](https://github.com/APSIMInitiative/ApsimX/files/2268946/PlantainGrazing_RemoveBiomassError.zip)

**Comment by hol353** [comment]
Cannot reproduce. I assume it has been fixed.
