### ISSUE TITLE
The value cannot be changed in the GUI

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2914]
In the master branch, I cannot change any values in the Replacements --> Wheat. For example,

The value will be restored into the original values after pressing enter and/or leaving focus.

![apsimx](https://user-images.githubusercontent.com/1657381/43870142-70036c86-9bb9-11e8-814b-89a0d710f247.gif)

**Comment by hol430** [comment]
When was the last time you pulled from master? One of my pull requests, which was merged a few hours ago, addressed some similar issues.

**Comment by byzheng** [comment]
I pull the master branch in 10 min before.

**Comment by hol430** [comment]
Ok - I will look into this.
