### ISSUE TITLE
Clock view not working

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2923]
Currently the clock view is blank so there is no way to set start and end dates through the GUI

**Comment by hol430** [comment]
I fixed this a few days ago...I thought I made a pull request but maybe I didn't. When was the last time you did a pull?

**Comment by HamishBrownPFR** [comment]
I am one behind master, I will pull and check again

**Comment by HamishBrownPFR** [comment]
Yep, the merge I was missing was the one where you fixed this.  Thanks @hol430
