### ISSUE TITLE
Morris/Sobol buttons in experiment view

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#2938]
@sno036 @hol353 Do we still want the morris/sobol analysis buttons in the experiment view? Under its current implementation, the Morris analysis seems to be available via a Morris model which you add directly into the simulations tree. If we still want these buttons in the experiment view, what should they do?

![morrisui](https://user-images.githubusercontent.com/36427516/44181394-e6fd2d00-a144-11e8-977f-854b3e2069f0.PNG)

**Comment by hol353** [comment]
Lets remove the buttons for now. I don't think they will be needed.
