### ISSUE TITLE
Checkpointing not writing all of models status

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2949]
@hol353 I will email you the test file I have been trying to get to work.  Issues I have encountered:
1. Put a checkpoint in the write method of the checkpointing class.  It is only called at the start of the simulation, not the end.
2. When using Chicory.Phenology as the model to checkpoint, it only writes the parameters of the model (i.e) those that come from chicory.xml, not the full status.
3. When using Chicory.Leaf the checkpointing throws an error because the model is null.  However, it comes up with intellisence so it must not be null.

**Comment by HamishBrownPFR** [comment]
@hol353 this is still not working correctly.  It is outputting full status now but there are other problems.  I will email you a test file which has a chicory simulation where I am trying to checkpoint on the PostPhenology event.  However, it only writes the status on the first time step.  For some reason PostPhenology becomes null after the checkpoint is called for the first time so this event is not broadcast again. 
The file also has a maize simulation in it which throws a null reference error when trying to checkpoint a linint function.

**Comment by HamishBrownPFR** [comment]
@hol353 I also wondered if it would be good to print some information to help locate the checkpoint print out in the timing of the simulation.  Perhaps have it write Clock.Today and the event in the closest event in the call stack so it is clear what the printed checkpoint status relates to in the context of time in the model.

**Comment by hol353** [comment]
@HamishBrownPFR I've had another go at this. It now checkpoints a whole simulation which seems to work better. The first argument to SaveStateOfObject method is the filename. If you want a date filename then do something like: checkpoint.SaveStateOfObject(clock.Today.ToString("yyyy-MM-dd"), Chicory.Phenology);

**Comment by HamishBrownPFR** [comment]
Thanks @hol353  This works for the chicory simulations in the example I sent you but the maize simulation checkpointing still causes a fatal.

**Comment by jcbowden** [comment]
Hi, I'm trying to use the Checkpoints class in the Report::DoOutput() code with the example Wheat.apsimx simulation and it fails. 
The code I added is:
public void DoOutput()
{
... // the db output stuff
Simulations parentSimulations = Apsim.Parent(this, typeof(Simulations)) as Simulations;
cp = new Checkpoints(parentSimulations);
cp.SaveStateOfObject(clock.Today.ToString("yyyy-MM-dd"),simulation);
}
The exception given:

System.Exception occurred
  HResult=0x80131500
  Message=Cannot find variable: [Leaf].MaxNodeNo in function: CohortArrayLive
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Models.Functions.ExpressionFunction.FillVariableNames(ExpressionEvaluator fn, Model RelativeTo, Int32 arrayIndex) in C:\tmp\APSIMX_git\ApsimX\Models\Functions\ExpressionFunction.cs:line 100
   at Models.Functions.ExpressionFunction.Evaluate(String Expression, Model RelativeTo) in C:\tmp\APSIMX_git\ApsimX\Models\Functions\ExpressionFunction.cs:line 153
   at Models.PMF.ArrayBiomass.AddValuesToList(String SubPropertyName) in C:\tmp\APSIMX_git\ApsimX\Models\Plant\Biomass\ArrayBiomass.cs:line 172
   at Models.PMF.ArrayBiomass.get_StorageN() in C:\tmp\APSIMX_git\ApsimX\Models\Plant\Biomass\ArrayBiomass.cs:line 36
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)

Any ideas of why this happens? 
Thanks,
Josh

**Comment by hol353** [comment]
Josh, this is a work in progress. We haven't ironed out all the bugs yet. It also won't yet allow you to reset to a checkpoint, which is probably the reason you're looking at it.

**Comment by hol430** [comment]
I've got a prototype of #2486, which will allow users to view the structure of a model in read-only mode in the GUI. 

I haven't treated it as high-priority, but you're not the first person recently to ask for something like this. I guess I'll push on and get it into the released version when I can (later this week or early next week maybe?).

**Comment by jcbowden** [comment]
Hi Drew,

The GUI viewer would be useful to understand the Model. What I really want a code based method to modify the values of a model – i.e. programmatically change “tt_XYZ” values or something as such. We are looking at uncertainty in model parameters so this is a requirement to do the analysis. I’m happy to write C# code to do this – I just need to know how to reference the model parts by name (using introspection).
Cheers,
Josh

**Comment by hol430** [comment]
You mean, you want to modify the model's values from, say, a manager script? That should be possible, although finding the property you want via the intellisense alone can be difficult. 

Are you using the release version of Apsim, or building from source?

**Comment by hol353** [comment]
A manager script (in C#) can be written to modify these properties at the start of simulation. The script is then stored in the .apsimx file. You can then write an external program to change the scripts values in the .apsimx file (XML), run the .apsimx file by calling Models.exe, collect the outputs in the .db file and repeat for the next set of parameter values. Is this what you're after?

**Comment by hol430** [comment]
If you want to see the model's structure, you can open up the model's xml file, which will be located at `Models\Resources\`. If you copy the entire contents of a file, you should be able to paste it into the GUI under replacements, and have a poke around and see how things work.

**Comment by hol353** [comment]
Drew, can you create an example .apsimx file based on the wheat example that has a manager script that changes some of the variables that Josh wants to change? I'm not too sure what the APSIM Next Gen. equivalent is to some of the variables listed above. Here are some possible candidates:

[Wheat].Phenology.GrainFilling.Target.FixedValue
[Wheat].Grain.NumberFunction.GrainNumber.GrainsPerGramOfStem.FixedValue
[Wheat].Phenology.VrnSensitivity.FixedValue
[Wheat].Phenology.PpSensitivity.FixedValue
[Wheat].Grain.MaximumPotentialGrainSize.FixedValue
[Soil].DUL

@HamishBrownPFR had a manager script to do this I think but I can't find it. For now, look at the ResetLAI script in Tests\Validation\Slurp\Slurp.apsimx folder.

**Comment by HamishBrownPFR** [comment]
using Models.Core;
using Models.PMF;
using System;

namespace Models
{
    [Serializable]
    public class Script : Model
    {
        [Link] Checkpoints checkpoint = null;

		[Link] Plant Maize;

		[Link] ISummary Summary = null;

		[Link] Clock clock = null;

		[EventSubscribe("DoReportCalculations")]
		private void OnDoReportCalculations(object sender, EventArgs e)
		{
			if (Maize.Phenology.Emerged == true)
				{
				checkpoint.WriteMessageLine("Maize",clock.Today.ToString());
				checkpoint.AddToCheckpointFile("Maize", Maize.Phenology);
				}
		}
	}
}

**Comment by HamishBrownPFR** [comment]
Sorry, you are thinking of a different script.  Try the sowing rule in the potato example

**Comment by HamishBrownPFR** [comment]
![image](https://user-images.githubusercontent.com/7295858/45134694-fb868f80-b1ef-11e8-9e97-c6fdca9e32ef.png)

**Comment by HamishBrownPFR** [comment]
or the Slurp validation
![image](https://user-images.githubusercontent.com/7295858/45134753-3ee0fe00-b1f0-11e8-8e16-6d29dd13e277.png)

**Comment by hol430** [comment]
This is pretty much what Hamish just posted anyway, but here's the sample you asked for.
[WheatSample.zip](https://github.com/APSIMInitiative/ApsimX/files/2355434/WheatSample.zip)

It should be pretty easy to write a tool which parses the XML and assigns a value to the GrainFillingTarget property of the script in the ChangeProperties manager.

**Comment by jcbowden** [comment]
Thanks for all this.

I’ll go through them soon to see what I can do with them.

Thanks heaps for your input. I’ll tell you how I go.

Regards,
Josh

**Comment by hol430** [comment]
@jcbowden If you do a pull, you should have the option to right-click on a released model and select "view model structure".

**Comment by HamishBrownPFR** [comment]
This issue is resloved now and conversation seems to have finished so closing
