### ISSUE TITLE
The "Help" button does not appear on the "Home" screen

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#2953]
The "Help" button does not appear on the "Home" screen and it is not until a simulation is opened that the user can see that is is any help.  Suggest adding it as a Home screen item.

**Comment by hol430** [comment]
Do you want it on the home screen as well as on each tab, or only on the home screen?

**Comment by sno036** [comment]
I am pretty sure that any other tabs must be simulations and they already have the help button on them.  So yes, it should be on every screen, but at present it seems to only not be on the Home screen.  Make sense?

**Comment by hol430** [comment]
Yep - #2954 will do exactly this.

**Comment by sno036** [comment]
:-)
