### ISSUE TITLE
APSIM crashes if you select a graph whilst a simulation is running

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2966]
APSIM crashes if you select a graph whilst a simulation is running.  For example, if you run an experiment, but then try to select a graph from another experiment, APSIM crashes with a windows error dialog box.

It would be good if you could select graphs for simulations not currently being executed.  Or, at the very least, if the GUI trapped the error and told the user that graphs cannot be selected whilst APSIM is currently running.

**Comment by hol430** [comment]
Same as #2209. Given how incredibly fast Apsim is, I'm surprised you have enough time to go around clicking on graphs while a simulation is running.

Still, I've fixed the UI crash on my branch without killing the simulations. Setting up access to the DB while a simulation is running will be a little more complicated, but I will see what I can do when I get the chance.

**Comment by hol430** [comment]
Closing this, as the main issue has been resolved.
