### ISSUE TITLE
Issue with units of met file

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#297]
The weather model has problems if the units look like
!title=Melkasa
[weather.met.weather]
Latitude = 8.4(DECIMALDEGREES)

   ! TAV and AMP inserted by "tav_amp" on 31/07/2015 at 11:57 for period from   1/1998 to 366/2012 (ddd/yyyy)
 tav =  21.47 (oC)     ! annual average ambient temperature
 amp =   3.27 (oC)     ! annual amplitude in mean monthly temperature

Site    year    day     radn    maxt    mint    rain
()      ()      ()      (MJ/m^2) (oC)    (oC)    (mm)
Melkasa     1998       1   18.00   27.73   15.47    0.00
Melkasa     1998       2   17.10   28.88   13.15    0.00
Melkasa     1998       3   17.60   29.77   13.15    3.44
Melkasa     1998       4   19.80   29.77   13.69    0.00
Melkasa     1998       5   21.30   29.45   13.69    0.00

If I change the units of the radn column it runs OK.  Not sure which character is not supported.

**Comment by hol353** [comment]
Can't reproduce this. Any other clues?

**Comment by hut104** [comment]
Error was with file contents rather than with APSIM.  APSIM was correct!!!
