### ISSUE TITLE
export green leaf number to match observations

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#2973]
In the observations, we normally count green leaf as more than 50% green parts, i.e.  counting as dead leaf when there are more than 50% senescence.

**Comment by HamishBrownPFR** [comment]
Hi @byzheng.  I have reopened this issue because would be good to see better variable names than GreenCohortNo2 and PlantAppearedGreenLeafNo2.  Can you think of something more descriptive?

**Comment by byzheng** [comment]
@HamishBrownPFR  How about the new name? GreenCohortNoHalfSenescence  and PlantAppearedGreenLeafNoHalfSenescence?

**Comment by HamishBrownPFR** [comment]
@byzheng the new names you suggest would be much better.   Thanks
