### ISSUE TITLE
Ubuntu installs not working

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#2979]
After doing an "upgrade" on Ubuntu, apsim is failing with a message that the DLL glibsharpglue-2 could not be found.

**Comment by zur003** [comment]
It comes from elsewhere. The ApsimNG installer indicates that it is dependent on the gtk-sharp2 package (among others). The "glue" files are installed as part of that package, and should be installed in the global assembly cache by the gtk-sharp2 installer.
Things get a bit messier, though, with the "native" DLLs (as opposed to .Net assembly DLLs), as the names are different on different platforms. libglib-2.0-0.dll on Windows has counterparts named libglib-2.0.so.0 on Linux, and libglib-2.0.0.dylib on OS X. There need to be mapping specified in the .config files of the applications - see Mono.TextEditor.dll.config for an example. Files loaded into the GAC by the gtk-sharp2 installer should already have .config files set up for them.
Getting all this right can be a bit tricky.

**Comment by zur003** [comment]
The OS X installer is "broken" in the same way.

**Comment by zur003** [comment]
Part (all?) of the problem seems to that Windows DLLs are being included in the distribution. Instead of pulling in libglib-2.0.so.0, mono sees libglib-2.0-0.dll is sitting there and loads it, but since it's a Windows native binary, it chokes on it.

**Comment by hol430** [comment]
I've just noticed an interesting issue in the Windows upgrade form. Whenever I click on one of the buttons, checkboxes, or textboxes, the main Apsim window moves in front of the upgrade form.

Is anyone else experiencing this?

**Comment by hol430** [comment]
@zur003 I've manually created and uploaded a new macOS installer for Apsim version 2018.08.24.2916. Does this work for you?

**Comment by zur003** [comment]
Almost. The OS X version also requires the file MonoMac.dll, which is in the repository in the ApsimNG\Assemblies directory. For the Mac version, this needs to be copied into the Bin directory.

**Comment by hol430** [comment]
Re-opening this so I can add MonoMac.dll to the installer.

**Comment by hol430** [comment]
I've just uploaded another macOS installer for Apsim version 2018.08.24.2916, which includes MonoMac.dll. Does this work for you?

**Comment by zur003** [comment]
Yes, it looks like the right files are there now.

**Comment by zur003** [comment]
The Mac OS X stuff now seems to by mostly working OK, although I get an error when the updater is trying to start up the new copy. That's a fairly minor problem; it runs just fine from Launchpad.

The Linux builds are still a problem, though. They still have all the Windows DLLs in them, causing havoc. If I delete the DLLs, the install works OK (although the version of Mono on Ubuntu 18.04 still crashes when trying to display the Mono.TextEditor stuff).

There's also a separate Linux problem when trying to do updates. You get a message along the lines of:
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.

Dr. Google suggests this is likely to be due to trying to open a modal dialog from a background thread. It can be quite annoying, since it often goes ahead and removes the existing installation even though it hasn't successfully downloaded the new one. This needs to be fixed.

**Comment by hol430** [comment]
I think the error when launching a new copy happens on Windows too. Linux builds are the biggest problem at the moment though, and there is no Linux installer available for most of the recent versions.
