### ISSUE TITLE
Morris View not working

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2983]
The Morris view is blank in the Morris example simulation.  Click on the morris node and the view should be a grid.

**Comment by hol430** [comment]
Do you have R installed?

**Comment by hol430** [comment]
@hol353 @hut104 Is this what you would expect to see in the Morris view?

![morris](https://user-images.githubusercontent.com/36427516/44961987-9ddb1480-af5d-11e8-97cd-87e8ee67c804.PNG)

**Comment by hol353** [comment]
Yes. Do you change something to get this to work?

**Comment by hol430** [comment]
It's a code change. I'll make a pull request later today, but there are some other problems here as well. To get the table of data to be displayed, we call `Morris.GetTable()`, and likewise to update the morris model's table, we call `Morris.SetTable()`. However, this means that any changes from the view cannot be applied to the model via the commands system, and therefore are not undoable.

**Comment by hol430** [comment]
Will you sometimes need to add more rows of data to this grid?

**Comment by hol353** [comment]
Ahh yes you're right. The number of rows needs to be open ended. There can be several dozen parameters. Probably no more than 50.
