### ISSUE TITLE
Morris Elementary effects do not look right

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#2984]
The value of Mu star should approach a near constant value with the number of paths explored.  It now seems to diverge.

**Comment by hol430** [comment]
To add to this, the Morris example generates a large number of simulations with the same name. 

You'll see the bug manifest itself if you set a breakpoint in the `GetNextJobToRun()` method of RunOrganiser.cs. If you compare `AllSimulationNames.Count` to `AllSimulationNames.Distinct().Count()`, you will notice that the Morris example is generating 534 simulations, but only 313 unique simulations.
