### ISSUE TITLE
Refactor Organ/Arbitrator interface

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#3000]
Currently DM and N supplies and demands are methods that do a whole lot of calcualtions.  They should really be properties with private sets in each organ on a specific event to reduce redundant calculation

**Comment by jbrider** [comment]
I'm currently in the middle of this code creating a sorghum arbitrator - hoping to put a pull request through late this week / early next week... can you hold off until then?  I'm not changing the existing classes  much other than to create an interface for Arbitrator.

**Comment by HamishBrownPFR** [comment]
Hi @jbrider.  I need to keep moving with this this refactor so I can move the parameterisation of DM and N demands out of the source code into the xml and can get a Ph.D. student moving with developing the Lucerne model for APSIM next gen.  You will also find this reafactor helpful for implementing SLN based N demand in the sorgham model.  I have time to work on it at the moment but won't later.  If this gets merged before your stuff and you have problems with conflicts I am happy to help resolve them but you can't really ask people to stop their work so you can get yours done.
Did you realize there is already an IArbitration interface that each of the organ classes is implementing (...Plant/Interfaces/IArbitration.cs.

**Comment by jbrider** [comment]
Hi @HamishBrownPFR, Sorry, I meant that more of a heads up that I was working in it than a cease and desist ;)  I had a couple of false starts trying to use the ArbitrationMethod interface and have taken the advice you gave me and replaced the Arbitrator itself - which is possibly overkill but just wanted to get the sorghum model working first - without breaking anything else.  Keen to see what you have in mind to get the DM and N into the interface.
