### ISSUE TITLE
[Link] behaviour not correct.

### ISSUE THREAD

**Issue by fai04d** [APSIMInitiative/ApsimX#302]
When using [Link], the name of the variable used to hold the link can influence the model that is linked.
For example, in the AgroForestry example, there is a main weather system with a local weather in each Zone. Also in the Zone is MicroClimate. When using the following code in MicroClimate:

[Link]
IWeather Weather = null

The link will find the main model 'Weather' in the parent system instead of LocalMicroClimate which also implements the IWeather interface and is a sibling to MicroClimate. If we change the code to:

[Link]
IWeather LocalClimate = null

Then the link works as expected and finds the sibling node.

**Comment by hol353** [comment]
Fixed on #350
