### ISSUE TITLE
Factor with one level

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3043]
In a simulation, I have set two factors 1) Cultivar with two levels, 2) Management with one level

![image](https://user-images.githubusercontent.com/1657381/45273083-317b8a80-b4f4-11e8-91ac-06f90983f339.png)

However, the Management factor is stored as the column name "Factors" and value as "Management". 

![image](https://user-images.githubusercontent.com/1657381/45273119-70a9db80-b4f4-11e8-8d95-1eaed54c1d39.png)

I would expect to store as the first Factor, e.g.

| Cultivar | Management |
| ------------- | ------------- |
| P100 | IHN |
| P150 | IHN |

In this way, I can mixed experiment with multiple levels and only one levels when plotting figures.

**Comment by byzheng** [comment]
This problem also existed in the GUI to generate the simulation table. When there is only one level in the two factors, I expect there is only one simulation, but actually two simulations in APSIMNG.

![image](https://user-images.githubusercontent.com/1657381/45523879-e7094f00-b80e-11e8-8638-e020b0a24dd2.png)

**Comment by hol430** [comment]
Yeah #3045 will fix this as well, once I get it to pass the performance tests.
