### ISSUE TITLE
Negative increases of phenology stage

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3047]
@HamishBrownPFR  In the `GenericPhenology` model or any other phenology model, the `Target` might be dynamic with time. Consequently, the `FractionComplete` might be decreasing comparing with previous day, especially when daily thermal time is close to zero and increasing target. For example, the testing simulation below.

![image](https://user-images.githubusercontent.com/1657381/45336788-58a38c00-b5c8-11e8-9f31-16072c242b86.png)

We might need to constrain the delta stage to zero.

**Comment by HamishBrownPFR** [comment]
Hi @byzheng.  Conceptually I don't have any problem with stage decreasing if the target is increasing.  Are there some technical problems this is causing you?

**Comment by byzheng** [comment]
@HamishBrownPFR I am trying to use DeltaHeight to calculate the stem demand. In the Height model, the potential height is depending on the Stage. Consequently, the DeltaHeight is negative, then negative stem demand. 

I have worked around with maximum function. 

Just report here for in case of other potential problems.

**Comment by HamishBrownPFR** [comment]
OK, thats a problem.  You are also going to have a problem if you constrain it as you will get periods when stage is not changing and demand will be zero.  Perhaps the real problem is that we are modelling height using stage and we should be using something else like node appearance and extension.

**Comment by ric394** [comment]
This very old. 
Closing. 
If this is still an issue, please feel free to create another issue with a reference to this one.
