### ISSUE TITLE
Include Simulations in Factor table

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#3062]
The "SimulationName" field is not included in PO tables which means the only way of identifying a simulation if read outside of the GUI (in python for example) is by "SimulationID"  To overcome this problem APSIM puts a Factors table (example of a factor table read into python below) in the data store which provides an extremely useful index for matching SimulationID to simulation name and other useful data in the Factors table.

However, simulations that are not part of an experiment don't appear in the Factors table so it is not possible to match simulation name to simulation ID outside of the GUI. 
Would it be possible to have single simulations included in the Factors table.  They would not have values in the ExperimentName, FactorName, or FactorValue columns but getting the other information is necessary.

![image](https://user-images.githubusercontent.com/7295858/45517620-da7ef980-b802-11e8-8624-a8d1155b3c47.png)

**Comment by hol430** [comment]
You should be able to get the name and ID of all simulations (even those outside of experiments) from the `_Simulations` table. Is this not working?

**Comment by HamishBrownPFR** [comment]
Yep its working.  Problem was I didn't know it existed.  Would it be possible to add Folder Name into the _Simulations table?
