### ISSUE TITLE
Unwanted return to origin of graph plots from multiple simulations generated by multiple factors 

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#3063]
When I select vary by "factor" from the legend creator, it fixes the problem  - but should it be happening in the first place?

**Comment by hol430** [comment]
I'm not convinced this is a bug. If you don't vary line type, marker type, or colour by either experiment, series, or cv, all of the data will appear in one big series. If the data is not supposed to appear in a single series, then the user needs to vary one of these properties. 

I can't think of a use case where someone would not want to vary any of these properties, but where they still get these lines returning to the origin:

![graphvarynone](https://user-images.githubusercontent.com/36427516/45604606-51bdc300-ba79-11e8-8678-e47b40cca6eb.PNG)
![graphvaryexperiment](https://user-images.githubusercontent.com/36427516/45604605-51bdc300-ba79-11e8-83bb-5c9c59cbb772.PNG)
