### ISSUE TITLE
plots wont generate from within field or simulation nodes when factors exist at the experiment node level

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#3064]
I can now understand why this occurs, but we wasted a lot of time before Drew managed to figure it out. Is there some way we can disable installation of graphs/plots in these nodes when factors are present - or simply allow the graphs to find the experiment names they need in parent nodes?
Alternatively you could put an error message in the plot window saying 'cannot find experiment names - try moving graph/plot to the experiment node'.

**Comment by hol430** [comment]
I think all that needs to happen here is that the graph/series needs to go looking for an experiment before it looks for a simulation. I will look into it.
