### ISSUE TITLE
Factor with one level

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3080]
Continue on #3043, this bug is still not fixed.

In the attached apsimx and screenshot. The table in the right should show the value of each level, not the factor name. 

![image](https://user-images.githubusercontent.com/1657381/45729360-84012900-bc0f-11e8-86ec-9fd4d4c6b535.png)

[factors.zip](https://github.com/APSIMInitiative/ApsimX/files/2395300/factors.zip)

**Comment by hol430** [comment]
Interesting - I'll look into it.
