### ISSUE TITLE
Unacceptable username and password while pushing changes

### ISSUE THREAD

**Issue by behnamxa** [APSIMInitiative/ApsimX#3087]
For a reason I cannot understand, I **can** commit my changes to local copies, but I **cannot** push them to the remote copies in SourceTree and I received this error and I am sure I am using the correct username and password (I don't have the same problem with GitHub Desktop):

```
git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --set-upstream Behnam ActualSoilWaterUptake:ActualSoilWaterUptake
fatal: HttpRequestException encountered.
   An error occurred while sending the request.

remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/behnamxa/ApsimX/'

Pushing to https://github.com/behnamxa/ApsimX
Completed with errors, see above.
```

**This is how I set up the repositories:**

![1](https://user-images.githubusercontent.com/39573622/45939516-73d5b900-c016-11e8-9839-80d7eb0c9cd6.png)

**Comment by hol430** [comment]
What happens if you go to `tools -> options -> git -> update embedded`? Does this fix the problem?
