### ISSUE TITLE
Cohort population vs max area in the flag leaf

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3090]
@HamishBrownPFR  In the leaf cohort model, FinalFraction is applied to reduce the max leaf area of flag leaf. Consequently, the maximum tiller number will be really sensitive to the time of terminal spikelet. 

I would suggest to reduce the cohort population of flag leaf, instead of max leaf area. The dynamic of flag leaf should be the same in the per square meter.

**Comment by HamishBrownPFR** [comment]
Hi @byzheng.  Sorry, I am not sure I follow your argument here.   Maximum tiller number is not a function of leaf area is it?  tillers are initiated by the structure class independent of leaf area.  
Neither what is implemented or what you suggest are ideal as in reality every plant has a flag leaf and  they have the same mean value so we should not alter area or population.  However, I am not sure what is a better solution.  We could initiate cohorts more often so we don't need to have a part final cohort to account for non-integer final leaf numbers.  The problem with this is it will slow the model down.  Not really sure what the best resolution is.
