### ISSUE TITLE
Accumulated variables by year

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/ApsimX#3132]
I am running a factorial simulation with more than one year, i.e. some simulations have 4, 5 and 6 years. I am using the ExtraVariables node to get accummulated irrigation and rainfall with the following scripts in the Harevest Report: 

[ExtraVariables].Script.AccumIrrigation
[ExtraVariables].Script.AccumRainfall

However, in the output file I can see just the accummulated in the simulation by year and not the accumulated by year, i.e. the second year has the amount of water of the first and second together. How can I ask just for the amount of water (rainfall and irrigation) by year in each simulation?

**Comment by hol353** [comment]
From the report documentation here: https://www.apsim.info/Report.aspx you could try:

Sum of [Weather].Rain from 1-Jan to 31-Dec as AnnualRainfall

**Comment by JJguri** [comment]
I got the AnnualRain with Sum of [Weather].Rain from [Potato].Sowing to [Potato].Harvesting as AccumRainfall.

For the accumulated irrigation during the season I tried with:
Sum of [AutomaticIrrigation].Amount from [Potato].Sowing to [Potato].Harvesting as AccumIrrigation
and
Sum of [ExtraVariables].Script.AccumIrrigation from [Potato].Sowing to [Potato].Harvesting as AccumIrrigation
but any of them works well.

**Comment by JJguri** [comment]
All done. Both working well!

Sum of [Weather].Rain from [Potato].Sowing to [Potato].Harvesting as InCropRain
Sum of [Irrigation].IrrigationApplied from [Potato].Sowing to [Potato].Harvesting as InCropIrrigation

**Comment by hol430** [comment]
Closing this now, since you've got this working. Feel free to re-open or continue the discussion if this is still an issue.

**Comment by JJguri** [comment]
Now I want to get the accumulated days of irrigation, i.e. number of days when irrigation was applied between sowing and harvesting. I tried Irrigation.Duration but it is a constant value.

**Comment by hol353** [comment]
There is no automated way to do that currently. You have two options:

1. Write a manager script (in c#) that keeps track of all irrigations and counts them up.
2. Do what a lot of people do and produce daily output files and post process them in another package/language like EXCEL / R / Python.

**Comment by JJguri** [comment]
Ok, thanks!

**Comment by JJguri** [comment]
I am using the automatic irrigation module. I fixed an irrigation efficiency of 0.85. I am obtaining Irrigation Applied (which would be the actual irrigation) and I am trying to get IrrigationTotal (before efficiency applied) as was mentioned here #2140. But [Irrigation].IrrigationTotal does not work. Should I specified some script related with the IrrigationTotal in the Automatic Irrigation module?

**Comment by hol353** [comment]
Report is capable of performing simple arithmetic so perhaps something like:

Irrigation.IrrigationApplied/0.85 as IrrigationTotal  
or
Irrigation.IrrigationApplied/Irrigation.Efficiency as IrrigationTotal 

Do either of these work?

**Comment by JJguri** [comment]
First script works well. With the second I got error because when the crop is not irrigated (0 mm), the efficiency is considered zero, therefore, the division is 0/0 and the model cannot create the report.

**Comment by hol430** [comment]
If your only problem is an unprotected divide, you could create a public property in a manager script, and report that property. The property could look something like:

```csharp
[Link] Irrigation Irrigation;

public double IrrigationTotal
{
    get
    {
        return Irrigation.Efficiency > 0 ? Irrigation.IrrigationApplied / Irrigation.Efficiency : 0;
    }
}
```

**Comment by JJguri** [comment]
I have created a new manager script (below) and I asked for [Irrigation].IrrigationApplied/[Irrigation].Efficiency as IrrigationTotal in the DailyReport:

using System;
using Models.Core;
using System.Collections.Generic;
using System.Text;
using Models.Soils;
using Models.PMF;
using Models;
using System.Xml.Serialization;
using APSIM.Shared.Utilities;

namespace Models
{
    [Serializable] 
    public class Script : Model
    {

		[Link] Irrigation Irrigation;

		public double IrrigationTotal

		{
    		get
    		{
            return Irrigation.Efficiency > 0 ? Irrigation.IrrigationApplied / Irrigation.Efficiency : 0;
            }
		}
	}
}

however, the following error still appears: 

System.Exception: ERROR in file: C:\Users\jjojeda\Dropbox\DATA\APSIM sim\Paper I.apsimx
Simulation name: Exp  WaterIrr  Weather91107 SoilBK
Divide by Zero. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Divide by Zero.
   at Models.Core.VariableExpression.get_Value()
   at Models.Report.ReportColumn.GetValue()
   at Models.Report.Report.DoOutput()
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Models.Core.Events.Publish(String eventName, Object[] args)
   at Models.Core.Runners.RunSimulation.Run(CancellationTokenSource cancelToken)
   --- End of inner exception stack trace ---
   at Models.Core.Runners.RunSimulation.Run(CancellationTokenSource cancelToken)
   at APSIM.Shared.Utilities.JobRunnerAsync.<>c__DisplayClass10_0.<JobRunnerThread>b__0()

**Comment by hol430** [comment]
In the daily report, instead of reporting `[Irrigation].IrrigationApplied/[Irrigation].Efficiency as IrrigationTotal`, try reporting:

```
[Name of manager script here].Script.IrrigationTotal as IrrigationTotal
```

**Comment by JJguri** [comment]
Perfect, it is working now!

**Comment by hol430** [comment]
Good to hear. Closing this issue now, since you've got this working. Feel free to re-open and/or continue the discussion if this is still an issue.

**Comment by JJguri** [comment]
How can I reopen this?, I tried last time but I could not because I have not created this.

Regards,
Jon

Dr Jonathan Ojeda
Junior Research Fellow – Agricultural Systems Modeller
Tasmanian Institute of Agriculture
University of Tasmania
Sandy Bay Campus
Hobart TAS 7005
+61 4 1756 5610
http://www.utas.edu.au/profiles/staff/tia/jonathan-ojeda
utas.edu.au/tia<http://www.utas.edu.au/tia/home>

[cid:image002.jpg@01D46617.4CC029D0]

TIA is a joint venture of the University of Tasmania and the Tasmanian Government

Recent publications:
-Ojeda et al (2018) Modelling inter-annual variation in dry matter yield and precipitation use efficiency of perennial pastures and annual forage crops sequences. Agric For Meteorol 259:1. doi:10.1016/j.agrformet.2018.04.014
-Ojeda et al (2018) Forage yield, water- and solar radiation-productivities of perennial pastures and annual crops sequences in the south-eastern Pampas of Argentina. Field Crops Res 221:19. doi:10.1016/j.fcr.2018.02.010.
-Ojeda et al (2018) Vertical distribution of root biomass and soil carbon stocks in forage cropping systems. Plant Soil. 423:175. doi:10.1007/s11104-017-3502-8.
-Ojeda et al (2018) Modelling forage yield and water productivity of continuous crop sequences in the Argentinian Pampas. Eur J Agron 92:84. doi:10.1016/j.eja.2017.10.004.
-Ojeda et al (2018) Modelling stover and grain yields, and subsurface artificial drainage from long-term corn rotations using APSIM. Agric Water Manag 195:154. doi:10.1016/j.agwat.2017.10.010.

**Comment by hol430** [comment]
The reopen button should be next to the comment button. If the button is not there, perhaps you do not have the needed permissions, due to your github account not being registered as a member of the APSIMInitiative organisation.

![image](https://user-images.githubusercontent.com/36427516/47057136-c7e15100-d202-11e8-8018-54a45bc2a102.png)

**Comment by JJguri** [comment]
Could I link my github account to be registered as a member of the APSIMInitiative organisation?

**Comment by hol353** [comment]
I don't think being a member of the APSIM Initiative organisation will help. See this thread:
https://github.com/isaacs/github/issues/583

It seems that if someone other than the original poster of an issue closes the issue then the original poster cannot reopen it. 

I'll reopen it now.

**Comment by JJguri** [comment]
Dean, thanks for the clarification. I just wanted to know for next open issues, I did not want to open again this issue. Thanks again.
