### ISSUE TITLE
Julian day as output

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/ApsimX#3171]
I am trying to get julian day as output of the simulations. I have looked in the Clock module but it is not a direct option in the lash

**Comment by hol430** [comment]
By Julian day, do you mean the day of the year? e.g. 11 for January 11, 42 for February 11, etc.

**Comment by hol430** [comment]
try reporting

```
[Clock].Today.DayOfYear
```

**Comment by JJguri** [comment]
perfect, it works, thanks
