### ISSUE TITLE
Name of "Plantain" model

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3178]
Plantain is one of the most important food crops across the world.  Some lists have it within the top ten food crops, after crops such as maize, wheat, soybean,  cassava, taro etc.  Annual production is over 34 million tonnes worldwide.  It is mostly eaten in Asia and West Africa. It is a plant very similar to common banana crops.
The Plantain model within APSIM is not this crop.  Plantain is the local name for a fodder crop in new zealand.  I am not sure how widely this name is used outside of new zealand.
In any case, I do wonder if the name of the model should be reconsidered at some point.  I know there is work from time to time on a banana model in APSIM.  I can see confusion from an international audience when banana means banana but plantain means a fodder crop.

**Comment by HamishBrownPFR** [comment]
Should we be using Latin names for crop models to avoid confusion from colloquial naming.

**Comment by rcichota** [comment]
@hol353 @hol430 
As I am going to be working on the Plantain model, I think we can tackle this issue. I am thinking in  renaming the model to 'PlantainForage', so we avoid much confusion with the Banana sibling as Neil pointed out.
The question is what it takes to do that? Where should I change the references to the plantain model?
I have just tried to rename all instances I could find in the json file in Resources and the test simulation, but when I run it, Apsim spits an error message saying it cannot find the model (or rather that PlantainForage doesn't have such and such variable). If I open the simulation and type PlantainForage on the report, for example, and then 'dot' I get access to all the variables... 
I search all APSIM directory for the word Plantain, but none other than simulations come with any relevant reference to Plantain. Nothing urgent, here, but I would like to do this before I, and colleagues, start using the model and then the name changes... maybe one of those conversion/updater thingys will have to be written?

**Comment by rcichota** [comment]
Correction. when using the Report to type PlantainForage and then 'dot', I get access to a number of variables, but not all, missing the organs... And I cannot visualise the model structure...
If I paste the json file in the replacements I can see all the structure, and the simulation works...
Must be something little I am missing

**Comment by hol353** [comment]
What you've done sounds right to me. Can you attach a simulation to this issue so I can have a look?

**Comment by rcichota** [comment]
Thanks @hol353 
I am working in the Tests\Validation\Plantain simulation. I have pushed into the save working branch you merged early on (https://github.com/rcichota/ApsimX/tree/Issue/FixPlantainSim%237207). Hopefully is easier for you to get it from there. 
I have it now with a 'copy' of it in the replacements, if that is deleted, I can no longer run the simulation...

**Comment by hol353** [comment]
Thanks I pulled your branch ok. I removed PlantainForage from replacements. When I run all sims in Tests\Validation\Plantain it runs correctly without errors.

![image](https://user-images.githubusercontent.com/1943827/161466739-5f976fcd-4561-4332-a7d5-ba103aeffd68.png)

**Comment by hol353** [comment]
Also, I notice on your branch you've changed a bunch of .apsimx files. You will probably need to write a converter instead. Otherwise users who are running a plantain simulation will suddenly find their sims don't run when they upgrade to a new version of APSIM.

**Comment by rcichota** [comment]
@hol353 
I am back working with Plantain. Me and Xiumei will be adding a few more datasets, but i would like to get this naming change done. How one goes about writing a converter?

**Comment by hol353** [comment]
You need to add a c# method to the ApsimX\Models\Core\ApsimFile\Converter.cs file. You also need to increment the version number at top of the file. Once you've got the converter working, upgrade all the resources files. There is a button in the GUI home page to do that. Then commit and create PR.

**Comment by rcichota** [comment]
Thanks @hol353 
I had chatted with Hamish at lunch time, and I think I got most things already. But missed the updating version... doing it now

**Comment by rcichota** [comment]
resolved by pull request #7605
