### ISSUE TITLE
Map doesn't work properly in auto-documentation

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3184]
The google map doesn't seem to zoom to an appropriate region of the globe when maps are inserted into auto-documentation.  The eucalyptus validation file inserts a map of Africa.  There are no experiments from Africa.

**Comment by hol430** [comment]
@hut104 if you change the zoom level on the map it appears to remember your selection:

![image](https://user-images.githubusercontent.com/36427516/64751885-04c3de00-d561-11e9-944b-43de6db1464c.png)

If you think this zoom level is ok then I'll commit the changed .apsimx file. Unfortunately the zoom increments are quite wide (they're integers internally) so zooming in any further than this causes some data points to be outside the bounds of the map. I guess you could put two maps into this file? One for Brazil, one for Australia.

**Comment by hol430** [comment]
My fix in #5126 seems to have broken the autodocs on Linux. No idea about mac.
