### ISSUE TITLE
Add <Polygon coordinates> and <Polygon area> fields to soil

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#32]
We are working on a tool that generates APSIM soil descriptions from the New Zealand soils database and are hoping for two new information fields on the APSIM soils front view:
1.	A <polygon coordinates> text field that contains northings and eastings of the area that the soil represents. 
2.	A <polygon area> double field that contains the area of the polygon.

**Comment by hut104** [comment]
The soil already has latitude and longitude included.

**Comment by HamishBrownPFR** [comment]
Which is fine if you consider the soil at a particular point.  However, if you consider that soil to represent an area then you want to know the boundaries of the area (polygon coordinates) and the size of the area

**Comment by fai04d** [comment]
Do you want code that will calculate the area or will you have that available already? Do you want the units to be m<sup>2</sup> or ha?
