### ISSUE TITLE
Move .apsimx files to JSON (rather than XML)

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#3215]
After profiling the slow startup times of the user interface and command line, we have decided to move to JSON as the file format for .apsimx files. The Newtonsoft JSON library for .NET is considerably faster at serialising /  deserialising JSON than the .NET XML serialisation.

**Comment by HamishBrownPFR** [comment]
@hol353 this may have a major impact on work @josharp22 is doing which involves creating large multi point simulation files from scripts outside of the UI.  I suspect there are others doing this to.  As part of this job can we test that the complex .xml files Jo has been making are properly can be easily converted to .json and still work properly after conversion.

I am guessing the converter will take an old .apsimx file and convert it to the new .json format but keen to be involved in the testing of this with a fairly complex test case.

**Comment by josharp22** [comment]
Thanks @HamishBrownPFR Yes, from the way it has been described, it would have an impact on quite a number of projects. Agree a robust test case would be essential.
@sno036 , @ed2014 and @rcichota may also be impacted by the proposed change.

**Comment by hol353** [comment]
Agreed that this will have a major impact on a lot of users and yes there is an XML to JSON converter that I wrote. I suggest:

1. You pull down my branch and test it on a **copy** of your files (remember it will change them to JSON).
2. OR send representative .apsimx files to me (or attach to this issue) and I'll check them.

**Comment by josharp22** [comment]
Hi
I'd like to propose that this issue should be labelled as 'Major' and go past the reference panel. 
It would also be great if we had a date in the future when the change would take place that would allow people time to change the tools they've developed to create and handle .apsimx files outside of the GUI.
Cheers
Jo

**Comment by HamishBrownPFR** [comment]
Is the converter a stand alone DLL that can be called by other software?  An issue here is that people who are creating xml from scripts are not using the interface so it would be useful if their scripts could continue to produce xml in the form they currently do and then call the converter to get it compatible with the current version of APSIM

**Comment by hol353** [comment]
It isn't currently a separate DLL. APSIM will continue to read existing XML for a long time yet (forever?). It only writes JSON though.

**Comment by HamishBrownPFR** [comment]
Sorry @hol353, my understanding of this is a bit light.  when you say apsim will continue to read XML for a long time do you mean the GUI will read it and convert it to JSON before running the model.  Or do you mean if you try to run apsim with an XML file from command line APSIM will still run it?  I.E if you are not running apsim via the GUI will it still work with XML

**Comment by hol353** [comment]
Both. The GUI will happily load and run it AND the command line will also happily load an XML file and run it. In the background a conversion from XML to JSON happens in memory.

**Comment by hol353** [comment]
Yes that is what I did initially and it does work but as soon as someone in the future changes a class (e.g. add, subtract a property, rename a class) then the serialisation breaks and we can no longer read in OLD XML files. It would also mean that we have to continue to create the serialisation DLL which gives us slow compiles in VS. Writing a JSON to XML converter gets around these problems.

**Comment by zur003** [comment]
Ah, right. It would mean any updating logic would have to update both JSON and XML, which would be a maintenance headache.

You actually wouldn't need to continue creating the serialization DLL, though; that's just an optimisation. Of course without it, reading in XML is very s........l.........o.........o.......o.......o.......w.

**Comment by hol353** [comment]
Note the pull request that is open against this issue has a lot of problems with it. Once it runs green on Jenkins then I'll be looking for some more test cases. Would be good to have ones that are a bit different in some way e.g. stock.

**Comment by zur003** [comment]
@hol353 - I'm happy to see this proceed, and agree with your position regarding the Reference Panel. This is an implementation issue (how do we serialize models?), not a modification of the models themselves. It's not very different from the question of whether we should use SQLite or Firebird for the datastore.
I'm looking forward to not waiting for the Models Serialization code to re-build on every compile!

**Comment by hol430** [comment]
All of the examples/tests/prototypes are still in xml. Is it worth committing json versions of these?

**Comment by hol353** [comment]
Yes I know. I didn't want to change them because of potential conflicts with others also modifying them. Need to be careful that no one else is fiddling with them before we do this.

**Comment by hol430** [comment]
@hol353 can this be closed now?
