### ISSUE TITLE
Unable to open database - Chinese username

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3219]
A user has demonstrated a situation where they were unable to run any simulations. The user had a chinese username, but changing it to english solved the problem.

**Comment by zur003** [comment]
I've submitted a pull request for a change in APSIM.Shared#62 that should fix this problem, and will allow databases to be created with international characters in their filenames.

**Comment by hol430** [comment]
Looks much more reliable than my short file name hack - I will remove this but keep the unit test.

**Comment by zur003** [comment]
Sounds good. Thanks. I did test this on Linux as well, and everything seemed to work correctly.
