### ISSUE TITLE
APSIM crash if a memo is attached to a manager

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#3230]
I wanted to add a more thorough description of a script manager that controls defoliation of PMF plants.  This would include rationale and usage instructions, so a bit too long to simply add to the code, so I wanted to use a memo. However, APSIM crashes badly, and/or does not save the added memo.  I tried this when the manager was in the 'Replacements' as well as within a simulations and APSIM always ended up crashing (though not always in the first try) and loosing anything added to it.

**Comment by hol430** [comment]
When does it crash for you? I've added a memo to a manager, run the simulations and successfully generated the documentation without a crash.

**Comment by zur003** [comment]
It's, at least in part, a deserialisation problem. Save your simulation, then re-open, and the memo will have "disappeared". That seems to be a problem at line 243 of Manager.cs, where ALL children of Manager are cleared, then the compiled Script child is added.

**Comment by hol430** [comment]
Yeah my pull request fixes that much, although I still haven't been able to reproduce the crash. Being unable to get Apsim to crash is a nice problem to have though.
