### ISSUE TITLE
Make Report properties tab the fist displayed

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#327]
Currently when you click on the report object the view it displays is the Data tab.  If there is alot of data in the datastore this takes along time to render and can even fail and close the simulations.  Can we make it so the properties tab is the one displayed when you click on the report module so it is possible to quickly view and change what is being reported without having to wait for the data tab to load before being able to change tabs

**Comment by HamishBrownPFR** [comment]
The test object has a similar problem, it tries to render everything in the datastore into its data grid and fails with large datastors

**Comment by fai04d** [comment]
I've added a limiter to the bottom of the report view so you can display X records at a time. There are also buttons to go forward and back through the data. This will stop the UI from trying to load very large data sets all at once.

The limiter can still be set to show all records at once by setting it to 0 or blank. The report will remember the number of records to display so you only need to set it once. It is specific to each report in a simulation.

At this point there is no 'go to end of data' button (well, there is but it's hidden) and the current page number is not shown as these require more information from the database for which the code does not exist at this point. If there is enough interest in these features I can add them, but for now I don't think it's worth the development time.
