### ISSUE TITLE
SoilArbitrator seems to be broken with multiple zones

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#3270]
@hut104 @HamishBrownPFR @hol353 

The testing of the SoilArbitrator that I completed in July (but never got committed for various reasons - yeah - I know!) is now broken.  This happened sometime between 5 July 2018 and now.  I've tagged the people that seem to have touched it since then.  This is only evident in the multi-zone testing.  

It might possibly be an AgPasture issue as I see someone from UQ\uqbababa (but I don't know who this is) has been modifying parts of AgPasture and AgPasture is used in the testing.

**Comment by sno036** [comment]
[SoilArbitratorTesting.zip](https://github.com/APSIMInitiative/ApsimX/files/2570425/SoilArbitratorTesting.zip)

This is the apsimx file in xml format

**Comment by behnamxa** [comment]
Hi @sno036. That guy's me :) I don't recall changing anything in **AgPasture** except that I suggested to add a new state variable **WaterDemand** to **ICanopy** to hold crop water demand (which is by default equal to **PotentialEP**, but in our photosynthesis model is calculated by the model and replaces the one calculated by **MicroClimate**). It does not even get assigned in **AgPasture**. It needed adding as it exists in the **ICanopy** interface. It's just there. And no problem was detected by the tests. Please let me know if you think I am the saboteur :)

**Comment by sno036** [comment]
Thanks @behnamxa.  We think we have tracked down the commit that did the deed (and that you are not the saboteur!) and are working on it.  Thanks for the info about Wheat and zones - we are not getting.  There is a test using PMF but I think what was only one zone so I'll add in a multi-zone PMF test once this gets sorted. Thanks for letting us know about the Wheat issue.

**Comment by rcichota** [comment]
Yes we've tracked down to some change I made while fixing issue #3188 
I reverted this and will re-send the appropriate changes in separate issues
