### ISSUE TITLE
Problem with factorial simulations when private fields were not used

### ISSUE THREAD

**Issue by behnamxa** [APSIMInitiative/ApsimX#3276]
When I did not use private fields to store the values of the public properties, I got strange results when factorial simulations were run simultaneously.

**Comment by hol430** [comment]
What do you mean by factorial simulations which were 'run simultaneously'?

**Comment by behnamxa** [comment]
Simulations with factors. I closed the issue following Dean's comments. It seems different simulations cannot access each other's variables. Cheers.
