### ISSUE TITLE
Initialisation of root in AgPasture needs some tidying up

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#3284]
Since work on , roots have become an List, and thus the parameters are initialised in a different way than the original, this is done for, and is also used for, splitting the roots in different soil zones. However this is a bit messy, there a few parameters that have not been transferred, some are transferred while adding a zone, etc.
The DoEndOrgan method is also a misnomer, it only transfers biomass to soil FOM...

**Comment by hol430** [comment]
Fixed by #3295
