### ISSUE TITLE
AgPasture crashing when biomass is very small

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#3296]
This was Identified by Mariana while converting the validation sets from Classic to ApsimX. The test for mass balance is done immediately after the organs are updated (by considering new growth and detachment). It is not clear why it breaks, and the errors are fairly small.  It probably is due to to some mistake done when the DoUpdate logic was transferred to Tissue (more calcs).

**Comment by rcichota** [comment]
This was indeed an issue with the logic to update the organs variable, in roots. A test was added to verify whether going through the layer was worth it: a significant DM or N amount. The problem is that the test was for AND, instead of OR...

**Comment by hol430** [comment]
Fixed by #3295
