### ISSUE TITLE
Is there a way to have more than one Replacements model?

### ISSUE THREAD

**Issue by behnamxa** [APSIMInitiative/ApsimX#3308]
I need to compare multiple photosynthesis models using the same validation dataset. I see that APSIM GUI cannot detect the **Replacements** models that are put in the same folder where the simulation rests. Is there any other way to have more than one **Replacements** model (and in turn Wheat models), so I can have more than one photosynthesis model in one APSIM file (by creating two identical simulations each using a different Wheat model)?

**Comment by behnamxa** [comment]
It did not work. It would be handy if we could either have **Replacements** models under each folder or could use the models as a factor. 

![image](https://user-images.githubusercontent.com/39573622/48811215-7c2d4480-ed78-11e8-8f6a-710ea9a91f97.png)

**Comment by hol430** [comment]
Does it work if you remove wheat from replacements?

**Comment by behnamxa** [comment]
Yes it works! I just need to remove the Wheat model from Replacements model. Disabling it doesn't work. Thanks.

**Comment by hol430** [comment]
Good to hear - I will close this issue now, but feel free to re-open if need be.
