### ISSUE TITLE
Arrays of dates - it would be nice if ...

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#3310]
I often seem to want to put several dates in as a user parameter in a Manger script (e.g. 15-jan 24-apr 14-aug) and then in the script test to see if Clock.Today matches any of those dates.  Sometimes the multiple dates include the year but often are just dd-mmm.  I clunkily pop the dates into an array and then cycle through each day checking.  There is likely a better way and someone much cleverer than I might be interested in adding it into all the other handy date handling things in DateUtilities.cs?

**Comment by hol430** [comment]
I was thinking the other day that at some point it might be nice to be able to enter lists/arrays into the properties tab of a manager script. I'm not sure what the UI would look like though. That said, if you've already setup your array of dates, you should be able to write something like

```csharp
if (arrayOfDates.Contains(Clock.Today))
{
    ...
}
```

**Comment by sno036** [comment]
Reading in arrays (I have not tried a list) is already possible. For example:
[Description("Enter the cutting dates as dd-mmm with comma separation: ")] public string[] CuttingDates { get; set; }
gives
[cid:image001.png@01D48251.540E4450]
in the properties and populates CuttingDates nicely without any more fuss. But as you can see, this is an array of strings not actual dates.  The reason I suggested something in DateUtilities was that ‘dates’ are often entered as dd-mmm without a year intentionally because they apply every year on that day.  DateUtilities contains a bunch of useful stuff to handle these types of dates without people like me trying to sort it out (which is very fortunate for everyone!).

**Comment by hol430** [comment]
The `DateUtilities.DatesEqual(string, DateTime)` method seems to do what you want:
```csharp
foreach (string ddMMM in ArrayOfDateStrings)
    if (DateUtilities.DatesEqual(ddMMM, Clock.Today))
        Summary.WriteMessage(this, "Today is one of the inputted days.");
```

The method accepts a string in dd-mmm format and a proper DateTime object (e.g. Clock.Today). It compares month and date but ignores year.

**Comment by sno036** [comment]
Thanks Drew - that works nicely and is cleaner than the approach I was taking.
