### ISSUE TITLE
The simulations "Under Review" do not appear in the performance tests

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3314]
It would appear that results for tests for models "Under Review" are not included in the performance test results.

**Comment by hol430** [comment]
My understanding is that the performance tests will look at all .apsimx files under the Tests directory, but it will ignore any file which is missing a `PredictedObserved` node.

**Comment by hol353** [comment]
Eucalyptus is under review. It has a predicted observed table. It isn't in the performance tests.
