### ISSUE TITLE
Calculating cumulative value of traits in daily reports

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3316]
I have been trying to use a script like this (just an example):

`Sum of [Wheat].Structure.ThermalTime from [Clock].StartOfSimulation to [Clock].Today as Test
`

to calculate the cumulative values of a daily output variable, but I failed. Is there any way to do this without needing to use a manager script, add that variable to the code or add a new arithmetic function to **ApplyAggregation** in **APSIM.Shared**?

**Comment by hol430** [comment]
This should work - looks like there is a bug here though. I'll look into it.

**Comment by sno036** [comment]
Just bumping this up the priority list. Most things seem to be working well but the aggregation using "Today" is not and it would also be really handy to add something that did an aggregation (Sum, Diff, Ave - as in the documentation) from whenever the last report was done (only of this particular Report model remembering that there can be multiple Reports in a single simulation) to Today. Having these would allow dumping a bunchy of Managers that are only there to do these sorts of calculations.  

Sum of [Weather]Rain from [Clock].StartOfSimulation to [Clock].Today as CumRain
Sum of [Weather]Rain from _LastReport_ to [Clock].Today as SumRain
