### ISSUE TITLE
Column labelled as containing 'error' (i.e. variability) data triggering duplicate heading error

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#3318]
[From_Dean.zip](https://github.com/APSIMInitiative/ApsimX/files/2609537/From_Dean.zip)
"ProfileWaterError" didn't trigger the problem.
But "Soil.SoilWater.SW(1)Error" did.
Sim attached - run 'Bremar' in SEQ.

**Comment by hol430** [comment]
Closing this as I can no longer reproduce the error and I doubt Allan remembers it; there appear to be a number of parametrisation issues with this early version of the chickpea model which prevent it from running properly.
