### ISSUE TITLE
simple way to reset SW from within soil?

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#3320]
Rather than using a manager script, it would be 'user friendly' if another node could be added to the soil file to reset various soil attributes on a date. Particularly N and Soilwater. Could simply be the same type of node as the 'initial water' node, with a date box (ideally in the title) to specify the date of reset, and an option to recur (either on the same DOY or event i.e. sowing)

**Comment by hol430** [comment]
This can already be done - you can drop a 'reset on date' script from the management toolbox. It has an option for date, and an option to reset N and/or water.
