### ISSUE TITLE
would be handy to view multiple time series graphs from different simulations in one place

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#3326]
Would be a useful feature for a model builder for sure if we could have a way to put a set of graphs on a page that have come from different simulations. Would probably have other applications as well, not just in model construction but for anyone attempting to model experiments, can be useful to see multiple time series from multiple experiments, all in one place

**Comment by hol430** [comment]
This can be done if you put your graphs under a god-level folder.
