### ISSUE TITLE
Ctrl-c in units grid cell causes fatal error in APSIM UI

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#334]

**Comment by fai04d** [comment]
Need more information. I was able to copy from water, nitrogen, manager scripts, micro climate and reports and confirm the copy worked by pasting the data elsewhere. I did not experience any errors.

**Comment by hol353** [comment]
Neil was trying to copy from the 'units' cell under phenology phase targets under Replacements in Teff.apsimx file.
