### ISSUE TITLE
Can the display of PAWC in the Water node be made 'live'?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#3346]
Can the display of PAWC in the Water node be made 'live'? So that users do not have to click away and back to see the updated calculation.

**Comment by hol430** [comment]
This seems to be live for me...are you talking about the PAWC column in a soil water node?
![livepawc](https://user-images.githubusercontent.com/36427516/49490709-ea0b5d00-f89c-11e8-912f-b238a0bafa9b.gif)

**Comment by hol353** [comment]
That's cool. An animated GIF.

**Comment by hol430** [comment]
Yeah, thought I'd try it out. Easier than typing a small novel in some cases

**Comment by jbrider** [comment]
Have you seen the new version of coderush at all - it can do embedded images within code.
Looks brilliant for documentation, need coderush to view it though I believe.

[embedded-images-inside-source-code](https://community.devexpress.com/blogs/markmiller/archive/2018/09/11/holy-grail-embedded-images-inside-source-code.aspx)
