### ISSUE TITLE
Images in memos don't work on Ubuntu

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3349]
If an Ubuntu user attempts to embed an image in a memo, the image is not displayed in the memo view. e.g. 

```
![alt text](SoltaniChickpeaPhenology.PNG)
```

**Comment by zur003** [comment]
Memo images are a bit broken in any case. In my opinion, it should be possible to specify an external URL (for example, http://blend-bp.nexus.csiro.au/images/csiro_logo.jpg) as the image source, but I think we're currently assuming the image is embedded as a resource.

I'm not sure why image display is not working on Ubuntu. The image file is extracted correctly, but the WebKit browser isn't rendering it. The same apples to OS X as well.
