### ISSUE TITLE
Running multiple APSIM file in command line in one call

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3351]
With old APSIM, it was possible to put the names of multiple APSIM/SIM files on the command line or in an ascii file to run all with one call of APSIM. Is it possible with APSIM-NG? I cannot find any option for that.

![image](https://user-images.githubusercontent.com/39573622/49420204-114b2700-f7d6-11e8-979c-d162d7569e1c.png)

**Comment by hol430** [comment]
Pretty sure Apsim only looks for one file specification, but this specification may contain a wildcard. e.g. If you move file1.apsimx and file2.apsimx into a single directory, you can run:

```
Models.exe Directory/*.apsimx
```

You can also add the `/Recurse` option to run files in all subdirectories as well.

**Comment by BenAbabaei** [comment]
Thanks Drew. I'll close the thread then. Cheers.
