### ISSUE TITLE
run APSIM NG in NeCTAR

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/ApsimX#3352]
I am trying to use APSIM NG in a Virtual Machine that run within the National Research Cloud (NeCTAR) for Australia. I already created an instance in the cloud but I do not know how to proceed. Do any of you know about a tutorial or have experience doing this?

**Comment by hol430** [comment]
Do you know which operating system your VM is running (e.g. Windows/Ubuntu/Fedora etc)?

**Comment by JJguri** [comment]
Ubuntu

**Comment by JJguri** [comment]
Recently, the NeCTAR team told me I could use Windows. Does this make the work simpler? For the moment I can manage the amount of simulations, but probably in the near future I will need to get more cores to do it.

**Comment by hol430** [comment]
If you're happy using Ubuntu and don't need a GUI it should be fairly painless:

1. Get a link to the Debian installer by registering on our [registration page](https://www.apsim.info/APSIM.Registration.Portal/Main.aspx)
2. Download the installer; Run this command (on the VM), replacing download_url with the download link provided in the email from the registration system:
```bash
wget download_url -O apsim.deb
```
3. Install Apsim
```bash
sudo dpkg -i ./apsim.deb
```
4. dpkg should complain about missing dependencies. This can be resolved by running
```bash
sudo apt-get -f install
```
At this point you should be golden. You can run your simulations with the Models command:

```bash
Models ./mySimulation.apsimx
```
