### ISSUE TITLE
SoluteManager is not treating fertilisers consistently with the rest of APSIM - danger ahead!

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#3353]
@hol353  (I was going to tag it as major but it is important, and perhaps urgent, rather than major)

The SoluteManager.Add method thingo does not recognise UreaN, NH4N or NO3N but is adding Urea, NH4 and NO3 as an N content rather than the fertiliser.  E.g. adding 100 kg of Urea adds 100 kg on N rather than 46 kg N.  This is inconsistent with the treatment of NO3 v's NO3N (for example) elsewhere in APSIM and is very likely to cause grief.

SoluteManager is relatively new? If so then I recommend/request that it gets changed to be consistent with the rest of APSIM soon before the effects are too pervasive. It is likely to be used in simulations not under version control so a warning message to all users would be helpful.

I've looked at the SoluteManager code and fixing this is beyond my capabilities!!

**Comment by hol353** [comment]
SoluteManager no longer exists. Problem solved?
