### ISSUE TITLE
Need a solid example for Stock with documentation

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#3360]

**Comment by sno036** [comment]
@APSIMInitiative/stock-and-related-matters 

Can we use GitHub Teams to get more targeted emails out to people? I tried looking at Projects and while they might be useful I don't see that they could be used to manage notifications.

**Comment by sno036** [comment]
And again

**Comment by sno036** [comment]
[StartersForStockExample.zip](https://github.com/APSIMInitiative/ApsimX/files/3872308/StartersForStockExample.zip)

Starting points for the example

**Comment by sno036** [comment]
Include a conservation manager in the examples.

**Comment by sno036** [comment]
Need several simple - how to - examples

**Comment by her123** [comment]
1. Sheep grazing wheat and moving feedlot (DH)
2. Cows on Plantain (Val to check and document)
3. Three paddock rotation of cows (Val)

Documentation required in memos for these:
- Simulation explanation
- Scripts
- Interpret charts
- Reports commented

**Comment by hol353** [comment]
Closing this as STOCK is now under review with validation, sensibility and examples.
