### ISSUE TITLE
Issues when transferring old-APSIM soils into APSIM-NG

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3370]
Soils can be successfully copied and pasted from old APSIM to APSIM-NG. But there are a few things that need to be done/fixed manually.

- APSIM-NG stores the parameter **RelativeTo** of the **InitialWater** model in uppercase (e.g. 'LL15') while it is stored in lowercase by old APSIM (e.g. 'll15') and it needs to be fixed manually.

- The **SoilCrop** model under the **Water** model in APSIM must be re-named to **WheatSoil** or [CropName]Soil when moving to APSIM-NG. 

- It would be handy if APSIM-NG would automatically add **CERESSoilTemperature** and **SoilNitrogen** models if they are missing (and they are missing in old APSIM soils).

**Comment by hol430** [comment]
What other values can be held in `RelativeTo`? e.g. Do we need to replace "ll15" with "LL15" or do we just need to convert this parameter to upper case regardless of what it holds?

**Comment by BenAbabaei** [comment]
These are the values in NextGen. I remember **ll15** needed changing to **LL15**. In old APSIM there is no **WheatSoil**. There is only **CropSoil**.

![image](https://user-images.githubusercontent.com/39573622/50619426-ea9f1e00-0f44-11e9-838f-f266b0c1c8e4.png)

**Comment by BenAbabaei** [comment]
A screen shot from old APSIM. As I mentioned before, there are two options, ll15 and [cropName].

![image](https://user-images.githubusercontent.com/39573622/50634049-1ba93e00-0f99-11e9-9819-71ba275d56a0.png)

**Comment by hol430** [comment]
#3398 will fix these problems. I've also added some code to the Soil model's `OnCreated()` method. A `SoilNitrogen` model will be added if the soil has no `INutrient` model, and a `CERESSoilTemperature` model will be added if the soil has no `ISoilTemperature` model. This code will run when a `Soil` model is added (via the add model button), pasted, or read in from a file. Might have been better to only add these models when pasting a soil, but I couldn't think of a good way to manage that. 

This behaviour may need to be reworked when the `Nutrient` model is finished.

**Comment by hol430** [comment]
Need to talk to @hol353 about one of the changes in my pull request. Once I've done that I'll merge it and close the issue.
