### ISSUE TITLE
Reading and writing APSIM JSON files with R

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3371]
When I read an APSIM file using the function **fromJSON** in the **rjson** R package and then (without any change) export it to a file using the functions **toJason** and **write**, the file cannot be imported into APSIM interface and I get his error:
**_Could not cast or convert from System.String to System.String[]._**

It seems that this package puts [Clock].DoReport in one line as a character string and not a vector. 

**APSIM-NG:**
```
"EventNames": [
"[Clock].DoReport"
],
```

**R:**
`           "EventNames":"[Clock].DoReport",
`

Even when I fix that, there are still other problems with other **Events** and then:
**_Could not cast or convert from System.String to System.Collections.Generic.List`1[System.String]._**

I am not sure if there are other issues in the final file. Is there any trick here to write APSIM files? What is the best way to, for example, add a block to these files? I also tried the package **jsonlite**. The same.

**Comment by hol430** [comment]
@hol353

**Comment by hol353** [comment]
I know nothing about other JSON packages. I do know that 

"EventNames": [
"[Clock].DoReport"
],

is correct syntax given that EventNames is a list of strings that in this case has one element.
