### ISSUE TITLE
The function 'MathUtilities.Sum' does not include the last index

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3372]
In the function **MathUtilities.Sum**, last index is never included in the summation. When **iIndex** reaches **iEndIndex**, the result is returned without accounting for the last value.

```
public static double Sum(IEnumerable Values, int iStartIndex, int iEndIndex,
                                double dInitialValue)
        {
            double result = dInitialValue;
            if (iStartIndex < 0)
                throw new Exception("MathUtilities.Sum: End index or start index is out of range");
            int iIndex = 0;
            foreach (double Value in Values)
            {
                if (iIndex >= iEndIndex)
                    return result;
                if (iIndex >= iStartIndex && Value != MissingValue)
                    result += Value;
                iIndex++;
            }
            return result;
        }
```

**Comment by rcichota** [comment]
@BenAbabaei , wondering why did you close this issue, I just came across the same problem (or I am interpreting something wrong?)

**Comment by her123** [comment]
It appears that this function is only every used in relation to soil layers. It should be named for that use and not named in generic terms that lead to confusion.

**Comment by BenAbabaei** [comment]
Dean told me that it was intentional. I still think it should be changed. You can see my other issue about auto-Irrigation manager.

**Comment by rcichota** [comment]
Thanks @BenAbabaei and @her123 
I believe this may be code from Classic (array with base 1?). I think we could create a more generic Sum that could be used for any array. This can be a useful function in manager scripts...

**Comment by BenAbabaei** [comment]
Like I said, as my suggestion was rejected once, I'd rather leave it to you guys and @hol430. Cheers.

**Comment by rcichota** [comment]
Hi @BenAbabaei 
I have added an override Sum() function that should do what you (and I) wanted. It takes only three parameters: the array, the initial index, and the final index over which the sum is performed - both inclusively)
This do not change any use of the older version, so the irrigation script you mentioned still has the problem of not considering the correct layers, but it could be fixed using the new version of the function...

**Comment by BenAbabaei** [comment]
Thanks @rcichota . I did the same thing a while ago but my commit wasn't merged by the admins. I hope yours is. Cheers. B.

**Comment by hol430** [comment]
@rcichota has your modified Sum() function been merged?

**Comment by rcichota** [comment]
Hi  @BenAbabaei 
just confirming that the alternative Sum() method has been merged.

**Comment by hol430** [comment]
Ah ok. @BenAbabaei see APSIMInitiative/APSIM.Shared#75 for details. Closing this issue now.
