### ISSUE TITLE
CO2 effect on Gsmax from Leaf Component

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3382]
There should be an effect of CO2 on the gsmax value provided to micromet.  The modifier should perhaps adjust gsmax relative to a reference value of approximately 350 given the timeframe of the underlying work on the gsmax model and parameters used (ie from Kelliher et al) and the assumptions that are already in the RUE model (which is itself relative to 350 ppm).

**Comment by ric394** [comment]
This is very old. 
Closing. 
If this is still an issue, please feel free to create another issue with a reference to this one.
