### ISSUE TITLE
Make Morris Method more flexible for users

### ISSUE THREAD

**Issue by LauraGagresearch** [APSIMInitiative/ApsimX#3391]
Allow Morris example to have reports not named Report and better include better reporting of errors surrounding this - I will do some work on this

**Comment by FlorjanCamlek** [comment]
I am also working on some documentation for the Morris method.
@hut104 Just FYI.
@sno036

**Comment by hol430** [comment]
@sno036 @LauraGagresearch is this finished?

**Comment by sno036** [comment]
I think it is - at least functionally so.
