### ISSUE TITLE
Accessing data from multiple simulations

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#3401]
As discussed with Drew .... I'd like to be able to do a numerical (e.g. regression) or logical test across data from multiple simulations.  This would aid sensibility testing for starters.  A simple example would be a simulation with an Experiment node in which the factors are increasing the amount of water available to the plant.  Across those simulations we should see a consistent pattern of behaviour and the point of interest is the general pattern (increasing, decreasing, parabolic, asymptotic) rather than the actual values. While these patterns can be graphed it does not seem to be possible to do anything like calculating a regression in a script or indicating that a test has passed or failed with it.  This would be a useful feature.

**Comment by hol430** [comment]
@sno036 can this issue be closed, or is there more work to be done here?

**Comment by sno036** [comment]
Great thanks.
