### ISSUE TITLE
Need to make APSIM version more visible

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#3405]
There are many cases (e.g. publication) in which we need to point out which version/build of APSIM we used (and to ensure we can eventually go back and reproduce simulations if needed). This info currently is currently written down in the summary file, but from the user interface there is no way to quickly (and intuitively) tell which version one is running.  An extension of the help button, for example, could include the options to show the documentations - as it is now - or to simply inform what version of APSIM is being used. A behavior that is typical in most applications...
When APSIM is compiled by the user, no version number is given (as @zur003 explained in #2473), which is unfortunate, though understandable, and at least the date of compilation is written in the summary file. If one uses a release version, the number is available and both it and the compile date are written in the summary (which makes me think I should use those for work to be published).
Now, we're running APSIM in our computer cluster here, where a release version of APSIM is installed, it took us a little while to figure out what was that version (hence it would be good to have a simple and intuitive way to get to it). and we had no quick answer to the cluster administrator as to which version we wanted added to it. This becomes important as we want/need to run different versions (due to different project timing), thus quickly recognizing what version we're at allows smooth changes...
In addition to this it would be great to be able to check what releases are out there in case we need/want to get to a given version different than the latest (this parallels to issue #1652). It would be great if we have a webpage with such list (like the one for Bob in APSIM classic). If the number of releases is proportional to merged pull requests than the list would become large quickly, so maybe limit this to one a day, or week...?  
Moreover, the actual version number seems to be best show as "2018.09.28.3099", instead of simply "3099". which is what is shown when one looks for the latest version...

**Comment by hol430** [comment]
When running a released version, the version string is written in the title bar at the top of the screen:

![image](https://user-images.githubusercontent.com/36427516/50809097-53bfd080-134d-11e9-9e6a-f32190018cde.png)

If you're running from the command line you can use the version switch:

```
C:\ApsimX>models /Version
Version 0.0.0.0, built 2019-01-08
```

With regards to a downgrade option, I was discussing this with @hol353 towards the end of last year and we came to the conclusion that this would be a good feature to add. What we had in mind was a checkbox in the upgrade form which has the option to show older releases. This would be unchecked by default, so normally you will only see upgrades. I ran out of time to implement this last year but I will see if I can get this done today or later this week.

**Comment by rcichota** [comment]
Thanks, 
I did not notice the title bar thing (as I only have the development version in my personal PC), the command line command is helpful, will add to my list of tips. and I will be looking forward to have the possibility to upgrade/downgrade the version running in an easy.
I still think it would be good to have the list of available releases in a webpage (especially if the development version would not show said list - I'm assuming that as it is not possible now to upgrade a user-compiled version - for obvious reasons).  Plus such list could have the quick description of the changes in that version (the comment given for the pull request, or something like that - I know I am being very optimistic here). We get these questions often, but it is not easy to answer as the solution you pointed out are not available in the development version, or not intuitive.

**Comment by hol430** [comment]
Yeah it would be nice to have a page similar to Apsim Classic's [Build page](https://www.apsim.info/APSIM.Builds.Portal/Bob.aspx). If I find time I will see what I can do.

In a pinch, it is possible to give your custom build a "version". This will trick Apsim into thinking you're on a released version which will allow you to open the upgrade form. All you have to do is edit the file `ApsimX/Models/Properties/AssemblyVersion.cs`. If you open the file, the changes you need to make should be self-explanatory; you just need to change it to look something like this:

```csharp
using System.Reflection;
[assembly: AssemblyTitle("APSIM 2019.01.02.3393")]
[assembly: AssemblyVersion("2019.01.02.3393")]
[assembly: AssemblyFileVersion("2019.01.02.3393")]
```
