### ISSUE TITLE
Trouble Inserting Images into Memo/Autodocs

### ISSUE THREAD

**Issue by FlorjanCamlek** [APSIMInitiative/ApsimX#3412]
I have managed to insert an image into the memo using Markdown (and it displays correctly), but when I try to generate the documentation, the image source file appears to get overwritten with an empty file of the same name, and the following error displays:

Unable to locate resource \resourcepath

The documentation does not get generated. This is on a Windows system.

**Comment by hol430** [comment]
Have you added the image as an embedded resource to the ApsimNG assembly?

**Comment by FlorjanCamlek** [comment]
No I hadn't and that fixed the problem, thanks. It might be useful to add this information into the image section of the memo/markdown page (https://apsimnextgeneration.netlify.com/usage/memo/).
