### ISSUE TITLE
CLEM post-merge bug fixes

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#3427]
A number of issues have been raised since merging CLEM into APSIM.

**Comment by hol353** [comment]
In future, I'd prefer a more specific description of the bugs rather than 'A number of issues have been raised...' That way we keep track of what has been fixed. Also better to have smaller, more frequent, pull requests that address a single issue.

**Comment by lie112** [comment]
OK. I wasn't sure during this stage. I am probably working on 10-20 issues a day as reported by those testing. After this stage development will be on individual components. I didn't want to appear to swamp the issues page with CLEM commits.
