### ISSUE TITLE
When copying / pasting / importing a soil from old apsim need to remove bad soil layers.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#3457]
The attached soil has bad soil layers in the Sample. We don't want these brought into APSIM Next Gen.
[Yeelanna_2016_Ex2_newsoil.zip](https://github.com/APSIMInitiative/ApsimX/files/2789995/Yeelanna_2016_Ex2_newsoil.zip)

**Comment by hol430** [comment]
What's the problem here? Is the depth column supposed to be the first on the left?

**Comment by hol353** [comment]
The problem is that in the GUI when clicking on InitialNitrogen, it looks fine but the JSON in the .apsimx file shows there are 2 layers that have a thickness of 999999 and NaN's for the values. e.g.

---
                  "$type": "Models.Soils.Sample, Models",
                  "Thickness": [
                    100.0,
                    200.0,
                    300.0,
                    300.0,
                    300.0,
                    500.0,
                    999999.0,
                    999999.0
                  ],
                  "NO3": [
                    9.1,
                    6.8,
                    2.9,
                    1.0,
                    2.3,
                    2.2,
                    "NaN",
                    "NaN"
                  ],
---

**Comment by hol430** [comment]
These values exist in the original .apsim file you posted - we're just copying and pasting the faulty data. Is this really a problem with Apsim?

**Comment by hol353** [comment]
Yes it is a problem with old APSIM but while importing the data into new APSIM it would be good to get rid of faulty data. Otherwise, the simulations don't run properly and it isn't obvious where the problem is.
