### ISSUE TITLE
when importing soil from 'Classic' currently CLL is incorrectly named

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#3459]
CLL is being imported into NextGen and named e.g. 'wheat' or 'sorghum' but actually needs to be called 'WheatSoil' or 'SorghumSoil'

**Comment by hol430** [comment]
Can you upload the soil you were trying to copy?

**Comment by AllanPeake** [comment]
Just in a meeting.

Any soil in APSIM classic will do it if you import into NextGen.

**Comment by hol430** [comment]
I just tried a few soils from the soils toolbox in old Apsim, and they all seem to work ok:

![image](https://user-images.githubusercontent.com/36427516/52313702-34bf6780-29fb-11e9-9aea-c0d4a5c876fc.png)
