### ISSUE TITLE
New Canola Model

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3467]
A model is to be developed for _Brassica napus_ (Canola) for use in APSIM Next Generation.  This will use test data from APSIM version 7.10, but incorporate new phenological understanding from current research projects.  New data will be incorporated from current canola agronomic projects.  
The model is to be developed using PMF.
The phenology model will be very similar to the canola model in APSIM classic, but with the improvements included in the Brassica oleracea var. italica (Broccoli) model in APSIM classic.  
Datasets from APSIM Classic test set are being converted to NG and new datasets from existing CSIRO projects are also to be added.  The model will use the newer approaches currently in NG for canopy development etc.  Oil modelling will benefit from current developments for soybean.
Involvement of CSIRO canola project leaders will ensure that the model is developed for current emerging areas, such as links to genetic work.

**Comment by sarahcleary** [comment]
@JackieOuzman

**Comment by hut104** [comment]
Please find the attached presentation and auto-documentation file (both in PDF format) for the canola model review (7-June-2022).  Note that the autodocumentation software appears to have a few deficiencies at this point in time.

[APSIM NG Canola Model Presentation.pdf](https://github.com/APSIMInitiative/ApsimX/files/8840960/APSIM.NG.Canola.Model.Presentation.pdf)

[Canola.pdf](https://github.com/APSIMInitiative/ApsimX/files/8840970/Canola.pdf)

**Comment by jbrider** [comment]
Little things...
- Grazing example has a full copy of the Model rather than referencing replacements?
- In Phenology in MidGrainFilling and LateGrainFilling there is a ThermalTimeNew.
  - As they are identical, would it be better to have a VariableReference to a ThermalTimeNew (or better name) that is located with the other ThermalTime related variables at the root of Phenology?
- In Leaf there are 3 Plastochron's - remove the 2 extra ones?
- In Leaf -> Branching Rate there is a memo that has "From Hammer Paper"
- In Stem there is a disabled DMDemandsOLD
- Quite a few empty Memo's.

**Comment by jbrider** [comment]
In Validation
- Phenology Experiments - Omics Phenology - Gatton 2019 - Phenology
  - Selecting Phenology shows several blank charts
  - EmergenceDAS has -ve values?
  - GreenBudDAS has -ve values?

- Phenology Experiments - Omics Phenology - Leaf Appearance PvO
  - Leaf Appearance appears to have a hard limit of 8?

**Comment by hut104** [comment]
Responses to requests.

- Grazing sensibility test changed to use Canola resource
- ThermalTimeNew was deleted in two places
- Two plastochron functions deleted
- Memos removed
- disabled DMDemands function deleted
- One blank chart removed, others repaired.
- -ve values are for underprediction on graphs showing (pre-obs vs obs)
- Memo changed to explain that leaf appearance was only measured to leaf 6
- Generic Cultivars (early, late, winter) added. The choice of cultivar follows from those used in Lilley et al "Defining optimal sowing and flowering periods for canola in Australia"
- Graze and Prune removed from biomass removal objects in each organ within Canola
- Grazing example has been added to examples folder
- Simple example has been added to examples folder
- Sensibility test for generic cultivars x TOS added

**Comment by hol353** [comment]
@APSIMInitiative/reference-panel : Neil has addressed the canola review issues. Is this ready for merging into release?

**Comment by sarchontoulis** [comment]
Thanks @hut104 for addressing the comments. I would like to suggest a deadline of end of the week for RP members to make any further suggestions before the canola model gets into release.
