### ISSUE TITLE
Chart legend not cleaning up after itself

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#3471]
Changing the Data Source for a series from 1 excel file to another excel file results in entries in the legend for both excel files.  
Issue persists after a program restart, so most likely not clearing previous series on the combo selection of the 2nd excel file.

**Comment by hol430** [comment]
This seems to work ok for me...do you have an example .apsimx file which reproduces this problem?

**Comment by jbrider** [comment]
If the image shows up - I thought it might be saving old data in the series settings - but this is a brand new chart.  It's showing 4 legend entries for 1 series. The first one is another imported excel file that isn't set as the data source.  I have noticed it since the json conversion, but it could have been doing it before.
This is inside the sorghum prototype, in the process of committing the latest version of that file... 

![image](https://user-images.githubusercontent.com/635772/52540943-20a0af00-2ddb-11e9-80bd-ffb6ffbf7cbe.png)

**Comment by jbrider** [comment]
The problem is still there.
Where there is more than one excel file available in the datastore it seems to get confused.
SorghumLeaf in the sorghum prototype folder is full of good examples.

**Comment by hol430** [comment]
#3527 did indeed fix this but it appears to have caused a lot of problems elsewhere. I'm re-opening this so I can revert the change and find a better solution.

**Comment by hol353** [comment]
Had another look at this and can't reproduce it:
![image](https://user-images.githubusercontent.com/1943827/55917308-4b1fb480-5c32-11e9-880c-f81ae4962bfb.png)
If I get rid of the 'Vary by SimulationName' then it shows only one series with one legend entry 'Series'

**Comment by jbrider** [comment]
I'll try clearing it and see if it fixes it.
Didn't think of it yesterday until after I had gone back a couple of commits to get a working graph.
