### ISSUE TITLE
We need a tool to convert soils from xml to json

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#3475]
We all have libraries with soil data developed over time, these currently are all in xml format (either from classic Apsim/Apsoil or earlier versions of ApsimX). It would be great if we had a tool to convert this soil information into json, especially when using batch runs.  @hol353 commented that it should be possible to "add a command line switch to models.exe that converts a apsimx file to the latest version". This could then be used to convert a soils library.

**Comment by hol430** [comment]
Re-opening, as this feature currently doesn't allow for files which don't contain a top-level simulations object.
