### ISSUE TITLE
ApsimX running time is getting slower? 

### ISSUE THREAD

**Issue by ianzhangtianyi** [APSIMInitiative/ApsimX#3479]
Dear all, 

I am calling the model.exe in ApsimX using R (using the CMD to call Models.exe) because I need to generate many . apsimx files and call apsimX model to calculate yields. It works very well at beginning but it is getting slower when I runed it >500 times. Now the running time is twice than ealier. I think the problem is the time to read JSON is slower but the time for model simulation is similar because R said "simulation complete time" is only 1.0 second but the "finished running simulations. Duration" time is getting increased.   I don't think the apsimx files I generated is getting longer because it is in the same length for each run. 

I also tried to re-compile the model but the problem still exists, which really confused me. 

Tianyi

**Comment by ianzhangtianyi** [comment]
This is solved. This is because there are too many temporary files created by ApsimX app. I just need to remove them.

**Comment by hol430** [comment]
Are you able to upload one of your .apsimx files? We ran into this problem a while ago, but I thought it was more or less fixed.
