### ISSUE TITLE
met file error could produce better error message to diagnose location of problem

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#3488]
[Hart_modified_CombGSE2.txt](https://github.com/APSIMInitiative/ApsimX/files/2839017/Hart_modified_CombGSE2.txt)

The attached met file is producing the following error message.

Cannot cast DBNull.Value to type 'System.Single'. Please use a nullable type

There is clearly an error within the met file (some missing temp data represented by hyphens in 2016 day 259-267

) - but it would be nice if the error message could report the line where the problem exists.

**Comment by hol430** [comment]
Is "222022-GSE_Radn" valid data for the Code column?

**Comment by AllanPeake** [comment]
It works OK in other met files, surprisingly.

**Comment by hol430** [comment]
Interesting....*should* it work? Or should we just throw an error in this scenario? With a decent error message it shouldn't be hard to track down the problem.

**Comment by AllanPeake** [comment]
I don’t think we want more error messages than we already have – so I think we ought to leave that be!

**Comment by sno036** [comment]
It would be nice if it gave a date or something to locate the issue ...

**Comment by hol430** [comment]
From an implementation perspective, it will be much easier to provide a date than a line number if we want to ignore faulty data in the code column of a met file. On the other hand, is a date as useful as a line number? For a large file it could still take a few seconds for a user to find the faulty row of data.

**Comment by hol430** [comment]
@sno036 @AllanPeake is this enough information?

```
Invalid data in column maxt on date 15/05/2016 (day of year = 136)
```

If I open notepad++ and search for "2016 136" it takes me straight to the faulty data.

**Comment by AllanPeake** [comment]
Looks good!

A
