### ISSUE TITLE
Addition of new sensitivity analysis model

### ISSUE THREAD

**Issue by FlorjanCamlek** [APSIMInitiative/ApsimX#3494]
I will add in a new model that facilitates a factorial ANOVA analysis. Model collects data at the end of an experiment run, sends it to R, and returns the results.

**Comment by sno036** [comment]
This is in addition to the existing Sobol and Morris suite of methods. It requires a complete factorial design but handles combinations of categorical and continuous variables well and gives first order and interaction effects. The complete factorial design means that it is not suitable for large numbers of factors or levels (there consider using Morris or Sobol). Florjan has been adding documentation for all three methods in tutorial style.
