### ISSUE TITLE
Models visible to UI via Add model

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#3498]
It seems the old approach of manually adding models in models.cs has been removed and any model (implementing IModel) in the code is now visible in the UI via Add Model.
Can we add an Attribute (NoDisplay or such) that leaves a model hidden from the user (e.g. for base classes and models the user is not suppose to use directly)?
This attribute could be checked in Apsim.IsChildAllowable or Apsim.GetAllowableChildModels.

It might also be useful to add NotChildOf or InvalidParent (opposite of ValidParent) attribute to ensure some models do not appear under particular models in the tree. This would mean we can remove CLEM models from appearing under a Zone for non-CLEM users and simplify the add model window.

**Comment by hol430** [comment]
There is a property `IModel.IsHidden`. Setting this to true should hide the model from the user. Does this do what you want?

**Comment by lie112** [comment]
The strangest thing has happened. I can no longer repeat the problem today and the Add model dialog looks ok now (I should have done a screen shot). Am I correct that the manual adding of available models has been removed, or was it moved somewhere else?

The option you provided only works if the model has been created where the Add model dialog has to work with all models in the system so needs a reflection approach. I'll see if the problem happens again. 

I would like the negative (Not) parent of option to get CLEM components out of other users selection lists.

**Comment by hol430** [comment]
Your unable to reproduce issue could be related to which model you tried to add models to. I think you should be able to right click on a folder or a factor and go add model, and have all of the CLEM Models show up.

> Am I correct that the manual adding of available models has been removed, or was it moved somewhere else?

By "manual adding of available models" do you mean right clicking on a model and clicking "add model"? If so, the code you're interested in is probably in AddModelPresenter.cs. Specifically, the call to Apsim.GetAllowableChildModels().

> I would like the negative (Not) parent of option to get CLEM components out of other users selection lists.

This sounds like a great idea - the add model dialog gets quite cluttered, especially with all of the CLEM models which I'm (usually) not interested in. I'm not sure how you've setup the inheritance hierarchy of your CLEM classes, but would it be logical to make any model which inherits from CLEMModel unable to be added to most "normal" models? e.g. 

```csharp
public static bool IsChildAllowable(object parent, Type childType)
        {
            if (childType == typeof(Simulations))
                return false;

            // CLEMFolder can be added to Simulations object.
            if (parent.GetType() == typeof(Simulations) &&
                childType == typeof(CLEM.CLEMFolder))
                return true;

            // If parent is not a clem model and child is a clem model, then no.
            if (!(parent is CLEM.CLEMModel) && childType.IsAssignableFrom(typeof(CLEM.CLEMModel)))
                return false;

            if (parent.GetType() == typeof(Folder) ||
                parent.GetType() == typeof(Factor) ||
                parent.GetType() == typeof(Replacements))
                return true;

            // Functions are currently allowable anywhere
            if (childType.GetInterface("IFunction") != null)
                return true;

            // Is allowable if one of the valid parents of this type (t) matches the parent type.
            foreach (ValidParentAttribute validParent in ReflectionUtilities.GetAttributes(childType, typeof(ValidParentAttribute), true))
            {
                if (validParent != null)
                {
                    if (validParent.DropAnywhere)
                        return true;

                    if (validParent.ParentType.IsAssignableFrom(parent.GetType()))
                        return true;
                }
            }
            return false;
        }
```

I'm not sure how many "normal" models regularly need to have CLEM model children, so maybe you need more fine-grained control than this, in which case perhaps something like an [InvalidParent] attribute might be helpful.

**Comment by jbrider** [comment]
Being able to filter this list - and the Addfunction list would be good.
A simple text search would be a good start.

**Comment by her123** [comment]
I suspect that the dependency of the parent excluding children may be better the other way around. You are more likely to have new children being developed that know where they should live.
A search or filter or grouping mechanism would be useful.

**Comment by lie112** [comment]
Sorry for confusion. By "manually adding models" I was referring to the old code practice where the model had to be added by developers in the code as a link (if I recall) to model.cs before it would show up in the GUI and the add model dialog. This seems to have disappeared and all models of type IModel are now available (leading to my problem where base classes were appearing). This may be related to changes that have made the compiling time for minor changes to APSIMx much faster and much appreciated!

**Comment by hol430** [comment]
@lie112 - yeah I remember the code you're talking about - now that we've moved to a json file format, it's no longer necessary to manually add the model as you say. 

My pull request adds a text search for the add model/function list. Does this issue require further action?
