### ISSUE TITLE
Vary by Graph Series option in Graph - Colour

### ISSUE THREAD

**Issue by pre078** [APSIMInitiative/ApsimX#3508]
How do I use the  "Vary by Graph Series" feature in the Graph - Colour option? I can't find documentation.

**Comment by hol430** [comment]
My understanding is that if you have a graph which has multiple series children, you would normally have to manually change each series to its own colour - perhaps red for the first series, blue for the second series, etc. 

If you set each series' colour to "vary by graph series", then each series will automatically be coloured differently. 

You can find the original feature request [here](https://github.com/APSIMInitiative/ApsimX/issues/2865).
