### ISSUE TITLE
Initialise FOM pools by layer

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3522]
The new soil Nutrient model requires FOM to be input on a layered basis (Called RootWt in Soil Nitrogen).  Many soil carbon modelling efforts would also benefit directly from an ability to specify the amount of FOM in each layer rather than the current application of an arbitrary exponential distribution with depth.
This will impact SoilNitrogen as well but will allow interoperability between soil nutrient and soil nitrogen.

**Comment by sarahcleary** [comment]
@EnliWang and @sarchontoulis - action from last RP meeting - can you please review and comment?
