### ISSUE TITLE
Null doesn't throw error in variablereference function

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3554]
The following code allows a variable reference to an incorrect link to simply return zero rather than throwing an error.
If the link is incorrect, the highlighted line will return o as null but then go on to return a value of zero.  It should test for o as null and throw.

        /// <summary>Gets the value.</summary>
        /// <value>The value.</value>
        public double Value(int arrayIndex = -1)
        {
            **object o = locator.Get(VariableName.Trim());**
            if (o is IFunction)
                return (o as IFunction).Value(arrayIndex);
            else if (o is Array)
                return Convert.ToDouble((o as Array).GetValue(arrayIndex), 
                                        System.Globalization.CultureInfo.InvariantCulture);
            else
            {
                double doubleValue = Convert.ToDouble(o, System.Globalization.CultureInfo.InvariantCulture);
                if (double.IsNaN(doubleValue))
                    throw new Exception("NaN (not a number) found when getting variable: " + VariableName);
                return doubleValue;
            }
        }

**Comment by hol430** [comment]
via @byzheng:

>Step to reproduce this problem. See example below
>
>    Open wheat example, create replacement and copy wheat.json into replacement.
>    Copy "Photosynthesis" under "Leaf" into "Photosynthesis_RUE"
>    Create "VariableReference" as "Photosynthesis" and add value as "[Photosynthesis_RUE"
>
>The value of "VariableReference" is missing right bracket. APSIM doesn't give any error.
>
>However, the biomass is close to zero.
>
>[test.zip](https://github.com/APSIMInitiative/ApsimX/files/3092074/test.zip)
