### ISSUE TITLE
Remove dependancy between Phenology class and EmergingPhase class

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3558]
The phenology model requires the emergence phase to be modelled using an emerging phase class.  however, this class could be replaced with a more flexible generic phase to allow much more user input on drivers of the emergence process.

However, the phenology class has the following
    if ((CurrentPhase is EmergingPhase) | (CurrentPhase.End == structure?.LeafInitialisationStage))
                    {
                         Emerged = true;
                    }

The model should be changed to allow emergence to be defined by something other than a class type.

**Comment by HamishBrownPFR** [comment]
I noticed this when I was refactoring phenology a while back but didn't have a use case so left it as it was.  Agree more flexibility is needed here
