### ISSUE TITLE
Leaf Class Detachment output does not work

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3559]
The leaf class has an output of type biomass to report daily detachment.  The value in this class is not updated with daily detachment.  It reports only manual detachment by external actions.  The detachment that it computes is never added to this value.

**Comment by ric394** [comment]
This appears to be an ongoing issue as shown below:
<img width="1270" alt="image" src="https://github.com/APSIMInitiative/ApsimX/assets/123442863/c7d0468f-d6bc-45f8-a1d2-044fcfdba166">

**Comment by hol353** [comment]
In the wheat model there is no daily leaf detachment happening. I had to set the values of:

```
Wheat.Leaf.CohortParameters.DetachmentLagDuration
Wheat.Leaf.CohortParameters.DetachmentDuration
```

to values of 1 to reproduce this issue. Most plant models have values of 100000 which stops leaf detachment. I suspect this is the same problem as reported in #3179
