### ISSUE TITLE
Divide by zero in report

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3577]
Is it possible to export NaN or NULL if divide by zero in the report? For example,

I want to export:

```
[Wheat].Leaf.NDemand.Storage / [Wheat].Leaf.DMDemand.Storage  as Wheat.Leaf.NConc.Storage
[Wheat].Leaf.NDemand.Metabolic / [Wheat].Leaf.DMDemand.Metabolic  as Wheat.Leaf.NConc.Metabolic
[Wheat].Leaf.NDemand.Structural / [Wheat].Leaf.DMDemand.Structural  as Wheat.Leaf.NConc.Structural
```

**Comment by hol430** [comment]
Don't think it's currently possible to do this via the report alone...but as a temporary workaround, you could achieve it with the aid of a manager script; Inside the script:

```csharp
public double Result
{
    get
    {
        return MathUtilities.FloatsAreEqual(denominator, 0) ? double.NaN : numerator / denominator;
    }
}
```

You could use `MathUtilities.Divide(numerator, denominator, double.NaN)` instead, but I'm not sure if this works - it seems to test the two doubles for equality. 

Then inside the report, just add the following, where ManagerName is the name of your manager script:

`[ManagerName].Script.Result`

**Comment by rcichota** [comment]
I came across this issue before and generally what you want is a zero not a NaN s output (graphs can break).
What I have used is to add a small value to the denominator (so you need to be careful with the order of magnitude of you variable). Something like that work for me:
``` 
([Wheat].Leaf.NDemand.Storage / ([Wheat].Leaf.DMDemand.Storage + 0.00000001)) as Wheat.Leaf.NConc.Storage
```

**Comment by byzheng** [comment]
@rcichota Great idea. It solved my problem.

**Comment by hol430** [comment]
Re-opening this, as it was never really fixed.
