### ISSUE TITLE
Order of items in graph legends

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3579]
I have observed vs simulation graphs in which the order of items in the legend does not seem right. I tried changing the order in the excel file of the observed data, but to no avail. It seems that the order depends on the order of simulations in the model tree. I think it's better that the graph sorts the items regardless of their position in the model tree or in the excel file of the observations.

![image](https://user-images.githubusercontent.com/39573622/53933544-92be9800-40ea-11e9-9103-af8284523f14.png)

**Comment by hol430** [comment]
How would you prefer they be sorted? Alphabetically?

**Comment by BenAbabaei** [comment]
I think if there is a lost of items, there should be sorted alphabetically. In this example, the first 'Wet/Dry' part is correct, but the second part is not. It would be ideal if we had a choice somewhere in the interface.

**Comment by BenAbabaei** [comment]
Perhaps an extra row in **PredictedObserved** object to set a column to sort the tables would be helpful.
