### ISSUE TITLE
Value is not changed if mouse clicks in the right hand side of windows

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3580]
Step to reproduce this problem. 

1) Mouse Click any item in the tree at the left hand side of window
2) Update the value
3) Mouse click in any place at the right hand side of window.
4) Value is restored in the updated item. 

See the attached gif file for an example.

![changevalue](https://user-images.githubusercontent.com/1657381/53935063-c00e4480-40f0-11e9-9deb-7347a66a8855.gif)

PS: The value will be updated only if mouse clicks in the left tree.

**Comment by ric394** [comment]
Unable to reproduce in the current version. Looks to have been resolved at some point in the past.
