### ISSUE TITLE
Storage allocation in the StorageNDemandFunction

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3583]
In the code below, the potential allocation is summed up by structural and metabolic. @HamishBrownPFR I think the `potentialDMAllocation.Storage` should be included here. Any reason to let it out?

https://github.com/APSIMInitiative/ApsimX/blob/acb26f9f27d4df3b397c5bb41bacb2f6e1fe8f9b/Models/Functions/DemandFunctions/StorageNDemandFunction.cs#L54

**Comment by HamishBrownPFR** [comment]
There would have been a reason to leave it out at the time but I don't recall what it was and have no idea if the reason is still relevant.  If this is causing you problems suggest changing it and putting up a pull request to see what impact it has.

**Comment by byzheng** [comment]
I also have no idea about for any impacts. Will submit a pull request and check it.

**Comment by par456** [comment]
Going to close this as the change seems to have been tested and rejected. The code hasn't been modified since, so if this is something that should be addressed, let's open a new issue on it with more details.
