### ISSUE TITLE
Null reference when trying to document the Agroforestry model.

### ISSUE THREAD

**Issue by fai04d** [APSIMInitiative/ApsimX#359]
This model does not have code to enable auto documentation. Needs to be added.

**Comment by hol353** [comment]
The way the autodoc works is that it looks for a model with the same name as the filename. In this case it will look for something in the tree called 'agroforestry' and obviously isn't finding it. It should provide a better error message rather than a null reference.

**Comment by fai04d** [comment]
To get this working I had to change the file name to WindbreakSystem which isn't the name of the model (that's ForestrySystem) but the name of the node in the simulation. This is kind of confusing, especially since I have two different kinds of ForestrySystem (windbreak and single tree) in the simulation. Additionally, it calls the model 'WindbreakSystem' in the docs which is incorrect. Someone looking for a model of that name won't find it. 

Plus it's also documented every one of the 14 Zones. The doc is 106 pages...

I'm not going to submit this change yet, but I will catch that exception and add a better error message.  Surely there's a better way of doing this. Since ForestrySystem extends Zone, all of the children are being documented as well.
