### ISSUE TITLE
Unable to edit water node

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3602]
Steps to reproduce:

1. Open Wheat example
2. Expand the simulation, expand the field, expand the soil, click on the water node

Expected behaviour:

*something* appears in the right hand panel

Observed behaviour:

Object reference not set to an instance of an object. Right hand panel is empty.

**Comment by jbrider** [comment]
I'm getting this one as well.

**Comment by hol353** [comment]
There is another problem as well. The UI tests run on Jenkins should have failed because the test simulates clicking on all nodes in a simulation. The UI tests should have run red.

**Comment by hol430** [comment]
Any exceptions thrown while attaching the presenter to the view are handled by the explorer presenter. Therefore, the error never propagates all the way up to the CheckStandardToolbox script which is run as part of the UI tests. As far as I can see, the test will only fail if clicking on the node would have caused a crash.

**Comment by hol353** [comment]
Then we need to change this.
