### ISSUE TITLE
How can I access the value of a manager script's parameter from another script?

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3603]
I need to set fertilization at sowing and I need to do it without explicitly setting sowing date in fertilisation manager script. So I need to read the sowing date from 'Sowing' manager script. How can I do that? **Sowing.Script.SowDate** does not work.

**'Models.Manager' does not contain a definition for 'Script' and no extension method 'Script' accepting a first argument of type 'Models.Manager' could be found (are you missing a using directive or an assembly reference?). Line number: 40**

**Comment by BenAbabaei** [comment]
Hi @hol430 . Could you please help me with this?

**Comment by hol430** [comment]
Can you post your .apsimx file?

**Comment by BenAbabaei** [comment]
I want to access sowing date of **Sowing** from **ResetWaterOnSowing**.

[APSIM-NG Template for TE Study - OldISMs2.zip](https://github.com/APSIMInitiative/ApsimX/files/2959367/APSIM-NG.Template.for.TE.Study.-.OldISMs2.zip)

**Comment by BenAbabaei** [comment]
I used this to check whether today is the planting date, instead of reading sowing date from that manager script. I am not sure if this is the ideal way of doing it.

**DateUtilities.DatesEqual(DateUtilities.DMYtoISO(Wheat.SowingDate.ToShortDateString()), Clock.Today)**

**Comment by hol430** [comment]
Try this:

```csharp
string sowDate = Apsim.GetVariableObject(Parent, "[Sowing].Script.SowDate").Value as string;
if (DateUtilities.DatesEqual(sowDate, Clock.Today))
```

It compiles of course, but I don't have your met files so have no idea if it works or not.

**Comment by BenAbabaei** [comment]
I got different results with my and your method. I have factors that modify sowing dates. I am not sure which one of our methods reads the 'real' sowing date, i.e. the one after it is modified by the factor.

[Badgingarra Research Stn.zip](https://github.com/APSIMInitiative/ApsimX/files/2959469/Badgingarra.Research.Stn.zip)

**Comment by hol430** [comment]
Something like this should tell you if my method is returning the correct sowing date:

```csharp
Simulation sim = Apsim.Parent(this, typeof(Simulation)) as Simulation;
string sowDate = Apsim.GetVariableObject(Parent, "[Sowing].Script.SowDate").Value as string;
Summary.WriteMessage(this, "SimulationName=" + sim.Name + ", SowDate=" + sowDate);
if (DateUtilities.DatesEqual(sowDate, Clock.Today))
```

As long as you know which simulation name is supposed to correspond to which sowing date, this should let you know whether my method is returning the correct sowing date.

Disclaimer: I haven't tested this.

**Comment by BenAbabaei** [comment]
Thanks Drew. Your method works fine. Mine tries to compare YY-mm-dd with today's date with DateUtilities.DatesEqual which apparently does not work. I need a dd-mmm date. I am using your method. Cheers.

**Comment by BenAbabaei** [comment]
Drew, your method keeps the date as it is in the original **Sowing** manager script, i.e. it does not take into account the modification of sowing date by factors. I think if I know how to convert date to dd-mmm my method would work fine, I am testing all the date convert functions one by one.

**Comment by hol430** [comment]
Can you upload your met file so I can run the file? That behaviour sounds like a bug

**Comment by BenAbabaei** [comment]
I did. It is a couple of comments above this. 

https://github.com/APSIMInitiative/ApsimX/files/2959469/Badgingarra.Research.Stn.zip

**Comment by hol430** [comment]
Ah right - I missed that sorry

**Comment by BenAbabaei** [comment]
This is the easiest way I think and it resets on sowing date every year.

```
        string sowDate = Wheat.SowingDate.ToString("dd-MMM");
        if (DateUtilities.DatesEqual(sowDate, Clock.Today))

```
Cheers.

**Comment by hol430** [comment]
It seems to be working ok for me - if I click on any of the simulations were sowing date has been set to 20-Apr, the script successfully figures out that the sowing date is 20-Apr. And in those sims where the sowing date is 20-May, the script seems to figure that out as well:

![image](https://user-images.githubusercontent.com/36427516/54249839-604ee800-458d-11e9-906a-5d239fb4b822.png)

![image](https://user-images.githubusercontent.com/36427516/54249813-5331f900-458d-11e9-8db1-9eb0e55aea30.png)

Are you seeing different behaviour, or is this not how the script is supposed to work?

**Comment by BenAbabaei** [comment]
You're right. It works as well. Thanks a lot Drew. That was really urgent for me.
