### ISSUE TITLE
Writing to the SQLite datastore is slow on physical disk drives

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#3614]
A bit of testing has shown that writing to the DataStore can be slow when using a physical disk drive; writing to SSD drives tends to be suitably quick. This typically manifests as a very long wait at the end of a set of simulations (the wheat validation set provides a good example of this).

**Comment by BenAbabaei** [comment]
Perhaps [this](https://github.com/APSIMInitiative/ApsimX/issues/3612) is a related problem. Maybe it can be resolved/closed at the same time as this one.
