### ISSUE TITLE
Tab display is corrupted when simulations are opened

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#3618]
If you are not running in a build environment, with source code at hand, the tab for the first simulation opened hides the "Home" tab.

**Comment by zur003** [comment]
Looks like there's still a problem here.

**Comment by zur003** [comment]
This is strange. The Jenkins build (APSIM 2019.3.15.3614) doesn't seem to work correctly, but my local build doesn't show the problem.

**Comment by hol430** [comment]
By your local build, do you mean the source code compiled in release mode?

**Comment by zur003** [comment]
@hol430 - Good catch! It seems to be working in Debug mode but not in Release mode. Any clues?
