### ISSUE TITLE
Add a sample-based standard deviation to MathUtilities

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#3630]
MathUtilities currently contains MathUtilities.StandardDeviation which appears to me a population standard deviation (the divisor is the total count, N). Could there also be a MathUtilities.StandardDeviationSample (or something) where the divisor is (N-1) which is the standard deviation of a sample?

**Comment by sno036** [comment]
Hi @hol430, @hol353, thanks for fixing this. I've tested this and it is giving the right answers. I only reopened the issue in case it is worth seeing if a population SD has been used anywhere else (other models/managers or in the test suite perhaps) when a sample SD should have been used. If there are no worries there then just close the issue again.  Cheers, Val

**Comment by hol430** [comment]
The population standard deviation is called in only one location from the source code - it's used to calculate yearly rainfall standard deviation in the weather file display in the GUI:

![image](https://user-images.githubusercontent.com/36427516/54721882-eaf79e80-4bae-11e9-96fa-3b43da0b3cce.png)

I guess this should be changed to use the sample SD. The population SD is not used in any .apsimx file in version control, so no problems there.
