### ISSUE TITLE
Merge legend of line and point

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3638]
I would suggest to merge the legend for line and point together if the serials have the same name to save some space in the figures.

For example

![image](https://user-images.githubusercontent.com/1657381/54583517-2768b480-4a60-11e9-8be0-ac0eeee301d5.png)

Instead of current version. 

![image](https://user-images.githubusercontent.com/1657381/54583458-f25c6200-4a5f-11e9-8422-1173f9f5aa18.png)

**Comment by hol353** [comment]
For this to work the series titles need to be identical as they are in the image above. This can be achieved by unclicked 'Include series name in legend?'
