### ISSUE TITLE
APSIM version has changed to 1652 from >3600

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3640]
On [this page](https://apsimnextgeneration.netlify.com/modeldocumentation/), the version of APSIM has reduced from something >3600 to 1652. Is this normal? Is there any other way to find out the latest 'built' version of APSIM than checking this page?

**Comment by zur003** [comment]
Well, it's "normal" in that the number is an Issue number used as a build identifier, rather than a more traditional build number. The numbers are a reflection of when the issue was raised, not of when it was resolved. This can be a bit misleading.

Probably the easiest way to find the latest build is by clicking on the Upgrade button in the ApsimX GUI.

**Comment by BenAbabaei** [comment]
Thanks @zur003 . But I am using a custom build and that button doesn't work. 

BTW, regarding the other issue you asked about, I did not update APSIM before running my simulations. So, I am not sure whether your push would fix that problem.

**Comment by hol430** [comment]
The latest built version corresponds to the latest source code on the master branch of this repository. To use this on your custom build, just checkout the master branch of this repository and do a git pull.

**Comment by BenAbabaei** [comment]
I know how to check out the master branch. I am asking this as we use APSIM-NG **.deb** file to build a singularity to be put on UQ cluster and each time we need to know the last build number. Currently and on [this page](https://github.com/APSIMInitiative/ApsimX), the latest pull request is **3639** and on [APSIM.Shared](https://github.com/APSIMInitiative/APSIM.Shared) it is **84**. But APSIM [website](https://apsimnextgeneration.netlify.com/modeldocumentation/), it is **1652**.

**Comment by hol430** [comment]
You can call a function on our webservice to get the URL to an installer for the latest version. You can pass operating system name as an argument (defaults to Windows):

https://www.apsim.info/APSIM.Builds.Service/Builds.svc/GetURLOfLatestVersion?operatingSystem=Debian

If you want to do this automatically from a bash script, as in the case on your UQ cluster, you could try something like this:

```bash
temp_file=$(mktemp)
curl -s https://www.apsim.info/APSIM.Builds.Service/Builds.svc/GetURLOfLatestVersion?operatingSystem=Debian > $temp_file
url=$(sed -e 's/<[^>]*>//g' $temp_file)
echo url=$url
```

**Comment by BenAbabaei** [comment]
This is going to be helpful. I will test it on Linux. Cheers.
