### ISSUE TITLE
Scaling up infertile tiller to population in the apex model

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3641]
Leaf cohort model is in a single plant level. Structure model is in a population level. Apex model is based on the leaf cohort and also in the single plant level. So apex model need to scale up from single plant level to population scale.

Two attributes in the model are contributing to the population scales.
* The appeared tip number in the main stem. The fraction of appeared tip number at terminal spikelet and flag leaf stages indicates the different growth stages of tillers, i.e some tillers have one more/less leaves.
* The apex age of infertile tillers at terminal spikelet. The fraction of apex age indicates the probability of tiller senescence with the same age after terminal spikelet. 

To simplify this problem, all tillers in the population were split into two groups (i.e. strong and weak) according to appeared tip number at the terminal spikelet.  Four different cases are considered to specify this problem in the details. 

Case | Tips | Age of infertile |  Infertile tillers | Notes 
--------| ----- | ----------------- | -------------------------  | ---------------------------------------------
1        | 7     |  3                  | N1+N2+N3                 |  
2        | 7     |  3.4               | N1+N2+N3+N4*0.4   |  Non-integer in the age of infertile indicates partial senescence for tillers with age 4 (40%)
3        | 7.2  |  3                  | (N1+N2+N3)*0.8 + (N1+N2)*0.2    |  We assume there are 20% tillers are stronger another 50% tillers (i.e. one more leaves). Consequently, the tillers can be split into two groups by 20% (stronger) and 80% (weaker). For 20% tillers, the Age of infertile equals to 2. For 80% tillers, the Age of infertile equals to 3.
4        | 7.2  |  3 .4               | (N1+N2+N3+N4\*0.4 )\*0.8 + (N1+N2+N3\*0.4)\*0.2  |  We still split all tillers into two groups (i.e. stronger and weaker) as Case 3. In each group, the method in Case 2 is used to calculate the infertile tillers.

In the implementation of the proposed method above, the total number of infertile tillers is calculated through looping all apex groups from the youngest to the oldest apex group. A few intermediate variables are defined to standardise the equations above.
   
* weakTillerRatio: The ratio of weak tiller
* strongTillerRatio: The ratio of strong tiller
* weakAge: The apex age for the weak tiller
* strongAge: The apex age for the strong tiller
* probabilityOldestApex: The probability of senescence of oldest  apex group

Case | Tips | Age of infertile |  weakTillerRatio | strongTillerRatio  | weakAge | strongAge | probabilityOldestApex 
--------| ----- | --------------------- | -----------------------  |  --------------------  |------------- |--------------  | -------------   
1        | 7     |  3                       |  1                          | 0                         | 4              | 3                |  0
1        | 7     |  3.4                    |  1                          | 0                         | 4              | 3                |  0.4
1        | 7.2  |  3                       |  0.8                       | 0 .2                     | 4              | 3                |  0
1        | 7.2  |  3.4                    |  0.8                       | 0 .2                     | 4              | 3                |  0.4

**Comment by scckite** [comment]
So this is used to do what? Work out how many infertiles there are so we can ignore their LAI or allow them to die?

**Comment by byzheng** [comment]
@scckite  The definition of infertile tiller at the terminal spikelet is those tiller will stop to growth and gradually die as the leaf senescence by age and other factors.
