### ISSUE TITLE
Copy graph to clipboard is not working

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3643]
Right click on a figure, then click "copy graph to clipboard"

The background is black in the generated figures

![image](https://user-images.githubusercontent.com/1657381/54732451-91f42e80-4bdf-11e9-9af5-cfebf9410a24.png)

**Comment by hol430** [comment]
Where are you attempting to paste the graph?

**Comment by byzheng** [comment]
Paint in Windows,

**Comment by byzheng** [comment]
Word is working as expected.

**Comment by hol430** [comment]
Interesting - I'm getting that as well. Will look into it.

**Comment by byzheng** [comment]
It might be related with format of images. I have the similar problem from other program. 

You might need to copy the background into clipboard too.

**Comment by byzheng** [comment]
Have the same problem when directly pasting into github. 

![image](https://user-images.githubusercontent.com/1657381/54970756-2c34e780-4fcf-11e9-8831-9d7f98bb87fe.png)
