### ISSUE TITLE
Compiling APSIM-NG on Linux

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3649]
I see a **build.bat** file in **ApsimX\Jenkins** folder and a **BuildDeb.bat** in **ApsimX\Setup\Linux**. Could we use these (or a part of the commands in them) to build APSIM-NG on our windows- or Linux-operated machine? I need to do this as I might need to run APSIM-NG on the UQ cluster for which we use the latest .deb file from APSIM website. But I don't know how to build that on my virtual machine without making any damage!

**Comment by hol430** [comment]
build.bat and BuildDeb.bat are batch scripts, which will only run on the Windows command prompt.

Which distribution of Linux are you using? There are some instructions for compiling on Ubuntu on the [website](https://apsimnextgeneration.netlify.com/development/contribute/compile/linux/), however, this will require you to install monodevelop, which you may not want to do.

**Comment by BenAbabaei** [comment]
My OS is Windows 10 and that is where I do all the changes in the code. But I need to build a singularity on my virtual Ubuntu-operated machine to put on the UQ HPC cluster. If I can use those batch files to create the APSIM .deb file, that would be perfect and I don't need to do it on Linux. I will read the website. Meanwhile please let me know whether I can do it on Windows.

**Comment by byzheng** [comment]
@BenAbabaei As I suggested to you last time, it will be much simple to compile it on Windows, and copy the list of files into Ubuntu, and run it under Ubuntu.

The command line is 

    mono Models.exe path-to-apsimx-file

The list files are required to run APSIMX under command line

- "Models.XmlSerializers.dll"
- "msvcr120.dll"
- "sqlite3.dll"
- "zlib1.dll"
- "APSIM.Shared.dll"
- "libsqlite3.so"
- "libxml2-2.dll"
- "MathNet.Numerics.dll"
- "Models.exe"

**Comment by BenAbabaei** [comment]
@byzheng we don't have the admin previliede on the UQ HPC to install mono. Let me see how I can put these files in a singularity.

**Comment by hol430** [comment]
You can build the .deb package on windows...but there are a large number of dependencies which you will need to install in order to do so. Have a look at ApsimX/Jenkins/getDependencies.bat. Running this script should install them all. Then you can just run ApsimX/Jenkins/build.bat to compile and ApsimX/Setup/Linux/BuildDeb.bat to create the .deb package.

That said, it might be easier to just compile on Linux. I've had problems in the past when copying files compiled on Windows over to Linux.

**Comment by peter-devoil** [comment]
There are many in the HPC community that laugh at the idea of a .NET program being considered "high performance", and quite a few administrators discourage its use. It is not available even as a loadable module on the UQ systems, though raijin has a (very old) version available. As well, the administrative privileges to install software on these clusters is guarded very tightly.

Under this scenario, it is possible to build mono as a normal user, and to bundle it in the same manner as apsim - downloaded and extracted on the executing machine before the simulation begins. But it's a large download, and its often difficult building new apsim and mono versions on the native OS of the cluster.

So, singularity (https://www.sylabs.io/) offers the non-admin user a way to bundle apsim and mono into a single container (ie both as ubuntu packages in a ubuntu install), allowing efficient access when mounted as a loopback filesystem (it only copies what is needed), and is widely supported. It allows the user to quickly build an image on their workstation (where they do have admin privileges), and upload it to the remote cluster.

**Comment by byzheng** [comment]
How about mkbundle? Just googling.

https://www.mono-project.com/docs/tools+libraries/tools/mkbundle/

**Comment by peter-devoil** [comment]
If you're happy to build it on the native OS, that's fine.

**Comment by BenAbabaei** [comment]
Running those batch files didn't work on Windows. Dependencies were installed, but running the other two files didn't do anything in the console. I am trying to do what Bangyou suggested though there is no **Models.XmlSerializers.dll** in APSIMX folder.

**Comment by hol430** [comment]
What output did you get from build.bat?

**Comment by BenAbabaei** [comment]
Nothing :) No error, no warning.

**Comment by hol430** [comment]
Yeah there are a few assumptions in the build.bat script...I haven't used it manually, it only gets used by Jenkins, in a known environment. Basically, msbuild needs to be on path, and so does nuget.exe. You also need to have an environment variable defined, called "apsimx", which points to the apsimx directory. I'm guessing that at least one of these problems is what's giving you grief.

To check if the two programs are on path, use the where command:
```cmd
where msbuild
where nuget
```

You will get an error message if they are not on path, in which case, you will need to add them to the path. If you ran the getDependencies.bat script, I think these files should have been installed somewhere under C:\Utilities\.

I'll remove the environment variable requirement - the script should be able to figure that much out for itself.

> there is no Models.XmlSerializers.dll in APSIMX folder.

Pretty sure this is no longer generated or needed, now that we've moved to json

**Comment by BenAbabaei** [comment]
@byzheng @peter-devoil, I managed to combine singularity with Bangyou's approach. The latest APSIM build is still installed from the website and the files of the custom build are added to a folder in the singularity image. The only trouble is that apparently there are other dependencies that we need to add. I will add **Newtonsoft.Json.dll** to the files and test it again.

I am not sure whether there is going to be other problems as both Peter and Drew mentioned that there could be problems with APSIM if compiled on windows. I will post it here if I see any problem. 

`
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies.
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
  at Models.Core.ApsimFile.FileFormat.ReadFromFile[T] (System.String fileName, System.Collections.Generic.List`1[System.Exception]& creationExceptions) [0x00047] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Core.Runners.Runner.ForFile (System.String fileName, System.Boolean runTests) [0x0001f] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Program.Main (System.String[] args) [0x0030b] in <beb84e7011c94d249ecea2fc308346f2>:0 
`

**==========================================================**
**==========================================================**

**The full script I used to build the singularity was like this:**

`
BootStrap:docker
From:ubuntu:latest
%labels
Maintainer b.ababaei@uq.edu.au

%setup
	mkdir -p ${SINGULARITY_ROOTFS}/usr/local/lib/myapsim

%files
	/home/behnam/Documents/UQ_HPC/ApsimNextGenExec/Models.exe  /usr/local/lib/myapsim
	/home/behnam/Documents/UQ_HPC/ApsimNextGenExec/msvcr120.dll  /usr/local/lib/myapsim
	/home/behnam/Documents/UQ_HPC/ApsimNextGenExec/sqlite3.dll  /usr/local/lib/myapsim
	/home/behnam/Documents/UQ_HPC/ApsimNextGenExec/zlib1.dll  /usr/local/lib/myapsim
	/home/behnam/Documents/UQ_HPC/ApsimNextGenExec/APSIM.Shared.dll  /usr/local/lib/myapsim
	/home/behnam/Documents/UQ_HPC/ApsimNextGenExec/libsqlite3.so  /usr/local/lib/myapsim
	/home/behnam/Documents/UQ_HPC/ApsimNextGenExec/libxml2-2.dll  /usr/local/lib/myapsim
	/home/behnam/Documents/UQ_HPC/ApsimNextGenExec/MathNet.Numerics.dll  /usr/local/lib/myapsim
		
%post
apt update && apt -y install gnupg curl

gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key A6A19B38D3D831EF
gpg -a --export A6A19B38D3D831EF | apt-key add -

echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/4.8.1 main" > /etc/apt/sources.list.d/mono.list
apt update && apt -y install mono-runtime mono-devel \
   sqlite3 libcanberra-gtk-module \
   gtk-sharp2 libwebkitgtk-1.0-0 libcanberra-gtk-module

temp_file=$(mktemp)
curl -s https://www.apsim.info/APSIM.Builds.Service/Builds.svc/GetURLOfLatestVersion?operatingSystem=Debian > $temp_file
url=$(sed -e 's/<[^>]*>//g' $temp_file)
echo url=$url

curl -o ApsimSetup.deb $url
dpkg -i ApsimSetup.deb
rm ApsimSetup.deb

mkdir /30days /90days /TMPDIR
`

**Comment by BenAbabaei** [comment]
Dear @hol430, I get this error when I try to use **mono** with windows-compiled APSIM executable and assemblies, but not when I used the latest build of APSIM directly from website. Could you help me understand what is wrong or what other assemblies I need to put with **Models.exe**? Cheers.

`
Object reference not set to an instance of an object ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Models.Storage.DataStoreWriter.ReadExistingDatabase (APSIM.Shared.Utilities.IDatabaseConnection dbConnection) [0x0000d] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Storage.DataStoreWriter.Start () [0x00051] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Storage.DataStoreWriter.WriteTable (System.Data.DataTable table) [0x00001] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Summary.CreateInitialConditionsTable () [0x003da] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Summary.OnDoInitialSummary (System.Object sender, System.EventArgs e) [0x0000b] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Clock.OnDoCommence (System.Object sender, Models.Core.Runners.RunSimulation+CommenceArgs e) [0x0000e] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00053] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <dbb16e0bacdc4a0f87478e401bc29b6c>:0 
  at Models.Core.Events+Subscriber.Invoke (System.Object[] args) [0x0000d] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Core.Events.Publish (System.String eventName, System.Object[] args) [0x00026] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Core.Runners.RunSimulation.Run (System.Threading.CancellationTokenSource cancelToken) [0x001a3] in <beb84e7011c94d249ecea2fc308346f2>:0 
   --- End of inner exception stack trace ---
  at Models.Core.Runners.RunSimulation.Run (System.Threading.CancellationTokenSource cancelToken) [0x0026d] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at APSIM.Shared.Utilities.JobRunnerAsync+<>c__DisplayClass9_0.<JobRunnerThread>b__0 () [0x00014] in <3a67f5e3ac2449e8a1c31601019adeed>:0 
----------------------------------------------
System.NullReferenceException: Object reference not set to an instance of an object
  at Models.Storage.DataStoreWriter.WriteSimulationIDs () [0x00015] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Storage.DataStoreWriter.Stop () [0x00016] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Core.Runners.RunOrganiser.RunPostSimulationTools (Models.Core.IModel rootModel, Models.Storage.IDataStore storage) [0x00007] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at Models.Core.Runners.RunOrganiser.Completed () [0x00028] in <beb84e7011c94d249ecea2fc308346f2>:0 
  at APSIM.Shared.Utilities.JobRunnerAsync.JobRunnerThread (APSIM.Shared.Utilities.IJobManager jobs, System.Int32 numberOfTasksToUse) [0x000e8] in <3a67f5e3ac2449e8a1c31601019adeed>:0 
----------------------------------------------
`

**Comment by hol430** [comment]
@BenAbabaei did you end up fixing this? I've been (slowly) working on putting together a test case to reproduce this problem, but if you figured out the problem then I won't bother.

**Comment by BenAbabaei** [comment]
The error was due to missing assemblies. I just copied all the dlls in the bin folder to the UQ cluster and it worked. Would be helpful if I knew which assemblies are really needed by Models.exe.

**Comment by frank0434** [comment]
@BenAbabaei 
I was trying to build an ApsimNG in the Ubtutu which I installed in a windows 10 as a subsystem. 
Reckon ran into the same question you had, maybe? How to build the `.sln` inside the Linux env.

I did install the `monodevelop` since it is just a local laptop. 

Used the `xbuild` to build the `ApsimX.sln` as mentioned in this [thread](https://stackoverflow.com/questions/8264323/how-to-compile-a-visual-studio-c-sharp-project-with-mono)

The `Models.exe` is available after the build.

Guess the singularity is a better approach for cluster anyway, this is just a random try out.

**Comment by hol430** [comment]
I believe xbuild is deprecated as of mono 5.0 in favour of the msbuild command (although it's still available and still works for now). I guess what's needed here is an addendum to the 'build on linux' instructions for users wishing to do a commandline build. This will also be helpful for people wishing to other IDEs such as vscode.

**Comment by frank0434** [comment]
Yes.  The message did mention the point.
```
>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
```
I was following the document on [ApsimNG website](https://apsimnextgeneration.netlify.com/development/contribute/compile/linux/).
Stuck in the last step which says
```
8. Set ApsimNG as startup project   
   In MonoDevelop, right-click on ApsimNG, and select “Set as Startup Project”.
```
I started to google how to build in a Linux environment and found that old trick. 

Guess an update on that existing document would be helpful?
