### ISSUE TITLE
Reporting properties of items in a list

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#3653]
I am trying to report a property of a model item in a list in the Report. It doesn't seem that the variable string supports Model.Item[index].PropertyName  I also tried creating a method Model.GetValue(int index) in the parent holding the list, but this function is not supported by the code getting the values either. 
Does anyone have a work around for this?
Rather than use lists of models provided in the UI, I create a List<type> in the background so that any code changes to these models does not influence the user setup for the next run. Now I need to report properties of some items in the list.

**Comment by hol430** [comment]
This seems to be working ok for me. Here is my setup:

Manager:

```csharp
public IModel[] Arr
{
	get
	{
		return Apsim.ChildrenRecursively(Apsim.Parent(this, typeof(Simulation))).ToArray();
	}
}
```

Report:

`[Manager].Script.Arr[2].Name`

Output:

Summary (name of the second model).

The array-indices in the report are 1-indexed (!), which is something to watch out for. Could you upload your .apsimx/.met files?

**Comment by lie112** [comment]
What if Arr is a List<IModel>? You can normally used List[index] to obtain items. Does this work in reports?

**Comment by hol430** [comment]
Yep, that also seems to work for me. Is this not working for you?

**Comment by lie112** [comment]
I am building my variableNames dynamically in a custom report and adding
[Resources].Labour.Items[1].AvailableDays as Male
I have been following through getting the value through the locator class and variableProperty
I realised that Items (List) was not a property, so I have addressed this. I have had this problem before.
But now in ProcessPropertyOfArrayElement() I get an error that Count() us not a property of LabourType.
I am not sure what it is doing or where this comes from. Count() would be a property of List, but not the list items.
I'll keep exploring, and maybe send you the aspimx file tomorrow.
Somewhere the full variable name is changed to [Resources].Labour.Items.Count() as Male and this causes an error.

**Comment by lie112** [comment]
Oh, I think it's the problem that when you add a list it works through all the values in the list, not a specific item you have identified. It is creating Male(1), Male(2) and Male(3) columns while also filling the Female and Hire (other two items in the list) correctly.

**Comment by lie112** [comment]
Thanks.
I had missed making the List a property and then there was a wayward report with an erroneous line causing problems.
Adam
