### ISSUE TITLE
Apsim should be able to download soil descriptions from web services

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#3655]
ASRIS and ISRIC provide web services which yield soil descriptions for any specified location. Apsim should be able to access these web services to populate its soil descriptions.

**Comment by BenAbabaei** [comment]
Hi @zur003 Thanks for this very handy tool. Just two questions/suggestions. Is it by any chance possible to use this to extract soil information for classic APSIM? And is it possible to make a change so no soil model is needed already in place (to be replaced by the new soil model) when we need to extract data from the databases (so we need to right-click on the 'field' node instead of the 'soil model' node)? Cheers.

**Comment by hol353** [comment]
Another use case after a discussion with @rcichota:

I think we should support multiple soil databases (e.g. Apsoil, Soil and Landscape Grid Australia, ASRIS, ISRIC and LandCare NZ). We could add the ability for the user to simply supply a URL or some way of pointing to the soil without actually copying the soil into the simulation. At runtime APSIM could download the soil, add in missing parameters (e.g. SWCON) and use it on the fly. That way if you’re using an external tool (e.g. R / Python) you don’t need to do any infilling of missing parameters or conversion of XML/JSON formats. The user could just put the URL into the .apsimx file and it works.

**Comment by JJguri** [comment]
@zur003 @hol353 @BrianCollinss We are working with ISRIC gridded soil data in an APSIM format retrieved from the CSIRO ApsimSoil API. We found negative values for `diffus_slope` (-1.64) and the `diffus_const` value is extremely high (6608.31). After reading the ISRIC metadata I assumed this parameters are calculated using texture or other variables but I was not able to find the exact method of calculation. Do you know how these parameters are calculated and converted in an apsim format? @leandrogiovannini

**Comment by zur003** [comment]
@JJguri : @her123 or @hut104 may be better able to advise on this, but as of a couple of years ago, the logic used this snippet of R code:

>   diffusivity_at_dul <- 1000.0 * campbell_b[diffusivity_layer] * k_dul * abs(psi_dul[diffusivity_layer]) / theta_dul[diffusivity_layer]
>  diffuse_slope      <- (propn_matrix_dul * p_matrix[diffusivity_layer] + (1.0 - propn_matrix_dul) * p_macro[diffusivity_layer] -(campbell_b[diffusivity_layer] + 1.0)) / theta_dul[diffusivity_layer]
>  diffuse_const      <- diffusivity_at_dul / exp(diffuse_slope * (theta_dul[diffusivity_layer] - theta_wwp[diffusivity_layer]))

Comments near these lines suggest the calculations for values related to hydraulic conductivity are from Littleboy (1997), p. 158.

"campbell_b" is earlier calculated as:

>   campbell_b  <- abs ( log(psi_dul/psi_wwp) / log(theta_dul/theta_wwp) )

"theta_dul" is DUL of APSIM, and "theta_wwp" is LL15. 

This is probably not quite enough to fully answer your question, but I hope it helps.

**Comment by peter-devoil** [comment]
@her123, is that code publically available?

**Comment by her123** [comment]
No.

**Comment by JJguri** [comment]
> @JJguri : @her123 or @hut104 may be better able to advise on this, but as of a couple of years ago, the logic used this snippet of R code:
> 
> > diffusivity_at_dul <- 1000.0 * campbell_b[diffusivity_layer] * k_dul * abs(psi_dul[diffusivity_layer]) / theta_dul[diffusivity_layer]
> > diffuse_slope      <- (propn_matrix_dul * p_matrix[diffusivity_layer] + (1.0 - propn_matrix_dul) * p_macro[diffusivity_layer] -(campbell_b[diffusivity_layer] + 1.0)) / theta_dul[diffusivity_layer]
> > diffuse_const      <- diffusivity_at_dul / exp(diffuse_slope * (theta_dul[diffusivity_layer] - theta_wwp[diffusivity_layer]))
> 
> Comments near these lines suggest the calculations for values related to hydraulic conductivity are from Littleboy (1997), p. 158.
> 
> "campbell_b" is earlier calculated as:
> 
> > campbell_b  <- abs ( log(psi_dul/psi_wwp) / log(theta_dul/theta_wwp) )
> 
> "theta_dul" is DUL of APSIM, and "theta_wwp" is LL15.
> 
> This is probably not quite enough to fully answer your question, but I hope it helps.

Thanks @zur003 for your response. In order to identify why those values were outside the natural range we should check each value used in the formulas. Would be good to have access to the raw data used for the calculations but as @her123 highlighted it is not public. For those regions were the data is not correct,  we are using the fix values reported [here](https://www.apsim.info/wp-content/uploads/2019/10/Parameters-for-soil-water-Ver24.pdf). I also conducted a sensitivity analysis an I found that the effect of huge changes in these parameters (more than 50%) are not significantly affecting yield estimations.

**Comment by hol430** [comment]
I'm going to close this issue; from what I can see, the original feature request has been implemented - we can now download soils from web services in the GUI. Any additional feature requests can be filed as such.

**Comment by JJguri** [comment]
> I'm going to close this issue; from what I can see, the original feature request has been implemented - we can now download soils from web services in the GUI. Any additional feature requests can be filed as such.

thanks @hol430 could you please show where is the function in APSIM to be used? Thanks

**Comment by hol430** [comment]
Right click on a zone -> download soil

**Comment by JJguri** [comment]
classic or NG?

**Comment by hol430** [comment]
NG - this issue is not about classic (nor this repo :).

**Comment by JJguri** [comment]
@hol430 I cannot fin zone. Can you please provide an screenshot of this function? Thanks

**Comment by hol430** [comment]
It's often called paddock or field:

![image](https://user-images.githubusercontent.com/36427516/148883061-2646cf32-fc6b-4d03-b876-0f4a842ff5dd.png)
