### ISSUE TITLE
Copy graph to clipboard is still not working 

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3671]
Following issue #3643, the copied figure is becoming a black figure when pasting into MS Paint and Github and white figure in the MS Word.

![image](https://user-images.githubusercontent.com/1657381/55202003-3cd4a000-5211-11e9-8f54-5e2f36ac0ab6.png)

**Comment by hol430** [comment]
This seems to work for me:

![image](https://user-images.githubusercontent.com/36427516/55202285-8a054180-5212-11e9-983a-6efee960de94.png)

The graph looks very strange (mostly black) when I enable windows high contrast mode - are you using this setting by any chance? And are you on the latest version?

**Comment by jbrider** [comment]
I get a black background when pasting into IrfanView.
![screenshot](https://user-images.githubusercontent.com/635772/55202570-afdf1600-5213-11e9-9bef-df2ea7ea5eda.jpg)

**Comment by jbrider** [comment]
In fact after pulling down the latest changes, the lines are black as well - same as @byzheng is getting.

**Comment by sno036** [comment]
And all I get is a white box

**Comment by hol353** [comment]
Is this because the background of the image is transparent?

**Comment by hol430** [comment]
Looks like this is a problem with the version of the Mono.Cairo assembly which we ship with Apsim. On my computer, .NET found a copy of this assembly in the GAC which had the same version number as the version which we ship with Apsim. The version in the GAC was loaded, but there's actually a difference between it and the assembly shipped with Apsim (default value of a specific property of a certain class). This difference is what caused my graphs to look perfectly fine, but other people's graphs to appear black. If I remove the file from the GAC, my graphs become black as well.

@zur003 where did the files in DeploymentSupport come from? I don't think there is a bug in Mono.Cairo, but I'm confused as to why two dlls with the same version number are different.

**Comment by zur003** [comment]
I don't actually remember where those files originated, but it's interesting that the Mono.Cairo.dll in DeploymentSupport is older than the other Gtk# .net assemblies in that folder. Let me browse through my files...   it appears that the version in DeploymentSupport came from a Gtk# 2.12 distribution, but I don't recall which.

@hol430  If you're really curious, it's easy to access the gtk-sharp git repository. What was the name of the property that is different? We could work out the point in the history at which it was changed.

I sometimes wonder whether I should clone/add the gtk-sharp repository, as I had to do a bit of tinkering with the source to build the 64-bit version of the Windows "glue" DLLs. Unlike the 32-bit versions, those DLLs don't seem to be readily downloadable in compiled form from any source on the internet (even though they are open source).

**Comment by hol430** [comment]
Interesting. The specific property I'm looking at is `Cairo.Context.Pattern`. When we create a new instance of this type (as we do [here](https://github.com/oxyplot/oxyplot-gtksharp/blob/master/Source/OxyPlot.GtkSharp.Shared/PngExporter.cs#L83)), the default value for its `Pattern` property is an object of type `Cairo.Pattern`. When I use the modified Mono.Cairo assembly, the default value is of type `Cairo.SolidPattern`.

I've just had a look at the history for Context.cs in the gtk-sharp repo, and this file doesn't appear to have been changed recently, but I'm still investigating...

**Comment by hol430** [comment]
If you guys pull down the latest changes, do you still encounter this issue?

**Comment by byzheng** [comment]
It works with gray background. We might expect a figure without background or white background.

![image](https://user-images.githubusercontent.com/1657381/55844668-cbd2a800-5b81-11e9-9619-ffa80175043b.png)

**Comment by hol430** [comment]
@byzheng How about now?

**Comment by byzheng** [comment]
@hol430 It works now. Thanks
