### ISSUE TITLE
Question: writing multi-day-aggregated outputs instead of daily outputs? 

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3687]
- I usually need to average daily outputs over 50-degree-day or 10-day periods or growth phases, especially in large simulations which require better memory management. Is there any option in APSIMX that can do this without the need for a manager script?

- In classic APSIM, there was a function (if I am not wrong, **do_output**) that would let us choose when daily outputs were printed, instead of printing when an event was triggered. Is there a similar function in APSIMX?

**Comment by hol430** [comment]
- Unsure about this, I suspect it's not possible without the aid of a manager script. Someone else might be able to shed more light here
- there's a function `Report.DoOutput()` which you can call from anywhere (e.g. a manager script) which will trigger a report output.

**Comment by hol353** [comment]
There is currently no option to advanced averaging in the report model. You'll need a manager script.

**Comment by BenAbabaei** [comment]
Thank you both.

**Comment by IrisKydH** [comment]
Hi, @hol353, @hol430 and @BenAbabaei. I'm a green hand to ApsimX, and I need to control the model running since I will assimilate some observations (eg. in situ or remote sensing data) into APSIM. But I'm really confused about writing 'manager script' at this stage, do you have any tutorials to recommend? Thanks.

**Comment by hol430** [comment]
Manager scripts are just scripts written in the C# programming language. I don't know if we have any tutorials, but you should find a few examples of manager scripts in the examples directory (hit open an example on the apsim home screen). The factorial example (factorial.apsimx) contains some very simple manager scripts - e.g. the FertiliserRule at `.Simulations.Experiment.Base.Field.FertiliserRule`. 

If you've done some programming before then it shouldn't be too hard to pick up. If you post more specific info about what you're trying to achieve, I can give more specific advice.
