### ISSUE TITLE
Get AgPasture into release

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#3689]
Past due that AgPasture was officially in release. Here starting the process. This is what Mariana is doing.

**Comment by sno036** [comment]
@hol353 can you add "mpandreucci" to the project please? (is that 'whitelisting'?)

**Comment by hol353** [comment]
@sno036 @mpandreucci Is this now ready for review by the Reference Panel?

**Comment by mpandreucci** [comment]
I don't know if @sno036 will want to add some managers to it. If she doesn't want to add anything else to it, then I think it's ready.
The only thing is that the graph still has some black points, instead of all of them being coloured. I'm not sure if it's something that needs to be fixed by you @hol353

**Comment by hol353** [comment]
Which graph is it?

**Comment by mpandreucci** [comment]
The predicted x observed from the Radcliffe validation test

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel  - to be discussed in Friday's RP meeting. In the meantime, any suggestions for reviewers?

**Comment by sno036** [comment]
Matt Harrison suggested as a reviewer

**Comment by sarahcleary** [comment]
RP agreed to see if Matt Harrison was available and willing to review (AI RP May Meeting).  @sarahcleary to contact Matt Harrison

**Comment by sarahcleary** [comment]
@sno036 - can you please provide the instructions for the reviewer - where can he find the validation example and documentation?

**Comment by sarahcleary** [comment]
Sent request to Matt Harrison to see if he is available to review model

**Comment by sarahcleary** [comment]
[AgPasture review ApsimX Matthew Harrison.docx](https://github.com/APSIMInitiative/ApsimX/files/3284212/AgPasture.review.ApsimX.Matthew.Harrison.docx)
[AgPastureTest3929MH1.pdf](https://github.com/APSIMInitiative/ApsimX/files/3284213/AgPastureTest3929MH1.pdf)
[AgPasture3929MH2.pdf](https://github.com/APSIMInitiative/ApsimX/files/3284214/AgPasture3929MH2.pdf)
Review by Matthew Harrison.  Minor comments attached.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - Review docs from Matthew Harrison above.  Please read prior to July RP meeting

**Comment by sarahcleary** [comment]
@sno036 - please note comment in RP Meeting

**Comment by sno036** [comment]
@sarahcleary - apologies but I don't think that I'm going to get to respond to the review comments before the RP meeting.

**Comment by sno036** [comment]
Remaining to do:
- remove the Sward from the validation version of AgPasture. simulations (@sno036 before release)
- add a Manager to access the expert-level parameters (@hol353 but can be after release)
- delete Sward from the AgPasture code base (@hol353 but can be after release)
- ?? anything else?

**Comment by sno036** [comment]
@sarahcleary, this is now ready for release. All the comments from Matt have been acted on, the example simulation is tidy for new users.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please note @sno036's comment above

**Comment by hol353** [comment]
@sarahcleary Following last weeks RP meeting, can I put AgPasture into release?

**Comment by sarahcleary** [comment]
@hol353 - yes.
