### ISSUE TITLE
Is it time to start categorising the possibilities under "Add model"

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#3698]
There are now at least 272 possibilities under some "Add model" right clicks. Is some categorisation past due? (I can't find the one I think I want!)

![image](https://user-images.githubusercontent.com/12176269/55455220-56298200-563f-11e9-8973-4a997fef7746.png)

**Comment by hol430** [comment]
There is a search box up the top if that helps

**Comment by sno036** [comment]
Maybe ...(I didn't see the search)

**Comment by hol430** [comment]
![image](https://user-images.githubusercontent.com/36427516/55528054-dce16c00-56de-11e9-8bb9-66e03c1c8546.png)

**Comment by hol353** [comment]
I think some categorisation would be useful. Need to think about how we want to do that though.

**Comment by hol430** [comment]
These are all C# classes, so we could categorise by the namespace in which they're declared.

**Comment by hol353** [comment]
Yes that would work. I guess we need a tree view in that window instead of a list.

**Comment by lie112** [comment]
I have been considering ways of removing the CLEM models unless the "add model" is selected under CLEM component as I realise these are not needed by most users and are quite numerous. I could add some code to ignore CLEM components for all but CLEM "add model". It could be that some more sophisticated means of setting valid parents and valid NOT parent may clean up the situation.

We could also add a treeview component to the side of the "add model" presenter to list all available models APSIM.Models.XXXX and "core components" that would act as a useful filter.

**Comment by her123** [comment]
A treeview for categories sounds good

**Comment by lie112** [comment]
I had more of a thought. There are times when you don't need or want to select from a filter. If the Parent attribute has been set well you might only have a couple options to chose from and they should simply be displayed. It could be the filtering appears when a large number of items appear or you are working with an imodel or zone. Still needs a bit of thought for best usability,

**Comment by hol430** [comment]
If I go into the add model view and expand or collapse a folder by double clicking on it, it will add a model of that name if it exists. e.g. If I double click on the folder for the graph namespace it will add a graph model because the namespace and the class have the same name:

![AddModel](https://user-images.githubusercontent.com/36427516/68553449-003a7980-046d-11ea-87e4-0d092fb5b18c.gif)
