### ISSUE TITLE
Soil C:N on a layered basis

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3709]
The test sets for soil OM modelling require soil C:N ratio to be different for different soil layers.  This has long been a limitation of the SoilNitrogen model.  Model utility will be greatly improved by allowing different C:N values for each soil layer.
Implementation will need to ensure that initialisation is appropriate with different soil profile layer specifications are used for the soil and the soilorganicmatter nodes in the user interface.  This requires mapping of C and N to calculate effective values of C:N for the new layer structure.

**Comment by hol353** [comment]
@APSIMInitiative/reference-panel This is a science change to soil nitrogen model.

**Comment by Keith-Pembleton** [comment]
Makes sense to me I think
