### ISSUE TITLE
Incorrect reference to Soil.OC

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3712]
The CERES Urea Hydrolysis function incorrectly references Soil.OC which is the initial OC, not the daily value
double potentialRate = -1.12 + 1.31 * soil.OC[arrayIndex] + 0.203 * soil.PH[arrayIndex] - 0.155 * soil.OC[arrayIndex] * soil.PH[arrayIndex];

**Comment by par456** [comment]
This has been fixed, closing issue,
