### ISSUE TITLE
Refactor of graph series and experiment / factor code

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#3716]
The code in experiments / factor / factorvalue is very convoluted. This needs a tidy up. Also, the Morris and Sobol models have 'factors' as well. Need to broaden factors beyond experiments so that they can be produced by and model. This has implications for graph series as well.

**Comment by HamishBrownPFR** [comment]
Please don't tell me the graphs are going to break again

**Comment by hol353** [comment]
OK I won't. This is an attempt to fix broken graphs. @hut104  has been feeding me graphs that are blank and I've been fixing the code to 'unblank' them. I've also written a bunch of graph unit tests that hopefully will stop it happening in the future.

**Comment by jbrider** [comment]
I'm still having issues as per  #3471

**Comment by jbrider** [comment]
It didn't improve...
![image](https://user-images.githubusercontent.com/635772/55855611-5976bd80-5bab-11e9-9543-c7b27c111934.png)

**Comment by HamishBrownPFR** [comment]
@hol430 thanks, it will be good to get those blank and plain coloured graphs fixed and have some unit tests.
