### ISSUE TITLE
Implement a dark theme

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3748]
It would be handy to have a dark theme for apsim. This would reduce eye strain when switching between apsim and other dark programs such as a terminal, IDE, etc.

It would also be good if the default (light) theme were compatible with any system-wide gtk themes which the user may have installed.

**Comment by her123** [comment]
Theme changes don't appear to work on Mac OSX

**Comment by hol430** [comment]
Does anything change at all? I don't have a mac to test this on, so this is going to be hard for me to debug

**Comment by her123** [comment]
No changes. The icon on the toolbar button changes but the application still looks the same.

**Comment by zur003** [comment]
This doesn't work on Ubuntu either.

**Comment by hol430** [comment]
How did you compile this on ubuntu? I get a compile error because of a typo (case error) in a filename

**Comment by her123** [comment]
ApsimX doesn't follow the Mac OSX dark theme system setting either. It appears to follow the system wide theme ok on Linux.

**Comment by zur003** [comment]
Just thinking - on Linux, because Gtk is widely used throughout, themes are usually set at the system level, rather than application level. It may be that system settings are overriding what you're doing in the application. And perhaps that's how it should behave. 

I've tried this just now, and ApsimX follows Ubuntu system themes reasonably well. The only bits that don't fit in nicely are the HTML displays, which continue to use a white background.

**Comment by hol430** [comment]
Yeah, the default theme is supposed to respect the system-wide theme settings. The dark theme is supposed to override them. The reason this isn't working is because we don't actually parse the .gtkrc file at all on 'nix systems. I'm not sure why exactly, but this appears to always have been the case - in the MainView, we have a line which looks like this:

```csharp
if ((uint)Environment.OSVersion.Platform <= 3)
    RefreshTheme();
```

This was in the code (more or less) before my changes. Any idea why we added this in the first place?

**Comment by hol430** [comment]
Is the Mac OSX dark theme a gtk theme?

**Comment by zur003** [comment]
I don't recall exactly why RefreshTheme was done only on Windows, but I think it was in part an effort to NOT override the "system" theme settings on Linux.  And partly to keep things from looking too much like a Windows application when run on non-Windows platforms.

The dark theme on OS X is NOT Gtk. Setting it has no impact on the appearance of ApsimX.

**Comment by zur003** [comment]
Oh, and the basic .gtkrc file was trying to pull in the Windows-specific "wimp" layer, so it didn't play nicely on non-Windows systems.

It might be possible to have a number of different .gtkrc configurations embedded as resources, and pull in the "correct" one based on system platform and user settings. I was always too lazy to figure out how to get that working nicely.

**Comment by hol353** [comment]
![image](https://user-images.githubusercontent.com/1943827/57111437-65efcf80-6d7f-11e9-9a4c-c6be1e22552b.png)
Can we make the lines in the tree control white when using a dark theme.

**Comment by hol353** [comment]
- Graph axes and ticks need to be white in dark theme.
- Operations and Report node (EditorView) has a white background - should be black.
- Making grid row and line separators (e.g. in water node) be white would make them easier to read:
![image](https://user-images.githubusercontent.com/1943827/57111678-5de45f80-6d80-11e9-81f5-ae4206b815c1.png)

**Comment by hol430** [comment]
> Operations and Report node (EditorView) has a white background - should be black.
You can right-click and choose a different theme for these nodes.

Will get back onto this dark theme stuff next week when I'm on csiro time.

**Comment by hol353** [comment]
Also red error text in the status bar is hard to read.

**Comment by hol430** [comment]
#3837 and #3838 should allow Unix users to use the dark theme. I've added code to detect if the macOS dark theme is enabled, but this code is currently not used anywhere. 

For Linux users, the dark theme works, but there is some code in both .gtkrc files which makes certain gui elements more 'windows-like'. I might add cut-down versions of our two .gtkrc files with these 'windows-esque' sections removed.

**Comment by hol430** [comment]
> Making grid row and line separators (e.g. in water node) be white would make them easier to read

I've been playing around with this, and have found that white borders tend not to play well with our grids. They seem to have inconsistent thickness when applied to the drop-down cells. That said, I've found that having dark cell borders works ok if I make the cells themselves a bit brighter. Here are a few screenshots:

This is what we have now:
![apsim-grid-default](https://user-images.githubusercontent.com/36427516/57504598-703e3a80-7338-11e9-8b27-0f266f87551e.png)

White borders and brighter cells:
![apsim-grid-light](https://user-images.githubusercontent.com/36427516/57504614-83510a80-7338-11e9-9ebe-01f6628082ef.png)

Dark borders and brighter cells:
![apsim-grid-lighter](https://user-images.githubusercontent.com/36427516/57504640-96fc7100-7338-11e9-94ed-ac34ae0cbe40.png)

Which one do we want to use? I can spend more time trying to work out why the white borders don't work properly but if option three looks okay it might be easier to go with that, as the documentation for this stuff is pretty poor.

**Comment by hol353** [comment]
Let's go with option 3 for now. It is certainly better.

**Comment by rcichota** [comment]
Just want to point to the fact that one of the colours in the graphs (for the data) is black, so it becomes nearly invisible in dark theme. Maybe it should be swapped with white when switching themes?

**Comment by hol430** [comment]
> Can we make the lines in the tree control white when using a dark theme.

Looks like this can't be controlled from the rc file. We can change the thickness and pattern, but not colour. My guess is that this is controlled by the rendering engine (libwimp.dll). @zur003 where did you find the wimp binary? I've found the source code in a cvs repository (which seems to contain the same .gtkrc file that we have in our source control!) but I haven't been able to compile it on Windows under cygwin and I'm not sure it will work well on Windows if I compile it on Linux.

> Also red error text in the status bar is hard to read.

This one is easy enough for us to change, but the question is what should we change it to? We could go with the orange from our 'standard' colour palette. This seems to stand out reasonably well:

![image](https://user-images.githubusercontent.com/36427516/57747819-86723f00-771a-11e9-9dea-dca43a3e3853.png)

@hol353 If you want to experiment with different colours, I've written up a quick and dirty colour tester which will allow you to change this on the fly and see the effects immediately:

![ColourChooser](https://user-images.githubusercontent.com/36427516/57747791-6c386100-771a-11e9-92dd-ec4fe218dd2d.gif)

Maybe we need a preferences panel where users can control these sorts of settings. There are currently a lot of settings which are very hard to control and the front page is starting to get a bit cluttered with all of the buttons up the top.

**Comment by hol353** [comment]
Orange is good for the status colours. I would like to fiddle with GUI look and feel. I don't like the fonts for example. They don't look crisp like this font on GitHub does.

**Comment by hol430** [comment]
Fonts were easier to modify than I expected. Check out the feature/ColourChooser branch on my fork if you want to have a play around. There's a font selection button on the home screen, next to a colour selection button. 

![image](https://user-images.githubusercontent.com/36427516/57749306-df44d600-7720-11e9-9d40-a9432b87937c.png)

**Comment by zur003** [comment]
libwimp.dll is normally distributed as part of the Gtk+ 2 stuff for Windows. (For example, you'll find a copy is part of the Windows GIMP installation.) I think I was able to compile it once upon a time, but I don't recall what was involved. It looks like it hasn't received a lot of attention from maintainers...

**Comment by hol430** [comment]
'Show Documentation status' feature doesn't seem to work in dark mode.

**Comment by hol430** [comment]
Closing this, as the issues mentioned in this thread have been resolved as far as I can tell.
