### ISSUE TITLE
Updater is broken on Ubuntu

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#3756]
Attempting to do an upgrade on Ubuntu results in:
1) a dialog indicating "Downloading file: 0%. Please wait".
2) This sits there unchanging for a while, then the application crashes with a SIGFPE

Upgrading on Mac worked, but the download % was a large magnitude negative number.

the % part of the display doesn't seem to appear if you select the option to see earlier version.

**Comment by hol430** [comment]
@zur003 Eric are you able to compile on Ubuntu 16.04 with monodevelop? I get an error that it doesn't support ToolsVersion 15.0, which is used in the Models project. If I change this to 14.0, I get a bunch of errors due to unsupported language features added in C#6.

**Comment by zur003** [comment]
Yes, I can compile on 16.04 Ubuntu, with MonoDevelop 7.7 and Mono 5.18.1.0. 

You may need to update mono (from https://www.mono-project.com/, not from the Ubuntu/Debian packages, which are badly out-of-date). I see that I have a /usr/lib/mono/msbuild/15.0/bin/Sdks folder, which suggests I have the support for ToolsVersion 15.0, and I think this was likely packaged with the Mono updates.

**Comment by hol430** [comment]
Ah ok, thanks Eric. Turns out I was on a very old version of both mono and monodevelop (I don't often use Ubuntu). Updating both solved the problem.

**Comment by zur003** [comment]
Yeah, the development tools need to be updated once in a while. I realised today that VS 2015 can't compile the current source, but that really shouldn't be a problem, as the Community Editions of VS 2017 or 2019 are readily available.
