### ISSUE TITLE
Testing a new cultivar in the Eucalyptus model

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#3793]
What should the procedure be for developing and testing new cultivars for the Eucalyptus model? 

I was able to add a new cultivar folder (and cultivar therein) to the Eucalyptus model and have it all work if I did that down in the individual simulation – as opposed to up in Replacements as I had attempted earlier. The latter could generally be handy for the future, but not essential for me currently. See how I added grandisEunopolis in the screenshot below and I now have quite a good OvP graph.

However, after saving, closing then reopening the simulation, the new cultivar folder had disappeared and the simulation would not run successfully, as it could not find the new genotype that was still nominated in the tree planting rule. Re-adding the cultivar folder and cultivar works, but it is not very satisfactory if it can’t be saved. 

Thanks again,
Philip

![Eunopolis tuned](https://user-images.githubusercontent.com/49378212/57052266-a1c85d80-6cc9-11e9-9157-365df19829b0.jpg)

**Comment by hol430** [comment]
Pretty sure this was fixed in #4671 and I forgot to tag this issue. I just tested this by adding a cultivar folder and new cultivar to the wheat model, saved + closed the file, opened it again and it was still there. If this isn't working for you, feel free to reopen the issue or create a new one.

**Comment by sme016** [comment]
Thanks. I’ll be working with this again in a month or so.
