### ISSUE TITLE
Filter in graphs is not working

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#3795]
Graphs that have a filter set up are not showing up and cannot be edited, this seems to be worse for observed values. This may be related to #3716 
I have a set of graphs for WhiteClover validation where I used a filter to show graphs for each NRate (I had set something like:```NRate = 100```), this seem to no longer work. No graph is produced and the Series window is all greyed out and one cannot change anything.  Creating a graph from scratch allow me to plot predicted values (but only if I use:```NRate LIKE 100```), attempt to filter using the "=" sign freezes the Series window. If I try to plot only the observed data, no option works, giving the error message: "A column named 'NRate' already belongs to this DataTable".

**Comment by zur003** [comment]
Perhaps that should that be: [NRate] = 100 ? The on-line help indicates that all column names need to be in square brackets.

**Comment by rcichota** [comment]
Thanks @zur003 , adding square brackets does work. However, going without used to work, so now old graphs have to be re-done (maybe, I will check after Dean's fix on XY graphs).
An extension of this issue, maybe, is that if I add an extra Factor (say a parameter I am optimizing), then the graphs show no observed values, even if I try to plot them separately and without any filter...

**Comment by rcichota** [comment]
Ok, graph are now working (with or without square brackets).
However, I still think that there is something wrong with graphs showing observed values. If I disable some of the Factors or add a new one, no observed values are shown. even if on their own and with no filter. Surely this is not the expected behaviour.?
Being a bit pedantic here, but it was a nice thing that the when using filters, the colour of series remained unaltered (that is they followed the same scheme as the graphs without filter). Now all colours (I presume lines and markers too) are reset.  @hol353 Is this intended or a side effect that can be fixed?
It used to be like:
![image](https://user-images.githubusercontent.com/12175986/57057603-2d5be180-6cfe-11e9-80f1-9580362e2ae8.png)
Now it looks like this:
![image](https://user-images.githubusercontent.com/12175986/57057627-68f6ab80-6cfe-11e9-8f75-66248581bfa0.png)

**Comment by hol353** [comment]
Not intended. Will try and fix tomorrow. Where can I find the graphs of your screen shot?

**Comment by hol353** [comment]
Another Q: How are you disabling factors?

**Comment by rcichota** [comment]
Thanks @hol353 , 
I am using the WhiteClover simulation (on /Tests/UnderReview). In either Experiment there is a Folder with graphs titled "ObservedResults".

To disable a Factor I am using the menu on Experiment (so I suppose I am disabling combinations, not only a factor). Looks like this:
![image](https://user-images.githubusercontent.com/12175986/57058846-2933c200-6d06-11e9-98dc-89ab8bbd1d38.png)

**Comment by hol353** [comment]
When I disable those 2 simulations I get this:
![image](https://user-images.githubusercontent.com/1943827/57110304-73a35600-6d7b-11e9-9b38-7cb5df94b16c.png)
Looks OK to me.

**Comment by rcichota** [comment]
Yeah, I think your changes yesterday fixed that, thanks. However, if I add another Factor (e.g. ```[Leaf].CriticalNConc.FixedValue = 0.04, 0.05```) the observed values are no longer shown. This is the case even if I have a graph with only observed values...

**Comment by hol353** [comment]
If you add a new factor, that will change the name of the Simulation (e.g. from FRNLRuakuraNRate0 to FRNLRuakuraNRate0NConc0.04). Have you also changed the simulation names in your observed file?

**Comment by rcichota** [comment]
No I have not, I should have thought about it. Although, I don't want to change those. My idea was to add this extra factor(s) to help debug or parameterise the model (for example checking the effect of varying CrticalNconc in organs)...
I thought that having both observed and predicted values in the same graph in this case could be difficult, but having the observed value even in a separate graph would be nice. But now I see clearer that simulation name is used to sort of pre-filter the data in the database, so probably this is not going to be possible... At least I can now have the original simulation open and showing the graphs. may close this issue then.

**Comment by hol353** [comment]
Don't close the issue. I have a fix ready for the changing colours of series.
