### ISSUE TITLE
XYPairs graphs not shown

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3796]
After today's pull, I cannot see the XYPairs graphs. It shows an empty white page.

**Comment by rcichota** [comment]
I've noticed that too (yesterday actually). It seems Apsim is trying to read the values of the XProperty instead of just plotting the values in the XYValues table... 
Probably Apsim should/could check whether the variable on XProperty exists, but certainly there is no need to look for values.
