### ISSUE TITLE
Simple Fruit Tree model

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#3801]
Develop a simple fruit tree model that is parameterised for multiple crop types (Apple, Kiwifruit, Grapes, Peaches etc) to do water and N balance of orchards.

**Comment by sarahcleary** [comment]
**ACTION from RP Meeting** - @Keith-Pembleton to link Hamish with a local consultant who developed a banana model which may have relevance to the Simple Fruit Tree Model.  @HamishBrownPFR might be able to help include banana model into NextGen.

**Comment by sarahcleary** [comment]
@HamishBrownPFR - is this "Ready for Review"?

**Comment by HamishBrownPFR** [comment]
superseded by #8175
