### ISSUE TITLE
More hotkeys would be nice

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3810]
Would be helpful to have hotkeys for some of the global actions - e.g.

ctrl + s - save
ctrl + shift + s or f12 - save as
ctrl + z - undo
ctrl + y - redo

Maybe something for split screen mode and to clear the status bar as well.

A pretty low-priority issue, just something which would be nice.

**Comment by peter-devoil** [comment]
Please add F5 to run simulation

**Comment by hol430** [comment]
This already exists - is it not working for you?

**Comment by peter-devoil** [comment]
Not while editing a manager script.

**Comment by hol430** [comment]
Ah - yeah it only works when you've clicked on a simulation/experiment.

**Comment by peter-devoil** [comment]
Can we have a hotkey to select a simulation/experiment whilst editing manager code then, or is that just being silly? :)

**Comment by hol353** [comment]
The keyboard shortcuts (eg F5) should work from everywhere, even while editing a manager script or editing report variables.

**Comment by byzheng** [comment]
How about ctrl + F5 to force to run the whole simulations no matter where you are?

**Comment by byzheng** [comment]
@hol353 Just have a testing. F5 is only working when you select a node which contain Simulation or Experiment in the children.
