### ISSUE TITLE
Documentation should first list VariableReferences and Constants

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3825]
If **VariableReferences** and **Constants** are put at the end of the lists of the objects linked to/under a Model/IFunction, in the model documentation they will be listed in the same order, which could be confusing. 

For example, in the **RUE photosynthesis model**, the parameter (i.e. a VariableReference) **RadnInt** is directly put under and linked to the **Photosynthesis** model, but in the document it is shown right after **FCO2**, which may make the reader think it is a parameter of/linked to **FCO2**.

![image](https://user-images.githubusercontent.com/39573622/57261665-1c1f2600-70ac-11e9-9a66-39c22c091fab.png)

**Comment by hol430** [comment]
In some contexts though, the order *does* matter - e.g. messing with the order of functions in a LessThanFunction is probably going to cause some confusion. Maybe variable references and constants need a heading? Or would that lead to too many headings?

**Comment by BenAbabaei** [comment]
One heading for each variable would do, yet they may be too many. Another solution would be to have one heading for all the VariableReferences and Constants linked to each Model/IFunction.
