### ISSUE TITLE
Allow methods with arguments to be used in reports

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#3830]
I would like to be able to use a method with arguments (only one string to start with) in the report variables. At present I believe there is limited code to access to methods, but not including arguments. I don't want to create public properties as I don't know the full suite that the users will require in the dynamic model building environment. 
Is this something others would use and something that could easily be added? I can have a look at adding this functionality as it will really assist some reporting I am needing to do in CLEM if no one else can do it.

**Comment by hol430** [comment]
I haven't really looked into it, but I imagine this should be possible. Seems like the simplest approach might be to add functionality to the Locator, allowing it to properly detect methods. I think at the moment it will look for the .Value() method of an IFunction, but no other methods.

**Comment by lie112** [comment]
I have implemented this functionality. Reports will now accept a method with any number of arguments of the types string, int32 and double (more can easily be added to a switch statement). I was able to add a small section of code to the Locator and add an arguments array to the VariableMethod to achieve this.

I have a couple questions/problems

1. What is the difference between Locater.cs and Locator.cs? I have added the code to Loactor.cs as this is the class operating in reports, but Locater is used extensively throughout code and looks very similar.

2. I need a bit of smart code to determine when an equation has been entered or whether it is a method with arguments inside brackets. I noted a comment in the code (Locator.GetInternal) "// expression - need a better way of detecting an expression". I have removed the "(" from the equation identifying search characters to allow the code to move on to identifying properties, models and methods. I figured an equation would have a +/* (note there is no -, I assume because people use - in model names and it will break too many runs. This may be why my minus '-' in an equation never worked.). I still need to add some code that removes all arguments from the string before breaking the string into components based on split('.") for namePathBits in Locator.GetInternal as the user may have added a "." to a double value in the arguments which is mistakenly taken as part of the model name structure.

I am not really familiar with equations people use. Is there another clever means of detecting an equation. I was thinking of looking between any  "(" and ")" and if there was no +/*- char it would be considered arguments and removed from the determination of namePathBits and replaced to determine method arguments.

At present using methods in reports works as long as the user doesn't add a "." in a double value in the arguments. I have not pulled this code until I get the equation identifier and passing doubles (including a ".") as arguments working.

**Comment by hol430** [comment]
Regarding expressions, have you come across the `ExpressionEvaluator` class in `APSIM.Shared`? It is able to parse and evaluate basic arithmetic and it also has some support for functions (sin, exp, etc). I think it is called by `VariableExpression`, which is an implementation of `IVariable`.

**Comment by hol353** [comment]
We need to consolidate locator and locater into one class. For now what you've done is fine.

Yes, we need to change the way expressions (as defined in ExpressionEvaluator class in APSIM.Shared) are recognised. It is very clumsy. I don't have any suggestions though how we might do this. We need to be careful though that the test for an expression isn't too complex because this code gets called a LOT during an APSIM simulation and a complex test would slow down APSIM runtime speed.

The "-" sign was probably excluded because of hyphens in model names as you say - or perhaps for negative numbers.

If you want to see a some example expressions, search for Expression in all .apsimx files in your Tests & Prototypes directory.

**Comment by lie112** [comment]
Thanks for the feedback. I have done some further exploring relating to Dean's concerns for increased processor time in all the checking rules especially relating to determining whether an equation or a method was supplied in a report.variable. I thought this would only be needed once at start of simulation when the report is set up. Then I found that the Locator.GetInternal was being run for every column (minus [parent] and [Clock]) of every report of every report event. I thought this was overkill as nothing should change in the column settings during a simulation once the IVariable was defined and started to look into this further. 
Then I found the cache in Locator which seems to do exactly what I think is needed, but a PropertyInfo or MethodInfo is never added to the cache as the code hits 
if (relativeToObject == null)
                        return null;
and never runs 
returnVariable = new VariableComposite(namePath, properties);
and 
cache.Add(cacheKey, returnVariable);

The code comments state
             // At this point there are only 2 possibilities. We have encountered a 
                // PropertyInfo or the path is invalid.
                // We now need to loop through the remaining path bits and keep track of each
                // section of the path as each section will have to be evaulated everytime a
                // a get is done for this path. 
                // The variable 'i' will point to the name path that cannot be found as a model.

I don't understand why you need to reevaluate this every time a get is called.
Surely the cache wasn't designed to hold only constant Clock and Parent.Zone, but all columns to avoid cpu overheads or unnecessary recalculation in all output value provision.

Can you explain when the GetInternal needs to rerun for every get call? I must be missing something. Is it because the returnVariable is dynamic based on lists. If so it would be good to determine if this is the case and only recalculate GetInterval when truly needed.

**Comment by hol353** [comment]
Consider this report variable:
[Wheat].Leaf.Leaves[1].Age

Leaves is a: List<LeafCohort> and its elements change during runtime as leaves develop and senesce. It needs to be reevaluated every time unfortunately. If the object at each part of the path (e.g. wheat, leaf, leaves) never changes then you can just keep track of the 'leaves[1]' object and simply call it's age property when needed. But we can't do this because the objects change. There are quite a few cases where this happens.

I haven't looked at the locator code for few years and I don't have time at the moment so I can't answer your specific questions about GetInternal. All I know is that we need to rethink this design at some point. It is a major cause of APSIM slow runtime speed.

**Comment by lie112** [comment]
Thanks. It could be as simple as needing to recalculate each time only if an array specifier has been used in the variable text as it is unlikely any properties other than an arrays or lists will change location during the simulation. This would be easily implemented and may reduce unneeded recalculation for 90% of properties outputted. Do you allow the output from entire dynamic lists, or just specified items in the list.
I certainly don't want to break or cause any issues. I might push the changes and not allow decimals to be included in arguments (it will just result in bad entry and leave blank in database). I think I can get away with a method using only string based arguments for my current requirements. 
There is very little to no extra demand at present from the code I have added unless you are using a method, or the variable is not a model.
I can see that reducing this computation unless necessary would be beneficial, and a more elegant approach would be difficult and require reassessing value locations OnCollectionChanged events of lists.

**Comment by lie112** [comment]
Note: this new feature does not allow properties to be passed as arguments, only constants.
