### ISSUE TITLE
Pasting of soil properties causes error in soil UI

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#384]
If I paste the table of soil numbers such as that below into the water tab of the soil I get an error message thrown.  It would be reallly good if I could easily paste the numbers from another version of APSIM into APSIMx.

0-20    1.190   0.060   0.200   0.250   0.522
20-40   1.200   0.060   0.200   0.250   0.522
40-60   1.200   0.060   0.230   0.250   0.450
60-80   1.300   0.070   0.250   0.315   0.450
80-100  1.167   0.090   0.270   0.325   0.363
100-120 1.167   0.090   0.270   0.325   0.363
120-140 1.167   0.090   0.270   0.325   0.363
140-160 1.167   0.090   0.270   0.325   0.363

**Comment by hut104** [comment]
You also get a failure if you add the depth info for a new soil layer at the bottom of the profile without the rest of the row of information

**Comment by fai04d** [comment]
Can you provide some more information? What was the error? I've tried copying from an Apsim 7.7 table and it worked. The above won't work as the tabs have been converted into spaces. It needs to be tab delimited to paste into a data grid.

**Comment by hol430** [comment]
I am unable to reproduce this behaviour. If anyone does experience this, just reopen this issue.
