### ISSUE TITLE
Report max number of records

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#3842]
If an integer is entered in Max. number of records it works ok. If a floating point then all records are returned. If an alpha is entered, all records are returned.
![Screen Shot 2019-05-10 at 8 55 51 am](https://user-images.githubusercontent.com/11879671/57491845-cc399c80-7301-11e9-8e27-2b6b2c5054f3.png)

**Comment by hol430** [comment]
What should we do in this situation? Not change the setting at all if the value entered is not an integer?

**Comment by her123** [comment]
Sounds good.
