### ISSUE TITLE
Phenology rarely updates its phases

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3849]
Phenology only updates its list of phases in the OnCreated() method. This only gets called when we open the .apsimx file. This was a problem today when I was testing some changes in Allan's chickpea model. I wanted to remove a duplicate phase, but the changes were not applied until I closed and re-opened the .apsimx file. Is there any particular reason we do this?

@hut104 @HamishBrownPFR

**Comment by hol353** [comment]
@hut104  and I found this today as well. If I delete a duplicate phase, the change needs to be applied immediately. This is a defect that needs fixing.

**Comment by HamishBrownPFR** [comment]
No reason but bad programming for doing it like this
