### ISSUE TITLE
Filters on graphs not working

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#3854]
Filters on my graphs that were previously working, have not been working for a couple of weeks. I thought the related issue that was raised back then would fix it, but I still have a problem. I am using the Eucalyptus model.

See screenshot attached.
[Issue - filter not working.pdf](https://github.com/APSIMInitiative/ApsimX/files/3184797/Issue.-.filter.not.working.pdf)

**Comment by hol430** [comment]
What exactly isn't working? That example in the screenshot seems to be working as expected - all datapoints shown in the graph seem to have an x value greater than 0. Some of them look like they could be pretty close to 0, but it's hard to tell from this scale. If that's the problem, could you upload your .apsimx and .met files to this issue?

**Comment by sme016** [comment]
No- that filer is not recognised. Firstly, the line of points above ‘0’ for predicted values should be excluded. Secondly, if I increase the value to say 20.00, it is still not recognised.

Thanks for getting onto it,
Philip

**Comment by sme016** [comment]
Hi Drew,

I am not sure if it’s related, but in the same simulation now, I cannot alter the euc model (specifically minimum N concentration in stems) in Replacements.

Regards,
Philip


From: Smethurst, Philip (L&W, Sandy Bay)
Sent: Thursday, 16 May 2019 10:24 AM
To: APSIMInitiative/ApsimX <reply@reply.github.com>; APSIMInitiative/ApsimX <ApsimX@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [APSIMInitiative/ApsimX] Filters on graphs not working (#3854)

No- that filer is not recognised. Firstly, the line of points above ‘0’ for predicted values should be excluded. Secondly, if I increase the value to say 20.00, it is still not recognised.

Thanks for getting onto it,
Philip
