### ISSUE TITLE
No csv file generated

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3879]
I use command "models.exe path-apsimx-file /Csv", but no csv file generated.

**Comment by byzheng** [comment]
I have tracked into source codes and change function ` public DataStore(string fileNameToUse)` (L81) for `DataStore.cs`. 

Not sure this is the correct way to implement. It seems there are another database type `firebird`.

```c-sharp
public DataStore(string fileNameToUse)
        {
            FileName = fileNameToUse;
            SQLite database = new SQLite();
            database.OpenDatabase(fileName, true);
            connection = database;
            dbReader.SetConnection(connection);
            dbWriter.SetConnection(connection);
        }
```

**Comment by hol353** [comment]
Yes that looks OK to me. Raise a pull request.
