### ISSUE TITLE
Add a rotation manager component

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#3890]
A bubble chart rotation manager similar to the apsim classic would make it easier to run farming systems simulations.

**Comment by peter-devoil** [comment]
@hol353 Is there a problem allowing manager scripts access to the publish / subscribe code methods of a Simulation?  At the moment they're local to Models.Core.RunSimulation(), but they could be accessed via the Simulation class with a bit of hack work.

**Comment by hol353** [comment]
This should work:
Events events = new Events(this);
events.Publish(...);

**Comment by peter-devoil** [comment]
hmm. Nearly there. I have a problem with private classes within a manager script failing to initialise with a "Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type." exception. Any clues?
[xx.zip](https://github.com/APSIMInitiative/ApsimX/files/3214607/xx.zip)

**Comment by hol353** [comment]
This is usually because the declaration of the event handler is wrong. Is it something like this:
void OnInitialise(object sender, EventArgs e);

Which event are you trying to trap? The second argument needs to match the event publisher.

**Comment by peter-devoil** [comment]
Ah. Too much copy paste from classic code. Tks

**Comment by hol353** [comment]
I've ported your directed graph code:
ApsimNG\Classes\DirectedGraph.

It is being used for the new nutrient model view:
ApsimNG\Presenters\DirectedGraphPresenter.cs

**Comment by peter-devoil** [comment]
Back to the publish bit: 
...
Events events = new Events(MySimulation);
events.Publish(action, new EventArgs());

'Models.Core.Events' does not contain a constructor that takes 1 arguments. Line number: 106
'Models.Core.Events' does not contain a definition for 'Publish' and no extension method 'Publish' accepting a first argument of type 'Models.Core.Events' could be found (are you missing a using directive or an assembly reference?). Line number: 107

**Comment by hol353** [comment]
??? Events does contain a constructor with one arg:
        /// <summary>Constructor</summary>
        /// <param name="relativeTo">The model this events instance is relative to</param>
        public Events(IModel relativeTo);

Events does have a publish method:
        /// <summary>
        /// Call the specified event on the specified model and all child models.
        /// </summary>
        /// <param name="eventName">The name of the event</param>
        /// <param name="args">The event arguments. Can be null</param>
        public void Publish(string eventName, object[] args);

Do you have another type called Event? Can I see your manager script?

**Comment by hol430** [comment]
Try wrapping the code in your comment with 3 backticks above and below

**Comment by peter-devoil** [comment]
I saw that and am continually perplexed by this
 language.. Here's the sample [xx.zip](https://github.com/APSIMInitiative/ApsimX/files/3214973/xx.zip)

**Comment by peter-devoil** [comment]
Ah. The constructor can only be used within the assembly:
        /// <summary>Constructor</summary>
        /// <param name="relativeTo">The model this events instance is relative to</param>
        internal Events(IModel relativeTo)
        {
        ...

**Comment by hol353** [comment]
For now use:
```
MySimulations.GetEventService().Publish(...)
```
This needs changing to make it simpler.

**Comment by peter-devoil** [comment]
Bother. Publish() isnt in IEvent. I am finally forced to build it..

**Comment by hol353** [comment]
Just put it into IEvent and raise a pull request.

**Comment by sarahcleary** [comment]
As per discussion at 2019-07 RP meeting - @Keith-Pembleton would like to be involved in testing this when ready

**Comment by hol430** [comment]
@peter-devoil - what's the status on this one? I see that #4060 went stale but the branch wasn't actually deleted. If you reckon it was in a mostly usable state then I'm happy to go and resurrect the branch and create a PR.

Asking because we're looking to set up a rotation example for sorghum, which will be easier with a rotation manager component.

**Comment by peter-devoil** [comment]
It's half done, drew - and I dont have time right now. There's some ugliness tying UI actions (eg menus) to DG nodes & arcs. And configuring graphs.

**Comment by hol430** [comment]
No worries - I'll see if I can get this finished.

**Comment by hol353** [comment]
I've had a look at this and I think we need this for complex (eg animals / multiple paddock) simulations. Some suggestions to make it more user friendly:
![image](https://user-images.githubusercontent.com/1943827/92669500-13e89200-f355-11ea-98f0-f6df7194ece0.png)

- Instead of showing ```[WheatManager].Script.CanSow``` and ```[WheatManager].Script.SowCrop()``` can we show the properties of the manager script?
- There would have to be one manager script for each transition (arc) between states. We could name the arcs (right click on arc and choose rename) and use the arc names as the manager names. 
- Each manager probably should be a child of RotationManager to make it tidier.
- Each manager would need two mandatory methods, something like ```bool CanTransition()``` and ```void DoTransition()```.
- Instead of setting the initial state via a dropdown, can we right click on a state and tick 'Initial State'. Or we could have a convention where a state called 'Initial' is always the initial state.

**Comment by hol430** [comment]
Good suggestions. Having child managers for each arc sounds like a good idea. We could add an interface called maybe `ITransition` which defines the `bool CanTransition()` and `void DoTransition()` methods you mentioned. The scripts would then implement the interfaces.

**Comment by hol353** [comment]
@peter-devoil In APSIM 7.10 do you use this state / transition system for moving animals across a farm? I'm thinking that if you had 10 paddocks or more then it would quickly become quite cumbersome with lots of states. I'm wondering whether we need a node/arc system where the nodes are paddocks (or other physical things like a feed store) and arcs that define the 'flows' (e.g. movement of animals or supplement) between the physical things. Thoughts?

**Comment by peter-devoil** [comment]
At the time it was tempting to try animal stocking routines, but on closer examination, state transition networks aren't flow networks - they don't represent movements of (animals or resources). Flow networks are usually short and uninteresting.

Yes, users do blow the networks out to large extents, and invariably find them so hard to properly examine (expose to many years of climate) that they reformulate their problem..

While on the subject - there is a mismatch with how we explicitly describe fallows, or empty nodes in the model: most scientists/practicioners think in terms of "crop2 after crop1, then maybe crop3", ie no "empty states", yet the network diagram requires the empty states - to explicitly harvest the crop etc...  I had a prototype that doesnt use the fallow nodes, but I find it difficult - it's not long before some sloppy thinking creeps in - usually around fallow length.

**Comment by jbrider** [comment]
@hol353 The common practice in Classic was to have the arc's hook into the methods of manager scripts. The number of arcs can be quite large so I don't think it will be practical to have one object for each one - but defining a consistent interface would be good. One thing that is difficult at the moment is to pass data between different scripts - I'm not sure if NextGen allows for that sort of flexibility.
