### ISSUE TITLE
Online Documentation Review

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3893]
Whilst demonstating the APSIM.info website at a recent conference, it became apparent that much of the online auto-documentation has graphs that are not working (e.g. blank or lines incorrect colour).  The wheat documentation also seemed to be missing.

A simple review is required to ensure that all documentation is available, and that all graphs are operating correctly.

**Comment by hol353** [comment]
@hol430 Looks like your last pull request worked in that it generated the under review documents but I still can't see them on the web.

**Comment by hol430** [comment]
The webpage points to documentation for the latest released version. My pull request however was a "working on" pull request - it doesn't actually generate a released version.
