### ISSUE TITLE
Eucalypt documentation

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3900]
The online documentation for eucalyptus has many legend items on top of the graphs that show overall model performance across all sites.  The text scattered across the graphs makes them difficult to follow.

**Comment by hol430** [comment]
Have these legend items always shown up in the euc autodocs? Or is this a recent addition?

**Comment by hut104** [comment]
I have asked Phillip Smethurst.  It may be that the graphs used to be bigger - ie one per row???? and so the legends did not cover so much.

I guess we are not sure.
________________________________

**Comment by hol430** [comment]
Legends are no longer shown on folders of graphs in the autodocs, so I'm going to close this as fixed.
