### ISSUE TITLE
How should ApsimX handle location information?

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#3909]
The World Modellers project will require us to run simulations based on a specified latitude and longitude. This location information can then be used to obtain G-Range parameters, and weather and soil data (via web services) for the site. However, it's not clear where this position information should reside in the simulation. Currently, for mapping purposes, latitude and longitude are obtained from the weather component (although there is no guarantee that longitude will be provided). And if weather data will be obtained "on the fly", is this still a good spot to store the location?

What is the best place to store location information? I'm inclined to think that it should be a property of a Zone. Thinking into the future, would this be the best option for a geospatially aware Apsim? If so, how do we migrate toward that? And what should happen if the location within a weather file (or soil?) does not match a location specified in some other part of the model?

Please discuss.

**Comment by peter-devoil** [comment]
I'd agree that it's a proper thing to store location (& extents) in a zone - but implementing it correctly will be prone to error - most users would remain unaware, and suddenly their plants start growing like they do in victoria.. Perhaps it should be updated whenever the met file is changed - but that sounds like a can of worms too: the last thing we want to do is introduce another dialog along the lines of "Update your location based on ...".

**Comment by BenAbabaei** [comment]
It could be easily implemented as part of the field/paddock properties. The least that can be added would be the **name** of the location, which is almost always needed in large-scale simulations. I always need to add that as the name of the folders or simulation or as a constant output variable. 

![image](https://user-images.githubusercontent.com/39573622/58601715-6bccc800-82cd-11e9-99ad-cac81a3bdf57.png)

**Comment by her123** [comment]
I think that it should be a property of the weather station. If the longitude is missing it needs to be set by the user/script. Every zone is dependent on a weather site. Zones do cover a grid but unlikely to have zones requiring different weather in the same simulation. It makes sense that a weather station has a location and further down the track Zones could have location that defines their position in a grid.

**Comment by hol430** [comment]
@sno036 could you leave a few of the older questions open? I just want to test the issue-closer bot

**Comment by sno036** [comment]
@hol430  - curious - issues can still be commented upon while closed! I'm done now.
