### ISSUE TITLE
No save option when closing APSIM immediantly after data change

### ISSUE THREAD

**Issue by fai04d** [APSIMInitiative/ApsimX#391]
If the user makes a change to a model then immediately closes APSIM, the option to save is not given and data is lost. This only happens if the user does not click another model before closing. If the users makes a change, clicks at least one other model in the explorer view then closes the option to save is given.

This is probably occurring because the GUI doesn't update the model itself until the view is detached.

**Comment by HamishBrownPFR** [comment]
This was resolved recently by @zur003
