### ISSUE TITLE
Division by zero error in MicroClimate

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#3920]
While running a simulation for Denmark it crashed because of a NaN generated due to a division by zero. Tracking it down, I found that it comes from the calculation of 'gc' in MicroClimate, which uses Radn divided by a variable called 'dayLengthEvap' that is zero. This variable should represent the "*length of time within the day during which evaporation will take place*", and is being calculated as zero for several days around winter solstice. This may be just a feature of the model at high latitudes and means no evaporation when the sun is too low in the sky.  Although I am not sure whether 60degrees is too high latitude to warrant no evaporation.  The model computes the value of 'dayLengthEvap' using the function ```MathUtilities.DayLength(day,angle,latitude)```, with a base angle of 15degrees (equivalent to one hour, as I understand), however the length of day in Denmark is still more than six hours in winter, so discounting two hours would still leave time for evaporation... (but maybe I misunderstood the calculation, maybe @sno036 or @hut104 can help here). The graph below shows the day lengths I am getting now:
![image](https://user-images.githubusercontent.com/12175986/58920442-53095a00-8786-11e9-9dd9-640b662c627b.png)
(Typical is the one computed using a twilight angle of minus six, as used in the plant models; LightOnly uses angle of zero and appears in Microclimate alongside 'dayLengthEvap'; for comparison)

**Comment by sno036** [comment]
Hi Rogerio - well spotted. I've just done a pull request for a temporary fix to get you moving again.

**Comment by hut104** [comment]
This solar elevation is to approximate the time of net positive radiation.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rcichota** [comment]
Thanks guys, let's see if Val's fix work, but for the record I add my thoughts on how this may be fixed:
1) Change the value of the angle used to compute 'dayLengthEvap'. I tried this and, not surprising, it changes quite a bit the radiation balance, so probably not the way to go;
2) Check and set a minimum value to 'dayLengthEvap', maybe a very small value (10^-9). This seems to work, but it produces a few weird values for radiation in winter... This is also what Val is trying to implement, only she's setting the value of 'dayLengthEvap' relative to 'dayLengthLight', with a factor of 2/3, this may be too intrusive, but maybe not.
3) Check for division by zero when computing 'Rflux' and then 'gc'. This is quite straigthforward and only changes the calculation that is actually breaking, but leaves the issue of whether 'dayLengthEvap' should be zero or not (the other implication of it being zero is that there is no PET as seen by MicroClimate - the soil's "eo" is small but not zero at these times)...
The graph below shows the results for MicroClimate PET as it is (blue) and after implementing my solution 3 (green) and Val's (grey-dotted). and eo for comparison
![image](https://user-images.githubusercontent.com/12175986/58926211-81932f00-879e-11e9-85c7-a7de4fd62ba4.png)
There is basically no differences...
