### ISSUE TITLE
Guide to compile on macOS is missing

### ISSUE THREAD

**Issue by schwemro** [APSIMInitiative/ApsimX#3935]
Unfortunately a guide to compile on macOS is not available ([Compilation Guide macOS](https://apsimnextgeneration.netlify.com/development/contribute/compile/osx/)). Although there is an OSX item in the guide, the guide shows the same information as for windows. May you please add the missing information how to compile APSIM on macOS. This would be great.

**Comment by hol430** [comment]
Hi @schwemro - I've updated the instructions for [compiling on macOS](https://apsimnextgeneration.netlify.com/development/contribute/compile/osx/). Let me know if it doesn't work for you.
