### ISSUE TITLE
Weather files with "date" column, but no "day" column, do not load correctly.

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#3953]

**Comment by hol430** [comment]
Can you upload the met file?

**Comment by zur003** [comment]
Here's a .met file that fails.
[Ethiopia.txt](https://github.com/APSIMInitiative/ApsimX/files/3312414/Ethiopia.txt)

I have a patch (for APSIM.Shared) that fixes this, but haven't submitted it yet.
