### ISSUE TITLE
PlantAvailableNO3 and PlantAvailableNH4 should be removed for most simulations

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3963]
Currently, APSIM requires two solutes called PlantAvailableNO3 and PlantAvailableNH4.  These are only used by AgPasture (I think) but the current implementation requires all plants to have these solutes, even though they are always zero.  These solutes are used in comms with the soil arbitrator, even though they are always zero.  The current design also requires these solutes to be part of the new Nutrient model, even though it also does nothing with them.  As a result, the solutes appear in the documentation, including the graphical representation of pools auto-generated by AutoDoc.

It would be good to see if it is possible to refactor this functionality somehow to minimise the implications for other models.

**Comment by Keith-Pembleton** [comment]
This was discussed briefly by the RP today.  Both those solutes are required for the nutrient (urine) patch in AgPasture.  The way nutrient patches are handled might need some more thought and it is conceivable that that this functionality could be desired across many of the crop models (eg for grazed crops).  It (the concept, not these two solutes specifically) also could have other applications for simulating the variability in other nutrients

**Comment by sarahcleary** [comment]
As discussed in July 2019 RP meeting - @rcichota to add comment to this issue

**Comment by sarahcleary** [comment]
@rcichota - reminder to add your comment to this issue

**Comment by sno036** [comment]
This is a solution for this but it would require all models to change to using PlantAvailableNO3/NO4 rather than their current variables.

**Comment by rcichota** [comment]
Sorry for the delay in getting something here. Agree with Val, if we get together we can figure the best way out. Here is a more lengthy (hopefully useful) explanation of why those variables exist:
The addition of 'PlantAvailableNxx' was a solution to a problem that arises when one uses the pseudo-patch capability in SoilNitrogen (Snow2016 [https://scholarsarchive.byu.edu/iemssconference/2016/Stream-B/8] and Snow2017 [https://doi.org/10.1016/j.envsoft.2017.01.005]).  This capability allows SoilNitrogen and its processes to be multiplied within a single simulation, thus enabling to account for some aspects of soil variability (particularly of interest in cases where N level is the main driver for variability). In general, even when using pseudo-patches, the other modes are no aware of this variability, the comms are made using weighted averages of all state variables.  And all the differences in how the model works are handled internally in SoilNitrogen.  
The main issue with this approach is handling changes in N content, some situations do not require anything specific (e.g. in simple fertiliser application, N is added equally to all pseudo-patches), other can be handled by SoilNitrogen (e.g. leaching is set to be proportional to the N content in each pseudo-patches). In these cases the values of N exchanged with other models are thus exactly or equivalent to those used in simulations that do not use pseudo-patches. The exception is plant uptake.  
Plants generally have a limited capacity to take up N from a given volume of soil (say 10kg/ha), and this limit should be valid for each pseudo-patch. However, if using pseudo-patches, SoilNitrogen provides values for NO3 and NH4 that are area weighted averages of all pseudo-patches and in many cases this will lead to overestimation of uptake. An example using the the 'infamous' urine patches: with two patches with (relative) areas of 0.95 and 0.05, and N contents of 5 and 500kg/ha, the averaged value of N will be 29.75, thus if the plant can take up to 10kg/ha it is not under stress. However, if the limit is applied to each patch and the weight averaged, the maximum uptake is 5.01kg/ha. This mean that it is important that the plant and SoilNitrogen get the comms right.
One way to do is to make the plants aware of the patches and let their uptake procedure decide what to take up. The other way, which was taken during the pseudo-patches development, was to add a different variable 'PlantAvailableNxx' that takes that maximum uptake limit into consideration. At the time (and note that this was in Classic Apsim) this was the easiest way as the only change needed was to add this variable. The alternative was to change each plant model...

**Comment by hol353** [comment]
@rcichota Hmmm so I'm trying to get the patching working with the Nutrient model. I can't see any code in SoilNitrogen that uses the PlantAvailableNO3 and PlantAvailableNH4 solutes at all. In SoilNitrogen.CNPatchHandlers.cs:partitionDelta there is this code:
```c#
                    switch (SoluteName.ToUpper())
                    {
                        case "UREA":
                            existingSoluteAmount[k] = Patch[k].urea;
                            break;
                        case "NH4":
                            if (senderModule == "Plant".ToLower())
                                existingSoluteAmount[k] = Patch[k].nh4AvailableToPlants;
                            else
                                existingSoluteAmount[k] = Patch[k].nh4;
                            break;
                        case "NO3":
                            if (senderModule == "Plant".ToLower())
                                existingSoluteAmount[k] = Patch[k].no3AvailableToPlants;
                            else
                                existingSoluteAmount[k] = Patch[k].no3;
                            break;
                        default:
                            throw new Exception(" The solute " + SoluteName
                                + " is not recognised by SoilNitrogen -  solute partition");
                    }
```
This code gets the value of the no3AvailableToPlants and nh4AvailableToPlants properties, not the values of the 'special' solutes. These properties seem to implement what you describe above:
```c#
            internal double[] nh4AvailableToPlants
            {
                get
                {
                    double depthFromSurface = 0.0;
                    double[] result = new double[g.nLayers];
                    double fractionAvailable = Math.Min(1.0,
                           MathUtilities.Divide(g.maxTotalNAvailableToPlants, totalMineralNInRootZone, 0.0));
                    for (int layer = 0; layer < g.nLayers; layer++)
                    {
                        result[layer] = nh4[layer] * fractionAvailable;
                        depthFromSurface += g.dlayer[layer];
                        if (depthFromSurface >= g.rootDepth)
                            break;
                    }
                    return result;
                }
            }
```
Have I missed something? Can I remove these 'special' solutes?

**Comment by hol353** [comment]
The other interesting thing is there is a bug in the first code snippet I posted above. This line will never be true:
```c#
 if (senderModule == "Plant".ToLower()) 
```

senderModule always = "Plant'. It will never be "plant". When I fix this bug though I get
```
problems with partitioning NO3 - System.Exception: attempt to change NO3[1] to a negative value
   at Models.Soils.SoilNitrogen.partitionDelta(Double[] incomingDelta, String SoluteName, PartitionApproachEnum PartitionType)
```

I'll look into it.

**Comment by hol353** [comment]
Ok So I fixed the bug above and I now also understand how these 'special' solutes work with AgPasture. Too convoluted. I'll ponder a better way of doing this.

**Comment by sno036** [comment]
Thanks Dean. Just seen this. Anything you need from me?

**Comment by rcichota** [comment]
Thanks @hol353 
Sorry I could not get to this before. I think you've found out that The output PlantAvailableNO3 is just the summary of no3AvailableToPlants (and so on). They are only use if the sender is a 'plant'. So I am not sure what the bug was (all plants had a sender in Classic, it this different in NG?), but if you fixed then all is good. 
The whole idea of this PlantAvailableN was to limit access to N in patches that have high contents (and this to consider their relative areas)...
Let me know if you need more details/discussion on this
