### ISSUE TITLE
BaseThermalTime not defined in maize model autodoc

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#3964]
I was trying to work out how thermal time was calculated in the maize model, but BaseThermalTime is not defined:
 
1.1.1.2.2 ThermalTime
ThermalTime = BaseThermalTime
Where: 

Can this please be fixed.

Regards,
Philip

**Comment by hol430** [comment]
Re-opening, as this doesn't fix the documentation for the maize example.
