### ISSUE TITLE
Only most recent simulation icon shown on apsimx GUI

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#3966]
We used to have many previous simulation icons shown on the GUI that could be user-deleted if required, but now only the latest is shown. Can this be reset to the previous view, please.

Regards,
Philip

**Comment by hol353** [comment]
Yes I have the problem as well. The most recent opened file list only ever has 1 item in it. I've noticed other users (e.g. Neil Huth) don't have this problem.

**Comment by hol430** [comment]
Doesn't affect me. I suspect the cause is the config file located at %appdata%\ApsimInitiative\ApsimX\ApsimX.xml. @hol353 can you open this file and tell me what the FilesInHistory variable is set to?

**Comment by hol353** [comment]
''
<FilesInHistory>0</FilesInHistory>
''

**Comment by hol430** [comment]
Yep that's the problem. If you close apsim and then delete this file, it will be reset to its default value of 20. Maybe when apsim first starts we should set this to 20 if it's set to 0.

**Comment by hol353** [comment]
Might be a good idea to set it to 20 if it has a value of 0.

**Comment by hol430** [comment]
I'll do that. Can you also upload your ApsimX.xml file to this issue? I think there may be more changes required here in order to rescue the mru list in some circumstances.

**Comment by hol353** [comment]
``
<?xml version="1.0" encoding="utf-8"?>
<Configuration xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <MainFormLocation>
    <X>0</X>
    <Y>0</Y>
  </MainFormLocation>
  <MainFormSize>
    <Width>1250</Width>
    <Height>884</Height>
  </MainFormSize>
  <MainFormMaximized>false</MainFormMaximized>
  <MruList>
    <string>C:\Users\hol353\Repos\ApsimX2\Prototypes\Nutrient\Nutrient.apsimx</string>
  </MruList>
  <FilesInHistory>0</FilesInHistory>
  <PreviousFolder>C:\Users\hol353\Repos\ApsimX2\Prototypes\Nutrient</PreviousFolder>
  <StatusPanelHeight>88</StatusPanelHeight>
  <DarkTheme>false</DarkTheme>
  <FirstName>Dean</FirstName>
  <LastName>Holzworth</LastName>
  <Organisation>CSIRO</Organisation>
  <Address1 />
  <Address2 />
  <City />
  <State />
  <Postcode>4350</Postcode>
  <Country>Australia</Country>
  <Email>Dean.Holzworth@csiro.au</Email>
  <MaximumRowsOnReportGrid>0</MaximumRowsOnReportGrid>
  <EditorStyleName>Visual Studio</EditorStyleName>
  <EditorZoom>1</EditorZoom>
  <BaseFontSize>12.5</BaseFontSize>
  <Font>
    <Owned>true</Owned>
    <Style>Normal</Style>
    <Variant>Normal</Variant>
    <Gravity>South</Gravity>
    <Weight>Normal</Weight>
    <Family>Calibri</Family>
    <Stretch>Normal</Stretch>
    <Size>12288</Size>
  </Font>
</Configuration>
``
