### ISSUE TITLE
Add crop option for context menu in GUI tree

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#3980]
Currently some of the crops are listed when the right click a zone and select the 'Add Model' option.  Should we have another option in the context menu which is 'Add Crop' that brings up a box with all the released crop models in it?

**Comment by zur003** [comment]
How do you define "crop"? Would this include pasture and tree models as well?

**Comment by rcichota** [comment]
Maybe "Add plant" then?

**Comment by HamishBrownPFR** [comment]
This is resolved now
