### ISSUE TITLE
Deadlock after cancelling a run in the gui

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#3996]
If I cancel a run in the gui, I seem to get a deadlock. Unsure if this happens every time or not. Am using the f5 runner if that helps. @hol353

**Comment by hol430** [comment]
This isn't strictly related to the deadlock issue, but I thought I'd post it here anyway. The AgPasture validation set now takes about 20 minutes to run on the latest master branch. If I check out code from before the recent changes to job running, this file runs in about 3 minutes.

The two runs were on different pcs so it's not a perfectly fair test, but I wouldn't expect the difference in hardware to account for this big a difference in runtime. The 3 minute run was on a Mac under mono. The 20 minutes run was on a laptop running Windows 10. If anything, I would expect performance on mono to be slightly worse, but this was not the case.

**Comment by hol353** [comment]
My Surface Pro can run the AgPasture validation in 2 minutes 30 secs.
