### ISSUE TITLE
Progress bar stopped reporting mid simulation

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#4015]
The progress bar has stopped working during a simulation and now only shows up as full when the simulation is complete.

**Comment by hol430** [comment]
Are you on latest master branch? And if so, which file are you running?

**Comment by lie112** [comment]
This happens on my latest build and the latest upgrade one of my users is using. We are running a CLEM simulation.

**Comment by zur003** [comment]
When dealing with multiple simulations (e.g., the wheat validation), the progress bar seems to update as each simulation completes. When dealing with a long-ish single simulation (e.g., the wheat example), nothing appears until the simulation has completed. For long simulations, having the progress feedback is comforting, as you get some assurance that something is happening.

**Comment by lie112** [comment]
A extensive beef herd simulation in CLEM may take 30 or so seconds. The UI used to provide a stepped indication of progress displayed in the progress bar as the simulation was performed. This has since stopped and now updates the progress bar on completion of the simulation.
