### ISSUE TITLE
Issue running Soybean validation

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4030]
I get an error when running the soybean validation set on a 32core workstation.  The model throws an exception "System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'"
The error is on the following line in APSIM.cs
        public static List<IModel> ChildrenRecursively(IModel model)
        {            
            List<IModel> models = new List<IModel>();
            **foreach (Model child in model.Children)**
            {                
                models.Add(child);                
                models.AddRange(ChildrenRecursively(child));
            }
            return models;
        }

**Comment by hol430** [comment]
This has been fixed.
