### ISSUE TITLE
apsimx R package

### ISSUE THREAD

**Issue by femiguez** [APSIMInitiative/ApsimX#4056]
I have been working on an R package that can interact with ApsimX, if anyone here wants to test it and provide feedback before I release it more broadly I'd appreciate it. The code is in github at: https://github.com/femiguez/apsimx

This is a potential contribution to the documentation of ApsimX as I include a vignette called 'writing scripts' that explains how to run ApsimX on the command line for Windows, Mac and Linux and this seems to be a frequently asked question and it is not specific to this package or to R.

**Comment by hol353** [comment]
Good to hear about this effort. Closing this issue until something needs changing in APSIM.
