### ISSUE TITLE
Create a new peanut model

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4075]
The APSIM Peanut model is being developed from the original APSIM Classic Peanut model described by Robertson et al (2002) using the Plant Modelling Framework of Brown et al (2014).

Phenology is represented as a sequence of field-observable states, the progression of each responding to temperature and (in some cases) soil water. DM partitioning is based on vegetative/reproductive state. Grain filling follows the 2002 HI model that partitions DM to grain via a target HI.

Funded by DNRME. To be built by Neil Huth. Support from Brendan Power.

**Comment by sarahcleary** [comment]
@yashvirchauhan - please discuss peanut developments with @hut104

**Comment by sarahcleary** [comment]
Please note action from RP 8/19 meeting: @yashvirchauhan - to discuss peanut developments with @hut104

**Comment by sarahcleary** [comment]
@hol353 - just following up the concept note.  For background, please refer to https://github.com/APSIMInitiative/ReferencePanel/issues/57#issue-595681585

**Comment by EnliWang** [comment]
@hut104 
In what stage is the model now?
 
At least 5 years of data from CAU (one cultivar only, but with different N treatments) can be made available to support the development and validation. These include dynamics of LAI, leaf/stem/pod/grain biomass, soil water usage.

CAU colleagues would be happy to contribute. Happy to chat in the new year?

**Comment by hut104** [comment]
Sounds good.
I hope to have an initial version of the model ready for the RP soon.
Neil.

**Comment by yashvirchauhan** [comment]
Hi Neil
It appears that the APSIM 7.10 is not able to adequately simulate the effect of high temperature. This results in a substantial gap in simulated and observed yield in hotter environments. I am attaching a paper on this aspect and if something can be done to incorporate the high (max) temperature effect on pod yield and we will have project to validate this in the northern tropics. 
[Hightemperatureeffectonpeanuts_Challinoretal2005.pdf](https://github.com/APSIMInitiative/ApsimX/files/5675981/Hightemperatureeffectonpeanuts_Challinoretal2005.pdf)

**Comment by hut104** [comment]
This certainly looks useful. We may be able to add something similar to this, however it would be useful to have test data for it.

________________________________

**Comment by yashvirchauhan** [comment]
Thanks, we will have opportunity to work on a three year project Grain and graze north: Dual purpose peanuts for northern Australia  with CQ University from next season under a CRCNA umbrella which can address the test data need. Possibly some date of sowing and heat tunnel experiments can generate required data in the first year and model modifications made which can be verified in the following two seasons. 
Some work has also been done in DSSAT.  Two additional papers relevant to this topic are attached.   Yash Chauhan
[Modellingheattolerance_BooteVaraprasad2018.pdf](https://github.com/APSIMInitiative/ApsimX/files/5686098/Modellingheattolerance_BooteVaraprasad2018.pdf)
[Sensitvityofpeanuttoheatstress_Varaprasad1999.pdf](https://github.com/APSIMInitiative/ApsimX/files/5686100/Sensitvityofpeanuttoheatstress_Varaprasad1999.pdf)

**Comment by hut104** [comment]
We need to leave this issue open as the model is not yet complete.

**Comment by hut104** [comment]
@sarahcleary I have taken this model as far as I can with the available resources.  I have autodoc, validation and sensibility tests.
Can this be put to the RP some time for review please?

**Comment by yashvirchauhan** [comment]
Good to see the peanut model coming to the review stage.

**Comment by sarahcleary** [comment]
@hut104 - there are RP Meeting "placeholders" for 6/7 and 3/8 (9:30 meeting slot). Would either of these suit you?

**Comment by sarahcleary** [comment]
@hut104 - can you please move the model into "Under Review" and upload the Model Documentation to https://apsimnextgeneration.netlify.app/modeldocumentation/

**Comment by hut104** [comment]
That’s all done.

**Comment by hut104** [comment]
I think Phil Smethurst also has his Forestry models due for review at some stage.  Perhaps we check which is more urgent.  His industry partners may have requirements.

**Comment by sarahcleary** [comment]
Thanks - will sort out offline.

**Comment by sarahcleary** [comment]
@hut104 - in preparation for the upcoming meeting- https://github.com/APSIMInitiative/ReferencePanel/issues/91
Can you please provide a copy of the presentation here?  
@APSIMInitiative/reference-panel - please note the documentation can be found here - https://apsimnextgeneration.netlify.app/modeldocumentation/

**Comment by hut104** [comment]
[Peanut Model Reference Panel.pptx](https://github.com/APSIMInitiative/ApsimX/files/6904998/Peanut.Model.Reference.Panel.pptx)
