### ISSUE TITLE
Refactor Simple leaf

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#4102]
Make code complient with code style requirements https://apsimnextgeneration.netlify.com/development/model/2-codingstyle/
Rename remove the Function suffix of the end of all the functions
Rename LeafAreaIndexFunction to Area
Remove option of setting Radiation Interception from a function.  Have it so LAI always come in from function and if a specific model is parameterised with radiation interception the can be done within the LAI function

**Comment by hol430** [comment]
Closing this, as these changes have all been implemented.
