### ISSUE TITLE
Bug in OnEventFunction

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4146]
The OnEventFunction will only update its value when we change phases. However the child functions' values could potentially change at any time. This problem was identified because we have a sorghum cultivar which modifies the value of a constant function which is referenced by the OnEventFunction. The OnEventFunction continues to return the old value of the constant even after the cultivar changes have been applied.

@HamishBrownPFR is this the intended behaviour of this function?

**Comment by HamishBrownPFR** [comment]
I thought cultivar changes were applied at sowing when the instance of the crop is set up.  The on event function should always be after sowing?
I think you are probably right that the on event function should return the current value for the Prevent function prior to the event and the current value for the postEvent function after the event.  Try changing this and see what damage it causes.  There is a HoldFunction which is intended to fix a value at an event which may be used to duplicate some of what the OnEvent function is currently doing

**Comment by hol430** [comment]
Thanks Hamish. As Jason said, it looks like several released models depend on this behaviour so we're not going to change it.
