### ISSUE TITLE
The enabled flag isn't respected when models are copied from Replacements

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4152]
This happens at the time of running a simulation.

**Comment by hol430** [comment]
How does replacing a disabled model even work? I thought disabled models were removed from the simulations tree when the simulation is run? Or does that occur after replacements are made?

**Comment by hol353** [comment]
Both. Disabled models are removed from a simulation when it is run. This happens after replacements get done.

**Comment by hol430** [comment]
@hol353 do you recall why we changed this? It appears that the behaviour now is that after the replacement model is copied into the simulation, its enabled flag is overriden with that of the model which was replaced. So if the model in the simulation is disabled, but the replacement is enabled, the replacement will be copied into the simulation and then disabled. This seems a bit counterintuitive to me - my expectation would be that if the model under replacements is enabled, but the model in simulations is disabled, the model under replacements would take priority, and would still be enabled after copying it into the simulation.
