### ISSUE TITLE
Can models be saved backward-compatible?

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#4167]
I'm working on ApsimX models and using the latest sources on Git. If I try to open a model with the latest pre-built version, it says I cannot because they were saved with a newer version. So, is there any way I can make usable versions to send to colleagues who are using pre-built ApsimX?

**Comment by lie112** [comment]
This has started to catch me out when my CLEM users are not up to date with APSIM and I send them example apsimx files. Is this to avoid known changes that cause errors, or just version control of the simulation files?

**Comment by jbrider** [comment]
There is an iterative conversion process that runs when a file is opened.
If the file is version 60 - and the version you're running is 66, it will
convert it to 61, then to 62, then to 63 and so on.
It will then record the version in the file as 66.

Unfortunately it does't work in reverse.
This process is contained within converter.cs.

People using an earlier version will not be able to open your files.
You would have to make changes to the raw json to be able to open them in
an older version - and it won't be a straight forward process in most
instances - most likely it will cause errors - and they may not be
immediately visible ones.
It would be easier to have them use the most recent version.

**Comment by rcichota** [comment]
Just want to add that we have experienced this issue a lot too. The lack of 'proper' versions and the nature of continuous improvements of APSIM can be quite a nightmare to navigate. Here we decided to created branches to freeze 'versions' of the model for use in specific projects and if all people involved are aware, it works fine. This isn't good when working with people that use a release version...

**Comment by hol430** [comment]
I think the real problem here is that there have been no new releases/pre-built version of apsim for almost 3 weeks now due to a bug in the continuous integration system, which means the compiled code will be several version numbers ahead of the released/pre-built version. I'm hoping that #4168 will fix this. Once fixed, if you do a `git pull` whenever your colleagues upgrade apsim, then your versions should generally be compatible in terms of sharing .apsimx files.

**Comment by hol430** [comment]
Closing this as it's been answered and fixed. The latest pre-built version should be able to open files created with the latest compiled version.

Feel free to reopen or open a new issue if this isn't working.

**Comment by lie112** [comment]
Would it be possible to try and deserialise the aspimx file before reporting the version error? If the file opens fine, there is no reason to report the error and the file can be assumed to be compatible. I believe this is the only reason to have the version checking. We could report a non-critical warning about the version issue and suggest they upgrade.

I am having problems with users during the rapid development phase where project files are very quickly out of date for trivial reasons and remote users (Nth WA and in Asia) aren't easily able to get the APSIM model upgraded. 

The UPGRADE server appears to be offline today.

**Comment by lie112** [comment]
Drew has alerted me to the fact that the Upgrade server issues are a result of the servers moving to a new web host and therefore getting a new address that is different to the address used in the APSIM Next Generation software code.

**Comment by zur003** [comment]
@hol430 , @hol353 - How does one now access the services that were on www.apsim.info? Specifically, I'm looking for ApsoilWebService.

**Comment by lie112** [comment]
I believe they are no on apsimdev.apsim.info
Maybe we need a txt file with links to servers that can be updated rather than have these hard coded in the code. It's going to be a bit painful getting remote people upgraded if the code can't do it.

**Comment by zur003** [comment]
@lie112 - you are correct. The services are now accessible via http://apsimdev.apsim.info/ApsoilWebService/Service.asmx. Is there any possibility the old URL could be automatically redirected to the new site?

**Comment by hol430** [comment]
There is now a redirect in place for upgrades, so upgrading should now work once more. Still a good idea to update the url in the source code though.

**Comment by lie112** [comment]
I have been looking at the upgrade code in Converter.cs. I had assumed the version was linked to the GIT build numbers used in the Upgrade window, but it seems that the APSIM Next Gen version number is a hard coded number. It is presently set to return 67 and must have recently changed to alert us to the issue of using newer apsimx files. When is this version changed and who changes it? I assume a converter is made for each step in version numbers and these are to ensure the apsimx file can be deserialised. If this process doesn't happen that often, then the upgrade to latest version approach is acceptable and shouldn't cause too many problems.

**Comment by hol430** [comment]
It's as you said - it's only there to fix breaking changes to ensure we can still deserialize old files. It has to be updated manually by the developer. It doesn't change often unless a group of us are doing a sprint with a lot of refactoring.

**Comment by lie112** [comment]
Doesn't appear that upgrade redirect is working.
Users getting 404 error on upgrade.
"The remote server returned an error: (404) Not found

**Comment by hol430** [comment]
Looks like there was another redirect needed. I've fixed  this and upgrading from an old version seems to be working for me now - can you confirm?

**Comment by hol430** [comment]
I'm going to close this now as it's been fixed. There are some ongoing issues with upgrades (specifically, we're still not signing releases) but there's a separate issue (#4315) to track such problems.

**Comment by lie112** [comment]
I'm about to push some changes I've made that pass the disable during custom build from the menu item for upgrade to the upgrade button on the popup. This will allow the dev user to see the upgrade list to communicate with users. I am just fixing a problem in that there is a null object error  on close if you already have a simulation open when doing/cancelling an upgrade.
