### ISSUE TITLE
Directory names with odd characters cause UI problems

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4189]
In CSIRO we are moving to Microsoft OneDrive. When someone shares a directory with you, the directory, by default, syncs to your computer like this:

C:\Users\hol353\CSIRO\Moore, Andrew (A&F, Black Mountain) - R-13151 DARPA World Modelers.

The APSIM user interface can open .apsimx files within this directory but when you exit you get: 
![image](https://user-images.githubusercontent.com/1943827/64930650-1a454a80-d876-11e9-87b4-3731f9920a5a.png)
Note the lack of any text. Also I notice that the file isn't being put on the most recent list on the home page. Everything else seems to be ok.

**Comment by zur003** [comment]
I'm not seeing quite that behaviour. Opening and saving on OneDrive appears to work for me, but as described, it doesn't appear on the  "most recent" list.

**Comment by hol353** [comment]
Saving works for me as well but the 'Save changes' dialog box for me doesn't have the name of the file or and text at all saying whether I want to save or not. I would expect it to look like this:
![image](https://user-images.githubusercontent.com/1943827/64932176-8f1d8200-d880-11e9-8302-ed3537471b05.png)

@zur003 Are you saying that your dialog box looks ok?

**Comment by jbrider** [comment]
The '&' seems to cause it on mine - and doesn't have to be to a onedrive
folder either.

**Comment by zur003** [comment]
Oops. No. I am seeing the same problem with saving changes. And I agree with @jbrider that the trigger for the problem seems to be the "&" in the path name, not a problem with OneDrive per se.

**Comment by zur003** [comment]
Yes, that's definitely the case with the dialog box. It's apparently using Pango markup, so "&" needs to be replaced with "&amp;". There is potential for problems with "<" and ">" as well, although those characters should never appear in filenames. 
Doing replacements is easy - the hard part is working out exactly where replacements ought to be done.
