### ISSUE TITLE
Problem when two crops are present in a field

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4193]
When plant A is sown, it publishes a PhaseChanged event. This event goes to plant B which reports the sowing as if it was it's own.

**Comment by hol430** [comment]
I thought we had tests for this sort of thing? Seems like something which would be easy enough to test.

**Comment by peter-devoil** [comment]
It only appears in the summary file. There is also a bug that shows NaNs reporting when there are two crop  modules present.
