### ISSUE TITLE
Checking of soils

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4195]
Soils in the APSIM test set can have incorrect values (e.g. LL>SAT).  There should be a discussion about when we test soil properties.  Perhaps an error should be thrown when a user enters an incorrect value.  A simulation should fail when executing with incorrect values.

**Comment by hol430** [comment]
Is this related to #1418, where soilwat will generate millions of warnings if, for example, SAT > total porosity? If so I've already changed this so that it will just throw a fatal. Just waiting on Jenkins.

**Comment by hol430** [comment]
This can be closed alongside #1418.
