### ISSUE TITLE
Improve aggregated reporting

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4202]
Would be handy if report was more powerful in terms of aggregation, as this could eliminate a lot of manager scripts.

Currently we can aggregate to [Clock].Today, but not from variable dates such as report's last report date. As part of this it would be good to refactor some of the reporting code as this is quite complex to work around.

We also need to update the test suite and documentation to include tests/examples for all of these features.

**Comment by hol430** [comment]
@hol353 the [Clock].EndOfSimulation event gets called before [Clock].DoReport. Is this intentional? It's causing some problems for me because the ReportColums need to perform some cleanup (manually unsubscribing from events) at the end of the simulation, but if we subscribe to the EndOfSimulation event, then we'll disconnect our event handlers before the final report.

**Comment by hol353** [comment]
EndOfSimulation is in the wrong place!! It will be invoked every date. This needs to be moved.

What's the use-case for moving EndOfDay to after DoReport?

**Comment by hol430** [comment]
EndOfSimulation will only be invoked on the last day of the simulation - there's a check:

```csharp
if (Today == EndDate && EndOfSimulation != null)
    EndOfSimulation.Invoke(this, args);
```

I don't have a specific use case for moving EndOfDay after DoReport; however the name EndOfDay implies that it happens at the end of the day, which is currently untrue.

If an end user without the source code is writing a manager script, they might make the (I think quite reasonable) assumption that end of day happens at the end of the day.

**Comment by sno036** [comment]
It might not be the end of the day but functionally there are no more meaty actions left?

There are times in simulations when you do want to do a report on the last day of the simulation (in these cases it would often be the only report). I don't mind if you change the stuff above provided I can set a report as "end_sim" either in Report or from a Manager script., 

Hope that makes sense!

**Comment by hol353** [comment]
Ok move the two events. This will still let you do a report on EndOfSimulation.

**Comment by hol430** [comment]
@sno036 I've added a `[Report].DateOfLastOutput` date so both of the examples you posted in the pull request *should* work. The rules around whether the aggregation is inclusive of the to/from dates are complicated but let me know if it's not doing what you expect.

Also worth noting that ave does not work for computing the average - it's actually avg despite what the documentation might say. I think we need to move away from a static PDF for the report documentation - perhaps we should create a new page on the next gen website. At least that way it's easier to find and modify.

```
Ave([Soil].SoilWater.SW) from [Report].DateOfLastOutput to [Clock].Today as AverageWaterContent
and (slightly ridiculously)
(Ave([Soil].SoilWater.Sat) + Ave([Soil].SoilWater.Dul)) from [Report].DateOfLastOutput to [Clock].Today as AverageSomethingSilly
```

**Comment by sno036** [comment]
Thanks Drew - I agree about needing to move to dynamic documentation. I think you created an issue assigned to me to create some examples? How about adding some stuff to that about making it documentation as well (i.e. using Memos to explain things)? Can you put in the info about Ave v's Avg in the comment as well please?

**Comment by hol430** [comment]
This report code should work but doesn't:

```
Sum of [Weather].Rain from [Clock].StartOfSimulation to [Clock].Today as CumulativeRainfall
```

The problem appears to be that the report initialisation occurs inside the `[Clock].StartOfSimulation` event and during report initialisation, the CumulativeRainfall report column will subscribe to the `StartOfSimulation` event but it's too late because the event has already fired.

**Comment by hol353** [comment]
@hol430 Try changing where report does it's initialisation to 'Commencing' rather than 'StartOfSimulation'
