### ISSUE TITLE
Context help button repeatedly "helpful"

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#4203]
Hi - when in the graph/series box when you press the help button for the filter function, the appropriate webpage opens. However, when you return to APSIM, whenever you click anywhere in the simulation the help webpage opens up. The only way out of this is to right click your mouse and the feature is de-activated.

Thanks

![image](https://user-images.githubusercontent.com/32279744/65479725-ab559a80-dee2-11e9-9c9b-2039f2b09f8e.png)

**Comment by hol430** [comment]
I'm unable to reproduce this one - everything here seems to work ok for me. What version of Apsim were you using? And do you still get this problem every time? Sometimes when I'm using the compiled version if I'm frequently pausing/unpausing via the debugger, the UI will get confused about whether the mouse button is held down or not. Right clicking or restarting apsim seems to fix it for me.

**Comment by MarkLieffering** [comment]
Using 4200. Could not replicate "feature" this morning. Only difference from last week was that I am on dual screens with laptop on docking station - last week on laptop only. Will try with latter configuration later in the day.

**Comment by MarkLieffering** [comment]
Upgraded to latest version 4226. Still occurs. Have narrowed it down to the issue arising when using a single screen (laptop or laptop docked to a single monitor) - does not happen when using double monitors. It is also ephemeral - will do it 10 times in a row but then not. Have not been able to establish a pattern yet. Mysterious.

**Comment by hol430** [comment]
To reproduce this you need to hold the mouse button down on the help button until the browser pops up. Then release the mouse button. Then alt+tab back to apsim. Then click anywhere and the help button will try to be helpful again. Can be reproduced on multiple monitors as long as apsim and the browser are using the same window. The solution is to show help info only when the user releases the mouse button.
