### ISSUE TITLE
Cut rotation automatic default?

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#4205]
Hi - in the cut rotation manager when you choose "How much of harvested DM (and C) is removed from the simulation? ", if you click somewhere outside the manager (i.e. one the sim tree) the selection seems to revert back to "Remove All" (when you click back to the cut rotation manager). You have to click somewhere else in the cut rotation manager itself to "save" your selection.

![image](https://user-images.githubusercontent.com/32279744/65483519-9b44b780-def0-11e9-9608-21025f0588f2.png)

**Comment by zur003** [comment]
I committed a change yesterday which should fix this problem. Try the most recent build and see whether there is still an issue.

**Comment by MarkLieffering** [comment]
I was using 2019.9.24.4197 yesterday - upgraded to 2019.9.24.4200 it seems to be fixed. Thanks!
