### ISSUE TITLE
SoilN documentation

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#4210]
Hi - when loading the Soil N documentation from https://apsimnextgeneration.netlify.com/modeldocumentation/

i.e. http://www.apsim.info/ApsimxFiles/SoilNitrogen4200.pdf

it results in a page with the APSIM headers etc. but nothing else. Is this deliberate?

Cheers

**Comment by hol353** [comment]
Looks like no-one has gone through SoilNitrogen and got the documentation right.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - for discussion at next RP meeting.

**Comment by hol353** [comment]
Add a link from SoilN documentation back to Apsim Classic SoilN documentation.

**Comment by sarahcleary** [comment]
@hol353 - has the link from SoilN documentation back to Apsim Classic SoilN documentation been added?

**Comment by sarahcleary** [comment]
@hol353 - has the link from SoilN documentation back to Apsim Classic SoilN documentation been added?

**Comment by hol353** [comment]
Nope - one day.

**Comment by sarahcleary** [comment]
@hol353 - OK, will leave this with you.  Will remove it from the RP Agenda/follow ups.

**Comment by hol353** [comment]
Done. Replaced with Nutrient documentation.
