### ISSUE TITLE
no CSV file created when running a simulation with /Csv 

### ISSUE THREAD

**Issue by HemdaLevyNZ** [APSIMInitiative/ApsimX#4231]
when running one simulation (using Models.exe) via a command line with one of the arguments is "/Csv", the csv file is not generated. 
version APSIM2019.09.24.4200

**Comment by hol430** [comment]
@HemdaLevyNZ if you do an upgrade (or a git pull if you're using the compiled version) this should be fixed.

**Comment by HemdaLevyNZ** [comment]
Thank you very much,
Hemda
