### ISSUE TITLE
Port the Classic prototype slope-aspect modifier of weather to Next Gen.

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4240]
The plan is to port the (unreleased) component developed by @rcichota to Next Gen. This would be a training task for Mike Rollo (AgResearch). Some GitHub discussion is needed to decide if it should be added into MicroMet or be a separate component. Will likely start this as a separate component so don't need an immediate decision.

**Comment by sarahcleary** [comment]
@sno036 - should this issue for linked to https://github.com/APSIMInitiative/ApsimX/issues/4288?

**Comment by hol353** [comment]
Duplicate of #4288 - closing this issue
