### ISSUE TITLE
Crash running ApsimX from command line in Debian Buster

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#4247]
Having built a model and run it interactively, I attempted to run it from the command line using this command:

`exec /usr/bin/mono /home/jaspert/Build/ApsimX/Bin/Models.exe maize_2m_gh_i3.apsimx`

...these messages were produced, before the console exited:
[errors.txt](https://github.com/APSIMInitiative/ApsimX/files/3708053/errors.txt)

Model is attached. It communicates with another program via a unix domain socket so will pause after opening.
[maize_2m_gh_i3.apsimx.gz](https://github.com/APSIMInitiative/ApsimX/files/3708043/maize_2m_gh_i3.apsimx.gz)

**Comment by zur003** [comment]
Try using:

exec /usr/bin/mono /home/jaspert/Build/ApsimX/Bin/Models.exe ./maize_2m_gh_i3.apsimx

This could be viewed as a bug, but the apsimx file argument requires a "path" portion. This path can be relative or absolute, so adding a simple "./" suffices.

**Comment by jal-frezie** [comment]
Thanks, it runs OK with that argument. Still puzzled as to why it exits the shell when it finishes though.
