### ISSUE TITLE
Add a "Fertilised" event to Fertiliser

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4253]
I am writing some documentation for Report and have realised that there are no events for Fertiliser.  Can a "Fertlised" or similar event be added. This would make it more consistent with Irrigation and easier to report on a fertilisation.

**Comment by sno036** [comment]
@hol430, @hol353 - unsure if this bug is caused by this issue or not but ...

if a "sowing fertiliser' rule is in a folder below Field then it does not seem to see the sowing event. When it is moved to directly below Field then it does respond to the event. 



        [EventSubscribe("Sowing")]
        private void OnSowing(object sender, EventArgs e)
        {
            Model crop = sender as Model;
            if (crop.Name.ToLower()==CropName.ToLower())
                Fertiliser.Apply(Amount: Amount, Type: Fertiliser.Types.NO3N);
        }

**Comment by hol430** [comment]
Yeah this is a known bug - see #3383. I wonder if we need to rethink the scoping rules.

**Comment by hol353** [comment]
Re-closing this as #3383 captures the bug.
