### ISSUE TITLE
Property presenter is not handling DisplayType.Filename

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#4263]
Properties marked with [Display(Type=DisplayType.Filename)], when viewed in the PropertyPresenter, should display both the filename text and a button which should invoke a file selection dialog when pressed. This isn't working. The button appears, but pressing it initiates editing of the text, and does not cause a dialog to appear.

**Comment by hol430** [comment]
@zur003 do you remember how this used to work? It seems like in order for the CellRendererToggle's Toggled event to fire, we have to click on it while the cell is in edit mode. It seems like it would be more intuitive if we could click on the button even if the cell is not already selected.

**Comment by zur003** [comment]
@hol430 - I have no idea why this isn't working as expected. I can't get the Toggled event to fire at all. I've submitted a pull request which provides a work-around, but we shouldn't have to do things that way. I thought this used to work (although it was never used very much), but I have no clue what may have broken it.

**Comment by hol430** [comment]
This is not a problem with the new properties UI. The old gridview-based properties UI no longer exists so I'm closing this as fixed.
