### ISSUE TITLE
Getting a dropdown of specific model types in a Manager UI

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4268]
Can we have a simple way to create a dropdown in a Manager UI that will restrict the user to choosing a particular type of model. The example below produced a massive list when I only wanted models of type Report.

And at the same time get rid of the full paths to models (@hol353 can elucidate)

        [Description("Name of the Report model for reporting on below dates every year: ")] 
        [Display(Type=DisplayType.Model)]
        public IModel ReportEveryYear_Name { get; set; }

**Comment by lie112** [comment]
I believe this functioanality is already present. From looking at the code there is an additional property of the Display attribute called "ModelType" of type "Type". If you supply this as well your list of models should be limited to the specified type.

`[Display(Type=DisplayType.Model, ModelType = typeof(Report))]`

**Comment by hol430** [comment]
> And at the same time get rid of the full paths to models

We kind of need the paths to distinguish between models of the same name:

![image](https://user-images.githubusercontent.com/36427516/66971698-8fa27600-f0d5-11e9-9270-209b03f96b29.png)

If we didn't have the full paths in the drop-down, then you'd have two items in the list both called Report and no way of knowing which is which.

**Comment by sno036** [comment]
@lie112  - thanks for that!! Needed a slight modification to work but solved the issue.

[Display(Type=DisplayType.Model, ModelType = typeof(Report.Report))]

@hol430  - would still be nice to lose the full path. If people have lots of Report models with the same name (I didn't know that was permitted) then wouldn't they have a few difficulties with graphing and other things?

Screen capture of my simulation (apologies for the quality!) below.

![image](https://user-images.githubusercontent.com/12176269/67044559-ff256d80-f188-11e9-851d-04762aaecb09.png)

**Comment by hol430** [comment]
Having multiple reports with the same name should work - they'll just store their data in the same table in the DB. Can't imagine why anyone would want to do this but a more common scenario might be having two models called Wheat - you might have a simulation called wheat and a plant called Wheat. In this case you would have two items in the drop-down both called wheat.

On the other hand, storing a full path is problematic when you copy the manager (or even the whole simulation) into another file as the path will probably become invalid.

**Comment by hol430** [comment]
I still think we need the ability to use a path-based model selection for those edge cases. Maybe we should stop showing path for DisplayType.Model and create a new value for the DisplayType enum called something like DisplayType.ModelPath, which stores/displays the full path to the model. That way you have better control as in most circumstances you would not need the path (or want it as it's less portable).

**Comment by hol353** [comment]
Yes we still need a path. Could we make it a bit smarter though. Perhaps if you enter 'wheat' as the model name, it will try and find the first wheat model that is in scope. If you enter a path then it will use that. It should never change 'wheat' to a full path though which is what is happening now.

**Comment by hol430** [comment]
>  If you enter a path then it will use that.

Well how do we want to enter a path? The drop-down component doesn't allow for raw text entry. We can populate it with paths, or we can populate it with model names.

Maybe a better solution is to always use model names, but if we hover the mouse over an item in the drop-down list a tooltip with the path to the model will appear.

**Comment by hol353** [comment]
So the gtk drop-down doesn't allow the user to type something in that doesn't appear in the drop down. The Windows Forms drop down has a property that allows this. Are you sure the gtk one doesn't?

**Comment by hol430** [comment]
I'm pretty sure we can enable text input, but isn't the whole point of a drop-down to force the user to select from a preset list of legal values?

**Comment by hol353** [comment]
Yes it is. The only option then is to show paths when needed and remove them when not.

**Use case 1 (the most common)**:
Manager is in a zone. [Display(Type=DisplayType.Model, ModelType = typeof(Report))]. The drop down should show all report models (with no paths) that are in scope. The reports in the zone with the manager should not have paths while other reports (i.e. at top level) should have paths.

**Use case 2**:
Manager is at top level. [Display(Type=DisplayType.Model, ModelType = typeof(Report))]. The drop down should show all report models (with no paths) that are in scope. The reports at the top level should not have paths while other reports (i.e. in the child zones) should have paths.

Doable?

**Comment by hol430** [comment]
So use model name for sibling models and use a path for other models in scope? That could probably work. I guess it might seem a bit odd or inconsistent to have paths and regular names side-by-side in the drop-down list.

**Comment by hol353** [comment]
Might be a bit odd but lets try it.
