### ISSUE TITLE
Miscellaneous updates could be applied

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#4272]
In trying to port ApsimX to .Net core 3, I've come across a few things that need to be updated for .Net core, but could (and should) be updated in the current code. For example, the use of the ArrayList class is now deprecated by Microsoft, but can be updated fairly easily in our current source. Also, some of the stuff for accessing Azure seems to be a bit behind the times, and is tied more closely to Windows than is necessary.

**Comment by hol430** [comment]
Closing this - these particular updates have been applied.
