### ISSUE TITLE
Jenkins builds have been failing.

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#4275]
Most of my recent pull requests have failed to run on Jenkins.  The log contains errors like this:

> StdErr:
>Warning message:
>package 'boot' was built under R version 3.5.3 
>Error: package or namespace load failed for 'sensitivity':
> .onLoad failed in loadNamespace() for 'pillar', details:
>  call: utils::packageVersion("vctrs")
>  error: package 'vctrs' not found
>In addition: Warning message:
>package 'sensitivity' was built under R version 3.5.3 
>Execution halted
>StdOut:
>   at Models.Sobol.Run() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Sensitivity\Sobol.cs:line 390
>   at Models.Core.Run.SimulationGroup.RunPostSimulationTools() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\Run\SimulationGroup.cs:line 269
>ERRORS FOUND!!

**Comment by hol430** [comment]
I don't have time to look into this this week so I am going to opt for the simple solution and install the missing packages for now and look into this more thoroughly when I have time. Will leave this issue open so that we know there is an issue for now.

**Comment by hol430** [comment]
I'm going to go ahead and close this as this particular problem appears to be fixed. Feel free to reopen if it shows up again.
