### ISSUE TITLE
How to create linked simulations in ApsimX

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#4276]
In the old Apsim I could create links in the simulation tree by alt-dragging a component to its parent node. This does not seem to work in ApsimX! Does the feature still exist, and if so, how do I access it?

**Comment by jal-frezie** [comment]
Also I tried right-clicking on my model and selecting "Copy path to link", then pasting to the parent node, and this made ApsimX crash. Attached file contains the messages produced.
[paste_error.txt](https://github.com/APSIMInitiative/ApsimX/files/3751379/paste_error.txt)

**Comment by jal-frezie** [comment]
(I wanted to ask this on the Help and Support Forum but that appears to have vanished!)

**Comment by sarahcleary** [comment]
@jal-frezie - Sorry Jasper it has.  Please post any questions on either of the two APSIM GitHub repositories. https://github.com/APSIMInitiative/ApsimX or https://github.com/APSIMInitiative/APSIMClassic

**Comment by hol430** [comment]
This feature is not currently supported in apsim next gen. Don't know if that's because someone decided against it or because no one has bothered to implement it yet. @hol353 is this a feature we want to add?

**Comment by hol353** [comment]
We don't currently have this feature in APSIM Next Gen. Maybe one day we'll implement it. We tend to use the Experiment node a lot instead.

**Comment by jal-frezie** [comment]
Hi, I don't know about the Experiment node but I just picked up some models which include Factor nodes. It looks like these implement a means of allowing one or more components of a model to be changed between runs with the rest of it staying the same, which is pretty much what I wanted to do with Links. Is there any documentation available on Factor nodes, or Experiment nodes?

**Comment by hol430** [comment]
You could check out the factorial example (ApsimX/Examples/Factorial.apsimx) which is shipped with apsim. It shows a few different ways of using the experiment/factorial system.

**Comment by hol353** [comment]
We won't be implementing links in Next Gen. Instead, a lot of users use a Replacements node at the top level of a simulation file. Any models added to it will, at simulation runtime, replace other models elsewhere in the file. This means you can have one copy of a model (e.g. REPORT or SOIL or anything else) that gets used everywhere which is what the APSIM 7.10 linking mechanism was mostly used for.
