### ISSUE TITLE
Grouped references in autodocumentation not formatted correctly

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#428]
Groups of references in autodocumentation PDF's are not formatted correctly.  For example:  See group of three references in the following text.

This test evaluates performance of the APSIM AgroforestrySystem model in simulating crop and soil water data of (Odhiambo et al., 1999)(Odhiambo et al., 2001)(Wilson et al., 1998). The experiment was conducted at ICRAF’s field station at Machakos, Kenya (1o 33’S and 37o 8’E) at a mean elevation of 1660 m. Bimodal annual rainfall averages 740 mm.

**Comment by hol353** [comment]
Not a defect. References should be separated by ';' characters inside square brackets. e.g.
[Odhiambo et al., 1999;Odhiambo et al., 2001;Wilson et al., 1998]
