### ISSUE TITLE
A box-whiskers plot style would be useful

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4285]
On the wish-list

**Comment by sno036** [comment]
As discussed @hol430  - this seems to have broken all graphs. Can this be your top priority now that Jenkins is up?

**Comment by hol430** [comment]
This should be fixed now that #4305 is fixed...is it still broken for you?

**Comment by sno036** [comment]
@hol430  - yes - sorry - missed that message. Just pulled and working again. Thanks.

**Comment by hol430** [comment]
Closing this because the box plots have been implemented.
