### ISSUE TITLE
What is Zone column in a Report?

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#4298]
Why is the zone column value in reports simply set to the Report's Parent.Name? (Report.cs line 142)
I would have expected Zone to read up the tree until it found a parent of type Zone.
I was looking to run multiple CLEM instances (each effectively a Zone) within a Simulation and use the Zone column in reports to distinguish the output from each farm, but the report presents the name of the folder holding the report ("Reports") as the zone name and seeing each farm has the same structure, they all report "Reports" as the Zone name.
Is this the intentional use of the Zone column, or is the a hangover from a previous simple implementation that adding a more complex tree structure for CLEM simulations doesn't follow?

**Comment by hol430** [comment]
This is a bug

**Comment by hol353** [comment]
It should look up the tree for a Zone model. This is a bug that needs fixing.

**Comment by lie112** [comment]
As this is now working, the data presented should be filtered by the zone that the report is present in like simulation filtering.
Add zone filtering to the data presented from a report.
