### ISSUE TITLE
Develop a Clover Root Weevil model

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4322]
Clover Root Weevil is an insect pest of clover in pastures and for seed. The larvae graze roots and nodules and as they mature into adults start grazing the leaves. The adults are somewhat mobile. The infestation accumulates and can be quite damaging resulting in reduced N fixation for the pasture and reduced pasture quality.

The model use the Lifecycle model (which may need some enhancement along the way). Funded by AgResearch's Strategic Science Investment Fund. Will only get to a prototype stage in this financial year. Mark McNeil will gather the various data sources and Val Snow will configure the simulations. There will likely be a workshop in March/April 2020 for some expert elicitation. Jeremy Whish will be involved in the development work and hopefully also in the workshop.

One addition known to be needed is a function from insect population to plant damage. Will design this in collaboration with Jeremy and PFR (who will be working on some sort of potato pest).

**Comment by sarahcleary** [comment]
Action from RP meeting - tagging in @josharp22' @RobZys; @ekhaembah and @HamishBrownPFR
