### ISSUE TITLE
Have to use the full path of apsimx file

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#4331]
In the master branch, the command line is not working as expected. 

Models.exe path.apsimx /Csv

Have to use the full path to apsimx file. The error message is 

System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at APSIM.Shared.Utilities.DirectoryUtilities.FindFiles(String directoryName, String fileSpec, List`1& fileNames, Boolean recurse, Boolean searchHiddenFolders) in C:\Users\zhe00a\Documents\Working\04-Software\032-ApsimX\ApsimX\APSIM.Shared\Utilities\DirectoryUtilities.cs:line 63
   at Models.Core.Run.Runner..ctor(String pathAndFileSpec, List`1 ignorePaths, Boolean recurse, Boolean runTests, RunTypeEnum runType, Boolean wait, Int32 numberOfProcessors, String simulationNamePatternMatch) in C:\Users\zhe00a\Documents\Working\04-Software\032-ApsimX\ApsimX\Models\Core\Run\Runner.cs:line 101
   at Models.Program.Main(String[] args) in C:\Users\zhe00a\Documents\Working\04-Software\032-ApsimX\ApsimX\Models\Main.cs:line 102

**Comment by hol430** [comment]
Unable to reproduce - this appears to be working perfectly for me. Can you zip up your .apsimx/.met files and tell exactly which command you are running and from which directory you're running it? e.g.

```powershell
PS C:\ApsimX\Examples> ..\Bin\Models.exe .\Factorial.apsimx /Csv
Successfully created csv file .\Factorial.csv
```

Also which OS/shell are you using?

**Comment by femiguez** [comment]
@byzheng I ran into that error because of path issues in Windows. See the following: https://femiguez.github.io/apsimx-docs/apsimx-scripts.html
It might help

**Comment by hol430** [comment]
@femiguez I had a quick read of the page you linked and I guess the need to use `Models.exe .\Wheat.apsimx` instead of `Models.exe Wheat.apsimx` could be the problem that Bangyou is running into. Apsim should probably work in both of these cases - I'll see if I can fix this.

> Note: it seems that, in Windows, it is only possible to run files in the current directory. So, for example, if the file ‘Wheat.apsimx’ was in subdirectory ‘./myApsimXsimulations’ and you want to replace the ‘./Wheat.apsimx’ above with ‘./myApsimXsimulations/Wheat.apsimx’ this does not work. I do not know if there is a possible workaround.

I'm not experiencing this behaviour though, and in fact I don't even need a ./ before the subdirectory name:

```powershell
PS C:\ApsimX> Models.exe .\Examples\Factorial.apsimx
PS C:\ApsimX> Models.exe Examples\Factorial.apsimx
PS C:\ApsimX>
```

Admittedly this is when running directly from a shell. Do you experience this problem only when running from R? If so, maybe you need to specify a working directory for the shell command?

**Comment by byzheng** [comment]
@femiguez @hol430 Thanks for your help. I have problem when the path doesn't start with ".\" in the R environment and shell. 

My working workaround in R is 

system(paste0('path-to-models.exe', file.path(getwd(), "relative-path-to-apsimx")))

**Comment by femiguez** [comment]
@hol430 The reason why it works for you and not for me might have to do with paths. On my windows machine, this is my path:

C:\Users\femiguez>path
PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\SASHome\SASFoundation\9.4\ets\sasexe;C:\Program Files\SASHome\Secure\ccme4;C:\Program Files\SASHome\x86\Secure\ccme4;C:\Program Files (x86)\Skype\Phone\;C:\Users\femiguez\AppData\Local\Microsoft\WindowsApps;C:\Users\femiguez\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\

Notice that although I have APSIM 'Classic' and 'NextGen' Installed they are not in the search path. I suspect that in your system, you have added 'C:\ApsimX' to the path, that's it why it works for you and why Windows is able to find 'Models.exe' and 'Wheat.apsimx'. Forcing the path to start with './' makes the file available. For most people, writing 'Models.exe Wheat.apsimx' at the command prompt will not work.

@byzheng I didn't realize you were trying to run APSIM-X in R. Did you see my package?
The reason why I wrote is to facilitate writing scripts in R which interact with APSIM-X. https://github.com/femiguez/apsimx 
Documentation:
https://femiguez.github.io/apsimx-docs/

**Comment by femiguez** [comment]
@hol430 A concrete example. When I run this at the prompt:

C:\Users\femiguez\Dropbox\apsimx-other\Examples>C:\PROGRA~1\APSIM2019.10.04.4236\Bin\Models.exe Wheat.apsimx

I get this error:

System.ArgumentException: The path is not of a legal form.

[...more error messages...]

and when I run this:

C:\Users\femiguez\Dropbox\apsimx-other\Examples>C:\PROGRA~1\APSIM2019.10.04.4236\Bin\Models.exe .\Wheat.apsimx

It works jut fine.

**Comment by hol430** [comment]
Hi @femiguez - I do have the apsimx bin directory on path which is why I don't need to specify the path to Models.exe, but I definitely don't have the apsimx directory or the examples directory or current directory (./) on path. Even if I did, apsim doesn't look on the path when trying to interpret the .apsimx file spec. That said, I'm now able to reproduce this bug and think I know the cause of the problem. Will get a fix out when I can.
