### ISSUE TITLE
Make a node 'read only' in the UI

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4342]
It would be handy - a 'nice to have' if it were possible to make a node and all it's children 'read only' - e.g. through a right-click on the item. The simulation (or whatever) would still be active etc. but the user could not accidentally edit it.

**Comment by hol430** [comment]
If the node is read-only, how do you make it editable again?

**Comment by sno036** [comment]
Unsure if you had your tongue stuck out there - will proceed as if not. The read-only would be a toggle (as with 'enabled').
