### ISSUE TITLE
IPostSimulationTool.Run() outside simulation performed

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#4346]
We have implemented some of the CLEM reports as IPostSimulationTool to allow SQL scripts to be executed at the end of the simulation to display synthesised data. I assume this is what this interface is designed for.
The problem is the code in SimulationGroup.cs runs (RunPostSimulationTools()) all models of type IPostSimulationTool in all simulations. I would have expected that only those models inside the simulation that you performed should have the Run() method called. Is this a bug or an intentional outcome I didn't expect?

**Comment by hol353** [comment]
This is intended. We use the IPostSimulationTool interface to allow us to gather predicted/observed data together after all simulations have completed. Even if the user only runs a subset of simulations we need to run the PredictedObserved.cs tool which is a child of DataStore. So the code has been written to run all post simulation tools regardless of what has been run.

**Comment by lie112** [comment]
Thanks. Is it possible to know what simulation has been run, or whether a model is inside the currently running simulation? I could then only perform the Run() on the reports of the current simulation being run.

**Comment by hol353** [comment]
Not currently possible. Would require some reworking of the infrastructure.

**Comment by lie112** [comment]
I don't suppose there is any documentation about the deeper workings of APSIM next gen. It would be nice to understand some of the linkage and perform simulation functionality without having to learn from reading and interpreting the code, even if only for my code education. I'm also keen to understand how manager scripts work to compile at runtime. Maybe some coffee chats at the workshop next year.
Do we report what .Net version (c# version) we are up to? I know it was Gtk# holding us back. I noticed Drew started using $"xxx{var]" string interpolation that I had to remove from all my code some time ago.
Anyway, another approach to solve my problem would be to add an additional PostSimulation or SimulationCleanUp event in the Clock that anything could subscribe to. This would suffice for my purposes as it would happen after the DoReport event. I assume everything else has been finalised by the time Simulation terminated normally is displayed at end of Clock and this would replicate the IPostSimulationTool.Run method.

**Comment by hol430** [comment]
According to the .csproj files we're using .NET 4.6. Don't know why we settled for this version specifically but there's probably not much point changing it if a move to .net core is on the horizon anyway. I think we officially support C#7 now - we dropped support for visual studio 2015 a while ago (around when vs 2019 was released?) which was when I started using the C#7 features like string interpolation and inline out variable declarations which if I recall correctly weren't supported by vs 2015 and C#6.

Regarding your specific problem, There is already an event called "EndOfSimulation" which you can subscribe to but I'm not sure if it will suit your purposes, as the data store writer thread may not have finished writing to the data store when this event fires.

I think that even if you add another event to the clock code you would still run into the same problem, because I don't think we wait for the datastore to finish writing until the IPostSimulationTools are run, at which point I don't know if you would have enough context to know which simulations have been run. I could be wrong though as I haven't tested this.

**Comment by lie112** [comment]
Totally agree with point 1. Hopefully .Net core isn't to difficult. I seem to have opened a large can or worms. 
EndOfSimulation is called before DoReport which fires after day loop is completed.
Actually, from what I read EndOfSimulation happens before EndOfYear and EndOfDay for the last day and year of simulation and all CLEM events. 
Why isn't EndOfSimulation fired after the day loop just before
`            Today = EndDate;
            Summary.WriteMessage(this, "Simulation terminated normally");`
Then this would suffice for what I need..

**Comment by hol430** [comment]
Yeah there was some discussion in #4202 where we decided that we should move the EndOfSimulation event, but I guess I never got round to it. Feel free to move it to happen after everything else. Would be interesting to see if it had an effect on the stats.

**Comment by lie112** [comment]
I am now using the corrected EndOfSimulation event as IPostSimulationTool was not the correct approach.

**Comment by hol430** [comment]
Does this solution work properly? I had a suspicion that the datastore may not have finished writing to disk when the EndOfSimulation event fires. Could be wrong though.

**Comment by lie112** [comment]
It doesn't appear that the functionality I need is present. I thought all events would be managed by the clock but I just found the Completed event fired by the JobManager and realised that this is where all the report data is written. This event doesn't really suit  either as I need to perform actions after I know all the reports are written and there isn't an event post Completed. Everything from Completed onwards through IPostSimulationTool.Run doesn't know about the actual simulation performed. I should be able to work with PostSimulationTool.Run()

**Comment by hol430** [comment]
@lie112 is this still a problem? If so, one thing you could try is subscribing to the `EndOfSimulation` event and calling:

```csharp
[Link] IDataStore storage;
...
storage.Writer.WaitForIdle();
storage.Reader.Refresh(); // this may or may not be necessary
```

The `WaitForIdle()` function of IDataStore will do a busy wait until the storage writer thread has finished writing everything. This sounds like it might be all you need.

**Comment by lie112** [comment]
Thanks. I had misunderstood this functionality and only wanted models within the simulation to perform Run() at the end (not all models in Simulations) so have addressed this in other ways.
