### ISSUE TITLE
LifeCycle output issues

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4347]
The two outputs from LifeCycle pasted below should give the same output but the first one always returns zero. "Count" is supposed to return the number of individuals in the Cohort but I suspect that it is not doing this correctly.

Sum([LifeCycle].Egg.Cohorts.Count) as EggCount1
[LifeCycle].Egg.TotalPopulation as EggCount2

@hol353 is thinking about it

**Comment by her123** [comment]
The aggregation in the first line is invalid. It would not be correct to aggregate a property of a list item this way.

**Comment by hol353** [comment]
Actually there is code specifically in the locator class to allow aggregation of a list item. It does work and it is really handy.

**Comment by her123** [comment]
A LifeStage does not expose the cohorts list so there is no Cohort property. The correct way to get the population for a LifeStage is to use TotalPopulation.
