### ISSUE TITLE
New comer want to learn Wheat module and wheat yield math equation

### ISSUE THREAD

**Issue by pandaUHM** [APSIMInitiative/ApsimX#4350]

**Comment by pandaUHM** [comment]
Seeking advice on crop yield math equation

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel and/or others - @pandaUHM is researching on how El Nino and Southern Oscillation impact on crop yield in different region by using your crop model. He is looking for using the crop yield math equation to see how much climate and weather part influence the crop yield and if they are important in the model. Can anyone assist?  or point to a relevant paper?

**Comment by peter-devoil** [comment]
There isn't a single equation - it's a dynamic model with many interacting components. The most complete set is [here](https://www.apsim.info/wp-content/uploads/2019/09/WheatDocumentation.pdf), your question is Eqn 34. It doesnt have a very direct link with ENSO. You might consider posing two questions "a) how does enso influence the environment that crops grow in, b) how do crops respond to the environment they grow in" 

Here's some reading that might help you get started:
https://doi.org/10.1071/AR9930625
https://doi.org/10.1007/978-94-015-9351-9
https://doi.org/10.1007/s10113-013-0455-1
https://doi.org/10.3390/cli6030077

**Comment by pandaUHM** [comment]
> @APSIMInitiative/reference-panel and/or others - @pandaUHM is researching on how El Nino and Southern Oscillation impact on crop yield in different region by using your crop model. He is looking for using the crop yield math equation to see how much climate and weather part influence the crop yield and if they are important in the model. Can anyone assist? or point to a relevant paper?

Thank you @sarahcleary helping me for seeking help. Appreciate that.

**Comment by pandaUHM** [comment]
> There isn't a single equation - it's a dynamic model with many interacting components. The most complete set is [here](https://www.apsim.info/wp-content/uploads/2019/09/WheatDocumentation.pdf), your question is Eqn 34. It doesnt have a very direct link with ENSO. You might consider posing two questions "a) how does enso influence the environment that crops grow in, b) how do crops respond to the environment they grow in"
> 
> Here's some reading that might help you get started:
> https://doi.org/10.1071/AR9930625
> https://doi.org/10.1007/978-94-015-9351-9
> https://doi.org/10.1007/s10113-013-0455-1
> https://doi.org/10.3390/cli6030077

Aloha，

First I really appreciate both of you guys Friendly help! My research is based on the MET  file change in the wheat module and I set the ENSO related Met file as the only Forcing. I control all the other variables like the sowing method, soil document not change. And see how wheat yield change with that. So I would like to see how Met part important in the dynamic equation.

Thanks you @peter-devoil  for giving me the link of the  paper and equation. I will read it seriously. And I think the result I need should be in it. And I appreciate for your generous help so much.

**Comment by peter-devoil** [comment]
Hi, You might want to have a read of this (quite dated)  [climate change exercise](https://www.apsim.info/support/apsim-training-manuals/apsim-training-simlesa/climate-change-projections/) that demonstrates change projections in maize. Wheat is easier as you dont need to hack .ini files (step 6) - it's CO2 parameters will work out of the box.

**Comment by hol430** [comment]
I'll close this now as it's been answered. Feel free to reopen or open a new issue if you have more questions.
