### ISSUE TITLE
ApsimNG crashes when run from command line

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#4356]
I get this error from command line, but no problem from inside the interface.

```
System.Exception: Error in file:C:\Users\uqbababa\UQ\00_Projects\2018.12.06 APSIM Calibrator\02_Simulations\Examples\TestNG_1__SUFI.apsimx ---> System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Models.Core.Run.SimulationGroup.Initialise() in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Models\Core\Run\SimulationGroup.cs:line 144
   --- End of inner exception stack trace ---
ERRORS FOUND!!
```

**Comment by BenAbabaei** [comment]
[TestNG_5__SUFI.zip](https://github.com/APSIMInitiative/ApsimX/files/3840740/TestNG_5__SUFI.zip)

**Comment by hol430** [comment]
Is there a sqlite.dll file in ApsimX/Bin/?

Sounds like you might need to manually copy the files from ApsimX/DeploymentSupport/Windows/Bin64/ into ApsimX/Bin/. This is supposed to happen when you compile but maybe it's not working properly.

**Comment by BenAbabaei** [comment]
Yes there is a sqlite3.dll. SHould I re-copy those files now?

**Comment by hol430** [comment]
Yeah give it a go. Also, what's in the `APSIMConsolePath` and `SimFiles` variables?

**Comment by BenAbabaei** [comment]
I copied the files, not fixed. 

```
APSIMConsolePath = C:/Users/uqbababa/UQ/07_Repository/ApsimNextGen/ApsimX/Models/Bin/Models.exe
SimFiles = Full name of the apsimx file.
```

**Comment by peter-devoil** [comment]
Point http://www.dependencywalker.com/ at sqlite3.dll, and also be sure youre not mixing 32/64 bit dlls?

**Comment by BenAbabaei** [comment]
Hmmm ... what is this now? 

![image](https://user-images.githubusercontent.com/39573622/68820737-0d0ed580-06d8-11ea-911d-4414c877f100.png)

**Comment by peter-devoil** [comment]
Looks like some sort of versioning/architecture thing - there are 1-2 missing for each dll. Importantly, there is a "64" next to  sqlite3.dll:
 
![Capture](https://user-images.githubusercontent.com/1924386/68826041-fff9e280-06e7-11ea-824c-461fdb303398.PNG)

b) have you rebooted today?
c) have you considered linux? :)

**Comment by peter-devoil** [comment]
You can probably [just ignore](https://stackoverflow.com/questions/36240215/dependency-walker-missing-dlls) them.

**Comment by BenAbabaei** [comment]
I tried reseting, didn't work. I also thought about Linux, I think it was in a nightmare :)

**Comment by peter-devoil** [comment]
Sorry, ben. Looks like a job for a debugger.

**Comment by hol430** [comment]
How did you compile apsim - was it in Debug|AnyCPU mode?

**Comment by BenAbabaei** [comment]
Yes. And I only have the problem through the command line, not inside the interface.

**Comment by hol430** [comment]
Can you run apsim fine from the command line (not from R - from a command prompt)?

**Comment by BenAbabaei** [comment]
Yes. Does APSIMNG has any sensitivity towards '__' in the file name?

**Comment by hol430** [comment]
Underscores in the filename shouldn't matter. The fact that you can run apsim from the command line but not from R is interesting. Can you try running from R something like `cmd /c /path/to/Models.exe /path/to/apsimx/file.apsimx`? e.g.

```r
cmd <- 'cmd'
args <- '/c /path/to/Models.exe /path/to/file.apsimx'
system2(command = cmd, args = args)
```

**Comment by BenAbabaei** [comment]
I got the same error:

```
System.Exception: Error in file:C:\Users\uqbababa\UQ\00_Projects\2018.12.06 APSIM Calibrator\02_Simulations\Examples\TestNG_1__SUFI.apsimx ---> System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Models.Core.Run.SimulationGroup.Initialise() in C:\Users\uqbababa\UQ\07_Repository\ApsimNextGen\ApsimX\Models\Core\Run\SimulationGroup.cs:line 157
   --- End of inner exception stack trace ---
ERRORS FOUND!!
```

**Comment by BenAbabaei** [comment]
I was mistalenly using **ApsimX\Models\Bin\Models.exe** instead of **ApsimX\Bin\Models.exe**. I am not sure whether my previous choice should have worked. But it does not. My case is closed now. Cheers.
