### ISSUE TITLE
Box plots graphs

### ISSUE THREAD

**Issue by sarchontoulis** [APSIMInitiative/ApsimX#4361]
the ability to generate box plots will be useful to check model performance. The functionality in APSIM classic will be nice to be added in the APSIM next

**Comment by hol430** [comment]
This should already be possible if you select Box from the graph type drop down:

![image](https://user-images.githubusercontent.com/36427516/68899692-f15e0a80-077d-11ea-8b8f-fb6eb82f54b4.png)

**Comment by hol430** [comment]
I'm going to close this. Feel free to reopen or open a new issue if this isn't working properly.
