### ISSUE TITLE
There is no icon associated with StorageNDemandFunction

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4362]
I'd suggest that  a storage icon from the old flowchart days might be appropriate.

**Comment by hol430** [comment]
@hut104 where can I find this flowchart?

**Comment by hut104** [comment]
Here is an example of some flowcharting symbols.  This is only a suggestion.
https://creately.com/blog/diagrams/flowchart-guide-flowchart-tutorial/
