### ISSUE TITLE
MaximumPotentialGrainSize is not actually used directly in code of reproductive organ

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4363]
This member was added to allow use by child functions.  However, we now have grain models that do not use grain number (ie use Harvest Index approach) and so these models must add this parameter even though it is not used.  I suggest that the member be removed and the models changed to directly read the function, rather than the member of the reproductiveorgan which just holds this value (not a good design approach in any case).

**Comment by hol353** [comment]
This has already been removed from reproductive organ
