### ISSUE TITLE
Problems with initial soil N

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4364]
If a property in a profile grid such as NO3N or NH4N is set to null, any attempts to edit any cell in the null property's column will be futile. After typing a value into the cell and hitting enter, the cell will immediately revert to being empty.

Additionally, any such sample which contains null for NO3N will throw an error when the simulation is run, when it converts from kg/ha to ppm. This code should be more forgiving of nulls, as the converter seems to sometimes spit out nulls when upgrading old files.

**Comment by hol430** [comment]
@hol353 I'm adding unit tests so that this doesn't happen again but I noticed that all of the existing soil tests are commented out... is there a reason for this?

**Comment by hol353** [comment]
Not intentional. I must have commented them out when I was refactoring soil and forgot to uncomment them.

**Comment by hol430** [comment]
Looks like there are some changes needed to get these tests up and going again so you'll probably have to do it yourself. e.g. it references some types that I can't find such as `SoilModel` and `APSIMReadySoil`.

**Comment by JJguri** [comment]
I want to export the total amount of NO3N in kg ha-1 (not ppm) for the entire profile using the Nutrient module. I tried 
`(sum([Soil].Chemical.NO3N.kgha)) as TotalNO3N` but it does not work. I was using a similar code to export this output using the Nitrogen module `(sum([Soil].SoilNitrogen.NO3.kgha)) as TotalNO3N` and it works well.

**Comment by hol430** [comment]
Looks like this isn't possible out of the box. @hol353, @hut104, is this intentional, or just something that hasn't been implemented yet?

I haven't tested this but you could probably achieve what you want via a manager script:

```csharp
[Link] private Soil soil = null;

public double NO3Nkgha
{
    get
    {
        return soil.ppm2kgha(soil.NO3N);
    }
}
```

Then you can add to your report:

```
sum([ManagerName].Script.NO3Nkgha) as TotalNO3N
```

**Comment by JJguri** [comment]
I want to get the total amount of N (initial N plus N from fertiliser) by simulation in kgN ha.

I tried with the script but it did not work. Please see below the error. I am also attaching the apsimx. The manager is included in the first simulation called 380074_Che8_sna_20_O. 

System.Exception: Errors found in manager model Fertkgha
Line 3: A namespace cannot directly contain members such as fields or methods
Line 4: Expected class, delegate, enum, interface, or struct
Line 5: Expected class, delegate, enum, interface, or struct
Line 7: Expected class, delegate, enum, interface, or struct
Line 14: Type or namespace definition, or end-of-file expected

   at Models.Manager.RebuildScriptModel()
   at UserInterface.Presenters.ManagerPresenter.BuildScript()

[Sorghum_V6.zip](https://github.com/APSIMInitiative/ApsimX/files/5100753/Sorghum_V6.zip)

**Comment by hol430** [comment]
Yeah sorry I omitted the rest of the script boilerplate in my example. You need a class/namespace declaration; a full copy of the script could look something like:

```csharp
using System;
using Models.Core;
using Models.Soils;

namespace Models
{
	[Serializable]
	public class Script : Model
	{
		[Link] private Soil soil = null;
		[Link] private Chemical chemical = null;

		public double[] NO3Nkgha
		{
			get
			{
				return soil.ppm2kgha(chemical.NO3N);
			}
		}
	}
}

```

**Comment by JJguri** [comment]
It is working now! Maybe a good idea will be to allow users to chose between ppm or kgha. It will depend on the objective of the modeller.

**Comment by JJguri** [comment]
Now, I included NH4N

```
using System;
using Models.Core;
using Models.Soils;

namespace Models
{
	[Serializable]
	public class Script : Model
	{
		[Link] private Soil soil = null;
		[Link] private Chemical chemical = null;

		public double[] NO3Nkgha;
		public double[] NH4Nkgha
		{
			get
			{
				return soil.ppm2kgha(chemical.NO3N);
				return soil.ppm2kgha(chemical.NH4N);
			}
		}
	}
}
```

but it provided this error:
```
System.Exception: Errors found in manager model FertKgha
Line 19: Unreachable code detected

   at Models.Manager.RebuildScriptModel()
   at UserInterface.Presenters.ManagerPresenter.BuildScript()
```

**Comment by hol430** [comment]
Try this:

```csharp
using System;
using Models.Core;
using Models.Soils;

namespace Models
{
	[Serializable]
	public class Script : Model
	{
		[Link] private Soil soil = null;
		[Link] private Chemical chemical = null;

		public double[] NO3Nkgha
		{
			get
			{
				return soil.ppm2kgha(chemical.NO3N);
			}
		}

		public double[] NH4Nkgha
		{
			get
			{
				return soil.ppm2kgha(chemical.NH4N);
			}
		}
	}
}
```

**Comment by JJguri** [comment]
all good! sorry I need to improve a little bit more my script writing

**Comment by hol353** [comment]
Doesn't this work from report?

```sum(NO3.kgha) as TotalNO3```

**Comment by JJguri** [comment]
No it does not work. Here is the error

```
System.Exception: ERROR in file: C:\Users\jjojeda\Google Drive\COALAR\Sorgo\Sorghum_V6.apsimx
Simulation name: 458099_LTi1_bow_19_F
System.Exception: Error in report InitialReport: Invalid report variables found:
NO3
   at Models.Report.DoOutput()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.PMF.Plant.Sow(String cultivar, Double population, Double depth, Double rowSpacing, Double maxCover, Double budNumber, Double rowConfig)
   at Models.Script.OnDoManagement(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) ---> System.Exception: Error in report InitialReport: Invalid report variables found:
NO3
   at Models.Report.DoOutput()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.PMF.Plant.Sow(String cultivar, Double population, Double depth, Double rowSpacing, Double maxCover, Double budNumber, Double rowConfig)
   at Models.Script.OnDoManagement(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   at APSIMRunner.Client.Run()
```

**Comment by hol430** [comment]
Try square brackets around NO3: `sum([NO3].kgha) as TotalNO3`

**Comment by JJguri** [comment]
yes! it is working now. Thanks @hol430. So now we have two ways to get it.
