### ISSUE TITLE
Function works in Excel but not apsimx

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#4365]
The An expression in Exce;l
(EXP(5.132+(0.644*(LN(23.703)))))/100

**Comment by sme016** [comment]
Restated, sorry:

The expression '= EXP(5.132+0.644*LN(23.703))/100'  works in Excel with the result 13.01. However, in apsimx a value 32.07 is returned. Do you get the same result in apsimx?

**Comment by hol430** [comment]
How are you evaluating this expression? In a manager script? In a report?

**Comment by sme016** [comment]
Hi Drew,

Thanks for getting to this.

It’s in an Alnus tree model that I am developing, which is an adaptation of the Eucalyptus model.

I have not changed the expression to something else that works, but it would still be good to know that the other could work if needed – screenshot below sowing location Alnus model (with is a similar location to that in the euc model).

Thanks,
Philip

[cid:image001.png@01D59E0C.0599CF60]

**Comment by hol430** [comment]
Your screenshot doesn't seem to have made it through...maybe email it to me if that's easier?

**Comment by hol430** [comment]
Wow....looks like apsim interprets ln(x) as log base 2 of x. That seems pretty bizarre to me - I'll fix it and see if it breaks anything.

**Comment by sme016** [comment]
I am glad you could reproduce the problem.

Thanks,
Philip
