### ISSUE TITLE
Tests table not showing

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#4370]
I am not sure this is an issue/problem or whether it has been decided that tests table are not to be shown (I could not find anything on that when searching issues). If I recollect right, when a simulation contains 'Tests' under a PredictedObserved (and after running the simulation), one could examine the a table with the results of the several metrics Apsim computes (this table was also added to the documentation). This is no longer the case; when selecting the 'Tests' node, one cannot see any of the results and no table is shown in the documentation (I've checked white clover). Is this right?

![image](https://user-images.githubusercontent.com/12175986/69020084-42892b00-0a18-11ea-8b8a-ecafd7377b23.png)

**Comment by hol430** [comment]
@rcichota is this what the table  used to look like?

![image](https://user-images.githubusercontent.com/36427516/70012513-4d1ef500-15c0-11ea-852e-65a9f99c3aa5.png)
