### ISSUE TITLE
Report - error summing array of root weights

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4380]
Summing parts of arrays works for Soil (for example) but not for plant roots (for example). Why?

In the attached the two lines
    Sum([Wheat].Root.LayerLive.Wt) as AllRoot
    Sum([Wheat].Root.LayerLive.Wt[2:5]) as AllRoot2_5
give the same values (they should not)

[SumExample.zip](https://github.com/APSIMInitiative/ApsimX/files/3866875/SumExample.zip)

**Comment by sno036** [comment]
Lucas found the problem but a fix is still needed.

Sum([Wheat].Root.LayerLive.Wt[2:5]) should have been Sum([Wheat].Root.LayerLive[2:5].Wt) 

but the original (wrong) version should have thrown an error.

**Comment by hol353** [comment]
Actually it shouldn't throw an error because it is valid syntax. My fix will now produce the expected results.
Fixed in #4547.

**Comment by sno036** [comment]
@hol353 - the prototype simulation ...Prototypes\CloverRootWeevil\CRW_V0.apsimx used to take a few seconds (it is only 2.5 years long) and now takes almost 5 minutes. After consultation with @HamishBrownPFR (because I initially blamed the new damage interface for Lifecycle!) it seems that it is being caused by aggregations in report is as

Mean([LifeCycle].Egg.Cohorts.PhysiologicalAge) as meanEggPhysAge

Could this be an unintended result of this fix?

**Comment by hol353** [comment]
@sno036:  I pulled your remote branch, did a rebuild, opened CRW_V0 in the GUI, ran APSIM and it took 4 seconds. Don't know why yours is taking so long.

Have you done a rebuild in Visual Studio and emptied the data store?

**Comment by sno036** [comment]
Yes I have (pulled and emptied) but will try again - probably not today though. Will let you know.

**Comment by hol430** [comment]
@sno036 is this still an issue?

**Comment by sno036** [comment]
Might as well close it - it can be reopened.
