### ISSUE TITLE
Stock and Supplement need NextGen "Science" documentation

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4385]
Static documentation uploaded to documentation website. There is the Grazplan documentation but that needs to be updated with variable names etc and there might be new or outdated features.

**Comment by sno036** [comment]
Refactor Stock and Supplement component documents into PDF for APSIM website. Leave out the parts not relevant to NextGen.

**Comment by her123** [comment]
Documentation required:
1. Example simulations with memos showing details
2. Science doc (GrazPlan technical doc) - make a link to https://grazplan.csiro.au/wp-content/uploads/2007/08/TechPaperMay12.pdf
3. Stock model component description
  - auto generate, includes methods and properties
4. An outputs document auto generated.

**Comment by hol353** [comment]
I have added a link to the grazplan technical doc on the APSIM Next Gen web site.
