### ISSUE TITLE
Validate Stock using the LUDF data in feedlot mode

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4386]
Use 'measured' intake to put known amounts and quality of forage in a feedlot. Validate against measured production and condition.

**Comment by hol353** [comment]
This is done. Closing issue as Stock is now under review by RP.

**Comment by zur003** [comment]
Reopening. The random number generator seed was not being applied properly, so validation runs are given (slightly) different results from run to run.
