### ISSUE TITLE
Stock - auto doc for the Component Description

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4391]
Left over from the 2018 sprint

Can we generated any useful auto documentation from Stock?

**Comment by sno036** [comment]
This will be useful for the Component Description

**Comment by hol353** [comment]
- If you right click on the top level 'Simulations' node in the tree and select 'Create documentation' you will get the usual auto-doc model / simulation description. 

- If you right click on a model e.g. stock and select 'Create Documentation' you will get a model description (list of outputs, links, methods).

**Comment by hol430** [comment]
> If you right click on a model e.g. stock and select 'Create Documentation' you will get a model description (list of outputs, links, methods).

I changed this a few weeks ago so that the create documentation context menu item only shows up if you right click on the simulations node (see #4349). Is that no longer the desired behaviour?

**Comment by hol353** [comment]
There is now a new type of generated document (2nd dot point above) that happens when user right clicks on a model.

**Comment by her123** [comment]
When I choose Stock I get the stock description followed by the Supplement component in the same doc. If I choose Supplement I get a supplement document containing stock at the end.

**Comment by hol353** [comment]
This will be because stock references supplement and vise versa. What happens is that any references to other types in the same namespace are also documented. That way we can have hyperlinks to the types.
