### ISSUE TITLE
Incorrect References in White Clover

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4412]
1) The White Clover model has a variablereference function that points to [Inflorescence].TargetAboveGroundFraction. This function does not exist.  
I did try changing this reference to use the same reference used in other places within the model but this badly affected the model statistics.
I have added a constant function at [Inflorescence].TargetAboveGroundFractionBrokenLink with a value of zero to reproduce current behaviour whilst avoiding a null reference exception arising from new checking code.
However, this is unlikely to be the desired functionality and so a model developer should look at this in the near future.

2) The White clover model also has a variablereference within Inflorescence that points to [TargetAboveGroundFraction].  As this function does not exist, this link is then resolving via scoping by using a value from another organ.

The White Clover model will need to be refitted once these errors have been fixed.

**Comment by par456** [comment]
[Inflorescence].TargetAboveGroundFraction no longer exists in WhiteCloser. Closing issue.
