### ISSUE TITLE
Change management rules to be more usable in rotations

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4416]
Management scripts in examples/toolboxes currently have lines such as
[Link] Plant Wheat;

If these are dropped into a rotation, scoping will just find the first plant.  We should explore options, such as:
[Link(ByName = true)] Plant Wheat;

So that the sowing, fertilise at sowing, etc rules work in combination with other crops.  
In some ways this should be designed properly, but at the very least, some basic changes now may assist in the short term.

**Comment by peter-devoil** [comment]
This is on the periphery of https://github.com/APSIMInitiative/ApsimX/pull/4060. The existing samples are so simple I'm loathe to add the complexity of a rotation manager to all of them - making a separate set designed to work in rotations seemed a far better option.

**Comment by hut104** [comment]
Agreed.  At the moment I’d just recommend small changes so that you can have more than one crop in a simulation (e.g. plant eucalyptus and an acacia understory – current planting scripts don’t allow you to sow two crops at once).
