### ISSUE TITLE
How to define a threshold for grazing (or cut) biomass in AgPasture?

### ISSUE THREAD

**Issue by monteiroleonardo** [APSIMInitiative/ApsimX#4427]
I would like to include in my AgPasture code a possibility to define a threshold for cut (or graze) the biomass when the total biomass produced achieve a given threshold. For example, when the cumulated biomass reach 4 tonnes per hectare, cut and leave a residual biomass of 1 ton per hectare (for example).

**Comment by monteiroleonardo** [comment]
I am asking this because I dont want to be considering a fixed interval for cuts but cuts when a given biomass (for example 5 tonnes) is cummulated, allowing also to have as output the number of harvests per yr.

**Comment by hol353** [comment]
@mpandreucci Can you answer this question?

**Comment by mpandreucci** [comment]
I[ve emailed Leonardo about it

**Comment by monteiroleonardo** [comment]
Thank you @mpandreucci,
Topic closed
