### ISSUE TITLE
Stock are eating more supplement than is actually provided

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4440]

**Comment by her123** [comment]
[LUDF_InputPasture.xlsx](https://github.com/APSIMInitiative/ApsimX/files/3903219/LUDF_InputPasture.xlsx)
[LUDF_Validate_Data.xlsx](https://github.com/APSIMInitiative/ApsimX/files/3903220/LUDF_Validate_Data.xlsx)
[LUDF_Observed.xlsx](https://github.com/APSIMInitiative/ApsimX/files/3903221/LUDF_Observed.xlsx)

**Comment by her123** [comment]
[LUDFStockWithSlurp_v0.apsimx.zip](https://github.com/APSIMInitiative/ApsimX/files/3903224/LUDFStockWithSlurp_v0.apsimx.zip)

**Comment by her123** [comment]
The supplement Feed() event is not doing the Feed first process correctly. It's feeding more than is provided during the AnimalGroup.CalculateRelIntake() function.

**Comment by sno036** [comment]
Throw an exception when the user selects "feed first". Fix it up later on.
