### ISSUE TITLE
Intellisense finds wrong component

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#4463]
The attached sample shows intellisense being asked about component M2, but returning information about M1
[x1.zip](https://github.com/APSIMInitiative/ApsimX/files/3909298/x1.zip)

![image](https://user-images.githubusercontent.com/1924386/69928237-c8bc6b80-1506-11ea-9951-ce0e292d3d5b.png)

**Comment by peter-devoil** [comment]
oops. not a bug. Just a thinko.

**Comment by peter-devoil** [comment]
Oops again. It is a bug. If there are two simulations, intellisense on the second simulation is showing  the components of the first simulation:
![image](https://user-images.githubusercontent.com/1924386/70002960-62d6ef00-15ad-11ea-9f67-9706cdc0dd27.png)

As well, within a simulation, the report component seems to get confused when there are multiple instances with the same variables. In this example, the value of M3.A should be 5, not 1. That's maybe a separate bug.
![image](https://user-images.githubusercontent.com/1924386/70003194-21930f00-15ae-11ea-8f89-6dc841c99637.png)

Sample: [x1.zip](https://github.com/APSIMInitiative/ApsimX/files/3913746/x1.zip)

**Comment by peter-devoil** [comment]
@hol430 - the second screenshot of the above example is showing the report module storing the wrong numbers in its DB. Should that be separate issue, or is it similar enough to remain in this one?

**Comment by hol430** [comment]
I'd say leave it in this one as they're pretty similar. I need to get back onto this one - the second issue is very strange.
