### ISSUE TITLE
How to run unit tests?

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#4479]
Any clues on how to run unit tests? I keep getting a message  "... Warning] No test is available in ...\UnitTests.csproj. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

I've checked the nuget manager and all seems in order.

**Comment by hol430** [comment]
On Linux or Windows? If you're on Windows, it's generally convenient to just run them through visual studio which allows you to debug the tests at the same time. On Linux you'll probably need to use the nunit3 console runner. Installation method will probably be dependent on your distribution but the syntax for using it will be something like this:

```
# run all tests:
nunit3-console /path/to/ApsimX/Bin/UnitTests.dll

# run a specific test (IrrigationWorks in this case):
nunit3-console /path/to/ApsimX/Bin/UnitTests.dll --test=UnitTests.IrrigationTests.IrrigationWorks
```

**Comment by peter-devoil** [comment]
Yes, I'm using VS2017.. When I open the test explorer, they're all displayed in grey. If I click "RUn All" it does a build of ApsimNG, and gives the informative message above..

**Comment by hol430** [comment]
Strange, I'm not sure if it's supposed to be looking in the .csproj file or the .dll file but either way ../UnitTests.dll seems like a strange path. Problem is I can't see a way to change where VS goes looking for the tests.

Are you able to run the tests from a terminal? The console runner should be installed in ApsimX/packages/NUnit.ConsoleRunner.3.xxx/tools/nunit3-console.exe so you could run it like this:

```
C:\ApsimX\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe C:\ApsimX\Bin\UnitTests.dll
```

**Comment by peter-devoil** [comment]
Yes, the console runner works, though it's rather slow. I'll persevere. ("..." was my longish source directory)

**Comment by peter-devoil** [comment]
On a related note, when the "Test" simulations are run (eg  Tests/Simulation/MultiZoneManagement/), how are the "tests" calculated for a pass/fail? In the bad old days we did byte/byte testing, but I cant see where the output of these simulations are compared against anything..
Ta

**Comment by hol430** [comment]
Ah, I didn't notice the third dot in your path there. As for pass/fail, if the test throws an exception then it fails. If the test doesn't throw then it's a pass. No need to parse output because Models.exe is referenced by UnitTests.dll so we can just create a job runner object and tell it to run a simulation. Or we can run Models.exe manually and make sure its exit code is 0.

**Comment by peter-devoil** [comment]
If you can think of a way to go about testing for the second bug in https://github.com/APSIMInitiative/ApsimX/issues/4463#issuecomment-560886247 I'd be grateful.. (also the first, which is a one line fix - but that might be harder!)

**Comment by peter-devoil** [comment]
@hol430 WRT above  I've made a unit test and will send a pull request as soon as I've fixed the bug!

**Comment by hol430** [comment]
Yeah that second one is nasty...somehow the manager script is changing during binary de/serialization. Haven't yet managed to figure out why...

**Comment by peter-devoil** [comment]
I'm going to have to pass this over - there's a PR in with a failing unit test. No doubt the conversation will continue [there](https://github.com/APSIMInitiative/ApsimX/pull/4486).
