### ISSUE TITLE
Stock intake needs to be updated for modern genetics

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4480]
Andrew identified this as the "Ci10" (?) parameter. Essential to be fixed.

**Comment by her123** [comment]
Testing by @sno036 is suggesting that dairy breeds may also be putting too much of their intake into body growth. This may need examination of the parameter.

**Comment by her123** [comment]
As commented by @sno036 in #4617:
I tested the dairy milk change that you made a while back ('before times'!) and it resulted in milk production falling off very quickly (like the cow was drying off) after calving.

There is a possibility that there was another parameter that should have been changed in the simulation or parameter file?

**Comment by sno036** [comment]
I think we've done as must as possible now so closing this off. Can always be reopened.
