### ISSUE TITLE
Problem with auto irrigation script?

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4492]
When calculating whether or not to irrigate, 'automatic irrigation based on water deficit' script doesn't seem to take into account any irrigation which has already been applied on a given day. Is this intentional or a bug? It's different to how old apsim works (not that that's necessarily a bad thing :)

**Comment by her123** [comment]
I had to rework the whole script to get it to work properly. It needed improving.

**Comment by hol430** [comment]
Is your improved version of the script included in one of the examples/test sets? Just wondering if it's worth replacing the old version in the management toolbox.

**Comment by her123** [comment]
I'm using it in a simulation that I'm writing at the moment.
