### ISSUE TITLE
Need to be able to alter PMF plant population during a simulation.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#450]
This is necessary to simulate the MouseControl wheat validation data set.

**Comment by HamishBrownPFR** [comment]
@hol353 @rcichota 
This is possible following the resolution of #953 

PlantMortality is a function that can be changed by the model its self.  each day this changes a property for Population which can also be set externally (and feeds the necessary changes to structure.cs) from a manager script
