### ISSUE TITLE
Multiple crops in one zone

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4517]
When I put two crops with cultivars in the same zone the sowing rule manager script will only see the cultivars for one of the crops.

**Comment by hol430** [comment]
The sowing rules need to be modified - I've added the ability to specify a plant name for the cultivar name drop down but haven't yet gone through and modified the existing sowing scripts.

If you need a quick fix, you can modify the sowing rule by specifying the PlantName property in the DisplayType attribute:

```csharp
[Description("Enter cultivar : ")]
[Display(Type = DisplayType.CultivarName, PlantName = "Wheat")]
public string Cultivar { get; set; }
```

Note that I only implemented this a few days ago so you'll need to be on latest master branch for this to work.

**Comment by sno036** [comment]
Thanks Drew

**Comment by hol430** [comment]
What action should be taken here? Do we want to keep the existing example files simple, or add in this (slightly more) advanced option to all of the sowing rules in the examples?

**Comment by hol353** [comment]
Update the examples so there is consistency.
