### ISSUE TITLE
Table property presenter is not updating cell changes

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#4518]
The table property presenter has a bug and after changing the value in edit mode, the changes are not reported to the grid unless you click off and back to the grid.

This table presenter is a bit sloppy as it was a copy of the PropertyPresenter that has since undergone significant improvements. 
The aim of the TablePropertyPresenter is to provide a series of columns for each object relating to the properties. This is used when you click on a parent component in CLEM that contains a list of children that the user may wish to display, edit or enter in a grid rather than individuals. I am not sure if anyone else would have use for this presenter.

**Comment by hol430** [comment]
Maybe it would be better in the long run to get the table property presenter to leverage the existing property presenter code. Maybe instantiate a property presenter for each object and somehow retrieve the DataTable created by the property presenter? Unsure how feasible this would be without trying it but we need to do something to eliminate this duplicated code.

**Comment by lie112** [comment]
Totally agree. I have tried to minimise repeated code. Probably need to implemented more protected properties and methods to allow better inheriting or build needed functionality for all. These presenters were not really implemented very well when written, but met the need.
I could probably combine them into one as most of the time others won't have need for the table style and will default to a single column of properties. Maybe when forced to rebuild grids for GTK3 or if I find some spare time. Just applied Frankenstein fix for now.
