### ISSUE TITLE
is .Value() still needed

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#4526]
@hol353 @hol430 @jbrider @hut104 
At one stage we had to put .Value() at the end of addresses when we wanted to return the value of a function.  It seems now functions return their value when the .Value() is not included at the end.  However, there are lots of places where .Value() remains in models and reports.  

It it is no longer needed it would be good to do a find and replace on the .json file to remove it and keep everything consistent

**Comment by hol430** [comment]
Yeah it's no longer needed in most contexts like Report or VariableReference and it would be good to remove any instances where it is provided unnecessarily. It may or may not still be needed in other places, such as an ExpressionFunction or as the x property of a linear interp function. Ideally, all of these different mechanisms for finding another model should work the same but that's not the case.

**Comment by HamishBrownPFR** [comment]
OK, this seems to tie in with #4423.  If we make a single consistent approach for getting variable references, for instance make Expression Function and Linint have variable reference children that get their variable reference, then it would be easy to tidy this up

**Comment by hol430** [comment]
Yeah that sounds like a good solution. Should be able to write a converter to do all of the heavy lifting.

**Comment by HamishBrownPFR** [comment]
I have just done a find and replace removing all .Value() from potato.json and it seems to work OK.  I am not sure there are any expression functions in potato.json but there are certianly linints that had .value in them.

**Comment by HamishBrownPFR** [comment]
OK, I could have a go at changing Linint and experssion functions to require a variable reference to get values.  This would not deal to the scoping issue in #4423 but would mean when that issue is dealt to it will only need to be done for the variable reference class

**Comment by hol430** [comment]
Well I guess the lininterp and expression functions don't necessarily have to have a variable reference as a child - do we want to allow any sort of IFunction?

**Comment by HamishBrownPFR** [comment]
Yeah, thats a good idea
