### ISSUE TITLE
Failing tests on clean build.

### ISSUE THREAD

**Issue by philderbeast** [APSIMInitiative/ApsimX#4545]
I have a clean install of visual studio 2019 on a clean install of windows 10. The solution built first time but there were failing unit tests. Some but not all of these seem to require sqlite. Should these tests be failing? Can we add a testing section to the contributing [guide](https://apsimnextgeneration.netlify.com/development/contribute/)?

<img width="434" alt="Screen Shot 2019-12-17 at 10 43 55 AM" src="https://user-images.githubusercontent.com/633283/70945625-78bed680-20ba-11ea-8edc-2e8613d1778a.png">

**Comment by hol430** [comment]
What errors are you getting? I think in visual studio 2017 (and maybe 19 too?) I had to change the default processor architecture under the test ribbon to get the unit tests to work:

![image](https://user-images.githubusercontent.com/36427516/70946454-ee1ead00-20a2-11ea-9d83-0df48fd0f787.png)

**Comment by philderbeast** [comment]
When I selected x64 instead of x86, all tests 243 tests ran successfully.

An example of a test failure with x86 is:

```
 TestCsvSwitch
   Source: CommandLineArgsTests.cs line 18
   Duration: 201 ms

  Message: 
    System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
  Stack Trace: 
    SQLite.sqlite3_open_v2(String filename, IntPtr& db, Int32 flags, String zVfs)
    SQLite.OpenDatabase(String path, Boolean readOnly) line 421
    DataStore.Open() line 206
    Simulations.SetFileNameInAllSimulations() line 170
    Simulations.Write(String FileName) line 143
    Utilities.GetRunnableSim() line 177
    CommandLineArgsTests.TestCsvSwitch() line 20
```

If x64 is required then should we ship a [`.runsettings`](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019) file with the tests?

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <RunConfiguration>
    <TargetPlatform>x86</TargetPlatform>
...
```

**Comment by hol430** [comment]
Makes sense. Will likely require minor changes to Jenkins since it looks like nunit-console.exe doesn't use the .runsettings file.
