### ISSUE TITLE
Equivalent of MWCON in ApsimX?

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#4550]
I think I've asked this on the Help and Support Forum but that has since disappeared.
Testing the effects of interventions that affect the maximum ponding depth, I found that the effect of ponding on soil conditions depended very much on the MWCON variable, which affects how quickly water infiltrates into the layer below when a soil layer is saturated. This was on Apsim 7.10. I am now trying to do the same sort of experiment on ApsimX but cannot find any soil property analogous to MWCON in the new interface. Is it possible to set this property?

**Comment by ver078** [comment]
@jal-frezie KS is the equivalent variable in ApsimX. Well sort of.

MWCON is the "above" saturation parameter in old Apsim which was used mostly on sandy soils over in Western Australia. It worked as a fraction of the water that was above saturation that got passed into the soil each day. They also created an equivalent called for the heavy clay soils of the Darling Downs here in Queensland which worked by specifying the number of mm per day that would go into the soil each day when above saturation. 

When ApsimX was created only KS was ported over as the feeling was that KS made the MWCON approach redundant.
