### ISSUE TITLE
SOBOL Example Improvement

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4565]
The current SOBOL example is incomplete and not consistant with the Morris example. It has no graphs to show results.
The SOBOL example should be changed to allow direct comparison between methods.

**Comment by hol430** [comment]
@hut104 it looks like the sobol example now generates ~11k simulations and takes about an hour to run on jenkins. We need to find some way to trim down the number of simulations.

**Comment by hut104** [comment]
I’ll reduce the execution time.  However, I might get you to help fix a bug in the  UI that makes it hard to alter the experimental design without doubling the size of the table!

**Comment by hol430** [comment]
@hut104 can this be closed?

**Comment by hol430** [comment]
I'll take that as a yes.
