### ISSUE TITLE
Running APSIMNG and APSIM7x series on different cores and upper limit of DB file

### ISSUE THREAD

**Issue by UKum540** [APSIMInitiative/ApsimX#4573]
Hi,
I am interested to run a large number simulations with APSIMNG and APSIM7.x on different cores. I would appreciate the suggestions/approach to do that.

I wonder, while thinking about running those simulations, if there is any upper limit of data storage in the Data Base File?
Thank you

**Comment by BenAbabaei** [comment]
Classic APSIM would take care of CPU cores. Regarding APSIM-NG, I always use my own sctipt to run the model on UQ Cluster, but maybe the developers have put some new facility to make it easirer. The size of the DB used to be an issue so I always needed to divide the simulations into smaller groups each being stored in one file. Again, that **might** not be a problem anymore.

**Comment by hol430** [comment]
Apsim will attempt to use all available CPU cores but there is a command-line option which will allow you to restrict apsim to a certain number of cores:

```
/path/to/Models.exe myfile.apsimx /NumberOfProcessors:32
```

**Comment by BenAbabaei** [comment]
@hol430 is this implemented in NextGen? I remember it was experimental or something.

**Comment by hol430** [comment]
Well as far as I know it's not *supposed* to be an experimental feature but you're right - I just tested it and it's definitely not doing what it's supposed to do. Will look into it.

**Comment by peter-devoil** [comment]
Another difference between old and new you may come across is the way NG writes output. In classic, each simulation (running in its own process) wrote its own files, in NG a single thread writes to the DB when asked by the simulation threads. This may not bother you for infrequent writes (eg harvest reports), but for lots of output (eg daily outputs of lots of things) you may spend time waiting to write. 
The solution is simple - just limit apsim to a smaller number of threads (after the above is fixed), and start multiple instances writing to separate DBs.

**Comment by UKum540** [comment]
I observed this issue of writing output in NG simulations. I ran one
simulation set up and when it was about to complete I ran another one
simultaneously. The first DB start accumulating the output of the second
simulation set up as well. The second simulation setup seems to be writing
DB okay. The first DB never stopped writing the output and it keep on
increasing so long the second set was running. I had to close both setups.
And now I am running only one set up at a time. That's why the I asked if
there is way to designate different simulation  setusp of NG (and APSIM7x)
to different cores. I have not tried the script posted by Drew to do that
yet. I will and update if it works.

There is another concern now that I would like to mention:
I observe now that even when I am running only one simulation setup and as
the size of DB file is increasing the APSIM interface is increasing the
physical memory consumption. Due to that the simulation process is getting
slower and slower. At the moment APSIM NG interface is using alomost all
the memory and compressing 98-99% of it. It's much much slower. I assume
this has to do something with writing the DB file again. Does anyone of you
have some thoughts about it? My simulation set up is with 108000 individual
simualations created by using the permutation option.
Thanks

**Comment by hol430** [comment]
@UKum540 how are you running your simulations? Via the GUI or command line? If via the GUI - are you clicking "run apsim (F5)" or "run apsim multi-process (f6)"? If via the command line - can you provide the command you're using? Also what sort of hardware are you using to run your simulations - laptop? workstation? hpc?

**Comment by peter-devoil** [comment]
Concurrent writes are always going to be a problem if you don't match the sink capacity (how fast you can write to the DB) against the number of sources. On the low end, Apsim's generally happy with less than ~16 simulations writing at once, but higher end hardware (> 40)  [has problems](https://github.com/APSIMInitiative/ApsimX/issues/647). The problem gets worse in HPC environments with 000's of simultaneous writers - in that case it's easier to restructure the problem and do the data aggregation as a separate processing task.  

You may find that sqlish data storage is not well suited to your problem - it's a relatively simple task to write an apsim manager component that writes data with libraries like Microsoft's [SDS](https://www.microsoft.com/en-us/research/project/scientific-dataset/) (still has the same concurrent write issues, but you can write per-simulation) - that you can subsequently manipulate with [other tools](http://nco.sourceforge.net/).

**Comment by UKum540** [comment]
@hol430 I am running bia GUI by clicking "run apsim (F5)" on a workstation with 32GB RAM with Intell Xeon E-2123 3.30GHz processer. 

@peter-devoil Could you send me the script to write this managment component. I am not very familiar to linking this to external libraries like the one that you suggested.  I will appreciate if you could exlain how to achieve that linking. 
Thanks!

**Comment by peter-devoil** [comment]
It was in Classic IIRC, and it shouldnt be hard to implement in NG provided we can sort out how to reference the assembly.  I'll have a look for it and add it to the "advanced" simulations.

**Comment by hol430** [comment]
Maybe it's worth writing an alternate datastore and/or job runner implementation which can work around this problem.
