### ISSUE TITLE
which weather factor can be used in the APSIM weather file

### ISSUE THREAD

**Issue by xiaozhhenu** [APSIMInitiative/ApsimX#4595]
When I used the APSIM, I noticed that only  'radn', 'maxt', 'mint' and 'rain' was used as the weather factor. so whether other climate factor such as ozone, aerosol can also be added to the met module? Or only 'radn', 'maxt', 'mint' and 'rain' can be used as weather factor.

In addiation, Could the APSIM be used to simulate the effect of climate change such as ozone and aerosol on crops?

Thanks in advance for any help!

**Comment by hol430** [comment]
@hut104?

**Comment by hut104** [comment]
In APSIM Next Generation, the weather component can use
Maximum Temperature (MaxT)
Minimum Temperature (MinT)
Radiation (Radn)
Rainfall (Rain)
Evaporation (Evap)
RainfallHours (RainHours)
Vapour Pressure (VP)
Wind (Wind)
Diffuse Light Fraction (DifFr)
Day Length (DayLength)
CO2 Concentration (CO2)
Some of those above are useful for controlled environment studies.

Impacts of Climate Change via CO2 are captured by the model.  Impacts by other aerosols would need to be captured via scripting through the manager if you can identify appropriate handles within the model (e.g. as used by some of the pest modelling for example).

**Comment by hol430** [comment]
Closing as answered. Feel free to reopen or open a new issue for more questions.
