### ISSUE TITLE
Soils downloaded in NextGen don't come with solute nodes

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#4602]
Can we please change this so that when the soil is downloaded, the solute nodes are already included in it?

**Comment by hol430** [comment]
@mpandreucci this seems to be working for me. I've downloaded a few soils and they all seem to contain some solutes. Can you post the settings you're using to download the soil (e.g. lat/long)?

![image](https://user-images.githubusercontent.com/36427516/72690976-557dc000-3b6d-11ea-8139-4be525d0616e.png)

**Comment by mpandreucci** [comment]
Hi Drew.
I tried to download a soil again and the solutes were included, so not sure how I did it.
I can't remember what I used to download the soil but I attached here the file with a simulation that has the soil file (it's unabled - SoilDalby) that came without the solutes. You can see that it has the nutrient node but not the solutes. Again, I can't remember how I downloaded, sorry. 
[CultivarsII.zip](https://github.com/APSIMInitiative/ApsimX/files/4083975/CultivarsII.zip)

![image](https://user-images.githubusercontent.com/43769255/72691188-5243fd80-3b88-11ea-8c69-b6bb48e8e8d4.png)

**Comment by mpandreucci** [comment]
It's quite weird that none of the options I tried now came without the solutes. I don't know what happened.

**Comment by hol353** [comment]
Can we put a test into APSIM that when a simulation is run, it shows an error message in these situations:

-  when a soil does not have a SoilWater child model. 
- when a soil does not have either a SoilNitrogen or a Nutrient model.
- when a SoilNitrogen or Nutrient don't have NO3, NH4, Urea, PlantAvailableNO3 and PlantAvailableNH4 solutes.

**Comment by hol430** [comment]
What about an error if the soil is missing a temperature node? That seems like a common cause of error as well.

**Comment by hol353** [comment]
Yep good idea.

**Comment by mpandreucci** [comment]
Doesn't APSIM already show an error when the temperature node is missing? I remember coming across that (yes, I do a lot of wrong thigs with apsim) a long time ago?

**Comment by jbrider** [comment]
What is the performance hit doing these checks every run?

**Comment by hol430** [comment]
@mpandreucci it does give an error if missing a soil temp node but the error is "Object reference not set to an instance of an object."

@jbrider performance hit should be negligible. I imagine the test will run once per simulation, and searches through the simulations tree are cached anyway.

**Comment by hol430** [comment]
- I notice that the soil has a WEIRDO property and an ISoilWater property, but WEIRDO implements ISoilWater. Why do we have two separate properties here? Is it valid for a soil to have a weirdo but no soil water?
- Should we throw an error if we don't find an Organic child? What about LayerStructure?

**Comment by hol353** [comment]
- Probably don't need 2 properties. WEIRDO is an alternative soil water so yes it is valid to have WEIRDO without a soil water.
- Yes we should throw an error if Organic is missing. LayerStructure is optional.
