### ISSUE TITLE
should csv file types be in the gitignore file?

### ISSUE THREAD

**Issue by ver078** [APSIMInitiative/ApsimX#4613]
Not sure why we are ignoring csv files from git? 
I asked Drew and he does not know either. 

Should this line be removed from the gitignore file? (Perhaps others should go also?)

Makes it hard to commit test datasets using graphical tools such as gitkraken. 
Have to use the command line instead.

**Comment by hol353** [comment]
Don't know either. Remove it from the .gitignore.
