### ISSUE TITLE
maize cultivar parameterisation

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/ApsimX#4615]
I would like to set up different genotypes using measurements of cobs (ears?)/plants, grains per cob and grain size, although I just found that APSIMX allows configuring only two parameters related to this: _MaximumPotentialGrainSize_ and _MaximumGrainsPerCob_. It is possible to parametrise cultivars using the observations (i.e. not maximums values) for each cultivar? I want to create new genotypes based on the thermal time from sowing to flowering and cobs/m2, grains/cob and grain size. It is possible?

**Comment by hol430** [comment]
@hut104?

**Comment by sarahcleary** [comment]
@hut104 - any answer?  or pass onto someone else?
@JJguri - still wish this to be answered?

**Comment by JJguri** [comment]
I just want to know if I can parameterize the model using the thermal time from sowing to flowering. If so, which would be the code to implement. I already found a way to parameterized _MaximumPotentialGrainSize_ and _MaximumGrainsPerCob_.

**Comment by hut104** [comment]
Yes, you can.
If you know the TT from sowing to flowering, you can back calculate the TT to flag leaf.  If you know this, you can calculate the final leaf number for that planting.  If you know the final leaf number, you can then back calculate the TT at which Floral Initiation had to occur.  Once you know that, you have a point on the Photoperiod response curve.    You then need to make sure your parameterised PP response goes through this point.  If it is a tropical cultivar (ie not much PP effect) then just make the PP response flat through this value.
The model should then flower on your observed date.

Hopefully this makes sense.

**Comment by JJguri** [comment]
it helps a lot, thanks.
