### ISSUE TITLE
Add output to MicoClimate

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#4628]
Can we please add % of radiation intercepted as an output of MicroClimate?

**Comment by hol353** [comment]
@mpandreucci MicroClimate has an output called RadiationInterception in MJ/m2/day. To convert this to a percent can't you do this in report:

[MicroClimate].RadiationInterception / [Weather].Radn * 100

**Comment by mpandreucci** [comment]
This is something Val asked me to put here to remind her that she wanted to have this as an output. I don't mind doing that in report.

**Comment by hol353** [comment]
Closing this as it can be done in report.
