### ISSUE TITLE
unable to create new cultivars in the maize model

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/ApsimX#4639]
I cannot create new cultivars in the maize model because it is not editable in the GUI, i.e. you can drop a cultivar folder into it and then a new cultivar in the cultivar folder. However, if you save the file and then re-open it you cannot see the new editions.  I tried this with my own simulation and the maize example and does not work. @hol430 @HamishBrownPFR 

Here is my simulation: https://www.dropbox.com/s/d3kaddb2kxcscpk/Trials.apsimx?dl=0

**Comment by hol430** [comment]
@hol353 @hut104 how do we want this to work? Should we be able to drop a cultivar onto a plant? This may be tricky to implement due to how the serialization works with the crop models.

**Comment by hol353** [comment]
Yes, we do want to be able to drop a cultivar onto a plant. Someone here at AgResearch tried to do that yesterday with wheat. It will need changes to ModelCollectionFromResource.cs to make it smarter wrt child models dropped by the user.
