### ISSUE TITLE
Need to update to .Net 4.7.2

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#4665]
This need relates to issue #4662 and the errors occurring in pull request #4663 
Can we have the reference assemblies for Framework 4.7.2 provided for Jenkins?
After discussions with @zur003 and @hol430 there should be no reason that APSIM next gen can't be using the latest of the 4.7 .Net release and coding principles.
I want to use private protected in one of my models base classes.

**Comment by lie112** [comment]
After more checking regading pull request #4663 
I need c# v7.2 which is in .Net 4.7.2

When I try to compile on Jenkins I get an error in Models.cproj stating that it is using c#7.0 which is .Net 4.6.2

CLEM\Resources\CLEMResourceTypeBase.cs(29,48): error CS8107: Feature 'private protected' is not available in C# 7.0. Please use language version 7.2 or greater. [C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Models.csproj]

Can someone please check what versions Jenkins is using?
I have updated the Target Framework for all APSIMx projects in the mentioned pull request.

This whole framework versus c# version has been doing my head in.
All projects are set to use the best available c# version based on framework..

**Comment by hol430** [comment]
I installed the .net 4.7.2 sdk on all of the Jenkins servers a few days ago so we should be all good on that side of things. I'm not sure why it's not compiling when set to use the latest C# version available, but if I change that setting to specifically target C# 7.2 then it works. Unsure why this is the case. Does the latest commit compile on your local machine?

**Comment by lie112** [comment]
I am not able to change the c# version number as it was disabled in VS2019 and set to Automatically selected based on framework version. Is the Properties/Build/Advanced the only place to access the language version?
My dev version compiles and runs fine. That's why I was a little surprised to see the build error in jenkins.

**Comment by zur003** [comment]
There is a explanation of C# compiler versions [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version). Is Jenkins using VS 2017 or 2019?

**Comment by hol430** [comment]
Ah, thanks the link Eric, I guess the key sentence there is 

>The C# compilers that are part of the Visual Studio 2017 installation or earlier .NET Core SDK versions target C# 7.0 by default.

The build servers have the standalone build tools which were most likely installed by the visual studio 2017 installer.

I can install the 2019 versions but do we want to maintain support for visual studio 2017? I remember we continued to support vs 2015 for quite a while after 2017 was released.

**Comment by lie112** [comment]
I like VS2019. Intellicode is great.
You could modify my pull code and set the language version to 7.2 as I can't change that setting. Then with 4.7.2 installed we should be right to compile and accept the pull request.

**Comment by lie112** [comment]
It seems VS 2015 will only let us go to c# 6.0. VS 2017 and 2019 will allow us to include up to 7.3 and 8.0
https://www.kunal-chowdhury.com/2018/02/visual-studio-change-language.html
Any chance Jenkins could get an upgrade to at least VS 2017?

**Comment by lie112** [comment]
Any news on an upgrade or fix here?
I have a heap of fixes awaiting this pull request and would like them incorporated for a big CLEM workshop next Tuesday.

**Comment by hol430** [comment]
The jenkins build servers should already be using the vs2017 build tools and have the .net 4.7.2 sdk installed. I think if we change the language version from latest to 7.2 then it should work (I hope). I don't know if this would work with vs2017 out of the box though - and I'm leery of breaking people's builds because as far as I've been told we still want to support vs2017.

Is private protected the only new feature you need? Because if so you could just use protected instead, right?

**Comment by lie112** [comment]
I have changed to protected and away from the private protected as intended
It seems I have broken things by changing the .Net framework to 4.7.2 (see #4663)
Is there a fix here, or do I need to change all the .Net frameworks back to 4.6 for all projects?

**Comment by hol430** [comment]
APSIMInitiative/APSIM.PerformanceTests#29 should fix the problem.
