### ISSUE TITLE
APSIM Sounds

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4674]
There seems to have been several changes to the APSIM sounds over recent months.  I am not sure 
about any previous discussions about these.  I apologise if I am going over old ground.

Can I suggest a few possible changes here?
1) We remove sounds.  For short simulations they are not really needed because of the visible queues given.  For long simulations (e.g. hours) it is unlikely that the user is waiting for such a sound.  In workshops, with dozens of people running APSIM the sounds can be a distraction. 
2) We allow users to turn sounds on/off.  We don't support an options menu, but we could start by simply having a switch in the config file.
3) We standardise on sounds, and persist with them.  I'd suggest that sounds are short and simple, with a theme (ie short bell/ding with high pitch for success and low pitch for failure).

I have previously run a training workshop overseas and found that the sound was changed to a Christmas song.  It was somewhat embarrassing and drew comment from trainees.

**Comment by her123** [comment]
Having different sounds for successful vs failed runs would be good.

**Comment by jbrider** [comment]
I support options 2 and 3.

**Comment by lie112** [comment]
I agree. Short sharp success (using standard system type sounds, that can be disabled, or only if simulation has taken more than 20 seconds) and double low tone fail sound. In a way only the fail sound is really needed as this alerts the user to the fact that something went wrong. The current sound seems to have a silent period of starting up you hear when wearing headphones.

**Comment by hol430** [comment]
#4677 implements idea no. 2 - you can disable the 'simulation complete' sounds from the config file. 

While poking around the config file I also came across the option to specify your own completion sound files for pass/failure. Is this sufficient to satisfy no. 3, or do we still want better defaults?

**Comment by hol430** [comment]
Another thought - and kind of unrelated - but I wonder if we should write some XML comments of property descriptions to the config file so that users can actually understand what some of these settings do.

**Comment by jbrider** [comment]
Sounds like a good idea.

**Comment by hol430** [comment]
What do we want to do about this issue? The user can choose their own sound via the config file which works well, but we could improve the default sounds. It is possible to use [system sounds](https://docs.microsoft.com/en-us/dotnet/api/system.media.systemsounds?view=dotnet-plat-ext-3.1) (we can choose from asterisk, beep, exclamation, hand, or question) but on windows, they all use the same sound by default, meaning most people would end up with the same sound for error vs success.

The other option would be to find/create our own sounds.

**Comment by hut104** [comment]
Perhaps we need to take this issue into our hands, and distribute a success and failure sound (bing vs bong).

________________________________

**Comment by hol430** [comment]
Current plan is to use system sounds, otherwise change default sounds to their old values.

**Comment by lie112** [comment]
Can I ask where the current successful completion sound came from?
Is it really from the start of the opening music to Battlestar Galactica? How nerdy of APSIM dev if so!!

**Comment by hol430** [comment]
Yep, I believe it's the teleporter from battlestar galactica(?)...I think it was @sno036's idea

**Comment by hol353** [comment]
Plan: remove the current sounds from APSIM but retain the ability for users to specify their own .wav files through the settings view.

**Comment by hol353** [comment]
To close this issue off. @ric394 Can you change the line in Configuration.cs to set the default for Muted to true i.e.

```c#
public bool Muted { get; set; } = true;
```

This will mean new users don't get sounds by default.
