### ISSUE TITLE
Reporter component doc needs more detail

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#4683]
The Reporter document needs to explain what happens when you use [0] for an array of structures. It appears to show all elements. This is not intuitive and inconsistent with Manager code.
https://apsimdev.apsim.info/ApsimX/Releases/2020.02.05.4370/Report.pdf

**Comment by hol353** [comment]
@her123 Do you have an example of what you mean? Indexing element zero in an array should throw an exception as arrays have one-based indexing in report.

**Comment by her123** [comment]
The only reference to array indexing seems to be inferred in the soil layer paragraphs. I think this needs to be more explicit. Especially since it is different to Manager scripts.
From memory I think when I referenced [0] it gave me the whole array. This is not documented.
