### ISSUE TITLE
Property descriptions in autodocs are truncated

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4685]
The property and model descriptions in the autodocs are being truncated:

![image](https://user-images.githubusercontent.com/36427516/73894232-8ed16200-48c7-11ea-8159-3ad405993149.png)

Is this intentional? The descriptions seem like one of the more useful pieces of info in the document.

**Comment by hol353** [comment]
Yes it is intentional so that it fits on a page.

**Comment by hol430** [comment]
Would it be worth including the full descriptions somewhere then? Maybe another document? As it stands, anyone who wants the full description will have to trawl through the source code.

**Comment by hol353** [comment]
Maybe we can get the descriptions to wrap instead of truncating them.
