### ISSUE TITLE
Wheat leaf bugs in controled environment

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#4700]
Two problems encountered when running APSIM against the Brooking and Jamieson 1999 data set.
1. Odcasionally (2 in 208 sims) the relative size of the final leaf was zero which caused problems
2. Occasionally (1 in 208 sims) sudden Pp reduction caused FLN to decline below the number of leaf cohorts initiated which left the leaf model in an endless loop unable to complete leaf appearance

**Comment by par456** [comment]
This was fixed by a later PR, closing.
