### ISSUE TITLE
Should 'working on' PRs be a release upgrade option for users?

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4706]
Currently only pull requests that are marked as 'resolves' will result in a new release made available to users. Should we also make pull requests marked as 'working on' be releases as well?

I notice that the installations are being built but they don't appear in the users upgrade box.

**Comment by jbrider** [comment]
Not sure I follow how that works...
Once the code is merged, wouldn't it become part of the installed version?
So you might not have an installer for that particular pull request, but
the next one that got built would include it, wouldn't it?

**Comment by hol430** [comment]
An installer gets created for every pull request. However, not all pull requests show up in the list of upgrades in the upgrade form - only those pull requests which close an issue appear in this list.

**Comment by jbrider** [comment]
going by the number of pull requests that are merged, this would then
become a long, frequently changing list?
Would that make it any more useful?
Is the list not being updated often enough, or just not listing specific
updates you think should appear on it?

I've never seen the upgrade form, so I have no issue with whatever changes
you want to make to it - just curious how it works.

**Comment by HamishBrownPFR** [comment]
I think it should stay as is.  Things should not be released until they are sufficiently well done that the issue they are associated with can be resolved.

**Comment by hol353** [comment]
Ok. I'll leave it as it is.
