### ISSUE TITLE
ExcelMultiInput not merging files

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#4713]
I have two excel files with observed data (worksheets named 'Observed') that I am trying to read in using the ExcelMultiInput object.  It will read in the data from the first file into and Observed table.  It sort of reads the 2nd file but does not merge in the simulation name so the data is not visiable in the UI and can't be matched with predicted values.

Interestingly, if I read one of the files in with the ExcelInput object, then change the file name on the ExcelInput object to the other file it will read it in and merge it properly with the data already in the Observed table.  That works but is painful.  

I can provide the two files I am working with to test this, just fire me an email

**Comment by hol430** [comment]
Hi Hamish - is your branch up-to-date? I fixed a bug very similar to this late last week or early this week. If you're up to date and it's still not working, can you send through your files?

**Comment by HamishBrownPFR** [comment]
Thanks Drew.  I lase updated on Monday.  I will do a pull and let you know how that works

**Comment by HamishBrownPFR** [comment]
Still not working.  I will email you the files

**Comment by HamishBrownPFR** [comment]
@hol430 .  I have pulled your changes.  It does not throw an error but is only reading in the first file in the list for Tests\Validation\Wheat\Wheat.apsimx.  Currently this validation only reads in one file.  However when #4726 is merged it will be [attempting] to read another 3 files as well.

**Comment by hol430** [comment]
Looks like there are a few problems here

- Spaces between the comma-separated filenames. This shouldn't be a problem - I will change the code so that it accepts this
- The excel input component is pointing to LincolnCE.xlsx, PalmerstonNorthCE.xlsx, and LaTrobeCE.xlsx, but the files actually seem to be called LincolnCE_Obs.xlsx, PalmerstonNorthCE_Obs.xlsx, and LaTrobeCE_Obs.xlsx. You'll need to either rename the files or change the filenames in the excel multi input component
- There seems to be some funny cells in the LaTrobeCE_Obs.xlsx file. E.g. F54, K54, maybe some others too, I haven't had a thorough look.

**Comment by HamishBrownPFR** [comment]
Thanks Drew.  I did fix the incorrect file pointers but it seems the change didn't stick.  I will look into the other things

**Comment by hol430** [comment]
@HamishBrownPFR this appears to be working for me now. I checked out your branch and pulled down the latest master branch, then refreshed the datastore. Inside the observed table I could see palmerston, latrobe and lincoln data which I'm guessing means it's working?

**Comment by HamishBrownPFR** [comment]
@hol430  it seems to be working better.  It does merge in all the excel files now for the Observed worksheet.  However, it does not seem to be reading in the MaxLeafSize spread sheet

**Comment by HamishBrownPFR** [comment]
@hol430 the error I was getting here (which also caused #4726 to fail) was caused by a space between worksheet names.  Can you make it so this list will cope with spaces between names in the list also.  Then we could probably close this one

**Comment by hol430** [comment]
I've already fixed it so that a space between filenames doesn't cause a problem (#4727), but I'd like to also make it so that if the target file doesn't exist it throws an error (it currently just silently fails).
