### ISSUE TITLE
Rearange the _Factors data table

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#4720]
Does anyone else use the _Factors table?
I use it to match SimulationName, ExperimentName and FolderName up to SimulationID in Apsim outputs we dealing with them outside of the UI.  This is necessary because other tables are only indexed with SimulationID.  
This is all OK.  The problem is with the lay out of factor identifiers (highlighted in yellow below) which are stacked up in columns and need to be unstacked by some messy process.  A more user friendly lay out would to have a colum called Factor1Name and a column Called Factor1Value, a colum called Factor2Name and a column Called Factor2Value and so on until there are enough columns to describe all the factors.  In this layout is then possible to join the factor names and levels back to their corresponding simulation names and use them for indexing.

I am currently doing this reorganizing externally but wonder it other people are having the same issue and if a rearrange would be generally usefull? 
![image](https://user-images.githubusercontent.com/7295858/74484616-c40c2e80-4f1d-11ea-8bd8-d220fc6f5769.png)

**Comment by jbrider** [comment]
I'm about to start using it @Hamish Brown <Hamish.Brown@plantandfood.co.nz>
It would be much easier if it was kept to a single row - it should even be
marginally faster performance wise?

**Comment by HamishBrownPFR** [comment]
@jbrider how do you use them when they are in single rows, I can't work out an effective workflow

**Comment by jbrider** [comment]
That's what you were after wasn't it?
The Factors in columns so a single simulation is represented by a single
row?
I haven't got to actually implementing it yet, so I could be
misunderstanding how it works?

**Comment by HamishBrownPFR** [comment]
I can work with it how it is but was just wondering if others were finding it awkward, if so a refactor might be justified.  If not I am still able to do the stuff I need.

**Comment by jbrider** [comment]
I'll be post processing, so building it like you are won't be a huge issue.
I would prefer it to be output into columns as you suggested though.

**Comment by hol430** [comment]
It makes sense to restructure it as you suggested - I'll look into it when I get the chance.

**Comment by HamishBrownPFR** [comment]
Might pay to ask around a bit more to see if there is anyone else has major post APSIM dependencies on the current structure of the _Factors table.

**Comment by HamishBrownPFR** [comment]
@sno036 @hol353 @hut104 can you think of anyone is is building major post simulation analyses that are dependend on the current structure of the _Factors table.  I have suggested a restructure of it but don't want to muck other people up

**Comment by zur003** [comment]
Maybe I don't fully understand what's needed, but it sounds like poor database design to keep adding name and value columns. Wouldn't the standard approach be to create and use a factor ID, and add a second table which maps that factor ID to a name and value?

**Comment by jbrider** [comment]
@Eric Zurcher <Eric.Zurcher@csiro.au> That's effectively what we have now -
and yes, that is the more correct database design.

When dealing with the individual simulations in post processing, it would
just be simpler if the factors table was output as 1 simulation per row -
with extra columns for each factor.

**Comment by hol353** [comment]
I'd be ok with a restructured _Factors table.

**Comment by hol430** [comment]
After thinking about it some more, I'm not so sure that the current implementation is the wrong way. In Eric's hypothetical scheme, how would we represent an experiment with 3 factors, each of which has 2 levels? Would each SimulationID have 3 FactorIDs? Or does a single FactorID describe values for each of the 3 factors?

**Comment by jbrider** [comment]
Yes, each SimulationID would have 3 Factor ID's - which is effectively what
it's doing now.
The current method is the technically correct one, it just requires some
collation when post processing.

The proposed change would just make it a bit easier to use.

**Comment by HamishBrownPFR** [comment]
It is easy enough to chop it up into different shapes post simulation.  Unless we can agree there is a fundamentally better approach the best thing is to do nothing.

**Comment by zur003** [comment]
The way I was thinking about it, an experiment with 3 factors, 2 levels each, would have 6 factor IDs (so I guess they could be factorLevelIds, not factorIds).

**Comment by hut104** [comment]
Just a quick note to remind people that apsim week is just around the corner.
Apsim needs to remain stable.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zur003** [comment]
Apsim needs to REMAIN stable???

**Comment by hut104** [comment]
Yes.  I hear what you are saying, but I’ve been noticing that key elements that we wish to demonstrate have been broken over recent weeks.

**Comment by HamishBrownPFR** [comment]
I don't think the _Factors table is used internally in APSIM for anything so won't affect stability.  I also don't think this is a short term priority but opened the issue to catch the thought.

**Comment by jbrider** [comment]
It's gotten more attention than any other issue has in the last 12 months
:)

**Comment by hol430** [comment]
Closing this after discussion with @HamishBrownPFR.
