### ISSUE TITLE
_Factors table reorders factorNames 

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#4723]
I tend to order factors in decending order of importance (importance being my opining at the time) with the most important factor at the top.  However when apsim creates the FactorName column it put things in a random order .  See image below, order in simulation is Treat, Cv, Durat in APSIM but puts them in alphabetical order in _Factors.  Is it possible to maintain the order they appear in the tree? 
![image](https://user-images.githubusercontent.com/7295858/74617021-f3c26d00-518f-11ea-91cb-9a0694eac5f8.png) 

This problem would be over come it the multiple factor levels were not recorded in the same column as identified in #4720

**Comment by hol430** [comment]
Closing after discussion with @HamishBrownPFR.
