### ISSUE TITLE
Choice between SoilWat and SWIM when conduct sensitivity analysis on APSIM

### ISSUE THREAD

**Issue by ShiruiH** [APSIMInitiative/ApsimX#4741]
I propose to conduct sensitivity analysis on APSIM Next Generation. But not quite sure which soil water model should be chosen.
1. From what I've reviewed, seems most researchers have used SoilWat to simulate their crops, which makes SoilWat has more audiences and attentions. A sensivity analysis based on SoilWat might of greater interest to researchers and users.
2. However, SWIM is based on Richard's equation, which makes it a more "sophisticated" model. And I'm also willing to explore the sensivity embedded it.
So, I guess this is a good opportunity to hear some advices or opinions from the model deveplopers and other users. Do you have any suggestions on which soil water modules to be tested?

Many thanks,
Shirui

**Comment by BenAbabaei** [comment]
Hi @ShiruiH . We have recently finished and submitted a paper on calibration, and sensitivyt and uncertainty analysis on APSIM-wheat (APSIM classic). The codes I prepared in R can be used for APSIM,  APSIM-NextGen and AquaCrop and uses SUFI-2 algorithm which has been widely used for model calibration in hydrology. Would be happy to help. Cheers.

**Comment by ShiruiH** [comment]
Hi, @BenAbabaei. Wish you luck on the submitted paper! Aappreciate your offer on help. I'm planning to use FAST or Sobol to do the sensitivity analysis.

**Comment by hol353** [comment]
Also note that SWIM is not yet released in APSIM Next Generation.
