### ISSUE TITLE
Pasture growth

### ISSUE THREAD

**Issue by 20091108wl** [APSIMInitiative/ApsimX#4748]
I am writing to ask which module to use for modelling pasture growth in APSIM classic version. I have tried AusfarmPasture and Agpasture. Followed are the problems I have when running APSIM.
1.AusfarmPasture, in User Interface/Standard/crops/AusfarmPasture, I found a lot of variety species like perennial ryegrass and Lucerne, but I can't find a file naming 'AusfarmPasture.xml'.I have simulated winter wheat before and I see I can establish my own variety and change the related parameters in 'Apsim79-r4044\Model\wheat.xml'. However for Ausfarmpasture I can't find it.
2.I have tried Agpasture module, and I found some problems.  I copied my own simulation from the example (Agpasture), however, the resultsshowed the pasture would not die during winter where the the average temepature is about -15℃ during winter seasons. I have read the Agpature.xml file and only found parameters describing cold temperature effect on photosynthesis. Without parameters controlling death rate under extreme low temeprature, the above-biomass remained quite high (about 500-1000 kg/ha) during winter while it should be all dead in reality. Also, the pasture stopped growth during summer season, and grow slowly during autumn in China (I am confused which parameter I should change, I under stand the growth pattern of Australia which located Southern Hemisphere， while China is in Northern Hemisphere ).
Thanks for your help. 
@sarahcleary

**Comment by mpandreucci** [comment]
Hi.
I'm currently trying to improve AgPasture in NextGen and once I get it done I can help you. We can even have a go at dealing with your simulation in NextGen, if you don't mind.
I'll get back to you.
Mariana

**Comment by hol353** [comment]
@APSIMInitiative/livestock-and-forages

**Comment by 20091108wl** [comment]
> Hi.
> I'm currently trying to improve AgPasture in NextGen and once I get it done I can help you. We can even have a go at dealing with your simulation in NextGen, if you don't mind.
> I'll get back to you.
> Mariana

Thanks Mariana. Looking farward to your improvment.

**Comment by smghajar** [comment]
Hello all,

Sorry to bump an old thread but I'm having the same issues with dormancy in AusFarm. When I try using AgPasture, I'm getting growth curves for perennial rye/clover mix that would be more typical of warm-season species when I use met files and soils from the United States. Has anyone found a fix for this?

**Comment by sarahcleary** [comment]
@her123 / @mpandreucci - are you able to help?

**Comment by mpandreucci** [comment]
Hi @sarahcleary. I had a chat to Dean about this and I wish I had the time to look into this right now.
It would be good if @smghajar could copy his simulation here so that we can have a look at it. Is this possible @smghajar?

**Comment by 20091108wl** [comment]
I can provide my simulation in China. I had the same problem before where the above biomass was very high during winter using Agpasture with average temperature of -20 oC.发自我的iPhone------------------ Original ------------------From: mpandreucci  <notifications@github.com>Date: Fri,Aug 14,2020 6:02 AMTo: APSIMInitiative/ApsimX <ApsimX@noreply.github.com>Cc: 20091108wl <wulu_agrimeteo@cau.edu.cn>, Author <author@noreply.github.com>Subject: Re: [APSIMInitiative/ApsimX] Pasture growth (#4748)
Hi @sarahcleary. I had a chat to Dean about this and I wish I had the time to look into this right now.
It would be good if @smghajar could copy his simulation here so that we can have a look at it. Is this possible @smghajar?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/APSIMInitiative/ApsimX/issues/4748#issuecomment-673732410",
"url": "https://github.com/APSIMInitiative/ApsimX/issues/4748#issuecomment-673732410",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mpandreucci** [comment]
@20091108wl that would be great. If you and @smghajar send the simulations, we can have a look at them.
Thanks for that

**Comment by 20091108wl** [comment]
Attached are my simulation files. The simulated biomass was very high during winter， although daily temperature was very low.

-----原始邮件-----
发件人:mpandreucci <notifications@github.com>
发送时间:2020-08-14 09:39:30 (星期五)
收件人: APSIMInitiative/ApsimX <ApsimX@noreply.github.com>
抄送: 20091108wl <wulu_agrimeteo@cau.edu.cn>, Mention <mention@noreply.github.com>
主题: Re: [APSIMInitiative/ApsimX] Pasture growth (#4748)






@20091108wl that would be great. If you and @smghajar send the simulations, we can have a look at them.
Thanks for that

**Comment by smghajar** [comment]
Thank you for the replies! One example simulation is attached. The pasture is highly productive in winter, and even more so in fall. What we would expect is winter dormancy followed by an immense spike in growth in spring, summer dormancy, then a milder spike in fall. I'm attaching a graph of the ten year average dry matter by day of the year. I have tinkered with temperature lag settings but thus far cannot seem to resolve the mismatch of real vs simulated pasture yield curves. The link to the example simulation is below. The met file is from Iowa, as are the soils. No grazing or fertilization is factored into the simulation, as I'm trying to simulate an unmanaged fallow pasture. 

[https://drive.google.com/file/d/1LNv0k1tLqOjmz0ox72PPMo7NeNSC3fhe/view?usp=sharing
![Seasonal growth and dormancy issue](https://user-images.githubusercontent.com/69594962/90266721-67cd8d00-de22-11ea-8847-7e0bc3353cc2.png)
](url)

**Comment by mpandreucci** [comment]
Sorry @20091108wl and @smghajar. Could you two please zip up your apsim files and attach them here? 
I didn't get any attachement in any of the replies. 
Thanks a lot

**Comment by smghajar** [comment]
I'm not sure how to zip files, so here is mine in a Google Drive link:

[https://drive.google.com/file/d/1LNv0k1tLqOjmz0ox72PPMo7NeNSC3fhe/view?usp=sharing](https://drive.google.com/file/d/1LNv0k1tLqOjmz0ox72PPMo7NeNSC3fhe/view?usp=sharing)

**Comment by mpandreucci** [comment]
Hi @smghajar
The simulation you sent me is currently done in APSIM Classic. I tried making a simulation similar to yours in APSIM NG (you will need APSIM NG running).
I could have got a few wrongs, but in NG the growth rate is quite low. The above ground mass doesn't go over the residual threshold and for that reason, there isn't any grazing happening.
Have a look at the simulation attached here. You will see there are two simulations in this file. The first called 'TemperateGrassEstablished' is what was exported from Classic to NG. The other simulation called 'Iowa' is the one that runs without error messages (because the necessary adaptations to NG were done). You will that there isn't AusFarm in this one, because it's not in NG yet. So, I used AgPasture and set up the grazing threshold in SimpleGrazing.
Have a go at using this simulation and see how you get on. Please let me know how you go.
Thanks
[Iowa.zip](https://github.com/APSIMInitiative/ApsimX/files/5093547/Iowa.zip)

**Comment by mpandreucci** [comment]
@20091108wl let me know if you want to send me your simulation and have a go setting it up in NG.

**Comment by 20091108wl** [comment]
It's so weird that I have sent you my simulations on last Friday and yesterday(notifications@github.com, ApsimX@noreply.github.com), but you didn't get my simulations.

I tried to attach it again here, please tell me if you have got my attachment.




Kind Regards,

Lu wu



-----原始邮件-----
发件人:mpandreucci <notifications@github.com>
发送时间:2020-08-19 09:38:43 (星期三)
收件人: APSIMInitiative/ApsimX <ApsimX@noreply.github.com>
抄送: 20091108wl <wulu_agrimeteo@cau.edu.cn>, Mention <mention@noreply.github.com>
主题: Re: [APSIMInitiative/ApsimX] Pasture growth (#4748)






@20091108wl let me know if you want to send me your simulation and have a go setting it up in NG.

**Comment by mpandreucci** [comment]
Hello @20091108wl  nothing came attached to it.
Can you please try to zip your simulation in a folder and then just drag the zipped folder into the comment box?

**Comment by hol430** [comment]
Hi @20091108wl it looks like you're replying to the email in your mailbox. To upload a file, you need to post the message on github rather than responding via email. You can do this by clicking the "view on github" link at the bottom of the email.

**Comment by 20091108wl** [comment]
[agpasture.zip](https://github.com/APSIMInitiative/ApsimX/files/5093741/agpasture.zip)
This is the simulation I use is uploaded here. Thanks for your effort.

**Comment by mpandreucci** [comment]
Thanks for that @20091108wl 
Is there a specific type of pasture you're trying to simulate, like ryegrass or tall fescue?

**Comment by mpandreucci** [comment]
Hi @20091108wl 
I set up your simulation in NG with Ryegrass. The first simulation ('agpasturePaddock') is the one that was imported from Classic. The second one ('China') is the one I set up in NG, following what you had set up in Classic. You will see that grazing is done by SimpleGrazing.
You can see that when the temperature falls below 0 degrees, not much happens.
Please have a look at it and let me know how you go. I'm happy to help if needed.
You will need APSIM NG running.
Kind regards
[China_Henan.zip](https://github.com/APSIMInitiative/ApsimX/files/5093811/China_Henan.zip)

**Comment by 20091108wl** [comment]
Hi @

> Hi @20091108wl
> I set up your simulation in NG with Ryegrass. The first simulation ('agpasturePaddock') is the one that was imported from Classic. The second one ('China') is the one I set up in NG, following what you had set up in Classic. You will see that grazing is done by SimpleGrazing.
> You can see that when the temperature falls below 0 degrees, not much happens.
> Please have a look at it and let me know how you go. I'm happy to help if needed.
> You will need APSIM NG running.
> Kind regards
> [China_Henan.zip](https://github.com/APSIMInitiative/ApsimX/files/5093811/China_Henan.zip)

Hi mpandreucci ,
Thanks for your help. I don't have next generation version in my laptop. So I run it again with classific version and shortened the simulation period to make the dis-match more clear. The dismatch is that the grass didn't die (biomass keep constant at about 3000kg/ha) during winter with extreme low  temperature(-20 — -30℃）, while biomass started to decrease when temperature started to increase (See figures in black square). 
![abovebiomass](https://user-images.githubusercontent.com/61308566/90595170-c7f77100-e21e-11ea-9411-6df537098cdf.JPG)

**Comment by mpandreucci** [comment]
Hi @20091108wl 
I understand that. Most of our fixes are being done for APSIM NG, so maybe it would be good to consider working in NG.
AgPasture has recovery parameters for when cold stress happens. That's pretty much what allows it to have any production after the temperature drops. It would be good to compare it with observed data to see what is needed. 
Sorry, it maybe wasn't much help.

**Comment by 20091108wl** [comment]
Hi @mpandreucci ,
Thanks for your help. I will try APSIM NG.

**Comment by mpandreucci** [comment]
@20091108wl let me know how you go. Good luck
