### ISSUE TITLE
Operations manager not keeping text that was typed or pasted

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#4771]
The operations component is not keeping text that is typed or pasted. So when I paste (or type) something in there, if I click somewhere else or save the simulation, everything disappears from the operations component. Not sure what is going on?

**Comment by hol430** [comment]
@mpandreucci I'm unable to reproduce this one. Note that the operations node will only save your operations if they're syntactically valid - they need to have a date, then a space, then the operation. If I type `2020-03-02 [Fertiliser].Apply(50, Fertiliser.Types.NO3N, 13)` then it works.

Do you remember what you were typing?

**Comment by mpandreucci** [comment]
Hi Drew.
1966-01-15 [Irrigation].Apply(amount:100);
this is what I was pasting in there. It's weird because it was working before. It's just when I paste (or type something in there) that this was happening. I'll try again now and see if this is still happening.

**Comment by mpandreucci** [comment]
Drew, this is not happening anymore. Not sure what was going on, maybe APSIM just had enough of it yesterday. 
Thanks for trying to help
