### ISSUE TITLE
PMF can't do multi-paddock/multi-crop simulations

### ISSUE THREAD

**Issue by josharp22** [APSIMInitiative/ApsimX#48]
The PMF needs some code to deal with multi-crop and multi-zone simulations please :-)

**Comment by hol353** [comment]
Jo, is this the same as your issue #68? If so can you close this one?

**Comment by josharp22** [comment]
No, it's not. #48 relates to PMF coding (Hamish will add more detail to this bug). #68 is to get a multi-paddock simulation example. Thanks.

**Comment by HamishBrownPFR** [comment]
There are two separate issues here.  
- firstly ApsimX throws an error if you try to sow a 2nd PMF model in a paddock so PMF models can't be used to do mixed crop simulations.  See the memo in Tests\SoilArbitrator\SoilArbitrator V2.apsimx in the folder PMFTest_NotWorking_SeeMemo for more info and a simulation that is ready to test this once it is done.
- Secondly PMF water and nitrogen supply properties that interface with the soilArbitrator don't contain code to deal with multiple zones in a simulation.  See image below.  Root.cs throws an exception (highlighted) when there is more than one zone in a simulation.

![image](https://cloud.githubusercontent.com/assets/7295858/7426354/718dc9b2-f017-11e4-8578-45196f468155.png)

In simple tree it is able to do multi zone simulations and has some code in the get uptake methods to enable this

![image](https://cloud.githubusercontent.com/assets/7295858/7426487/8bf8e040-f01a-11e4-89cc-81cc7f3fe7a8.png)
