### ISSUE TITLE
Question: How to reach Plant organs in a manager?

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#4807]
I have this manager script. How can I read/set the values of a plant organ's function, e.g. Wheat.Grain.DMDemandFunction?

```
        [Link] Clock Clock;
        [Link] Plant Wheat;

        public double PotDemand = 0;
        public double DemandLoss = 0;
        public double GWImpact = 0;

        [EventSubscribe("DoManagement")]
        private void OnSowing(object sender, EventArgs e)
        {
			DemandLoss = 0;
			PotDemand = 0;
			GWImpact = 0;
        }

        [EventSubscribe("DoManagement")]
        private void OnDoManagement(object sender, EventArgs e)
        {
        	DemandLoss = DemandLoss + Wheat.Grain.DMDemandFunction * Wheat.Grain.DMDemandFunction.HeatImpact.DailyLoss;
        	PotDemand = PotDemand + Wheat.Grain.DMDemandFunction  + DemandLoss;
        }
```

`'Models.PMF.Plant' does not contain a definition for 'Grain' and no extension method 'Grain' accepting a first argument of type 'Models.PMF.Plant' could be found (are you missing a using directive or an assembly reference?). Line number: 33`

**Comment by hol430** [comment]
In general, you can't set the value of a function. (Most) Functions calculate and return a value, they don't store data. In terms of accessing them from a manager script, you could try link by path:

```csharp
[Link(Type = LinkType.Path, Path = "[Grain].DMDemandFunction")]
private IFunction dmDemandFunction = null;
```

**Comment by BenAbabaei** [comment]
At this stage I just need to get the value. I will try this one. Thanks.

**Comment by BenAbabaei** [comment]
How can I fix this?

`The type or namespace name 'IFunction' could not be found (are you missing a using directive or an assembly reference?). Line number: 23`

**Comment by hol430** [comment]
`using Models.Functions;`
