### ISSUE TITLE
Display CLEM relationships as graph in HTML view 

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#4843]
Hi,
I want to display a quick visualisation of a relationship the user has defined in CLEM in my Summary tab (HTMLView). For this I chose a simple Chart.js (https://www.chartjs.org/) implementation which works well. This is an open source javascript library. This will also assist in data analysis visualisation in CLEM which is tending towards providing HTML output.

Q: Can I use Chart.js in APSIM next generation?
Q: If so, where is the best place to store the .js file so it doesn't require online access?

Working example 
![image](https://user-images.githubusercontent.com/19215637/75933933-bca7c780-5ec2-11ea-97f9-54332da4e0ac.png)

**Comment by hol353** [comment]
I don't want another dependency that we have to get working and maintain on Linux and MacOS. Why not use the chart control we already use?

**Comment by zur003** [comment]
I don't see any technical reason why this wouldn't work. The embedded web browser should have no problem rendering this. (I will note, however, that one of the stumbling blocks I've encountered in trying to go to ApsimNG under .Net Core is that it's not easy to embed a web browser on Windows. Webkitgtk works fine on Linux, but not Windows, where its Javascript implementation is broken.) Presumably Chart.js could be embedded as a resource.
Dean is right, though, in wanting to keep the number of dependencies to a minimum. Do the charts really need to be embedded in HTML?

**Comment by lie112** [comment]
This isn't an installation, but a simple .js file library (I just add a script src tag to my html). It should be compatible with all browsers so avoids the system compatibility problem and other than the html generated by CLEM doesn't affect APSIM, that's why I saw it as a safe option.
I have never got my head around the Charting in APSIM (along with a huge number of other aspects I hope to learn about at symposium) other than to use the graph tools provided. I want to be able to embed the graph in with other information as HTML and don't necessarily want to include additional graph components.
I am able to get the graph drawn in one method with limited lines of code.

**Comment by hol353** [comment]
I guess if it is a simple commit of a file then go for it. Put it into one of the CLEM directories.
