### ISSUE TITLE
Implement a more lightweight installer

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4891]
A version of the installer which doesn't require admin rights would be useful for people who do not have root access to their machines.

**Comment by zur003** [comment]
On which platform?

**Comment by hol430** [comment]
Windows was the platform I had in mind. Linux users ought to be able to crack open the .deb file if need be (or compile the source), and I don't really know much about macos or how our mac installer works.

I'm not sure if iscc.exe can generate an installer which will run without admin permissions. Certainly it would require some changes to our .iss file to prevent it from adding those registry entries. Maybe it's easier to just provide a self-extracting archive of a jenkins build.

**Comment by zur003** [comment]
Users would still need admin privileges to install anything into Program Files.
Innosetup is pretty flexible. You can indicate the level of privileges the user requires, and could probably write registry entries only if the user is suitably privileged. The registry stuff was a hack anyway - I don't know whether we still really need it.

**Comment by hol430** [comment]
I thought that removing the registry hack would break the map component on windows due to the htmlview using an older version of the browser widget. However, after testing this, I get javascript errors which break the map view even when the hack is present. Any ideas why this might be the case?

**Comment by zur003** [comment]
@hol430 - I have no idea. The embedded browser widget versioning stuff was needed when we were using Google maps, but now we are using Leaflet, which isn't as fussy.

**Comment by hol430** [comment]
Ah, ok - I will look into it on my end then. Cheers

**Comment by zur003** [comment]
@hol430 - What version of Innosetup are we currently using on the build machine? Version 6.0.0 introduced changes that improve handling of administrative vs. non-administrative installs. The newest version (6.0.4, which just came out) has an in-built function to detect whether a given version of .Net is installed, so we could simplify our install script a bit if we made use of it.

**Comment by hol430** [comment]
5.6.1 was previously installed. I just upgraded to 6.0.4, so we should now have access to these new capabilities.

**Comment by zur003** [comment]
If everyone is happy with the revised installer, this issue can be closed. I didn't want to flag the pull request with "resolves" until people have had a chance to look at it.

**Comment by hol430** [comment]
Looks like there was an error on jenkins when building the windows installer:

```
Error on line 17 in C:\Jenkins\workspace\CreateInstallation\ApsimX\Setup\apsimx.iss: Unrecognized [Setup] section directive "PrivilegesRequiredOverridesAllowed"
```

**Comment by zur003** [comment]
That would indicate that it's still trying to use an earlier version of Inno Setup. The changes require the newest version (6.0.4).

**Comment by zur003** [comment]
@hol430 - Perhaps the Jenkins scripting needs to be modified? Inno Setup 5 installed (by default) into "program files (x86)\Inno Setup 5", version 6 installed into "program files (x86)\Inno Setup 6", so maybe the path needs to be updated?

**Comment by hol430** [comment]
Yep, we're using chocolatey to install most of these dependencies. I did a `choco upgrade` yesterday which supposedly installed v6.0.4 of this package. I've just gone and uninstalled/reinstalled this package and although it claims to have installed v6.0.4 of the package, it's actually installed InnoSetup v6.0.4 **and** v5.6.1 for some reason. It's then created some sort of windows symlink to the 5.6.1 binary which it's placed on path, which is why we're seeing the error.

I've gone and manually removed v5.6.1 and calling iscc now gives this output:

```
C:\Users\Dean Holzworth>iscc /?
Inno Setup 6 Command-Line Compiler
Copyright (C) 1997-2020 Jordan Russell. All rights reserved.
Portions Copyright (C) 2000-2020 Martijn Laan. All rights reserved.
Portions Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.
...
```

So I think we're good.

**Comment by hol430** [comment]
The most recent CreateInstallation job succeeded, so I guess this is working once more.

**Comment by zur003** [comment]
Reopening this, as it appears that Updates are not working correctly.

**Comment by zur003** [comment]
Reopening again, rather than starting a new issue, but I need a bit of advice. The installer is not currently doing a proper job of adding Apsim to the start menu. I can fix this, but should Apsim go into the top level of the start menu, or into a folder within the menu? If into a folder, are there any other bits that should accompany it (e.g., link to home page or shortcut to documentation)?

**Comment by hol430** [comment]
Would it be possible to add an option to have no desktop icon created?

**Comment by zur003** [comment]
That's there now. 

It used to be that you were offered a choice between installing an icon for all users, or just yourself, but no option for having no icon at all. I've changed that so now it's a checkbox for having a desktop icon or not. If you're running as administrator, it gives the icon to all users.

**Comment by hol430** [comment]
@zur003 - do you know if it's possible to get the uninstaller to run without admin privileges when run from the add or remove programs dialog?

**Comment by zur003** [comment]
@hol430 - I don't know. I may depend on where the program was installed. You can't modify (including delete) anything in the Program Files folders without admin privileges, I think.

**Comment by hol353** [comment]
I would have thought that if the user had the privileges to install APSIM then the uninstaller should have the necessary privileges to uninstall APSIM.

**Comment by hol430** [comment]
In my case, I installed apsim without admin privileges into the default location (somewhere in AppData I think). I can run the uninstaller manually without any problems, and it doesn't require admin privileges. However if I try to run it via 'add or remove programs' then it asks for admin privileges. This may be a windows issue, I'm not really sure.

**Comment by peter-devoil** [comment]
@yashvirchauhan - this seems like the problem you described where the installation disappears after the UI exits. Can you keep an eye on this and test (on QGovt rollout) pls.

**Comment by yashvirchauhan** [comment]
Hi Peter
The problem got resolved. The upgrade button started working fine. As this issue maybe experienced by others in the Queensland Government this could help others also. To start with one has to save the software in the 'Temp' folder on the compuater hard drive and launch it from there using  developer's credential. Also install it for every one to use it rather than for yourself. If you do it for yourself it does not get loaded into Program folder and hence creates issue with creation of desktop icons etc. To activate upgrade, one has to open the program using developer's credential. This will then work perfectly. Thanks Peter and Drew for responding to address this issue.

**Comment by hol430** [comment]
Hi @yashvirchauhan,

- Why do you have to save the installer in the temp folder? What happens if you try and run it from the downloads folder?
- If you install it just for yourself, you shouldn't need admin privileges, but you also won't be able to install it into program files. I don't see this as much of a problem - the start menu entry and desktop icons should still appear (assuming you enable those options when installing apsim). Is this not working for you?
- If you install just for yourself. upgrading shouldn't require admin privileges. Otherweise, if you installed in program files, you will need to provide admin privileges each time you upgrade.

**Comment by yashvirchauhan** [comment]
HI Drew
Tried other options you mentioned, but nothing else seems to work. 

I cannot install the ApsimNG for myself at all without using admin privileges.With admin privileges and installing for myself the desktop icon can not be seen and can not be launched from start menu. It does not show in the APPs list and can not be uninstalled using control panels uninstall option. Upgrade is also prevented. 
The upgrade button does not work unless the program is opened as 'run as administrator' mode and it has been saved in the temp folder - do not know the reason. Our IT guys advised so.
The solutions we worked out might appear unusual, but for now to save time and gain required functionalities, will have to implement them.

**Comment by lie112** [comment]
Did we come up with a non-admin install and upgrade process?
Will installing to c:\APSIMNextGen or something similar work?
I have certain CLEM users that should not ever be given admin rights applying for them so they can install and use APSIM Next Generation. I would have suggested getting IT support to do the install, but if they require admin rights for every upgrade this isn't really a suitable outcome.

**Comment by hol430** [comment]
Yes, the windows installer will work without admin rights. It will install to %LOCALAPPDATA% (ie C:\Users\username\AppData\Local). Upgrades will also work without admin access.

The catch is that if you had admin access when you installed apsim (ie you installed to program files), you will need admin access to uninstall or upgrade that particular installation of apsim.
