### ISSUE TITLE
Adding 'Cultivars' to 'Replaqcements' instead of the whole plant model?

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#4896]
It would be handy to be able to add 'Cultivars' (or any child of any model) to 'Replacements' instead of the whole plant model (or any model). We usualy just need to keep/update the list of cultivars that we used in simulations. Unless there is already a way to do this.

**Comment by hol430** [comment]
You should already be able to add any model to replacements. Is this not working for you?

**Comment by BenAbabaei** [comment]
What I suggested was the ability to add, for example, 'Grain' to the 'Replacements' instead of 'Wheat'.

**Comment by hol430** [comment]
This should still be possible:

![image](https://user-images.githubusercontent.com/36427516/76817473-a4cf2c80-684e-11ea-8e38-1111a9f92bbf.png)

**Comment by BenAbabaei** [comment]
OK. I only tried 'Cultivars' and didn't work. Maybe models work.

**Comment by hol430** [comment]
How did you try to add the cultivars? You should be able to drag them from somewhere else (e.g. from wheat). Or you can right-click on the replacements node, click "add model" and choose cultivar from the list of models.

**Comment by BenAbabaei** [comment]
I just what you did with Grains.

**Comment by hol430** [comment]
Are you on latest code? I made some changes last week which will affect this.

**Comment by hol430** [comment]
@BenAbabaei is this still broken for you? If so, could you let me know exactly how you tried to add the cultivar? The following works for me:

1. Right click on replacements
2. Click add model
3. Double click cultivar in the right hand view

**Comment by BenAbabaei** [comment]
This is what I did:

- Added **Cultivar** folder to the **Replacements** and removed all but one, named **Janz**.
- Then I inputtd a wrong value for a parameter.
- Then I ran the mode, and it worked!
- I still have access to the complete list of cultivars, which means the interface still reds the **Wheat** model completely from the **Resources** folder.

![image](https://user-images.githubusercontent.com/39573622/77864589-d55e8f80-726c-11ea-8d22-2b9d71468223.png)

**Comment by hol430** [comment]
Ah ok, thanks Ben. There's an issue there alright.
