### ISSUE TITLE
`locator.Get()` could throw if it returns null

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#4911]
This would be consistent with recent changes to reporting/soil checking, and would allow for error-free fetching of variables with a value of null.

**Comment by lie112** [comment]
I’m away from my computer. It’s an easy fix. Throw error if IVariable is null and if not return the .Value regardless of whether it’s null instead of error if value was null. As mentioned other areas check for null and report will act as it did with new error if invalid parameter string.
