### ISSUE TITLE
Naming of Lifecycle and LifeStage

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#4920]
@hol353  @sno036 Keen to generate some discussion around the best name the pest/disease model?  I find Lifecycle is contrived as the plant models also model lifecycles.  Suggest a name describing the group of organisms the model represents could be better.  Biotic Antagonist, Pest and Disease.  Perhaps an acronym is needed.  BAD (Bug and Disease).

Also the name life stage is not really correct because a stage is a point in time, the Life stage objects are actually representing phases (the period of time between two stages).  We have tidied this terminology up in the plant model and it would be good to do the same in this framework.

**Comment by zur003** [comment]
The LifeCycle and LifeStage names come from the Dymex modelling framework, and emulate components within that framework. They are in no way restricted to emulating pests and diseases, Retaining the old names has obvious advantages to anyone porting Dymex simulations into Apsim.

Personally, I regard the terms "stage" and "phase" as being pretty much synonymous, and don't generally regard a "stage" as being a point in time

**Comment by HamishBrownPFR** [comment]
Thanks @zur003.  I understand they can be used to emulate any lifecycle but they are no longer restricted to emulating lifecycles, we are putting plant damage functionality in there too so the term lifecycle no longer captures the complete functionality of the model.

The distinction between phase and stage is pretty hazy.  In PMF we have adopted the definition of a phase being a period of time between two stages.  It makes it easier to explain things to people if we are clear on these difinition.  Was thinking it would be good to keep consistency within APSIM components but the lifecycle model has no notion of stages, just phases (or vise versa) so it is perhaps not so important.

**Comment by HamishBrownPFR** [comment]
Another semantic one.  How well embedded is the term growth.  From a plant perspective the change in physiological age (which is what the growth function does) is defined as development.  Growth is a change in mass.  What sort of resistance would I meet if I suggested changing this?

**Comment by jwhish** [comment]
Eric has given a good summary of the history and why we have what we have. I agree that the plant model also models life cycles, but at this stage does not consider different cohorts which the lifecycle model does. Following the dymex history when building a population model, you would first describe the specific organism’s lifecycle by identifying each stage. Then describe how to move between stages and the mortality associated with each stage. 


If describing a phase and the process to move between phases was more consistent across apsim then that change makes sense.  

Lifecycle is a different issue, the term lifecycle describes the information that is held within and what is required, to create a population model of the specific organism. You could call it BAD or population model, but you would then require documentation describing that you put the lifecycle of the specific organism within this container to model the population.

**Comment by her123** [comment]
Good summary @jwhish . I would go with phase also if required.

**Comment by HamishBrownPFR** [comment]
Thanks, good discussion guys
