### ISSUE TITLE
XYPairs graphs blank

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4925]
- Open Example\Lifecycle.apsimx
- Click on Tutorial_1_1_PseudoAphid_AgeBasedDevt.Field.LifeCycle.Juvenile.MaturingProcess.TransferToAdult.XYPairs

All XYPairs seem to be blank.

**Comment by hol430** [comment]
Seems to work for me. Note that I don't have Examples\Lifecycle.apsimx - I have Examples\Tutorials\Lifecycle.apsimx

![image](https://user-images.githubusercontent.com/36427516/76815100-68003700-6848-11ea-919f-18a2f7ff36d5.png)

**Comment by hol430** [comment]
@hol353 did you change the xypairs values at all before you observed this bug?

**Comment by hol353** [comment]
OK. The graphs seem to be working now. Don't know what was happening last week. Perhaps I wasn't on a clean branch. Closing...
