### ISSUE TITLE
Annoying null reference exceptions are being raised in WaterBalance when models are loaded

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#4940]
When you're debugging, you'll find that when an .apsimx model is loaded, several NullReferenceExceptions are thrown.  More specifically, this occurs when the WaterTable, SW, and Eo properties within WaterBalance are being copied (I think they are trying to use Links that haven't yet been resolved). The calling CopyPropertiesFrom function quietly catches and discards these exceptions, so they don't affect execution, but they're a nuisance when you're debugging and a break occurs with each exception.

**Comment by hol430** [comment]
This should be #4930

**Comment by zur003** [comment]
Looks good now. Nice to have the fix in the mill before the bug is reported!
