### ISSUE TITLE
Met file 'splitter' / 'resampler' thingo

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4949]
Purpose is to allow random resampling of whole years of weather data from a met file.

**Parameters / inputs**
- read in a met file
- parameter setting the 'start' of the year as dd-mmm-yyyy (e.g. "01-jun-3000") where the dd-mmm part sets the start of all sampling years and the full dd-mmm-yyyy sets the start date of the simulation (end date is the start plus the number of years listed below)
- read in either:
 a list of years in order to sample (e.g. "1997,2014,2000"); or 
the number of years required and "random"; or
the number of years required and "pseudo-random" and a seed value
- ? an add-on to the existing met file?
- needs to be able to be used as a factor in an experiment

**What it does**
- sets the (fake) start date of the simulation (here 01-jun-3000) along with the weather data to be used with the "sampling_date" (here the first one would be 01-jun-1997 for example) being outputable
- leap years - ignores 29-feb in the sampling data and pads an extra final day in the year if needed (want the same weather regardless of the simulation year - hope that makes sense!)
- in the example above, by the time the simulation gets to 31-may-3001, sampling_date is 31-may-1998. Then on simulation date 01-jun-3001 the sampling_date is  01-jun-2014. Equivalent behaviour for randomly generated weather years.

@mpandreucci  - any comments?
@hol353 - make sense?

**Comment by mpandreucci** [comment]
I think that's really good. We will know better if we need anything else apart from that once we get this going. It doesn't look like much more will be needed.

**Comment by zur003** [comment]
How do you see this being used? It's easier for me to think about these things with a use case in mind.

Would a "year" always be a calendar year from 1 January to 31 December, or could the bounds be altered to, say, 1 April to 31 March?

Leap days will be a headache. Where would the values for a padding day come from?

**Comment by mpandreucci** [comment]
The bounds will need be able to be altered. That's the only way to make it useful to more people.

**Comment by sno036** [comment]
@zur003  - the use case for our immediate use is surrounding using legacy experimental data for validation when there are some really good features about the data (for us, duration of each trial and the spread of the many trials across NZ) but the experiments were so long ago that we don't have daily weather data available. 

If we assume that the weather has not changed at the location then we can sample 'current' (post 1972 which is when we first have reliable daily weather) for an appropriate duration (10 years, 20 years, depends on the duration of the original trial) and rather than compare using a time series, compare using annual mean and variation. Ideally we would sample our current weather with many start dates, but if we want each sample to be independent then there can be no overlap. With ~48 years total, for longer-running trials we can only get two samples which is not really enough. Ten years is a more common duration and even then we can only get four samples. So we want to investigate randomly resampling whole years (just pick a biophysically-sensible start/end to your year) to create more samples. 

Another approach would be to use a weather generator. I've used one before and it was sort of OK but I'm not all that keen on them - although it would be an interesting addition to this work maybe.

**Comment by sno036** [comment]
Leap years are a pain but they are only one day. Two options if sampling to create a leap year. Just make the weather on the 28th the same as was on the 29th. Or just keep on going and use one day into the next year so that your created 29-feb is taken from 01-mar in the weather file and everything post 28th is off by one day. I think I prefer this second option as it avoids the potential issue when there is a mass of rainfall on the 28th.

**Comment by mpandreucci** [comment]
How does the weather generator work?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sno036** [comment]
It was ages ago but I think we used https://support.goldsim.com/hc/en-us/articles/115012797188-WGEN-Weather-Simulator
