### ISSUE TITLE
Problem with the sintax of the mean in the seasonal report of AgPasture

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#4951]
Hi @hol430. 
The sintax of the mean in the seasonal report in the AgPasture validation simulation doesn't seem to be working. Could you please have a look at it?
Thanks
![AgPastureMean](https://user-images.githubusercontent.com/43769255/77497692-ccf40680-6eb2-11ea-8276-bfe724689c83.PNG)

**Comment by BenAbabaei** [comment]
Are you sure you can apply **mean** on another expression?

**Comment by hol430** [comment]
Hi Mariana - I had a look in ApsimX/Tests/Validation/AgPasture/AgPasture.apsimx but can't find this variable in any of the reports. In fact, the seasonal report doesn't even have a reporting frequency specified which means that it will never report anything.

**Comment by hol353** [comment]
@hol430 Can you syntax highlight 'mean', 'on' and 'stddev' keywords in report.

**Comment by BenAbabaei** [comment]
@hol430 **prod** is also a keyword.

**Comment by hol430** [comment]
In what context? Report? I can't see any references to a "prod" keyword in the expression parser (although there is a "multiply" keyword). Although now that you mention it there are a bunch of other keywords (percentilexx, median, etc) which should have syntax highlighting.

**Comment by hol430** [comment]
Sorry for the double comment - I found prod in VariableGroup.cs (of course, why didn't I think of looking there earlier...). Will add syntax highlighting here as well.

**Comment by BenAbabaei** [comment]
I added a 'product' agregator 1-2 weeks ago (https://github.com/APSIMInitiative/ApsimX/issues/4790). I am not sure if it does the same as **multiply**
