### ISSUE TITLE
Add ProportionOfTotalDM output to SimpleGrazing

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#4960]
This is a convenience output and makes reporting simpler.

Instead of:

mean of ([AGPWhiteClover].AboveGroundWt / ([AGPWhiteClover].AboveGroundWt + [AGPRyegrass].AboveGroundWt + 1.0)) from [Clock].StartOfSimulation to [Clock].EndOfSimulation as PropCloverHarvested

you can do:

mean of [SimpleGrazing].ProportionOfTotalDM[2] from [Clock].StartOfSimulation to [Clock].EndOfSimulation as PropCloverHarvested

Note: ProportionOfTotalDM is an array - one value for each species. In the example above *[SimpleGrazing].ProportionOfTotalDM[2]* is the second value in the array. The order of species in the simulation tree in the GUI has clover as the second species so this variable returns the clover proportion. 

**Order of species in the tree is important**

**Comment by hol430** [comment]
Does this actually make the intent clearer? Yes it's shorter but instead of seeing the word AGPWhiteClover and knowing that this is about AGPWhiteClover, you see the index 2 (if you look closely) and think "now which species is at index 2" and "does array indexing start at 1 or 0"?

**Comment by hol353** [comment]
Yes, I don't really like the array indexing either but we don't have the ability to create properties 'on the fly' e.g. SimpleGrazing.ProportionClover and SimpleGrazing.ProportionRyegrass depending on which pasture species are in the simulation. 

I think having the array variable is still better than a really long expression in REPORT.
