### ISSUE TITLE
Lifecycle enhancements

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#4977]
Lifecycle needs to be able to:

1.  reproduce into parallel lifecycle (As in a population reproducing resistant and non-resistant ofspring
2. migrate into parallel lifecycle (As in individules from on population moving to another)
3. Vector transmission (As in individules moving from one population (in vector) to anohter population (in host) as a result of vector activity)

**Comment by hol353** [comment]
@APSIMInitiative/pest-and-diseases : fyi
