### ISSUE TITLE
LAI property should not be presented in the GUI for GRange

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#4985]
I just noticed that the LAI (leaf area index) property is being displayed by the generic property presenter for GRange, although setting the value will have no effect on the model. That's apparently because it's a settable property (as it needs to be to implement ICanopy), and has a Description attribute associated with it.

I can readily fix the immediate problem, but it got me wondering about the criteria for adding properties to the property presenter. It this case, the Description attribute was intended for output labelling, and the property was "settable" because that was required to implement a specific Interface, but there was no intent to actually allow the user to be able to set the value. Should I be using a different set of attribute tags? And do we have this documented anywhere?

**Comment by hol430** [comment]
I think the intent here is that use of the description attribute indicates that a property should be settable from the UI, and that output labelling should be based on the summary tag. This is briefly mentioned on [this page](https://apsimnextgeneration.netlify.com/usage/writemanagerscript/). 

Perhaps to make this clearer, the description attribute should be renamed (to InputAttribute?) and its description in the code should be updated. And it should not be applicable to classes.

I'm also not sure why the description attribute has a line number property.
