### ISSUE TITLE
Error in Job Runner

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4994]
We get intermittent problems with the job runner calculating the %complete when the list changes.  This happens regularly in large multicore PCs.  I'm now getting it on my 4 core machine running large simulation groups (e.g. the wheat validation with 1400 sims).

                if (jobRunner != null)
                {
                    // Should this have a lock? If so, on what?
                    foreach (IRunnable runningSim in jobRunner.SimsRunning)
                    {
                        Simulation sim = (runningSim as SimulationDescription)?.SimulationToRun;
                        nComplete += sim?.FractionComplete ?? 0;
                    }
                }

**Comment by zur003** [comment]
What is the nature of the problem?

**Comment by hut104** [comment]
SimsRunning changes as you iterate through it.
