### ISSUE TITLE
Report presenter slow to load

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5016]
If you have a large DB file with daily data, and then click the daily report file in the ui, it can take a long time to load.  That is understandable, you have lots of data.
However, does it need to load all that data  at that point.
If you only want to edit the reporting variables and not look at the data in the DB file, could it just load the presenter for the reporting variables, and then only read all the data when you click on the tab with the data?

**Comment by hol430** [comment]
I'm re-opening this as it has been suggested that we load the report table by default, but with limited data.

**Comment by lie112** [comment]
Relates to #5530

**Comment by hol430** [comment]
Closing as fixed by the new sheet widget.
