### ISSUE TITLE
Chart lines joining results

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#5024]
When displaying experiment results, the chart sometimes draws a line back to 0 - as if it has joined 2 series together.
I don't think it happens if using Date (using DaysAfterSowing in that attached file).
In the attached file it displays 1 phenology chart different to the next one.

Changing the marker type from None to something - sometimes fixes it - with large markers being displayed - changing the size of the marker does not change the size of those markers.

![image](https://user-images.githubusercontent.com/635772/78749510-be791500-79b1-11ea-91d3-30abb022c14f.png)
![image](https://user-images.githubusercontent.com/635772/78749735-30e9f500-79b2-11ea-8900-80e377cd099b.png)

[chartTest.zip](https://github.com/APSIMInitiative/ApsimX/files/4448497/chartTest.zip)

**Comment by hol353** [comment]
It always means that you have a multi factor experiment but you are only using one 'Vary By' option in your series. Use another 'Vary By' e.g. Vary By colour and line type.

**Comment by hol430** [comment]
As @hol353 says, I'm not sure that the line going back to 0 is necessarily a bug. If you don't want markers on your lines, you can set either line type or colour to 'vary by simulation name', and then set the other option to vary by crop and you should end up with something a bit more readable, although there are still a lot of lines. 

The marker size thing is definitely a bug though.

**Comment by jbrider** [comment]
So basically, underneath it is grouping simulations in a multifactor and
treats them as a single series - splitting them apart when you specify a
Vary By.
I can see how that works - but it has a downside when drawing lines.
This can be closed.
