### ISSUE TITLE
Several inconsistencies between documentation and model parameters in terms of photoperiod effect

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#5041]
Short days are usually defined as 8-hour long days in the documentation while that is not the case in the wheat model parametrisation. For example, for head emergence it is 11 hours and for final leaf number it is 10 hours.

**Comment by BenAbabaei** [comment]
@hol430 I wouldn't label this as 'science'. It is more about wheat documentation.

**Comment by hol430** [comment]
Yeah, feel free to add whatever labels you want/

**Comment by BenAbabaei** [comment]
I think labelling is beyong my pay grade ;)
