### ISSUE TITLE
Root horizonral expantion at each depth is calculated with a wrong equation

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#5050]
In **Root.cs**, there is a function to calculate root area at each depth. If a triangular shape is assumed for root expansion, the expression that calculates root horizontal expansion is wrong, as:

Tan(RootAngle) = xDist / Depth = RootSpread / RootFront

![image](https://user-images.githubusercontent.com/39573622/79524711-8f932b00-80a4-11ea-82aa-1b558a02b11c.png)

**Comment by BenAbabaei** [comment]
@jbrider, as only sorgum currently uses this option, would you mind having a look and comment?

BTW, I get no yield with Wheat when I set **RootAreaCalcType** equal to 1. Is wheat not supposed to work with this?

**Comment by jbrider** [comment]
@BenAbabaei It's for Sorghum and C4Maize specifically - from the Classic code base.
It is calculating a semi-circle - not a triangle.

**Comment by BenAbabaei** [comment]
Thanks @jbrider . The reason I thought I might have been transgular was this line:
**zone.RootSpread = zone.RootFront * Math.Tan(DegToRad(RootAngle));**

Is there any change we can make to make it usable for wheat (as we are interested in working on RootAngle)?

**Comment by jbrider** [comment]
Your commit about the Null exception didn't make sense to me - you changed it from an == to a >= which is half fixing a floating point comparison issue.  How does it fix a null exception?

**Comment by BenAbabaei** [comment]
It is silly actually! It is written as >= in other parts of the code, which measn anything >=1 should work, except in this part.

**Comment by jbrider** [comment]
The switch to use the semicircle calculation is contained in RootFrontCalcSwitch - did you set that to 1?
RootAreaCalcType is there for C4Maize as it calculates the area slightly differently to sorghum.

**Comment by BenAbabaei** [comment]
Yes, I added **RootFrontCalcSwitch** to the model and set it to be 1. But I don't get any yield for wheat. I am trying to understand why.
