### ISSUE TITLE
Years per day

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#5065]
Rather than the current years/day value in I think all models, which is a non-leap year value (1/365), wouldn't it be better to specify it more precisely as: 0.00273785 (=1/365.25) to account for leap years on average. So currently there is an error of 0.068493% per year, or about 3.4% for 50 years. This is not important for short term crop simulations of one or a few years, but for oil palm and forest plantation etc. it is adding an error that we could otherwise avoid.

**Comment by zur003** [comment]
Actually, as a pedant I think it should be 1/365.2422 rather than 1/365.25 - Gregorian calendar, not Julian.

**Comment by hol430** [comment]
@sme016 is there a specific calculation which you want adjusted?

**Comment by sme016** [comment]
Sorry, we proably don't need to implement it across all released models now, as the validations will change slightly demanding some small recalibration, perhaps. Instead, I think it best that Eric's suggestion of the valeu be kept in mind during any model revalidation, model review or new model develpoment . . . . but we just have to remember to do that. 

Thanks,
Philip

**Comment by hol353** [comment]
Closing this for now. If there is something specific you want changed then reopen and tell us.
