### ISSUE TITLE
Implementing a skip-row configuration

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#5068]
If there is not, can we implement something like this?

![image](https://user-images.githubusercontent.com/39573622/79818824-09405700-83cc-11ea-9395-f6ddc4c69212.png)

**Comment by jbrider** [comment]
SowingData has a property called SkipRow
It's used in RootZoneState - starting at line 172

It is used in a couple of other places as well.

**Comment by BenAbabaei** [comment]
Thanks Jason. I am working on that. Cheers
