### ISSUE TITLE
Maize long term

### ISSUE THREAD

**Issue by guillemodon** [APSIMInitiative/ApsimX#5096]
Hi, I'm new to APSIM Next, I'm trying to model a long-term simulation of continuous corn, but it seems to restart every year, so no mineralization occurs ... anyone who knows? Thank you

**Comment by hol430** [comment]
@hut104 are you able to answer this one

**Comment by BenAbabaei** [comment]
@guillemodon It alwasy helps if you upload the APSIM file or at least a screenshot of what is inside it. If you have a node named like "Reset on sowing" or "Reset on date" right click on it and uncheck "Enabled". See if this helps.

**Comment by guillemodon** [comment]
Hi Ben, thanks for answering. I removed that node directly ... Attached screenshot 
![Apsim](https://user-images.githubusercontent.com/64509279/80703838-e55ece80-8ab9-11ea-9459-901abec0dd5a.JPG)

**Comment by BenAbabaei** [comment]
So, did it help?

**Comment by guillemodon** [comment]
I didn't get any different result ... if you want I can send you the simulation

**Comment by BenAbabaei** [comment]
How do you say it resets every year? What do you see in the outputs?

**Comment by guillemodon** [comment]
The simulated yields are very very low, when I check the mineralization of the N it tells me that there is no, I do not have N mineralized in any layer ... so I assume that in some way it is not simulating continuously

**Comment by BenAbabaei** [comment]
Can you please share screenshots of any node related to N or organic matter?

**Comment by guillemodon** [comment]
![Captura](https://user-images.githubusercontent.com/64509279/80707364-37a2ee00-8ac0-11ea-81e2-e1612c06108c.JPG)
![N](https://user-images.githubusercontent.com/64509279/80707366-38d41b00-8ac0-11ea-92e8-db2617e27f20.JPG)

**Comment by BenAbabaei** [comment]
Nutrient is relatively new. Don't have much experience with it. Can you tell me what's the WaterFractionForMineralisation? Does soil reach that fraction?

**Comment by guillemodon** [comment]
Where should I find that value .... I'm looking for it ... sorry my inexperience.

**Comment by BenAbabaei** [comment]
At the end of the objects under Nutrient.

**Comment by guillemodon** [comment]
![nn](https://user-images.githubusercontent.com/64509279/80709513-c7966700-8ac3-11ea-865e-ea375543905e.JPG)

**Comment by hut104** [comment]
From what I see of that simulation you are not adding any fertiliser.  If that was intended, I'd suggest you check your soil organic matter levels if intrinsic productivity is too low.
