### ISSUE TITLE
Pond handling seems to have changed

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#5098]
My management script that previously set MaxPond in SoilWater and read current pond worked OK in older versions, now I get errors:
Type `Models.Interfaces.ISoilWater' does not contain a definition for `pond' and no extension method `pond' of type `Models.Interfaces.ISoilWater' could be found. Are you missing an assembly reference?. Line number: 85
Type `Models.Interfaces.ISoilWater' does not contain a definition for `SetMaxPond' and no extension method `SetMaxPond' of type `Models.Interfaces.ISoilWater' could be found. Are you missing an assembly reference?. Line number: 102
Also if I save a model from the latest Git version I cannot open it with the latest pre-built download (5091)

**Comment by BenAbabaei** [comment]
Hi @jal-frezie. Just as for the last part of the question, you can open the file with an older version by removing the objects that GUI cannot find (as they have been added in a newer version) and lowering the version of the file (with a text editor).

**Comment by hol430** [comment]
It looks like the ponding variables were removed from the `ISoilWater` interface as part of the recent refactoring of the soil water model. @hol353 do you remember what happened to these variables?

As for the second problem - the latest released version can lag behind the latest git version by a few hours. If you now upgrade your installed version you should be good.

**Comment by hol353** [comment]
The ponding variables were removed because they weren't being used anywhere in Next Gen. One of these days we need to think about how we are going to do ponding.

**Comment by sarahcleary** [comment]
@hol353 - should this be closed?

**Comment by hol353** [comment]
This can be closed. At some point we'll create a new issue to build a new ponding capability.
