### ISSUE TITLE
Does summary table in db get cleared at the start of a simulation?

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5107]
I have noticed that old errors displayed in the summary report (lower pane) remain even after further runs. It seems that summary table must be cleared at a time after some of the CLEM validation (at the start of Do Commence) occurs such that the summary isn't cleared when the exceptions are thrown. A manual empty datastore resolves the problem. Could we get the summary table cleared at the start of the simulation? I can't see that this should cause anyone any problems as the info should only be from the previous simulation run.

**Comment by hol430** [comment]
By summary table, do you mean the data shown in the summary model?

If you have multiple simulations in your file and only run one simulation, you probably will only want to clear the data from that one particular simulation, rather than dropping the entire table. I thought this was already happening somehow - otherwise all of the stuff in the summary file would show up more than once.

**Comment by hol430** [comment]
@lie112 can you upload an .apsimx file which shows the problem?

**Comment by lie112** [comment]
I am referring to the information displayed in red in the bottom pane that presents the errors in a simulation. I can't repeat the problem at present as I have addressed all errors. If I get a object not set null error or the like, even after I have fixed the problem the error persists in the bottom until I empty the datastore and run again. Then additional errors and warning produced by CLEM are displayed. It's like my validation errors occur before the summary errors are cleared. CLEM validation happened in CLEMValidate after DoInitialSummary and StartOfSimulation on DoCommence in the Clock.

My users are often trying to fix old errors that is the first still displayed at the bottom of the screen when the actual error is thrown by invalid parameters and displayed lower in the list. 

I'll see if I can repeat the problem, but most errors are now trapped. I was unable to full understand what was happening.

Note: Another issues I can raise is that the red error text in dark theme doesn't show up very well and maybe should be pink (light red) or yellow.

**Comment by hol430** [comment]
Ah, ok. Yeah the text in the bottom pane is not tied to the datastore and is not permanent/persistent at all. As soon as something else writes a message to the bottom panel, the error will be overwritten and will be permanently gone. That being said, the error should also be written to the summary file, so if you're looking for errors which occurred in a simulation, that's the place to look.

![image](https://user-images.githubusercontent.com/36427516/82009250-31ad2f80-96b2-11ea-9357-eb362e74910f.png)

Agreed about the font colour, it is hard to read.
