### ISSUE TITLE
Trim model name on rename in UI tree

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5108]
Is anyone opposed to trimming spaces from the name of a model when the user changes it in the tree with "Rename"? A space on the end of a model name is currently accepted but now causes problems with the new invalid path error reporting in Locator as the model names do not match the namebits that have had empty spaces trimmed.

**Comment by zur003** [comment]
Personally I'd be happy if spaces were banned from names entirely, but trimming is the next best thing. It can be hard to see that an invisible leading or trailing space is causing a name mis-match.
