### ISSUE TITLE
Working with excel files in APSIM

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5109]
I assume most users only use excel files (xlsx) for entering Met data. CLEM uses the excel file reader functionality of APSIM for reading data files. Any error generates the APSIM Met data format error (The excel sheet [XXXX] is not a recognised Weather File format) which is not relevant to CLEM users. Is it possible to identify when met files are being used and provide a more generic excel data reader? The reader still works for all I need. 

Also the only excel extension permitted is xlsx. Is there any reason we can't also allow xls and xlsm extensions that some users have attempted to use, or is this a limit of the excel reader. I could add a string[] for the extensions property and even a static method to check if passed extension is in the list (it is relevant to 2 sections of code). This would better determine if the file is an excel file. At present, the error trap to report to the user that only xlsx files are supported is never fired as IsExcel is false and the error code is never reached.

**Comment by hol430** [comment]
Theoretically, the excel input component should allow you to choose any sort of file (*.*) in the UI, but will only work if the file is in the OpenXML (office '07) format (*.xlsx, *.xlsm, maybe some others?). As far as I know, .xls is not OpenXML so it would need to be converted to the newer format.

If ApsimTextFile can be used for reading non-weather files then changing its error message to reflect that sounds like a good idea to me.

**Comment by hol430** [comment]
@lie112 - can you upload the .apsimx and .xlsx files which show the error?

**Comment by lie112** [comment]
I don't have an offending setup at present. 
I do know that there is a bug in logic to catch excel files over everything else that care considered text files. It only allows for xlsx and so even if OpenXML accepts xlsm they can't be used but are considered text files and looks for ( ) units in second row. There needs to be a few more extensions allowed to identify excel files and then if xls then throw the error that "this format is not supported" (the not supported catch is never reached ). One user tried to use xlsm but got errors as it considered it a text file. 
I'll look into the error that threw the "Not a valid met file" error, but I think it's thrown by a very general try catch statement.
