### ISSUE TITLE
 T amp

### ISSUE THREAD

**Issue by IrisVogeler** [APSIMInitiative/ApsimX#5112]
there seem to be different definitions on T amp, can you please clarify if this is the difference between the mean monthly temperature and the maximum or
Tmax - Tmin on a monthly average.  The provided GUI implies this last one

**Comment by hol430** [comment]
Pretty sure it's the second one. See [here](https://www.apsim.info/wp-content/uploads/2019/10/tav_amp-1.pdf):

> Amp is obtained by averaging the mean daily temperature of each month over the entire data period resulting intwelve mean temperatures, and then subtracting the minimum of these values from the maximum

**Comment by hol430** [comment]
Ping @IrisVogeler (in case you missed my above comment).

I'll close this for now - feel free to reopen it or open a new issue if you have more questions.
