### ISSUE TITLE
Intercropping in APSIM Next Generation

### ISSUE THREAD

**Issue by ElsaLagerquist** [APSIMInitiative/ApsimX#5120]
Hi,
I have an intercropping system with cereal and legumes that I would want to model in APSIM to make some system assessments. When I have had a look around the web and in ApsimX I have not seen any module for intercropping, such as the canopy module in the old version of APSIM. Is there an intercropping module under development, and if so when will it be available?

Best regards,
Elsa

**Comment by sarahcleary** [comment]
@peter-devoil and/or @jwhish?

**Comment by peter-devoil** [comment]
Sorry, try @hut104 or @sno036

**Comment by sno036** [comment]
@ElsaLagerquist - Micromet does the above-ground competition and SoilArbitrator does the below-ground competition. Both are mandatory modules in all ApsimX simulations. Apart from that you just have to get the management rules right. Hope this helps.

**Comment by hut104** [comment]
There is also a capacity to have intercrops as mixtures or as strip crops, with shading of zones and roots across zones.

**Comment by ElsaLagerquist** [comment]
Thanks a lot for the help all of you! Then I know where to start. Exciting to see how it works!

**Comment by hol430** [comment]
Closing as answered. Feel free to reopen or open a new issue for more questions.
