### ISSUE TITLE
photoperiod function does not return the correct daylength

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#5150]
@hut104  @HamishBrownPFR 
I was trying to use the daylength to trigger the endoDormancy of the grapevine. I found the photoperiod function does not return the correct daylength. 
for example, around 21 March, daylength should be around 12. however, the photoperiod function returns 13. 
![image](https://user-images.githubusercontent.com/13222562/81753695-785f2600-9508-11ea-838c-7ce28e5125f5.png)

**Comment by zur003** [comment]
"Daylength" is a fuzzier concept than one might expect. Note the following comments from the MathUtilities,DayLength function:

   /// Civil twilight ends after sunset or begins before sunrise when the solar depression angle is 6deg;. e.g SunAngle = -6deg;
        /// Nautical twilight : 12deg;
        /// Astronomical twilight : 18deg;

I take this to mean that "daylength" includes a bit of time at dawn and dusk when the sun is actually below the horizon.

**Comment by junqi108** [comment]
yeah, adding the twilight could make the daylength a bit longer. 
I wonder whether this corresponds to the photoperiod that used in plant phenology.

**Comment by zur003** [comment]
@junqi108 - Note that the MathUtilities.DayLength function does allow the solar depression angle to be specified. I'm not sure what photoperiod function you are using, but if you get results like that with a depression angle of 0, then I would agree that something is wrong.

**Comment by junqi108** [comment]
sorry, I think I am wrong. I tested with a depression angle of 0, and it produces good result.
