### ISSUE TITLE
Need more flexibility in operations model

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#5164]
Currently the action part of an operation is almost c# code i.e. method call e.g.
`[Irrigation].Apply(amount: 8, efficiency: 0.8)`
`[Fertiliser].Apply(Amount: 20.0, Type: Fertiliser.Types.UreaN, Depth: 30)`
`[CuttingManagement].Script.DoCut(10, 50);`

Why don't we just compile this as c# code rather than parsing the text string into bits? This will allow us to write c# code which means we can use LINQ, create objects etc. Very flexible. We already have a function that can compile c# on the fly (CSharPExpressionFunction). Perhaps we can use this function.

**Use case:**

Sell is a method of STOCK:
`public void Sell(double number, IEnumerable<AnimalGroup> groups)`

I would like this extra capability in the STOCK refactor so that the user can do the following from operations:

`Stock.Sell(number: 10, Stock.AnimalGroups.Where(animalGroup => animalGroup.Tag == 10));` - LINQ version
`Stock.Sell(number: 10, Stock.ByTag(10));`  - non LINQ version where ByTag is a method call into STOCK.

**Comment by hol430** [comment]
How do you resolve a symbol like `[Irrigation]` which is not valid C# syntax?

**Comment by hol353** [comment]
I'll probably write a converter to strip all these brackets. Then if I have a [Link] Irrigation Irrigation; it will compile. Essentially I'm converting an operations in a manager script.

**Comment by hol430** [comment]
Well, the name in square brackets could be a type or a name, or an absolute path, or a child reference (ie no path or square brackets). So you could almost get away with adding

```csharp
Irrigation Irrigation = Apsim.Find(operations, "Irrigation");
```

But this still won't work in the case where you have an irrigation module called "irrig".

**Comment by hol353** [comment]
Yes we pay a price for the 'looseness' of APSIM's API. 

I suspect 99 times out of 100 it will be the name of a model. For the 1% of cases where this won't work it might break their simulations. Not ideal I know.

**Comment by hol353** [comment]
Have backed away from implementing this. There are a lot of subtle differences between an operations action and a valid c# line. Closing...
