### ISSUE TITLE
Dark theme not available when you click on the composite factor node

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#5167]
Is the dark theme meant to work on the composite factor or have I done something wrong?
Everything else seems to have a dark background but when I click on the composite factor node (under a factorial experiment) the background is white.

**Comment by hol430** [comment]
You need to right-click in the text area -> use style. There are a few different styles to choose from. This should persist between closing the apsim file and opening it again, and should also affect other components which use a text editor in the gui (manager, report, operations, ...).

**Comment by mpandreucci** [comment]
Thanks for that Drew. That's very cool!
