### ISSUE TITLE
Running experiment cases in parallel

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#5169]
I found that when running an experiment in apsimx, the different cases run in parallel, and I took advantage of this to build a meta-model incorporating several experiment cases running in parallel and communicating with a master model by pipe so they all ran in step. However it seems that I am limited to 12 cases running in parallel. This is plenty for the needs of my project, but I am wondering if it is because my PC has 12 virtual cores, and users with fewer cores may be restricted to fewer parallel executions. If so, is there a way of altering the number of experiment cases that can run at once?

**Comment by sarahcleary** [comment]
@hol430 - are you able to respond?

**Comment by hol430** [comment]
Hi @jal-frezie - yes, by default APSIM will attempt to create as many threads (or processes, depending on which job runner you use) as you have vCPUs. If you don't want it to do this, you can set the environment variable NUMBER_OF_PROCESSORS to however many threads/process you want APSIM to use.

Alternatively, if you're running from the command line (via Models.exe) you can use the /NumberOfProcessors switch like so:

```
Models.exe /path/to/file.apsimx /NumberOfProcessors:256
```

**Comment by jal-frezie** [comment]
Thanks, that does just what I need
