### ISSUE TITLE
Why does IModel require children to be of type Model?

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#5182]
In type `IModel`, children is defined as:

```csharp
List<Model> Children { get; set; }
```

This leads to a lot of unnecessary casts (e.g. [here](https://github.com/APSIMInitiative/ApsimX/blob/fe4934e21dfedbf4809ee991a2ae632f945cedf3/Models/Core/Run/ModelReplacement.cs#L63)) which would be error-prone if we actually had more than one implementation of `IModel`.

Is there any particular reason for this?

**Comment by hol353** [comment]
It shouldn't. It should be List<IModel> Children.
