### ISSUE TITLE
Operations deleting pasted items when we try to save changes (or click out of the operations)

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#5187]
I don't think this a problem that can be reproduced but it has already happened to me twice. 
When I copy, paste and delete lots of items into the operations, these items disappear when I either click out of the operations or if I save the changes done.
I don't know if it has to do with the fact that too many changes were being done or if I was doing something wrong. I'm just leaving this here in case someone else runs into this problem too.

**Comment by hol430** [comment]
Out of curiosity, does your operation string contain tabs instead of spaces? Looking at the code, it seems that changes to a particular line will only be saved if the line contains at least one space. I just tested with tabs instead of a spaces and I get the same result as you (changes aren't saved).

**Comment by mpandreucci** [comment]
No, it doesn't have tabs but it also doesn't have any spaces. However, it also happened when I copied full strings from notepad, which had spaces in them. So not sure?
At least I'm glad you got to make them disappear too hahaha

**Comment by hol430** [comment]
What did your operation look like if it didn't have tabs or spaces? There should be some sort of whitespace between the date and the actual operation.

**Comment by hol353** [comment]
I suspect the problem was with a tab character between the date and the operation. If you were copying operation lines from a text editor or EXCEL then there is a high probability that there was a tab character (which can't be seen by default).

Closing this. Reopen if it comes back.
