### ISSUE TITLE
Need a post simulation tool that calculates basic stats between simulations.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#5208]
If I have an annual report like this:

![image](https://user-images.githubusercontent.com/1943827/82850928-887ff800-9f41-11ea-9b9f-b1a7f180e80c.png)

I want to be able to have whole of simulation stats like this:

![image](https://user-images.githubusercontent.com/1943827/82850974-a8172080-9f41-11ea-9d6f-fa81dd3f4bae.png)

I can't do this in REPORT and I want to be able to graph say average AnnualHarvestedWt.

**Comment by lie112** [comment]
We developed a CLEM SQLReport to basically pass an sql script to a special report that makes a View in the SQLite database that can then be viewed or plotted and all views now show up in all table dropdowns. This doesn't cause data duplication in the database and is fast for analysis. The example above is a simple sql script.

**Comment by hol353** [comment]
I'm not sure what 'example above' you're referring to. 

I wanted a way to do it without writing SQL. Almost no APSIM users know SQL and I didn't want to write it for them. My PR provides a really simple way to fulfill their current needs in NZ.
