### ISSUE TITLE
Auto save functions

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#5221]
I think we need an autosave function. the interface crashes very often when changing the names of the variables. This often makes losses of configurations and decreases efficiency.

**Comment by hol430** [comment]
Which variables are you renaming when apsim crashes?

**Comment by zur003** [comment]
That's the right question to ask. Ideally, Apsim should NEVER crash. If it does, that's a bug to be fixed.

**Comment by junqi108** [comment]
I was renaming on couple of different names, one is the structuralWt in the DM demands. i find when i want to rename variables, click the delete button would cause the interface crash. Met several times, as i have habits to use the delete button. 
![image](https://user-images.githubusercontent.com/13222562/82976290-c6a91480-a032-11ea-986e-92c54e114d54.png)

**Comment by junqi108** [comment]
not sure why the shortcut key combination F2 + delete when renaming works well today

**Comment by hol430** [comment]
Yeah I'm not sure exactly how you managed to trigger an error here (I'm unable to reproduce) but I think I've found the bug nonetheless. I agree with Eric - any crashes should be considered a (fairly serious) bug to be fixed, so I'm not sure that an autosave feature is required. Autosave would also mean that you have modified files showing up in git much more regularly, which would have to be discarded or ignored.
