### ISSUE TITLE
Experiment in Agroforestry - factor only applied to first zone

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#5226]
Attached is a single tree agroforestry simulation in an experiment with one factor of several N rates. The N rate factor is applied only to the first zone of the simulation, but should be applied to all zones. 

This problem might exist for the Windbreak agroforestry system also.

[WorkingFolder.zip](https://github.com/APSIMInitiative/ApsimX/files/4699124/WorkingFolder.zip)

**Comment by hol430** [comment]
Hmm, yes it looks like the experiment/factorial system wasn't really designed with a multi-paddock scenario in mind. I will see what I can do.

**Comment by sme016** [comment]
Sorry, but this fix is not working for my agroforestry example. The factor is manager script 'ExtraNFert', but the tool in the paddock is not overwritten with the different levels of N, as it is in the first zone.

**Comment by hol430** [comment]
Sorry Phil - looks like my test wasn't really representative of the wider problem, as it didn't consider the case of nested zones. Will get a fix out today.

**Comment by sme016** [comment]
I imagine it’s tricky. Thanks

**Comment by sme016** [comment]
Thanks. That now seems to work.
