### ISSUE TITLE
Graphs in Gliricidia Autodoc not working

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5246]
The gliricidia model tests include graphs showing total annual N fixation.  The data are calculated by the report using "sum" between two dates (1-jan and 31-dec).  As a result, the first year is often null.  The graphs do not work when this happens.

**Comment by hol430** [comment]
@hut104 - you've only got one datapoint and your line type is set to solid and your marker type is set to none. I'm not sure how you can draw a line with only one point. Setting marker type to something other than none fixes the problem, although the x-axis is still very zoomed out and must be manually adjusted. I'll push up a fixed version of the file.

**Comment by hut104** [comment]
Well spotted.  The axis range I think had a strange value.  It really made the tick marks and labels to weird things.
I also noticed that the other graphs for Annual N fixation, though they looked the same, had a different problem.  They had no Annual report file in the simulation - and hence there is no data and so the graphs are blank.
I'll have to add an annual report to those experiments if the graphs are going to actually work.

________________________________

**Comment by hol430** [comment]
Yeah, I added in the missing reports and fixed up the x-axes as well in #5247. I think the graphing software was struggling to come up with sensible axis scales with only a single datapoint provided. It was trying to show 0 and the x-value on the same scale - and the x value was 1989 or something which made for a very zoomed-out x-axis.
