### ISSUE TITLE
Don't allow duplication of variable names with JSON objects

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#5275]
Currently it is possible to make an object in JSON that has the same name as a property of the parent object.
For example Phenology has a property called AccumulatedTT.  Currently I can also put a function on the Phenology class in the json file named AccumulatedTT.  The phenology class will not call this when running, it will use its own property.  However, if you report Phenology.AccumulatedTT Apsim will report the the Value of the Function named AccumulatedTT rather than the property that belongs to the phenology class.
This is a pretty silly thing to do but it happens (I just did it) and causes confusion.  Could we include a test that throws an error if function names duplicate the names of properties in the class they sit upon?

**Comment by hol430** [comment]
Yeah, that probably shouldn't be allowed. I've added this check and I'm getting a few errors which will be quite widespread:

- GenericPhase has a child, a field, and a property all called Target
- Soil has a property and a child both called SoilWater
- Plant has a property and a child both called AboveGround

There may be others too - the error is only thrown if the property/child is accessed, and my simulations are bombing before the simulation even starts, when report does its initialisation.

**Comment by hol430** [comment]
This will be a problem for any C# code which uses `Apsim.Get(...)` (this seems to happen a bit in manager scripts). I have written a test to detect this by basically just adding a few lines into the locator code which, when we find a child model with matching name, checks if a public property also exists with the same name. (Note that if the property/model is never accessed, the exception is never triggered.)

Getting my test committed and merged may be difficult.

**Comment by hut104** [comment]
Can we start by helping to avoid this getting worse?

e.g. can we extend the test that naming of child nodes in the UI doesn't duplicate function names to also look for duplication of names of properties.

**Comment by hol430** [comment]
We could, but that might prevent people from setting up a generic phase from scratch. E.g. it expects a child called Target (it has a child link by name), but it also has a property called Target.

**Comment by hut104** [comment]
This is sounding like that earlier soil water property error, of that null reference bug, which required us to have a branch checked out for months while we slowly worked our way through every instance of the problem.
I'm assuming we finished those other two bugs????

**Comment by hol430** [comment]
Yep, they should be fixed now. It's also similar in scope to the duplicate observed data issue which I notice no one has been brave enough to follow up on.

I guess the biggest problem here will be if people reference any of these models or properties in manager scripts. If we don't have to write a converter for manager scripts the problem shouldn't be too bad.

**Comment by hut104** [comment]
Hey, I think I deleted 6 rows of data from the wheat test set, and Hamish and I did discuss how we might clean it up.
We might need to have a meeting to discuss that one.

________________________________

**Comment by par456** [comment]
Apsim.Get() is now Locator.Get(), further units are needed to make sure this isn't a problem still.
