### ISSUE TITLE
List of all simulations in an apsimx file

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5300]
I am trying to run a big apsimx in cluster with multiple nodes, and assume "/MultiProcess" only support local computer. 

It would be useful to add an argument to list of all simulations names.

**Comment by hol430** [comment]
Well we can certainly add a feature which does this, but how does it relate to the /MultiProcess option? And why do you need to list all simulation names?

**Comment by byzheng** [comment]
I want to run simulations on the cluster which are cross multiple nodes with MPI.  Arguments `/MultiProcess /NumberOfProcessors:7` should be only on local computer.

I can split the jobs by parallel by external scripts with argument `/SimulationNameRegexPattern:xx` if I know list of simulations.

**Comment by hol430** [comment]
Makes sense, I'll add something which does this.

**Comment by BrianCollinss** [comment]
List of 'enabled' simulations, I'd say.

**Comment by hol430** [comment]
Here is what I had in mind for sample output. It should be easier to parse than a table, and listing disabled simulations would be tricky. Easier to just go with simulations which are enabled. Note that the simulation regex pattern is not necessary, I just used it here so I didn't get 2000 lines of output :).

```
PS C:\ApsimX> models .\Tests\Validation\Wheat\Wheat.apsimx /ListSimulations /SimulationNameRegexPattern:APS.*
APS26NRate0WaterWet
APS26NRate40WaterWet
APS26NRate80WaterWet
APS26NRate160WaterWet
APS26NRate0WaterDry
APS26NRate40WaterDry
APS26NRate80WaterDry
APS26NRate160WaterDry
APS6NRate0
APS6NRate40
APS6NRate80
APS6NRate120
APS6NRate160
APS6NRate360
APS14StubbleBareNRate000
APS14StubbleLucerneNRate000
APS14StubbleStrawNRate000
APS14StubbleBareNRate040
APS14StubbleLucerneNRate040
APS14StubbleStrawNRate040
APS14StubbleBareNRate080
APS14StubbleLucerneNRate080
APS14StubbleStrawNRate080
APS14StubbleBareNRate200
APS14StubbleLucerneNRate200
APS14StubbleStrawNRate200
APS2TOS1
APS2TOS2
```

**Comment by BrianCollinss** [comment]
How can we have this list before running the model?

**Comment by hol430** [comment]
You'll be able to get this list by using the `/ListSimulations` command line switch, once I get a pull request up and going.

**Comment by BrianCollinss** [comment]
Sorry I think I wasn't clear. Does this command NOT run the model? Does it just extract the list?

`PS C:\ApsimX> models .\Tests\Validation\Wheat\Wheat.apsimx /ListSimulations /SimulationNameRegexPattern:APS.*`

**Comment by hol430** [comment]
Ah sorry, that's right yes, it doesn't run the model, just spits out the list of simulation names.

**Comment by byzheng** [comment]
Thanks @hol430. The enable simulations in a list will be enough for me.
