### ISSUE TITLE
Clover fixation defaults AGPasture Science document

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#5307]
In Table 5 of the AGPasture Science document there are no default values for the N fixation parameters. 

Function of the parameter Public double Deafault Value
Minimum fraction of N demand supplied by biologic N fixation MinimumFixation 0
Maximum fraction of N demand supplied by biologic N fixation MaximumFixation 0
Respiration cost factor due to the presence of symbiotic bacteria SymbioticCostFactor 0
Respiration cost factor due to the activity of symbiotic bacteria NFixingCostFactor 0

**Comment by mpandreucci** [comment]
I have no idea why they are 0 but I'll fix it on Thursday

**Comment by MarkLieffering** [comment]
thanks.
like this @sno036 ?

**Comment by rcichota** [comment]
Are the values of SymbioticCostFactor and NFixingCostFactor actually used? I have a suspicious that these are left overs from an attempt of using a more mechanistic procedure for fixation than the base one. If so, sorry for leaving some mess code. But maybe some development did happen...

**Comment by mpandreucci** [comment]
I’ll check that.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mpandreucci** [comment]
MinimumNFixation and MaximumNfixation were fixed. 
The cost factor are not used. They are only indicated.

**Comment by hol353** [comment]
Actually the 2 cost factors are being used in the source code.
```c#
        /// <summary>Calculates the costs of N fixation</summary>
        /// <remarks>
        /// This approach separates maintenance and activity costs, based roughly on results from:
        ///   Rainbird RM, Hitz WD, Hardy RWF 1984. Experimental determination of the respiration associated with soybean/rhizobium 
        ///     nitrogenase function, nodule maintenance, and total nodule nitrogen fixation. Plant Physiology 75(1): 49-53.
        ///   Voisin AS, Salon C, Jeudy C, Warembourg FR 2003. Symbiotic N2 fixation activity in relation to C economy of Pisum sativum L.
        ///     as a function of plant phenology. Journal of Experimental Botany 54(393): 2733-2744.
        ///   Minchin FR, Witty JF 2005. Respiratory/carbon costs of symbiotic nitrogen fixation in legumes. In: Lambers H, Ribas-Carbo 
        ///     M eds. Plant Respiration. Advances in Photosynthesis and Respiration, Springer Netherlands. Pp. 195-205.
        /// NOTE: This procedure will use today's DM for maintenance costs, but yesterday's fixedN for activity (as today's fixation has 
        ///  not been calculated yet).
        /// </remarks>
        /// <returns>The amount of carbon spent on N fixation (kg/ha)</returns>
        private double DailyNFixationCosts()
        {
            double fixationCost = 0.0;
            if ((SymbiontCostFactor > Epsilon) || (NFixingCostFactor > Epsilon))
            {
                //  respiration cost of symbiont (presence of rhizobia is assumed to be proportional to root mass)
                double Tfactor = TemperatureEffectOnRespiration(Tmean(0.5));
                double maintenanceCost = BelowGroundLiveWt * CarbonFractionInDM * SymbiontCostFactor * Tfactor;

                //  respiration cost of actual N fixation (assumed as a simple linear function of N fixed)
                double activityCost = fixedN * NFixingCostFactor;

                fixationCost = maintenanceCost + activityCost;
            }

            return fixationCost;
        }
```
The species files don't specify a value for these two parameters. The default values in the source code for the two parameters are zero so the science document is now correct. I'm not sure if the legumes should have a non zero value for the 2 parameters. 

Closing issue. Feel free to reopen if there is still an problem.
