### ISSUE TITLE
Adding 'Cultivars' to 'Replaqcements' 

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5309]
Following the question #4896, I still cannot replace the cultivar Axe with the latest version of APSIM.

Steps what I have done:

* Right click on replacements
* Click add model
* Double click cultivar or cultivar folder in the right hand view
* Change Axe parameters into a wrong value (AAA in my case)
* APSIM still runs without errors

Example to add Cultivar Folder in the replacement. 

![image](https://user-images.githubusercontent.com/1657381/84732104-29605100-afde-11ea-801c-c361828fb6ac.png)

**Comment by hol430** [comment]
Thanks @byzheng, definitely looks like the same issue as #4896. Will add a test this time so I don't end up fixing it a third time...

**Comment by hol430** [comment]
Sorry for the double comment @byzheng - but I just tried this again and it's working for me (I get an error) after I renamed my cultivar folder to "Cultivars" like you did. Are you able to upload your .apsimx file so I can test it?

**Comment by byzheng** [comment]
My example is directly cut from wheat.apsimx and can be stored under Tests\Validation\Wheat to run it.  

[GattonBZ.zip](https://github.com/APSIMInitiative/ApsimX/files/4784710/GattonBZ.zip)
