### ISSUE TITLE
Get regression data by simulation as an output

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/ApsimX#5346]
I created a factorial between Nitrogen and Water levels which generates 9 simulations. I am comparing the predicted values to observed values. Then, I created an XY graph with regression data by SimulationName. I would like to export (e.g. txt/csv file) this data or see it in APSIM in some way that allows to identify which Simulation had the best fit to the 1:1 line. I can see the values in the graph but I cannot identify the corresponding SimulationName for each regression data. @hol430 
![Untitled](https://user-images.githubusercontent.com/41041705/85649289-1a685580-b6e6-11ea-8c56-d5083f6d8c84.jpg)

**Comment by mpandreucci** [comment]
Hi Jonathan.
Not sure if it's the same thing but I think I had that problem too. If you change the background to white you will see that the equations will have the same colour of the respective regression.

**Comment by hol430** [comment]
Yep, this is probably just an oversight/bug, however it does raise the question of what should it be doing in this scenario. E.g. we could change the text colour of the regression stats to match the series, but in this case you have 3 green series, so you'd end up with 3 green regression stats.

**Comment by mpandreucci** [comment]
Yeah, that's another problem on top of the colour/background one haha

**Comment by JJguri** [comment]
Thanks @mpandreucci and @hol430 

I got it. And I can see different colors by SimulationName. However, I would like to export these data outside apsim or, at least, see it in a table like the attached image, but at SimulationName level. The current Test is creating the stats by Variable , not by SimulationName like in the graph. Another point is the position of the equations/legend. Is there a way to move it outside the figure?

![Untitled](https://user-images.githubusercontent.com/41041705/85802308-0c6b1100-b788-11ea-812a-7ae94a435e5e.jpg)
![Untitled2](https://user-images.githubusercontent.com/41041705/85802316-112fc500-b788-11ea-9c08-70464390e7a3.jpg)
