### ISSUE TITLE
Display child simulation results when no factorial experiment run

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5354]
I am working with an Experiment and there are times when I want to run the underlying simulation (with an empty DataStore) and look at the generated results before running the larger factorial experiment. I realise I can just cut and paste the simulation to the tree structure outside the experiment or another file, but this is a bit messy, duplicates details and is unnecessary.

At present the DataStorePresenter does not allow the display of simulation data when an experiment is present as a parent. I have made a small change to DataStorePresenter.GetData() to recalculate the data presented and try display of the simulation results when the experiment simulation has not been performed (ExperimentFilter is present but no rows returned).

I am writing to see if this change would break any APSIM Next Gen logic with experiments, cause anyone problems and be supported by others before committing.

**Comment by hol430** [comment]
You can always just filter by simulation name in the report view or datastore view. On the other hand, if your datastore is empty before you run the simulation, then you can just run that one simulation and the only data in the datastore will be from that simulation.

**Comment by lie112** [comment]
The problem is that Report Presenter does not pass a Simulation filter (and therefore simulation name) when an Experiment is present as a Simulation parent and so I don't think either of your approaches will work. There is no means of filtering on simulation name as there is no data and your second example does not work as the Experiment filter details mean that the report returns no data even though the simulation is in the datastore. This is the problem I have written a bit of code to address. I could modify (or disable an entry) in the experiment factors to run one factor, but I thought there was a little bit of logic missing to be able to report the simulation outcomes when you don't run the full factorial experiment.

**Comment by hol430** [comment]
If you've run the simulation/experiment but there's nothing showing up in the report, that may be a bug but it doesn't happen for me. I tested in the factorial example and data shows up for me in the report after I empty datastore and run a single simulation of the experiment, or the entire experiment. Filtering by simulation name also seems to be working fine for me. Are you looking at one of the example files - and if not can you upload your .apsimx file?

![image](https://user-images.githubusercontent.com/36427516/86183158-bf66b080-bb74-11ea-880e-8bcd5ee38833.png)

**Comment by lie112** [comment]
I agree that works as you've run the experiment with a single factor and value. Maybe what I am doing isn't done elsewhere and there are workarounds. What happens when you empty the data store and right click/run on Base2 simulation? I would expect that the results for that simulation (separate to the experiment) should show up as all the data with Base2 in Simulation column is present in the datastore, but nothing shows up in the DataStorePresenter display due to filtering of the experiment details.

**Comment by hol430** [comment]
Ah, ok I'm with you, I get the same result (no result) when running the base simulation. I notice the summary view also doesn't show anything for the base simulation. I'm not sure if this is a bug or deliberate - I don't think the base simulation is really intended to be run by itself, but maybe we should allow for this in the report/summary. On the other hand, if you run the base simulation and then run the experiment (or part of it), the base simulation probably shouldn't show up in the report.

In your case, why not just run a single factor value/combination of the experiment (you can do this by right-clicking one of the rows in the experiment view)?

**Comment by lie112** [comment]
Thanks, I wasn't aware of the ability to run a single factor from the experiment view. So many things I don't know about.
I agree, probably a simulation inside an experiment isn't meant to be run on its own and doesn't have results unless at least one factor of the experiment is run. My approach only showed the simulation results if present and the experiment filter returned no results (i.e. wasn't run), but this could get confusing and relies on the datastore being emptied after experiment simulations.

Is there a way of running two factors in an experiment that change together. Not a permutation and I can't get what I want in the composite factor.
What I want is basically
[xxx].MaxBreeders = 1600 to 2600 step 200
[xxx].MinBreeders = 1600 to 2600 step 200

so that simulation1 is Maxbreeders 1600 and minBreeders 1600
simulation 2 is  Maxbreeders 1800 and minBreeders 1800 ...
ie combine the columns below
![image](https://user-images.githubusercontent.com/19215637/86190710-42dbce00-bb84-11ea-9a26-e246d0f7c42b.png)

Happy to close this issue after you let me know if my second question is possible. Otherwise I will have to write code to handle it for a special case of if MinBreeders < 0 then minbreeders = maxbreeders or something.

**Comment by hol430** [comment]
No, I don't think that's possible out of the box unfortunately. What you can do is do a full permutation, and then just disable the simulations which you don't want run (right click on a particular row in the experiment view and hit disable. You can also drag/shift click to select multiple rows). I think that would be the standard approach.

![image](https://user-images.githubusercontent.com/36427516/86191859-7b32da80-bb8b-11ea-9a59-5d3a740d21f7.png)

I guess you could also write a new model which functions similarly to the Permutation model, and add an interface (implemented by Permutation and the new model), and change Experiment to talk to the interface, rather than to the Permutation model directly.

**Comment by lie112** [comment]
Thanks heaps for all your help. Good workarounds and the sign of a well thought out model when you can usually achieve things with what is provided. The experiment display does add a lot of extra functionality with run and disable. It's not a usual request and I have allowed the code to handle setting min breeders to match max breeders when the user sets min breeders as a number larger than max breeders thus allowing a single factor and a large (100,000) min breeders set.
