### ISSUE TITLE
AgPasture science review.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#5356]
It is time for a review of the science in AgPasture. Two things to kick off the list:

- There are 4 options for doing water and solute uptake. Need to standardise on one. Currently AgPasture uses the 'basic' option. Should look at one of the other options.
- From @MarkLieffering: the CO2 response in AgPasture needs a to have no effect for when CO2 is below the reference level of 380ppm. It should be like this from EcoMod http://imj.com.au/wp-content/uploads/2014/08/GrazeMod.pdf page 4.12:
![image](https://user-images.githubusercontent.com/1943827/86410768-c02b4e00-bcfe-11ea-89ee-277b7a69edd4.png)

**Comment by peter-devoil** [comment]
Can we also have establishment / killing routines so it works in a rotation?

**Comment by hol353** [comment]
@peter-devoil Can you elaborate a bit on this? What do you mean by establishment routines. 

The model does respond to a Kill management call. It also implements the plant and organ damage routines so that crop consumers (pest and diseases) can damage a pasture species.

**Comment by peter-devoil** [comment]
Sowing routines. Perhaps I am missing something, or thinking of classic. One day it would be good to run a crop/pasture rotation.

**Comment by sarahcleary** [comment]
@jwhish - you may wish to comment?

**Comment by hol353** [comment]
I've found a problem in AgPasture that needs fixing. 

Soil Arbitrator sends 4 soil N states to a pasture species and expects an estimate back for each on how much N would be taken up. AgPasture does this but always returns the same estimate back to soil arbitrator regardless of the soil state passed to it. The result is that each species will be given full access to all the available N in the soil which means that there is no competition between the species. 

When I fix the bug I get a dramatic over prediction in the validation harvested wt:
![image](https://user-images.githubusercontent.com/1943827/86556100-a9525900-bf95-11ea-9b29-e1d5c6bfdaa9.png)
The blue dots are with the bug fixed. The orange dots are the original validation values.
RMSE changes from 2045 kg/ha to 3529 kg/ha
NSE changes from 0.57 to -0.27
R2 changes from 0.57 to 0.56

This needs further investigation.

**Comment by rcichota** [comment]
> Sowing routines. Perhaps I am missing something, or thinking of classic. One day it would be good to run a crop/pasture rotation.

@peter-devoil ,
The model does have a sowing routine now (I had implemented in late versions of Classic). I have run simulations with rotations (and multi-cropping) involving PMF crops and AgPasture (they may need a better look/validation, but they are possible at least). Phenology is very simplified in AgPasture, so germination and early development would benefit of having some development...
For pastures being able to run simulations without needing to sow (with the crop already established) can be quite handy, maybe there is room for thought and development in both AgPasture and PMF in this regard...

**Comment by rcichota** [comment]
Regarding the 4 options to do the water/N uptake (from first comment), I have implemented them, trying to test different ways to do these processes in Apsim. Thus, I probably should have either selected one deleting the rest or make clearer what was going on (I probably have some documentation if needed). AgPasture had a very simple (too simple) way of doing uptake, one of the implementation was to mimic what Plant was doing. The others, I think, were attempts to get rid of KL. I had no time (nor good data) to properly test them, it would be good to check whether it is worth pursuing them (maybe not only for AgPasture) or simply delete and make the code cleaner... Happy to give some help if needed

**Comment by demlie257** [comment]
I am using APSIM Next Generation for modelling the pasture (Ryegrass and white clover) and eucalyptus tree growth. I want to extract information on the water and nitrogen stress in both the pasture and tree production systems, and I would like to kindly ask you to give me a hint on the methods/steps to extract such outputs from APSIM Next Generation.

**Comment by sarahcleary** [comment]
@HamishBrownPFR; @her123, @sno036  -are you able to help @demlie257?

**Comment by MarkLieffering** [comment]
from the documentation (https://apsimnextgeneration.netlify.app/modeldocumentation/ and the pdf for ryegrass https://apsimdev.apsim.info/ApsimX/Releases/2021.04.15.6139/AGPRyegrass.pdf) choose the appropriate output e.g. GlfNSupply Gets the growth limiting factor due to soil N availability or GlfWaterSupply Gets the growth limiting factor due to water deficit. Then just output these in report e.g. [AGPRyegrass].GlfWaterSupply or  [AGPRyegrass].GlfNSupply

**Comment by MarkLieffering** [comment]
Also check out the AgPasture example simulation for examples

**Comment by sno036** [comment]
All the outputs (and inputs, parameters, ...) can be found in https://apsimnextgeneration.netlify.app/modeldocumentation/ then go to the "Params/Inputs/Outputs" column and open the PDF. In AgPasture species the stresses all start with "Glf" so you will find them together in the middle of Page 11.

@hut104 can you point the stress outputs for Eucs?

@demlie257 - to help us, can you say where you initially looked for this information but couldn't find it? We do attempt to provide options for new users but one thing that we don't know is where new users look for information.

**Comment by demlie257** [comment]
Thank you all a lot for providing me your relevant feedback for my
enquiries.

Kind regards,

Demlie

**Comment by demlie257** [comment]
Dear all,

I was simulataing N and Water stress in APSIM, and I
obtained different values in the range between 0 and 1.  What does ‘0’,
‘0.45’ and ‘1’ values in water and nitrogen stress simulation result in
APSIM?

Kind regards,

Demlie

**Comment by demlie257** [comment]
Dear all,

When simulating cow weight gain in APSIM, the cow weight doesn't not
sometimes increase as proportional to increased supplementary feeding
instead the cow weight decreases over time. Is there any mechanism related
to climatic or any other conditions for that cow weight is not increasing
regardless of the amount of supplementary feeding?

Kind regards,

Demlie

**Comment by MarkLieffering** [comment]
with regard to the stress (GLF) out outputs, as described in the AgPasture example ReportExample:

"// outputs that indicate what conditions are limiting growth - each growth-limiting factor is 0 (full stress) to 1 (no stress) but there are two components and the values are added so 2 indicates no stress"

So 0 is full stress and 1 is no stress - these are for each of the stresses (water, temperature etc.) and multiplied with the growth without stress - so a value of 0 for water stress and 1 for the other stresses for example will give no growth (0 * 1 * 1 * x = 0)

**Comment by demlie257** [comment]
Thank you very much for the feedback, and the clarification  made.

Kinde regards,

Demlie
