### ISSUE TITLE
Cannot read observed file

### ISSUE THREAD

**Issue by JJguri** [APSIMInitiative/ApsimX#5357]
I cannot read the observed file, therefore, it is not matching data from DailyReport in the TimeSeriesData to create XY graphs. Please see error below:
![Untitled](https://user-images.githubusercontent.com/41041705/86417444-5e73df80-bd10-11ea-9d2e-db3d7f9ce244.jpg)

**Comment by hol430** [comment]
What file format is your observed file in? And can you show the configuration of your Observed node in apsim (ie just click on it and take a screenshot)?

**Comment by JJguri** [comment]
The file is xlsx, here is the screenshot
![Untitled](https://user-images.githubusercontent.com/41041705/86418209-c4f9fd00-bd12-11ea-9778-30ca47abbf22.png)

**Comment by hol430** [comment]
Hmm, that looks legit, and the excel input (observed) component should be throwing an error if it's not working. Are you able to upload your .apsimx and .xlsx files?

**Comment by JJguri** [comment]
It is weird because I was working on it yesterday. Today, I just changed some column names. Here you have apsimx, met and observed file 
[Sorgo.zip](https://github.com/APSIMInitiative/ApsimX/files/4867105/Sorgo.zip)

**Comment by hol430** [comment]
Ah ok, looks like the problem is the square brackets in the column names in the observed file. If you just remove the square brackets, then everything seems to work ok.

We should probably allow for square brackets in the column names though - I'll see what I can do.

**Comment by JJguri** [comment]
Thanks @hol430 ! It will be nice to be able to put directly the name of variables as they are stated in the Report.

**Comment by hol430** [comment]
Agreed -there should be a new upgrade available later today which fixes this.
