### ISSUE TITLE
Simulate climate change

### ISSUE THREAD

**Issue by guillemodon** [APSIMInitiative/ApsimX#5366]
Hi, does anyone know what module I have to use to simulate temperature and CO2 gaps

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - can someone help?

**Comment by MarkLieffering** [comment]
It is not clear to me what you mean by "simulating temperature and CO2 gaps" - you mean gaps in existing data? Or just simulating the effects of changing temperature and CO2?

**Comment by guillemodon** [comment]
Exactly, simulate the effects of temperature change ... I want to see what effects it would produce on the crop

**Comment by MarkLieffering** [comment]
If you have an existing weather file then you can use the ClimateController model to change rainfall, temperature, radiation etc. See the example simulations in \ApsimX\Examples\Tutorials\ClimateController.apsimx. See the AgPasture example \ApsimX\Examples\AgPasture.apsimx for a manager script to change CO2

**Comment by guillemodon** [comment]
Thank you so much !!! I have to adapt to corn
