### ISSUE TITLE
Newbie request compiling APSIMX visual studio code

### ISSUE THREAD

**Issue by nicola31** [APSIMInitiative/ApsimX#5385]
Hi,

Thanks in advance for the help, I pulled the code for APSIMX so I can do some mods and integrate the outcome into economic modelling.  I'm a PhD Ag. Econ student, I've done modelling in APSIM classic, I did training in visual coding and now I am trying to get it all happening together.

I've built APSIMX successfully in Visual, but I am not sure how to import the weather data and set up the Visual APSIMX file to run a simulation and view the results, if anyone has any suggestions or links to documentation I can use as a guide I would appreciate them. 

Cheers
Nicola

**Comment by hol430** [comment]
When setting up an .apsimx file, it's generally easier to start with an existing file and modify it to suit your purposes. There are a number of example files in the ApsimX/Examples directory which are a good starting point. For importing the weather data, have a look at the file format of the files in ApsimX/Examples/WeatherFiles directory (just open one of them up in a text editor). If you add your weather data to a similarly-formatted file then you should be able to use it from apsim. Alternatively, you can use an excel file for weather (documentation [here](https://apsimnextgeneration.netlify.app/usage/usingexcelforweatherdata/)).

**Comment by nicola31** [comment]
I've been working on it and I think its just a matter of debugging the code - there are a few test fails due to the code I've added I need to iron out.
