### ISSUE TITLE
Write boolean as integer (0-1) to SQLite reports

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5393]
The current Sqlite.GetDBDataTypeName(Type type) method reports boolean properties as TEXT for database column creation.
Is there a reason for this or could we create boolean based columns as integer (0-1) in our SQLite reports?

**Comment by hol430** [comment]
Probably no reason, but the performance tests will let you know for sure.

**Comment by lie112** [comment]
Performance test? Is this a Jenkins test to see if the changes provided are detrimental to speed and memory?
I would suggest it will be quicker for SQLite and result in smaller database size, but may need a converter to display values on the screen in grid view if we don't want 0/1 but current true/false.
Do other expect/work with the reported values as text?

**Comment by hol430** [comment]
Sorry - the performance tests test the models' accuracy, to ensure that code changes don't cause their goodness-of-fit to become worse. It would be nice to test speed/memory as well but we don't do that at present. You should see the performance tests show up as a separate status check to jenkins on a pull request:

![image](https://user-images.githubusercontent.com/36427516/87386405-c4e7e000-c5e3-11ea-8ff4-9b705368445e.png)

The performance tests only evaluate files under Tests/UnderReview, Tests/Validation, and Tests/Simulation, for all files which have a PredictedObserved node under the datastore.
