### ISSUE TITLE
Need some new post simulation tools

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#5397]
1 Need a tool to filter rows of a table e.g. Year > 1990
2 Expand the functionality of SimulationStats to allow user to select the stats to calculate and to specify the fields to 'group on'. Currently it only groups on SimulationName. Need the ability to group on other fields.
3 Need a post simulation tool that lets the user write an expression using simulation names that takes a source datatable and calculates a new table that gets stored in the datastore.

For example: there are two simulations (ambient and elevated co2) in a table. Need to calculate a new table that shows the difference in growth between the two situations expressed as a percentage (ELEV-AMB)/AMB is XX%. The expression string for this would be:
   ```(ElevatedCO2-AmbientCO2)/AmbientCO2*100```
where ElevatedCO2 and AmbientCO2 are the names of the simulations in the source data table.

**Comment by lie112** [comment]
This is an easy sql statement and we can create a view so there is no doubling up of storage with large datasets stored in the database. No need to wrote code to create new tables. A user interface could be used to help build the sql, then add a view based on the select statement. This works really well.

**Comment by hol353** [comment]
Could do it that way but the users want the data stored in the .db file so they can extract it to EXCEL. It is also quicker this way as I don't need to write yet another user interface view and presenter.

**Comment by hol430** [comment]
Well the view (but not duplicate data) would be stored in the DB, so you could still extract it to excel, even from say python or R. There should be some advantages to using views, and I suspect we should consider refactoring some components such as PredictedObserved to use views. No idea about their performance characteristics though.
