### ISSUE TITLE
Deleting soil layers

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#5400]
@hol430 I had a chat to @hol353  and he told me to copy you in this (sorry haha) for you to have a go and see if you get this error.
When I delete soil layers from the physical and SoilWater nodes, the layers end up not being completely deleted from the SoilWater node. For that reason, APSIM throws an error that the layers from the physical node don't match the layers in the SoilWater node. This is happening in the Validation of AgPasture. 
Drew if you have a look at the SouthKaipara location, you will see the soil I had a go with (I actually tried it with two other locations and that happened in both too, so I guess it would happen with any other soil in the simulation).
I pushed some changes that were done to the validation so I guess it would be best to wait until this is merged to have a look at the soils.
Thanks a lot

**Comment by hol430** [comment]
Yeah, when you want to delete a layer you need to delete the entire row at once (you can shift click to select multiple cells, just select the entire row(s) and hit delete). I just tested this on the disabled soil in south kaipara on your branch and it seems to be working ok for me.

**Comment by hol353** [comment]
@hol430 I think we need to either stop the user doing what @mpandreucci did (which is the most obvious way of doing it) or we write code to do it either way.

**Comment by mpandreucci** [comment]
Thanks for that @hol430 
Yeah, I agree with @hol353, apsim either warns the user to select everything at once or we need a way to not make this a problem anymore.

**Comment by hol430** [comment]
Well we could change it so that when you delete a cell(s), if all non-readonly cells in the row are empty, the row is removed. That might be more intuitive

**Comment by hol353** [comment]
Yep that sounds like a good idea.
