### ISSUE TITLE
Checkpoints in datastore

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#5407]
@hol430 I tried adding a checkpoint to a simulation and when I cliked to have it added to the graphs I got an exception thrown at line 669 of the DataStoreWriter.cs 
With that I couldn't get the checkpoint working.
Hopefully I didn't break anything?
![image](https://user-images.githubusercontent.com/43769255/87738178-e093f600-c830-11ea-90ab-89c47f980dba.png)

**Comment by hol430** [comment]
Ah ok, yep that's a bug, shows how well tested the checkoints code is.
