### ISSUE TITLE
effects of extreme climate events on crop production 

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/ApsimX#5415]
Dear Sir/Madam

Here I have a couple of questions regarding the effects of extreme high (heat stress) and low (frost/cold shock) temperature on crop production in ApsimX.

(1) Wheat and Canola: Not sure if the effects of extreme temperatures on crop production have been internally captured by these two crop models. But I do know that external empirical functions on the effects of heat stress and frost risk on these two
crop production are available in the Management toolbox of the APSIM 7.10.

(2) Cotton, Barley and Oats: Just wondering if the effects of extreme high and/or low temperatures on these crop production have been considered internally by the relevant crop models in the current apsimX or external empirical functions are available to use.

Hope to get you feedback at your earliest convenience!

Best regards!

Qunying

**Comment by hol430** [comment]
Worth noting that apsim next gen doesn't have a canola or cotton model yet. I think the other models you mentioned do respond to temperature stress but someone else (@hut104, @sno036, ...) could say for sure.

**Comment by qluo02** [comment]
Thanks Drew for your feedback!

Kind regards!

qunying

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
