### ISSUE TITLE
Create Models.Climate namespace

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#5438]
All of the weather-related components are in a directory called Weather but are in namespace Models. If I add a new class to the weather directory via visual studio, it automatically places it in the namespace Models.Weather, but this fails because Models.Weather is a type. I propose that we rename the weather directory (maybe to to Climate?), and move all of the classes in this directory into the Models.Climate namespace. @hol353 does this sound ok to you?

**Comment by hol353** [comment]
Yep this is a real problem. What you're suggesting sounds good to me. Will need to write a converter though!
