### ISSUE TITLE
using excel for met file instructions

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#5440]
it is really handy being able to use excel files as the met file in NG: https://apsimnextgeneration.netlify.app/usage/usingexcelforweatherdata/

one of the requirements of the met file has been to have values for Tav and Tamp. It has been brought to my attention that these are now internally calculated by APSIM and are not required for the met file (I have checked and this appears to be the case). It would be good to update the text in the URL so that people do not need the angst of calculating these values.

Thanks Drew - I somehow submitted issue somehow without finishing before

**Comment by hol430** [comment]
Hi @MarkLieffering, there is some documentation for this [here](https://apsimnextgeneration.netlify.app/usage/usingexcelforweatherdata/)

**Comment by MarkLieffering** [comment]
Just to add - maybe in the documentation stress that the sheet name MUST be specified (seems need a couple of clicks to ensure it is) - otherwise if you have copied a simulation (and changed the met file) but leave the sheet field blank it reverts to using the original met file

**Comment by hol430** [comment]
Sure, I can update the docs. As for the second issue with providing the sheet name, maybe we should throw an error if sheet name is not specified.

**Comment by MarkLieffering** [comment]
Thanks Drew. the sheet name error - sounds like a good idea - it'll only be a line of code :-)
