### ISSUE TITLE
Remove Leguminosity from plant models

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5449]
/// <summary>Gets a value indicating how leguminous a plant is</summary>
        [XmlIgnore]
        public double Legumosity { get; }

This is only used in the stock model, which could do a look-up on crop type.

**Comment by hol430** [comment]
@hol353 @hut104 What is the reasoning for removing leguminosity? It appears that the various IPlants actually implement this differently. For most it's just a 0/1 value, but in G_Range it's actually defined as `parms.maxSymbioticNFixationRatio * 100.0`. We don't want stock_padd to end up looking like this:

```csharp
if (forageObj is G_Range)
    result.LegumePropn = ...
else if (forageObj is Plant)
    result.LegumePropn = ...
else if ...
```

**Comment by zur003** [comment]
@hol430 - Don't worry too much about the GRange implementation. It's only in there to satisfy the requirements of the IPlant interface. The value for parms.maxSymbioticNFixationRatio is expressed as g N fixed / g C new growth, and usually has the value 0.001, so Leguminosity will be returned as 0.1 - hence it's actually on the 0-1 scale. It's probably rather meaningless though - GRange doesn't have an internal concept of leguminosity per se.

**Comment by hol430** [comment]
Ok, that will make it easier if we can change the GRange implementation.The only other class with a non-constant implementation is PastureSpecies:

```csharp
/// <summary>Gets a value indicating how leguminous a plant is</summary>
public double Legumosity
{
    get
    {
        if (SpeciesFamily == PastureSpecies.PlantFamilyType.Legume)
            return 1;
        else
            return 0;
    }
}
```

I'm not sure how this could be generalised to work with other plant types. SpeciesFamily is specific to agpasture, and CropType is specific to Plant. It seems that if we get rid of Legumosity, we will need another property to take its place.

**Comment by hol353** [comment]
You can't just remove it unfortunately because STOCK uses it to calculate LegumePropn which in turn is used to calculate herbageEfficiency and intake. If you do want to remove it from the plant models (and I think you should), you'll have to add a list of legume CropTypes in STOCK to use the plant.CropType and do a lookup to determine legumosity. Don't use plant.Name for the lookup though as there might be a wheat and a wheat1 in a simulation.

**Comment by hol430** [comment]
Well stock is looking at IPlants, and IPlant has no concept of a CropType. So you would have to first check if the IPlant is a Plant, and then look at CropType. Otherwise handle each other IPlant implementation differently.

**Comment by hol353** [comment]
Add CropType to IPlant.

**Comment by hol430** [comment]
Well, I can't say I like the idea of doing a string lookup here, but I can't think of any better alternatives which also involve removing Leguminosity so I guess that sounds like a plan. I will rename CropType to PlantType though.

What would be the PlantType for your pasture species?

**Comment by hol353** [comment]
One the species names that AgPasture supports. Look at the AGP... resources in Models.exe .e.g. the first one would be Browntop.
