### ISSUE TITLE
ReduceCanopy method should be in Leaf models

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5472]
In fact it is probably not required as LAI is settable in the ICanopy interface

        /// <summary>
        /// Set the plant leaf area index.
        /// </summary>
        /// <param name="deltaLAI">Delta LAI.</param>
        public void ReduceCanopy(double deltaLAI)
        {
            var leaf = Organs.FirstOrDefault(o => o is ICanopy) as ICanopy;
            var lai = leaf.LAI;
            if (lai > 0)
                leaf.LAI = lai - deltaLAI;
        }

**Comment by hol430** [comment]
This is required by the `IPlantDamage` interface, I think it will have to stay. It could be made more efficient though.

**Comment by hut104** [comment]
Can we change IPlantDamage? It seems silly to have two ways of doing something so basic.

**Comment by hol430** [comment]
Well `PastureSpecies` also implements `IPlantDamage`, but its `ReduceCanopy()` implementation is a bit different - it manually calls `leaf.RemoveBiomass()`. Theoretically there could be other `IPlantDamage` implementations as well which also do it differently. So it's not as simple as just exposing LAI in the interface with a setter. I'm not sure what the best solution is.

**Comment by hut104** [comment]
We should investigate why changing LAI is handled differently.  Is one of these doing something incorrectly?

**Comment by jbrider** [comment]
Isn't the damage interface allowing for removal of actual leaf not just reduction in potential growth.  How is the biomass and N accounted for if you just change LAI in isolation?

**Comment by HamishBrownPFR** [comment]
I never finished implementing the damage stuff from Lifecycle so it is quite possible there is some weird stuff in there.  Even it I did finish it there is still a high posibility of there being weird stuff in there

**Comment by hut104** [comment]
I'm not sure they should ever be done in isolation. If you remove leaf area you should remove the biomass related to it.

________________________________

**Comment by hol430** [comment]
The ReduceCanopy function is called from 2 places, once from PlantOrganFunctionalDimensionReduction and once from Plant.RemoveBiomass(). However it gets more confusing because Plant has 3 methods called RemoveBiomass and only one of them manually reduces the Canopy. To make things even more confusing, I don't think the PlantOrganFunctionalDimensionReduction actually works. This is the code:

```csharp
[EventSubscribe("DoPestDiseaseDamage")]
private void DoPestDiseaseDamage(object sender, EventArgs e)
{
    if (HostOrgan.GetType() == typeof(ICanopy))
        HostPlant.ReduceCanopy(Reduction.Value());
    else if (HostOrgan.GetType() == typeof(IRoot))
        HostPlant.ReduceRootLengthDensity(Reduction.Value());
    else
        throw new Exception("FunctionalDimensionReduction is only possible for organs implementing ICanopy or IRoot interfaces");
}
```

I'm pretty sure the HostOrgan's type will never be equal to an interface, so I would expect this code to always throw.

**Comment by hol353** [comment]
We should have a hall of fame for the best names of variables, classes etc. **PlantOrganFunctionalDimensionReduction**  would be on the list.

**Comment by hut104** [comment]
I'm just working a pull request to add PlantOrganFunctionalDimensionReduction2

________________________________
