### ISSUE TITLE
Need to allow TreeProxy properties for Height, ShadeModifier and NDemand to be settable from scripts

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5478]
These changes would allow APSIM agroforestry models to be more easily operated within larger whole-of-farm models in Simile etc.
It would also allow for more flexible manager rules within APSIM.

**Comment by hol430** [comment]
While you're at it, if you could refactor out the `public List<List<string>> Table { get; set; }`, that would be great.
