### ISSUE TITLE
Remove case-specific logic from Phenology

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5490]
Phenology.cs has the following text to deal with simplefruittree models (#3801)  It may be that rewinding of phenology as per grape or perrenial pastures could be used to have an interative or cycling phenology. 

        /// <summary>Called when crop is being harvested.</summary>
        [EventSubscribe("Harvesting")]
        private void OnHarvesting(object sender, EventArgs e)
        {
            //Jump phenology to the end
             if(this.Parent.Name != "SimpleFruitTree") //Unless you are a perennial fruit tree.  There must be a better way of doing this
                SetToStage((double)(phases.Count));
        }

**Comment by hol353** [comment]
@HamishBrownPFR Is this bit of code in Phenology still needed? I can't see a Harvest line in Prototypes\Orchid.apsimx. The manager script I'm looking at has this:

```c#
           if (DateUtilities.WithinDates(HarvestDate, Clock.Today, HarvestDate))
            {
                SimpleFruitTree.RemoveBiomass("Harvest");
                object NotHarvested = 0;
                zone.Set("SimpleFruitTree.Fruit.DMDemands.Structural.PartitionFraction.FruitGrowth.Fraction.NotHarvested.FixedValue", NotHarvested);
            }

            if (DateUtilities.WithinDates(PruneDate, Clock.Today, PruneDate))
            {
                SimpleFruitTree.RemoveBiomass("Prune");
                object NotHarvested = 1;
                zone.Set("SimpleFruitTree.Fruit.DMDemands.Structural.PartitionFraction.FruitGrowth.Fraction.NotHarvested.FixedValue", NotHarvested);
            }
```

This removes biomass but doesn't do a harvest so the bit of code in Phenology wouldn't be triggered.
