### ISSUE TITLE
C4WaterUptakeMethod does not seem to be used

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5493]
This class does not seem to be called from any code or JSON file

**Comment by jbrider** [comment]
It's used in Sorghum and C4Maize - it resides beneath the Arbitrator node in both.

**Comment by hut104** [comment]
OK, so it's not in a resource as yet.  That's why it never showed up.

________________________________

**Comment by hol430** [comment]
Yep, there's probably quite a bit of code out there which only gets used by prototype models.

Closing this as not a problem.
