### ISSUE TITLE
Auto indent alignment in Manager scripts

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#55]
Can we get the alignment of things in manager scripts sorting its self out nicely like it does in visual studio?

**Comment by HamishBrownPFR** [comment]
Either that or get column editing working so we can move chunks of text in one go rather than a line at a time.  It would be nice to have both

**Comment by hol353** [comment]
I can't find an easy way to do auto alignment of manager scripts. Also there is no column selection mode.

Block indenting works though. Select 1 or more lines and press tab to indent to the right or shift tab to indent to the left.

**Comment by HamishBrownPFR** [comment]
Ok.  This would have been nice but not essential functionality so we can shut this down

**Comment by hol353** [comment]
I've thought about this some more. We could write a simple formatter that formats the c# script when the user clicks away from the script - not as they are typing. This is doable.

**Comment by HamishBrownPFR** [comment]
That would be awesome.

**Comment by HamishBrownPFR** [comment]
sorry clicked to wrong button

**Comment by byzheng** [comment]
Not sure which text editor APSIMX used. A full feature text editor could be easier to format scripts, e.g. ScintillaNET (https://github.com/jacobslusser/ScintillaNET)?

**Comment by zur003** [comment]
Currently using ICSharpCode.TextEditor (some old code from the SharpDevelop project), because it's cross-platform. ScintillaNET, if I recall correctly, relies on native Windows DLLs, and hence would not be usable on Linux, Android, iOS, etc.

**Comment by hol353** [comment]
We are currently using ICSharpCode.TextEditor. 
We would need to know that Scintilla works under MONO on Linux and Mac. I'd like to see a test WindowsForms app that can run on Linux and Mac.
