### ISSUE TITLE
NANs in arbitrator

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5507]
public double TotalUptakeSupply { get { return MathUtilities.Sum(UptakeSupply); } }

This code above from BiomassArbitrationType.cs should use Uptake.Sum() however, UptakeSupply often has NAN values provided by organs.  The source of these NAN values should be investigated.

**Comment by hol430** [comment]
Which file/model did you see this in?

**Comment by hut104** [comment]
Wheat Example - as part of the speed test work.
