### ISSUE TITLE
Treatment name column doing weird stuff

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#551]
The treatment name column that is put in the report doesn't appear go be working properly.  Its column header is the name of the first treatment, the first treatment is named with what should be the column header and the other treatments get no name.  See screen shot of SCUM test.

![image](https://cloud.githubusercontent.com/assets/7295858/11194156/640da7cc-8d0f-11e5-8a6d-4509e030d85b.png)

Seems to work alright for first simulation in maize
![image](https://cloud.githubusercontent.com/assets/7295858/11194298/2686142e-8d10-11e5-942c-e4f693228e01.png)
 but not for subsequent simulations in the file
![image](https://cloud.githubusercontent.com/assets/7295858/11194343/5ce5ef44-8d10-11e5-9ead-6c861ca5c1e2.png)

**Comment by hol353** [comment]
This is because the infrastructure can't work out your treatment / values and so it doesn't write anything in particular to the report file. You get Popn and Fert columns because you are using the same report table for all experiments.

What would you like to see happen Hamish?

**Comment by HamishBrownPFR** [comment]
that was not a good example.  Baxters experiment in the potato validation is better

There is a Sow factor with levels of 14Oct, 2Nov and 23Nov and a Popn factor with levels of 2 and 4.

What would be useful is if we have a column header with the factor name (a column for sow and a column for popn) and the factor level for the given factor and the given simulation in the data table.  This seems to be back to front at the moment with the factor levels being stuck in the column header and the factor name being put into the datatable.

![image](https://cloud.githubusercontent.com/assets/7295858/11709856/d3fb8892-9f7f-11e5-8132-ca43c11c8870.png)

Simulation | Population | Fert
