### ISSUE TITLE
Optional function DltThermalTime can be removed from Root class

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5521]
There is no reference to this function in the source code.  It is referenced in PMF functions in JSON but this can be achieved without the requirement for a function in the class.  

        /// <summary>Used to calc maximim diffusion rate</summary>
        [Link(Type = LinkType.Child, ByName = true, IsOptional = true)]
        public IFunction DltThermalTime = null;

**Comment by hol353** [comment]
This is a simple one - just remove the function from root.cs
