### ISSUE TITLE
Number should be zeroed in clear method in ReproductiveOrgan

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5528]
Number is grain number.  The masses are zeroed in Clear but not the number.

**Comment by hol353** [comment]
@ric394 : Easy one: Can you zero the Number property in ReproductiveOrgan.cs Clear method as well as any other properties that aren't zeroed.

I also notice that HIReproductiveOrgan has properties that aren't zeroed in 'Clear'.
