### ISSUE TITLE
Add proper API documentation to website

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#5537]
There are quite a few tasks in apsim which are difficult to do without reading the source code (e.g. writing manager scripts, figuring out model dependencies (links), etc). The intellisense helps with this, but perhaps it's worth putting up some proper API documentation on the netlify site. We kind of have this with the params/inputs/outputs documentation, but it doesn't tell you everything - only what's in the .apsimx file. I have done some testing with a tool called docfx which can generate a static website from the documentation files (Models.xml, ApsimNG.xml, ...) which are generated when we build apsim. The result is quite readable and I don't think it would be too much work to have this automatically deployed to the website when we merge a pull request.

![image](https://user-images.githubusercontent.com/36427516/90099813-ac9fe800-dd7e-11ea-8c4e-158007614c5d.png)

**Comment by jbrider** [comment]
@hol430 Have you looked into github pages - that would be a great place for this documentation and works well with static pages.

**Comment by hol430** [comment]
Yeah github pages would do the job well, but there may be something to be said for keeping our documentation together in one place. I haven't looked into hijacking the 'deploy to netlify' step yet though, so maybe it would be easier to use gh pages (or apsimdev.apsim.info).

**Comment by hol430** [comment]
@hol353 I'm not sure how well this would work on the netlify site. Docfx cannot easily emit .md files (it can but it requires code changes to docfx) and hugo doesn't work with the .html files produced by docfx. What do you think of the suggestion to put this on github pages?

I've also tried doxygen and it does support exporting to all kinds of formats (pdf, rtf, md, even man pages), but it misses out on docfx's github integration, and I don't know how well it integrates with github pages.

**Comment by hol353** [comment]
Yeah we can try GitHub pages. If it works well we can migrate to it for all our Next Gen. doc. Maybe...
