### ISSUE TITLE
New Zealand Soil Database work

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#5539]
Soil download capability:
1. Refactor the soil download modal dialog box into a regular modeless APSIM presenter with glade view.
2. Allow place names from countries other than Australia to work.
3. Change to show all soils from all data sources and allow user to pick which ones they want to add to simulation

Changed map component to show soils if there aren't any weather sites to show.

**Comment by hol430** [comment]
@hol353 what still needs to be done here?

**Comment by hol353** [comment]
I'm waiting for the APSoil gatekeeper to OK the soils.

**Comment by hol353** [comment]
NZ soils are now in APSOIL. Closing this issue.
