### ISSUE TITLE
ExcelMultiInput not finding all files

### ISSUE THREAD

**Issue by ZhiganZhao** [APSIMInitiative/ApsimX#5548]

**Comment by hol430** [comment]
Hi @ZhiganZhao, can you upload your .apsimx and excel files?

**Comment by HamishBrownPFR** [comment]
Hi @hol430   It is the wheat validation it only seems to be reading data in from the first 3 files.  If @ZhiganZhao copies the data from the other files into one of the first 3 then it ends up in the data table and works fine but not if left as it is.

![image](https://user-images.githubusercontent.com/7295858/90460886-04f93000-e159-11ea-94ef-e8d4b667bc57.png)

**Comment by ZhiganZhao** [comment]
Hi Drew @hol430 , I am using the Wheat.apsimx under the 'Validation' folder, it seems only combine the first 3 excel files.

**Comment by hol430** [comment]
Hmm, seems to be working for me. E.g. I can see data from the palmerston file. Can you right click on the data store and click refresh? Then click away, and back onto the datastore, and type this into the row filter:

```
SimulationName LIKE '%Palmerston%'
```

![image](https://user-images.githubusercontent.com/36427516/90463215-b72afa80-e14d-11ea-9f0f-5389cfe661bd.png)

If it's still not working:

- Which version of apsim are you using?
- Do you get an error in bottom panel when you refresh the datastore?
- Have you made any local changes to code/Wheat.apsimx?

**Comment by ZhiganZhao** [comment]
Hi @hol430 , it's still not working. No error in bottom when refresh the datastore. Hi @HamishBrownPFR , can you provide other info regarding the version and local changes?

**Comment by HamishBrownPFR** [comment]
All fixed, the problems were with variable names in files and some errors in simulations
