### ISSUE TITLE
Errors compiling in Windows

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#5552]
Trying to follow instruction to copy files from C:\Work\ApsimX\DeploymentSupport\Windows\Bin I found there were two folders, Bin32 and Bin64 -- I copied the latter as I have a 64-bit OS

Tried to build solution with Visual Studio 2019 and got these errors:
1>------ Build started: Project: APSIM.Shared, Configuration: Debug Any CPU ------
2>------ Build started: Project: Updater, Configuration: Debug Any CPU ------
2>  Updater -> D:\Build\ApsimX\Bin\Updater.exe
1>  APSIM.Shared -> D:\Build\ApsimX\Bin\APSIM.Shared.dll
3>------ Build started: Project: Models, Configuration: Debug Any CPU ------
3>  Models -> D:\Build\ApsimX\Bin\Models.exe
4>------ Build started: Project: ApsimNG, Configuration: Debug Any CPU ------
5>------ Build started: Project: APSIMRunner, Configuration: Debug Any CPU ------
5>  APSIMRunner -> D:\Build\ApsimX\Bin\APSIMRunner.exe
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "ISO3166, Version=1.0.3.0, Culture=neutral, PublicKeyToken=8d672889792f7833, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
4>D:\Build\ApsimX\ApsimNG\Presenters\DownloadPresenter.cs(4,7,4,14): error CS0246: The type or namespace name 'ISO3166' could not be found (are you missing a using directive or an assembly reference?)
4>D:\Build\ApsimX\ApsimNG\Presenters\DownloadPresenter.cs(72,17,72,24): error CS0246: The type or namespace name 'Country' could not be found (are you missing a using directive or an assembly reference?)
6>------ Build started: Project: UnitTests, Configuration: Debug Any CPU ------
7>------ Build started: Project: CreateDocumentation, Configuration: Debug Any CPU ------
6>D:\Build\ApsimX\Tests\UnitTests\ApsimNG\Views\GraphViewTests.cs(179,37,179,44): error CS1061: 'ICheckBoxView' does not contain a definition for 'Checked' and no accessible extension method 'Checked' accepting a first argument of type 'ICheckBoxView' could be found (are you missing a using directive or an assembly reference?)
7>  CreateDocumentation -> D:\Build\ApsimX\Bin\CreateDocumentation.exe
========== Build: 5 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by jal-frezie** [comment]
Please ignore this for the time being, I think I may have done something foolish when setting up the directory structure...

**Comment by jal-frezie** [comment]
Yep, building OK now, I was building the wrong .sln

**Comment by hol430** [comment]
I'm re-opening this, there should only be one .sln file. I will remove the Models/ApsimX.sln which hasn't been touched in 7 years. @lie112 do you still use the ModelsAndNGSolution.slnf? I'm happy to leave it if it's being used, otherwise I'll remove it as well.

I'll also update the docs, copying files manually from DeploymentSupport is no longer necessary.
