### ISSUE TITLE
Intelisense not working for Harvestable output of AGP Species

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#5556]
In report, when we want [AGPRyegrass].Harvestable. the intelisense doesn't bring up the options available as harvestable for the AGP species (I also tested it for Tall Fescue and it didn't work).

**Comment by hol430** [comment]
Seems to be working for me. I tested on the agpasture validation set on the daily report inside radcliffe simulation. Can you upload your .apsimx file?

**Comment by mpandreucci** [comment]
Oh really? I wonder if I'm doing something wrong then

[TallFescue.zip](https://github.com/APSIMInitiative/ApsimX/files/5093378/TallFescue.zip)

**Comment by hol430** [comment]
Hmm, the intellisense is ok for me for AGPTallFescue. It's not showing suggestions for AGPRyegrass because there is no AGPRyegrass in the file. Which version of apsim are you using?

![image](https://user-images.githubusercontent.com/36427516/90577900-519a4500-e205-11ea-827a-cd58438a4409.png)

**Comment by mpandreucci** [comment]
Yeah, I didn't test Ryegrass in that simulation. If you select Harvestable and then click . you shoul then get options that I couldn't get
The Harvestable bit is working well, the problem was from there on

**Comment by hol430** [comment]
Ahh ok I'm with you, yep definitely a bug

**Comment by mpandreucci** [comment]
haha I have been having trouble expressing myself lately. Sorry
