### ISSUE TITLE
In the SoilWat documentation it mentions that '‘runon" can be provided on a daily basis from the met file or from a separate input file. Is this feature available in Apsimx? I'm interested in making soil moisture observations available using a mechanism similar to this.

### ISSUE THREAD

**Issue by pjinnes** [APSIMInitiative/ApsimX#5575]

**Comment by pjinnes** [comment]
Just noticed issue #4028 is similar and has a response from hol353 which explains can be done with a manager script

**Comment by hol430** [comment]
Hmm, Runon doesn't actually seem to be used at all in the new WaterBalance model as far as I can see. @hol353 is this correct?

**Comment by hol353** [comment]
Hmm You are correct. That's a bug. The fix is quite simple. Line 444 of WaterBalance.cs should be:

```c# 
Water[0] = Water[0] + Infiltration + Runon;
```

and it should be zeroed in ``OnDoDailyInitialisation``` method.

**Comment by hol430** [comment]
Where does it get set though? Or is this an optional parameter which can be set by the user, e.g. from a manager script?

**Comment by hol353** [comment]
The idea is that it is set from a manager. If you have multiple zones in a sim, a top level manager can take the runoff from one zone and make it runon in the other zone. This allows us to simulate overland flow down a hill slope. Very few people ever do this but it was something that was possible in APSIM 7.10.

**Comment by hol430** [comment]
@pjinnes - see above comment. Basically you can do something like this in a manager script:

```csharp
...
using Models.WaterModel
...
[Link] WaterBalance soilwat;
...
[EventSubscribe("DoManagement")]
private void ChangeRunonEachDay(object sender, EventArgs args)
{
    soilwat.Runon = 42;
}
...
```

In the current version of APSIM, this has no effect (it's ignored by the soil water model). Once #5594 is merged, a new upgrade will be released, in which runon is no longer ignored.

**Comment by pjinnes** [comment]
OK thank you for that
