### ISSUE TITLE
Scripts not compiling properly??

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#5602]
Will try my best to describe:

1. in the attached simulation there is a manager script called "LMU6PlantParameterChange"
2. there is a calculation on 148 that creates a value for LowRadCO2Factor1 = (Weather.Radn*10);
3. this works fine - see the Report and compare "Weather.Radn" and "LowRadCO2Factor1"
4. if you then change the value of "10" to "100" on line 148 this again works fine - see the Report
5. if you then change the value of "100" to "1000" on line 148 this again works fine - see the Report
6. but if you try and change the value to a lower number it keeps the previous higher value
7. only if you make your changes and exit the simulation and then run it again are the changed values used
8. I don't think it is just a calculation issue - changes to if and then statements for example did not seem to be kept - only if I saved and then opened and re-ran the simulation (though this was harder to diagnose - I thought my coding was not up to spec)

I hope that makes sense. (metfile is also in the zip file)

Cheers

**Comment by MarkLieffering** [comment]
@hol430; @hol353  I have been doing some detective work.

- changes to the radiation multiplier (in my example) are picked up if you keep increasing (or decreasing) the value - it appears you can only go one way - not up and then down (if that makes sense). So you can go

LowRadCO2Factor1 = (Weather.Radn*10);
and then change it to 100 and then 1000 - this works. But going back down doesn't

Conversely starting at 100, changes to 10 and 1 and 0.1 are picked up OK but then a change to 1000 is not picked up. However, it seems very ephemeral as sometimes it does pick up the change - can't detect a pattern though!

- interestingly, if I assign the multiplier in the script through the GUI e.g.

[Description("Radiation Multiplier")]
        public double RadMulti { get; set;}

and then use that in the equation e.g. 

LowRadCO2Factor2 = (Weather.Radn*RadMulti);

there are no issues - changes are picked up each time

HTH

**Comment by MarkLieffering** [comment]
Further to my earlier comment: after extensive testing:

in LowRadCO2Factor1 = (Weather.Radn*10); for example

using the + or - operator always works - while / and * seem to sometimes work - mostly not

**Comment by hol430** [comment]
Hi @MarkLieffering, I downloaded your attached McIntosh2.apsimx but couldn't find a manager script called "LMU6PlantParameterChange"...did you upload the wrong file or am I missing something?

**Comment by MarkLieffering** [comment]
You are right - sorry - that is the trouble with having file names that are similar

Attached is the wheat example where I have repeated the issue and also show that GUI values work OK.

Manager script TestComp, line 26 is the problematic one - using *  or / does not compile properly most of the time 
whilst + and - does

[wheattest.zip](https://github.com/APSIMInitiative/ApsimX/files/5153157/wheattest.zip)

**Comment by MarkLieffering** [comment]
Just to clarify: "Manager script TestComp, line 26 is the problematic one - using * or / does not compile properly most of the time"

It compiles but if you change the number in the equation/script that change is only picked up under some circumstance - see initial and subsequent comments above
