### ISSUE TITLE
Using photoperiod function in xypairs results in unexpected values 

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#5612]
Hi there: 
it's me on photoperiod function again. 
I find using photoperiod function in xypairs results in unexpected values. the result is not what you put in the xypairs. I tested in two different models, and hope i did not make it wrong. 
Input
![image](https://user-images.githubusercontent.com/13222562/91777625-7c908a00-ec44-11ea-9e39-7b6ae0419382.png)
Output
![image](https://user-images.githubusercontent.com/13222562/91777681-a77ade00-ec44-11ea-885a-a5a2bff00de7.png)
Junqi
@junqi108 @HamishBrownPFR

**Comment by hol430** [comment]
Could it be a bug in the linear interp code? One thing you could try is putting the x values in ascending order.

**Comment by junqi108** [comment]
@hol430 it seems ascending order do works ^-^, maybe the linear interpolation does not work well with descending order

**Comment by HamishBrownPFR** [comment]
Perhaps LinInt needs to do a sort ascending on its Pairs

**Comment by hol430** [comment]
Yeah, sort ascending on the x values seems like it would do the job, I'll get a fix out today sometime.

**Comment by HamishBrownPFR** [comment]
Will be interesting to see if that changes any models.  I wonder if anyone else have put things in descending order and not noticed a problem
