### ISSUE TITLE
Croptimiser issues

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5615]
1) Croptimiser needs to pull code down from github but the user can exceed the rate limit from github causing installation to fail.
2) RTools needs to be installed but installation process is different depending on R version
3) When installing github packages can fail when there is a cyclic dependency

**Comment by hol430** [comment]
When passing simulation names and observed data to CroptimizR, we need to limit the simulation names to only those present in the observed data.

**Comment by hol430** [comment]
To be implemented:

- remove option for output path. always copy results to same directory as .apsimx file
- actual english in crit function description
- fix tolerance criterion tooltip
- graph vary by on numeric column
- put initial values next to final values variable-wise in datastore
- bar chart shows repetition + .4 when clicking on a bar
- add column for optimal-ness (bool)
- create docs page in netlify site
