### ISSUE TITLE
Updating resource files

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5619]
There needs to be a quicker way for developers  to submit updated resource files when a file converter is written.

**Comment by hol430** [comment]
I can tweak the tool in the GUI so that it's easier to use (e.g. just rename it to "upgrade resource files" or similar and have it do everything automatically, no need to choose a folder/file). Or I could add a batch script. Which would be more convenient for you guys?

**Comment by hol353** [comment]
Go with your first suggest. Have it fully automatic, no dialog box. It just changes all resource files.

**Comment by hut104** [comment]
Does anyone other than developers need this?  If not, perhaps it could be taken out of the GUI.

________________________________

**Comment by hol430** [comment]
The option only appears if the gui is compiled in debug mode.

**Comment by hut104** [comment]
The just tell it to update all resource files.

________________________________

**Comment by hol430** [comment]
Yeah it seems like the best solution, that's what I"ve done in #5623.
