### ISSUE TITLE
Downloaded soils missing link for NO3 and WheatSoil

### ISSUE THREAD

**Issue by pjinnes** [APSIMInitiative/ApsimX#5670]
Attempting to run wheat yield simulations at Temora, Lake Cargellico, Yanco by running Wheat.apsimx but downloading local soils to replace the example (Darling Downs) soil.
All downloaded soils get error: 
"System.Exception: Cannot find a match for link NO3 in model .Simulation.Field.Fertiliser"
If I copy and paste Nutrient node from the Darling Downs soil into downloaded soils this error disappears. 

However, for soils other than the Synthetic Soil Derived from ISRIC SoilGrids, now get error:
" System.Exception: Cannot find a soil-crop parameterisation for WheatSoil"
If I copy and paste a WheatSoil to the Physical node then this problem is resolved.

Is this how it should work? should this be documented?

![image](https://user-images.githubusercontent.com/68268897/93704267-38b1e600-fb5b-11ea-8da8-8f5a186bcbb7.png)

**Comment by hol430** [comment]
It looks like the soil downloader is attempting to add SoilN instead of nutrient. @hol353 is this intentional?

**Comment by hol353** [comment]
Nope. It should add Nutrient. I wouldn't be surprised if the importer (old to new APSIM) did the same thing.

**Comment by hol430** [comment]
@pjinnes if you upgrade to the latest version and try downloading some soils, nutrient should be automatically added (so you should no longer get the "Cannot find a match for link NO3" error). I'm not sure if we can automate the addition of addition of a WheatCrop, although I could be wrong. Perhaps someone else can comment on that.

**Comment by pjinnes** [comment]
@hol430 downloaded the latest version but still don't see that nutrient node when I loaded a synthetic soil
![mungindiSoil](https://user-images.githubusercontent.com/68268897/95451051-f8ec5a80-09b2-11eb-965b-3922e11adef1.JPG)

**Comment by hol430** [comment]
Hi @pjinnes- there was a problem with the build system last week, and the latest version didn't contain the bugfix. I think if you ugprade to latest version again (should be 2020.10.16.5740) it should be fixed.

**Comment by pjinnes** [comment]
all good now, thanks
