### ISSUE TITLE
Incorrect Latitude in Fodderbeet Test Set met files

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5677]
The Fodder Beet test set includes a series of met files which all have a latitude of -43.7
The correct latitude AND longitude should be included in all test set met files.

The location in the met file for hobart lies off the coast of tasmania,

**Comment by hol430** [comment]
I note also that many of these met files are duplicated in the various test sets (e.g. we have 12 copies of lincoln.met). Sure, disk space is cheap and they ought to compress well, but it does seem vaguely wasteful...

**Comment by hut104** [comment]
Hhhmmmm. I now see that all the met files have the same latitude and longitude.
These sites are spread across New Zealand.

**Comment by hol430** [comment]
Do we want to try and find out the actual coordinates of the weather stations, or do I just look up the town/place and plug in the coordinates of the middle of town? I guess the second option while not perfect would still be an improvement over what we have currently.

**Comment by HamishBrownPFR** [comment]
Kick this one back to the developers of the test set

**Comment by HamishBrownPFR** [comment]
@RobZys are you and Edith able to fix up the Lat and long in the met files for the test set

**Comment by RobZys** [comment]
Just spoken to Edith, we will co-ordinate this
