### ISSUE TITLE
Folders in Plant Arbitrator

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5688]
All instances of plant arbitrator seem to now have folders of examples within them.  We don't tend to do this.  I'd imagine that these should sit within the example toolbox places, but not in real instances of models we distribute.

I'm not sure how they got into our resource files, but it is most probably due to a converter at some point.

**Comment by hol430** [comment]
I thought we discussed this in March and decided it was how we wanted this to be set up. I don't really recall the details though...@jbrider might remember. I guess it could all be hidden away as a resource model, which is probably worth doing so people don't start changing them and breaking their simulations.

**Comment by hut104** [comment]
I might be missing something.  So does the maize model use all the methods in this image? 
![image](https://user-images.githubusercontent.com/11881178/94226085-07aa2a80-ff3a-11ea-8fa4-67bfdf36d278.png)

**Comment by jbrider** [comment]
Sorry @hut104 - I saw empty examples and didn't realise what you meant.
That's the result of removing the Base Arbitrator class - it extracted the methods out to classes.
Yes, Maize uses them all - sorghum uses less, but different ones for N.

**Comment by hol430** [comment]
Yes they are all used, if you look in the code, you'll see that there is code behind each of those nodes.

**Comment by hol430** [comment]
What action is required here?

**Comment by jbrider** [comment]
They probably need an icon so they look legit.
Something that shows that they're a component of the arbitrator would be
good.
My first thought was a gray version of the arbitrator's icon - but that
probably won't work if they're disabled.
