### ISSUE TITLE
Multiple simulations won't run in GUI. 

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#569]
Progress bar throwing fatal error whenever more than one simulation is run.  This is because the percent field is negative (see below)

![image](https://cloud.githubusercontent.com/assets/7295858/11669546/1f66d38c-9e62-11e5-82a1-94c2471d9f18.png)

This is being caused by jobManager.JobCount returning a number that is 1 greater than numSimulationsToRun

![image](https://cloud.githubusercontent.com/assets/7295858/11669607/84ab8652-9e62-11e5-96c4-d0cb627513e6.png)

I exceed my depth here.

**Comment by hol353** [comment]
This is fixed in JobManager.cs in APSIM.Shared. I reverted the change I made the other day. Do a pull on APSIM.Shared.
