### ISSUE TITLE
Soil and met download option

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#5690]
1. When a soil is downloaded from a lat and long search, the Nutrient model needs to be added.

2. When downloading a met from SILO or NASA/Power, my laptop screen was too small to see and use the OK button, and the dialogue box could not be dragged higher for that use, even if I decreased font size in the GUI.

**Comment by hol430** [comment]
@hol353 what will be involved in adding nutrient to the downloaded soils? Is it as simple as creating a new nutrient object, setting the resource name, and adding it to the soil?

**Comment by sme016** [comment]
I am not sure of the detailed steps you’ll need do to achieve this, but in the end you want the soil that’s downloaded to look any other soil in APSIMx that we work with, i.e. have the ‘Nutrient’ node included (probably this is the Nutrient.json file in Resources). I don’t think anything else needs to change.

A similar job that I haven’t logged would be to consider replacing the SoilNitrogen with Nutrient in the Soil node of the StandardToolbox.

Thanks

**Comment by sme016** [comment]
Another issue for downloading soil from the SLGA is that there are two 'Initial water' nodes included rather than one.

**Comment by hol430** [comment]
Didn't mean to close this, there's still the issue of being unable to resize the dialog.

**Comment by sme016** [comment]
Another issue related to the downloadable soil file from SLGA : 
In SoilWater, slope is meant to be in the range 0-1, but I notice that sometimes slope values of 8, for example, are provided. What happens then? Does the script used to generate the soil file from SLAG need to be modified? 

For example, at lat -35.33 long 148.92, the ISRIC slope is 0,5, but the SLGA slope is 8.63724

**Comment by hol430** [comment]
Interesting, here is the comment from the code:

> DSG: The units of slope are metres/metre.  Hence a slope = 0 means horizontal soil layers, and no lateral flows will occur.
>
> A slope = 1 means basically a 45 degree angle slope, which we thought would be the most anyone would be wanting to simulate.  Hence the bounds 0-1.  I still think this is fine.

So I guess a slope of 8 would technically be possible but it would be rather steep. @hol353 any thoughts? See [this soil](https://www.asris.csiro.au/ASRISApi/api/APSIM/getApsoil?longitude=148.92&latitude=-35.33) for reference. Could it be a units mismatch?

**Comment by sme016** [comment]
Yep – I saw that too.

8 would be almost waterfall grade – so I definitely think there is a unit mismatch, or more likely an incorrect conversion, of slope in SLAG (probably % or degree) to slope in APSIM (m/m).

But also, what was APSIM doing when it was the slope value of 8, as it might be the key to some soil water simulation problems I have had lately?

Thanks for getting onto it.

P

**Comment by hol353** [comment]
Slope is not used in Next Gen simulations except if you have a SlopeAndAspect model in your sim (which you almost certainly won't - unless you added it). The water balance certainly doesn't use it. Old APSIM uses it in the calculation of erosion, which we don't have in Next Gen. I'm unsure of units.

**Comment by zur003** [comment]
In Next Gen, slope is an attribute of the Zone, not of the soil, and units are degrees.

**Comment by zur003** [comment]
According to https://www.clw.csiro.au/aclep/soilandlandscapegrid/ProductDetails-LandscapeAttributes.html, SLGA expresses slope as %, so unless Ross's script is doing a transformation, that's what you'll get. So where does this leave things? It sounds like slope might be expressed as ratio, percentage, or degrees. depending on the source. At the moment might not be much of an issue, since as @hol353 pointed out, it's not used in most models. However, I suspect Next Gen will want an erosion model someday. This should be sorted out before that day arrives.

**Comment by hol430** [comment]
Hmm, I can't see a SlopeAndAspect model anywhere in the source code. I do see a SlopeEffectsOnWeather - is this what you're referring to @hol353?

> In Next Gen, slope is an attribute of the Zone, not of the soil, and units are degrees.

Looks like there are actually two slopes here - there's the one in zone, which is in degrees, and there's the one in WaterBalance, which is a proportion (m/m). The one in zone is used by SlopeEffectsOnWeather. The one in WaterBalance is actually used in lateral flow calculations, which is consistent with the comment I pasted above.

**Comment by sme016** [comment]
So, for WaterBalance, it looks as if slope % from SLGA needs to be transformed to m/m for SoilWater in the download script.

Thanks for the help.

**Comment by hol353** [comment]
Yes, I meant SlopeEffectsOnWeather. It's a model that changes weather data during the simulation depending on the slope you are on and the facing aspect of the slope.

**Comment by zur003** [comment]
So how should this be handled? I don't see any good reason to have slope in two different places, unless there is a need for a distinction between slope at a point and slope over a broader area (SGLA seems to allow for this). Is it better to regard it as a property of a Zone or of a Soil? I'll argue that it's better placed in the Zone, but could be persuaded otherwise.  However, that means that the lateral flow logic for soil water balance should be changed to fetch a slope value from the Zone, not from WaterBalance. And what units are best? Do we stick with degrees, as that is apparently what SlopeEffectsOnWeather is already using? Or proportion as used in the lateral flow calculations?

**Comment by sme016** [comment]
Your reasoning appears sound to me.
Degrees or % of slope are more commonly used than proportion.
Thanks

**Comment by hol353** [comment]
We don't want slope in two places. Slope should be in zone. We can change SoilWater. I probably would prefer degrees as the units.

**Comment by rcichota** [comment]
I concur with Dean, having slope in one place (zone) is best and I would think degrees is the most common/easy unit.
One other related parameter used in SlopeEffectsOnWeather is the aspect angle, should it be also a property of zone? (I think so).

**Comment by hol353** [comment]
Aspect is already a property of the zone.
