### ISSUE TITLE
Importing Aspim Classic file doesn't create Irrigation

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#5696]
After importing an Apsim classic file, running NextGen results in "_Cannot find model:[Irrigation]"

**Comment by jbrider** [comment]
Fertiliser didn't come across either.
The sowing script is also commented out so the crop doesn't sow.

**Comment by hol430** [comment]
Manager scripts will need to be rewritten, as the manager infrastructure is all different between old vs new apsim. The others definitely sound like bugs though. Could you upload your .apsim file?
