### ISSUE TITLE
　Using SWIM3 in ApsimNG

### ISSUE THREAD

**Issue by ks265** [APSIMInitiative/ApsimX#5709]
I want to use SWIM3 in ApsimNG and I copied and pasted "Swim" in the old APSIM file of "Continuous Wheat with SWIM3".
Then, there is the error of "Could not find parameters for solute called NO3." in the run of the Simulations.
I can not understand how to modify the Simulations.

Please teach me how to use SWIM3 in ApsimNG.
If there are some examples, please give me the information.

Thank you,

Kazuhito SAKAI

**Comment by sarahcleary** [comment]
@m8harrison - do any of your videos cover this aspect?
Links to Next Gen training videos  - https://www.apsim.info/support/videos/

**Comment by m8harrison** [comment]
Hi Sarah, sorry none of my training videos address this. I had a look and got the same error with SWIM – comparing the old SWIM to the new it look like the component called ‘SWIMSoluteParameters’ is missing from APSIM NG? I had a look at the options for this but could not see it.

**Comment by hol430** [comment]
Well officially there is no SWIM in ApsimNG yet, it's not finished, which is why there's no examples/documentation. I think there's a development/experimental version somewhere, but I'm not sure I'd recommend using it.

**Comment by sno036** [comment]
@ks265 - I am working with SWIM at the moment and it is a fair way off being ready for usage. I suggest you use SoilWater. Or is you really need Richard's equation then APSIM Classic would be a better option.

**Comment by ks265** [comment]
For All - Thank you for your kind responses.  I want to simulate the soil moisture movement in a sugarcane field.  I have been using Hydrus. However, Hydrus can not calculate plant growth. (Users decide the growth regardless of a climate condition.)
Therefore, I want to use SWIM. I will try to use APSIM Classic with SWIM. 
Thank you.

**Comment by sno036** [comment]
Not stale
