### ISSUE TITLE
Weirdness in the model description screens in the UI

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#5724]
Something has gone astray with the model descriptions as displayed in the UI. Pasted an example for SoilArbitrator below.

![image](https://user-images.githubusercontent.com/12176269/95532818-03a00180-0a3e-11eb-8676-f8cd37c1b11c.png)

**Comment by hol430** [comment]
This is probably due to my work on #480 which we never followed up on. Should be easy enough to fix once #5720 is merged.
