### ISSUE TITLE
LayerStructure could be more user friendly

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#5726]
OOhhh - it seems that I am not allowed to use "!" in a title! The original title was "LayerStructure !user-friendliness"

LayerStructure could do with a change of a label at the top to "Thickness (mm)" to remind users of the units. It could also do with an adder upper to total the sum of all the layers.

**Comment by hol430** [comment]
Does the LayerStructure work? Neil mentioned in #1785 that it doesn't do anything.
