### ISSUE TITLE
The blank manager is too blank to be helpful

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#5728]
I think that the blank manager (i.e. Add model version) is perhaps just a little too blank. Your thoughts? How about something like below as a starter for users? I’d add it myself but I can see where to do that.

using Models.Climate;
using APSIM.Shared.Utilities;
using Models.Soils.Nutrients;
using Models.Soils;
using Models.PMF;
using Models.Core;
using System.Xml.Serialization;
using System;
using Models.Soils.Nutrients;
        
namespace Models
{
    [Serializable] 
    [System.Xml.Serialization.XmlInclude(typeof(Model))]
    public class Script : Model
    {
        [Link] private ISummary summary;
        [Link] private Clock Clock;
              
        //User inputs for the Parameters tab
        [Description("Descriptive text for the UI")] public double HereIsAParameterFromTheUI { get; set; }

        //Not on the UI but available to other models
        [XmlIgnore] public double HereIsAParameterNotOnTheUI { get; set; }

        //Not on the UI and not available to other models
        private double HereIsAPrivateParameter { get; set; }
    
        [EventSubscribe("StartOfSimulation")]
          // code executed only at the start of the simulation
        private void OnStartOfSimulation(object sender, EventArgs e)
        {   
        }
             
        //Code executed pretty much at beginning of each day before the other models do their thing
        [EventSubscribe("DoManagement")]
        private void OnDoManagement(object sender, EventArgs e)
        {
        }
        
        //Code executed at the end of each day after the other models do their thing but before reporting
        [EventSubscribe("DoManagementCalculations")]
        private void OnDoManagementCalculations(object sender, EventArgs e)
        {
        }

    }
}

**Comment by hol430** [comment]
Sounds like a good idea. Do we really want the example properties though? They seem like they would fit in better in a tutorial/example manager somewhere.
