### ISSUE TITLE
Group collaboration

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5730]
I am seeking opinions on the best way forward with user group collaboration/discussion that I am sure the APSIM initiative have been discussing

I am now directing the growing CLEM userbase to use the Git repo to report issues (bugs and UI issues/suggestions relating to code for now), but many are overwhelmed by Git and revert to email questions to the team that go unrecorded. The detailed posts in issues are also very technical in nature and the interface is more advanced/expert than needed. It is also difficult to search for information on closed issues (I know how to do it, but it's not real intuitive and polished). 

I have looked at the ResearchGate site, but it doesn't allow for separation of users very well, and I wouldn't want to potentially swamp this information with CLEM based requests. It also doesn't allow for searching within questions of a specified group as far as I can tell. I could create a CLEM user group of ResearchGate, but not sure it's quite what I am after.

I don't have the time to build a FAQ blog post component to add to the Wordpress-based APSIM website.

I was looking for group collaboration options capable of allowing group discussion that builds FAQ, important news and updates and also perform the task of replacing a group email list (with self subscribe and unsubscribe capabilities). This would share the workload between the developers (me) and the user community to answer questions. I assume this is what the Git issues page or ResearchGate group is supposed to offer and is working for everyone to date.

Options like Yammer (or Teams that has been suggested by CSIRO IT) fit this purpose and allow external collaboration but these are commercial packages. I feel the level of general, basic, CLEM discussion will muddy the issues repo when getting very basic new user "how do I add a model" questions. I can see a Yammer or the like "Users group" for each model (like the labels in Git) would be worthwhile. It seems CSIRO yammer or Teams I could create is not very external facing and wouldn't really be correctly branded CLEM User Group. I am not sure if one of the Initiative partners could host an APSIM Yammer, that could have sub groups created. I believe this would be a very useful tool and leave GIT for science and code related (technical) issues.

It could be that the CLEM user base is quite different to other modellers in APSIM.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel

**Comment by hol353** [comment]
What about creating your own CLEM GitHub repo somewhere and just use the GitHub issues system? No need to commit any code although it might be useful to commit some docs, examples, tutorials etc. This avoids CLEM uses seeing the complexity of the  APSIM repo.

**Comment by sarahcleary** [comment]
@lie112  - did you decide on a mechanism/solution?

**Comment by lie112** [comment]
Haven't found a solution yet. I thought there would be much better tools available for this. 
I have been passed from CSIRO IT to social communication, but haven't heard anything from them.
What are you using for group email list management that provides the legal requirement that users can unsubscribe at any time. The CSIRO system does not allow external participants and I don't want to use a free mailchimp account.
I have taken on board the suggestion by @hol353 to use Git, but it's not really suitable for the intended audience or style of posts and everyone has to be a git user to collaborate.
I thought I'd bring this up with APSIM in case others were also struggling to find a way of collaborating with increasing userbase, but happy if this is closed after the discussion at the last meeting.

**Comment by sarahcleary** [comment]
@lie112  - the www.apsim.info website allows people to receive updates - so opt in/opt out for any new posts.  We can't 'see' this list.  We also utilize the researchgate project which people can 'join'.  So far hasn't seen the engagement I had hoped but also 'pushes' out news/updates.  We do have an opt in for correspondence when downloading APSIM - but haven't used list, yet.  As discussed, we utilise GitHub as we have made a decision to utilise a single platform.   It's relatively easy to search which helps and hopefully makes it a useful resource long term.

**Comment by frank0434** [comment]
What about the [GitHub discussion feature](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-team-discussions)
It was designed for community-level discussion whether private or public. 
Non-git user can still join the discussion and contribute.
