### ISSUE TITLE
What does "Undo" do?

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#5734]
Used to text editors, I expect it to reverse changes I recently made to the script of a manager module. But instead it just seems to change focus to the top level without affecting the model at all.

**Comment by hol430** [comment]
Yeah the undo button doesn't really integrate with the manager script text editor, which has its own undo-redo buffer which is usable via ctrl+z/ctrl+y. Once you're finished editing your manager script, and you click onto another node in the tree, the changes are saved to the manager model and should be undoable via the undo/redo buttons. The undo/redo buttons at the top of the screen should undo all other changes you can make. Clicking on a node counts as a change for some reason though, so clicking undo can sometimes do unexpected things. Possibly related is #5692.
