### ISSUE TITLE
AgPasture/SimpleGrazing outputs

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#5743]
I have a couple of questions related to the AgPasture and SimpleGrazing outputs. I am using a modified AgPasture example simulation with a ryegrass/white clover sward. The outputs for ryegrass [AGPRyegrass].AboveGroundWt,  [AGPRyegrass].AboveGround.Wt and [AGPRyegrass].AboveGroundHarvestable.Wt with the same ones for white clove. The SimpleGrazing outputs of interest are [SimpleGrazing].GrazedDM, [SimpleGrazing].PostGrazeDM and [SimpleGrazing].PreGrazeHarvestableDM. 

Sample output from a single grazing event with the residual set to 1500:

[SimpleGrazing].PostGrazeDM = 1509.702
[AGPRyegrass].AboveGroundWt (plus the clover component of course) = 1608.402
[AGPRyegrass].AboveGround.Wt (plus the clover component) = 1540.218
[AGPRyegrass].AboveGroundHarvestable.Wt = 1390.218 (I know why this is lowest)

What I am having trouble with is that the SimpleGrazing residual output ([SimpleGrazing].PostGrazeDM) seems to lie somewhere between [AGPRyegrass].AboveGround.Wt and [AGPRyegrass].AboveGroundHarvestable.Wt but never between [AGPRyegrass].AboveGround.Wt and [AGPRyegrass].AboveGroundWt

So I guess my question is – what is the “correct” residual to use and/or are things being calculated properly?

([SimpleGrazing].PostGrazeDM) seems to most closely aligned to [AGPRyegrass].AboveGround.Wt – the difference is possibly to be related the daily pasture growth rate. Are there temporal reporting issues that cause the discrepancy? However, the difference is not always positive and between the two in the simulation I am working on ranges from about -10 to 30 across about 500 harvests (average is about 1)

Also, [AGPRyegrass].AboveGroundWt and  [AGPRyegrass].AboveGround.Wt are different (after multiplying the latter by 10 to get to kg/ha) with the latter being lower – why is this – shouldn’t they be the same? The differences in the daily values in the simulation I am using range from 2 to 300 (always positive) with a marked seasonal trend – lowest in winter, highest in summer.

I hope this makes sense! Simulation is attached.

Cheers

Mark
[aptest.zip](https://github.com/APSIMInitiative/ApsimX/files/5381216/aptest.zip)

**Comment by lamonteiro** [comment]
Hi Mark,
I also been facing similar troubles in AgPasture as well. 
Do you have some idea how I suppose to specify a date for harvest?

take care,

LM

**Comment by MarkLieffering** [comment]
Hi - are you using SimpleGrazing to control the grazing of AgPasture? There is an option for "Flexible" grazing parameters whereby you can specify conditions when to graze. I was thinking that you could specify the exact dates when to graze. However, when I tried to specify Clock.Today = 1/1/1983 for example it throws an error:

Cannot compile expression: Convert.ToDouble(Clock.Today = 1/1/1983)
Line 19: Property or indexer 'Models.Clock.Today' cannot be assigned to -- it is read only
Line 19: Cannot implicitly convert type 'int' to 'System.DateTime'

@hol353  - looking at the code am I correct that the expression for flexible grazing can only be a string?

Alternatively there is an grazing parameter option "TimingControlledElsewhere" which I believe enables you to write a manager script to control grazing times but I have no experience with this sorry.

Cheers

**Comment by mpandreucci** [comment]
Leonardo (@lamonteiro ) you can specify dates by using an operations component using the 'TimingControlledElsewhere', as Mark said.

**Comment by MarkLieffering** [comment]
Like this 1975-06-14 [SimpleGrazing].GrazeToResidual(1000)

**Comment by hol353** [comment]
@MarkLieffering your flexible condition should be something like:
```
Clock.Today == new DateTime(1983, 01, 01)
```

A bit ugly! Using operations would be nicer.

**Comment by MarkLieffering** [comment]
Thanks @hol353 - very ugly if you want to put more than a couple of dates:

Clock.Today == new DateTime(1996, 01, 01) | Clock.Today == new DateTime(1998, 01, 01) 

 TimingControlledElsewhere and Operations would be the way to go.
