### ISSUE TITLE
Ability to modify model constants for a single sim (similar to inserting an ini node in APSIM Classic)

### ISSUE THREAD

**Issue by JodyBig** [APSIMInitiative/ApsimX#5748]
To test process constants it would useful to be able to modify them within an individual sim, in a similar way as inserting a ini node in APSIM Classic.
For example:
As I understand, currently, to modify the n2o fraction from nitrification you need to drag a Nutrient node into a Replacements node which impacts on all simulations. So the work around currently would be to have separate *.apsim files.

**Comment by BrianCollinss** [comment]
How about using Factors, or manager scripts that manipulate the parameters of interest?

Yet, it would be handy if the scope of Replacements could be limited to their parents so they could be put under individual simulations or folders.

**Comment by hol353** [comment]
As pointed out by @BrianCollinss you can create a factorial of values of n2o fraction.
