### ISSUE TITLE
Simulating the effects of claying in WA using WEIRDO

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#5752]
I'm trying to simulate the effects of claying, particularly in relation to water repellency, in WA in APSIM Next Gen in WEIRDO please. 
Both APSIM Next Gen and WEIRDO are very new to me, but my understanding is that the current MRSpline node does not fit water characteristic curve so I tried to compute Xf and Cf using R. 
I fitted a five-point monotonic cubic Hermite spline by assuming an air-entry water potential head of 10, to the following data
SAT water.contenthBub   DUL   LL15  AirDry
0.46   0.46                        0.115 0.051  0.025
![image](https://user-images.githubusercontent.com/63323287/96211649-3e62e600-0fb8-11eb-8a69-b93a5b599f25.png)

I'd like to ask:
1. if there is any rule-of-thumb on the air-entry pressure head if it needs to be assumed;
2. whether the spline fitted is sensible or there is further adjustment that needs to be made to the spline; and 
3. how is Xf determined from the spline please. 

Thank you very much! 

@HamishBrownPFR @hol353

**Comment by Chloe0317** [comment]
Further to my question, in Huth et al. (2012) SWIM3: Model Use, Calibration and Validation, KDUL was assumed a notional value of 0.1 mm/day, I tried it using water content at SAT (0.4), DUL (0.08), LL (0.025), and Ks (500), for the deep sand APSoil profile: Deep sand_unripped (Esperance No452), it will result in a Kmatrix of 1.3E7, which doesn't make sense.  

Brown et al. (2018) stated that Xf and Cf are coefficients in relation to the two-region model of hydraulic conductivity described in Huth et al. (2012), I thought it was referring to b and P in Huth et al. (2012) though I've tested it and don't think this was the case. 

@HamishBrownPFR @hol353 is another model used for the fitting of the hydraulic conductivity curve and deriving Xf and Cf please? If yes, could you let me know what model was used and how can I drive Xf and Cf please?

If it is the two-region model described in Huth et al. (2012), should I further adjust kdul to a nominally small value, say 10^-8? What do Xf and Cf refer to please?

**Comment by sarahcleary** [comment]
@Chloe0317 - are you happy for this issue to be closed?
