### ISSUE TITLE
help me finding chicory genetic coefficient in  apsimx

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#5758]
How can i find plant gentic constant in apsimx?

**Comment by masooandy** [comment]
Is there anybody wanna help?I am sure this would be a question of many researchers?

**Comment by BrianCollinss** [comment]
You should check the folder **ApsimX\Models\Resources**. There is a file names **Chicory.json**.

**Comment by BrianCollinss** [comment]
This site would be helpful: https://apsimnextgeneration.netlify.app/modeldocumentation/

**Comment by masooandy** [comment]
> You should check the folder **ApsimX\Models\Resources**. There is a file names **Chicory.json**.

thank you @BrianCollinss for considering my issue .all i have in my apsimx folder is this 
![Captureeee](https://user-images.githubusercontent.com/45214463/97112443-95279880-16f9-11eb-914e-3ea22e6feae3.PNG)
 idont have models folder and apsimx is working well

**Comment by peter-devoil** [comment]
It's in version control, not the installation: https://github.com/APSIMInitiative/ApsimX/blob/master/Models/Resources/Chicory.json

It used to be that you could copy this file, rename it to a .apsimx extension and open in the GUI - but I get an incomplete display accompanied by strange messages about missing "link storage in PropertyPresenter" with my (slightly out of date) source tree...

**Comment by hol430** [comment]
You can copy the contents of the file and paste them into the gui. Or just right click -> add model -> chicory, it will have the same effect.

**Comment by masooandy** [comment]
this is really **`confusing`**. after upgrading to version 5778 .in Resources folder there is only folder  World  .
how can i find model folder and  its containers ?crop properties files (cultivars and so on)?
if they are missing how apsimx works without error ? 
is it a bug?
whats going on here?
 its 3:30 AM here and i am still working.

**Comment by peter-devoil** [comment]
When you install via the [installer](https://www.apsim.info/download-apsim/downloads/), you get a compilation of the [source](https://github.com/APSIMInitiative/ApsimX) where resources are bundled inside. Use a [git client](https://git-scm.com/download/gui/windows) to get the source.

**Comment by masooandy** [comment]
My problem solved because of your support and consideration @peter-devoil @BrianCollinss @hol430 .I wanna thank you .hopfully have chance to make it up to you all.
