### ISSUE TITLE
Should find related models methods ignore disabled models by default?

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5775]
Should all Find related models methods (FindAncestor, Sibling, Child, Descendant) ignore disabled (Enabled = False) models by default?
I believe some of the previous implementation of these did ignore disabled models as CLEM functionality appears to have changed. Currently, it seems to be the users responsibility to filter for enabled models after the method call and it would be great to move this .Where(a => a.Enabled) into the method code.

The default (), <type>(), (string Name) and <type>(string Name) calls could ignore disabled models
A second call (bool), <type>(bool), (string Name, bool) and <type>(string Name, bool) could allow the user to determine whether disabled models should be included where bool is include disabled. The defaults just call these full implementations with (true).

**Comment by hol430** [comment]
> I believe some of the previous implementation of these did ignore disabled models as CLEM functionality appears to have changed.

Is the changed clem functionality occurring at simulation runtime, or in the GUI? When a simulation is run, all disabled models are removed from the tree - so at simulation runtime it wouldn't matter if these functions filter out disabled models or not. I'm also not sure that these functions ever filtered out disabled models anyway. I had a quick look through the git history and couldn't find any references to the enabled property in Apsim.cs. They certainly didn't filter on Enabled as of Jan this year ([for reference](https://github.com/APSIMInitiative/ApsimX/tree/df4989a2ef0a9434e487a8228ccacc8485ab4b45/Models/Core/Apsim.cs)). It's possible they were changed more recently, but I couldn't find any evidence of this in the logs.

**Comment by lie112** [comment]
It was UI where this change was noticed.
Good to hear that it isn't affecting any runtime, even thought I have placed enabled filters everywhere. 
If the disabled models are removed at runtime, is there any reason people would want to list the displayed models in the user interface. Could we simply ignore all disabled models in the relationship methods?

**Comment by hol430** [comment]
People want disabled models to appear in the UI-  otherwise they would delete the models instead of disabling them. So I think we need to continue to show disabled models in the UI. I think this issue may be more general than accounting for disabled models though - in various places we have hacks to check if the model is being overriden by replacements, or by factors in an experiment. Perhaps the explorer presenter could deal with this somehow when calling presenter.Attach(). E.g. if it generates the simulation as it would be run (e.g. replacements applied, disabled models removed, ...) and then passes in the appropriate model from the simulation to be run.

**Comment by lie112** [comment]
I was thinking about this the other night and agree with you (just never got to responding) and realised that yes, the disabled values need to be provided by model relationship methods for use in UI and where user needs to know all models provided, even those disabled. I am happy to place all my multitude of .where(a => a.Enabled) filters throughout the code for working with UI, but an optional bool switch in the relatives Methods to specify whether disabled are included or not would be useful with the default empty call falling to true and provide cleaner code, with the knowledge that disabled models do not exist in the running simulation.

**Comment by hol430** [comment]
I'm kind of reluctant to add even more functions into this class, which already contains a lot, and this one doesn't really add any new functionality. Perhaps an extension method would be a good compromise here?
