### ISSUE TITLE
Is SWIM compatible with oil palm crop module?

### ISSUE THREAD

**Issue by Akram-tec** [APSIMInitiative/ApsimX#5784]
Hi, I have run OP crop module with SoilWat but when I use SWIM it shows the following error: soil properties of the crop are not defined for the given crop in water node of SWIM. However, I have specified the crop properties in crop manager of water node. Any suggestions?

**Comment by hol430** [comment]
It appears that oilpalm is incompatible with the soil arbitrator because the uptake methods haven't been implemented yet on oilpalm. I'm not sure why this might be the case (@hol353?), but swim isn't released in next gen anyway, so you might be better off using old apsim for this simulation.

**Comment by Akram-tec** [comment]
Thank you for the reply. I have used the old apsim also; same issue! It seems that Oilplam is not compatible with SWIM.
