### ISSUE TITLE
Can the soil hydraulic parameters be changed

### ISSUE THREAD

**Issue by Starkeng** [APSIMInitiative/ApsimX#5785]
Hydraulic parameters of top soil such as bulk density, field capacity, saturated and hydraulic conductivity are readily affected by frequent field measures (tillage or short-term crop rotation). And I am trying to simulate the impact of hydraulic parameters on crop biomass. 
I’d like to ask:
(1)	the parameters can be outputted and changed daily or per tillage or per rotation in continuous simulation? or can we improve it by embedding the empirical formulas based on our multi-year field datasets into model? Hao do the APSIM initiative address or consider this problem?  
(2) could I finish the simulation easily in APSIMX? How about using manager scripts?
(3) do I have to operate source code? What should I do first (Programming is very new to me)?
Would you mind giving me some good advice?  
Thank you very much.

**Comment by hol430** [comment]
> the parameters can be outputted and changed daily or per tillage or per rotation in continuous simulation? 

Yep, these parameters can be outputted at any of these times by using the Report module. There's documentation for report in the tutorials section on [this page](https://apsimnextgeneration.netlify.app/modeldocumentation/).

> can we improve it by embedding the empirical formulas based on our multi-year field datasets into model?

As far as I know, this isn't really possible without changing the source code

> could I finish the simulation easily in APSIMX? How about using manager scripts?

It depends on which crops you need. Also, swim isn't released yet in next gen so if you need swim then you'll probably need to use classic. There's documentation for manager scripts on the same page I linked above

> do I have to operate source code? What should I do first (Programming is very new to me)?

We have guides for [getting started with](https://apsimnextgeneration.netlify.app/contribute/sourcetree/getsource/) and [compiling/running](https://apsimnextgeneration.netlify.app/contribute/compile/) the code.
