### ISSUE TITLE
@peter-devoil and/or @jwhish?

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#5786]
@peter-devoil and/or @jwhish?

_Originally posted by @sarahcleary in https://github.com/APSIMInitiative/ApsimX/issues/5120#issuecomment-633764322_

**Comment by masooandy** [comment]
Hi folks 
Could you help me finding  chicory cultivar coefficients or any other plants in apsimx?
Kindly regards

**Comment by masooandy** [comment]
Hi folks 
Could you help me finding  chicory cultivar coefficients or any other plants in apsimx?
Kindly regards

**Comment by BrianCollinss** [comment]
@masooandy it'd be good to follow the forum convention for the title of the posts/issues so everyone would know what it is about without reading them. Cheers.

**Comment by masooandy** [comment]
@BrianCollinss you can found it here https://github.com/APSIMInitiative/ApsimX/issues/5758 eventhough I'v got no response yet.

**Comment by BrianCollinss** [comment]
I don't think creating a second issue will help.

**Comment by hol430** [comment]
Duplicate of #5758.
