### ISSUE TITLE
How do I report soil organic carbon?

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#5787]

**Comment by jal-frezie** [comment]
If I add "sum of [Organic].Carbon" to the report table it gets an empty column, and if I use MathUtilities.Sum(Organic.Carbon) in a manager script its value is zero

**Comment by hol430** [comment]
You could try `sum([Nutrient].TotalC)`. I don't know too much about how the soil infrastructure is set up but it appears that `[Organic].Carbon` isn't really used except to define the initial carbon.
