### ISSUE TITLE
Mac_ Install

### ISSUE THREAD

**Issue by jwhish** [APSIMInitiative/ApsimX#5788]
The current version of APSIMX has no Icon on a Mac
There is no trusted source so requires user to override permissions for install
There is no help file within MarkDown 

No ability to adjust the font size within the memo edit window current font size is minuscule

**Comment by hol430** [comment]
> There is no trusted source so requires user to override permissions for install

From what I understand, in order to get around this we need to pay an annual fee to be part of apple's developer program. I think I spoke to @hol353 about this a few months ago and we decided not to do this.
