### ISSUE TITLE
Mac_Markdown

### ISSUE THREAD

**Issue by jwhish** [APSIMInitiative/ApsimX#5789]
is there a way to include pictures without having to provide the full path from the root directory

the abbreviated methods used on windows are not working in the Mac version 

would be good if images in the same folder as the simulations could be picked up and included within the markdown document

**Comment by hol430** [comment]
It's possible and there's an example of this at Examples/Tutorials/Memo.apsimx. Unfortunately it looks like this example references an image which is not actually included in the released versions of apsim. There's also a bug in the path resolution mechanism where it does work with the relative path, but the path must be relative to the parent directory. #5791 should fix these problems.
