### ISSUE TITLE
Mac_Crashing 

### ISSUE THREAD

**Issue by jwhish** [APSIMInitiative/ApsimX#5790]
The current version of APSIMX crashes following the inclusion of a module of memo.

sequence  right click add lifecycle   works ok
right click to add LifePhase 

Error
Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'SharpMap.Layers.TileLayer:_source' (1) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not set up parent class, due to: Could not load type of field 'SharpMap.Layers.TileLayer:_source' (1) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:/Applications/APSIM2020.10.22.5692.app/Contents/Resources/Bin/SharpMap.dll type:TileLayer member:(null)
Could not load type of field 'SharpMap.Rendering.Decoration.GoogleMapsDisclaimer:_tileSource' (7) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load type of field 'SharpMap.Layers.TileAsyncLayer+<>c__DisplayClass4:info' (0) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Invalid type SharpMap.Layers.TileAsyncLayer/<>c__DisplayClass4 for instance field SharpMap.Layers.TileAsyncLayer+<>c__DisplayClass6:CS$<>8__locals5
Invalid type SharpMap.Rendering.Decoration.GoogleMapsDisclaimer for instance field SharpMap.Rendering.Decoration.GoogleMapsDisclaimer+<>c__DisplayClass1:<>4__this

if you Add one memo   its ok 
if you add a second 

System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load type of field 'SharpMap.Layers.TileLayer:_source' (1) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not set up parent class, due to: Could not load type of field 'SharpMap.Layers.TileLayer:_source' (1) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:/Applications/APSIM2020.10.22.5692.app/Contents/Resources/Bin/SharpMap.dll type:TileLayer member:(null)
Could not load type of field 'SharpMap.Rendering.Decoration.GoogleMapsDisclaimer:_tileSource' (7) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Could not load type of field 'SharpMap.Layers.TileAsyncLayer+<>c__DisplayClass4:info' (0) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Invalid type SharpMap.Layers.TileAsyncLayer/<>c__DisplayClass4 for instance field SharpMap.Layers.TileAsyncLayer+<>c__DisplayClass6:CS$<>8__locals5
Invalid type SharpMap.Rendering.Decoration.GoogleMapsDisclaimer for instance field SharpMap.Rendering.Decoration.GoogleMapsDisclaimer+<>c__DisplayClass1:<>4__this
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <b4d1a66727f44ba888b54966284fabb4>:0 
  at APSIM.Shared.Utilities.ReflectionUtilities.GetTypesThatHaveInterface (System.Type interfaceType) [0x00015] in <75638c9453b84e008ed9e2b8c6779635>:0 
  at Models.Core.Apsim.GetAllowableChildModels (System.Object parent) [0x00013] in <83a2f0bc18ee4d9795af1414991582f4>:0 
  at UserInterface.Presenters.AddModelPresenter.Attach (System.Object model, System.Object view, UserInterface.Presenters.ExplorerPresenter explorerPresenter) [0x00055] in <594b4331721e438ca36ccf656c869a37>:0 
  at UserInterface.Presenters.ExplorerPresenter.ShowInRightHandPanel (System.Object model, UserInterface.Views.ViewBase newView, UserInterface.Presenters.IPresenter presenter) [0x00035] in <594b4331721e438ca36ccf656c869a37>:0 
  at UserInterface.Presenters.ExplorerPresenter.ShowInRightHandPanel (System.Object model, System.String gladeResourceName, UserInterface.Presenters.IPresenter presenter) [0x00013] in <594b4331721e438ca36ccf656c869a37>:0 
  at UserInterface.Presenters.ContextMenu.AddModel (System.Object sender, System.EventArgs e) [0x00045] in <594b4331721e438ca36ccf656c869a37>:0 
System.TypeLoadException: Could not load type of field 'SharpMap.Layers.TileLayer:_source' (1) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.TypeLoadException: Could not set up parent class, due to: Could not load type of field 'SharpMap.Layers.TileLayer:_source' (1) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:/Applications/APSIM2020.10.22.5692.app/Contents/Resources/Bin/SharpMap.dll type:TileLayer member:(null)
System.TypeLoadException: Could not load type of field 'SharpMap.Rendering.Decoration.GoogleMapsDisclaimer:_tileSource' (7) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.TypeLoadException: Could not load type of field 'SharpMap.Layers.TileAsyncLayer+<>c__DisplayClass4:info' (0) due to: Could not load file or assembly 'BruTile, Version=0.7.4.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.TypeLoadException: Invalid type SharpMap.Layers.TileAsyncLayer/<>c__DisplayClass4 for instance field SharpMap.Layers.TileAsyncLayer+<>c__DisplayClass6:CS$<>8__locals5
System.TypeLoadException: Invalid type SharpMap.Rendering.Decoration.GoogleMapsDisclaimer for instance field SharpMap.Rendering.Decoration.GoogleMapsDisclaimer+<>c__DisplayClass1:<>4__this

solution is to close and reopen APSIM

**Comment by jwhish** [comment]
Adding machine and software info 
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,2
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
System Version:	macOS 10.15.7 (19H2)
  Kernel Version:	Darwin 19.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal

**Comment by hol430** [comment]
@jwhish - which version of apsim are you using? In theory this should be fixed in version 5778 which was released on Friday.

**Comment by jwhish** [comment]
thanks Dean, updated Mono and latest version of APSIM and seems to be working
