### ISSUE TITLE
Phenology.CurrentPhase.Name defaults to "Germinating"

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#5801]
The Current Phase Name reports as "Germinating" even if the crop hasn't been sown.
It should return null if the crop hasn't been sown?

Similarly, Phenology.Stage defaults to 1.0 - should this be 0?

**Comment by sarahcleary** [comment]
@jbrider - is this still a question requiring an answer?

**Comment by jbrider** [comment]
I'll look into changing it - just wanted to make sure no-one expected it to
behave that way.
