### ISSUE TITLE
Create new cultivar in APSIM NG PMF

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#5807]
How do I create a new cultivar in APSIM NG? I can see all the parameters in the PMF, but they are read only. Is there a simple way I can modify e.g. phenology (e.g. through creation of a temporary cultivar)?

(just asking for a friend!)

@m8harrison, @HamishBrownPFR, @hut104, @hol353

**Comment by peter-devoil** [comment]
This would be a good candidate for a how-to / video somewhere. It gets asked very often.

**Comment by hol430** [comment]
Right click on the plant -> add model -> cultivar (in the PMF folder)

**Comment by m8harrison** [comment]
Thanks Drew

**Comment by m8harrison** [comment]
This may help https://www.youtube.com/watch?v=ZE0cAPoKk2k

**Comment by sarahcleary** [comment]
@sno036 - can this issue be closed?
