### ISSUE TITLE
PAWC in WEIRDO "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#5809]
Hi, when sowing Wheat using WEIRDO as the soilwater model, the following error appeared.

Claying\APSIM\WA_UMU00041.apsimx
Simulation name: DalyupRepellencyNone
System.Exception: Unable to evaluate linear interpolation function .DalyupRepellencyNone.Field.Wheat.Leaf.CohortParameters.ExpansionStress.WaterStressEffect ---> System.Exception: Error while locating variable '[Root].WaterTensionFactor' in variable reference '.DalyupRepellencyNone.Field.Wheat.Leaf.CohortParameters.ExpansionStress.WaterStressEffect.XValue' ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Models.PMF.Organs.Root.get_WaterTensionFactor() in C:\ApsimX\ApsimX-master\Models\PMF\Organs\Root.cs:line 400
   --- End of inner exception stack trace ---

I think this is because PAWC is not calculated in WEIRDO from DUL and LL15, on WEIRDO.cs line 138
@hol430  Dear Drew, could you kindly check if this is the reason and probably rectify it please?
Thank you very much.

**Comment by hol430** [comment]
Can you upload your .apsimx and .met files? I'm running into different errors which I'll also fix, but want to make sure I'm seeing the same problems as you.

@hut104 - in the nutrient json, there are several references to `[Soil].Physical.BD` (e.g. in the initial carbon expression function). This doesn't work if you're using WEIRDO, unless you rename the weirdo node to "physical". I'm not sure what the best solution is. For now I've just renamed my weirdo to physical.

**Comment by Chloe0317** [comment]
@hol430 
Dear Drew, 

I think WEIRDO.cs at line 138 should be changed to 

        public double[] PAWC { get {
              return APSIM.Shared.APSoil.APSoilUtilities.CalcPAWC(Thickness, LL15, DUL, null);
           }
        }

to rectify the issue, as PAW doesn't equal to PAWC. 

My apsimx file can be found at https://github.com/Chloe0317/APSIMsims 

Also, I suspect currently WEIRDO doesn't do solute transport but I need to look into these further.

**Comment by HamishBrownPFR** [comment]
@hol353 @hut104 @Chloe0317   It is probably time for a bit of a tidy up of Weirdo now that the soil has been refactored.  we should probably include a physical node with Weirdo simulations and move the relevant variables off the Weirdo to physical.  
@Chloe0317 you are correct, weirdo is not doing solute yet.

**Comment by par456** [comment]
Pull request was merged, closing issue.
