### ISSUE TITLE
APSIMX-Mac drag and drop

### ISSUE THREAD

**Issue by jwhish** [APSIMInitiative/ApsimX#5818]
The drag and drop to clone simulations or objects does not work only copy and paste seems to work for objects in the tree

**Comment by hol430** [comment]
What are you trying to drag and where are you trying to drop it? Not all nodes can be dropped onto all other nodes. E.g. you can't drop a fertiliser onto a datastore. As a test, you should be able to drop anything onto a folder.

**Comment by jwhish** [comment]
I have a folder with graphs in it and tried to drag and drop a new graph into it + sign appeared but no result

**Comment by hol430** [comment]
Seems to be working for me, although I haven't tested on a mac. If it's still not working, can you upload your .apsimx file?
