### ISSUE TITLE
APSIMX-Mac Add folder

### ISSUE THREAD

**Issue by jwhish** [APSIMInitiative/ApsimX#5819]
There is no option to add a folder at the field level this makes building Graphing pages difficult. you can add folders at a higher level and then copy to the field level.

**Comment by hol430** [comment]
You should be able to right click on the field -> add model -> folder (in the core folder).

![image](https://user-images.githubusercontent.com/36427516/97818156-96a22380-1cec-11eb-8ad4-62ac6435d730.png)

**Comment by jwhish** [comment]
restart fixed this or I Amy have just not looked properly sorry
