### ISSUE TITLE
APSIMX-functions. LinearAfterThresholdFunction

### ISSUE THREAD

**Issue by jwhish** [APSIMInitiative/ApsimX#5821]
the LinearAfterThresholdFunction is not calculating values correctly if you use the lifecycle tutorial 2.2 to check it the x trigger value is set to 10 and the slope s set to 0.01 however the image created shows a slope that starts from 0.1 not 0 so the function appears to be ignoring the trigger value and initiating from 7 this means the rate of development is faster than expected.

**Comment by jwhish** [comment]
This function is working as expected it is just the image that is displayed that is wrong

**Comment by hol430** [comment]
I guess the assumption here is that the line after the trigger point has an x-intercept of 0.

**Comment by jwhish** [comment]
yes

**Comment by hol430** [comment]
Wow you're right, that's very misleading when you click on the function. Well spotted
