### ISSUE TITLE
ANOVA has no guide.

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#5826]
Hello 
How can i findANOVA tutorail if basicly such  this thing exist. How does it work?any clue?
thanks for help

**Comment by hol430** [comment]
There's a link to some documentation for the anova component on [this page](https://apsimnextgeneration.netlify.app/modeldocumentation/) in the tutorials section. There's also an example .apsimx file located at .../ApsimX/Examples/Tutorials/Sensitivity_FactorialANOVA.apsimx.

**Comment by masooandy** [comment]
@hol430 thank you very much to help
