### ISSUE TITLE
Page breaks for new sections

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#583]
Often next is getting lost under a graphs when it actually relates to the graph on the following page.  Is it possible to have some control on where page breaks occur.  for example include a page break at the top of memo so the text of the memo starts at the top of the next page.
![image](https://cloud.githubusercontent.com/assets/7295858/11733794/138e1ec0-a016-11e5-8ff6-a9b3487dd40c.png)

**Comment by hol353** [comment]
Very difficult to prevent orphan headings like in the image above. I would have to write a lot of conditional code to achieve it. Also a model reviewer have commented on too much white space as it is.

I've added page breaks before all major top level headings. That will have to do.
