### ISSUE TITLE
APSIM-MAC. Update not working 

### ISSUE THREAD

**Issue by jwhish** [APSIMInitiative/ApsimX#5830]
Following an update and closing the application down APSIM won't startup. A work around was to delete apsim from the applications folder and drag the new version in from the installation directory. This could be that the update does not change the name of the application within the applications folder

**Comment by hol430** [comment]
Just upgraded from version 5833 to 5850 and it seemed to work ok. Do you recall which versions you were upgrading from and to? Did you have more than one version of apsim installed? Were any instances of apsim running at the time?

**Comment by jwhish** [comment]
just tested this on APSIM 2021.4.7.5628 unfortunately no new versions, but it progressed to showing the update dialogue box with is more than what it used to do, so looking promising will test later.

**Comment by ric394** [comment]
If this is still an issue feel free to reopen but because of the issues age and the version of APSIM used, it is likely no longer relevant.
