### ISSUE TITLE
Apsim-Mac Home screen has to be cleared after update before links will work

### ISSUE THREAD

**Issue by jwhish** [APSIMInitiative/ApsimX#5831]
Home screen has to be cleared after update before links will work

**Comment by hol430** [comment]
@jwhish - are you talking about the apsim home screen? If so, which version are you using and what specifically isn't working?

**Comment by jwhish** [comment]
This is still an issue on APSIM 2021.4.7.5628

**Comment by hol430** [comment]
What's going wrong here exactly? ie - what happens when you try and click on one of the old links?

**Comment by ric394** [comment]
Due to the age of this issue and the version of ApsimX used I'm going to close this issue. Feel free to reopen if the more recent versions are causing similar issues.

**Comment by jwhish** [comment]
Looks like the issue is now fixed because the APSIM window no longer adheres to typical Apple window format. That is there is no title bar at the top of the screen. When it was there in the older version the file > close menu didn’t work. Now that you just close the window and apsim closes. The problem is solved

Jeremy


Dr Jeremy Whish
Farming Systems Researcher
CSIRO Agriculture & Food
Phone: +61 7 32142448 | Mobile: 0428763 426

Address: CSIRO Agriculture, Queensland Biosciences Precinct
306 Carmody Road, St Lucia QLD 4067, Australia


On 25 May 2023, at 4:36 PM, Julian Rich ***@***.***> wrote:



Due to the age of this issue and the version of ApsimX used I'm going to close this issue. Feel free to reopen if the more recent versions are causing similar issues.
