### ISSUE TITLE
VP is zero in weather files generated from GUI

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5837]
The attached weather file has VP as zero for many days.  It was generated using the GUI.  This will impact on ET estimates from microclimate.
[IMPAC1981-2020.zip](https://github.com/APSIMInitiative/ApsimX/files/5485490/IMPAC1981-2020.zip)

I also note that radiation is constant for a long time as well.

**Comment by hol430** [comment]
@hol353 -see above. The met file was downloaded from the nasa/chirps dataset and had VP of 0. However if I try and replicate this with the same date range and coordinates, there is no VP column. I also can't see any indication that apsim is adding VP. Do you know anyone involved with the nasa/chirps project we could talk to about this?

**Comment by hol353** [comment]
Talk to @her123. Perhaps VP was taken out of the met files at some point.

**Comment by hol430** [comment]
@her123 - see above. Do you know if there's anyone involved in the nasa/chirps project who we could talk to about this?

**Comment by her123** [comment]
@hol430 the VP values were coming back from NASAPower faulty for a while. They had issues with the specific humidity (which was used to calc vp) and said they may fix it one day. So I have removed the VP column from the apsim format file from the World Modellers service as APSIM weather works around it anyway.

**Comment by her123** [comment]
Not sure what going on with radiation. I will have to look at that. They have had gaps in it but maybe it's broken now.

**Comment by her123** [comment]
Radiation looks fine for the locations I chose. There maybe something specific about Neil's location.

**Comment by hol430** [comment]
What action is required here? Do we want to add some sort of sensibility checks for downloaded met data? Or all met data?

**Comment by hut104** [comment]
Perhaps at least warnings should be issued.

**Comment by hol353** [comment]
@par456 @ric394 Assigning this to you.

Perhaps add checks into weather.cs to check the weather variables once per day. Some checks:

WARNING IF:
Mint > MaxtT
VP (if present) <= 0
Radn< 0 or Radn > 40
Rain < 0

ERROR IF:
non consecutive days found i.e. today not equal to yesterday + 1
