### ISSUE TITLE
 can not change the  ANOVA input &output rows same as Factors  nods order

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#5850]
When iam trying to chang the rows content of ANOVA nothing hapend.altough with text editor its done but i wanna know whats wrong with this?

**Comment by masooandy** [comment]
Anybody want to take a look? Give a hand ?or what?

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - is anyone able to comment?

**Comment by hol430** [comment]
Definitely a bug, I'll submit a fix today.
