### ISSUE TITLE
climate controller

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#5864]
@hol353 , @hol430 and others: I am probably missing something obvious but where is the "ClimateController" (https://apsimdev.apsim.info/ApsimX/Releases/2020.11.16.5850/ClimateController.pdf) model found? In Add Model, the likely place would be in the "Climate" subdirectory but it is not there - or anywhere else AFAIK. The only way to get it that I can see is to open the ClimateController example and copy/paste. Cheers

**Comment by hol430** [comment]
There is no ClimateController model. The ClimateController.apsimx example/tutorial contains a manger script called ClimateController...is this what you're referring to?

**Comment by MarkLieffering** [comment]
Aaah - that is why I couldn't find it - my bad - rookie terminology mistake! I thought it would be akin to the SlopeEffectsOnWeather  model. Thanks
