### ISSUE TITLE
sobol method doesnt work on [Clock].Today 

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#5870]
Sobol method like morris crashed when i wanna run simulation on single year "clock.today
On a [Clock].Today.Year with mullti year its Ok.the last i  updated last night morris problem fixed but sobol problem still remains

**Comment by hol430** [comment]
Yeah, looks like the sobol component was making certain assumptions about table name and which variable to aggregate on. Previously, it was assuming your predicted table was called Report and that you wanted to aggregate on Clock.Today.Year. #5872 should remove these assumptions by allowing you to specify a variable and table name in the user interface.

I will note that aggregating on day of year in a multi year simulation will be very slow. It took my laptop about 15 minutes to run the post-simulation analysis for a two year simulation which aggregates on day of year.

**Comment by masooandy** [comment]
hi
i don't understand how this solved #5870 ? should i Chang sobol.cs file in apsimx/model/sensetivity with this one?

**Comment by hol430** [comment]
You'll need to upgrade to the latest version, and then you should notice two new inputs in the user interface for the sobol component - table name and variable to aggregate. For table name, choose the table containing your predicted data (e.g. Report). For variable name, this is the variable which you want to aggregate on - in your case Clock.Today.
