### ISSUE TITLE
Error to load apsimx file

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5877]
With the latest version of ApsimX (master branch), I get an error when loading any apsimx file

```
System.MissingMethodException: Method not found: 'System.Object Models.Core.Apsim.Get(Models.Core.IModel, System.String, Boolean)'.
   at UserInterface.Presenters.ExplorerPresenter.ShowRightHandPanel()
   at UserInterface.Presenters.ExplorerPresenter.OnNodeSelected(Object sender, NodeSelectedArgs e) in ApsimX\ApsimNG\Presenters\ExplorerPresenter.cs:line 871
   at UserInterface.Views.TreeView.OnAfterSelect(Object sender, EventArgs e) in ApsimX\ApsimNG\Views\TreeView.cs:line 491

```

**Comment by hol430** [comment]
Strange, was this your first time upgrading in a while? Do you have any uncommitted changes? Which files did you try opening?

**Comment by byzheng** [comment]
I almost have daily updates, but not check apsimng.exe every time. No uncommited changes in my computer. I have reset head every time before pull. 

I just open the Wheat.apsimx example through the menu. The error is happening after opening the file. 

PS: Still the same error after checking out now.

**Comment by hol430** [comment]
Sounds like there might be an old dll lurking somewhere. Can you try deleting the Bin directory and rebuilding? (Might need to use git to discard changes to Bin directory after deleting it, as some files in there are actually tracked by git.)

If that doesn't fix it, you could try deleting the bin/ and obj/ directories inside ApsimNG, Models, and APSIM.Shared directories.

**Comment by byzheng** [comment]
I found the problem, but no idea how to fix. The command line below doesn't compile the APSIMNG.exe.

```
set devenv="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe"
%devenv% ApsimX.sln /Build Release
```

**Comment by hol430** [comment]
To compile apsim, launch a visual studio command prompt, and run `msbuild ApsimX.sln` from inside the apsimx directory.

**Comment by byzheng** [comment]
Thanks msbuild is working now.
