### ISSUE TITLE
Best practises for doing sensitivity analysis using Morris

### ISSUE THREAD

**Issue by frank0434** [APSIMInitiative/ApsimX#5880]
Hi team, trying to use the Morris method to run some sensitivity analysis on ASPIMX-Slurp. 
**Wondering the best practices doing this on HPC since it is taking too much time on a laptop.**

**What I did**

1. Mimic the logic in the current apsimx set up in an [R workflow](https://github.com/frank0434/Master/blob/Sensitivity/_targets.R).  
2. Build a configuration file for each combination of the parameter set in each layer for each treatment.  
3. Use the `Edit` flag in `Models.exe` to create simulation files from a base apsimx file.  

The parameters I'd like to test are: `BD`, `DUL`, `LL`, `KLR`, `SKL` and `RFV`. 
I set up the morris sampling method for each layer which has a total of 22 layers. 
The path number I used was 100 to ensure it can reach the stability. 

The total number of simulation files become rather large: ( 6 (Parameters) + 1) * 100 (Paths) * 22 (Layers) * 20 (Treatments) = 308000. 
The `Edit` feature will create a `BAK` and a `DB` along with the apsimx file, which makes the size of file 3 times greater. @hol430, not sure if this only happens to me. 
![image](https://user-images.githubusercontent.com/30789416/99856878-d3c44c00-2bee-11eb-90b8-7c855aa3fdb8.png).

**Comment by hol430** [comment]
Are you using the morris component built into apsim? There's an example in ApsimX/Examples/Sensitivity/. As far as I know, it shouldn't generate a temp file for each simulation.

**Comment by frank0434** [comment]
No, I didn't use the built in module. 
I think the temp files are not caused by the morris module. 
It happened whenever I use the `/Edit` flag.

**Comment by hol430** [comment]
Yeah, the .db and .bak files will be created whenever apsim opens or closes a file, respectively. I'm actually working on modifying the command-line argument parser for Models.exe this morning, so I can add a flag to optionally not create the .apsimx.bak file.

I'll also try and figure out if we can stop creating the .db file when we open the file. This may be related to the issue of each simulation file writing to its own .db file when we run them - it would be nice if they could all write their data to a central database somehow, so we don't have to manually merge them all once everything has finished running.

**Comment by frank0434** [comment]
Thanks, Drew. 
Looking forward to it.

**Comment by hol430** [comment]
Hi Frank - just as a heads up, we've slightly changed the meaning of the /Edit switch, apsim will now apply the changes and immediately run the file. It doesn't save the change, so you won't have the extra .apsimx.bak being created anymore.

**Comment by frank0434** [comment]
Thank you Drew.

I updated apsimx just before this message and was a bit worried why it took more time than usual. But now all make sense. Thank you very much for the heads up and nice to have improvements.
