### ISSUE TITLE
possibility to import the faba bean from apsim classic to apsimx

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#5881]
Hi guys 
Is there any way i can import faba bean from apsim to apsimx  or importing chicory from apsimx to apsim classic? I need to work on this sooner than wating to validate new plants in apsimx.

**Comment by hol430** [comment]
There's no faba bean model for apsimx, so any simulation using faba bean isn't going to work in next gen. There is a chicory model in next gen, but there's no way to automatically convert an apsimx simulation into apsim classic.

**Comment by masooandy** [comment]
Hi @hol430 
Thanks for response. is there any way that I can transfer the structure of chicory  model and its coeifficents to apsim classic.as you know there are not any of bean family in apsimx.however chicory model should be similar to weed in apsim classic.

**Comment by hol430** [comment]
Well the plant models' infrastructure is totally different between classic and next gen, so to make an equivalent change to both, you'd really need to understand how both models work - which I certainly don't. If you're just using the 'official' chicory model in next gen, then it's probably comparable to the official chicory model in classic.
