### ISSUE TITLE
Using Folders to organize model

### ISSUE THREAD

**Issue by env99** [APSIMInitiative/ApsimX#5895]
Hi, 

I'm trying to organize my model to be more user friendly (and a lot less cluttered) by using a folder in my model. However, it doesn't seem to be working as it is always throwing the following error: _Cannot find a match for link Irrigation in model .RussetBurbank.Irrigate.Irrigate on fixed dates.Script_

Is anyone able to help with this? 
*For reference I do not have any coding experience* 

<img width="254" alt="APSIM Model Folder Parent" src="https://user-images.githubusercontent.com/74792163/100476477-eaf9b280-30a2-11eb-9e12-3366428fe52e.PNG">

<img width="259" alt="APSIM Model Folder Children" src="https://user-images.githubusercontent.com/74792163/100476499-f4831a80-30a2-11eb-8a21-9bb36a160c75.PNG">

<img width="814" alt="APSIM Model Folder Error" src="https://user-images.githubusercontent.com/74792163/100476504-f8af3800-30a2-11eb-9b8a-b33bf7478f30.PNG">

**Comment by env99** [comment]
I ended up using 'Operations' instead of a Folder and inputted each date and amount of irrigation to be applied.

**Comment by hol430** [comment]
If you move your folder into the zone it should work. The scoping rules can be strange when you've got manager scripts inside folders, as they often don't receive events properly from components which aren't in the folder (#5149).
