### ISSUE TITLE
Error from R .....Error: cannot allocate vector of size 6.4 Gb Execution halted" 

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#5896]
anova doesnt work with 990 test ( 5 x18 x 6 with permutation) after minutes of running apsimx this message appears "Error from R:
Script path: 'C:\Users\masoud\AppData\Local\Temp\ANOVAscripta6d53d4b-b4ea-4bcf-999e-fd583e0d7f01.r'
StdErr:
Error: cannot allocate vector of size 6.4 Gb
Execution halted
StdOut:

Script contents:
inputs <- c("density","date","nitrogen")
inputs <- inputs[inputs != ""]
outputs <- c("biomass")
outputs <- outputs[outputs != ""]
factorial_data <- read.csv("C:/Users/masoud/AppData/Local/Temp/anovaVariableValuesa6d53d4b-b4ea-4bcf-999e-fd583e0d7f01.csv")
indices <- data.frame(matrix(ncol = 4, nrow = 0))
colnames(indices) <- c("Input", "Output", "FirstOrder", "TotalOrder")
for (output in outputs){
  data <- factorial_data[, names(factorial_data) %in% inputs | names(factorial_data) == output]
  data[, names(data) %in% inputs] <- lapply(data[, names(data) %in% inputs], factor)
  output_mean <- mean(data[[output]])
  TSS <- sum((data[[output]] - output_mean)^2)
  anova_model <- aov(data[[output]] ~ (.)^1000, data = data[, names(data) %in% inputs])
  SSi <- summary(anova_model)[[1]][2]
  variance_contributions <- SSi / TSS
  parameter_names <- trimws(rownames(SSi), which = "both")
  all_results <- data.frame(parameter_names, variance_contributions, row.names = NULL)
  names(all_results) <- list("input", "% of variance")  
  for (input in inputs){
    first <- all_results[all_results$input == input, colnames(all_results) == "% of variance"]
    total <- sum(all_results[grepl(input, all_results$input), colnames(all_results) == "% of variance"])
    result <- data.frame(Input=c(input), Output=c(output), FirstOrder=c(first), TotalOrder=c(total))
    indices <- rbind(indices, result)
  }
}
write.table(indices, sep=",", row.names=FALSE)

this is really pain in the ...

**Comment by BrianCollinss** [comment]
Make sure you just run model for as long as you need by changing the clock. Reduced the size of the daily output file, if any, by removing unnecessary variables from it. See if it helps.

**Comment by masooandy** [comment]
thank you @BrianCollinss for share on contrary by reducing the size of experiment the size of output file in c/user/app data/temp/... has been increasing. even deleting the out put file (without post simulation of curse) didn't solve the problem those three    
sensitivity modules are really sensitive and easily crashed with simple error. as the matter of fact apsim classic is more stable and resistance

**Comment by BrianCollinss** [comment]
Dear Masoud. If you try to spend some more time writing your issues, it would be a lot easier for others to read it and help you. I personally cannot know (in your first comment) where your comment ends and where the script you wanted to show starts. There are tools in the text editor you can use. It would also help to use punctuations as often as needed. The clearer you ask the questions, the higher the chance of getting a helping response. Cheers mate.

**Comment by masooandy** [comment]
Dear Brian I appreciate your heed. at the moment I need help about two things if you have time and be willing to give tips 
the first is i cant find correct format of SowDate  (Sow on a fix date)in Factorrial nod  for morris or sobol method ?i tried  everything and the format of root nod (sow on a fix date) but get nothing. 
the second is that i cant work with function nods is there any help or manual  for them ? 
many thanks in advance. 
Masoud.

**Comment by masooandy** [comment]
[morris folder.zip](https://github.com/APSIMInitiative/ApsimX/files/5622871/morris.folder.zip)


Dear  @hol430  I need help about two things if you have time and be willing to give tips 
the first is i cant find correct format of SowDate  (Sow on a fix date)in Factorrial nod  for morris or sobol method ?i tried  everything and the format of root nod (sow on a fix date) but get nothing. 
the second is that i cant work with function nods (add model/function/childs )is there any help or manual  for them ? 
many thanks in advance. 
Masoud.

**Comment by masooandy** [comment]
Any one dosnt want to give help?

**Comment by hol430** [comment]
Hi @masooandy, yeah using the dates as parameters in the sensitivity analysis won't work at the moment. I'll have a think about how we could implement it, but in the meantime your best bet will be to use some sort of proxy property in the manager script (e.g. an integer) which has can be translated by the script into a sowing date. For example:

```csharp
[Description("Sowing date code (# days after start of simulation)")]
public int SowDate { get; set; }
```

And then you could change the condition for sowing:

```csharp
if ((Clock.Today - Clock.StartDate).TotalDays == SowDate)
{
...
}
```

> i cant work with function nods (add model/function/childs )is there any help or manual for them ?

You might need to be a bit more specific about what's not working here. It's worth noting that not every model can be added as a child to every other model. For example you can't add clock as a child of fertiliser. So if you're trying to add a model but can't find it in the list, that might be the reason why.

**Comment by masooandy** [comment]
Hi  drew thanks for usefull tip about "Sowing date code". About Function I can understant the Logic
For exsample i understant the plant physiological parts  like photoperyod, cultivar and etc....childe
But i need  a manual or something all along spacially about those which related to statistics . 
 at last just for your information I gott a lot of  help for  free from you and others here and by all mean will be happy  to give help in return as much as i can.
Cheers.

**Comment by ric394** [comment]
This is very old and will be closed.
If this is still an issue, please feel free to create another issue with a reference to this one.
