### ISSUE TITLE
Canopy temperature routine

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#5897]
I would like to know whether there is a plan to develop a robust canopy temperature routine for NextGen.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - question from @BrianCollinss

**Comment by jbrider** [comment]
@BrianCollinss I'm pretty sure you're aware of Alex's work with Photosynthesis. We're starting to implement hourly data inside of DCaPS. I don't think anyone is looking any closer at canopy temperature's than that at the moment.

**Comment by BrianCollinss** [comment]
Thanks @jbrider. I was just wondering if any standalone module is being developed. Good to hear that DCaPST is coming in soon. Cheers.
