### ISSUE TITLE
Reference external files from manager script

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#59]
There is a working example of how we want to do this on feature branch https://github.com/PlantandFoodResearch/ApsimX/tree/WaterExtractionTest located in C:\ApsimX\Tests\ReadExternalFiles\ReadFileTest.apsimx 
![image](https://cloud.githubusercontent.com/assets/7295858/7326115/01fd735e-eb17-11e4-886c-2e88da8c942e.png)

This will only work on machines where APSIMX is installed in C:\ApsimX so won't pass on Jenkins.  However I can't work out how to make this a relative file path.

**Comment by hol353** [comment]
I've had a look a this. I've made some changes to your script that will work. Primarily I'm calling a utility function in PathUtilities to get an absolute path.

I added a link:
      [Link] Simulation simulation;

and then modified 2 lines:
      string fullPath = PathUtilities.GetAbsolutePath(CoverFile, simulation.FileName);
      CoverVals.LoadFile(fullPath);

Full script is here:
using System;
using Models.Core;
using System.Collections.Generic;
using System.Text;
using Models.PMF;
using Models;
using System.Xml.Serialization;
using APSIM.Shared.Utilities;
using System.IO;
	  

namespace Models
{
	[Serializable] 
	public class Script : Model
	{     
	
   [Link] Clock Clock;
   [Link] Zone zone;
   [Link] Simulation simulation;
   
  [Description("File of covers to load")]
   public string CoverFile { get; set; }
   [Description("Column to load, 0 based excluding date column")]
   public  int Column { get; set; }
   [Description("Extinction coefficient")]
   public  double Ext_coef { get; set; }
   
   
   [Description("Path for coefficient to be Overwritten")]
	public string OverRidePath { get; set; }

   
   CoverIntcs CoverVals;
   
  public double CoverToday { get; private set; }
  public double leaflai { get; private set; }
     
   int Col;
   string CF;
   
   public class CDateValues
   {
      public   DateTime DT = new DateTime();
      public   double[] Values = new double[8];
      
   }

 
   public class CoverIntcs
   {
      //string CoverDataFile = CoverFileg();
     
      public List<CDateValues> CLS = new List<CDateValues>(); 

      public double GetCover(DateTime dt, int C)
      {
         
         foreach(CDateValues CDV in CLS)
         {
            double k = CDV.Values[C];  
            if (CDV.DT.DayOfYear == dt.DayOfYear)
               return k;
         }
         return 0;
      }
      
      public void LoadFile(string CF)
      {

		 StreamReader infile = new StreamReader(CF);


         string S = infile.ReadToEnd();

         string[] elements = S.Split('\n');
          

         //
         int L = 0;
         foreach (string line in elements)
         {
            L++;
            if (L < 2) continue; //skip first 1 lines

            string [] StrVals = line.Split(',');
            CDateValues CL = new CDateValues();
            try
            {
               CL.DT = Convert.ToDateTime(StrVals[0]);
            }
            catch (Exception E)
            {
               //Probaly extra lines at end lets just 
               break;
            }

            for (int l = 1; l < StrVals.Length; l++)
            {
               CL.Values[l - 1] = Convert.ToDouble(StrVals[l]);
            }


            CLS.Add(CL);


         }

      }


   }
   
   
   
   // The following event handler will be called once at the beginning of the simulation
   //[EventHandler] public void OnInitialised()
   [EventSubscribe("StartOfSimulation")]
     private void OnStartOfSimulation(object sender, EventArgs e)

   {
      CoverVals = new CoverIntcs();
      string fullPath = PathUtilities.GetAbsolutePath(CoverFile, simulation.FileName);
      CoverVals.LoadFile(fullPath);
   }
      
   // The following event handler will be called each day at the beginning of the day
 //  [EventHandler] public void OnPrepare()
    [EventSubscribe("StartOfDay")]
     private void OnStartOfDay(object sender, EventArgs e)

   {
      
      CoverToday = CoverVals.GetCover(Clock.Today.Date,Column);
      
      if (CoverToday == 1)
         leaflai = Math.Log(0.01)/-Ext_coef;
      else
      {
         if (CoverToday > 0)
            leaflai = Math.Log(1 - CoverToday) / -Ext_coef;
         else
            leaflai = 0;
      }
            object ResetValue = leaflai;
			zone.Set(OverRidePath, ResetValue);  
   }
   
 }

}

**Comment by HamishBrownPFR** [comment]
Yep that works.  I have implemented the changes in ApsimX\Tests\SoilWater\ShallowSoilTests\LucerneAndPasture.apsimx on https://github.com/PlantandFoodResearch/ApsimX/tree/WaterExtractionTest which will end up in the master when this branch is pulled in. 

Issue resolved
