### ISSUE TITLE
Report arbitrary key and value pair in weather file

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5909]
@hol430 Hamish and I discussed to add extra variables to classify the experiment, e.g. state or region. 

We thought the simple method would be to add state and region in the met file with key and value pair, then export in the report, e.g.

```
State = QLD
Region = North QLD
```

Could we report the key and value pair in the weather file? Would be very useful if we can implement as this way.

If not possible, I guess another way is to write a manager script. Do you have other suggestions?

**Comment by BrianCollinss** [comment]
Maybe a new optional 'model' that keeps all such site-specific information with the ability for the user to creat new pairs as needed.

**Comment by byzheng** [comment]
How about a manager script in the management toolbox for extra information

![image](https://user-images.githubusercontent.com/1657381/100965543-03743c00-357f-11eb-9502-280c60f9049b.png)

**Comment by BrianCollinss** [comment]
Seems an easily solution, specially if it comes with many default parameters.
