### ISSUE TITLE
Show non-existing table in replacement

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#5910]
If a report model exist in the replacement, but not in the paddock, the data store is not generated a table for it as expected. However, when clicking the `Data` panel under `Replacement`, the `Data` panel is showing the first table in the data store, e.g. the `HarvestReport` in the figure below.

![image](https://user-images.githubusercontent.com/1657381/100832602-efafd380-34b3-11eb-8d27-bed253e9a4d3.png)

**Comment by hol430** [comment]
Interesting. I can change it so that it shows nothing in this scenario - should we also grey out the table dropdown in the report view? Or leave as is?

**Comment by byzheng** [comment]
"Show nothing" in this scenario would make more sense similar as a simulation is not run (i.e. no table in the data store).

**Comment by lie112** [comment]
relates to #5530
