### ISSUE TITLE
How can i know the effects of tillage, crop residues cover or organic fertilizer on soil properties

### ISSUE THREAD

**Issue by Starkeng** [APSIMInitiative/ApsimX#5912]
Hi, everybody!
Recently, i focus on the effects of tillage, crop residues cover or organic fertilizer on soil properties (physics and chemistry). what i need to know is how does the apsim consider the effects. I am trying to explore it through looking up the document or the source code of apsim, but i failed. So, whether some guidelines have been compiled or what can i do to help me understanding it quickly.

Thank you very much！
Regards

**Comment by hol430** [comment]
@hut104?

**Comment by sarahcleary** [comment]
@ Starkeng - is this question still unanswered?

**Comment by Chloe0317** [comment]
I believe that tillage operations have not been implemented in APSIM Next Gen yet. [See a discussion here](https://github.com/APSIMInitiative/ApsimX/issues/1542). So a getaround as proposed in the link will be to use the Incorporate method of SurfaceOrganicMatter model, though @hol353 Dean might have a better idea on the latest development. 

This link discussed how tillage is handled in [APSIM classic](https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/surfaceom/)

I hope this somewhat addresses your question. Cheers.
