### ISSUE TITLE
APSIM Next Gen model documentation web link

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5914]
Where does APSIM get all the information to propagate the online documentation page?
https://apsimnextgeneration.netlify.app/modeldocumentation
 
Are aspects of this page manually entered?
I am trying to correct the web link for the CLEM help system that currently points to apsimdev address which is an old build of the website and it should point to www.apsim.info/clem
Should the old apsimdev website be deleted?
I'm pretty sure this page is the only link to the apsimdev version.

**Comment by hol430** [comment]
The file you want is `.../ApsimX/Docs/CreateDocumentation/Documentation.json`. Happy to delete the old website if we don't need it anymore, just let me know.

**Comment by lie112** [comment]
Thanks, I have modified the documentation.json file and will pull that change soon.
I do not need the old version of the website sitting in the apsimdev system (wherever that is) as the only maintained clem help and reference system is at https://www.apsim.info/clem/content/home.html (srv/www/apsim.info/html/clem on wpext2-prod.it.csiro.au)
