### ISSUE TITLE
Observed Initial Water

### ISSUE THREAD

**Issue by env99** [APSIMInitiative/ApsimX#5917]
Hi guys, 
Is there a way to add in actual observed initial water content into the model? So rather than adding in a depth of wet soil or a percentage, can I add in volumetric or gravimetric water content values for each layer as observed in the field?

**Comment by hol430** [comment]
Yep, you can add volumetric initial water via a sample model. To add a sample to your soil, right click on the soil -> add model -> sample (in the soils folder). Then just specify your volumetric water content in the water column of the newly-added sample node.

**Comment by env99** [comment]
Thanks! I gave it a shot but APSIM is throwing an error that 'Sample is not a child of Soil' 
<img width="608" alt="APSIM Error_not a child" src="https://user-images.githubusercontent.com/74792163/101528516-a85e9280-394c-11eb-9fb2-19411d191da1.PNG">
<img width="159" alt="Sample child of Soil" src="https://user-images.githubusercontent.com/74792163/101528598-c3310700-394c-11eb-9be4-ee6260258d40.PNG">

**Comment by frank0434** [comment]
Hi @env99 Did you specify the `Depth(cm)` column? 
Looks like apsim complaint about the `Depth` in you `Sample` node.
I changed the name of `Sample` to `InitialConditions" but it is the same sample model. 
Please see snapshot below. 
![image](https://user-images.githubusercontent.com/30789416/101537984-4875f380-3a01-11eb-8402-2d802a745496.png)
![image](https://user-images.githubusercontent.com/30789416/101538015-5d528700-3a01-11eb-8a33-1a29a2484fbe.png)

Also, suggest that you delete the `Initial water` model if you'd like to define `VWC` for each layer. Apsim may confused if we supply two methods to define the initial soil water conditions. 

Apsim-NG has this nice feature called `/Edit`. You won't need to manual type all the `vwc` for each layer in the `UI` if you prefer to use command line to make the changes and run simulations. 
more details [here](https://apsimnextgeneration.netlify.app/usage/editfile/)

**Comment by env99** [comment]
Thank you! I did not realize the Initial Water was confusing the model. As soon as I deleted it the model ran fine. Appreciate the help!
