### ISSUE TITLE
Morris Sensitivity - Errors

### ISSUE THREAD

**Issue by env99** [APSIMInitiative/ApsimX#5918]
I'm trying to run the Morris Sensitivity test on a potato model. Each time I want to look at the sensitivity for one of the below three outputs, I get the same error message after the model tries to run for a while. Does anyone know what this error means or how to fix it?

*For reference I have no coding experience*

Outputs:
[Soil].SoilWater.SWmm
[Soil].SoilWater.PAWmm
[Soil].Temperature.Value

Error:
<img width="406" alt="APSIM Error_0 paths" src="https://user-images.githubusercontent.com/74792163/101087898-20edd980-3570-11eb-91b6-4d6747fafded.PNG">
<img width="431" alt="APSIM Error_0 paths extended" src="https://user-images.githubusercontent.com/74792163/101087914-24816080-3570-11eb-9d3f-4cf4112ae6a6.PNG">

**Comment by hol430** [comment]
Hi @env99 - could you upload your .apsimx/.met files?

**Comment by masooandy** [comment]
There is no soil layer []determined.if you upload your .apsimx file better solution may be  present.

**Comment by env99** [comment]
[Field S APSIM.zip](https://github.com/APSIMInitiative/ApsimX/files/5644977/Field.S.APSIM.zip)

**Comment by masooandy** [comment]
[potato.zip](https://github.com/APSIMInitiative/ApsimX/files/5646175/potato.zip)
@env99 i had to reduce the number of path and jump because of time  and had to  delete your graphs preventing errors. so you can recreate your desired morris method. good luck

**Comment by hol430** [comment]
I actually don't get an error when running the file - perhaps that's due to us running different versions of apsim. I notice that in the report you have some missing parentheses in some of the sum() functions. It's probably worth fixing these anyway. I'm also not sure of the implications of aggregating on year in a 1-year simulation - perhaps someone else could comment on the sensible-ness of this.

**Comment by env99** [comment]
Hey @masooandy which version of APSIM are you using? I can't open the file, it's saying your version is newer than mine.

**Comment by masooandy** [comment]
Hey @env99 upgrade your apsimx to the latest version.then you can run morris method for year or today

**Comment by env99** [comment]
Thank you, @masooandy. I've updated APSIM and tried to rerun the model you sent back to me. The model runs but the values from the report containing 'sum of' did not get reported in the results, so I'm not able to graph the results to see which inputs affect these outputs. 

I'm mainly interested in Soil Temperature as an output as it is consistently 10*C higher than what was observed in the field.

**Comment by masooandy** [comment]
I did run that Report conditiobs and that was ok any way you can use this cod in a new "Reporttem"alone.
"Field.Soil.Script.SoilTemperature[1:7]" for each 7 soil layer

**Comment by masooandy** [comment]
[NewZip.zip](https://github.com/APSIMInitiative/ApsimX/files/5675297/NewZip.zip)
Hey @env99 check this out. if it doesnt work properly .clean the graph rerun the simulation and ...

**Comment by env99** [comment]
Thank you. Once I upgraded APSIM I was actually just able to run my original model without error.
