### ISSUE TITLE
padding and margins in GTK# notebook page

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5925]
Can anyone assist me in setting the left hand margin of a viewport, or the left hand padding of a notebook page in C# code?
GTK# documentation is less than friendly.

**Comment by hol430** [comment]
Yep, can you send a screenshot showing what you're trying to change?

**Comment by lie112** [comment]
I want to add some spacing beside my Markdown that is in a view inside the notebook
I can't fin a property for the viewport or the tab area.

![image](https://user-images.githubusercontent.com/19215637/101307043-0ed0ab80-388e-11eb-8950-3859025ceefb.png)

Another Q:
In our markdown can we have a link to a file:// with full c drive path. I want a link to the html file I create for the description summary. It seems the parsing does not recognise my file:// as a link like it would http://

**Comment by lie112** [comment]
![image](https://user-images.githubusercontent.com/19215637/101307412-ee552100-388e-11eb-99ec-69e0b2f30c96.png)

I don't know a relative path to the .apsimx simulation folder

**Comment by hol430** [comment]
The best way to add a view next to the markdown inside the tab would probably be to add a hbox as the main widget in that tab of the notebook. You can add multiple child widgets to a hbox, and it will stack them horizontally left to right. So whatever you want to add to the left of the markdown would be added to the hbox first (via Hbox.PackStart method) and then you could add the markdown widget to the hbox after that.

I don't think our markdown view supports a link to a local file but I think it should be possible to add it in. I'll have a look.

**Comment by lie112** [comment]
I got rid of the c: in the path and replaced it with ../ and the link is recognised, but I get an error "the system cannot find the file specified", so it's to do with developing a relative path to the apsimx file folder

**Comment by hol430** [comment]
Strangely, clicking on a hyperlink doesn't work for me, even if it's a plain old http link (as in the memo example). Looks like the problems with file:// are due to the markdown parser not recognising it as a uri (probably an upstream bug). It may be possible to get this halfway working by using relative paths (does using ./ work if the file is in the same directory as the .apsimx file?) but for now I'm going to try and figure out why I can't even click on a link.

**Comment by lie112** [comment]
Got it with a minor hack to allow markdown parser to identify it as a link and markdownview.cs to convert it back to a accepted path.
I'll now get back to the margin..

**Comment by lie112** [comment]
It will work for all relative links people need. I just needed an absolute path.

**Comment by lie112** [comment]
All sorted. I wrapped everything in an EventBox with a white background and added a border.

**Comment by lie112** [comment]
Yes you are right. Microsoft Markdown parser does not recognise file:///C:/xxxx/xxx/xxx as a valid link for security purposes.
https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops
As this is software and not a secure web service I think we can trust our own generated links hdd links

I have formatted the offending string to file://../C[drive]/xxxx/xxx/xxx.html (added ../ and removed the : after C) so that is is considered a relative path and a valid link. Then in the link section of MarkDownView.cs I look for [drive] in the URL and if present convert it back to 
file:///C:/xxxx/xxx/xxx.html which all works. This will allow any drive to be used not just C. I assume it will continue to work across ios and linux.
The only other fix would be to search through all the text before being parsed to MarkDown and change it so that the parser recognises them as links before being changed back to a recognised address before running the link. This would then allow anyone to perform such a link in their markdown. I could try and attempt this if you like. I'll open this work as a new issue in that case.

I am about to pull all the changes needed to remove HTMLView from CLEM as it's now done. There are a few other models still using HTMLView (GenericView, ExplorerView, HTMLView, UpgradeView, and ViewName attributes for Simulations and Stock

**Comment by hol430** [comment]
What action is required here? Is the only remaining issue the problem with the links? I've tested #5970 and the clem links to files on disk seem to be working ok.
