### ISSUE TITLE
REMS

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#5931]
@APSIMInitiative/reference-panel 
Work has been progressing on a new version of REMS and we would like to give it a home as a repository on the Apsim Initiative's github.

For those not familiar with REMS it is a **R**esearch **E**xperiment **M**anagement **S**ystem that allows users to store and manage their experimental data. It also allows the user to export their experiments as APSIM simulations
It is using the same database tech as NextGen, but the user interface is currently implemented using WinForms so it is not cross platform at this stage.

**Comment by hol353** [comment]
REMS public repo created here: https://github.com/APSIMInitiative/REMS. Hopefully you have write permissions. Let me know if there is a problem.

**Comment by hol430** [comment]
Can this issue be closed as fixed?
