### ISSUE TITLE
Need ability to provide absolute file path in markdown link

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5932]
A bit of fiddling is required to allow absolute paths rather than relative server paths to be used as a link in markdown.
This is because microsoft.markdown parser no longer accepts paths as valid links for security reasons.

I have found a work around and will think about how to implement this for all others using markdown rather than my hack method of preformatting the path for acceptance and converting it back to make it a valid link.

Relates to #5925

**Comment by lie112** [comment]
This relates to removing the HTMLView for Windows .Net Core compatibility
Last discussion point from #5925 is as follows to continue discussion here.

[Microsoft Markdown parser](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops) does not recognise file:///C:/xxxx/xxx/xxx as a valid link for security purposes.

As this is software and not a secure web service I think we can trust our own generated links hdd links

I have formatted the offending string to file://../C[drive]/xxxx/xxx/xxx.html (added ../ and removed the : after C) so that is is considered a relative path and a valid link. Then in the link section of MarkDownView.cs I look for [drive] in the URL and if present convert it back to
file:///C:/xxxx/xxx/xxx.html which all works. This will allow any drive to be used not just C. I assume it will continue to work across ios and linux.
The only other fix would be to search through all the text before being parsed to MarkDown and change it so that the parser recognises them as links before being changed back to a recognised address before running the link. This would then allow anyone to perform such a link in their markdown. I could try and attempt this if you like. I'll open this work as a new issue in that case.

I am about to pull all the changes needed to remove HTMLView from CLEM as it's now done. There are a few other models still using HTMLView (GenericView, ExplorerView, HTMLView, UpgradeView, and ViewName attributes for Simulations and Stock

**Comment by lie112** [comment]
Introduced a slight hack is to produce a formatted invalid path that markdown accepts as a link, then this is converted back to a file:// path on creation of the link.

It would be useful if we could add the ability to send the link to a target tab in the browser, but I'm not sure quite how to specify this. Some markdown parsers allow the target to be provided in the link string but the Mircosoft.Markdown parser won't find this.

**Comment by hol430** [comment]
Not sure I understand, if you click on a link it should open in the browser. Unless you mean a link to a pdf file stored on disk somewhere?

**Comment by lie112** [comment]
Yes, I am trying to open *.html from the apsimx simulation folder
The current parser only allows relative paths on a server or fully qualified web addresses http:// www mailto: or /
I need to use file://c:/xxx/xxx/xxx/currentsummarydescrption.html which is a security risk for the current parser. 
No parser seems to allow you to specify link target and stop it creating multiple tabs
