### ISSUE TITLE
Markdown view improvements - tables

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#5937]
I can see that APSIM is generating its own markdown view in GTK for displaying markdown text.
I assume this will be maintained and improved in future. I assume it also means we can improve functionality over time.

Are the [markdown instructions](https://apsimnextgeneration.netlify.app/usage/memo/) correct in that should the final display look like the examples given on the webpage or is this an example taken from online and not what APSIM NextGen produces?

![image](https://user-images.githubusercontent.com/19215637/101565034-be835600-3a13-11eb-8cb2-3d42d68c7802.png)

I have built a table but the cell contents do not get markdown rendered and there is no/incorrect formatting of the table. There is no centring of contents or shading of headers correctly. Is this because I have incorrectly provided the markdown text?

![image](https://user-images.githubusercontent.com/19215637/101565180-0b672c80-3a14-11eb-9b66-76649be262c6.png)

I assume all the markdown tools online are converting to html/css and thus look professional but not what we will get for now.

![image](https://user-images.githubusercontent.com/19215637/101565253-33569000-3a14-11eb-9366-ed4991df8a39.png)

**Comment by hol430** [comment]
Yeah the markdown view is assembled out of gtk widgets on the fly. It's far from perfect but we will be improving it over time. The docs on the website won't look exactly like what you will see in apsim, they exist mainly to help with the syntax.

That being said, the way tables are handled is a bit clumsy at the moment. The problem is that if we use a gtk table, the text can't be selected/copied. If we try to layout the text so that it lines up, we have to use a monospace font which is not really ideal either. There may be a possible middle ground, as the gtktextview api is supposed to be pretty flexible, but I haven't found time to look into it yet. I'm also currently working on changing markdown parsers (to markdig), as we have run into several problems with the current parser.

**Comment by lie112** [comment]
Maybe the website needs a NOTE to tell the user this is not what markdown will look like in APSIM Next Gen
I had assumed that was the table I was getting and thought it was totally acceptable, but the current table is pretty poor. 
Is it possible to have an editable table and a non editable table specified by the user and build a much prettier table than cannot be selected.?

**Comment by hol430** [comment]
I guess we could add a flag to the MarkdownView class which controls whether tables are rendered as selectable text or as labels inside a GtkTable. The initial implementation of that MarkdownView used the latter approach, so it should be possible to ressurect that approach from the murky depths of the git history - or just rebuild it from scratch as it wasn't anything fancy.

**Comment by hol430** [comment]
Hi @lie112, I've revisited how tables are rendered in the markdownview, and I've also changed markdown parsers at the same time. I've checked the existing clem UI components and all seems to be working ok as far as I can see. If you send me the markdown table you were trying to render in your initial comment, I'll double check that it works.

**Comment by lie112** [comment]
This is the markdown text I am creating in code.

- Seems it is not obeying the centre text in column when using :---: as stated in instructions
- Does not obey formatting of labels in column 1. Some should be italic surrounded with _ which are replaced with * in render
- Seems to have entire table in grey box. Is this the header row or expected format?

`| Activity | Adult Male OnFarm | Adult Male OffFarm | Adult Female | Child Male |  
| :--- | :---: | :---: | :---: | :---: |  
| LabourActivityOffFarm |  | 1 |  |  |  
| Wheat HARVEST | 1 | 3 | 2 |  |  
| _Manage Wheat Residue_ |  |  |  |  |   
| Prepare | 1 | 1 |  |  |  
| Planting | 1 | 1 |  |  |  
| Fertiliser | 1 | 1 |  |  |  
| Irrigation | 1 | 1 |  |  |  
| Herbicide | 1 | 1 |  |  |  
| _Sell Wheat_ |  |  |  |  |   
| Mung HARVEST | 1 | 3 | 2 |  |  
| _Manage Mung Residue_ |  |  |  |  |   
| Prepare | 1 | 1 |  |  |  
| Planting | 1 | 1 |  |  |  
| Fertiliser | 1 | 1 |  |  |  
| Irrigation | 1 | 1 |  |  |  
| _Sell Mung_ |  |  |  |  |   
| Rice HARVEST | 1 | 3 | 2 |  |  
| _Manage Rice Residue_ |  |  |  |  |   
| Prepare | 1 | 1 |  |  |  
| Planting | 1 | 1 |  |  |  
| Fertiliser | 1 | 1 |  |  |  
| _Sell Rice_ |  |  |  |  |   
| LabourActivityTask |  |  | 1 |  |  
| _Feed Wheat Residue_ |  |  |  |  |   
| _Feed Mung Residue_ |  |  |  |  |   
| _Feed Rice Residue_ |  |  |  |  |   
| _Feed Gram husk_ |  |  |  |  |   
| _Feed Choker_ |  |  |  |  |   
| _Feed MustardCake_ |  |  |  |  |   
| Milk |  |  | 1 |  |  
| _Sell Milk 30kept_ |  |  |  |  |   
| _Move to pasture_ |  |  |  |  |   
  
***  
Notes  
-  Only activities capable of including a labour requirement are displayed.  
-  Activities with no labour requirement provided are displayed with italic text.  
-  Multiple rows for a given activity show where more than one individual is required.  
-  The preferential allocation of labour is identified from 1 (1st) to 5 (5th, max levels displayed)  
  
***  
Warnings  
-  As this simulation allows aging of individuals (see Labour) these allocations may change over the duration of the simulation.  
***  
`

**Comment by lie112** [comment]
Resulting table. this uses all latest changes at time of submitting this post.

![image](https://user-images.githubusercontent.com/19215637/102435454-2c57ff00-405e-11eb-82e2-1f622995c235.png)

**Comment by hol430** [comment]
Well, I haven't made a pull request for these changes yet, so I'd be surprised if you were seeing the same output that I see :). Anyway, I just tested it and some parts are working and some parts are not.

- Text alignment in table columns has not been implemented, nor has it ever worked as far as I can see. Not sure why it was included in the docs. The good news is that the new markdown parser has support for column alignment, and it's picking up on the alignment correctly in your table. I'll have a crack at adding support for this into our markdown view when I get  the chance
- Italics (and other inline content such as links) are displaying correctly
- The grey boxes are an artifact of the old table rendering method (building GtkTable widgets and adding them as siblings of the textview) coupled with the weird gtk theme we're using on windows. This will no longer be a problem with the new method  - we're adding the text to the textview and aligning it via TextTags, so everything is inside the textview

Let me know if there are other cosmetic changes you'd like to see. The markdown syntax doesn't really allow for this sort of thing, but I'm just wondering if there are any obvious improvements that could be applied to all tables in the markdownview. Grid lines are probably not doable (at least, I can't think of a way off the top of my head). Unsure about other stuff - row shading may be doable but I can't say I've really looked into it.

![image](https://user-images.githubusercontent.com/36427516/102447975-d6468400-407c-11eb-841a-0f44e52c9d23.png)
