### ISSUE TITLE
Changing soil layer depths

### ISSUE THREAD

**Issue by pjinnes** [APSIMInitiative/ApsimX#5942]
I want to change the soil profile so the top layer is 5cm deep. Are there complications with doing this? When I change from the default 15cm to various other layer depths (top layer 5cm) simulated yields (wheat) drop about 30%.

**Comment by pjinnes** [comment]
[WMaA16SPRS4_test.apsimx.txt](https://github.com/APSIMInitiative/ApsimX/files/5670636/WMaA16SPRS4_test.apsimx.txt)
[WMaA16SPRS4_test_5cm.apsimx.txt](https://github.com/APSIMInitiative/ApsimX/files/5670637/WMaA16SPRS4_test_5cm.apsimx.txt)
[WMaA16SPRS4_-23.90_148.40.met.txt](https://github.com/APSIMInitiative/ApsimX/files/5670638/WMaA16SPRS4_-23.90_148.40.met.txt)

**Comment by BrianCollinss** [comment]
Too thin a top layer may cause complications as evaporation rates is sensitive to it.

**Comment by pjinnes** [comment]
Any suggestions how to proceed if I need to use a top5cm layer?  I tried using swim3 but get exactly same low yield result.

**Comment by hol430** [comment]
As @BrianCollinss said, changing the top layer is going to change your evaporation and water distribution. In general you could consider layer thickness to be a parameter like any other, so yes, by changing it you could reasonably expect changes in the model output.

**Comment by pjinnes** [comment]
OK thanks, I'm looking at evaporation parameters (SummerCona and WinterCona) which I can set lower and that brings yield results back up.
