### ISSUE TITLE
Sugarcane ratoon crop throws exception

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#5980]
- When I use the **q117** variety there is now problem, but with **q117_ratoon** I get this error: **Could not find in the Sugarcane ini file a cultivar called: q117_ratoon_ratoon**. It seems the code tries to add **ratoon** to the name of the variety.
- Where can I find the sugarcane model and varietal parameters? It seems sugarcane is not the same as other crop models.
- May I know if someone is actively developing the sugarcane model?

**Comment by hol430** [comment]
Unsure about the first point off the top of my head. I can say that the sugarcane model is different to the other models in that it doesn't use the PMF, it's defined entirely in code as far as I know (.../ApsimX/Models/Sugarcane.cs). I don't believe it's being actively worked on.

**Comment by BrianCollinss** [comment]
Cheers mate. I'll dig a bit.
