### ISSUE TITLE
APSIM needs to be able to choose what R version to use

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#5984]
```
Error from R:
Script path: 'C:\Users\uqbababa\AppData\Local\Temp\morrisscript8029b4b8-426b-4fb7-a422-62d0be5f6c8b.r'
StdErr:
During startup - Warning message:
package 'lattice' was built under R version 3.5.3 
Error in library("sensitivity", lib.loc = "C:/Users/uqbababa/AppData/Roaming/ApsimInitiative/ApsimX/rpackages") : 
  there is no package called 'sensitivity'
Execution halted

StdOut:

Script contents:
.libPaths(c('C:/Users/uqbababa/AppData/Roaming/ApsimInitiative/ApsimX/rpackages', .libPaths()))
library('sensitivity', lib.loc = 'C:/Users/uqbababa/AppData/Roaming/ApsimInitiative/ApsimX/rpackages')
params <- c("SOC","Load","DUL")
apsimMorris<-morris(model=NULL
 ,params #string vector of parameter names
 ,25 #no of paths within the total parameter space
 ,design=list(type="oat",levels=11,grid.jump=5)
 ,binf=c(1,100,0.2) #min for each parameter
 ,bsup=c(10,1000,0.4) #max for each parameter
 ,scale=T
 )
write.table(apsimMorris$X, row.names = F, col.names = T, sep = ",")

```

**Comment by hol430** [comment]
Which version of R do you have installed?

**Comment by BrianCollinss** [comment]
3.6.2 and 4.0.0

**Comment by hol430** [comment]
Ok, you'll need to install [rtools40](https://cran.r-project.org/bin/windows/Rtools/) if you don't already have it installed. Also worth noting that the optimiser will only run on R >= 4.0.0. Given that you have two versions of R installed, I'm not 100% sure which one is being called by apsim (in theory, apsim should use the latest installed version, but it may depend on how you intalled the two R versions). My first suggestion would be to delete the directory `%appdata%\ApsimInitiative\ApsimX\rpackages`, and try and run the simulations again - this will force a reinstallation of R package dependencies. If this doesn't work, then my guess would be that apsim is calling R 3.6.2, so you could try uninstalling R 3.6.2, deleting that rpackages directory again, and rerunning again.

**Comment by BrianCollinss** [comment]
Thanks Drew. I did all you instructed. It still does not install the **sensitivity** package. Doe sit depend on 4.0.0 as well?

![image](https://user-images.githubusercontent.com/39573622/102838919-175ae180-444b-11eb-8764-466ab5e8affb.png)

**Comment by hol430** [comment]
The sensitivity analysis components don't rely on a particular version of R as far as I know, but mixing up packages between different versions of R (especially versions before and after 4.0.0) seems a likely culprit. In the output you posted, there's a warning about a package (lattice) being built under an older version of R, so it may be worth trying to purge any old packages on your system.

My first suggestion though would be to try and install the package by hand and see what happens:

```
install.packages('sensitivity', lib = 'C:/Users/uqbababa/AppData/Roaming/ApsimInitiative/ApsimX/rpackages')
```

**Comment by BrianCollinss** [comment]
The warning about **lattice** is for it is built under a version < 4.0.0. I also already have **sensitivity** installed in R. But APSIM looks for it in its own R packages folder, where sensitivity is not found.

**Comment by BrianCollinss** [comment]
Yeah. I could install sensitivity. But it seems APSIM still uses version 3.6.2. Cheers.
