### ISSUE TITLE
APSIM X weather file handling - dates and headers

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6]
From Val (2014-08-19):

- if, for example, rain is not in the body (i.e. the columns of data) in the weather file but is in the header (which should provide a constant value every day) then APSIM X thinks that rain cannot be found and crashes

- need a better way of handling the case when the dates in Clock in a simulation are not within the dates in the weather file.  At present this is an unhandled exception.

**Comment by zur003** [comment]
Just for the record, if the dates in Clock exceed the dates in the weather file, it still raises an exception, but the exception is handled in a fairly reasonable way. This could be improved, but it's not too bad.
