### ISSUE TITLE
Screen left blank on save button click

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6009]
When the save button is clicked, the right hand pane goes blank, the success message is displayed, but the screen item displayed in the right pane (e.g. properties) is not refreshed and the UI is out of sync with user clicks. I can't see that the right hand pane needs to be blank during the save process.

**Comment by hol430** [comment]
You may need to upgrade to a more recent version, this was fixed in #5971.

**Comment by lie112** [comment]
Thanks, seems my last pull from master never did anything.
