### ISSUE TITLE
Additional commands for writing doco in summary field

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#6019]
When we use the [Documment blablabla] tag in the summary of a class (as for target and progression in the example below) the doco system writes a heading for each at the current indent level.  We are getting excessive use of headings and it would be really useful if we could include a key word in this tag "NoHeading" so the doco is just added under the heading of the parent class.
![image](https://user-images.githubusercontent.com/7295858/104955002-4bb3c480-5a2e-11eb-967e-220f4091ddb6.png)

If we move away from using document methods then the issue with headings changes.  Currently something that is documented from the summary field can not have a heading.  We need some way of putting headings into summary tags.  We also need a method for working out what level that heading will be at.
Can we make it so the headings get their level from their distance from the Plant Class.  I.e Phenology, organs etc would be first level headings, their children would be 2nd level headings and so on.

**Comment by HamishBrownPFR** [comment]
Some additional commands that would be useful
[Units] - finds the units of a class and returns string
[ParentName] finds the name of the parent class and returns string

**Comment by HamishBrownPFR** [comment]
Other questions I have
How do we cite a paper from the summary field
How do we create an indent from the summary field

**Comment by HamishBrownPFR** [comment]
@hol353 The [DocumentMathFunction -] method works well except it throws an error if the operator is + or / or *.  Works fine if operator is - or x

**Comment by HamishBrownPFR** [comment]
Below the DocumentMathFunction is docummenting a multiply of PhotoPeriodResponse X PpSensitivity where PpSensitivity is a variable ref.  It is writing the ref instead of the name in the equation which is good but then documenting the variable ref again.  Need something to stop it from docummenting variable ref children.  Not sure what happens with constants.  It could just include the value in the equation instead and not document that either.
![image](https://user-images.githubusercontent.com/7295858/105445122-03b5cb80-5cd4-11eb-8bed-0871adf72fe6.png)

**Comment by HamishBrownPFR** [comment]
@hol353 I am still having this problem.  The [DocumentMathFunction -] method works well except it throws an error if the operator is + or / or *. Works fine if operator is - or x

**Comment by hol353** [comment]
This is an old issue so closing. If this is still a problem then reopen.
