### ISSUE TITLE
Better include/exclude of models for AutoDoc needed

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6020]
Y'all know the frustrations. One solution might be to go explicit. This might be:

- an AutoDoc model that can be dropped at (almost) any point in the simulation. It contains a listing of all the models "below" it in the simulation and some way of selecting them to be included or excluded from AutoDoc. Some sort of multi-select to do this will be needed.
- an AutoDoc at a lower level overrides choices made above
- by default the selection (completely new AutoDoc UI or new model added to the simulation) is "on" and apply "on" if there is no AutoDoc model added by the user

**Comment by hol430** [comment]
I'm going to tentatively close this, as the autodocs are now very different to how they were in January. Most models are now never documented (ie clock, zone, fertiliser, ...). Other models are documented sometimes, depending on their position in the simulations tree. E.g. a plant model (wheat) is never documented if it's under a simulation. But it is documented if it lives at the god level (as in the Wheat.json resource file).

Hopefully the new system solves some of the problems of the old system, but feel free to reopen this if need be.
