### ISSUE TITLE
Stock Sprint - units

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6021]
All the variables in the model need a units tag (e.g. as below) so that the users can find them in the description (e.g. https://apsimdev.apsim.info/ApsimX/Releases/2021.01.19.6016/Stock.description.pdf). 

@her123 - assigning this to you - hope that OK.

@hol353  - can you confirm that this will also have the units show up in outputs and in tool tips?

       /// <summary>
        /// Gets the age of unweaned young animals by tag number
        /// </summary>
        [Units("d")]

**Comment by her123** [comment]
Yes. Good idea. There are still a few properties that need units.

**Comment by her123** [comment]
Some units still incomplete
