### ISSUE TITLE
Stock Sprint - Stock 1 added a section (memo) in the auto-generated documentation describing the basic option

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6022]
Stock 1  "We have added a section (memo) in the   auto-generated documentation describing the basic options "

**Comment by MarkLieffering** [comment]
A new high level memo named "Simulation Overview" has been added after the Title Page memo. The new memo points users to the list of parameters and variables in the auto-generated APSIM Next Gen documentation as follows:

Overview

These simulations are a validation of the Stock model in APSIM Next Gen. A description of the validation dataset can found in the "Description" memo of the "Validation" node. Descriptions of the two validation simulations ("LUDF" and "StockSlurp")  can be found in the memos of the respective simulations.

The parameters and variables that can be specified in the Stock model are in the auto-generated APSIM Next Gen documentation which can be found at https://apsimnextgeneration.netlify.app/ under the "Model documentation" link; the "Stock" model is near the bottom of the first table.
