### ISSUE TITLE
Met UI is not informative enough

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#603]
We spent much of a project workshop developing and testing input data, including met data.  The met UI in APSIM7.7 is much better for debugging issues relating to met data.
1) Met UI in APSIMx does not include radiation data in the table of data values.  This table should include anything in the file.
2) The APSIM7.7 UI provided graphs of rainfall, temperature and radiation etc, including estimates of clear sky radiation values.  This are invaluable for debugging issues WRT met data.

**Comment by hol353** [comment]
Same as #495
