### ISSUE TITLE
Pinus

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#6058]
Improving the Pinus model

**Comment by sarahcleary** [comment]
@APSIMInitiative/forestry-and-agroforestry - FYI

**Comment by sno036** [comment]
@sme016  - @hol353 and I just discussed this to get it moving for you. Can you disable (leave it in the file but get it crossed out) the grazing test for Pine and do a pull request for it? Dean is a little way away from having the new way of specifying grazing sorted and the grazing test can be reenabled after that.

@hol430  - see above. Once Philip has disabled the grazing test the simulation should run to completion and then can you move it into release (Philip doesn't know what to do there). If you need additional information @hol353 will assist. Some urgency as there is a training workshop soon. 

OK everyone?

**Comment by hol430** [comment]
If you want, I can disable the grazing test and move this into the release in one fell swoop.

**Comment by sme016** [comment]
I'd be happy to remove grazing, but that is unnecessary as that (pre-)test didn't make it into the the Pinus validation that I committed. The Pinus validation and example simulations currently released are good for now, as far as I am concerned. I'll be happy to put a stock sensibility test into the validation after we get that working properly. Thanks

**Comment by jbrider** [comment]
Apologies @sme016 I told you via email that I would follow this up and I got sidetracked.
Thanks @sno036 for following up.
As all of the requests have been addressed and people have had time to comment I think this is now right to be put into release.
