### ISSUE TITLE
Units of outputs in APSIM Next Generation

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#606]
Users struggle to determine the units of outputs recorded in reports in APSIM Next Generation.  It would be good if the units could be captured and displayed where possible to inform users.
(e.g. users were not aware that grain weight was in g/m2 and soil N was in kg/ha, etc)

**Comment by hol353** [comment]
@zur003 Can this one be closed?

**Comment by zur003** [comment]
Yes, I think so. There is more work that could be done to improve the way units are handled, but I think that would best be done under a different Issue.
