### ISSUE TITLE
Difficult to see data when looking at reports in UI if you are running multiple factorial experiments

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#607]
In the UI, if you look at the data within your data's report viewer the UI puts a freeze payne thing between the simulation name, factors, zones, and date, etc.  When working on a laptop you find that this only leaves enough screen space for the user to see one column of data at a time.

**Comment by HamishBrownPFR** [comment]
The main problem here appears to be there are a couple of factor name columns to the left of the freeze pain that are the same factor regardless of the experimental scope.  See Screen shot.  The report in view does not have Popn or Fert treatments.  Need to inforce an order where SimName is first column, date is 2nd and columns to the right of this scroll

![image](https://cloud.githubusercontent.com/assets/7295858/17273222/8cd9c980-5701-11e6-9a7d-908faff02b63.png)

**Comment by hol430** [comment]
Is this still an issue? I have not had any problems on a (n admittedly high-resolution) laptop. The Popn and Fert columns are also not appearing for any of the experiments/simulations I've tried.

**Comment by hol353** [comment]
Yes this is still a problem. Use your surface pro screen and look at a report for an experiment with several factors. The fixed columns take up most of the screen.

**Comment by zur003** [comment]
Should now be resolved.
