### ISSUE TITLE
conversion of apsim 7.8 file to apsimX

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/ApsimX#6076]
Dear ApsimX users 

From the apsimX user interface, I imported an old apsim file (v7.8), but the imported file could not run successfully in the apsimX with outputs not being generated. By the way how to output Zadok stage 55 (mid heading) in apsimX?

Thanks in advance!

qunying

**Comment by Chloe0317** [comment]
Hi Qunying,

When importing, you'll need to edit the manager script and change the reporting variables to the apsimx format. I suspect these two will be the likely reasons. 
May I also suggest you to provide a minimal reproducible example please? e.g. a version of your apsim file and the error message should be helpful. 

Cheers,

**Comment by qluo02** [comment]
Thanks, Chloe for your feedback!
There is no error message during the running period but without any output. I did modify the output variables. Please see attached an example file in apsimX format after conversion from apsimV7.8. As I indicated in my last message, I would like to output key phenological stages such as beginning of stem elongation which corresponds to zadok stage of 30.

Looking forward to your help!
Thanks in advance!

Qunying

[cid:image002.png@01D6F652.8EE45C50]


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by qluo02** [comment]
Sorry I forgot to attach the sample apsim file in my last message!

Here you go!

qunying





Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Chloe0317** [comment]
Hi Qunying,

Unfortunately I cannot see your attachment. 
If you want to output Zadok Stage, you can do 

[Wheat].Phenology.Zadok.Stage
[Wheat].Phenology.CurrentStageName

in your daily report.

**Comment by sarahcleary** [comment]
[Boigneville.zip](https://github.com/APSIMInitiative/ApsimX/files/5907901/Boigneville.zip)

@Chloe0317 - please find @qluo02's file attached

**Comment by Chloe0317** [comment]
Hi Qunying,

After converting from classic to next gen, the manager script in classic is no longer applicable, so you'll need to edit them in the next gen format for it to actually work. In your manager script,  the green /* text */ code blocks are actually commented out. Since no wheat is sown, no output is produced.

A typical wheat sowing script can be:

```
using APSIM.Shared.Utilities;
using Models.Utilities;
using Models.Soils;
using Models.PMF;
using Models.Core;
using System;

namespace Models
{
    [Serializable]
    public class Script : Model
    {
        [Link] Clock Clock;
        [Link] Fertiliser Fertiliser;
        [Link] Summary Summary;
        [Link] Soil Soil;
        [Link(ByName = true)] Plant Wheat;
        

        [Description("Sowing Date")]
        public DateTime SowingDate { get; set; }
        [Display(Type = DisplayType.CultivarName)]
        [Description("Cultivar to be sown")]
        public string CultivarName { get; set; }

        [Description("Sowing depth (mm)")]
        public double SowingDepth { get; set; }

        [Description("Row spacing (mm)")]
        public double RowSpacing { get; set; }

        [Description("Plant population (/m2)")]
        public double Population { get; set; }

        [EventSubscribe("DoManagement")]
        private void OnDoManagement(object sender, EventArgs e)
        {
            if (Clock.Today.Date == SowingDate)
            {
                Wheat.Sow(population: Population, cultivar: CultivarName, depth: SowingDepth, rowSpacing: RowSpacing);    
            }
        }
    }
}

```

You'll need to edit all the manager scripts so that they conform to Next Gen manager scripts. 
Using existing scripts in apsimx examples usually helps!

More details on how to write manager script in APSIM Next Gen can be found [here](https://apsimnextgeneration.netlify.app/usage/writemanagerscript/)


Cheers

**Comment by qluo02** [comment]
Thanks Chloe for your help!

cheers

qunying

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by qluo02** [comment]
Dear All

Regarding the issues associated with the conversion from old apsim file to apsimX, I have fixed the scripts for relevant management info. But for outputting the day for specific zadok stages (e.g. beginning of stem elongation which corresponds to the zadok stage of 30), it seems very challenging in apsimX. Just wondering if there are any scripts for doing this job. I looked at relevant example files, but could not find any manager scripts which handle the reporting of the day for specific zadok stages.  Hope to get your support!   

Thanks with anticipation!

Best regards!

**Comment by Chloe0317** [comment]
Hi Qunying,

I believe what you want is ```[Wheat].Phenology.CurrentPhaseName``` in your reporting properties. 

This will output the different phenology phases, including "germinating, emerging, vernalising, stem elongation, head emergence ... ripening, ready for harvesting".

However, when I checked the Wheat json model script, the stem elongation phase is actually handled from terminal spikelet to start grain fill, with a stemFraction set at 0.7, while pre stem elongation is handled from emergence to terminal spikelet, with a stemFraction set at 0.2, with the "StemElongation" phase defined as the initial stage being TerminalSpikelet and final stage being FlagLeaf. So, your start of stem elongation phase will correspond to when ```[Wheat].Phenology.CurrentStageName``` outputs TerminalSpikelet.
 
I hope this helps!

Cheers!

**Comment by qluo02** [comment]
Thanks Chloe!
