### ISSUE TITLE
Stock's ME concentration calculations for Plantain (and perhaps other crops)

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6080]
See the attached simulation (and memo attached to Report).
[MEConcCalcTest.zip](https://github.com/APSIMInitiative/ApsimX/files/5884063/MEConcCalcTest.zip)

When the N concentration of the plantain is about 3% the ME concentration should be about 12-13. 

At present the heifers are eating about 3% of their body mass (close to maximum possible) and they are losing weight (should be gaining - maybe 0.75-1 kg /day).

The reported ME concentration is ~6 (not 12) so the loss in weight makes sense at that level but the ME of 6 given the N concentration does not.

**Comment by hol353** [comment]
This might have been fixed - or at least I'm not seeing the problem. 

AveBodyMass and AveConditionScore are both increasing and the AveMEConcIntake is around 11.3 (not 6 as stated in the comment above).

**Comment by par456** [comment]
Going to close this as @hol353 was not seeing it anymore 12 month ago.
