### ISSUE TITLE
Intellisense is slow

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6098]
The intellisense currently takes several seconds to load suggestions for stock outputs in report. This is partially due to the large number of outputs in stock, but it may be possible to speed things up. An option to disable intellisense has also been suggested. A list of most recently used outputs associated with a given model could also be possible.

**Comment by hol430** [comment]
To add to this, the intellisense popup doesn't appear to be working for a factor in an experiment referencing a model in the base simulation.

**Comment by hol353** [comment]
Just checked the time it takes to show intellisense for the stock model - about 1 second. Not too bad. Closing for now...
