### ISSUE TITLE
Remove old property UI

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6106]
The new property UI has been tested and is ready to go. We can phase out the old propertyPresenter/GridView and replace it with the new one.

**Comment by lie112** [comment]
I will have to update a couple CLEM presenters to point to the new one unless it is a direct name substitution. I am moving house today so can address this next week.

**Comment by hol430** [comment]
No problem. If it's easier for you then we can do a direct name substitution I think. @hol353 any preference here

**Comment by hol353** [comment]
I don't have any preference for which way you do this.

**Comment by lie112** [comment]
I'm looking into how Shaun created the CLEM PropertyTreePresenter, PropertyTablePresenter and PropertyTreeTablePresenters in Presenters/CLEM as I think he made copies of the old PropertyPresenter and added additional changes. These are used to create

![image](https://user-images.githubusercontent.com/19215637/106422358-fce24200-64a5-11eb-8bec-0fd7a06720ea.png)

and 

![image](https://user-images.githubusercontent.com/19215637/106422421-16838980-64a6-11eb-9494-a14acc4de457.png)

I was never really happy with this approach as it is not very flexible and wont take advantage of any improvements to the copied original presenter as we're seeing now.

What is the name of the new PropertyPresenter? 

I will have a look at whether I can just substitute the new property presenter or whether the modifications to the presenter would make it work for all. The standard CLEM wrapper with a property grid will be fine and we can always just leave the other detailed presenters there for now until I update them. If the new presenter no longer uses a grid we might be stuffed and a legacy of what we had to work with in early APSIM Next Gen development.

Likewise there's some duplication of Reports into CLEM reports based on Shaun's initial development. I wanted to make the Standard report a little more inheritable to create custom reports (e.g. dynamic creation of properties and events), but haven't had the time.

**Comment by hol430** [comment]
The new presenter is called SimplePropertyPresenter and the view is called PropertyView. The way they're used should be essentially the same as the old PropertyPresenter/GridView combo (just call .Attach() on the presenter and add the view's MainWidget to the parent view).

The first picture above looks like it's using the PropertyPresenter/GridView so I would imagine you could just change the type names of the presenter and view and it should just work. The second image won't work with the new property UI, as it doesn't look like it's using the PropertyPresenter. It might be possible to adapt it to use the PropertyView with a different presenter - or perhaps with some minor changes to the model's attributes it might be possible to use the SimplePropertyPresenter.

**Comment by lie112** [comment]
the second image is simply a multicolumn version of the old property presenter with a column for each model displayed. I'll see how the changes go.

**Comment by lie112** [comment]
There's a bit of work to do. I think you can switch everyone else across and I'll bring CLEM up to speed.
There are some CLEM display types (dropdowns) not currently supported
I need to add a couple lines to store and filter if needed filterByCategory and filterBySubCategory for the tree version.
Also previously the presenters were not wrapped in a named group box and so could be placed in any presenter. Is there a way to disable the named box. Maybe it is a property of the SimplePresenter
![image](https://user-images.githubusercontent.com/19215637/106535561-04552a00-653e-11eb-8c7b-2536d876169c.png)

**Comment by lie112** [comment]
Just learning all the new approaches such as filter and the new dropdown options to set custom drop down lists etc. This is what we added to previous version. The new version looks a lot cleaner.
I will try and transfer all CLEM use of property presenter and keep you informed of progress here.

**Comment by lie112** [comment]
Drop down completed and moved some logic back to CLEM.ResourcesHolder.
Is the grouping display part of the new sub-model property functionality added?
The code is much cleaner. I was even able to access the attrib variable to get all I needed. I also cleaned up my code in the proces.
I'll next look at fixing the PropertyTreePresenter to make it a wrapper for the new SimplePropertyPresenter and useful for everyone. I can explain how to use it later, but you add a category and sub-category attribute to each property.

**Comment by hol430** [comment]
Yeah, the sub models are displayed using the groups in the property class. That way if a model has a property which is itself a model, that "submodel"'s properties can be edited in the same property UI. There's some examples of this in ApsimX/Examples/Optimisation/CroptimizRExample.apsimx and ApsimX/Examples/Tutorials/PropertyUI.apsimx (in this file look in the script inside the folder).

**Comment by lie112** [comment]
I have updated the PropertyTreePresenter and it now works.
![image](https://user-images.githubusercontent.com/19215637/106560709-fd92db00-656e-11eb-949e-c6d5a14ddd5b.png)
I am not going to be able to get our table presenter to work with the new SimplePropertyPresenter moving away from a grid so  we'll leave the old CLEM\PropertyTablePresenter and CLEM\PropertyTreeTablePresenters there for now to do what the users need in the older styling.
I do not believe CLEM uses the old PropertyPresenter anymore. 
There are a number of other things still using it BiomassRemovalPresenter, GraphPanelPresenter, LinearAfterThresholdPresenter, ManagerPresenter, ProfilePresenter and TreeProxyresenter.

**Comment by lie112** [comment]
Is is possible to add a bit of padding between entry boxes (rows)?
I think it looks good with a row spacing of 3
propertyTable.RowSpacing = 3;  in PropertyView.DisplayProperties() 
![image](https://user-images.githubusercontent.com/19215637/106567312-2c15b380-6579-11eb-9b20-c25edca2a70f.png)

**Comment by lie112** [comment]
SimplePropertyPresenter issues

- loses focus if you use down arrows below last property in list

- If the top property in list is an enum, moving focus up the list past the top changes the value up the enum list. This is dangerous as arrowing around shouldn't really change values. Maybe an enter key (or mouse click for mouse users) on enum to start editing would be useful. 

Not sure if I should create small issues as I identify them with the new property presenter or include here.

**Comment by hol430** [comment]
Good catch on the arrow keys, I didn't actually realise the up/down arrows could be used for navigation here. Perhaps the easiest solution would be to disable up/down for navigation between text inputs? That way you could still use tab/shift-tab for navigation, and up/down to change the dropdowns if you wanted to, but it would be hard(?) to accidentally change the dropdowns via up/down arrows. It seems slightly unnatural to me that arrow keys shift the focus between the widgets here but if you guys think it makes sense to keep it, we could look at other options.

Agreed about the spacing on the entry widgets. This must be a result of the windows theme we're using, as they already have some vertical spacing in the adwaita theme that I'm running. When we move to gtk3 it will be a good chance to use a more modern windows theme. For now I'll add in that extra spacing on windows/mac builds.

**Comment by lie112** [comment]
I suggest the arrow keys is trying to mimic moving around a table (equivalent to spreadsheet) which I like. I'm pretty sure old school property grids allow up-down arrows to move around rather than tab/shift-tab which is usually used to move between widgets placed around the UI.
If I can work out how to easily add the additional columns to reproduce our table property presenter, then the ability to move left and right between cells would be great. I looked into it and just trying to find the simplest approach.. Maybe the SimplePropertyPresenter can be passed an single model or an array of Model objects (of same type). In the attach this is converted to a the array that is worked with from that point onward. A single item in the list produces the current outcome, while more than one produces columns (with a column header) so we can pass lists of models to the property presenter.
