### ISSUE TITLE
Need options to suppress summary messages from several models

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6112]
including: supplement, fertiliser, irrigation. They insist on reporting everyday and it makes it nearly impossible to find actual information. I often use a 'verbose' setting on manager scripts to turn off messages like these. Can something like that be added to most of the models. By default verbose is on an all messages (as is at present) go to the summary. User can set verbose to off and only genuine warning messages and errors get sent? (or some way to filter out the dross?)

**Comment by jbrider** [comment]
+1

**Comment by peter-devoil** [comment]
There are many logging packages which would let us to do better than "Console.WriteLine...", though not much more difficult.The sooner we make that change, the better.

**Comment by hol430** [comment]
Sounds like a good idea. That being said, there's already an option in the summary model to filter which messages are captured. Is this not sufficient?

**Comment by peter-devoil** [comment]
At the moment, there are warnings, errors, and the informative messages that are overwhelming. We could replace these 3 with a severity index ranging from fatal (highest) to debugging (lowest) - informative being somewhere in the lower half. Then the filtering gets a bit more flexible, especially if we can filter whingeing components.

**Comment by sno036** [comment]
The filtering that is there (actually, I am uncertain what it actually does - apparently nothing to the summary file I was looking at) does not filter out all the 'i did this today' messages that clutter up the summary file. It gets worse with multi-paddock simulations. A filter (in or out) by model (or field-model) would help. A filter that could also remove on a template (e.g. filter out all messages including the text "water added via irrigation") would be even better.

**Comment by hol430** [comment]
Currently, all messages written to the summary have a log level associated with them (info, warning, or error). We could add a drop-down to the summary ui which restricts which messages are shown. We could also add more log levels (e.g. debug?). We could also add an option to the summary UI to filter which components' messages are shown. When running the simulation, all messages would still be recorded as normal - these changes would be mainly at the gui level.

Would that fix the problems? Or do we actually want to be able to control which messages are recorded when running the simulation?

**Comment by jbrider** [comment]
So currently the options in the summary file only affect it the next time it is run?
Does that mean you have to change every summary file in files with multiple simulations?

I would assume that the option is there to be able to reduce the summary file size on large runs - so you would still need the option to restrict logging at runtime?

**Comment by hol430** [comment]
Yep - the current options in the summary ui only have an effect next time you run the simulation, and yeah you would need to go through your file and change them in every simulation. You could always put a 'master' copy of the summary under replacements and only change that one. But that seems like more of a bandaid. Adding an option to control this at runtime sounds like a useful feature, although I'm not sure of the best way to expose this in the gui. Actually there are quite a few options for running simulations which we expose in the cli but not in the gui.

**Comment by jbrider** [comment]
It doesn't look like it's working as expected?
If I turn off Capture Summary, it is still showing the summary messages after running.

Is there enough detail in the summary file component to be able to filter after the data is written?
If the existing checkboxes show/hide the levels it would work pretty well. 
I don't think it would need an extra level - that would probably require the models themselves to add extra outputs as well.

@sno036 suggestion of filtering models would be good - as would the template idea.

**Comment by sno036** [comment]
For a three-year simulation I got a file of over 10,000 rows in the summary file! What I really want (what I really really want!) is as attached but the functionality embedded in the UI.

[WhatIWant.xlsx](https://github.com/APSIMInitiative/ApsimX/files/5907693/WhatIWant.xlsx)

**Comment by hol353** [comment]
Yep. The spreadsheet of @sno036 would be great. I'd have another column for zone as well so that you can filter by zone. The simplest way to do this would be an export to EXCEL option.

**Comment by sno036** [comment]
I agree that it could be done in Excel but I can already do that and it gets tedious for run after run. How difficult would it be to build the filtering into the UI?

**Comment by hol430** [comment]
Filtering in the gui via a couple of dropdowns would be easy enough. If you want it in the tabular format like in Excel that's not impossible but would be a bit more work - and we don't have as much screen real estate in that right-hand panel so it might not work too well anyway. Adding an export to excel feature would be easy but as you say, probably not really ideal if you're frequently making changes and re-running your simulations.
