### ISSUE TITLE
Report tables do not automatically display

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6115]
The report data does not display when selected. The dropdown list of available tables is filtered to only the report selected, but the user has to select this list and the table item for data to be displayed.
Was this a workaround for reducing the CPU load on reports? Previously the data was displayed when selected and users looking at lots of data could move between reports without having to select the table to display each time.

**Comment by hol430** [comment]
This was changed deliberately to reduce the load time for the right hand panel when clicking on report. There was talk about only loading the first hundred (or so) rows instead of loading nothing - but it will depend on how fast it is to do so.

**Comment by lie112** [comment]
Are other APSIM users using the data tab of their report to investigate all model output. CLEM is generating large output tables and so an improved means of display was previously suggested. Maybe a .Take(100) would suffice for now and we can implement autoload as we move down the data table later. Async data loading is also an option.
Relates to #5530 #5016

**Comment by sno036** [comment]
@hol353 @hol430 - could this get bumped up the priority list?

**Comment by hol430** [comment]
Well this was deliberately changed (#5530) to make the report ui faster to load in cases when you only want to change a few variables. Perhaps we could go back to the old behaviour, but not populate the data tab until you click on it.

**Comment by sno036** [comment]
Sounds like a possible solution. Or if that is slow then automatically load the first 1000 data items with a button to get the rest?

**Comment by lie112** [comment]
I have implemented on tab click refreshing of CLEM components (in the CLEMPresenter) with IRefreshPresenter and also remembering the last Tab selected for the user and so the data display may be the selected tab and so needs to be propagated with at least the screens worth of rows when the presenter is attached.

**Comment by hol430** [comment]
This is fixed in the latest version.
