### ISSUE TITLE
Y Axis Labels

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#6122]
Recent changes have changed the Y Axis labels to be concatenated with new lines rather than comma's.
2cfe71a - Merge pull request #6018 from hol353/chart-axis-units

If this is the new preference, can we add an option to override it?

![image](https://user-images.githubusercontent.com/635772/106690200-1c4fab00-661d-11eb-9fb2-f13564064f1b.png)

**Comment by hol353** [comment]
The change was made so that the axis titles were visible in the documentation. A reviewer of soybean asked for it I think. We can make it a setting on the axis presenter / view.

**Comment by jbrider** [comment]
A setting would be good - I don't hate the new way, but we have panels of graphs where space is at a shortage and it just won't work well. 
From the image above, you can also see the legend either uses quite large margins - or is set to stay inside the axes - is there some config that would let that go to the edge of the panel?

**Comment by hol430** [comment]
If you double click on the legend you'll find a few options for the placement and orientation.

**Comment by jbrider** [comment]
Playing with the options, it still stays within the axis boundaries.
Not asking for a change to the legend - just raising the issue in case there was an easy fix.

**Comment by hol430** [comment]
There should be a checkbox which controls whether the the legend is inside or outside the chart area, does that do what you need?

**Comment by jbrider** [comment]
It will let the legend be displayed above the top of the chart, but still contains it within the left and right axis - at least that's what it did on mine.
If the left axis label is only 1 line deep, it won't be worth the effort to gain back a few pixels.

**Comment by hol430** [comment]
If you double click on the axis title, you can type in your own custom title - does that fix the problem?

**Comment by hol353** [comment]
Is this still an issue? The only thing I can think of is to add another checkbox on the graph series view that says something like 'Single line axis title? e.g. at the bottom of this screenshot:

![image](https://github.com/APSIMInitiative/ApsimX/assets/1943827/bfeb4747-1672-492e-b0fc-6286225710de)

Would this be helpful?

**Comment by jbrider** [comment]
Single line axis title would solve the issue.
