### ISSUE TITLE
Can we have an option to change size of regression equation on plots?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#6125]
An option would be helpful to:

Change size of regression equation
Change size of regression statistics.

**Comment by BrianCollinss** [comment]
An option would be helpful to:

- Change size of regression equation
- Change size of regression statistics.

**Comment by hol430** [comment]
Can you send a screenshot showing the problem?

**Comment by BrianCollinss** [comment]
It's a general thing. I thought having options to relocate and resize the box of regression equation and statistics would be really helpful, especially as the box and texts are small and too close to y-axis.
