### ISSUE TITLE
Remove Output Leaf Tallness

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#6131]
The leaf class has a fuction called "Tallness" - the reviewers for models have enquired as to whether this is height. 
This should be removed as it duplicates other properties, is confusing and the name is not ideal.
@jbrider @hol430 I think this was added as part of the Sorghum work. Are you able to refactor this?

**Comment by jbrider** [comment]
@hut104 We don't have anything called Tallness in sorghum, so very much doubt that we added it to Leaf.

**Comment by hut104** [comment]
Sorry, Drew said that he had implemented it and I’d assumed it was part of that work.  It was some other refactoring.

**Comment by hol353** [comment]
I'm looking for a pattern to resolve the problem of having the a naming clash between a property and a child function. Currently we have:

```c#
[Link(Type = LinkType.Child, ByName = true)]
private IFunction tallness = null;
...        
public double Height { get; set; }
...
Height = tallness.Value();
```

Can we adopt a pattern of naming functions with a 'Function' suffix. Many functions already do this. This will avoid the naming clash and it makes it clear to the user in the GUI what is a function (a model that calculates something) and what is a state variable. The code above would become:
```c#
[Link(Type = LinkType.Child, ByName = true)]
private IFunction heightFunction = null;
...        
public double Height { get; private set; }
...
Height = heightFunction.Value();
```

- the property is given a private setter
- the property is given a [JsonIgnore] as there is no need to write the value of Height to the .apsimx file. 
- If the property isn't needed as a reportable variable to the user or made available to another class then it should be a private field.
- properties should never calculate anything 'on the fly'. Profiling has shown that 'expensive' properties (e.g. ones that call a child function.Value in their getter) can have a big impact on runtime speed. They should be given a value in a method somewhere. In the above example Height is assigned a value once in the _OnDoPotentialPlantGrowth_ method.

This coding guideline should be documented somewhere (e.g. https://apsimnextgeneration.netlify.app/development/software/modeldesign/)

**Comment by HamishBrownPFR** [comment]
It was me!!!  I added tallness.   It use to be called HeightFunction but it was decided that we did not want function suffixes.

If we are going to add suffixes would it be better to do it in the code where fewer people will be exposed to it.  What about a suffix to show which interface properties are in.  CanopyHeight for instance for something that is in ICanopy?
