### ISSUE TITLE
Resetting and uploading personal Soils.Soils file in apsimX

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/ApsimX#6138]
Dear apsimX users

I used "Reset on sowing" & "Reset on date" in apsimX. Neither did not work. The error message is  
"can't find a match for link nutrient in model Mery.Field. Reset on date.Script".

Another query is how to upload my own soil files to ApsimX user interface?

Thanks with anticipation!

qunying

**Comment by hol430** [comment]
I'm guessing you're using soil nitrogen rather than nutrient. If you delete soilN from under the soil node and add a nutrient node to replace it, then that should fix this problem, although potentially it could break other scripts. If you upload your .apsimx file I can give more specific advice.

**Comment by qluo02** [comment]
Thanks Drew for solving the reset issue! It worked now. 

In my last message, I also asked how to upload my own soil files to ApsimX user interface? If you can help that would be great! :)

**Comment by hol430** [comment]
In theory, an individual soil can be pasted directly into the gui, but if it's wrapped in some other xml we may need to tweak it. Could you upload one of your soil files to this issue?

**Comment by qluo02** [comment]
Hi Drew

The soil file is actually based on the APSOIL database (APSRU-Australia-Soils.soils.txt) but with crop root parameters estimated and inserted in for more locations. Juts wondering how to upload the modified soil database onto the apsimX GUI. 

Thanks in advance!

**Comment by hol430** [comment]
What happens if you try the "import old .apsim file" option to open this file in next gen?

**Comment by qluo02** [comment]
Thanks Drew for giving me the hints! This maybe the way forward.
