### ISSUE TITLE
Depth column in soil UI is too narrow by default

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6141]
The depth column in the profile grids shown by most soil components (physical, sample, etc) is too narrow by default and should be made wide enough that the contents are visible.

**Comment by zur003** [comment]
My "installed" version (the latest currently available - 2021.2.8.5854) is displaying depths as expected, but my self-compiled version "hides" the depth column by apparently giving it a width near 0. This happens with both Frameworks and Core builds. That suggests that: (1) updated builds haven't been "released" for the last 10 days or so, and (2) this problem developed at some point in that interval. 

Also, for what it's worth, scrolling of the profile grid doesn't seem to be working correctly in the Gtk3 version.
