### ISSUE TITLE
Limited transpiration rate module

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#6151]
Details in: Limiting transpiration rate in high evaporative demand conditions to improve Australian wheat productivity 
https://doi.org/10.1093/insilicoplants/diab006

**Comment by hol353** [comment]
@APSIMInitiative/cereals @APSIMInitiative/legumes @APSIMInitiative/other-crops

**Comment by hol353** [comment]
@kchenu This has now been merged into the release. It is now an option that can be turned on if the user is interested. We have created an example simulation where this demonstrates how to turn it on:  Apsimx/Prototypes/LimitedTranspirationRateWheat/LimitedTranspirationRateWheat.apsimx

**Comment by hol430** [comment]
I guess that would depend on your definition of "in the release" since the prototypes aren't distributed with the official builds.
