### ISSUE TITLE
Three days with TMin>TMax in WaggaWagga.met

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#6153]
![image](https://user-images.githubusercontent.com/39573622/107773408-593c4000-6d89-11eb-9359-2861bca02cb8.png)

I found this when running **Stock.apsimx** after I added a module that was sensitive to this issue. It seems by default there is no check for such issues, at least in **Stock** modules.

**Comment by BrianCollinss** [comment]
Same in **pendletonAPSIMtav.met**:

![image](https://user-images.githubusercontent.com/39573622/107893349-5fdbda80-6f76-11eb-8d71-8614aeea2b7d.png)

**Comment by hol353** [comment]
Add some checks into weather.cs for maxt > mint, radn > 0, rain > 0, consecutive days etc. This should happen as the data is read in one day at a time (as opposed to checking the weather file up front - too slow).

Once the checks are in place, run a simple simulation over all weather files in Examples\WeatherFiles to make sure they are ok.
