### ISSUE TITLE
If a Resources file is updated, file must be reloaded to take changes in

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#6155]
When I changed Wheat in Resources folder, I had to close and re-open the apsimx file so APSIM adopt the changes. Is this intentional?

**Comment by hol430** [comment]
The resource files are embedded inside Models.exe, so you actually need to compile apsim in order for any changes to have an effect. So yes it's deliberate, but re-opening the .apsimx file by itself should be insufficient to apply any changes (I would have thought).

**Comment by BrianCollinss** [comment]
I just tested it and just needed to be reopened!
