### ISSUE TITLE
Can't go to bottom of Download Weather dialog

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#6157]
When using the Download Weather option in the GUI on my laptop, I can't work down to the bottom of the dialog to complete the inputs required. Whereas all is visible and working on a bigger screen.

**Comment by hol430** [comment]
@sme016 - there should be a scrollbar on the popup window. Is that not appearing for you? If so, which version of apsim are you using?

**Comment by sme016** [comment]
Sorry, I can’t see the scrollbar for the dialog box (see screenshot below). However, I notice that if I connect a second screen, the image on the laptop is compressed and all is visible. In the latter case the scroll bar is still not visible, but I wouldn’t expect it to be.

This is using a standard issue laptop and the most recent version of next gen.

Thanks,
Philip

[cid:image001.jpg@01D706D2.96BC7170]

**Comment by sme016** [comment]
I still have this issue, but I have now discovered that I can resize the dialog box to invoke the scroll-down bar, then I can see the OK button at the bottom. So the issue might be one of auto-resizing of the dialog box for different screen sizes.
