### ISSUE TITLE
Summary files not showing in GUI

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#6160]
Drop down to select summary file has simulation names in it but nothing is showing in the view.  Have seen this with three separate users all working with most current build.  Does not seem to be specific to anything, not showing is all .apsim files I have looked at

**Comment by Chloe0317** [comment]
I have the exact issue. Not able to see any summary files from my .apsimx simulations. @hol430 Drew, do you know what might be going on here please?
Thank you very much!

**Comment by hol430** [comment]
Definitely a bug. Fixed by #6168.
