### ISSUE TITLE
Many of our .apsimx files are not culture-friendly

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6163]
Many of the .apsimx files in this repository fail when run under culture settings that are not en-AU.

**Comment by lie112** [comment]
What aspects of the apsimx file cause the issues? Number, date formatting? If I know I'll have it in my head for further development.

**Comment by hol430** [comment]
Yep, date and number formatting mainly. The problems that I found today have all been with manager scripts which are converting strings to dates, or reading data (including dates) from a separate csv file. The easiest way I've found to test files is to just modify `ApsimNG/Main.cs` and add something like this (this will use a german locale but you could use others):

```csharp
System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("de-DE");
```

**Comment by hol430** [comment]
Re-opening this issue. Many of our validation files give different results when run under the invariant culture:

- Barley
- Chicory
- Maize
- Plantain
- RedClover
- Wheat
- WhiteClover

In most cases this is due to converting strings to DateTimes without specifying a culture. Please don't do this.

**Comment by hol430** [comment]
Closing as fixed (as far as I can tell).
