### ISSUE TITLE
Predicted/Observed Date format

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#617]
In Tests/Slurp.apsimx the predicted/observed object is not generating a table. I think the problem is due to the format of the date column which is being used for matching with predicted data. This format does not seem to worry the graph object which is able to graph this data from the observed tables correctly. I have tried different things with the format in the excel sheet that the observed data is being read from but nothing seems to work. The wheat test also uses the excel reader to create an observed data table and it does not change the date format but I can't work out why it is working and the Slurp one is not.

I need to get this working to set tests for Slurp

![image](https://cloud.githubusercontent.com/assets/7295858/12763219/137b68fe-ca58-11e5-8892-26f46f735ad3.png)

**Comment by hol353** [comment]
You're not going to believe this but if you save your .xls observed file as a .xlsx file it will work. Looks like the older .xls file reader is limited in their handling of dates.

**Comment by HamishBrownPFR** [comment]
Thanks Dean, converting files to xlsx fixes the issue.  However, I suspect others will fall into the same trap.  Do we need a message appearing on the excel file reader view noting that files need to be in xlsx format?
