### ISSUE TITLE
Mapping should be improved

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#6171]
The current map only works at a world scale, has outdated national boundaries, and indicates points a bit inaccurately. It should be improved.

**Comment by hol430** [comment]
Reopening this, as maps in autodocs don't appear to be working.

**Comment by zur003** [comment]
It appears that OpenStreetMap maps are no longer being retrieved. I have no idea why. Modifying the source code to use Bing maps works correctly, so it appears to be some change (or failure) in the server providing the OpenStreetMap tiles. In the GUI, if the OSM maps can't be retrieved, it falls back to the old out-of-date world map, which is embedded as a resource.

I'd like to add an option to allow the user to select the base map for the range of maps available through BruTile. This could be a drop-down list.

**Comment by hol353** [comment]
This issue is very old. Closing for now. Reopen if more work is needed.
