### ISSUE TITLE
Review Grape Vine Model

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#6175]
@APSIMInitiative/reference-panel 
With a final push this week we (@junqi108 @ed2014 @rcichota) have got the Grape Vine model to a state that we think is suitable for release.  The bulk of the work for this has been logged against #1822 and we will close that issue and move the validation set from prototypes into UnderReview.
The Grape vine model is built in PMF and some new functionality was introduced to facilitate its completion, most notably a alternative arbitration approach that partitions structural and non-structural fractions simultaneously.  It contains phenology that goes from dormancy through vegetative and reproductive growth and back to dormancy each year.  Its predictions of Berry yield integrate climate and management factors that accumulate effects over a 18 month period prior to each harvest.  As well as predicting the usual yield, water and N uptake, it also has functions to predict berry composition that influence wine quality.
All of the validation experiments are set up as multi zone strip row simulations with a row growing grapevines and an alley growing grass simulated with SLURP.
The validation currently only covers New Zealand Data sets and the parameterization of cultivars only covers cultivars relevant to NZ.  There are more important grape growing regions around the world and ultimately the model should include validation from Australia, Americas and Europe.  However, we the model itself is sufficiently complete to justify Release which will help to facilitate further testing and improvement.

**Comment by hol353** [comment]
Why have a separate GitHub issue? I would prefer to have all commits dealing with the grape model release under one issue.

**Comment by HamishBrownPFR** [comment]
@hol353 Good Question.  I was thinking it would be cleaner to have the review on a separate issue.

**Comment by hol353** [comment]
The RP development plan has the original vine issue on it. Probably best to keep that same issue. Can you transfer the text in the top box into  #1822 and then close this one?

**Comment by junqi108** [comment]
done
