### ISSUE TITLE
read only status not being saved

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#6190]
If I copy a read only component (from Show Model Structure on a crop) and paste it into the replacements tree, I couldn't move it up or down the tree  - with a read-only error appearing in the status bar below.
Toggling the read-only status via right-click did not allow it to move.
Attempts to delete it also resulted in errors.

The component had a child node - possibly related?
It looks like toggling the parent's status does not appear to actually change the read only state in this situation. 
Right clicking on the copied node shows read-only=true -> toggling the read-only off via the right click and then right clicking again would show the read only status as false as expected.
But then clicking away onto another node and back again and then right clicking would show the read-only status as true.

**Comment by hol430** [comment]
This seems to be working for me, although there have been some changes to the toggling of a model's read-only/enabled status recently. Could you pull from master and double check that this is still happening for you? In my testing, toggling read-only on and off seems to be working ok.

**Comment by pjinnes** [comment]
I have a similar problem trying to add a node to the Wheat phenology and, even though I have toggled read-only to off, I get and error saying "unable to modify Phenology, it is read-only". When I select other nodes the read only enabled status on phenolgy gets set again.
![read-only](https://user-images.githubusercontent.com/68268897/143509546-b3dcb51b-3522-4e8a-9b02-9ee8e4da7980.jpg)

**Comment by hol430** [comment]
Making changes to the plant models is intentionally difficult. Normally you need to be explicit and copy the whole plant into a replacements node, and make your changes there.

**Comment by hol353** [comment]
I can't reproduce the original problem of moving/deleting/enabling/disabling a model under replacements.
