### ISSUE TITLE
Copying and pasting the peanut model doesn't seem to work

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6192]
In the attached file the surface organic matter model is throwing an exception 'residue type not found'. The reason is that it is looking for a residue type of null. That is coming from Plant.PlantType property which is also null. In an attempt to fix this, I copied the peanut model from prototypes\peanut.apsimx (which has PlantType correctly set) but the PlantType seems to be set to null upon pasting into the EthiopiaPeanutMaizeChickpeaMaize.apsimx and the exception is still thrown. I don't know what is causing this.

[EthiopiaPeanutMaizeChickpeaMaize.zip](https://github.com/APSIMInitiative/ApsimX/files/6032031/EthiopiaPeanutMaizeChickpeaMaize.zip)

**Comment by hol430** [comment]
Ok I've fixed this particular bug, but the resource model serialization rules are rather opaque and I expect we will continue to discover little edge cases like this in the future. We should rethink the design of this feature.
