### ISSUE TITLE
Possible to modify crop genetic coefficnets?

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/ApsimX#6194]

**Comment by hol430** [comment]
Duplicate of #6195.

**Comment by qluo02** [comment]
Dear apsimX users

Just wondering if possible to modify crop genetic coefficients for sensitivity studies in ApsimX. If yes, how? Unlike apsim classic crops models, the relevant crop models are inaccessible for users in apsimX. 

Looking forward to your great support!
