### ISSUE TITLE
Possible to modify crop genetoc coefficients?

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/ApsimX#6195]

**Comment by sarahcleary** [comment]
https://github.com/APSIMInitiative/ApsimX/issues/6194#issuecomment-784630236:
Dear apsimX users

Just wondering if possible to modify crop genetic coefficients for sensitivity studies in ApsimX. If yes, how? Unlike apsim classic crops models, the relevant crop models are inaccessible for users in apsimX.

Looking forward to your great support!

**Comment by qluo02** [comment]
Dear apsimX users

Just wondering if it is possible to modify crop genetic coefficients for sensitivity studies. if yes, how? Unlike Apsim classic, it seems that users have no access to crop models in apsimX. 

Looking forward to your great support!

**Comment by hol430** [comment]
@qluo02 you will need to add a replacements node in your file, and then add the crop to the replacements node. To do this, right click on simulations -> add model -> replacements (in the core folder). Then right click on replacements -> add model -> (add your crop - it's probably in the PMF folder).

Any changes to the plant in replacements will affect all other plants in the file. You should also be able to view the full structure of the plant under replacements.

**Comment by qluo02** [comment]
Many Thanks, Drew!

**Comment by byzheng** [comment]
@qluo02 For sensitivity analysis, my practice is to add replacements as @hol430 suggested. 
* Setup a template 
* Add replacements model,
* Create virtual cultivars for sensivitity analysis
* Add a new factor cultivar under factor model

All the operations above can be finished through script. Functions in https://rapsimng.bangyou.me/ might be helpful for you.

**Comment by qluo02** [comment]
Bangyou, you are so helpful!

**Comment by byzheng** [comment]
@qluo02 Some example codes might be useful for you: https://rapsimng.bangyou.me/articles/sensitivity.html

**Comment by qluo02** [comment]
Thanks Bangyou!

Cheers

qunying



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
