### ISSUE TITLE
Add a post simulation tool to send a datastore table to SQLServer

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6213]
This is useful when running APSIM on compute clouds where each nodes writes the important data to a central database.

The tool needs to allow the user to specify one or more DataStore table names to send to the database.

**Comment by hol430** [comment]
Wouldn't it be more efficient to imlement the appropriate interfaces (IDataStore/IStorageWriter maybe) so that you can just write directly to the remote database?

**Comment by hol353** [comment]
I did that and it does work but it is very slow. For my use case I only need one table (probability table) and not _Simulations, _InitialConditions, _Messages, Report etc. In the end I decided to do it as a post simulation tool - much simpler and runs much quicker.
