### ISSUE TITLE
Issue on VS2015

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#6220]
This is what I see on VS2015 in a freshly-cloned project.

![image](https://user-images.githubusercontent.com/39573622/109888089-a5b2d580-7cce-11eb-8482-708427c156d7.png)

**Comment by hol430** [comment]
@BrianCollinss you will need visual studio 2019 or newer to build latest apsim. We dropped support for vs2015 over a year ago I believe, and 2017 a month or two ago. If the download size is a concern, you could use VS code after installing the appropriate SDKs.

**Comment by BrianCollinss** [comment]
Oh. Sorry for being so behind in the game ;) Cheers.
