### ISSUE TITLE
Memory problem when exporting large datastores to csv

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#623]
We will run into this now the factorial approach enables easy propagation of simulations.  Lots of long simulations with user wanting to do some additional aggregation and comparison with other results that is not currently possible in the UI

![image](https://cloud.githubusercontent.com/assets/7295858/12969117/960d19b4-d0e0-11e5-8fa3-dd41e820fe09.png)

Not sure how we address this.  Restraint in good, doing things in the GUI is also good but there will be occasions when both off these are violated.

**Comment by HamishBrownPFR** [comment]
Need to alter report generation to work line by line rather than reading all data into memory

**Comment by hol353** [comment]
Can you attach your overseer.apsimx file as a way for me to reproduce this?

**Comment by hol353** [comment]
I have removed export to CSV menu option. Too slow. Memory intensive.Use the Export to EXCEL instead.
