### ISSUE TITLE
Report does not show [Clock].Today unless an alias is used

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#6244]
![image](https://user-images.githubusercontent.com/39573622/111054953-85e49400-84bc-11eb-8248-c08c23605eb4.png)

![image](https://user-images.githubusercontent.com/39573622/111054968-b1677e80-84bc-11eb-95b0-ee10338c0125.png)

**Comment by hol430** [comment]
Looks like you just need to drag the splitter to the right - the question is why is the splitter so far to the left. Are you running latest code?

**Comment by BrianCollinss** [comment]
Oh! That was interesting. Yes, it was hiding!!! I am on the latest code.

**Comment by hol430** [comment]
Yeah this looks like the same problem as #6141. I'm unable to reproduce the problem with the wheat example - it's working fine for me. Can you tell me what is the most recent commit in your local repo? Maybe worth uploading your apsimx file too, perhaps it's a problem specific to the combination of outputs in your report.

**Comment by BrianCollinss** [comment]
My local branch is at:

```
Commit: ee4e0c71f928189f493624a5626ff098072871ad [ee4e0c7]
Parents: 18f4d214dc, 99abe7e847
Author: Dean Holzworth <Dean.Holzworth@csiro.au>
Date: Friday, 12 March 2021 12:40:26 PM
Committer: GitHub
Merge pull request #6234 from MikeStower/pivot_table
Rebuilt PivotTable into ReportPivot
```

[Test.zip](https://github.com/APSIMInitiative/ApsimX/files/6137965/Test.zip)
Note that only the dirst simulation works in this file.

**Comment by hol430** [comment]
The datastore UI no longer uses the old GridView widget, so this is no longer a problem.
