### ISSUE TITLE
Report generation is broken

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#625]
When I try to view the "SummaryFile", it does not appear, but an error message reading "String was not recognized as a valid DateTime" appears in the status bar.

**Comment by hol353** [comment]
This was fixed yesterday I think. Can you pull from both APSIM.Shared and ApsimX and try to reproduce the problem?

**Comment by zur003** [comment]
Pulling the latest APSIM.Shared source fixed the problem. I will close this issue.
