### ISSUE TITLE
I can't see terms of Apsim license when I upgraded

### ISSUE THREAD

**Issue by yacobbeletse** [APSIMInitiative/ApsimX#6251]
While upgrading CLEM this morning, I could not see the terms of the APSIM license. Restarting my PC also could not fix the issue. Is this a bug?
![terms to Apsim license](https://user-images.githubusercontent.com/23515057/111239720-e22aed80-864d-11eb-9b02-58ef7c708422.png)

**Comment by hol430** [comment]
Definitely a bug, thanks for reporting it. This will be fixed by #6252 - so you should see a new upgrade available later today or tomorrow containing the fix.
