### ISSUE TITLE
Error if two soils in one zone

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#6256]
We spent time debugging a simulation that crashed after several years only to find that there were two soils in the zone.
There should have been an error at the beginning of the simulation.

**Comment by hol430** [comment]
Is your faulty .apsimx file in version control? I ask because this problem will probably be fixed by #5982, which also addresses problems like having both soil N and nutrient in the same simulation.

**Comment by hut104** [comment]
You can reproduce this issue simply by taking the Wheat example and duplicating the soil in the paddock.  It will crash after the first year of simulation with an error about decomposition (which is due to soil data becoming NAN)
