### ISSUE TITLE
Run current simulation with F5 from any model

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6257]
A user has asked if a quick run F5 to run can be allowed from any node selected rather than having to select a Simulation or Simulations node before right clicking and selecting run or hitting F5. I guess a smart system would know what level of run is to be performed (e.g. if an experiment is present, run the experiment)

**Comment by hol430** [comment]
Yep, it's not too high on the priorities list at the moment, but it would be nice. Related is #3810.
