### ISSUE TITLE
PMF doesn't have a mechanism to stop grazing of organs

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6258]
Currently the Gliricidia plants in APSIM (and other tree models) will have their stems (trunks) grazed when livestock is in the same zone as the tree. PMF doesn't have a mechanism the model developer can use to stop this from happening.

Organs in the AgPasture model have a property specifying an ungrazable amount of biomass. This could be used to achieve non-grazing of trunks. This approach could be adopted by PMF. Is there a better mechanism?

**Comment by hut104** [comment]
Wouldn't it need to be specified by stock if it is a generic damage thing?
Cows don't graze stems, but termites do.
Or, cows don't graze some organs that goats might.  Certainly, different animals have different preferences.

...and, it may be best not to complicate plant models with animal parameters.

________________________________
From: Dean Holzworth ***@***.***>
Sent: Tuesday, 16 March 2021 2:21 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] PMF doesn't have a mechanism to stop grazing of organs (#6258)


Currently the Gliricidia plants in APSIM (and other tree models) will have their stems (trunks) grazed when livestock is in the same zone as the tree. PMF doesn't have a mechanism the model developer can use to stop this from happening.

Organs in the AgPasture model have a property specifying an ungrazable amount of biomass. This could be used to achieve non-grazing of trunks. This approach could be adopted by PMF. Is there a better mechanism?

**Comment by hol353** [comment]
The stock model would need some way to determine whether something is digestible. Currently we have a digestibility property in the organ live and dead biomass classes. We could use that. I know plant modellers aren't happy with digestibility being in the plant models though.

Does it make sense for the consumer (animal) to maintain a plant organ (live and dead) x animal type matrix? I see problems with this approach as well (e.g. the list gets out of date when new plant models are added).

**Comment by jbrider** [comment]
Just to make it even more difficult - digestibility can also change over time.

**Comment by HamishBrownPFR** [comment]
A plant organ has composition which varies from plant to plant and over time.  This affects grazing preference and digestibility.  Grazing preference is a result of animal behavior which the plant knows nothing about.  Digestibility is a function of feed composition (Plant controlled), gut type (rumen vs simple) and physiological state of the animal consuming it which the plant also knows nothing about.  I would be tidier if the plant modelling activity focused on modelling the composition of organs correctly and animal modelling focused on when they will be consumed and how they benefit the animal.

**Comment by Keith-Pembleton** [comment]
I agree with Hamish, but plants do know something about grazing (predation) and try to avoid it through morphological adaptations like spines (might be beyond the scope of APSIM) and the accumulation of compounds that are bitter tasting or lead to physiological effects in the animal (eg ryegrass staggers).  Ideally we would have the plant model the components that contribute to digestibility (ie fiber fractions, fats/lippids, cell contents and sugars) and grazing preference (the protective compounds an morphology) and then the animal works out what it wants to eat and if it wants to eat it in the presence of other food sources.  This would be a massive research and model development undertaking but would ensure that plants could be eaten by any animal (e.g. cow, sheep, insect, elephant) without having the know anything about the animal eating it.  It is probably simpler for the plant or animal to maintain a table as Dean suggests.

**Comment by hol353** [comment]
I'm looking for a simple solution. I wonder if we should expose digestibilities and other grazing parameters to the user. 

Do we get the user to put a 'Plant Digestibility' node under the stock model for each plant model that is to be grazed? Each node would contain digestibilities for that plant organs. If no digestibilities are given for an organ then that organ won't be eaten. e.g.

![image](https://user-images.githubusercontent.com/1943827/111543398-baa76280-87be-11eb-9d8e-cf4f174e0159.png)

Perhaps we could also put in whether the plant is leguminous. The downside to this approach is that the user has to know what organs a plant model has. This could be overcome by having a toolbox of these nodes. Perhaps an upside is that the user has to think about digestibilities of plant parts, something that was hidden away in the source code.

I'm interested in what @sno036 thinks about this.

**Comment by sno036** [comment]
@hol353 - I think I like this as a direction (but would like to discuss). Can the organs be discoverable or prepopulated with possibilities in some way? Can warning messages be added if there are crops in the simulation with no matching component under Stock? If we want to get fancydancy (this has to be read with an Australian accent) can the fixed value be replaced with an expression. I think that would futureproof the design.

**Comment by her123** [comment]
The digestibility may be associated with the animal but it is not meant to be static through the growing season. It would be driven by the state and environment around the plant (not just age). This makes it problematic trying to get something generic that is dependent on plant and animal. Would it be possible to have a property of the plant which is the animal that could eat it. Then the plant queries the animal to find out something about the digestibility? The plant could then model the digestibility based on that animal. Or it is conceivable that the animal could request the pool aging details from the plant to adjust the digestabilities?

**Comment by hol353** [comment]
What we're trying to achieve is to remove all knowledge of animals from the plant models. We do want the flexibility of being able to change digestibility of organs during a simulation.

After discussing with Val, here is the next iteration of a screenshot of the GUI.

![image](https://user-images.githubusercontent.com/1943827/111563896-8c3c7e00-87e4-11eb-848c-f6a16426ee92.png)

After specifying an animal type and a plant type combination the user enters organ specific numbers.

For Live and Dead for each organ the user specifies digestibilities. We also let the user change the percentage of each organ's live and dead pool that the animal is allowed to eat. This will allow the user to say that animals can't eat trunks or that they can only eat 30% of the stolons of white clover (because not all of stolons are accessible to a given animal). These numbers will all be prepopulated with defaults. We will also allow an expression to be entered into any of the boxes to allow digestibility to be a function of any APSIM variable.

This will provide a lot of flexibility that doesn't currently exist and it will tidy up a lot of code in the plant models. Is there a use case that can't be done with this proposal?

FYI: @APSIMInitiative/livestock-and-forages (sorry, forgot to tag this team earlier)

**Comment by her123** [comment]
Would this be required for all pasture species?

**Comment by hol353** [comment]
Yep. If you want to graze a plant then it will need a node under the stock model.

**Comment by hol353** [comment]
So I've found time to work on implementing this. Question for @sno036, @rcichota , @mpandreucci.

AgPasture calculates it's own digestibility for leaf/stem/stolon. Do you want to use AgPasture's calculated digestibilities instead of the values entered by the user into a screen like the mockup above? I see a lot of code in Agpasture devoted to calculating digestibility and I was about to remove it when I thought I'd better check first.

**Comment by her123** [comment]
Since the digestibility of the plant will change through the growing period, if AgPasture does those calculations it may be better to keep them.

**Comment by sno036** [comment]
I agree with @her123. Thanks for doing this @hol353 - I am sure that @sme016 will be pleased to know this. But I thought there was already a mechanism to stop stock eating organs? How was it done in grape?

**Comment by sno036** [comment]
Also - the method above is not that much different to AgPasture - the live-dead ratio changes with age and while that is not all of the story it is a large part of it. Is it possible to have a "UseInternalValues" option as well as this?

**Comment by hol353** [comment]
An update: I'm getting close to having a working implementation for this.

APSIM will automatically add a 'Forages' component to a simulation that has Stock or SimpleGrazing. This component will automatically populate itself with sensible (?) defaults for all grazable plants that it finds.

![image](https://user-images.githubusercontent.com/1943827/141194889-c61f1bef-f469-424c-be1e-7ab5e4df348c.png)

Stock and SimpleGrazing now communicate with 'Forages', not the plant models. 

Digestibility and the fraction of an organ that can be grazed has been removed from the plant models. The minimum harvestible weights have been removed from AgPasture (the properties are still there but have a value of 0). All the 'harvestible' properties can be removed from AgPasture I think.

You can see in the screenshot that surface residues are treated in the same way as the plant models. 

The user can enter an expression into the digestibility columns to have digestibility as a function of something else.

The user can type 'internal' into the digestibility columns for AgPasture models to tell it to use AgPasture calculated digestibility.

Feel free to suggest changes.
