### ISSUE TITLE
APSIM crashes when invalid filter data entered in Reports

### ISSUE THREAD

**Issue by alisonml** [APSIMInitiative/ApsimX#6282]
When I enter invalid data into a field in a Report and then click to go to the next cell APSIMx crashes without warning. PLEASE could you fix this as it is very frustrating!! Thank you :)

**Comment by alisonml** [comment]
This seems to happen when I enter data into the Column Filter field

**Comment by lie112** [comment]
The text entered was mistaken formula (UID=1)

**Comment by hol430** [comment]
I'm not actually seeing a crash when this happens, but the UI does freeze. I think the problem is probably the same either way - and should be fixed by #6284. I imagine this will be merged on Monday, at which point an upgrade should become available which will contain the fix.

**Comment by alisonml** [comment]
That’s great, thanks Drew – looking forward to the new upgrade next week!
Alison
