### ISSUE TITLE
ApsimNG Rotation

### ISSUE THREAD

**Issue by XijuanXu** [APSIMInitiative/ApsimX#6287]
Hello sir，I have recently been using ApsimNG to simulate the rotation of winter wheat and summer maize. I'm not familiar with the programming language in which I write scripts. How to achieve the wheat harvest on a fixed date ？

**Comment by hol430** [comment]
For harvesting on a fixed date, try this:

```csharp
using Models.Soils.Nutrients;
using System;
using Models.Core;
using Models.PMF;
using Models.Soils;
using Models.Soils.Nutrients;
using Models.Utilities;
using APSIM.Shared.Utilities;

namespace Models
{
    [Serializable]
    public class Script : Model
    {
    	[Link] IClock clock;
        [Link(ByName = true)] Plant maize;
        [Link(ByName = true)] Plant wheat;
        
        [Description("Wheat harvesting date (dd-MMM)")]
        public string WheatHarvestDate { get; set; }

        [Description("Maize harvesting date (dd-MMM)")]
        public string MaizeHarvestDate { get; set; }

        [EventSubscribe("DoManagement")]
        private void OnDoManagement(object sender, EventArgs e)
        {
            if (wheat.IsAlive && DateUtilities.DatesAreEqual(WheatHarvestDate, clock.Today))
        	{
        		wheat.Harvest();
        		wheat.EndCrop();
    		}
    		if (maize.IsAlive && DateUtilities.DatesAreEqual(MaizeHarvestDate, clock.Today))
    		{
    			maize.Harvest();
    			maize.EndCrop();
			}
        }
    }
}
```

You just need to choose the harvesting dates in the properties tab (should be dd-MMM format - e.g. 01-Jan for January 1).

There is also an example of a wheat-maize rotation shipped with apsim. You can open it by going to the home screen in apsim -> open an example -> Rotation.apsimx. The rotation rules are all inside a component called RotationManager, which is inside the field.
