### ISSUE TITLE
Microclimate development discussion

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#6296]
@APSIMInitiative/cereals 
@APSIMInitiative/developers 

After planning an initial discussion on sorting out microclimate and sorghum, it has broadened to become a more general discussion on future microclimate development.

We hope to address sorghum as part of this meeting still, but it will be a smaller part of the overall discussion.
I have tagged @APSIMInitiative/cereals as it is our largest team but there are probably others interested so please spread the word.  I will also look at the possibility of creating a new team for this topic?

I will setup a zoom meeting for the 14th April at 9:30am (AUS time - daylight savings is finished by then) with those in the initial email list invited.  Please comment on this issue if you would also like to be invited to the meeting.

**The sorts of issues to discuss in this group would include all aspects of the current microclimate model, including:**

- Transpiration (and related links to photosynthesis)
- Interception losses (water evaporated from canopy during and after rainfall)
- Radiation Interception (for simple 1D systems, and strip crop/skip row/trellis systems, and layers within canopies)
- Energy Balance and individual terms therein
- Links to soil energy balance)
- Deficiencies in current components, such as shelter effects within canopies (ie intercrops) and between zones with different canopies (ie multipoint simulations of windbreaks etc)

Other related issues include: 

- Diffuse radiation in extreme latitudes
- Correction for sloping land

**Comment by uqschap7** [comment]
Frost?

From: Jason ***@***.***>
Sent: Wednesday, 24 March 2021 11:17 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Scott Chapman ***@***.***>; Team mention ***@***.***>
Subject: [APSIMInitiative/ApsimX] Microclimate development discussion (#6296)


@APSIMInitiative/cereals<https://github.com/orgs/APSIMInitiative/teams/cereals>
@APSIMInitiative/developers<https://github.com/orgs/APSIMInitiative/teams/developers>

After planning an initial discussion on sorting out microclimate and sorghum, it has broadened to become a more general discussion on future microclimate development.

We hope to address sorghum as part of this meeting still, but it will be a smaller part of the overall discussion.
I have tagged @APSIMInitiative/cereals<https://github.com/orgs/APSIMInitiative/teams/cereals> as it is our largest team but there are probably others interested so please spread the word. I will also look at the possibility of creating a new team for this topic?

I will setup a zoom meeting for the 14th April at 9:30am (AUS time - daylight savings is finished by then) with those in the initial email list invited. Please comment on this issue if you would also like to be invited to the meeting.

The sorts of issues to discuss in this group would include all aspects of the current microclimate model, including:

  *   Transpiration (and related links to photosynthesis)
  *   Interception losses (water evaporated from canopy during and after rainfall)
  *   Radiation Interception (for simple 1D systems, and strip crop/skip row/trellis systems, and layers within canopies)
  *   Energy Balance and individual terms therein
  *   Links to soil energy balance)
  *   Deficiencies in current components, such as shelter effects within canopies (ie intercrops) and between zones with different canopies (ie multipoint simulations of windbreaks etc)

Other related issues include:

  *   Diffuse radiation in extreme latitudes
  *   Correction for sloping land

**Comment by mpandreucci** [comment]
Hi Jason.
I’d like to join this meeting, if it’s not a problem.
Thanks,
Mariana

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JJguri** [comment]
I would like to be invited to the meeting. thanks

**Comment by daianfrancia** [comment]
Hi! I'm quite new at this, but I'd like to join the meeting. 
Thanks in advance,
Daián.-

**Comment by PengchengHU** [comment]
Hi Jason,

I'd like to join this meeting too. 

Thanks and Cheers,
Pengcheng

**Comment by Achraf-UM6P** [comment]
Hi Dear Jason
I'm quite new at modelling, but I'd like to join the meeting.
Thanks in advance,
best regards

Achraf

**Comment by andomariot** [comment]
Hi Jason,
I  will be happy to join. Thanks for the initiative.
In addition of effect on  resources distribution, in  rice crop, microclimate is very sensitive as the ponded water environment is creating different gradients of conditions during the day and the night that affect phenology, growth and quality of the grain.

**Comment by QiaominChen** [comment]
Hi Jason,

Could you please include me in this meeting as well? I am doing some simulation things with APSIM at the moment.

Kind regards,

Sophie
________________________________
From: Jason ***@***.***>
Sent: Wednesday, March 24, 2021 11:17 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Qiaomin Chen ***@***.***>; Team mention ***@***.***>
Subject: [APSIMInitiative/ApsimX] Microclimate development discussion (#6296)


@APSIMInitiative/cereals<https://github.com/orgs/APSIMInitiative/teams/cereals>
@APSIMInitiative/developers<https://github.com/orgs/APSIMInitiative/teams/developers>

After planning an initial discussion on sorting out microclimate and sorghum, it has broadened to become a more general discussion on future microclimate development.

We hope to address sorghum as part of this meeting still, but it will be a smaller part of the overall discussion.
I have tagged @APSIMInitiative/cereals<https://github.com/orgs/APSIMInitiative/teams/cereals> as it is our largest team but there are probably others interested so please spread the word. I will also look at the possibility of creating a new team for this topic?

I will setup a zoom meeting for the 14th April at 9:30am (AUS time - daylight savings is finished by then) with those in the initial email list invited. Please comment on this issue if you would also like to be invited to the meeting.

The sorts of issues to discuss in this group would include all aspects of the current microclimate model, including:

  *   Transpiration (and related links to photosynthesis)
  *   Interception losses (water evaporated from canopy during and after rainfall)
  *   Radiation Interception (for simple 1D systems, and strip crop/skip row/trellis systems, and layers within canopies)
  *   Energy Balance and individual terms therein
  *   Links to soil energy balance)
  *   Deficiencies in current components, such as shelter effects within canopies (ie intercrops) and between zones with different canopies (ie multipoint simulations of windbreaks etc)

Other related issues include:

  *   Diffuse radiation in extreme latitudes
  *   Correction for sloping land

**Comment by sno036** [comment]
Suggestion - perhaps those wanting to join the meeting might like to add some information to their profile so we know who you are? See @JJguri for a great profile!

**Comment by cranju** [comment]
Hi Jason,

I am a PhD candidate with UTAS. For my Ph.D., I am working on quantifying and decomposing crop model uncertainty. I am working on quantifying model structure uncertainty using APSIM as one of my objective. Since, one of my model (Brown model in APSIM classic) uses micromet for ET, I was interested in joining this meeting.

Regards
Ranju

**Comment by jbrider** [comment]
It is apparent there is a lot of interest about this meeting, just a note that the discussion will very much be targeted towards future code development - around both requirements and capacity.
I have contacted almost everyone that showed interest - if you haven't received anything - please email APSIM@csiro.au to get login details - we didn't want to expose them on a public site.

**Comment by sarahcleary** [comment]
FYI - @APSIMInitiative/reference-panel @APSIMInitiative/steering-committee
