### ISSUE TITLE
Manager script using statements: difficult to know what is required

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6297]
When writing a manager script, the only way to know which using statements are necessary is to look at the source code. Some possibilities:

- Have info in autodocs showing which types are exposed by which namespaces
- Implement an IDE-like code refactoring feature which can add the missing namespaces automatically. I believe this functionality is exposed via the roslyn API, and the textview/sourceview API is pretty extensible so this may actually be possible with some effort

**Comment by hol353** [comment]
In the GUI you can right click on any model in the tree and select 'Copy manager snippet'. This will copy a using statement and a [Link] line to the clipboard for accessing that model. This can be pasted into a manager script. This seemed the simplest way to helping the user determine what using statement is needed.
