### ISSUE TITLE
Slurp validation uses SoilN

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6307]
@hol353 - do we want to change these to nutrient? This will probably have an impact on the stats.

**Comment by hol353** [comment]
Yep definitely change to Nutrient. We'll have a look at the impact on the stats.

**Comment by hol430** [comment]
I've had to do some manual fixups in the ExtraVariables script in the SlurpTestBase simulation - previously it was talking to SoilNitrogen directly, and I've changed it so that it references INutrient. Could someone confirm that SoilNitrogen.dlt_n_min_res is equivalent to nutrient.SurfaceResidue.Decomposition.MineralisedN? Most of the other changes were reasonably obvious (e.g. FOMN -> FOM.N).

**Comment by rcichota** [comment]
You're correct @hol430 , ```SoilNitrogen.dlt_n_min_res``` is the same as ```Nutrient.SurfaceResidue.Decomposition.MineralisedN```

**Comment by hut104** [comment]
There is a converter in converter.cs that maps a lot of the variable names.  That code might be a good place to look for ideas on translating variable names

________________________________
