### ISSUE TITLE
Problem with new property presenter

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6309]
- After typing something into a string edit box and then immediately clicking on another node in the tree, the modified string is lost. After editing a string, you need to click on another edit control (or hit tab) and then click on something else in the tree.
- In the attached file, if you click on ManageStock, the ExpressionToMoveAnimalsToField and ExpressionToMoveAnimalsToFeedlot are blank. They shouldn't be.
[Stock.zip](https://github.com/APSIMInitiative/ApsimX/files/6219169/Stock.zip)

**Comment by hol430** [comment]
> After typing something into a string edit box and then immediately clicking on another node in the tree, the modified string is lost. After editing a string, you need to click on another edit control (or hit tab) and then click on something else in the tree.

Were you using gtk2 or gtk3 version? I'm having trouble reproducing this one (in both builds).
