### ISSUE TITLE
Filter variables in graph drop downs so they don't display varialbes that have no data.

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#633]
The drop downs in the graph object show all of the columns names in the data frame but when a graph is put in the scope of a simulation or experiment not all of the columns will have data in them.  This is really confusing for users as they select variables in the graph object that have no data in scope and wonder why the graph has nothing on it.  Would be better if the menus could check if the variable has data in scope and not display it in the drop down if it doesn't??

**Comment by hol353** [comment]
Fixed in #663
