### ISSUE TITLE
Change edit file command line option to allow multiple combinations of changes

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6339]
Need to rework the edit file command line option, and allow users to specify multiple change sets within a single configuration file. Currently, when someone wants to run the same .apsimx file with multiple different parameter sets they need to re-run the file multiple times, which has the overhead of reading the file each time (which can be rather slow for large files such as the wheat validation).

**Comment by frank0434** [comment]
Hi, @hol430 
I thought the previous version already had multiple editing done. or maybe I'm wrong? 
https://github.com/APSIMInitiative/ApsimX/issues/4905

also, I saw the usage changed quite a bit in the last few months 
the latest:
![image](https://user-images.githubusercontent.com/30789416/114380968-bd8b4c80-9bde-11eb-8ec1-9e2284341db9.png)

A late November build last year
![image](https://user-images.githubusercontent.com/30789416/114380930-b5cba800-9bde-11eb-87a4-0c7437b61359.png)

on the documentation website 
![image](https://user-images.githubusercontent.com/30789416/114381124-e0b5fc00-9bde-11eb-9008-110cbc631060.png)


It would be good to have stable usages. assume the latest will be the stable version follow Linux style?  
The latest `--edit` will run the simulations immediately after the simulations, and the apsimx file remains intact. I believe this is a good thing for a big apsimx file that has all experiments/simulations within it. But not necessarily convenient for chopping simulation into a single base one then generating many apsimx files to run on a cluster. 
wondering if it is possible to have a switch flag to allow the user to choose whether overwrite the original configuration (as [the initial edit functionality](https://github.com/APSIMInitiative/ApsimX/issues/4905#issuecomment-598509516)) or just run the re-configured simulation and leave originals intact.  

thanks

**Comment by frank0434** [comment]
Another question is around changing the simulation name itself. basically, allow `--edit` to mimic the functionality of `Factors`. wondering if it is possible. 

I tried to do 
```
[Simulation].Name = Funtest
[Weather].FileName = C:/Data/Master/01Data/ClimateAndObserved/AshleyDene.met
```
The weather file path successfully modified, but the simulation name hadn't. 

![image](https://user-images.githubusercontent.com/30789416/114464515-f99fcb00-9c39-11eb-9df9-e7c96caf8e91.png)

Just want to understand the possibilities of `--edit` flag. 
Thank you.

**Comment by hol430** [comment]
Hi Frank,

> I thought the previous version already had multiple editing done. or maybe I'm wrong?

Yep, the current version allows you to change multiple parameters simultaneously. What we want to add here is the ability to add mulitple combinations of changes. For example:

```
[change1]
[Weather].FileName = met1.met
[Clock].StartDate = 2021-01-01

[change2]
[Weather].FileName = met2.met
[Clock].StartDate = 2022-01-01

[change3]
[Weather].FileName = met3.met
[Clock].StartDate = 2023-01-01
```

The idea being that apsim will run the file for each of these different parameter sets. Previously, you would have had to run the file multiple times, each time with one of these parameter sets. This would have had the disadvantage of having to read the file multiple times (once per parameter set).

The usage has indeed changed in the last few months. It's backward-compatible, so any of the old-style switches will still work, but I'd recommend writing any new code to use the new switches if possible. If we do change it again, we would make it backwards compatible again.

> wondering if it is possible to have a switch flag to allow the user to choose whether overwrite the original configuration (as the initial edit functionality) or just run the re-configured simulation and leave originals intact.

Yes this is possible. Out of interest, how were you planning on chopping the .apsimx file up into small chunks? By using the gui?

> Another question is around changing the simulation name itself.

That sounds like a bug - it should work. I'll look into it.

**Comment by frank0434** [comment]
Thanks for the answers, Drew. 
> Yes this is possible. Out of interest, how were you planning on chopping the .apsimx file up into small chunks? By using the gui?

Yes, I used the gui to setup a very basic apsimx file. 
But I wonder if it is a good approach to do because I swamped our HPC last time I did this. the job scheduling time for each apsimx file was greater than the actual running time of the simulation.

wondering what others do when it comes down to use apsimx in HPC.

**Comment by asherbender** [comment]
Currently the CLI provides an interfaces for editing a file before running it:

`Models --edit /path/to/config/file.txt /path/to/file.apsimx`

I believe this is done in memory and there is no way to access the modified simulation? 

It would be useful to have an interface for modifying the file and writing the new configuration to file _without_ running a simulation. I do not believe this would be a large change (the CLI implements ~99% of this feature!)

If you are happy to implement a breaking change, you could change the `--edit` flag to edit a file in-place _without_ running the simulation

`Models --edit /path/to/config/file.txt /path/to/file.apsimx`

or write the changes to a new file:

`Models --edit /path/to/config/file.txt /path/to/file.apsimx /path/to/newfile.apsimx`

The new simulation could then be run with a regular call to:

`Models file.apsimx` or `Models newfile.apsimx`

For a non-breaking change, you could introduce a new flag/option...


This would allow users some ability to configure simulations programmatically AND keep the simulation file as a record.
