### ISSUE TITLE
Problem with ReportView rows not lining up.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6358]
This was found in the SimpleGrazing example:

![image](https://user-images.githubusercontent.com/1943827/114801941-1970f380-9de0-11eb-8356-f51959613495.png)

**Comment by lie112** [comment]
I have a similar issue in CLEM reports
![image](https://user-images.githubusercontent.com/19215637/129124166-18285fe6-9a8c-49e1-8c4c-9fced0fe02f6.png)

**Comment by hol430** [comment]
It's a problem with the gtk3 GridView. We are moving away from this in other areas, using the SheetWidget instead (which doesn't have this problem).

I can't remember if there's a workaround for this problem in the GridView. You could try altering the heading on the frozen column ("Activity" in your example) by adding a newline character to make it the same height as the headings in the non-frozen columns. Avoiding the use of frozen columns altogether would also fix the problem, although may not be feasible for your use case.
