### ISSUE TITLE
Newtonsoft.json.dll not loading in linux

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#6383]
Here's where the problem started - running an ordinary simulation in a linux singularity container, built with the same components as the [docker build containers](https://github.com/APSIMInitiative/APSIM.Docker/blob/master/NextGen/apsimng-build/Dockerfile).

```System.Exception: Error in file:/TMPDIR/potato_var_test_v4.apsimx ---> System.Exception: Errors found in manager model Harvesting
Line 0: Metadata file `/usr/local/lib/apsim/2021.03.15.6157/Bin/Newtonsoft.Json.dll' does not contain valid metadata

  at Models.Core.Run.SimulationGroup.Initialise () [0x00066] in <a7a4d9f3913649dabc7df6e57b1d1c6a>:0 
   --- End of inner exception stack trace ---
ERRORS FOUND!!
```
There's a [SO question](https://stackoverflow.com/questions/59209700/compiling-c-sharp-code-at-runtime-under-mono-fails-when-referencing-newtonsoft-j) that looks identical, but the solutions don't look convincing. Before I get to deep in this, has anyone managed to run NG in linux containers recently - since the json component was upgraded?

TIA

**Comment by femiguez** [comment]
Not sure if this helps, but that is the same error message I received on Mac and it was resolved by installing mono 6.12

**Comment by peter-devoil** [comment]
That's one f the reasons I'm suspicious - I'm running 6.12 as well:
```
Singularity ApsimNG-2021.04.15.6139.sapp:~> mono --version
Mono JIT compiler version 6.12.0.122 (tarball Mon Feb 22 17:29:18 UTC 2021)
```

**Comment by hol430** [comment]
I can't say I've run into this particular problem before - but I'll run a few tests and see if I can reproduce. We do have official docker images on [dockerhub](https://hub.docker.com/u/apsiminitiative) if that helps. The dockerfiles are [here](https://github.com/APSIMInitiative/APSIM.Docker). The images aren't regularly updated for now - eventually it will become part of the CI release cycle but I haven't implemented it yet.

**Comment by hol430** [comment]
Can you provide details about how your container was built? I've just tried this in a docker image based on Debian, using the same installed version and didn't have any problems.

**Comment by peter-devoil** [comment]
Installing the dll with gacutil inside the container makes to problem go away. But it shouldnt be needed.
```
gacutil -i /usr/local/lib/apsim/$ApsimVersion/Bin/Newtonsoft.Json.dll
```

@hol430 if you could test that some examples (with manager components requiring runtime compilation) run inside the container, I'd be grateful.

**Comment by peter-devoil** [comment]
Here's the build:
```
apt-get update && apt-get -y install gnupg ca-certificates wget
gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF; \
	gpg -a --export 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF | apt-key add -
echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" > /etc/apt/sources.list.d/mono-official-stable.list
wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb; \
dpkg -i packages-microsoft-prod.deb; \
rm packages-microsoft-prod.deb

apt-get update && apt-get -y install \
	gtk-sharp2 mono-devel dotnet-sdk-3.1 libwebkitgtk-1.0-0 sqlite3 libcanberra-gtk-module

dpkg -i /Apsim.deb
rm -f /Apsim.deb

gacutil -i /usr/local/lib/apsim/$ApsimVersion/Bin/Newtonsoft.Json.dll
```
Apsim.deb is downloaded from apsim.info

**Comment by hol430** [comment]
I just tried a docker container which looks like this and managed to run the wheat example without error. Which base image are you using?

```
FROM ubuntu:latest

RUN apt-get update && apt-get -y install gnupg ca-certificates wget; \
    gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF; \
	gpg -a --export 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF | apt-key add -; \
    echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" > /etc/apt/sources.list.d/mono-official-stable.list; \
    wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb; \
    dpkg -i packages-microsoft-prod.deb; \
    rm packages-microsoft-prod.deb;
ENV TZ=Australia/Brisbane
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone; \
    apt-get update && apt-get -y install \
	gtk-sharp2 mono-devel dotnet-sdk-3.1 sqlite3 libcanberra-gtk-module; \
    wget -O /apsim.deb http://apsimdev.apsim.info/ApsimXFiles/ApsimSetup6157.deb; \
    dpkg --force-depends -i /apsim.deb; \
    rm -f /apsim.deb;
RUN mkdir /apsim; \
    cp /usr/local/lib/apsim/2021.03.15.6157/Examples/Wheat.apsimx /apsim/wheat.apsimx
WORKDIR /apsim
```

**Comment by peter-devoil** [comment]
The only diff from that was using 18.04 base (latest is 21?)

Singularity's a little bit different from docker, but not that different

P

**Comment by hol430** [comment]
I still get successful runs even with 18.04. You could try the .net core version. Although since you already have that gacutil workaround I guess it may not be necessary.

**Comment by peter-devoil** [comment]
Yes, we've found a workaround, but no idea why it was necessary. Lets close this for now.
