### ISSUE TITLE
Properties in map component overlap map in gtk2 version

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6392]
In the gtk2 build, the properties in the map component overlap the actual map area.

**Comment by zur003** [comment]
#6393 may fix the problem, but the whole layout seems a bit odd. The co-ordinates for the map centre aren't obviously available, requiring re-sizing or scrolling to see them (if you know they're there). Values are given with about 15 digits of precision, which is pointless. Couldn't we just reduce the precision, provide less space for each value, and allow all the values to appear on a single line?

**Comment by hol430** [comment]
Yep, that would be a sensible compromise although I'm not sure that we actually need the properties section here. I'm not sure how useful it is - I don't think I've ever used it apart from testing for bugs.
