### ISSUE TITLE
Develop ryegrass model

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#64]

**Comment by sno036** [comment]
@rcichota  - I don't think this is active. Should we close it?

**Comment by rcichota** [comment]
Maybe. This is from the time was meant to help with not to do the development of forages, so I could do this as an addin. It didn't happen and it may take a while for someone to get onto it.  However, this is an issue that eventually needs solving, AgPasture can be used as an alternative, but it is not ideal, a PMF ryegrass is needed. Maybe Mariana or someone else can take over in the future? I am happy to assist where possible, but given my current employer I don't think I will be dong much on this anytime soon. I have no objections if you think it easier to close and re-open at a later date, otherwise leave it open as a reminder that someone, sometime, will need to do..

**Comment by sno036** [comment]
Yup. This is still on the wish list but it is not active so I'll close it.
