### ISSUE TITLE
Changes to .sln

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6408]
What changes to the visual studio solution file (.sln) can be ignored and what need to be included in version control.
Occasionally I get changes to the .sln without obvious reason. In the past these have been included in my commits.
When if ever should these changes be ignored, or is it safe to keep updating everyone's .sln file.

Example
![image](https://user-images.githubusercontent.com/19215637/116950137-4ddf1d80-acc3-11eb-9d25-e985f9cb697d.png)

**Comment by lie112** [comment]
@hol430 is it ok to just accept all these changes through time?

**Comment by hol430** [comment]
As far as I know, no one else seems to see these changes so it may be something specific to the configuration on your pc. Do you these changes occur every time you hit save in visual studio?

**Comment by lie112** [comment]
I don't think so. I just noticed them in my last changed files and thought I'd check what's going on before submitting.
I'll backup the sln and discard the changes and see how it goes.

**Comment by lie112** [comment]
Removing changes seems to be ok
