### ISSUE TITLE
Autodoc failures

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#6409]
@APSIMInitiative/reference-panel @hut104 @hol430 
During the grapevine model review it was noted that the autodoc had failed to produce some of the graphs and most of the equations.  The question was raised if generating pdf's was the best way to continue or if we should look at an online version instead that reflected the current tree structure of the model.

We ran out of time to get into this properly during the meeting, so could people add their thoughts here to see if we need to have further discussions during the next meeting.

**Comment by jbrider** [comment]
I find the generated text for items such as interpolated graphs etc to be very useful and much easier to read than the model nodes themselves, so I feel there would still need to be a step where documentation is generated.
I don't think that documentation needs to be printed, and would find an interactive format to be much easier to review/read.

**Comment by HamishBrownPFR** [comment]
I find the GUI tree view much easier to navigate for studying the structure configuration of the model.  Having the tree view makes it clearer where you are.  If I want to check how a model is set up I never go to the doco, I always open it in the GUI and check it there.  I think it would be more useful and easier to maintain if the model doco was simply a web app that allowed you to view model.json files the same as the GUI does.  Currently we spend lots of time trying to get the pdf renders of the model looking correct and don't focus enough on the content (names of nodes and inclusion of memos).  If we were not spending time on the former we could do a better job on the latter.  
Checking the models performance is easier from a pdf that provides a summary of the key graphs and memos without needing to navigate all the other stuff that is in the .apsimx file.  Could the doco be a mix of a public web based GUI for reading model.json files and a pdf detailing the model performance.
