### ISSUE TITLE
[Soil].Nutrient.Natm and [Soil].Nutrient.N2Oatm not calculating properly

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6411]
In Nutrient, [Soil].Nutrient.Natm and [Soil].Nutrient.N2Oatm are not capturing the appropriate (i.e. any) values from deeper in the structure. 

[Soil].Nutrient.Natm should be capturing all of: 
- [Soil].Nutrient.NO3.Denitrification.Natm
- [Soil].Nutrient.NO3.Denitrification.N2Oatm (actually - check that this is not included in Natm)
- [Soil].Nutrient.NH4.Nitrification.N2Oatm

 [Soil].Nutrient.N2Oatm should be capturing: 
- [Soil].Nutrient.NO3.Denitrification.N2Oatm 
- [Soil].Nutrient.NH4.Nitrification.N2Oatm

**Comment by sno036** [comment]
@hol353 - not sure if this is behaving as expected or not ...

Would you expect "[Soil].Nutrient.NH4.Nitrification.Value" to give the same value as "[Soil].Nutrient.NitrifiedN". I did - but am unsure if my expectations are correct! The former more detailed is returning zeros but the later is giving sensible values.

**Comment by sno036** [comment]
Thanks to some patient help from @hol353! ... to get the N2O loss from nitrification as it should be, N2OFraction (for nitrification) should be 1 (no losses of N other than by N2O) and the NLoss factor should be 0.01 (the loss rate) but this should be user-settable. The parameter values for denitrification look right to me. Discuss with @hut104 why the default is for no n2O from nitrification.

**Comment by hut104** [comment]
It should be returning the Natm for all N flows according to the source code

        /// <summary>
        /// Total N lost to the atmosphere
        /// </summary>
        [Units("kg/ha")]
        public double[] Natm
        {
            get
            {
                double[] values = new double[FOMLignin.C.Length];

                foreach (NFlow f in FindAllChildren<NFlow>())
                    values = MathUtilities.Add(values, f.Natm);
                return values;
            }
        }

________________________________
From: Val Snow ***@***.***>
Sent: Wednesday, 5 May 2021 10:53 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] [Soil].Nutrient.Natm and [Soil].Nutrient.N2Oatm not calculating properly (#6411)


In Nutrient, [Soil].Nutrient.Natm and [Soil].Nutrient.N2Oatm are not capturing the appropriate (i.e. any) values from deeper in the structure.

[Soil].Nutrient.Natm should be capturing all of:

  *   [Soil].Nutrient.NO3.Denitrification.Natm
  *   [Soil].Nutrient.NO3.Denitrification.N2Oatm (actually - check that this is not included in Natm)
  *   [Soil].Nutrient.NH4.Nitrification.N2Oatm

[Soil].Nutrient.N2Oatm should be capturing:

  *   [Soil].Nutrient.NO3.Denitrification.N2Oatm
  *   [Soil].Nutrient.NH4.Nitrification.N2Oatm

**Comment by sno036** [comment]
Will be fixed in #6438
