### ISSUE TITLE
Working with git (still newbie Q)

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6412]
A question about git and APSIMx issue management:
Do we allow a pull request to relate to a closed issue, or should we create/have an open issue for each pull request?
This is different to "working on" as the initial issue is closed. I have improved functionality for a resolved issue (#6285) and was going to uses "fixes" or "resolves" or still "working on" in the pull request linkage. There isn't a git issue linking keyword for this.

**Comment by zur003** [comment]
When I've been in this situation, I've re-opened the issue before making the pull request. There should be a "Reopen issue" button near the bottom of the issue description page.

**Comment by hol430** [comment]
Jenkins and the build system will still work if you reference a closed issue. The main thing to be careful of is using "resolves X" on an issue that has previously been resolved. This will cause a new release to be generated with an identical issue number and description to an existing release, which can lead to some confusion. So I'd suggest either reopening and doing a "working on X" PR (and then manually closing the issue after the PR is merged), or just opening a new issue.

**Comment by lie112** [comment]
Thanks... good to get consensus
