### ISSUE TITLE
Update the updater

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6416]
The updater currently uses winforms message boxes to display error messages to the user. This appears to be causing some problems on linux/mac machines when an error occurs. It also prevents us from migrating the updater to .net core, because as far as I know, .net core winforms apps cannot be built on mac/linux systems.

When run on linux, the updater also makes certain assumptions; e.g. that zenity is installed, and that the system is a debian derivative using apt/dpkg. This raises the question of whether we even want to support upgrades from the gui on linux. It may be simpler to get apsim added to the official apt repositories, or to provide our own repository (I don't know if apsim would actually fit Debian's definition of free software). This wouldn't help people using other distributions but it certainly won't hurt them either since upgrades currently won't work for them anyway.

@hol353 any thoughts? I think at the very least, it would be good to remove the dependency on winforms - we could either display errors in a console window or in a gtk window, or via some other mechanism. Using gtk would provide a better user experience but would add some substantial dependencies to the updater program, meaning we would need to rethink how it gets run (currently, Updater.exe is copied into temp path and run; we would need to also copy the GtkSharp support libraries).

**Comment by hol353** [comment]
How hard is it to get APSIM into apt using either the official apt repositiory or our own? If you think that is easier than getting the upgrader worker then go for it. I'd prefer to do it the linux way if we can.

If that is too much work then let's at least get the upgrader working on debian OSs. For now I can live the assumption that zenity (whatever that is) is installed. Get rid of WinForms stuff, go with gtk widgets and deal with the extra support libraries required.

I'll let you choose which way is quicker / better.

**Comment by sme016** [comment]
It seems still not to be working, as I need 3 or 4 attempts before success.
