### ISSUE TITLE
Provide official docker images

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6417]
We currently have some images on [dockerhub](https://hub.docker.com/u/apsiminitiative) which work but aren't version stamped or regularly updated. As part of the continuous release cycle, we could update these images using the dockerfiles [here](https://github.com/APSIMInitiative/APSIM.Docker).

**Comment by BrianCollinss** [comment]
Would be helpful for people like me to have a sort of a document that describes how/when to use these dockers? Would they be able to be used, for example, on HPC clusters?

**Comment by peter-devoil** [comment]
That would be a really good thing for us, @hol430. @BrianCollinss - [this background doc](https://singularity.lbl.gov/archive/docs/v2-3/docs-docker) might help. We would take our existing 15 line singularity recipes down to about 2 lines.

**Comment by BrianCollinss** [comment]
Hi @hol430. Have you had a go at this? Would be a very big help to people like me that work on Windows and don't want to have a Linux VM just to compile APSIM on Linux. Cheers.

**Comment by hol430** [comment]
Was previously blocked by the lack of .net core installers which are now available, but I haven't really looked into this yet. Maybe next week. Worth noting that this is nextgen-only, I don't have an image for old apsim on linux. Maybe one day...

**Comment by hol430** [comment]
We now have official docker images but they are not regularly updated. This is on the to-do list.

**Comment by hol430** [comment]
This has now been implemented. Moving forward, there will be a new tagged version of [the apsimng docker image](https://hub.docker.com/r/apsiminitiative/apsimng) pushed to dockerhub each time a new version of apsim is released.
