### ISSUE TITLE
Write SimulationName into DataBase

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#644]
I have been working on reading data from an APSIM next gen DataBase into a python notebook for analysis which is relatively easy to do.  However, the column named "SimulationName" that appears in the DataTable view in the UI is not in the DataBase.  I am guessing that the report view creates the "SimulationName" from the "SimulationID" column and and displays it in the view but does not store it in the DataBase? 

A name is much more informative that a number and it would be good to have this included in the DataBase also.

![image](https://cloud.githubusercontent.com/assets/7295858/13309607/4f328674-dbe3-11e5-83dd-69bec0c18c49.png)

**Comment by hol353** [comment]
Try changing "Select * from report" to "Select * from Report,Simulations where Report.SimulationID = Simulations.ID"

**Comment by HamishBrownPFR** [comment]
That didn't work but I think the point is I need to learn how to do sql queries to get this working properly.  Can you recommend a good reference?

**Comment by hol353** [comment]
It should have worked. What error did you get? Quite a good SQL resource: http://www.w3schools.com/sql/

**Comment by HamishBrownPFR** [comment]
Sorry, it did work.  It added simulation name to the end of the dataFrame and I was expecting to see it at the start so looked in the wrong place
