### ISSUE TITLE
Updates are not being released

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#6441]
Running a Upgrade indicates 2021.4.29.6139 as the last release. I would have expected something containing the May updates to be available.

**Comment by hol430** [comment]
Updates are going again, so I'm going to close this. For discussion about the underlying problem of releases regularly breaking, see #5606.

**Comment by lie112** [comment]
Do we need an open updates not being released issue
Seems 08/07/2021 Annoying Exceptions was the last successful build of upgrade today (19/7/2021)
That's the last one showing up in my Upgrade form but Jenkins suggests there's a 17th July built.
