### ISSUE TITLE
APSIM Next Generation - Video

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ApsimX#6445]
Please use this issue to comment and/or ask questions in relation to the following video:
https://www.youtube.com/watch?v=5DogVqLYbUs

**Comment by MarkLieffering** [comment]
Great intro video Dean - excellent pace and very clear. Glad to see I am not the only one that deletes instead of pastes!

**Comment by yashvirchauhan** [comment]
Great introductory video on the APSIM nextgen.  If I watch a couple of more times to remember all the steps outlined in the presentation I hope to become a trained user of APSIM Next Gen. Well done Dean.

**Comment by tkd708** [comment]
Thank you so much for the great instruction!
I have a couple of questions regarding the use of APSIM Next Gen mainly from the perspectives of simulating soil N cycling as follows.

**1. How can we see Nutrient module algorithms?**
Related to the first question, I wonder about the algorithms behind the Nutrient module.
Some parts are visible by "Show model structure" but others are not shown there (only as memos) or in the code either (APSIMInitiative/ApsimX/Models/Soils/Nutrients/Nutrient.cs).
To my understanding, they are mostly inherited from SoilN in the classic. Nevertheless, it would be great if we could trace them step by step just like SoilN (SoilN documentation and/or the code in APSIMInitiative/APSIMClassic/Model/SoilN/SoilN.f90).

**2. How can we modify Nutrient module constants?** 
Related to the first question, I would like to change some model constants (e.g. nitrification_pot, dnit_rate_coeff, etc...) as we could in APSIM classic by editing those in soil.xml.
How can we do that in APSIM Next Gen? "Replacement" shows only limited parameters and does not for those interested.
If currently not adjustable, would they be in future updates?

Again, I much appreciate the video as well as the documents currently available... it would be even more helpful if you could provide any information related to the questions above!

Best,
Naoya

**Comment by hol353** [comment]
1. 'Show model structure' will show **all** components of the Nutrient model. To see the source code behind a component, hover the mouse over the component in the tree to see the c# class name of that component. For example, hovering over 'Denitrification' under 'NO3' shows that the code is in 'NFlow.cs'. The two locations where you can see the source files are:

https://github.com/APSIMInitiative/ApsimX/tree/master/Models/Soils/Nutrients
https://github.com/APSIMInitiative/ApsimX/tree/master/Models/Functions/SoilFunctions
 
The code is not in a single source file like APSIM 7.10. Instead it is broken up into many smaller source files. The functionality of Nutrient is identical to SoilN in APSIM 7.10. We compared the 2 versions and they produce the close results.

2. The constants are mostly shown in the user interface although there needs to be further work to expose some constants in the CERESNitrification and CERESDenitrification components. For now the only way to change these is to modify the source code and recompile. We will fix this at some time in the future.

**Comment by tkd708** [comment]
@hol353 
Awesome, I did not notice "SoilFunctions" but I just checked how they were described.

>> "The functionality of Nutrient is identical to SoilN in APSIM 7.10. We compared the 2 versions and they produce almost identical results."
I much appreciate this information since it's hard to test this for extensive conditions on my own. It would be helpful if you could show the comparison again when there would be differences after updates (mostly on Nutrient I guess) in the future.

It would be great if those constants were editable since they were changed in some previous studies (e.g. Thorburn et al., 2010).
Enabling the threshold parameter of WFPS above which denitrification starts (Mielenz et al., 2016; 2017) would also be helpful, which seems fixed at DUL in the current CERESDenitrificationWaterFactor component but was optionally editable in APSIM 7.10.

I'm very thankful for your answers and efforts!

Best,
Naoya

**Comment by hol353** [comment]
I have created a separate GitHub issue for this suggestion so that we don't lose it.

**Comment by sarahcleary** [comment]
If you're interested in receiving updates on new videos developed by the APSIM team, please email apsim@csiro.au
