### ISSUE TITLE
Dry matter digestibility (DMD)

### ISSUE THREAD

**Issue by demlie257** [APSIMInitiative/ApsimX#6452]
How dry matter digestibility (DMD) for the given pasture is determined from Agpasture in APSIM?

**Comment by sno036** [comment]
It is in the documentation but perhaps not as clear as it might be / could be improved! See page 43 in the 'science' documentation. It is calculated based on leaf age and protein concentration.

![image](https://user-images.githubusercontent.com/12176269/118078293-f7cc5180-b409-11eb-9e4a-430e93e3bfcc.png)

**Comment by demlie257** [comment]
Thanks a lot again for the feedback forwarded and the clarification
made.They are really helpful.

Kind regards,

Demlie
