### ISSUE TITLE
Simplify downloading APSIM

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6454]
Currently there are too many clicks from APSIMs homepage to actually downloading APSIM. This needs to be simplified.

**Comment by sno036** [comment]
I endorse this effort! And where it is only taking the user to one version of APSIM it should say which one.

![image](https://user-images.githubusercontent.com/12176269/118079082-8db4ac00-b40b-11eb-82af-16d36c518b4f.png)

**Comment by hol353** [comment]
Notes from @sarahcleary 
* Provide reasonable notice
   - Objective test – layout, language used
   - is it obvious on the webpage where the T&Cs are
   - is the layout conducive to someone knowing there are T&Cs which bind the user
   - is the webpage too cluttered to know that there are T&Cs
   - interestingly, doesn’t matter if someone doesn’t click on the T&Cs, if one is aware that there are T&Cs, they are bound by them if they continue to use the product/webpage
* Ensure contracting party has considered and accepted the T&Cs
   - Objective standard
   -  Did the user by its conduct, accept the T&Cs
   - Require an action – press accept or clicking on sign up etc..
* Case Law examples
   - Book Now – with an “I agree with the T&Cs” - GOOD
   - T&Cs easily accessed through a hyperlink - GOOD
   - 2 steps where acknowledging the T&Cs was deemed favourable by the courts - GOOD
   - Need to keep a log/record of when we change the T&Cs.  – may be needed but would be able to be generally traced back to our uJV changes/agreement by parties
   - Hyperlink terms in small font – BAD
   - Font - Didn’t stand out (light blue on white background) – BAD
   - No sufficient notice that the user was agreeing to the T&Cs – used NEXT not “I Agree …..” – BAD
* Click-Wrap Agreements
   - Require users to affirmative agree by clicking on a button marked “I agree”
   - Contract terms can be presented in different ways – hyperlink or scrollpane
   - Single purpose button or checkbox explicitly require ser to manifest assent
   - Generally upheld by the courts although more onus on website owners.

**Comment by lie112** [comment]
I just went to have a look and provide some feedback and the Download link (menu option) is not currently working

**Comment by sarahcleary** [comment]
@hol430 - are you updating the link?

**Comment by hol430** [comment]
Which link? The answer is no either way, but I'm not sure which link is broken here.

**Comment by lie112** [comment]
The main menu link just started working again. must have been web glitch

**Comment by lie112** [comment]
I have had a quick go and reducing the number of pages to a single workflow and removing duplicated information
I have it in a word document I'll send to @sarahcleary 

This is the text version - from the download menu on main APSIM page
-------------------------

How do I download APSIM?
There are four steps to obtaining and maintaining the APSIM software.
1.	Select and agree to appropriate licence agreement
2.	Determine which version of APSIM you require
3.	Register to download the software
4.	Registered users can also Upgrade the software 

REGISTER NOW BUTTON

Your licence to use APSIM
All access to the APSIM software is through approved licence agreements.

Licensed users may access and modify all source code. All modifications to APSIM must be submitted to the AI and be subject to the Reference Panel evaluation process before inclusion into the official APSIM release. Instructions for Submitting Improvements to APSIM for Review by the APSIM Initiative Reference Panel can be found see here.

It can be useful to notify the APSIM Initiative that you are planning on making an improvement to APSIM. This can often lead to others suggesting ideas or collaborators to work with. To do this you need to create an LINK TO HOW TO DO THIS issue in GitHub with a description of what you intend doing. This is for APSIM 7.x and APSIM Next Generation.

You will need to agree to one of two types of licences before downloading the software:

Non-Commercial Research and Development
If your use is non-commercial then you can choose the APSIM Non-Commercial R&D Licence Agreement. In summary, this agreement states:
•	Access to APSIM will be free of charge to users for non-commercial purposes
•	Non-commercial use of APSIM means public-good research & development and educational activities. It includes the support of policy development and/or implementation by, or on behalf of, government bodies and industry-good work where the research outcomes are to be made publicly available.
•	Any improvements you make to the model belong to, and need to be returned to, the APSIM Initiative.  For more information, please review What is an APSIM Improvement?
•	The APSIM Initiative will provide regular, official releases of APSIM free of charge for non-commercial use to those who agree to the terms of the license agreement.

Commercial
If you are using, or plan to use, APSIM for commercial purposes, then you need to apply for a commercial licence agreeing to the APSIM Commercial Licence Agreement. For more information see What is commercial use? 

APSIM Versions
There are two versions of APSIM available.

APSIM Classic (last release version was 7.10)
Please note there will be no more major APSIM Classic Releases.  However, there are currently more models available in APSIM Classic, so please refer to this list – Models in Release – APSIM

APSIM Next Generation.  
Quick intro here. This is the future. All improved functionality and future development xxx x xxx x xxxx

Other products
There are a number of other products that can also be accessed at the registration page
EXPLAIN why there are other products to download at the registration page

REGISTER NOW BUTTON

Minimum System Requirements
•	1 GHz CPU
•	512MB RAM
•	Windows XP / Mono 2.10 for Linux

Recommended System Requirements
•	Quad Core 3GHz + CPU
•	4GB RAM

Troubleshooting APSIM Installations
For Mac Users
If you are using Classic, you will need to install Parallels, which allows you to run windows software (ie APSIM Classic) on a Mac.
For Next Gen, you can choose the mac download option when registering.

For APSIM 7.10
International users running Microsoft Windows may have trouble with number & date formatting (eg commas vs decimal points in numeric entries), and may need to change their regional settings to Australian or similar.

For APSIM 7.9
APSIM has been changed to use Microsoft Visual C++ 2015. The implications for users is that the installation process can be more complicated. The APSIM Installer will check for Microsoft Visual C++ 2015 and attempt to install it if required. On versions of Windows before Windows 10 (i.e. Windows 7, 8, and 8.1) it may be necessary for the user to manually install Microsot KB2999226 (Update for Universal C Runtime in Windows).
This update can be found here
For this to succeed though, it may be necessary to update Windows via Windows Update. For example on Windows 7, we have found it necessary to install Windows 7 service pack before installing the above update.
APSIM version 7.4 and 7.5 requires the following 2 Microsoft runtimes to be installed:
1.	The Microsoft .NET 4 Framework
2.	The Microsoft C++ Runtime for Visual Studio 2010
APSIM version 7.3 and earlier requires the following 2 Microsoft runtimes to be installed:
1.	The Microsoft .NET 2 Framework (included with the .NET 4 distribution above)
2.	The Microsoft C++ Runtime for Visual Studio 2008
The APSIM Installation should detect when the above two runtime libraries are missing and install them automatically. If this doesn’t occur, then you can manually install them from the above links.

Release Details
APSIM Next generation provides an upgrade option in the software with a full list of all upgrade through time. These upgrades provide the version details of APSIM Next Generation

The following releases relate to APSIM Classic
29 March 2018 – APSIM 7.10 Release Notes
3 May 2017 – APSIM 7.9 Release Notes
24 Mar 2016 – APSIM 7.8 Release Notes
12 Dec 2015 – APSIM 7.7 Release Notes
21 Mar 2014 – APSIM 7.6 Release Notes
10 Apr 2013 – APSIM 7.5 Release Notes
10 Feb 2012 – APSIM 7.4 Release notes
24 Feb 2011 – APSIM 7.3 Release notes
23 Aug 2010 – APSIM 7.2 Release notes

11 Nov 2009 – APSIM 7.1 Release notes
23 Apr 2009 – APSIM 7.0 Release notes
22 Aug 2008 – APSIM 6.1 Release notes
26 Mar 2008 – APSIM 6.0 Release notes
For previous releases, please email apsim@csiro.au


OTHER PAGES
Non-Commerical use page not needed. Less links and pages to follow the better
Keep What is commercial use page as this information can’t be on main download page

On the register form page
•	Format to same look and feel as website to make look official. I see this is on a different website/server so cannot be embedded in webpage for confidence in download by users.
•	We haven’t mentioned anywhere that there are lots of products available and I know this has confused some users
•	It’s confusing to have to select APSIM and then under version Next Gen not understanding that 7.1 isn’t simply the latest version of APSIM
•	Add APSIM Classic and APSIM Next Generation to Product list
•	Then have their versions in the version drop down.

**Comment by hol430** [comment]
Closing as finished. The wordpress site now links to the new registration site.
