### ISSUE TITLE
Cow weight is not increasing in proportion to supplementary feeding 

### ISSUE THREAD

**Issue by demlie257** [APSIMInitiative/ApsimX#6455]
When simulating cow weight gain in APSIM, the cow weight doesn't not sometimes increase as proportional to increased supplementary feeding instead the cow weight decreases over time.  Is there any mechanism related to climatic or any other conditions for that cow weight is not increasing regardless of the amount of supplementary feeding?

**Comment by sno036** [comment]
![image](https://user-images.githubusercontent.com/12176269/118077727-c69f5180-b408-11eb-9900-427d87a05bf0.png)

Hi @demlie257  - Stick is quite a complex/difficult model. The full documentation is found at https://apsimnextgeneration.netlify.app/modeldocumentation/ and make sure to investigate all the sources of information. 

If there is not enough energy in the feed or the feed is not in the same location as the stock then they will lose weight and eventually die. Have you checked the DM and ME intake? Also that the feed is disappearing? I suggest that you start with the agistment grazing in the example file and modify bit by bit keeping an eye on the outputs each time you change something.
