### ISSUE TITLE
Tree biomass in APSIM

### ISSUE THREAD

**Issue by demlie257** [APSIMInitiative/ApsimX#6456]
When I simulated the total above ground biomass for eucalyptus tree in APSIM over 100 years period of time, the biomass was increasing over time and showed almost a perfect linear relationship over time. I want to check if it is an acceptable trend?

**Comment by sme016** [comment]
We don't know the real pattern up to 100 years for plantation eucalypts, but up to about 27 years (as I recall) it was approx linear after a few years in one case I know of - check the Coffs Harbour case in the validation. Some studies on native forest stands might have estimates up to a few hundred years that could be checked, but I don't konw tha literature.

**Comment by demlie257** [comment]
Thanks a lot for the feedback forwarded.

Kind regards,

Demlie
