### ISSUE TITLE
Expose constants/parameters from Nutrient CERES models

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6458]
Taken from issue #6445 by @tkd708

I have a couple of questions regarding the use of APSIM Next Gen mainly from the perspectives of simulating soil N cycling as follows.

1. How can we see Nutrient module algorithms?
Related to the first question, I wonder about the algorithms behind the Nutrient module.
Some parts are visible by "Show model structure" but others are not shown there (only as memos) or in the code either (APSIMInitiative/ApsimX/Models/Soils/Nutrients/Nutrient.cs).
To my understanding, they are mostly inherited from SoilN in the classic. Nevertheless, it would be great if we could trace them step by step just like SoilN (SoilN documentation and/or the code in APSIMInitiative/APSIMClassic/Model/SoilN/SoilN.f90).

2. How can we modify Nutrient module constants?
Related to the first question, I would like to change some model constants (e.g. nitrification_pot, dnit_rate_coeff, etc...) as we could in APSIM classic by editing those in soil.xml.
How can we do that in APSIM Next Gen? "Replacement" shows only limited parameters and does not for those interested.
If currently not adjustable, would they be in future updates?

Again, I much appreciate the video as well as the documents currently available... it would be even more helpful if you could provide any information related to the questions above!

Best,
Naoya

It would be great if those constants were editable since they were changed in some previous studies (e.g. Thorburn et al., 2010).
Enabling the threshold parameter of WFPS above which denitrification starts (Mielenz et al., 2016; 2017) would also be helpful, which seems fixed at DUL in the current CERESDenitrificationWaterFactor component but was optionally editable in APSIM 7.10.

**Comment by hol353** [comment]
@APSIMInitiative/soil

**Comment by ric394** [comment]
@hut104 What parameters do you think should be exposed from Nutrient CERES models?

**Comment by tkd708** [comment]
Hi there,

I'm following up on this since I asked for this originally...

It would be great if the next gen model could have similar flexibility as the classic one, including some other soil N constants as follows.

```
<nitrification_pot units="ppm" description="Soil Nitrification potential (ug NH4/g soil)">40.0</nitrification_pot>
<nh4_at_half_pot units="ppm" description="NH4 concentration at half potential">90</nh4_at_half_pot>
<dnit_rate_coeff description="denitrification rate coefficient (kg soil/mg C per day)">0.0006 </dnit_rate_coeff>
<dnit_wf_power description="power term for calculation of water factor for denitrification">1        </dnit_wf_power>
<dnit_k1 description="K1 parameter from Thorburn et al(2010) for N2O model">25.1        </dnit_k1>
<dnit_wfps description="WFPS for calculating n2o fraction of denitrification">21.33333 100.0 </dnit_wfps>
<dnit_n2o_factor description="WFPS factor for n2o fraction of denitrification">0.0   1.18 </dnit_n2o_factor>
<nit_n2o_frac description="Fraction of nitrified nitrogen lost as n2o">0.0 </nit_n2o_frac>
```

I looked into the codes of next gen for locations of the constants above.

### CERESDenitrificationModel.cs
```
public double DenitrificationRateModifier { get; set; } = 0.0006
```

### CERESDenitrificationWaterFactor.cs
The water factor module in the next gen does not seem to have the power factor (Thorburn et al., 2010) or the adjustable threshold (Mielenz et al., 2016), but would it be possible to incorporate and expose them too?
```
double WF = MathUtilities.Divide(soilwater.SW[arrayIndex] - physical.DUL[arrayIndex], physical.SAT[arrayIndex] - physical.DUL[arrayIndex], 0.0);
```

### DayCentN2OFractionModel.cs
Some constants related to N2:N2O ratio.

```
public double N2ODiffusionCoefficient { get; set; } = 25.1;

if (WFPS > 21.3)
            WF = 1.18 * (WFPS - 21.3) / (100 - 21.3);
            double CO2Factor = Math.Max(0.16, Math.Exp(-0.8 * MathUtilities.Divide(NO3.kgha[arrayIndex], Nutrient.Catm[arrayIndex], 0)));
            double N2N2ORatio = Math.Max(0, N2ODiffusionCoefficient * WF * CO2Factor);
```

### CERESNitrificationModel.cs
Nitrification-related constants following Meier et al. (2006) and also the fraction for N2O from nitrification which I could not find.
```
public double PotentialNitrificationRate { get; set; } = 40;
public double ConcentrationAtHalfMax { get; set; } = 90;
```

Although I understand it wouldn't be recommended to change these and many other constants in cases of generic applications, it would be great if we could modify them in the model for research purposes to investigate processes with extensive datasets.

**Comment by hol353** [comment]
I'm unsure about the water factor but the other parameters / constants are all public and settable in a manager script or experiment factor. This will allow you to modify them for research purposes.

**Comment by tkd708** [comment]
@hol353, thanks very much for your swift reply.

Apologies that I missed recent updates... I'm having troubles running APSIM NextGen right now but can see the denitrification rate coefficient (#7696), part of N2:N2O ratio constants (#7575), nitrification parameters (#7272) and some others are exposed. I much appreciate the team's efforts for them.

I'm not sure if I followed the discussion on N2O from nitrification (#6410) correctly, but is the fraction parameter introduced and set editable?

It would be greatly appreciated if you could also expose the other constants in the water factor for both the denitrification rate as well as N2N2ORatio.

**Comment by hol353** [comment]
The N2OFraction from nitrification is settable.

The required changes to CERESDenitrificationWaterFactor will require someone to incorporate the functionality you want. N2O isn't my area of expertise and I don't have time so someone else will have to modify CERESDenitrificationWaterFactor.cs file. 

If you have the required skills you could make the changes to the file, attach it to this issue and we'll have a look at it.

**Comment by JodyBig** [comment]
Hi Naoya,
I believe the fraction of nitrifcation lost as N2O can be modified here.
![image](https://user-images.githubusercontent.com/29561776/218601093-e2e3dfc3-1805-4037-adad-9673e740cce3.png)

**Comment by JodyBig** [comment]
For your information the power function was not implemented originally because Thorburn et al., (2010) found optimising it did not improve predictions beyond that achieved by optimising denit rate only. Meilenz et al., 2016 also found the power function did not notably improve predictions

**Comment by tkd708** [comment]
Hi Jody,

Thank you for your input!
I had issues installing the updated version but now checked the settable fraction on my end too.

@hol353 I understand that and will look into how to modify the file.

**Comment by hol353** [comment]
Closing this for now as CERES parameters are now exposed and settable in GUI and via manager. The only bit that isn't done is the power function and the adjustable threshold in CERESDenitrificationWaterFactor. As noted by @JodyBig, optimising them doesn't improve predictions. If you want these incorporated for research purposes, then modify CERESDenitrificationWaterFactor.cs and attach to this issue or raise a pull request and we'll have a look at it.
