### ISSUE TITLE
SWIM ignores (?) CNBare parameter (and possibly others)

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6461]
[SWIMErrorRunoff.zip](https://github.com/APSIMInitiative/ApsimX/files/6490822/SWIMErrorRunoff.zip)

Setting CNBare to 0 should cause all water that cannot infiltrate to pond and there be no runoff. Attached experiment simulation shows that there are minor differences in runoff but not the extent that there should be. ?? possibly a unit problem?

@hol353 - can we discuss?

![image](https://user-images.githubusercontent.com/12176269/118427864-4cc9d980-b722-11eb-8d48-81a4d08a3651.png)

**Comment by hut104** [comment]
I think SWIM is working the same way as Soilwat.  CN runoff is an initial estimate of runoff, but sub-surface restrictions (e.g. water table, restrictive layer, etc) can result in some of this infiltration being unable to do so.  The water that did not infiltrate is added to the initial runoff estimate.

I think you can retain water on the surface if you want via specifying a soil water storage (ie the same as for soilwat).

From: Val Snow ***@***.***>
Sent: Monday, 17 May 2021 1:16 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] SWIM ignores (?) CNBare parameter (and possibly others) (#6461)


SWIMErrorRunoff.zip<https://github.com/APSIMInitiative/ApsimX/files/6490822/SWIMErrorRunoff.zip>

Setting CNBare to 0 should cause all water that cannot infiltrate to pond and there be no runoff. Attached experiment simulation shows that there are minor differences in runoff but not the extent that there should be. ?? possibly a unit problem?

@hol353<https://github.com/hol353> - can we discuss?

[Image removed by sender. image]<https://user-images.githubusercontent.com/12176269/118427864-4cc9d980-b722-11eb-8d48-81a4d08a3651.png>

**Comment by sno036** [comment]
Thanks @hut104  - does the CN runoff method ignore irrigation and just act on rainfall perhaps?

I am trying to test the water balance under ponding. It is not a restrictive soil layer issue here - Ks increases with depth.

**Comment by hol353** [comment]
By default CN runoff only acts on rainfall. There is a parameter in the irrigate apply method to let irrigation water run off. e.g.

Irrigation.Apply(100, willRunoff: true)

**Comment by sno036** [comment]
Thanks @hol353  - looking forward to the next steps
