### ISSUE TITLE
Reference Height in MicroClimate

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#6476]
It is possible for people to have Reference Height set to zero in MicroClimate if they have not thought about the value.

If Reference Height is zero, wind profiles become extreme and ET becomes very high (e.g. twice what they should be).

MicroClimate should check that Reference Height has some sensible value.

**Comment by hol430** [comment]
This is possibly related to #5946 - the micro climate source already specifies a lower bound of 0 and an upper bound of 10, but these values are never checked. @hut104 what would you suggest as a lower bound, and do you think a breach of these bounds should result in a fatal error?

**Comment by hut104** [comment]
It might be worth initially trying a test that reference height is between 1 and 10m and through a fatal if not.  We might find that we have tests within the system that have been committed with bad data and these may influence the nightly build.

________________________________

**Comment by hol430** [comment]
Ok, I have added a test for reference height in #6497 and it has caused jenkins to light up as expected. I can fix most of the failures, but in the interests of avoiding merge conflicts it may be easier for some people to fix problems themselves.

@her123 / @JulianneLilley: [This file](https://github.com/APSIMInitiative/ApsimX/files/6536397/canola.log) contains a list of simulations with uninitialised microclimates in the canola test set.

@sme016: [This file](https://github.com/APSIMInitiative/ApsimX/files/6536400/euc.log) contains a list of simulations with uninitialised microclimates in the eucalyptus test set.

If you click on microclimate in any of these simulations, you'll notice that all of the inputs are set to 0. I'm not sure what would constitute sensible defaults here. Perhaps @hut104 could comment.

**Comment by sme016** [comment]
Some clarification needed, please, as I find that some inputs are already not set to zero. E.g. for Eucalyptus at Coffs Harbour (1st on the list in your file), the inputs are in sequence: 0, 1, 0, 0, 0.13, 0, 0, 0, 0. More recently in commits involving temperate eucalypts I have been using 0, 1, 0.1-0.8, 0, 0.13, 0, 0, 0, 0.
So which of the zeros do you need to be changed?

**Comment by hol430** [comment]
The problem in this case is the reference height. It shouldn't be 0 - see Neil's initial comment for info. I'm not really sure what a sensible value is, but my test is checking that it's between 1m and 10m.

**Comment by sme016** [comment]
I assume you mean instruments other than rainfall, as I often see that at abouto.4 m?

**Comment by hut104** [comment]
The reference height is for wind speed measurements.

**Comment by hut104** [comment]
Let's start by just getting reference height set to 2m in each of the simulations.  
I'll add an issue about the redundancy in salb sitting in two models (ie microclimate and soil)

**Comment by sme016** [comment]
Thanks. Then I’ll change that value from 0 to 2 in all Euc validation sims the next round of commits to Eucalyptus.

**Comment by her123** [comment]
I can set all the canola ones also

**Comment by sme016** [comment]
Eucalyptus is now done and awaiting merging under pull request Euc microclimate #6503
