### ISSUE TITLE
Calculating Thermal Time for Use in APSIM - Video

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ApsimX#6477]
Please use this issue to comment and/or ask questions in relation to the following video:
https://youtu.be/t-8bwU9ke2s

**Comment by lie112** [comment]
This video is truncated and does not include the end of the presentation.

Very interesting Jeremy (git handle?) and sends my mind back to working with degree days in growing pastures in N Australia in the Savanna.au model.

**Comment by sarahcleary** [comment]
thanks @lie112.  Something has gone wrong with the upload to youtube.  I'll try and fix it now

**Comment by sarahcleary** [comment]
@lie112 - thank you.  updated - https://youtu.be/t-8bwU9ke2s

**Comment by sarahcleary** [comment]
If you're interested in receiving updates on new videos developed by the APSIM team, please email apsim@csiro.au
