### ISSUE TITLE
Should JSON data be culture invariant?

### ISSUE THREAD

**Issue by MikeStower** [APSIMInitiative/ApsimX#6483]
See the discussion at QAAFI/REMS2020#110

For manager script parameters, the DateTime data is being formatted as "MM/dd/yyyy" despite being presented as "dd/MM/yyyy" in client, which has caused the above issue. Is this intentional behaviour, and is it likely to change in future?

**Comment by hol430** [comment]
Data is displayed in the gui using the current culture/locale settings, but it's saved to the apsimx file in a culturally-invariant format. If someone saves a file on a German computer, I want to be able to open it on my Australian computer, and that wouldn't be possible if, for example, dates were saved using your computer's culture. Manager script parameters are saved in a somewhat unorthodox manner, but they should still be using the invariant culture. If you've found a case where that's not true, that will most likely be a bug. In general, the data as it appears in the UI is not necessarily indicative of how it will look in the .apsimx file.

Your example is the correct behaviour - MM/dd/yyyy is the invariant format for dates, and dd/MM/yyyy is the Australian (en-AU) culture. You shouldn't need to hardcode the MM/dd/yyyy format anywhere - just call ToString() on any DateTime object and specify the invariant culture.

The other thing to watch out for will be array parameters of manager scripts. If I recall, we save array properties as a single string with the values separated by commas(!). Can't remember if this affects all IEnumerable properties or just arrays - but it's only a "feature" of manager scripts.

**Comment by MikeStower** [comment]
Makes sense. As long as all the REMS data is exported in a culture-invariant format APSIM should be able to handle it then, and it is a nicer approach than directly specifying 'MM/dd'. 

Haven't had the pleasure of working with arrays in manager scripts yet, but I'll also keep that in mind for the future.

**Comment by hol430** [comment]
Copy that. I'll close this issue but feel free to reopen or open a new one if need be.
