### ISSUE TITLE
Overseer test VERY slow

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#649]
Prototypes\SCUM\Overseer is very slow and is the reason why Jenkins takes as long as it does. Any chance of speeding this up @HamishBrownPFR?

**Comment by HamishBrownPFR** [comment]
This test doesn't need to be there and could be deleted.  It was left there because there was an issues that it was demonstrating but I can't find it in the issues list and can't remember what it was so just delete it
