### ISSUE TITLE
Develop Chicory model

### ISSUE THREAD

**Issue by ndb01** [APSIMInitiative/ApsimX#65]

**Comment by rcichota** [comment]
Chicory (Cichorium intybus) is a perennial forage herb that has increasingly been used as a forage in New Zealand and elsewhere.  The chicory plant produces leafy tops and has a thick deep taproot, it can be drought and pest tolerant.  Chicory is also characterised by high nutritional quality and potential to produce high dry matter yields.  It can be used for animal grazing or for silage production (in mixed swards), with good regrowth after harvest/graze.
Given the increasing use of chicory as forage, there is a good demand for a model that is able to simulate its growth and regrowth in APSIM. It is one of the forage crops considered in a New Zealand study with the objective of reducing N losses from grazing systems by manipulating the mix of forages grown, thus influencing N and water usage as well as animal diet. Chicory grows in temperate and subtropical climates, the forage and therefore the model will have a wide range of interest worldwide.

**Comment by zur003** [comment]
Also of considerable interest in grazing systems in Australia.
