### ISSUE TITLE
Soil Albedo in two places

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#6500]
The soil albedo is currently set in two models (Soil and Microclimate).  MicroClimate should use the values in the soil, and in doing so allow for variations in soil albedo between zones.

**Comment by hol430** [comment]
@hut104 what do we want to do in cases where the soil's albedo is different to that in microclimate? This actually happens in the wheat example (the first file I looked at). In micro climate it's set to 0.3 and in soilwat it's set to 0.12.

**Comment by hut104** [comment]
I’d imagine that nobody has ever looked at the microclimate values.  The soil values appear more realistic as well.  Perhaps we just use those.

**Comment by hol430** [comment]
The microclimate values are actually used by microclimate (in the CalculateEnergyTerms() function). That being said - if we import a file from old apsim, should the soil_albedo in microclimate overwrite the soil albedo specified in the soil? And what would then happen if we import a single microclimate node from old apsim without a soil? Would we just throw away the soil_albedo?
