### ISSUE TITLE
Extract soil data from ISRIC in R 

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/ApsimX#6502]
Does anyone who had experience with extracting soil data source provided APSIM NG (https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PRFF8V) in R? If yes, could you please share your codes with me? Many thanks!!

**Comment by femiguez** [comment]
In case anyone is interested in this question. This is possible in the apsimx R package (in github). See function 'get_isric_soil_profile'. However, there are a number of unresolved issues at the moment about the best way to go about this.
