### ISSUE TITLE
Phenology Documentation errors

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#6511]
Nodes after the Phenology Phases are not appearing in the documentation correctly.
It adds text at the same level as the final Phase node text so there is no distinction.
The documentation generated by the chickpea model that is under review doesn't write out the names of any nodes below the phases..
Comparing it to the wheat documentation it looks like the issue is related to the OnEventFunction documentation

**Comment by hol430** [comment]
Closing as fixed.
