### ISSUE TITLE
Remove Surface Crop Residue with Crop Rotations

### ISSUE THREAD

**Issue by nicola31** [APSIMInitiative/ApsimX#6512]
I've been trying to migrate Apsim 7.10 "remove crop residue at harvest" across to Apsim2021.01.15.6004 but not having much luck with the code differences.  Is there an existing plug in available in an example?

I tried copying in the 'Defoliate' plug in from the Plantain example and calibrating that, with crop name changes but that didn't work either.

Any suggestions?
Thanks

**Comment by hol430** [comment]
I don't know what the 'recommended' way of doing this is (perhaps someone else can comment here), but as far as I know it should be possible to achieve what you want by modifying that defoliation script and setting the fraction to residue to 0. What specifically isn't working with your modified defoliator? If you upload the .apsimx file I'll take a look.

**Comment by nicola31** [comment]
Hi,

Thanks - sorry, lockdown in Melbourne, I got distracted.... 

I want to remove a fraction of the crop residue at harvest - 50% so I can simulate livestock grazing post harvest crop residue.  I have not been able to do that with the "Simple Grazing" plug in, so thought to have a set amount of manure applied and remove 50% of crop residue at harvest instead.  

If you have an alternative method to achieve that I would be very grateful for any suggestions.

[1950 2015 conventional wagga wagga May 2021.zip](https://github.com/APSIMInitiative/ApsimX/files/6587458/1950.2015.conventional.wagga.wagga.May.2021.zip)
