### ISSUE TITLE
Question: Edit rotation manager from config.txt file

### ISSUE THREAD

**Issue by youngmr290** [APSIMInitiative/ApsimX#6518]
Hi there,

Hoping this is the correct place for a question? If not please let me know.

I am looking to edit the rotation manager from the command line using config.txt file.

For example, I would like to change the rule and action for arc 1.
I would like the Rules to be: `[WheatManager].Script.CanHarvest`
and the action to be: `[WheatManager].Script.HarvestCrop("glable")]`

I have looked through the source code and I can access the Arcs variable. However, I am unsure how I can assign new rules and actions.

My config file currently looks like (this doesnt work):
`.Simulations.Mar1.Field.RotationManager.Arcs[1] = [WheatManager].Script.CanHarvest,[WheatManager].Script.HarvestCrop("glable")`

error: ` Unable to convert [WheatManager].Script.CanHarvest,[WheatManager].Script.HarvestCrop("glable") to type System.Collections.Generic.List`

So is there a way to enter a generic list in a config file?

Thanks.
`

**Comment by hol430** [comment]
Hi @youngmr290, the recommended way to set this would probably be something like

```
.Simulations.Mar.Mar.Field.RotationManager.Arcs[1].Conditions[1] = [WheatManager].Script.CanHarvest
.Simulations.Mar.Mar.Field.RotationManager.Arcs[1].Actions[1] = [WheatManager].Script.HarvestCrop("glable")
```

However I've just tested this and it looks like this doesn't work, due to a bug. It appears that our existing tests related to this functionality only test for array properties - not for generic lists or other such types. I'll fix this and let you know when the fix becomes available. (Are you using the installed version or a compiled version?)

**Comment by youngmr290** [comment]
Hi @hol430,

Thanks for chasing this up. 
I am just using the installed version obtained from the APSIM website. However, if required I can pull the source code?

Thanks.

**Comment by hol430** [comment]
The installed version is fine - if you upgrade your installed version to the latest version (>=6518), it should contain the bugfix, allowing you to use the syntax I mentioned above. Feel free to re-open this issue or open a new one if it continues giving you problems.

**Comment by youngmr290** [comment]
Thanks Drew, it all appears to be working.
