### ISSUE TITLE
Empty lines or lines with tab only in met files

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#6534]
Links to #6532 , in the weather file Tests/Validation/Barley2020NPI_WaggaWagga.met of master branch, there are three tabs and two spaces in the last line (L268).

Models.exe can use this file to run simulations. 

However, models.exe fails when I read the weather file and write into a new file from R. R add a new end of line to the file (L269). 

The error is Models.exe thinks L268 is a weather record without enough values. 

![image](https://user-images.githubusercontent.com/1657381/121110370-83da6900-c850-11eb-838d-8b9ccabe97f8.png)

Not sure we should fix it in the source codes or weather file which I have done in the pull request #6533.

**Comment by BrianCollinss** [comment]
If I'm not wrong, there is a argument in writeLines (perhaps other write functions as well) to address this.

**Comment by hol430** [comment]
I'm inclined to view this as a bug in our text file reader. I don't think it would hurt to fix this in the apsim source even if a workaround is possible in your R code.
