### ISSUE TITLE
Visual Basic scripting support in .Net Core

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#6539]
If you run the .Net core version of ApsimX in the IDE with all CLR exceptions reported, at run-time you will receive a "file not found" exception for the file Microsoft.CodeAnalysis.VisualBasic.Features. The exception is raised in CodeCompletionServices.cs, at a line reading:
            assemblies.AddRange(MefHostServices.DefaultAssemblies);

This isn't a particularly serious problem, and can be readily resolved by adding the appropriate version of the file via nuget, but my question is whether it is necessary. Are we supporting Visual Basic scripting in ApsimX? If so, then we should probably add it. If not, then we could add eliminate the use of MefHostServices.DefaultAssemblies and just add those assemblies needed for CSharp one-by-one (there are not very many).

So, @hol353, does ApsimX formally support Visual Basic scripting?

**Comment by hol353** [comment]
No APSIMX doesn't support VB. I don't think any of our users are using it so let's remove the use of that assembly.
