### ISSUE TITLE
Pause at end of simulation using multi-core workstations

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#6553]
When running the wheat validation set with a 32 core machine, the datastore keeps writing for about 200s after simulations have ended.  This only happens if the datastore is not emptied prior to running.

We need to speed up the process of deleting existing data from the datastore.

**Comment by zur003** [comment]
@hut104 - What sort of disk drive are you using? I recall a similar problem a while back, and finding that using as SSD was MUCH faster than a traditional drive. And I'm not seeing any pause of the magnitude you describe with the wheat validation set on my humble 8-core laptop.

**Comment by hut104** [comment]
I see the same - no delay on surface pro.  The issue will be a mix of disk speed and increased number of processors (32 in my case).

________________________________
