### ISSUE TITLE
apsimng.exe will not have response  in the big simulations if there are many errors

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#6556]
I am running barley.apsimx in the master branch with a few modifications in the report. The interface apsimng.exe have no response when running to the last simulation for couple times. After restarting apsimng.exe, I only run a single experiment and find some errors in my modifications. 

The whole barley.apsimx can smoothly run after fixing the error.  I believe it is related with interface cannot handle too many error messages as there are 2000+ simulations in the barley.apsimx file.

I also noticted models.exe only stop when all simulations are run even there are some errors. For example, I use the wrong variable name in the harvest report (`[Barley.Phenology.FloweringDAS`) (missing the right bracket). models.exe still run all simulations before display any error messages. It would be much easier if program stops when first error happens.

**Comment by hut104** [comment]
We may find a way to have the error messages remain in the status window so that they are visible. This would allow the user to end the simulations once they see many error messages.

**Comment by byzheng** [comment]
Would be useful to get an option to allow users decide to stop or continue running when error occurs.
