### ISSUE TITLE
Online Seminar Series: The nature of crop models (and modellers) needed to advance crop adaptation and improvement

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ApsimX#6561]
Please use this issue to comment and/or ask questions in relation to the following video:
https://youtu.be/6yfqUOCrUCk 
@uqghamme

**Comment by hol430** [comment]
Could these online seminar series issues be moved to another repository (ie reference panel repo) or consolidated into a single issue? The issues on this repo are intended for apsim-related queries, bug reports, feature requests, etc which can be closed once they are resolved. These issues don't do anything except advertise videos on the youtube channel and seem to stick around and slowly take over the front page of the issue tracker.

**Comment by sarahcleary** [comment]
Would it be possible to have these issues automatically close if inactive after a month  - just like the issues with the question label?

**Comment by hol430** [comment]
Good suggestion, I'm sure stale bot won't mind.

**Comment by sarahcleary** [comment]
@hol430 - will you set this up? or show me how to?
