### ISSUE TITLE
NO3 and NH4 concentration dynamics in soil

### ISSUE THREAD

**Issue by terenzio266** [APSIMInitiative/ApsimX#6576]
Hello
I'm traying to simulate the NH3N and NH4N concentrations dynamics in soil of a maize crop using the simulation attached. While is given me reasonbale N20 emission the NH3N and NH4N concentration does not show any variation compare to the initial level.
Can you give some advice ?
Thanks

[IT_BCI_2007.zip](https://github.com/APSIMInitiative/ApsimX/files/6707106/IT_BCI_2007.zip)

**Comment by BrianCollinss** [comment]
Until you get a better response, I would see if it is related to this issue: https://github.com/APSIMInitiative/ApsimX/issues/6505

**Comment by terenzio266** [comment]
Not easy to say....I'm using APSIM 2021.5.14.6410.
I have filled the chemical node with values in ppm and initailN node in kg/ha

**Comment by hol353** [comment]
What is the name of the variable you are reporting? Is it something like:
[Soil].Nutrient.NO3

**Comment by terenzio266** [comment]
No I have used
[Soil].Chemical.NO3N

**Comment by hol353** [comment]
All properties in the Chemical model are initial values only and won't change. If you're using the new Nutient model (recommended) then report:
[Soil].Nutrient.NO3

If you're using the older SoilNitrogen model use:
[Soil].SoilNitrogen.NO3

**Comment by terenzio266** [comment]
I'm using the new nutrient model (see my screenshot below). By using in the report 
[Soil].Nutrient.NO3

But I got the error message
Error in report Report: Invalid report variables found:
Soil.Nutrient.NO3: Cannot report variable "[Soil].Nutrient.NO3": Variable is a non-reportable type: "Solute".

My goals is to have the NO3 and NH4 dynamics concentration in soil (to be compared with the observed values)


![nutrient model](https://user-images.githubusercontent.com/83574578/124228263-4219a700-db0c-11eb-8678-3eadf57a9901.png)

**Comment by hut104** [comment]
NO3 is a solute model. So you need to output the reportable properties.

e.g. [Soil].Nutrient.NO3.ppm

________________________________

**Comment by terenzio266** [comment]
Thanks @hut104 it works now

P.s. sorry for my late answer. ......I was on holiday...!!!
