### ISSUE TITLE
Problem with simulation count in status area

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#6577]
When running a single simulation (e.g., the Wheat example simulation), the status area at the bottom of the screen indicates that there are 2 simulations, with the first completing almost immediately, so that one sees "Simulations running (1 of 2 completed)" when the (single) simulation is running.

**Comment by lie112** [comment]
This may also relate to the problem I am having where the results for datastore._Messages get written every time I run a simulation (duplicated) by clicking the simulation and selecting run. It seems to forget what simulation run is performed or no longer clears the datastore between manual simulations.

**Comment by hol430** [comment]
I'm having trouble reproducing the problem with the _Messages table - does the problem occur every time for you? I notice that the CleanCommand could run concurrently with the simulation which makes me wonder if this is a race condition...

**Comment by lie112** [comment]
@hol430 I am able to repeat the issue with the Messages table, by doing multiple runs of examples\clem\grazing.
I get a terminated successfully message each time it finishes with the correct clock, so it seems the table is not cleared at the start of a simulation.

**Comment by hol430** [comment]
Yeah there have been a number of changes to the database cleaning code over the last few weeks. I haven't used apsim much this week, but when I have, I've observed some suspicious happenings related to the datastore. Will look into this when I get the chance.

**Comment by hol430** [comment]
@lie112 - could you check if this is still an issue for you? I have a feeling it may have been fixed by #6669.

**Comment by lie112** [comment]
The incorrect counter display in GUI problem is fixed

HOWEVER
If the simulation has a long post simulation process the message displayed during this stage (something like "searching for simulations") is inappropriate and should be "finalising 1 of 1" or something

I will discuss the message table in database in the more appropriate #6586
