### ISSUE TITLE
OnInitialisationError corrupts the aspimx file

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6579]
For some reason the OnInitialisationError object is added occasionally to my Simulations model and then written to the apsimx file.
`  "OnInitialisationError": {
    "$type": "System.Action`1[[System.Exception, System.Private.CoreLib]], System.Private.CoreLib"
  },`

After this is added the file is corrupt and cannot be opened without removing this entry. This took me many hours to track down as the error is next to useless with no further detailed information is given. The error is "Value cannot be null. Parameter name: method" when trying to deserialize the model.

**Comment by hol430** [comment]
This should be fixed on latest master.
