### ISSUE TITLE
How to know variable names to add to report?

### ISSUE THREAD

**Issue by JRichetti** [APSIMInitiative/ApsimX#6588]
APSIM has a large number of output variables that previously you could search and simply double click to add them to your output report. Now you have to know it by heart? Where can I find what I want to output?

Let's say the soil water matrix. Would that be `[Soil].sws`? No, because it gives me an error.

**Comment by BrianCollinss** [comment]
Don't forger that in the output panel, when you add a dot after [Soil], you can see its properties and children. If you select a child and then add a dot, the sane. And so on. If you are familiar with APSIM structure, it would be easier. Otherwise, you can find the property that you are interested in by some patience.

**Comment by JRichetti** [comment]
Found it, but is not very intuitive. Even being familiar with APSIM structure. Thus, if possible I would suggest some thinking here, specially for new modellers. It will be challenging to have to both understand and find where things are. Maybe a quick how to with a list of what is where? Was a bit frustrating to me, so I am raising this as something to consider. Thanks! ;)

**Comment by ric394** [comment]
@JRichetti The large list of output variables functionality is now available in Report. However, the lists are quite small, if you have any reporting variables you commonly use, could you submit them through the issue system please?

1. We could provide a tab amongst the 'Property' and 'Data' tabs in the Report view that gives instructions on how to find events and report variables if that is helpful, might save newer modellers from having to read external documentation. 

2. A simple hierarchical diagram of a basic runnable simulation and the related report variables could be made to assist in knowing where to find common variables or events in a tab similar to the above.

**Comment by JRichetti** [comment]
Hi @ric394, thanks for following up on this. The list that comes in the report in the examples is what I mostly use. That is a massive help! Nonetheless, I would mind a little search box in that panel where one could type the description and look for some less-used obscure simulated variables :)
Great progress on this!

**Comment by ric394** [comment]
@JRichetti The Report and Event variable boxes allow you to type regular text to filter on the description field as you can see from the below picture. This should perform quite closely to a search box.

<img width="1151" alt="image" src="https://github.com/APSIMInitiative/ApsimX/assets/123442863/f699ac3f-7bbb-4e45-99ad-55499cc98ab6">

For now I'll close this issue but if you have further suggestions or improvements please create a new issue 😄
