### ISSUE TITLE
Scroll position of simulations tree after opening new file

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6590]
It seems the default scroll bar position upon opening is close to the bottom
Can frames open scrolled to the top?
If, for example, you have a large simulation tree, the simulation does not open up with the Simulations model showing which is not really logical given Simulations is the selected node.

_Originally posted by @lie112 in https://github.com/APSIMInitiative/ApsimX/issues/6573#issuecomment-869493997_

**Comment by zur003** [comment]
#6594 fixed the problem for Gtrk3 builds. Did the problem ever exist with Gtk2? If not, can this issue be closed?

**Comment by hol430** [comment]
The problem seems to occur for me in gtk2 builds - not sure why.

**Comment by hol430** [comment]
Closing as we've dropped support for the gtk2 builds.
