### ISSUE TITLE
How to run APSIMx on Linux from Python script?

### ISSUE THREAD

**Issue by JRichetti** [APSIMInitiative/ApsimX#6597]
I've downloaded the .deb file from APSIM initiative, extracted the contents and tried to run from Python 3 script on a Linux SuSE machine. 

```
import subprocess

apsim_exe = '/.../usr/local/lib/apsim/2021.06.22.6357/bin/Models.exe'
apsim_file = '/.../Wheat_simulation.apsimx'

subprocess.run([apsim_exe,apsim_file])
```
But I get an OS Error
`OSError: [Errno 8] Exec format error: '/.../usr/local/lib/apsim/2021.06.22.6357/bin/Models.exe'`

**Comment by hol430** [comment]
You'll need to install mono, and use the mono command to run Models.exe (`mono /path/to/Models.exe`). If you have a look around inside the .deb file you should see a script called Models (in `/.../usr/local/bin/`) which does just this.

**Comment by peter-devoil** [comment]
If you havent got a [binfmt_misc](https://www.kernel.org/doc/html/v4.14/admin-guide/mono.html) package installed alongside mono, then use /usr/bin/mono as your main process, apsim_exe as the 1st arg, and simulations after
