### ISSUE TITLE
Create new grid control for GUI

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6603]
We need a new, **simple**, grid control to replace the existing GTK grid (which is really just a tree view).

The grid should:
- allow multiple rows and columns to be frozen,
- be theme aware,
- allow cell editing,
- allow multiple cell selection,
- allow simple cell formatting (bold, italics, text left/right justification),
- NOT allow cells to contain drop downs, images, checkboxes etc.,
- NOT allow different fonts in cells.

**Comment by hut104** [comment]
It is good to see clear indication of things OUT of scope.  Less is more.  Grids have caused issues for a long time.

________________________________
From: Dean Holzworth ***@***.***>
Sent: Thursday, 1 July 2021 2:46 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Create new grid control for GUI (#6603)


We need a new, simple, grid control to replace the existing GTK grid (which is really just a tree view).

The grid should:

  *   allow multiple rows and columns to be frozen,
  *   be theme aware,
  *   allow cell editing,
  *   allow multiple cell selection,
  *   allow simple cell formatting (bold, italics, text left/right justification),
  *   NOT allow cells to contain drop downs, images, checkboxes etc.,
  *   NOT allow different fonts in cells.

**Comment by lie112** [comment]
I would like to be able to include some additional functionality or use the grid as a base class
I need to be able to provide an image (or font-icon) in each cell for a status report. Link image/icon to value for display.
At present this report has become slow to render and not very responsive to move around so look forward to grid and an upgrade to justify more girded display.

example of the current activity status report using the old treeview based grid
![image](https://user-images.githubusercontent.com/19215637/124206770-266dcb00-db23-11eb-9936-48f79cc11087.png)

Grid also needs to be more responsive for large datasets, display on demand as previously discussed.

**Comment by hol430** [comment]
You should be able to subclass the sheet widget, and just override the DrawCell() function. That would give you complete control over what gets rendered in each cell.

> more responsive for large datasets, display on demand as previously discussed.

Data retrieval is hidden behind an interface (`ISheetDataProvider`), and the current implementation used for the DataStore loads data lazily, so the UI remains responsive and loads quickly.

> read only switch to disable cell editing
> allow select cells/rows to be disabled

I don't think either of these has been implemented yet, but both will be needed for the soil profile grid, so they should eventually be added in some fashion.

**Comment by zur003** [comment]
There is a problem when running the .Net Core version on Windows. If the widget is too narrow, things get stuck in an infinite loop. The problem is in this block of code in SheetWidget.cs:

>              // Keep incrementing the number of hidden columns until the column
>             // is fully visible.
>             NumberHiddenColumns = 0;
>             while (!FullyVisibleColumnIndexes.Contains(columnIndex)) 
>                 NumberHiddenColumns++;
> 

The "while" loop never exits.

**Comment by hol353** [comment]
My idea is to keep the SheetWidget control simple. Most of the requests for changes (e.g. copy/paste and cell images) can be done in other classes, not the sheet widget itself.

Current implemented capabilities:

- multiple rows and columns can be frozen
- dark / light theme aware
- optional cell editing (sheets can be readonly)
- optional single cell selection (can stop all cell selection)
- simple cell formatting (bold, italics, text left/right justification)
- lazy loading of data. Will be much more responsive for large datasets
- read only switch to disable cell editing

Future needs:
- multi-cell select (this can be done by creating a new multi-cell select class
- copy / paste (this can be implemented in the multi-cell select class)
- ability to have some cells editable and others readonly. Adapt the SheetEditor class to allow this.
- cells containing images (I personally don't like this). Could extend the ISheetCellPainter interface to allow this quite easily.

Things not in scope.
- Cells containing different fonts.
- Cells containing drop downs, checkboxes etc.,

**Comment by hol353** [comment]
Closing this original issue. New, specific, issues about the grid / sheet control can be added.
