### ISSUE TITLE
How to set Initial SW from manager script

### ISSUE THREAD

**Issue by DavidJohnston491** [APSIMInitiative/ApsimX#6607]
Possibly going back on an old issue here (eg #4141)...
As part of a SOBOL analysis, I need to set Initial SW as FractionOfPAWC, evenly distributed, and use this in soil water resets. I am attempting to do this via a manager script.
Issue #4141, about InitialWater referenced in scripts, it said to use 

    **[Link] private Sample sample;**
    ...
    **sample.SW = x;**
    ...

Is this still the approach to use?

If so, how do I access the **PAWC,** or the **DUL** and **CLL** values?
I have the following links, but I am still unable to find a way to access the necessary soil water parameters.
        **[Link] Soil Soil;
        [Link] ISoilWater SoilWater;
        [Link] private Sample sample;**

(I am using APSIMX 2021.6.22.6357)

**Comment by hol430** [comment]
PAWC is a property of the physical node (if you click on the physical node in the GUI, you'll see there's a PAWC column). So if you link to the physical component you'll be able to access the PAWC array:

```csharp
[Link] private IPhysical physical;

...

sample.SW = physical.PAWC;
```

**Comment by DavidJohnston491** [comment]
@hol430 Thank you. That was the link that I missed.
