### ISSUE TITLE
Annoying exceptions

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#6612]
If one tries to run the Wheat Validation simulations under the IDE debugger, with settings to stop on all exceptions (whether handled or not) one sees a lot of exceptions (well, mostly Null Reference exceptions when trying to get a value for root depth, I think). Things seem to run correctly, but stopping for all these exceptions make debugging problematic. The triggering condition should be handled in some other way, rather than relying on silent exceptions.

**Comment by hol430** [comment]
If it's the problem I'm thinking of, then what's happening is that report is attempting to check the units each of its variables, which currently involves retrieving the value of the variable for some reason. At this point in time, many models haven't had a chance to initialise themselves, so many properties will throw when accessed. I haven't had a chance to look into this much further, but we really shouldn't be accessing the variables' values here.
