### ISSUE TITLE
SOBOL tables not cleared

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#6620]
Data seems to stay in the SOBOLStatistics table in the datastore between runs.  It seems that these are not cleared when emptying the datastore manually either.
The user needs to close the UI, delete the DB file, and then restart the UI between SOBOL runs.

**Comment by hol430** [comment]
On the latest version, emptying the datastore will delete the data for the current checkpoint, but leave the data for other checkpoints, which I think is correct.
