### ISSUE TITLE
MultiLineText dispay type in new property presenter

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6637]
Is the MultiLineText display type going to get the new rounded corners and padding for the new property presenter?
When multiple lines are provided with hard returns separating the values, an additional space is added between entries upon save, corrupting the stored value.

**Comment by lie112** [comment]
I think I'm working it out. It seems to accept a comma delimited string that it formats across lines, but that gets mucked up with the user deleted one of the entries from the list.

**Comment by hol430** [comment]
I think from memory this display type behaves differently for array/collection properties vs for regular string properties - it's something to do with splitting on commas (string property) vs splitting on linefeeds (string collection/array).

Will it have rounded corners - maybe one day. Multiline text properties use a GtkTextView widget which looks different to a GtkEntry widget (which we use for normal string properties). I have no idea if it's possible to get rounded corners on a GtkTextView - I would guess yes it's possible but I haven't looked into it.

**Comment by hol353** [comment]
I can't reproduce. Reopen if this is still a problem.
