### ISSUE TITLE
Productivity year reporting

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6638]
How do people manage the reporting of productivity year (e.g. financial year) for summary analysis?
I can see that this functionality could be managed by the Clock (property -> ProductivityYearMonth "Productivity year start month") with a property of Clock to report current productivity year.
For example [Clock].ProductivityYearToday for 10/7/2021 might return 2021 or "21/22" as .ToString() if July was set as start of year.
This also may apply to crop years and pasture years (especially in wet/dry tropics)
I was looking for the logical place for this an I don't think the top of the CLEM tree (Zone) is appropriate as multiple instances are possible in a simulation.

**Comment by hut104** [comment]
This looks very much context dependant and could/should be the property of the thing that needs it.

I'm thinking that we might need to start a discussion about financial records

________________________________
From: Adam Liedloff ***@***.***>
Sent: Friday, 16 July 2021 1:38 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Productivity year reporting (#6638)


How do people manage the reporting of productivity year (e.g. financial year) for summary analysis?
I can see that this functionality could be managed by the Clock (property -> ProductivityYearMonth "Productivity year start month") with a property of Clock to report current productivity year.
For example [Clock].ProductivityYearToday for 10/7/2021 might return 2021 or "21/22" as .ToString() if July was set as start of year.
This also may apply to crop years and pasture years (especially in wet/dry tropics)
I was looking for the logical place for this an I don't think the top of the CLEM tree (Zone) is appropriate as multiple instances are possible in a simulation.
