### ISSUE TITLE
Need to be able to specify a format in report.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6639]
Use case: I'm running many simulations on Microsoft VMs. Some of these VMs seem to reside in different time zones because in Report the Clock.Today sometimes is in dd/mm/yyyy format and sometimes it is mm/dd/yyyy format. 

Can we something like the 'format' statement in APSIM 7.10 e.g. allow this on a report line

[Clock].Today as Date format dd/mm/yyyy

**Comment by hol430** [comment]
Is this actually being stored differently in the database? (e.g. dd/MM/yyyy on some machines, MM/dd/yyyy on others?)

**Comment by hol353** [comment]
SQLite doesn't have a date data type as such, instead storing it as a string. You can see this if you open the wheat example, put a breakpoint in SqLite.cs in method ExecuteQuery and click on the graph in the GUI.

For the Clock.Today column it goes through this bit of code:
```c#
else if (sqliteType == SQLITE_TEXT)
{
    IntPtr iptr = sqlite3_column_text(stmHandle, i);
    columns[i].addTextValue(Marshal.PtrToStringAnsi(iptr));
}
```

**Comment by hol430** [comment]
What should happen is that dates should always be converted to a standard formatted text string (ie invariant format) when it's stored in the DB. When we read the results, there's some code to convert the date strings to .NET DateTime instances. When it's displayed in the UI, it should be once more converted to a string using the current culture.

So when you say you're seeing different formats depending on where the simulation was run - are you looking directly in the DB file (e.g. with the SQLite db reader program) or are you observing this in the GUI after clicking on a datastore node?

**Comment by hol353** [comment]
I'm not using the GUI at all. Some of my datacube (not APSIM) code is reading the .db files. I see if I can find more info on where the problem is.

**Comment by hol430** [comment]
Copy that. I would be reluctant to make the reporting code even more complex by adding something like this though.

**Comment by hol353** [comment]
Closing this issue. Turns out the problem wasn't with APSIM but with my code that was dealing with dates.
