### ISSUE TITLE
soil water content simulation

### ISSUE THREAD

**Issue by terenzio266** [APSIMInitiative/ApsimX#6648]
I'm trying to simulate the Soil water content (SWC) and compare the results with real observation of SWC measured as % of water in soil (typical TDR observation). Which parameter should I choose in the report ? is the 
[Soil].SoilWater.SW  (value in mm/mm) correct ? can the model simulation be compared  directly with the observed values ?

Thanks

**Comment by hol430** [comment]
Yep, `[Soil].SoilWater.SW` and `[Soil].SoilWater.Water` should both be correct. In theory, the only difference between the two properties is the units. It's also [possible](https://apsimdev.apsim.info/ApsimX/Releases/2021.07.21.6618/Report.pdf) to report only a particular layer or layers.

**Comment by terenzio266** [comment]
Thanks.
