### ISSUE TITLE
Reset sowing example from Management folder not working

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#6655]
Its seems that 'nutrients' have been renamed as 'chemical' at some stage, but the code has not been updated in this example.
I tried renaming all instances of nutrients to 'chemical' within the script but that didn't work

**Comment by hol430** [comment]
@AllanPeake which .apsimx file was this in? Was it one of the example files which come with apsim?

**Comment by AllanPeake** [comment]
Yes but it will be in any APSIMX file I would think. It is to do with the 'reset sowing' example that is located in the 'management' folder in the home screen. i.e. not in an actual simulation file.

**Comment by hol430** [comment]
The management toolbox has a script called "reset on sowing", is this the one you're referring to? As far as I can tell it seems to work. Chemical and nutrient are not the same thing...chemical's old name was analysis I think. The "old" version of nutrient was soilnitrogen. This script doesn't seem to reference analysis or soilnitrogen.

**Comment by AllanPeake** [comment]
I'll look at it again tomorrow when I have time. Couldn't get it working in the example chickpea sims I built so I gave up. Wanted a way to reset soilwater.

Will get back to you.
________________________________

**Comment by AllanPeake** [comment]
Just had a quick chance to look at it.

I put that script into the new chickpea validation example sim ‘ExtremeEnvironmentsKatherine’

And it failed. Gave the following error:

ERROR in file: C:\Users\pea235\OneDrive - CSIRO\a_chickpeas\Model finishing may21\Chickpea.apsimx
Simulation name: ExtremeEnvironmentsKatherineTOSSep
Models.Core.SimulationException ---> System.Exception: Cannot find a match for link nutrient in model .ExtremeEnvironmentsKatherineTOSSep.Field.Reset on sowing.Script
   at Models.Core.Links.ResolveInternal(Object obj, ScopingRules scope, Boolean throwOnFail)
   at Models.Core.Links.Resolve(IModel rootNode, Boolean allLinks, Boolean recurse, Boolean throwOnFail)
   at Models.Core.Simulation.Prepare()
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Prepare()
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager)

……..
So it is demanding something called ‘nutrients’ which I am not using. What is it? If it isn’t soilN, or chemical?

It seems that the problem is, you can put what I would consider ‘nutrients’ within ‘chemical’, ‘initial water’ and ‘soil nitrogen’.

So it is possible to run a sim without ‘nutrients’ whatever it is – but can’t use this script if you do.

Allan

**Comment by hol353** [comment]
Sounds like your chickpea model is using SoilNitrogen rather than the newer Nutrient model. We might need to go through the chickpea validation as well to ensure that Nutrient is being used. Time to get rid of SoilNitrogen!!!!

**Comment by hol430** [comment]
Is the chickpea file in version control currently the latest version? Or does Allan have a more recent version stored locally?

**Comment by hol353** [comment]
The one in version control is the latest. I can now 'release' it this week.

**Comment by hol353** [comment]
I have removed SoilNitrogen from the chickpea simulations.

**Comment by hol430** [comment]
Closing as fixed.
