### ISSUE TITLE
UI Locks up when being shared via zoom

### ISSUE THREAD

**Issue by ben-mallee** [APSIMInitiative/ApsimX#6658]
I've been using the APSIM2021.07.08.6612 Windows build, and demonstrating it to a class of students via a Zoom (v5.7.1) screen (window) share.
The students have also screen shared from their computers. 

The UI has locked up (won't open/close tree nodes, or do other actions like download/add soil) on a variety of computers (mine and student). This only happens when the window is being shared via zoom. It's intermittent - reminds me a bit of the behaviour of a single threaded browser app.

I'm not sure why Zoom is a particular problem. There has been no problem with the UI in other screen captures (eg OBS Studio).
Hopefully something that someone who is familiar with the UI components can figure out.

Cheers and well done on the new version!
Ben

**Comment by hol430** [comment]
Thanks for the heads up. I was able to reproduce on windows only, and only when sharing my entire screen (when sharing just apsim I didn't have any problems). The problem doesn't appear in the gtk3 builds - so ultimately this should solve itself when we release the gtk3 version.

See also: #5985

**Comment by ben-mallee** [comment]
Thanks Dean. Sounds like the same issue as #5985 . I didn't try sharing the entire screen; was having the problem with sharing the APSIM window itself. Hopefully the gtk3 release isn't far off.

**Comment by hol430** [comment]
@ben-mallee - the problems with webex are now fixed on the latest version, though I'm not sure about zoom. I did a quick check yesterday but didn't notice any problems.

**Comment by par456** [comment]
Works on Teams and Webex, closed.
