### ISSUE TITLE
Unable to overwrite .apsimx file after clicking "save as"

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6660]
1. Open any .apsimx file in the gui
2. Click save as
3. Select an existing .apsimx file
4. When prompted, click "replace" to overwrite the existing file

At this point, apsim should overwrite the specified file and close the file selection dialog, however, the file dialog seems to reopen, and the selected file is not changed.

**Comment by zur003** [comment]
Reopening, as it is not working correctly on Linux systems.
