### ISSUE TITLE
Datastore is not cleaned properly between serial runs in the gui

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6661]
1. Open the wheat example in the gui
2. Empty the datastore
3. Run the file
4. Click on datastore - should be 79 rows
5. Run the file again
6. Click on datastore - there are now 158 rows

**Comment by zur003** [comment]
And it keeps adding another 79 rows for each subsequent run.

Also note that emptying the datastore raises an exception (which is silently caught), while trying to execute "DROP TABLE keyset".
