### ISSUE TITLE
Denitrification from a water table? 

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#6663]
I don't understand why NO3 is denitrified from the water table in the attached simulation (which does not drain, is not reached by roots, and has almost no C and of that all is inert C) to which I have added nitrate. Inititally the nitrate is there, but it denitririfies almost entierly over a period of a few years. The reality is that, in the Mount Gambier region, it says around and is a problem for the town water supply.   
[Sims.zip](https://github.com/APSIMInitiative/ApsimX/files/6890457/Sims.zip)

**Comment by hol430** [comment]
@hut104 are you able to look into this for Phil?
