### ISSUE TITLE
Build fails because Models.deps.json was not found

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6681]
After pulling the latest changes to my working copy I cannot build APSIM.Server because I am missing \netcoreapp3.1\Models.deps.json

Error	MSB3030	Could not copy the file "C:\Data\Source\Repos\ApsimX\bin\Debug\netcoreapp3.1\Models.deps.json" because it was not found.	APSIM.Server	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets		

Any idea how I might fix this problem?

**Comment by hol430** [comment]
Try deleting bin and obj directories (visual studio has a "clean solution" option I think which may be more convenient).

**Comment by lie112** [comment]
Clean solution didn't work
I removed the bin and obj files from the various projects for full rebuild
Pulled all latest changes from master
Some builds have errors 
APSIMNG 
Model.deps.json from Microsoft.Common.CurrentVersion.targets
Model.runtimeconfig.json from Microsoft.Common.CurrentVersion.targets
Model.runtimeconfig.dev.json from Microsoft.Common.CurrentVersion.targets

APSIM.Server same issues as APSIMNG

APSIM.Tests no error logged. coverlet.collector.targets

Have we made any significant shifts to .Net Core that need to be included in solutions or anything?

**Comment by lie112** [comment]
Community help with issue
https://developercommunity.visualstudio.com/t/could-not-copy-the-file-depsjson-because-it-was-no/1400396
Clean solution, build solution, succeeds

But upon running ApsimNG
I get this error

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'UserInterface.Intellisense.CodeCompletionService' threw an exception.
  Source=ApsimNG
  StackTrace:
   at UserInterface.Intellisense.CodeCompletionService.Init() in C:\Data\Source\Repos\ApsimX\ApsimNG\Intellisense\CodeCompletionService.cs:line 48
   at UserInterface.UserInterface.<>c.<Main>b__0_0() in C:\Data\Source\Repos\ApsimX\ApsimNG\Main.cs:line 23
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Drawing.Common, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)


Rebuild solution results in errors reported above again

I have done a Visual Studio upgrade to 16.10.4

**Comment by hol430** [comment]
That type load exception will be related to the manager intellisense. I'll push up a fix, but for now you should be able to ignore it (it's non-fatal, right?)

**Comment by lie112** [comment]
It's fatal at present! I can't get passed CodeCompletionService.cs when running ApsimNG
I can get a successful build with Clean/Build solution (but not with Rebuild Solution), but can't run APISM. I have had a successful run while fiddling, but can't repeat it now.
