### ISSUE TITLE
Are all Models returned by FindChildren<> etc enabled?

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6689]
Have disabled models already been accounted for and removed by the time FindChildren<> is called, or does this need to be handled by the developer? I can't find any code, but have a feeling I saw this somewhere when the object is serialised.

**Comment by hol430** [comment]
Disabled models are removed from the simulations tree before the simulations are run. So if you're calling this function from the gui, you need to account for whether models are enabled or not. If you're calling this function from a running simulation, you don't need to account for whether the resultant models are enabled or not.
