### ISSUE TITLE
Checkpoints not working if not displayed

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#6697]
Create a checkpoint.
Click on predicted/observed graph - has the error message ```x is empty``` and nothing is displayed.
If you then click on the checkpoint and change 'Show on graphs' and go back, it seems to display ok.

Looks like it is creating an error if there are checkpoints that aren't displayed?
Possibly related: Clicking on the datastore and selecting the checkpoint and there is no data displayed in the table.

**Comment by jbrider** [comment]
Reopening the file and rerunning all simulations has ended up with the ```x is empty``` even when the checkpoint is set to show on graphs.  It's making it difficult to check for changes.

**Comment by hol430** [comment]
@hol353 - `FindInScope<IDataStore>().Reader.GetCheckpointShowOnGraphs("Current")` seems to return false. Is this deliberate? (My understanding is that the "Current" checkpoint should always be shown on graphs, so I would expect this to return true.) It's not the cause of this particular bug, but I thought it was a bit strange.

**Comment by hol353** [comment]
Yes it should probably return true.
