### ISSUE TITLE
Resizing of property presenter widgets with window resize

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6702]
The resizing of property presenter entry boxes cannot keep up with a quick resize of the window under windows.
Entry box right hand side resize works if you slowly shrink the window in windows with the mouse, but stops resizing as you start to change the window size quickly, or one rapid shrink.

**Comment by zur003** [comment]
@lie112 I'm not seeing that problem exactly, but if the vertical space available for the widget becomes too small, the application will crash.

**Comment by lie112** [comment]
Maybe it's because I have property presenter wrapped in the CLEM presenter
If I resize too quick the entry widgets don't resize.
If I shrink below the min widget size too quickly I don't get the horizontal scroll bar added

I can somewhat repeat the problem by shrinking horizontally the Report when open in properties tab but this seems to be after I go below a set size the GroupBy box stops shrinking and the scroll bar doesn't size but still works.
Summary does the same thing. There is some min width set somewhere

I need to add scroll bar functionality to the presenters added to the CLEM presenter tabs.

You will see the problem if you look at one of the CLEM examples. I don't think the resize widget  is my problem, but it could be because there is some other background cpu demand on resize I haven't handled

**Comment by hol430** [comment]
I can't see any problems with resizing quickly. There are some oddities, but they happen when resizing slowly as well. I also can't see a crash if I resize too small. Do you have high CPU usage or temperature (e.g. from another program) while you're observing this? If the ui is sluggish, my first guess would be that the main thread's event loop is not getting enough cpu time. This has happened to me before when running simulations. I've seen similar things on colleagues' computers when onedrive or dropbox decides to sync files.

To add scrollbars to the CLEM tabs - you should be able to do this by wrapping the appropriate widget in a ScrolledWindow widget.

**Comment by zur003** [comment]
@hol430 - I only see the "resize too small" crash with reports on the Gkt3 netcore version. It appears to me that the Gtk2 version maintains a minimum height for the widget, but the Gtk3 version doesn't.

**Comment by hol430** [comment]
Strange, I seem to have a minimum size in report on the gtk3 version too:

![resize](https://user-images.githubusercontent.com/36427516/129512650-27344784-6bab-4892-adc4-65cdfda4756f.gif)

I do see some noise from gtk in the stdout. Do you see these before it crashes? I'll look into it - they're probably worth fixing either way.

```
Gtk-CRITICAL **: 14:44:00.150: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
```

**Comment by zur003** [comment]
@hol430 - Try it with the "Data" tab open, rather than the "Properties" tab.

**Comment by hol430** [comment]
Ok - yep I'm seeing that one too. Fortunately it looks easy enough to fix.

**Comment by hol430** [comment]
@lie112 - is there a model (e.g. in one of the example files) which consistently shows this problem for you?

**Comment by lie112** [comment]
Try the CLEM\grazing example
Select the random number generator and the properties display
Resize from the right. You don't need to shrink the window very fast to be faster than the resize of the right of the property widget.

**Comment by zur003** [comment]
This appears to be a consequence of the handling of SizeAllocated in ModelDetailsWrapperView.cs. We need to find a better way. Can you point to an example where the size adjustments made in Vbox1_SizeAllocated are required?

**Comment by lie112** [comment]
Thanks for identifying that. No idea really, it's either from legacy code or was to address a problem with the description and title labels not fitting, but it seems to have very limited affect and turning it off fixes this quick resize issue.
So, happy to get rid of it!
In playing I am trying to work out where I need and extra scroll bar. I think the whole wrapper presenter needs to be in a scroll box as at present you can shrink the window smaller than the content of the wrapper presenter and only a scroll bar for the property presenter eventually appears and that doesn't let you scroll the hidden wrapper space.

**Comment by zur003** [comment]
ModelDetailsWrapperView.cs also has a HBox_SizeAllocated member function which is never used.

I followed the link in the Summary tag associated with VBox1_SizeAllocated, and it warns that "this method is a hack and should be used only if there is no other solution available. Why? Applications that use this hack will behave somewhat strange, since parent can be shrunk only for the difference between allocation width and actual label width during one allocate event. " That's exactly what has been happening - shrinking of the window has been restricted. 

If there are no objections, I'll gladly remove both *SizeAllocated functions....
