### ISSUE TITLE
Morris method in APSIM

### ISSUE THREAD

**Issue by tomtad92** [APSIMInitiative/ApsimX#6705]
Hi! 
I currently run the APSIM next GEN on Mac (ver. 2021.8.5.6674). I would like to run a sensitivity analysis with the Morris method that should be included in the Morris node (from the APSIM instruction: "It can be found in Models, and should be added at the same level as the DataStore"). Unfortunately I can't find where this Morris node is and how to add it on the APSIM main menu.
Could you please help me?
Thanks a lot for your support, 
Tommaso

**Comment by hol430** [comment]
Hi @tomtad92 - you'll need to open an .apsimx file if you haven't already. If you don't already have one open, you'll want to start with one of the example files ("open an example" button on home screen).

Once you've opened the file, you can add a morris node by right clicking on the "Simulations" node in the tree control on the left, and choosing "Add model" from the context menu.

![image](https://user-images.githubusercontent.com/36427516/129111666-e6a4570e-18d4-4242-bbb7-928d3750319b.png)

After clicking "Add model", you should see a screen similar to below, in the right hand panel. Just double click on the Morris node to add it to your simulation.

![image](https://user-images.githubusercontent.com/36427516/129111744-4930da74-d6a7-4c6e-bbca-23fe6f3e7b23.png)

**Comment by hut104** [comment]
It is usually easiest to start with a working example. There is a working Morris Example.  Adapt that by altering or exchanging the simulation within the Morris node.
Perhaps play with the example first to ensure that you understand how it works.

________________________________

**Comment by tomtad92** [comment]
Thanks @hol430 for the clear answer. 
I have a problem setting the parameter for the sensitivity. I'm working with residue decomposition module. I would like to extract the parameters that actually impact on the different factors limiting the residue decomposition (i.e. moisture factor, contact factor, temperature factor and C:N factor). For example, the moisture factor strictly depends from the cum_eos_max parameter (from APSIM manual). In the sensitivity analysis, I would like to insert the cum_eos_max parameter, but I can't find it with the Intellisense assistant in any module. In addition the potential decomposition rate seems not present. Could you help me?
Thanks, Tommaso

**Comment by tomtad92** [comment]
Thanks for your kind answer!
I have another issue to ask you about.
I have a problem setting the parameter for the sensitivity. I'm working with residue decomposition module. I would like to extract the parameters that actually impact on the different factors limiting the residue decomposition (i.e. moisture factor, contact factor, temperature factor and C:N factor). For example, the moisture factor strictly depends from the cum_eos_max parameter (from APSIM manual). In the sensitivity analysis, I would like to insert the cum_eos_max parameter, but I can't find it with the Intellisense assistant in any module. In addition the potential decomposition rate seems not present. Could you help me?
Thanks, Tommaso

**Comment by hut104** [comment]
You will need to use the variable names for APSIM Next Generation, not APSIM Classic.  The equivalent would be maxCumulativeEOS

However, that constant is private, so will not appear in your list.

________________________________

**Comment by tomtad92** [comment]
Ok that s clear! So there s no way to calibrate that kind of parameters?

**Comment by hol430** [comment]
The other factors you mentioned for potential decomposition are also inaccessible from outside the model in nextgen.
