### ISSUE TITLE
Improve "add model" assessment of ValidParent and expanded state

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6706]
The Add Model Presenter tries to remove unavailable models from the list offered to the user based on the parent model selected. This is not quite working as expected for models in CLEM. 
I'm happy that some models are always present (Functions, Memo, and can live with Map), but given only the CLEM timers have the valid parent ResourcePricing (see example below), I would not expect any of the other model folders to appear. Are they also functions to be accepted anywhere in the simulation tree?

With respect to branches expanded upon opening, it would be nice if when only a small number of models are possible (say less than 20) and a folder contains < 10 models, those branches are expanded on opening. Therefore, when only a couple options are available to the user in a single folder they will all show up expanded and save a couple mouse clicks to find them.

Example of "add model" screen when selected from a ResourcePricing model in CLEM. All branches expanded manually

![image](https://user-images.githubusercontent.com/19215637/129129177-59722105-ce80-42a1-91f2-2ba0e1a61779.png)

**Comment by hol430** [comment]
The idea is that IFunctions can be dropped anywhere, as they have `DropAnywhere = true` on their `ValidParent` attribute. Unsure how useful to this is - usually you will only need them in a PMF model. Perhaps others could comment here. Expanding all nodes when there are only a few visible seems like a good idea.

**Comment by hol353** [comment]
IFunctions can be dropped anywhere. I know Nutrient uses them so they aren't just a PMF thing. Auto-expanding nodes in the AddModels tree when the node only as a few child nodes (e.g. < 20) might work ok.  

Some of the nodes in the screenshot shouldn't be displayed e.g. AccumulateCohortExpression, ColdUpRegVrn1, PTQPhyllochron, HeightFunction, CNReduction..., RunoffModel etc. They are probably missing ValidParent attributes.

**Comment by hol430** [comment]
All of those models are showing up because they're IFunctions.
