### ISSUE TITLE
how to output soil moisture stress in ApsimX

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/ApsimX#6711]
Dear ApsimX users

Just wondering if soil moisture stress index is available from relevant crop model (let's say peanut) for output.  
I do remember this is possible for Apsim classic. Please let me know how to model and output soil moisture stress in ApsimX crop models. 

Looking forward to your help!

Thanks and regards!
qunying

**Comment by hol430** [comment]
@hol353 do you know what the relevant output variable would be here?

**Comment by hol353** [comment]
Usually it is FW for water stress and FN for nitrogen stress. These are in the leaf organ e.g.

```[Peanut].Leaf.FW```

It is a 0 to 1 variable. 0 is full stress. 1 no stress.

**Comment by qluo02** [comment]
Thanks, Dean!


________________________________
