### ISSUE TITLE
Sorghum crop

### ISSUE THREAD

**Issue by terenzio266** [APSIMInitiative/ApsimX#6718]
I'd like to simulate the N20 emission and the NO3 dynamics in  Sorghum crop (to compare the data with field observation).
In the APSIM 2021.5.14.6410 the sorghum crop is not available. I was wondering if is alredy available in more recent version (considering that is "under review" in the model documentation)

Thanks

**Comment by jbrider** [comment]
@terenzio266 The sorghum model is still being worked on. I am currently cleaning up a lot of existing code, so be wary of developing using the under review model.  The answers it gives are the same as Apsim Classic - but any cultivar parameters or scripts that reference current naming may may change (there shouldn't be too many of them though).

**Comment by terenzio266** [comment]
Thanks
