### ISSUE TITLE
APSIM root model

### ISSUE THREAD

**Issue by sarchontoulis** [APSIMInitiative/ApsimX#6725]
As part of a project supported by ISU and AI, we are current working on testing the APSIM NG root module using data from Iowa. We will have our first meeting on March 12 to review the Next Gen root model, come up with alternative modeling concepts for potential implementation/testing and identify additional datasets or scientists. The focus of the meeting will be on the simulation of root mass, root nitrogen, and root to shoot ratio.

@hol353 @HamishBrownPFR @hut104 @EnliWang @uqghamme; @kchenu @ElvisElli

**Comment by hol353** [comment]
Closing as this is very old and very general. If work is still happening on the root model then I suggest you open a more specific issue.
