### ISSUE TITLE
Refactor Sugarcane code

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6729]
- Change all .apsimx files to use a sugarcane resource file rather than their own copy of sugarcane.
- The code needs a tidy up.

**Comment by BrianCollinss** [comment]
Hi @hol353 Is there any plan to re-structure sugarcane into PMF? BTW, as you are aware there has been some minor changes and bus fixed in the classic Cane.

**Comment by hol353** [comment]
No, we don't have funds or resources to move sugarcane into PMF at this stage.

**Comment by hol353** [comment]
> Change all .apsimx files to use a sugarcane resource file rather than their own copy of sugarcane.

This has been done.
