### ISSUE TITLE
Documentation for "contribute" is still pointing to SourceTree

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6736]
https://apsimnextgeneration.netlify.app/contribute/sourcetree/getsource/
![image](https://user-images.githubusercontent.com/12176269/130184040-191bbba4-96d9-4bb9-b2ae-beac82d3e545.png)
The URL highlighted has a stray trailing “]” giving a 404

![image](https://user-images.githubusercontent.com/12176269/130184086-d149fc60-d478-4963-9142-a690aaacef1a.png)
If want to use current Fork terminology then:
-	“Clone / New” is now “Clone”
-	“Source Path” is now "Repository Url”
-	“Destination Path” is now “Parent Folder”
-	If you use the destination path as in the current doco you end up with one extra APSIMX layer in the folder structure

![image](https://user-images.githubusercontent.com/12176269/130184122-3d9ceaf6-930d-4d3c-89da-ad6115f5ef80.png)
Perhaps add text to make clear that this is in Fork? (first dot point?)
-	“Repository | Settings for this repository”
-	Right click Remote, Add new
(I kind of stopped here but it all needs a bit of a refresh to get it current)

![image](https://user-images.githubusercontent.com/12176269/130184190-e54190ec-0121-417c-9750-f92bf936b728.png)
![image](https://user-images.githubusercontent.com/12176269/130184195-6864e995-d15e-4399-9004-eaa0aac1c7f8.png)

**Comment by hol430** [comment]
*Do* we want to recommend fork? We discussed this in #5106 and I stand by what I said then.

> git fork costs money. Do we really want to encourage people to shell out $50 just to contribute to apsim? Especially when there are plenty of [free alternatives](https://git-scm.com/downloads/guis).

To be honest, I'm not sure why we even have instructions for using sourcetree on our website - it's not our software, and there are plenty of better guides out there for sourcetree, fork, or whichever other git client you may choose to use.

Good catch on the trailing ']', I'm surprised no one has never noticed that before.

**Comment by ric394** [comment]
This issue should be resolved by #7753. 
The SourceTree section has been returned to draft status and the overall process has been updated.
