### ISSUE TITLE
Editing .apsimx file from Python

### ISSUE THREAD

**Issue by JRichetti** [APSIMInitiative/ApsimX#6743]
Hi APSIMx team,

I would like to control APSIMx from Python. I've been able to call and run the model, but I'm struggling in how to edit the APSIMx to change the simulation, lets say change the fertilising application and date or the amount of fertiliser at sowing. With APSIM Classic was relatively easy to search the xml file for the parameter that I wanted to change and change it. For example:
```
change_temp = apsim_xml.findall('.//fert_amount_sow')
change_temp[0].text = str(new_fert_amount)
```
I'm looking with the json structure of the .apsimx file and I can't really get similar results. Any tips or guidance is much appreciate.

Cheers,
J

**Comment by lie112** [comment]
You are able to use standard json manipulation tools in python.

We use ujson.
`try:
    import ujson as json
except ImportError:
    try:
        import simplejson as json
    except ImportError:
        import json
`
Then we have a series of custom methods to grab or write the various tree elements
Let me know if you'd like a copy of some code to help you get started

**Comment by hut104** [comment]
APSIM has built methods to allow manipulation of parameters within the command line.  This is often used in parameter optimisation.  
Check the command line for models.exe
