### ISSUE TITLE
N20 emission daily dynamics

### ISSUE THREAD

**Issue by terenzio266** [APSIMInitiative/ApsimX#6747]
hello
I was wondering if is possible to get N20 emission at hourly (or 30 minute) time step. I'm comparing N20 measured with the eddy covariance and simulated (see figure attached). After the N fertlisation N20 measured showed a well defined daily trend....and I'd like to simulate it
Thanks
![eddy vs APSIM110 kg](https://user-images.githubusercontent.com/83574578/130924760-c937d7cc-c833-4347-8a8c-ee64d7ad6c68.jpg)

**Comment by sno036** [comment]
@terenzio266  - the model is running on a daily timestep so that is the shortest step that can be reported. The only solution here is to aggregate the flux data to a daily basis. Note also that APSIM stops at the generation process and does not include the time delay in diffusion through the profile so a cumulative comparison can be a good idea.

**Comment by terenzio266** [comment]
Thanks @sno036 
One more question: is the documentation of the new Nutrient model available ? i.e. equations adopted 
Thanks
Terenzio

**Comment by sno036** [comment]
Yes - see https://apsimnextgeneration.netlify.app/modeldocumentation/
The equations are unchanged from the (very old!) Probert publication. N2O emissions have been added using a DayCent style approach based. There has been limited testing of this (read the axes on the validation plots carefully! they are not the traditional measured-observed) so approach with a degree of caution. The test set obviously needs a good N2O data set at some point.

**Comment by terenzio266** [comment]
Thanks
One more thing: would be possible add an error (i.e. stadev ) of the APSIM N20 emission ?
My comparison of one year of eddy covariance vs ASPIM N20 emission is quite promising....see fig attached

![cumulative emission](https://user-images.githubusercontent.com/83574578/131628558-cf33d4ee-d147-4239-8e8b-506516771d54.jpg)
![Eddy vs APSIM](https://user-images.githubusercontent.com/83574578/131628559-2d62121e-888c-40c0-b916-a43879e9c1d5.jpg)

**Comment by terenzio266** [comment]
Thanks
