### ISSUE TITLE
Documentation continued

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6750]
Model design
Communicating With Other Models - Links example 
The private variable Clock should start with a lower case 'c'

Auto documentation
Paragraph 3, unneeded hard return

Software interfaces
First line is missing a word "be" I think. Doesn't quite make sense

User interface
Model view presenter
Change all xml - json to reflect latest approach

Build a model tutorail
At end. For advanced users and further understanding of APSIM Next Gen and the ordering of models all responding to a single published event.
Note: Two instances of this model in the Explorer tree structure would apply their cumulative changes in the order that they are provided in the simulation tree. The logic would hold that they both respond to the published PreparingNewWeatherData event, with the second model using the altered rainfall as a result of the first model and it's OriginalRain reporting the first altered ranfall.

**Comment by lie112** [comment]
relates to #6749 
All my comments and corrections from reading the APSIM Next Gen online documentation

**Comment by lie112** [comment]
I am unable to find the documentation from source control to make these changes.
![image](https://user-images.githubusercontent.com/19215637/131267744-3f27d17a-e08a-4a08-b42e-97051329f86e.png)

**Comment by hol430** [comment]
It doesn't have any .cs files - so it won't show up in visual studio. You'll need to look in a file explorer.
