### ISSUE TITLE
I'm not sure EnergyBalance.cs is in the right folder

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#6761]
It is in the PMF/Organs folder.  It is not an organ.

**Comment by HamishBrownPFR** [comment]
Its not in the right folder.  I will have a tidy up of this and other things in the stuff I am doing with organ and arbitrator at the moment.  There are plenty of other things that are not really in the right place either like SupplyFunctions and DemandFunctions are in the Functions folder and name space but they only work on an organ so should be moved back into the plant folder and namesapace.  They were moved out when the other functions were made generic for use in models other than plant.
