### ISSUE TITLE
Property presenter drop-down pop-up. Autocomplete?

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6780]
The pop-up for the drop down widget in property presenter needs to have a max height and maybe a top at the bottom of the parent widget. At present it will go to screen height with large lists of options filling any extra room with white space (as seen in the image below on a portrait monitor). 

As it is only the  move up and move down arrow icons on the pop-up that allow navigation to the option you require, it is slow to select an option in large lists as there's no scroll bar handle.

Could I request someone with Gtk# skills create an auto complete selector that allows the user to start typing to select the value from the list. This is not a combo box allowing any value, but must select an item in the list

The pop-up should therefore start at the date entry widget and go down for a max height with maybe a scroll bar to make looking around the list faster for the user.

![image](https://user-images.githubusercontent.com/19215637/132419664-f52afa26-7dbf-48bd-ac19-a9d197a602b5.png)

**Comment by par456** [comment]
At some point this was improved, dropdown goes from the box position to the bottom of the screen, has a scrollbar and mouse support. Closing this issue unless I missed something.
