### ISSUE TITLE
Open and Save dialog boxes in Core

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6787]
I have found that the open dialog box (from Open APISM file on toolbar) became slow to respond a couple months ago. I put this down to working from home, but I think it's worth a check as it has the same response to local files.

If you double, or triple click this button (.Net Core) it will open multiple dialog boxes.
I noticed this when slow opening tempted me to click again to make sure it was working.

This is a triple click of the Open APSIM file button
![image](https://user-images.githubusercontent.com/19215637/132601678-ea4d63c7-fdb6-4ecc-bfb4-5869dc110531.png)

**Comment by hol353** [comment]
I can't reproduce. Reopen issue if still a problem.
