### ISSUE TITLE
Run code linter as part of jenkins builds

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6791]
Need to run a code linter as part of jenkins builds to automatically fail pull requests which don't follow style guidelines. Ideally this would only fail a pull request on the basis of lines of code which were changed by that pull request.

**Comment by hol353** [comment]
This one will take a while. We'd like to turn on StyleCop (a lint tool) for the Models assembly. @hol430 made a start on this but it was never completed. Attached are his files. I think the .editorconfig file is the newer way of using StyleCop and supercedes the older Settings.StyleCop file. Might need to google how StyleCop works.

There will be *a lot* of old code that needs to be refactored to make it pass the StyleCop rules. Perhaps you could turn on one rule at a time and get that to pass before turning on another rule.

[StyleCopSettings.zip](https://github.com/APSIMInitiative/ApsimX/files/10762841/StyleCopSettings.zip)
