### ISSUE TITLE
Problem opening named pipes in Linux

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#6798]
I have a model that includes a manager script that communicates with another application (Simile) via a named pipe. This all worked when ApsimX was built on Mono. However, I just upgraded to version 6775 and I am getting a weird error message which I suspect may be something to do with the fact that it has moved to .Net Core 3.0. The message is:

APSIMef5d821f-8661-43cf-bf2d-f9d17764ea73.cs(45,24): error CS1069: The type name 'NamedPipeClientStream' could not be found in the namespace 'System.IO.Pipes'. This type has been forwarded to assembly 'System.IO.Pipes, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

I am executing Apsim using .NET Core SDK (3.1.412)

**Comment by hol430** [comment]
Hi @jal-frezie - yep, the manager script compilation is completely different in the .net core builds. In #6801 I've added the missing referenece to System.IO.Pipes.dll which I think should fix your problem. (With that fix, I was able to use a manager script which referenced the NamedPipeClientStream type.)

**Comment by zur003** [comment]
@hol430 - #6801 fixes the immediate problem, but are there likely to be any other situations where the author of a manager script will want to reference an assembly that we're not automatically including? Should we provide a mechanism to allow script authors to specify additional assemblies? I suspect this sort of thing is enough of an edge case that we don't really need it, and that providing such a mechanism would, 99.999% of the time, just clutter the user interface, but I thought I should raise the question.

**Comment by hol430** [comment]
I think managers should probably aim to allow references to most (all?) "standard" libraries out of the box. If we're missing one, I'd probably consider that a bug. As for non-standard libraries, I'm not sure.

I don't think this feature would clutter the UI too much - I'm imagining a button somewhere on the manager UI, or maybe an extra tab (alongside properties and script tabs). We could store the file name of any custom assembly(s) (without path) as a property of the manager. The trick would be loading this assembly on another machine. Did old apsim have this feature? If so, how did we handle it there?

**Comment by peter-devoil** [comment]
Yes, classic had a "miscellanous assembly" [UI component](https://github.com/APSIMInitiative/APSIMClassic/blob/cfeceaf62b2ca0435e7a9df9b93b68eee702ffcd/Model/Manager2/Manager2.cs#L122) that would sometimes work (eg if it was the correct framework version etc)
