### ISSUE TITLE
Specify order of properties in property presenter

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6806]
Would it be possible to allow developers to include the 
System.ComponentModel.DataAnnotations.Display attribute with associated Order property on any property to further define the order that properties are presented in the property presenter?
At present the properties are ordered as provided in the model using line number of the description attribute associated with the property.
This is not sufficient for properties inherited from a base classes and an additional order index would allow customisation of property order or some or all properties of a model.

propertyList.OrderBy(Display.Order).ThenBy(Description.LineNumber)
If no order properties were provided then this would revert to LineNumbers and all properties without a Order (0) would also be sorted by line number rather than the base alphabetical from GetProperties

**Comment by hol430** [comment]
Seems reasonable, as long as we don't need to modify all of the existing display attributes. Sounds like setting a default value of 0 means that won't be necessary.

**Comment by lie112** [comment]
I think this is totally backward compatible and would not require any change to any existing model. Adding this optional property will add further functionality to a model allowing the developer to easily move to top or bottom of list and full customised list order by attributing all properties if required. Setting 0 is not neccessary but assumed if Order not provided so easy to move before -ve or after 1000 (a number larger than 0) the current list of properties working with linenumber
The question is whether to use System.ComponentModel.DataAnnotations.Display or Add Order Property to Core.Display that models are already using. There is currently a little using confusion between System..Display and Core.Display. I suggest using the available System..Display.Order as that is what it is intended for and the logical place to look for that.

**Comment by hol430** [comment]
The `Models.Core.DisplayAttribute` contains some features which are missing from  `System.ComponentModel.DataAnnotations.DisplayAttribute` (e.g. display type). The one in System is also a sealed class so we can't extend it. So best bet is probably modify the one in Models.
