### ISSUE TITLE
Error: package 'ggplot2' was installed before R 4.0.0: please re-install it Execution halted

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#6818]
hi guys
last version of ggplot2 is2.3.3 and croptimizerR has not funded from apismRpacks.  I had to installed  from SticsRPacks.so I'm not sure where is the exact problem comes from.anyway when Im trying to install older R version than 4.1.1 v suitable to ggplot2 like R3.3.2  ,this time croptimizeR and corresponding packages isn't supported. and apsimx send this message"Error: package 'ggplot2' was installed before R 4.0.0: please re-install it
Execution halted".

**Comment by hol430** [comment]
This repository is not the place for problems with R or R packages. That said, the apsim wrapper for CroptimizR will not work with R versions earlier than 4.0.0 (I'm not sure about CroptimizR itself). In general, you need to be careful switching between R  >=4.0.0 and R <4.0.0. Usually, you would need to reinstall most/all(?) of your packages if you do this.

**Comment by masooandy** [comment]
The problem belongs to apsimx.becuas occurred through apsimx run ?doesn't it?  this leads croptimizer useless. 
I tried every thing  including  older versions nothing good hapend.left whitout choice .then share broblme here.this helps others.

**Comment by masooandy** [comment]
How ever if it's wasting your time please accept my apology
