### ISSUE TITLE
Add possibility of comments in Operations

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6825]
This is a nice to have - a useful way of documenting assumptions etc.

**Comment by hol430** [comment]
Also a good way to accumulate cruft in your .apsimx files over time - similarly to disabling models :). But we do allow this in report so it probably makes sense to have it in operations as well.

**Comment by hol430** [comment]
@sno036 - actually I just had a look at this and it appears that this is already possible. Is it not working for you?

![image](https://user-images.githubusercontent.com/36427516/135936160-f02b3d71-5370-42d9-8ee5-ed6fd8ccab31.png)
![image](https://user-images.githubusercontent.com/36427516/135936182-56bbe585-e156-4c08-9171-f960bd877040.png)

**Comment by sno036** [comment]
Well - that is odd! It works for me too. Must have been a different error that I assumed was the commenting! Thanks @hol430
