### ISSUE TITLE
About APSIM server socket connection, can anyone provide Python script examples

### ISSUE THREAD

**Issue by xiangyi-wang** [APSIMInitiative/ApsimX#6830]
I have successfully connected to APSIM server according to the documentation and the C API example. But I don't know how to send messages to the server further.

`def start_apsim_client(msg,host = '127.0.0.1', port = 27747,socketname='ApsimNGServer'):
    if platform.system().lower() == 'windows':
        clientSoscket = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
          # socket.gethostname()#获取本地主机名
        addr = (host,port)
    elif platform.system().lower() == 'linux':
        clientSoscket = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        addr = "\0"+socketname
    clientSoscket.connect(addr)

    while True:
        # msg=input('>>>').strip()
        if not msg:
            break
        # 向服务器发送指令
        clientSoscket.send("RUN".encode('utf-8'))
        # clientSoscket.send("[Phenology].Phyllochron.BasePhyllochron.FixedValue".encode('utf-8'))
        # clientSoscket.send("1.5".encode('utf-8'))
        # clientSoscket.send("READ".encode())
        # clientSoscket.send("HarvestReport".encode())
        # clientSoscket.send("Wheat.AboveGround.Wt".encode())

        # 接收服务端返回的数据
        msg = clientSoscket.recvfrom(1024)

        # print("From Server:", msg.decode())
    clientSoscket.close()`

`Starting server...
Listening on 0.0.0.0:27747...
Waiting for connections...
Client connected to server.
Waiting for commands...
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at System.Text.Encoding.GetString(Byte[] bytes)
   at APSIM.Server.IO.NativeCommunicationProtocol.WaitForCommand() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Server\IO\NativeCommunicationProtocol.cs:line 54
   at APSIM.Server.IO.NetworkSocketConnection.WaitForCommand() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Server\IO\NetworkConnectionManager.cs:line 99
   at APSIM.Server.ApsimServer.Run() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Server\ApsimServer.cs:line 58
   at APSIM.Server.Program.Run(GlobalServerOptions options) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Server\Program.cs:line 40`

**Comment by xiangyi-wang** [comment]
change title

**Comment by hol430** [comment]
Hi @xiangyi-wang - I would recommend calling the C api from python, rather than attempting to re-implement the communication protocol, which is still in a state of active development and is subject to change. One way to achieve this is to use something like the [ctypes](https://docs.python.org/3.8/library/ctypes.html) library. For example:

```python
from ctypes import cdll
from ctypes import c_ushort
from ctypes import c_int

client = cdll.LoadLibrary("libapsimclient.so")
client.connectToRemoteServer.restype = c_int
client.connectToServer.restype = c_int

def connect_to_remote_server(ip_address, port):
    return client.connectToRemoteServer(ip_address.encode('UTF-8'), c_ushort(port))

def connect_to_local_server(pipe_name):
    return client.connectToServer(pipe_name.encode('UTF-8'))

def disconnect_from_server(socket):
    client.disconnectFromServer(c_int(socket))

print('Connecting to remote server...')
socket = connect_to_remote_server("127.0.0.1", 27746)
print('Successfully established connection to server. Disconnecting...')
disconnect_from_server(socket)
print('Disconnected')
```

Note that I haven't tested this feature on windows at all.

**Comment by xiangyi-wang** [comment]
> Hi @xiangyi-wang - I would recommend calling the C api from python, rather than attempting to re-implement the communication protocol, which is still in a state of active development and is subject to change. One way to achieve this is to use something like the [ctypes](https://docs.python.org/3.8/library/ctypes.html) library. For example:
> 
> ```python
> from ctypes import cdll
> from ctypes import c_ushort
> from ctypes import c_int
> 
> client = cdll.LoadLibrary("libapsimclient.so")
> client.connectToRemoteServer.restype = c_int
> client.connectToServer.restype = c_int
> 
> def connect_to_remote_server(ip_address, port):
>     return client.connectToRemoteServer(ip_address.encode('UTF-8'), c_ushort(port))
> 
> def connect_to_local_server(pipe_name):
>     return client.connectToServer(pipe_name.encode('UTF-8'))
> 
> def disconnect_from_server(socket):
>     client.disconnectFromServer(c_int(socket))
> 
> print('Connecting to remote server...')
> socket = connect_to_remote_server("127.0.0.1", 27746)
> print('Successfully established connection to server. Disconnecting...')
> disconnect_from_server(socket)
> print('Disconnected')
> ```
> 
> Note that I haven't tested this feature on windows at all.

**Comment by xiangyi-wang** [comment]
Thanks @hol430  How do I send the run and changes command to the server after I establish a connection.When I run the following code, the server still prompts to wait for the command, and the client does not get a response.
` clientSoscket.send("RUN".encode('utf-8'))`

**Comment by hol430** [comment]
Hi @xiangyi-wang - what command line arguments are you using to start the server? If you use `-m`, the server will be attempting to read commands in "managed" mode, which works well if you are connecting from a C# client, but will be pretty useless in any other scenario. You will want to use `-n` instead - which tells the server to attempt to read commands in "native" mode.

**Comment by xiangyi-wang** [comment]
This is my command line
`>E:\APSIM\bin/apsim-server.exe --file E:\APSIM\Examples\Wheat.apsimx --verbose  --native --remote --address 127.0.0.1 --port 27747`

**Comment by hol430** [comment]
Ok - if you're using the native protocol, you'll need to first send the length of the message before sending the message itself. The length of the message should be a signed integer (so 4 bytes). This applies to every message that you send. You can see the C implementation of this [here](https://github.com/APSIMInitiative/APSIM.Client/blob/master/src/client.c#L81).

**Comment by xiangyi-wang** [comment]
Thanks! @hol430  This is where I'm confused. Let me try.

**Comment by xiangyi-wang** [comment]
Successful!
```
    while True:
        msg=input('>>>').strip()
        if not msg:
            break
        # send message
        length = len(msg.encode('utf-8'))
        slen = '%08d' % length
        msg = slen + data
        print(msg)
        clientSoscket.send(msg.encode('utf-8'))
        msg, ADDR = clientSoscket.recvfrom(1024)
        if not msg:
            break
        print("Server Response：", msg.decode('utf-32'))
```
