### ISSUE TITLE
Directed graphs (ie nutrient, rotation manager) don't respect user's font settings

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6833]
Title. This is probably due to our usage of `Cairo.Context.ShowText()`. We should probably be using the parent widget to create pango text layouts.

**Comment by hol430** [comment]
Probably not related but good to know nonetheless. Are you looking at the rotation manager in the example file? I think if you create a new rotation manager (via the add model button), there will be no arcs (or nodes) to start with.

**Comment by femiguez** [comment]
Sorry, I should have been more clear. These are the steps to reproduce the issue I see. Open the 'Rotation.apsimx' example (APSIM2021.10.11.6842). Then click on 'RotationManager' (under Mar -> Mar -> field). I see the nodes (Maize, Wheat, initial, WinterFallow) but not the arcs. If I try to add an arc, nothing happens (I think the arcs is added, but not visible). It seems to run fine, so it must be a GUI issue.
