### ISSUE TITLE
Graph for leaf.fw doing odd things

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#6834]
The y-axis is going a bit crazy @hol353 
[201_2021.zip](https://github.com/APSIMInitiative/ApsimX/files/7289403/201_2021.zip)
is

**Comment by hol430** [comment]
This is happening because Wheat.Leaf.FW is actually varying very slightly - the unique Y values shown in this graph are (1 - 1e-16), (1 - 2e-16), and (1 - 3e-16). The precision in the DataStore UI is not sufficient to see the difference, but I think the graph is actually correct here.
