### ISSUE TITLE
Mass balance error in SWIM3

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6848]
There is a mass balance error (even with the gradient lower BC) in SWIM3. It is not apparent in SWIM3 Classic (the Fortran version). It is our understanding that SWIM3 NG was ported from SWIM3 C# that probably did not not get as much user testing as the Fortran version in Classic. Or perhaps it might be related to the changes made to get the number of nodes equal to the number of layers?

**Comment by jbrider** [comment]
@sno036 were you able to debug the Classic version? We've been having some issues with this. Did you have to install an older Visual Studio?

**Comment by hol353** [comment]
I'm not able to debug classic. I remember about 4 years I did get debugging working in Fortran using Eclipse. I have some notes somewhere about this if you're interested. For c#, once you have everything compiled you should be able to debug just using VS.
