### ISSUE TITLE
Runoff, erosion and SWIM 3

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6854]
Not addressable until the approach to ponding #6841 is addressed.

NOT WORKING: No solutes in runoff water. There aren't any solutes in rainfall anyway.
UNCLEAR "Once we implement solutes in irrigation this should be fixed." Automatically or on a pathway to being implementable
NOT WORKING: Erosion.

What options are active
Do they align with Verburg, or how not
Do they do what is expected?
And is there a test for this?
Does the mass balance with these options?
Is it included in the documentation memo?

**Comment by hol353** [comment]
I've documented this in a memo in the Swim3 apsimx file.
