### ISSUE TITLE
Separator lines in the new GUI possible?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6861]
Can we get separator lines working in the new GUI?

Some blank space to the left of the text would be aesthetically pleasing. Right justification would be more functional but probably ugly.

New version
![image](https://user-images.githubusercontent.com/12176269/137402022-7e1c3cd7-a22d-457a-9deb-6812a11d9d3d.png)

Old version (they do not need to be as dark as this!)
![image](https://user-images.githubusercontent.com/12176269/137402197-9e76d70a-a10e-44ef-b50b-a0372304da36.png)

**Comment by lie112** [comment]
There is a UserInterface.Presenters.PropertyCategorisedPresenter and associated UserInterface.Presenters.PropertyCategorisedView created for CLEM that provides a tree view of property categories for large property sets with two levels of categorisation if needed. We might have to tweak the icons to ensure more generic options are available.

![image](https://user-images.githubusercontent.com/19215637/137406457-7ffe5d2d-fe2d-4f84-8c41-6c36c5b4cf5c.png)
