### ISSUE TITLE
A way to turn graph series on/off in the new GUI would be exceedingly helpful

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6864]

**Comment by hol430** [comment]
Should already be able to do this - if you double click on the legend, a small panel witll popup with some options, one of which gives you a checkbox next to each series name, allowing them to be enabled/disabled individually.

**Comment by sno036** [comment]
It was not producing a legend for me. Has this been fixed?

**Comment by hol430** [comment]
If you have the 'show in legend' option disabled on all of your series, you won't have a legend. Otherwise, you *should* have a legend.

**Comment by hol430** [comment]
I'm going to tentatively close this. If you have a graph with no legend showing up (when you think you should have a legend), I'd be happy to take a look at that.
