### ISSUE TITLE
What’s the datatype  when Apsim-client receives  'Clock.Today' field from Apsim-server 

### ISSUE THREAD

**Issue by xiangyi-wang** [APSIMInitiative/ApsimX#6867]
when i use c_int32 
`544106784, 1096563269, 1835627376, 1346460760, 776816979, 1987208531, 1096577637, 1835627376, `

when i  use c_char
` b't', b'i', b'o', b'n', b' ', b'e', b'r', b'r', b'o', b'r', b')', b' ', b'i', b'n', b' ', b'E', b':`

**Comment by hol430** [comment]
I haven't yet implemetned a  protocol for sending/receiving dates here - your best bet for now might be to report `Clock.Today.DayOfYear` and use that (it's an int).
