### ISSUE TITLE
Enable url link to a specific version

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#6870]
To make it easier to provide a specific link to a 'training' version, enable the current download link to be able to specific  a specific version.
People can then publish a url to a specific version for download.
eg: https://apsimdev.apsim.info/APSIM.Registration.Portal/Register.aspx?2021.10.11.6842

- Also allow the user to search for a specific version by entering the release number (version).
- Also enable the Upgrade functionality to work with a specified release as well by providing a search field.

Q: My compiled version doesn't show the current release number (version) - does the released version show it somewhere?

Note: Release Number (version) is sequential for subsequent days as the primary identifier is the date of release.
If there was more than 1 release during a given day, only then will the numbering be out of order for that day.

**Comment by hol430** [comment]
> Q: My compiled version doesn't show the current release number (version) - does the released version show it somewhere?

Should be displayed in the title bar of the GUI. Or you can check from command line by running `Models.exe --version`.

**Comment by hol430** [comment]
yep

**Comment by hol430** [comment]
Closing this after discussion with @hol353. Link to a specific version is already possible, e.g.

https://registration.apsim.info/?product=APSIM%20Next%20Generation&version=2022.02.7020

Or a specific platform:

https://registration.apsim.info/?product=APSIM%20Next%20Generation&version=2022.02.7020&platform=Linux
