### ISSUE TITLE
Move API documentation to dev.apsim.info server

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6875]
API documentation currently lives on apsimdev.apsim.info. Need to move this to the new (apache) server.

**Comment by hol353** [comment]
Which API documentation are you referring to and where is it on apsimdev (if you can still remember)?

**Comment by hol430** [comment]
https://apsimdev.apsim.info/apsimx-docs/

(link to api documentation at top of page)

**Comment by hol353** [comment]
I can't see where this api documentation is updated in our build system. Does anyone think this type of documentation is useful?

**Comment by hol430** [comment]
I think there were problems at some point with IMT wanting to close certain ports on some servers which were owned/maintained by csiro, which was makindg it difficult to upload the documentation efficiently. I wouldn't be surprised if this API documentation was dropped from the build system at some point as a result of that, but I don't really remember the details.

I think the idea was to make things a bit easier for people who were writing manager scripts (or attempting to) without using a debugger/IDE, which was(/is) a challenging prospect. Without API docs, you've got to rely on the intellisense in the manager script editor, which can be iffy. Whether this documentation actually helps with that is up for debate. If it's not going to be updated regularly then it's pretty useless.
