### ISSUE TITLE
More mathematics options in Report possible?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6882]
Would it be possible to enable more mathematical functions in Report. Something like:

Log10(-1 * [Soil].Swim3.psi[1]) * -1

Perhaps also operating on arrays such as 

Log10(-1 * [Soil].Swim3.psi * -1   // this would apply the function element by element and produce a value for each layer

**Comment by hol430** [comment]
@sno036 I can do this if you want. Do you have a list of functions you want added?

**Comment by sno036** [comment]
Perhaps:
- exp()
- power()
- abs()
- ceiling()
- floor()
- log()
- log10()
- round()

@rcichota  - any additions?

**Comment by rcichota** [comment]
Thanks @sno036 , that should cover our bases pretty well. Except for trigonometry, but I don't think we need those...
I wonder if log() and log10() are needed explicitly of we could use log(x, b), where b is the base of the log, if left blank (or even better if we could use "e" for base) it becomes the natural log. In many science areas ln() is used, although most computer languages use log() for natural log (excel has the three versions), so there is no 'standard/official' version. In my opinion, making the base explicit reduces confusion, but I am not starting any fights over it :)

**Comment by sno036** [comment]
I was basing these off the C# standards but would be happier with ln() and log10() as they are explicit enough that I don't have to wonder what system is being followed. I agree that I don't think we are likely to need the trig functions.

Good to go @hol430?

**Comment by sno036** [comment]
.... but while you are here ...

One SWIM thing that we already know we need to test is layering. And one of the things that I have always wanted (used to have in con-par days) was the ability to have output give me a value at a specified depth in the soil (rather than pointing to a particular array index). e.g. "drainage(600mm)". @hol353 and I have a session next week and might think more about that then.

**Comment by hol430** [comment]
Ok, so most of these are already in there. I think the only missing one is ceil which I'll add in now.

Regarding the log functions, what we have already is `log(x)` which is a base-10 log, `ln(x)` the natural log and `logn(x, b)` where b is the base of your choice. I agree that `log(x)` is a bit ambiguous, but removing it would be a breaking change to some .apsimx files, which makes me a bit nervous (not that it's stopped us in the past :).

We've also got trig functions already in there. In fact here's the full list of what's already in there:

Scalar functions:

- `cos()`
- `sin()`
- `tan()`
- `cosh()`
- `sinh()`
- `tanh()`
- `log()`
- `ln()`
- `logn()`
- `sqrt()`
- `abs()`
- `acos()`
- `asin()`
- `atan()`
- `floor()`
- `exp()` (also works with array operand)

Array functions:

- `mean()`
- `sum()`
- `subtract()`
- `multiply()`
- `divide()`
- `min()`
- `max()`
- `stddev()`
- `median()`
- `percentile5()`
- `percentile10()`
- `percentile15()`
- `percentile20()`
- `percentile25()`
- `percentile30()`
- `percentile35()`
- `percentile40()`
- `percentile45()`
- `percentile50()`
- `percentile55()`
- `percentile60()`
- `percentile65()`
- `percentile70()`
- `percentile75()`
- `percentile80()`
- `percentile85()`
- `percentile90()`
- `percentile95()`

**Comment by rcichota** [comment]
Wow!! That will satisfy the most picky of the customers...
Thanks Drew

**Comment by sno036** [comment]
In Report? I did try a few possible options for log before I put in the issue (and @hol353 was looking over my virtual shoulder!). If they are in there they need documenting!

**Comment by hol430** [comment]
Hmm, maybe you were trying to use the log function on an array? I think that probably wouldn't work currently - perhaps it should (in an element-wise fashion). Agreed about documentation - maybe a "functions" section in the report tutorial would be useful.

> Is it possible to see how many log(x) usages are in the system already?

None of the .apsimx files in the repo use `log(x)` in report, but other people's files may do so. Writing a converter function for this would be difficult.

**Comment by sno036** [comment]
Yes - it was on an array and that is important (to me!) functionality. How difficult would it be to enable it? See the first message on this issue - both usages would be helpful.

For the second question I think the sooner it is changed the better. Given that it is not documented, there may be no one using those functions yet. And if there are then a message to users could cover it.

**Comment by hol430** [comment]
Re-opening until I add array support to all of the existing functions.
