### ISSUE TITLE
Can't download ApsimX

### ISSUE THREAD

**Issue by pjinnes** [APSIMInitiative/ApsimX#6890]
I can't get get the apsim next generation download link to work when I click on the Windows option.
https://apsimdev.apsim.info/APSIM.Registration.Portal/Downloads.aspx

Apsim classic download works OK

**Comment by granawkins** [comment]
I had the same issue on Mac with Brave browser. After reading this, I tried with Safari and it worked fine. 👍

**Comment by hol430** [comment]
This should be fixed now. Feel free to reopen or comment further if you're still having problems.
