### ISSUE TITLE
Mapping is broken

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#6891]
Adding a map to the example Wheat simulation (and probably to anything else) gives garbage results.

**Comment by hol430** [comment]
@zur003 - when I add a map to the wheat example, I get this:

![image](https://user-images.githubusercontent.com/36427516/139777524-0ae60022-2603-436b-8178-38a143cf8db1.png)

Which can then be panned/zoomed as desired. Are you seeing something different?

**Comment by zur003** [comment]
I see something quite different:

<img width="529" alt="Capture" src="https://user-images.githubusercontent.com/11879340/139825861-a904f392-0aa0-4cba-9108-8855bde9fc29.PNG">

**Comment by zur003** [comment]
And with a bit of panning and zooming, I can get this, which doesn't exactly point to Dalby.

<img width="551" alt="Capture2" src="https://user-images.githubusercontent.com/11879340/139826530-6d4c8b0a-9847-42dc-a94d-9f64b6ba7685.PNG">
:

**Comment by zur003** [comment]
@hol430 - Interesting - it works almost correctly when run on Ubuntu, but is broken on Windows. On Ubuntu, display is mostly working as expected, although a saved map center is not being restored.
