### ISSUE TITLE
CroptimizerR doesn't work and error has no solution

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#6916]
CroptimizerR doesn't work base on R errors. there is no solution for This issue.is there anyone working on it?

**Comment by femiguez** [comment]
I would recommend providing more detail and context. It is not possible to reproduce your problem or understand the exact nature of the issue you are dealing with. We do not know: OS, APSIM Next Gen version or the file you are trying to run.

**Comment by masooandy** [comment]
Hi femiguez. The problem belongs to CroptimizerR latest update of apsimx.windows 10 os. You can check #6818 
I guess this should be a bug.even I run the example of croptimizer in prototype folder.error appears.

**Comment by femiguez** [comment]
There is an alternative to CroptimizerR (https://femiguez.github.io/apsimx-docs/optim-apsim.html) but it requires a certain level of proficiency with R. Your ggplot2 error is not related to APSIM Next Gen however.

**Comment by masooandy** [comment]
> There is an alternative to CroptimizerR (https://femiguez.github.io/apsimx-docs/optim-apsim.html) but it requires a certain level of proficiency with R. Your ggplot2 error is not related to APSIM 
By this conditions no one can use CroptimizerR and it is useless.

**Comment by femiguez** [comment]
APSIM and related tools are available to the scientific community in the hope that they are useful. The effort of the people involved are constrained by time and available resources. Some of these tools require a higher level of expertise and many of us use free open-source software while recognizing that there might a considerable amount of effort in adapting them to our needs. Good luck with your project!

**Comment by masooandy** [comment]
Thanks for your time.
