### ISSUE TITLE
Bad color for text highlight with Dark Theme

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#6925]
The text highlight is almost the same color as the text in dark theme which makes reading the text difficult.  Could the highlight be changed to a darker color.
![image](https://user-images.githubusercontent.com/7295858/140662802-4d1cbba6-3953-4a39-9655-ffe17ae41ef4.png)

**Comment by hol353** [comment]
Yes this annoys me as well. You can right click and choose a different style but the GUI seems to forget about your style selection when you shut it down.

**Comment by HamishBrownPFR** [comment]
The blue highlight in the tree view works well.

**Comment by hol430** [comment]
You need to right click and choose a different style. The default doesn't work well in the dark mode. The gui will remember your selection for next time, but it only saves your settings to the config file when you close the GUI. So if you abort a debug session, any changes to your preferences won't be saved.

It might be worth automatically changing the selected editor theme when the user toggles between light/dark mode.

**Comment by HamishBrownPFR** [comment]
It would be good to have a sensible default so this doesn't keep coming up

**Comment by HamishBrownPFR** [comment]
The text color for the SoilCrop grid is also hard to distinguish.  Should be white like other grids
