### ISSUE TITLE
Edit file doesn't edit some bits (or I can't find the proper bit!)

### ISSUE THREAD

**Issue by JRichetti** [APSIMInitiative/ApsimX#6929]
Hi folks,

I'm using command line to edit the APSIMx file (as described [here](https://apsimnextgeneration.netlify.app/usage/editfile/)) but looks like some parts it doesn't like it. I was able to edit some soil properties like (LL and DUL). But the copy path to node is not clear of the names of the variables. For example, if I want to modify, for example, the fertilisation amount applied at a given data the path:

.Simulations.Simulation.Field.Fertilise_1.Amount = 40 

doesn't work. Also, for other bits it is not clear what the full path is.

Cheers,

**Comment by hol430** [comment]
Yep, there's no general way to work out the paths you need without looking at the code, although using the intellisense in the gui can be a good way to figure them out. In general, if you can report it, you should be able to change it from the CLI.

In the case of fertiliser amount - fertiliser has no property called amount. Instead, the amount is provided during calls to Fertiliser.Apply(). So if you're fertilising via a manager script, you would need to edit the amount property of the manager script from the CLI, and this would then be passed into the fertiliser module when the fertiliser is applied.

If you're fertilising via an operations node, you're probably out of luck. It's going to be very difficult to edit your operations from the command line.

**Comment by JRichetti** [comment]
Okay, thanks!
