### ISSUE TITLE
How to find the outputs?

### ISSUE THREAD

**Issue by JRichetti** [APSIMInitiative/ApsimX#6930]
Hello,

Is there a list where we can find outputs?
For example, if I want to see the Total Water Stress of a crop, what is the path?
I looked for [Plant].Total. _?_ but could not find any water stress related variables. Similarly, for many other variables it is really hard to find what the correct path is. Is there any solutions for this?

APSIM Classic had a search box that made quite easy to find the outputs I needed.

Cheers,
Jonathan

**Comment by hol430** [comment]
Yep, it's a real problem. The intellisense is currently your best bet (your only bet actually).

As far as I know, none of the crops have a concept of a total water stress - I'm not sure how it would work if they did. Some organs (ie leaf) have a water stress effect defined but as the crops are all implemented slightly differently (very differently in some cases), this won't be consistent across all crops.

**Comment by JRichetti** [comment]
Thanks for this. So, a search function that go through description and naming of output variables would be very handy!
