### ISSUE TITLE
Can we have a 'close simulation' button on the GUI please?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6934]
(PS - I refuse to label this as a new feature! 😜)

**Comment by hol430** [comment]
Maybe a stupid question, but what would this button do? We already have a button to close the file.

**Comment by sno036** [comment]
Can you point me to where it is?

![image](https://user-images.githubusercontent.com/12176269/140856425-f3c97276-c6f7-4f52-bc3c-65c593117271.png)

**Comment by hol430** [comment]
Well it is there, but you would need damn good eyesight to see it :). I'll change it to the same blue as the other icons there.

![test](https://user-images.githubusercontent.com/36427516/140857216-e304af1e-6278-4639-9b66-08fb1fd7291d.png)
