### ISSUE TITLE
Manager model is remembering old parameters

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6937]
- A manager model has a public property defined with a Description attribute
- Save the .apsimx file (file is serialised)
- Remove the Description attribute from the property (don't delete the property)
- Save the .apsimx file.

The .apsimx file will still have a manager 'parameter' for the property that no longer has a description attribute.

**Comment by peter-devoil** [comment]
I remember @hol430 fixing a similar bug where the compiled assembly was being incorrectly cached.

**Comment by hol430** [comment]
Unable to reproduce this one. Is this what you're doing?

![manager-repro](https://user-images.githubusercontent.com/36427516/142960486-81aaf04d-4d3f-4df8-8f78-a206d3751bd9.gif)

**Comment by hol353** [comment]
Yes I think so, but in my case it wasn't changing the .apsimx file when I saved. I'll have another go and see if I can reproduce it.

**Comment by par456** [comment]
Tried to reproduce again on the latest build, property was updated correctly. Will close.
