### ISSUE TITLE
Excessive scrolling in manager script

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#6938]
If you scroll with the mouse wheel and then hit enter, the script window scrolls unnecessarily.

**Comment by hol430** [comment]
I'm unable to reproduce this one, but I do remember you showing me this the other day. Do you remember which version of apsim you were using at the time? I definitely remember fixing this a while ago (months ago), is it possible you were using an old version when you ran into this bug?

**Comment by hol353** [comment]
Yes it could have been an old version. I can't reproduce it either - closing.
