### ISSUE TITLE
New icons in APSIM ng

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6945]
Congratulations on another GUI appearance upgrade with the new icons. 

What are the new icon standards in APSIM NG (#6855) ? I will start upgrading the CLEM suite of icons.

I realise icons can now be svg providing better scaling and display, but what is the target size of the various icon when displayed (recent list and tree view)? Once all icons are updated the treeview may need a larger gap between the new larger icons and the node label.

How does APSIM decide what icon to provide previously loaded simulations in the home tab. Some of my files seem to have been assigned icons (simulation icon and up arrow) based on the name of the icon found in the filename i.e.  "simulation" and "upgrade". This seems like a flimsy means of defining a recent file icon.

![image](https://user-images.githubusercontent.com/19215637/141252988-27bff733-3be2-41a5-91b1-cf9d93c393b1.png)

**Comment by hol430** [comment]
There are no real standards. It would be nice to have svgs for all of our icons but that's not going to happen anytime soon.

> what is the target size of the various icon when displayed (recent list and tree view)?

I don't think we specify a size, the assumption is that the icons' default size is appropriate. I think the tree view icons are 20x20 and the icons on the home screen are 32x32. In the screenshot above BaseGeneticsSimulation.apsimx is using the simulation treeview icon, and it's noticably smaller than the others.

> How does APSIM decide what icon to provide previously loaded simulations in the home tab

ListBoxView.cs, inside AddFileNameListItem(). It searches through all of the images stored as embedded resources in the ApsimNG assembly, and finds one with a file name which is part of the .apsimx file's name. The idea is that if you have a file called "wheat simulation.apsimx", it will use the wheat icon. This could certainly be improved - perhaps we should only check the icons for the resource models. Would also be nice to have a better fallback icon than the apsim logo.

**Comment by lie112** [comment]
Thanks, thought i'd ask rather than spend ages looking through the code.

I had copied some old apsim treeview icons when I started building clem icons and so all clem icons are 16x16, so moving to 20x20 gives better resolution.

The move to svg also means there's no size restriction and the simulation icon example in previously loaded could have scaled easily to 32x32 being an svg. As mentioned I think we can do with a bit more vertical and icon-label padding with the 20x20 treeview icons (simulations-datastore-simulation are now packed tightly at 20x20).  This will allow text zoom in future which would be nice for sharing and presenting apsim online.

I think the means of assigning an icon for previously opened does need a new method or only apply to resources as while it would let me apply this approach, it does not let me avoid it in the example above. It seems this only started to happen with the new icons, but I do recall some wheat icons appearing in the past.

The new simulations or simulation icon could be a suitable default icon for all previous simulation files. I never liked the apsim logo there.

**Comment by lie112** [comment]
I need to export my svg icons at different sizes for treeview, web and other uses. It is a super pain to handle this in illustrator where I develop the artwork. I could look for tools to alter the svg attributes but easier to handle it at rendering. Can we hardcode or provide a global icon size so that svgs are scaled to 20x20 in the code? This would allow scaling of fonts and icons in future when everything goes svg. It actually works with bitmaps but looks terrible as expected. I'm not sure if this can be handled by css.

This is easy to achieve by scaling the Pixbuf in TreeView.RefreshNode as shown here.

`        private void RefreshNode(TreeIter node, TreeViewNode description, bool checkForExisting = true)
        {
            Gdk.Pixbuf pixbuf = null;
            if (MasterView != null && MasterView.HasResource(description.ResourceNameForImage))
            {
                pixbuf = new Gdk.Pixbuf(null, description.ResourceNameForImage);
                if (description.ResourceNameForImage.Contains(".svg"))
                    pixbuf = pixbuf.ScaleSimple(20, 20, Gdk.InterpType.Bilinear);
            }
`

**Comment by hol430** [comment]
Using ScaleSimple() like this will cause the pixbuf to be scaled after it's already been converted to a raster icon, so the result looks blurry. This is especially noticeable on round icons like clock, and even more so if you increase the scale resolution (I tried 128x128 and it was very noticeable). I haven't been able to find a simple way to scale vector images using gtk without calling into librsvg, a library which isn't wrapped by GtkSharp.

I don't have time to look into this further at the moment, so for now it may be best to just put up with the slightly smaller clem icon sizes, or find some way to convert the clem icons to the expected size in bulk.

**Comment by lie112** [comment]
I was unable to get any examples working in Gtk# where the scaled resource was read in as the new instance of pixbuf as that's the only constructor that supports resources as far as I can tell as I couldn't get [new scaled from resource](http://www.crategus.com/books/cl-cffi-gtk/pages/gdk-pixbuf_fun_gdk-pixbuf-new-from-resource-at-scale.html) to work . It seems I could only access the scale methods on the pixbuf once created.
My code only applies to svg icons and so all the current svg icons should already be in at 20x20 so no scale is applied . This would only apply to svg icons not at 20x20 and mine were 56x56 so the shrink looked good. Maybe there are some icons less that 20x20 as svg in which case there would be a scale of a raster up to 20x20 that would not look good. Gtk seems to be behind in svg scaling and use.  I did not see any poor quality icons in windows when I was testing this. Maybe this is a screen resolution rendering issue for you so in not going to work across platforms. I am also unable to save the svgs as 96dpi in Adobe but can't see this as the issue.
There is no rescale of the raster icons and they are rendered at the size they are provided.
I will look into converting my svgs to 20x20 and that will address the problem for now until someone adds a treeview icon not save 20x20.
