### ISSUE TITLE
Where is the CumulativeReport module？

### ISSUE THREAD

**Issue by julianwong82** [APSIMInitiative/ApsimX#6947]
I watched a video about Modelling Soil Carbon (& Nitrogen) Dynamics with APSIM  from YOUTUBE.  A CumulativeReport module was used in this video, But I can't find CumulativeReport module from APSIM. I want to ask where I can find this module？
![apsim](https://user-images.githubusercontent.com/50697583/141406147-4a601c00-538d-4d59-8944-9bb1459f3d01.png)

Best regards

**Comment by hol430** [comment]
That cumulative report is a manager script - it's not a builtin apsim model. Without seeing its source code I don't really know what it does, but if you're interested in writing cumulative output variables, there are some examples of that in the report model documentation which is linked on [this page](https://apsimnextgeneration.netlify.app/modeldocumentation/).

**Comment by hedycau** [comment]
We wrote that manager script to accumulate rainfall, CO2, N2O emission etc. within the growing season in simulations of the video. I'm attaching an example to accumulate the rainfall within the wheat growing season.  You can play with it and generate your own script if you want.
##########
using Models.Core;
using Models.Interfaces;
using Models.PMF;
using APSIM.Shared.Utilities;

namespace Models
{
    [Serializable]
    public class Script : Model
    {
        [Link] IClock Clock;
        [Link] ISummary Summary;
        [Link] IWeather Weather;
        [Link(ByName = true)] private Plant Wheat;
        [Description("Total rainfall from sowing")]
        public double TotalRain { get; set;}

        [EventSubscribe("DoManagement")]
        private void DoDailyCalculations(object sender, EventArgs e)
        {
            if (Wheat.IsAlive) 
            {
            	TotalRain += Weather.Rain;
            } else 
            {
            	TotalRain = 0;
            }

        }
    }
}

**Comment by julianwong82** [comment]
I have another question, my simulation simulated the soil carbon content from 1971 to 2020 , there were 3 residue retention scenarios and 5N application rates, all factorial combination have 15 simulations.
![1](https://user-images.githubusercontent.com/50697583/141673252-e256e7e0-80a0-433e-be32-d9791440410d.jpg)
 I want to plot a graph, every graph included the changes of soil carbon content under the same N application rate and different residue retention scenarios, But my graph included  all simulation results. I want to ask how to plot the graph in APSIMNG.
That is correct graph:
![3](https://user-images.githubusercontent.com/50697583/141673263-983f6159-c61a-4c72-a86d-09967f984eb0.png)
That is my gragh:
![2](https://user-images.githubusercontent.com/50697583/141673241-60b04e7d-95bf-45b5-89ce-a09729c70e52.png)

All the best

**Comment by hol430** [comment]
You probably need to change graph colour to 'vary by simulation name'.

**Comment by hedycau** [comment]
Create a folder, use “filter” to plot each panel. Please see the screenshot. If you are interested in the graphs of APSIM NG, more documentations are available in the Usage of APSIM NG https://apsimnextgeneration.netlify.app/usage/.
Cheers,
Di
***@***.***
