### ISSUE TITLE
Unwanted Forages model appeared

### ISSUE THREAD

**Issue by pre078** [APSIMInitiative/ApsimX#6965]
Since last upgrade a Forages Model has suddenly appeared in my Simulation model of CLEM.
![image](https://user-images.githubusercontent.com/19523746/142783972-932031c9-312a-4f7d-a3ce-4446b583570d.png)

**Comment by hol430** [comment]
I think the forages node is now a requirement of stock and simple grazing. Do you have either of these in your simulation?

**Comment by pre078** [comment]
No, not in this simulation

  *    I am using CLEMs GrazeAll Model

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hol430** [comment]
@hol353 - looks like a forages model will be added if any model in the simulation has a type name containing the words "Stock" or "SimpleGrazing". Is this deliberate? ie is there a reason we don't just check type names on an exact-match basis?

**Comment by hol353** [comment]
No reason. I'm not sure why I did it that way.
