### ISSUE TITLE
Online Seminar Series - Variance decomposition of model outputs using APSIM Next Generation

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ApsimX#6982]
Please use this issue to comment and/or ask questions in relation to the following video:
https://youtu.be/dI_cDTCkFxo 
@JJguri

**Comment by tefera21** [comment]
Many thanks Jonathan for your incredible work.  Can we apply this on outputs generated by classical version (APSIM 7.10, for example)? and how?

**Comment by JJguri** [comment]
Hi @tefera21 thanks! yes of course you can, however you need to update the Jupyter Notebook to read the Classic .out files instead of the .db file. The issue here is that in Classic you will get several .out files based on the experiment you create with the factorial. So you need to iterate through these files and finaly get the general dataframe. [Here](https://github.com/JJguri/APSIMClassicTools/blob/main/ClassicOutputReading-RanjuPaper.ipynb) I implemented a Python code to read .out files and put everything in a single dataframe. You can adapt it accordingly with your data.

**Comment by tefera21** [comment]
> Hi @tefera21 thanks! yes of course you can, however you need to update the Jupyter Notebook to read the Classic .out files instead of the .db file. The issue here is that in Classic you will get several .out files based on the experiment you create with the factorial. So you need to iterate through these files and finally get the general dataframe. [Here](https://github.com/JJguri/APSIMClassicTools/blob/main/ClassicOutputReading-RanjuPaper.ipynb) I implemented a Python code to read .out files and put everything in a single dataframe. You can adapt it accordingly with your data.

Awesome, very useful info. Thanks!

**Comment by ElvisElli** [comment]
Hi Jonathan, congrats on the very nice presentation and I really enjoyed the topic. Do you have any material that could help to reproduce this approach using R?

**Comment by JJguri** [comment]
Hi @ElvisElli, the code is straightforward and well-documented so I think if you have basic/medium skills using R it can be replicated. If you want create an issue in my Var-Decomp repo and add the code there. I can possibly help you to understand the meaning of each piece of code if required. I know some people tried to write a similar code in R. I will post here if I can find something. Good luck!

**Comment by ElvisElli** [comment]
> Hi @ElvisElli, the code is straightforward and well-documented so I think if you have basic/medium skills using R it can be replicated. If you want create an issue in my Var-Decomp repo and add the code there. I can possibly help you to understand the meaning of each piece of code if required. I know some people tried to write a similar code in R. I will post here if I can find something. Good luck!

Thanks Jonathan! I'll try to replicate this in R and will let you know about the progress.

**Comment by JJguri** [comment]
@ElvisElli I got the R codes where created by Dr Heidi Webber (ZALF, Germany). I am sharing the R code and the associated table to create the figures reported in her paper which is as referenced in the Var-Decomp repo. Good luck!
[R_codes.zip](https://github.com/APSIMInitiative/ApsimX/files/7689072/R_codes.zip)

**Comment by ElvisElli** [comment]
> @ElvisElli I got the R codes where created by Dr Heidi Webber (ZALF, Germany). I am sharing the R code and the associated table to create the figures reported in her paper which is as referenced in the Var-Decomp repo. Good luck! [R_codes.zip](https://github.com/APSIMInitiative/ApsimX/files/7689072/R_codes.zip)

Thank you very much Jonathan, this is will be very helpful!
