### ISSUE TITLE
Use docker to wrap calls to R

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#6984]
Some of our upstream R packages are known to be unstable. This problem could be solved by having apsim use a docker container with known-stable versions of R packages to run CroptimizR/Morris/Sobol.

**Comment by peter-devoil** [comment]
It's a bit late to mention this, but the good folks at microsoft invented a "[checkpoint](https://mran.microsoft.com/documents/rro/reproducibility)" package that allows the R user to specify packages at a snapshot in time.

**Comment by hol430** [comment]
We tried using [packrat](https://rstudio.github.io/packrat/) which I think does the same thing. We still had problems - particularly with the version of R which is installed on the user's computer. It appears that what's stable in one version of R is not necessarily stable in another version (particularly around the 4.0.0 version). There were also some problems with packages disapparing from cran, with windows vs linux, etc. Docker solves most of these problems, though granted it does introduce some of its own with regards to file/path management.

**Comment by hol430** [comment]
Closing as fixed.
