### ISSUE TITLE
Call met input in manager script

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#6996]
@hol430 dear Drew, are there functionalities in the Weather module that support the extraction of values of an added column from met file at the current timestep for use in manager script? The normal weather input works with Weather.Rain/Wind etc. but not for other parameters. I've added a ground wind column and am wondering if there's a way to directly call it or do I need to ApsimTextFile the met file and convert that column individually please? 
I think it's a good feature to include if not available yet. Thanks heaps!

**Comment by hol430** [comment]
Not currently possible, but wouldn't be hard to implement. I'll look into it.
