### ISSUE TITLE
Sorghum switch in Root needs refactoring

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#7004]
The sorghum model introduced an optional function *RootFrontCalcSwitch* into the root organ. It is used in 3 locations (2 in root and one in RootZoneState. Because the function is optional, there is code like:

```c#
if (RootFrontCalcSwitch?.Value() >= 1.0)
...
else
...
```
Need to make the function non optional which will get rid of the if statements.

As an aside, I came across a *PlantAvailableWaterSupply* method in Root. It seems to be sorghum specific but isn't used anymore. Please delete it.

**Comment by hol430** [comment]
Pretty sure this was refactored out as part of #6986.

**Comment by hol353** [comment]
Ahh you are correct. I forgot about that PR. I'll move *PlantAvailableWaterSupply* issue to the PR for fixing. Closing...
