### ISSUE TITLE
Changing the harvest date for Maize

### ISSUE THREAD

**Issue by dexy58** [APSIMInitiative/ApsimX#7005]
Is it possible to change the harvest date for Maize? I see sowing rules (start and finish), but sowing is defined as the process of placing the seed in soil to germinate and grow into plant, so that means when we plant the seeds. I want to change the harvest date, but I don't know how to do it.

Also, why is sowing starting at 1-nov? Of course, different places have different best sowing date (as per my research), but I am still curious why 1-nov is a valid sowing date? I have found no sowing dates in research papers that say 1-nov is a valid date for sowing start date.

**Comment by femiguez** [comment]
In the toolbox Management there is a 'Harvesting' option. Look into the script and you might be able to change it to suit your needs. The sowing date of Nov-1 is reasonable for the southern hemisphere, but you can change it to a date that is more reasonable for your location.

**Comment by dexy58** [comment]
> In the toolbox Management there is a 'Harvesting' option. Look into the script and you might be able to change it to suit your needs. The sowing date of Nov-1 is reasonable for the southern hemisphere, but you can change it to a date that is more reasonable for your location.

Ty for the reply :)

I have looked at Harvesting option, but I have failed to find a solution.
I have looked at [#3008](https://github.com/APSIMInitiative/ApsimX/issues/3008) issue, but it doesn't work for me.
Can you please provide an example?
Thank you :)

**Comment by femiguez** [comment]
There is some good advice in the issue that you referenced. Give it a try and let us know what kind of error message you get.

**Comment by dexy58** [comment]
```
using Models.PMF.Phen;
using APSIM.Shared.Utilities;
using System.Xml.Serialization;
using Models;
using Models.PMF;
using Models.Soils;
using System.Text;
using System.Collections.Generic;
using Models.Core;
using System;
using Models.Soils.Nutrients;

namespace Models
{
    [Serializable] 
    public class Script : Model
    {
        [Link(ByName = true)] private Plant Maize;
        [Link] private Zone zone;
        [Link(Type = LinkType.Path, Path = "[Maize].Phenology")]
        [Link] Clock Clock;
        
        private Phenology phenology;
                    
        
        [EventSubscribe("StartOfSimulation")]
        private void OnSimulationCommencing(object sender, EventArgs e)
        {
        }
        
        [Description("Harvesting Date (dd-MMM)")]
		public string HarvestingDate { get; set; }
        
        [EventSubscribe("DoManagement")]
        private void OnDoManagement(object sender, EventArgs e)
        {
            if (phenology.CurrentPhase.Name == "ReadyForHarvesting" || DateUtilities.DatesEqual(HarvestingDate, Clock.Today))
            {
                Maize.Harvest();
                Maize.EndCrop();
            }
        }
        
        [EventSubscribe("DoManagementCalculations")]
        private void OnDoManagementCalculations(object sender, EventArgs e)
        {
            
        }
    }
}
```

This is a code that I created. However, I don't have properties tab and I get this error:
![image](https://user-images.githubusercontent.com/40712374/145597707-336c55ef-94f5-4df3-a205-3af9118dc10b.png)
When I remove [Link] Clock Clock; it says that it's missing this link. I don't know what to do :/

**Comment by dexy58** [comment]
Okay, I found the problem.
[Link] Clock Clock; has to be above [Link(Type = LinkType.Path, Path = "[Maize].Phenology")], not below.
