### ISSUE TITLE
APSIM thinks user is using a custom build and won't upgrade

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7006]
A CLEM user can no longer upgrade as the software thinks he is using the developer version.
He has installed APSIM Next Generation and never had a problem until this issue

![Screenshot 2021-12-13 11 17 01 (002)](https://user-images.githubusercontent.com/19215637/145763783-29593f15-2e04-46af-aa14-13cfa3340494.png)

**Comment by femiguez** [comment]
I just noted that the 'ApsimVersion' node has disappeared from the .apsimx file (See image below). The file is from the Barley example. Could this be related?
<img width="746" alt="APSIM_Version_issue" src="https://user-images.githubusercontent.com/10869358/145879429-2d873a70-b8ea-4ec7-aa38-cfc013b22195.png">
