### ISSUE TITLE
Sorghum issues for release

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#7016]
I didn't have my notes with me and forgot to raise two minor issues at the recent meeting for #572 

The sorghum examples use SoilNitrogen in the soil model.  These, and the validation files, should all use Nutrient.

The output variable names in the observed data should be the standard apsim names otherwise readers of Autodoc will see only the alias names.  It is best that people know what the output really is (e.g. sorghum.leaf.live.wt)

**Comment by jbrider** [comment]
@hut104 I'm getting differences in the results after replacing SoilNitrogen with Nutrient. Is that expected?

I would prefer that the observed data uses the alias... and it looks to be common through the existing autodocs as well.
The full name is in the report if people want to find where it comes from.
