### ISSUE TITLE
Can't launch upgrade of APSIMx

### ISSUE THREAD

**Issue by MikeDoddNZ** [APSIMInitiative/ApsimX#7022]
After download, error message is "Cannot find user interface C;\ProgramFiles\APSIM2021.12.16.7017\Bih\ApsimNG.exe" it seems to be pointing to a non existant folder. The folder that was downloaded was APSIM2021.12.6988.0. The ApsimNG.exe in this folder will not launch.

**Comment by hol430** [comment]
The "cannot find user interface" error is going to continue to happen when upgrading from a fairly old version (>6 months or so ago). The workaround is that you'll need to manually launch apsim after doing an upgrade in this case.

Re ApsimNG.exe not launching - does anything happen at all when you try to launch it? Also when you upgraded, you should have been prompted to install a gtk runtime - did you choose yes here?

**Comment by MikeDoddNZ** [comment]
Nothing but a blue swirl for a couple of seconds. There was no gtk runtime prompt on install.
I can't seem to open old simulations either.

**Comment by hol430** [comment]
Interesting. Does the directory `%localappdata%\Gtk` (ie `C:\Users\<username>\AppData\Local\Gtk`) exist on your compute? If so, could you delete it or rename it, then uninstall the `2021.12.6988.0` version of apsim, then rerun the installer?

**Comment by MikeDoddNZ** [comment]
There is a folder called gtk-2.0 with a single file "gtkfilechooser.ini" dated 12/11/2021. So I can delete this folder without impacting any other apps?

**Comment by hol430** [comment]
Yes. If there's only one file, then any other apps which rely on the gtk runtime will not be functioning correctly anyway. Of course if you wanted to be cautious, you could always just rename the Gtk directory to something else instead of deleting it.

**Comment by MikeDoddNZ** [comment]
Renamed gtk-2.0 folder and downloaded latest version 6900.
Same result. No gtk runtime prompt on install. Checked launch box on install but it did not. Nor will it launch from the destop shortcut or the exe file in Progamme Files/APSIM2021.12.6990.0/bin folder.

**Comment by hol430** [comment]
Sorry if I wasn't clear - you don't need to rename the gtk-2.0 folder, you want to rename `C:\Users\<username>\AppData\Local\Gtk` - which I think is probably a few levels up from gtk-2.0.

**Comment by MikeDoddNZ** [comment]
Seems I may be missing a critcal component? Definitely no Gtk anywhere in there.

**Comment by MikeDoddNZ** [comment]
Have tried again this year (recalling that I have a seperate user account for APSIM install with permissions to enable me to upgrade regularly). In this user account I did find the Gtk folder in the location you specified. So I renamed it, uninstalled APSIM, reinstalled APSIM, and this time there was a runtime prompt to install Gtk. That installed OK. However, I got the same result at the end of re-installing APSIM. No launch, either after the install, or using the new desktop icon, or using the icon in the bin folder.

**Comment by hol430** [comment]
If installing apsim as a different user is the problem, then there are probably 2 workarounds:

- Copy gtk directory into equivalent location in the user account which you're using to run apsim. ie copy from `C:\Users\<installuser>\AppData\Local\Gtk` to `C:\Users\<normaluser>\AppData\Local\Gtk`
- Install gtk as your "normal" user (note that this doesn't require admin privileges as long as you don't right click and run the installer as admin)

**Comment by MikeDoddNZ** [comment]
Boom. Option 1 successful thanks.
