### ISSUE TITLE
How to add new cultivar in APSIM Next Gen installed on desktop? 

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7038]
I am new to APSIM Next Gen, and I am currently trying to get my head around it with the knowledge of the conventional version. 

I am currently stuck with adding a new cultivar for maize. Can I please get a direction on how to manually do that on my desktop? 

I was able to clone APSIMX from Github onto my machine, and I have added a new cultivar in the Maize.json file under the Models -> Resources folder, but the cultivar does not show up as an option when setting up the simulation and even after restarting my machine. 

Your help will appreciated. 

With thanks,

**Comment by hol430** [comment]
Hi @andynen - you'll need to recompile apsim after making changes to Maize.json in order for them to show up in your simulations. You'll also want to make sure you're running the compiled apsim, rather than any official/release versions you may have installed. If you've done both of those, can you upload your edited Maize.json, and I'll take a look at it.

**Comment by andynen** [comment]
Hi @hol430, 

Thank you for your swift reply. 

Please are there instructions on how to recompile APSIM from the GitHub folder? How can I do that? 

How can I know I am running the compiled version and not the official release one? 

Sounds good I will upload the edited version. 

Thanks!

**Comment by hol430** [comment]
Hi @andynen - if you've never compiled apsim, you'll be running the released version. In that case, there is an easier way to do this:

1. Open your .apsimx file in apsim
2. Right click on simulations -> add model -> add a replacements node (in the core folder)
3. Copy the contents of your modified Maize.json file, and paste it on the new replacements node

At this point, you should see your new cultivar in the maize model under the replacements node. This version of maize will be used to replace the maize model in all of your simulations in this file.

**Comment by andynen** [comment]
Hi @hol430, thank you for your reply. 

When I right click on **Simulations**, which folder specifically should I add as there is no folder named "replacement node". 

I also tried adding a cultivar node under the maize node, but I could not copy and paste the content of the Maize.json file. 

My apologies for my probably obvious questions. 

![APSIM](https://user-images.githubusercontent.com/68366659/148706028-6ccecccf-bffb-4d7d-9925-42d8598da76c.PNG)

**Comment by andynen** [comment]
@hol430 thank you so much. I can now see my cultivars among the cultivar options. 

I have added Obatampa and Sotubaka in the attached .txt file below. json file format seems not to be supported by GitHub.  

For a clarification on transiting from the cultivar format of APSIM 7.9 to APSIM Next Gen : 

-  For parameter Juvenile.Target.FixedValue -> is it okay to sum the two parameters  tt_emerg_to_endjuv + est_days_endjuv_to_init? this I guess will complete the number of days expected to achieve the juvenile period. 
- just for clarification, is "g" or "mg" the unit of parameter "MaximumPotentialGrainSize"? 
- Any reason for removing parameter grain_gth_rate in APSIM N G cultivar parameter? 

[Maize_json.txt](https://github.com/APSIMInitiative/ApsimX/files/7836307/Maize_json.txt)


Thank you, 
Andree

**Comment by hol430** [comment]
@hut104 are you able to answer any of these?

> For a clarification on transiting from the cultivar format of APSIM 7.9 to APSIM Next Gen :
>
> - For parameter Juvenile.Target.FixedValue -> is it okay to sum the two parameters tt_emerg_to_endjuv + est_days_endjuv_to_init? this I guess will complete the number of days expected to achieve the juvenile period.
> - just for clarification, is "g" or "mg" the unit of parameter "MaximumPotentialGrainSize"?
> - Any reason for removing parameter grain_gth_rate in APSIM N G cultivar parameter?
