### ISSUE TITLE
Soil toolbox in APSIM Next Gen and Multiple Simulations

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7040]
Hi there, 

I have a soil toolbox I had created when using APSIM 7.9. Can it e used in APSIM NG? if yes how can I upload it in APSIM NG? 

I am planning to run thousands of simulations using APSIM NG, can you please direct me on how I can do that without creating them manually in the APSIM UI? 

Thank you

**Comment by hol430** [comment]
You could probably import your soil toolbox into next gen - there is an import button on the homescreen which will prompt you for your .apsim file, and it will attempt to convert it to .apsimx format.

You can also download soils through the nextgen GUI from various data sources - you can do this by right clicking on a zone -> download soil.

**Comment by andynen** [comment]
I uploaded my toolbox and it worked awesome!!! 

I will try for the download through other sources and revert. 

Thank you!

**Comment by andynen** [comment]
I have found where to add soils from other sources. 

Using APSIM Next Gen is a daily discovery since last week. Amazing!!

Thanks, 
Andy
