### ISSUE TITLE
Maize model is insensitive to nitrogen 

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7048]
Hi, 

I am currently testing the sensitivity of the maize model in APSIM NG to fertilizer. I tested three different one time application N=0, 100, & 300 kg/ha. Surprisingly, it has no effect on the yield variability. 
However, the N uptake output increases as the fertilizer increase - but this is not reflected on the yield. 

I increased the initial N as well as the chemical N but no change could be captured on the yield output. 

Is this a bug in APSIM NG or is there something I am not doing right? 

Thank you!!

Below are the two images of the unchanging yield and increasing N uptake per fertilizer treatments respectively. 

![image](https://user-images.githubusercontent.com/68366659/149057139-ac8e6002-f908-451f-8c01-6fd2c570b6ee.png)

![image](https://user-images.githubusercontent.com/68366659/149057218-1947ebc2-8b02-484a-aec1-fe62a3bf2cdd.png)

Also find attached a copy of my simulation file: 
[APSIM_Test.zip](https://github.com/APSIMInitiative/ApsimX/files/7851370/APSIM_Test.zip)

**Comment by hol430** [comment]
Well, I'm no soil scientist, but the initial N values look quite high. These can be set in either the chemical node or a sample node in the soil, but the values in the chemical node will overwrite those in the sample (see: #6505). For some reason, the chemical node expects values in ppm, but the sample (aka initial N in your file) expects values in kg/ha. Either way - in the attached file it looks like the values were copied from the initial N node into the chemical node without accounting for the different units. As a result the plant isn't N-stressed so we get the same/similar outputs in all 3 would see different numbers):

![image](https://user-images.githubusercontent.com/36427516/149063599-e0629d18-beca-4185-8f3f-90fffff2bd6a.png)

**Comment by andynen** [comment]
@hol430 Thank you so much for your return. It is surprising that you get a response for adding N and I don't. 

I added the high values to evaluate the model's response to higher initial N increase. I expected the yield to increase but that was not the case. 

I have now changed the N init to realistic values and tested runs - but still - the model response to N application is quasi-null. It is surprising, because I used the exact soil data, and management in APSIM 7.9, and not only are the yield larger, there is a clear difference between no fertiliser and fertiliser treatment. 

It is also surprising to see that the model is insensitive to fertiliser application for both APSIM 7.9 and APSIM NG. Probably there is no N stress? 

The soil parameters: runoff, cona, etc... are not included in the soil module. The soil module I imported from APSIM 7.9 has them as children but they are empty. Can this also explain the difference? 

I suspect there is something that keeps the maize yield very low. 


Thank you, 
Andree

![image](https://user-images.githubusercontent.com/68366659/149246551-4005c73b-9970-451c-9119-d638313ac512.png)

APSIM 7.9: 
![image](https://user-images.githubusercontent.com/68366659/149246592-16393a27-a2f1-475e-9da1-0c22ce98839c.png)

My simulation file APSIM NG: 
[APSIM_Test_vo2.zip](https://github.com/APSIMInitiative/ApsimX/files/7859178/APSIM_Test_vo2.zip)

APSIM 7.9 simulation 
[APSIM_7_9_test.zip](https://github.com/APSIMInitiative/ApsimX/files/7859374/APSIM_7_9_test.zip)

**Comment by hol430** [comment]
The only difference between my runs and yours is the .met file. I would suggest that your crop is perhaps not N-limited (maybe due to less rain in your met file, in which case you might try adding some irrigation).

The soil parameters you mention are accessible in the soil water node (under soil). They're in the top section - you may need to scroll down a bit.

As for why you get a bigger response in old apsim - no idea. It has a completely different maize model so you can expect different results, but I don't really know anything about old apsim or maize so I can't really speculate further. Perhaps someone else could chime in here.

**Comment by andynen** [comment]
@hol430 Thank you for your help last week. 

After many trials on different parameters I have realized that it is the SOC content which was making the model insensitive to nitrogen. 

The SOC was very high 1.9% ~ 19 g/kg in the top soil which is quite high for the environment where my cultivars were calibrated, thus making the model insensitive to nitrogen. This is in fact expected as higher SOC reflect a fertile soil (with higher activities by the soil microorganism), so adding Nitrogen would barely add value to the growth of the plant. 

Thank you, 

![image](https://user-images.githubusercontent.com/68366659/150062649-6887d04c-13cd-497f-a6b7-e813df30788d.png)

**Comment by andynen** [comment]
Just one additional question @hol430: are there ways to express the output in kg/ha rather than in g/m2? 

I should admit that it confused me at first. 

Thank you!

**Comment by hol430** [comment]
There's no feature for automatic unit conversion as far as I know, but the report module does support basic arithmetic, so you can always do the conversion manually. E.g. you could report `[Maize].Grain.Wt / 10`.
