### ISSUE TITLE
 APSIM Server how to change cultivar parameters

### ISSUE THREAD

**Issue by xiangyi-wang** [APSIMInitiative/ApsimX#7054]
I recently wrote a [Python client ](https://github.com/xiangyi-wang/ApsimClient-python/blob/master/run.py)based on the Apsim.Client [C_api](https://github.com/APSIMInitiative/APSIM.Client/blob/master/examples/main.c) example, I change the cultivar parameter with the following statement and the result does not change.
`path = "[Potato].Phenology.Juvenile.Target.FixedValue"
`

So I took the following steps, the results have changed accordingly. I wonder if this is the simplest and most efficient way to do it.

1. Create a replacement
2. Add a blank cultivar in replacement
3. Add Command to cultivar by apsim server
```
    print("Connecting to server...")
    try:
        sock = connect_to_remote_server("127.0.0.1", 27747)
        print("Connected\n")
    except Exception as e:
        print(e)

    changes=[
        {"path": "[Rua].Command[1]",
         "value": '[Structure].FinalLeafNumber.FixedValue = 29',
         'paramtype': PROPERTY_TYPE_STRING
         },
        {"path": "[Rua].Command[2]",
         "value": '[Tuber].LiveFWt.DryMatterContent.XYPairs.Y = 0.13,0.21',
         'paramtype': PROPERTY_TYPE_STRING
         },
        {"path": "[Rua].Command[3]",
         "value": '[Structure].Phyllochron.Phyllochron.Phyllochron.XYPairs.X = 0,0.15,0.74,0.75,1',
         'paramtype': PROPERTY_TYPE_STRING
         },
        {"path": "[Rua].Command[4]",
         "value": '[Structure].Phyllochron.Phyllochron.Phyllochron.XYPairs.Y = 5,40,40,60,60',
         'paramtype': PROPERTY_TYPE_STRING
         },
        {"path": "[Rua].Command[5]",
         "value": '[Structure].BranchingRate.PotentialBranchingRate.XYPairs.X = 0,6,7,20,21',
         'paramtype': PROPERTY_TYPE_STRING
         },
        {"path": "[Rua].Command[6]",
         "value": '[Structure].BranchingRate.PotentialBranchingRate.XYPairs.Y = 0,0,0.5,0.5,0',
         'paramtype': PROPERTY_TYPE_STRING
         },

    ]
    run_with_changes(sock,changes)
    tablename='Report'
    param_list={
                'Clock.Today.DayOfYear':c_int32,
                'Yield':c_double}
    results=read_output(sock,tablename,param_list)
    print(results)
```
The second problem was that when I copied the cultivar parameters from the planting rule into rerepacement's cultivar, the results were different from the model simulation when the Repacement was empty. I don't know if I'm making myself clear. I'm sorry for my broken English.

![image](https://user-images.githubusercontent.com/22881957/149613757-2c86a0b5-b300-40db-af7b-b80076b61469.png)
![image](https://user-images.githubusercontent.com/22881957/149613764-98895ab8-eae5-46c6-8da4-1098b078053d.png)
![image](https://user-images.githubusercontent.com/22881957/149613866-f08d61f7-4434-49c8-a0ae-cc7a68f01e4c.png)
![image](https://user-images.githubusercontent.com/22881957/149613771-1951b970-d151-4800-9edd-87129a3010d7.png)
![image](https://user-images.githubusercontent.com/22881957/149613809-897f84ed-5c5b-4b6a-a9e9-2478cfa0da89.png)
![image](https://user-images.githubusercontent.com/22881957/149613832-9a69fa88-d5fc-4809-a7c3-88eeca90b483.png)

**Comment by hol430** [comment]
> I change the cultivar parameter with the following statement and the result does not change.
path = "[Potato].Phenology.Juvenile.Target.FixedValue" 

The potato model doesn't have a juvenile phase (ie there is no child of phenology called Juvenile) so this path won't work. As a test, you could try instead modifying `[Potato].Phenology.Vegetative.Target.FixedValue`.

> The second problem was that when I copied the cultivar parameters from the planting rule into rerepacement's cultivar, the results were different from the model simulation when the Repacement was empty.

When you have an empty cultivar under replacements, the empty cultivar will overwrite the actual cultivar in the model when the simulation is run. In the case of the rua cultivar, it normally contains 6 commands, but when your simulation is run, rua will be overwritten by the empty cultivar with 0 commands, and the model behaves differently, leading to your changed results.

**Comment by xiangyi-wang** [comment]
Thanks @hol430. It was my carelessness. Now it has changed. However, when I did not set replacement, the simulation result was different from the simulation result of the software interface, which means that replacement must be set for parameter change. This operation is not required when operating on software interface.

![image](https://user-images.githubusercontent.com/22881957/149688847-bd04755f-6c37-4857-a5af-50bbd9d9b210.png)
![image](https://user-images.githubusercontent.com/22881957/149688875-8f9b2deb-95aa-40ee-a079-cdb4b480130f.png)
![image](https://user-images.githubusercontent.com/22881957/149688911-3d2dde85-a157-4a70-9863-847527857b5f.png)
![image](https://user-images.githubusercontent.com/22881957/149688928-ebb4fde9-40b0-4c94-8d4a-1e1ce5506de8.png)


And then, I would like to know in what format should I send the sequence  parameters if I want to change them. For example `[Structure].Phyllochron.Phyllochron.Phyllochron.XYPairs.X = 0,0.15,0.74,0.75,1`
I tried to make it a string without changing it
```
 changes =[{"path":'[Potato].Structure.Phyllochron.Phyllochron.Phyllochron.XYPairs.X',
               #"[Potato].Phenology.Vegetative.Target.FixedValue",
                "value": '0,0.15,0.24,0.25,1',
               "paramtype": PROPERTY_TYPE_STRING}]
```

**Comment by hol430** [comment]
I haven't implemented array support in the native comms protocol yet. As a workaround, you could probably change one element at a time. E.g. `[Structure].Phyllochron.Phyllochron.Phyllochron.XYPairs.X[1] = 0`. Biggest problem would be that there's no way to change the length of the array, but I don't really have an easy solution for that.

Also I could be wrong but I think apsim may treat the array indices as 1-based for some reason (ie the first element has index 1). Might be worth double checking that.

**Comment by xiangyi-wang** [comment]
Thanks !@hol430
