### ISSUE TITLE
Link between nodes in RotationManager not showing

### ISSUE THREAD

**Issue by youngmr290** [APSIMInitiative/ApsimX#7055]
Hi there,

I have just downloaded and installed the newest version of apsimx from the website and the arcs between the nodes in the rotation manager are not showing (as in the picture below). The sim runs as expected but it is challenging to edit without being able to see the arcs.

![Capture](https://user-images.githubusercontent.com/53179665/149722111-b9b5eaf9-9b9c-485f-a589-f448074e5a6a.PNG)

**Comment by zur003** [comment]
@youngmr290 - as a temporary work-around, you can switch to "dark theme enabled" in the Settings dialog accessible from the Home tab. You'll need to restart Apsim for the changed setting to take effect.
