### ISSUE TITLE
download error 

### ISSUE THREAD

**Issue by b-t-das** [APSIMInitiative/ApsimX#7061]
I’m having trouble getting the APSIM download link to work. First it was the UTAS firewall but spent a day getting that sorted. Now there’s a 404 error - file or directory not found. Has something changed? Am I doing it wrong?!
Cheers

**Comment by b-t-das** [comment]
the link that isn't working is https://apsimdev.apsim.info/ApsimXFiles/apsim-7059.exe

**Comment by b-t-das** [comment]
I went to the APSIM upgrades page and downloaded from there https://apsimdev.apsim.info/APSIM.Registration.Portal/Downloads.aspx 
The windows link that worked is https://apsimdev.apsim.info/ApsimXFiles/apsim-6993.exe
I also had to download/install a core runtime file to make it work https://dotnet.microsoft.com/en-us/download/dotnet/3.1/runtime

**Comment by hol430** [comment]
Looks like a problem with the old website. The [new site](https://registration.apsim.info) doesn't have these problems, so if you were to register on the new site, the download link in the email should be correct. All links to the old site (that I know of) have just been updated to point to the new site.
