### ISSUE TITLE
Problem building CairoContext and accessing netcore3.1

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7081]
I have just pulled the latest version so I can run a user simulation, but I cannot build the project even after a clean solution and rebuild all.
1.  Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8141	The tuple element names in the signature of method 'CairoContext.GetPixelExtents(string, bool, bool)' must match the tuple element names of interface method 'IDrawContext.GetPixelExtents(string, bool, bool)' (including on the return type).	ApsimNG (netcoreapp3.1)	C:\Data\Source\Repos\ApsimX\ApsimNG\Views\Sheet\CairoContext.cs	75	Active

Any advice to get back up and running?

**Comment by hol430** [comment]
Do you have any local changes on your branch? The names of the tuple values were changed on Jan 5 in both the class and the interface, so if for some reason you made a change on your branch (such that the tuple value names in the class don't match those in the interface), that might cause the error.

**Comment by lie112** [comment]
hmm. I won't have any changes in those classes. I have pushed all my local changes to my branch and pull release master and there were no conflicts. But I seems I haven't picked up any of the commits on the 5th . maybe Ill try pull my changes and see if I can get up to date.

**Comment by lie112** [comment]
I had all the Jan 5 commits, but had a couple unloaded projects.
After 3 clean solution/restart vs/rebuild all, it downloaded and installed gtk 3.24.24 and built successfully. 
Now the code runs. very odd
