### ISSUE TITLE
Adding Urine N load in APSIM

### ISSUE THREAD

**Issue by amthant** [APSIMInitiative/ApsimX#7083]
Hi All,
I am a new user of APSIMX and trying to estimate N leaching from different forage crops.
As a brief, I have done some forage cropping trials for two years in NZ. From these trials, I got dry matter yield and crop N content. Based on that, I estimated the cow’s N intake and Urine N loading by using Urinary N excretion equations. Then, I got a Urine N load (kg N/ha) for each type of crop, assuming this Urine N load will be deposited into the paddock at the end of the crop cycle. To be easier, all Urine N loads will be one-off deposition in this exercise.

So, I have tried to add this Urinary N load as a **Urea-N** using the manager-script as in the picture. To be a kind of urine N, this Urea-N is provided 5 mm of water on the day of its application [as in previous literature] (see both manager scripts under UrineN management folder in the picture).

Here, I am a little bit in doubt whether it is correct or not? If not, how I can add this excreted urinary N load to the APSIM (30 years long-term simulation). 

Your support is appreciated.
Thanks
Aung
![image](https://user-images.githubusercontent.com/84106498/152749423-f7cd096f-297a-4ec1-9b65-f0f4ad3c1e14.png)
![image](https://user-images.githubusercontent.com/84106498/152749873-c3a0b3b3-f6b7-4cfa-9409-3b2880cb1e0d.png)

**Comment by hol430** [comment]
@sno036 are you able to assist here?

**Comment by sno036** [comment]
Hi @amthant - we would usually use the SimpleGrazing manager/model for this. See the AgPasture example simulation.

For the shots above I don't see anything particularly wrong. I assume you have outputted the end of say soil N amounts to check you got what you intended?

**Comment by amthant** [comment]
Thank you, Val Snow @sno036. Yes, soil N amount is outputted and ranged 100-150 kg N/ha on average, but higher in simulation without irrigation in summer (~200 kg N/ha). 

I will look at the SimpleGrazing manager and will see how the result changed.
