### ISSUE TITLE
Model documentation appears to be down

### ISSUE THREAD

**Issue by youngmr290** [APSIMInitiative/ApsimX#7099]
Looks like a recent change has introduced a bug into the documentation.

[https://apsimnextgeneration.netlify.app/modeldocumentation/](url)
![image](https://user-images.githubusercontent.com/53179665/153818629-4e38b715-5dcf-4ffd-bfc3-da69ba2b39df.png)

**Comment by hol430** [comment]
Thanks for the heads up - this is now working once more.
