### ISSUE TITLE
Remembering expanded state on node collapse/expand in ExplorerPresenter

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7106]
Does the UI always remember the user expanded state of tree nodes after you have closed a node? Just as the last state is remembered and restored when you open the simulation, are the user expanded states descendant nodes remembered when you collapse a node? It would be super useful if the previous state was saved so that when you open a node it expands to the previous user defined state of all descendants rather than just showing each child collapsed.
This would be really valuable when working with large nested tree structures such as a CLEM grazing simulation as you often want to close off a branch to clear up the screen, but later when expanding the branch would like it how it previously was expanded. 
Also when is the expanded state saved? It seems that unless you close the application the node expanded states are not saved, and don't save with the Save menu option. I have been unable to understand it from code, but seems the expandedRows.ForEach in refresh() needs to be called in Expand() as well.

**Comment by hol430** [comment]
If you collapse a node in the tree, its expanded state will not be saved. This mainly a result of the data structure used to store the expanded rows in a file, which can't really support collapsed rows. That structure could be changed, of course.

The expanded rows' state will be saved when you close the tab or the whole GUI.

**Comment by lie112** [comment]
Hey stalebot, please keep this issue open
I believe an Expanded property such as Enabled would be a useful addition to Model.cs. While GUI tree state of a model is not really the responsibility of the Models.Model domain, this property would be able to remove all code needed to remember the tree expanded state on exiting and improve functionality by allowing previous sub-branch expanded state to be remembered. One could argue IsHidden and ReadOnly are also GUI based properties of Model.cs as they don't affect the simulation unlike Enabled which has model control use. Model itself is really a base class (could called "ModelHolder") responsible for identifying a model object and locating it and others in scope in the simulation tree and provides no code relating to each biophysical  "model"

**Comment by lie112** [comment]
please keep this on to do list

**Comment by lie112** [comment]
please keep on to do list

**Comment by lie112** [comment]
keep on to do list
