### ISSUE TITLE
Developing new algorithms to affect photosynthesis or RUE in APSIM NG

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/ApsimX#7110]
Does anyone know where and how to write scripts to set some conditions (e.g temperature stress) to affect wheat photosynthesis in APSIM NG? 

I have added some simple scripts below to clarify. Many thanks for your help!

if (wheat.zadok_stage > 60 and wheat.zadok_stage < 79 AND maxt >= 32 AND maxt < 34) then
   heat_multiplier = 0.9
   RUE or Photosynthesis =RUE or Photosynthesis*0.9
endif

**Comment by hol430** [comment]
See [here](https://apsimnextgeneration.netlify.app/usage/writemanagerscript/) for some help writing manager scripts. Your example script might look something like this in next gen:

```csharp
using System;
using Models.Core;
using Models.Functions;
using Models.Interfaces;
using Models.PMF;
using APSIM.Shared.Utilities;

namespace Models
{
    [Serializable]
    public class Script : Model
    {
        [Link] Plant wheat;
        [Link] IWeather weather;
        [Link(Type = LinkType.Ancestor)] Zone zone;

        [EventSubscribe("DoManagement")]
        private void DailyTimestep(object sender, EventArgs args)
        {
            if (wheat.Phenology.Zadok > 60 && wheat.Phenology.Zadok < 79 && weather.MaxT >= 32 && weather.MaxT < 34)
            {
                double heatMultiplier = 0.9;
                Constant rue = (Constant)FindByPath("[Wheat].Leaf.Photosynthesis.RUE").Value;
                rue.FixedValue = rue.FixedValue * 0.9;
            } 
        }
    }
}
```

**Comment by KeLiu7** [comment]
Many thanks @hol430
