### ISSUE TITLE
add water uptake and (no3+nh4) uptake as N uptake to IPlant

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#7112]
// add water uptake and (no3+nh4) uptake as N uptake to IPlant

This is a note that we made as finished the last spring. TBD today.

**Comment by hol353** [comment]
Actually this is already done. The outputs are WaterUptake and NitrogenUptake. NitrogenUptake sums no3 and nh4.

**Comment by sno036** [comment]
Done.
