### ISSUE TITLE
Day report for simution in ApsimX

### ISSUE THREAD

**Issue by VicB18** [APSIMInitiative/ApsimX#7138]
Hello,
I want to create a day report for a single season crop simulations like [here](https://www.apsim.info/support/apsim-training-manuals/single-season-crop-simulations/). How can I define a day report frequency in ApsimX?
Is there any tutorial about this?

Thank you

**Comment by hol430** [comment]
See [report documentation](https://apsimdev.apsim.info/ApsimX/Releases/7016/Report.pdf). Normally one would set the reporting frequency to `[Clock].DoReport` or `[Clock].EndOfDay`.

**Comment by VicB18** [comment]
Thank you, Drew.
Finally, I've got that `[Clock].EndOfDay` must be added to the Report frequency window, not `[Clock].Today` must be changed in the Repoting variables window.
