### ISSUE TITLE
Weaner feeding in month of weaning only

### ISSUE THREAD

**Issue by wat-404** [APSIMInitiative/ApsimX#7147]
In CLEM, am using filters to feed hay to filter "IsWeaner" (see PDF). It works fine if I feed in the month of weaning (June in this case) but if I move the feeding month to July, no hay is fed. There are still plenty of weaners in July. Anyone know what I am doing dumb?
[Feeding_Weaners.pdf](https://github.com/APSIMInitiative/ApsimX/files/8175323/Feeding_Weaners.pdf)
@lie112

**Comment by lie112** [comment]
Can you send a screen shot (windows key, type "snipping tool", or Fn+PrintScreen) of the tree structure and all children under the weaning activity? It a bit hard to understand from the summary description with so many disabled components. I suspect you have two conflicting timers happening. The child component with timer will also respect the parent timer.

**Comment by wat-404** [comment]
How is this? Works fine in June but no hay fed if June is changed to July. (I like the “Notes” field!). Ian

***@***.***

**Comment by lie112** [comment]
That didn't seem to work passing the image. Looks like it was an email address that git strips for security..
You'll need to copy (Ctrl+C) the image and paste (CTRL+V) it into a message here. It will be embedded and show up in the git issues.

**Comment by wat-404** [comment]
This any better?

***@***.***

**Comment by wat-404** [comment]
[FeedWeaners.docx](https://github.com/APSIMInitiative/ApsimX/files/8175695/FeedWeaners.docx)

**Comment by wat-404** [comment]
Here as a doc and I’ve also uploaded as a comment.

**Comment by lie112** [comment]
As previously stated, you have a conflict of timers.
![image](https://user-images.githubusercontent.com/19215637/156515734-8ce3ac84-3526-46a7-9acb-1c1a0ed55cf3.png)
The ActivityIntervalTimer below V_FeedWeaners is ok in June, but conflicts with WeanJune Timer from the parent Wean_June when set to July. As you cannot be in both June ad July at the same time, the second activity (feeding) is not performed. 
See [CLEM Help - Uisng timers](https://www.apsim.info/clem/Content/Features/Timers/UsingTimers.htm) for example and explanation.
Solution: move the V_feedWeaners activity up on level to be a sibling (not child) of Wean_June

One day I might try and report these as warnings to alert the user to potential problems.

Note when you paste an image into the git issue message it will create a image tag with a web link included.
