### ISSUE TITLE
CLEM - Disc I/O error

### ISSUE THREAD

**Issue by wat-404** [APSIMInitiative/ApsimX#7148]
Kept getting "Disc I/O error" on opening APSIMx CLEM file. Eventually found there was a problem with the *.db-shm and *.db-wal files. I renamed the APSIMx file but can't delete the two offending files. I'm running CLEM from my C: drive, no link to OneDrive.

**Comment by hol430** [comment]
Try closing apsim before deleting them. If that still doesn't work, try rebooting and then deleting them.

**Comment by lie112** [comment]
We have tried all these options and the files remain locked after restarting the computer. If this is not a OneDrive sync issue (which we don't believe it is as this is a local c:\ folder), then all I can think is that it's the issue of locked SQLite wal files across threads. This may be a one off situation, but just wanted to get to the bottom of this in case it's a bug and it's not nice to have files that cant be deleted off a computer.

**Comment by wat-404** [comment]
Yep, have tried rebooting (etc), and upgraded all Dell drivers.

Have moved all the files that I can into another folder but the ones left behind (see attached doc) are all the same situation. So, three separate APSIMx files have created them.

Regards, Ian

**Comment by wat-404** [comment]
[Doc1.docx](https://github.com/APSIMInitiative/ApsimX/files/8182043/Doc1.doc

**Comment by wat-404** [comment]
[Doc1.docx](https://github.com/APSIMInitiative/ApsimX/files/8182050/Doc1.docx)
