### ISSUE TITLE
CLEM - Animal pricing 'Both' not working

### ISSUE THREAD

**Issue by wat-404** [APSIMInitiative/ApsimX#7149]
When AnimalPricing set to 'Both' (i.e. Both Purchase and Sale) three types of strange things happen. (Note that at the end of my AnimalPricing I have a catch-all filter of $2/head. All other AnimalPricing higher up the tree is at a $/kg. = see attached doc).

1) CastrateMaleSales not picked up by AnimalPricing  FiltersByProperty and get sold at $2/hd
2) ExcessBreeder and DryBreeders were sold at $/kg in the first few years and then switched to $2/hd in later years. Strange!
3) I set Bulls with a Purchase Price of $3000 and a Sale Price of $2.50/kg but they always get sold at $3000/hd, never at $2.50/kg

If I change my AnimalPricing from 'Both' to 'Sale' then the animals in (1) and (2) get sold correctly at $/kg. (I haven't played with the Bulls). That is, when I set to 'Both' my sales are corrupted but when I set to 'Sales' they work fine.

Note that I am never buying females and only Sires so I haven't experimented with separate AnimalPriceGroups for buying and selling stock

BTW - Does it matter that CLEM uses the terms 'Both', 'Purchase' and 'Sale' whereas the Descriptive Summary uses 'Buy and Sell', 'Buy' and 'Sell'?
 
[Buy-and-Sell.docx](https://github.com/APSIMInitiative/ApsimX/files/8183380/Buy-and-Sell.docx)

**Comment by wat-404** [comment]
Lie112 - sorry Adam I meant to tag you on issue #7149 re AnimalPricing.

**Comment by lie112** [comment]
I'll have to look into these issues.

**Comment by lie112** [comment]
I think there's a problem when the model switches between buy and sell price requests. I'll fix this and improve the functionality at the same time.
