### ISSUE TITLE
Error in graphing series colours

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#7153]
When there are multiple plots on a graph, most with "vary by simulation name" for colouring, changing one plot to a set colour changes them all to that colour.

**Comment by sno036** [comment]
AArgh - sometimes but not always!

**Comment by hol430** [comment]
Do you have a file which shows the problem? I'm more than willing to believe there are problems with the graphing code, am just having some trouble reproducing this one.

**Comment by hol430** [comment]
@sno036 I don't suppose you remember which file this happened in? I've tried a few graphs configured differently and couldn't reproduce the problem.

**Comment by sno036** [comment]
Can't reproduce so closing.
