### ISSUE TITLE
EnabledCallback method of DisplayAttribute

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7154]
I cannot find the implementation of the EnabledCallback method name passed as a DisplayAttribute variable in the code.
Lots of properties provide a value for this parameter in the DisplayAttributes.
I was hoping to utilise this feature or add a similar VisibilityCallback method to not display properties in some Model instances (e.g. when no value provided by the drop down Method).
Has this functionality been lost in the upgrade of UI to .Net core?

**Comment by hol430** [comment]
Looks like the feature was lost when we migrated to the new property UI. From the git history, it seems that it was only used to set the property cell to read only if the callback returns false. I can add this back in, but would it be better to not show the property at all?

**Comment by lie112** [comment]
I can understand the benefits of both approaches

- Disabled is still a visible property to the user, just not enabled suggesting something has turned it off and a setting would get it back
- turning visible off would be better when the developer would like to hide the property under certain conditions, when the user doesn't need to know about the property. 

I'd actually be happy if the disabled was reinstated and a VisibilityCallback was also added.

**Comment by lie112** [comment]
Does adding this into the Infrastructure plan mean we should keep this issue open?

**Comment by hol430** [comment]
Better to leave it open, otherwise it might not get fixed :).
