### ISSUE TITLE
MathUtilities float comparisons >= <=

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7157]
I had found various code snipped in APSIMx where float comparisons were handled directly in the code and so I created my own float extension methods to safely handle double comparisons accounting for double rounding. After this I found the provided methods in Shared.MathUtilities and have switched across to using the standard methods provided. This is not working as I would have expected.

The IsGreaterThanOrEqual and IsLessThanOrEqual do not provide the additional FloatsAreEqual() test so
MathUtilities.IsGreaterThanOrEqual(1.0, 1.0) = false (a value1 - value2 [0] is not >= tolerance)
I would expect this needs to be <= tolerance for the test to return true.

- Are these Is methods correct and tested or are they meant for something other than what I expected?
- Should the difference between the two values be absolute before comparing with the tolerance level to account for precision error above and below expected value? Only FloatsAreEqual does the absolute conversion.
- Should IsGreaterThanOrEqual have || FloatsAreEqual(value1, value2) to also check for equality?

This will also apply to IsPositive and IsNegative using the simple IsLessThan and IsGreaterThan.

**Comment by lie112** [comment]
Upon further investigation I have answered some of my previous questions and it appears that only the >= and <= need to have the FloatsAreEqual test added
I have worked out what the various comparisons in LessThan and LessThanOrEqual are for
The assumption that if the difference is >= tolerance does not hold for the OrEqual cases.

Examples using the equations provided in the MathUtilities with a tolerance of 0.001
![image](https://user-images.githubusercontent.com/19215637/157169989-3056e9c4-a404-4778-a60d-b214fb87e6ed.png)

**Comment by lie112** [comment]
It seems I am the first to ever use these methods, so I will make the correction for my current refactor and pull.

**Comment by par456** [comment]
This has been fixed Mar 15, 2022.
