### ISSUE TITLE
Cattle loading, 'truck' vs 'deck'

### ISSUE THREAD

**Issue by wat-404** [APSIMInitiative/ApsimX#7160]
CLEM (TruckingSettings) currently uses the terminology "Number of 450 kg animals per truck load".  The term 'truck' is then used throughout TruckingSettings. @lie112 

This may cause confusion about what is being calculated.
I think that the correct term is "Number of 450 kg animals per DECK".

That is, each 'truck' could have up to six 'decks' (i.e. 3 trailers at 2 decks each).

1) I think the terminology should change in the 'Number of 450 kg animals per truck load' to 'per DECK'
2) It should be very clear to the user what the term 'truck' refers to in the various cost and methane calculations in TruckSettings. Is it cost and methane per DECK or is it per TRUCK (which potentially has anything from 1 DECK to 6 DECKS depending on configuration and road transport rules)?

https://www.tanamitransport.com.au/faq.html

Decks are also called 'Pens' in the doc below.
https://roads-waterways.transport.nsw.gov.au/documents/business-industry/heavy-vehicles/livestock-calculator-user-guide.pdf

**Comment by lie112** [comment]
I built the trucking component based on the NABSA model rules and terminology and improved the functionality and realise it was simplistic.  This component was supposed to add a bit of functionality to trucking rules, but to replicate the NSW roads calculator would need more effort and a new version of the trucking component.

As you are the first user to use this aspect of CLEM I am happy to discuss your requirements and modify the trucking component to provide the generic functionality needed across all users' requirements. If you want trucks to limit sales/purchases and effectively skip purchases or leave some sale individuals behind, we can do that. Alternatively, you may just be interested in realistic load and truck combinations for calculating costs and emissions. 
Current loads do not consider fleece moisture content and fleece weight or horned/polled state of male cattle.

Trucking has been moved into the new activities functionality and will provide much more customisation. To meet your needs and terminology I propose to update trucking to the following  properties with associated logic

- Standard animal size (kg, e.g. 450kg for beef and xx kg for DSE sheep) but will need one value for mixed species trucking or you will have to include two BuySell activities each filtered by species with different trucking details provided for each. It is not sufficient to use the breed standard reference weight as this is not a standardised measure for trucking so we'll need a user defined value.
- Number of standard animals per loading unit (Deck/Pen)
- Minimum load units per truck (smallest truck load, can be less than 1 for small truck to obtain purchases. This assumes you can fit in twice as many individuals of 50% standard weight as 100% standard weight which may not be correct and is the outcome of using purely weight as a loading measure)
- Maximum load units per truck (allows for regional road rules to be enforced)
- Load unit group size (e.g. 2 will mean you can only have 2,4,6 decks per truck)
- km to market 
- costs have now been moved out of the trucking activity component to the RuminantActivityFee and will allow cost to be calculated per truck, per load unit (deck or pen), per head, per standard animal etc.
- Minimum proportion of deck group before adding (0 continuous and not considered) 

We will need calculations for trucking emissions. 
Is this known per deck per km or is there a truck emissions + additional emissions per deck?

This will take a bit of time to implement.

**Comment by wat-404** [comment]
Sorry, was not suggesting implementing the NSW roads calculator – I was just using the doc as an example to show decks/pens and truck configurations.

Re horned vs poll – presumably the user-entered estimate of animals per deck will allow for polls or horned.

Re your dot points.
#1 I think you are still saying that user decides how many animals /deck. Makes sense. (mixed species is a bit of a trick and would be unusual)
This is from https://farmstyle.com.au/news/cattle-transport-loading-strategies-road-transport
Mean Liveweight of Cattle (kg)
Floor Area (m squared /head)
No of Head per 12.2 m deck (single deck trailer)
250
0.77
38
300
0.86
34
350
0.98
30
400
1.05
28
450
1.13
26
500
1.23
24
550
1.34
22
600
1.47
20
650
1.63
18
Table 1: Recommeded loading densities for adult cattle transported by road.

Rest of dot points make perfect sense.

I don’t know about calculating truck emissions. I assume there are calculators on the web based on total weight and distance moved.
Just quickly there is one here at
https://business.edf.org/insights/green-freight-math-how-to-calculate-emissions-for-a-truck-move/
based on 161.8 grams of CO2 per ton-mile.

Thanks, Ian

**Comment by lie112** [comment]
This issue is currently being addressed in a refactor of CLEM activities and will be resolved in an upcoming pull request.

**Comment by lie112** [comment]
Working on this
