### ISSUE TITLE
'Proportion taken up with buildings' in LandType

### ISSUE THREAD

**Issue by wat-404** [APSIMInitiative/ApsimX#7161]
@lie112 
In Resources.LandType 'Proportion taken up with buildings etc'.
This wording makes perfect sense for small-holders but for extensive cattle properties this parameter is used for the proportion of country unavailable for grazing (e.g. due to lack of water, or inaccessible rocky terrain, or whatever).

Yesterday, I was working through my CLEM file with a cattle expert from the NT Govt and we got bogged down on this term 'buildings'. That is, CLEM users can mentally adapt but explaining it to stakeholders becomes a distraction.

Could it be changed please to something like 'Proportion unavailable for grazing (e.g. buildings, or not watered)'
Or 'Proportion unavailable for grazing' (and then the help talks about buildings, bunds, not watered, inaccessible, or whatever.)
Or something similar.

**Comment by lie112** [comment]
I'm not sure this property is actually accounting for the land not grazed as that is the responsibility of the pasture management activity when it requests land upon which to grow pasture. This land "away from water" etc could contain pasture that could be managed or collected as feed, or it may be a other soil that can actually be grazed in different seasons. Once assigned buildings, it is used up and not available for any other activities to access and use. I am more inclined to simply remove the property, but there is currently no other activity allowing a user to assign land to other sources such as buildings (a mere help with calculating land areas). You could have total land and set the proportion to assign to 0.75 or whatever to account four your unused land, but this would still be available for other activities to use.  The area of pasture you are grazing should be defined in the area of pasture managed as the model assumption is that pasture is homogeneous and individuals can access all pasture.  I'd suggest you set building to zero and set the pasture area to the area than can be grazed. I don't like mixing other resource management terms in the Land (i.e. grazing). I have plans on building in accounting for pasture mass and uneven grazing. We could suggest that assigning one huge pasture for a grazing enterprise has a range of additional implications.  Do you need your total property land area to be set and assigned. I'd suggest just setting your pasture to the usable pasture area. and ignore buildings and any unused land resources, that could be used later by a solar panel activity generating power.

**Comment by wat-404** [comment]
On reflection I think you are dead right. I was following the practice of Andrew Ash (not quite blindly but not questioning enough). I was wrong to suggest to the NTG person that the Land area was grazed/watered/use area only. You are right, it should just be ‘buildings’ taken out (and maybe bunds, etc) and the grazed area can be a function of pasture area. Sorry to stuff you around but at least I suppose it is good to question assumptions.
