### ISSUE TITLE
Setting parameter values in a script

### ISSUE THREAD

**Issue by VicB18** [APSIMInitiative/ApsimX#7162]
Hello,

I want to update the parameter PH of `.Simulations.Simulation.Field.Soil.Chemical`.
![kuva](https://user-images.githubusercontent.com/47314151/157657420-45163d24-6175-41a2-98de-34df53f514a3.png)
The script is similar to [https://apsimdev.apsim.info/ApsimX/Releases/2022.2.7020.0/Manager.pdf](https://apsimdev.apsim.info/ApsimX/Releases/2022.2.7020.0/Manager.pdf). There, for example, Soil gets parameter Water, `Soil.Water`.
But in the script there is no all these parameters, neither Water, nor Chemical, nor PH.
`using Models.Soils;`
![kuva](https://user-images.githubusercontent.com/47314151/157658758-78388aa1-d380-4e40-a89c-b8bfa4715ac9.png)
How can I set their value?

Thank you

**Comment by lie112** [comment]
The options in your drop down are the properties of the soil model. The models in the tree structure below soil are other individual models. Try access these directly by surrounding the model name with square brackets to locate the model e.g. [Chemical] then you will be able to access the properties of those models.

**Comment by VicB18** [comment]
Thank you, Adam.
Sorry, I still don't understand how to use it and I am a bit frustated in general from the structure of the program. Can you, please, clarify it?
1. I write the script in VS C#. The .cs file is inside Models folder. Does the VS C# allow using square brackets? Can the project be compiled with this notation?
2. In the example [https://apsimdev.apsim.info/ApsimX/Releases/2022.2.7020.0/Manager.pdf](https://apsimdev.apsim.info/ApsimX/Releases/2022.2.7020.0/Manager.pdf) there are no square brackets. What is the difference between that script and mine?
3. Is there a possibility to write a script in ApsimX GUI and debug it?

I defined the `chemical` variable and assigned a value to it.
![kuva](https://user-images.githubusercontent.com/47314151/157870827-ed29d2a8-685a-4c25-9bf2-80acaedaf1e1.png)
It worked, it appeared in the report.
![kuva](https://user-images.githubusercontent.com/47314151/157871959-12b91ee8-ec75-4f68-bbad-415de5455bf9.png)
4. Is a defenition of a variable (e.g. chemical) enough to be connected to the model in the simulation? And if there are a number of the same models in the simulation?
5. I added the script in the simulation GUI (Simulation->Add model...). Can the script be just a .cs file or must it be compiled with the entire project?

Thank you

**Comment by lie112** [comment]
Maybe I should have let someone else explain things a lot clearer as it was late and I confused using square brackets for linking to the available models and providing intellisense in UI property entry boxes (such as reports) with Link attribute in the manager scripts.

See [Contribute to APSIM](https://apsimnextgeneration.netlify.app/contribute/)
See [Developing models in APSIM](https://apsimnextgeneration.netlify.app/development/)

For a detailed exaplination of what I say below look at [Write Manager Scripts](https://apsimnextgeneration.netlify.app/usage/writemanagerscript/)

You are able to create and edit the manager script inside the APSIM Next Gen UI, by add in a manager script to your tree and clicking on this manager script model in the tree structure you will get a code entry area in the right hand panel. Improved code editing is being considered by APSIM at present. When included in your simulation tree the manager script details (code) will be saved within the simulation apsimx file. This means the manager script code can be passed to others running your simulation and does not require access to the development environment with the need to precompile the manager script into the executable and thus needed to add separate cs file in models directory which most users will not have access to when using the installed version of APSIM NG. For other users to use your compiled manager script logic, they will need to be using the compiled version you create outside the APSIM version control and quality testing. New functionality added to the models directory and the models it contains can be submitted to APSIM as a GIT pull request and incorporated in the release build, this is how the models in add new model are added to APSIM for all to users. Manager scripts are designed to be custom code added to the installed version of APSIM providing functionality to a simulation such as defining fertilisation and planting dates needed by the plant models and not precompiled with the release executable of APSIM NG. Of course this flexibility means a manager script can provide any new functionality, even a new model.

The square brackets I mentioned are equivalent to the [Link] attribute when you define an object in manager scripts as seen in the example and your code. This will locate the instance of the model (default is locate by type) you want to work with and make the properties and methods available to you. You have done this with chemical model which looks through all the models in your simulation tree structure and finds the Chemical model. If you have multiple instances of a model type you can adjust the additional properties of the Link attribute. For example [Link(ByName=true)] will Link by a model name in the tree structure which must be the same as the name of the object you are creating. IsOptional, Path and Type properties are also available from the Link attribute.

**Comment by VicB18** [comment]
Thank you, @lie112. I try to set measured values to the SoilWater every simulation day according to your explanations and the examples in [Manager](https://apsimdev.apsim.info/ApsimX/Releases/2022.2.7020.0/Manager.pdf) and [Report](https://apsimdev.apsim.info/ApsimX/Releases/2022.2.7020.0/Report.pdf).
If I set it according to the explanations
![kuva](https://user-images.githubusercontent.com/47314151/167717773-e8ff622d-a5e4-4082-aa2c-4e81194b4cbe.png)
there is no effect on the variable
![kuva](https://user-images.githubusercontent.com/47314151/167716894-b3990520-4baf-4437-b7b8-d7feabaea6ed.png)

If I try to set the value through the Soil according to the example in the file Manager.pdf,
![kuva](https://user-images.githubusercontent.com/47314151/167717029-0262005a-8273-4acf-b5b1-4bdaee5337d6.png)
the property `Water` does not exist.

If I try to set the value through the Soil according to the example in the file Report.pdf,
![kuva](https://user-images.githubusercontent.com/47314151/167717126-210b88d6-7ea8-4b0e-8947-14ceb4c8c156.png)

I succeeded before to set values to the PH, though, it had no influence on the simulation. But now I miss something.
Can you, please, explain a way to set values to the parameters?
Thank you

**Comment by hol430** [comment]
This is a problem with the design in WaterBalance, and, more generally, a problem with exposing mutable types like arrays. This workaround may seem stupid, but give it a go:

```csharp
double[] sw = SoilWater.SW;
sw[1] = 0.5;
SoilWater.SW = sw;
```

**Comment by VicB18** [comment]
Thank you, @hol430. No, it doesn't work for me.
![kuva](https://user-images.githubusercontent.com/47314151/167850048-b515817b-e043-4fa3-a01d-a8af2d974be1.png)
Still there is no changes in the yield or Soil.SoilWater.SW values in the report or graph.
![kuva](https://user-images.githubusercontent.com/47314151/167850264-4211dc15-f713-442a-a51d-88c4133b63cf.png)
(By the way, the units and the title of the graph are incorrect.)
