### ISSUE TITLE
Creating a standalone ApsimX server [question]

### ISSUE THREAD

**Issue by enviroeye** [APSIMInitiative/ApsimX#7179]
Hi there,

We're engaged in a project modelling sugarcane in QLD with a view to working to reduce nutrient run-off onto the Barrier Reef.

We've been building out our modelling using the standard client. However, we would like to run a server version that we can push data to form our own platform which gathers weather and crop data and run simulations there.

We realise there is good documentation on doing this using MS Azure but alas we're an AWS shop and realise there is currently no support today for other cloud providers.

We've taken a good look at the .apsimx file that's generated along with the .met files are confident we can create these based on data stored/gathered by our platform.

We'd just not to clear on how the server version of ApsimX processes these files; does it monitor a specific directory for new files, is it listening on a particular port for an API push or some other method?

Ideally, we'd like to push updated .apsimx and .met files to an AWS S3 bucket which triggers a mechanism (Lambda function) in AWS that has the server run the simulation(s) across the modified files.

And by extension, in the server version how the results of the simulation are returned; e.g. written to a file in a directory on the server?

Any help or guidance would be greatly appreciated.

Mark

**Comment by hol353** [comment]
> We'd just not to clear on how the server version of ApsimX processes these files

I'm not sure what you mean by 'server version'. There is an APSIM Server assembly but this has nothing to do with sending simulation jobs to Azure. If you mean the functionality in the user interface then it calls the Azure web API to submit the simulations currently open in the GUI. The user can then come back later and click a download button to retrieve the results as a .zip file. It is a manual step triggered by the user.

To use AWS you'll need to write your own tool / scripts to do this.

**Comment by hol430** [comment]
The apsim server tool will hold an .apsimx file open in memory, and listen on a TCP port for a client to connect. When the client connects, it can tell the server to rerun the simulations with modified paramter values. The main advantage of this is to avoid the overheads associated with using the CLI (Models.exe), which can be significant in some workloads.

It sounds like you'll be re-running things (relatively) infrequently. If that's the case, you may not want to pay for a compute instance to be running an apsim server 24/7 waiting for connections.

I'd like to have some kind of support for running sims on GCP/AWS, but it would probably be via something like kubernetes, and probably wouldn't quite cover your use case anyway - as @hol353 says, the Azure feature is mainly intended to help with manual runs.

**Comment by enviroeye** [comment]
Thank-you so much for you both your replies and the clarifications.

So we could run some type of ephemeral instance of the server tool (as per the documentation here: https://apsimnextgeneration.netlify.app/usage/server/) and load into memory the requisite .apsimx file.

Would it them be possible to rewrite the client from the APSIM.Client repo from C to C# and create an AWS Lambda function which initiates the simulation, receives the .zip file of the results and then performs ETL on the results data?

I assume the Client receives a .zip of of the result?

Also, the -file <file.apsimx> argument when initiating the server instance only supports paths to local disk, and could not for example reference a file sitting an S3 bucket. Same question for the .met file referenced by the .apsimx

**Comment by hol430** [comment]
There's already a C# client [here](https://github.com/APSIMInitiative/ApsimX/blob/master/APSIM.Server/IO/ManagedCommunicationProtocol.cs). However, if all you want to do is run the simulation and return some results, then you could probably just use the CLI (Models.exe).

The client doesn't receive a .zip file, it will just receive arrays of data. The CLI will produce a single sqlite database (.db file on local disk) containing the outputs.

Yes, the .apsimx and .met file paths will only be resolved from local disk.

**Comment by Furbie** [comment]
Hi all, 

I'm Simon, I have been working with Mark to help in developing the modeling capability for the Reef initiative.

Ideally, our end goal is to have a function based routine that can process generated files on demand.
ie. apsimx/met files dropped in a location (NFS/S3) which triggers a Lambda function containing the modeling routines to process and output the data.

Stage 1 is the ability to process files in an automated fashion - keeping it simple, we just need to be able to process on demand. (Not to worried if we need to run a standalone machine at this stage to achieve it)
By reading through the above I am thinking that an instance running the models.exe could be used to process the apsimx/met files and create the sqllite db output. This sounds like a good starting point!

P.S - I would be super keen to work with you in getting this in to AWS and porting the modules to Lambda .NET Core :)

Cheers,
Simon
