### ISSUE TITLE
APSIM - Sugar development stages (question)

### ISSUE THREAD

**Issue by WillOvenden** [APSIMInitiative/ApsimX#7203]
Question regarding the development stage simulations of the crop model as I need to be able to identify when the crop progresses through the stages - particularly emergence to begin_cane (stalk growth)

According to the manual, there are 1200-1800 'C days  #between the two (depending on genotype). I was wondering if you could advise how I should recognize and categorize stalk growth vs emergence. 

When I run the sugar example in APSIM the 'stage' changes from emergence to begin_cane at the end of September (sown 1st April) so ~ 6 months. (see below)

Also, when checking the cane weight change over the cycle of the same year, the weight doesn't actually increase much until July despite emergence beginning at the end of April. 

I understand the degree days are more important than actual months but 6 months seems quite developed for the 'beginning of stalk growth'. Please could anyone explain why / how I can recognize the change in the development stage in the field?

thanks in advance!

![aspim_example](https://user-images.githubusercontent.com/77625201/160646297-0c228116-75ad-4608-a894-95d4eef7ba88.png)

**Comment by BrianCollinss** [comment]
Interesting question. I think it would help the responders if they know more about the climate and management.

**Comment by hut104** [comment]
This is a little difficult on a few fronts.

In the field it probably appears with the beginning of stem elongation.  Prior to this the stems will be mostly leaf and cabbage.  Some of that cabbage really becomes stem (it's a bit arbitrary).  The timing is somewhere around the time that tiller numbers will peak prior to loss of smaller tillers.  You could monitor the larger stems to search for elongation.

In the model, the stage is there mostly to provide some control of stem partitioning.  However, if growth is larger than leaf and cabbage DM demand, the remaining biomass is thrown into stem.  For this reason, you can get the sorts of things that you see in this graph, with stem increasing before the beginning of cane growth.  This is likely if temperature is low enough to slow leaf appearance (ie TT) but not photosynthesis, or if days are cool(ish) and radiation is high.

So, the stage in the model is really indicative only in some regards.

Neil.

________________________________
From: WillOvenden ***@***.***>
Sent: Wednesday, 30 March 2022 1:24 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] APSIM - Sugar development stages (question) (Issue #7203)


Question regarding the development stage simulations of the crop model as I need to be able to identify when the crop progresses through the stages - particularly emergence to begin_cane (stalk growth)

According to the manual, there are 1200-1800 'C days #between the two (depending on genotype). I was wondering if you could advise how I should recognize and categorize stalk growth vs emergence.

When I run the sugar example in APSIM the 'stage' changes from emergence to begin_cane at the end of September (sown 1st April) so ~ 6 months. (see below)

Also, when checking the cane weight change over the cycle of the same year, the weight doesn't actually increase much until July despite emergence beginning at the end of April.

I understand the degree days are more important than actual months but 6 months seems quite developed for the 'beginning of stalk growth'. Please could anyone explain why / how I can recognize the change in the development stage in the field?

thanks in advance!

[aspim_example]<https://user-images.githubusercontent.com/77625201/160646297-0c228116-75ad-4608-a894-95d4eef7ba88.png>
