### ISSUE TITLE
Morris SA: Analysis Results 3 only showing one point with an NA

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7204]
Hello @hol430 

I am doing a Morris SA on three parameters, the models runs pretty well. However, the graphical representation does not show as expected. The image below shows the AnalysisResults3 section where the problem is - I was expecting to have at least 5 points corresponding to 5 reporting years, but it only shows one dot and NA value. 

I have changed the Morris parameters, but it still remained the same. None of the rows in the DataStore have an empty cell for the reporting variables.  I have attached the simulation file below - thank you in advance for looking through this. 

Another question: is it possible to print more than 5 reporting years for the graph in the AnalysisResults3 section? 

![image](https://user-images.githubusercontent.com/68366659/160950820-b570cb0f-43e0-439a-8076-cecd8fab9f91.png)

[Morris_Sensitivity_Maize.zip](https://github.com/APSIMInitiative/ApsimX/files/8384909/Morris_Sensitivity_Maize.zip)

**Comment by hol430** [comment]
Hi @andynen, some of the simulations are failing because you're varying DUL between 0.2 and 0.4 in the top layer, while having an LL of 0.23. Any simulation in which DUL is lower than LL will fail to run, which is probably why you're not seeing the expected output. The lack of dots on graph will be because lots of sims are failing.

**Comment by andynen** [comment]
Thank you so much @hol430 - I have changed my DUL to 2.8 onwards, and it worked. Amazing!! 

![image](https://user-images.githubusercontent.com/68366659/160961516-e34d5149-f7b5-4b67-86cc-0eab2374bc12.png)
