### ISSUE TITLE
Performing a summation when reporting on a simulation [Question]

### ISSUE THREAD

**Issue by enviroeye** [APSIMInitiative/ApsimX#7215]
Hi there,

We're quite new to ApsimX and are currently using it to model soil water balance in sugarcane. From the Soil Water model, we are reporting on PAWmm i.e. [Soil].SoilWater.PAWmm

This returns plant available water at the individual depths defined by the soil physical properties:

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/16280541/161861224-f29a095d-6783-4e9b-8782-53945f95e786.png">

However we would also like to return a summation of PAW across the entire soil profile.

Is there a syntax we can add when defining the reporting that would return the summation rather than the individual depths?

Or there there some way we can use a function to achieve this via the 'Add Model' capability?

<img width="460" alt="image" src="https://user-images.githubusercontent.com/16280541/161861501-984476b1-1b54-4046-b8b0-868a8b9e3514.png">

By extension, is there any documentation that might help us better understand the syntax of the Reporting module and the 'Add Model' -> functions feature. We've trawled the apsim.info and apsimnextgeneration.netlify.app site, but haven't come up with anything.

Mark

**Comment by hol353** [comment]
This will sum all values in an array (i.e. all values in the profile)
```
sum([Soil].SoilWater.PAWmm)
```

If you click the Help button in the GUI and then 'Model Documentation', scroll down to the bottom and there is a report PDF that explains the syntax of reporting variables.

**Comment by enviroeye** [comment]
Thanks so much Dean, that's fantastic, we finally have a summation!

I'd read through some of the module documentation for specific crops, but had failed to notice the document for reporting. Apologies for wasting your time with this question!

Mark
