### ISSUE TITLE
Please release some CLEM upgrades - urgently needed for project milestone delivery!

### ISSUE THREAD

**Issue by alisonml** [APSIMInitiative/ApsimX#7221]
Issue # 7130 was raised (by Yacob Beletse, CSIRO) and it was fixed (# 7142) in late January (by Adam Liedloff, CSIRO). We really need this fix in CLEM to be able to deliver project milestones, due this month. Please could you release this? We're happy to install without the security certificate.

**Comment by hol430** [comment]
There's a problem with the upgrade form in the GUI right now, but there should be a new release available on the website.

**Comment by hol430** [comment]
Upgrading from the GUI should be working again now and future releases will be signed, so I'm going to close this one. Feel free to reopen if need be.
