### ISSUE TITLE
Kill AgPasture RespirationLossC

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#7224]
In AgPasture, when ryegrass and white clover are killed through the EndCrop() operation (i.e. there is no pasture there) the output RespirationLossC is retained from the last day that the pasture was there. A screenshot probably explains it better:

![image](https://user-images.githubusercontent.com/32279744/162862602-91bad6c2-d4cf-4788-96ab-981b949838a7.png)

**Comment by par456** [comment]
Was resolved by branch #7290
