### ISSUE TITLE
Maintaining Carbon Balance

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#7225]
There seems to be an issue with the reported values of GPP and NPP: GPP minus RespirationLossC should equal NPP

![image](https://user-images.githubusercontent.com/32279744/162863238-049e1c2c-9945-4f5a-a442-2aed428187a1.png)

The error comes from lines 1759 and 1766 of PastureSpecies.cs where GPP with units of kgC/ha is calculated from grossPhotosynthesis (also KgC/ha) but is then divided by CarbonFractionInDM (0.4) which converts the kgC to kgDM (which is incorrect). 

public double GPP
        {
            get { return grossPhotosynthesis / CarbonFractionInDM; }

Note that GrossPotentialGrowthWt has the same value as GPP - they use the same formula in the code.

For NPP there is a similar issue (note that respirationGrowth and respirationMaintenance are also in kgC/ha

public double NPP
        {
            get { return (grossPhotosynthesis - respirationGrowth - respirationMaintenance) / CarbonFractionInDM; }

**Comment by hol353** [comment]
Some more context here. The above described problem is about trying to do a whole of simulation carbon balance using AgPasture. After fixing a defect in nutrient / soil organic matter (#7445), the daily carbon balance pseudocode looks like:

Daily change in carbon = start of day carbon (nutrient.TotalC.Sum() + surfaceOrganicMatter.C + plant.TotalC)
+ AGPRyegrass.NetPotentialGrowthAfterNutrientWt
- nutrientBalance.Catm.Sum()
- end of day carbon (same calculation as for start of day)

This should equal zero each day of the simulation.
