### ISSUE TITLE
Q on cover calculation in water balance

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#7234]
I've got a nitpick about the Eo calculation in the water balance module, and its correctness in an inter/relay cropping situation. At the moment, the individual crop cover values are summed arithmatically, eg [here](https://github.com/APSIMInitiative/ApsimX/blob/73d7ee18d563e7fc44cfcdf6c6c4b5e0d4aad19d/Models/Soils/WaterModel/EvaporationModel.cs#L173). This summation should use beers law, as implemented [here](https://github.com/APSIMInitiative/APSIMClassic/blob/8c824210c1d80fd1a51243dd52d1e6e4bd1708f4/Model/FortranInfrastructure/science.f90#L1329) in classic. If beers law isn't used, the sum of green cover may exceed 1. 

This would only become a problem in multicrop simulations.

The procedure is done correctly a [few lines later](https://github.com/APSIMInitiative/ApsimX/blob/73d7ee18d563e7fc44cfcdf6c6c4b5e0d4aad19d/Models/Soils/WaterModel/EvaporationModel.cs#L222).

**Comment by hol353** [comment]
Well spotted. Turns out the code in CalcEo wasn't being used. PR #8380 just removes the unused code.
