### ISSUE TITLE
Saving a file freezes the UI

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#7237]
When making changes to a simulation if one hit the save button in the interface, APSIM just freezes. Windows shows the message 'not responding', trying to close the program does not seem to work, even using through the Task Manager I have not been able to close it. only re-starting the computer seem to work... This seem to occur in only the most recent versions, of this week. I have this issue using the release version (downloaded) as well as if I build myself.
Note that the simulation is actually saved...

**Comment by hol430** [comment]
When you click save, apsim will hide the right-hand panel, save the file, then redraw the right-hand panel, all on the UI thread. So if you're looking at a folder of graphs which takes a long time to draw, apsim will "freeze" when you click save for the time taken to load the folder of graphs in the GUI, which can sometimes take a few seconds. Could something like that be what's happening here?

**Comment by rcichota** [comment]
Closing this as the issue seem to have been resolved or it was indeed some quirk of graphs that is hard (cannot) be replicated easily
