### ISSUE TITLE
Error: simx ... parse_json -> parse_and_simplify -> parseJSON -> parse_con

### ISSUE THREAD

**Issue by lyfranki** [APSIMInitiative/ApsimX#7249]
Hi, I got this error when I submitted it on HPC through slurm. Does anyone know why it is?

```
Edited (node):  Clock
Edited (child):  none
Edited parameters:  Start
New values:  2017-01-01T00:00:00
Created:  /data/keeling/a/yinl3/apsim//Maize-edited.apsimx
Edited (node):  Clock
Edited (child):  none
Edited parameters:  End
New values:  2017-12-31T00:00:00
Created:  /data/keeling/a/yinl3/apsim//Maize-edited.apsimx
simx ... parse_json -> parse_and_simplify -> parseJSON -> parse_con
Execution halted
```

**Comment by peter-devoil** [comment]
Is there anything in standard error?

**Comment by hol430** [comment]
What's generating this output? It doesn't look like it's coming from apsim.

**Comment by lyfranki** [comment]
When I ran the APSIMX in R, it generated this output.

**Comment by hol430** [comment]
How are you running apsim in R? And as @peter-devoil said, is there anything being written to stderr?

**Comment by lyfranki** [comment]
I solved this issue when I remade .apsimx file.
