### ISSUE TITLE
GPP - missing C?

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#7264]
I am running a very simple rotational grazing experiment using AGPasture. Ryegrass/white clover with no N inputs. I have attached the simulation and weather files:
[MassBalanceGH.zip](https://github.com/APSIMInitiative/ApsimX/files/8606540/MassBalanceGH.zip)

The graph below is taken from the simulation (C losses) and shows the simulated annual GPP (top black line) and then all the various respiration losses (pasture, animal, soil, residue etc.) as well as C offtake in product, CH4 production.  There are also any changes in C stocks i.e. soil C and standing plant C on the day of reporting (June 30) though the plant C is a not very useful but included for completeness. The second yellow line (CALC) shows these added together. If my understanding is correct they should add up to the GPP line but don’t. 

![image](https://user-images.githubusercontent.com/32279744/166342216-725fd7ba-c571-4e08-9cfb-62dc6fb4a317.png)

It is either a coding issue or I am reporting incorrectly. I found a coding error in how GPP is calculated (reported in Git) and have corrected that in my reporting. Is something in the code being calculated as CO2 or something like that? – I could not find anything.

The reporting is done in "AnnualReporting" - I hope the comments are self-explanatory to explain what is being calculated. 

I have tried numerous situations - for example don't graze (by setting SimpleGrazing to a very high target mass), removing clover (enable Operations and uncomment 1990-07-01 [AGPWhiteClover].KillCrop()) but the problem persists. An possible avenue of investigation is that when I add N fertiliser (by enabling FertiliseFixedDates) there is less "missing C" and in some years nearly all the GPP can be accounted for by the respiration losses and changes in soil and plant C.

![image](https://user-images.githubusercontent.com/32279744/166342509-4e390e55-349f-4d2b-80ab-0eebb721788d.png)

Any ideas?

Cheers

Mark

**Comment by sno036** [comment]
Thanks Mark - @hol353 and I will discuss next week and see if we have a solution.

**Comment by MarkLieffering** [comment]
@sno036 @hol353 I have delved a bit more into this and had a look at a daily file (I tried this ages ago but got nowhere). Same simulation as before but with daily outputs. I made two reports - a start of day and end of day. This enabled me to match the daily change in C stock in the plant and soil. I exported to excel - see attached file. Should be self-explanatory. No grazing, so plants are just photosynthesising, respiring and dying and entering the soil C cycle. The daily GPP can only go into respiration (plant, soil and residue respiration), the plant C pool or the soil C pool. We can then calculate what that was based on the respiration and stock C outputs (CalcGPP). It does not match the reported GPP. If you plot the Diff% you can see that there appears to be a seasonal pattern.
[SOD_EOD_MassBalance.xlsx](https://github.com/APSIMInitiative/ApsimX/files/8774195/SOD_EOD_MassBalance.xlsx)

**Comment by MarkLieffering** [comment]
Just making sure this does not go stale!
