### ISSUE TITLE
UI exception in CodeView used by composite factors

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7265]
I am getting an exception thrown by CodeView.cs from the composite factors displayed in an experiment.
The problem occurs in _mainWidget_Destroyed as scroller.Hadjustment is null when trying to unsubscribe Hadjustment_Changed. This also relates to Vadjustment.
I handled it in my code with a null check but not sure why this happens and thought it should be checked properly

**Comment by hol430** [comment]
Are you running the latest code? I can't see any references to scroller or hadjustment in that function.

**Comment by lie112** [comment]
Maybe it's been fixed
I've got pretty new code, but I'll pull again and let you know.

**Comment by lie112** [comment]
this has been resolved in latest updates
