### ISSUE TITLE
Object reference not set to an instance of an object 

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7268]
Hello @hol430, 

I made a Morris simulation which successfully ran at first, but upon changing some variables in the Report module, it started giving the following error: **"Object reference not set to an instance of an object"** and the one below

![image](https://user-images.githubusercontent.com/68366659/166613644-4123bfe0-eb94-4d76-9964-c95c7641d634.png)

I have removed all the variables reported to check if it was the source, but the error still persist. 
I checked the path and they all seem to be rigt. 
I have also reduced the number of parameters in the Morris module but no change. 

Can you please have a look - I am not sure how to check. Thank you. 

NB: I am using the latest version of APSIMX. It ran successfully after upgrading at first. Not sure where the issue may come from. 

Attached here is a sample of the run. 
[Morris_Sensitivity_Maize_Vo4Test.zip](https://github.com/APSIMInitiative/ApsimX/files/8617620/Morris_Sensitivity_Maize_Vo4Test.zip)

**Comment by hol430** [comment]
The problem is in the ResetAndOutput manager script. You have events called Reporting and Reseting, but nothing subscribes to them. You should either subscribe to them (e.g. subscribe to the Reporting event in your report module by adding `[ResetAndOutput].Script.Reporting` to the reporting frequency), or by adding a null check inside the ResetAndOutput script. The same also applies to the Reseting event.

```csharp
using Models.Soils.Nutrients;
using System;
using Models.Core;
using Models.PMF;
using Models.Soils;
using Models.Soils.Nutrients;
using Models.Interfaces;
using Models.Utilities;
using Models.Surface;
using APSIM.Shared.Utilities;
using Models;

namespace Models
{
    [Serializable]
    public class Script : Model
    {
        [Link] private Clock Clock;
        [Link] private ISoilWater SoilWater;
        [Link] private INutrient Nutrient;
        [Link] private SurfaceOrganicMatter SOM;
        [Link] private Summary Summary;
        [Link] private Report Report;
        public  event EventHandler Reseting;
        public  event EventHandler Reporting;

        [Description("Date for output:")]
        public string OutputDate {get;set;}

        [Description("Date for reset:")]
        public string ResetDate {get;set;}

        [Description("Reset Water?")]
        public string ResetWater {get;set;}

        [Description("Reset Nitrogen?")]
        public string ResetN {get;set;}

        [Description("Reset Surface Organic Matter?")]
        public string ResetSOM {get;set;}

                /// <summary>Occurs when a plant is about to be harvested.</summary>
                /// <summary>Occurs when a plant is about to be harvested.</summary>


        [EventSubscribe("DoManagement")]
        private void OnDoManagement(object sender, EventArgs e)
        {
            if (DateUtilities.WithinDates(OutputDate, Clock.Today, OutputDate))
            {
            	if (Reporting != null)
                   Reporting.Invoke(this, new EventArgs());
               //Report.DoOutput();
            }

            if (DateUtilities.WithinDates(ResetDate, Clock.Today, ResetDate))
            {
                if (ResetWater == "Yes")
                {
                    Summary.WriteMessage(this, "Reset Water", MessageType.Diagnostic);
                    SoilWater.Reset();
                }
                if (ResetN == "Yes")
                {
                    Summary.WriteMessage(this, "Reset Nitrogen", MessageType.Diagnostic);
                    Nutrient.Reset();
                }
                if (ResetSOM == "Yes")
                {
                    Summary.WriteMessage(this, "Reset Surface OM", MessageType.Diagnostic);
                    SOM.Reset();
                }
		if (Reseting != null)
                    Reseting.Invoke(this, new EventArgs());
            }
        }
    }
}
```

**Comment by andynen** [comment]
@hol430 
, 
Thank you. 

To subscribe to both reseting and reporting events,  I added the syntax "Sum of [Soil].SoilWater.Runoff from [ResetAndOutput].Script.Reseting to [ResetAndOutput].Script.Reporting as Runoff" in the reporting module, and it ran successfully. 

The null checks you provided in the scripts also worked perfectly. 

Thank you.
