### ISSUE TITLE
Mungbean Model for APSIM NextGen Ready for Review

### ISSUE THREAD

**Issue by hrpasl** [APSIMInitiative/ApsimX#7283]
A new mungbean model has been built for APSIM NextGen and is now ready for review. The model was calibrated and tested using field datasets from throughout Australia and found to have accurate (RMSDYield=282 kg ha-1; RMSDBiomass=787 kg ha-1). The new model can also simulate water stress and the different responses to varying environment and management schemes recorded in the field. The review of the model by the APSIM panel is scheduled for June 7, 2022.

**Comment by hrpasl** [comment]
[Mungbean Review Panel Final.zip](https://github.com/APSIMInitiative/ApsimX/files/8820626/Mungbean.Review.Panel.Final.zip)
Powerpoint for Review

**Comment by hrpasl** [comment]
[Mungbean.pdf](https://github.com/APSIMInitiative/ApsimX/files/8820896/Mungbean.pdf)
Auto-documentation of Mungbean Model.

**Comment by jbrider** [comment]
Small things...
In Phenology.ReproductiveThermalTime.Response
 - XYPairs has a Graph node below it?

In Phenology at the bottom there are DAS variables that all have the same Memo

In Leaf BranchingRate and Phyllochron have the same memo

In Shell and Stem there are quite a few empty memo's

In Validation
 - In the Yield Gap folder there are a few Graphs folders that have Regression nodes that don't need to be there?

**Comment by hrpasl** [comment]
Jbrider: Thank you for your thorough review of the model! I removed the extra bits that you found and condensed all the memos into one that is at the top of each section (except for a few that explain a particular parameter itself, not the value attributed to it). I removed the blank memos.

**Comment by hrpasl** [comment]
[Responses to comments from the APSIM Review Panel.docx](https://github.com/APSIMInitiative/ApsimX/files/8865987/Responses.to.comments.from.the.APSIM.Review.Panel.docx)
Thank you for all the comments and suggestions. I have addressed all of the raised issues or will in the future as more datasets are made available (see attached document for details).

**Comment by hol353** [comment]
@APSIMInitiative/reference-panel: Heather has addressed the review comments. Can you please have a look at her response and comment here on any further issues you might have. If there are no further responses by Friday 10th it will be merged into the release.

**Comment by jbrider** [comment]
@hrpasl The differences between NextGen and Classic were very well detailed in the word document - can they be added into the model somewhere - maybe as a memo so it's picked up in the autodocumentation.

**Comment by hrpasl** [comment]
@jbrider I put in a new memo for that.
