### ISSUE TITLE
grain_gth_rate in APSIM NextGen

### ISSUE THREAD

**Issue by guillemodon** [APSIMInitiative/ApsimX#7291]
Hi everyone. I'm currently trying to calibrate the parameters for maize in Argentina. I'm using APSIM NextGen and currently having issues trying to follow methodologies such as the ones used by Archontoulis (2014) and Balboa (2019) - they used APSIM 7.x.
In particular, I can't find the equivalent parameter for grain_gth_rate, which, according to the authors cited, is set to a constant value. I've read that the parameter has been removed in APSIM NextGen. Anyone can help?
Thanks in advance. 
Teamed with @daianfrancia

**Comment by sarchontoulis** [comment]
The maize models are different between classic and next gen. The names of the cultivar parameters are different and some params have been replaced, eg., the grain-growth-rate (classic) has been replaced with the max kernel size (next gen).

Make a right-click on the maize model and select "show model structure". Then you can see the model structure and if you go to the cultivar folder you can see the parameter values, here is an example for the "mh18" cultivar

[Phenology].Juvenile.Target.FixedValue = 260
[Phenology].Photosensitive.Target.XYPairs.X = 0, 12.5, 24
[Phenology].Photosensitive.Target.XYPairs.Y = 0, 0, 264.5
[Phenology].FlagLeafToFlowering.Target.FixedValue = 10
[Phenology].FloweringToGrainFilling.Target.FixedValue = 170
[Phenology].GrainFilling.Target.FixedValue = 550
[Rachis].DMDemands.Structural.DMDemandFunction.MaximumOrganWt.FixedValue = 14
[Grain].MaximumGrainsPerCob.FixedValue = 486
[Grain].MaximumPotentialGrainSize.FixedValue = 0.361

**Comment by guillemodon** [comment]
Thank you so much!
