### ISSUE TITLE
Importing Apsim Classic file will fail if DCaPs is present

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#7300]
Exception occurs if DCaPs is present in the classic file and it aborts the whole import process.

**Comment by her123** [comment]
Can you attach the classic file?

**Comment by jbrider** [comment]
Thanks @her123 We want to test and validate the new nextgen component before writing a converter.
I should have assigned myself to it.
If you wanted to write a general fix that doesn't crash the whole import process when it encounters something unexpected I would say go for it - and I can dig up an example for you. 
Pretty sure there are higher priorities right now though if you have some time to help out. 
@hol353 probably has a long list at the moment.

**Comment by hol353** [comment]
Another issue for the importer:

when a soil is imported (or copied / pasted from APSIM 7.10), 

- the soil must have Nutrient (rather than SoilNitrogen)
- the soil must have 3 solutes (no3, nh4 and urea)
- the soil must have a (CERES) soil temperature model.

**Comment by hol353** [comment]
I used an old APSIM DCAPS example (Continuous Sorghum with DCaPST.apsim) to reproduce the problem. I changed the importer to not stop when it encounters a manager script compile error.
