### ISSUE TITLE
Tables in Params/Inputs/Outputs documentation unreadable in some cases

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#7307]
This mostly happens when the first column in the table is far too narrow. Text gets overwritten. AgPasture is a good (bad) example of this.

**Comment by MarkLieffering** [comment]
Any update on this? Not super urgent - just a minor irritation!

**Comment by hol353** [comment]
It's not anywhere near the top of my todo list. Of course @sno036 controls part of my time (life?). Perhaps at our upcoming SWIM / AgResearch sprint I might find the time.
