### ISSUE TITLE
AutoDoc adds documentation for things that probably shouldn't be documented

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#7314]
The canola validation includes folders that are disabled.  These still get documented.
The disabled folders (and children) in the canola validation have folders that are set to not document.  The experiments within these folders still get documented.

**Comment by jbrider** [comment]
The pull request regarding the inconsistencies in XYPairs presenter and documentation #7311 fixed the graph labelling for me.

**Required** appears to be some sort of key word for documentation, as any variable called Required gets a surrounding set of *. It looks like t's trying to bold it, but is just adding *

Aren't the lower level functions the details that need to be documented?

**Comment by jbrider** [comment]
GetDocumentationElement function appears to remove all tabs and spaces - which would remove any deliberate formatting using indents. 
Found this trying to get it to use bullet points where * is specified in the Summary section at the start of a model. 
Summary comments don't appear to be using markdown rules consistently?

**Comment by hol430** [comment]
The reason for the weird whitespace handling in that function is that the contents of Models.xml are all indented. The current de-indenting implementation is quite dumb - it should keep track of how far it's indented and remove exactly that much whitespace from the start of each line. At the moment, I think it just removes all whitespace from the start of each line(?).

**Comment by jbrider** [comment]
It looks like it's removing any subsequent instances of a space or tab.
Markdown uses multiple spaces for a variety of layout interactions - so the current approach is going to break markdown syntax.
Are the summary comments being translated using markdown similar to the MarkDig that is used for memo's?
I couldn't get bullet points to work from the summary comments at all.
