### ISSUE TITLE
ApsimNG command line

### ISSUE THREAD

**Issue by raphaellinker** [APSIMInitiative/ApsimX#7324]
Is there a way to run ApsimNG in command-line mode? I only found instructions for Apsim but not for ApsimNG
Thanks

**Comment by peter-devoil** [comment]
Try Models.exe in the same directory as ApsimNG.exe

**Comment by raphaellinker** [comment]
That works. Thanks! I see that only the .db file is created. Is there a flag that can be used to generate automatically .csv output files?

**Comment by peter-devoil** [comment]
Not that I'm aware of. You could use the apsimx R package to get the individual tables.

**Comment by hol430** [comment]
Try the `--csv` command-line option, I think it does what you want. For a full list of options, run with `--help`.

```bash
Models.exe --csv myfile.apsimx
Models.exe --help
```

**Comment by raphaellinker** [comment]
That works! Thanks a lot!
