### ISSUE TITLE
Add validation datasets to AgPasture

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#7325]
There are a few datasets for pasture production that can be added to the AgPasture validation set. Three sets were already in the current set, but only for annual total. We do have the values for events and so we can add them as more detailed simulations. Additionally there are a few short term data (approx. two years) from fertiliser trials in two locations in New Zealand. These include single species...

**Comment by par456** [comment]
Was resolved by branch #7290
