### ISSUE TITLE
Auto download of R is broken

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#7329]
On the Windows platform only, if R is required (e.g., for Morris), but is not yet installed, an attempt is made to automatically download and run an R installer. This procedure seems to be broken in several respects:

1. The download procedure is run asynchronously, with APSIM attempting to run R scripts while the download is still occurring.
2. The download retrieves a URL which is intended to re-direct to the latest version of the R installer. However, it appears that WebClient does not do this re-direction itself, so one is left with a file containing the following instead of an installer: `<html><head><META HTTP-EQUIV="Refresh" CONTENT="0; URL=R-4.2.0-win.exe"><body></body>`
3. No feedback is presented to the user. If the installer were actually downloaded, it might take several minutes, so progress ought to be reported.
4. Progress reporting is made difficult because the download procedure lives in Models, not ApsimNG, and it knows nothing about the user interface.

Given these problems, and the fact that auto-installing is only attempted on the Windows platform, I suggest that auto-installation of R be abandoned, and that if R is not installed (on any platform) a message is displayed informing the user that they must install R and providing them a URL or other instructions (possibly platform-specific) on how they can do that installation.

**Comment by hol353** [comment]
Yes I agree. In fact I think we should use Docker for running R so that we can get the R version and library dependencies right and not rely on the user having the correct version of R and libraries. It would require users to have docker installed but nothing else.

The question then is whether we use WSL/Docker and/or Docker Desktop for Windows.
