### ISSUE TITLE
Next Gen new Windows install won't launch

### ISSUE THREAD

**Issue by edvlmaas** [APSIMInitiative/ApsimX#7331]
Hi, I just installed both Apsim Classic (7.10-r4220) and Next Generation (2022.6.2046.0). Classic launches fine, but Next Generation does not launch at all. When I watch in the Task Manager, the process appears for a fraction of a second, then disappears. There is no error message or any activity at all other than what happens in the Task Manager. When I installed it, it needed to install Gtk, which it did, and then I installed the Windows runtime, so both those requirements are met. I'm running Windows 10 Enterprise.

**Comment by hol353** [comment]
Did you install Next Gen 'just for you' or 'for all users'? How did you answer that question the installer asks? Could you try the other option? Please post back here when you try the other option.

**Comment by hol353** [comment]
I just installed a fresh copy of APSIM Next Gen by going through www.apsim.info download form. Worked for me. If it installed ok for you but you can't start the GUI then that probably means there is a problem with GTK or .NET. Have you rebooted since installing GTK and .NET?

**Comment by edvlmaas** [comment]
I had installed it as "all users" and yes, rebooted after the initial installation of everything: APSIM, GTK, and .NET. I do have restricted admin privileges on this computer - had to input the admin user name and password to install it. I uninstalled it and reloaded it "just for me" and it worked! Thanks so much for your help!
