### ISSUE TITLE
PDF documentation available?

### ISSUE THREAD

**Issue by edvlmaas** [APSIMInitiative/ApsimX#7332]
Hi, I prefer a PDF format for software documentation. Is that available for APSIM? Thanks.

**Comment by edvlmaas** [comment]
Thank you for the quick response. While those documents are helpful, none of them starts at the beginning. Where does one start? What does the user interface look like and how does it work? Is it the same as Classic? How do these separate modules and other pieces listed in the Next Gen fit together? What are the minimum necessary inputs provided by the user to run a simulation (vs parameters that have defaults)? My own preference is to have a book that starts at the beginning, explains the system and flow of the processing, then details about what the software needs you to give it as input, what it'll give as output, and how it calculated it. Is that available for either version (I have both)?

**Comment by jbrider** [comment]
This might be of some help.
[APSIM Youtube Channel](https://www.youtube.com/channel/UCawR0E_PzYJcv15oTk-ssjQ/videos)

**Comment by edvlmaas** [comment]
That's a great repository of examples and looks like it will be useful. Videos aren't searchable, though, if I have something I need to look up, so it doesn't really address the underlying need I typically have when I'm going to system documentation. I did see that there is a search field on the website but it appears to search the whole website content, not just the documentation. I am going to consider the binary answer to my question as 'no' and go ahead and close this question. I would just say again that having an actual, fully-searchable manual that starts at the beginning, explains the system and how all the pieces fit together, down to the technical details which a developer like myself would find useful, would be so very helpful. Thank you for your time.
