### ISSUE TITLE
Morris Sensitivity Analysis: How are multiple layer parameter values varied? 

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7333]
Hello, 

For a Morris Sensitivity Analysis in Next Gen, is the value range for a multiple layer parameter applied per layer or is it on a cumulative value across all layers. 

For example, in the image below: will the values of OC per layer be considered between 1 and 10%, or is it the OC over the whole soil profile? 

![image](https://user-images.githubusercontent.com/68366659/172968258-6f156111-d871-4194-ac49-22583e122061.png)

Thank you, 
A

**Comment by hol353** [comment]
The value range is applied per layer. So in your example, 

Field.Soil.Organic.Carbon[1] range 1 to 10

tells the Morris algorithm to try values between 1 and 10 for the organic carbon in the top layer.

**Comment by hut104** [comment]
Morris will only change the value for the layer specified.
________________________________
From: andynen ***@***.***>
Sent: Friday, 10 June 2022 10:51 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Morris Sensitivity Analysis: How are multiple layer parameter values varied? (Issue #7333)


Hello,

For a Morris Sensitivity Analysis in Next Gen, is the value range for a multiple layer parameter applied per layer or is it on a cumulative value across all layers.

For example, in the image below: will the values of OC per layer be considered between 1 and 10%, or is it the OC over the whole soil profile?

[image]<https://user-images.githubusercontent.com/68366659/172968258-6f156111-d871-4194-ac49-22583e122061.png>

Thank you,
A

**Comment by andynen** [comment]
Thank you, that helps a bunch.
