### ISSUE TITLE
Release builds are broken

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#7339]
When a file in examples directory (e.g. Canola Grazing.apsimx) has a space in it's name, Jenkins fails with:

```
rsync: [sender] link_stat "/tmp/ApsimX/Examples/Canola" failed: No such file or directory (2)
rsync: [sender] link_stat "/tmp/ApsimX/Setup/netcoreapp3.1/debian/Grazing.apsimx" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
```

It appears to come from the debian build.

**Comment by hol430** [comment]
Re-opening this, as #7338 was really just a bandaid solution. File names containing whitespace will still break the builds.
