### ISSUE TITLE
Simulating rotations and intercropping in APSIM Next Generation

### ISSUE THREAD

**Issue by ElsaLagerquist** [APSIMInitiative/ApsimX#7348]
Hi,
I simulate a rotation of cereals, which some years also are intercropped with red clover. I have some questions regarding these types of simulations, so I do not miss out on including some module. The simulations runs and it looks like the crops are interacting and that effects from a previous crop is carried over to the next.

Rotation
In the example Rotations there is a specific rotation module used to rotate two different crops. Is it necessary to use this module or can rotations with several crops be done without it? At the moment I do not use it and use "Operations" to specify which crop is to be sown when.

Intercropping
In the simulations I specify that two crops should be sown together (using "Operations"). MicroClimate seems to be important for the two crops to be simulated together, but is there anything else I need to add so that the simulations are preformed correctly? In APSIM Classic one needed to include the Canopy module.

Best regards,
Elsa

**Comment by hol353** [comment]
> In the example Rotations there is a specific rotation module used to rotate two different crops. Is it necessary to use this module or can rotations with several crops be done without it?

You don't need to use any specific rotation component. Using operations is fine.

> MicroClimate seems to be important for the two crops to be simulated together, but is there anything else I need to add so that the simulations are preformed correctly

MicroClimate is necessary. It arbitrates the light interception between canopies. SoilArbitrator is also important. It arbitrates the below ground competition for water and nitrogen. As long as you have both of these in your simulation you should be good.

**Comment by ElsaLagerquist** [comment]
Thank you Dean! Then I can continue as I started.
Best regards,
Elsa
