### ISSUE TITLE
Autocompletion list appears on different monitor

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#7356]
When editing a script - auto-completion list appears on a different monitor (when using 2 monitors).
This was working previously, so a recent change has potentially caused this.
Not using zoom or teams at the time.

**Comment by hut104** [comment]
I've raised an issue about this previously. I've had this for 6 months or more.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jason ***@***.***>
Sent: Sunday, June 26, 2022 11:27:24 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Autocompletion list appears on different monitor (Issue #7356)


When editing a script - auto-completion list appears on a different monitor (when using 2 monitors).
This was working previously, so a recent change has potentially caused this.
Not using zoom or teams at the time.

**Comment by jbrider** [comment]
Closing - see #6447 for existing issue.
