### ISSUE TITLE
Convert APSIM Classic Files To APSIMX file

### ISSUE THREAD

**Issue by smkuhlani** [APSIMInitiative/ApsimX#7365]
Hallo APSIMers,

Is it possible to convert an APSIM Classic file to an APISM X file?
I am just hesitant to invest time recalibrating APSIM X from scratch yet i have done that before.

Thanks

**Comment by jbrider** [comment]
@smkuhlani There is a button on the tool bar labelled _Import old .apsim file_ that will ask for your old file and convert it.
It won't attempt to convert any scripts you have - but they should be imported and the code commented out. If they were written in C#, they shouldn't be too hard to uncomment and edit to get working.

**Comment by hol353** [comment]
This list of models in Next Gen is here: https://apsimnextgeneration.netlify.app/modeldocumentation

Intercropping is included in Next Gen. The Microclimate model arbitrates the competition of light between different canopies and the SoilArbitrator arbitrates the competition of water and nutrients between competing root systems. These two models replace the old canopy model in APSIM 7.10.
