### ISSUE TITLE
can apsimNG model simulate soil organic carbon?

### ISSUE THREAD

**Issue by julianwong82** [APSIMInitiative/ApsimX#7368]
can apsimNG model simulate soil organic carbon? I find  [SOIL].Nutrient.TotalC in APSIMNG model, Is TotalC soil organic carbon? If not where can I find soil organic carbon.
Thanks

**Comment by hol353** [comment]
TotalC is defined in the nutrient model as the sum of the carbon in these nutrient pools:

Inert
SurfaceResidue
FOMLignin
FOMCellulose
FOMCarbohydrate
Microbial
Humic

I hope this helps answer you question.

**Comment by MAGALA-RICHARD** [comment]
> TotalC is defined in the nutrient model as the sum of the carbon in these nutrient pools:
> 
> Inert SurfaceResidue FOMLignin FOMCellulose FOMCarbohydrate Microbial Humic
> 
> I hope this helps answer you question.

I am interested in understanding how to incorporate manure into APSIM Next generation
