### ISSUE TITLE
NG programming questions

### ISSUE THREAD

**Issue by edvlmaas** [APSIMInitiative/ApsimX#7369]
Hi, I am interested in submitting changes to APSIM in the future. I have some questions:
 1) What language is APSIM coded in?
 2) Is there a developer's guide?
 3) Where do I find the source code?
 
I realize that submitting improvements to APSIM requires its own Issue to be submitted with details about the project. I will do so at a later time.

Thanks for your help!
Ellen

**Comment by hol353** [comment]
Hi Ellen, we welcome all changes to APSIM!

1. APSIM is coded in C#
2. There is some documentation here: https://apsimnextgeneration.netlify.app/development/
3. The repository is here: https://github.com/APSIMInitiative/ApsimX

Dean
