### ISSUE TITLE
cover crop model

### ISSUE THREAD

**Issue by edvlmaas** [APSIMInitiative/ApsimX#7370]
I learned in the APSIM training course recently that there is a cover crop model in development. Is there a release date for that module?

**Comment by hol353** [comment]
I'm not aware of a cover crop model under development. If you want a cover crop of a particular type couldn't you just sow that model in APSIM? e.g. if you want a wheat cover crop, just sow the wheat model.

**Comment by edvlmaas** [comment]
I suppose. It just sounded like a thing coming. I don't see many cover crop species in the available models, though. I see oats and red and white clover. What about vetch, other legumes, brassicas? Any idea about those?
