### ISSUE TITLE
problem with save? converter?

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#7376]
Do this:
1.  Check out a clean branch up to date with master
2. open the wheat validation set.  - this should run the converter and simulations should have swcon values on the soilWater node.
3.  save the file.
4.  reopen the file - now the swcon data will have gone missing if you are getting the same issue I did.

**Comment by hol353** [comment]
The defect was in the writing of .apsimx file. Internally the SWCON values were valid i.e. the converter is working correctly.

**Comment by HamishBrownPFR** [comment]
Thanks Dean
