### ISSUE TITLE
Soil LL15 node

### ISSUE THREAD

**Issue by SumanGajurel** [APSIMInitiative/ApsimX#7380]
Hi, 
   I am using APSIM NG 2022.6.7052.0 version. I have an issue while editing the soil LL15. Soil LL15 node doesn't change while I edit it but it works fine with BD, DUL and even with crop LL15.

**Comment by femiguez** [comment]
@SumanGajurel Does this happen when using the GUI? Or was this the same issue that you reported for the apsimx package. If this was related to the apsimx R package, then I think it can be closed here.

**Comment by SumanGajurel** [comment]
@femiguez yes it is to do with apsimx R package, have noted that you have fixed this issue and closing off.
