### ISSUE TITLE
Simulation runs but no report is generated

### ISSUE THREAD

**Issue by iMarang** [APSIMInitiative/ApsimX#7386]
Hi
I've run the attached .apsimx file successfully within the APSIMx GUI but when I've gone to review the output ('Wheat Yield Time Series') it's empty and there are 3 WARNINGs in the status panel.  I've run it multiple times (each finishing after ~ 0.31s)

WARNING: .Simulations.Simulation.Wheat Yield Time Series.Wheat Yield: Selected Data Source 'Report' does not exist in the datastore. Have the simulations been run?

----------------------------------------------
WARNING: .Simulations.Simulation.Wheat Yield Time Series.Wheat Yield: Selected X field name 'Clock.Today' does not exist in the datastore table 'Report'. Have the simulations been run?

----------------------------------------------
WARNING: .Simulations.Simulation.Wheat Yield Time Series.Wheat Yield: Selected Y field name 'Yield' does not exist in the datastore table 'Report'. Have the simulations been run?

My Reporting variables are:
[Clock].Today
[Wheat].Phenology.Zadok.Stage
[Wheat].Phenology.CurrentStageName
[Wheat].AboveGround.Wt
[Wheat].AboveGround.N
[Wheat].Grain.Total.Wt*10 as Yield
[Wheat].Grain.Protein
[Wheat].Grain.Size
[Wheat].Grain.Number
[Wheat].Grain.Total.Wt
[Wheat].Grain.Total.N
[Wheat].Total.Wt

On:
[Wheat].Harvesting

I checked the .db (also attached) and it has no _Report table.

Can you please advise what's wrong with my simulation file?
[Trangie_Gregory_70_2017.zip](https://github.com/APSIMInitiative/ApsimX/files/9138036/Trangie_Gregory_70_2017.zip)

**Comment by hut104** [comment]
This report will be executed when the wheat crop is harvested.  Perhaps check the simulation summary file to see if the crop is being harvested.  If not, there will be no report generated.
________________________________
From: iMarang ***@***.***>
Sent: Tuesday, 19 July 2022 4:22 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Simulation runs but no report is generated (Issue #7386)


Hi
I've run the attached .apsimx file successfully within the APSIMx GUI but when I've gone to review the output ('Wheat Yield Time Series') it's empty and there are 3 WARNINGs in the status panel. I've run it multiple times (each finishing after ~ 0.31s)

WARNING: .Simulations.Simulation.Wheat Yield Time Series.Wheat Yield: Selected Data Source 'Report' does not exist in the datastore. Have the simulations been run?

________________________________

WARNING: .Simulations.Simulation.Wheat Yield Time Series.Wheat Yield: Selected X field name 'Clock.Today' does not exist in the datastore table 'Report'. Have the simulations been run?

________________________________

WARNING: .Simulations.Simulation.Wheat Yield Time Series.Wheat Yield: Selected Y field name 'Yield' does not exist in the datastore table 'Report'. Have the simulations been run?

My Reporting variables are:
[Clock].Today
[Wheat].Phenology.Zadok.Stage
[Wheat].Phenology.CurrentStageName
[Wheat].AboveGround.Wt
[Wheat].AboveGround.N
[Wheat].Grain.Total.Wt*10 as Yield
[Wheat].Grain.Protein
[Wheat].Grain.Size
[Wheat].Grain.Number
[Wheat].Grain.Total.Wt
[Wheat].Grain.Total.N
[Wheat].Total.Wt

On:
[Wheat].Harvesting

I checked the .db (also attached) and it has no _Report table.

Can you please advise what's wrong with my simulation file?
Trangie_Gregory_70_2017.zip<https://github.com/APSIMInitiative/ApsimX/files/9138036/Trangie_Gregory_70_2017.zip>

**Comment by iMarang** [comment]
Thanks for your help.  It appears the NaN in SowingRule1 for 'Minimum extractable soil water for sowing (mm)' and 'Accumulated rainfall required for sowing (mm)' were the problem.  Running through to harvest and reporting successfully
