### ISSUE TITLE
Building fertiliser inputs via Operations

### ISSUE THREAD

**Issue by edvlmaas** [APSIMInitiative/ApsimX#7387]
I am using the Operations module to build management history at a long-term research site and have some questions about how to code several of the treatments that I have. I see a list of types in Fertliser.cs, but I have several that I don't know how to match up or what work-around is recommended:

1) 28 kg/ha of N. It doesn't say what kind of N.
2) 28% UAN. I see there are types for Urea, UreaN, UreaNO3, and NH4N, but nothing that combines all three.
3) 19-19-19. I think this is a solid fertilizer.
4) 19-17-0.  This is a liquid fertilizer.
5) "Ammonium sulfate"
6) 11-0-0-26
7) 12-0-0-26 
8) P2O5
9) 0-0-60 potash
10) 0-46-0 

For each, I have the kg/ha of the total substance, as well as the kg/ha of each element (N,P,K).

Thanks for your help!

**Comment by edvlmaas** [comment]
Think the most important question, actually, is if fertilizer (kg/ha) is entered as the weight of the whole fertilizer, or just the N in the fertilizer? If it's just the N, then my question here is moot because I have the kg N/ha for all of the fertilizers applied. (In which case, why does APSIM want to know what form the N is applied as?)

**Comment by hol353** [comment]
If you specify the fertiliser as NO3N then it is the amount of N in the fertiliser. The other fertiliser types are simply provided as convenience functions. When used, APSIM internally converts the amount to NO3N. Some users like to specify the fertiliser application as urea.

**Comment by edvlmaas** [comment]
I see, so are you saying that regardless of the type of my N fertilizer, I
can just enter it all as NO3N and just supply the N amount?

**Comment by hol353** [comment]
Yes
