### ISSUE TITLE
Unit of initial values on NO3, NH4, Urea are not response after changing

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#7388]
apsimx master branch in the latest version, Windows 10 

Steps to reproduce this error

* Open wheat.apsimx in the validation folder
* Find the node: .Simulations.Validation.NPIField2019.WaggaWagga.WaggaWagga2019Base.Field.Soil.NO3
* Right click the unit of Initial values and change from ppm to kgha.
* The unit is not updated and the values are not changed.
* Switch to another node and come back. The unit is updated but values are still not changed

**Comment by zur003** [comment]
The same problem affects pH (with units water or CaCl2).

**Comment by zur003** [comment]
Also Organic Carbon (Total or Walkley Black).

**Comment by hol353** [comment]
We want to leave the values entered by the user in what ever units they specify i.e. the GUI never converts the units. If the user change the units in the GUI, we don't convert the values. The values only get converted when the simulation starts running. This seems much simpler. The bug, I think, is that the units as shown in the GUI isn't changed when you select a new units from the popup menu.

**Comment by byzheng** [comment]
Thanks @hol353. I still like the feature in APSIM Classic which we could convert the unit and values from interface to help me understanding the values. 

It would be better if we could have an option/checkbox to allow user convert values and units.

* If not checked (in default), just switch units. In case of the wrong units
* If checked, update unit and values.

**Comment by peter-devoil** [comment]
Seconded. If the GUI can't do unit conversion, then a hyperlink to a wiki page on how to do it correctly would be useful.
