### ISSUE TITLE
Update Models.Soils.Soil from version 121 to 153

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#7389]
I have a soil file with version 121 (See attached zip file).

Then I used command to convert to newer version of soil file (version 153)

```
Models.exe soil_121,json /Upgrade
```

After upgrading (attached), there are a few missing modules in the soils which I have to manually add them.

```
[Soil].NO3
[Soil].NH4
[Soil].Urea
[Soil].Temperature
[Soil].SoilNitrogen
```

[data.zip](https://github.com/APSIMInitiative/ApsimX/files/9146446/data.zip)

**Comment by ric394** [comment]
@byzheng Just like issue #7471 these are old versions and you'll need to replace them.
