### ISSUE TITLE
Can soil layers be deleted in the GUI?

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#7392]
This is perhaps a silly question, but once soil layers have been added in the GUI, is there any way to delete them? Some of my attempts to do so resulted in exceptions and application crash.

**Comment by hol353** [comment]
Yes, I noticed this bug yesterday. Ideally, if you select multiple cells and click delete, it should delete the values in those cells (like a spreadsheet).

**Comment by zur003** [comment]
That sort of approach can be tricky, though. How do you know whether the user's intent is to completely delete the layer, or simply to clear the old values to make way for a set of new ones? I wonder if, when presenting soil layers, it might be good to add a context menu item to specifically allow for deletion of the layer.

I should also note that currently, if the user deletes the contents of a "Depth" cell or puts in something not of the form 100-300, the GUI eventually crashes after tossing exceptions around..

**Comment by hol353** [comment]
I guess the idea is to look at the depth column and only rows in the grid where there is a valid depth specified. I don't really like the idea of a context menu. I'd rather just make the code more tolerant. Yes it can be tricky.

**Comment by hol353** [comment]
The soil grid needs a bit of work to make it more excel like. 

- Multiple cells can't be selected using mouse.
- The DELETE key does nothing.

**Comment by Jatinderbai** [comment]
In the earlier version of 2021, it was really easy to create and delete soil layers , so the improvement was not needed in this section , kindly make it flexible to use, whole model is flexible to use, then why not soil file

**Comment by hol353** [comment]
You can now delete cells and whole layers without crashes (hopefully). Select a block of cells and click delete.
