### ISSUE TITLE
Potential bug: SoilWat XF (root exploration factor)

### ISSUE THREAD

**Issue by enviroeye** [APSIMInitiative/ApsimX#7399]
Hi there.

We’re using the root exploration factor (XF) to reflect the rooting depth of the crop (sugarcane) and the consequently crop based PAWC.

Depth breaks in our input soil data do not always align exactly with the crop rooting depth. So for example we may have a depth range of 900mm to 1200mm, with an associated crop rooting depth of 1000m.

To ensure we calculate the correct _crop based_ PAWC we have been adjusting the XF factor to reflect rooting depth. 

In the example above, we set the XF for the 900mm to 1200mm depth to 0.33 indicating roots are only present in the first one-third of the range (i.e. 900mm to 1000mm), expecting the crop PAWC to adjust and reflect this.

However it seems the model only considers XF as being 0 or 1 and ignores fractional components. In the attache screenshots from APSIMX (version 2022.7.7064.0 - latest), having XF at 1 or 0.33 yields the same crop based PAWC under crop specific physical properties under soil physical properties.

<img width="426" alt="XF_At_033" src="https://user-images.githubusercontent.com/16280541/180890472-742e3900-3264-4e22-8007-0eadcf0e2463.png">
<img width="441" alt="XF_at_1" src="https://user-images.githubusercontent.com/16280541/180890762-a3ab5773-c8dd-4678-8f71-569b2c0331f7.png">

XF at 0 for comparison

<img width="426" alt="XF_at_0" src="https://user-images.githubusercontent.com/16280541/180890478-9bfae0de-2f5c-4a63-8009-ea43cc006056.png">

Is this by design or a bug in the code?

Our modelling is primarily focused on tracking soil water deficits. Therefore having an accurate quantification of crop based PAWC, inclusive of rooting depth is important. If we’re approaching this all wrong, please let me know.

Mark

**Comment by peter-devoil** [comment]
XF controls the rate of root advance; if you want to limit pawc then trim LL

**Comment by hol353** [comment]
To example on @peter-devoil comment: your understanding of XF isn't quite right. A value of 0.33 means the roots will advance through that layer at a third of the rate they would normally. The roots still have access to the water in that layer though, hence why it is still included in the calculation of PAWC. A value of zero means the roots can't enter that layer.
