### ISSUE TITLE
Do crop models (xml files) compile into Model.exe?

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#74]
Steps to reproduce my problem:

1. Run my test `phenology.apsimx` in command line `Model.exe phenology.apsimx`. 
2. Edit `WheatPMFPrototype.xml` file to change parameter value `Target` of `FloralInitiationFloweringPhase'.
3. Run `phenology.apsimx` again.
4. Check results of two runs, and I get the same answer.
5. I get different answer in I repeat the steps in the debug mode using VS.

It looks the `WheatPMFPrototype.xml` in the `Model\Resources` is compiled into `Model.exe`. 

Is it true?

**Comment by hol353** [comment]
Yes the .xml files are compiled into the resources of Model.exe. If you change the .xml you'll have to recompile.

Alternatively, you can put the contents of the .xml into the .apsimx file directly. The example here does this:
Tests\SugarCane\Example\SugarCane.apsimx

**Comment by byzheng** [comment]
Hi Dean,

Thanks for your clarification and suggestion. I believe there is a good reason to design like this. 

From a model developer point view, it will be better to let `Model.exe` to reload `.xml` files. During model development, we could set up multiple test simulations and frequently modified the model `.xml` file. It will be really convenient to directly run all test `apsimx` files through command line tool `Model.exe`. 

Cheers,
Bangyou

**Comment by hol353** [comment]
No need for Model.exe to reload the .xml files. Instead put the contents of .xml file directly in the .apsimx file and you can change it all you like without having to recompile anything. It won't even read the one in the resources. When we get an IDE back for PMF it'll become obvious.
