### ISSUE TITLE
Viewing experiment outputs with large output database

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7402]
Is it possible to access an individual simulation output/graph from a multi-sim experiment in a report view or graph view? Often, in an experiment setup, I need to check a particular outcome, but the report viewer or graphs only support "current" which doesn't exist. Could the checkpoint drop down with "current" also include all simulations in the output file when an experiment is present?

I have generated a 300 MB db file. Whenever I click on the datastore, to view or empty the database, the UI hangs with spinning icon and never displays anything. Is this because it's trying to load all the tables, or another issue? I'd suggest it isn't loading data as it persists for >15 minutes. Given it's an experiment there isn't anything to display, given the issue above.

**Comment by hol353** [comment]
> Is it possible to access an individual simulation output/graph from a multi-sim experiment in a report view or graph view?

Not sure what you mean by this. On the graphs you can click on simulations / factors in the legend to turn them on/off. You can also filter graphs to only show particular simulations.

> Whenever I click on the datastore, to view or empty the database, the UI hangs 

This sounds like a bug that needs fixing. 300Mb db file isn't that large and should work ok in GUI.

**Comment by lie112** [comment]
If graphs or reports are provided in the simulation model managed by an experiment, they cannot be viewed after an experiment based run. Only graphs provided under the experiment (outside simulation) allow the simulations to be plotted.
It would be nice to explore the results of individual simulations from the reports and graphs of the simulation model.

**Comment by zur003** [comment]
I suspect the problem you saw with the UI "hanging" was resolved with #7420.
