### ISSUE TITLE
soil temperature calibration

### ISSUE THREAD

**Issue by edvlmaas** [APSIMInitiative/ApsimX#7403]
I have a scenario where the APSIM upper layer soil temp is consistently about 7 deg C higher than observations. I will say that the upper layer is 20 cm in APSIM and the observations were taken at 10 cm. Given this, if anything I would expect APSIM to be cooler, but I'm expecting that 10 cm should actually be a good average for the 0-20cm depth. However, I am not sure what all in my simulation I can change that will bring the soil temperature down. I haven't found any APSIMX documentation related to it. I looked in SoilTemperature.cs and, based on SurfaceTemperatureInit() and DampingDepth(), the air temperature, water balance, solar radiation, and bulk density are the main factors I gleaned from them. I have already calibrated the soil water to a very acceptable fit, so I'm not sure where else to go. Should I look at surface residue? What else?
Thanks.

**Comment by hut104** [comment]
Check values for Tav and Amp

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: edvlmaas ***@***.***>
Sent: Thursday, July 28, 2022 6:11:25 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] soil temperature calibration (Issue #7403)


I have a scenario where the APSIM upper layer soil temp is consistently about 7 deg C higher than observations. I will say that the upper layer is 20 cm in APSIM and the observations were taken at 10 cm. Given this, if anything I would expect APSIM to be cooler, but I'm expecting that 10 cm should actually be a good average for the 0-20cm depth. However, I am not sure what all in my simulation I can change that will bring the soil temperature down. I haven't found any APSIMX documentation related to it. I looked in SoilTemperature.cs and based on SurfaceTemperatureInit() and DampingDepth() it looks like air temperature, water balance, solar radiation, and bulk density are the main factors I gleaned from them. I have already calibrated the soil water to a very acceptable fit, so I'm not sure where else to go. Should I look at surface residue? What else?
Thanks.

**Comment by edvlmaas** [comment]
I'm not including those in the weather files I'm importing, so I assume that means APSIM is calculating them for me from the data I give it?

**Comment by edvlmaas** [comment]
There appears to be a problem with the soil temperature function in APSIM. Sotirios Archontoulis will check with Neil.
