### ISSUE TITLE
Soil Temperature initialisation 

### ISSUE THREAD

**Issue by hedycau** [APSIMInitiative/ApsimX#7417]
cannot initialise soil temp module

**Comment by sno036** [comment]
Suggest adding this as an optional input (overriding the tav/amp estimate) on the UI. Also implement so that the current array of temperatures can be reset from a manager or operations at any point during the simulation.

**Comment by peter-devoil** [comment]
Yes please. This was missing from classic.

**Comment by sno036** [comment]
I've added this to the SoilTemp wish list and when more work (not currently funded/planned) is done it will be considered.
