### ISSUE TITLE
Bug: Months disappearing in RainfallChart

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7424]
Hello, 

When visualizing the rainfall distribution under the Rainfall Chart window of the Weather node, months appear only in the first year, and then disappear in subsequent years. 

Below is the chart for the first year: 
![image](https://user-images.githubusercontent.com/68366659/182976707-04786a77-5c4b-4539-b230-9cf0b934b7f2.png)

The chart for the second year. The months are no more displayed when returning to the first year. 
![image](https://user-images.githubusercontent.com/68366659/182976754-3b9e749c-25c6-4d95-b272-9eac41aa6d9a.png)

**Comment by zur003** [comment]
Whoever takes this on might also increase the size for the control for setting the start year. I'm currently seeing only 3 digits of a 4 digit year.

**Comment by zur003** [comment]
Also note that text providing the rainfall total for multiple years is misleading, as it's the total for the range of years, not just the starting year.

![image](https://user-images.githubusercontent.com/11879340/182982132-43792408-963f-414d-a8f7-61d113962701.png)
