### ISSUE TITLE
Chemical Node is empty when pasting the Soil module under the parent Simulation

### ISSUE THREAD

**Issue by andynen** [APSIMInitiative/ApsimX#7425]
Hello,

I am trying to create a soil toolbox! 

First, in a saved APSIM example simulation file, when I copy and paste the Soil module in the parent "Simulations", I get the following error 
![image](https://user-images.githubusercontent.com/68366659/182981164-ee0addca-6273-4a1b-b947-e559b4f7ab21.png)

It is only after closing and reopening the file that the Soil module appears. However, the Chemical node is empty. 
![image](https://user-images.githubusercontent.com/68366659/182981315-df8596d3-9a1d-4221-85e4-f3ffc8b62590.png)

A copy of the simulation file is attached. 
[APSIM_test.zip](https://github.com/APSIMInitiative/ApsimX/files/9264447/APSIM_test.zip)

Thank you,

**Comment by MarkLieffering** [comment]
@andynen - I have that exact same problem - I am trying to copy a soil from one simulation to another and get the same as you. As you said, the copied soil only shows up in the tree when you save, close and re-open - but with missing values in "Chemical". Even deleting the errant "Chemical" node and pasting one that has values (from another simulation) causes the values to disappear upon pasting. I have struck copying and pasting issues before which seem to fix themselves when you click away but this is not one of them. I am using the LAG (latest and greatest) version. @hol353 any ideas? I have added "bug" and "interface" labels to this

**Comment by MarkLieffering** [comment]
Further to this - when in the "Soil" node, if you use "Add Model", "Soils", "Chemical" the new "Chemical" node is empty (except for the words "Parameters" and "Layered variables") - nothing can be entered

**Comment by codeandkey** [comment]
I am running into this issue too. Copying any soil results in duplicate children `NO3`, `NH4`, `Urea`, and `Water`, which have to be manually removed from the .apsimx file before the sim will run.

**Comment by MarkLieffering** [comment]
Thanks @hol353 for fixing this. Just to note that the issue of "Further to this - when in the "Soil" node, if you use "Add Model", "Soils", "Chemical" the new "Chemical" node is empty (except for the words "Parameters" and "Layered variables") - nothing can be entered" is still happening - though I must admit I am not sure what it is supposed to look like as I have never had to add a Chemical node. I would have expected a grid that can be filled in?
