### ISSUE TITLE
Setting parameters values

### ISSUE THREAD

**Issue by VicB18** [APSIMInitiative/ApsimX#7434]
Hello,
I need to set programmatically values for the soil and other models. For some of them I found a way to set values, such as `Chemical` and `Firtiliser`, but for others I cannot find. For example, I cannot set a value to `Physical.ParticleSizeClay`. I tried different variations of the function `SetValue` and indexing.
![kuva](https://user-images.githubusercontent.com/47314151/183648905-82a1d6d5-09f7-4eb0-8b63-473979438444.png)

`InitialN` is not recognized at all.

![kuva](https://user-images.githubusercontent.com/47314151/183648938-f94f52f8-4892-4197-84dc-72d5803d124c.png)

Can you please direct me to an example showing how to do it or description of the models with their features?
In C# the setting for `Physical.ParticleSizeClay` is simple, but in a script it doesn't work.
![kuva](https://user-images.githubusercontent.com/47314151/183648805-f6df44c2-ab55-44a7-a4e5-78945e0db4ac.png)

Thank you

**Comment by lie112** [comment]
As the error states, there is no expected ; character after the InitialN statement in your second error. Every statement/line in c# must end with a ;
Doesn't the clay size set like the PH of the previous line? Physical.ParticleSizeCley[1] = 1;
I may be wrong as I am not working with these models, and someone else will provide the solution.

**Comment by VicB18** [comment]
Thank you, lie112.
I checked this combination `Physical.ParticleSizeClay[1]=20;` either.
This works.
![kuva](https://user-images.githubusercontent.com/47314151/183863492-a71916bb-b36a-449a-b93d-fe749f3c9e33.png)

This doesn't work.
![kuva](https://user-images.githubusercontent.com/47314151/183863130-b3d4784d-b79f-49b5-a277-0e12e744b492.png)


The `InitialN` is not recognized in any case.
![kuva](https://user-images.githubusercontent.com/47314151/183863901-6c12eb5c-fa54-4dd5-b491-d368d4fb7e3b.png)

**Comment by hol353** [comment]
```Physical.ParticleSizeClay[1]=20``` should work.

For initial N you will need a link up the top:
```
[Link(ByName=true)] Solute NO3;
```

and then you can do:
```
NO3.InitialValues = new double[] { 1, 1, 1, 1, 1, 1};
NO3.InitialValuesUnits = Solute.UnitsEnum.kgha
```

The initial values supplied to NO3 need to be an array (1 value per layer).

If you can't get this working, can you zip and attach your .apsimx file and I'll have a look.

**Comment by VicB18** [comment]
Hello Dean, thank you for the help.

I still have questions, should I continue to write in the issue?

I found the problem with the Physical.ParticleSizeClay.
I run the simulation from C# and it stopped on an error inside the script.
***@***.***
I looked at the Physical variable and saw that ParticleSizeClay is null, while other parameters, like BD are arrays.
Probably, this is the reason that a value cannot be assigned. But this is according to (Chichota 2021 A protocol to build soil descriptions for APSIM simulations), where it is written in the chapter Particle size distribution on page 9 that "These values are currently only used directly by APSIM's SoilTemperature model, but it is recommended to record them whenever possible."
Physical.BD[1]=1; works well and I can see it in the report according to [Soil].Physical.BD.

InitialN
I did not understand what you suggested to do to initialize N. Did I make it correctly?

  1.  When I added to the both simulations W1.apsinx and W2.apsimx
[Link(ByName=true)] Solute NO3;
and then
NO3.InitialValues = new double[] { 1, 1, 1, 1, 1, 1};
NO3.InitialValuesUnits = Solute.UnitsEnum.kgha;
the compiler gave an error
Errors found in manager model Manager
APSIM2c2ee23b-299c-4ef4-991d-83b4c0176337.cs(15,29): error CS0246: The type or namespace name 'Solute' could not be found (are you missing a using directive or an assembly reference?)
APSIM2c2ee23b-299c-4ef4-991d-83b4c0176337.cs(22,29): error CS0103: The name 'Solute' does not exist in the current context
but succeeded to run the simulation.

  1.  To see the effect of it, I added to the Report [Soil].InitialN.NO3. After the running, there was an error
Error in report Report: Invalid report variables found:
Soil.InitialN.NO3: While locating model .InitialN.NO3: InitialN is not a child of Soil
When I added [InitialN].NO3, the error was
Error in report Report: Invalid report variables found:
InitialN.NO3: Unable to find any model with name or type InitialN in scope of Report

Additional question.
I wrote this script in a .cs file located in the Models folder. I want to put a breakpoint inside the script to debug. But when I compile Apsim in C# and run a simulation, it doesn't enter the script and doesn't stop on the breakpoints. Do I have to do something additional?

Thank you
Victor

**Comment by lie112** [comment]
A quick google search for your error "The type or namespace name  could not be found (are you missing a using directive or an assembly reference?)" will show you this is a C# code error. Your code doesn't know about "Solutes" and so you have to tell the manager script to include the different namespace. This is performed by the "using" statements at the top of your manager script code. A quick look at APSIM code shows Solutes is in the Models.Soils namespace so add
using Models.Soils;
to the top of your code.

Given you have found that ParticleSizeClay is null, this means it has never been initialised and so isn't an array yet and thus you cannot access each index within the array such as  Physical.ParticleSizeClay[0] = 20. I'm not sure why it hasn't been set

To initialise the ParticleSizeClay so you can use it, you will need to use the same code style as 
NO3.InitialValues = new double[] { 1, 1, 1, 1, 1, 1};

Physical.ParticleSizeClay = new double[] { 1, 20, 1, 1, 1, 1};
This will set the particle size clay array. you will need as many values as you have layers.

I'm not sure if this will work as you may have missed some other setup methods, but this will fix the code errors.
I'd suggest having a look at some c# coding websites to understand this situation. This will improve your ability to build and debug your manager scripts in future.
