### ISSUE TITLE
Silent Install of ApSim NextGen

### ISSUE THREAD

**Issue by ditchorama** [APSIMInitiative/ApsimX#7436]
I am unable to get ApSim to install silently, it always prompts that the GTK isn't detected even though it's installed.
Installing use the following :

gtk3-runtime-3.24.31-2022-01-04-ts-win64.exe /S
windowsdesktop-runtime-3.1.14-win-x64.exe /INSTALL /QUIET /NORESTART
apsim-7066.exe /VERYSILENT /SUPPRESSMSGBOXES

Any suggestions would be greatly accepted

Cheers

**Comment by hol353** [comment]
The installers mechanism for determining whether GTK is installed is quite crude. It looks for the presence of a directory called:

C:\Users\<windowsusername>\AppData\Local\Gtk\3.24.24

where <windowsusername> is the user name of your windows login. If you create this directory (and leave it empty), the installer should be happy.

**Comment by ditchorama** [comment]
thanks for that, was assuming it would be registry related
we install software using the system account which doesn't have a profile under the c:\users folder structure but under C:\Windows\System32\config\systemprofile.
will have to test this out - many thanks Hol
