### ISSUE TITLE
How to use APSIM to model Soil Carbon as an output

### ISSUE THREAD

**Issue by SasankhM** [APSIMInitiative/ApsimX#7440]
Hi, I am new to using APSIM and would like some guidance on how I can use it for modeling Soil Carbon as an output (rather than as an input to track yield).

Thanks!

**Comment by MarkLieffering** [comment]
For on a daily report set your reporting frequency to Clock].EndOfDay and to output total soil C (for the whole profile) use: 

Sum([Soil].Nutrient.TotalC)

Leave out the "Sum" if you want C for the individual layers

If for example you wanted to output annual changes in soil C set the reporting frequency to a specific day (what ever you want to use as the end of the year e.g. 30-jun) and use:

Diff of Sum([Soil].Nutrient.TotalC) from [Clock].StartOfSimulation to [Clock].Today as AnnualChangeInSoilC

Hope that helps

**Comment by SasankhM** [comment]
@MarkLieffering thanks! What is the difference between [Soil].Nutrient.TotalC and [Soil].Organic.Carbon? One seems to be decreasing and the other seems to be constant in my simulation- shouldn't they stay them?

**Comment by MarkLieffering** [comment]
@SasankhM the term [Soil].Organic.Carbon is the concentration of C in the various soil layers (if you use the intellisense it says "Carbon concentration" - no units but I presume %) at the start of the simulation. Cheers

**Comment by SasankhM** [comment]
Thanks for the update @MarkLieffering. I am confused as to how if the concentration stays the same, how does the TotalC change?

**Comment by MarkLieffering** [comment]
@SasankhM it is only the concentration at the start of the simulation - TotalC is is dynamic and responds to the various inputs and losses during the simulation. See https://builds.apsim.info/api/nextgen/docs/Nutrient.pdf and https://www.apsim.info/documentation/model-documentation/soil-modules-documentation/soiln/

**Comment by SasankhM** [comment]
Got it thanks @MarkLieffering. So to clarify the concentration only represents values at the start of the simulation and will not change/update?

**Comment by MarkLieffering** [comment]
@SasankhM correct
