### ISSUE TITLE
Copying and pasting a crop model to Replacements doesn't show any children

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#7444]
Probably related to #7443 

Editing the crop resources (json) file and manually copying and pasting the json into the Replacements shows the whole model structure.

**Comment by femiguez** [comment]
I'm having the same problem. I also noted that cultivar parameters used to be under "Command" in the JSON file, but now there is a duplication called "Lines" and "Command" seems to be effectively ignored. I'm not sure if this was intentional, but it is strange.

**Comment by hol353** [comment]
> Editing the crop resources (json) file and manually copying and pasting the json into the Replacements shows the whole model structure.

Isn't this what is supposed to happen? You want the full model to be shown in Replacements.

> I also noted that cultivar parameters used to be under "Command" in the JSON file, but now there is a duplication called "Lines" and "Command" 

Yes this is a bug I'll fix now.
