### ISSUE TITLE
JS version of Soils.xml?

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#7447]
Has anybody converted the old xml formatted apssoil database to json/apsimx, and has a link handy? TIA

**Comment by hol353** [comment]
Not that I know of. Next gen command line (Models.exe) has an upgrade switch that might do the job.

**Comment by rcichota** [comment]
I have done in the past, I coded in C# (to convert and also add plant params). More recently I simply used APSIM, it worked fine. To convert a library file, I first had to 'convert' it into a simulation (in classic), then I opened it in NextGen and all soil info was re-formatted appropriately...

**Comment by her123** [comment]
Any soil xml will now import into NextGen without needing to be in a simulation.
