### ISSUE TITLE
Soils Interface Issues

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#7454]
I found these issues while looking for a simple example of a variety of locations for the sorghum release.
I found a couple in Chickpea for Katherine and Launceston which seemed like a good place to start.
Both locations use the same derived sandy soil that appears worse than the sandy soils in WA.

**Physical Node within a soil**

- Poor error message when you are missing a crop node underneath the Physical node.
- Needs a specific syntax that is not mentioned in the error or the help file
- Where is the help for Soils?
- Copying from another soil with a different layer structure caused corruption and errors that were difficult to recover from.
- Classic had a button called _Manage crops_ the functionality of which does not appear to be replicated in Nextgen.
- The graph is not resizable - no matter how big your monitor is.
- Is there a way to show the Crop specific lines on the graph? No graphs are shown on the Crop specific nodes below Physical.
- The table shows columns for Sand, Silt, Clay and Rocks (90% of the time I imagine these are empty?) in the left of the table - the mot prominent position for viewing shows nothing most of the time.
- Also 90% of the time, the simulation will contain a single crop and soil - would it be difficult to show the details for the current crop type on the left instead of empty columns? It would be a good place for an error message before trying to run the model as well.

**Download a soil**

- Assuming you know there is somewhere you can download a soil file, it takes a while to find that you have to right click the Soil node and click Download Soil.
- Like most Select boxes (combo box) in Nextgen, the drop down list takes up most of the screen height if the list has a long list of items in it.
- If you scroll towards the top - it will scroll well past the first item to show empty space scrolling down the screen.
- Searching for a soil has resulted in the following error both times I searched:

```
Error resolving type specified in JSON 'Models.Soils.InitialWater, Models'. Path 'Children[0].$type', line 25, position 50. --> Could not find type 'Models.Soils.InitialWater' in assembly 'Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

- Clicking the Add selected soil to simulation button will add a new soil **inside** of the soil you had just right clicked.
- Copying the new child soil and attempting to paste it in the Field above will result in the following error:

```
Duplicate models found: ~paddock.Synthetic Soil Derived from ISRIC SoilGrids has 2 children named Water
```
- It didn't create a newly pasted soil. (Apparently it did create it, but you have to go to another tab and come back again to see it. When you try to copy that node and paste it - it will now say there are 3 Water nodes).
- The source soil doesn't appear to have 2 Water nodes.
- Doing a check soil on the child soil node (the one inside the original - nothing appears to have been pasted) will show ```No starting water values found```  - Nothing about multiple Water nodes.
- Is No starting water values a critical issue? I checked other soils and I got quite a few missing initial warnings - but no interpretation of what that means other than it is in red text.
- Doing a Soil check on the Parent soil produced a long list of errors saying ``` Crop LL in layer 'n' is below air dry ```
- I think what is happening is that it is comparing the Physical node of the parent with the children of the physical inside the Soil that ended up as a child.
- What it does not say is that it looks like you have a soil as a child inside your parent soil. 

I haven't recreated this on another machine, but I have verified similar behaviour across multiple files.
Manually editing the file finds that it had made copies of the Water, NO3, NH4 and Urea nodes.

**Soil Specific**

After removing them, I am getting a strange graph that doesn't show the entire profile - just the top 1400mm.
![image](https://user-images.githubusercontent.com/635772/185791018-bf3b2509-133e-4396-8446-4601a3ad94b4.png)
This is shown more dramatically in the slightly wider graph within the Water node:
![image](https://user-images.githubusercontent.com/635772/185790934-03b4eb57-9783-466d-9fc5-c7177458f482.png)
I see the read only (calculated?) SW field is set to 0 in the bottom 3 layers - but not sure what is causing them to affect DUL but not Airdry - hopefully it is a visual thing only?
Where they start is also odd - around the 250mm point. Other graphs are displaying from the end of the first layer which would be 150mm?

**Comment by jbrider** [comment]
It looks like the error pasting has nothing to do with the soil downloading.
See:  #7425

**Comment by Chloe0317** [comment]
I ran into the same error code when trying to download a soil in one simulation 
``` 
Error resolving type specified in JSON 'Models.Soils.InitialWater, Models'. Path 'Children[0].$type', line 25, position 50. --> Could not find type 'Models.Soils.InitialWater' in assembly 'Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```
Then in another simulation, an error about not able to download SLGA synthetic soil appeared as 
```
Cannot get data from https://www.asris.csiro.au/ASRISApi/api/APSIM/getApsoil?longitude=150&latitude=-31.52
```
Though this error seems to be transient and when I tried to replicate it, it reverted to the first error. 
It seems that the option to download the SLGA synthetic soils in Next Gen is disabled.  I would assume based on the data sources it may be more accurate than ISRIC soils for Australia @hol353 what might be the reason for not including it please? 
Thanks heaps!

**Comment by hol353** [comment]
Yes there seems to be several defects dealing with downloading / editing soils. SLGA would be better than ISRIC for Australia. APSoil is probably better than SLGA though depending on what you're trying to do.

**Comment by hol353** [comment]
@her123 Can you look at the 'Download a soil' issues?

**Comment by her123** [comment]
@hol353 can you check the changes I made in the pull request. The remaining part of this issue may be for your attention.
