### ISSUE TITLE
How to include effects of management practices (e.g. cover crops, tillage, crop rotation) in APSIM?

### ISSUE THREAD

**Issue by SasankhM** [APSIMInitiative/ApsimX#7461]
I am trying to study the effect of various management practices on SoilC using APSIM. I am confused as to where to enter information on cover crop, tillage and crop rotation? Also, APSIM requires the initial residue pool - how do we obtain that?

**Comment by SasankhM** [comment]
@MarkLieffering  would you be able to chime in?

**Comment by MarkLieffering** [comment]
Have you looked at the various examples? For example, there is one called Rotation which might be useful.

**Comment by MAGALA-RICHARD** [comment]
Hello, Please, for tillage, look at this https://doi.org/10.1016/j.fcr.2021.108344  paper. Although there is still a lot to be done on conservation tillage.

**Comment by MAGALA-RICHARD** [comment]
It is straightforward for the cover crop; just plant them in the same paddock. The start and end date will determine whether it is a cover crop, but at some time, you may need to write a termination script to ensure they don't overlap with the principle crop when replanting in the preceding year. Please let me know if you ned help on the termination script

**Comment by soilmodel12** [comment]
@MAGALA-RICHARD thanks for chiming in! How about residue retention? Is it under the tillage component? Is there a way to do no-till and residue retention? And is the default in APSIM no till?

**Comment by soilmodel12** [comment]
@MAGALA-RICHARD can you share the termination script?

**Comment by JJguri** [comment]
@soilmodel12 and @MAGALA-RICHARD please have a look to [this](https://github.com/APSIMInitiative/APSIMClassic/issues/2216) and [this](https://github.com/APSIMInitiative/ApsimX/issues/6614) thread
