### ISSUE TITLE
ReflectionUtilities.Clone() fails with "SerializationException: Unable to find assembly" when using non-default AssemblyLoadContext

### ISSUE THREAD

**Issue by tom93** [APSIMInitiative/ApsimX#7464]
### Summary

When ApsimX's ReflectionUtilities.Clone() method is called on an instance of a type that belongs to an assembly that was not loaded in the default AssemblyLoadContext, it fails with `SerializationException: Unable to find assembly '...'.`

(Another possibility is that the assembly will also be found in the default load context, and Clone() will succeed, but then there will be an InvalidCastException when the caller of Clone() tries to cast the result.)

A fix is proposed in #7465.

### Background and analysis

ApsimX's [ReflectionUtilities.Clone()](https://github.com/APSIMInitiative/ApsimX/blob/265679cee30b0355e222f6a5832272ecc16f98da/APSIM.Shared/Utilities/ReflectionUtilities.cs#L544) method is implemented by serializing and deserializing using .NET's [BinaryFormatter](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter).
When BinaryFormatter performs deserialization, it needs to be able to load assemblies.
.NET Core has something called "AssemblyLoadContext" ([documentation](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext)), which allows assemblies to be loaded in isolated contexts (e.g. in order to load multiple versions of an assembly).
By default, BinaryFormatter.Deserialize loads assemblies using [Assembly.Load(AssemblyName)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.load#system-reflection-assembly-load(system-reflection-assemblyname)) (source code references: [[1]](https://github.com/dotnet/runtime/blob/v6.0.7/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryObjectReader.cs#L1109), [[2]](https://github.com/dotnet/runtime/blob/v6.0.7/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/FormatterServices.cs#L319)). In the context of BinaryFormatter, this uses the [default AssemblyLoadContext](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.default).
If the type that is being cloned belongs to an assembly from the default context, this works fine.
But if the type belongs to an assembly from a *different* context, this is problematic: the assembly might not be found in the default context, and if it *is* found it may later [cause an InvalidCastException](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext#type-conversion-issues) (because loading the assembly in the default context results in a new Assembly instance and its types are distinct).

One situation where non-default contexts arise is when writing a COM (Component Object Model) server.
.NET Core loads the COM server in an isolated AssemblyLoadContext (reference: [COM hosting design doc](https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md#loading-managed-code) and [notes in the .NET Core COM server docs](https://docs.microsoft.com/en-us/dotnet/core/native-interop/expose-components-to-com#additional-notes)).
The dependencies of the COM server (e.g. Models.dll) are automatically loaded in this isolated context when the COM server starts.
So if the COM server creates a Simulation instance that is later passed to Clone(), the call will fail:
If Models.dll is not found in the default context, there will be a SerializationException "Unable to find assembly 'Models ...'."
If Models.dll *is* found, there will be an InvalidCastException when the caller of Clone() tries to cast the result to Simulation, because the result's type will be from a different Assembly instance.

#### Example 1 (minimal, contrived)

This is a minimal (but contrived) example that manually loads an assembly in a non-default AssemblyLoadContext and calls Clone() on an instance of a type from that assembly.

1.  Create a class library project "DemoLibrary":

    ```
    dotnet new classlib -f netcoreapp3.1 -o DemoLibrary
    ```

    Create a file "DemoSimulation.cs" in this project with the following contents:

    ```c#
    using System;

    namespace DemoLibrary
    {
        [Serializable]
        public class DemoSimulation
        {
        }
    }
    ```

    Run `dotnet build` in this project (this generates bin\Debug\netcoreapp3.1\DemoLibrary.dll).

2.  Create a console application project "DemoApp" that loads the library and calls Clone():

    ```
    dotnet new console -f netcoreapp3.1 -o DemoApp
    cd DemoApp
    dotnet add reference ...\ApsimX\APSIM.Shared\APSIM.Shared.csproj # replace "..." with the actual path
    ```

    Modify Program.cs to have the following contents:

    ```c#
    using APSIM.Shared.Utilities;
    using System;
    using System.IO;
    using System.Reflection;
    using System.Runtime.Loader;

    namespace DemoApp
    {
        class DummyAssemblyLoadContext : AssemblyLoadContext
        {
        }

        class Program
        {
            static void Main(string[] args)
            {
                AssemblyLoadContext assemblyLoadContext = new DummyAssemblyLoadContext();
                Assembly demoLibrary = assemblyLoadContext.LoadFromAssemblyPath(Directory.GetCurrentDirectory() + @"\..\DemoLibrary\bin\Debug\netcoreapp3.1\DemoLibrary.dll");
                Type demoSimulationClass = demoLibrary.GetType("DemoLibrary.DemoSimulation", throwOnError: true);
                object sim = Activator.CreateInstance(demoSimulationClass); // dynamic equivalent of "DemoSimulation sim = new DemoSimulation();"
                object clone = ReflectionUtilities.Clone(sim); // fails with "SerializationException: Unable to find assembly 'DemoLibrary, ...'."
                Console.WriteLine("Clone() succeeded. IsInstance: {0}", demoSimulationClass.IsInstanceOfType(clone));
            }
        }
    }
    ```

    Run using `dotnet run`.

Output (on ApsimX at commit 4cc851718f8b):

```
Unhandled exception. System.Runtime.Serialization.SerializationException: Unable to find assembly 'DemoLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at APSIM.Shared.Utilities.ReflectionUtilities.BinaryDeserialise(Stream stream) in C:\Users\User\ApsimX\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 344
   at APSIM.Shared.Utilities.ReflectionUtilities.Clone(Object sourceObj) in C:\Users\User\ApsimX\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 551
   at DemoApp.Program.Main(String[] args) in C:\Users\User\DemoApp\Program.cs:line 21
```

(If a reference to DemoLibrary is added to DemoApp, Clone() will succeed and the output will be `Clone() succeeded. IsInstance: false`.)

#### Example 2: COM Server

This is a larger example that uses a COM (Component Object Model) server. It is the real-life use case that led to the discovery of the issue.

1.  Download the repository [dotnet/samples](https://github.com/dotnet/samples) to get the COM Server Demo ([documentation](https://docs.microsoft.com/en-us/dotnet/core/native-interop/expose-components-to-com), [source subdirectory](https://github.com/dotnet/samples/tree/main/core/extensions/COMServerDemo)).

2.  Modify the COMServer project to use ApsimX:

    ```
    cd samples\core\extensions\COMServerDemo\COMServer
    dotnet add reference ...\ApsimX\Models\Models.csproj # replace "..." with the actual path
    ```

    Modify Server.cs to have the following contents:

    ```c#
    using Models.Core;
    using Models.Core.Run;
    using System;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;

    namespace COMServer
    {
        [ComVisible(true)]
        [Guid(ContractGuids.ServerClass)]
        public class Server : IServer
        {
            double IServer.ComputePi()
            {
                Simulations sims = Simulations.Create(new Simulation[] { new Simulation() });
                // based on APSIM.Cli/Program.cs
                Runner runner = new Runner(sims);
                List<Exception> errors = runner.Run();
                if (errors != null && errors.Count > 0)
                {
                    throw new AggregateException("Simulation ran with errors", errors);
                }
                return 3.14;
            }
        }
    }
    ```

    Build the server:

    ```
    dotnet build -p:RegFree=True
    ```

    (The above command also copies the COMServer output files to the COMClient project. I'm using registration-free mode because it does not require administrative privileges.)

3.  Build and run the COMClient project:

    ```
    cd ..\COMClient
    dotnet build -p:RegFree=True
    dotnet run --no-build
    ```

    (Note that `dotnet run` must be invoked with `--no-build`, otherwise it might try to automatically build without `-p:RegFree=True`. If that happens, the fix is to run `dotnet clean; dotnet build -p:RegFree=True`. Cleaning is necessary because the build system does not recognise the property change as a reason for a full rebuild.)

Output:

```
Unhandled exception. System.AggregateException: Simulation ran with errors (Error in file:  Simulation: Simulation)
 ---> System.Exception: Error in file:  Simulation: Simulation
 ---> System.Runtime.Serialization.SerializationException: Unable to find assembly 'Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at APSIM.Shared.Utilities.ReflectionUtilities.BinaryDeserialise(Stream stream)
   at APSIM.Shared.Utilities.ReflectionUtilities.Clone(Object sourceObj)
   at Models.Core.Apsim.Clone[T](T model)
   at Models.Core.Run.SimulationDescription.ToSimulation()
   --- End of inner exception stack trace ---
   at Models.Core.Run.SimulationDescription.ToSimulation()
   at Models.Core.Run.SimulationDescription.Prepare()
   at APSIM.Shared.JobRunning.JobRunner.Prepare(IRunnable job)
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager)
   --- End of inner exception stack trace ---
   at COMServer.Server.IServer.ComputePi()
   at IServer.ComputePi()
   at COMClient.Program.Main(String[] args) in C:\Users\User\dotnet-samples\core\extensions\COMServerDemo\COMClient\Program.cs:line 12
```

### Proposed fix

#7465

### Alternative workaround

There is a simple (but ugly) workaround which can be implemented in the user's application code without modifying ApsimX. The idea is to add a handler to the event [AssemblyLoadContext.Resolving](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.resolving) of the default context (or the event [AppDomain.AssemblyResolve](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyresolve)), and when it occurs load the assembly from the desired context instead. Note that this event only occurs when assembly resolution fails, so this workaround only works if the assembly is *not* found in the default context.

```c#
...
    public class Server : IServer
    {
        public Server()
        {
            // [Somewhere at the start of the program]
            AssemblyLoadContext.Default.Resolving += OnResolving;
        }

        public static Assembly OnResolving(AssemblyLoadContext originalContext, AssemblyName assemblyName)
        {
            // [Replace "Server" with the name of some class from the desired load context]
            AssemblyLoadContext customContext = AssemblyLoadContext.GetLoadContext(typeof(Server).Assembly);
            return customContext.LoadFromAssemblyName(assemblyName);
        }

        ...
    }
```

**Discovered by:** @HemdaLevyNZ.

**Comment by hol430** [comment]
@tom93 very interesting. Out of curiosity, what led to the discovery of this bug? Are you developing a wrapper/bindings for apsim from another language?

**Comment by tom93** [comment]
@hol430 That's right. (I'm not personally involved.)
