### ISSUE TITLE
Adding released crop models into the standard toolbox

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#7467]
I noticed that some of the released crop models are not updated in the standard toolbox while working on some APSIMX tutorials. Might be worth adding them in please.

**Comment by hol353** [comment]
I think what we need to do is to get rid of the standard toolbox and modify the 'Add Model' view to show all the models that are in resources. This will provide a single place for finding models (e.g. crops) to add to a simulation as well as all the non crop models e.g. soil, folder etc. Doing this means we don't need to continually update a toolbox when a new model is released.

**Comment by Chloe0317** [comment]
Yes, I agree. I doubt the standard toolbox gets used very often.
