### ISSUE TITLE
Replacement for System.Drawing.Common

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#7469]
While looking into issue #7139, I became aware that Microsoft is encouraging developers to move away from the use of System.Drawing.Common because of issues with cross-platform support. We are currently using version 5, although version 6 is available. However, version 6 emits compiler warnings if non-Windows targets are supported. Microsoft describes the situation [here](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only). They suggest three alternative for cross-platform graphics support: ImageSharp, SkiaShap, or Microsoft.Maui.Graphics. Which of these options will be best for us? We are already pulling SkiaSharp into APSIM.Interop, so there may be less overhead there. On the other hand, Microsoft.Maui.Graphics may offer a simpler upgrade pathway (or maybe not). Interestingly, I think it actually wraps bits of SkiaSharp for its Linux support (though I might be wrong about that).

So what do people think is the best alternative? You may think we're not doing much with System.Drawing.Common, but that's not the case. The classes Color, Font, Point, and Rectangle all live there, and they are used in many places. For those specifically, we could probably use roughly equivalent Gdk classes, so that's another alternative to consider.

The problem is not immediate, but will need to be addressed in the longer term if we are to maintain cross-platform support.

**Comment by hol353** [comment]
Looks like we need to migrate to one of the suggested options. After a quick look at the 3 options:

- Microsoft.Maui.Graphics: Is an experimental package. Will it continue into the future? 
- ImageSharp: the license it is distributed under isn't as open as the others although we will still come in under a free license.
- SkiaSharp: Primarily an image rendering library but will do 2d graphics. 

Given we already link to SkaSharp, do we just give it a go?

**Comment by lie112** [comment]
I believe Maui will become MS cross platform graphics and provides single app hardware driven support for Win, iOS and Android, but still lacks any/full support for Linux

**Comment by jbrider** [comment]
Or we could copy microsoft's example of a successful cross platform application - VSCode.
Electron may be memory hungry but it is well established as a successful cross platform engine.
The engine can also be upgraded/changed and html will still work over the top.

**Comment by zur003** [comment]
Looking at this a bit more, I realised that we are already using a cross-platform graphics library in the form of CairoSharp (as part of the GtkSharp stack). We might as well just use that where possible - the only reason I can think of for not doing so would be if we are likely to port the whole GUI to Maui in the future. How likely is that?

I should also note that a possible snag in moving completely away from System.Drawing is that SharpMap pulls it in. Development of SharpMap isn't very active, so we may need to fork and modify it, or find a different mapping tool.

**Comment by hol353** [comment]
> Electron may be memory hungry but it is well established as a successful cross platform engine.

Yes it is but we would need a lot of resourcing to move to that. It would be a substantial rewrite of the GUI.

> the only reason I can think of for not doing so would be if we are likely to port the whole GUI to Maui in the future. How likely is that?

It is possible but not likely in the short/medium term.

I forgot about CairoSharp as well. I used it in the grid control and it works quite well. Agree that we should just migrate to that.

**Comment by jbrider** [comment]
You're about to advertise for programmer's - how many jobs for front end developers on seek.com ask for knowledge of GTK?
I'm pretty sure it's 0.  80-90% of front end development positions are asking for knowledge of React (web development).  
Saying we don't have resources to change direction while putting resources into something that has no future is not a convincing argument to me.  What resources do you currently have to fix bugs in the front end?

**Comment by hol353** [comment]
> You're about to advertise for programmer's - how many jobs for front end developers on seek.com ask for knowledge of GTK?

None. And we don't mention GTK in the job ad. We ask for programming skills and an eagerness to learn something new. Drew is evidence that this strategy can work. Also, we aren't appointing a UI developer. We are appointing someone who can work on APSIM. UI development will be part of their job.

> Saying we don't have resources to change direction while putting resources into something that has no future is not a convincing argument to me. 

We have resources to stabilise the current UI (might take me a week or two). We don't have resources to rewrite the GUI (might take an FTE a year).

> What resources do you currently have to fix bugs in the front end?

Neville and I currently have time allocated to fix bugs in APSIM, some of which will be UI bugs.

I'm happy for a new UI to be added to the to-do list. The trick will be prioritising that over everything else.

**Comment by zur003** [comment]
A little more follow up on this: I made a start last week at trying to convert Point and Color declarations from System.Drawing to Cairo or Gtk equivalents, with mixed results. There is a bit of ambiguity: in Gtk, a Color might be expressed as a Cario.Color, a Gtk.Color, or a Gtk.ARGB. Gtk.Color is deprecated; Cairo.Color provides little more than a basic "stuct" definition, and Gtk.Color requires pulling in the rest of the Gtk stack. I tried to use Cairo.Color where possible. Most bits ported easily, but there are some serious issues related to serialization. For one, the way colors are serialised into JSON can result in named colors like "Black" being used rather than RGB or ARGB values. Cairo.Color does not predefine any color names (nor does Gtk.ARGB), so deserialising .apsimx files holding color names is problematic. Probably worse, however, the Cairo and Gtk classes don't carry the Serializable attribute, and so the BinaryFormatter serializing and deserializing that we use to clone objects doesn't work when the objects contain Colors. I tried a work-around where I created my own "proxy" color class, but that seems a very clumsy solution, and also fails if the user attempts to use Color in a Manager script. Given those problems, I'm now tempted to see whether SkiaSharp provides a better solution.

I also had a very quick look at Maui, but wasn't overly impressed. At this point, I wouldn't guarantee it will have much more of a future than Silverlight did.

**Comment by hol353** [comment]
Thanks Eric for your continued interest in this. I also looked at Maui and like you I'm not sure it has a future. SkiaSharp might be a possible way forward.

**Comment by zur003** [comment]
Another update: 
As was the case with CairoSharp, SkiaSharp classes don't carry the Serializable attribute, so BinaryFormatter doesn't work with those classes either. However, Microsoft is gradually deprecating BinaryFormatter anyway, and we will eventually need to replace it with something else. We use BinaryFormatter primary to create a "deep clone" of an object, by first serialising the object then deserialising it into a new copy. It should be possible to use JSON serialisation for this in the same way, although it may be a bit less efficient. I've been working on this, but it appears that BinaryFormatter must do some dark magic that Newtonsoft Json can't perform. Json serialisation of properties involves a "get" of the property's value. This can be a problem when the getter expects the object to have been fully initialised, and doesn't check for the possibility of null objects. For example, in EvaporationModel we have:
`        public double CONA
        {
            get
            {
                if (IsSummer)
                    return waterBalance.SummerCona;
                else
                    return waterBalance.WinterCona;
            }
        }`

This raises an Exception if waterBalance is null, and it will be null prior to resolution of Links. There are numerous similar cases. I don't know how BinaryFormatter avoids this problem, but it does.

**Comment by hol353** [comment]
Json serialization will be slower and it doesn't serialize (by default) privates which a clone will do. 

Our extensive use of cloning might have been a design mistake. I suspect we do too much of it (because it is easy) when it isn't always needed. Anyway...

As you've found, one of the problems with serialisation is that it calls all the getters of the properties, which shouldn't be a problem except that our objects aren't always in a consistent state (which is another design problem). Objects should ALWAYS be in a consistent state. Anyway...

Option 1: we could just stay with BinaryFormatter for now. 
Option 2: we use Json serialisation and find a way to work around the exceptions thrown from getters.
Option 3: we try a 3rd party nuget package to do the cloning e.g. NClone (https://github.com/mijay/NClone)

**Comment by zur003** [comment]
A few more observations on cloning and serialization:

1. This issue will need to be addressed at some point. This [roadmap](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md) suggests that BinaryFormatter will be totally removed when .Net 9 is released at the end of 2024. We have a couple of years to think about it, but the time will be coming eventually.
2. A pure cloning package might help, but wouldn't address all our usages. Specifically, BinaryFormatter is used in the PipeUtilities that feed into Apsim.Server. This really does require serialization/deserialization of some sort,. Also serialization and deserialization would likely be part of any future checkpointing scheme. 
3. I've tried several different packages for this, with varying success. At this point, the most promising seems to be [Apex.Serialization](https://github.com/dbolin/Apex.Serialization). It's quite fast (see [these benchmarks](https://aloiskraus.wordpress.com/2019/09/29/net-serialization-benchmark-2019-roundup/), and it doesn't require that new Attribute tags be embedded everywhere. It's chief drawbacks would seem to be that the serialized form is subject to change from version to version, so it's not suitable for long-term shortage (but we're using JSON for that), and it is rather slow to initialize. The initialization delay at first usage is noticeable, but after that it's quite fast. It actually clones faster than the BinaryFormatter logic we're using now. The only code modification that I needed to make was a slight change to avoid cyclical references when dealing with soil nitrogen patches.

**Comment by zur003** [comment]
A further update to my original issue: I wasn't quite correct. Not all bits of System.Drawing.Common will become "Windows-only". The Color, Point and Rectangle structures will remain cross-platform. It's things like Bitmap and Image that are problematic. That's still a fair bit of stuff to replace, though. I'm still not sure what the best substitute will be. CairoSharp would cover a lot of things, but in several places we use in-memory png images as a currency for exchanging images (e.g., maps). Cairo itself has a method for reading a png stream, but CairoSharp does not wrap it, presumably because it uses a callback mechanism which is a bit tricky to convert to C#. (CairoSharp does wrap the methods for reading and writing png files, but not streams). Throwing in the Gdk layer, with Gdk.Pixbuf does provide for streaming png, but that means pulling GdkSharp into Apsim.Interop; I'd prefer to pull in only Cairo. 

SkiaSharp remains an option, I think. 

A further problem in all of this is that SharpMap, which we use for mapping, isn't being intensively maintained, and may not get away from use of Windows Bitmap stuff for some time, if ever.
