### ISSUE TITLE
Error in importing old apsim file

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#7471]
Following the similar bug in #7389. After importing old *. apsim file, the nitrogen module is located under `SoilNitrogen` (red circle), instead of `Soil` (blue circle).

![image](https://user-images.githubusercontent.com/1657381/187102427-b387b8eb-36ab-4b6b-9029-a6eb8adc0fc9.png)

The error code can be found from here: https://github.com/APSIMInitiative/ApsimX/blob/5ed3f61a0b326d7d107f6fb8d548e14e42e8365b/Models/Soils/Soil.cs#L298

```
[Soil].NO3
[Soil].NH4
[Soil].Urea
```

**Comment by hol353** [comment]
We also need to make sure that Nutrient is added - not SoilNitrogen. Water and 3 solutes (no3, nh4 and urea) should also be added.

**Comment by hol353** [comment]
Here's another file that doesn't convert correctly.
[DroughtSoilsOriginal.zip](https://github.com/APSIMInitiative/ApsimX/files/9501513/DroughtSoilsOriginal.zip)
