### ISSUE TITLE
Skip phase in some years for canola model

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#7481]
In the canola model (from master branch),  phases `Maturing` and `Ripening` are skipped in some years.

![image](https://user-images.githubusercontent.com/1657381/187580588-40fb1e10-55d8-40f0-9cd0-629cabbe7256.png)

In the example below, we should expect phases `Maturing` and `Ripening` after `LateFrainFilling`. However, canola directly reaches to `ReadyForHarvesting` .

![image](https://user-images.githubusercontent.com/1657381/187580553-d75ca11c-11cd-404d-a01a-a079e7e7cb60.png)

But phenology is normal in 1958 (harvested at Maturing phase).

![image](https://user-images.githubusercontent.com/1657381/187581188-7c3ecb7f-e045-4f61-8d7d-25c7ff9d3171.png)

Any ideas?

PS: I have to setup script to harvest canola at phase `ReadyForHarvesting` or `LateGrainFilling`.

**Comment by hol353** [comment]
So the issue is probably that canola has a thermal target of 5 deg days for maturing and 1 deg day for ripening. Both of these targets might be met on the same day if it is warm enough. Could this explain what you are seeing?

**Comment by byzheng** [comment]
It makes sense to me now. We might have to update harvesting rule in Canola.apsimx.
