### ISSUE TITLE
Unable to rename pasted nodes (for example new cultivars)

### ISSUE THREAD

**Issue by mpandreucci** [APSIMInitiative/ApsimX#7495]
Hi @hol353
So the problem of being unable to rename the cultivars is still happening.
It's keeps on saying that the "it's read-only".
The error information is:
Models.Core.ApsimXException: Unable to rename Kerrin1 - it is read-only.
   at UserInterface.Commands.RenameModelCommand..ctor(Model modelToRename, String newName) in C:\Users\andreucm\ApsimX\ApsimNG\Commands\RenameModelCommand.cs:line 33
   at UserInterface.Presenters.ExplorerPresenter.OnRename(Object sender, NodeRenameArgs e) in C:\Users\andreucm\ApsimX\ApsimNG\Presenters\ExplorerPresenter.cs:line 1007

Thanks for that Dean :)

 
![RenameIssue](https://user-images.githubusercontent.com/43769255/188760429-d298f0c3-80a3-463a-8c48-431f15faece3.PNG)

**Comment by mpandreucci** [comment]
It wouldn't also allow me to delete the new added cultivar. I could only get rid of it by using the undo command.

**Comment by hol353** [comment]
Can you zip and attach your .apsimx file?

**Comment by mpandreucci** [comment]
[Dewi.zip](https://github.com/APSIMInitiative/ApsimX/files/9501644/Dewi.zip)

Hi Dean.
Here it is.
The problem of reverting back changes done to the values of parameters is also happening.
If I try to change the values in the array for [Wheat].Structure.BranchingRate.StressFactors.CoverEffect.XYPairs.X = 0,0.2,0.4 it won't keep the changes made. If I save of try to run, it will revert the values to the same 0,0.2,0.4
I'll try to change that via Notepad++ and will let you know how that goes.
Thanks a lot for that Dean. I really appreciate it.

**Comment by mpandreucci** [comment]
Hi @hol353 
Just letting you know that it worked changing the values of the array via Notepad++
Do you want me to put a separate issue for this?

**Comment by hol353** [comment]
@mpandreucci This is a bug that we need to fix. The idea is that you can right click on the cultivar and make it not readonly but that doesn't work. Not sure when this will be fixed. For now you have a work around.

**Comment by mpandreucci** [comment]
Hi Dean.
All good, the work around is just fine and is pretty simple really.
Thanks a lot for that :)
