### ISSUE TITLE
Missing sqlite3 in Linux after publish

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#7496]
I compile Models project under Linux to run in cluster with command below

```
dotnet publish -c Release -f netcoreapp3.1 -r ubuntu.20.04-x64  --self-contained  true Models.csproj

dotnet publish -c Release -f netcoreapp3.1 -r sles.15-x64  --self-contained  true Models.csproj
```

I get an error if Linux is not installed sqlite3, e.g. cluster managed by module. 

```
 ---> System.DllNotFoundException: Unable to load shared library 'sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libsqlite3: cannot open shared object file: No such file or directory
```

I have to use `module load sqlite/3.35.4` to load sqlite.

It seems Models.exe looks for sqlite.so instead of sqlite3.dll in the publish folder.

**Comment by hol353** [comment]
> It seems Models.exe looks for sqlite.so instead of sqlite3.dll in the publish folder.

I think this is correct. On Linux, models.exe will look for sqlite.so. sqlite.dll is an unmanaged DLL that only works on Windows. You will need to install sqlite on Linux to get APSIM to run.

**Comment by byzheng** [comment]
Thanks. Would be better to document it for other information

**Comment by byzheng** [comment]
This is my notes about how to compile and publish APSIM NG. Hope it is helpful. Feel free to copy to any places.



# Compile APSIMNG from source codes

## Checkout the latest source codes from APSIMInitiative

```
git clone --depth 1 https://github.com/APSIMInitiative/APSIM.Shared.git
git clone  --depth 1  https://github.com/APSIMInitiative/ApsimX.git
```

## Compile APSIMNG GUI 

Open `ApsimX.sln` under folder `ApsimX` with Visual Studio (2019 above), and then use menu `Build` -> `Build Solution` to build whole projects.

## Publish models for batch mode

Run following command under Models folders on Windows

Publish for windows

```
dotnet publish -c Release -f netcoreapp3.1 -r win-x64 Models.csproj
```

Publish for Ubuntu

```
dotnet publish -c Release -f netcoreapp3.1 -r ubuntu.20.04-x64  Models.csproj
```

Publish for SLES (e.g. CSIRO cluster):

```
dotnet publish -c Release -f netcoreapp3.1 -r sles.15-x64  Models.csproj
```

All runtime identify for other operating system can be found from [github](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json)

Copy the contents `bin/Release/netcoreapp3.1/<runtime-identify>/publish/` to your operating system.

## Further steps 

On Windows, check whether `sqlite3.dll` is under `bin\Release\netcoreapp3.1\win-x64\publish`  folder. If not, copy from `bin\Release\netcoreapp3.1\win-x64\` to `publish` folder.

On Linux, sqlite3 should be installed into system with following command

for Ubuntu

```
sudo apt install sqlite3
```

for CSIRO cluster

```
module load sqlite/3.35.5
```
