### ISSUE TITLE
Overwriting the cultivar specified parameter values.

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#75]
I am trying to setup some cultivar specified parameter values in the WheatPMFPrototype.xml, e.g.

	<Cultivar>
		<Name>hartog</Name>
		<Alias>hartog</Alias>
                <Command>[Phenology].Vernalisation.VernSens = 0.9</Command>
                <Command>[Phenology].Vernalisation.PhotopSens = 0.9</Command>
                <Command>[Phenology].FloralInitiationFloweringPhase.Target = 630</Command>
	</Cultivar>

It seems `[Phenology].Vernalisation.VernSens` and `[Phenology].Vernalisation.PhotopSens` are overwrote during simulation, but `[Phenology].FloralInitiationFloweringPhase.Target` still uses the default value. 

Do I use the correct way to specify the `[Phenology].FloralInitiationFloweringPhase.Target`? 

Not sure how to debug and fix this problem.

**Comment by hol353** [comment]
There is no FloralInitiationToFlowerPhase in the PMF wheat model under Phenology. There is a  FloralInitiationToFlagLeaf though but it doesn't have a 'Target' as it is a LeafAppearancePhase. You need to check the WheatPMFPrototype.xml file to see what is possible.

**Comment by byzheng** [comment]
I have modified a phase name into "FloralInitiationToFlowerPhase". An exception will be give if the phase name is not in the phenology model. While create a reproduce example for debugging.
