### ISSUE TITLE
APSIMX not simulating all the years in my weather file

### ISSUE THREAD

**Issue by Janewanguimugo** [APSIMInitiative/ApsimX#7504]
My issue is that APSIM does not simulate all the years I have. here is a screenshot of what I mean. Please guide me on what could be wrong in the simulation. When using the soybean example 1923 is missing.
![image](https://user-images.githubusercontent.com/103818039/190082933-39d40ee0-3503-4336-82f9-79c86b42e093.png)

When using my own weather data many more years missing 1995 to 1997

![image](https://user-images.githubusercontent.com/103818039/190084462-2d6b0bf5-68d8-48f5-8d2a-085de414bc0d.png)

**Comment by peter-devoil** [comment]
The soybean manager component usually has criteria for planting; and chances are that these criteria aren't met. As well, the plants can die - so they aren't recorded as harvested. Check your met (and possibly soil water) data for the former, the summary file (reads like a diary) for the latter

**Comment by Janewanguimugo** [comment]
Thank you
