### ISSUE TITLE
HarvestReport for many simulations 

### ISSUE THREAD

**Issue by Janewanguimugo** [APSIMInitiative/ApsimX#7510]
APSIM GUI gives me the names of my simulation E.G mridina,scsafari, scsentinile, and scserenade.
![image](https://user-images.githubusercontent.com/103818039/190600694-ee13b881-2074-470d-8b3d-aa373c0a8a3a.png)

When I do the simulation using the R package I am not able to tell the simulation name since they are now converted to factors (1, 2, 3, and 4). Thus it's hard to know which is mridina,scsafari, scsentinile, or scserenade. My question is how to get the harvest report to with the simulation names just as in the APSIMX GUI

My command is  sim <- apsimx("soybean_Goodnature.apsimx", value = "report")

![image](https://user-images.githubusercontent.com/103818039/190601958-bd93e8d4-14f5-4eaf-8634-b5f7174b6850.png)

**Comment by BrianCollinss** [comment]
What do you get for: print(sim$SimulationID)?

**Comment by Janewanguimugo** [comment]
I get the numbers
 [1] 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 2 2 2 2 2 2
 [44] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 [87] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
[130] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3

**Comment by BrianCollinss** [comment]
Is there no column named **SimulationName** in **sim** table?

**Comment by Janewanguimugo** [comment]
There is no SimulationName. What I have is...

> glimpse(sim)
Rows: 79
Columns: 16
$ CheckpointID                     <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ SimulationID                     <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ Zone                             <chr> "Field", "Field", "Field", "Field", "Field", "Fi…
$ Clock.Today                      <chr> "1900-11-14 12:00:00", "1901-11-15 12:00:00", "1…
$ Wheat.Phenology.Zadok.Stage      <dbl> 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, …
$ Wheat.Phenology.CurrentStageName <chr> "HarvestRipe", "HarvestRipe", "HarvestRipe", "Ha…
$ Wheat.AboveGround.Wt             <dbl> 933.982037, 1059.496122, 1.548387, 1764.142504, …
$ Wheat.AboveGround.N              <dbl> 14.78228741, 14.26695375, 0.06193548, 28.6482841…
$ Yield                            <dbl> 3404.204, 4098.183, 0.000, 7346.298, 3796.183, 3…
$ Wheat.Grain.Protein              <dbl> 14.86777, 13.51513, 13.51513, 14.65415, 14.17322…
$ Wheat.Grain.Size                 <dbl> 0.02754058, 0.02958773, 0.00000000, 0.03591527, …
$ Wheat.Grain.Number               <dbl> 12360.684, 13850.954, 0.000, 20454.525, 14238.64…
$ Wheat.Grain.Total.Wt             <dbl> 340.4204, 409.8183, 0.0000, 734.6298, 379.6183, …
$ Wheat.Grain.Total.N              <dbl> 8.863910, 9.700086, 0.000000, 18.853545, 9.42279…
$ Wheat.Total.Wt                   <dbl> 1080.717737, 1236.110223, 1.800470, 2046.893516,…
$ Date                             <date> 1900-11-14, 1901-11-15, 1902-10-21, 1903-11-04,…

**Comment by hol353** [comment]
You need to use SQL to query the .db file and join two tables. The SQL statement will look like:

```
SELECT * FROM _Simulations,Report WHERE Report.SimulationID = _Simulations.ID
```

'Report' is the name of the table that you want to read data from.

I don't know how to run an sql query in R. Hopefully someone else can help with that.

**Comment by BrianCollinss** [comment]
This might be helpful:

```
  con <- dbConnect(drv=SQLite(),dbname=OutFile)
  AllTables <- dbListTables(con)

  Outputs <- list()
  for (Table in AllTables) {
    Outputs[[Table]] <- data.table(dbGetQuery(con,sprintf('select * from %s',Table)))
  }
```

This is just an example, You can change the quiry anyway you need.

**Comment by Janewanguimugo** [comment]
Hi,
I redid the experiment using a factorial design where the factors were the varieties (mridina,scsafari, scsentinile, and scserenade) and the apsimx package executed it well.
