### ISSUE TITLE
C dung incorporated into the soil

### ISSUE THREAD

**Issue by francobilotto17** [APSIMInitiative/ApsimX#7515]
Dear APSIM community,

I was wondering where do you find the C incorporated from dung? I mean, what is the specific pool that captures C from dung after grazing?

Regards,
Franco

**Comment by MarkLieffering** [comment]
I presume you are talking about the SimpleGrazing module being used with AgPasture?

**Comment by francobilotto17** [comment]
Thanks Mark! yes, I was talking simplegrazing. how the model captures dung decomposition and the C pools to corroborate the assimilation of carbon after grazing.
