### ISSUE TITLE
Can a simulation be cloned inside itself?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7516]
A colleague asked me if it is possible to pause a simulation on one day, and kind of clone the simulation 100 times, and then run through the next day. I assume it is not currently possible. Is there a chance that such a strucutre be implemented in APSIM?

In SiriusQuality model, the whole simulation is encapsulated inside a class called **universe**. That universe could be cloned. I used that strucutre to implement a stress index which needed to run multiple scenarios on each specific day, save some state variables, and then revert back to the original state. Such a strucutre can be quite useful in APSIM, for instance when it comes to running simulations stochastically.

**Comment by hol353** [comment]
This is theoretically possible but would require some changes to the infrastructure and then some fancy manager scripting to make it work. Unlikely to happen because we have limited resources and higher priority things on the todo list.

**Comment by BrianCollinss** [comment]
Thanks Dean. Just a follow-up question. In [this protocol](https://www.apsim.info/wp-content/uploads/2019/09/Protocol-Specification.pdf), Checkpoints are intented to be able to save a component state so that component can be **resumed** in another simulation. I was wondering if this idea has been implemented in APSIM Nextgen?

**Comment by hol353** [comment]
Nope it isn't in Next Gen and checkpointing was never implemented in APSIM 7.10 either.

**Comment by BrianCollinss** [comment]
Cheers.
