### ISSUE TITLE
How to convert soil carbon output in kg/ha from APSIM into percentage (%) ?

### ISSUE THREAD

**Issue by demlie257** [APSIMInitiative/ApsimX#7517]
I was getting an output of the soil carbon in APSIM simulation using  this command, 
                    [SurfaceOrganicMatter].C

The output results for soil carbon were in kg/ha. I want to get this output in percentage (%).  Which soil depth should I consider?

**Comment by hut104** [comment]
Hi.
First, we may need to clarify.  You mention soil organic carbon, but the example you provide is the C in the surface organic matter (ie the crop residues on the soil surface).
If you require the soil organic carbon, you will need to look at the outputs for the soil models.

________________________________
From: debtz2453 ***@***.***>
Sent: Wednesday, 21 September 2022 3:21 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] How to convert soil carbon output in kg/ha from APSIM into percentage (%) ? (Issue #7517)


I was getting an output of the soil carbon in APSIM simulation using this command,
[SurfaceOrganicMatter].C

The output results for soil carbon were in kg/ha. I want to get this output in percentage (%).

**Comment by demlie257** [comment]
> 

Thanks for your reply and clarification made. To make it clear. I want to convert it the carbon output in kg/ha into the percentage (%). Thanks for your help.

**Comment by MarkLieffering** [comment]
Output [SurfaceOrganicMatter].Wt and calculate using [SurfaceOrganicMatter].C?
