### ISSUE TITLE
Data Needed to run APSIM simulation to model soil carbon and regenerative ag

### ISSUE THREAD

**Issue by SasankhM** [APSIMInitiative/ApsimX#7519]
Want to confirm that the following information is what is required and is exhaustive to run APSIM to model soil carbon when using regenerative ag (cover cropping, reduced tillage): 

Weather Data (can get from Weather API)

- Daily Solar radiation (MJ/m^2)
- Max Daily Temperature (°C
- Minimum Daily Temperature (°C)
- Daily Rainfall (mm)

Soil Data
  Physical Numbers:
  - Sand %
  - Silt %
  - Clay %
  - Rocks %
  - BD (Bulk Density) %

  Organic Numbers:
  - Carbon Content (Total)
  - SoilCNRation (g/g) (estimate)

  Chemical Numbers:
  - NO3 (ppm)
  - NH4 (ppm)
  - Urea (ppm)
  - pH (water)

Management of Crop
  Surface Organic Matter:
  - Type of initial residue pool (e.g. wheat)
  - Mass of initial surface residue (kg/ha)
  - Standing fraction (0 to 1)
  - Carbon Phosphorus Ratio (g/g)
  - Carbon:Nitrogen Ratio (g/g)

  Sowing Fertilizer:
  - Amount of fertiliser to be applied (kg/ha)
  Sowing Rule:
  - Start Date of Sowing
  - End Date of Sowing
  - Cultivar to be sown
  - Sowing Depth (mm)
  - Row spacing (mm)
  - Plant Population (/m2)

Practices 
  Cover Crop (add a crop with following information)
  - Start Date of Sowing
  - End Date of Sowing
  - Cultivar to be sown
  - Sowing Depth (mm)
  - Row spacing (mm)
  - Plant Population (/m2)

  Tillage 
  -   Tillage Date
  -   Fraction of Residues to Incorporate (0-1)
  -   Depth of Tillage (mm)

**Comment by sno036** [comment]
HI -  I think your best approach is to work through the training material and after that set up a simulation close to what you want. That will give your list on inputs, actions, etc.
