### ISSUE TITLE
Factorial design

### ISSUE THREAD

**Issue by Janewanguimugo** [APSIMInitiative/ApsimX#7520]
How can I vary the planting dates by 5 days? I tried the range command below and got an error.

[SowingRule].Script.SowDate = 01-dec to 07-jan step 5

The error is: 
Error in file:D:\Jane\apsimruns\soy.apsimx --> Input string was not in a correct format.

**Comment by hol353** [comment]
Without having time to look into it I'd say that the dates need to be yyyy-mm-dd e.g.
 
2022-12-01

**Comment by hol430** [comment]
The `value = x to y step z` only works if x, y, and z are all numbers - it doesn't support dates or strings. So you'll need to specify the sowing dates 1 by 1, separated by commas.

Ultimately the date format required here will depend on how you've written your manager script. If the `SowDate` property is of type `DateTime`, then you can provide the dates in yyyy-MM-dd format. If the property is a string then its format will depend on how the script was written. For what it's worth, I think the default "sow on a fixed date" script in the manager toolbox uses a dd-MMM syntax (e.g. 31-Jan) for some strange reason.

**Comment by Janewanguimugo** [comment]
Thank you. This works
[SowingRule].Script.SowDate = 01-dec, 06-dec, 11-dec, 17-dec, 22-dec, 27-dec, 01-jan, 06-jan
