### ISSUE TITLE
Error after switching off graph series "on right?"

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7524]
If the "On right" switch has been set previously and then switched off the values of X2 and Y2 remain set in the apsimx json file.
This is fine while these fields remain in the database but if they are changed or removed a warning is thrown when selecting the series 

WARNING: .Simulations.Graphs_Summary.Females numbers by class.FBreeders: Selected X2 field name 'TotalAE' does not exist in the datastore table 'ReportResourceBalances'. Have the simulations been run?

There is no way to fix this other than edit the json file to set X2 and Y2 to null or delete and recreate the series.

When "on right" is turned from on to off, the values need to be set to null.
I cannot determine a way of achieving this through the UI.

**Comment by ric394** [comment]
@lie112 I'm unable to reproduce this issue. Do you recall what graph type you were using?

**Comment by lie112** [comment]
I get this all the time. Maybe it arises if you have a graph that used to have a right axis and you modify the series to a new data source and x,y values. By that time it seems impossible to remove the errors by turning on and off left right check boxes etc. I'll see if I can find a current example
