### ISSUE TITLE
Problem with edit_apsimx_replace_soil_profile() command

### ISSUE THREAD

**Issue by Janewanguimugo** [APSIMInitiative/ApsimX#7528]
The simulation works when I run the soybean example in R with the default soil. However, when I replace the soil and rerun the simulation it does not work. I get errors both in R and in the APSIM GUI

library(apsimx)
setwd("D:/Jane/apsimruns")
tmp.dir <- tempdir()
extd.dir <-"D:/Jane/apsimruns"
sim <- apsimx("soybean.apsimx", value = "HarvestReport")

############################Soil Replacement
sp <- get_isric_soil_profile(lonlat = c(23.7, -16.9))

edit_apsimx_replace_soil_profile("soybean.apsimx", soil.profile = sp, overwrite = TRUE)
sim1 <- apsimx("soybean.apsimx", value = "HarvestReport")

**This is the error in R**
Warning messages:
1: In system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait,  :
  running command 'C:\WINDOWS\system32\cmd.exe /c C:\PROGRA~1\APSIM2022.8.7072.0\bin\Models.exe .\soybean.apsimx' had status 1
2: In read_apsimx(file = sub("apsimx", "db", file), src.dir = src.dir,  :
  Report table has no data

**This is the error in the GUI**
![image](https://user-images.githubusercontent.com/103818039/192974279-15f97a1b-6cc0-4264-8d23-6f36b11e5b0e.png)

**Comment by hol353** [comment]
The error messages coming from APSIM says that the starting water in layers 2 to 6 are above saturation. Starting SW needs to be > LL15 and < SAT. What are your starting soil water values? They will probably need to change if you change the soil.

**Comment by hut104** [comment]
The apsim error seems to be pointing to the problem.
Your hydraulic properties are not internally consistent.
There is inconsistency between BD and moisture retention.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Janewanguimugo ***@***.***>
Sent: Thursday, September 29, 2022 5:59:29 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Problem with edit_apsimx_replace_soil_profile() command (Issue #7528)


The simulation works when I run the soybean example in R with the default soil. However, when I replace the soil and rerun the simulation it does not work. I get errors both in R and in the APSIM GUI

library(apsimx)
setwd("D:/Jane/apsimruns")
tmp.dir <- tempdir()
extd.dir <-"D:/Jane/apsimruns"
sim <- apsimx("soybean.apsimx", value = "HarvestReport")

############################Soil Replacement
sp <- get_isric_soil_profile(lonlat = c(23.7, -16.9))

edit_apsimx_replace_soil_profile("soybean.apsimx", soil.profile = sp, overwrite = TRUE)
sim1 <- apsimx("soybean.apsimx", value = "HarvestReport")

This is the error in R
Warning messages:
1: In system(cmd, intern = intern, wait = wait | intern, show.output.on.console = wait, :
running command 'C:\WINDOWS\system32\cmd.exe /c C:\PROGRA~1\APSIM2022.8.7072.0\bin\Models.exe .\soybean.apsimx' had status 1
2: In read_apsimx(file = sub("apsimx", "db", file), src.dir = src.dir, :
Report table has no data

This is the error in the GUI
[image]<https://user-images.githubusercontent.com/103818039/192974279-15f97a1b-6cc0-4264-8d23-6f36b11e5b0e.png>

**Comment by Janewanguimugo** [comment]
I have realised the APSIM X package consistently downloads with this error, but the GUI downloads well
