### ISSUE TITLE
How to obtain LL15 and DU to model soil carbon  in APSIM?

### ISSUE THREAD

**Issue by SasankhM** [APSIMInitiative/ApsimX#7529]
I am curious for LL15 and DUL, how are those ground truth values measured or obtained? Are they obtained from a soil lab with a soil sample or obtained from literature?

**Comment by MarkLieffering** [comment]
Let Google be your friend....https://www.apsim.info/wp-content/uploads/2019/10/Parameters-for-soil-water-Ver24.pdf

also https://www.youtube.com/watch?v=vELxkR0TUFY may be useful

Have you gone through the basic APSIM training? - this kind of stuff is covered
