### ISSUE TITLE
Add replacements into the 'Add Model' view in the GUI

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#7539]
To make it easier for users, add 'Replacements' into the 'Add Model' feature of the user interface.

**Comment by Hull4Progress** [comment]
Maybe you can help me - I am trying to run apsim-7143 on my Mac with Ventura 13.2 (I also was trying it on Ventura 13.1, and I tried an older version of apsim also).  I have disabled the Gatekeeper with its security blocks on my Mac.  This app does not open for me (which I click to open, a bouncing icon appears on my docker tray for a few seconds, but then disappears).  Has anyone else successfully run the apsim on the Ventura OS?  Thx

**Comment by ric394** [comment]
@Hull4Progress The issue your having would be best raised in the APSIM Classic repository located here: [APSIM Classic Issues](https://github.com/APSIMInitiative/APSIMClassic/issues)
The version you've mentioned is an APSIM Classic version and issues concerning these are best handled there.

**Comment by Hull4Progress** [comment]
Hi - thank you so much for responding to my issue!

I find it curious, however, that you think the version I'm mentioning is
for APSIM Classic.  I downloaded it using the link

https://registration.apsim.info/?product=APSIM%20Next%20Generation&version=2023.02.7140.0&platform=MacOS,
which appears to have the phrase "Next Generation" in it.


I found that link on a page with URL https://registration.apsim.info/ which
I got to from https://www.apsim.info/download-apsim/ by clicking on
"Non-Commercial Use".  I am attaching a screenshot of the page I made the
download from -- please note that the scroll down choice for "Product" is
"APSIM Next Generation"

Can you please explain to me how I can download the latest version of APSIM
Next Generation?

Many thanks!
Rick Hull

[image: Screenshot 2023-02-09 at 7.06.28 PM.png]

**Comment by ric394** [comment]
@Hull4Progress my apologises I misread the version. You are downloading the APSIM Next Generation version.

**Comment by Hull4Progress** [comment]
Hi Julian - that's OK.  Also, I found a GitHub issue
https://github.com/APSIMInitiative/ApsimX/issues/7765 which seems
similar/related to my problem, so I added a comment to that one.

Do you have any insight about whether someone might be able to look into
that issue sometime soon?

Many thanks
Rick Hull
