### ISSUE TITLE
Is it possible to simulate ponding with Next Gen?

### ISSUE THREAD

**Issue by femiguez** [APSIMInitiative/ApsimX#7551]
Some of the online documentation is about Classic. The 'max_pond' input is hidden in Next Gen. Is it possible to simulate ponding?

**Comment by peter-devoil** [comment]
No - it's on the [aspirational](https://github.com/APSIMInitiative/ApsimX/issues/5360) list though.

**Comment by hol353** [comment]
Actually, if you use SWIM the answer is yes. The SWIM validation tests the ponding capability.

**Comment by femiguez** [comment]
Thanks @peter-devoil @hol353 ! We'll be testing SWIM then.
