### ISSUE TITLE
Clock Event Documentation

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#7568]
Knowledge of the order of clock events is beneficial for modellers writing manager scripts or sometimes for reporting.

1) The list of events in report (for reporting frequency) includes the CLEM events (which are many).  It is good that they have CLEM in the name to help.  Is it possible for CLEM to use a different list to APSIM?

2) It would be good to have documentation that tells APSIM users the order of clock events during an APSIM simulation. It would be difficult to currently autogenerate this (and therefore it may become incorrect when clock is edited).

**Comment by lie112** [comment]
I could move the list of CLEM time-step events to to a public void CLEMEvents() so they aren't in the main sequence for clarity.

After StartOfSimulation event I have two initialisation events and a validation event. These could be renamed to something more generic for everyone else to use. Validation happens after these Initialisations have done their bit and they needed to be after the logic performed in StartOfSimulation and this is the place for all validation before the simulation starts.

I am not sure where the list of Events is defined, I assume it looks at Clock and grabs all the EventHandlers. I cannot foresee CLEM users needing to use the control logic events in reports so they could be flagged with an Attribute and ignored when creating the list. This attribute would also allow other events to be omitted from the list, but can still be used by the user by typing them out. 

CLEM reference manual defines all [CLEM events](https://www.apsim.info/clem/Content/Details/Events.htm)

**Comment by hol353** [comment]
@par456 & @ric394  I wonder if we could write some c# code in APSIM.Documentation/program.cs to parse (using RegEx) Clock.cs looking for ```xxxx.Invoke(this, args);``` lines and write them to a clock.html file. We could also filter out the CLEM ones at the same time so they don't clutter the .html.

The APSIM documents are rendered as pdf and published here: https://apsimnextgeneration.netlify.app/modeldocumentation/

This is going to be a bit difficult as APSIM.Documentation assumes that all documentation is created by running a .apsimx file and generating a pdf of each one. In addition the code needs a refactor.

**Comment by lie112** [comment]
I have been thinking about hiding the CLEM Clock events from non-CLEM users. As Clock is basically an event manager with the one controlling loop fired on DoCommence it can't easily be inherited to provide a version with additional CLEM specific functionality (what we have now). 
The other option would be to check if there is a ZoneCLEM model in scope when wiring up Events visible to the user in dropdowns etc.
