### ISSUE TITLE
Calculating crop specific Plant Available Water

### ISSUE THREAD

**Issue by LindsayWBell** [APSIMInitiative/ApsimX#7576]
It would be really helpful if it was possible to calculate the plant available water relative to a particular crop - this could be associated with the cropSoil module under Physical so that this module could be called to provide this variable for output. This could be calculated using the below method for all layers which can then be added to give the total profile value. 

(sum([soil].Water.MM) - sum([mungbeanSoil].LLmm)) as MungbeanPAW

**Comment by peter-devoil** [comment]
Similarly, I've been accumulating "snippets" of obscure calculations, eg "calculate water content to 120cm" or "OC%".. Of course, they get lost (and subsequently re-invented) when the code isn't in active use. 

Is the best place for these in the repo somewhere, an issue, or some other sort of online collaboration?

**Comment by LindsayWBell** [comment]
As this is a common challenge especially for doing 'experiments' with different soil water availabilities - it is also always confusing when PAW can mean quite different things, so I thought it would be a useful variable to be made available for output as it clarifies some of the potential confusions - others could then add them up by whatever layers they want etc.

**Comment by jbrider** [comment]
It would definitely be useful to have an online collection of 'snippets' for Apsim manager code.
A quick and dirty way to get started might be to create a separate repository for them on github.

**Comment by hol353** [comment]
The easiest for most users is to have them in the manager toolbox. Most APSIM users don't do git.

**Comment by jbrider** [comment]
Ideally we could create a website that allowed easy browsing/submission of snippets - but initially a repository would be a good interim step that requires little time/effort on our part.
It might also be a way to gauge interest in something like this.
