### ISSUE TITLE
Add an example simulation that shows creating events in scripts

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#7577]
Need a simulation example that shows how to define events in a manager script that are published to the simulation.

**Comment by peter-devoil** [comment]
Is it possible to make custom events at runtime, and pick them up with a second manager?

**Comment by hol353** [comment]
Yep.
```c#
var e = new Events(this);
e.Publish("MyEvent", new object[] { this, new EventArgs() });
```

**Comment by hol430** [comment]
I note that your event handler method needs to be private. That could be regarded as a bug.
