### ISSUE TITLE
Adjustment of PAWC in Water module

### ISSUE THREAD

**Issue by LindsayWBell** [APSIMInitiative/ApsimX#7579]
While it is possible to adjust the % of full profile or depth of wet soil it would be good to be able to set the Plant available water also in this module. And the variable should be changed to PAW not PAWC.

**Comment by hut104** [comment]
@LindsayWBell It may be worth stating what the difference between PAW and PAWC is within your nomenclature.  There are different definitions out there.

**Comment by LindsayWBell** [comment]
To clarify - what I mean is that the PAW (i.e. current water content minus lower limit relative to a crop or ll15) should be able to be specified.
