### ISSUE TITLE
Adding new fertilizer

### ISSUE THREAD

**Issue by harsh-pathak-purdue** [APSIMInitiative/ApsimX#7592]
Does the following capture your interest? if yes please proceed

Hi all,

I am interested in adding a new fertilizer to the (APSIM next generation 2022.6.7044.0) interface. Could you all please provide me some guidance or suggestions?

Appreciate your time and help

**Comment by harsh-pathak-purdue** [comment]
@hol353 would appreciate your thoughts and suggestions. Thank you

**Comment by hol353** [comment]
Internally, APSIM doesn't care about fertiliser types when applying fertiliser. It only wants to know about the amount of NO3 being applied. The fertiliser types are in the GUI to help the user.

If you want to add a fertiliser type you will have to modify the source code (fertiliser.cs) and recompile.

**Comment by harsh-pathak-purdue** [comment]
Thanks much, I wanted to add 10-34-0, Ammonium Polyphosphate [https://www.plantfoodco.com/golf-professional-turf/products/liquid-fertilizer/10-34-0/#:~:text=Ammonium%20Polyphosphate%2010%2D34%2D0,and%20to%20encourage%20root%20development.]  and ATS (https://crops.extension.iastate.edu/blog/angie-rieck-hinz/use-ammonium-thiosulfate-ats-crop-production)
