### ISSUE TITLE
Ingore .sln file?

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7596]
Do people have the .sln file in the got.ignore file and is git.ignore local or across all users?
I keep getting code changes wanting to upgrade the solution from Visual studio 16 to 17. I assume this is a local issue and not something that should be included across all users.

**Comment by hol353** [comment]
We are still using Visual Studio 2019 - version 16 (we should upgrade!). You must be using VS 2022 - version 17 which is why you're seeing messages to upgrade the .sln files.

No, .sln is not in git .ignore. The git .ignore file is committed into the repo so everyone uses the same git .ignore.

**Comment by lie112** [comment]
Thanks, just as I thought. 
VS2022 is much faster and finally runs as 64-bit application with all the memory benefits. Hot reload works when developing other apps and web. I'll just ignore my sln updates.  I'm not sure how this ever really worked for people running older versions of vis studio.
