### ISSUE TITLE
Error during upgrade/installation on Windows 10 C: drive

### ISSUE THREAD

**Issue by genkiwi04** [APSIMInitiative/ApsimX#7601]
![Error during Apsim installation](https://user-images.githubusercontent.com/32096482/199976680-ce8b7783-7401-4349-9a2d-745b3a891edb.jpg)

**Comment by hol353** [comment]
Is this on a Mac? It doesn't look like it but I need to check.

Other questions: How did you answer the first question in the installer "Install for me only or for everyone"? If you say install for you only then it doesn't need admin privileges. 

It can't write to your disk. Do you have sufficient disk space?
