### ISSUE TITLE
What are Model overrides and Operations

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7606]
I have come across ModelOverrides and Operations in the add new models and wondered what they are?
The code isn't very clear on what they do. Can I have a quick description to see if they are of use to me?

**Comment by hol353** [comment]
A ModelOverrides models can be added somewhere in your simulation. At the start of simulation it will apply the user specified property=value lines.

An operations model lets the user specify management actions like sowing, fertiliser, irrigation etc on specific dates. Look in any of validation .apsimx files for examples.

**Comment by femiguez** [comment]
I'm looking at APSIM2022.10.7104.0 and I see 'ModelOverrides' but it appears as if 'Replacements' have disappeared. To be more specific. I right-click under 'simulations', then 'add model' and 'Replacements' used to be under 'Core' (if I'm not mistaken), but I can't find them

**Comment by sarchontoulis** [comment]
Fernando, try adding a "folder" and then rename it to "replacements"

**Comment by sarchontoulis** [comment]
instead of adding a simulation, try to add a crop model or a report under the replacements. Will that work?

**Comment by femiguez** [comment]
@sarchontoulis Apparently, it does not work. There are work arounds, but the problem with the GUI was mentioned in #7539 and that is what I was running into

**Comment by daSilva5** [comment]
Hi,
I would like to re-open it.
I actually to not understand what "it will apply the user specified property=value lines" looks like.
If I want to change crit_residue_wt and opt_temp from SurfaceOM and sen_detach_frac in sugar model that has values for ratoon and plant crop. Can I do this using ModelOverrides? If yes, what does it looks like?


Cheers,
Isis
