### ISSUE TITLE
Optimization of parameters

### ISSUE THREAD

**Issue by harsh-pathak-purdue** [APSIMInitiative/ApsimX#7610]
Hi all,

Does the following capture your interest, if yes please proceed and help:

I am trying to optimize the parameters through APSIM GUI, but not sure why I am getting the following error:

''' 
Error from R:

Script path: 'C:\Users\Harsh\AppData\Local\Temp\CroptimizR-9438582c-b2b8-41c7-8245-3b596058ea7e\parameter_estimation.r'
StdErr:
Learn CroptimizR at: https://SticsRPacks.github.io/CroptimizR
Attaching package: 'dplyr'
The following objects are masked from 'package:stats':
    filter, lag
The following objects are masked from 'package:base':
    intersect, setdiff, setequal, union
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
Error in apsimx_wrapper(model_options = model_options) : 
  C:/Program Files/APSIM2022.6.7044.0/bin/Models.dll is not executable or is not a apsimx executable !
In addition: Warning message:
In system(cmd, wait = TRUE, intern = TRUE) :
  running command 'dotnet C:/Program Files/APSIM2022.6.7044.0/bin/Models.dll /Version' had status 32913
Execution halted
'''

**Comment by harsh-pathak-purdue** [comment]
@ApsimBot any suggestions

**Comment by femiguez** [comment]
It is helpful to add the version of APSIM Next Gen you are running and the session info for R. As you can see, R packages are being used in the optimization, but there might be some conflicts. There also appears to be a problem running apsim from R. 

One alternative is to use this approach: https://femiguez.github.io/apsimx-docs/optim-apsim.html
