### ISSUE TITLE
GUI is not handling 'enable' properly in Factors

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#7611]
I have a Permutation with three different Factors, one of which contains a list of Operations (for different fertiliser levels), while testing the simulation, I noticed something odd when trying to switch the property ```enable``` of the Operations, particularly when switching the property on the first or last item of the list. Switching the ```enable``` status in the first item will disable/enable all items in that factor. Switching the status in the last item will enabled/disable all factors (not only the one containing the item).
This glitch works both way (enabling/disabling) and it does not seem to affect other items (eg soil or compositefactor) nor other collections (e.g. graphs or folders, etc.). Below is a screenshot of the simulation with everything enabled, the result of disabling the first, second and last item in the Factor 'NRate':
![image](https://user-images.githubusercontent.com/12175986/200410614-d7921dc9-c650-4061-ba47-4c98cb684feb.png)
![image](https://user-images.githubusercontent.com/12175986/200410722-8bf4c1f1-6826-45da-a63f-6ba8a60d674b.png)
![image](https://user-images.githubusercontent.com/12175986/200410835-ea8f6112-f44b-405c-b67e-f7b4c6219c2e.png)
![image](https://user-images.githubusercontent.com/12175986/200410931-362932a2-21cd-4aa7-ba42-692dc53f1bad.png)

**Comment by rcichota** [comment]
This is making no sense. Every time I close and open the simulation the behaviour is a bit different. I tried with a different simulation that has the same Factor structure (it is the MultiSpeciesPastures, in ApsimX/Prototypes/MultiSpeciesPasture/). All seem to work fine in there. I am attaching the simulation I am seeing the oddity frequently...
[PlantainHarvestTest.zip](https://github.com/APSIMInitiative/ApsimX/files/9955417/PlantainHarvestTest.zip)

**Comment by zur003** [comment]
@rcichota - Darn it, that's something I broke with PR #7595. Disabled items aren't being "located" in all of the contexts where they should be. Nasty bug. Thanks for finding it. I need to think a bit more about when disabled items should be locatable, and when they shouldn't.

**Comment by hol353** [comment]
I think they should always be locatable. When a simulation is being run, the disabled models are removed from the simulation anyway so they won't be found at simulation run time.
