### ISSUE TITLE
Unable to add Excel Input File to Report

### ISSUE THREAD

**Issue by SasankhM** [APSIMInitiative/ApsimX#7618]
Based on this video: https://www.youtube.com/watch?v=88O2c6xWGos&ab_channel=MatthewHarrison, when I try to add a model (Excel Input File) to my Report to perform comparisons, it doesn't allow me to select an excel file from my finder. Please note the file is .xlsx. Appreciate the help- thanks!

**Comment by hol353** [comment]
You normally add an ExcelInputFile under a DataStore (not report). When I do this I can browse to a .xlsx file ok. You mention 'finder' above. Are you using a Mac?

**Comment by SasankhM** [comment]
Yes, I am trying to do it under DataStore, and using a Mac. Not able to select it still!

**Comment by hol353** [comment]
2 options:

1. Can you type the name of the .xlsx file into the box rather than trying to browse to it?
2. If the above doesn't work, then you can put the .apsimx into a text editor (e.g. notepad) and manually enter the filename (with path) into the right place e.g.

```json
          "$type": "Models.PostSimulationTools.ExcelInput, Models",
          "FileNames": [
            "observed.xlsx"
          ],
```
