### ISSUE TITLE
Speed-up APSIM runtime

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#7621]

**Comment by jbrider** [comment]
@hol353 Could you check the Replacements functionality performance. I haven't had a chance to look at it more closely, but we were having no issue with it earlier in the year but now it appeared to be much slower to do some variable replacements (200ms runtime -> 1200ms runtime).
I will be looking at it soon to check it wasn't just a config issue, but thought I would mention it if you're looking at performance issues.

**Comment by hol353** [comment]
@jbrider I had a look at the Replacements functionality but nothing appeared out of the ordinary in the profiler. If it is still a problem, perhaps attach a simulation that I can profile.
