### ISSUE TITLE
Create play list of simulations

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#7635]
When developing and testing models we often want to run a set of simulations from the test set.  It is slow to run the full set but also slow to find and run the specific experiments (or treatments) we want to run.  
It would be handy if we could create a play list of simulations that we want to run.  Either by specifying a variable and running all simulations that have observed values for that variable.  Or selecting a sub set of simulations some how else.

**Comment by par456** [comment]
Looking into this, we're thinking of adding a playlist node that can be attached to simulations. It will have a view like a report where you can list the name of the simulations and experiments you want to run. You could also use wildcards * to select multiple simulations with similar names easily.

If you've got any other feedback to this, that would be helpful.
