### ISSUE TITLE
Failed attempt at upgrading an old NextGen file

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7640]
I need to open / upgrade a relatively old NextGen file, but I get this error:

![image](https://user-images.githubusercontent.com/39573622/202309359-0e178b93-4e3a-4a00-9458-87022a716684.png)

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Models
  StackTrace:
   at Models.Core.ApsimFile.JsonUtilities.RenameVariables(JObject node, Tuple`2[] changes) in C:\Users\jc837076\Documents\07_Repository\APSIM NextGen\Models\Core\ApsimFile\JsonUtilities.cs:line 672
```

**Comment by BrianCollinss** [comment]
[APSIM-NG.zip](https://github.com/APSIMInitiative/ApsimX/files/10026211/APSIM-NG.zip)

**Comment by zur003** [comment]
@BrianCollinss - There are actually some other conversion issues in this simulation. PR #7664 addresses enough of these to allow the file to be opened, but you will still find errors in the manager scripts - for example, Links to the old InitialWater model. These are difficult to upgrade automatically.

**Comment by BrianCollinss** [comment]
Thanks Eric. Yes, InitialWater is troublesome now. I was wondering, is there any way we can easily calculate each layer's initial soil moisture from the percentage of PAW (like in classic)? I can see it is possible in the GUI, but it is hard to write a script to do it without knowing how many layers there are, etc.

**Comment by hol353** [comment]
Not sure I understand the question but from a manager script you can set the fraction full in 'Water' and then read the resulting initial water values e.g. 

```c#
[Link] Water water;
...
water.FractionFull = 0.5;
double[] halfFullValues = water.InitialValues;
```
