### ISSUE TITLE
Error thrown when "Standard Toolbox" is selected

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7641]
On the latest update from GitHub, I open VS2022, run APSIM-NG in debug mode, and try to open "Standard Toolbox":

![image](https://user-images.githubusercontent.com/39573622/202313230-ed289a87-4e21-445f-b624-508e63e6da2a.png)

**Comment by zur003** [comment]
This is a duplicate of #7608

**Comment by BrianCollinss** [comment]
Cheers Eric. I'll close it then.
