### ISSUE TITLE
One crop exists, but there are two crops selectable in a manager script

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7642]
I have Wheat in the simulation, and another Wheat under "ModelOverrids". 

![image](https://user-images.githubusercontent.com/39573622/202313525-7e6b35c2-a66d-4a90-b5b2-df0d962afbe4.png)

**Comment by ric394** [comment]
@BrianCollinss What are trying to achieve? If you are trying to have a different cultivar here that would be a better option.
For now i'll put in a change that makes ModelOverride only work as a child of Plants.
