### ISSUE TITLE
Exception thrown when tried to move a node up

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7645]
I got this error several times today with different nodes under Leaf and Cultivars. They can be moved down, but not up.

![image](https://user-images.githubusercontent.com/39573622/202315107-fc45ff44-9e59-4578-836f-15fcc72a0838.png)

**Comment by peter-devoil** [comment]
I've noticed weirdness in this tree control under linux/debug. The Enabled flag seems flaky too. Release build is OK.

**Comment by zur003** [comment]
This may have just been fixed with PR #7634, which was merged about an hour ago. Can you test to see whether the problem has been resolved?

**Comment by peter-devoil** [comment]
Well, spotted, @zur003. Works properly again.

**Comment by BrianCollinss** [comment]
So far so good @zur003

**Comment by hol353** [comment]
Has this been fixed? If so, please close the issue.
