### ISSUE TITLE
Report does not identify a property that is added under ModelOverrides/Wheat

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7649]
It seems most of the GUI components do not identify the new nodes that are added under the ModelOverrides. I have added a new node to Grain called HeatFactor. But the report Properties window does not show it and the model does not run.

![image](https://user-images.githubusercontent.com/39573622/202352836-989b84cc-0afe-439c-84ea-40a59ad37084.png)

**Comment by hol353** [comment]
In your screenshot I can't see a ModelOverrides. The error says it can't find a HeatFactor function (which looks like a SubtractFunction) under GrainNumber.

**Comment by BrianCollinss** [comment]
Hi Dean. It's outside the screen above wheat. In general, anything I add to this Wheat under ModelOverrides doesn't appear and cannot be used in the gui, including new cultivars.
