### ISSUE TITLE
Interest in modelling heat/frost in wheat?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7660]
- I have ported a module we had developed in APSIM Classic for the impact of heat shocks on grain number and grain size (https://doi.org/10.1016/j.agrformet.2019.107889).
- I have combined two approaches to modelling the impact of frost on grain number and grain size.

Is there any interest in testing these modules with field data?

**Comment by hol353** [comment]
@JulianneLilley FYI
