### ISSUE TITLE
Non-zero yield with zero grains in wheat

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7661]
![image](https://user-images.githubusercontent.com/39573622/202587573-24859460-ab2d-471d-9841-0a8234a4168c.png)

**Comment by par456** [comment]
I had a go at reproducing this, but wasn't able to get the same result, Have you still got an apsim file that does this, or can you describe what caused your 0 yield in those two years.

**Comment by BrianCollinss** [comment]
It was with a much older version. Perhaps it has been fixed.

**Comment by par456** [comment]
Closing this for now. Reply with a comment if you spot it happening again and we can reopen the issue.
