### ISSUE TITLE
Running NextGen on Linux with Mono

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7662]
I used to run NextGen on the HPC system with a command like this:

```
singularity exec -B $TMPDIR:$TMPDIR --pwd $TMPDIR MySingularity.sapp mono /MyFolder/Models.exe
```

I just needed to have all the necessary EXE and DLL files in /MyFolder/.

Now, I get this error:

```
Cannot open assembly '/MyFolder/Models.exe': File does not contain a valid CIL image.
```

Does it have to do with using DotNet Core? Should I copy any other file as well?
What's the best way to run NextGen on Linux without needing to compile it on Linux?

**Comment by hol353** [comment]
APSIM Next Gen is a dot net core application and cannot be run using mono. Need to install .NET Core 3.2 (or later?)

**Comment by BrianCollinss** [comment]
Thanks Dean. With helps from Peter, I created a new profile in VS2022 and published the models project as a self-contained project and copied that onto the HPC system. I am testing it now. I hope this was what you meant. Cheers.
