### ISSUE TITLE
Setting XF does not update PAWC immediately

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7666]
User needs to click on the tree and then get back here to see the updated value of PAWC.

![image](https://user-images.githubusercontent.com/39573622/202842950-a0a4f63a-b335-4eb8-af9e-67e62f8d464d.png)

**Comment by ric394** [comment]
@BrianCollinss After changing the figure and pressing enter key, PAWC will update without reselecting the Physical node tree with the current APSIM next gen version.
