### ISSUE TITLE
SoilWater layer depths not setable

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#7670]
In the WaterBalance ('SoilWater') node of Soil, the layer depths cannot be edited and they are not copied from Physical.

**Comment by hol353** [comment]
Can you zip and attach a simulation file (.apsimx) where this is a problem? It makes it easier for us to reproduce the problem.

**Comment by sme016** [comment]
Here's a the Barley example [Example for SoilWater Issue.zip](https://github.com/APSIMInitiative/ApsimX/files/10100460/Example.for.SoilWater.Issue.zip), but this issue occurs everywhere I have looked so far, i.e. Standard Toolbox, Examples, and my own simulations. Thanks

**Comment by sme016** [comment]
Thanks, but now I notice that the ability to copy more than one value from a table in the Soil node has disappeared, e.g. copy all horizons of AirDry to LL15 in Physical.

**Comment by hol353** [comment]
Yes you are right. I hadn't noticed that either. Reopening the issue.
