### ISSUE TITLE
ModelOverrides is now being triggered on StartSimulation and EndSimulation

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#7671]
ModelOverrides is now being triggered on StartSimulation and EndSimulation to apply overrides (and cultivars?) and then undo the changes.
This works directly against the model used by ApsimServer that was based on running Apsim once to load everything into memory then change a few small parameters each run.

@hol353 Am I missing something in how to configure overrides to allow the previous/desired behaviour to work?

**Comment by hol353** [comment]
I'm surprised you're using ModelOverrides. It was only created a few months ago. How are you using it?

ModelOverrides was based on how the Cultivar class worked. At the end of the simulation it would 'Unapply' the overrides. I thought ModelOverrides would be roughly the same behaviour.
