### ISSUE TITLE
Rice Module

### ISSUE THREAD

**Issue by Janewanguimugo** [APSIMInitiative/ApsimX#7672]
Does the new APSIMX have a rice module?

**Comment by hut104** [comment]
Hi,
A prototype upland rice model is currently under development, but no rice model is currently available within the APSIM release.
________________________________
From: Janewanguimugo ***@***.***>
Sent: Monday, 21 November 2022 3:49 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Rice Module (Issue #7672)


Does the new APSIMX have a rice module?

**Comment by hol353** [comment]
Closing as there is already a GitHub issue about a rice model: #5197
