### ISSUE TITLE
Odd behaviours working in UI simulation tree

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7673]
I'm finding some odd behaviour working in the simulation tree lately.

- Tried to delete a folder model under the Simulations model. error in deleteModel as this.parent is null
- When enable/disable the strike through doesn't change but the enabled state does seem to change
- When I tried to disable a node the other day it acted on the parent node state.

**Comment by lie112** [comment]
It seems uninformed CLEM users may be adding folders below the Simulations model. This might be breaking logic. If this is not allowed, I suggest the valid parent for folders is changed so it doesn't include Simulations.  Given this is the NOT Parent of Type style not implemented in ValidParent attribute this might be tricky.

**Comment by lie112** [comment]
If you delete a model (delete key), the newly highlighted model is not ready to receive key strokes.
For example you cannot keep hitting delete to delete the highlighted model
This is true for other aspects too.
If you add a new model, it is not ready for the key strokes to move it up or down even though highlighted.
I'd suggest the tree view has lost focus in the process.

**Comment by lie112** [comment]
when clicking on models to delete, sometime the click is registered as a rename and after deleting the model, the parent is displayed in edit name mode.

**Comment by zur003** [comment]
@lie112 - Some of these issues sound like problems that should have been fixed with PR #7634. What version are you using?

**Comment by lie112** [comment]
I had a #7631 in my git history. I've pulled the latest. I'll see how I go repeating some of the problems.

**Comment by mpandreucci** [comment]
Hi.
I've also noted that when we past an extra node, for example 'Soil', into a simulation and delete the old node, you can't rename the pasted node (the pasted node is 'Soil1' and even if you try to rename it, it keeps returning to 'Soil1'.
This was happening a while ago. I'm using the latest version of APSIM NG.

**Comment by ric394** [comment]
I've tested the strikethrough, deleting issue, and focus issue and I can't recreate them with the version I'm currently using (7166).
I suggest upgrading.
In addition, I was not able to recreate the issue for @mpandreucci
