### ISSUE TITLE
Conditional reporting (if Clock.Today >= new DateTime(2011, 2, 21))

### ISSUE THREAD

**Issue by JodyBig** [APSIMInitiative/ApsimX#7680]
I have a long simulation which I'm reporting at harvest. However for the last few years I want to report daily output. I found in the report tutorial that it should be possible using something like this:
![image](https://user-images.githubusercontent.com/29561776/203651749-bcfa9e4a-28c4-448a-bc10-97e1e1f618ff.png)
If I paste this into the Reporting Frequency I get this error:
Failed to publish event SubscribeToEvents. Error from subscriber SubscribeToEvents.OnConnectToEvents --> Exception has been thrown by the target of an invocation. --> Invalid report frequency found: if Clock.Today >= new DateTime(2017, 1, 1) [Clock].EndOfDay
I have attached the apsimx file,
[ExperimentBased_Scenarios.zip](https://github.com/APSIMInitiative/ApsimX/files/10079342/ExperimentBased_Scenarios.zip)

**Comment by zur003** [comment]
@JodyBig - That looks like an error on the tutorial. I think it will work if you just drop the "if" at the start. That is, just use "Clock.Today >= new DateTime(2011, 2, 21)".

**Comment by JodyBig** [comment]
IS that worked. Thank you.
