### ISSUE TITLE
NextGen keeps requesting more CPUs than available on HPC

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7687]
```
#PBS -S /bin/bash
#PBS -N BrianCollins
#PBS -l select=1:ncpus=12:mem=200GB
#PBS -l walltime=48:00:00
```

```
=>> PBS: job killed: ncpus 14.92 exceeded limit 12 (sum)
```

**Comment by Keith-Pembleton** [comment]
Try setting the ncpus to the maximum available on the node.  On our HPC APSIM will take all the CPUs on a node irrespective of the ncpus we set so now we always request the maximum (our HPC jobs are big so it make sense for us to do this).

**Comment by BrianCollinss** [comment]
Do you mean there's a way to request maximum number available instead of specifying the exact number? 

If you mean setting the number to be equal to the maximum CPUs each node have, it will mean waiting in the line much longer as our HPC is quite busy and not huge. I wonder why APSIM (only Nextgen) goes for more than the number of CPUs requested. By definition, it must only see the CPUs requested, not all CPUs available.

**Comment by Keith-Pembleton** [comment]
I mean set the number to the maximum number on a node.  Yes waiting in line for longer is the trade off we make, but usually we would ask for the maximum cpus on a node anyway.  APSIM classic has the same behaviour.  I am not sure how it sees more CPU's than what is requested but it does.  Our HPC engineer suggested putting it inside a container and I think that is what UQ does (@peter-devoil will be able to confirm), but we have gone down that path yet.  

Another note of caution: watch for drive fragmentation.  We run APSIM on a temporary workspace that gets wiped every 30 days and copy back outputs to home directories because it fragments our drive.  It was with APSIM classic that we had this problem, but we have maintained the practice with nextgen.

**Comment by BrianCollinss** [comment]
Thanks Keith. I've been using UQ APSIM classic singularity (container) for long and never had this issue. Recently I get lots of failed jobs without any reason, but no issue with CPUs. 

I'll go with your solution till someone finds out why nextgen now sees all physically available CPUs instead of those requested. I used nextgen on UQ HPC (without a container, but it was not using Dot Net Core at the time) without this issue. Perhaps something was changed since or it has something to do with Dot Net Core, or something is wrong with JCU HPC.

**Comment by peter-devoil** [comment]
Classic used an environment variable to limit the job runner.

NG's Models has an arg 
```
  --cpu-count                    (Default: -1) Maximum number of
                                 threads/processes to spawn for running
                                 simulations.
```
(ie "-1" is all cpus) But I've never used it to be sure that another thread doesnt kick in when simulations are running (eg GC, DB writes etc)

**Comment by BrianCollinss** [comment]
@hol353 Hi Dean. Do you think there is an issue in NextGen? Should it be able to see all available CPUs, or just as many as requested?

**Comment by zur003** [comment]
Taking a quick look at the source code, NextGen first checks for a "--cpu-count" command line option. If that is not found, or is set to -1, it check for an environment variable "NUMBER_OF_PROCESSORS". If that is absent, it calls Environment.ProcessorCount, which is in the .Net system runtime library, then subtracts 1 from that value (if it's > 1). Exactly what the ProcessorCount property returns in containers isn't entirely clear to me, but there is a discussion to be found [here](https://github.com/dotnet/runtime/issues/48094).

**Comment by BrianCollinss** [comment]
Thanks Eric. I'll try these variable to see how it goes. Are there similar variables for memory? I've had a similar issue with the memory too.

**Comment by hol353** [comment]
There is no way to restrict memory usage. If you are running inside a docker container you can specify number of processors and memory available to the container. Singularity can probably do the same.

**Comment by peter-devoil** [comment]
Indeed there are [command line args](https://docs.sylabs.io/guides/main/user-guide/cgroups.html#command-line-limit-flags) to singularity that enforce limits in the same way as the HPC job runner. Apsim will still bomb when it exceeds that resource limit.

**Comment by hol430** [comment]
I note that this apsim CLI argument only affects the number of threads created for running simulations. We also have a garbage collector running in server mode, so you will also see one garbage collector thread for each logical(?) cpu available. You could try switching to workstation GC and setting the apsim cpu count argument to `nproc` - 2, but that will significantly reduce your simulation throughput for large values of nproc.

**Comment by BrianCollinss** [comment]
FYI, I set the **NUMBER_OF_PROCESSORS** (and I have always set **SINGULARITYENV_NUMBER_OF_PROCESSORS** 1-2 cores less than total) and hasn't had any issues since.

```
export NUMBER_OF_PROCESSORS=20
export SINGULARITYENV_NUMBER_OF_PROCESSORS=18
```
