### ISSUE TITLE
DB files are huge

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7690]
I am running a large ensemble of factorial simulations. Each APSIM file produces a DB file in excess of 13 GB. When I export the data into an RData file, it is only 3 MB. Am I doing something wrong? Is there anyway to compress the DB file, or somehow reduce its size?

**Comment by peter-devoil** [comment]
Noise in the summary "file"?

**Comment by BrianCollinss** [comment]
I double check. But I think I disabled summary.

**Comment by BrianCollinss** [comment]
It seems having an enabled Summary is compulsary!

**Comment by lie112** [comment]
You could try a VACUUM; query on the database in db browser, or try the tools/compress in db browser. If either of these can reduce the db file size they could be added to the ASPIM workflow when running saving the database. Is it obvious which section (table) is causing all the file size? Is it a data table or summary?

**Comment by BrianCollinss** [comment]
Thanks, Adam. The issue is keeping the files on HPC. I generate lots of +50GB files (for 40-year simulations). I am running another round with Summary verbosity set at 0 (errors only). I will let you know how this went.

**Comment by BrianCollinss** [comment]
FYI, I set the NUMBER_OF_PROCESSORS (and I have always set SINGULARITYENV_NUMBER_OF_PROCESSORS 1-2 cores less than total) and hasn't had any issues since.

```
export NUMBER_OF_PROCESSORS=20
export SINGULARITYENV_NUMBER_OF_PROCESSORS=18
```

**Comment by BrianCollinss** [comment]
Setting the Summary verbosity level at 0 reduced the size of the DB files significantly. Thanks for the help.
