### ISSUE TITLE
GUI freezes by clicking on Summary in a large factorial experiment

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7691]
I have >260K simulations in this template. GUI never unfreezes. DataStore is empty. Removing some of the factors fixes the issue.

![image](https://user-images.githubusercontent.com/39573622/204677364-41b84a7a-8fae-42cc-b18f-07894b6303d0.png)

**Comment by ric394** [comment]
@BrianCollinss Could you please attach this simulation so I can take a look please?

**Comment by ric394** [comment]
If this is continuing to give issues, perhaps running this simulation via the command line may help avoid the freezing issue.
You're welcome to reopen this issue if you have further questions or concerns.
