### ISSUE TITLE
Won't download .NET Core dependency

### ISSUE THREAD

**Issue by RyanKBailey** [APSIMInitiative/ApsimX#7694]
When installing APSIM next generation the installation wizard won't automatically download/install the .NET core dependency. Attempting to run APSIM will cause a popup to appear that states that .NET core isn't installed and asks whether the user wants to install it. However, clicking yes does nothing and I had to manually install .NET core. I tried installing the latest version of APSIM (7127) and encountered this issue. I also tried an earlier version of APSIM (7009) which had worked on another computer but still encountered this issue.

**Comment by zur003** [comment]
And now we also see Issue #7702, which may be related. @RyanKBailey  - a couple of questions for you:

1. What version of Windows is running on the machine where the installation failed?
2. Was the installation wizard on a network drive or a local drive?

**Comment by zur003** [comment]
@RyanKBailey - Thanks - that eliminates a couple of possibilities. One more question: are you using any anti-virus software beyond the Windows Defender stuff that comes with Windows?

**Comment by RyanKBailey** [comment]
Yes, I'm using Norton 360 Antivirus.

**Comment by tkd708** [comment]
I'm experiencing the same with the latest version (7147), any updates on this?

Regarding #7702, the installation of Gtk runtime seems successful but the program cannot start due to this error.

As a work around, do I just need to install .NET core separately? if so, does its latest version work or should I go for the earlier one like 3.1.?

**Comment by zur003** [comment]
The Apsim Windows installer currently attempts to download the Win64 .Net 3.1.14 runtime from [this URL](https://download.visualstudio.microsoft.com/download/pr/88437980-f813-4a01-865c-f992ad4909bb/9a936984781f6ce3526ffc946267e0ea/windowsdesktop-runtime-3.1.14-win-x64.exe). What do you see if you try going there from a web browser? Does the runtime installer .exe download as expected, and do you see any error or warning messages?

**Comment by tkd708** [comment]
@zur003, Thank you for your swift reply! I could download the installer from the provided URL and the installation enabled me to run APSIM NextGen. Hope this helps others too.
