### ISSUE TITLE
Expose the denitrification rate coefficient

### ISSUE THREAD

**Issue by JodyBig** [APSIMInitiative/ApsimX#7696]
Could the denitrification rate coefficient be exposed so to enable change?
By default the value is 0.0006 but there is evidence that higher rates are more suitable.
See:
Thorburn, P.J., Biggs, J.S., Collins, K., Probert, M.E., 2010. Using the APSIM model to estimate nitrous oxide emissions from diverse Australian sugarcane production systems. Agr. Ecosyst. Environ. 136, 343–350. https://doi.org/10.1016/j.agee.2009.12.014

**Comment by hut104** [comment]
Are you looking to suggest a new value in the release, or at this stage just change the value to evaluate other values?
If the later, the value is settable already (according to the code).  It has a really unhelpful name (misleading really).

If you look at the structure of the model in the UI, you should be able to navigate to this class and set the value below in a manager script.

I suggest that we raise another issue to rename the value to something more accurate.





using System;
using System.Collections.Generic;
using Models.Core;
using Models.Soils.Nutrients;

namespace Models.Functions
{
    /// <summary>Fraction of NO3 which denitrifies today</summary>
    /// \pre All children have to contain a public function "Value"
    /// \retval fraction of NO3 denitrified.
    [Serializable]
    [Description("Soil NO3 Denitrification model from CERES-Maize")]
    public class CERESDenitrificationModel : Model, IFunction
    {
        [Link]
        Soils.IPhysical soilPhysical = null;

        [Link(ByName = true)]
        INutrientPool Humic = null;

        [Link(ByName = true)]
        INutrientPool Inert = null;

        [Link(ByName = true)]
        INutrientPool FOMCarbohydrate = null;

        [Link(ByName = true)]
        INutrientPool FOMCellulose = null;

        [Link(ByName = true)]
        INutrientPool FOMLignin = null;


        [Link(Type = LinkType.Child)]
        CERESDenitrificationTemperatureFactor CERESTF = null;

        [Link(Type = LinkType.Child)]
        CERESDenitrificationWaterFactor CERESWF = null;

        /// <summary>
        /// Rate modifier on the CERES denitrification model. Default = 0.0006.
        /// </summary>
        public double DenitrificationRateModifier { get; set; } = 0.0006;

        /// <summary>
        /// Kludge
        /// </summary>
        public bool IsInertActive { get; set; } = true;


        /// <summary>Gets the value.</summary>
        /// <value>The value.</value>
        public double Value(int arrayIndex = -1)
        {
            if (arrayIndex == -1)
                throw new Exception("Layer number must be provided to CERES Denitrification Model");
            double ActiveC;
            if (IsInertActive)
                ActiveC = Humic.C[arrayIndex] + Inert.C[arrayIndex] + FOMCarbohydrate.C[arrayIndex] + FOMCellulose.C[arrayIndex] + FOMLignin.C[arrayIndex];
            else
                ActiveC = Humic.C[arrayIndex] + 0.0 + FOMCarbohydrate.C[arrayIndex] + FOMCellulose.C[arrayIndex] + FOMLignin.C[arrayIndex];

            double ActiveCppm = ActiveC/(soilPhysical.BD[arrayIndex] * soilPhysical.Thickness[arrayIndex] / 100);
            double CarbonModifier = 0.0031 * ActiveCppm + 24.5;
            double PotentialRate = DenitrificationRateModifier * CarbonModifier;

            return PotentialRate * CERESTF.Value(arrayIndex) * CERESWF.Value(arrayIndex);
        }

        /// <summary>
        /// Get the values for all soil layers.
        /// </summary>
        public double[] Values
        {
            get
            {
                if (soilPhysical == null)
                    return null;
                double[] result = new double[soilPhysical.Thickness.Length];
                for (int i = 0; i < result.Length; i++)
                    result[i] = Value(i);
                return result;
            }
        }
    }
}
________________________________
From: Jody Biggs ***@***.***>
Sent: Thursday, 1 December 2022 12:47 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Expose the denitrification rate coefficient (Issue #7696)


Could the denitrification rate coefficient be exposed so to enable change?
By default the value is 0.0006 but there is evidence that higher rates are more suitable.
See:
Thorburn, P.J., Biggs, J.S., Collins, K., Probert, M.E., 2010. Using the APSIM model to estimate nitrous oxide emissions from diverse Australian sugarcane production systems. Agr. Ecosyst. Environ. 136, 343–350. https://doi.org/10.1016/j.agee.2009.12.014

**Comment by JodyBig** [comment]
Hi Neil

I want to evaluate new values.
I can report the DenitrificationRateModifier using: [Soil].Nutrient.Denitrification.Rate.DenitrificationRateModifier
But I cannot find it in the model structure (See below)
 
![image](https://user-images.githubusercontent.com/29561776/205757487-69a4b9e9-0e10-4848-855e-3e110858cdbb.png)
