### ISSUE TITLE
Export to HTML is slightly broken

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#77]
The current "Export to HTML" option for a model component is generating HTML with an entry for "r>" in the Model Documentation section.
Also, it might be nice if exporting the HTML could include additional information depending on the module type. For example, SummaryFile could include the actual summary results.

**Comment by hol353** [comment]
The Export to HTML option is primarily for auto-documenting the models. Not sure if summary file contents would be useful or not.
