### ISSUE TITLE
The required Gtk runtime cannot be installed when installing the next generation of APSIM

### ISSUE THREAD

**Issue by zhuqianqian0907** [APSIMInitiative/ApsimX#7702]
I recently got a new computer (win11) and when installing the next generation of APSIM, "Setup has detected that the required Gtk runtime is not installed. Doyou wish to have it automatically downloaded (~50MB) andinstalled? The user interface will not run if this is not installed. Y or N "Then I click on Y, followed by" Error sending data:(12007) cannot resolve the name or address of the server ". It can't be installed all the time, but I don't have these tips on my old computer win10, it can be installed smoothly directly, why is this?

![1](https://user-images.githubusercontent.com/90237327/205480678-b77c6fe6-5d5b-4dc3-b966-b4dcd2af4bfd.png)
![2](https://user-images.githubusercontent.com/90237327/205480680-be323de1-4039-486f-9f20-03d5a9cbdd32.png)

**Comment by zhuqianqian0907** [comment]
> 我最近买了一台新计算机（win11），在安装下一代APSIM时，“安装程序检测到未安装所需的Gtk运行时。您是否希望自动下载（~50MB）并安装它？如果未安装，用户界面将不会运行。Y 或 N“然后我点击 Y，然后是”发送数据时出错：（12007） 无法解析服务器的名称或地址”。它不能一直安装，但是我的旧电脑win10上没有这些技巧，可以直接顺利安装，这是为什么？
> 
> ![1](https://user-images.githubusercontent.com/90237327/205480678-b77c6fe6-5d5b-4dc3-b966-b4dcd2af4bfd.png) ![2](https://user-images.githubusercontent.com/90237327/205480680-be323de1-4039-486f-9f20-03d5a9cbdd32.png)

I tried win10 can be successfully installed, but win11 seems not to work, always reported errors, should be win11 system is not compatible

**Comment by hol353** [comment]
To install GTK manually unzip  

https://github.com/GtkSharp/Dependencies/blob/master/gtk-3.24.24.zip

to:

C:\Users\<windowsusername>\AppData\Local\Gtk\3.24.24 

where <windowsusername> is your windows profile name. e.g. C:\Users\hol353\AppData\Local\Gtk\3.24.24

**Comment by par456** [comment]
Closing this for now, as this hasn't been reported by anyone else, and the manual install instructions should be enough to fix this.
