### ISSUE TITLE
How do you report Soil Organic Carbon?

### ISSUE THREAD

**Issue by soilmodel12** [APSIMInitiative/ApsimX#7709]
Is [Soil].Nutrient.TotalC - the total organic carbon? If not how do you report the organic carbon? I know [Soil].Organic.C - is only used for initialisations? And confirming that [Soil].Nutrient.TotalC does not include **inorganic carbon**.

**Comment by femiguez** [comment]
I think [Soil].Nutrient.TotalC at the moment includes FOM. However, you might want to subtract it. I don't think it includes inorganic carbon

**Comment by hol353** [comment]
Looking at the source code:
```
TotalC = Inert.C + FOMLignin.C + FOMCellulose.C + FOMCarbohydrate.C + Microbial.C + Humic.C
```
