### ISSUE TITLE
Deployment Issues (GTK Check)

### ISSUE THREAD

**Issue by GRDC-IT** [APSIMInitiative/ApsimX#7721]
Hi team,

We are attempting to package up APSIM NextGen to allow remote deployment to users, but are having issues with the 'gtk detection' part of the installer causing it to not install.
As the remote install process runs as the System account, and is attempting to run silently, we believe that the install freezes at the point where it would bring up the 'Would you like to download GTK 3.24" window.

1. Is there a command line switch to ignore this check? (We are installing GTK into the users profile seperately)
2. Alternatively, is there a build without this check?

Note: we have attempted to copy the GTK files to both the 'users' folder, and to the 'correct' system profile locations as per below, none of which have allowed the installer to complete.
1. "C:\Users\$username\appdata\Local\gtk-3.24.24"
2. "$env:LOCALAPPDATA\gtk-3.24.24"
3. "C:\Windows\System32\config\systemprofile\AppData\Local\gtk-3.24.24"
4. "C:\Windows\SysWOW64\config\systemprofile\AppData\Local\gtk-3.24.24"
If we run the package manually as an admin account (not possible through remote deployment), it works correctly with both locations 1 and 2 for the GTK files, and then APSIM installs silently.

Powershell code currently used.
```
#Define Global Variables
$user=(Get-WmiObject -Class Win32_Process -Filter 'Name="explorer.exe"').GetOwner().User
$username=$user.split(' ')[0]

#Copy GTK Files
if(Test-Path -Path "C:\Users\$username\appdata\Local\gtk-3.24.24") {} else {
    Copy-Item -Path ".\gtk-3.24.24" -Destination "C:\Users\$username\appdata\Local" -Recurse -Force
    log "$(Get-Date -format 'HH:mm:ss') - GTK files copied to C:\Users\$username\appdata\Local as required" }
if(Test-Path -Path "$env:LOCALAPPDATA\gtk-3.24.24") {} else {
    #  Copy-Item -Path ".\gtk-3.24.24" -Destination "C:\Windows\System32\config\systemprofile\AppData\Local" -Recurse -Force
    #  Copy-Item -Path ".\gtk-3.24.24" -Destination "C:\Windows\SysWOW64\config\systemprofile\AppData\Local" -Recurse -Force
    Copy-Item -Path ".\gtk-3.24.24" -Destination $env:LOCALAPPDATA -Recurse -Force
    log "$(Get-Date -format 'HH:mm:ss') - GTK files copied to $env:LOCALAPPDATA as required" }

#Delay
Start-Sleep -s 10

#Install APSIM
$cmd = 'Apsim-7130.exe'
$prm = "/VERYSILENT /LOG=c:\windows\logs\APSIM-NextGen-MSI.log /NORESTART /ALLUSERS"
$process = (Start-Process -Wait $cmd $prm -PassThru)

#Delay
Start-Sleep -s 20

#Clean up Desktop Shortcut file
Remove-Item -Force "C:\Users\Public\Desktop\APSIM*.lnk"
```

Thanks
GRDC IT Team.

**Comment by zur003** [comment]
The installer is basically testing for an installed copy of Gtk by looking for the existence of a folder at "$env:LOCALAPPDATA\Gtk\3.24.24", so what you're currently trying is very close to what should work. You should just need to change the path from `"$env:LOCALAPPDATA\gtk-3.24.24"` to `"$env:LOCALAPPDATA\Gtk\3.24.24"` (that is, a backslash where you currently have a dash).

**Comment by GRDC-IT** [comment]
Thanks heaps for the quick response...
I'll give that a go and advise.

**Comment by GRDC-IT** [comment]
That has worked.

For anyone else who is interested, to get the GTK files, I just performed a manual install, clicked yes on the prompt to download them, and then copied them from the user profile.
The GTK folder is put into the same folder as the APSIM installer, and the powershell file with the following code.

```
#Define Global Variables
$user=(Get-WmiObject -Class Win32_Process -Filter 'Name="explorer.exe"').GetOwner().User
$username=$user.split(' ')[0]

#Copy GTK Files
if(Test-Path -Path "C:\Users\$username\appdata\Local\gtk") {} else {
    Copy-Item -Path ".\gtk" -Destination "C:\Users\$username\appdata\Local" -Recurse -Force
    log "$(Get-Date -format 'HH:mm:ss') - GTK files copied to C:\Users\$username\appdata\Local as required" }
if(Test-Path -Path "$env:LOCALAPPDATA\gtk") {} else {
    Copy-Item -Path ".\gtk" -Destination "C:\Windows\System32\config\systemprofile\AppData\Local" -Recurse -Force
    #  Copy-Item -Path ".\gtk" -Destination "C:\Windows\SysWOW64\config\systemprofile\AppData\Local" -Recurse -Force
    #  Copy-Item -Path ".\gtk" -Destination $env:LOCALAPPDATA -Recurse -Force
    log "$(Get-Date -format 'HH:mm:ss') - GTK files copied to $env:LOCALAPPDATA as required" }

#Delay
Start-Sleep -s 10

#Install APSIM
$cmd = 'Apsim-7130.exe'
$prm = "/VERYSILENT /LOG=c:\windows\logs\APSIM-NextGen-MSI.log /NORESTART /ALLUSERS"
$process = (Start-Process -Wait $cmd $prm -PassThru)

#Delay
Start-Sleep -s 20

#Clean up Desktop Shortcut file
Remove-Item -Force "C:\Users\Public\Desktop\APSIM*.lnk"
```
Note: You will need to package "Windows Desktop Runtime 3.1.x" and make it a pre-req for APSIM NextGen...
Note2: When using the '/verysilent' the installer possibly should skip these checks, but it definitely should not be trying to pop up a "Message box (Yes/No):" window.

Thanks again for the assistance, and I hope this helps others.

**Comment by GRDC-IT** [comment]
Upon further testing, it only works if I manually copy the files to "C:\Windows\System32\config\systemprofile\AppData\Local".
It seems that both CMD.exe and Powershell.exe are unable to access this location as they both redirect the files / query / etc. to "C:\Windows\SysWOW64\config\systemprofile\AppData\Local".

Any assistance you may be able to give in getting the app to install using a system account, without the files manually copied to "System32" would be greatly appreciated.

**Comment by GRDC-IT** [comment]
Looks like old school DOS commands have come to the rescue...
I really didn't think I'd still be needing this part of my brain today. :)

Created a Batch file with the following
```
Set ORIGINALPROFILE=%USERPROFILE%
Set USERPROFILE=C:\Windows\syswow64\Config\SystemProfile
Start "" /b /wait powershell.exe  -ExecutionPolicy Bypass -File "./APSIM - Install.ps1"
Set USERPROFILE=%ORIGINALPROFILE%
```
Seems to work in a Command Prompt launched with RunAsSystem.
Hopefully the final package works the same way.


My guess is that the installer was just looking at the %userprofile% path, which, even on a 64bit os, points to System32.
Unfortunately, whilst navigating to, and modifying the 'system32' profile does not work in command window, nor in powershell, it seems to work in an app space.

Current Powershell Script.
```
#Define Global Variables
$user=(Get-WmiObject -Class Win32_Process -Filter 'Name="explorer.exe"').GetOwner().User
$username=$user.split(' ')[0]

#Copy GTK Files
if(Test-Path -Path "C:\Users\$username\appdata\Local\gtk") {} else {
    Copy-Item -Path ".\gtk" -Destination "C:\Users\$username\appdata\Local" -Recurse -Force }
if(Test-Path -Path "$env:LOCALAPPDATA\gtk") {} else {
    Copy-Item -Path ".\gtk" -Destination $env:LOCALAPPDATA -Recurse -Force }

#Delay
Start-Sleep -s 10

#Install APSIM
$cmd = 'Apsim-7130.exe'
$prm = "/VERYSILENT /LOG=c:\windows\logs\APSIM-NextGen-MSI.log /NORESTART /ALLUSERS"
$process = (Start-Process -Wait $cmd $prm -PassThru)

#Delay
Start-Sleep -s 20

#Clean up Desktop Shortcut file
Remove-Item -Force "C:\Users\Public\Desktop\APSIM*.lnk"
```
