### ISSUE TITLE
Values in "Physical" module change by themselves

### ISSUE THREAD

**Issue by ElsaLagerquist** [APSIMInitiative/ApsimX#7722]
Hi!
Today when I have tried to run some APSIM Next Generation files the values in the "Physical" module change by themselves. It did not happen the first two-three times I ran the simulations but now it seem to happen for any file. It is the decimal sign which is moved to that the value becomes 1000x larger for each time I run the simulation. If I try to change the values manually they keep on changing each time I move from one cell to another.

In December I did an update of APSIM so the version I have now is 12.7130.0, which should be the latest version. I'm located in Sweden, if region could have an impact. I have used both Swedish and Australian region and time and have the same issue with both. Earlier running APSIM NG have worked equally well with both settings.

Quite recently I started running APSIM via R, if this bug could somehow be related to that. However, I have been able to use the interface before although I was also running APSIM via R.

Is this a problem anyone is familiar with and know how to solve?

Best regards,
Elsa

**Comment by Dan-vale** [comment]
Hi Elsa! 
I had the same problem, until I read on the APSIM website that those bugs can be eliminated when you change your regional settings to Australia: https://support.microsoft.com/en-us/office/change-the-windows-regional-settings-to-modify-the-appearance-of-some-data-types-edf41006-f6e2-4360-bc1b-30e9e8a54989
Hope it helps us as well! 
Best, Danila

**Comment by hol353** [comment]
Is this still a problem? Recent changes to the soil grid controls may have fixed this.

**Comment by ElsaLagerquist** [comment]
Hi Danila and Dean,
Thank you Danila for your tip, it worked for me as well! 
Now I can run APSIM with both Australian and Swedish settings. The recent changes to the soil grid controls may have contributed to that.
Best,
Elsa
