### ISSUE TITLE
What on earth is going on with the initial water content?!?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#7739]
This is what it looks like to start with:
![image](https://user-images.githubusercontent.com/12176269/214450805-9e2e74ab-97f3-4a4f-87f6-00f4dadb0dfe.png)

Then I enter a "7" in the "Percent full" box and get - of all things!!!
![image](https://user-images.githubusercontent.com/12176269/214450996-abd18b80-0320-4246-8d2a-868857f090ae.png)

The I use the backspace key to remove the final "2" of the 112 that I did not enter and get (note where my cursor ends up - might assist with the bug fixing?)
![image](https://user-images.githubusercontent.com/12176269/214451105-f7e8a9e6-facc-4644-8276-6b56bb317f2a.png)

**Comment by hol430** [comment]
This may be fixed by #7667, which fixes a comedy of errors in this area of the GUI. I'll try and finish that PR in the next few days...

**Comment by zur003** [comment]
There is still some quirkiness, even after applying #7667. Trying to enter a value for percent full can result in a value appearing that is different from the one entered. I think (but haven't completely confirmed) that this may happen when the soil water layers don't correspond with the "physical" layers.
