### ISSUE TITLE
WEIRD PROBLEMS with the SOIL MODULE

### ISSUE THREAD

**Issue by daianfrancia** [APSIMInitiative/ApsimX#7742]
Hi everyone. I found a problem with most of the tabulated parameter setting in the soil module. The issue is the same as in [#7525](https://github.com/APSIMInitiative/ApsimX/issues/7525), but it doesn't seem to have been solved. The thing is, when changing any value, the rest of the values are multilplied and the problem continues even after erasing the whole table. The worst thing is that I just found this issue with the latest version and can't go back to an older one since files won't open. 

Thanks in advance.

**Comment by guillemodon** [comment]
I'm having the same issue, anyone can help??

**Comment by daianfrancia** [comment]
Just solved it by changing decimal and thousand config in regional config. fiuu!

**Comment by daianfrancia** [comment]
Just solved it by changing decimal and thousand config in regional config. fiuu!
