### ISSUE TITLE
Add an emergence event from the wheat model

### ISSUE THREAD

**Issue by hanrahs** [APSIMInitiative/ApsimX#7743]
I have a manager script that by specifying a variable and then the value of that variable it will trigger a management event or countdown until a management event (ie fertiliser after 10 days, irrigate today etc) .

example
Specify the name of a variable 
[Wheat].Phenology.Zadok.Stage

Specify the value of that variable to trigger management 
30

and this will cause my fertilising or irrigation to occur at the correct times.

It works fine with any variables like Zadok.Stage where the value is a double. But I would also like to use it with EmergenceDAS which seems to be an onEventTrigger.

just going to add some correspondence from Dean:
I can't get the emergence event working either. EmergenceDAS isn't doing what I thought it would. Plus APSIM doesn't publish an 'emergence' event.  Can you add a GitHub issue into our ApsimX repo asking for an emergence event from the wheat model?

**Comment by hol353** [comment]
Hi @hanrahs can you attach your simulation if you still have it? Alternatively, can you attach your manager script that sets a variable value?

**Comment by hol353** [comment]
[FertiliseDaysAfterZadockSrage.zip](https://github.com/APSIMInitiative/ApsimX/files/11266953/FertiliseDaysAfterZadockSrage.zip)

**Comment by hol353** [comment]
I have added 2 manager scripts into the management toolbox - one for fertilising on a variable value threshold and another for fertilising on an event (e.g. [Wheat].Phenology.PlantEmerged)
