### ISSUE TITLE
Intercropping vs Strip cropping using zones

### ISSUE THREAD

**Issue by hanrahs** [APSIMInitiative/ApsimX#7744]
Just wondering on the differences and when I should be using each. 

If I want to simulate alternating rows of a cereal and a pulse for example, should I use narrow zones set up similar to the one in the  MicroClimate validation test but with each zone essentially being the width of the row spacing, or would the intercropping built into MicroClimate and the  SoilArbitrator cover this. My first thought was that the intercropping here was more of a mixture rather than 2 rows but I can't find any documentation to confirm.

The validation test shows how to set up the roots across zones, is there anything that needs to be done above ground allowing the canopy to share space or shading/height, etc.

If I don't need zones for the above, at what point do I, 2 rows of each, a certain width, other factors like height differnces?

Thanks

**Comment by hut104** [comment]
For many systems with alternating rows, canopies become mixed (ie leaves extend over the next row).  I would not use the strip crop model for these.  The strip model assumes basic hedge rows (rectangular) with the leaves of each crop confined to those hedges (ie not mixed).  So, I would agree with your initial assessment.
For mixed canopies, there is nothing required, other than to sow two crops into the one zone.  Microclimate will look after the mixed canopy, soil arbitrator will deal with the below-ground competition.  One zone will do for mixed intercrops.
The answer to the final question is a little subjective and will depend on individual crops.  e.g. maize may have much wider row spacing than wheat and so geometry is influenced by crop type.  You may be able to get a feel for this by looking at the tests for microclimate's strip crop model.  The measured data may give you a feel for how important it may be.  Alternatively, run the model as a few thought experiments to see if the model is sensitive at all for the types of situations you are dealing with.
