### ISSUE TITLE
Running Apsim in Colab in new version doesn't work any more.

### ISSUE THREAD

**Issue by megpaiop** [APSIMInitiative/ApsimX#7757]
Hello,
For some time now I used to try Apsim in Colab by installing it and using this command:
subprocess.run(['mono','/usr/local/lib/apsim/2021.8.31.6677/bin/Models.exe','/usr/local/lib/apsim/2021.8.31.6677/Examples/'+'Wheat.apsimx'],stdout=subprocess.PIPE)
However, since the new Colab doesn't use the Models.exe anymore, and in fact it is a completely new version written in Dotnet, this line doesn't work.
How can I run the new Apsim in Colab env?

**Comment by peter-devoil** [comment]
a) You'll have make sure apsim is installed in your colab runtime - perhaps you set up a local runtime previously? b) You dont need mono, nor the .exe bit in Models,  c) you should be ok with something like ```subprocess.run(['/usr/local/bin/Models','/usr/local/lib/apsim/X.Y.Z/Examples/' + ...```

**Comment by peter-devoil** [comment]
Yes, for quite a while now.
