### ISSUE TITLE
Weather download error (NASA POWER w)

### ISSUE THREAD

**Issue by GNISUD** [APSIMInitiative/ApsimX#7760]
Hi, 

I got an error downloading weather data using the **Weather downloader**. The data source was **NASA POWER w/ CHIRPS rainfall (Global)**. I tried the **latest version (2023.1.7136.0)** and an old one, and there were errors in both (The old version only had an error dialog). 
```
Cannot find the expected header in weather file: D:\weather.met
```
The contents of the **.met** file are as follows
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

```
Thank you.

**Comment by GNISUD** [comment]
> It's possible you may be choosing dates outside of the range available from the servers. The rainfall is only available 45 days prior to today and the NASAPower is a couple days ago. Narrow your search.

For example, the date I selected was from **2021-01-01** to **2021-12-31**, but there is still an error. 

![SDQPK9OMAE@S%M`B0(PQ9Q3](https://user-images.githubusercontent.com/51102482/216917295-9c45906e-065d-475d-9c3f-1fe03b70db87.png)

There is only the following content in the met file. Is it my network problem?

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Thank you!

**Comment by her123** [comment]
There was an issue with the intermediate server. It is now resolved. You can test this again now.

**Comment by Yuval-Sadeh** [comment]
I am experiencing the same issue.
"Cannot find the expected header in weather file: "

Additionally, why the rainfall is only available 45 days prior to today and the NASAPower is a couple days ago? How can you simulate a growing in-season with weather data ?

![image](https://user-images.githubusercontent.com/101714083/217129905-ad7d8139-46b0-47b1-a285-2bad12ecbaf3.png)


Thanks

**Comment by her123** [comment]
My fix required another. It is working now. 
The reason the rainfall can be dated up to 45 days before today is because the CHIRPS provider processes and validates their data and releases it around the 18th day of every month. They do release unchecked data close to the current date but we have not used it in this service.

**Comment by GNISUD** [comment]
It's working fine now. Thank you!
