### ISSUE TITLE
APSIMx Functions

### ISSUE THREAD

**Issue by Janewanguimugo** [APSIMInitiative/ApsimX#7761]
I requested APSIMx for the following information
Sum of [Weather].Rain from [Soybean].Sowing to [Soybean].Harvesting as InCropRainfall
Sum of [Weather].Rain from [Soybean].Sowing to [Soybean].Flowering as InCropSFRainfall
Sum of [Weather].Rain from [Soybean].Flowering to [Soybean].Harvesting as InCropFMRainfall

I would expect **InCropRainfall** to be different from  **InCropSFRainfall**. I would also expect the amount of rainfall from sowing to harvesting to be the highest ...however **InCropFMRainfall** has the highest rainfall amount yet it is supposed to return rainfall totals from flowering to harvesting.![image](https://user-images.githubusercontent.com/103818039/216896417-eaca064e-a177-4ac6-931f-f8345686a433.png)

**Comment by Janewanguimugo** [comment]
The issue only comes up with the Soybean module...even the example

**Comment by ric394** [comment]
@Janewanguimugo Could you please attach the apsimx file so we can try and reproduce the problem.

**Comment by Janewanguimugo** [comment]
I used the example that comes with the GUI...I didn't change anything except add the function to return rainfall, temperature etc
[soybean.zip](https://github.com/APSIMInitiative/ApsimX/files/10696758/soybean.zip)
The same using the maize module gives good results

**Comment by ilhuber** [comment]
Seems like this has to do with the stage names in the Soybean model not being what is expected in Plant.cs:

https://github.com/APSIMInitiative/ApsimX/blob/9bb22f8dc26456eeb0a682e12b2475e2238a306f/Models/PMF/Plant.cs#L309-L310

A quick way to work around this issue would be to use a Replacements folder and rename the phases for Soybean there. Unfortunately a lot of different parts of the PMF portion of the Soybean model refer to this phase by name, and all will need to be kept in sync with the renaming. A fast way to accomplish that would be to copy the soybean model (from replacements) into a text editor, use find/replace (changing StartFlowering to Flowering or similar) and then paste this back into replacements. 

This is an immediate solution to these problems, but is not a great long term fix.

**Comment by Janewanguimugo** [comment]
I am not sure how to do this...Kindly assist am I to action the above solution?

**Comment by Janewanguimugo** [comment]
Hello, was this fixed?

**Comment by ilhuber** [comment]
[Replacements.txt](https://github.com/APSIMInitiative/ApsimX/files/10926176/Replacements.txt)
I've attached a text file containing some .json (the format that .apsimx files are specified in) that defines a Replacements folder containing a version of the Soybean model with StartFlowering renamed to Flowering wherever it occurred. Pasting this text into the Apsim UI with the Simulations node highlighted should add it as a child.

Open the file in notepad or a similar text editor, select all and copy, then in the Apsim UI (in the Simulation tree pane on the left) right click on Simulations and select Paste. Replacements ought to show up as a new folder at the bottom of your simulation tree. If you already had a Replacements folder it will show up as something like Replacements1, in which case you should add the Soybean inside of the new Replacements1 folder to the older Replacements folder.

**Comment by Janewanguimugo** [comment]
Thank you, it now works!
