### ISSUE TITLE
New documentation changes not reflected in Netlify site

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#7762]
After updating and merging the documentation for how to contribute and removing some of the older folders and pages (source tree and CLI) the changes are not reflected in the APSIM Netlify site.

I thought that any changes to the files automatically changed the Netlify site. Is there a way to manually force an update? or does anyone know how to work around this issue?

**Comment by ric394** [comment]
Issue resolved after a successful merge of a subsequent pull request.
Issue was caused by not using a `resolves #1234` comment in the pull request. Omitting the comment caused Netlify to avoid updating the site.

**Comment by hol430** [comment]
The docs should be updated every time a new release of apsim is generated, which should occur every time a "resolves" pull request (ie a pull request which fixes an issue) is merged.

However, there seems to be an intermittent [fault](https://jenkins.apsim.info/blue/organizations/jenkins/apsim-release/activity/) in the release builds; [some jobs](https://jenkins.apsim.info/blue/organizations/jenkins/apsim-release/detail/apsim-release/176/pipeline/) are failing with errors like this:

```
/usr/share/dotnet/sdk/7.0.102/NuGet.targets(132,5): error : Failed to download package 'HarfBuzzSharp.2.6.1.4' from 'https://api.nuget.org/v3-flatcontainer/harfbuzzsharp/2.6.1.4/harfbuzzsharp.2.6.1.4.nupkg'. [/tmp/ApsimX/ApsimX.sln]
/usr/share/dotnet/sdk/7.0.102/NuGet.targets(132,5): error : The download of 'https://api.nuget.org/v3-flatcontainer/harfbuzzsharp/2.6.1.4/harfbuzzsharp.2.6.1.4.nupkg' timed out because no data was received for 60000ms. [/tmp/ApsimX/ApsimX.sln]
/usr/share/dotnet/sdk/7.0.102/NuGet.targets(132,5): error :   Exception of type 'System.TimeoutException' was thrown. [/tmp/ApsimX/ApsimX.sln]
```

I don't know for sure why this is happening, but it seems to be more common in the release builds and in the unit tests stage of the regular builds, but not in the main testing stage of the regular pull request CI builds. I note that `dotnet restore` will by default attempt to restore all projects of a solution in parallel. My theory is that in build contexts with a limited number of CPUs (ie release builds/unit tests), some threads of the parallel restore are not getting enough CPU time and the downloads on those threads are timing out.

One way to test that theory would be to disable the parallel restore. E.g. edit the CI scripts, changing `dotnet build` to something like this:

```
PARALLEL=
if [ `nproc` -lt 8 ]
    PARALLEL=--disable-parallel
fi
dotnet restore ${PARALLEL}
dotnet build
```

Of course that's just a guess - I could be totally wrong there..

**Comment by ric394** [comment]
@hol353 This would be worth investigating.
