### ISSUE TITLE
Mac installs broken?

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#7765]
Can anybody verify that the mac installer is working? A current install (7137) won't start, but from last year (7130) does.

It appears the dotnet runtime isnt being installed: ![image](https://user-images.githubusercontent.com/1924386/217417266-67b30876-add7-40e4-ab53-934e5f046cd9.png)

**Comment by Hull4Progress** [comment]
I am also finding that apsim-7143 on my Mac with Ventura 13.2 is not launching on my Mac.  I am running Ventura 13.2, but I had also tried on Ventura 13.1.  I have disabled the Gatekeeper with its security blocks on my Mac. When I click to open the app (which landed in /Volumes/APSIM2023.2.7140.0/APSIM2023.2.7140.0.app) a bouncing icon appears on my docker tray for a few seconds, but then disappears. Has anyone else successfully run the apsim on the Ventura OS? Thx

**Comment by hol353** [comment]
I have merged PR #7776. @Hull4Progress: Can you please download the new APSIM installation and try again?

**Comment by Hull4Progress** [comment]
Hi Dean - thank you so much for working on issues 7776 and 7765.  I downloaded the latest version (2023.2.7147) and it successfully launched on my mac.  

BTW, I have recently discovered some of your papers and software on crop modeling and APSIM - it is really an impressive body of work!
