### ISSUE TITLE
apsimx: edit_apsim()  

### ISSUE THREAD

**Issue by JF888666** [APSIMInitiative/ApsimX#7779]
Recently, I was using the apsimx() package to build a maize growth model, and I was able to edit the "Weather" and "Clock" module information changes in the Maize.apsim file smoothly using the edit_apsim() function. However, maize varieties, management information, etc. cannot be modified because there is no modification path. Please help!

**Comment by ric394** [comment]
Hi @JF888666, could you please provide more information/pictures detailing what you are trying to do and I will be able to assist.

**Comment by JF888666** [comment]
Okay, thanks！I tried to modify the maize planting information (variety, planting mode, sowing time, harvest time, density, and row spacing) using the edite_apsim() function, and each of the above parameters can be modified individually. Unfortunately, when the next parameter modification is confirmed, the previous modified parameter is returned to the original state when it was not modified. For example, I first modified the maize variety information, by confirming that the maize variety was changed from sc401 to Zhengdan958, and then I modified the maize planting method from sole to strip intercropping, and the modification result was also confirmed, at this time there was a result that I did not want to see, the modified maize variety information changed to sc401. I don't know how to deal with this situation, please help me！
The picture (1-1~3) shows the process of modifying and confirming the information of maize varieties and planting mode
![1-1](https://user-images.githubusercontent.com/103365891/218627080-0357cb81-fc47-43a5-a317-ec4dcb825db1.png)
![1-2](https://user-images.githubusercontent.com/103365891/218627049-a213e70d-7154-4da7-b3bf-18dee5455c57.png)
![1-3](https://user-images.githubusercontent.com/103365891/218626994-f3205c6e-a3b2-4093-addf-c2c506808eab.png)

**Comment by JF888666** [comment]
Okay, thanks！@ric394 (https://github.com/ric394), @hol353

I tried to modify the maize planting information (variety, planting mode, sowing time, harvest time, density, and row spacing) using the edite_apsim() function, and each of the above parameters can be modified individually. Unfortunately, when the next parameter modification is confirmed, the previous modified parameter is returned to the original state when it was not modified. For example, I first modified the maize variety information, by confirming that the maize variety was changed from sc401 to Zhengdan958, and then I modified the maize planting method from sole to strip intercropping, and the modification result was also confirmed, at this time there was a result that I did not want to see, the modified maize variety information changed to sc401. I don't know how to deal with this situation, please help me！

The picture (1~3) shows the process of modifying and confirming the information of maize varieties and planting mode
![1-1](https://user-images.githubusercontent.com/103365891/218629667-02e2f34f-8dc3-4b5c-92a2-97fdd11602b9.png)
![1-2](https://user-images.githubusercontent.com/103365891/218629687-e483b043-babd-4044-b9b9-54fb545cd6f0.png)
![1-3](https://user-images.githubusercontent.com/103365891/218629703-72f4bf9b-cea4-4b08-99ef-379e4978aed2.png)

**Comment by ric394** [comment]
@JF888666 It looks like on your second edit you've edited 'Maize.apsim' instead of 'Maize-edited.apsim'.
I think you intended to edit 'Maize-edited.apsim' which had the cultivar set to Zhengdan958.

**Comment by JF888666** [comment]
@ric394 (https://github.com/ric394)
   Thank you very much, this problem is solved according to what you said. Every time I run apsim(), there will be the following prompts. I don't know how to solve it?

![3](https://user-images.githubusercontent.com/103365891/218649300-7acd775b-43b0-4390-97ef-89c91c7d2cbe.png)

**Comment by JF888666** [comment]
Hi, Rich
Thank you for your advice, the last problem was solved according to what you said. At the moment, I still have a problem, every time I run apsim (Maize.apsim), An error about In APSIM Classic you can only run a file from the current directory is reported, maybe you can help solve this problem, could you give me some help? I will be grateful!
----- 原始邮件 -----
发件人：Julian Rich ***@***.***>
收件人：APSIMInitiative/ApsimX ***@***.***>
抄送人：JF888666 ***@***.***>,  Mention ***@***.***>
主题：Re: [APSIMInitiative/ApsimX] apsimx: edit_apsim()   (Issue #7779)
日期：2023年02月14日 11点55分


@JF888666 It looks like on your second edit you've edited 'Maize.apsim' instead of 'Maize-edited.apsim'.

I think you intended to edit 'Maize-edited.apsim' which had the cultivar set to Zhengdan958.

&mdash;

**Comment by ric394** [comment]
@JF888666 is "Maize-edited-ab.apsim" in the current working directory? if not, could you please try moving the file to that location. Let me know how you go.

**Comment by JF888666** [comment]
Hi, ric394
Thank you very much for your advice, I made some wrong settings that caused the computer not to recognize the file, and now the problem has been solved.
