### ISSUE TITLE
Too few decimal places in RH column of tables in documentation

### ISSUE THREAD

**Issue by ben-mallee** [APSIMInitiative/ApsimX#7799]
Just noticed in the wheat model documentation that the right hand column of most tables (haven't done an exhaustive survey) only shows numbers with one decimal place. Doesn't work well for N concentrations etc. where 0.05 shows as 0.1 eg section 1.6.6.4 Nitrogen Demand.

**Comment by par456** [comment]
This was resolved by #7976
