### ISSUE TITLE
Fodder Beet Model

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#78]
Fodder Beet model needed

**Comment by HamishBrownPFR** [comment]
@RobZys if you put up a pull request now that:
1. Removes the fodder beet model from replacements (it is in a number of .apsimx files so will need to search to make sure you get them all)
2. Adds a fodderbeet.json file into the resources
3. Includes a simple example in the examples folder
4. tidies up the auto doc as requested by @hol353 in #1845 
5. deal to any other needed so Dean can merge the pull request
Once it is all running clean I think this is ready for release.
@sarahcleary are you happy that all reference pannel requirements have been met and this can be merged

**Comment by sarahcleary** [comment]
thanks @HamishBrownPFR.  Yes, as per the RP meeting yesterday https://github.com/APSIMInitiative/ReferencePanel/issues/27 - I understand if the above is done, the RP is happy for Fodder Beet to be put in release.

**Comment by sarahcleary** [comment]
In release
