### ISSUE TITLE
edit_apsim() function

### ISSUE THREAD

**Issue by JF888666** [APSIMInitiative/ApsimX#7805]
Dear friends
I have encountered a problem recently， I edited the Weather, Clocks and Crop management information in the Maize.apsim file using the edited_apsim( ) function. Unfortunately, the operation results of apsim(Maize-Edited.apsim) are the same as apsim(Maize.apsim). Please give me help！！

    Best Regards

**Comment by ric394** [comment]
Hi @JF888666 could you show me what you did so I can see what is happening with your issue? Screenshots are very helpful.

**Comment by JF888666** [comment]
Dear ric394
Thank you very much for your help. There are 4 pictures in total here, the first picture is the summary result of the original Maize.apsim file operation, the second and third pictures are displayed on the results of the original Maize.apsim file editing Weather and Clock results, the fourth picture states that the crop management information of the Maize.apsim file is also modified, the specific process is omitted. We got a new Maize-abcdefgh.apsim file and run with apsim () function. The operation results are consistent with the running results of the original Maize.apsim.

![1](https://user-images.githubusercontent.com/103365891/220003974-e77b22f5-f7ed-43f1-9285-daf3b4184b7c.png)
![2](https://user-images.githubusercontent.com/103365891/220003993-66a18fc2-4dbe-4ed4-b3e7-a03a192a8924.png)
![3](https://user-images.githubusercontent.com/103365891/220004006-308683a5-99ed-4f31-8c10-35e9666394a7.png)
![4](https://user-images.githubusercontent.com/103365891/220004022-5183402e-314b-461b-9733-c7b0b11e3f1e.png)

**Comment by ric394** [comment]
@JF888666 could I see the details for "maize-abcdefgh.apsim" please?

**Comment by JF888666** [comment]
Dear ric394
I uploaded the Maize-abcdefgh.apsim file. Unfortunately, the model results have not changed. Please take a look at what went wrong, thank you！

[Maize-abcdefgh.txt](https://github.com/APSIMInitiative/ApsimX/files/10830785/Maize-abcdefgh.txt)

**Comment by femiguez** [comment]
@ric394 @JF888666 I'll look at this. This question is about the apsimx R package, which is separate from the APSIM software. Please in the future post these questions to https://github.com/femiguez/apsimx

**Comment by femiguez** [comment]
@JF888666 This question is about APSIM Classic, and this github is for Next Gen. For your first attempt, I was able to modify the clock as long as you do one parameter at a time. So this works for me.

```
inspect_apsim("Maize.apsim")

edit_apsim("Maize.apsim",
           node = "Clock",
           parm = "start_date",
           value = "01/02/2021",
           edit.tag = "-a")

inspect_apsim("Maize-a.apsim")
```
As for the second edit, it looks like it work just fine, so I don't know how to help you with that.

**Comment by par456** [comment]
Closing this, as a solution has been provided, and further questions should go over on the relevant Github repo.
