### ISSUE TITLE
Download soil placename means postcode

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#7822]
Using the Eucalyptus example, for example, downloading an Australian soil in a simualtion using right-click on a Zone and providing place name 'Mount Gambier' returns no soils, but justing using it's postcode '5290' does.  A quick fix would be to change the input required to Postcode, but providing place name and postcode options would be more useful.

**Comment by ric394** [comment]
@sme016 Using place names does work for many places. It's unfortunate in this instance that it was not successful.
I was also able to find soils by appending "SA" to "Mount Gambier" in the Place name field:
![image](https://user-images.githubusercontent.com/123442863/220829844-29ddd85a-0647-4a72-8268-79d8ef3d43df.png)
It seems adding state information helps in locating relevant soils. 
I hope this helps in your future searches.

**Comment by sme016** [comment]
Thanks for looking at this. Perhaps all that is needed for a bit more clarity is to change 'Place name' to 'Place name, postcode, state'
