### ISSUE TITLE
Downloaded synthestic SLGA soil has no initial water values

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#7823]
A downloaded synthestic SLGA soil has no initial water values. For example, this one is for postcode 7007: 
![image](https://user-images.githubusercontent.com/49378212/220773046-02c2cac5-4b94-4b9e-bbe1-013299a7387f.png)

**Comment by ric394** [comment]
@APSIMInitiative/soil Is this something we can have corrected with APSOIL or another relevant party?

**Comment by hol353** [comment]
We don't want to put Initial Water nodes into APSoil. Instead we just need to change the GUI soil download form to add them when the soils are downloaded.
