### ISSUE TITLE
Lat-Lon query of APSoil in json-format without GUI

### ISSUE THREAD

**Issue by ugrewer** [APSIMInitiative/ApsimX#7827]
_**Issue**_: I would like to retrieve the json-code segment  of an APSoil-profile based on a Lat-Lon coordinate without manually using the GUI.

_**Context**_: I am using python to generate apsimx-files for a range of locations and management scenarios. I am running the list of apsimx-files invoking APSIM from command-line.

_**Solution ideas**_:
- If being able to access the APSoil database in json format, I could automatically run a Lat-Lon query and extract the desired json-code segments. However, I am only able to locate APSoil in xml format. Is the APSoil database released in json, too?
- The APSIM NextGen GUI provides the functionality of manually querying both APSOIL and ISRIC based on Lat-Lon-coordinates and retrieve the respective json-code of the soil profile. Is it possible to invoke this functionality from outside the GUI? (I.e. is it possible to query APSoil for a given lat-lon combination from command-line and export the json-code of the soil?)
- Continue to work with APSoil in xml and find a script that translates an APSoil xml-node to json.

Could you kindly advice on how to best approach this issue?

**Comment by ric394** [comment]
@hol430 @hol353 @her123 @hut104 is this possible?

**Comment by hol353** [comment]
Not currently possible. APSoil web API returns the old XML APSIM 7.10 format. We should probably add a new endpoint to return the newer JSON. The problem is that APSIM Next Gen soil format is a moving target and changes fairly often as we rearrange things.

It would be relatively easy to write a script to get the old XML from the APSoil API and then run APSIM Next Gen Models.exe with the --upgrade switch to convert it to JSON.

**Comment by ugrewer** [comment]
Thank you very much for the information!
I already have a python script in place that runs such a Lat-Lon-query on APSoil and returns me the xml-snipped of the desired profile. Could you give me some more prescriptive guidance with regards to how I can run Apsim Next Gen with the mentioned upgrade switch to convert from xml to json?

**Comment by hol353** [comment]
Assuming APSIM Next gen is installed here: C:\Program Files\APSIM2023.2.7165.0
Assuming your XML soil is in file c:\Work\Soil.txt

Then you can run APSIM like this to convert the soil file:

C:\Program Files\APSIM2023.2.7165.0\bin\Models.exe --upgrade  C:\Program Files\APSIM2023.2.7165.0

This will change the contents of Soil.txt into the new JSON format.

**Comment by ugrewer** [comment]
To avoid confusion of potential future readers, I belief there is a typo in the above command, that should be:

C:\Program Files\APSIM2023.2.7165.0\bin\Models.exe --upgrade C:\Work\Soil.txt

Works like a charm. Thank you very much for the guidance.
