### ISSUE TITLE
RedClover continue to take up nitrogen when "terminated"

### ISSUE THREAD

**Issue by ElsaLagerquist** [APSIMInitiative/ApsimX#7830]
Hi,

I'm trying to simulate a rotation of cereals and clover service crops (e.g. cover crops/catch crops/living mulch) with APSIM NG. It is grown in a rotation of oats and winter wheat, sown into oats and "terminated" in winter wheat, and I'm looking at the long-term effects of growing the service crop with different frequency over a longer period. Everything works relatively well in the simulation of the crops, but there is something not working with the RedClover module in its simulation of nitrogen uptake.

I have used the end crop command to simulate the termination of the service crop, and it works with regards to biomass, but the RedClover continues to take up nitrogen (see figure below), even more than when grown and more than the cereals as well. I guess this has a large impact on the other simulated processes. This does not occur for water uptake. 
Is there something I have missed on my side, or is there something the APSIM development team can do to fix this? Probably it is connected to the "termination" which is out of what this module was designed for, but it seems to have worked well for the other module related processes.

Thank you for your help!
Kind regards,
Elsa

**Comment by ric394** [comment]
Hi @ElsaLagerquist are you able to provide your simulation so we can take a closer look.

**Comment by ElsaLagerquist** [comment]
Hi @ric394 
Sure! Here's the simulation. I have prepared graphs for the simulated red clover biomass, water uptake and nitrogen uptake so you can see that the red clover biomass, water uptake and nitrogen fixation stops when it is ended. And also that nitrogen uptake from the cereal crops stops when they are ended.
 
[SA_to_Github.zip](https://github.com/APSIMInitiative/ApsimX/files/10823248/SA_to_Github.zip)

**Comment by ric394** [comment]
@APSIMInitiative/developers Any ideas why this would continue to uptake N after ending crop? 
I've attached the original simulation with graph overlaying N uptake and biomass. You can clearly see that N uptake continues even when biomass is gone.
[SA50V2.zip](https://github.com/APSIMInitiative/ApsimX/files/10893158/SA50V2.zip)

**Comment by ElsaLagerquist** [comment]
If I end the crop a bit earlier the nitrogen uptake is reduced, but it is not 0 as it is for biomass and water uptake. It does not have anything to do with phenology stage, but maybe with how much the crop has started to grow again after winter.
