### ISSUE TITLE
Incorrect units on linearInterpolation function graph in Cotton Prototype

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#7832]
This is located in Cotton Prototype

File path: \ApsimX\Prototypes\Cotton\Cotton Tiemen\Cotton 20230124.apsimx

When looking at the graph, the graph is displaying the incorrect units of measurement (g/m2).

.Simulations.Replacements.Cotton.Leaf.DMDemands.Structural.DeltaLAIPotential.PreCutout.Delta.RelativeArea.XYPairs

**Comment by par456** [comment]
Think this bug report needs some more detail, there are a lot of graphs within that file, but none of match the details written here. 

Quite a lot of the graphs are showing g/m2 on the Y axis, and the simulations under Validation seem to be interchanging ppm and kgha quite a bit, so unclear if this is a problem with the graph, or the values the simulations were set up with.
