### ISSUE TITLE
Sum("non-scalar type") report variable not raising error on simulation run

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#7835]
Tried to have a report variable as:

"sum([Soil].Nutrient.Denitrification) as Denitrification"

This did not report an error on run when it should have, as 'summing' all the members of that class would not make sense.

**Comment by peter-devoil** [comment]
In the same area, adding a second report variable with the same "as" name as another variable (specifically, a factor name under the simulation's experiment node) is silently ignored

**Comment by ilhuber** [comment]
Looks like IFunction types will also report 0 when used in an expression, while reporting their .Value() (without any index argument) when not. The code to handle these cases appears to be in:
https://github.com/APSIMInitiative/ApsimX/blob/71491ae2064212ec17d2f94f451f03b303f3be90/Models/Core/VariableExpression.cs#L133

**Comment by par456** [comment]
This issue has been fixed.
