### ISSUE TITLE
Tree crop (fruit type) modelling

### ISSUE THREAD

**Issue by HongtaoXing** [APSIMInitiative/ApsimX#7838]
Good morning, everyone.

I am wondering if our APSIM have some modules available (or in planning) for modelling fruit tree crops (e.g., macadamia, mango, banana, avocado and citrus). 

Thanks

Hongtao

**Comment by peter-devoil** [comment]
We do have a slightly out of date [development plan](https://github.com/orgs/APSIMInitiative/projects/4) that lists a simple fruit tree, which I suspect wont be doing fruit production. @HamishBrownPFR might have info on its progress.

**Comment by hut104** [comment]
Unfortunately no.

It may be possible to use some simplified models within APSIM to simulate resource use (e.g. light interception, water use and N uptake) but not dynamically simulate fruit tree production.

________________________________
From: HongtaoXing ***@***.***>
Sent: Monday, 6 March 2023 10:36 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Tree crop (fruit type) modelling (Issue #7838)


Good morning, everyone.

I am wondering if our APSIM have some modules available (or in planning) for modelling fruit tree crops (e.g., macadamia, mango, banana, avocado and citrus).

Thanks

Hongtao

**Comment by HongtaoXing** [comment]
Thanks for your response, Neil
