### ISSUE TITLE
PredictedObserved doesn't show correct key fields

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#7841]
When using the PredictedObserved component the matching field name drop down doesn't contain the correct fields (e.g. SimulationName).

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/11879671/223593563-2e30d85e-d77e-48f2-ae7d-a041ebde9984.png">

**Comment by ric394** [comment]
@her123 Can I please have a copy of your simulation?

**Comment by ric394** [comment]
@her123 I was able to view SimulationName in the drop down when I ran your simulation. Both reports' variables can be seen in the drop-down lists when selected as the predicted table.

## Daily Report variables
![image](https://user-images.githubusercontent.com/123442863/223862936-31e03940-6ab2-4c56-9644-6f021458f0da.png)
## Daily Report selected in PredictedObserved Node
![image](https://user-images.githubusercontent.com/123442863/223863107-7da9ca55-7883-4679-a266-0977b902053a.png)
## HarvestReport variables
![image](https://user-images.githubusercontent.com/123442863/223863340-ed35f3f1-dc49-4e10-bb7e-1d2c4ca3530f.png)
## HarvestReport selected in PredictedObserved Node
![image](https://user-images.githubusercontent.com/123442863/223863502-a424092f-6c97-4447-81e8-8a436601429f.png)

**Comment by her123** [comment]
My platform was Win 11 (ARM version). Also noticed the same on Mac OSX (ARM).

**Comment by her123** [comment]
@ric394 it occurs on other Windows platforms also
