### ISSUE TITLE
Cannot set certain parameters in APSIMx simulations

### ISSUE THREAD

**Issue by Hull4Progress** [APSIMInitiative/ApsimX#7845]
I am working with APSIM NextGen on the eucalyptus rotation example described in the file "APSIMForPlantationForestryInstructionsExercises.pdf" from <https://www.apsim.info/wp-content/uploads/2021/10/APSIMForPlantationForestryInstructionsExercises.pdf>, which I accessed from the page https://www.apsim.info/support/apsim-training-manuals/ .  In step 9e it suggests that I change the cultivar to nitens (from grandisCoffsHarbour).  However, that change does not "stick" in the IDE; rather the cultivar remains as grandisCoffsHarbour.  I am working with APSIM2023.3.7168.0 on a MacBook Pro running MacOS Ventura 13.2. 

 I have found similar issues with some other parameters with some other enumerated value sets.   Thank you.

**Comment by Hull4Progress** [comment]
I have come across another problem, which may be related to the one mentioned above.  Specifically, I have been working through the video "APSIM Next Gen Training Video" at https://www.youtube.com/watch?v=5DogVqLYbUs.  At minute 22:36 there is a step in the "Wheat Yield" window which is to replace the value of "Colour" with "Vary by N".  For some reason, when I attempt to make that selection it does not "stick".  Here is a screen shot of where I am getting stuck.  Thanks.

![Vary-by-N-screenshot](https://user-images.githubusercontent.com/53884411/224184002-76d6de50-8b66-45c4-93fb-4f8011e786e0.png)

**Comment by Hull4Progress** [comment]
BTW, the trouble I mentioned above does NOT seem to happen with APSIM2022.12.7130.0...
Thanks

**Comment by ilhuber** [comment]
At the ISU workshop (on version 7219) someone had this issue again. The participant was unable to interact with any dropdown menu with her mouse, but using arrow keys would move the menu one space before closing. Hers was the only mac to have such an issue, others were able to interact with dropdown menus normally. I'll update this with her OS version + hardware when I can get it. 

Possibly related:
https://gitlab.gnome.org/GNOME/gtk/-/issues/5556
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5436

**Comment by Max-Tweddell** [comment]
Also had this problem on latest 01 August build of apsim. Downloading .net runtime fixed it but there needs to be an error message or some indication of the problem.
