### ISSUE TITLE
Cannot import a .xlsx file from a manager script.

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#7846]
The attached simulation fails while trying to read a .xlsx file.

The bug is in ApsimTextFile.cs line 129:

```c#
        /// <summary>
        /// Open the text file for reading
        /// </summary>
        /// <param name="fileName">The Name of the file to open</param>
        public void Open(string fileName)
        {
            Open(fileName, "");
        }
```

We need a way to pass the sheet name into the Open method. In the attached .apsimx file, the LCA script contains code to call the ApsimTextFile.ToTable method, which calls Open.

A blank string is being passed into the Open method.

[emissionfactor.zip](https://github.com/APSIMInitiative/ApsimX/files/10916901/emissionfactor.zip)

**Comment by ric394** [comment]
@hol353 for simplicity, could I get a copy of "BARSsenap.met" weather file.

**Comment by hol353** [comment]
I don't have it. Just change the weather file name to an example weather file. You might also need to change the clock start and end dates to match.

**Comment by ric394** [comment]
The below simulation contains a LCA script that converts the excel file to data set and allows the emission values to be referenced.

[BARS-LTT2021-V2.zip](https://github.com/APSIMInitiative/ApsimX/files/11035097/BARS-LTT2021-V2.zip)
