### ISSUE TITLE
Soils downloaded in user interface don't work

### ISSUE THREAD

**Issue by BFLOHR100** [APSIMInitiative/ApsimX#7850]
soils downloaded don't have any numbers in the water node

**Comment by ric394** [comment]
@BFLOHR100 which soils did you download? I'd like to test them if I could.

**Comment by hol353** [comment]
I think the problem exists with all soils downloaded through the gui.

**Comment by hol353** [comment]
Same as #7823

**Comment by ric394** [comment]
resolved with #7861
