### ISSUE TITLE
Default Soybean model doesn't report flowering

### ISSUE THREAD

**Issue by ilhuber** [APSIMInitiative/ApsimX#7851]
The Plant model's Flowering event is never triggered for Soybean (see #7761). It seems like this is because Plant.cs expects there to be a phase named exactly "Flowering" but the default Soybean model doesn't contain one.

**Comment by hol353** [comment]
I did the simple thing and added a 'StartPodDevelopment' event to plant for models that don't have flowering. Users can now report on 'StartPodDevelopment'.

It seems there is a design problem where runtime events can't be sent in APSIM i.e. can't read the soybean resource file and send events for whatever phenological stages it finds. As a result these events are hard coded. Will need to find a way around this.
