### ISSUE TITLE
Oats grain number appears as an improved stat in every pull request

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#7858]
The accepted stats appear to be different to the tip revision stats.  It is not clear why the accepted stats are different in terms of observed data.

We may need a rethink of the stat acceptance process.

**Comment by hol353** [comment]
An updated performance stats site has been deployed. This will treat improvements to a model as a 'Fail', requiring new stats to be accepted. This will get around the issue described above.
