### ISSUE TITLE
How to properly tag animal groups based on buy and sale events in the stock model 

### ISSUE THREAD

**Issue by Chloe0317** [APSIMInitiative/ApsimX#7866]
Hi Dean @hol353 

I'm trying to use the stock model to manage the number of stocks on the paddock each day, e.g. my data have both cattle and lamb of varying numbers each day. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/u8012681/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/u8012681/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link=blue vlink=purple>

day| 1 | 2 | 3 | 4 | 5 | 6
--|-- | -- | -- | -- | -- | --
cattle| 8 | 14 | 16 | 22 | 24 | 20
lamb| 4 | 7 | 8 | 11 | 12 | 0

</body>

</html>

I'm using R to compile the data from excel spreadsheet into manager script by calling Stock.Buy() and Stock.Sell() function.
How can I make sure in the manager script that I'm selling the right animals, please? 

I think it is a matter of tagging each event with a unique tag no. in the Stock Buy() and Sell() function. 
I'm writing the buy and sale of each event together, first all the management of cattle, followed by lamb , e.g.,
....
2011-09-01 [Stock].Buy(genotype: "Angus", number: 21, sex: Castrate, age: 24, weight: 650, fleeceWeight: 0)
2011-09-06 [Stock].Sell(21)
...

2012-09-14 [Stock].Buy(genotype: "Angus", number: 28, sex: Castrate, age: 24, weight: 650, fleeceWeight: 0)
2012-09-25 [Stock].Sell(28)
2011-09-03 [Stock].Buy(genotype: "Suffolk", number: 25, sex: Female, age: 24, weight: 50, fleeceWeight: 0)
2011-09-07 [Stock].Sell(25)

How can I tag each buy and sale to ensure the right animals are being moved to and removed from the paddock please?

Your help will be greatly appreciated!

Many thanks!

Chloe

**Comment by hol353** [comment]
@her123 : can you help with this question?

**Comment by Chloe0317** [comment]
Thank you Dean @hol353 and Neville @her123 !
Just an update:
I have got it to work by adding a tag parameter to the Stock.Buy() function to the source code that takes in the stock class UseTag. 

All the animal purchases can now be scheduled using the scheduler, unique tags for cattle, lamb, ewe and ram. 

stock.cs line 3844

		/// <param name="tag">The tag of stock model uses </param>
        public void Buy(string genotype, double number, ReproductiveType sex, double age, double weight, double fleeceWeight, int tag)
        {
            StockBuy stock = new StockBuy();
            stock.Genotype = genotype;
            stock.Number = Convert.ToInt32(number, CultureInfo.InvariantCulture);
            stock.Sex = sex;
            stock.Age = age;
            stock.Weight = weight;
            stock.FleeceWt = fleeceWeight;
			stock.UseTag = tag;
            outputSummary.WriteMessage(this, "Buying " + stock.Number.ToString() + ", " + stock.Age.ToString() + " month old " + stock.Genotype + " " + stock.Sex.ToString() + " ", MessageType.Diagnostic);
            StockModel.Buy(stock);
        }

Would you consider adding **tag** in the source code?


However, I cannot find a way to implement the Stock.Sell() function through scheduler with the tag number as the second parameter for the Sell() function is of the type 
IEnumerable<AnimalGroup>


My current workaround is using R to create manager script lines 
...
		    if (DateUtilities.DatesAreEqual("02-mar-2011", clock.Today))
		    {stock.Sell(13, stock.ByTag(1));}
		    if (DateUtilities.DatesAreEqual("02-apr-2011", clock.Today))
		    {stock.Sell(20, stock.ByTag(2));}

...

If you have recommendations of a more efficient way to achieve this, I'm open to suggestions please!

Thank you very much!

**Comment by her123** [comment]
Tags are designed for tracking animals for management activities. What you have done will be fine.
