### ISSUE TITLE
Modeling the Impact of Water and Nitrogen Stress on Maize Phenology Using APSIMX

### ISSUE THREAD

**Issue by lyfranki** [APSIMInitiative/ApsimX#7881]
Hello there,

1. I'm currently simulating maize phenology using APSIMX and I'm unsure if the Maize.Leaf.Fw variable represents water stress. Could you please confirm if this is the case?
2. While analyzing my simulation results, I observed that Maize.Leaf.Fw values were sometimes below 1. However, it did not appear to affect thermal time accumulation or the duration between corresponding phenology stages. Can you provide any insights on why this might be the case?
3. I'm interested in understanding how APSIMX considers water stress and nitrogen levels when simulating maize phenology. While APSIM accounts for these factors as shown following, I have not been able to locate the relevant code in APSIMX. Could you please confirm if APSIMX incorporates these factors in a similar manner, and if so, provide any guidance on where I can find this information? Generally, the APSIMX inherit all the module in the APSIM Classif, right?

![image](https://user-images.githubusercontent.com/59980694/227409848-99bc525b-54b4-4d9d-bf05-cc76b6b5b0c9.png)
(https://github.com/APSIMInitiative/APSIMClassic/blob/27396788a2c0fcc2750b72700d7fccf35fc7c7ea/Model/Maize/Phenology.cpp#:~:text=double%20Phenology%3A%3AcalcStressesTT(void))

Thanks!
Yin

**Comment by KeLiu7** [comment]
> Hello there,
> 
> 1. I'm currently simulating maize phenology using APSIMX and I'm unsure if the Maize.Leaf.Fw variable represents water stress. Could you please confirm if this is the case?
> 2. While analyzing my simulation results, I observed that Maize.Leaf.Fw values were sometimes below 1. However, it did not appear to affect thermal time accumulation or the duration between corresponding phenology stages. Can you provide any insights on why this might be the case?
> 3. I'm interested in understanding how APSIMX considers water stress and nitrogen levels when simulating maize phenology. While APSIM accounts for these factors as shown following, I have not been able to locate the relevant code in APSIMX. Could you please confirm if APSIMX incorporates these factors in a similar manner, and if so, provide any guidance on where I can find this information? Generally, the APSIMX inherit all the module in the APSIM Classif, right?
> 
> ![image](https://user-images.githubusercontent.com/59980694/227409848-99bc525b-54b4-4d9d-bf05-cc76b6b5b0c9.png) (https://github.com/APSIMInitiative/APSIMClassic/blob/27396788a2c0fcc2750b72700d7fccf35fc7c7ea/Model/Maize/Phenology.cpp#:~:text=double%20Phenology%3A%3AcalcStressesTT(void))
> 
> Thanks! Yin

Maize.Leaf.Fw refer to water stress (drought) on photosynthesis but not phenology. This is why you did not see changes in phenology.

As far as I know, phenology is not expected to show big difference when exposed to stress in APSIM Classic but not sure in APSIM Next Gen.  Maybe you can check the Maize documentation. I guess it might be the same as APSIM Classic. You need to create some scripts to associate those stress wth phenology. This is what I'm doing now (simulate waterlogging stress on phenology).
