### ISSUE TITLE
ApsimX - Grapevine - Question - Climate change

### ISSUE THREAD

**Issue by markosdask** [APSIMInitiative/ApsimX#7884]
Hi everyone,
We have a quick question now that we are trying to learn ApsimX, especially the Grapevine feature recently published, which looks very promising and helpful for our country, Greece:
We would be interested to develop a generic approach for calculating the impact of climate change on grapevines. Does ApsimX reacts in the different levels of CO2 concentration for future periods?
Thank you in advance,
Markos.

**Comment by hut104** [comment]
Hi
The grapevine model is released but has been only tested within a narrow range of environments and calibration for conditions in Greece would be required.  The stomatal conductance model does not respond to CO2 level as yet and the model has not been tested under dryland conditions and so water stress response may need further development.
________________________________
From: markosdask ***@***.***>
Sent: Monday, 27 March 2023 9:19 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] ApsimX - Grapevine - Question - Climate change (Issue #7884)


Hi everyone,
We have a quick question now that we are trying to learn ApsimX, especially the Grapevine feature recently published, which looks very promising and helpful for our country, Greece:
We would be interested to develop a generic approach for calculating the impact of climate change on grapevines. Does ApsimX reacts in the different levels of CO2 concentration for future periods?
Thank you in advance,
Markos.

**Comment by markosdask** [comment]
Thanks @hut104 for the answer.
