### ISSUE TITLE
Cultivar coefficient computation tool or excel sheet or python code

### ISSUE THREAD

**Issue by KrishnaDevkota** [APSIMInitiative/ApsimX#7885]
I am struggling to calibrate wheat varieties (manually deriving cultivar coefficients). I do not think manual hit and trial method is the only method so far for the computation/optimization of cultivar coefficient in APSIM? I am really looking for some tool/excel sheet to compute cultivar coefficient for APSIM NG using my climate, soil and management file ( as DRATES and PRAM tools of ORYZA or Glue of DSSAT performs that job ). Can anyone please suggest/share any such computation method in APSIM NG?
Thank you a lot for your support!

**Comment by KrishnaDevkota** [comment]
Thank you Brian, this is helpful. I have some issue with this simulation,
can you please have a look at it?

**Comment by BrianCollinss** [comment]
Hi Krishna. Sorry I cannot help you. I have not used this tool as I have developed my own optimisation package.
