### ISSUE TITLE
Integrate "disable zero values" in scatter (line) plot

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#789]
Multiple lines in a plot get confusing when e.g. biomass drops to 0 at harvest ripeness (see attached). An option to disable the display of zero values would be nice.
Not sure if this can already be achieved with the "Filter"?

![apsim_line_plot](https://cloud.githubusercontent.com/assets/17924125/14673753/12ce812c-0700-11e6-8214-a7595842b38b.jpg)

**Comment by HamishBrownPFR** [comment]
Filter can be used.  A tick box to hide zero values would be a quicker way of doing it.
![image](https://cloud.githubusercontent.com/assets/7295858/14685187/b35914a4-0787-11e6-9701-76a0b99732b0.png)

**Comment by hol353** [comment]
Closing this. The graph filter is the best way to do this.
