### ISSUE TITLE
Add Euc and Pine soils to ASRIS APSOIL downloads

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#7890]
Please add EucalyptusSoil and PinusSoil to the APSOIL downloads at:
urlsoil = 'https://www.asris.csiro.au/ASRISApi/api/APSIM/getApsoil?' 
This is somewhat urgent as it's needed for a current short-term project with the forest industry.

**Comment by hol353** [comment]
Where do I currently find EucalyptusSoil and PinusSoil and why do they need to be in APSoil?

The process to add a soil to APSoil is to submit the soils to Kirsten V. She checks them to make sure they make sense. The problem is that she has just gone on a months leave.

**Comment by hol353** [comment]
We don’t manage the code for SLGA and so can’t change it to add EucalyptusSoil and PinusSoil parameterisations.
The job here is to add PinusSoil to the ISRIC (and other soil) downloads in APSIM.

**Comment by sme016** [comment]
Also, SCRUMSoil needs to be added. which is needed for the Eucalyptus Example to run.

**Comment by hol353** [comment]
I notice that SLGA is returning ‘SCRUMSoil’ as a soil crop. I have asked Ross to change this to just ‘SCRUM’? That will fix the problem with SCRUM not coming through. Pinus and Euc are already present.

**Comment by hol353** [comment]
From @sme016 

Thanks for this, but it might need a bit more of a tweak, as Water now has soils depths but still no initial values. 

It’s not a priority for me, but it would also be good to get PinusSoil and SCRUMSoil into the ISRIC downloads. EucalyptusSoil is already there.

**Comment by hol353** [comment]
I've added the initial water values (DUL) to the water node. Also added the extra soil crop parameterisations to ISRIC soils.

**Comment by sme016** [comment]
Thanks. The initial water values are there, but PinusSoil and SCRUMSoil are not yet in the ISRIC downloads that I checked from within the GUI.
