### ISSUE TITLE
Permutations wording question

### ISSUE THREAD

**Issue by DocHollandD** [APSIMInitiative/ApsimX#7910]
I noticed that APSIM uses the word permutation in the model and documentation, but given that permutations are timing/order-dependent, shouldn't combination be a clearer word here? As implemented, it's more a combination of different levels of factors/strategies. Just wondering from a clarity of wording standpoint here. I understand if it's a legacy holdover or there's another reason for it, but was just wondering.

Thanks!

**Comment by hol353** [comment]
The word permutation can be defined in different ways. I just searched it online and the top result (https://byjus.com/maths/permutation/) defines it as:

A permutation is an arrangement of objects in a definite order

A permutation object in APSIM also combines factors in a definite order. The term seems appropriate to me.
