### ISSUE TITLE
Cannot add “constant” into Root module

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/ApsimX#7912]
[Barley_cannot add function in root module.zip](https://github.com/APSIMInitiative/ApsimX/files/11199657/Barley_cannot.add.function.in.root.module.zip)

I get stuck with adding “constant” into Root module- “Unable to modify Root- It is read- only”. I tried to cancel the "√“ in front of “Read-off” checkbox in the root module but it will tick again. Does anyone have any ideas? I have attached the file. Many thanks!

**Comment by par456** [comment]
Could you provide some clarification on why you are editing the Root node. Just need some more info to provide the right solution.

**Comment by KeLiu7** [comment]
> Could you provide some clarification on why you are editing the Root node. Just need some more info to provide the right solution.

I'm trying to add a stress factor that is relevant to Root module, so need to add a `constant` there to define it.

**Comment by par456** [comment]
I've attached the json data (Barley.txt) for the Barley model. If you open up your apsimx file in a text editor, you can copy that in to replace your existing Barley node in the Replacements folder (it starts right at the top, I've put a picture showing where it is). Then your Barley node will be able to be edited.

Let me know if you need any more help with doing that.

[Barley.txt](https://github.com/APSIMInitiative/ApsimX/files/11206295/Barley.txt)
![instruction](https://user-images.githubusercontent.com/130029141/231326283-0628c1c0-4a3a-41d4-a627-34366f9bc34f.png)

**Comment by KeLiu7** [comment]
> 



> I've attached the json data (Barley.txt) for the Barley model. If you open up your apsimx file in a text editor, you can copy that in to replace your existing Barley node in the Replacements folder (it starts right at the top, I've put a picture showing where it is). Then your Barley node will be able to be edited.
> 
> Let me know if you need any more help with doing that.
> 
> [Barley.txt](https://github.com/APSIMInitiative/ApsimX/files/11206295/Barley.txt)
> 
> ![instruction](https://user-images.githubusercontent.com/130029141/231330042-aba1f43c-80ad-4cc6-8e31-cc7dd44f90ce.png)

Many thanks Andrew！it works well😊
