### ISSUE TITLE
Selecting another node while renaming a Manager Node may cause a crash

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#7924]
If you have left-click or rename a Manager node, then click on another node, it may cause a soft crash. 
`(Object Reference not set to an instance of an Object)`

It seems to normally work the first time, but if you do it again, then the crash nearly always happens.

**Comment by ilhuber** [comment]
This behavior seems like it was uncovered by #7911. Using earlier versions I never encountered this particular error and can't reproduce it, but using the latest revision I can easily get it to happen. Undoing that commit I no longer encounter the error. Only happens with Manager scripts too, which is a bit odd.

**Comment by par456** [comment]
The change to make the undo function redraw the right panel definitely could have allowed this bug to happen, since I think that change would also force a redraw when renaming. 

The reason its only effecting manager scripts is because there were no checks to see if an editor exists when putting the text in. But if this was caused by the change in #7911, there could be other nodes that have also been effected.
