### ISSUE TITLE
Having issues opening APSIM once downloaded onto Mac

### ISSUE THREAD

**Issue by SummicronC** [APSIMInitiative/ApsimX#7932]
Hello.

I am running the latest Mac OS. I am able to download APSIM no problem. My computer informs me that it suspects the application is malware, so I go through the channels of opening it in 'privacy and security' settings. It is here where my problem arises. When the pop up opens, and I click 'open now', the APSIM icon in the menu bar starts to bounce like an app would when it is about to open, and then nothing happens. The app then disappears out of my menu bar, and I have to go through the process again via the download folder. 
Any help would be kindly appreciated. 
Thanks

**Comment by Hull4Progress** [comment]
I, too, am having trouble with opening versions 2023.4.7188.0 and 2023.4.7189.0 on my mac.  I am reminded of issue #7765, which was resolved by the fix for issue #7776.  Thanks

**Comment by Hull4Progress** [comment]
In fact, I am having challenges with APSIM 2023.3.7170.0 on my Mac.  I had been using it in a read-only mode, but today I am trying to update some fields in one of my models, and the updates are not accepted by the app.  I had reported the same problem in connection with APSIM2023.3.7168.0  in issue #7845.

**Comment by SummicronC** [comment]
I have downloaded 2023.2.7146 and it has opened so will work on that for now. Thank you

**Comment by Hull4Progress** [comment]
The following issue may be related to the above ...

I recently installed apsimx for R on my mac, and then attempted the following simple command using version APSIM2023.4.7189.0
> wheat <- apsimx_example("Wheat")
But got the following response:

> wheat <- apsimx_example("Wheat")
You must install .NET to run this application.

App: /Applications/APSIM2023.4.7189.0.app/Contents/Resources/bin/Models
Architecture: x64
App host version: 6.0.15
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=osx.13-x64&apphost_version=6.0.15
Error in read_apsimx(file = sub("apsimx", "db", file), src.dir = src.dir,  : 
  There are no .db files in the specified directory to read.
In addition: Warning messages:
1: In auto_detect_apsimx_examples() :
  Multiple versions of APSIM-X installed. 

                    Choosing the newest one: APSIM2023.4.7189.0.app
2: In auto_detect_apsimx() : Multiple versions of APSIM-X installed. 

                    Choosing the newest one: APSIM2023.4.7189.0.app
3: In system(command = run.strng, ignore.stdout = silent, intern = TRUE) :
  running command '/Applications/APSIM2023.4.7189.0.app/Contents/Resources/bin/Models /var/folders/3l/gd1qj_mw8xl3gm001s6w9h180000gp/T//RtmpiewJQW/Wheat.apsimx' had status 131

I then ran the command using APSIMX version APSIM2022.12.7130.0.app, and got the following successful response (e.g., after that command I successfully ran "summary(wheat)"):

> wheat <- apsimx_example("Wheat")
Warning messages:
1: In auto_detect_apsimx_examples() :
  Multiple versions of APSIM-X installed. 

                    Choosing the newest one: APSIM2022.12.7130.0.app
2: In auto_detect_apsimx() : Multiple versions of APSIM-X installed. 

                    Choosing the newest one: APSIM2022.12.7130.0.app

Two questions:
1) Why does version APSIM2023.4.7189.0 want me to install .NET, given that I am on a mac
2) If I do need to install .NET, how would I do that? (I tried "install.packages(".NET"), but that didn't find a .NET package)

Thanks

**Comment by par456** [comment]
We've been able to replicate this issue. There was a large merge prior to the April 12 build (2023.4.7177) and something in there seems to have caused this. Will investigate further.

**Comment by her123** [comment]
Confirmed on my M1 also for that version. 2023.4.7176 works. It appears to be related to .net 6.0 on M1

**Comment by ilhuber** [comment]
A number of mac users at the workshop were having similar issues where ApsimNG would refuse to start without an error message through the UI (but trying to launch through the terminal would display the error message posted by @Hull4Progress above). Installing the recommended version of dotnet allowed them to launch Apsim normally.

**Comment by ric394** [comment]
Closing pending #8796
