### ISSUE TITLE
Standard toolbox is missing

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#7934]
I received this issue by email.
I'm teaching Apsim this Wed/Thurs and the standard toolbox seems to be missing from the current version. Do you know who might know what to do? Thanks. Enquiry was submitted on: 17/04/2023 02:38 PM

**Comment by par456** [comment]
The standard toolbox has been replaced by right clicking on a node and selecting "Add Model..."

Otherwise the functionality should be the same, though the Add Model menu will filter so that only valid node types for the one selected will appear.

**Comment by rowaneisner** [comment]
That was me! Thanks guys, yesterday's class went ok and teaching it again today.
