### ISSUE TITLE
Failure to successfully upload the wather data

### ISSUE THREAD

**Issue by wycliffe20** [APSIMInitiative/ApsimX#7935]
I'm new to using APSIM, and therefore I have been using the manuals to learn. I formatted my Excel file containing weather data following the format recommended but am not getting the correct data when I import it into APSIM. 

This is from the manual
![Apsim Issue 0](https://user-images.githubusercontent.com/115987765/233314291-23ac02b0-f46c-40da-9e2e-9ffa69b58542.png)

Data view after importing

![Apsim Issue 1](https://user-images.githubusercontent.com/115987765/233314585-2388351f-2233-4ceb-b56b-69b70d2f435c.png)

Summary of my imported data
![Apsim Issue 1 1](https://user-images.githubusercontent.com/115987765/233314659-6d7f0d9d-af5c-413f-85c3-84dbf569f939.png)

![Apsim Issue 1 2](https://user-images.githubusercontent.com/115987765/233314687-5b4e3d27-9bf3-48b1-8e77-d7fb94ab65d2.png)

![Apsim Issue 1 3](https://user-images.githubusercontent.com/115987765/233314716-ef34e825-0d45-4c21-8098-4da295333f8c.png)

**Comment by par456** [comment]
I'm not sure what's going on here, could you send a copy of the weather file so we can take a look?
