### ISSUE TITLE
Subsurface Irrigation in SWIM3

### ISSUE THREAD

**Issue by ks265** [APSIMInitiative/ApsimX#7937]
I want deal with subsurface irrigation in SWIM3 of the APSIM Next Generation.
 I tried to use " irrigation.Apply(amount:amount, depth:depth);" in the script.
There was no error message, but it did not work correctly.
Can I use the depth argument in SWIM3?

If I cannot use it, I want to use the lateral inflow (lnflow_lat) which can be used  in SoilWat.
However, I can not find how to use it in SWIM3.

I request you to kindly help with this issue.

**Comment by par456** [comment]
Can you upload a copy of your apsimx file in a zip or in json format? That'll help us figure out what's going wrong.

**Comment by ks265** [comment]
Dear par456
Thank you for your kind reply.

I attach the apximx file.
I write the subsurface irrigation in the script of "OPSIS".

[ITOMAN-SUGAR_OPSIS2.apsimx.zip](https://github.com/APSIMInitiative/ApsimX/files/11292659/ITOMAN-SUGAR_OPSIS2.apsimx.zip)

**Comment by hut104** [comment]
Subsurface irrigation or lateral inflow cannot be applied to SWIM.

________________________________
From: ks265 ***@***.***>
Sent: Friday, 21 April 2023 3:16 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Subsurface Irrigation in SWIM3 (Issue #7937)


I want deal with subsurface irrigation in SWIM3 of the APSIM Next Generation.
I tried to use " irrigation.Apply(amount:amount, depth:depth);" in the script.
There was no error message, but it did not work correctly.
Can I use the depth argument in SWIM3?

If I cannot use it, I want to use the lateral inflow (lnflow_lat) which can be used in SoilWat.
However, I can not find how to use it in SWIM3.

I request you to kindly help with this issue.

**Comment by ks265** [comment]
Dear hut104

Thank you for your comment. I try to consider other measures.
