### ISSUE TITLE
Can maize cultivar parameters calibrated in APSIMClassic be used in APSIMX directly?

### ISSUE THREAD

**Issue by yangxuening** [APSIMInitiative/ApsimX#7940]
Dears, 

I have calibrated maize cultivar parameters in APSIMClassic 7.9. Can I use the values of these calibrated parameters in APSIMX directly? Or do I need to calibrate a new set of cultivar parameters for APSIMX?

**Comment by hol353** [comment]
You will need to recalibrate the maize cultivars. The models are quite different.
