### ISSUE TITLE
Latest docker image won't run

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#7941]
Was looking into issue #7697 and tried to run the CroptimizR example to test if the problem had been fixed. However, trying to run the latest apsimng-complete docker image, will produce this error:

> It was not possible to find any compatible framework version
> The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
> The following frameworks were found:
> 3.1.32 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

I think this is related to issue #7916 where the build targets were changed to remove .net 3.1, as rolling back to an earlier docker image (I used image 7171) runs without errors.

Looking into the build instructions for the image, I can see that it installs and configures .net 3.1, but not 6.0, so to fix this should be as easy as updating the .net package that the image is installing/configuring.

**Comment by hol353** [comment]
I've updated the docker image on DockerHub. Does it work now?

**Comment by par456** [comment]
Yep, all working now.
