### ISSUE TITLE
Difference of Maize LAI simulation between APSIM Classic and APSIMX

### ISSUE THREAD

**Issue by JoannaYRS** [APSIMInitiative/ApsimX#7948]
Hi, I used both APSIM Classic 10 and APSIM Next Generation simulating maize growth. And I found that LAI curves simulated by APSIM Classic version usually have green down shape, as the first figure shows below. While curves simulated by APSIMX usually show a symmetric pattern, as the second figure shows. 
I'm curious about the reason that causing the differences. 
![image](https://user-images.githubusercontent.com/132005487/234958719-e8817f17-b086-4260-a984-4f9143596d19.png)
![image](https://user-images.githubusercontent.com/132005487/234959531-1c4d1c78-8b3f-4f5b-a117-3e406c0f295d.png)

**Comment by hut104** [comment]
Hi,
I am unsure as to what is happening in your simulations, but the time courses of LAI in the validation set follow a normal shape, unlike the simulation in the second graph.
There may be an issue in your simulation. Perhaps check your summary file and/or simulation plant stress levels.

________________________________
From: JoannaYRS ***@***.***>
Sent: Friday, 28 April 2023 5:09 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Difference in Maize LAI simulation (Issue #7948)


Hi, I used both APSIM Classic 10 and APSIM Next Generation simulating maize growth. And I found that LAI curves simulated by APSIM Classic version usually have green down shape, as the first figure shows below. While curves simulated by APSIMX usually show a symmetric pattern, as the second figure shows.
I'm curious about the reason that causing the differences.
[image]<https://user-images.githubusercontent.com/132005487/234958719-e8817f17-b086-4260-a984-4f9143596d19.png>
[image]<https://user-images.githubusercontent.com/132005487/234959531-1c4d1c78-8b3f-4f5b-a117-3e406c0f295d.png>

**Comment by JoannaYRS** [comment]
Thank you for your response! 
In order to eliminate other potential effects, I used the Maize data example provided by APSIMX and ran a simulation. The graph shows the simulated LAI from 1999 to 2000. I'm curious whether this shape is representative of what we would expect to see in a simulation like this.
Additionally, I'm interested in understanding whether the LAI patterns generated by different versions of APSIM (e.g. APSIM Classic and APSIM Next Generation) are expected to differ. Any help is appreciated.
![image](https://user-images.githubusercontent.com/132005487/235337577-f4e6458b-f524-4160-97df-70ccf119b2d6.png)
