### ISSUE TITLE
Allow setting of FertileTillerNumber

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#7959]
Had some issues around setting variables from external source due to cultivar overrides at sowing.
Had to enable FertileTillerNumber to be set (and update correctly) from outside a sowing script.

**Comment by KeLiu7** [comment]
Hi Jason, do tiller functions only work for Sorghum in APSIM Next Gen?

**Comment by jbrider** [comment]
Wheat also has tillers, but they work in a different way.
This implementation is for Sorghum specifically - brought across from Apsim Classic.
It won't work with other leaf types at this stage - just sorghumLeaf.
