### ISSUE TITLE
Are MinimumNConc and MaximumNConc in Potato equal to zero?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#7967]
It seems there is a rounding issue in these two tables, as the values are non-zero in the graphs.

Page 10:
![image](https://user-images.githubusercontent.com/39573622/236740422-9d537659-75e2-493b-a532-2b52f0c24977.png)

Page 11:
![image](https://user-images.githubusercontent.com/39573622/236740405-bb22bac5-599d-4633-bc90-9cdd4d84c3d8.png)

**Comment by par456** [comment]
This may be related to issue #6834 where the same thing is happening. In the Datastore, the values are getting rounded, but the graph is showing all the significant places.

**Comment by par456** [comment]
Leaving this here for later

![image](https://user-images.githubusercontent.com/130029141/236963508-99ccac8c-ec8a-49e7-aacb-5b364145ff79.png)
