### ISSUE TITLE
Output variables in Next Gen

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/ApsimX#7969]
Dear all,

In APSIM Next Gen, there are many variables that are grouped by types such as Double, Biomass, Double[], Int32, BiomassRemoval, String, Constant, List<IModel>etc. 

I have been confused with output those variables. Sometimes variables need to end with FixedValue, sometimes not or with others. 

Is there any documentation available for users to learn how to output the parameter for different types in the right way?

**Comment by ric394** [comment]
There is documentation available [here](https://builds.apsim.info/api/nextgen/docs/Report.pdf)
This should provide plenty of information for your question.
If you have any further questions, please feel free to reopen this issue.

**Comment by KeLiu7** [comment]
> There is documentation available [here](https://builds.apsim.info/api/nextgen/docs/Report.pdf) This should provide plenty of information for your question. If you have any further questions, please feel free to reopen this issue.

Thanks Ric. this documentation is useful but does not provide the information how to output different types of variables (e.g. Double, int32, double[] etc...
