### ISSUE TITLE
Expression Function do not throw exceptions when an error happens

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#7981]
### What happened?

This was found during issue #7963 where I noticed that an incorrect Expression Function will just silently return 0 instead of throwing an exception. 

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/d1fe9425-8777-4d25-91fd-a0e5da40d2b6)

As expected when turning this on, some of the Unit tests failed because they have expressions returning an error. The first of which was Examples/Rotation.apsimx which uses the Wheat model. The Wheat model has a function for Wheat.Grain.Protein:

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/504bacfe-4d94-459b-be78-f0e7625b933f)

This works well most of the time, however if your simulation has a period where there is no wheat ([Grain].Live.Wt and [Grain].Dead.Wt are both 0), then it will throw a divide by 0 error. This doesn't happen in the Wheat example, but does happen in the Rotation example. 

Previously you wouldn't see this error and it would return 0, which is kind of what we want (since 0 wheat means 0 grain protein), but we obviously don't want to just hide errors.

The most straightforward solution to this for me is that we fix the expression so that it avoids trying to do the calculation if both are 0, but I'm drawing a blank with the current functions we have that could avoid this.

### What Operating System are you on?

Windows

**Comment by HamishBrownPFR** [comment]
use 
([Grain].Live.N + divide([Grain].Dead.N , [Grian].Live.Wt + [Grian].Dead.Wt, 0)) * 1000 * 5.71.

The divide expression in the evaluator takes an arguement to return if there is an error in the divide
![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/64e439b9-3d12-4aeb-9bfc-8dd9fd68ac52)
