### ISSUE TITLE
CO2 concentration too low for Stomatal Conductance CO2 Function

### ISSUE THREAD

**Issue by AnnaBlanke** [APSIMInitiative/ApsimX#7983]
### What happened?

I am running simulations where the CO2 level is directly read from the met file. The CO2 Level is around 330ppm in the starting year (80´s) of my simulations. I get the error message mentioned in the title. This issue was already discussed here and it seemed that the threshold value was set to 300ppm. I don´t understand why I am still getting this error message. When I run the same simulations with CO2 level above 350ppm everything works fine. Anyone an idea what could be wrong? I am using APSIMX, version 2023.4.7192.0. Thanks!

### What Operating System are you on?

Windows

**Comment by hut104** [comment]
(I am assuming that you are using one of the crops that use MicroClimate for water and energy balance)

It would appear that the reference stomatal conductance is at 350ppm (the parameter is called Gsmax350 for this reason).  The correction factors are often calculated therefore as
[IWeather].CO2 - [Leaf].CO2internal)/(350 - [Leaf].CO2internal

We would need to extend the CO2 correction term for Gs to allow for CO2 levels below 350.  Given the way the model works in NG, it may be that the sort of checks used in 7.10 are not required and the correction is probably OK.  However, we should check all related the equations first.

**Comment by AnnaBlanke** [comment]
Hi! Sorry for the late reply. I am using the Peanut model in APSIMX. It would be great if the equations could be checked. I am still encountering the issue. Thanks a lot!

**Comment by hol353** [comment]
Sorry for taking so long to look at this. Can you attach a simulation (zipped) that shows the problem?

**Comment by AnnaBlanke** [comment]
Yes, sure. Here is the apsimx file and .met file [APSIM_Madagascar.zip](https://github.com/APSIMInitiative/ApsimX/files/14111442/APSIM_Madagascar.zip)

**Comment by Chloe0317** [comment]
Dear Dean @hol353 , just wondering if there is any progress on this, please? I'm interested in running some wheat simulations using GCMs and encountered the same issue.

**Comment by hol353** [comment]
@Chloe0317 There has been no progress that I'm aware of and this isn't near the top of our long to-do list unfortunately. We'd welcome someone in the APSIM community to take a lead on CO2 responses in APSIM although it will require someone with good knowledge of how the plant models work.

**Comment by HamishBrownPFR** [comment]
This issue has caused us some problems too.  I will take a look at it

**Comment by Chloe0317** [comment]
My background is in soils, not plants. However, I did a quick empirical test of the stomatal conductance function, as the function uses gsmax 350 as a reference point, when the co2 value is less than 350, the relative co2 gradient will be less than one, when co2 value is larger than 350, the gradient will be larger than one. This is consistent with the understanding of reduced stomatal conductance with increasing co2 concentrations. So mathematically, the equation works at preindustrial levels of CO2. 

Co2 <- 280:350
summary(avTemp)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  19.80   24.00   26.90   26.51   29.32   31.40

summary(gr)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.7625  0.8149  0.8771  0.8789  0.9417  1.0000 


However, maybe @HamishBrownPFR  and @hut104 will be best to advice if the scaling down 350 is sensible. The average temp I used is just some data from 1980s in Queensland when the CO2 levels were around 330 ppm. The calculated gradient was about 0.93.

If scaling down is sensible and won't affect other parts of the plant model, I propose removing the restriction on CO2 concentration:

        public double Value(int arrayIndex = -1)
        {
            double temp = (MetData.MaxT + MetData.MinT) / 2.0; // Average temperature
            double CP = (163.0 - temp) / (5.0 - 0.1 * temp);  //co2 compensation point (ppm)
            if (MetData.CO2 == 350 || MetData.CO2 == CP) // Avoid division by zero, assume no modification needed when CO2 is at compensation point or at 350
                return 1.0;
            else
            {
                double first = (MetData.CO2 - CP);
                double second = (350.0 - CP);
                return PhotosynthesisCO2Modifier.Value() / (first / second);
            }
        }


Please let me know what you think.

Many thanks!

**Comment by BrianCollinss** [comment]
I always wonder, if the correctness of the CO2 modifier rationale has been proved, why is it not used when cultivar parameters are calibrated? Why is APSIM still using 350 PPM as default for experiments post-2000?

**Comment by BrianCollinss** [comment]
@Chloe0317, I have a manager script of my own that modifies CO2 using a polynomial fitted on the data from Cape Grim (CSIRO) and Mauna Loa Observatory. Happy to share.

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/56ef0433-1ffa-434a-9342-3484369da183)

**Comment by HamishBrownPFR** [comment]
StomatalConductanceCO2Modifier.cs has a check that throws an error if CO2 < 350.  
RUECO2Function.cs has a check that throws an error if CO2 < 300.  
Not sure the rational for either error threshold but I suspect it is that there is not much data testing responses below these values.
If we assume the shape of the CO2 response is correct then we don't hit mathamatical issues until CO2 concentration is below compensation point and fRUE becomes negative.  
![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/24f60596-7067-477c-8dbc-61ae8404e705)
Scenarios based on field CO2 would normally be at CO2 > 300 so are in part of the response where the changes are still not too steep.  
I think we can change the error trap to throw if CO2 < compensation point which will allow CO2 concentrations down to about 75ppm (depends on temperature) which should allow all feasible field situations to run and will only throw for simulations where CO2 conc is low enough to cause a negative fRUE.
There is also a temperatue check in RUECO2Function that throws if temperature is >50.  However, the fRUE respose curve inverts at temperatures > 46.6oc
![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/b53c399e-2505-471b-b362-c894e5eb4671)

So we should also change the temperature error trap to throw if temperature is >46.5
