### ISSUE TITLE
Adjust non-cultivar specific parameters of a crop using Apsim Nextgen.

### ISSUE THREAD

**Issue by sunjianxin** [APSIMInitiative/ApsimX#7985]
### What is your question?

Dear Authors

We are doing a simulation using Apsim Nextgen to predict the biomass of Rye. 

Could you show us how to adjust non-cultivar specific parameters of a crop? We successful did this by changing the .XML file for classic Apsim, but we don't know how to do the same thing using the Apsim Nextgen. 

We are wondering if there is a template of manager script of Apsim Nextget to achieve the goal. or is there any suggested method of doing so? 

Thank you so much for the help!

Best,
Jianxin

**Comment by KeLiu7** [comment]
Better say which non-cultivar parameter that you would like to change so then others could provide help directly.

**Comment by par456** [comment]
If you right click on a resource node (such as a crop like so), there is a button to show the entire structure. However, all of this is frozen as read only, so we have an alternative to editing them.

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/f8084de9-67f2-4bd8-bb14-b67919fdc70c)

Instead, add a 'Replacements' node to your Simulations, then add your crop as a child of that.

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/e90a0a9c-2925-4198-9c10-40e6fb93da0b)

This will override any crops of that name in your file with the version of the crop in the Replacements folder. This crop is also able to be edited, so you can adjust any of the parameters.

Let me know if I've misunderstood your question.

**Comment by sunjianxin** [comment]
Thank you so much for the help! 
This is the default parameter of USA Yecora in my replacements:
<img width="638" alt="1" src="https://github.com/APSIMInitiative/ApsimX/assets/6218289/e7d632c3-270d-4b69-bcbd-0d929fcfeac6">
This is the default parameter of USA Rex
<img width="653" alt="Screenshot 2023-05-25 094316" src="https://github.com/APSIMInitiative/ApsimX/assets/6218289/0704d49d-5e3a-4577-98e5-90c8be72956a">
Since line 4 and 5 parameters in Rex are not currently in Yecora, do you mean I can add these two parameters currently in Rex to Yecora (copy from Rex the line 4 and 5, and paste behind line 5 of Yecora) to change those parameter value for Yecora? like this: 
<img width="662" alt="3" src="https://github.com/APSIMInitiative/ApsimX/assets/6218289/4fa53889-8383-48a2-8af1-5afc8f9fb7fb">

Thank you so much for the help!

Best.

**Comment by par456** [comment]
I believe so yes. Though I would recommend making a copy of Yecora and giving it a new name (YecoraSpecial or something specific) so you have both the original and your edited version. Then just change your references from Yecora in your manager script to the new one you just created.

That might just save you some headaches in the future in case you need to refer back to the original, or someone tries to use your simulation without realising it's been modified.

**Comment by par456** [comment]
Issue has been resolved.
