### ISSUE TITLE
Methods for finding and diagnosing source of model changes needed

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#799]
The new test system is really good to determine the impact of intended changes on model performance and ensuring model performance is maintained at an accepted standard.  

However, if falls short when a pull request causes model differences that were unintended.  It will tell you that the model is producing some differences and provides some information about what variables have changed (depending on the extent of the tests) but provides no information for working out what simulations the changes have come from and no way of comparing other variables that are not in the tests.

This is a problem because when unexpected diffs come up, if it is not easy to diagnose them it is tempting to just to a superficial check of the stats and then accept the new values.

The solution could be to put a lot more variables into the tests but this will make them bigger that what is needed for their intended use of keeping track of model performance.  

So we need some alternative methods to: 
- enable quick determination of which simulations differences are coming from.  The baseline file system use to enable this.  Some sort of system where we have baseline files under version control but the files that are committed on a merge are always the ones that Scoop produces would work.  This way a pull will give you the baseline files for the current master but it is not necessary to push the correct version of baseline files with each pull request.
- enable detailed comparison of simulation results from two versions to work out exactly what is causing diffs.  A diff of every variable for a single simulation between the current source code and the master source code would achieve this.  If we new what simulation(s) was(were) causing the problem(s) we could switch to the master branch.  Run this simulation in 'OutputEverything' mode Save the results into a csv file, switch back to the current branch, re-run the model in mode in 'OutputEveryting mode and diff the two files.  The table compare functionality in BeyondCompare will then enable quick identification of which variables started changing first, leading us the to root of the problem.  So to crack this one we need some sort of method that allows us to dump all properties into a file that can be diffed (excel or csv).

**Comment by hol353** [comment]
Completed here: http://www.apsim.info/APSIM.PerformanceTests.Portal/
