### ISSUE TITLE
Lentil Model - How to access

### ISSUE THREAD

**Issue by daianfrancia** [APSIMInitiative/ApsimX#7993]
### What is your question?

Hi everyone! Some months ago I saw that the lentil model was under development and from the Git issue (https://github.com/APSIMInitiative/ApsimX/issues/5288) I figure that it has already been released or is just about to. However I do not see it among the examples that APSIM provides with. Can anyone help me to have access to it? Thanks!

**Comment by hut104** [comment]
Unfortunately, the Lentil model development will be commencing within a project starting over the coming months.  There have been some conversations on who may undertake the task of creating the model with funding for those works to follow.
________________________________
From: Daián Francia Laurenzo ***@***.***>
Sent: Wednesday, 17 May 2023 10:18 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Lentil Model - How to access (Issue #7993)


What is your question?

Hi everyone! Some months ago I saw that the lentil model was under development and from the Git issue (#5288<https://github.com/APSIMInitiative/ApsimX/issues/5288>) I figure that it has already been released or is just about to. However I do not see it among the examples that APSIM provides with. Can anyone help me to have access to it? Thanks!

**Comment by daianfrancia** [comment]
Alright @hut104. Thanks for the information and sorry for the delay to answer. We're looking to adapt an existing model to develop hairy vetch model, anyone working in this?
