### ISSUE TITLE
Implict calculation of thermal time in TropicalPasture Module

### ISSUE THREAD

**Issue by MAGALA-RICHARD** [APSIMInitiative/ApsimX#7994]
### What is your question?

The TropicalPasture Module in the APSIM next generation prototype lacks clarity in how thermal time calculation is done. I expected XY pair but it only exhibits a fixed value of 1. Is the the thermal time calculated internally.
![tripical_thermal_time_pci](https://github.com/APSIMInitiative/ApsimX/assets/105811040/fb5d2afe-b842-46f6-a02b-f0bafe0e3ea1)

**Comment by hut104** [comment]
Please note that this model is only a prototype, and not operational.
________________________________
From: MAGALA-RICHARD ***@***.***>
Sent: Thursday, 18 May 2023 11:08 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Implict calculation of thermal time in TropicalPasture Module (Issue #7994)


What is your question?

The TropicalPasture Module in the APSIM next generation prototype lacks clarity in how thermal time calculation is done. I expected XY pair but it only exhibits a fixed value of 1. Is the the thermal time calculated internally.
[tripical_thermal_time_pci]<https://user-images.githubusercontent.com/105811040/239108596-fb5d2afe-b842-46f6-a02b-f0bafe0e3ea1.PNG>
