### ISSUE TITLE
netcoreapp3.1 in apsimx?

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#7998]
### What is your question?

With the latest version of APSIMX (mater branch today), I cannot compile with framework `netcoreapp3.1`.  The error message

C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5)
: error NETSDK1005: Assets file 'C:\APSIMNG\NPI2\ApsimX\Models\obj\project.assets.json' doesn't have a target for 'netc
oreapp3.1'. Ensure that restore has run and that you have included 'netcoreapp3.1' in the TargetFrameworks for your pro
ject. [C:\APSIMNG\NPI2\ApsimX\Models\Models.csproj::TargetFramework=netcoreapp3.1]

Is netcoreapp removed from apsimx?  How should I compile netcoreapp now?

**Comment by par456** [comment]
We recently stopped targeting net3.1 in the apsimx build, as we were targeting both 3.1 and 6.0 and wanted to simplify that process. 

I think you've found a 3.1 link that was missed during that process, so can you let me know how you are compiling apsimx (a build command, visual studio etc) and what platform you are building for, and I'll track down the problem.

**Comment by byzheng** [comment]
Thanks @par456, I tried to compile APSIM NG into Linux with command 

```
dotnet publish -c Release -f net6.0 -r ubuntu.20.04-x64 --self-contained  Models.csproj
dotnet publish -c Release -f net6.0 -r sles.15-x64  --self-contained Models.csproj
```

Seems net6.0 also works for ubuntu.

**Comment by peter-devoil** [comment]
I dont have a problem building on ubuntu 20.04 once dotnet-sdk-6.0 is installed.

**Comment by par456** [comment]
Thanks Peter, I think this issue is now that the linux build documentation is out of date. We'll add it to our list of tasks to fix up.
