### ISSUE TITLE
How to set Factorial Experiment changing cultivars?

### ISSUE THREAD

**Issue by JRichetti** [APSIMInitiative/ApsimX#8000]
### What is your question?

Howdy, APSIMx ninjas!

I'm trying to set a Factorial Experiment, only changing cultivars. I tried to set it as in the pic below, but it didn't work. I don't know how to set this properly.

![image](https://github.com/APSIMInitiative/ApsimX/assets/21336666/4beaa52a-6b33-4589-84bb-ad067ccf0a00)

I also tried:
[SowingRule].CultivarName = "Yitpi", "Scepter"
[SowingRule].CultivarName = Yitpi, Scepter

The error APSIM gives me is meaningless to me.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Models.Core.Run.SimulationDescription.ToSimulation() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 187
   at Models.Core.Run.SimulationDescription.Prepare() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 104
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 213
```

Thanks!

**Comment by KeLiu7** [comment]
[SowingRule].Script.CultivarName=hartog, dekan, Axe.

You need to have the cultivar in your sowingRule as well. I just tried and it works well.

![image](https://github.com/APSIMInitiative/ApsimX/assets/72141690/ba0bb146-01d0-41cb-8c74-3bb9d227c5a4)

**Comment by JRichetti** [comment]
Can you elaborate a little bit more? I could not reproduce what you showed. What do you mean by having the cultivar in the sowing rule? I'm using the 'Sow using a variable rule' from the toolbox. It only allows the selection of one cultivar.

I thought I was missing the ".Script." but adding that did not solve my problem, I still received the same error.

**Comment by par456** [comment]
Can you upload a copy of your apsim file? I have some ideas what might be causing your error, but I think I'll need to run it on my end to work it out.

**Comment by JRichetti** [comment]
It is not a particular apsim file, @par456 
I just can't make it work with sowing rule like @KeLiu7 shown.

**Comment by par456** [comment]
I rebuilt what you showed in your picture at the top here and was able to get the same error, there were two things going wrong I had to fix.

The first is that your Simulation node needs to be a child of the Experiment node like so, that's what caused the linking error you saw.
![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/9b071b23-3800-4f8b-97b9-b1cd77d05145)

Then as @KeLiu7 said, you need .Script in the factor line to have it work correctly:
`[Sow using a variable rule].Script.CultivarName = Yitpi, Scepter`

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/115f7f0f-8501-45f5-ae6e-3a04c1f2423c)

Doing both of these fixes solved the problem and it ran no problems.

**Comment by JRichetti** [comment]
Ah! That was the missing bit. Thanks. The Simulation needs to be in the Experiment; I overlooked that. Thank you very much!

**Comment by JRichetti** [comment]
Ah! That was the missing bit. Thanks. The Simulation needs to be in the Experiment; I overlooked that. Thank you very much!
