### ISSUE TITLE
Use of IClock consistently / Custom clock models

### ISSUE THREAD

**Issue by mpastell** [APSIMInitiative/ApsimX#8006]
### What happened?

Would it be possible to use IClock consistently in the codebase instead of Clock? This would enable implementation of other clock implementations. Currently the use seems to quite mixed.

We have a use case where we are calling APSIM from Python (using [Python.NET](https://github.com/pythonnet/pythonnet), code: https://github.com/TwinYields/farmingpy/blob/main/farmingpy/apsim/apsim.py) and it would be useful to be able to interact with the models when the simulation is running which could be implemented with a custom clock. This would enable writing management scripts in Python and also enable to more easily to combine simulations with neural networks etc.

I tried to implement earlier this year https://github.com/APSIMInitiative/ApsimX/pull/7720 and would be happy to update the pull request to work with current master.

### What Operating System are you on?

Windows

**Comment by hol353** [comment]
I'm keen for this to happen. Update your pull request and get it to run green.

**Comment by mpastell** [comment]
Thanks! I I made new pull request implementing the change, happy to receive feedback.
