### ISSUE TITLE
Isric soil giving high initial soil water and simulations not responding to initial soil water

### ISSUE THREAD

**Issue by VimbayiChimonyo** [APSIMInitiative/ApsimX#8035]
Hello

We downloaded soil parameters using the APSIMx add-on function. Our initial soil water was very high (>200% PAW). We tried to correct this manually and even added a factorial for initial soil water to check the model's sensitivity. However, yield did not change with changes in initial soil water (rainfed conditions). I am attaching the file

Not sure if it is a bug or we are doing something wrong.

Can you please assist

[MaizeFactorialAugSep.zip](https://github.com/APSIMInitiative/ApsimX/files/11593502/MaizeFactorialAugSep.zip)

**Comment by hol353** [comment]
You didn't attach your weather file so I can't run your simulation. You also don't mention which version you are running.

I used another weather file and the latest version of APSIM and can't see the problem. 

* Where are you seeing initial soil water being very high?
* When I click on Water under the soil I see PAW = 56mm which is 25% full.
* I notice you have 2 base simulations under your experiment. Only one base simulation is supported.

**Comment by Janewanguimugo** [comment]
Hello...
-We are running APSIM version 2023.5.7220.0
-We have set the water InitialPAWmm= 56, 112, 169 there is no difference in yield for all as seen below
![image](https://github.com/APSIMInitiative/ApsimX/assets/103818039/13bec613-8b13-4c6f-b46f-1b1d97d27398)
Here is the new file with the weather attached

[MaizeFactorialAugSep.zip](https://github.com/APSIMInitiative/ApsimX/files/11688649/MaizeFactorialAugSep.zip)

**Comment by hol353** [comment]
I've had a quick look at your simulations. The reason the maize model shows no difference in yield is because there is a lot of water in the simulation. Your in-crop rainfall is > 1000mm. Varying your starting water will have no effect as the maize crop has sufficient water even when starting water = 0mm.

**Comment by par456** [comment]
Closing this as I think the question has been answered. If not, leave a comment and I'll reopen it.
