### ISSUE TITLE
APSIM web server location

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#8037]
### What is your question?

Has the APSIM web server changed? It used to be wpext2-prod.it.csiro.au where I had rights to ftp to the CLEM folder to update CLEM Help system? I need access to the current location.

**Comment by hol353** [comment]
Yes, CSIRO IM&T migrated it to wpext3-prod.it.csiro.au back in March.

**Comment by lie112** [comment]
That's how long it's been since I updated the website
Would my access have transferred to the new server
I get access denied, Authentication failed.

**Comment by hol353** [comment]
No idea sorry. I had nothing to do with the transition. Talk to Andrew Wright (IMT)
