### ISSUE TITLE
Add CLI --edit-file option to save modified .apsimx file *without* running simulation

### ISSUE THREAD

**Issue by asherbender** [APSIMInitiative/ApsimX#8038]
Currently the CLI provides an interface for editing a file before running it:

`Models --edit /path/to/config/file.txt /path/to/file.apsimx`

I believe this is done in memory and there is no way to access the modified simulation?

It would be useful to have an interface for modifying the file and writing the new configuration to file _without_ running a simulation. I do not believe this would be a large change (the `--edit` CLI implements ~99% of this feature!). 

For instance, editing a file in-place _without_ running the simulation:

`Models --edit-file /path/to/config/file.txt /path/to/file.apsimx`

or write the changes to a new file _without_ running the simulation:

`Models --edit-file /path/to/config/file.txt /path/to/file.apsimx /path/to/newfile.apsimx`

The new simulation could then be run with a regular call to:

`Models file.apsimx` or `Models newfile.apsimx`

This feature would allow users some ability to configure simulations programmatically AND keep the simulation file as a record.

Some relation to Issue #6339

**Comment by peter-devoil** [comment]
Can I add a vote for a new flag pls? I'd hate to have an old batch file unintentionally modify a template..

**Comment by asherbender** [comment]
> Can I add a vote for a new flag pls? I'd hate to have an old batch file unintentionally modify a template..

I updated the title and text to reflect this. A breaking change would cause headaches!

**Comment by ric394** [comment]
As discussed, this will not be merged, but instead be replaced with the new --apply switch workflow. See #8045
