### ISSUE TITLE
Crops not available in Apsim next gen

### ISSUE THREAD

**Issue by FekreMih** [APSIMInitiative/ApsimX#8039]
### What is your question?

Hello,

I would like to ask assistance on how to work with crops not yet included in APSIM next generation such as Faba bean and Lucerne. One of the things I am doing now is replacing them such as red clover with lucerne, and chickpea with Faba bean. 

Thanks. 
Fekre

**Comment by hol353** [comment]
If next gen doesn't have the crops that you need there are three options. 
* Do what you are doing and find another crop model that can substituted for the crop that you want.
* Build a new model. This is a big task that requires a good experimental data set and the knowledge of how to build a model.
* Use the older APSIM 7.10.

**Comment by FekreMih** [comment]
Thanks, this helps.
