### ISSUE TITLE
Report Module rounding numbers

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#804]
E.g.  In Maize validation, in the Australia folder, Experiment DRK2, the first treatment 'SowingDec11' the variable Maize.Leaf.AppearedCohortNo has a value of 19.120 when the crop is harvested (See first screen shot).  However, when this variable is aliased and reported as 'FinalLeafNumber' on Harvest (2nd screen shot) it reports a value of 20 (Third Screen shot).  This is making the test for final leaf number crappy because all the FLN numbers are being rounded up.
![image](https://cloud.githubusercontent.com/assets/7295858/14760647/a6eb954e-099d-11e6-861c-68b4b6d81d4e.png)
![image](https://cloud.githubusercontent.com/assets/7295858/14760692/be1adc24-099e-11e6-9b00-1f66d38d784b.png)
![image](https://cloud.githubusercontent.com/assets/7295858/14760679/6c9b705c-099e-11e6-84d6-4a500b76dc17.png)

**Comment by HamishBrownPFR** [comment]
I just tried removing the alias and it still rounds the number up.

**Comment by cla473** [comment]
This is not actually a rounding issue.  This is related to the order of the events in clock.cs and the code associated in determining what is output as the AppearedCohortNo.  The order of clock.cs has DoManagement (in this instance, harvest), DoPotentialPlantGrowth (which impacts of Node and Leaf Counts), and at the end of the day, DoReport.
When retrieving the data (from Leaf.cs), there is an if statement 'If (Final Leave Appeared) then AppearedCohortNo = AppearedCohortCount - (1-FinalLeafFraction).  This is returned by DoReport on each day, returning a decimal value.  FinalLeafAppeared = (is MainstemNodeNo < MainstemFinalNodeNumber), which returns true.  
The clock clicks over to the next day, and DoManagement (Harvest) is triggered. FinalLeaveAppeared returns false, which means it only returns the AppearedCohortNo, which is an integer.
This appears to be an issue with the order that events occur in Clock.cs.  The output value for the Daily Report occurs the day before the Harvest Report value is output.

**Comment by HamishBrownPFR** [comment]
Since refactoring the leaf appearance code, the way FLN is being reported in the Maize validation is no longer appropriated.  Will close this bug.  We really need to get the observations and reporting tidied up for maize like we have got it not for wheat and chickpea
