### ISSUE TITLE
CourseRoot organ in Eucalyptus and Pinus shouldn't be aboveground

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#8051]
### What is your question?

The CourseRoot organ in the Pinus and Eucalyptus models is currently aboveground. This was probably not an issue for the validation work orginally, as those datasets were all or mostly only for one rotation. (I need to check if any went for more than one rotation.)  

Now I am doing multi-rotation simulations, courseroot biomass, which can be considerable, is being added to the surface at harvest, which might upset to some degree soil evaporation, erosion, energy balance, decomposition and N availability. Overall, I suspect it will only be having a minor effect on tree growth and wood yield, but we should change it to better reflect reality anyway.

Overall allocation to courseroots should not change in the models, I suspect, but it needs to be distributed amongst soil layers. I suspect copying fineroot proportional allocations to depths would be a good enough approximation. As courseroots have minimal or no sensence, they should accumulate in sizable biomass mostly in surface layers, which could be in contrast to fine roots that have a short lifespan. There are few data in the validation datasets on this, but some.

In changing this organ to below-ground, should I detick the 'aboveground box' of the organ? Then what? Do I need to add the RootShape model to that organ?

If you want me to have a go at this, please set me up with an editable version of the Pinus and Eucalyptus models, which so far I have not had success in doing by working with them in Replacements.

**Comment by sme016** [comment]
@hut104 what do you think could be a strategy to put CoarseRoot belowground?

**Comment by sme016** [comment]
@hol353 I need to resolve this in a week or so. Can you please advise on how I can go about making this correction.
The attached simulation includes the Eucalyptus.json from master included in replacements and the coarse root organ deticked for IsAboveGround, and also no BiomassRemovalDefaults putting organic matter on the surface, but it still does at each Harvest for all the 'Rem' (removal) treatments according to the graph of SurfaceOM. 
[Slash.zip](https://github.com/APSIMInitiative/ApsimX/files/11952727/Slash.zip)

**Comment by hol353** [comment]
IsAboveGround is only used by livestock to determine if an organ is consumable i.e. above ground. If you set it to false for CoarseRoot then nothing should change. 

I've had a look at your simulation and have found a bug in perennial leaf where the live and dead pools were NOT being updated correctly following a biomass removal. PR #8117 fixes this problem.

I also had to change your biomass removal defaults for coarse and fine root. If you set all the harvest defaults to 0 then no biomass is removed at harvest but what happens is that at EndCrop (the next day of simulation) any remaining biomass is automatically moved to surface organic matter. Instead set the defaults for coarse and fine root 'remove from system' to 1. That way there won't be any left over biomass following harvest.

**Comment by sme016** [comment]
Thanks, but I am not sure that achieves the option I need. When a plantation is harvested or thinned or some trees die, in 99.9% of cases no roots coarse or fine are touched, but simply die in situ. So we need, I assume, in APSIM to be able on those occassions to send coarse and fine roots to the FOM pool of the soil depth they grew in. None should be put on the surface. On very rare occassions, coarse roots are also removed with heavy equipment, but it is so rare I don't think we need to worry about it yet.

**Comment by hol353** [comment]
Ah ok. So the problem here is that coarse and fine roots are implemented as a generic organ, not a proper root organ. They have no concept of a root depth or of roots (biomass) occupying layers. I could write code to send roots to the soil but to which layers? All layers uniformly? 

Ideally, to do this properly there should probably be a generic below ground organ rather than hacking generic organ to do something that it wasn't intended to do. To hack generic organ I'd have to do something like:
```c#
 public virtual void RemoveBiomass(string biomassRemoveType, OrganBiomassRemovalType amountToRemove)
 {
     if (IsAboveGround)
         biomassRemovalModel.RemoveBiomass(biomassRemoveType, amountToRemove, Live, Dead, Removed, Detached);
     else
         biomassRemovalModel.RemoveBiomassToSoil(biomassRemoveType, amountToRemove, Live, Dead, Removed, Detached);
 }
```
This isn't very nice. I'd still have to do something about what layers to put the biomass in.

BTW: Neil is on holiday this week and unable to advise on a way to resolve this.

**Comment by sme016** [comment]
Thanks. Equal distribution won't be correct. So I think the first thing to do is for me to find a generic depth function for biomass distribution for fine and coarse roots scaled to maximum rooting depth that APSIM already calculates. Is tha OK? 
By then Neil might be back from leave, as it would be good to have his input too, and I think a generic below ground organ like you say should be our aim, but also to have the biomass distribution built into the FineRoot (Root) organ that does water and N uptake.

**Comment by hol353** [comment]
Sounds ok to me. Neil and I are at a conference next week in Darwin so won't be much time for APSIM changes.
