### ISSUE TITLE
GitHub Repo Info out of date

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#8061]
### What happened?

Viewing Community Standards on APSIMX Project in Github
https://github.com/APSIMInitiative/ApsimX/community

The readme is somewhat out of date (not sure we can run APSIM on a windows vista machine with 2MB of RAM)
https://github.com/APSIMInitiative/ApsimX/blob/master/README.md

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
The readme has been updated in PR #8317.
