### ISSUE TITLE
DateTime.ToString (dd-mmm) now returns long month names

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#8062]
### What happened?

Lines of code like this
```C#
                        EmergenceDate = Convert.ToDateTime(row[CultivarName]);
                        EmergenceString = EmergenceDate.ToString("dd-MMM");
```
In the wheat validation at
.Simulations.Validation.NPIField2020.Urrbrae2020.Urrbrae2020Base.Field.Sowing

Now returns dates with long month names such as "June" rather than "Jun" and so GetDate function now fails.

### What Operating System are you on?

Windows

**Comment by par456** [comment]
It's running with no errors on my end with the latest version of apsim. I also put a debug into the script and my dates are being returned as dd-MMM (so Jun instead of June)

Not sure what's happening on your end Neil, but that's also why jenkins doesn't have a problem.

**Comment by hol353** [comment]
I'm seeing it too on my PC. See: https://stackoverflow.com/questions/76405816/incorrect-date-formatting-for-mmm-in-net-in-unix-containers. If I use InvariantCulture the problem disappears.

```c#
 EmergenceString = EmergenceDate.ToString("dd-MMM", CultureInfo.InvariantCulture);
```

**Comment by hol353** [comment]
Apparently it is by design: https://github.com/dotnet/runtime/issues/86643
