### ISSUE TITLE
Why is Jenkins running green when the wheat validation is failing?

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#8064]
### What happened?

An error is identified in #8062 and this causes simulations to fail.
However, Jenkins build for Pull Request Camp tidyup #7727 has a green tick next to the build test.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
Jenkins was running on a different dotnet version than windows 11.
In regards to #7727, there is a bug described in #8066 that inconsistently returns a crash.
