### ISSUE TITLE
Export database to excel or text throws date error

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8069]
### What happened?

Try exporting the database from tests/validataion/Barley/Barley.apsimx and you will see what I mean

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Hi Hamish,

This seems to be a problem with the Observed files, as Observed.xlsx has a Sowing value that is a number and TOS column with a date, while the Obs_APSIMX_NPIField2019_Barley.xlsx has a TOS with a number and Sowing with a date. These are getting combined into the Observed in Apsim and it fails when trying to convert them back out again.

You can see this in apsim if you scroll down the Observed data:

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/a7eddfc9-49e1-4efd-8903-3f85375bd700)

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/f54be91a-f271-4f2e-b569-ad71b6a36b50)
