### ISSUE TITLE
Add error if invalid remove or return fractions set in residue

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8074]
### What happened?

RemovalFractions is passed into BiomassRemove() in plant to specify the proporitons of biomass removed (from the system) and returned (to SOM).  They should only ever be between 0 and 1 but currently can be set at any value.  Need error message

### What Operating System are you on?

Windows

**Comment by sme016** [comment]
Thanks for alerting me to this poroblem. It results from actual forest plot measurements where a measurer thought a tree dead at one stage (or forgot to include it) then later considered it a live tree (or found it again). Multi-stem trees can also cause problems, if all stems large enough are considered individuals in the population, and as some larger ones die and some smaller ones grow into bigfger ones and start to be counted. I suppose this error in these models is causes C and N mass balance errors. 

Where this occurs in a validation, I'll have to design a new DoThin trajectory to end up with the final meaured population density. I think your solution will provide a positive bias to actual final population densities, which I'd like to avoid. I'll try to make the changes required and commit new validations for Eucalyptus and Pinus, but I need a few weeks to do this.

Related question: Is there not a C and N mass balance check done at the validaiton stage on all models? I.e. changes in the total of all pools start to finish of simulation should equal the sum of all the inputs and outputs to the system. If we did that, I wonder if other issues might arise in these models or other models.
