### ISSUE TITLE
How to add the intercrop management in APSIMX

### ISSUE THREAD

**Issue by Demoncx** [APSIMInitiative/ApsimX#8079]
Hi,
I have an intercropping system with oilseed flax(built by canola) and soybean that I would want to model in APSIM next generation to make some system assessments. But I didn't find a 'manager' component to build my intercropping experimental design when I have had a look around the web and in ApsimX. 

What component should I build to fill in the crop planting rules for intercropping, such as four rows of oilseed flax followed by two rows of soybean.Whether there is an existing intercropping manager component in APSIMX?

thanks

**Comment by Demoncx** [comment]
@kiwiroy @jbrider

**Comment by Demoncx** [comment]
hello

**Comment by jbrider** [comment]
@hut104 is probably the most familiar with setting up something like this?
I think there was an example involving multiple root zones - which from the configuration you are suggesting, might be needed?

**Comment by Demoncx** [comment]
@jbrider thanks for your comments, and apologies for this belated reply.
Well, where should I look for this?

thank you very much for your help！

**Comment by Demoncx** [comment]
Are there any examples of intercropping in APSIMX?
