### ISSUE TITLE
Graph throw error on simulation names with - in them

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#808]
this is a problem because it means you can't use dates as factor levels.

Try to graph something from the FlagNFlowers table in WheatValidation.apsimx for a test case

**Comment by hol353** [comment]
Can't reproduce this. The Factorial Example has sowing date as a factor and hence it has dashes in the simulation names. I can create a graph just fine and have the simulation names show up in the legend.
