### ISSUE TITLE
Add TreeThinning model to Manager toolbox

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8084]
### Describe the new feature

#8075 identified an issue with the TreeThinning script in Eucalypt and Pinus tests.

Need to check the utility of the fix implemented in #8075 and put TreeThinning script into manager toolbox.

Liase with @sme016 to progress

**Comment by sme016** [comment]
The attached simulation has two tools that do thinning
[ThinningTool.zip](https://github.com/APSIMInitiative/ApsimX/files/11765938/ThinningTool.zip)
: TreeThinning and TreeThinningFromAboveOrBelow. Both are in the Pinus example in the GUI. The latter is a minor variation of the former for when a thinning is biased towards retaining or removing the larger trees such that average tree size changes, which is very common in forestry or with mortality. Note that I have introduced and used a ThinBias factor. If its value is 1, then the latter tool should provide the same results as the first tool.  
Please check the logic of the code. If ok, can you provide an entry option for ThinBias in Parameters, then add it to the Management toolbox simply called TreeThinning.
Is that ok @hut104 ?
