### ISSUE TITLE
Future weather

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8085]
### Describe the new feature

#8073 needs to access future weather to derive coefficients for each sowing of SCRUM.  It has implemented some bad code to do this but there will be a need for other models to access future weather so would be useful to implement a tidy and efficient way of doing this.

Currently weather properties (e.g MinT) are read in each day of the simulation time step and trying to call GetMetData(Date) causes errors if called more than once per day.

Maybe change each property to a DateTime indexed dictionary: 
Dictionary<DateTime, double> MinT
Which are established on start of simulation:
Current references to MinT would be replaced with MinT[Today] and future (or past) references would a be MinT[DateOfInterest]

**Comment by hol353** [comment]
@par456 I think the easiest way to do this is to get ```c# Weather.GetMetData(DateTime date)``` working for dates > clock.Today. We don't want to load the whole weather file at start of simulation though as that will incur an unnecessary time penalty for 99% simulations that don't need it. Instead, only load the file contents when necessary in GetMetData. Create a unit test to exercise.
