### ISSUE TITLE
Error in Agpasture digestibility?

### ISSUE THREAD

**Issue by mpastell** [APSIMInitiative/ApsimX#8086]
### What happened?

There seems to be an error in how AgPasture `Harvestable.Digestibility` is calculated here: https://github.com/APSIMInitiative/ApsimX/blob/a2e29d4c132df74d313bf4f84039ce7dd902c7d7/Models/AgPasture/PastureSpecies.cs#L2195 This causes the digestibility to get very high values e.g. after a calling: 

```
AGPRyegrass.RemoveBiomass(AGPRyegrass.Harvestable.Wt);
```

The code divides `DMTotal` by `DMTotalHarvestable` which is probably not right?

[AGP_digestibility.zip](https://github.com/APSIMInitiative/ApsimX/files/11743038/AGP_digestibility.zip)

### What Operating System are you on?

Windows

**Comment by sno036** [comment]
Thanks for letting us know about that @mpastell. I'll look at it during the next sprint on pasture type work (not scheduled yet). Is this causing any particular issues for you right now?

**Comment by rcichota** [comment]
@mpastell is right, the calculation should use only DMTotalHarvestable. 
As a work around, one can compute the digestibility in a manager script using the corrected version that you see in the model's code. Hopefully this works for now until we fix the code...

**Comment by mpastell** [comment]
@sno036 @rcichota Thanks for the responses. We are currently evaluating the use of AgPasture for timothy in Finland when noticing the issue (One of the experiments has been published here : https://doi.org/10.1111/gfs.12461 ). We can use a custom build of APSIM for now as a quick fix.

**Comment by sno036** [comment]
Reopening as I think this may have caused another issue.

![image](https://github.com/APSIMInitiative/ApsimX/assets/12176269/227a9e06-3da3-4c95-a526-c6a4bae71c2a)
Above works

But when that field is blank then object reference error
![image](https://github.com/APSIMInitiative/ApsimX/assets/12176269/2890e058-770d-4ba8-a2d4-24938fff8ccc)

**Comment by sno036** [comment]
[New folder.zip](https://github.com/APSIMInitiative/ApsimX/files/14475593/New.folder.zip)
Example
