### ISSUE TITLE
Graphs have started treating some observed data sets as categorical.

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8088]
### What happened?

This means they don't show up on graphs (when put on the same graph as non-problematic data) or don't graph properly
I have struck it this week in a number of test sets that are not in the bulid system but here is an example that is. 
Prototypes/Orchard/Orchard.apsimx.  The graph of ProfileSoilWater has two Series (Predicted and Observed) but only the data from the predicted series are showing. as seed below in the first screen shot.  If you delete the Predicted Series the Observed data will show up but is not plotted correctly (as shown in the second screen shot).  I have seen this sort of behavior in the past where Series gets catagorical data.  
I have done a bit of testing on other data sets.  It seems if there is a missing value in a series (i.e if there is a date that has data for another variable but not the one in the series), the series becomes categorical. 
![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/6d76c098-1863-4afd-b1c5-6be00c41a619)
![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/989537cb-c75c-4048-b27e-9d430d7ded31)

This is causing us issues in current model development so any help to fix it would be much appreciated

### What Operating System are you on?

Windows

**Comment by HamishBrownPFR** [comment]
@hol353 I am having trouble progressing the simple fruit tree model development.  Would I be able to get some help to resolve this bug.  It is beyond me

**Comment by par456** [comment]
I just opened up the Orchard prototype and it's graphing correctly for me. I would guess that something has changed in the observed files on your end compared to what is in the current build.

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/1495d583-c8b7-4a79-b747-137f4b2a9ea0)

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/22eaf4d6-71da-4154-800c-44d4edc96df4)

**Comment by par456** [comment]
Was most likely related to #8067, confirmed working on latest build.
