### ISSUE TITLE
How to modify parameters like "cardinal temps" in Apsim NextGen?

### ISSUE THREAD

**Issue by sunjianxin** [APSIMInitiative/ApsimX#8089]
### What is your question?

Dear Authors

We are doing a simulation using Apsim Nextgen to predict the biomass of Rye. We successfully did a modified wheat simulation for Rye using classic Apsim through a . XML file. We now basically need to replicate the same modification to Apsim Nextgen.

What we need to adjust in Apsim Nextgen are:
1. Cardinal temps
Classic Apsim Modification: 
**_<x_temp units="oC" description="cardinal temps.">0  18  30</x_temp>
<y_tt units="oCd" description="effective thermal time">0  18   0</y_tt>_**
2. Vernalization sensitivity
Classic Apsim Modification: 
**_<vern_sens>1.5</vern_sens>_**
3. Soil water required for germination at seeding depth
Classic Apsim Modification: 
**_<pesw_germ units="mm/mm" description="plant extractable soil water in seedling layer inadequate for germination (mm/mm)">0.15</pesw_germ>_**
4. Extinction coefficient
Classic Apsim Modification: 
**_<y_extinct_coef>0.35 0.35 0.35</y_extinct_coef>_**

We did not find those parameter names (for example the pesw_germ) in the cultivar modification as shown in the attached screenshot. Could you please show us how to do that in Apsim Nextgen? 

Thank you so much for the help!

Best,
Jianxin
<img width="654" alt="n1" src="https://github.com/APSIMInitiative/ApsimX/assets/6218289/fb65ad7b-15b9-43a2-80ec-645642c9e0eb">

**Comment by hut104** [comment]
If you right click on the wheat model you can get it to show you the model structure.  This will give you help on addresses for variables.
However, I would strongly advise against changing the cardinal temperatures without considering the impact on the VERY large number of parameters that are related (ie units include degree days).  This includes leaf appearance rates, durations of phenological phases, rates of processes express in terms of degree days, etc.  Even grain filling rates will be impacted.  Changing thermal time accumulation is fraught.
Ther vernalisation model is also very different to APSIM 7.10 and so I would suggest reading about the new model in papers such as those by Brown et al before proceeding.
