### ISSUE TITLE
Report Model error and intellisence issue

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#809]
When typing a calculation in the Report model, such as

`Wheat.Total.Wt+1.1`

ApsimX immediately throws an error when typing the dot after "1". The same happens with `Wheat.Total.Wt+Wheat.`, but not with only `1.1`.

@intellisence:
`[Wheat].` opens the intellisence as expected, but
`[Wheat].Total.Wt+[Wheat].` gives other and very limited operations (such as "CompareTo").

**Comment by hol353** [comment]
This has been fixed. The intellisense works better when Wheat has square brackets around it e.g. [Wheat].Total.Wt rather than Wheat.Total.Wt
