### ISSUE TITLE
Eliminate -ve DoThin values in Eucalyptus and Pinus

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#8091]
### What happened?

Some DoThin values in Eucalyptus and Pinus are -ve, which shouldn't be the case. Minor chagnes are needed, while reaching same final stocking. 

### What Operating System are you on?

Windows

**Comment by sme016** [comment]
Related to #8074

**Comment by par456** [comment]
Pull request was merged, closing issue.
