### ISSUE TITLE
Make parameterisation of SWIM3's hydraulic property parameterisation accessible

### ISSUE THREAD

**Issue by KirstenVer** [APSIMInitiative/ApsimX#8106]
### Describe the new feature

We would like to explore the effect SWIM3's hydraulic property parameterisation may have on depth of drying simulated, which seems insufficient currently. If not included as user-input, then please provide script to help us assess.

**Comment by hut104** [comment]
We will first try by making the PoreInteractionIndex value settable by the user using a manager script.  If this functionality is useful, we can try other properties.
We can then consider what is required within the user interface

**Comment by hut104** [comment]
An ability to set values for the PoreInteractionIndex has been developed.  The value can be set via the manager scripts as follows:

```
using System;
using Models.Core;
using Models.Interfaces;
using Models.PMF;
using APSIM.Shared.Utilities;

namespace Models
{
    [Serializable]
    public class Script : Model
    {
        [Link] IClock Clock;
        [Link] ISummary Summary;
        [Link] ISoilWater swim3;

        [EventSubscribe("StartOfSimulation")]
        private void DoStartOfSimulation(object sender, EventArgs e)
        {
            // Called once 
            double[] p = new double[19];
            Array.Fill(p,5.0);
            swim3.PoreInteractionIndex = p;
            
        }
    }
}
```
Use of the code to change P to 1 or 5 has the following effect on K(pF).  
_Note that P operates in the micropore space and so K(pF) is not effected above DUL (ie pF=2)_

![image](https://github.com/APSIMInitiative/ApsimX/assets/11881178/03941168-7e36-482a-9649-93e72441c1ab)

**Comment by hol353** [comment]
@hut104 Is this still an issue or can we close it?
