### ISSUE TITLE
RUE reduction factor

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/ApsimX#8109]
### What is your question?

Dear all,

In Next Gen Barley/wheat, RUE is adjusted according to stress factors using the equation below such as nutrition (FN), air temperature (FT), vapour pressure deficit (FVPD), water supply (FW) and atmospheric CO2 concentration (FCO2).

RueReductionFactor = min(FT, FN, FVPD) * FW * FCO2 

My question is Why are FW and FCO2 muliplied, whereas FT, FN, FVPD are subject to a min?

@jbrider @sno036 @hut104 @kiwiroy Could you please help to explaine the reason? Thanks

**Comment by hut104** [comment]
Hi,
This approach follows that used on models such as 3PG etc.
Potential (non water limited) photosynthesis is calculated from RUE and Radiation, with modifiers for things like temperature, nutrition and VPD).  The modifiers in that list are used to estimate stomatal conductance and therefore potential water use.  FW is calculated from water demand vs water supply, and so is applied after the others.

**Comment by KeLiu7** [comment]
> Hi, This approach follows that used on models such as 3PG etc. Potential (non water limited) photosynthesis is calculated from RUE and Radiation, with modifiers for things like temperature, nutrition and VPD). The modifiers in that list are used to estimate stomatal conductance and therefore potential water use. FW is calculated from water demand vs water supply, and so is applied after the others.

Thanks Neil for your reply😊
