### ISSUE TITLE
Excelinput throws error

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#813]
When clicking the "EXCEL file name" - "value" field, Apsim throws an error. I've tried this in my simulations as well as in the standard toolbox, with the same result.

**Comment by HamishBrownPFR** [comment]
I have this error too.  See screen shot

![image](https://cloud.githubusercontent.com/assets/7295858/14897984/a00b0720-0dd8-11e6-8c83-9c6a69bdaa2f.png)
