### ISSUE TITLE
Unable to open APSIM

### ISSUE THREAD

**Issue by bernisschow** [APSIMInitiative/ApsimX#8135]
### What happened?

I am able to download the most updated APSIM Next Gen on MacOS but am unable to open the application even after allowing it on my system's privacy settings.

Please advise on what to do, thank you.

### What Operating System are you on?

MacOS

**Comment by her123** [comment]
See the issue #7932

**Comment by ric394** [comment]
If this issue is still a problem please feel free to reopen but for now i'll close this issue.
