### ISSUE TITLE
Load external assemblies into manager code?

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#8141]
### What is your question?

In classic, we used to be able to load external assemblies into manager code. Is there a way to do this in nextgen, without adding it to the [big long list](https://github.com/APSIMInitiative/ApsimX/blob/master/Models/Core/ScriptCompiler.cs#L187) already in the script compiler?

**Comment by par456** [comment]
It is still possible, I've gone through and written up an example of how I was able to do it in a manager script.

I wrote a simple dll library to load in and test with that looked like the following, and compiled it into a dll library that was stored in the same folder as the apsimx file.
`c#
using System;

namespace TestAssembly
{
    public class TestClass
    {
        public void TestFunction()
        {
            System.Console.WriteLine("This is a test print");
        }
    }
}`

Then in my apsimx manager script I wrote this:
`c#
using System;
using System.Reflection;
using System.IO;
using Models.Core;

namespace Models
{
    [Serializable]
    public class Script : Model
    {    
		[Link]
		Simulation Simulation;
		
    	Assembly lib;
	    object TestInstance;
    
        [EventSubscribe("StartOfSimulation")]
		private void OnStartOfSimulation(object sender, EventArgs e) {
			string path = Path.GetDirectoryName(Simulation.FileName);
			lib = Assembly.LoadFrom(path + "/TestLib.dll");
			Type TestClass = lib.GetType("TestAssembly.TestClass");
			MethodInfo TestFunction = TestClass.GetMethod("TestFunction");
			TestInstance = Activator.CreateInstance(TestClass);
		}

        [EventSubscribe("DoManagement")]
        private void OnDoManagement(object sender, EventArgs e)
        {    
        	Type TestClass = lib.GetType("TestAssembly.TestClass");
        	MethodInfo TestFunction = TestClass.GetMethod("TestFunction");
        	
			TestFunction.Invoke(TestInstance, null);
        }
    }
}`

This loads in the assembly library at the start of the simulation, along with a new instance of the TestClass it contains. Then in the DoManagement event, it runs the TestFunction function that the class has. In this case I just printed a message to console to test it was working.

You cannot store the Type and MethodInfo as properties in a script as they are not serializable, so instead we have to make those references in each event we use them. This isn't too expensive in regards to time, but is something to be aware of.

It's a bit harder to use than a normal class that is built into apsim directly, but hopefully it will be useful for you.

**Comment by peter-devoil** [comment]
That's great, thanks andrew, and glad it will make its way into the docs. 

TBH, I was hoping for a general solution like the ability to "add XYZ nuget package" or similar. However the specific use case was to add System.Threading.Channels which for some perverse reason is in a separate assembly. Eventually I found another way. Other use cases have covered using a netcdf library, and IronPython..
