### ISSUE TITLE
How to activate soil parameters related to higher mineralisation in sand as per Asseng 1998

### ISSUE THREAD

**Issue by JodyBig** [APSIMInitiative/ApsimX#8143]
### What is your question?

In APSIM Classic if soil type was set to sand an alternative set of parameters describing higher rates of mineralisation in sands could be used as described by Asseng 1998. Is this option available in APSIM-X? If so, where?

**Comment by hut104** [comment]
It should be the same. Set soil type to sand. Check summary file. I think it records that it is doing this.

**Comment by JodyBig** [comment]
Thanks Neil.
For the next person how ends up here:
You can force a simulation to use the built-in parameter modifications described by Asseng et al. 1998 by entering 'sand' in the 'Soil texture or other descriptor' field for the Soil main node (see next image).
![image](https://github.com/APSIMInitiative/ApsimX/assets/29561776/8bacee7d-af91-4bd6-bdd3-9e0b168a6b1f)
However, **be warned** not all of the changes proposed by Asseng et al., 1998 were implemented. Only the potential microbial decomposition rate and the mineralisation water factor at LL15 are modified (see following images).
![image](https://github.com/APSIMInitiative/ApsimX/assets/29561776/3bc331e2-5fc7-4e0e-8664-0b536facc7d5)
![image](https://github.com/APSIMInitiative/ApsimX/assets/29561776/3c52ba3c-c1f3-49db-acbb-9f22177503ed)

Asseng, S., Fillery, I.R.P., Anderson, G.C., Dolling, P.J., Dunin, F.X., Keating, B.A., 1998. Use of the APSIM wheat model to predict yield, drainage, and NO3− leaching for a deep sand. Australian Journal of Agricultural Research 49, 363–377.

**Comment by JodyBig** [comment]
I forgot to mention there is no details reported in the summary file of a change in parameters when setting soil texture to sand.
