### ISSUE TITLE
unable to parse operation in model "Operations"

### ISSUE THREAD

**Issue by feverlii** [APSIMInitiative/ApsimX#8151]
### What happened?

Warning: unable to parse operation in model "Operations". There is no whitespace or code error. What happened? (apsimx2023.7.7271)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
This will be related to the recent DateUtility refactor, can you provide a copy of your apsim file that we could debug with?

**Comment by feverlii** [comment]
[demo.zip](https://github.com/APSIMInitiative/ApsimX/files/12065920/demo.zip)
Here is a test demo, please check it.

**Comment by par456** [comment]
Just ran that file on my end and didn't encounter any problems. Looking into this a bit deeper, that error should happen when a line in the Operations node can't be read correctly. In the example you sent me, there are no operations listed, which might be why it ran fine.

**Comment by feverlii** [comment]
But any characters I type can't be saved in the Operations.

**Comment by feverlii** [comment]
Yes, any characters I type can't be saved in the Operations, so all line are blank in the Operation.

**Comment by par456** [comment]
I see what you mean, any text I write in there is not getting saved. I will look into this further.
