### ISSUE TITLE
How to modify potential decomposition rate of wheat residue?

### ISSUE THREAD

**Issue by JodyBig** [APSIMInitiative/ApsimX#8174]
### What is your question?

Hi,

How do I modify potential decomposition rate of wheat residue? I used 'show model' on the SurfaceOrganicMatter node but it does not provide any clues. I also not sure how to use intelli-type to get a crop-specific residue parameters. i.e. [SurfaceOrganicMatter].????

Thank you
JB

**Comment by hut104** [comment]
This may be hard, unless you change the json resource and recompile.

We may need to discuss what you need and get someone to work on refactoring APSIM to allow this.
________________________________
From: Jody Biggs ***@***.***>
Sent: Thursday, 20 July 2023 3:26 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] How to modify potential decomposition rate of wheat residue? (Issue #8174)


What is your question?

Hi,

How do I modify potential decomposition rate of wheat residue? I used 'show model' on the SurfaceOrganicMatter node but it does not provide any clues. I also not sure how to use intelli-type to get a crop-specific residue parameters. i.e. [SurfaceOrganicMatter].????

Thank you
JB

**Comment by mdiancoumba** [comment]
Dear Neil
Sorry for not using a platform to ask this question.
My name is Madina Diancoumba. I am an Apsim user.  And I am arguing with a colleague about the ability of the currently released versions (classic and ApsimX) of Apsim to accurately simulate the growth of photoperiod sensitive millet and sorghum cultivars. Could you clarify us.

Thanks in advance for your response.
Kind regards,
Madina
________________________________
