### ISSUE TITLE
Intercropping (Maize-Groundnut/Soybean) Systems in Apsim New Generation

### ISSUE THREAD

**Issue by smkuhlani** [APSIMInitiative/ApsimX#8183]
### What is your question?

Is it possible to undertake Inter-cropping (Maize-Groundnut/Soybean) Simulations with the APSIM New Generation? Is there an example of such already?

**Comment by hol353** [comment]
Yes it is possible and quite easy. You just add as many crop models as you like to a field and set the management (sow, harvest etc) of the crops. APSIM will inter-crop automatically. We don't yet have an example but here is one that I built recently for someone else.

[intercrop.zip](https://github.com/APSIMInitiative/ApsimX/files/12492281/intercrop.zip)

**Comment by smkuhlani** [comment]
Received. Working well. Thank you.
