### ISSUE TITLE
Manure Injection Simulation

### ISSUE THREAD

**Issue by jakew57** [APSIMInitiative/ApsimX#8184]
### What is your question?

Hello, I am pretty new to APSIM Next Gen, and I am trying to simulate the differences in crop yield between subsurface manure injection, surface manure application, and surface application of synthetic fertilizer. Is there a way to model manure injection? I was only able to figure out surface application of manure. Thanks!

**Comment by hut104** [comment]
You could simply try cultivating the soil to move the manure into the soil as part of your experiment.  In one treatment you can add the manure to the surface, in the second you add the manure to the surface and then cultivate it in.
________________________________
From: jakew57 ***@***.***>
Sent: Wednesday, 26 July 2023 4:52 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Manure Injection Simulation (Issue #8184)


What is your question?

Hello, I am pretty new to APSIM Next Gen, and I am trying to simulate the differences in crop yield between subsurface manure injection, surface manure application, and surface application of synthetic fertilizer. Is there a way to model manure injection? I was only able to figure out surface application of manure. Thanks!
