### ISSUE TITLE
Function to accumulate thermal time from any variable 

### ISSUE THREAD

**Issue by jwhish** [APSIMInitiative/ApsimX#8186]
### Describe the new feature

Currently the list of accumulate functions need an initial growth stage to start accumulating thermal time.
however, we want to start accumulating thermal time between node 0 and node 4 on a canola plant to simulate the susceptible period for Blackleg disease and to initiate the disease growth. if we had an accumulation function that could be initiated by any variable, different use could be, to accumulate the  discount fraction from a frost counter.

**Comment by hol353** [comment]
Test simulation.

[test.zip](https://github.com/APSIMInitiative/ApsimX/files/12318627/test.zip)

**Comment by hol353** [comment]
@jwhish: I've created an AccumulateExpressionFunction that will accumulate the value of child functions when a given expression evalulates to true. In the attached test.zip above, the function F has this expression:

```c#
Wheat.Phenology.Stage > 4 && Wheat.Phenology.Stage < 6
```

This says that when Wheat.Phenology.Stage is between 4 and 6 it will accumulate the value of the child function of F which in the example is a variable reference to Thermal Time. 

The above expression could just as easily be Canola.Leaf.NodeNumber.Value() > 4.
