### ISSUE TITLE
Documentation presenter is slow to render.

### ISSUE THREAD

**Issue by ilhuber** [APSIMInitiative/ApsimX#8193]
### What happened?

It seems like when selecting a simulation node whose presenter is a DocumentationPresenter it can take a while (often more than a second) for the right hand side of the UI to render, lagging the UI pretty considerably -- especially when using the keyboard to navigate. This seems to be caused by two separate issues: building the documentation markdown takes a while, and so does drawing the markdown in a MarkdownView (mostly due to measuring out table tabstops).

### What Operating System are you on?

Windows

**Comment by par456** [comment]
If the problem is lag in the GUI when it's trying to load such a big page, it might be useful to put the markdown generation into an asynchronous method so the GUI will continue to respond even as it's loading the presenter.
