### ISSUE TITLE
DualGridView and IModelAsTable should be refactored

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8198]
Related to pull request #8190 where I ran into this problem.

This view and helper interface are the best for displaying a table GUI for a class, however they are poorly named, as it can do both single and dual grid views. It is also only used with a TablePresenter, which is only used with DualGridView, which should be more obvious.

There is also a GridView and NewGridPresenter that are tied heavily into the soil classes, as they use TabularData not a DataTable to store the grid. This refactor should address this, either by renaming this view and presenter, or by reworking them to use the more generic DualGridView that we have.

My proposal is to do some refactoring on this view and presenter to add additional properties to the ModelAsTable interface and rename each to be consistent.

In the related pull request, I added an additional panel to the top of this view to show a description and instructions on what the class is and how it can be used in the GUI. This should be incorporated into the other classes that use this view and presenter.

Summary:

ModelAsTable:
- Rename this interface to be consistent with the view and presenter
- Add Description/Instructions property that classes can provide to be shown in the GUI
- Are there other properties about the table that classes should be able to set individually without breaking our model-view pattern?

DualGridView:
- Adding a section where a description can be shown at the top of the window (should be in related pull request)
- Automatically setting the height to match the amount of text.
- Renaming this back to our default grid view, will need to deal with the soil GridView to do this.
- This should use SheetWidget instead of directly using a grid

TablePresenter:
- Give this presenter the same name as the view so that it's clear they are used together
- Find out why Grid2 has intellisense hooked up but Grid1 does not

Work out if GridView and NewGridPresenter can be adapted to work with DualGridView and TablePresenter since they are both doing similar things, but NewGridPresenter is more specialised.

Any other comments on this that should be addressed?

**Comment by hol353** [comment]
This all sounds fine. 

Perhaps this is too big for this issue but I'd like to delete the old GridView completely and move those models using it (CLEM mostly) to use the new SheetWidget instead. GridView is a very large chunk of code (~2800 lines) that has all sorts of problems.

I'd also like one way (one c# interface) for a model to be shown as a grid in the GUI. This includes the soil profile models like chemical, solute etc. Ideally, Currently we have IModelAsTable (which is nice and simple) and ITabularData which is much more complex but gives models great control over what is shown. If we decide to keep the 2 interfaces, then at least name them consistently with the presenters that use those interfaces.

**Comment by peter-devoil** [comment]
Rectangular select/cut/paste would be nice to have again

**Comment by par456** [comment]
Seems like the DualGridView should also be using sheetwidget then, instead of the current gridview (which does the gtk calls) that it builds. Seems to be a lot of overlap in the GridView and sheetwidget classes.

**Comment by HamishBrownPFR** [comment]
May also be useful to have a property display if a class has both gridded and single dimensional properties.  I.e  If I add 
[Description("Really Important setting")]
public enum settingThatIsReallyImportant {get; set;} 

to a class with dual grid view presenter, it would need to display an input field for that

**Comment by par456** [comment]
Known Bugs to fix:
[ ] Scroll bars always appear even when not required
[ ] Scroll bars do not smoothly scroll
[ ] Sheet moves when editing and it's within a Paned container
[ ] Pasting input that is larger than the graph causes it to be cut off
[ ] Moving between Physical and Organic causes rows to get deleted
