### ISSUE TITLE
Graphics in high contrast mode

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#820]
The background of graphics is black in the Windows high contrast mode (See figure below). It will be east to read through  fixing the background colour as white.

![image](https://cloud.githubusercontent.com/assets/1657381/15002981/5d85c0f0-11ea-11e6-95f2-d8ba297489d7.png)

**Comment by hol430** [comment]
The graphs actually seem to work pretty well for me in high-contrast mode. That said, there are a lot of other issues in high contrast mode, so I will not mark this as resolved just yet.

![highcontrast](https://user-images.githubusercontent.com/36427516/43052023-9969a1ec-8e64-11e8-8539-7c097a1a0c32.PNG)
