### ISSUE TITLE
Crop rotation does not work properly

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/ApsimX#8200]
### What happened?

[generated-0.zip](https://github.com/APSIMInitiative/ApsimX/files/12225563/generated-0.zip)
Dear all,

I'm trying to run the designed crop rotation in Nextgen but it said "Input string was not in a correct format."

Could anyone help to solve this issue? many thanks. Sim fiels are attached.

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Once this pull request goes through, this file should now work correctly.

[generated-0.zip](https://github.com/APSIMInitiative/ApsimX/files/12234578/generated-0.zip)

**Comment by peter-devoil** [comment]
It's good practise to have a fallow between crops - then your harvest dates wont be influenced by the sowing date of the next crop. We got it wrong calling them "fallow" - it's a period of time when there is no crop in the ground. 

PS white text on a white background is hard to read.

**Comment by KeLiu7** [comment]
> Once this pull request goes through, this file should now work correctly.
> 
> [generated-0.zip](https://github.com/APSIMInitiative/ApsimX/files/12234578/generated-0.zip)

Thanks Andrew. Could you please tell me why we need to add HarvestCrop("glable") or HarvestCrop("") sometimes so that the rotation could go through?
