### ISSUE TITLE
UI quirks in rotation manager

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#8202]
### What happened?

Arc selection is really hard - you have to click on a very narrow line to select it

The default placement of new nodes need ~~offsetting by the radius of the node~~ to be at the point where the user right clicked and opened the popup menu - at present it's partially off screen (0,0). The default colours should be something other than white text on a white background

In the settings grid at the bottom, when an arc is selected - the multiline rules & actions entries arent individually resizable

Would be good to trap errors in transitions (rules/actions) and write an informative message in the summary file as to which one is blowing up 

### What Operating System are you on?

Linux

**Comment by par456** [comment]
Closing this as it's being covered by #8203 which has a PR attached to it.
