### ISSUE TITLE
BubbleChartPresenter has unfinished parts

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8203]
There are a lot of comments left in BubbleChartPresenter for work that should be done and known bugs. Some examples:

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/77b45f6a-9cba-4f6d-a39e-82b4e9398822)
...
![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/9a716f6a-592c-4146-8d7a-a2ed05916a66)
...
![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/42d12a2e-1293-4bce-b36c-e2e67dad5b87)

Just needs a general cleanup along with the bubblechartview so they provide the intended functionality. 

- Address all the todo and fixme comments
- Determine if any functionality from the view should be in the presenter
- Cleanup commented out code if it's no longer needed.

**Comment by par456** [comment]
More additions that should be looked into when doing this in #8202

**Comment by par456** [comment]
To do list:
- [ ] Place node at cursor when created
- [ ] Make default color randomized
- [ ] Resizeable script panes on arc selections
- [ ] Show script errors when they happen
- [ ] Make Arcs easier to click on
- [ ] Fix arcs position/curve when node is moved
- [ ] Fix Intellisense positioning

**Comment by peter-devoil** [comment]
The "Show script errors when they happen" tickbox is addressed in https://github.com/APSIMInitiative/ApsimX/pull/8419/commits/8a0819c545424290cc26620163529e2e0f6a01a6
