### ISSUE TITLE
Display input for DateTime[] array properties to maintain input format

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8204]
### What happened?

If I include a property on a class which is an array of dates
eg
        /// <summary>
        /// Dates to trigger biomass removal events
        /// </summary>
        [Description("Removal Event Dates (comma seperated dd/mm/yyyy")]
        public DateTime[] RemovalDates { get; set; }

The input field on the u.i. is buggy.  This can be done on any class but putting something in a manager script is the quickest way to reproduce the problem.
Entering dates for the first time works OK, you can enterthem and dd/mm/yyyy coma seperated and everthing works.
the problem is that once you click away from the input field the UI changes the format to mm/dd/yyyy hh:mm:ss.  This is still editable but the hours, mins and secs are redundant and could be done without.  More importantly, it inverts the order of months and days so if you try to edit date you need to fix the order or else the parser will then throw an error.  This can be done but gets annoying if you have to fix each date each time you want to make any changes to the list.

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Yep, running up against the limitation of DateTime and string inputs here.

This should ideally be two properties, one visible on in the view that takes and stores the text that is entered. Then you either:
- Have the text property store the text given, and have RemovalDates convert the text to dates when called with custom getter.
- Have the text property update the date array property (which isn't directly shown in the view) with a custom getter and setter.

I prefer the first option, as it means user input is not modified by apsim and only one property is stored in the file. Here's how I would implement it:

`c#
/// <summary>
/// Dates to trigger biomass removal events
/// </summary>
[Description("Removal Event Dates (comma seperated dd/mm/yyyy")]
public string RemovalDatesInput { get; set; }

/// <summary>
/// Dates to trigger biomass removal events as dates
/// </summary>
[JsonIgnore]
public DateTime[] RemovalDates
{
    get 
    {
        if (String.IsNullOrEmpty(RemovalDatesInput))
            return new List<DateTime>().ToArray();
        List<DateTime> dates = new List<DateTime>();
        string[] inputs = RemovalDatesInput.Split(',');
        foreach (string input in inputs)
        {
            dates.Add(DateUtilities.GetDate(input));
        }
        return dates.ToArray();
    }
}
`

**Comment by par456** [comment]
Closed with #8190
