### ISSUE TITLE
Some issues with BiomassRemovalFractions when crops are removed from simulation

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8209]
### What happened?

I have been setting up some examples for the BiomassRemoval approach we have developed.  Needed to make a few changes so it can deal with multiple crops in the same simulation.  

The problem I encountered was copying a simulation with maize and wheat (which had maize and wheat specified in BiomassRemovalFractions) and then removing maize (I only needed wheat in the second example).  The view for the grid only shows up wheat which is expected but the BiomassRemovals list in BiomassRemovalFractions.cs has not been cleaned out so still contains maize.  An object ref error is then thrown when BiomassRemovalFractions steps through each member of BiomassRemovals and can not find the maize model (which is still in the list by not in the simulation).

To reproduce the error pull branch https://github.com/HamishBrownPFR/ApsimX/tree/Defoliator build and then try to run the "SendingDatesFromOpperations" simulation in C:\GitHubRepos\ApsimX\Examples\BiomassRemovalsFromPlant.apsimx you will see what I mean

### What Operating System are you on?

Windows

**Comment by HamishBrownPFR** [comment]
Oh, the other thing was the grid removed the maize rows from the top of the table and then trimmed the surplus data from the bottom of the table so the maize data has remained and aligned itself against wrong organs for wheat.

**Comment by par456** [comment]
Thanks Hamish, I'll have a look into it now and find out what's going wrong.

**Comment by par456** [comment]
Just looking at the interface you've got for the Biomass Removal, it's starting to get a lot of duplication with the Fractions node the more you customise it. My worry is in the future you'll want also be able to define the organs in the event and then we're basically just back where we started. 

I think the use cases you wanted this for were not outlined quite right when creating original design, We've moved away from using it to cut all crops at once, and back to cutting each crop individually and with different types.

I feel like something like this would be more suitable, with a single class controlling this, but multiple nodes in the trees for the different cuts and crops that you want to be able to preform.

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/a069e1dd-8d24-44db-971d-264b74bf1e88)

That way you'd select a crop, a cut type and the table would be populated with the organs of that plant. I'm really not a fan of putting the values in one node, then having a 2nd node that references a line in that one, as that's adding a bunch of complexity that really isn't needed when we can just put the options with the values.

**Comment by HamishBrownPFR** [comment]
Thanks @par456.  Yes, agreed.  It would be better to have a BiomassRemovalEvent that is specific to a crop and removal type with a BiomassRemovalFractions child that only populates the table with the organs for the crop specified in the parent and the numbers are only relevant to the type.  
That's the way I had it set up in the original prototype.  Now that we have your table class programmed in I think I can modify it to this pattern and check back in for review or if I get stuck.  That will also make the issue I raised with #8210 redundant.

**Comment by par456** [comment]
We do have the PropertyAndGridView and PropertyAndTablePresentor GUI windows that can do that layout already, but they use the old gridding system that I am working to replace. You could port the class over to use it, but its setup is a little bit different.

**Comment by HamishBrownPFR** [comment]
I like the table presenter you wrote.  Good to have the instruction field at the top
