### ISSUE TITLE
Documentation unneeded index page

### ISSUE THREAD

**Issue by Max-Tweddell** [APSIMInitiative/ApsimX#8212]
### What happened?

In the documentation tab the "modify the website" section has an unneeded index page, there is only one page in this section.

<img width="699" alt="image" src="https://github.com/APSIMInitiative/ApsimX/assets/17261837/9018d8a8-e198-4669-8fbb-f3a26fb5de67">

### What Operating System are you on?

MacOS

**Comment by ric394** [comment]
@Max-Tweddell To remove this double up, remove the _index.md file from Contribute/ModifyWebsite/

**Comment by ric394** [comment]
This has been resolved. Closing issue.
