### ISSUE TITLE
Docs not building 

### ISSUE THREAD

**Issue by Max-Tweddell** [APSIMInitiative/ApsimX#8213]
### What happened?

I get these error when trying to build the docs with hugo 
<details><summary>Details</summary>
<p>

``ERROR render of "page" failed: "/Users/maxtnz/Workspace/ApsimX/Docs/themes/hugo-theme-docdock/layouts/_default/baseof.html:15:9": execute of template failed: template: _default/single.html:15:9: executing "_default/single.html" at <partial "original/body-beforecontent.html" .>: error calling partial: "/Users/maxtnz/Workspace/ApsimX/Docs/themes/hugo-theme-docdock/layouts/partials/original/body-beforecontent.html:37:6": execute of template failed: template: partials/original/body-beforecontent.html:37:6: executing "partials/original/body-beforecontent.html" at <partial "menu.html" .>: error calling partial: "/Users/maxtnz/Workspace/ApsimX/Docs/themes/hugo-theme-docdock/layouts/partials/menu.html:21:23": execute of template failed: template: partials/menu.html:21:23: executing "section-tree-nav" at <.URL>: can't evaluate field URL in type *hugolib.pageState
Built in 253 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/Users/maxtnz/Workspace/ApsimX/Docs/themes/hugo-theme-docdock/layouts/_default/baseof.html:15:9": execute of template failed: template: _default/single.html:15:9: executing "_default/single.html" at <partial "original/body-beforecontent.html" .>: error calling partial: "/Users/maxtnz/Workspace/ApsimX/Docs/themes/hugo-theme-docdock/layouts/partials/original/body-beforecontent.html:37:6": execute of template failed: template: partials/original/body-beforecontent.html:37:6: executing "partials/original/body-beforecontent.html" at <partial "menu.html" .>: error calling partial: "/Users/maxtnz/Workspace/ApsimX/Docs/themes/hugo-theme-docdock/layouts/partials/menu.html:21:23": execute of template failed: template: partials/menu.html:21:23: executing "section-tree-nav" at <.URL>: can't evaluate field URL in type *hugolib.pageState``

</p>
</details> 

I am on mac OS and have tried Hugo 0.116, 0.115 and 0.113.

### What Operating System are you on?

MacOS

**Comment by ric394** [comment]
Hi @Max-Tweddell 
Please try this version of Hugo.
[Hugo.zip](https://github.com/APSIMInitiative/ApsimX/files/12296736/Hugo.zip)
Let me know how you go.

**Comment by Max-Tweddell** [comment]
I get another, different error 

`fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x1b0a45d, 0x21)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0x7ff7bfeff438 sp=0x7ff7bfeff418 pc=0x1029991
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff468 sp=0x7ff7bfeff438 pc=0x1027513
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:501 +0xd6 fp=0x7ff7bfeff4d0 sp=0x7ff7bfeff468 pc=0x102c286
runtime.rt0_go(0x7ff7bfeff500, 0x2, 0x7ff7bfeff500, 0x1000000, 0x2, 0x7ff7bfeff790, 0x7ff7bfeff7c3, 0x0, 0x7ff7bfeff7ca, 0x7ff7bfeff806, ...)
	/usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff4d8 sp=0x7ff7bfeff4d0 pc=0x1053364`

Which seems to be a problem with that hugo version and the latest versions of Mac OS

**Comment by ric394** [comment]
As this is an issue outside of APSIM it will be closed.
