### ISSUE TITLE
Duplicate Nutrient in Soil from File Version 152 to 176

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#8218]
### What happened?

I update the latest version of APSIMX (master branch in this morning). Get an error message to load old apsimx with File Version 152 (update to File Version 176). 

```
Duplicate models found: .Simulations.Experiment.badingarra.paddock.soil has 2 children named Nutrient
```

I can confirm there are only one Nutrient in the old file.

Example file attached.
[example-152.zip](https://github.com/APSIMInitiative/ApsimX/files/12307673/example-152.zip)

When I run the simulations, I get another error message

```
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Models.Soils.Nutrients.Nutrient.OnDoSoilOrganicMatter(Object sender, EventArgs e) in C:\APSIMNG\NPI2\ApsimX\Models\Soils\Nutrients\Nutrient.cs:line 466

```

It seems it is related with Soil Organic Matter. But I have `Organic` model in the soil.

### What Operating System are you on?

Windows

**Comment by byzheng** [comment]
In the file version 152, I have `Nutrient` as below.

```
{
  "$type": "Models.Soils.Nutrients.Nutrient, Models",
  "ResourceName": "Nutrient",
  "Name": "Nutrient",
  "Enabled": true,
  "ReadOnly": false
}
```

After deleting `Nutrient` in the text editor, `apsimng.exe` still opens the apsimx and displays `Nutrient` model. 

After saving, a new `Nutrient` model is added into apsimx file. It seems there is a bug to upload Nutrient model.

**Comment by ric394** [comment]
@byzheng I was able to get it running using the same method you used above. 

This has to do with the converter class converting older version of files using SoilNitrogen models.
I'll correct this in the relevant converter method. Thank you for bringing this to my attention.
