### ISSUE TITLE
Moving by drag&drop in the GUI works only after reopening Apsim

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#822]
Moving (not just copying) an item, eg. a graph, into a folder by drag&drop (click, SHIFT hold) does actually work, but is not displayed in the GUI (the item remains at the same position in the GUI).
![apsim_move](https://cloud.githubusercontent.com/assets/17924125/15074942/2aa44b16-13a2-11e6-9b1d-aa345e7d79db.jpg)

![apsim_move2](https://cloud.githubusercontent.com/assets/17924125/15075082/cf03ce8e-13a2-11e6-9379-092912c69e7f.jpg)

After saving, closing and re-opening the file, the item appears at the correct (moved) position.
![apsim_move3](https://cloud.githubusercontent.com/assets/17924125/15075060/ba585d7e-13a2-11e6-9277-5087daa03842.jpg)

**Comment by zur003** [comment]
This is a problem with the Windows Forms GUI (UserInterface.exe), but not the Gtk one (ApsimNG.exe).
