### ISSUE TITLE
No reset of second stage evaporation SoilWat

### ISSUE THREAD

**Issue by KirstenVer** [APSIMInitiative/ApsimX#8221]
### What happened?

Using the simulation that formed the basis for my earlier issue #8112, a simulation of evaporation measured under a bare soil, I noticed both SWIM and SoilWat struggle to dry out at 5 cm depth. Which for SWIM this is something to delve in deeper, but it surprised me for SoilWat as this was the first layer.

In outputting daily es I noticed it very quickly went down to almost nothing each time after the high evaporation during first stage following a rainfall event even though Eos was still high and there was sufficient water in the soil.
Below a screenshot during a brief period in November when you can see the higher evaporation for two days, but it dropping back to < 0.25 right after. Figure below that shows that we’re on a downward trend during the season, except for small discontinuities on 1 Nov and 1 Apr.

 
![image](https://github.com/APSIMInitiative/ApsimX/assets/82482332/d2874940-3377-47b3-9eba-e6a91745e1d9)

![image](https://github.com/APSIMInitiative/ApsimX/assets/82482332/2c56d726-5015-4727-8d4a-95e9ad58f862)

 
I wonder whether the code works as intended. I thought after each rainfall event that triggers first stage evaporation (based on U), it would restart its second stage evaporation.

Manual calculation in Excel using Cum Es (second stage) = cona * sqrt(t in days), I get higher values:
Cona=	3.5		2	
t	cumEs	Es	cumEs	Es
1	3.5	3.5	2.0	2.0
2	4.9	1.4	2.8	0.8
3	6.1	1.1	3.5	0.6
4	7.0	0.9	4.0	0.5
5	7.8	0.8	4.5	0.5
6	8.6	0.7	4.9	0.4
7	9.3	0.7	5.3	0.4
8	9.9	0.6	5.7	0.4
9	10.5	0.6	6.0	0.3
10	11.1	0.6	6.3	0.3

Indeed, we see such values of Es following the first rainfall event at the start of the simulation.
![image](https://github.com/APSIMInitiative/ApsimX/assets/82482332/f77b75d8-b181-4879-84ea-6a264393b8a5)

It seems there is no reset of days since first stage?

 

### What Operating System are you on?

Windows

**Comment by KirstenVer** [comment]
I am surprised that this bug would not have thrown an error elsewhere. This was part of a simulation that had a SWIM/SoilWat permutation. Disabling nodes of the opposite model. So now wondering if it could relate to model getting confused there? (As enabling disabled nodes had previously also resulted in weird behaviour?

**Comment by KirstenVer** [comment]
Reran as stand-alone Soilwat simulation, but same problem, so it does not appear to be related to the set-up as an experiment with two models

**Comment by hut104** [comment]
The approach is basically that from the original CERES Maize.

If you are, for example, 100 days into stage 2 evaporation with cona=3.5, the sum of stage 2 evaporation will be 35mm. If you have a rainfall event, stage 1 is reset and will evaporate at potential.  That which is evaporated in stage 1 (e.g. a total of water equal to U, with some discounting I think), is then subtracted from the rain to give the amount that sum of stage 2 evaporation is wound back.  Stage 2 then pretty much continues on its previous path because the soil is basically just as dry as prior to the rainfall event.
Stage 2 really only gets wound right back when you have large events.

**Comment by KirstenVer** [comment]
Confirmed against another dataset with evaporation data that this behaviour is indeed correct (and does a remarkably good job for that dataset). Rainfall events were in this case too small to cause reset of Stage 2.

**Comment by hut104** [comment]
Recent tests have found that this change does result in significant differences in evaporation rates after U and Cona are changed.  There may be some benefit in revisiting these changes via investigation of changes in behaviour in the Yield Gap simulation set.
@par456 has simulations that can demonstrate the changes.
