### ISSUE TITLE
BiomassRemovalEvents does not work with prototype crops

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8236]
### What happened?

If you add a BiomassRemovalEvents to a simulation that does not have a crop.json resource file, the grid does not appear.  This happens for prototype crop models where the json for the crop model is only in the replacements node.  In this case BiomassRemovalEvents finds a plant model that has a valid parent but has no organs.  It this case it needs to find the crop model in replacements not the shell model in the simulation.

### What Operating System are you on?

Windows

**Comment by HamishBrownPFR** [comment]
Sorry @par456 was trying to get @Xiumei2017 sorted with finalising the lucerne test set for release and ran into this one.  Let me know if more information would be helpful.

**Comment by par456** [comment]
Ah yep, I see the problem. I'll jump on that this afternoon for you.

**Comment by HamishBrownPFR** [comment]
Thanks @par456, Much appreciated
