### ISSUE TITLE
Mungbean Cultivars

### ISSUE THREAD

**Issue by Janewanguimugo** [APSIMInitiative/ApsimX#8243]
### What happened?

I right-clicked on the mungbean module to view the cultivars and also add some of my own, but there are no cultivars in there despite being able to view them in the sowing rule. I am unable to create any new cultivars, it seems the folder is inactive or read-only.

I have attached my experiment here 
[GreengramKenya.zip](https://github.com/APSIMInitiative/ApsimX/files/12405246/GreengramKenya.zip)

### What Operating System are you on?

Windows

**Comment by hol353** [comment]
To see existing cultivars right click on Mungbean and select 'Show Model Structure'. Scroll down to the 'Cultivar' folder. All cultivars are under that.

To add a new cultivar, right click on Mungbean and select 'Add Model', go to 'PMF' and double click 'Cultivar'. This will add a blank 'Cultivar1' to Mungbean. Rename it to whatever you want. You can then copy the contents of an existing cultivar to your new cultivar:

![image](https://github.com/APSIMInitiative/ApsimX/assets/1943827/ee57d09a-bc82-479c-b665-080a9c289c96)

**Comment by par456** [comment]
Closing this as the question seems to be answered. Leave a comment if it needs to be reopened.
