### ISSUE TITLE
Choosing harvesting dates

### ISSUE THREAD

**Issue by matteolongo2** [APSIMInitiative/ApsimX#8247]
### What is your question?

Hello, I'm new to APSIM. From the documentation it seems that it's not possible to choose harvesting dates. Is it really like that?
I am trying to replicate short period soil dynamics and it would be important for me to choose them since they did not match with physiological maturity dates. Thank you.

**Comment by hol353** [comment]
Yes it is possible. I notice that the management toolbox in APSIM doesn't have a Harvest on a fixed date rule. That's an oversight. We'll add this soon. In the meantime, you can use an operations model and type:

```
2023-06-01 Wheat.Harvest()
```

Change the date to whatever you want. You can also have multiple lines in this operations model for different harvests of different crops in different years.

**Comment by matteolongo2** [comment]
Thank you very much. Also, is it possible to specify management dates (sowing, tillage, etc) on long term crop rotations using the interface?
Thank you

**Comment by hol353** [comment]
Yes. Like harvest, use an operations model:
```
1995-06-15 [Wheat].Sow(population:120, cultivar:"Hartog", depth:40, rowSpacing:250);
1995-06-15 [SurfaceOrganicMatter].Incorporate(fraction:0.1, depth:100);
```

**Comment by par456** [comment]
Closing this issue as it seems to be solved. Please leave a comment or reopen if it is not.
