### ISSUE TITLE
Remove Stylecop error/warnings until addressed

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8253]
### What happened?

Just adding on from the issue we raised this morning in the meeting. Can we turn off the stylecop errors for unused parameters and using directives inside of a namespace, so they stop cluttering up the error list when building.

They should be added back in again later when that is worked on again, but while it's not, it would be good to exclude them so our error lists are useful again.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
That is a good idea @par456, that was bugging me and I'm certain it is bugging other users.
