### ISSUE TITLE
Graph does not update y axis label

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#8256]
### What happened?

When changing the Graph Series data source and Y properties the Y axis label for the chart does not change accordingly and will remain whatever it was when first set. I have not found a way of tricking it to change other than editing the json. This is an issue when copy and pasting Graphs and changing all the series to new Y values or even using different data sources. 

### What Operating System are you on?

Windows

**Comment by lie112** [comment]
I think this might be true when a right-hand axis has been previously used as well. I recall changing to plot on left and not being able to get rid of the right-hand axis label in the past.

**Comment by ric394** [comment]
@lie112 I've given this one a go and I found that if I remove the title text located here in the title input, that the y axis label would update when changed:

![image](https://github.com/APSIMInitiative/ApsimX/assets/123442863/af585c70-86be-4572-a575-c04576cafed8)

If this fixes the problem, I'll close off this issue.
