### ISSUE TITLE
Equation Addition and Content Deletion Issue After NG Update

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/ApsimX#8258]
### What is your question?

Dear Next Gen community,

I added some functions in the photosynthesis module, but after updating Next Gen, I can't continue to add new content to it, and all the content I previously added has been deleted. Does anyone know why this is happening?

Also could you please guide me how to edit Photosynthesis module with current model version? Many thanks！

[root_fr & FOx.zip](https://github.com/APSIMInitiative/ApsimX/files/12470662/root_fr.FOx.zip)

**Comment by peter-devoil** [comment]
There is a ResourceName attribute in the PMF component that is used to point to a compiled in (ie readonly) object. When you make changes to the component's structure (via show structure/readonly menus), your changes are (usually) preserved, but I suspect that when the installation is updated the model becomes potentially broken, as the infrastructure changes between versions may introduce incompatibility. Thus your changes are discarded and the resource points to a virgin (new) component.

I'm not 100% sure how to do this via the GUI but setting the ResourceName attribute by hand to something unrecognisable will stop the update. Its easier not to update, but sooner or later that becomes tedious. There is a diff tool [proposed](https://github.com/APSIMInitiative/ApsimX/issues/8139) that might make this process easier

**Comment by hol353** [comment]
I'm surprised that content has been removed from your .apsimx file. It will probably be related to what @peter-devoil says above but it still shouldn't happen.

Were you making your changes in Barley under Replacements? I can't tell because it looks like you attached your file after photosynthesis modifications have already been removed. Do you have the file before the modifications have been removed? The GUI usually makes a .bak file before modifying the file.

**Comment by KeLiu7** [comment]
> I'm surprised that content has been removed from your .apsimx file. It will probably be related to what @peter-devoil says above but it still shouldn't happen.
> 
> Were you making your changes in Barley under Replacements? I can't tell because it looks like you attached your file after photosynthesis modifications have already been removed. Do you have the file before the modifications have been removed? The GUI usually makes a .bak file before modifying the file.



> There is a ResourceName attribute in the PMF component that is used to point to a compiled in (ie readonly) object. When you make changes to the component's structure (via show structure/readonly menus), your changes are (usually) preserved, but I suspect that when the installation is updated the model becomes potentially broken, as the infrastructure changes between versions may introduce incompatibility. Thus your changes are discarded and the resource points to a virgin (new) component.
> 
> I'm not 100% sure how to do this via the GUI but setting the ResourceName attribute by hand to something unrecognisable will stop the update. Its easier not to update, but sooner or later that becomes tedious. There is a diff tool [proposed](https://github.com/APSIMInitiative/ApsimX/issues/8139) that might make this process easier



> There is a ResourceName attribute in the PMF component that is used to point to a compiled in (ie readonly) object. When you make changes to the component's structure (via show structure/readonly menus), your changes are (usually) preserved, but I suspect that when the installation is updated the model becomes potentially broken, as the infrastructure changes between versions may introduce incompatibility. Thus your changes are discarded and the resource points to a virgin (new) component.
> 
> I'm not 100% sure how to do this via the GUI but setting the ResourceName attribute by hand to something unrecognisable will stop the update. Its easier not to update, but sooner or later that becomes tedious. There is a diff tool [proposed](https://github.com/APSIMInitiative/ApsimX/issues/8139) that might make this process easier

So, a safer approach is to back up the original simulation files before updating.

In addition, I remember that there used to be a `read-only` option in the right-click menu. This function seems to have been removed in the recent update? How can I add equations independently in the latest version?

**Comment by hol353** [comment]
The read-only option is gone. It wasn't working correctly anyway. To make changes to a model put the model under Replacements and edit it there. Your attached .bak file has this already and it is editable. It seems to work.
