### ISSUE TITLE
Sugarecane model didn't showing the crop varietal parameters.

### ISSUE THREAD

**Issue by Rizwan3946** [APSIMInitiative/ApsimX#8259]
### What happened?

Hi, I am trying to find out Sugarcane model crop varietal parameters by right clicking on Sugarcane model and clicking on "show model structure" but it didn't work for me.

![2023-08-30 (2)](https://github.com/APSIMInitiative/ApsimX/assets/135749442/c4ff10c8-ff78-43d1-989f-1ac310ccdec1)

### What Operating System are you on?

Windows

**Comment by BrianCollinss** [comment]
The Sugarcane module has been just ported from APSIM Classic without converting to the PMF structure. You can use the model but cannot see the structure in the interface.

**Comment by hol353** [comment]
The variety parameterisation for sugarcane is in https://github.com/APSIMInitiative/ApsimX/blob/master/Models/Resources/Sugarcane.json.

As noted above, the parameters are not visible in the GUI.
