### ISSUE TITLE
Simulation Error in after Modifying Rotation Files

### ISSUE THREAD

**Issue by smkuhlani** [APSIMInitiative/ApsimX#8268]
### What happened?

Dear APSIMers,

I am creating a Maize-Peanut rotation simulation. I am creating this by editing the default Maize-Wheat rotation. The simulation is however throwing an error: 'Test condition '[WheatManager].Script.CanSow' returned nothing', yet i have replaced all the Wheat components.  I have attached the error screenshot and the simulation file.

Cheers

![image](https://github.com/APSIMInitiative/ApsimX/assets/34687653/828557e3-ac5f-46a2-a0b3-1a384602da45)

[MaizePeanutRotation.zip](https://github.com/APSIMInitiative/ApsimX/files/12497037/MaizePeanutRotation.zip)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
I just checked your file, and in the Rotation Manager two of the lines still have WheatManager in their Rules and Actions. 

I assume those are meant to be PeanutManager, though PeanutManager doesn't have a CanSow function, so you would need something else for that transition.

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/d12674ba-75a3-44ea-aa4e-5046b7c59458)

**Comment by smkuhlani** [comment]
corrected the crop name to peanut. I am getting the error 'Test condition '[PeanutManager].Script.CanSow' returned nothing' below.  I assume it's related to the transition. Can you advice what i should add in the transition, to enable this to run.

![image](https://github.com/APSIMInitiative/ApsimX/assets/34687653/06097549-1b66-4c12-9bb6-bdf09712793a)

**Comment by par456** [comment]
You'll need to add a CanSow and CanHarvest function to your PeanutManager script. I've adapted these from the MaizeManager, so you can edit them to better tune the conditions for sowing and harvesting, but these should work.

```csharp
        [Units("0-1")]
        public int CanSow
        {
            get
            {
                bool inWindow = DateUtilities.WithinDates(StartDate, Clock.Today, EndDate);
                                
                if (!Crop.IsAlive && inWindow && accumulatedRain.Sum > MinRain && MathUtilities.Sum(waterBalance.ESW) > MinESW)
                    return 1;
                    
                if (DateUtilities.DatesEqual(EndDate, Clock.Today) == true)
                    return 1;      
                           
               	return 0;
            }
        }
        
        public void SowCrop()
        {
            Summary.WriteMessage(this, this.FullPath + " -  sowing " + (Crop as Model).Name, MessageType.Diagnostic);
            Crop.Sow(population: Population, cultivar: CultivarName, depth: SowingDepth, rowSpacing: RowSpacing);    
        }
        
        [Units("0-1")] 
        public int CanHarvest
        {
            get
            {
                return Crop.IsReadyForHarvesting ? 1 : 0;
            }
        }
        
        public void HarvestCrop()
        {
            Crop.Harvest();
            Crop.EndCrop();
        }
```

**Comment by smkuhlani** [comment]
Thank you. 

Worked for a but but i can't view the yield outputs. I have attached the 'erroneous' file.
[MaizePeanutRotation4Sep.zip](https://github.com/APSIMInitiative/ApsimX/files/12516772/MaizePeanutRotation4Sep.zip)

Thank you!

**Comment by par456** [comment]
There seems to be a few things wrong here. A good way to check if your simulation is running is to look at the summary node after running it, as all the big events should get listed there if it ran. If you don't see anything, it's a good suggestion that your simulation isn't running.

First thing you had your permutations disabled under factors, so enabled one of them so it would run, but not all so that it would be easier to test what's going wrong.

You also had incorrect frequencies on your reports, they should be:

TransitionReport: 
[RotationManager].Transition

Report: 
[Peanut].Harvesting
[Maize].Harvesting

I then couldn't get the rotation manager to transition, so I ended up remaking the PeanutManager based off the code of the MaizeManager, and just setting the parameters to what you had before. Not sure what the problem was here, but remaking that script solved it.

In the rotation manager, arc 1 was missing a rule and action, I gave it [PeanutManager].Script.CanHarvest for the rule and [PeanutManager].Script.HarvestCrop() for the action.

After all that I could run the simulation. I was getting Yields for Peanut, but not for Maize. This is because to get the yield for Maize you'll need: [Maize].Total.Wt as MaizeYeild

This is something we are looking to improve at the moment to make it easier to know what variables you need to enter for different crops.

**Comment by smkuhlani** [comment]
It is working but what are the purpose of the permutations. I would like to simply undertake a rotation simulation for a single location.

**Comment by par456** [comment]
That simply allows you to run multiple variations of a simulation with a variable changing between each one. If all you want is a single simulation, you can move the Simulation node (called Mar in your file) outside of the Experiment Node (also called Mar), then delete the experiment and just run the simulation directly.

**Comment by smkuhlani** [comment]
Dear Andrew,

This is working, thanks.  I have 2 remaining issues:

1-Would like to view. Total seasonal Carbon and Mean NO3 for the 4 layers per season.

I am getting the error below:

![image](https://github.com/APSIMInitiative/ApsimX/assets/34687653/498f86c1-6687-445c-b589-cf36de3fee5c)


2-On the reports, i still get outputs which i have removed from the report. These are: Peanut.Grain.Size, Peanut.Grain.Number & MaizeYield1. Where could i be getting it wrong. 

3-I am getting outputs for the sowing date of 10-Apr, but i have since removed it from the simulation.

I have attached the apsims
[MaizePeanutRotation6Sepb_ok.zip](https://github.com/APSIMInitiative/ApsimX/files/12616370/MaizePeanutRotation6Sepb_ok.zip)
 rotation file wit these issues.

**Comment by peter-devoil** [comment]
1 - try "[Soil].Nutrient.TotalC" - the SoilNitrogen component went away some time last year

2 - It could be that the datastore hasnt been "emptied" for a while, and remembers that once upon a time those variables existed. NG doesnt wipe the datastore completely unless you a) delete the files from disk, or b) right click and choose "Empty the datastore".

3 - Likewise if there are simulation errors then the datastore is not emptied and likely contains stale data from old simulations. SummaryFile data should be refreshed immediately, but best to wipe it to be sure. For some obscure programming reason, simulation output is not written to the data store until the end of the simulation, and if you get an error before then, then you dont get the most recent data

**Comment by smkuhlani** [comment]
1. Thanks, simulation running. Any idea what the units are for Total C.

**Comment by hol353** [comment]
kg/ha

**Comment by par456** [comment]
Closing this because I think everything has been solved now.
