### ISSUE TITLE
Can we set soil mineral N values using the manager in APSIM NG?

### ISSUE THREAD

**Issue by HongtaoXing** [APSIMInitiative/ApsimX#8278]
### What is your question?

Hi All

I am wondering if we could set the values for soil mineral N using Manger in APSIM NG? 

In our simulations, we would like to set particular mineral N values for certain soil layers in the mid of simulations. 

If so, how could we do it? 

Thanks

**Comment by peter-devoil** [comment]
If your observation dates are known in advance, you can use the operations module like a calendar:
![image](https://github.com/APSIMInitiative/ApsimX/assets/1924386/1214ce39-de01-4214-87f7-2e35790f244f)

Or some conditional logic in the manager:
![image](https://github.com/APSIMInitiative/ApsimX/assets/1924386/f904a6e8-1a05-45e9-895a-5a58c035f227)

As always, check that the model is doing what you think it should be. It's very easy for this sort of logic to be silently ignored.

**Comment by HongtaoXing** [comment]
Thank you very much, Peter
It works well for me now.

**Comment by HongtaoXing** [comment]
Problem solved
