### ISSUE TITLE
:warning: Chickpea does not respond to fertiliser

### ISSUE THREAD

**Issue by asherbender** [APSIMInitiative/ApsimX#8280]
### What happened?

The chickpea crop model does not appear to respond to varying levels of applied fertiliser (management actions).

The attached simulation demonstrates this behaviour. It is a simplified version of the Wagga Wagga [chickpea example](https://github.com/APSIMInitiative/ApsimX/blob/master/Examples/Chickpea.apsimx) where:
- A factorial experiment is executed to apply 0, 60 and 120 kg/ha of NO3N to a Chickpea crop.
- A graph has been added to compare the above ground weight of the chickpea across the fertiliser trials. **The above ground weights are identical**. I would expect the crop to respond to varying amounts of applied fertiliser.
- A graph has been added to compare the soil NO3 across the fertiliser trials. The plot shows varying soil NO3 levels across the three different trials.

[chickpea-test.zip](https://github.com/APSIMInitiative/ApsimX/files/12577358/chickpea-test.zip)

### What Operating System are you on?

Linux

**Comment by hut104** [comment]
Hi,
Chickpea is a leguminous crop and so can fix some of its N demand from the atmosphere.  If you add an extra output for Chickpea.Nodule.NFixed you should see that, in each season, N fixation is delayed and reduced under increasing fertiliser application as the crop makes use of soil N before fixing N from the atmosphere.

There is also a sensibility test within the chickpea validation set that explicitly looks at this using a fertiliser experiment similar to your example.  This test simply reproduces findings from central NSW that shows that the amount of crop N fixed from the atmosphere drops from about 90% to a low number as fertiliser application is increased.  You may be able to check this same response within your example simulation.

In some legume species and legume models, there is a cost of N fixation which is accounted for using a carbohydrate requirement from daily photosynthesis.  This chickpea model does not include such a cost and so you find no positive response to fertiliser (ie reduced need for fixation means lower fixation costs and therefore higher biomass production).

I hope this helps.

**Comment by asherbender** [comment]
Neil,

Awesome reply. Thank you! And apologies for what sounds like obvious behaviour!
