### ISSUE TITLE
Ability to immediately move a newly pasted model in tree

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#8281]
### What happened?

When a model is copied and pasted in the UI tree structure it appears highlighted at the bottom of the group it was pasted into but it is not ready to move up/down with the keyboard strokes (crtl + up or down arrows). You have to click another model and click back to the newly added model to allow for the move up and down keyboard functionality to work.

### What Operating System are you on?

Windows

**Comment by lie112** [comment]
This is now working. There must be a case where this doesn't work. I'll try and repeat it and open again if I can reproduce the problem.

**Comment by par456** [comment]
I've also seen this bug, I'll keep an eye out for it again to see how it can be repeated.
