### ISSUE TITLE
Add docs for report

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#8284]
### Describe the new feature

Current documentation is only included a `Report Node` (https://apsimnextgeneration.netlify.app/usage/report/). I would suggest adding following documentation for Report

* How to create a report and explain report frequency
* List of common variables for soil nitrogen and water

**Comment by ric394** [comment]
We are currently in the process of improving the report with exactly these features. See this issue: #8227.

**Comment by ric394** [comment]
this has been resolved with #8293 

* New functionality of the Report node allows the filtering of common report variables and events in the text editor.
* Users can now submit common report variables and events via the GitHub Issue system.
* In addition to this we've added further documentation. Please let me know if you have any feedback.
