### ISSUE TITLE
Setting obscure soil N parameters in manager

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#8285]
### What is your question?

A colleague wants to experiment with the soil temperature denitrification response, which is implemented [here](https://github.com/APSIMInitiative/ApsimX/blob/master/Models/Functions/SoilFunctions/CERESMineralisationTemperatureFactor.cs#L31).   

I'm lost with the magic expression to manipulate it - I was expecting something from ```Model.Find<xyz>```, but all I get is nulls. Is there something like the below that would work?

```
  var CTF = Nutrient.FindByPath("Nitrification.Rate.CERESMineralisationTemperatureFactor").Object as CERESMineralisationTemperatureFactor;
  CTF.MineralisationSTOpt = 42;
```

**Comment by hol353** [comment]
Here's what I tell everyone.

* Find the model in the tree you want to access. In this case Nutrient | Nitrification | Rate | CERESMineralisationTemperatureFactor
* Right click on it and select 'Copy manager snippet (full path)'. This will copy some code to the clipboard
* Paste it into your manager. The snippet looks like this:
* 
```c#
using Models.Functions;

[Link(Type=LinkType.Path, Path=".Simulations.Agistment Grazing Example.Agistment Grazing.Field.Soil.Nutrient.Nitrification.Rate.CERESMineralisationTemperatureFactor")] private CERESMineralisationTemperatureFactor CERESMineralisationTemperatureFactor;
```

The using statement is put up the top with the other using statements. The link is put with the other links. The link path can be shortened to ```[Soil].Nutrient.Nitrification.Rate.CERESMineralisationTemperatureFactor```

You then have an instance you can use.

**Comment by peter-devoil** [comment]
Wow - I had no idea that nutrient had a structure to display. Thanks for the heads up.

Why are some UI objects with hidden children shown with a sideways caret (eg a Field/Zone) and not others?

**Comment by hol353** [comment]
We are trying to hide 'constants' in models or at least not make it too obvious (i.e. like ini files in Classic). Once you change one of these constants you have a different, potentially unvalidated model. We don't really want users casually changing constants in nutrient.
