### ISSUE TITLE
Run with CO2 < 350 ppm

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8286]
### Describe the new feature

Currently APSIM throws a fatal error is CO2 < 350 ppm.   Atmospheric CO2 reached 350 ppm in 1988 so climate change simulations with base lines prior the this can not currently be run in APSIM.

@hut104 @hol353 

Need to augment CO2 response function so it works at lower concentrations

**Comment by LenLon** [comment]
Is there an update on this? Running counterfactual climates with APSIM is currently impossible due to this issue

**Comment by HamishBrownPFR** [comment]
Correction, APSIM throws when CO2 is below 300.  However pre industrial CO2 levels were about 270-290 so historic simulations throw.

**Comment by LenLon** [comment]
300 is already much closer to pre industrial levels, so this is good to know!
