### ISSUE TITLE
The Nutrient documentation is pretty naff - it needs attention and is not currently useful to users

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8288]
### What happened?

As above

### What Operating System are you on?

Windows

**Comment by peter-devoil** [comment]
Likewise swim3 - it consists of 1 line: ".NET port of the Fortran SWIM3 model Ported by Eric Zurcher July 2014"...

**Comment by ric394** [comment]
This will be fixed by #7100.
