### ISSUE TITLE
Inquiry on Representing Shading Effects and Yield in APSIM

### ISSUE THREAD

**Issue by odjopuen** [APSIMInitiative/ApsimX#8291]
### What is your question?

Dear APSIM Team,

I hope this email finds you well. I am writing to seek your guidance on how to effectively represent shading of an area and its impact on plant growth, temperature changes, and yield within the APSIM modeling framework.

Specifically, I am interested in modeling the effects of shading on plant development and crop yield, specifically Wheat, Barley, Maize and Canola. I am trying to model shading levels from 10% to 50% of the total area. Until now the only option I have found is to gradually reduce the solar radiation given by the weather files, here I receive a linear relationship in between radiation and Yield but I would greatly appreciate your expert advice on the best approach to capture these dynamics accurately.

Could you please provide insights or recommendations on how to:

1. Model shading effects on plant growth and development?
2. Incorporate changing shading levels (from 10% to 50%)?
3. Integrate the effects of shading on crop yield?

Additionally, if there are any specific modules, parameters, or functions within APSIM that are particularly suited for handling shading scenarios and yield predictions, please do let me know.

Thank you very much for your time and assistance.
I look forward to your response and learning from your insights.

Best regards,
Jonatan Puente Schick

**Comment by hut104** [comment]
Hi,
If you look in the management toolbox there should be a weather folder.  Within that is a climate controller which will allow you to apply modifiers to radiation, temperatures, wind, etc to adjust your weather file.
Such a manager script can but used as part of a factorial experiment if need be to create the various cover levels etc .

These approaches have been used previously, see https://link.springer.com/article/10.1007/s10457-017-0119-0 for example.
[https://media.springernature.com/w200/springer-static/cover/journal/10457.jpg]<https://link.springer.com/article/10.1007/s10457-017-0119-0>
Potential of the APSIM model to simulate impacts of shading on maize productivity - Agroforestry Systems<https://link.springer.com/article/10.1007/s10457-017-0119-0>
link.springer.com
I hope this helps.

________________________________
From: odjopuen ***@***.***>
Sent: Thursday, 14 September 2023 6:20 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Inquiry on Representing Shading Effects and Yield in APSIM (Issue #8291)


What is your question?

Dear APSIM Team,

I hope this email finds you well. I am writing to seek your guidance on how to effectively represent shading of an area and its impact on plant growth, temperature changes, and yield within the APSIM modeling framework.

Specifically, I am interested in modeling the effects of shading on plant development and crop yield, specifically Wheat, Barley, Maize and Canola. I am trying to model shading levels from 10% to 50% of the total area. Until now the only option I have found is to gradually reduce the solar radiation given by the weather files, here I receive a linear relationship in between radiation and Yield but I would greatly appreciate your expert advice on the best approach to capture these dynamics accurately.

Could you please provide insights or recommendations on how to:

  1.  Model shading effects on plant growth and development?
  2.  Incorporate changing shading levels (from 10% to 50%)?
  3.  Integrate the effects of shading on crop yield?

Additionally, if there are any specific modules, parameters, or functions within APSIM that are particularly suited for handling shading scenarios and yield predictions, please do let me know.

Thank you very much for your time and assistance.
I look forward to your response and learning from your insights.

Best regards,
Jonatan Puente Schick

**Comment by par456** [comment]
Closing this for now, leave a comment if it needs to be reopened.
