### ISSUE TITLE
SimpleGrazing was generating an exception when there was no error

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8294]
### What happened?

There was a condition in which an exception was generated when the user requested more biomass than was available. The code already applies minimum harvestable amounts so this exception is not needed.

### What Operating System are you on?

Windows

**Comment by sno036** [comment]
@hol353, Rogerio and I talked about the biomass post-grazing and it turns out that it was the effect of the SurfaceOrganicMatter being 'grazable' in Forages and a large initial SOM. I'd like to see the grazability of SOM defaulting to zero in Forages but am not sure how to do that.

**Comment by hol353** [comment]
In the real world, livestock by default will graze residues.

**Comment by her123** [comment]
Definitely need to have grazable SOM by default.

**Comment by sno036** [comment]
Need a bit more flexibility in SimpleGrazing for removing some of the urine and/or dung from the simulation.
