### ISSUE TITLE
Monotonicity in SWIM3 moisture characteristics

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#8304]
### What happened?

In sandy soils, if LL15 is very low (e.g. < 0.01) the spline interpolation can become non-monotonic.  Given that this part of the characteristic is approximating a linear relationship (as attempted in the way that the cubics are specified) perhaps use a linear calculation directly.

### What Operating System are you on?

Windows

**Comment by KirstenVer** [comment]
Thanks Neil and Dean, this allowed the Mingenew Sand simulation to run without crashing!
