### ISSUE TITLE
Weed manager in APSIM NG

### ISSUE THREAD

**Issue by smkuhlani** [APSIMInitiative/ApsimX#8307]
### What is your question?

Does APSIM NG has a weeding manager? We would like to mimic  a farming system, with weeding stress?

**Comment by ric394** [comment]
@smkuhlani Currently we do not have a weeding manager or a specific way to simulate weeding stress.
However, a SLURP model may be able to be used to simulate weeds. @HamishBrownPFR can you confirm if this possible?
