### ISSUE TITLE
New report VerticalSplitterPosition has odd interactions with tree view/presenter divider.

### ISSUE THREAD

**Issue by ilhuber** [APSIMInitiative/ApsimX#8309]
### What happened?

It seems like when the value of ReportView's VerticalSplitterPosition is low (far to the left of the presenter) for the new report, it is very difficult to resize because the divider between the simulation tree view and the right-hand presenter has priority.

Additionally, when resizing the simulation tree/right-hand presenter with a Report selected the reportVariableBox (top pane) and reportFrequencyBox (bottom pane) don't have their vertical splitters change position evenly. Clicking away and back re-aligns the vertical splitters to the reportFrequencyBox.

I encountered both of these behaviors on d76ee20.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@ilhuber Which version of Apsim NG are you using?

**Comment by ilhuber** [comment]
Sorry, this was on master under commit d76ee2066. I should have specified in the main post. I pulled this morning and encountered these odd behaviors when interacting with the new Report. The new features are pretty cool, though! They should help ease a lot of Classic users into NextGen.
