### ISSUE TITLE
Extra resource information is being added into .apsimx files

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#8311]
### What happened?

I noticed that .apsimx files are now having extra information added into them that previously was held in resources.
Examples include
- fertiliser type information
- nutrient graphical information
- lots of extra parameters in models (e.g. agpasture)
This resulted in the addition of about 8000 lines to swim.apsimx when working on #8305

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Opening the swim validation file in the current build and saving the file again removes all those lines. So the current build won't add them. Was there something about the branch you were on that was adding those in?

**Comment by par456** [comment]
Since that branch has now been closed, and these variables are not showing up in files I've tested, I'm going to close this issue as I think it's been resolved.
