### ISSUE TITLE
Soil Profile Creation Assistance for APSIM

### ISSUE THREAD

**Issue by odjopuen** [APSIMInitiative/ApsimX#8321]
### What is your question?

Hello APSIM Team,

I am new to APSIM and currently trying to develop a simulation for a German land. The soil description provided by the farmer is "sandy loam, silty loam, loam." Unfortunately, I am unable to conduct further testing, and I'm seeking guidance on how to create a soil profile for this scenario. Specifically, I am unsure about the values for Bulk Density, AirDry, LL15, Dul, Sat, SW, and PAW across a 2-meter soil depth.

Initially, I thought I could use Apsoil for this purpose, but I couldn't find any option to download it as a program. Is there a resource where I can access pre-defined soil profiles that align with the parameters I need?

Your assistance would be greatly appreciated.

Thank you very much,
Jonny

**Comment by pjinnes** [comment]
I've used the ISRIC World Soil Information for my simulations. If you have the location details, it can generate a soil profile for you. You need to right click on the Field node of your simulation and then select download soil.

**Comment by odjopuen** [comment]
Hello, thank you very much! i have not seen it anywhere.
I tried this this morning and the only result I get is: "Object reference not set to an instance of an object."
![Apsoil](https://github.com/APSIMInitiative/ApsimX/assets/119527851/2edb07ae-5050-4606-a693-ba1419c6126f)

What can i do about it?

**Comment by pjinnes** [comment]
Hi Jonny, just looking at your screenshot, is that a comma instead of a full stop in your coordinate spec?
cheers, Pete
