### ISSUE TITLE
Running simulation for a particular trait with multiple values for future climate adaptation 

### ISSUE THREAD

**Issue by MPSbangari** [APSIMInitiative/ApsimX#8323]
### What is your question?

Hi,
I am looking to create a virtual cultivar with varying levels of a single trait such as RUE within a single simulation run 
 Currently, i can only generate one cultivar at a time, with a single trait value. Is there a way to establish a range for trait values and generate multiple cultivars in a single simulation run?

**Comment by par456** [comment]
For clarification, do you mean changing a trait while a simulation is running (so that its value is modified across the time the simulation runs), or do you mean being able to set up an experiment structure where a simulation is run multiple times with a trait having a slightly modified value each time (without having to make all those variations of the simulation).

**Comment by par456** [comment]
This is possible with a manager script and an experiment structure, I've made up an example provided below and I'll explain how it works.

I started with the Wheat example, and moved the simulation under an experiment node. I then added a Cultivar to the Wheat based off the Hartog Cultivar. I named this Variable Cultivar and removed the [Grain].MaximumPotentialGrainSize.FixedValue line as I'm going to make that the dynamically set variable for this.

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/babe660e-35eb-4019-b4fb-8c47bbf8d776)

Next I renamed and rewrote the Sowing Manager script, calling it SowingRule. In that I have some new variables for linked up the cultivar and adding MaximumPotentialGrainSize back into the cultivar based on a variable in the script. So based on the value of MaximumPotentialGrainSize in the script, the cultivar is modified before it is sown in. 

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/9e566a04-e2ee-4b64-a950-d14f34b20d36)

But to do this with different values we need to add a factor to our experiment. Under the experiment node I have this factor which modifies the variable in the script that sets the value of the cultivar.

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/aae7ec4c-39cc-4f6a-b8a2-59039c6cfb8d)

Running the experiment, I reported out the MaximumPotentialGrainSize in a report and it looks like this:

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/7464c9c8-04d3-49de-be4e-d7d60e7ec267)

It would be possible to do more than one trait at a time, however that would be a more complex Experiment setup with permutations and such.

**Comment by MPSbangari** [comment]
Thank you very much for your suggestion i set the factorial experiment earlier but didn't modify the script in the sowing rule. 

I tried to do the same with RUE but always get the error invalid path 



![RUE ](https://github.com/APSIMInitiative/ApsimX/assets/106666845/44f58d92-e825-4e2b-a7ae-b9deb4b3972a)

**Comment by MPSbangari** [comment]
![image](https://github.com/APSIMInitiative/ApsimX/assets/106666845/50bb2532-576c-4f30-a691-49edaf7c52d6)
![image](https://github.com/APSIMInitiative/ApsimX/assets/106666845/e6f6d2bf-a690-45a5-a6a3-14849708409f)
Could you please review these images?
 I attempted to modify the cultivar parameters with variable values without making any changes to the sowing script. However, I'm unsure if this is the correct approach. I am from a plant biology background and I am new to crop modeling. thats why i am not so confident about my approach.
Thanks for your help.

**Comment by lie112** [comment]
This video will provide you with a better understanding of using Experiments and factorials in APSIM Next Generation
[Factorial tutorial video](https://www.youtube.com/watch?v=S1E8V6jsW4A)

**Comment by par456** [comment]
> Could you please review these images? 

In your factor you are trying to change the trait directly on the crop, but those are read only so nothing will happen. That's what we need the parts in the sowing script for, as that lets us modify the cultivar.

If you've got the script set up correctly (and at least the part you showed looks good), then the line in your factor should look like something like this:

[SowingRule].Script.RUE = 1 to 2 step 0.1

I'm happy to look at your apsim file if you are still having trouble getting it working. But certainly have a watch of the video Adam linked above to make sure your factorial is set up correctly as well.

**Comment by MPSbangari** [comment]
> > Could you please review these images?
> 
> In your factor you are trying to change the trait directly on the crop, but those are read only so nothing will happen. That's what we need the parts in the sowing script for, as that lets us modify the cultivar.
> 
> If you've got the script set up correctly (and at least the part you showed looks good), then the line in your factor should look like something like this:
> 
> [SowingRule].Script.RUE = 1 to 2 step 0.1
> 
> I'm happy to look at your apsim file if you are still having trouble getting it working. But certainly have a watch of the video Adam linked above to make sure your factorial is set up correctly as well.

Thank you very much for reviewing the script. I believe I may have missed something in the script, as I am encountering these errors. yes i have seen the video that Adam has suggested. 

APSIMb6498525-c56c-492d-af1f-735f0e2d4af8.cs(55,9): error CS0106: The modifier 'private' is not valid for this item

APSIMb6498525-c56c-492d-af1f-735f0e2d4af8.cs(75,2): error CS1513: } expected

Additionally, I definitely intended to maintain 2 traits with variable ranges. I attempted to replicate the script you provided earlier for the wheat
[Sor_MPS.zip](https://github.com/APSIMInitiative/ApsimX/files/12811285/Sor_MPS.zip)

**Comment by par456** [comment]
Your file was pretty close to working, just had a typo in the script to fix and getting the right names for the factors. I've attached a version here that should run:

[Sor_MPS_2.zip](https://github.com/APSIMInitiative/ApsimX/files/12812133/Sor_MPS_2.zip)

Only other thing to note, just make sure your weather file has values until 2030 (since that is what the clock is set to end at), but otherwise I think this is what you were after.

**Comment by MPSbangari** [comment]
> Your file was pretty close to working, just had a typo in the script to fix and getting the right names for the factors. I've attached a version here that should run:
> 
> [Sor_MPS_2.zip](https://github.com/APSIMInitiative/ApsimX/files/12812133/Sor_MPS_2.zip)
> 
> Only other thing to note, just make sure your weather file has values until 2030 (since that is what the clock is set to end at), but otherwise I think this is what you were after.

Thank you very much for correcting this.. ..
