### ISSUE TITLE
Divide Function may need rethinking

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#8341]
### What happened?

This divide function is rather simplistic.  It does not take into account the relative size of either number when trying to avoid overflow.

https://github.com/APSIMInitiative/ApsimX/blob/36798c99979d5819ebc34accda0d055fc0b3fb82/APSIM.Shared/Utilities/MathUtilities.cs#L195C11-L195C11

### What Operating System are you on?

Windows

**Comment by hol353** [comment]
Fixed in #8343
