### ISSUE TITLE
Adding a new layer to Soil.Water cause unhandled exception

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#836]
soil.CalcPAWC checks the number of layers against the number of LL and DUL and throws an exception if they are different. This means you cannot add a new layer to the Soil.Water grid.

**Comment by zur003** [comment]
See also #31. I'm not sure whether than was ever resolved.

**Comment by zur003** [comment]
Also #594 appears to be a duplicate of this issue.

**Comment by hol353** [comment]
@zur003 Do we also close issue 31 and 594?

**Comment by zur003** [comment]
I would close 594, but not 31, which is a somewhat different issue.
