### ISSUE TITLE
Ability to suppress non-fatal error messages in Summary file

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8360]
### Describe the new feature

It would be quite useful if it were possible to optionally suppress messages to the Summary file. The DB file can get 'rather' bloated with these messages - totally out of proportion to the size of the actual output. This becomes more of an issue as large simulation jobs (grids across the country/world) are run. Would this be possible?

**Comment by ric394** [comment]
@sno036 Are you looking for a more specific option for only fatal errors in the capture rules drop down box? or just a checkbox to ignore the writing of non-fatal errors when using any of the other capture rule options?
<img width="914" alt="image" src="https://github.com/APSIMInitiative/ApsimX/assets/123442863/6aee088a-2961-4a80-9cb4-70f0da674bb7">
