### ISSUE TITLE
Specify N form in organic matter addition

### ISSUE THREAD

**Issue by matteolongo2** [APSIMInitiative/ApsimX#8373]
### What is your question?

Hi, I am trying to add slurry applications to my simulations using the operation model. However, looking at the Models/Interfaces/ISurfaceOrganicMatter.cs file I do not see the type of N among the list. I was thinking to combine it with multiple mineral fertilizer applications to simulate NH4 and NO3 addition but I do not see how to specify the amount of organic N.
Thank you

**Comment by hol353** [comment]
Are you wanting to add an amount of NO3 and NH4 to a layer (or top layer) in the soil? If so, then not possible from operations. You could use a manager script as a workaround. If this is what you want we could change the fertilise model to allow you to do this in operations via a fertilise apply.

SurfaceOrganicMatter can only add an amount of N.

**Comment by matteolongo2** [comment]
Yes, I would like to specify the amount of NO3, NH4, organic N, organic C (if possible also organic P) added to the soil surface (if possible also organic P). I am not familiar to manager scripts therefore it would be very helpful a change on the fertilise model.
Thank you

**Comment by hol353** [comment]
Ok thanks for the info. We'll think about this next week when we have an APSIM week. We alternate between APSIM development weeks and other project weeks.

**Comment by sno036** [comment]
The attached simulation in the zip file might work for you @matteolongo2. As @hol353 noted, Operations wont do this (but it would be great if it did) so I knocked up a Manager script to do a similar job. You can have multiple of these scripts in a simulation if needed.

[AddSlurry.zip](https://github.com/APSIMInitiative/ApsimX/files/13184792/AddSlurry.zip)

**Comment by hol353** [comment]
Thanks @sno036. Your AddSlurry management script is useful. 

Notes for @par456 and/or @ric394:
To make this easier we could add a method overload to SurfaceOrganicMatter.AddFaeces method that takes these arguments:
organicC, organicN, NO3N, NH4N, P

This would then be callable from Operations.

**Comment by matteolongo2** [comment]
The model seems to work properly, thank you. What if I also wanted to inject (not incorporate) the slurry to a specific depth?

**Comment by matteolongo2** [comment]
Answer update: actually, the model seems not to affect  NO3 and NH4 amount but just organic N. I attached an example. Thank you
[test.zip](https://github.com/APSIMInitiative/ApsimX/files/13267746/test.zip)

**Comment by hol353** [comment]
So it seems that the made Add method of SurfaceOrganicMatter doesn't allow NO3, NH4 to be added.


```c#
        /// <summary>Adds material to the surface organic matter pool.</summary>
        public void Add(double mass, double N, double P, string type, string name, double fractionStanding = 0)
        {
            if (mass > 0 || N > 0 || P > 0)
            {
                // Assume the "cropType" is the unique name.  Now check whether this unique "name" already exists in the system.
                int SOMNo = GetResidueNumber(type);
                if (SOMNo < 0)
                    SOMNo = AddNewSurfOM(type, type);

                summary.WriteMessage(this, $"Adding {mass:F2} kg/ha of biomass ({N:F2} kgN/ha) to pool: {type}. ", MessageType.Diagnostic);

                // convert the ppm figures into kg/ha;
                SurfOM[SOMNo].no3 += MathUtilities.Divide(no3ppm[SOMNo], 1000000.0, 0.0) * mass;
                SurfOM[SOMNo].nh4 += MathUtilities.Divide(nh4ppm[SOMNo], 1000000.0, 0.0) * mass;
                SurfOM[SOMNo].po4 += MathUtilities.Divide(po4ppm[SOMNo], 1000000.0, 0.0) * mass;

                for (int i = 0; i < maxFr; i++)
                {
                    SurfOM[SOMNo].Standing[i].amount += fractionStanding * mass * frPoolC[i, SOMNo];
                    SurfOM[SOMNo].Standing[i].C += fractionStanding * mass * C_fract[SOMNo] * frPoolC[i, SOMNo];
                    SurfOM[SOMNo].Standing[i].N += fractionStanding * N * frPoolN[i, SOMNo];
                    SurfOM[SOMNo].Standing[i].P += fractionStanding * P * frPoolP[i, SOMNo];

                    double fractionLying = 1 - fractionStanding;
                    SurfOM[SOMNo].Lying[i].amount += fractionLying * mass * frPoolC[i, SOMNo];
                    SurfOM[SOMNo].Lying[i].C += fractionLying * mass * C_fract[SOMNo] * frPoolC[i, SOMNo];
                    SurfOM[SOMNo].Lying[i].N += fractionLying * N * frPoolN[i, SOMNo];
                    SurfOM[SOMNo].Lying[i].P += fractionLying * P * frPoolP[i, SOMNo];
                }
            }
        }
```

We need to refactor this to take NO3, NH4 (as kg/ha) as arguments and add those amounts into the pools ``` SurfOM[SOMNo].no3``` and ``` SurfOM[SOMNo].nh4``` pools instead of the using the existing concentrations and multiplying by mass.

**Comment by matteolongo2** [comment]
I am sorry to stress again. How should I write it in the operation model? I do not see any changes in the application.
Again, I would like to specify 80 kg  N-NH4, 30 kg N-NO3 and 70 kg of organic nitrogen. Thank you
