### ISSUE TITLE
Cannot change initial water relative to crop in factorial with multiple soils

### ISSUE THREAD

**Issue by gdurri** [APSIMInitiative/ApsimX#8393]
### What happened?

Hi, 

I am having some issues setting up the soils in my file to have the initial water relative to the crop (sorghum) versus LL15. I have a factorial in my file with five factors for different sites that include sowing parameters, a weather node, and a soil node. 

As the default, the soils are all set to be relative to LL15 and I am wanting to change this to be relative to sorghum, which is parametrised for each individual soil. It seems as though there is a bug which means this won't work properly in the factorial. It works correctly for the first factor but will not for the subsequent factors, returning a 'Value cannot be null. (Parameter 'source')' error. If you leave it set to sorghum after it has shown this error and click into a different factor the initial water node will clear and throw a 'System.ArgumentNullException: Value cannot be null. (Parameter 'source')' error. I have looked at all the soils in a separate simulation by themselves and the relative to behaviour all works fine, only has issues in the factorial.

If anyone could please advise if I have done something wrong to get this behaviour, or if it is a bug that would be much appreciated. I have updated my apsim version (using 2023.10.7338.0.) and have attached my file. 

Thank you!
[File.zip](https://github.com/APSIMInitiative/ApsimX/files/13110769/File.zip)

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@gdurri I was able to run your apsim file with no errors. Was there any additional setup required to your example file?
I'm running the most current version of APSIM at the moment which is: 7349

**Comment by gdurri** [comment]
Hi @ric394, thanks for taking a look. 

There aren't any errors in the file itself, my issue was more about the buggy behaviour when trying to make the initial soil waters relative to sorghum for all the different soils. I have all soil waters set relative to LL15 (as this is the only possible way currently), the behaviour I described appears when you try to make them all relative to sorghum. 

Did you try to change the what the initial soil water was relative to for different soils or just run it as is?
