### ISSUE TITLE
How to load apsimx file in R 

### ISSUE THREAD

**Issue by eelsaf** [APSIMInitiative/ApsimX#8394]
[RC_Pundu_Apsimx.zip](https://github.com/APSIMInitiative/ApsimX/files/13116069/RC_Pundu_Apsimx.zip)
### What is your question?

Hi All

I try to use apsimx package in R. 
But i cannot upload the file. 

I tried 1st option using this code

# Load the APSIM-NG simulation file using db file
library("apsimx")
sim <- read_apsimx("RC_Pundu_15yr.db")

and 2nd option using 2nd code : 
# Load the APSIM-NG simulation file using apsimx file
library(apsimx)
tmp.dir <- tempdir()
extd.dir <- system.file("extdata", package = "apsimx")
RC <- file.copy(file.path(extd.dir, "RC_Pundu_15yr.apsimx"), tmp.dir)

But those options did not work.

Please help. 
I need to do parameter optimization using ApsimX in R.

Thank you.
Lisma

**Comment by peter-devoil** [comment]
Try:
```
setwd("<wherever your .apsimx file is>")
read_apsimx("<whatever your apsim file is called>.db")
```
If you have multiple report components (eg daily & harvest) then it can be loaded as a list, and the tables are then list elements:
```
read_apsimx("<whatever your apsim file is called>.db", simplify = F)$Harvest
```

**Comment by eelsaf** [comment]
Hi @peter-devoil 

Thank you. 
The code read_apsimx("<whatever your apsim file is called>.db", simplify = F)$Harvest is working. I modified to

sim <- read_apsimx("RC_Pundu_15yr.db", simplify = F)$AnnualOutput
And it can read my output.

However, I need to read whole simulation part : parameters, variables, input, etc.
I tried using 
sim_sim <- read_apsimx("RC_Pundu_15yr.db", simplify = F)$Simulation
or 
sim_OP <- read_apsimx("RC_Pundu_15yr.db", simplify = F)$OilPalm

But it ended up by NULL. 

This code 
setwd("<wherever your .apsimx file is>")
read_apsimx("<whatever your apsim file is called>.db")
also end up by NULL

Thanks

**Comment by peter-devoil** [comment]
Hi,

The simulation parameters aren't stored in the .db file - they're in json format inside the .apsimx file.

In the past, I've generated 1-line report tables for static parameters, eg soil LL/DUL etc which makes plotting easier, these can be useful when you've got multiple soil profiles inside a set of simulations

You'd have to use a json reader to get the rest though. All the json readers for R are particularly ugly. And the apsim parameter formats (ie structure of the json) change all the time.

P

**Comment by JodyBig** [comment]
My workflows have also been broken by the continually rearranging of the structure of the json file.

**Comment by femiguez** [comment]
@eelsaf If you need to perform parameter optimization you want to look at the 'optim_apsimx' function in the 'apsimx' package.
