### ISSUE TITLE
Summary Presenter is Difficult to use

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#8398]
### What happened?

1) The upper part of the presenter (ie settings) extends beyond the right hand side of the screen when working on a tablet and so cannot to used.
2) No vertical scroll bar is visible and so it is hard to navigate the summary log.
3) When using page down to navigate, the page scrolls right and so you cannot see the start of each line.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
Some changes suggested in #8378 will partially resolve this issue.
