### ISSUE TITLE
New GTKUtilities not compatible with CLEMPresenters

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#8402]
### What happened?

CLEM provides a number of components to help users with less coding ability and acts more as a plug and play model.
To achieve this there are a number of wrapper presenters providing greater detail, access to helper properties and custom displays to the user. These were written to allow any APSIM models to use this functionality in future while not affecting any APSIM functionality.

One example is the CLEM report presenter that provides a number of properties for the user to set and creates the variables and events for a given report in the background. Most CLEM models have a properties, summary and version tab as well as the property name and description provided when selected in the tree as well as the direct link to the Online reference page for the model. The report presenter (see image) has a "Data" tab that shows the Report presenter for the data created (usually between Properties and Summary tabs).

The latest changes have introduced the GtkUtilities.GetBorderOfRightHandView(owner as ExplorerView) call. Unfortunately, as the report presenter is wrapped in the CLEM wrapper presenter the explorer view isn't available for this call. I had added functionality to get around situations like this in the past. Rather than get my head back around all the GTK I haven't touiched for a year, does anyone have any idea of an easy way to provide the owner to this call from the CLEM presenter (use CLEM examples with APSIM as examples) when it has to bubble up another level to get the explorerView? Basically, owner is passed in all the constructors while ReportView is is defined and if a CLEMWrapperPresenter. I need to look up another level to give the ExplorerView reference, but I have tried to avoid any Type based if statements to achieve this in the past. 

![image](https://github.com/APSIMInitiative/ApsimX/assets/19215637/e3c04fc6-b5d7-4a55-bc72-d93ea33baeb0)

This also relates to the ActivitiesPerformedPresenter that used the old GridView to display a table of icons relating to when all activities were performed and their status during complicated CLEM simulations. This provides the user with a level of transparency as to what has happened in their simulation. The display no longer works, but fortunately I had written a HTML based alternate version.

P.S. Does anyone else not like the new big fat chunky scroll bars that came with the latest upgrade?

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Ah, yep that's a fairly easy fix to make it work. Just need to make that function accept a more generic version of the view and handle for situations where its not the explorer view. I'll put a pull request in with a fix.
