### ISSUE TITLE
Search and replace in Report component doesn't save changes

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#8404]
### What happened?

When doing a Ctlr+H search and replace in the Report component text, the text is replaced but it never saves the changes.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@her123 This is working as intended. To save changes you'd normally click save or run.
I've tried clicking away from the report node and coming back and the text has remained changed. 
Is the text not remaining changed in your current environment?

**Comment by her123** [comment]
I tried again after a couple of rebuilds and it seemed to work. It must have been an incomplete rebuild.
