### ISSUE TITLE
Improved batch running

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8407]
### Describe the new feature

@hol353 set me up with the current system to run apsimx files in batches. Currently it is more designed for where there is a single experiment in the apsimx file - that that works well where there is a complete/balanced design in the experiment. When there are some soils with some locations and note others (for example) and a series of simulations within each valid soil-weather combination then the current design doesn't work well. I got around this with a script/instruction file as below with Dean's assistance:

```
load BaseCl.apsimx
[Soil]=SoilLibrary.apsimx;[Ahiaruhe_1a1]
[Weather].FileName=16864.met
[SimulationExp].Name=Sim0001
run

load BaseCl.apsimx
[Soil]=SoilLibrary.apsimx;[Ahuriri_7a1]
[Weather].FileName=19479.met
[SimulationExp].Name=Sim0002
run

load BaseCl.apsimx
[Soil]=SoilLibrary.apsimx;[Ailsa_5a1]
[Weather].FileName=19479.met
[SimulationExp].Name=Sim0003
run
```

It works ..., but is uninformative about progress (I can see the DB file size increasing is all) and is (probably) very inefficient. 

What would be great would be the ability to:
- describe the simulation variants in some form of template
- have that template insert combinations from a text file (e.g., taking the above there would be three lines specifying soils and weather files)
- have the Experiment node automatically (or use the template to assign names) rename itself
- and have something to show progress through what could be tens-hundreds of thousands of simulations

I hope this makes sense!

**Comment by ric394** [comment]
I like the idea of a simulation variant template. There is a definite need for this feature.
I also like the idea of it reporting progress, this is also sorely needed.
@hol353 I think these would be good additions to the cli feature. Are you happy for me to work on these?

**Comment by BrianCollinss** [comment]
Could I please know about the instruction/script you used to run our simulations? How is it run?

**Comment by ric394** [comment]
> Could I please know about the instruction/script you used to run our simulations? How is it run?

If you're looking for instructions on how to do a similar thing the documentation is [here](https://apsimnextgeneration.netlify.app/usage/commandlineusage/)

**Comment by LenLon** [comment]
I got around this limitation by pregenerating the .met files for each simulation grid point, and then writing a long and complex loop in R using the apsimx R package. I am currently working on a gitlab repo to make the necessary code public. It is not as complex as psims but requires more data handling beforehand. It works with a more complex set of simulations, soil profiles and fertilisers if everything goes as planned. 

I would love a command-line implementation as well!

**Comment by ric394** [comment]
@hol353 and I have had a think about this one.

We think implementing another switch like `Models.exe --batch model-property-changes.csv commands.txt` will be appropriate.

The idea is:
1. Provide a csv (model-property-changes.csv) with column names that are used in a config file as placeholders.
2. The placeholder values in the corresponding location of the config file will be replaced with the cell values in that column.
3. A run through of the config file will occur for each record/line in the csv.

If we use the example by @sno036 here:
```
load BaseCl.apsimx
[Soil]=SoilLibrary.apsimx;[Ahiaruhe_1a1]
[Weather].FileName=16864.met
[SimulationExp].Name=Sim0001
run

load BaseCl.apsimx
[Soil]=SoilLibrary.apsimx;[Ahuriri_7a1]
[Weather].FileName=19479.met
[SimulationExp].Name=Sim0002
run

load BaseCl.apsimx
[Soil]=SoilLibrary.apsimx;[Ailsa_5a1]
[Weather].FileName=19479.met
[SimulationExp].Name=Sim0003
run
```

we could create a csv like below:
```
soil-name,weather-file-name,sim-name
Ahiaruhe_1a1,16864.met,Sim0001
Ahuriri_7a1,19479.met,Sim0002
Ailsa_5a1,19479.met,Sim0003
```

and we could create a config file like:
```
load BaseCl.apsimx
[Soil]=SoilLibrary.apsimx;[$soil-name]
[Weather].FileName=$weather-file-name
[SimulationExp].Name=$sim-name
run
```

**Comment by peter-devoil** [comment]
Dollar sign substitition. Haven't we come a long way!

**Comment by ric394** [comment]
@peter-devoil it is a command line feature after all 😄
