### ISSUE TITLE
Cannot run older versions of APSIM

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#8411]
### What happened?

After pulling the tip version of APSIM from the repo this morning and compiling, I noticed that I no longer can run any older version of APSIM. I have projects in which we have fixed the version of APSIM that is used, for that I download and install the particular version I need (e.g. apsim-7317). After the last pull/compile, that version does not run at all (the GUI does not load). This has been replicated in another PC here. If I click on the icon/shortcut to APSIM or go to the bin folder and run the executable, the result is the same: windows sort of attempts to run it (briefly popping up a reference to it in task manager) but then closes it with no clear feedback  (the only 'clue' is that during the fraction of second that APSIM pops up in the task manager, it is shown with status 'suspended'). Now I cannot run any of the old versions I have (regardless of whether I have the tip version open or not).
I have tried rebooting the PC, I have re-installed the old version, and also tried to run it as an administrator, but nothing works… I then tried to revert the repo to an older date, if I go to an old enough date (say early October) then I cannot run even the compiled version (not even in debug mode). I tried several dates and I noticed that can only run APSIM versions older than the 19th of October...
I could not find any clue by looking at what was committed around the 18th, the error I get in the debugger is cryptic to me (it says 'There is an error in the XML document', stopping at ConfigurationCoverter.cs, line 52). Whatever it is, we need to find a way to revert this (and prevent, eventually). Because at the moment, I cannot run my projects as they depend on specific older versions. I don't even any idea of what I could to delete/uninstall to get those back up running... Any help much appreciated.
@dea

### What Operating System are you on?

Windows

**Comment by zur003** [comment]
It appears to be a problem with parsing of the ApsimX.xml file, which resides in your [user]\AppData\Roaming\ApsimInitiative\ApsimX folder. Rename it, and the old versions should run. That's just a temporary work-around - obviously the underlying problem needs to be fixed.

**Comment by zur003** [comment]
It appears that the problem is that StatusPanelHeight in Configuration.cs was changed from int to double, and the XML parser in the older versions chokes when attempting to read a floating point value where it's expecting to see an integer. At least, that's my tentative diagnosis. I'll leave the fix to someone else.

**Comment by ilhuber** [comment]
#8384 is related. Dotnet apparently still creates objects even if conversion fails, these go to GC and an exception is thrown which takes the application down.

The change I made in #8385 should prevent this from being an issue on future versions of APSIM, though I believe it will clobber whatever settings had been there before. If rescuing earlier versions of APSIM is wanted the type change in #8359 will probably have to be reverted.

**Comment by par456** [comment]
> It appears that the problem is that StatusPanelHeight in Configuration.cs was changed from int to double, and the XML parser in the older versions chokes when attempting to read a floating point value where it's expecting to see an integer. At least, that's my tentative diagnosis. I'll leave the fix to someone else.

Yep, this is the problem. We changed the saved positions from pixels across the screens to a percentage (because it was struggling when you changed resolution), but that's had this unintended problem.

I think I know a decent way to fix this, will put in a patch.
