### ISSUE TITLE
How to change precision for a specific report variable?

### ISSUE THREAD

**Issue by JodyBig** [APSIMInitiative/ApsimX#8417]
### What is your question?

In APSIM classic you could set the precision of a single report variable or for all reported variables. Is this functionality still available?

**Comment by peter-devoil** [comment]
I think they're stored as doubles, so it depends on your presenter. The UI report presenter doesnt keep its state from what I can tell, but if you're reading from the .db you can format it afterwards

**Comment by par456** [comment]
As Peter said, underneath all numbers are stored as doubles, which have lot of precision. The GUI will limit numbers to 3 decimal places when displaying it in the datastore, but if you want to see the entire number then you can always export to excel or csv and see them that way.

Any rounding of the number in the datastore is purely visual, underneath the full precision is always used.

**Comment by JodyBig** [comment]
Excellent - thanks.
