### ISSUE TITLE
A bug to calculate the `PlantAppearedLeafNo` in Leaf.cs

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#842]
The calculated values of `PlantAppearedLeafNo` are not per plant, but per square meter if my understanding is correct.

I try to fix this bug, but cannot compile current source codes. The first error message is 

	Severity	Code	Description	Project	File	Line
	Error	CS0103	The name 'In' does not exist in the current context	APSIM.Shared	APSIM.Shared\Utilities\ApsimTextFile.cs	747

**Comment by HamishBrownPFR** [comment]
Should be a simple fix.  Have you updated your APSIM.Shared repository, this needs to be kept in sync with the APSIM repository

**Comment by HamishBrownPFR** [comment]
There is a property in Structure.cs (PlantTotalNodeNumber) which is doing what PlantAppearedLeafNo will do when you fix it.  I suggest deleting PlantTotalNodeNumber and redirecting its dependencies to the fixed PlantAppearedLeafNo

![image](https://cloud.githubusercontent.com/assets/7295858/15301548/46e24630-1c02-11e6-9e47-4699fa47514a.png)

**Comment by byzheng** [comment]
Hi Hamish,

I have brand new clone for both repositories, but still have the same
error. Not sure what's happen here.

Cheers,
Bangyou

**Comment by HamishBrownPFR** [comment]
Do you have a file called Model.xml in your C:\ApsimX\bin dirrectory.  If so delete it.  There might also be another file there that starts with model that needs deleting, there should only be files in there called models

**Comment by byzheng** [comment]
I re-cloned APSIMX and APSIM.Shared from github into new folder (didn't find model.xml), but still have the same error message. Not sure which package defines `In` function. Do you need to update my visual studio 2015 (Version 14.0)?

**Comment by hol353** [comment]
The compile error was introduced yesterday. We're working on it.

**Comment by hol353** [comment]
APSIM.Shared has been patched to fix this. Do a pull.

**Comment by byzheng** [comment]
Thanks Dean. I can compile it now. Will fix this bug according to Hamish suggestions.

**Comment by HamishBrownPFR** [comment]
Thanks guys

**Comment by byzheng** [comment]
I have change source codes to fix this bug which is working in my own simulation. However, i still cannot run the WheatValidation.apsimx. Some strange error message:

    Unable to find assembly 'zukhkl15, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by hol353** [comment]
The temporary file name assembly mentioned above (zukhkl15) refers to a manager script that hasn't compiled correctly. Do you have errors in your summary file?

**Comment by byzheng** [comment]
I recloned the APSIM.Shared and ApximX from github, compiled and run simulations of WheatValidation.APSIMX in debug mode. After clicking run simulation twice (no response in the first time), the error message:


     An exception of type 'System.Runtime.Serialization.SerializationException' occurred in mscorlib.dll but was not handled in user code

     Additional information: Unable to find assembly 'h1scn1pi, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by hol353** [comment]
OK I think I know what is happening. When you click Run, it seems to do nothing for almost a minute but in fact it is building 875 simulations. Don't click Run a second time. Be patient.

We'll have to fix this. How about you create an issue on GitHub about this.

**Comment by byzheng** [comment]
Thanks @hol353. Just tested. WheatValidation.APSIMX is runing now. Will create issue for it.

**Comment by HamishBrownPFR** [comment]
This bug has been resolved as far as I can see
