### ISSUE TITLE
Problem with graph

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#8421]
### What happened?

My graph is blank and I'm not sure why. I've simplified the sim and attach it here.

[test.zip](https://github.com/APSIMInitiative/ApsimX/files/13261477/test.zip)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
It seems to be working on my end?

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/682f276e-c881-4417-a9ad-70e2dbbc8889)

**Comment by hol353** [comment]
Sorry I forgot to mention the graph that isn't working is called 150 (Under Soil water folder). I have deleted the .db file and rerun it and it still doesn't work.

![image](https://github.com/APSIMInitiative/ApsimX/assets/1943827/e7d98fd7-5702-4a58-b146-1e1adcaae743)
