### ISSUE TITLE
Formulas in observed data aren't converted to numeric

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#8425]
### What happened?

The chickpea observed harvests contain a few formulas in the MaturityDAS column that aren't converted to numerics when graphing

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@peter-devoil I was able to see the values being pulled in. The rows with formulas where being converted correctly as shown in the graph below:

<img width="485" alt="image" src="https://github.com/APSIMInitiative/ApsimX/assets/123442863/bae05e1c-266f-4cac-8f9e-374239bc2f52">

The values in the observed file with formulas:

<img width="848" alt="image" src="https://github.com/APSIMInitiative/ApsimX/assets/123442863/9a40de4a-be44-4542-b849-4ce701f5a94b">

**Comment by peter-devoil** [comment]
I should have explained that I had trouble plotting pred:obs maturity das in the chickpea verification dataset. The regression equation doesn't show but the points do

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by par456** [comment]
Is this what you're seeing Peter?
![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/6c245482-8a53-4589-9996-74d61e20a12f)

I can see the 4 points from the related experiment in that folder, the 1:1 line and the regression line and equation for it in the top left.

**Comment by peter-devoil** [comment]
I was looking at 
![image](https://github.com/APSIMInitiative/ApsimX/assets/1924386/dd9f9e17-17c7-4b7a-9553-f051868847d2)

**Comment by ric394** [comment]
@peter-devoil that graph isn't in the current version of the Chickpea validation file. Could you send us a copy of the file you are using please?

**Comment by peter-devoil** [comment]
It's a copy of the flowering das chart immediately above, change the variable to MaturityDAS
[Chickpea.apsimx.zip](https://github.com/APSIMInitiative/ApsimX/files/13313470/Chickpea.apsimx.zip)
