### ISSUE TITLE
WSC stress for tiller number in wheat model

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#843]
@HamishBrownPFR Not sure about your point of WSC stress for tiller number in wheat model. But tiller number is too sensitive to WSC in our trait model experiment, in 2015. 

The results with enabled WSC:

![default](https://cloud.githubusercontent.com/assets/1657381/15306401/a7bc6fd4-1c0d-11e6-9892-a906ef2350d5.png)

The results with disabled WSC:

![disable-wsc](https://cloud.githubusercontent.com/assets/1657381/15306409/bada1cba-1c0d-11e6-9880-a269c33f329d.png)

**Comment by HamishBrownPFR** [comment]
@byzheng This is work in progress in issue #454
