### ISSUE TITLE
N Initialisation Q

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#8439]
### What is your question?

If I specify N distribution on a profile that is incomplete - eg only defined for surface layers in a soil of 1800mm:
![image](https://github.com/APSIMInitiative/ApsimX/assets/1924386/b54e8302-8370-4db5-9711-a746d5118dd2)
 the initial N content (66 kg/ha) has some extra N from somewhere. Where could that be?

[no3.apsimx.zip](https://github.com/APSIMInitiative/ApsimX/files/13329716/no3.apsimx.zip)

**Comment by BrianCollinss** [comment]
Could it be from previous crop's root residue?

**Comment by peter-devoil** [comment]
It's a 2 day simulation. The value at the end of day 1 is 66kg, yet the initial value was 50.

**Comment by hol353** [comment]
It currently ramps NO3 and NH4 (and SW) back to zero below your sample depth (300mm) in a rather crude way.

See Solute.Standardise method: https://github.com/APSIMInitiative/ApsimX/blob/master/Models/Soils/Solute.cs#L235-L254

**Comment by hol353** [comment]
Actually it sets it to a low ppm value. Must be because our models don't like zero N.

**Comment by peter-devoil** [comment]
The N model does just fine with zero N. The plants not so much, though..

It's hard to think of what the correct behaviour is here - throw an error when undefined, or use some hard-coded default that isnt obvious to the user. If I was to forced to guess a default value, 0 would be my preference.
