### ISSUE TITLE
Failure to clean up temporary files on simulation runs (Debian release)

### ISSUE THREAD

**Issue by JBris** [APSIMInitiative/ApsimX#8440]
### What happened?

When I try running APSIM on Ubuntu, I run into an issue where a large number of temporary files are created: 

![image](https://github.com/APSIMInitiative/ApsimX/assets/16170973/c967b418-67c4-40b1-8bc8-d188153c5c54)

These files are not cleaned up at the end of the APSIM simulation. This can result in a large number of created files when many APSIM simulations are run.

### What Operating System are you on?

Linux

**Comment by par456** [comment]
Those could be manager scripts dlls. Can you check if they still get created in a simulation that has no manager nodes in it?

**Comment by JBris** [comment]
Hi @rcichota

I think from what we had discussed previously, the issue is related to the use of manager scripts. But would you like to please test this out to confirm?

**Comment by rcichota** [comment]
Yes, they are the compiled versions of manager scripts. In windows they are either deleted as soon as the simulation terminates or are stored in some 'hidden' place and windows takes care of cleaning up... In Linux these go to ```/tmp``` and stay there. I've been running thousand simulations with a few managers in them. The disk usage builds up pretty quickly. I now have a script to 'manually' delete them, but it is not ideal and risks deleting files from other users...

**Comment by Keith-Pembleton** [comment]
We have this problem on our HPC so we would like to see a fix.  Can/could the APSIM temporary directory be set on the command line or via a variable?, this way it could be set to the temporary job working directory in /localscratch, so when the directory is deleted at the end of the job, it also deletes the temporary files?

**Comment by hol353** [comment]
I've made a change that means the files aren't created in the first place when running from the command line. It turns out they are only needed if you are running from the GUI and want to debug manager scripts.
