### ISSUE TITLE
How to add genetic information to APSIM?

### ISSUE THREAD

**Issue by ankanasadhu** [APSIMInitiative/ApsimX#8445]
### What is your question?

In all the sources we have referred to the information provided was to add the genetic information as cultivar[phenology]. Please let me know if that is the way to proceed or there is some other way to add.
Does genetic information refer to any other data other than cultivar information? Any references or guides to the same will be much appreciated!

**Comment by hol353** [comment]
I'm unsure what you are asking. To add cultivar specific parameters you can add a cultivar model to a plant model and then modify that plant's phenology (or any other) parameters.

What genetic information are you referring to?

**Comment by ankanasadhu** [comment]
I want to add plant chromosomes information or any genetic information to my APSIM model. There isn't any particular genetic information I am referring to but in general any and all forms of it. I want to understand in what ways can I add genetic information to APSIM model.

**Comment by hol353** [comment]
APSIM is an empirical model that is parameterised by things that can be measured in the field. APSIM doesn't really operate at the genetic level e.g. there is currently no way to add plant chromosome information. The exception to this is plant phenology. Some of APSIM's models genotypes are parameterised with genetic information. This isn't my area of expertise so I'll leave it to others to comment.

**Comment by peter-devoil** [comment]
Daniel Wallach wrote a chapter on this subject in his book "Working with Dynamic Crop Models: Methods, Tools and Examples for Agriculture and Environment". Highly recommended.

**Comment by ankanasadhu** [comment]
Thank you for the clarifications!
