### ISSUE TITLE
APSIM.Server + APSIM.Client example hangs on sys/socket read() calls

### ISSUE THREAD

**Issue by MorganMasters** [APSIMInitiative/ApsimX#8449]
### What happened?

supporting files: [met_and_apsimx.zip](https://github.com/APSIMInitiative/ApsimX/files/13398069/met_and_apsimx.zip)

APSIM Version: 2023.8.7298
APSIM.Client Version: e303a9b (https://github.com/APSIMInitiative/APSIM.Client/tree/e303a9b18870682bafe36905c4fab29b6b6bfe2a)
.NET Version: 6.0
Building from source, [per webpage instructions](https://apsimnextgeneration.netlify.app/contribute/compile/linux/)
architecture: x86_64

Hello, APSIM,

I am trying to establish a server/client pair using the ZMQ+msgpack APSIM.Server version and APSIM.Client/examples/main.c. We can establish the socket connection, but using the attached *.apsimx and *.met files hangs upon the first call to sys/socket `read(...)` within `validateResponse(...)`.

The entire readout from executing APSIM.Client/examples/main.c is:
``` 
$ ./example
Connecting to server on 127.0.0.1:57220...connected
Running sims with the following changes:
  [Sorghum].Phenology.Juvenile.Target.FixedValue = 120.00
```

The entire readout from the server is:
```
$ dotnet run -project APSIM.Server/ZMQ+msgpack/APSIM.ZMQServer.csproj -v -a 127.0.0.1 -p 57220 -f ApsimX/Examples/Sorghum.apsimx
Started external server on tcp://127.0.0.1:57220
```

Probing on the server side, we found that the code hangs on the server's OneshotCommunicationProtocol call to `ReceiveMultipartMessage()`, where no non-null message ever arrives during preceding `sendString(...)/sendInt(...)` calls in APSIM.Client.

### What Operating System are you on?

Linux

**Comment by MorganMasters** [comment]
@jmadden173 
@cjosephson

**Comment by peter-devoil** [comment]
Apsim.Client uses an older, homegrown protocol in https://github.com/APSIMInitiative/ApsimX/tree/master/APSIM.Server/V1, which is the apsim-server binary in bin/Debug/net6.0 .

The ZMQ protocol is very different. There's an R script in https://github.com/APSIMInitiative/ApsimX/tree/master/Tests/Simulation/ZMQ-Sync that used to work once upon a time - let me know if it's not.

**Comment by cjosephson** [comment]
@peter-devoil we get similar client/server issues even when using APSIM.Server/V1 , but it sounds like ZMQ is where future development effort would be focused, so we'll check out the R script and report back.

**Comment by MorganMasters** [comment]
@peter-devoil @cjosephson Confirmed: after fixing a few hard-coded filepaths, we have a successful run of ZMQ-InteractiveVariables.R

Are you aware of what might be different between this working instance of an APSIM.Server and the instances the tutorial content generates?

**Comment by peter-devoil** [comment]
Sorry - which tutorial?

**Comment by MorganMasters** [comment]
apologies, I meant the [Usage/Server page](https://apsimnextgeneration.netlify.app/usage/server/)

After that primer, "the tutorial" was using the example.c I cite in my initial post to talk with ZMQ servers

**Comment by peter-devoil** [comment]
Thanks - I'll update that page. ZMQ isn't the same as the C client, as you've found.

FYI there are a plethora of server implementations around - don't feel like you have to choose something that isnt working for you. The samples here are only intended as a capability guide, no doubt your particular application and hardware will operate differently.

**Comment by ric394** [comment]
@peter-devoil can you please update the documentation page?
