### ISSUE TITLE
Sum of plant nitrogen uptake and water uptake don't work 

### ISSUE THREAD

**Issue by hedycau** [APSIMInitiative/ApsimX#8452]
### What happened?

1. Sum([Plant].NitrogenUptake) and Sum([Plant].WaterUptake) don't work in the daily report. Suspect due to the null value before sowing.
2. [Plant].NitrogenUptake[i] is not available, as the format is list not array. Could we make them as an array? Or create a variable to sum them as APSIM Classic does? 

### What Operating System are you on?

Windows

**Comment by Keith-Pembleton** [comment]
Hi Di 
does Sum of [Wheat].Root.NTakenUp do what you need?

**Comment by hedycau** [comment]
> Hi Di does Sum of [Wheat].Root.NTakenUp do what you need?

Aha, yep, silly me, forgot the root! Thanks!
