### ISSUE TITLE
GUI rename of copied node not working properly

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8459]
### What happened?

If you copy a node in the GUI then rename the copied version, quite often the name change gets applied to the original version and not the node you are actually chaining the name on.  I have also found sometimes if you try to move a copied node using ctrl+up or down it is the original node that is moved and not the one you are trying to move.

### What Operating System are you on?

Windows

**Comment by HamishBrownPFR** [comment]
I have also found if you copy a graph and change the series it is plotting, the view changes when you are on the series node but goes back to the view of the copied graph if you select the parent graph node.

**Comment by HamishBrownPFR** [comment]
Sometimes saving will restore normal behavior and sometimes it requires a reopen of the gui

**Comment by par456** [comment]
The first problem should be closed by the pull request #8458

Once that's merged in can you check if it also fixes the graph problem? I've not been able to reproduce that.

**Comment by HamishBrownPFR** [comment]
This has been resolved
