### ISSUE TITLE
Userinterface has no response or indicator when preparing big simulations. 

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#846]
When I run WheatValidation.apsimx, it takes a long time to prepare 875 simulations. After clicking `Run`, UserInterface has no response or indicator about simulation preparing. There is an error message when clicking `Run` again:

    An exception of type 'System.Runtime.Serialization.SerializationException' occurred in mscorlib.dll but was not handled in user code

    Additional information: Unable to find assembly 'h1scn1pi, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

We should stop user to click `Run` simulation again if simulation is preparing/running and add indicator  for preparing.

See #842 for more details.

**Comment by HamishBrownPFR** [comment]
This is partly related to #806.  There are currently lots of simulations being run that are not needed but there is no easy way to drop them out of the factorial.  Certainly something is needed to show that the model is actually doing something while it is preparing simulations

**Comment by hol353** [comment]
Done.
