### ISSUE TITLE
How to write Operations?

### ISSUE THREAD

**Issue by matteolongo2** [APSIMInitiative/ApsimX#8463]
### What is your question?

What is the proper way of writing Operations? Is there documentation showing which operations users are allowed to insert and how to write them?
E.g. I would like to apply irrigation using
`2012-06-15 [Irrigation].Apply(Amount: 500, depth: 0, efficiency: 0.5,willRunoff:FALSE)` but I get "Cannot find method: Apply in model: [Irrigation]". Same for AddFaeces

**Comment by BrianCollinss** [comment]
Do you have **Irrigation** object in your simulation tree?

**Comment by par456** [comment]
Just a syntax error on there that was confusing the complier.

`2012-06-15 [Irrigation].Apply(500, depth:0, efficiency:0.5, willRunoff:False)`

Because Amount is a required parameter, you don't name it like the other optional ones.

**Comment by matteolongo2** [comment]
Thank you very much! They both work.
I guess I need to look at the code to understand what I can input in the Operations, isn'it?

**Comment by hol353** [comment]
You can nominate amount though - with a lowercase first letter I think.

**Comment by par456** [comment]
Ah yep, that does work. You can still name required parameters, but the whole thing is case sensitive which is what was causing the problem with the original line.

`1912-06-15 [Irrigation].Apply(amount:500, depth:0, efficiency:0.5, willRunoff:False)`

> Thank you very much! They both work.
> I guess I need to look at the code to understand what I can input in the Operations, isn'it?

Operations should be able to call any function on a model in your simulation, it's just a matter of getting the name and parameters exactly right, and the error message isn't always the most helpful when you get it wrong.

If that's all sorted, I'll close this issue.

**Comment by hol353** [comment]
When you press a '.' character in the irrigation line, intellisense should pop up a menu and let you choose 'Apply'. If you hover of 'Apply' it should show the arguments you can supply.

![image](https://github.com/APSIMInitiative/ApsimX/assets/1943827/0ef00b94-4380-42f8-bf04-32b490800973)
gh I think it shows what arguments can be supplied
