### ISSUE TITLE
Error in calculation of PAW

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8466]
### What happened?

The calculation of PAW in the fourth layer for ryegrass is out by a factor of 3 - all the others are wrong as well. By layer they should be 24.9, 24.8, 32.35, 33 mm. Simulation attached

[PAWerror.zip](https://github.com/APSIMInitiative/ApsimX/files/13445960/PAWerror.zip)

![image](https://github.com/APSIMInitiative/ApsimX/assets/12176269/de70b439-aedf-404e-91ce-81bb7f71472f)
![image](https://github.com/APSIMInitiative/ApsimX/assets/12176269/554b0e4d-3d94-47f1-8dc7-7b9ed595c457)

### What Operating System are you on?

Windows

**Comment by hol353** [comment]
Looks OK to me. 

PAWC = DUL - CropLL
= 0.35 - 0.012
= 0.338 x 300 to convert to mm
= 101.40

Perhaps you are assuming that PAWC is relative to LL15 instead of crop LL?

**Comment by ric394** [comment]
Closing. If this is still an issue feel free to reopen this issue.
