### ISSUE TITLE
Why the calculated ratio between PAWmm and Physical PAWCmm is greater than one? 

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/ApsimX#8467]
### What is your question?

Dear ApsimX users 
I tried to reset initial soil water on the 1st Feb each year based on soil water modelling on the 31st Jan alongside wheat crop modelling from 1/1/1957 to 31/1/2023 using ApsimX package. PAWmm was output on the 31st Jan relative to LL15 (fill from the top). The physical PAWC is calculated from the difference between dul and ll15 across the whole soil profile. But I noticed that the calculated ratios between PAWmm/PAWCmm in some years (1971, 1996, 2001 and 2012) are greater than one. Just wondering where the problem comes from. Please pay attention to 31st Jan output as this is our interested point for output PAWmm.

Your support and help are greatly appreciated!

Warm regards!
Qunying Luo  

[Soil water & crop modelling.zip](https://github.com/APSIMInitiative/ApsimX/files/13445942/Soil.water.crop.modelling.zip)

**Comment by hol353** [comment]
PAW and PAWC  are both calculated as DUL - LL15. Soil water and hence PAW can go above DUL though so fraction full can be > 1.

**Comment by qluo02** [comment]
Thanks, Dean!
