### ISSUE TITLE
Unable to find where I can modify the CO2 conc. in model?

### ISSUE THREAD

**Issue by Rizwan3946** [APSIMInitiative/ApsimX#8470]
### What is your question?

Hi Folks, I want to change the CO2 conc. levels in model to check the impact on crop performance. Previously it can be modified in "ClimateController" but now it's not showing the CO2 conc. Could you please clarify where I can modify this in model?

**Comment by BrianCollinss** [comment]
I usually write manager scripts to change it. I assume you can add it to the weather/met file as well though I've never tried.

**Comment by Rizwan3946** [comment]
> I usually write manager scripts to change it. I assume you can add it to the weather/met file as well though I've never tried.

Hi Brian, thanks it working in weather/met file. But I don't have any idea about manager script where I can place it and write script.

**Comment by BrianCollinss** [comment]
You can have a look at Example files to familiarise yourself with the manager scripts. Writing a script requires some knowledge of C# (or VB?).
