### ISSUE TITLE
How to deal with cutting? 

### ISSUE THREAD

**Issue by matteolongo2** [APSIMInitiative/ApsimX#8474]
### What is your question?

Hello, I'm interested in cutting cover crops and leaving them on the ground. If I use `EndCrop(),` I assume the crops will stay as standing dead biomass. 
Moreover, what if I want to cut the crop residues, leave them on the ground, and then remove them after n days? Thank you.

**Comment by par456** [comment]
Closing this as I believe the question has been answered.
