### ISSUE TITLE
No new builds since November 7th

### ISSUE THREAD

**Issue by ilhuber** [APSIMInitiative/ApsimX#8475]
### What happened?

It seems like there hasn't been a new version released since November 7th at registration.apsim.info as well as in the upgrade dialogue in the APSIM UI.

**Comment by jbrider** [comment]
Could someone check the Classic builds as well.
Has the build results page moved for Classic?

**Comment by hol353** [comment]
@peter-devoil. Jenkins is failing on creating new releases. If you look at the jenkins logs (https://jenkins.apsim.info/job/apsim-release/437/console) you can see this:

```
[91msed: can't read /apsim/APSIM.Server/Properties/AssemblyVersion.cs: No such file or directory
[0mThe command '/bin/sh -c echo version=$version && sed -i -e "s/0\.0\.0\.0/$version/g"     /apsim/Models/Properties/AssemblyVersion.cs     /apsim/APSIM.Server/Properties/AssemblyVersion.cs' returned a non-zero code: 2
[Pipeline] }
```

Is this something to do with your APSIM Server changes?

**Comment by peter-devoil** [comment]
I changed the .csproj files for the move, looks like I missed the mac installer.  Quelle surprise.

Is [this](https://github.com/APSIMInitiative/ApsimX/blob/49dd7571d688bc5cfb130545551c05edc325c607/Setup/net6.0/macos/buildMacInstaller#L38) the offending sed script?

**Comment by hol353** [comment]
@jbrider Looking at the scripts, I think the compile, run, create installations all happen in the single 'oldapsim' jenkins step. I don't think 'oldapsim-release' ever ran. We'll find out I guess when (if) someone raises a PR for APSIM 7.10.

**Comment by peter-devoil** [comment]
@hol353 see if that PR makes it go away. I'm only guessing what else may be using apsim.server.

**Comment by par456** [comment]
Release builds are building again.
