### ISSUE TITLE
Manager editing buglets

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#8476]
### What happened?

\<ctrl>-T doesnt test the script compilation (for errors) any more

\<ctrl>-S (save) changes insertion to [0,0] and moves view to origin

Clicking on / off the component resets the view to origin (editing position isnt preserved)

Weird stuff happens when errors are present and the component is copied/duplicated (may be related to https://github.com/APSIMInitiative/ApsimX/pull/8458)

### What Operating System are you on?

Linux

**Comment by par456** [comment]
Ctrl - T is still compiling the script on my end, so I'm not sure what's happening there.

The manager resetting to parameters page whenever you save or click off is a known bug that annoys me as well, we'll look into a solution.

I tried to move-copy a node and the GUI didn't do it (which is a bug). I then tried to copy-paste the node and it didn't do anything, however after reloading the file the copies did show up. So there are two bugs here to fix.

**Comment by peter-devoil** [comment]
Ah. \<ctrl>-T doesn't work if you've got a manager in the root of the simulation, but it does when it's in a zone/field/paddock.

![image](https://github.com/APSIMInitiative/ApsimX/assets/1924386/517779e4-ca24-4340-84cb-2cefecfae98e)

**Comment by hol353** [comment]
Ctrl-T seems to work for me on this branch. When I click away and come back it goes straight back to 'Script' tab (which is good) but it doesn't go back to the previous editing position (which is bad).

**Comment by hol353** [comment]
Sorry above comment should be on the PR, not this branch.

**Comment by peter-devoil** [comment]
Some collected notes / irritants  using the manager

a). misbehaviour when errors present:
 1. go to the script editor and type some garbage that will cause an error
 2. copy the manager component to clipboard
 3. paste it somwehere. It appears to be invisible, as an error is displayed in the status window from a module called (eg) "Manager**1**"

b) It often tries to compile any disabled manager script that shouldnt be in the simulation

c) If the property presenter is displaying a long list of manager parameters, one must scroll down to the ones at the end. When a parameter at the end is changed (ie click off the entry), the focus resets to the top of the page.

d) Jumping inserting point: 
1. Open a big script
2. start typing somewhere immediately
3. after a while, the background compilation will finish and the insertion point will jump to (0,0)

e) Run button doesnt use what is in front of you
1. make some changes to any manager code
2. press run button (ie don't click anywhere else)
3. apsim runs without your changes
4. click anywhere off the manager component, and press the run button again
5. your changes are used!

f) weirdness when changing parameter variables: When a new parameter is made, or an existing one has its name changed to something else, then switching to the Parameters tab doesnt reflect the most recent list of parameters. Clicking off and on the manager component will refresh the list.

g) similar to (e) if a parameter value is changed, and the run button is clicked without clicking something else first, the original value is used

**Comment by par456** [comment]
A few more things I've noticed.

If your script has an error, you cannot click the 'more information' button in summary while it is open

When I hit cntrl-s to save, it doesn't show script error messages, just that it's saved correctly.
