### ISSUE TITLE
Split screen not working

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#8478]
### What happened?

The split screen button doesn't do anything anymore. I'm not sure if this is my dev build only or wider issue that has occurred.  

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Just had a look, it is coming up, but seems to be suffering the same bug that the other panels were in regards to screen resolution and appearing at the edge of the screen.

Until we get a fix merged in, if you put your cursor on the right side of the screen after clicking the button you should be able to drag it back into view. It should keep its position after that.

**Comment by lie112** [comment]
Found it after many click and drags. Happy to add this to the other issues and close.

**Comment by par456** [comment]
Leave this one open, I'll do a PR on it since I think the others have been closed.
