### ISSUE TITLE
Export to excel crashing

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#848]
The file Overseertest.apsimx can be cloned from:
https://github.com/PlantandFoodResearch/Overseer-testing

this file throws the following error when all simulations are run and attempted to export to Excel.  We have tried this on two seperate computers and get the same error on both.
![image](https://cloud.githubusercontent.com/assets/7295858/15378192/6dad6a1a-1db5-11e6-81f5-3c0ff9ec7537.png)

**Comment by zur003** [comment]
Github doesn't seem to know about that repository.

**Comment by cla473** [comment]
Hi Eric,

Not sure how I sort that out, but here is a sample excel met data file.  This is four sheets, that should all be in the correct format.

Let me know if you have any issues with these.

Regards,

Loretta Clancy
Software Developer | CSIRO Agriculture
Qld Biosciences Precinct, 306 Carmody Road, St Lucia  Qld  4067 | Ph:  (07) 3214 2609

**Comment by hol353** [comment]
Hamish, the repo you posted above is OK but I can't run your sims because of issue #851. Can you send me the .db file?

**Comment by hol353** [comment]
OK, it is running out of memory (which we knew). Going to Release|AnyCPU (64bit) for all our projects will probably fix the issue but...

The build configurations are screwed so this isn't as easy as it should be. Also, we are using sqlite.dll which is a 32bit DLL so we'll have to look at another mechanism for handling SQLITE database. Using something from nuget would be good.

For now Hamish, I suggest you use an external tool like DbBrowser for SQLite and do an export to csv. It can be downloaded from: http://sqlitebrowser.org/

**Comment by HamishBrownPFR** [comment]
Thanks Dean.

I have a phyton script that I can set Edith up with to extract the data in the short term.  We will progress with that solution.

Thanks,

Hamish
