### ISSUE TITLE
Option to disable writing message into db file

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#8480]
### Describe the new feature

I have an apsimx file with 84 canola simulations from 1957 to 2022. The runtime of this file is doubled when I run it from laptop to HPC (i.e. petrichor). Then I noticed the db file size is about 104 MB with lots of messages. 

Here is the performance test on three computers with

* master branch
* no message comment out `storage?.Writer?.WriteTable(table, false);` on Summary.cs

| System | Setup                          | db size                | single thread runtime (s) |
| ------------- | ------------- | ------------- | ------------- | 
|Windows 11 Laptop |APSIM Master| 103 MB               |             515|
|Windows Server 2016 |APSIM Master| 103 MB               |             321|
|Linux Petrichor computing node |APSIM Master| 104 MB               |             684|
|Windows 11 Laptop |No message| 1.43 MB                 |                   364|
|Windows Server 2016 |No message| 1.43 MB                 |                   326|
|Linux Petrichor computing node |No message  | 1.50 MB                 | 300|

In a summary, the `_Messages` table in db file increases file size about 102 MB and runtime about 300 s. It is much worse in case of high I/O  of NFS (e.g. it takes at least one hour for same simulations in a shared VM).

It is not necessary to have messages in the long term simulations, especially in the command line mode.

Could I suggest adding an argument to disable all messages wrote into _Messages table?

**Comment by byzheng** [comment]
Thanks @par456, I believe the performance is related with I/O of db file, especially in the shared cluster.

It would be more efficient if we could cache more data in memory and then reduce frequency of writing in the database.

**Comment by hol353** [comment]
I think you can already do this. If you go to the summary node in the GUI you can change the level of reporting to be written to the summary table in the db. If you change it to 'Error' then only errors will be reported. Then when you run APSIM (from command line or anywhere else) it will not create huge summary tables.

**Comment by byzheng** [comment]
Thanks @hol353, It works for me.

**Comment by byzheng** [comment]
Following on this issue, could we add an argument in the command line to disable simulation log or specify a log level? e.g. 

```
Models.exe --log "Error"
```

In general, we don't need to store any logs to run an apsimx file in the command line, but might be interesting to check in the GUI.
