### ISSUE TITLE
Parsing of config file when using --apply needs to be smarter

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#8489]
### What happened?

My config file has a line like:
```
[N].Specification = [Fertilise at sowing].Script.Amount = 0 to 200 step 20
```
where N is the name of an Experiment Factor. I want to set the Specification of the factor to a string that contains an equals sign. The equals sign gets stripped so that the specification becomes.
```
[Fertilise at sowing].Script.Amount 0 to 200 step 20
```

When I run APSIM it bombs with an Exception.

[test.zip](https://github.com/APSIMInitiative/ApsimX/files/13594932/test.zip)

### What Operating System are you on?

Windows

**Comment by peter-devoil** [comment]
strings with "//" inside (eg tcp://a.b.c.d/) are similarly mangled

**Comment by ric394** [comment]
> strings with "//" inside (eg tcp://a.b.c.d/) are similarly mangled

@peter-devoil do you have an example command of the above?

**Comment by peter-devoil** [comment]
in [this manager script](https://github.com/APSIMInitiative/ApsimX/blob/d00a86fce15084a93688c5c195c15dac153964d3/Tests/Simulation/ZMQ-Sync/ZMQ-sync.apsimx#L1059),  identifier is passed in from a controlling process [here](https://github.com/APSIMInitiative/ApsimX/blob/d00a86fce15084a93688c5c195c15dac153964d3/APSIM.Server/ZMQ%2Bmsgpack/InteractiveCommunicationProtocol.cs#L42). Not hard to see the workaround, but still..
