### ISSUE TITLE
SimpleGrazing needs a "WasGrazedToday' event

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8490]
### Describe the new feature

There is a Grazed event but that is part way through the day and if used for reporting does not produce the hoped-for outputs. This new event would be triggered at the end of the day instead. Val to discuss with Dean.

**Comment by hol353** [comment]
There is already a true/false variable called 'GrazedToday'. You can use this in the report frequency box:
```
[SimpleGrazing].GrazedToday == true
```

**Comment by sno036** [comment]
Thanks - that will do the trick
