### ISSUE TITLE
Error in the way phenology sets Emerged

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8496]
### What happened?

When phenology increments phase, the first thing it does should be increment the phase index.   Currently it determines if the crop is emerged based on current phase (which is actually the old phase because we have not incremented the currentPhaseIndex yet.  
The result is the Emerged property is one behind where it should be.  We have worked round this error by setting IsEmerged to true on the Emerging phase for all our models which is not correct.  We need to move the setting of currentPhaseIndex to the top of the while loop as shown below and then go through all our models and change the IsEmerged on the Emerging phase of all our models from true to false.
![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/b8961c63-bd84-42e5-aa57-24b18a215e00)

### What Operating System are you on?

Windows

**Comment by BrianCollinss** [comment]
Hi Hamish. Do you think [this](https://github.com/APSIMInitiative/ApsimX/issues/8510) is related?

**Comment by par456** [comment]
Do you have a file that causes this to happen Hamish? It doesn't consistently happen.

**Comment by HamishBrownPFR** [comment]
Hmm.  I wonder if I have mis-diagnosed this.  I would have thought it would happen in all models using PMF phenology.cs
