### ISSUE TITLE
New Sesame (Sesamum indicum) Model

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8498]
### Describe the new feature

As part of an AgriFutures research project, a new sesame module (largely derived from mungbean and canola) is being developed at UniSQ using the Plant Modelling Framework of Brown et al (2014). 

_More information will be soon provided regarding the parameterisation and validation data._
**Contact:** Brian Collins (brian.collins@unisq.edu.au, @BrianCollinss).

**Comment by hol353** [comment]
Is this the same as #7759? We only want one GitHub issue on sesame.

**Comment by BrianCollinss** [comment]
@hol353 Thanks Dean. I did not know that Ando had opened an issue before.
