### ISSUE TITLE
Seed shattering

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8509]
### What is your question?

I need to simulate seed shattering in sesame. From what I see in the code, the ReproductiveOgran does not implement senescence and detachment. What do you recommend is the best approach to simulating seed shattering?

**Comment by hut104** [comment]
I would check whether you really need to simulate this process.  Even if so, I'd suggest that you wait until the rest of the model is functional before worrying about this process.
Just a suggestion.
________________________________
From: Brian Collins ***@***.***>
Sent: Monday, 18 December 2023 9:59 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Seed shattering (Issue #8509)


What is your question?

I need to simulate seed shattering in sesame. From what I see in the code, the ReproductiveOgran does not implement senescence and detachment. What do you recommend is the best approach to simulating seed shattering?

**Comment by BrianCollinss** [comment]
Thanks, Neil. I am collecting information on all aspects of the model. Do you have a recommendation as to the best approach to implementing seed shattering?
