### ISSUE TITLE
Using Excel files for met data input not working

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#851]
Although #16 has been closed, it appears that reading met data from .xlsx files is not working correctly. You get a message like "The excel Sheet Sheet1 is not in a recognised Weather file format.Exception of type 'System.Exception' was thrown."

**Comment by cla473** [comment]
Hi Eric,
The error message you received is a deliberate message when the format of the file is not correct.  I have attached a sample excel file which contains multiple sheets in the correct format.
[MetData.xlsx](https://github.com/APSIMInitiative/ApsimX/files/276824/MetData.xlsx)

Please let me know if you are still getting issues.

**Comment by hol353** [comment]
I'm getting an "Object reference not set..." error when I click on any weather component. e,g,

![image](https://cloud.githubusercontent.com/assets/1943827/15486422/ea26ff44-2188-11e6-83b7-6f7b0a9005ac.png)

**Comment by zur003** [comment]
I've submitted a patch to APSIM.Shared that should cope with either the old or new formats.
