### ISSUE TITLE
EventNamesOnGraph's vertical lines are drawn at incorrect places?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8510]
### What happened?

**It seems the "CurrentStageName" column has a 1-day lag relative to "AccumulatedTT"**. For example, while EndPodDevelopment was reached on December 14, the maximum shell weight was reached on December 13.

I noticed that sometimes the event lines/markers seem to have been drawn at incorrect places (see the gap between vertical lines and the LAI or shell WT lines):

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/b7bb5203-cc15-4dbe-b603-3cc5ef66773d)
![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/4e1b13d4-6c3d-4769-b7f6-aa4c3944cbe3)

And sometimes it seems fine:
![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/d5845d91-7a21-4101-a6d1-727465cf4729)

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
This will be fixed by #8496.
