### ISSUE TITLE
Matching observed harvest data with data in daily report

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8515]
### What is your question?

I have set up my observations this way:

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/d3b817f2-70a0-42e7-8523-cba929c59ac2)

When I use the PredictedObserved table to match the observations and predictions to generate X:Y scatter plots to display DaysAfterSowing, it works fine. But when I to the same for GrainWt, I keep getting this warning:

```
AboveGroundWt: X Axis values contain NaN values.
AboveGroundWt: X Axis values contain NaN values.
AboveGroundWt: X Axis values contain NaN values.
AboveGroundWt: X Axis values contain NaN values.
AboveGroundWt: 4 points are outside of the provided graph axis. Adjust the minimums and maximums for the axis, or clear them to have them autocalculate and show everything.
```

Should I assume that cells with empty values are the reason?

**Comment by par456** [comment]
The value "null" is normally used for an empty cell, and that should be handled without creating NaN values.

Since you are working with predicted/observed data, are the NaNs coming from your predicted data or the observed data?

**Comment by BrianCollinss** [comment]
As can be seen in the screenshot I attached, NaNs are from observed data.

**Comment by par456** [comment]
Ideally, you'd just want to graph the rows that have data in them and ignore the rows with empty values in those fields. Does the graph show anything at the moment? If not I'll have to dig into why this is breaking instead of just providing a warning.

**Comment by BrianCollinss** [comment]
Yes it does show the data. But it seems it is unhappy with the empty cells in the observed data,

**Comment by par456** [comment]
Thanks, that helps, I'll look into it. 

Those should be treated as nulls and not try to be drawn, but at some point they have become NaNs. I'll see if I can replicate it and fix it.
