### ISSUE TITLE
More helpful error messages

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#8516]
### Describe the new feature

We have the following messages when there are issues with graphs (see below).  I suggest some changes.

1) It is not clear which graph is involved if you get this error when you click on a folder of graphs.  I suggest adding the graph name to the message.
2) If you click on each graph with issues like this within a graph folder, the errors accumulate in the error list, making it harder to know what message is for which graph.  Messages just keep being added, and are often repeats of the previous messages, but it is not clear that they are the same message.  Perhaps clear the list when a different node is selected or something so that the list is updated.

-----------------------------------------
LAI: Y Axis values contain NaN values.
LAI: 2 points are outside of the provided graph axis. Adjust the minimums and maximums for the axis, or clear them to have them autocalculate and show everything.
LAI: Y Axis values contain NaN values.
LAI: 2 points are outside of the provided graph axis. Adjust the minimums and maximums for the axis, or clear them to have them autocalculate and show everything.
Mainstem nodes: Y Axis values contain NaN values.
Height: Y Axis values contain NaN values.
LAI: Y Axis values contain NaN values.
LAI: 2 points are outside of the provided graph axis. Adjust the minimums and maximums for the axis, or clear them to have them autocalculate and show everything.
Mainstem nodes: Y Axis values contain NaN values.
LAI: Y Axis values contain NaN values.
LAI: 2 points are outside of the provided graph axis. Adjust the minimums and maximums for the axis, or clear them to have them autocalculate and show everything.
Mainstem nodes: Y Axis values contain NaN values.
Height: Y Axis values contain NaN values.

**Comment by jbrider** [comment]
From a user perspective, adding lines of text at the bottom of the screen is less than useful - especially when the list gets long.
It would be more useful to have links in the message that took you to the corresponding graph with the error.
Overlaying a red exclamation/stop icon to to the graph node would also allow the user to more quickly find offending graphs.
This could also allow for multiple levels of issues - not working being red, points outside the graphing view being a warning etc...
Having a quick right click option to reset the graph axis would make this easier to fix quickly.
