### ISSUE TITLE
About adding a new soybean cultivar to ApsimX

### ISSUE THREAD

**Issue by ankanasadhu** [APSIMInitiative/ApsimX#8517]
### What is your question?

We are trying to add a new soybean cultivar, JS335 to ApsimX as given in [https://doi.org/10.1016/j.agee.2012.02.013](url).

We are not able to find the corresponding names of the following parameters:

Emergence: end of juvenile      TT_EMERG_TO_ENDJUV 
End of juvenile: floral initiation TT_ENDJUV_TO_INIT 
Floral initiation: flowering         TT_INIT_TO_FLOWER 
Flowering: start grain filling       TT_FLOWER_TO_SATRT_GRAIN
Start grain filling: end grain       TT_START_TO_END_GRAIN 
End grain: maturity                     TT_END_GRAIN_TO_MATURITY
Maturity: harvest ripe                 TT_MATURITY_TO_RIPE 

Radiation use efficiency                         RUE 
Transpiration use efficiency coefficient TRANSP_EFF_CF 
Soybean water lower limit                     LL 
Rate of soil water extraction                  KL

**Comment by BrianCollinss** [comment]
The parameters you mentioned belong to the APSIM Classic. You should find out whether equivalent parameters exists in NextGen. You can right click on Sorghum object in your simulation and make model structure visible, then investigate the parameters' names.

**Comment by ankanasadhu** [comment]
Thanks for the help!
