### ISSUE TITLE
Row order in DataStore

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8519]
### What happened?

When there are multiple factorial simulations. data in DataStore is messy. As can be seen in the following example, the data is presented for the 2016 experiment ordered by date, then it is cut on day 220 and data for the 2015 experiment starts. Should we be able to sort the data by clicking on the column names?

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/1a8a3880-ae23-42c7-9a68-3ca58932a338)

### What Operating System are you on?

Windows

**Comment by lie112** [comment]
I think this is somewhat related to #6923 and has been raised in another previous issue I can't locate.
I believe it results from experiments being multithreaded and there is no way of determining the order in which each CPU thread will write to the single database. 
The only solution will be to order the database before display in UI. This could be achieved with an additional order in the SQL statement, but it's not known whether looking at a single run or an experiment where there might be multiple columns that need to be ordered by nesting.  Filtering by the simulation you are interested in will order the results for that simulation by date.
This issue also causes problems when trying to plot results.

**Comment by BrianCollinss** [comment]
Can we just have the ability to order columns manually?

**Comment by hol353** [comment]
New feature: allow sorting of column(s) in the screenshot above. Will need the ability to sort by multiple columns e.g. by SimulationName and then Clock.Today.
