### ISSUE TITLE
Soil profile download failed

### ISSUE THREAD

**Issue by ankanasadhu** [APSIMInitiative/ApsimX#8521]
### What happened?

The following error keeps on popping:
"Error in open.connection(con, "rb") : 
  cannot open the connection to 'https://rest.isric.org/soilgrids/v2.0/properties/query?lon=75.6673785921665&lat=23.3321620920167&property=bdod&property=soc&property=phh2o&property=clay&property=sand&property=nitrogen&property=cec&depth=0-5cm&depth=0-30cm&depth=5-15cm&depth=15-30cm&depth=30-60cm&depth=60-100cm&depth=100-200cm&value=mean'
In addition: Warning message:
In open.connection(con, "rb") :
  URL 'https://rest.isric.org/soilgrids/v2.0/properties/query?lon=75.6673785921665&lat=23.3321620920167&property=bdod&property=soc&property=phh2o&property=clay&property=sand&property=nitrogen&property=cec&depth=0-5cm&depth=0-30cm&depth=5-15cm&depth=15-30cm&depth=30-60cm&depth=60-100cm&depth=100-200cm&value=mean': Timeout of 60 seconds was reached"
  
  I understand rest.isirc.org is presently unservisable. But how do I resolve it since this is an inbuilt url for the function get_isric_soil_profile in apsimx?

### What Operating System are you on?

Windows

**Comment by LenLon** [comment]
This might be a problem with the apsimx R package, not APSIM NextGen.

**Comment by ric394** [comment]
As this an issue with ISRIC, I'll close this issue.

**Comment by sme016** [comment]
There seems to be a similar issue going on again. When 'Download Soil' is requested within the GUI for a country other than Australia or New Zealand, one soil per country or none are found. For example, requesting a soil with 100 km radius of Bonn, Germany, of Kigali, Rwanda, or of Cali, Colombia. Searches within Australia or New Zealand seem to be ok.
