### ISSUE TITLE
[Canola].Flowering event doesn't work in reporting aggregations.

### ISSUE THREAD

**Issue by hedycau** [APSIMInitiative/ApsimX#8523]
### What happened?

Some examples,
Sum of [Weather].Rain from [Canola].Sowing to [Canola].Flowering will sum up the rainfall from sowing to harvesting.
Sum of [Weather].Rain from [Canola].Flowering to [Canola].Harvesting will give a constant number for every season.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
Canola uses StartFlowering in place of Flowering. This is why the Report outputs odd values.
At this stage using StartFlowering will not work either as it's not setup for this event.
This is also the case for other Plant models and will have to be addressed in the future.
