### ISSUE TITLE
Cannot save the file. Error getting value from 'InitialPAWmm' on 'Models.Soils.Water'.

### ISSUE THREAD

**Issue by jsenriquez21** [APSIMInitiative/ApsimX#8531]
### What happened?

Greetings! I encounter this error message when I try to run simulations and even in closing the application if I use the potato model example:

Cannot save the file. Error:  --> Error getting value from 'InitialPAWmm' on 'Models.Soils.Water'. --> Object reference not set to an instance of an object.

All the other examples (Wheat, Maize, etc) are running properly so far. Also, I can't close the application if I use this potato file and would need to use task manager to close it. 

Thank you very much!

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@jsenriquez21 What version of apsimx are you currently running? If you are on a version less than 7322 could I suggest upgrading and trying the simulation again.
If you are on a version greater than 7322 could I please have a copy of your apsimx file with met file included please?

**Comment by jsenriquez21** [comment]
@ric394 Greetings! Apologies for the delayed response. When I got the error, I just used the default met file and soil profile. I also used the latest version of APSIMX as well. However, I managed to work around the problem. 

Thank you for the fast response!
