### ISSUE TITLE
Changing InitialPAWmm is not possible 

### ISSUE THREAD

**Issue by LenLon** [APSIMInitiative/ApsimX#8537]
### What happened?

Hello everyone,

I am currently trying to automate replacing soil profiles, and have run into an issue with the Water node in the Soils model. I want to change the initial soil water content for my soil, but editing the `Simulations.Simulation.Field.Soil.Water.InitialPAWmm` in the .apsimx file does NOT change the value in the GUI (which I am assuming is the PAW (mm) field). If I change the value in the GUI, the graph or Percent full field does not update, and if I click on another node and then back on Water, it is changed to "NaN" for both the PAW and the Percent Full, leading to errors when trying to run the sim (as Soil water in all layers is now 0). 

I can only change initial soil water contents by modifying the Percent Full field, which then also updates the PAW (mm) field. The kicker: There is NO Percent Full variable parameter in the .apsimx file at all? So I am a bit confused as to how one should handle this, as changing the Percent Full would be a great and easy way to adjust initial soil water (typically assumed to be 50% on my end when there is no data or for spinup protocols) but seems currently impossible from command line (or using the apsimx R package), and changing InitialPAW is seemingly bugged.

This might be related to this issue: #8531 

### What Operating System are you on?

Windows

### ApsimX Version I am using

2023.11.7349

**Comment by BrianCollinss** [comment]
Does "Simulations.Simulation.Field.Soil.Water.InitialPAWmm" even exist? I might be wrong, but I remember a time that nextgen couldn't use the initial SW parameter the way Classic could and we had to modify the values of each layer. If that's still the case, then GUI only facilitates that modification and the value in that textbox isn't linked to anything in the file.

**Comment by LenLon** [comment]
For me it's written at around line 480 in my .apsimx file:

![grafik](https://github.com/APSIMInitiative/ApsimX/assets/118363045/272fa3d1-f6cc-42ab-92a7-cc07ba5ac271)

If I change it in the GUI by modifying the Percent full field, it does update as well in the .apsimx file. If I change it in the .apsimx file, it does not change in the GUI. So maybe it is a read-only property, but from the GUI??

**Comment by BrianCollinss** [comment]
Do you close and re-open the GUI after any chance in the file?

**Comment by BrianCollinss** [comment]
I checked the code and it was not read-only.

**Comment by ric394** [comment]
InitialPAWmm is a generated value. The Physical and Water nodes need to be linked, this does not occur until the simulation models are loaded and the linking system has linked them.
I agree that it would be handy to do this via command line, I'll have to think this through.

**Comment by LenLon** [comment]
> Do you close and re-open the GUI after any chance in the file?

Yes - when I change the InitialPAWmm in the file and close and reopen the GUI, the GUI reflects no change either, which might be due to the simulation models not having loaded before running a sim? 

@ric394 : Glad to hear it's being considered. Changing the Percent Full parameter from command line would make initialising large simulations so much easier and user-friendly! :)

**Comment by ric394** [comment]
@LenLon using the command line it's possible to update the initialValues/InitialPAWmm by changing the FractionFull property. 
To do this use the ```--apply``` switch functionality. 
In your config file include these two commands: 
```[Water].FractionFull=0.5```
```save $nameOfFileToSaveChangesTo>```
I'll include an example apsimx file with config file below.
[8537CommandLineWaterPercentFull.zip](https://github.com/APSIMInitiative/ApsimX/files/13915492/8537CommandLineWaterPercentFull.zip)

**Comment by LenLon** [comment]
@ric394 So what this does is open my Apsim file, change the FractionFull field to 0.5, and close my simulation? I'm wondering where this FractionFull value is coming from, because it is not saved anywhere in the Apsim file itself. Is that also the reason why the `--edit` switch will not work, because their is no path to that node/value in the Apsim file?

I'm assuming the code for the command line is then as follows:

`/path/to/Models.exe <PathToApsimXFile> --apply <PathToConfigFile>`

**Comment by BrianCollinss** [comment]
Hey @ric394, is there a way to make config commands (or blocks of command) run in parallel?

**Comment by ric394** [comment]
> Hey @ric394, is there a way to make config commands (or blocks of command) run in parallel? 

At the moment all commands are run one at a time. Having the commands or groups of commands run in parallel is a great idea. I think at some point in the near future this is going to have to be added.
