### ISSUE TITLE
--list-referenced-filenames always lists filenames as absolute paths

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8538]
### Describe the new feature

Sometimes I need to list the referenced files and replace their path with their basic names. However,

**Comment by ric394** [comment]
Are you looking for an option to get referenced filenames or are you looking for an option to get the relative paths of the referenced files?

**Comment by BrianCollinss** [comment]
Am option to get the paths as they are mentioned in the file. Relatives be relatives and absolutes be absolutes.
