### ISSUE TITLE
Models.exe @FileWithListOfSimulations

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8539]
### What is your question?

In Classic we could use the following command to run simulations listed in a file:

`Apsim.exe @FileWithListOfSimulations`

Is there an equivalent in NextGen?

**Comment by par456** [comment]
We have a Playlist node that can be attached to a Simulations, in which you can input a list of simulation names. Then when it's run, only those simulations are run.
