### ISSUE TITLE
Grid view for CSV files

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8541]
### Describe the new feature

A new simple crop modelling approach I am developing holds the parameters for crops in a CSV with each column representing a different crop (parameterisation) and each row representing a different parameter.
It would be really useful to have a grid view that is able to read the contents of this csv so they can be viewed while running the model.  The problem with just opening the csv to look at them is it causes a file clash error when you try to run the model if the file is open so you find you are forever opening and closing the file.  
I have attached a copy of the file that the model reads that I would like to have a grid view to work with.
[CropParameters.csv](https://github.com/APSIMInitiative/ApsimX/files/13910749/CropParameters.csv)

**Comment by BrianCollinss** [comment]
@HamishBrownPFR NotePad++ won't cause any trouble if the file is open. In case you don't need the data/file open in an Excel sheet.

**Comment by par456** [comment]
This is a very basic implementation for using the grid view in that way, you should be able to adapt this for what you are trying to do. Would need some more polish before it goes into apsim proper, so feel free to change it for your needs.

[CSVFile.zip](https://github.com/APSIMInitiative/ApsimX/files/13914897/CSVFile.zip)

**Comment by HamishBrownPFR** [comment]
> @HamishBrownPFR NotePad++ won't cause any trouble if the file is open. In case you don't need the data/file open in an Excel sheet.

That is true but you don't get grid lay out which makes editing the file error prone.

**Comment by HamishBrownPFR** [comment]
> This is a very basic implementation for using the grid view in that way, you should be able to adapt this for what you are trying to do. Would need some more polish before it goes into apsim proper, so feel free to change it for your needs.
> 
> [CSVFile.zip](https://github.com/APSIMInitiative/ApsimX/files/13914897/CSVFile.zip)

Thanks @par456.  I will have a go and let you know how I get on.  Once something is operational I will get you to review and tidy up before going into release.

**Comment by HamishBrownPFR** [comment]
Hi @par456.  I have taken the compents you provided, moved them into ApsimX\Models\PMF\SimplePlantModels\DEROPAPY.cs and made further refinements to get it working how I wanted.  Thanks for the leg up here, I would not have been able to work out the pattern without that.  
I still have this out on a branch which is a bit of a mess as it has to much stuff on it.  I will let you know when I have a pull request ready so you can review what I have done and suggest further improvements.

**Comment by par456** [comment]
I'll close this off
