### ISSUE TITLE
Attaching a residue type to APSIMX file

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8542]
### What is your question?

Is there a way to attach (e.g., under Replacements) a custom residue type that does not exist in Resources/SurfaceOrganicMatter.json to an APSIMX file so it can run anywhere without needing to copy the modified SurfaceOrganicMatter.json to the Resources folder?

**Comment by ric394** [comment]
At the moment we do not have a way to add custom residue types other than the method you described.

**Comment by BrianCollinss** [comment]
Ta.
