### ISSUE TITLE
Water Presenter 'Filled from top?' checkbox not working correctly

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#8543]
### What happened?

as above.

Selecting the checkbox has no affect on graph or figures.

### What Operating System are you on?

Windows

**Comment by BrianCollinss** [comment]
It works when it is checked, but does not work when it is unchecked.

Another potential issue is "Depth of wet soil". I am unsure whether wetness refers to moisture being above DUL. But if that is the case, GUI shows weird values when "Filled from top" is unchecked.

**Comment by ric394** [comment]
This whole UI is in need of fixing. There may be other problems in need of fixing here.
