### ISSUE TITLE
Factors vs config file for large simulations

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8547]
### What is your question?

To run a large ensemble of simulations with NextGen, I usually tend to use factors. However, that cannot be the case when soils need to be downloaded on the fly or added via the command line. As running Models.exe with a config file does not run the simulations in parallel, I am keen to seek advice on the best approach to doing this sort of simulations: (1) downloading the soils, creating the factorial experiments beforehand, and running the file, OR (2) downloading the soils, and somehow running the Models.exe with a config file but in parallel.

**Comment by hol353** [comment]
I always do as much as possible on each individual execute node (which run in parallel). I use Microsoft Azure but HPC or other compute providers will work as well.

Each node will run this workflow (which can be a script) for each grid point.:

* Get weather data for grid point
* Get soil data for grid point
* Create a command.txt (config) file to pass to APSIM. The templated version of command.txt looks like this:

```
[Soil] = GSGApsoilAdjusted.apsimx;[$SoilID]
[Weather].FileName=$Latitude:f4_$Longitude:f4.met
run
```

* Call: Models.exe --apply command.txt --csv    This will run APSIM by applying command.txt and write outputs to .csv files (easier that .db)
* Do a bunch of post simulation stuff to the .csv file.
* Store the .csv file on cloud storage. This will append all .csv files automatically. Azure does this bit automatically which is nice.

If you download all the weather and soils up front it will be too slow and will probably take longer than running APSIM.

**Comment by ric394** [comment]
@BrianCollinss @sno036 or @hol353 may have some experience with a similar use case.

**Comment by BrianCollinss** [comment]
Thanks @hol353. Your approach is a combination of the two and puts most of the load on the HPC instead of the local machine. I'll work on the implementation.

**Comment by LenLon** [comment]
This is exactly what I want to do without the need to use external software! A bit more info on replacing the soils would be highly useful - can you save those as their own files? I have my .met files per grid point ready, just the soils are still an issue.

**Comment by hol353** [comment]
> A bit more info on replacing the soils would be highly useful - can you save those as their own files?

I have all my soils in a file called GSGApsoilAdjusted.apsimx. I then create a 'config' file (command.txt) that looks like this:

```
[Soil] = GSGApsoilAdjusted.apsimx;[123]
[Weather].FileName=dalby.met
run
```

When I call: ```Models.exe --apply command.txt template.apsimx``` it will 

1. Open template.apsimx
2. Open command.txt and iterate through all lines it finds in the file.
3. For line 1 of command.txt it will find a soil in GSGApsoilAdjusted.apsimx with a name of '123' and use it to replace the soil in template.apsimx
4. For line 2 of command.txt it will set the weather filename to 'dalby.met'
5. For line 3 it will run template.apsimx.

Instead of the run command, you could do a save and it will save the modified template.apsimx to a file.

More information on how apply works can be found here: https://apsimnextgeneration.netlify.app/usage/commandlineusage/

**Comment by BrianCollinss** [comment]
Does APSIM still use N CPUs to run each `apsimx` file when `--apply` command is present? I understand that the `--apply` command itself does not do parallel runs (i.e., multiple lines or blocks of lines at the same time).

**Comment by hol353** [comment]
> Is there a way to automatically populate the soil .apsimx file with the necessary soils?

Not that I know of. If you have the soil data in an .Rdata file then it should be possible to write a R script to pull the data out and write an .apsimx file. Not a quick job though.
