### ISSUE TITLE
Models.exe runs all simulations despite a Playlist being present

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8550]
### What happened?

[Test.zip](https://github.com/APSIMInitiative/ApsimX/files/13957724/Test.zip)

I have a Playlist in which 3 simulations are listed. When I run APSIM via the GUI, only these three are run. However, when I run it via the command line on HPC, it seems it tries to run all 9 simulations existing in the apsimx file. (Note: there is an issue with residue type so the model fails to run, but there are 9 errors instead of 3).

Does it mean Playlist only works in the GUI?

**EIDT: It runs all 9 simulations when I run it on my laptop (which does not have the issue with residue type).**

### What Operating System are you on?

Windows

**Comment by BrianCollinss** [comment]
We already have `expression = "^" + expression + "$";` in the code. Could it be the reason? I also added ^ and $ to my playlist.

**Comment by ric394** [comment]
I'm finding the same thing with a simply 3 simulation file. It was only meant to run Simulation1 and 2.
![image](https://github.com/APSIMInitiative/ApsimX/assets/123442863/5bd157ad-50a3-4caa-80a5-19a9aab2fb67)
I'll investigate this further.
