### ISSUE TITLE
Where does "arrayIndex" come from in "SoilWaterScale"?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8553]
### What is your question?

Some functions, like **SoilWaterScale**, calculate some indexes for each layer of the soil. My question is: when these functions are placed under an organ (like the example below for Root), where does the value of **arrayIndex** (i.e., layer index) come from? In terms of the example here, it seems to refer to the root front layer.

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/9936fdd7-124b-4306-8999-b3b11e9d41f9)
![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/14f9e908-240f-40fd-b098-205050991ad0)

**Comment by hol353** [comment]
arrayIndex will come from the calling code. From memory, I think the root organ calls SoilWaterScale once for each layer of the soil so in that case root will pass arrayIndex (soil layer index) into the function. Because of this you won't be able to call SoilWaterScale from report.

**Comment by BrianCollinss** [comment]
Thanks @hol353. May I please know what you mean by "calling code"? Is it a specific class/method in the code?

**Comment by hol353** [comment]
In your screenshot, SoilWaterScale is placed under WaterFactor so WaterFactor will call SoilWaterScale once for each layer of the soil and pass a value for arrayIndex.

**Comment by BrianCollinss** [comment]
Thanks @hol353. My question is: how does WaterFactor know it needs to pass multiple attayIndex to just one? In this example, WaterFactror is just an interpolation function. Moreover, when I track the values of arrayIndex passed to SoilWaterScale, it starts from zero at the beginning of the simulations and then starts going up, which means it refers to the layer index of the root tip. How does SoilWaterScale or the calling function know it should pass the layerindex of the root tip?

**Comment by hol353** [comment]
All functions always pass an arrayIndex. In most functions it is ignored but in some (SoilWaterScale) it is used. In your screenshot, Root will loop through all layers and pass arrayIndex (layer index) into the RootFrontVelocity multiply function which in turn will call PotentialRootFrontVelocity, passing the arrayIndex along and so on. Eventually SoilWaterScale will receive the arrayIndex that gets passed along and actually use it.

**Comment by BrianCollinss** [comment]
Thanks Dean. Sorry for my massive confusion! What the model needs, eventually, is the value of SoilWaterScale for the last root layer. I debugged the code and it seems SoilWaterScale only gets the array index of the last root layer. This is what I can't get my head around: how does SoilWaterScale only use the index of the last layer, and not all layers?

**Comment by BrianCollinss** [comment]
Thanks Dean! I appreciate your help and patience.

**Comment by hol353** [comment]
No problems. Feel free to close the issue if you're happy.
