### ISSUE TITLE
Conversion of soil with old SoilNitrogen to one with new Nutrient

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#8558]
### What happened?

When opening old simulations in the current version of ApsimX, if the soil node contained SoilNitrogen, and error is generted. Apsim deletes SoilNitrogen but Nutrient is not added. Is this a 'feature' or an issue? Also, the error message created when trying to run the converted simulation is not very useful to most people for identifying the problem. 
Furthermore, if one tries to simply add Nutrient (via right click -> add model), another error appears as it seems not all of its components (pools) comes with it... One has to copy Nutrient from another simulation...

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
Hi @rcichota thanks for reporting this bug.
Do you have a copy of the apsimx file before it's conversion? I believe you may have found a bug with that specific version of the converter that makes that change.

**Comment by rcichota** [comment]
Hi @ric394 
I am adding a simulation that reproduces the issue. It was build using version 2022.9.7805.0. I know that @ed2014 was using a different version (also fairly old) when he noticed this problem in the first place...
[oats_example.zip](https://github.com/APSIMInitiative/ApsimX/files/14002667/oats_example.zip)
