### ISSUE TITLE
Can we move GetWorldModellersSoilsAsync out of ApsimNG/Presenters?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8560]
### Describe the new feature

I assume **GetApsoilSoilsAsync**, **GetASRISSoilsAsync**, and **GetWorldModellersSoilsAsync** are all designed to be called from the GUI. Is there any chance these methods be moved from ApsimNG/Presenters so they can be called (for example from the command line) to download the soil using the coordinates provided (for example, via the command line or from the met file)? This would spare users from lots of out-of-APSIM work to download, store, and pre-process soil data. Currently, the SoilGrids REST API is out of service, so users like me who used to depend on APSIM R package can no longer download their data.

**Comment by LenLon** [comment]
I second this! That would be a GREAT feature :-)

**Comment by LenLon** [comment]
Sure, I'll try and compile what changes I can find tomorrow :)

I recently couldn't even get the old `edit_apsim_replace_soil_profile()` working because of 
`
Error in !missing(soilwat) || !is.na(soil.profile$soilwat) : 
  'length = 18' in coercion to 'logical(1)'
`
and I don't even remember that this function had a soilwat argument you could fill.

**Comment by femiguez** [comment]
@LenLon So you need this feature for APSIM Classic, Next Gen or both? soilwat should be an object of class 'soilwat_parms'. Thanks for reporting this. The approach I'm taking is creating a new argument for 'InitialWater' which will allow you to set those values. Including using the variable for the SoilGrids function

**Comment by LenLon** [comment]
Which feature are we talking about here? Setting InitialWater?

**Comment by BrianCollinss** [comment]
Hey @femiguez. I just tested the SoilGrids API and it is not working. I am working to create a function to extract data from the World Modelleres database. I will be happy to help with the package update.,

**Comment by BrianCollinss** [comment]
I am using this script to download data from the Soil Modellers database. Then I open the APSIM file in the NextGen GUI to convert the soils to NextGen format. Use it at your own risk.

  ```
library(jsonlite)
  library(xml2) 

  folderNode <- read_xml('<folder version="37" creator="Apsim 7.10-r4220" name="Soils"></folder>')
  for (i in 1:nrow(SILOGrid)) {
    x <- xml2::read_xml(sprintf('https://worldmodel.csiro.au/apsimsoil?lon=%s&lat=%s', SILOGrid$Long[i], SILOGrid$Lat[i]))
    x <- xml2::xml_find_all(x, 'Soil')[[1]]
    xml2::xml_set_attr(x, 'name', SILOGrid$GrName[i])
    xml2::xml_add_child(folderNode, x, .copy=F)
  }
  xml2::write_html(folderNode, file=paste0(GridFold,'/SOILGrid.apsim'))
```

**Comment by LenLon** [comment]
That's such a simple script, wow! Thank you very much.

I don't understand some things: 
What is the Soil Modellers database? Does it have an API call limit? :-D
Do I have to adapt the folderNode definition? It works fine on my desktop, but I have no idea which folder it is referring to.
Will it save all soils into one .apsim file? I could then use the apsimx R package to copy these into my active simulation one by one (I hope).

**Comment by femiguez** [comment]
@BrianCollinss That looks great! I'll look into providing a convenient solution using the apsimx package. Do you have any documentation about 'worldmodel.csiro'? The website https://worldmodel.csiro.au doesn't have any.

**Comment by femiguez** [comment]
I started implementing this here
[https://github.com/femiguez/apsimx/blob/9d99d35ef31076c64a550caa48fd6e002c4704e1/R/get_worldmodeler_soil_profile.R](url)
But it consistently results in a pointer exception related to the xml2 package, which is probably a bug.

**Comment by BrianCollinss** [comment]
Sorry I meant "World Modellers". I read somewhere that it's the same as ISRIC with some differences in organic carbon content.

You can certainly replace xml2 with another package. I put soils under a folder as APSIM NextGen cannot convert APSIM Classic soils if they're not under a parent node (see my other github issue on Water node).

 I usually run simulations for a couple of years before the target period (as a warm-up period) so the effect of choosing the initial values is minimal.

**Comment by hol353** [comment]
We (CSIRO) built the 'World Modellers' soil API as part of a large World Modellers project a several years ago. It calls the ISRIC API to fetch soil data and then adds the extra parameters that APSIM needs (e.g. fbiom, finert, cll etc).


There is no API call limit.

**Comment by femiguez** [comment]
@BrianCollinss The function 'get_worldmodeler_soil_profile' in the apsimx package is now exported. It gets a soil and converts it into the 'soil_profile' class. In this way, you can use 'edit_apsimx_replace_soil_profile' and there is no need to go through Classic. The function 'read_apsim_soils' is used to do the conversion from the '.soils' file to the R object.

**Comment by femiguez** [comment]
@BrianCollinss @hol353 The worldmodel.csiro.au API was working well for a while. It does not seem to be working now. I can't find any information about it anywhere else. Do you have any ideas?
