### ISSUE TITLE
If solues are missing, GUI adds solues with wrong depths

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8563]
### What happened?

If Solutes are not present in the soil, when it is copied under the Paddock node, all three solutes are automatically added, but the Depth column is not the same as the physical Depth column.

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/74279b05-3f24-4dde-ac50-7a9075089137)

At least in SoilDownloadPresenter, these depths are meant to be the same as physical depths:

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/1f7e179c-3f5d-49e4-b2cb-a16c19b13a70)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
This is working as intended, the layers in the solute don't have to match the layers in the physical layer. If you want to edit it per layer, you can copy the structure from the physical into the solute.

This is worth addressing though to make it a bit clearer.

**Comment by BrianCollinss** [comment]
The depth is always 1800.
