### ISSUE TITLE
Using modified Apsim plant models in publication work

### ISSUE THREAD

**Issue by LenLon** [APSIMInitiative/ApsimX#8568]
### What is your question?

Hello,

I am currently working on heat stress as a possible crop varietal adaptation under climate change. Considering that heat stress is not implemented in ApsimX's crop models (yet), many users (it seems) make use of the modularity of the PMF in ApsimX to introduce heat stress effects in ApsimX's plant models, either based on other publications or previously implemented approaches in Apsim classic. 

Now that replacements are read-only by default to discourage the implementation of non-validated models for "routine application tasks", I was wondering what the stance is on using these models for scientific impact studies which might end up being peer-reviewed and published? Does the end-user license cover this? I assume it should be made clear in the paper that the plant model has been modified and how, but can you still call it an Apsim study? What would the correct approaches for validation be, considering we are often simulating under projected or counterfactual climates? 

Though this question only indirectly pertains to ApsimX development, I thought discussion around this could be stimulating for everyone. I'm happy to take this to email if better suited.

**Comment by hol353** [comment]
These are great questions. Moving to discussions section (which we're migrating to for these sorts of questions).
