### ISSUE TITLE
Script Parameters no longer keep changes.

### ISSUE THREAD

**Issue by ilhuber** [APSIMInitiative/ApsimX#8569]
### What happened?

It seems like with the current version (2024.01.7346.0) the Parameters tab of a manger script will no longer keep changes. Oddly, changes to the Parameters tab will be kept if the Script tab has been modified.

### What Operating System are you on?

Windows

**Comment by peter-devoil** [comment]
Presumably related, it appears the scroll bars misbehave when very long lines are present (they go to sleep / very sluggish), and the view doesnt follow the insertion caret when the keyboard moves it (pgup/pgdown etc). (on Linux, btw)

**Comment by par456** [comment]
Thanks Peter, Dean was also noting that the pageUp and pagedown aren't working.

I've put in a merge to quickly patch the properties problem, and I'm looking into those other problems that have been found.

**Comment by par456** [comment]
Reopening so a better pull request can be attached to fix other problems.
