### ISSUE TITLE
Change canola grain minimum nitrogen concentration to 0.02

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#8595]
### What happened?

Reduce canola grain minimum nitrogen concentration. The current value is 0.05

### What Operating System are you on?

Windows

**Comment by hol353** [comment]
It improved all stats of all simulations - very rare. From https://apsimdev.apsim.info/APSIM.POStats/8596:

![image](https://github.com/APSIMInitiative/ApsimX/assets/1943827/a1556f13-64d7-4144-a507-dd4fd45239c1)

![image](https://github.com/APSIMInitiative/ApsimX/assets/1943827/c0b5abd3-7116-4917-94e0-a61204c82340)
