### ISSUE TITLE
Compile APSIMX under ubuntu

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#860]
Following the instruction that @zur003 provided, I can compile `Models.exe` using Ubuntu 14.04 now. However I make a few changes of source codes including
- Copy all nuget packages from windows to ubuntu 
- Remove the target `AfterBuild` in the Models.csproj
- On line 59, change “bin” to “Bin” (otherwise the build will go into the wrong directory) in the Models.csproj
- On lines 45 and 63, change the setting for TreatWarningsAsError from “true” to “false” in the Models.csproj
- change the setting for TreatWarningsAsError from “true” to “false” in the ApServer.csproj

**Comment by zur003** [comment]
The TreatWarningsAsError problem is interesting. The Mono C# compiler is reporting a number of warnings that the MS compiler is not (mostly dealing with unused variables). I'm not sure why the MS compiler is not reporting these; it probably should be.

**Comment by zur003** [comment]
As mentioned above, the Mono C# compiler issues warnings for code that the MS compiler does not. In the interest of making compilation under Mono slightly easier, I will submit a series of pull requests which intended to reduce, if not fully eliminate, these warnings.

**Comment by hol353** [comment]
@zur003 Can we close this one?

**Comment by zur003** [comment]
Yes, close it.
