### ISSUE TITLE
TYPE OF INITIAL SURFACE RESIDUE

### ISSUE THREAD

**Issue by Malitoz** [APSIMInitiative/ApsimX#8604]
### What is your question?

Greetings, I would like to conduct a simulation where no SOM was applied. Which option under 'type of initial residue pool' in the SOM node is most suitable for this scenario? Additionally, could you recommend any literature or tutorials for further reading on this topic? 
https://1drv.ms/v/s!ArK9rrVUdFuKgosc54FbJufdk3HowQ?e=JZuMKI

**Comment by BrianCollinss** [comment]
If another roo was harvested before planting the current crop, you can let APSIM know how much residue from that crop was left on the ground.

**Comment by hut104** [comment]
You can use any type, but set amount to zero or a very small number.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Malitoz ***@***.***>
Sent: Friday, February 2, 2024 10:24:45 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] TYPE OF INITIAL SURFACE RESIDUE (Issue #8604)


What is your question?

Greetings, I would like to conduct a simulation where no SOM was applied. Which option under 'type of initial residue pool' in the SOM node is most suitable for this scenario? Additionally, could you recommend any literature or tutorials for further reading on this topic?
https://1drv.ms/v/s!ArK9rrVUdFuKgosc54FbJufdk3HowQ?e=JZuMKI

**Comment by Malitoz** [comment]
Thank you @BrianCollinss & @hut104 for your feedback.
