### ISSUE TITLE
Folder class has public properties, but these are not shown in presenter

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8608]
### Describe the new feature

Folders have two properties, ShowInDocs and GraphsPerPage that seem to be set up to be editable in a propertypresenter in the gui, however the folderpresenter doesn't not implement them to be shown.

These should appear somewhere on the presenter so it can be customised.

**Comment by hol353** [comment]
The right hand side of a Folder shows graphs so we can't use a property presenter. 

ShowInDocs property can be set via the context menu when you right click on a folder. The [Description] decorator on the property isn't needed though so it can be removed.

GraphsPerPage: No one has asked to change the number of graphs on a page. Remove the [Description] decorator and make it private.
