### ISSUE TITLE
Rename CompositeFactor when empty causes error

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#8614]
### What happened?

If you rename a Factorial.CompositeFactor in the tree view before any entries have been provided a null object error is thrown due to Specifications being null in OnModelChanged of CompositeFactorPresenter (line 146).

### What Operating System are you on?

Windows

**Comment by lie112** [comment]
This also relates to trying to disable an empty CompositeFactor and it cannot be disabled.

**Comment by lie112** [comment]
When an empty CompositeFactor exists there is also an error when you click on SummaryFile as it tries to determine the factorial information. I had assumed an empty CompositeFactor would be allowed if one of the treatments was using the base simulation without a parameter change,

**Comment by lie112** [comment]
Don't worry about the need for blank base compositefactor as I can just set a property to the same value as the base simulation, but need to remove the errors when renaming and disabling before factors are provided.

**Comment by lie112** [comment]
I figure it's a better workflow to report these issues and have you guys fix them than for me to fix them and potentially have them lost in my branch commit or have to do a branch switch and commit a change. There's always "simplified" code to remove additional if logic and the attach suggests this doesn't need to be set to the null value anyway.  It would be interesting to discuss whether people consider this easier to read or not.
<factor.Specifications?.ToArray()?? Array.Empty<string>();>

**Comment by par456** [comment]
In my mind that style of shorthand is much harder to read than explicitly stating the checks. It's also harder to tell when something breaks, what part of that line caused the problem.
