### ISSUE TITLE
Undoing a Water model initialValues change causes exception

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#8616]
### What happened?

<img width="1281" alt="image" src="https://github.com/APSIMInitiative/ApsimX/assets/123442863/47b3bbe5-4d2e-4d7a-bfa8-04e24d3d7591">

the column header ("mm") is included in the depth strings array. It needs to be removed.

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Don't happen anymore after #8613
