### ISSUE TITLE
Multiple 'run' commands in a config file

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8617]
### What is your question?

[Files.zip](https://github.com/APSIMInitiative/ApsimX/files/14215979/Files.zip)

I am trying this config file:

```
load Sesame_Job1.apsimx
#=========================================================================
[Soil] = SOILGrid.apsimx;[Grid1]
[Weather].FileName = Met/Grid1.met
save Sesame_Job1_Grid1.apsimx
run
#=========================================================================
[Soil] = SOILGrid.apsimx;[Grid2]
[Weather].FileName = Met/Grid2.met
save Sesame_Job1_Grid2.apsimx
run
```

After I run `Models.exe --apply Config.txt`:

- Sesame_Job1_Grid1.apsimx has Met/Grid2.met in [Weather].FileName.
- Sesame_Job1_Grid2.apsimx has Met/Grid1.met in [Weather].FileName.
- Both apsimx files have SOILGrid.apsimx;[Grid1].
- The daily report shows that both 'apsimx' files used the same weather data!

Questions:
- Why are the met file names incorrect after `save` commands are called?
- Why do both apsimx files have the same soil (Grid1)?
- When `run` is called, which file is run? The temporary apsimx file (which is the modified version of the original file), or the apsimx file that was just saved?
- When a node is replaced, will the new name be the same as the replacing node's name or the replaced node's name?

**Comment by BrianCollinss** [comment]
When I add another load Sesame_Job1.apsimx after the first run, Sesame_Job1_Grid1 will have Grid2 for weather, and Sesame_Job1_Grid2 has the same file as the original apsimx file.

**Comment by ric394** [comment]
I'll investigate and see what I can find @BrianCollinss

**Comment by BrianCollinss** [comment]
Added the files APSIM and input files for your consideration.

**Comment by BrianCollinss** [comment]
Hey Julian. By any chance, have you had time to have a look at this issue? I wonder why it had not been reported before. It seems like a major issue, or I am doing something wrong. Ta

**Comment by ric394** [comment]
@BrianCollinss I've just had a quick look and there seems to indeed be a bug. Good catch! I'll not sure I'll be able to fix this one this week, but I'll arrange to work on it next week.

**Comment by BrianCollinss** [comment]
Thanks @ric394. We look forward to hearing from you as our simulations are on hold. Ta

**Comment by BrianCollinss** [comment]
Hey @ric394. Just checking in on this issue. Looking forward to a resolution so we can continue our simulations. Ta :)

**Comment by ric394** [comment]
@BrianCollinss I'm on this one now.

**Comment by BrianCollinss** [comment]
I hope you answer these as well:

- When run is called, which file is run? The temporary apsimx file (which is the modified version of the original file), or the apsimx file that was just saved?

- When a node is replaced, will the new name be the same as the replacing node's name or the replaced node's name?

**Comment by ric394** [comment]
1. The intended behaviour is to follow what the full version of APSIM does, which is save the changes to the original file then run the original file. However, this is not the case at the moment, but changes in a PR ( #8499 ) will change this.
2. When replacing a node using the override method (commands that use =), the name of the existing node is retained.

**Comment by BrianCollinss** [comment]
> The intended behaviour is to follow what the full version of APSIM does, which is save the changes to the original file then run the original file

Hi @ric394. Just to confirm this: now that I am running my test, I get two .db files named the same as the 'modified' APSIM files that were saved by the save command in the config file. Is this correct?

**Comment by ric394** [comment]
> > The intended behaviour is to follow what the full version of APSIM does, which is save the changes to the original file then run the original file
> 
> Hi @ric394. Just to confirm this: now that I am running my test, I get two .db files named the same as the 'modified' APSIM files that were saved by the save command in the config file. Is this correct?

This is the intended behaviour. Apologises for the poorly worded explanation. This is showing that the two modified files are the only files being run. The original file is not run or modified.
