### ISSUE TITLE
'Nutrient' technical document is empty

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8620]
### What is your question?

- Is the module fundamentally different from APSIM Classic's SoilN?

### More Information
This is all there is about the Nutrient module:

> The soil nutrient model includes functionality for simulating pools of organic matter and mineral nitrogen. The processes for each are described below.

The rest of the document is 'Validation'.

**Comment by par456** [comment]
We'll have to look into why the documentation isn't being written out, but here is what is supposed to be there from the Nutrient class.

> The soil nutrient model includes functionality for simulating pools of organmic matter and mineral nitrogen.  The processes for each are described below.
> Soil organic matter is modelled as a series of discrete organic matter pools which are described in terms of their masses of carbon and nutrients. These pools are initialised according to approaches specific to each pool.  Organic matter pools may have carbon flows, such as a decomposition process, associated to them.  These carbon flows are also specific to each pool, are independantly specified, and are described in each case in the documentation for each organic matter pool below.
> Mineral nutrient pools (e.g. Nitrate, Ammonium, Urea) are described as solutes within the model.  Each pool captures the mass of the nutrient (e.g. N,P) and they may also contain nutrient flows to describe losses or transformations for that particular compound (e.g. denitrification of nitrate, hydrolysis of urea).
> A nutrient pool class is used to encapsulate the carbon and nitrogen within each soil organic matter pool.  Child functions within these classes provide information for initialisation and flows of C and N to other pools, or losses from the system.
> The soil organic matter pools used within the model are described in the following sections in terms of their initialisation and the carbon flows occuring from them.
> The soil mineral nutrient pools used within the model are described in the following sections in terms of their initialisation and the flows occuring from them.

**Comment by BrianCollinss** [comment]
BTW, the components of the Nutrient model are not displayed properly. The panel cannot be Zoomed in or out:
![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/dc2fb347-b80f-4ff4-9356-1bb0ec104f39)
