### ISSUE TITLE
Manager doesn't work in multi-zone simulation if it has not public properties.

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#8624]
### What happened?

In the attached file I have set up a multizone simulation to represent an area of crop under plastic cover and an adjacent fallow area that water is shed to from the covered area.  To do this I have put a weather model in each zone and a manager that modifies Rainfall and wind to zero and increased maxT and VP in the CoveredRow zone and doubled the rainfall in the InterRow zone.

The intended modifications have worked in the example I have uploaded with this issue.  However, I have had to include a superfluous property (highlighted in yellow) for the intended set up to work.  
If you comment that property out the model does not recognize this manager (won't stop on a break point there if you include one) and it uses the weather data from the zone above (i.e. not only does it fail to apply the modification intended for this zone, it brings in the modifications applied to the other zone).

![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/788cf127-d0d8-494c-a53b-9ed5a4512270)

With superfluous property
![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/bf529afd-9e94-46cd-b312-56a11519b990)

With superfluous property commended out
![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/e04ce1fb-5c55-4a08-b835-2c6ab3c602f9)

While this is a simple work around, it should be fixed to avoid future confusion.

[Uploading ManagerBug.zip…]()

### What Operating System are you on?

Windows

**Comment by hut104** [comment]
In the agroforestry simulations we use a local weather object that has weather data pushed to it from some external source (e.g. to have windspeeds reduced in the lee of tree windbreaks).
________________________________
From: Hamish Brown ***@***.***>
Sent: Monday, 12 February 2024 2:21 PM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Manager doesn't work in multi-zone simulation if it has not public properties. (Issue #8624)


What happened?

In the attached file I have set up a multizone simulation to represent an area of crop under plastic cover and an adjacent fallow area that water is shed to from the covered area. To do this I have put a weather model in each zone and a manager that modifies Rainfall and wind to zero and increased maxT and VP in the CoveredRow zone and doubled the rainfall in the InterRow zone.

The intended modifications have worked in the example I have uploaded with this issue. However, I have had to include a superfluous property (highlighted in yellow) for the intended set up to work.
If you comment that property out the model does not recognize this manager (won't stop on a break point there if you include one) and it uses the weather data from the zone above (i.e. not only does it fail to apply the modification intended for this zone, it brings in the modifications applied to the other zone).

image.png (view on web)<https://github.com/APSIMInitiative/ApsimX/assets/7295858/788cf127-d0d8-494c-a53b-9ed5a4512270>

With superfluous property
image.png (view on web)<https://github.com/APSIMInitiative/ApsimX/assets/7295858/bf529afd-9e94-46cd-b312-56a11519b990>

With superfluous property commended out
image.png (view on web)<https://github.com/APSIMInitiative/ApsimX/assets/7295858/e04ce1fb-5c55-4a08-b835-2c6ab3c602f9>

While this is a simple work around, it should be fixed to avoid future confusion.

Uploading ManagerBug.zip…

What Operating System are you on?

Windows

**Comment by HamishBrownPFR** [comment]
Thanks @hut104.  I will take a look at that.  The point of this bug though is that it works with an apparently redundant property in the manager but does not when that redundant property is removed

**Comment by par456** [comment]
Can you attach the file again? It doesn't seem to have uploaded the first time.

**Comment by HamishBrownPFR** [comment]
[Covered Rows example.zip](https://github.com/APSIMInitiative/ApsimX/files/14413099/Covered.Rows.example.zip)

@par456 file should be attached this time.  

Note: the SCRUM crop model in replacements is under active development at the moment.  If the simulation does not run you may need to copy the SCRUM model across from Prototypes/SCRUM/SCRUM.apsim

**Comment by hol353** [comment]
I wonder if this problem is because there are two scripts with the same name (different zones in the same simulation, different contents). Commenting out the property line recompiles the script and then it works again. We'll look into it.
