### ISSUE TITLE
Cannot find a match for link biomassRemovalModel in Canola simulations

### ISSUE THREAD

**Issue by KeLiu7** [APSIMInitiative/ApsimX#8626]
### What happened?

Hi,

I'm trying to run Canola simulations with SWIM3 module but it says "A canopy was found that isn't a plant. Name: EnergyBalance", I then added the EnergyBalance

![image](https://github.com/APSIMInitiative/ApsimX/assets/72141690/426049bf-9290-46d5-bc2b-222ccde4c2a7)

error still exists and says "Cannot find a match for link biomassRemovalModel in model .Canola Example.Zone.Canola.GenericOrgan"

I then put `BiomassRemovalDefaults `under `GenericOrgan` module but the error still exists and says "Cannot find a match for link SenescenceRate in model .Canola Example.Zone.Canola.GenericOrgan". 

I then put `SenescenceRate` into  `GenericOrgan` module, the error says"Cannot find a match for link detachmentRateFunction in model .Canola Example.Zone.Canola.GenericOrgan"

After put `DetachmentRate` into  `GenericOrgan` module,, the error says "Cannot find a match for link detachmentRateFunction in model .Canola Example.Zone.Canola.GenericOrgan". Does anyone could help? I have attached my sims. Many thanks.
![image](https://github.com/APSIMInitiative/ApsimX/assets/72141690/1a10430b-57ed-4c41-9fa1-1e702c88ca0c)
[Canola test.zip](https://github.com/APSIMInitiative/ApsimX/files/14235393/Canola.test.zip)

### What Operating System are you on?

Windows

**Comment by peter-devoil** [comment]
From what I can tell, Canola is using an PMF model/component that is incompatible with swim; but I've no idea how it should be modified. The author is @hut104, perhaps he's got a plan to move it forward

**Comment by KeLiu7** [comment]
> From what I can tell, Canola is using an PMF model/component that is incompatible with swim; but I've no idea how it should be modified. The author is @hut104, perhaps he's got a plan to move it forward

Thanks Peter. Barley and Maize works well with SWIM but not for Canola... Hi, @hut104, could you please help?
