### ISSUE TITLE
Can we have a general stress factor for root N uptake?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8627]
### Where is the code located?

Root.cs

### What needs to be changed?

NUptakeSWFactor

### Why does the code need changing?

According to the documentation:

> In each layer, potential uptake is calculated as the product of the mineral nitrogen in the layer, a factor controlling the rate of extraction  (kNO3 or kNH4), the concentration of N form (ppm), and a soil moisture factor (NUptakeSWFactor) which typically decreases as the soil dries.

I want to have the impact of other stress factors, e.g. PH, accounted for. Currently, the only way I do it is by including it under `NUptakeSWFactor`. Should we change the name of this to NUptakeStressFactor (which could include all stress factors), or add a separate stress factor to the root class?

**Comment by hut104** [comment]
Is this for any particular crop, or all crops?
________________________________
From: Brian Collins ***@***.***>
Sent: Tuesday, 13 February 2024 10:12 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Can we have a general stress factor for root N uptake? (Issue #8627)


Where is the code located?

Root.cs

What needs to be changed?

According to

Why does the code need changing?

According to the documentation:

In each layer, potential uptake is calculated as the product of the mineral nitrogen in the layer, a factor controlling the rate of extraction (kNO3 or kNH4), the concentration of N form (ppm), and a soil moisture factor (NUptakeSWFactor) which typically decreases as the soil dries.

I want to have the impact of other stress factors, e.g. PH, accounted for. Currently, the only way I do it is by including it under NUptakeSWFactor. Should we change the name of this to NUptakeStressFactor (which could include all stress factors), or add a separate stress factor to the root class?

**Comment by BrianCollinss** [comment]
I assume it should be for all crops, as it exists in Root.cs.

**Comment by BrianCollinss** [comment]
May I ask another question here, @hut104? 

When I add this Zero constant under NUptakeSWFactor, I expect the N uptake to be zero. But I still get the same amount of biomass. How is this possible? 

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/ab46b363-479e-4021-9e8c-89edd0cbe700)
