### ISSUE TITLE
ADDING A NEW MAIZE CULTIVAR

### ISSUE THREAD

**Issue by Malitoz** [APSIMInitiative/ApsimX#8633]
### What is your question?

Hello,

Is it possible to add a new maize cultivar in APSIMX? The variety I wish to add is H513 (https://www.smartfarmingug.com/product/h513-maize-seed-variety/)

**Comment by BrianCollinss** [comment]
Have a look at [this](https://github.com/APSIMInitiative/ApsimX/issues/8640).
