### ISSUE TITLE
VALIDATING THE ACCURACY OF APSIM IN SIMULATING MAIZE PHENOLOGY & YIELD

### ISSUE THREAD

**Issue by Malitoz** [APSIMInitiative/ApsimX#8634]
### What is your question?

Is it feasible to utilize different statistical indicators like RMSE, NRMSE, R^2, and Consistency index (D) within the APSIMX interface to assess the accuracy of the model's predictions?

**Comment by BrianCollinss** [comment]
It's best to have a look at one of the Validation datasets (e.g., APSIMNextGen\Tests\Validation\Wheat\Wheat.apsimx) to see how the PredictedObserved data are used along with graphs for validating the model outputs.

**Comment by Malitoz** [comment]
Hello @BrianCollinss,

Graphical validation is ok, but can statistic such as **RMSE** AND **R^2** be done within APSIM? Also, this path (_APSIMNextGen\Tests\Validation\Wheat\Wheat.apsimx_) that you've indicated here is not in APSIMNextGen. Furthermore, kindly verify that the folder "_Tests_" exists. Here's what I have: https://1drv.ms/v/s!ArK9rrVUdFuKgowko588bqmIob0kDA?e=AawwPy

**Comment by BrianCollinss** [comment]
I was referring to the APSIM folder on your computer. If you compare predicted vs observed values using graphs (like those in the validation files) you will see the R2 and other indexes.

**Comment by Malitoz** [comment]
@BrianCollinss , Can you demonstrate in a screen recorder.

**Comment by BrianCollinss** [comment]
You just need to open one of the Validation files and look at observed-vs-predicted graphs.
