### ISSUE TITLE
Can't delete rows from Physical

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8636]
### What happened?

When I try to delete a layer from physical, all the input lines are cleared, but the the calcualted SW line and PAWC line (in the cropsoil) are set to 999999 and the empty cells are left as NaNs and not deleted from the structure. Undoing the delete is also no possible as an exception is thrown.

This causes cascading errors through the soil as the layers still exist, but with NaN or 999999 values which screw everything up.

My workaround for this at the moment is to delete what I can, then to edit the file directly and remove the deleted lines from physical in the json.

### What Operating System are you on?

Windows

**Comment by Malitoz** [comment]
Same here: https://1drv.ms/v/s!ArK9rrVUdFuKgowlh3xqTS_brhYB9A?e=yjYQUS
