### ISSUE TITLE
Crop cultivar file didn't work when I reopens it to change some crop genetic coefficient

### ISSUE THREAD

**Issue by Rizwan3946** [APSIMInitiative/ApsimX#8640]
### What happened?

Hi Folks,
I am facing an issue when I reopen the crop cultivar file to change some genetic coefficients and it didn't work properly for me. I have added it in the replacement folder as well (screenshot attached) but it works only once and afterwards it didn't change any coefficient. 
![2024-02-15 (2)](https://github.com/APSIMInitiative/ApsimX/assets/135749442/cd9be00b-640c-4794-85de-2b2d38fb0e47)
![2024-02-15](https://github.com/APSIMInitiative/ApsimX/assets/135749442/50db6a74-09d4-4455-9f71-3bf2049e4890)

I am attaching the screenshot. Please sort out this issue for me. Thanks. Rizwan

### What Operating System are you on?

Windows

**Comment by BrianCollinss** [comment]
The Maize node in your screenshot seems to be read-only. What do you need to do? Do you want to add a new cultivar?

**Comment by BrianCollinss** [comment]
BTW, it's best to label your questions as "question", unless you're somewhat sure it's a bug.

**Comment by Rizwan3946** [comment]
Brian, I want to add new cultivar or make a copy of existing one during calibration of my local crop cultivar. Actually it work when I add the crop in the replacement folder you seen in picture. But the problem is it only works once and when I try to change something in it again it looks read-only.

Sorry for putting it as bug.

**Comment by BrianCollinss** [comment]
I have never done this, but try removing Maize from Replacements. Instead, just add a Cultivar object (right-click on Replacements and double-click on Cultivar). I assume you can rename this to be the same name as an existing cultivar, and then add/change its parameter values. Or, you can create a new cultivar whose name does not already exist.

**Comment by Rizwan3946** [comment]
Thanks Brian. Its working now.

**Comment by BrianCollinss** [comment]
You're welcome. Feel free to close this issue if you're happy with my answer.

**Comment by Rizwan3946** [comment]
Yes I am closing the issue.
