### ISSUE TITLE
Unable to rename some Plant modules due to hard-coded names in resource JSON files

### ISSUE THREAD

**Issue by kdelwat** [APSIMInitiative/ApsimX#8660]
### What happened?

If I create a simulation containing a `Chickpea` plant, and rename the plant to `CustomChickpea`, I see this exception:

```
ERROR in file: /home/.../simulation.apsimx
Simulation name: Simulation
Models.Core.SimulationException
 ---> System.Exception: Unable to evaluate linear interpolation function .Simulation.51.CustomChickpea.Leaf.ExtinctionCoeff
 ---> System.Exception: Error while locating variable '[Chickpea].SowingData.RowSpacing' in variable reference '.Simulation.51.CustomChickpea.Leaf.ExtinctionCoeff.XValue'
 ---> System.Exception: Unable to find any model with name or type Chickpea in scope of XValue
   at Models.Core.Locator.GetInternal(String namePath, LocatorFlags flags) in /tmp/ApsimX/Models/Core/Locator.cs:line 200
   at Models.Core.Locator.GetObject(String namePath, LocatorFlags flags) in /tmp/ApsimX/Models/Core/Locator.cs:line 86
   at Models.Functions.VariableReference.Value(Int32 arrayIndex) in /tmp/ApsimX/Models/Functions/VariableReference.cs:line 45
```

It appears this is due to the `Models/Resources/Chickpea.json` file having hardcoded references to `[Chickpea]` (e.g. `[Chickpea].SowingData.RowSpacing`).

I noticed some other references in the json file that use `[Plant]` instead (e.g. `[Plant].SowingData.Depth`). If I change the usages of `[Chickpea]` to `[Plant]` in the file and recompile APSIM, my simulation with the renamed module runs correctly.

---

I'm happy to open an MR to fix these hardcoded references in the plant resource files, but I don't have a deep understanding of the APSIM internals so I wanted to check first if this is a valid fix or if I'm missing some subtlety :smile: 

### What Operating System are you on?

Linux

**Comment by BrianCollinss** [comment]
`Chickpea.json` is the 'released' version of the chickpea model. A lot of other modules refer to this (e.g., surface residue). Why do you need to rename the plant?

**Comment by BrianCollinss** [comment]
If you do that, you will need to make some changes in other places as well. 

One solution is to change, for example, [Chickpea].SowingData.RowSpacing to [Plant].SowingData.RowSpacing or [CustomChickpea].SowingData.RowSpacing. You may need to do this in other places under Replacements.

**Comment by BrianCollinss** [comment]
Ahh, I see. you are not using Replacements. You just renamed the plant. That is not going to work.

**Comment by HamishBrownPFR** [comment]
@kdelwat if you are wanting to use chickpea as a start point for building another plant model.... the approach we take for developing prototype models is to take a copy of the chickpea.json, paste it into a replacements folder and rename it there.  
See the prototypes folder for examples of unreleased models that are under various stages of development using this approach

**Comment by kdelwat** [comment]
Ah I understand now - I think the replacements approach is best, thanks for your help :1st_place_medal:
