### ISSUE TITLE
Soybean Leaf.RelativeArea starts at 0.667 instead of 0.0

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8663]
### What is your question?

In Soybean, the **Leaf.DMDemands.Structural.DeltaLAIPotential.Vegetative.Delta.RelativeArea.BeforeEndPod.RelativeArea** starts at 0.667. Does this mean there is some leaf area without any node on the main stem? Should there be one more line in the table (0,0)?

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/bbdc8e81-c8ec-443c-b85b-eb883846b362)

**Comment by hol353** [comment]
Not a defect. Closing...

**Comment by BrianCollinss** [comment]
Adding a (0,0) to the table certainly (slightly) improves the stats.

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/7cfcd90a-3b98-4653-a89b-82fda52765a8)
