### ISSUE TITLE
We need a post simulation tool that creates a profile table from an existing table

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#8667]
### Describe the new feature

This tool would convert a source table like this:
```
/// SOURCE TABLE:
///    Year     Col1(1)  Col1(2)  Col2(1)  Col2(2)
///    1970          10       11       12       13 
///    1971          14       15       16       17 
/// TO:   
///    Year     Col1  Col2
///    1970       10    12
///    1970       11    13
///    1971       14    16
///    1971       15    17
```

**Comment by lie112** [comment]
If you can work out the SQL script to perform the action you can use the CLEM\Reporting\ReportQuery model that you place as a child under your report. It creates a View in the database during the post simulation to avoid duplicating data. This view is given the name of the model in the tree and is available to view in report and plot in the GUI. There's also ReportPivot that creates a pivot table view and has a UI to help you select columns and rows and time-step. There might be some CLEM specific aspects to the report.
