### ISSUE TITLE
Reorganise the labels in GitHub issues

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#8684]
### Describe the new feature

To make it easier to track what is a bug and what is an improvement we need to refactor the GitHub issues.

- We currently have 'newfeature' and 'Improvement' that mean the same thing. Lets adopt 'Improvement'. Need to change the GitHub template to set the correct label.
- Can we rename the label 'interface/infrastructure' to 'Software' (so that bugs/improvements are either 'Science' or 'Software'. 
- Can we ask the user whether the improvement or bug is science or a software change?
- Can remove the 'other' label? Doesn't serve any useful purpose.
- Remove labels 'request' and '.NET'. They aren't used.
- 'More information needed' and 'Needs clarification' mean the same thing. Use the former.
- I'm not sure 'Informative' is useful.
- Uppercase the first letter of all labels.
- Move all questions to the discussion forum. Will need to change the github template to create discussion rather than a GitHub issue. Then remove the question label.

Once this is done it will be easier to add all Improvements to the 'long list' of the [APSIM Software Plan](https://github.com/orgs/APSIMInitiative/projects/14/views/1). We can then use this plan to prioritise what improvements need implementing.

**Comment by BrianCollinss** [comment]
Just an opinion: the intense contrast in the selected color for "Improvement" makes it difficult to distinguish other labels. At least in my eyes. It completely stands out among all texts, while it's expected that the issue titles be the most prominent texts.
