### ISSUE TITLE
Saving an incomplete manager script causes loss of data.

### ISSUE THREAD

**Issue by fai04d** [APSIMInitiative/ApsimX#87]
If you try to save a simulation while editing a manager script that will not compile (e.g. because you haven't finished it) the script loses all code on the script tab. The code does appear to be in the .apsimx file, but does not show in the UI.

**Comment by byzheng** [comment]
Looks same with #8.

**Comment by fai04d** [comment]
Not quite. The same issue does exist, but in that case you can get the display to refresh by clicking away and back again. In this case the compile will fail every time you come back so it will never display the code again. This basically means you can no longer edit the code in the UI because it will never show.

**Comment by fai04d** [comment]
Fault was caused by a previous change to PropertyPresenter.cs. The new PictureBox used to display a model image did not correctly handle instances where the model could be null. Fixed.
