### ISSUE TITLE
Wrong Cursor on XY Pairs

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8702]
### What happened?

When you are in the XY Pairs presenter, you have a double arrow cursor when the mouse is over the table. Still functions, but makes it harder to know where to click.

### What Operating System are you on?

Windows

**Comment by par456** [comment]
@ric394 I can't see to replicate this now, can you check on your system? Maybe I was on an old branch when that happened.

If the cursor is right for you, then we'll just close this.

**Comment by ric394** [comment]
@par456 I'll check this out.

**Comment by ric394** [comment]
I can still see this one appearing on my main branch. Also, I'm seeing the 'double arrow' cursor pop up in many different places on my main branch. 
The places I've noticed the double arrow cursor:
1. The add model view
2. When hovering over any table in view
4. The Nutrient view
