### ISSUE TITLE
:bug: edit-use-config and run-use-config options not following config file

### ISSUE THREAD

**Issue by luanabeckerdaluz** [APSIMInitiative/ApsimX#8704]
## Description

I am using ApsimX by running Models in command line. The options ***--edit-use-config*** and ***--run-use-config*** are listed when I run ***Models --help*** but they are not working as expected. When I use these options, the models runs normally but don't change the parameters following the config file. I checked the source code and there is no implementation for the parameters below:

https://github.com/APSIMInitiative/ApsimX/blob/66653254abe96c3bfd9913ad74281168893208a4/Models/Options.cs#L68-L69
https://github.com/APSIMInitiative/ApsimX/blob/66653254abe96c3bfd9913ad74281168893208a4/Models/Options.cs#L77-L78

I think these parameters were replaced by **--apply** feature, but they were not deprecated like the parameter **--edit** was.

### What Operating System are you on?

Linux

**Comment by ric394** [comment]
@luanabeckerdaluz You are correct. These options need to be removed as they have been superseded by the --apply switch.

**Comment by luanabeckerdaluz** [comment]
Hi @ric394! Ok, perfect! 
I just modified the help message for these two parameters following the same message of the edit parameter, which is *"Deprecated. Use --apply switch with config file workflow instead."*.
