### ISSUE TITLE
Graph Series cannot hide with legend

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8705]
### What happened?

If you have two series that produce the same Legend items, clicking on the legend to hide a line doesn't work. You can get some functinoality back by disabling "show legend" on one of the series, which lets you turn off the other series with the legend, but still not that one.

For an example, look at graphs in the Wheat validation, I was working specifically with Lincoln2014 Canopy Cover.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@par456 I wasn't able to reproduce the issue. I was able to hide the line. 
Are you able to check if this is still an issue on your machine?

**Comment by par456** [comment]
Yep, this is very specifically with predicted observed graphs. I'll upload an example file that has the right setup for you to work from.

**Comment by par456** [comment]
Test File

[graphtest.zip](https://github.com/APSIMInitiative/ApsimX/files/14502673/graphtest.zip)
