### ISSUE TITLE
Zadok Stage on day of sowing is 4.9

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8717]
### What happened?

In the GerminationPhase, FractionComplete always returns 0.999, which leads to the strange situation where on the day of sowing, the plant is already at Zadok Stage 4.995

This then causes inconsistencies with observed data where people list a zadok stage of 0 the day it's sown, and apsim says it's almost completely germinated.

APSIM should probably return a zadok stage of 0 on the day of sowing, and then go through germination on the next day so that it can match the existing phenology still.

### What Operating System are you on?

Windows

**Comment by HamishBrownPFR** [comment]
It might be better to set to fraction complete to zero in the germination phase.  That way it will be zero on the day of sowing and fix the problem you are having.  Im not sure if there is anything else referencing fraction complete on this stage but I suspect not.  The way this phase works is it will progress on the day following sowing unless the soil is very very dry so it is usually only relevant for the first day.  In dry sowing situations the crop model has no idea when the rain is comming to give germination so a fraction complete of 0 (not progress) seems more appropriate than 0.9999 (almost there)

**Comment by BrianCollinss** [comment]
Without this change, **CurrentPhaseName** is "Germinating" from the beginning of simulations (i.e., no crop planted yet).
