### ISSUE TITLE
Cannot run simulation after modifying the wheat model

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#874]
I am trying to modify the wheat model to implement a new equation of maximum leaf size. The idea is to increase the leaf size by rank until terminal spikelet, then apply for another another function to adjust the leaf size based the maximum leaf size at the terminal spikelet. 

I have implemented the basic feature to my target above. However, simulation cannot be rerun after modifying parameters (i.e. Replacements -> Wheat->Leaf->CohortParameters->MaxArea->StemElongation->MaxAreaStem->MaxAreaVeg->XYPairs). The error message is 

    Type 'APSIM.Shared.Utilities.Symbol' in Assembly 'APSIM.Shared, Version=1.0.0.0,
     Culture=neutral, PublicKeyToken=null' is not marked as serializable.

After restarting APSIMX, I can run the test simulation. Could you please give me some advices how to fix it? I have attached my example simulation with met file. 

[simulation.zip](https://github.com/APSIMInitiative/ApsimX/files/296902/simulation.zip)

**Comment by hol353** [comment]
Bangyou

If you've created a new c# class, can you make sure that it has [Serializable] immediately before the class e.g.

    [Serializable]
    public class Summary : Model, ISummary

The error suggests that your class 'Symbol' doesn't have this.

Dean

On 3/06/2016 2:12:34 PM, Bangyou Zheng <notifications@github.com> wrote:

I am trying to modify the wheat model to implement a new equation of maximum leaf size. The idea is to increase the leaf size by rank until terminal spikelet, then apply for another another function to adjust the leaf size based the maximum leaf size at the terminal spikelet.

I have implemented the basic feature to my target above. However, simulation cannot be rerun after modifying parameters (i.e. Replacements -> Wheat->Leaf->CohortParameters->MaxArea->StemElongation->MaxAreaStem->MaxAreaVeg->XYPairs). The error message is

Type 'APSIM.Shared.Utilities.Symbol' in Assembly 'APSIM.Shared, Version=1.0.0.0,
 Culture=neutral, PublicKeyToken=null' is not marked as serializable.


After restarting APSIMX, I can run the test simulation. Could you please give me some advices how to fix it? I have attached my example simulation with met file.

simulation.zip<https://github.com/APSIMInitiative/ApsimX/files/296902/simulation.zip>

**Comment by byzheng** [comment]
Hi Dean, 

I didn't create a new C# class, just modify the APSIMX file (the parameter values). I can change other parameters and run correctly, except the one I just added. Not sure what's happening in my simulation.

Cheers,
Bangyou

**Comment by hol353** [comment]
OK I've fixed this. You will need to do a pull from APSIM.Shared GitHub repo.

**Comment by byzheng** [comment]
Thanks Dean. It is working now.
