### ISSUE TITLE
-apply generates a DB file the same name as the original apsimx file

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8741]
### What happened?

When the `-apply` command is used, Models.exe generates a DB file the same name as the original apsimx file. It's like APSIM runs that file's simulations, while that's not the case. When a script is run to import APSIM outputs to R, it also tries to read this file, while the data in that file (if any) is not supposed to be part of the outputs and an empty file is also undesirable. 

- Why does APSIM generate this file when no simulation is run from the original apsimx file?
- Can we have APSIM not generate this DB file or remove it at the end? 

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
> * Can we have APSIM not generate this DB file or remove it at the end?

There is a bug with the cleanup function in Models which is supposed to remove these files at the end.  I'll investigate.

**Comment by ric394** [comment]
> > * Can we have APSIM not generate this DB file or remove it at the end?
> 
> There is a bug with the cleanup function in Models which is supposed to remove these files at the end. I'll investigate.

After a bit of investigating, the creation of a db file is normal. Whenever an apsim file is 'opened' a db file is created. You can see this when you open any apsimx file in the GUI version.
I not sure that creating an option to clean up the original file's db file is appropriate. A better option may be to clean this up with your import script.

**Comment by ric394** [comment]
I've reopened this issue to implement a cleanup if the config file directory has db files where the file size is 0.

**Comment by BrianCollinss** [comment]
The size is usually 4KB! :)

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/a4fc343f-d479-406e-b3bd-d19df1e3821e)

**Comment by BrianCollinss** [comment]
Also, sometimes the temp files are not removed. I re-ran the simulations on my own laptop to see if there was an error, but there was not.

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/d269ba84-e2c5-42d2-ba54-5f5d72a19b96)

**Comment by ric394** [comment]
@BrianCollinss I'm going to close this one. There is a fundamental issue with DataStore not 'unlocking' files when it should, and it makes it so I can't delete the db file from the original apsimx file. I was hoping this would be an easy fix but is going to take more time than its worth.
