### ISSUE TITLE
Missing data when a soil is copied from APSIM Classic

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8742]
### What happened?

I converted the APSoil database from Classic to NextGen by copying Australia's folder in Notepad and pasting it in NextGen. 

I encountered some issues:

- There is no SoilTemperature node.
- While Urea has 'zero' in all layers, NO3 and NH4 have no soil layers added.
- Initial soil moisture values are empty. This could be replaced by a default value (e.g., LL or DUL) so the user can run the model without entering these values.

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/c7a9585c-633d-436f-a2fb-9e12bdce978d)

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/8716478a-9d36-4e83-ba02-482528a58bd2)

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/04522eae-d1c2-4904-9e46-282342b3c015)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Copy-pasting the soil xml from classic to NextGen doesn't really work.

They way I would recommend porting over soils, is to use the "Import old .apsim file" option from the Home menu with a classic files with all the soils you want, and then copying each soil from that conversion over to your apsimx structure. The values convert across to the next format correctly with that.

**Comment by BrianCollinss** [comment]
I did try that and got an empty Simulations tree.

![image](https://github.com/APSIMInitiative/ApsimX/assets/39573622/11d54393-2d82-43ae-a58e-35436ad762cf)

**Comment by par456** [comment]
Ah, then that is a bug in the importer, that should be working.

Is it possible to send over the classic file so I can check where in the process it's failing?

**Comment by BrianCollinss** [comment]
@par456 It's the APSoil file/database but only for Australia.
[APSRU-Australia-soils.zip](https://github.com/APSIMInitiative/ApsimX/files/14565971/APSRU-Australia-soils.zip)
