### ISSUE TITLE
Link to CLEM documentation is broken

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8745]
### What happened?

In [the model documentation page](https://apsimnextgeneration.netlify.app/modeldocumentation), clicking on CLEM's Science Documentation redirects the user to https://www.apsim.info/clem, which is empty. It must be https://www.apsim.info/clem/Content/Home.htm.

### What Operating System are you on?

Windows

**Comment by lie112** [comment]
The www.apsim.info/clem link used to work. I used this as my standard URI for clem and is everywhere. Something has changed on the server settings. I'd I like to be able to continue using this path rather than the clunky full /Content/Home.htm path.

**Comment by ric394** [comment]
Fixed by Web Solutions team.
