### ISSUE TITLE
Mac APSIM version

### ISSUE THREAD

**Issue by CinziaCremonini** [APSIMInitiative/ApsimX#8756]
### What happened?

I'm working on some simulations but I'm facing problems inserting the soil data as I can't insert the number of layers I need 
Also, I can't see the simulations graphs correctly
I'm using the version of APSIM on Mac and I've already tried to update it
Could anyone help me?
[file apsim.zip](https://github.com/APSIMInitiative/ApsimX/files/14604498/file.apsim.zip)

### What Operating System are you on?

MacOS

**Comment by par456** [comment]
A fix for removing layers was only added recently, so there is a chance you edited your physical layers prior to that version and it left in those empty layers with 9999 in the SW column. If you select an empty depth cell and hit delete in the latest version, it should clear those empty layers out for you now.

I was able to do that on my version here, so if that doesn't work for you, I'll have a further look into what it's broken specifically on your end.

For the graphs, I'll have to grab a copy of that fodderbeet_quadr file you were working with, as I haven't seen it draw like that before and will need to see what's going on.

**Comment by CinziaCremonini** [comment]
Thanks for your help with the soil layers, I've updated APSIM.
I'm having trouble viewing graphs on all simulations, even the one I shared.
I attach another simulation with the screen of the graph I see.
[wheat_ann.zip](https://github.com/APSIMInitiative/ApsimX/files/14667037/wheat_ann.zip)

**Comment by ric394** [comment]
I've run your file (with a different weather file) and can confirm that the graph axes and graph legend show on Windows and Linux. Sounds like it may be isolated to MacOS.
### Linux
![image](https://github.com/APSIMInitiative/ApsimX/assets/123442863/2c5f8e8f-67c4-4837-96c2-d3091d710d04)
### Windows
![image](https://github.com/APSIMInitiative/ApsimX/assets/123442863/b0db6809-91ec-4efa-bca3-e0810e7d87c9)

**Comment by ric394** [comment]
@CinziaCremonini I believe I have found a temporary work around to get the axes back. If you remove a file called ApsimX.xml located in a hidden .config directory and re-run apsim, they will reappear.
The location of the file will be something like this: /Users/<your_username>/.config/ApsimInitiative/ApsimX/ApsimX.xml

I'll investigate a proper fix for this issue.
