### ISSUE TITLE
Add in default/assumed values to the soil node

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8757]
### Describe the new feature

Needed for SoilTemperature and generically useful as more models are added. 

For Clay
* If no Clay% data is supplied then assume the Clay% is 30% at all depths
* Insert this into the GUI, highlighting that it is an APSIM assumed value, encourage users to input more accurate data but allow the simulation to proceed as is
* User can then type over the supplied values in the GUI if they have better information – and in this case the highlighting would go away

For Rocks
* If Rocks% is non-blank (0 is a valid entry) then assume those values
* If Rocks% is blank then estimate the value by layer:
   * Assume rp (particle density) is 2.65 Mg /m3 
   * Estimate effective total porosity (tp) as (1-bd/rp)*0.93
   * If (1-Sat/tp) > 0.1 then take RocksFraction = (1-Sat/tp), else 0.0

Will supply similar methods for CEC later on.

**Comment by hol353** [comment]
Depends what you mean by runtime. They are added to the soil in the GUI so that the user has the opportunity to change the infilled values if they don't like them. Because of this requirement, the values must be added to the soil in the .apsimx file. The synthetic values are shown in the GUI with a red colour - they stand out.

**Comment by sno036** [comment]
There are issues here! 

- If there are Clay values already supplied then the defaults mean that <> 100% unless that Clay% is 30.
- Something odd in happening when Layering is used
- Something more odd (order of operations) is happening when Clay is in a factor

**Comment by sno036** [comment]
Suggested rule 

•	If no composition data is supplied then assume 5, 65, 30 % for Sand%, Silt%, Clay%
•	If only Clay% is supplied then Silt%=0.65*(100-Clay%) and the remainder as Sand%
•	If only Silt% is supplied then Clay%=0.3*(100-Silt%) and the remainder as Sand%
•	If only Sand% is supplied then Clay%=0.3*(100-Silt%) and the remainder as Silt%
•	If any two values are supplied then the missing value is 100 minus the two supplied
•	Apply these rules at each depth
