### ISSUE TITLE
Use In Memory DB to reduce I/O on hard drive

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#8759]
### Describe the new feature

To run APSIMNG simulations in HPC with large number of CPUs, frequently writing report into db file is a bottleneck.

For example, I run simulations in HPC (petrichor) with 1800 cores. All data are red and wrote from high speed hard drive (i.e. scratch3). An apsimx file contains 500 single year simulations with reporting at harvest. 

A single apsimx only takes 60 s with less than 500 cores, but gradually increases to 250 s with 1800 cores. See figure below for runtimes of 12K apsimx files. 

![image](https://github.com/APSIMInitiative/ApsimX/assets/1657381/476be7d7-c94a-41c0-9d82-8858120d7ce8)

This is caused by frequently I/O (i.e. write report to db file) from multiple cores. I/O will be minimised if we could use in memory DB and export report into `csv` file at the end of simulations. 

I noticed `UseInMemoryDB` is defined in the source codes and used in the unittest.

https://github.com/APSIMInitiative/ApsimX/blob/f3c769263ca33910ebb0114ba83e762fcc1b1cef/Models/Storage/DataStore.cs#L40-L53

Do we already have the ability to use in memory DB in command line (i.e. `Models`)? If not, could we implement it?

**Comment by BrianCollinss** [comment]
Do you have access to 1800 CPUs from one node?!

**Comment by ric394** [comment]
We don't currently have the ability to use in memory db for command line but it would be possible to implement.

**Comment by byzheng** [comment]
Thanks @ric394. Would be great to implement it.

**Comment by BrianCollinss** [comment]
@byzheng how is this in-memory DB used/read after simulations complete?
