### ISSUE TITLE
VS Code Configuration

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8764]
### Describe the new feature

With our move over to vscode, we need to amend the launch configuration for apsim. #8763 will remove some old debugging config that breaks symbols in vs code.

We'll then need to add in the default launch.json and build tasks.json that we've made locally to do a full clean and build to make sure vscode is running the latest code each time (have been running into problems where old dlls were not being rebuilt when they should).

**Comment by HamishBrownPFR** [comment]
Will it still be possible to use visual studio or will we all need to transition to VS code

**Comment by par456** [comment]
Visual Studio will still work fine with the project, feel free to keep using it.

We are just switching over to see how effective code is since we use it for other projects, and it would be good for us if we just had one set of tools instead of multiple.
