### ISSUE TITLE
New Stock Model

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#877]
Add the GrazPlan Stock component.

**Comment by her123** [comment]
The Stock component is now functioning. It eats supplement, and transfers urine to SoilNitrogen and faeces to SurfaceOrganicMatter.

**Comment by hol353** [comment]
Neville

This now needs to go to the Reference Panel. They will want to see some documentation and validation that demonstrate that it works. What tests have you got?

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - this is ready for review.  Call for possible reviewers?  or offers to review?

**Comment by hol353** [comment]
Nearly ready for review - later today it should be. I'll let you know.

**Comment by hol353** [comment]
@sarahcleary This is now ready for review. Possible reviewer: Matthew Harrison.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel -  any other suggestions or confirmation with @hol353's suggestion?

**Comment by peter-devoil** [comment]
Di Mayberry?

**Comment by hol353** [comment]
Di helped with creating some of the examples and was involved in some of the early workshops so not completely independent.

**Comment by hol353** [comment]
What about @peter-devoil as a reviewer?

**Comment by her123** [comment]
What about Lindsay?

**Comment by sno036** [comment]
@peter-devoil  and Matt Harrison I reckon

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - any comments on the above suggestions?

**Comment by jbrider** [comment]
Pete and Matt sound like great choices.

Are there more validation datasets available?

**Comment by hol353** [comment]
No unfortunately. At a workshop a couple of years ago Andrew Moore was tasked with trying to find additional validation datasets. Apparently they are not easy to come by.

**Comment by sarahcleary** [comment]
@m8harrison and @peter-devoil - are you both happy (and have time) to review this new model?

**Comment by peter-devoil** [comment]
No. Such a formative component needs an international reviewer with broader scope / experience than I. I'm still asking around for one over email.

**Comment by m8harrison** [comment]
Happy to do this but it will need for be next financial year as I have several commitments before June 30. Thanks for the invitation Sarah.

**Comment by sno036** [comment]
Thanks @m8harrison - next FY is fine!

**Comment by peter-devoil** [comment]
I've been recommended Aaron Ingham, Lindsay Bell or Andrew Ash. Lindsay's already been suggested above, and I'm not sure if [Aaron](https://people.csiro.au/I/A/Aaron-Ingham) or Andrew are active modellers.

**Comment by sno036** [comment]
And has Lindsay used NG at all?

<... sent on the go from my phone - please forgive typos and brevity!>
________________________________

**Comment by lie112** [comment]
Andrew Ash was instrumental in the development of IAT (Integrated Assessment Tool), NABSA (North Australian Beef Systems Analyser) and CLEM which is derived from these two models.
He is actively using CLEM in northern Australia to model beef systems, but from a CLEM user perspective and won't know about manager scripts or the finer details of APSIM Next Gen.

**Comment by sarahcleary** [comment]
@sno036 - we've had a few others review NG models with limited NG experience - @MarkLieffering from memory.  Always had at least one other reviewer in these cases as it can take the reviewer sometime to get up to speed.

**Comment by sarahcleary** [comment]
@m8harrison - as requested, a reminder since it's post July 1.  As you can see, still looking for a second reviewer, but no reason for you not to commence if you have capacity.  thanks!

**Comment by sarahcleary** [comment]
@peter-devoil - any update on additional reviewer/s?

**Comment by peter-devoil** [comment]
I'll contact lindsay.

**Comment by peter-devoil** [comment]
@LindsayWBell has agreed to providin a review by mid september.

**Comment by sarahcleary** [comment]
[Review of APSIM Next Generation Stock model Matt Harrison.docx](https://github.com/APSIMInitiative/ApsimX/files/5082732/Review.of.APSIM.Next.Generation.Stock.model.Matt.Harrison.docx)

**Comment by sarahcleary** [comment]
@sno036 - any comments on @m8harrison's review?

**Comment by sno036** [comment]
@sarahcleary  - starting to work on the reply to the review. About two weeks away or so.

**Comment by sarahcleary** [comment]
@sno036 - how is the response going?
@LindsayWBell - how is the review progressing?

**Comment by sno036** [comment]
Making some progress @sarahcleary with @m8harrison's comments. Awaiting the second review with interest.

**Comment by sarahcleary** [comment]
@LindsayWBell - how is the review progressing?

**Comment by sarahcleary** [comment]
Any update @LindsayWBell?   Are you still able to undertake a review of this model?

**Comment by sno036** [comment]
Kia ora @APSIMInitiative/reference-panel  - thanks for agreeing at the last RP meeting that, under the circumstances, one review for Stock was acceptable. Ages ago, the Stock team constructed a reply to Matt. Some of the changes have already been done but we were waiting for the second review before doing the more major parts. 

Following the example of Neil with soybean, please see attached a reply that is essentially a plan for what we would do. You will see that there are some requests from Matt that we cannot comply with but we have explained why. Can we have @APSIMInitiative/reference-panel agreement that if we do as described then it will be acceptable for merging and release?

[Reply - StockModel_MattHarrison.docx](https://github.com/APSIMInitiative/ApsimX/files/5640564/Reply.-.StockModel_MattHarrison.docx)

**Comment by sno036** [comment]
@sarahcleary

**Comment by sarahcleary** [comment]
Thanks @sno036 and @m8harrison 
@APSIMInitiative/reference-panel - please review the document provided by the Stock Model Development team.
Can you please let me know if have any queries, concerns and if so, happy for it to proceed to release?

**Comment by jbrider** [comment]
@sno036 Your 3rd last response seems to be a copy paste of the comment before - was that deliberate? It seemed to be a separate question.

**Comment by sno036** [comment]
Oops - thanks eagle-eyes @jbrider! Updated document attached and the new text just below.

"Reply: We know that the structure of these parameter strings is not user friendly but they are forced on us because the need for the code to stay aligned with Grazplan. We have [TBD] added comment into a memo on the documentation and provided more information also with a sensibility/sensitivity analysis. Users are also directed to the Grazplan website and the Cattle/Sheep explorer spreadsheets in the documentation [TBD]."


[Reply.-.StockModel_MattHarrison.docx](https://github.com/APSIMInitiative/ApsimX/files/5650055/Reply.-.StockModel_MattHarrison.docx)

**Comment by sno036** [comment]
@APSIMInitiative/reference-panel  - any further comments?

**Comment by jbrider** [comment]
@sno036 I agree with Matt's suggestion for more examples - which I know you're also keen on usually, so I'm hoping that you can add one for managing different types of stock at least as per Matt's suggestion.  Is Stock able to manage a breeder herd over a number of years or is it only designed for adding and removing from an external source?  If it is, then I would see that as a very useful example and could be setup to show how younger stock can be managed differently to older stock (also one of Matt's suggestions).

In the first example - Forage Crop Grazing - there is a node below the Stock node named Small Merino - but in the GrazeForageCrop script it refers to 'Friesian' as the stock Genotype. Is that why the animal is losing body weight while grazing on pasture?  Obvious effort has been made for neutral terms in the script properties tab ie: use of 'animals' - but the Manager script settings pages refer to 'Initial location of the cows' - picky I know.  I did have to lookup 'parturition'.

In the 2nd script the memo suggests what the next script should do, but doesn't say anything about the current script.  How does it know what type of stock is being grazed - cows must be a default?  The PGR and SupplementStore graphs are blank? The BiomassPlot1 chart is showing Paddock 2 out of all 5?

3rd script - Supp intake chart has 3 series which are named Series 1, Series 2 and series 3 - are they supposed to be wheat and crushed as defined in the ManageSupplement script? 1 of them does not appear at all.  The Animal Liveweight has a non visible series as well.

**Comment by Keith-Pembleton** [comment]
Agree on the more examples.  More examples will be useful for users working out how to use stock in their particular use cases.  Longer term it might be worthwhile looking at the "new" dairy cow model that was implement in dairyMod c.a. 2014-15.  Might help guide how to improve the representation of a dairy animal and some of their more "extreme" metabolism.

**Comment by sno036** [comment]
@APSIMInitiative/reference-panel  - last day for comments.  The plan has been live for over ten days and that was deemed an acceptable time for comment by the RP. The planning for the final sprint will take place tomorrow (Wednesday).

**Comment by peter-devoil** [comment]
My 2c: it doesnt have an example of tropical grazing, or cut & carry systems. I'm sure other people will find it useful though.

**Comment by peter-devoil** [comment]
Oops. I didnt mean to close it!

**Comment by sarahcleary** [comment]
@sno036 - how did the sprint go?

**Comment by sarahcleary** [comment]
@sno036 et al - any update?

**Comment by sno036** [comment]
[To get Stock into release .docx](https://github.com/APSIMInitiative/ApsimX/files/5901723/To.get.Stock.into.release.docx)

@APSIMInitiative/reference-panel, @sarahcleary 

Once PullRequest #6133 (https://github.com/APSIMInitiative/ApsimX/pull/6113) has been merged we will have completed the agreed list of actions with the exception of the request for a cut and carry example. We note that the latter can be added at a future date and for anyone particularly interested there is probably enough information already in the examples to construct one. 

The examples could be more numerous etc. but they are a pretty damn good start. Many thanks to the efforts of @her123, @hol353 , @MarkLieffering!

**Comment by sarahcleary** [comment]
Thanks @sno036 and team. 
@hol353 - I assume you will merge in the next few days.  Please close this issue when done.

**Comment by m8harrison** [comment]
Thanks @sno036<https://github.com/sno036> @her123<https://github.com/her123>, @hol353<https://github.com/hol353> , @MarkLieffering<https://github.com/MarkLieffering> for your efforts (and imagination) in creating relevant examples – these will be very helpful.

**Comment by hol353** [comment]
@sarahcleary : Can I put this into release or does the @APSIMInitiative/reference-panel need another round of review?

**Comment by sno036** [comment]
@hol353  - it was pre-approved by the RP and @m8harrison (see above) approves so can (at last!) go into release. Thanks, Val

**Comment by hol353** [comment]
The Stock model is now in the release. Well done everyone!
