### ISSUE TITLE
APSIM fails downloading soil via GUI

### ISSUE THREAD

**Issue by bj-far** [APSIMInitiative/ApsimX#8773]
### What happened?

Using current build, APSIM GUI:
Select Field node of a simulation
Add soil
(I chose Minnipa - this seems to trigger the failure, which arises in MapConcentration but is actually triggered (I think) when the FileConverter fails to detect a version number for the APSoil XML downloaded from the API and tries to convert it to the latest APSIMx - see stack trace):
![image](https://github.com/APSIMInitiative/ApsimX/assets/127154017/8e575dfb-8e0e-4fac-b772-cdca96a300d1)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
It looks like the original soil in APSoil had an error entered into it when it was created (someone entered an extra NaN value into Rocks).

Spoke with Dean and that'll take a bit of time to fix, so I've fixed the soil xml it downloads and imported it into Apsim so you can at least keep going with it.

[MinnipaSoil.zip](https://github.com/APSIMInitiative/ApsimX/files/14680745/MinnipaSoil.zip)


There is an unrelated soil import error that is happening from the download soils presenter (which throws an exception, but still imports the soil correctly) that I'm going to go and fix now.

**Comment by bj-far** [comment]
@par456 I need to fix that problem for more than one soil (!). My soil xml was version 47 and this code must have run plenty of times previously. Not sure why the upgrade to version 65 has never failed like this before?!

The NaN isn't actually a problem - it fits the situation where the Chemical thickness is shorter than the Physical thickness (in that case the value in a Chemical array that's been made with the Physical length is NaN). What's more a problem is that those values are now in several of the soils? 

Not sure if there are other considerations, but I've made a workaround function and added it in where each of the conversions in UpgradeToVersion65 happens (for example for Rocks - but I added it in for the three particle sizes and pH too). It seems to work gracefully enough now:
``` 
        var values = naNToZero(chemical["Rocks"].Values<double>().ToArray(), chemicalThickness);
```
```
        private static double[] naNToZero(double[] values, double[] thicknesses)
        {
            double[] ret = values;
            if (thicknesses.Length < ret.Length)
            {
                Array.Resize<double>(ref ret, thicknesses.Length);
            }
            for (int i=0;i<ret.Length;i++) { if (Double.IsNaN(ret[i])) { ret[i] = 0; } }
            return ret;
        }
```

**Comment by par456** [comment]
So the chemical property has its own thickness that is independent

**Comment by par456** [comment]
> @par456 I need to fix that problem for more than one soil (!). My soil xml was version 47 and this code must have run plenty of times previously. Not sure why the upgrade to version 65 has never failed like this before?!

The way the soil importer works is that it converts the soil xml to a very old format of apsim (version 47), then runs it through the converter system to get it up to date. It's a holdover because the APSoil structure is from classic days, and the NG structure has been modified a lot over the years.

So I wouldn't get too hung up on the version number, every XML soil will start as version 47 because that's when we switched from XML to JSON for the first time. 

> The NaN isn't actually a problem - it fits the situation where the Chemical thickness is shorter than the Physical thickness (in that case the value in a Chemical array that's been made with the Physical length is NaN). What's more a problem is that those values are now in several of the soils?

Yeah, I see what you mean, that code has made an assumption about the layer structure. I'll dig into this some more and figure out exactly what it should be doing here to map correctly.
