### ISSUE TITLE
Need a manager to manipulate species diversity in a pasture simulation

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8782]
### Describe the new feature

The best way to achieve this is to put all the potentially wanted species in the simulation and then "EndCrop" on those not wanted in a particular simulation.

**Comment by KeLiu7** [comment]
> No chance of crop/pasture rotations then?

Yes, see details here https://github.com/APSIMInitiative/ApsimX/discussions/8755

**Comment by sno036** [comment]
I don't see why this would prevent you simulating crop-pasture rotations? Can you please elaborate @peter-devoil and @KeLiu7?

**Comment by peter-devoil** [comment]
Wasn't there no way to establish a pasture after a crop?

**Comment by rcichota** [comment]
I cannot see why you wouldn't be able to sow only specific crops (pasture or not). Is this specific to 'AgPasture'? Though, all plants should have the 'capability' of being sown and ended. It is not clear whether the manager being suggested is simply something that needs adding (additional to a sow manager, just with multiple crops) or something else...

**Comment by Keith-Pembleton** [comment]
This is what I use to do pasture and crop rotations (ryegrass as an exampe):
To sow ag pasture use [AGPRyegrass].Sow(population: 10, cultivar: Amerthist, depth: 10, rowSpacing: 10)
To kill ag pasture [AGPRyegrass].EndCrop

**Comment by peter-devoil** [comment]
Once again I am proven wrong. I'll see if I can put together an example.

**Comment by KeLiu7** [comment]
> I don't see why this would prevent you simulating crop-pasture rotations? Can you please elaborate @peter-devoil and @KeLiu7?

When I specify Crop pasture rotations (e.g. Redclover and Maize) in the RotationManager, the maize disappears after appearing in the first year, and the subsequent ones are all Redclover. This may be that the Rules and Actions in the RotationManager do not work for RedClover (Redclover cannot be terminated). If we need the two to appear alternately, we need to terminate Redclover in Operation. @peter-devoil Examples like this might help a lot😊
