### ISSUE TITLE
Properties views no longer drawing correctly

### ISSUE THREAD

**Issue by ilhuber** [APSIMInitiative/ApsimX#8810]
### What happened?

It seems like model properties views (such as Clock or any Manager script) no longer display any user enter-able properties on the most recent version of NextGen (2023.4.7442). Other text on these views not relating to properties will still be displayed. This seems to be related to #8808, as it does not happen on prior versions.

### What Operating System are you on?

Windows

**Comment by par456** [comment]
I will look into this right away.
