### ISSUE TITLE
Nutrient node in SLGA downloads needs replacing

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#8857]
### What happened?

The Nutrient node in SLGA downloads needs replacing. With the current node, a simulation fails to run. If I replace it with a current version of Nutrient, it works. Please update it.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
I've tested 5 different SLGA soils and was unable to replicate the issue. 
Do you have a copy of your simulation file we could test?

**Comment by sme016** [comment]
[SLGA Nurtient issue.zip](https://github.com/APSIMInitiative/ApsimX/files/15189097/SLGA.Nurtient.issue.zip)
I've reproduced the issue again just now in the attached simulation. In the W experiment, the base simulation has two downloaded SLGA soil nodes. One is disabled and was downloaded but didn't run. I copied it and replaced the Nutrient node with a Nutrient node form another simulation that I knew ran, and this simulation now also runs. Thanks

**Comment by ric394** [comment]
I was able to run the simulation with both soils with my version (2024.5.7470) of APSIM.
Are you using an older version of APSIM? 
Some updates have recently been applied that correct issues with Nutrient nodes in APSIM files. Updating may fix your issue.

**Comment by sme016** [comment]
Thanks. I upgrade very frequently, so the file I sent was either one of todays or yesterday’s releases. So that is strange. Anyway, I’ll continue and hopefully one of the latest realises has fixed the problem. Thanks anyway for looking into it so far.
________________________________
