### ISSUE TITLE
Manage script parameters' values are lost if not saved

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8859]
### What happened?

If I change a parameter in a manager script and click on another node without saving first, when I re-select the manager, the parameter is back to its original value.

### What Operating System are you on?

Windows

**Comment by par456** [comment]
I've had this happen, and I've seen it happen on another user's system, but every time I go to debug the problem I can't see to reproduce it.

Next time it happens, can you send me the simulation file in the state it's in right then? It may be one of those bugs that only happens under a very particular circumstance.

**Comment by BrianCollinss** [comment]
You are right it does not happen any more!!! I will inform you if I ever come across the bug again. Sorry.

**Comment by peter-devoil** [comment]
Got it.

1. open a manager component, change a property, click off the component
2. click back on the manager component and the saved value of the property is there ***correct***
3. edit some text in the script editor 
4. back to the properties tab, change a property, click off the component
5. click back on the manager component and the property changes haven't been saved ***incorrect behaviour***

**Comment by BrianCollinss** [comment]
I observed more or less the same pattern. In most cases, the first time I click on the Properties tab (usually going from Script) and change a parameter, it does not hold the value. When I try again without leaving the Properties tab, it works fine.

**Comment by par456** [comment]
Thanks Peter, I can do that reliably now. Will get it fixed.
