### ISSUE TITLE
Report does not accept a boolean from a manager script as report event

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8870]
### What happened?

While reports work with something like `Maize.IsAlive == true` as the "report event", they don't work with a boolean from a manager script, like `AutoIrrigate.Script.IrrigNeeded == true`.

`Failed to publish event SubscribeToEvents. Error from subscriber SubscribeToEvents.OnSubscribeToEvents --> Exception has been thrown by the target of an invocation. --> Invalid report frequency found: AutoIrrigate.Script.IrrigNeeded == true`

### What Operating System are you on?

Windows

**Comment by par456** [comment]
The problem you are running into here with manager scripts is that the scripts are not defined until they are compiled at runtime, which is after linking happens. So the report doesn't know that the Script has a property called IrrigNeeded that it can call and fails.

There is a workaround for this however. If you type your event as:
(bool)AutoIrrigate.GetProperty("IrrigNeeded") == true

Then it will be able to pass the checks when linking, and access the property at runtime correctly. This really only applies to manager scripts, as any other object would be defined in its class ahead of time.
