### ISSUE TITLE
--list-simulations lists disabled simulations too

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8871]
### What happened?

Is this intentional?

### What Operating System are you on?

Windows

**Comment by par456** [comment]
This is intentional, so that you can see everything that is in the file. Did you have a particular reason for wanting to get a list of only sims that would run?

**Comment by BrianCollinss** [comment]
I use this flag to do what APSIMBundle.exe does in Classic: listing simulations and dividing them into many HPC jobs.

**Comment by par456** [comment]
Seems the best way to handle this would be to add a --list-enabled-simulations flag in then. We'll have a look at adding that.
