### ISSUE TITLE
Unable to download soil data

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#8893]
### Discussed in https://github.com/APSIMInitiative/ApsimX/discussions/8864

<div type='discussions-op-text'>

<sup>Originally posted by **ParameshwariS-tiger** April 24, 2024</sup>
Hi all, I was able to download soil data for the below coordinates few days back but now I am unable to do so. It says "0 soils found"
![image](https://github.com/APSIMInitiative/ApsimX/assets/147519876/54f41582-cabe-478b-a8ee-014f8d7808c6)

Below image is the downloaded soil for the same few days back
![image](https://github.com/APSIMInitiative/ApsimX/assets/147519876/eed79ba5-ecf6-4514-8f34-817077297242)

I tried with different other coordinates for which I have downloaded before but now I am facing this problem

Any assistance on this would be greatly appreciated, thanks:)</div>

**Comment by par456** [comment]
Was accessing worldmodel.csiro.au/apsimsoil? which wasn't working correctly after it was moved. Has been fixed, I now have a soil showing up again.

**Comment by ric394** [comment]
I was testing this out and there are IOExceptions slowing down the downloading of soils. This will need a bit of look.

**Comment by par456** [comment]
Good catch, it looks like https://worldmodel.csiro.au/ is completely down now (it was up and working before though). Will contact the relevant people and find out what happened.

**Comment by ric394** [comment]
Might be a good opportunity to add some exception handling for if/when these web services go down.

**Comment by par456** [comment]
It has got that whole section in a try-catch, so it might just need a better error message for this case. I'll go do that.

**Comment by hol353** [comment]
Looks like this is a problem again.

**Comment by par456** [comment]
Is working again, just need to keep an eye on the https://worldmodel.csiro.au/ endpoint.
