### ISSUE TITLE
External supply of eo

### ISSUE THREAD

**Issue by KirstenVer** [APSIMInitiative/ApsimX#8901]
### Describe the new feature

The summer and winter U and Cona used by many with SoilWat are a fix but unlikely a real solution to what may be a problem with the calculation of eo. APSIM 7.10 had the provision of supplying an alternative eo - either as a column in met file or via manager code - which SoilWat and SWIM could pick up with the right settings in the soi.xml file. It would be useful to have that capability in APSIM Next Generation so that we can start testing alternative calculations of eo without the need to change the code (which we would only do once satisfied we have a permanent solution). It would also allow us to run 'what if' scenarios.

**Comment by BrianCollinss** [comment]
https://github.com/APSIMInitiative/ApsimX/discussions/8866
