### ISSUE TITLE
--apply does not change manager parameters

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8911]
### What happened?

I am unsure whether this is a bug.

In the following config commands, the first line works fine and replaces the met file name. But the second line does not change the manager script parameter, with or without quotation marks.

```
[Weather].FileName = Met/AU-Emerald.met
[Sowing].Script.SowDate = 15-Jan   ---> OR ("15-Jan")
```

### What Operating System are you on?

Windows

**Comment by BrianCollinss** [comment]
Hey @ric394 . I would appreciate it if you could have a look at this and let me know if this is a bug or there is a just quick workaround specific to manager scripts. Ta

**Comment by ric394** [comment]
@BrianCollinss could you attach your APSIM file and config file so I can have a look at this one please?

**Comment by BrianCollinss** [comment]
[Maize1.zip](https://github.com/APSIMInitiative/ApsimX/files/15270453/Maize1.zip)

Thanks @ric394

**Comment by BrianCollinss** [comment]
Hey @ric394 . Did you have a chance to have a look at this?

**Comment by ric394** [comment]
@BrianCollinss I'll try to investigate this one today. Thanks for being patient

**Comment by BrianCollinss** [comment]
Thanks for the help. Sorry for bothering you too much! We are stuck with this issue :)

**Comment by ric394** [comment]
@BrianCollinss this is indeed a bug. I'll create a fix for this shortly.
