### ISSUE TITLE
Add ability to define water seasons in weather sampler

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#8931]
### Describe the new feature

The weather sampler is limited to changing sample years only on day 1 - right in the middle of a summer rainfall season. It would be useful to allow a season break to be specified (eg 1-oct) so that an entire water season is used, not half of one, half the other.

**Comment by sno036** [comment]
@peter-devoil - there were already a number of features in WeatherSampler that were not obvious from the rather 'terse' UI. I have added more explanation (not merged yet) as in the screenshot below. Does this do what you need?


![image](https://github.com/APSIMInitiative/ApsimX/assets/12176269/3dbaa256-5eb7-4b35-b806-76f5dd7e8672)

**Comment by peter-devoil** [comment]
From what I can see [here](https://github.com/APSIMInitiative/ApsimX/blob/f7eb85093c07819e19bbed82dc708ecca87bbfeb/Models/Climate/WeatherSampler.cs#L299) it's flipping each year on 1-jan?
