### ISSUE TITLE
Slow data writing to cleared datastore

### ISSUE THREAD

**Issue by MikeDoddNZ** [APSIMInitiative/ApsimX#8948]
### What happened?

Simulation takes a long time to write data to the data store after the simulation is complete.
Message is
"Simulations running (waiting for datastore to finish writing) - 362527 operations remaining)"
Looking at the .db file in explorer it appears to be cumulatively adding data as the file size increases from the previous value.
However, slow write problem occurs even after clearing the data store from a previous simulation.
Current workaround is deleting the .db files between simulations.
[Whatawhata1972-2021.zip](https://github.com/APSIMInitiative/ApsimX/files/15371896/Whatawhata1972-2021.zip)

### What Operating System are you on?

Windows

**Comment by sno036** [comment]
My observation when I was looking over Mike's shoulder was that it was initially quite fast but as soon as the 'empty datastore' options was used the time to tidy up after simulations blew out. Deleting the DB files fixed the issue.

**Comment by par456** [comment]
I think that PR should have solved this issue.
