### ISSUE TITLE
Cannot debug manager scripts

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#8956]
### What happened?

I used to be able to debug manager scripts by putting in a line like ```Debugger.Break()```. When I do this now, it stops in VSCode but it doesn't show the manager script.

### What Operating System are you on?

Windows

**Comment by par456** [comment]
It seem to be a bug in vscode, it cannot load symbols from a dll/pdb at runtime and use it in the debugger. You'll see this when it compiles a manager script:

![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/c91b5203-c123-4af8-a8e8-481e58b85a09)

Looking around on the web has show no solution and I even recreated the error in a new project. Only way to debug a manager script right now is to load it up in Visual Studio.

**Comment by hol353** [comment]
The fix mostly works. I can step line by line, look at values of variables etc. I can't set a breakpoint though and get it to stop in VSCode. Notice the dots are greyed out in the screenshot below.

![image](https://github.com/APSIMInitiative/ApsimX/assets/1943827/001cfaab-03f0-4981-9d46-8b7785bac106)

I also get errors like the one below.

```
[Error - 7:32:49 AM] Document pull failed for text document debug:Source%20file%20extracted%20from%20PDB%20file.%20Original%20path%3A%20APSIMa90a307c-b705-4121-8b0f-65643818f84a.cs?session%3D1a3ec229-23f1-4c2a-85d6-6dfe4e4d28d1%26ref%3D1
  Message: Unsupported extension '.cs?session=1a3ec229-23f1-4c2a-85d6-6dfe4e4d28d1&ref=1' and LSP language id ''
  Code: -32000 
[object Object]```
