### ISSUE TITLE
Ability to report events .PlantEnding and .Harvesting together for zero-yield years

### ISSUE THREAD

**Issue by LenLon** [APSIMInitiative/ApsimX#8988]
### For each event or variable write a short description followed by the code. An example: End of day: [Clock].EndOfDay

Currently, [Crop].Harvesting seems to only report when the plant survives until HarvestRipe, leaving out years where the plant dies (and has zero yield). 
[Crop].PlantEnding reports those years, but gives zero values for all plant-related variables in all years, presumably because it triggers after the plant has been harvested?

Using both events at once is possible, but results in non-zero yield years being reported twice (once with harvested yields and once with zero yields), resulting in an ugly datastore table. Is there a way to report each year once, independent of yields being zero or not?

**Comment by par456** [comment]
There is by using a manager script to craft a variable we can check against. This is how I'd do it:

Add this as a manager script into your sim, I called mine "CropStatus"

```c#
using Models.PMF;
using Models.Core;
using System;

namespace Models
{
    [Serializable] 
    public class Script : Model
    {
        [Description("Crop")]
        public IPlant Crop { get; set; }
        
        public bool DiedWithoutHarvest { get; set; } = false;
        
        private bool WasAlive { get; set; } = false;
        private bool WasHarvested { get; set; } = false;
        
        [EventSubscribe("StartOfSimulation")]
        private void OnStartOfSimulation(object sender, EventArgs e)
        {
			(Crop as Plant).Harvesting += OnHarvest;
        }
        
        [EventSubscribe("DoManagement")]
        private void OnDoManagement(object sender, EventArgs e)
        {
        	if (!Crop.IsAlive && WasAlive && !WasHarvested)
        	{
        		DiedWithoutHarvest = true;
        		WasAlive = false;
        	}
        	else
        	{
        		DiedWithoutHarvest = false;
        	}
        	
        	if (Crop.IsAlive && !WasAlive)
        	{
        		WasAlive = true;
        	}
        	
        	if (Crop.IsAlive && WasHarvested)
        	{
        		WasHarvested = false;
        	}
        }
        
        private void OnHarvest(object sender, EventArgs e)
        {
			WasHarvested = true;
        }
    }
}```

Then in the report I have these reporting variables:
`
[Wheat].Harvesting
(bool)CropStatus.GetProperty("DiedWithoutHarvest") == true
`

So this report will trigger either on harvest, and report the values of the plant right before harvesting, or it will report on the first day the plant is dead and you'll get a bunch of 0s for plant stats since it's dead.

**Comment by peter-devoil** [comment]
Another day comes when I learn something new about NG - I never knew that GetProperty() call was possible. Would be good to add it to the report manual, and add a bit about what event drives it (ie what stage(s) during the daily cycle).

**Comment by hol353** [comment]
The box at the bottom of the report view can accept a line of c# (the bit inside an if statement) so you can do all sorts of fancy stuff like what @par456 posted above.

**Comment by par456** [comment]
> Another day comes when I learn something new about NG - I never knew that GetProperty() call was possible. Would be good to add it to the report manual, and add a bit about what event drives it (ie what stage(s) during the daily cycle).

GetProperty (along with SetProperty and RunMethod) are fairly new, I added it about a month or two ago so that you could use a manager object to get variables without needing to get a reference to the script object. It's also really useful for operations commands.

**Comment by peter-devoil** [comment]
I just tried to find out where the docs live. Any clues where to find [report](https://builds.apsim.info/api/nextgen/docs/Report.pdf) to add a 1 liner?

**Comment by par456** [comment]
The report documentation is built from Examples\Tutorials\Report.apsimx

**Comment by LenLon** [comment]
Am I right in the assumption that it should be possible to modify this script to report when a certain phenological stage is reached?
