### ISSUE TITLE
CroptimizR crashes on exit

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#9005]
### What happened?

Running the example CroptimizR simulation crashes at the end of the run with a docker error: "Cannot kill container:  Container ... is not running". We get the same error on windows as linux.

There isnt a table created in the .db report that indicates what it did:
```
$ sqlite3 croptimsr.db 
SQLite version 3.41.2 2023-03-22 11:56:21
Enter ".help" for usage hints.
sqlite> .tables
DailyReport         _Checkpoints        _InitialConditions  _Simulations      
Observed            _Factors            _Messages           _Units            
```
Should there be a log of what it was trying to do? 

### What Operating System are you on?

Windows

**Comment by peter-devoil** [comment]
Addendum: running the simulation from the command line (via Models) appears to work (on linux, at least..)
![image](https://github.com/APSIMInitiative/ApsimX/assets/1924386/95782386-d95c-4f92-b908-d01c507011d5)

**Comment by KeLiu7** [comment]
I have encountered this problem before, sometimes it works and sometimes it doesn't. So, I mostly use CroptimizR in R to calibrate parameters of Next Gen. This way is more stable. 

But I also encounter new problems. CroptimizR seems unable to calibrate vector parameters (e.g. Specific Leaf Area Max. @par456 Do you have any tips? 
![image](https://github.com/APSIMInitiative/ApsimX/assets/72141690/6fe3823f-6a13-48ba-a385-4643b14fc9d6)
