### ISSUE TITLE
Name clash between model name and properties

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#9009]
### What happened?

I have found that you cannot name a model in the tree with any of the names of properties in Model or the parent Model type.
For example, I had a model in the tree structure called "Children" which leads to an odd error for the user and causes strange denial of adding further child items. This could be an issue for common names like "soil" etc.
This is because Locator.GetInternal() checks for Methods and Properties before checking if a Model. The order may need to be reconsidered or expect Method and Properties as the last part of the object path array. "Children" was not the last item in the path.
To trap this for future users APSIM either needs smarter checking to determine object or deny renaming to Parent or Model properties which not as desirable.
In debugging this issues I was getting other errors when trying to rename tree view items (os does not support serialisation) that I have seen lately but before I was using "children". The error is thrown and the rename does not take place. The error went away with a restart of APSIM.
This could be related to the finding that often the first time you click on a treeview item to rename it, make changes and hit return, it reverts to the previous name, and you need to try again. Moving the cursor around a bit seems to help.

### What Operating System are you on?

Windows

**Comment by lie112** [comment]
The error thrown when I try to change the name of a tree node is "Serializing delegates is not supported on this platform".  I was just trying to rename the Simulation model. I am not sure if this relates to the CLEM setup.  Was resolved by cloosing the tab and opening the simulation again.
I also have two nodes that when I click either, I get "Object not set to instance of object errors" because the explorerPresenter.CurrentNode is null in EnabledChecked.

**Comment by lie112** [comment]
Update: Two of my treeview node model names ended with a space. Can we have rename automatically strip spaces before saving new name? I guess it can happen when you rename and select part to remove and miss a space in name.

**Comment by par456** [comment]
> I have found that you cannot name a model in the tree with any of the names of properties in Model or the parent Model type.
> For example, I had a model in the tree structure called "Children" which leads to an odd error for the user and causes strange denial of adding further child items. This could be an issue for common names like "soil" etc.
> This is because Locator.GetInternal() checks for Methods and Properties before checking if a Model. The order may need to be reconsidered or expect Method and Properties as the last part of the object path array. "Children" was not the last item in the path.

Yep, this behaviour was changed exactly as you have said, it was possible for both a child and a property to have the same name and then the Locator was inconsistent about which object it would return. The change means that going forward, new children and properties cannot share the same name if created in the GUI, and old classes that had the name conflict would always return the property before a child (since often the property just links to the child anyway). You can see that change in #8610

Sounds like that renaming isn't quite working right if after triggering the error it's blocking you from making more children.

In fact looking at the current release, it looks like that name matching has been broken and children can be the same name as properties again, so that in fact needs fixing.

> Update: the rename error happens if you click a node to rename and type over the selected text and hit return. It does not update. If you type over the text and move the cursor position it saves the changes.

There was a bug like that a few months ago where rename was not working right (and even renaming the incorrect node), but that has been solved now. I just did your instructions there on the release version and had no problems.

**Comment by lie112** [comment]
Thanks. I had just pulled the latest master yesterday so assumed I had all the latest changes. I'll try again.
Does the check for naming at Rename in the tree give the user a status message of the problem or just revert to the previous name which may lead to confusion?
I'll wait to have the new version and see if I get the renaming issue again.

**Comment by par456** [comment]
If it has a name conflict, it is supposed to just append a number to the end of the name until it finds a unique name. So if I had a Sim called "Sim" and tried to rename another simulation to the same, it would change it to "Sim1" after the rename box closed.

Julian has also just run into their renaming issue this morning, so we'll merge that PR as soon as possible to see if it fixes both your issues.

**Comment by lie112** [comment]
It also seems that you cannot have a child of a model in the tree with the same name as a child of any of the ancestors of the model. This is the catch that has been getting me. It never seemed to cause any issues in the past. 
I have a GrowTotatoes/Harvest and I want to put GrowCucumbers/Harvest as a child of GrowTomatoes. It gets messy to use harvest and harvest2 etc right down my tree. I nest a lot of repeated groups with the same naming.
I can see this is a tricky one to solve as whichever you give highest priority will cause problems for someone.

Why can't we assume everything is a Model when doing Locator.GetInternal() calls from the UI as it will not have any properties or methods which are only accessible from user paths in reports etc?

**Comment by par456** [comment]
That's definitely a bug you've found there, those names should not conflict. I will make sure I address that in the PR if it's happening with the changes I have.

>Why can't we assume everything is a Model when doing Locator.GetInternal() calls from the UI as it will not have any properties or methods which are only accessible from user paths in reports etc?

Locator also returns values of properties like int, float, string etc, so basically could return anything. The locator is on the list for a refactor soon for exactly the reasons you are seeing. It's used by the reporting systems, object and script linking, file structure and gui, so it's very complex and has a lot of edge cases.
