### ISSUE TITLE
Unintended interaction between factor levels when using Soil.Physical in a factor

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#9020]
### What happened?

It is possible (and sometimes reasonable) to put a Soil.Physical model under Experimental Factors to have an experiment with soils of different water holding capacities.  
However, the GUI enforces a constant set of values for SW across all Soil.Physical models in a simulation.
In the attached file I have set up a simple example.  The screen shot shows SW values of 0.4 all the way down for the Physical model under the Light Factor which is reflecting the values set for SW in the Heavy factor.  If I change them to 0.2 all the way down here that will change them to 0.2 in the Physical model under the heavy factor.
![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/afda0d46-cff8-4bfc-b8b4-4120cf0b79a9)

[SoilEg.zip](https://github.com/user-attachments/files/15779298/SoilEg.zip)

### What Operating System are you on?

Windows

**Comment by HamishBrownPFR** [comment]
A work around is to include the entire soil model in the factor.  With this set up the model takes initial soil water from the Water model and initializes the SW as required.  However, the values displayed in the grid on the physical node do not agree with what is set in the Water node (see screen shot below).  

![image](https://github.com/APSIMInitiative/ApsimX/assets/7295858/89270b6f-9765-4f04-9f88-5312b140d671)

**Comment by HamishBrownPFR** [comment]
Also, important to note in the first example, the Physical nodes on the Factors interact with the Water node in the Water node in the base simulation.  So if I change the settings in Water, it changes SW in both Physical nodes under Factors.  And visa versa, if I change the SW under the factor it changes the settings in Water under the base simulation.

**Comment by par456** [comment]
My guess would be that physical is linking to the wrong thing when it's by itself in a factor. We've seen this before with other nodes, where it's using a 'findinscope' or similar and just linking to a completely wrong model to draw values.
