### ISSUE TITLE
Arithmetic operation resulted in an overflow error when dragging and dropping model from add model view

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#9075]
### What happened?

I get an error on the first attempt, but subsequent attempts work without error.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
Exception:



![Image](https://github.com/user-attachments/assets/90af88ba-27bc-4e44-bbbf-7d44fa3fe59c)

@hol353 This drag prop process seems very complicated. Does it make sense to simplify this? 
By that I mean store whatever object is being dragged rather than using pointers and GTK.

**Comment by hol353** [comment]
Yes, it is complicated - not sure why. Not sure you want to refactor it though - might take a while. Is there a simple fix for this specific problem?
