### ISSUE TITLE
How should I generate a documentation?

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#908]
I create a simulation and want to generate the documentation for figures. After clicking "Create documentation", I get this error.

    Could not find a model of the name TraitAssessment. 
    Simulation file name must match the name of the node to document.

Have no idea about this error message. Any suggestions to fix it?

**Comment by hol353** [comment]
It expects the name of the .apsimx file to be name of the model to be documented.

e.g.

wheat.apsimx

model is wheat.

**Comment by byzheng** [comment]
Have tried it with another error: 

     Object reference not set to an instance of an object.

But cannot find the related codes in debug mode.

**Comment by byzheng** [comment]
The error about is caused by the model name under simulations (case sensitive). For example, `Wheat` in the replacement and `wheat` under simulations.

**Comment by byzheng** [comment]
It will be better to fix this bug to remove the case sensitive in the documentation.
