### ISSUE TITLE
Add Stock model report for EBW

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#9092]
### Describe the new feature

The stock model would benefit from a reporting variable for Empty Body Weight.
EBW calculations can be derived from code in AnimalGroup.cs line 4081.
It would possibly be BaseWt/GainC[18]

**Comment by her123** [comment]
base_wt is a fleece and conceptus-free weight.

**Comment by hut104** [comment]
I'm new to this but Empty body weight is defined as live body weight minus gastrointestinal tract contents.

The code has the following 
~~~

            EmptyBodyGain = this.AnimalState.EnergyUse.Gain / this.AnimalState.GainEContent;

            WeightChange = Genotype.GainC[18] * EmptyBodyGain;
            BaseWeight = BaseWeight + WeightChange;
~~~

This seems to suggest that there is a conversion between BaseWeight and EBW.

**Comment by andrew-moore-csiro** [comment]
Neil is correct: "base weight" excludes fleece and conceptus but includes (a typical level of) gut contents

And yes, C(G,18) = AParams.GainC[18] = 1.09 is the relevant multiplier
