### ISSUE TITLE
Remove deprecated Gtk features

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#9125]
### Where is the code located?

User interface code in ApsimNG

### What needs to be changed?

Gtk features which have been deprecated should be replaced with more modern equivalents.

### Why does the code need changing?

This does not strictly need to be done at this stage, but should make future updating a bit less complicated. We are currently using GtkSharp 3.24.24.38, but updating to 3.24.24.95 treats use of some of these deprecated feaures (e.g., HBox constructor) as errors. 

This should be regarded as a "sub-issue" of #9088 (question: does github provide any formal mechanism for treating an issue as a series of smaller sub-issues?)

**Comment by ric394** [comment]
>  (question: does github provide any formal mechanism for treating an issue as a series of smaller sub-issues?)

Yes. If you create a check list in the 'parent issue' you can hover over any check list item and convert to an issue.
