### ISSUE TITLE
EXPORT TO EXCEL TAKING TO LONG or NEVER

### ISSUE THREAD

**Issue by Malitoz** [APSIMInitiative/ApsimX#9166]
### What happened?

I am running a long-term simulation (31 years), unfortunately saving the output takes forever; I have not been able to save a single output from the data store. Am using APSIM 2024.7.7553.0

### What Operating System are you on?

Windows

**Comment by par456** [comment]
I've noticed this myself when trying to export a datastore. I have had better luck exporting to text file (.csv) and then combining the tables into sheets in excel manually. We need to investigate why trying to export directly to excel is so slow though.

**Comment by lie112** [comment]
I also noticed this.
An alternative is to use Sqlite ODBC driver in windows to link your database (db) created by APSIM directly to Excel using power tools in Excel. This has some benefits and issues. The benefit is you can open huge datafiles beyond what is possible in Excel and you can refresh your entire spreadsheet (f5) when the underlying data is updated really improving data analysis workflow in that all graphs and tables update automatically and don't need to be recreated or have large blocks of data copied and pasted. You can also add calculated columns and query/filter data as it is read into tables and create dashboards. It's a bit clunky to connect to a different database and you need to learn sql connection strings (available online) and how to work with power pivots and power queries for the data tables. But this does provide a great workflow if you do a lot of pivot tables on your simulation results.

**Comment by Malitoz** [comment]
The issue seems to have been resolved on my end after running an update. @par456 and @lie112  instal the update and let us know.
