### ISSUE TITLE
Is the Nitrification Inhibition Factor in Next Gen?

### ISSUE THREAD

**Issue by hrpasl** [APSIMInitiative/ApsimX#9173]
### Describe the new feature

Could someone check if the nitrification_inhibition factor is already included in Nutrient model (as it was in APSIM 7.10 Soil N model)—a search in GitHub shows that it is probably isn’t, but would be nice if you all can double check--needed for the EEF project
In 7.10, the output was "inh," but the 7.10 code specifies "nitrification_inhibition(max_layer)"

**Comment by KirstenVer** [comment]
It does not appear to be in NextGen yet. The place for this to be added - request for two projects - is to have an inhibition factor (0-1) added within the code of CERESNitrificationModel.cs (under APSIMX>Models>Functions>SoilFunctions).

As in APSIM7.10 suggest this is a factor that sits outside that of the existing RateModifier that is the minimum of TF, CERESWF and CERESpHF. 

I.e. PotentialRate * RateModified * Inhibition

The Inhibition would "come from outside" and be bounded between 0 and 1. 

In 7.10 the implementation in soilN.f90 was:

real         nitrification_inhibition(max_layer)  ! nitrification inhibition 
....
   g%nitrification_inhibition(:) = 0.0 ! nitrification inhibition - default to no effect 
....
   ! use a combined index to adjust rate of nitrification  [KV: calculation of minimum of environ factors]
   ! NOTE phn removed to match CERES v1
   pni = min (wfd, tf, phf)

   ! get actual rate of nitrification for layer
   nh4ppm = g%nh4(layer)*soiln2_fac (layer)
   opt_rate_ppm = divide((c%nitrification_pot* nh4ppm),(nh4ppm + c%nh4_at_half_pot),0.0)
   opt_rate = divide(opt_rate_ppm,soiln2_fac(layer),0.0)

   !-----Changes by VOS 13 Dec 09, Reviewed by RCichota (9/02/2010)----------------
   opt_rate = divide(opt_rate_ppm,soiln2_fac(layer),0.0) * max(0.0,1.0-g%nitrification_inhibition(layer))
[KV: use of max is bounding the factor to be between 0 and 1]

   dlt_rntrf = pni * opt_rate !* (1.0 - g%NH4_absorbed(layer))  [KV: applying the reduction from environmental factors]
   nh4_avail = l_bound (g%nh4(layer) - g%nh4_min(layer), 0.0)
   dlt_rntrf = bound (dlt_rntrf, 0.0, nh4_avail)

**Comment by KirstenVer** [comment]
Three further comments:
- In my solution for the problem in the text above please use 'nitrification_inhibition' instead of 'Inhibition'. To allow later differentiation with similar factor added to the code in CERESUreaHydrolysisModel.cs
- Coming from outside the nitrification_inhibition needs to be settable (and reportable)
- In 7.10 inh was used in some code as "short hand" for nitrification_inhibition. This is not required.

**Comment by sno036** [comment]
Hi @KirstenVer and @hrpasl - just FYI, @keren0818 and I will be working on implementing DCD and other inhibitors starting later this year.

**Comment by KirstenVer** [comment]
Hi @sno036 and @keren0818: need to have a meeting, as we're in process of doing the same with @hrpasl and software team in Toowoomba (funded allocation). This will be a set-up that will allow a range of inhibitors and controlled-release fertiliser option, so not specific to DCD, but allowing for DCD.

**Comment by KirstenVer** [comment]
Current implementation uses NitrificationInhibition as a constant across the profile. In reality, the inhibition will vary by layer, e.g. depending on where the nitrification inhibitor compound is applied or has moved to.
