### ISSUE TITLE
Solute output arrays

### ISSUE THREAD

**Issue by hrpasl** [APSIMInitiative/ApsimX#9176]
### What happened?

When I output [Soil].nutrient.no3.ppm, I get the array starting at (1) but the value is actually reflecting the value for the Soil's second layer. Should the array be starting at 0?

### What Operating System are you on?

Windows

**Comment by hol353** [comment]
Report always numbers it's arrays starting from 1 so [Soil].nutrient.no3.ppm[1] should be the first layer in the soil.

Manager scripts always number layers starting at zero.

I'd be amazed if you what you are saying is correct, but we need to check. Can you attach a zipped simulation that shows the problem.

**Comment by par456** [comment]
Closed as per Heather
