### ISSUE TITLE
Next Gen and 7.10 Wheat Simulation giving different results

### ISSUE THREAD

**Issue by hrpasl** [APSIMInitiative/ApsimX#9182]
### What happened?

duplicated a simulation that I built in Next Gen into 7.10 (see both attached to corresponding email) and got very different results. The 7.10 results lined up with the measurements that the field teams took. Cannot find a way to get the same results in Next Gen. Would appreciate you all looking into this and helping me out.

### What Operating System are you on?

Windows

**Comment by hrpasl** [comment]
[Issue for Github.zip](https://github.com/user-attachments/files/16340569/Issue.for.Github.zip)

**Comment by BrianCollinss** [comment]
There is no way you can get exactly the same results from NextGen. Not only has APSIM-Wheat been modified in several ways, there have been many changes (some of which significant) in other APSIM modules as well.

**Comment by par456** [comment]
We worked through both simulations and found out why they differed by so much. More work to do around water stress, but the difference is not as bad once we got the management matching,
