### ISSUE TITLE
Right Click to change units for soil chemical contents not working

### ISSUE THREAD

**Issue by emdigman** [APSIMInitiative/ApsimX#9184]
### What happened?

In the APSIM Next Generation tutorial module 1, the following instruction is given when setting up the soil module: 
_To change the units, right-click the “initial values” cell and select “kg/ha”_

I am following the tutorial using the current (2024.7.7557.0) version of APSIM and right clicking the initial values field produces no response in any of the chemical components of the soil module (NO3, NH4, or Urea). I am not sure if this is an error with my installation of APSIM, the current version, my misunderstanding of the instructions, or if this functionality has been moved from a right click and to another part of the software UI and the tutorial has not been updated to account for this.

Is there a way to either fix this issue (if it is an issue) or an alternative process to change the units for these values? Thank you.

### What Operating System are you on?

Windows

**Comment by par456** [comment]
We just pushed an update to our gridding system the other day and it looks like you've found a bug in the new system, the menu isn't coming up for me either. Will get that sorted fairly quickly.
