### ISSUE TITLE
Link on Manager Script Structure (Documentation) APSIMx is broken

### ISSUE THREAD

**Issue by i-heis** [APSIMInitiative/ApsimX#9186]
### What happened?

I am trying to get more familiar with setting up manager scripts in APSIMx and therefore, I wanted to follow this link (https://apsimnextgeneration.netlify.com/usage/writemanagerscript) in the manager documentation pdf (https://builds.apsim.info/api/nextgen/docs/Manager.pdf), but it is broken. I am also happy about any other instructions/guides on how to set up a manager script. 
Thanks
Irina

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Ah, the link should be: https://apsimnextgeneration.netlify.app/usage/writemanagerscript/

We'll have to fix the autodoc so that it works from the pdf like it should.

**Comment by BrianCollinss** [comment]
@i-heis Irena, the best way to familiarise yourself with manager scripts is to learn from existing ones, including those in the toolbox and examples.
