### ISSUE TITLE
Labels have been left out of Playlist presenter

### ISSUE THREAD

**Issue by bj-far** [APSIMInitiative/ApsimX#9193]
### What happened?

Playlist fails to open in 2024.7.7561.0 (Object Ref not set to instance of an object).
Playlist uses TextAndCodeView which is missing label1 and label2 in the the .glade file (accidentally deleted in the gtk upgrade?).
Copying them back from previous .glade seems to restore the Playlist to behave the way it used to.

### What Operating System are you on?

Windows

**Comment by zur003** [comment]
I will add a brief explanation here of how this error arose, as there is a possibility that it may appear elsewhere, but hasn't yet been detected.

When working on the Gtk upgrades in PR #9149, I edited the *.glade files with the 'glade' utility, as it conveniently points out the existence of deprecated features. Unfortunately, it can also make unexpected changes. In this case, the `Label` widgets were held within `ScrolledWindow` widgets. However, a `Label` cannot be held as a child directly by a `ScrolledWindow`; it must be wrapped inside a `Viewport`. Gtk and GtkBuilder are helpful in that if a `Label` (or other widget without native scrolling support) is added directly to a `ScrolledWIndow`, it adds the missing `Viewport` wrapper automatically. The `glade` utility, however, is not so clever, and (with no warning at all) drops the "invalid" content of the `ScrolledWindow`.

**Comment by bj-far** [comment]
Hopefully the only model affected (I was a bit surprised no-one else had run into it already). Can see it's not an easy one to pick up in testing, because the error only shows up when the model is opened in the UI. There must still be quite a few models that are still to be opened in the UI since the Gtk upgrade. Good idea to put your note here!

**Comment by zur003** [comment]
And after a very quick look at the `TextAndCodeView.glade` file, I must ask why another `ScrolledWindow` is there at all: does `scrolledwindow2` do anything useful? It doesn't appear to ever hold any contents, nor did it do so before #9149. Is it just there to take up space?

**Comment by bj-far** [comment]
I'm not sure :) First time I've encountered a .glade file. I just put the labels back where it seemed like they went. Wasn't 100% sure why there were so many ScrolledWindows but was hoping that what/whoever put them there knew what it/they were doing!

**Comment by bj-far** [comment]
(another reflection was that it would be handy if the elements had meaningful names; top and bottom label for example (given it's meant to be a generic controller), or input and output label. If you are tidying it up and understand what's meant to be there.

**Comment by zur003** [comment]
@bj-far - I've just done a quick search to see whether there may be other .glade file where `ScolledWindow` widgets have had their contents removed. It looks like there was a problem with `CustomQueryView.glade`, but that file is not currently in use. The associated View was deleted about 3 years ago; the glade file should probably just be deleted.

**Comment by zur003** [comment]
@bj-far - scrolledwindow2 has its content added in code, so I removed my earlier comment about it.
