### ISSUE TITLE
Warning user about saving modifications does not always work correctly

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#920]
If the user closes a simulation, or the entire application, after having made modifications to that simulation, she should receive a warning, and be offered the opportunity to save the changed work. This currently isn't working correctly. If the entire application is closed, no warning at all is given, and the work is lost. If a tab is closed, a "do you want to save" dialog appears, but if the user selects "Cancel", the simulation is closed anyway.

**Comment by HamishBrownPFR** [comment]
I have just come into issues to log the same problem!!! 

Also, running the simulation does not save the .apsimx file as it did in the old APSIM so a prompt to save before closing is essential.
