### ISSUE TITLE
Graph and yeild data dont process despite weather data being accepted

### ISSUE THREAD

**Issue by ewill26** [APSIMInitiative/ApsimX#9203]
### What happened?

I was running an APSIM file using custom weather data. The APSIM was able to successfully simulate a file previously but after trying multiple new files with different data the weather file is accepted with no shown errors but after running a simulation graph, series, and data store are all blank. Could this be an issue with the file? However, weather files I have attempted that work vs the ones not working seem identical in format besides different data we wanted to compare. APSIM is also fully updated and the issue still persists. Below is original excel file that was converted to .met and PRN.
[2021westpalmbeach.xlsx](https://github.com/user-attachments/files/16417317/2021westpalmbeach.xlsx)

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@ewill26 are you able to share a copy of the apsimx file for testing?

**Comment by ewill26** [comment]
@ric394 [2021westpalmbeachex.zip](https://github.com/user-attachments/files/16420969/2021westpalmbeachex.zip)
Here is the file as a compressed zip, hope this works. Thanks for helping.

**Comment by BrianCollinss** [comment]
@ewill26 Please upload all the files you have used, including the weather/met file.

**Comment by ewill26** [comment]
Here is the APSim file in a zip and the weather file in xslx format (github would not let me send prn space delimited format). These were all files used in the sim. Please let me know if there's anything else needed.

[West Palm Beach Met (1).xlsx](https://github.com/user-attachments/files/16421257/West.Palm.Beach.Met.1.xlsx)
 
[2021westpalmbeachex.zip](https://github.com/user-attachments/files/16421258/2021westpalmbeachex.zip)

**Comment by BrianCollinss** [comment]
I get this error. It seems your data is incomplete:

`Date 1/01/2020 12:00:00 AM doesn't exist in file: C:\Users\U8019357\Downloads\2021westpalmbeachex\2021westpalmbeach.xlsx`

**Comment by ewill26** [comment]
Oh sorry, I put the wrong weather met file, the correct one was the one I first submitted in the thread 
[2021westpalmbeach.xlsx](https://github.com/user-attachments/files/16421466/2021westpalmbeach.xlsx)

**Comment by BrianCollinss** [comment]
Still:

`Date 1/01/2020 12:00:00 AM doesn't exist in file: C:\Users\U8019357\Downloads\2021westpalmbeachex\2021westpalmbeach.xlsx`

**Comment by BrianCollinss** [comment]
It works for me when I run from 1/01/2021 to 31/12/2021.

**Comment by ewill26** [comment]
When I do it the graph still shows blank and series blank although the clock is set to run 1/1/2021 - 12/31/2021
![Screenshot 2024-07-29 222135](https://github.com/user-attachments/assets/243bd398-50a6-4789-be5f-12bb2983b13a)
![Screenshot 2024-07-29 222116](https://github.com/user-attachments/assets/a3dba2fa-9fde-4818-ae41-7b2c99de49fb)

**Comment by BrianCollinss** [comment]
You had set the sowing rules in a way that Maize was not planted at all. I changed it to this to relax those rules and ensure Maize is planted in all seasons:

![image](https://github.com/user-attachments/assets/0350e46f-3c9a-43d7-b593-a7c63d261a6e)

**Comment by ewill26** [comment]
Thank you so much! After changing the parameters I was able to get a yield. I still only get one harvest shown at 2021-04-10. Is there any other parameters I need to change in order to have the full yield as shown in the photo you sent before? Also, I noticed you used the Katumani variety, do you have any suggestions for Maize variety that would be more applicable for US regions?

**Comment by BrianCollinss** [comment]
I don't know your study area so I cannot suggest a cultivar. This kind of information must come from the experiment you are trying to model, or other sources.

You need to add a report that produces data outputs, then link the Graph to that report to see the day-by-day change in, for example, yield. 

I suggest you have a look at APSIM NextGen documentation and/or have a look at Example simulations provided to familiarise yourself with APSIM interface, etc.
