### ISSUE TITLE
Error thrown when Report is selected

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9209]
### What happened?

I get this error when I click on reports, while DataStore works fine. Example APSIM file can be found here: https://github.com/APSIMInitiative/ApsimX/issues/9203

![image](https://github.com/user-attachments/assets/2f38ee79-a222-47b9-b874-93f59f0e0bbf)
![image](https://github.com/user-attachments/assets/10c4867f-17f5-4801-b0fd-d8195069a93c)
![image](https://github.com/user-attachments/assets/e122737d-2f28-4ad9-84a0-b15c2460859e)

### What Operating System are you on?

Windows

**Comment by zur003** [comment]
@BrianCollinss - I have not been able to replicate this error.

**Comment by BrianCollinss** [comment]
Hmmm... And I wonder why it only occurs in this file. I haven't had similar issue with other files.

**Comment by par456** [comment]
I'm seeing it now too in my file, it's got something to do with ListView in report, so tagging @ric394 to have a look at.

**Comment by zur003** [comment]
I'm seeing it as well after re-opening the file. Very odd.

**Comment by zur003** [comment]
I think it is now failing for me because I did a recent pull. I think PR #9204 may have created the problem. It seems to be assuming a filter will be filtering by SimulationName, but in this context the filter is by Zone. Maybe @hol353 should also have a look.
