### ISSUE TITLE
ISRIC SoilGrids has 2 children named Temperature

### ISSUE THREAD

**Issue by Yuval-Sadeh** [APSIMInitiative/ApsimX#9222]
### What happened?

When trying to download a new soil file from ISRIC using the GUI, results in the following error message:**"Duplicate models found: .Folder.Synthetic Soil Derived from ISRIC SoilGrids has 2 children named Temperature"**.

I have used the "Download Soil" function in the GUI. When providing the coordinates (in Europe), the GUI identifies the Place Name automatically, but no soils appear in the results ("0 soils found"), and the error ("Duplicate models found: .Folder.Synthetic Soil Derived from ISRIC SoilGrids has 2 children named Temperature") appear.
I am using the **APSIM 2024.7.7563** version

Thank you for such a great model!

Here is an .apsimx file and a .met file:
[APSIM_ISRIC_Download_Issue.zip](https://github.com/user-attachments/files/16478177/APSIM_ISRIC_Download_Issue.zip)

### What Operating System are you on?

Windows

**Comment by daSilva5** [comment]
I am having the same problem with APSOIL Australia: 
Duplicate models found: .Synthetic Soil Derived from the SLGA has 2 children named Temperature

**Comment by ric394** [comment]
@daSilva5  @Yuval-Sadeh Upgrading APSIM to 7567 resolves this specific issue, however be aware there is an issue downloading soils originating from world model API at this time that is currently being resolved.

**Comment by ric394** [comment]
@Yuval-Sadeh @daSilva5 if you have updated, could you please check if this is still an issue?

**Comment by daSilva5** [comment]
> @Yuval-Sadeh @daSilva5 if you have updated, could you please check if this is still an issue?

Hi,
Unfortunately, my computer is blocking the installation of this version. One of my technicians checked, and said that because the code is hidden, microsoft is identifying it as a malware. Version  7563 install with no problems, would be great if you could fix it!

Thanks

**Comment by Yuval-Sadeh** [comment]
Dear Julian,

Thank you so much for looking into this.
I have just upgraded to version 7570 and it seems to be *working well!*
Thanks for solving this issue!

Can I take this opportunity and ask if APSIM-Initiative has updated any
cultivars into APSIM over the last year? I'm especially interested in
wheat, maize and soybeans. I have found that the existing cultivars are
often not up to date out side of Australia.

Kind regards,
Yuval

**Comment by ric394** [comment]
> > @Yuval-Sadeh @daSilva5 if you have updated, could you please check if this is still an issue?
> 
> Hi, Unfortunately, my computer is blocking the installation of this version. One of my technicians at work checked, and said that it is because the code is hidden, microsoft is identifying it as a malware. Version 7563 install with no problems, would be great if you could fix it!
> 
> Thanks

@daSilva5 Could you provide some screenshots of the errors you receive when trying to install APSIM? It may also be helpful to know what steps you've taken to install APSIM.

**Comment by ric394** [comment]
> Thank you so much for looking into this.
I have just upgraded to version 7570 and it seems to be *working well!*
Thanks for solving this issue!

@Yuval-Sadeh I'm glad I could assist 😄 

> Can I take this opportunity and ask if APSIM-Initiative has updated any
cultivars into APSIM over the last year? I'm especially interested in
wheat, maize and soybeans. I have found that the existing cultivars are
often not up to date out side of Australia.

1. I can see that more than 20 cultivars have been added to Wheat this year.
2. No new or updated cultivars for soybean.
3. No new or updated cultivars for maize either.

**Comment by daSilva5** [comment]
> > > @Yuval-Sadeh @daSilva5 if you have updated, could you please check if this is still an issue?
> > 
> > 
> > Hi, Unfortunately, my computer is blocking the installation of this version. One of my technicians at work checked, and said that it is because the code is hidden, microsoft is identifying it as a malware. Version 7563 install with no problems, would be great if you could fix it!
> > Thanks
> 
> @daSilva5 Could you provide some screenshots of the errors you receive when trying to install APSIM? It may also be helpful to know what steps you've taken to install APSIM.

Oh Well. I was trying to install from .exe file. It gave the error and I missed, when I tried again it just installed. After days trying  hehehe
I can inform that the soil tool is working now!
