### ISSUE TITLE
Failed Module 4: Sowing A Crop

### ISSUE THREAD

**Issue by pmasikati** [APSIMInitiative/ApsimX#9229]
### What happened?

<img width="709" alt="APSIMx error" src="https://github.com/user-attachments/assets/0992ffd5-5ba2-41c1-9ff1-c4215b840b65">

### What Operating System are you on?

Windows

**Comment by BrianCollinss** [comment]
What do you have under "Factor"? And please share a screen from under "Field".

**Comment by pmasikati** [comment]
> What do you have under "Factor"? And please share a screen from under "Field". The error you shared indicates that there is no "Fertilise at sowing" under Field, or the name is different.

<img width="929" alt="image" src="https://github.com/user-attachments/assets/fd539e32-6e11-4b27-9358-6898c962010c">

**Comment by BrianCollinss** [comment]
I still can't see whether you have a "Fertilise at sowing" object under Field!

**Comment by pmasikati** [comment]
> I still can't see whether you have a "Fertilise at sowing" object under Field!

<img width="593" alt="image" src="https://github.com/user-attachments/assets/435c7eb9-a7b5-4334-99d4-33dd8a70c11f">

**Comment by pmasikati** [comment]
> I still can't see whether you have a "Fertilise at sowing" object under Field!

ok got it thanks

**Comment by BrianCollinss** [comment]
You have changed its name to "SowingFertiliser". Make the same change under Factor.

**Comment by pmasikati** [comment]
> You have changed its name to "SowingFertiliser". Make the same change under Factor.

Yes
<img width="686" alt="image" src="https://github.com/user-attachments/assets/5eec923e-28ec-4ba3-96da-4cee96aa8651">

**Comment by BrianCollinss** [comment]
If this fixed your problem, you can go ahead and close this issue. Also, you can ask your questions under Discussions.

**Comment by pmasikati** [comment]
Thank you
