### ISSUE TITLE
Weather data download fails with unknown error

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9237]
### What happened?

![image](https://github.com/user-attachments/assets/63613151-48a4-4c29-bf21-a77b8817cd18)
![image](https://github.com/user-attachments/assets/c040f364-8e0a-499d-ab83-01df624a359e)

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
I'm unable to replicate this issue.
Can you tell me the steps that you're taking?
Do you also have the specific start and end dates?
It may also be helpful to have a copy of the specific apsimx file that you're using as well.

**Comment by BrianCollinss** [comment]
It does not happen any longer! Perhaps one of the recent pull requests fixed it. I am unsure. Will reopen it if I encounter it again.
