### ISSUE TITLE
Square plot area on APSIM.POStats.Portal

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9244]
### Describe the new feature

Would it be better to have:

- square plot area to make it easier to visually inspect model performance (i.e., equal range on axes + 1:1 line at 45 degree)?
- separate best-fit lines for 'accepted' and 'current'?
- thick black 1:1 line?

![image](https://github.com/user-attachments/assets/6e63256b-258d-424f-b06a-f99a8239d833)

Note @hut104: GitHub [went down yesterday](https://www.theverge.com/2024/8/14/24220685/github-down-website-pull-request) and it seems the issue I had opened and you commented on was removed. So I created a new issue.

**Comment by ric394** [comment]
@BrianCollinss I moved the original issue across to the appropriate repo [here](https://github.com/APSIMInitiative/APSIM.PerformanceTests/issues/70). Apologies for not linking to it earlier.

**Comment by BrianCollinss** [comment]
@ric394 Thanks. I didn't know there was another repo! Now I feel stupid.
