### ISSUE TITLE
Error while evaluating transition from initial to Peanut - rule '': Test condition returned nothing

### ISSUE THREAD

**Issue by smkuhlani** [APSIMInitiative/ApsimX#9246]
### What happened?

Formatting the maize-wheat rotation example to maize-soybean. Throwing this error: Error while evaluating transition from initial to Peanut - rule '': Test condition returned nothing
[Rotation_mze_sbn.zip](https://github.com/user-attachments/files/16646412/Rotation_mze_sbn.zip)

### What Operating System are you on?

Windows

**Comment by BrianCollinss** [comment]
Have you updated APSIM to the latest version? I haven't opened your file, but there used to be an issue related to blank lines in the Conditions panel of rotation manager.

**Comment by smkuhlani** [comment]
I am using the latest version.

**Comment by BrianCollinss** [comment]
Please share the met files as well.
