### ISSUE TITLE
APsoil downloads have errors

### ISSUE THREAD

**Issue by MikeDoddNZ** [APSIMInitiative/ApsimX#9252]
### What happened?

Downloaded APsoils is generating an error, see screenshot below.

This one appears when you first select a soil in the download list after a search:
![image](https://github.com/user-attachments/assets/c8da6a50-5157-436e-88af-c98ca20074e9)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
APSoil was having problems, it has been resolved now.
