### ISSUE TITLE
Slight tweaks to manager codes to avoid confusion

### ISSUE THREAD

**Issue by KirstenVer** [APSIMInitiative/ApsimX#9261]
### Describe the new feature

Suggest the following changes to Manager codes in the Management toolbox to make them more robust:
- Reset on date: expand the code to act with both "Yes" and "yes"  (while the question does clearly ask for a "Yes", it's too easy to accidentally type 'yes' and then wonder why nothing happens)
- Reset on sowing: same as above
- Sow using a variable rule: use >= instead of > for minimum extractable soil water and accumulated rainfall required for sowing (currently does not sow if you meet these amounts exactly, which is not what the text suggests)
- Various Fertilise manager codes: can we add the depth of application?

**Comment by sno036** [comment]
Might be better to change those 'yes' inputs to a tick box / boolean?
