### ISSUE TITLE
Manager editor - test has stopped working

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#9266]
### What happened?

When editing manager code the test - <ctrl>-T - no longer works: nothing happens. Saving (<ctrl>-S) seems to trigger a test. 

### What Operating System are you on?

Windows

**Comment by par456** [comment]
It's working fine on my system? Is it something to do with that specific file?

**Comment by ric394** [comment]
@peter-devoil were you getting the issue on Linux? 
Also, can you include your file so we can check it please?

**Comment by peter-devoil** [comment]
Hmmm. It appears to be working now. At the type I was fixing missing assemblies, and there were lots of errors. I'll see if I can get a repeatable case together.

**Comment by par456** [comment]
Seems to still be working, closing this issue.
