### ISSUE TITLE
DB presenter hiding data

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#9267]
### What happened?

Perhaps we could adjust the column width to the data and the header, or make the columns adjustable?

![image](https://github.com/user-attachments/assets/102ff89e-2369-4ed0-ab80-e8a0dc427956)
vs
![image](https://github.com/user-attachments/assets/cee3812a-7ddf-44bf-878d-fc30028320f2)

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
@peter-devoil I'm having trouble reproducing this one. Can I get a copy of the APSIM file that caused the issue please?

**Comment by peter-devoil** [comment]
Here you go, @ric394  [dbp.zip](https://github.com/user-attachments/files/16776049/dbp.zip)
