### ISSUE TITLE
Sugar model error: "Cannot find a soil crop parameterisation called SugarcaneSoil"

### ISSUE THREAD

**Issue by daSilva5** [APSIMInitiative/ApsimX#9276]
### What happened?

Hi,
When I replace "Macknade 923 1R" for Ferrosol (Babinda N0649", which I downloaded using the download tool within APSIM next gen, I get this error "Cannot find a soil crop parameterisation called SugarcaneSoil".
It is APSIM version 2024.8.7568.0

Thanks

### What Operating System are you on?

Windows

**Comment by BrianCollinss** [comment]
Does your soil have moisture-related parameters for Sugarcane under SoilWat?

**Comment by daSilva5** [comment]
> Does your soil have moisture-related parameters for Sugarcane under SoilWat?

Hi,
I would say I have the same components I have for this soil in Classic.
![image](https://github.com/user-attachments/assets/e770831f-506d-4c7c-9aa2-695a09ae5431)

**Comment by BrianCollinss** [comment]
Sorry, I meant under Water.

**Comment by par456** [comment]
You'll be missing the sugarcane soil under physical. The soils often come with a bunch of crop soil options, but this one might not have had a sugarcane one. This is what it should look like:

![image](https://github.com/user-attachments/assets/0f63742a-f0e3-4797-9b70-f076697ba8e5)

That just defines how the crop interacts with that soil, such as how deep it can grow in it and what water it would have access to. Structure has to match the physical layers. You'll be able to see an example in the original Macknade 923 1R soil that you replaced.

**Comment by daSilva5** [comment]
> You'll be missing the sugarcane soil under physical. The soils often come with a bunch of crop soil options, but this one might not have had a sugarcane one. This is what it should look like:
> 
> ![image](https://private-user-images.githubusercontent.com/130029141/363812563-0f63742a-f0e3-4797-9b70-f076697ba8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzM5NzMsIm5iZiI6MTcyNTMzMzY3MywicGF0aCI6Ii8xMzAwMjkxNDEvMzYzODEyNTYzLTBmNjM3NDJhLWYwZTMtNDc5Ny05YjcwLWYwNzY2OTdiYThlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwMzIxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTA5ZTlmNmY0MTI2NzIyOTM4OGQ1YjNkYjNjMDdhNTNiYzAyMmQ3MWY2MWM4OGZjZjM4OWQ0N2RjZDJjZjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LsqKJcI6HmYqWA0UUx9bzlIqRU5YBBy6mZAkpNnKxvI)
> 
> That just defines how the crop interacts with that soil, such as how deep it can grow in it and what water it would have access to. Structure has to match the physical layers. You'll be able to see an example in the original Macknade 923 1R soil that you replaced. It also has to be named exactly "SugercaneSoil" otherwise it won't be found by the other components.

I see the problem now. This soil import the "Classic" version for this parameter. 

![image](https://github.com/user-attachments/assets/a7b7d0df-2a10-4fed-848b-d45e3da4eb6e)


If I copy the one from the original soil and delete the "Classic" version it runs. But I notice that the values for PAWC differ and I cannot change them manually.

**Comment by daSilva5** [comment]
> You'll be missing the sugarcane soil under physical. The soils often come with a bunch of crop soil options, but this one might not have had a sugarcane one. This is what it should look like:
> 
> ![image](https://private-user-images.githubusercontent.com/130029141/363812563-0f63742a-f0e3-4797-9b70-f076697ba8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzM5NzMsIm5iZiI6MTcyNTMzMzY3MywicGF0aCI6Ii8xMzAwMjkxNDEvMzYzODEyNTYzLTBmNjM3NDJhLWYwZTMtNDc5Ny05YjcwLWYwNzY2OTdiYThlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwMzIxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTA5ZTlmNmY0MTI2NzIyOTM4OGQ1YjNkYjNjMDdhNTNiYzAyMmQ3MWY2MWM4OGZjZjM4OWQ0N2RjZDJjZjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LsqKJcI6HmYqWA0UUx9bzlIqRU5YBBy6mZAkpNnKxvI)
> 
> That just defines how the crop interacts with that soil, such as how deep it can grow in it and what water it would have access to. Structure has to match the physical layers. You'll be able to see an example in the original Macknade 923 1R soil that you replaced. It also has to be named exactly "SugercaneSoil" otherwise it won't be found by the other components.

It is importing with the old name of the parameter. Renaming it worked!!!
