### ISSUE TITLE
CroptimizR error: The process cannot access the file 'input_file.db'

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9287]
### What happened?

Running the example with docker. It seems the job is done, though I cannot be certain. 

```
System.IO.IOException: The process cannot access the file 'input_file.db' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Models.Optimisation.CroptimizR.Run(CancellationTokenSource cancelToken) in Models\Optimisation\CroptimizR.cs:line 503
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in APSIM.Shared\JobRunning\JobRunner.cs:line 226
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in APSIM.Shared\JobRunning\JobRunner.cs:line 189
```

![image](https://github.com/user-attachments/assets/399f1212-bf6c-4fa0-91bf-f834f99a0015)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
This is a bug I've had in the past as well with croptimizR, but it's caused by something locally and comes and goes. We've been unable to replicate it here at the moment.

But answer is yes, it has completed fully, but in a cleanup step it gets stuck trying to clear a temporary db file. It does have all the data in it.

One thing we've tried is clearing all the temporary files and remanent docker images before running again. Otherwise I don't think we can debug this until it happens to one of us devs again.

**Comment by par456** [comment]
Is this still happening on the latest build? and did you change anything in the example before running it?

Just checking in to see if this is an ongoing problem and see if I can replicate it.

**Comment by BrianCollinss** [comment]
I run the example and did not get the error. Has something changed?

**Comment by par456** [comment]
Not 100%, but we might have got it with another bug fix. We'll close this for now, but if it comes back re-open it and we'll have another look.

**Comment by jgbondad** [comment]
Hi @par456, I'm currently learning croptimzR through the example, and I'm getting the same error.

**Comment by par456** [comment]
Hi @jgbondad are you running on windows, mac or linux?

Also, when you are using the example, are you opening and saving it to a new location, or running it from within the examples folder? Might help me reproduce exactly what you're seeing.

**Comment by jgbondad** [comment]
I'm running it on windows. I've copied the example file into a new folder and have updated the .apsimx path in the code. I am testing the set up on my work laptop (no error and seems to be working), and my office PC (where I get this error). On both systems, I'm following the same procedure, the only differences are the APSIM version and file locations. Could there be something else causing the discrepancy?
