### ISSUE TITLE
Documentation of leaf cohort model

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#93]
Will document the leaf cohort model (Leaf.cs and LeafCohort.cs).

**Comment by byzheng** [comment]
Add a figure (plantuml) to show the life cycle of a leaf cohort. Not sure about the meaning of detachment period (@HamishBrownPFR).

![Life cycle of a leaf cohort](http://byzheng.github.io/ApsimX/Documentation/html/inline_umlgraph_4.png)

**Comment by hol353** [comment]
Bangyou, feel free to commit the figure where you like.

The figure needs a bit of work. Need to put the condition statements (e.g. Plant mortality != null) closer to the diamond shape. Instead of 'Decreases of ...' just say 'Decreases...' Also I don't think the 'Structure' tab is appropriate as we have a Structure class. Perhaps call it what it is 'Leaf cohort life cycle'. I also notice a '~=' in one of the conditional statements. Should this be '!='

Is there going to be a reference to this figure somewhere? Where do you want it to appear in the doco?

**Comment by HamishBrownPFR** [comment]
@byzheng Where are we at with this one?

**Comment by byzheng** [comment]
@HamishBrownPFR I am still working on it, but use different method now. I found it will be simple to document the input and output together to understand the model and spot any strange things. 

You can find the latest version from github: byzheng.github.io/APSIM-Wheat-Doc. I have added a few  warning and important boxes for strange behaviour in the model.

**Comment by HamishBrownPFR** [comment]
@byzheng Your documentation looks really good.  Are you planning to integrate this with the auto documentation system that is used for generating the release documentation?  Otherwise we are going to end up with two sets of documentation and will be duplicating effort.

**Comment by byzheng** [comment]
@HamishBrownPFR  It will be best to merge them together. But I am not sure how to do it in the current stage. I can generate  pure HTML codes from my script and then write into wheat validation file. Just not sure how to align with the structure of wheat  PMF. Can discuss more with you.

**Comment by HamishBrownPFR** [comment]
@byzheng Yep, lets discuss this more.  It would be really good to get our efforts integrated here.

The auto documentation works on the xml in a .apsimx file and the documentation routines in the source code.  The idea of using source code is so the doco is always in sync with the code but it is not possible to put crop specific documentation into generic source code.  This is where xml comes in.  We put memo fields into the xml that configures a model to provide crop specific information.  The memo class renders markdown so we can write markdown in memos and it comes up in the doco.  There is an APSIM.bib file in C:\ApsimX where references that we want to cite are placed (in BibTex format) and these can be cited in memo fields using square brackets as delimiters.  It is also possible to reference an image in memo fields that will be rendered into the doco so the nice graphs you are creating could be included.

Are you coming up to Toowoomba the week, I could show you through it in a bit more detail

**Comment by HamishBrownPFR** [comment]
@byzheng  Not sure about the type of MarkDown.  @hol353 would be able to answer that

**Comment by HamishBrownPFR** [comment]
@byzheng Can we close this issue down as the discussion has moved away from the title?  (We are trying to keep the issues list tidy so it is easier to focus on  the things that need fixed).  The documentation of the wheat model sits under the major task #454.

I will add your name @byzheng and Karin's into the title page for the wheat documentation (in Prototypes\Wheat\WheatValidation.apsimx and then we can all contribute there.

**Comment by byzheng** [comment]
Yes I will close it now.
