### ISSUE TITLE
Manager

### ISSUE THREAD

**Issue by IrisVogeler** [APSIMInitiative/ApsimX#9301]
### What happened?

I have used a manager folder where I put in manager scripts for sowing, fertilisation and harvesting of Maize.
When doing long term simulations, I get crazy results.
When I instead have the manager scripts directly in the Field, it works ok.

### What Operating System are you on?

Windows

**Comment by hut104** [comment]
Yes, this is a known behaviour.

Folders are scoping units.  This limits the scope of data comms for certain things.  e.g. One can have a folder of graphs and those graphs only show data for simulations within that folder.

This means that scripts within a folder will also be scoped.

Zones (or fields) are also scoping units.  Placing scripts within a zone/field will access data within that scoping unit.

Scoping is a complex matter and difficult to explain simply, but perhaps we should document this for users.
________________________________
From: IrisVogeler ***@***.***>
Sent: Tuesday, 10 September 2024 12:59 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Manager (Issue #9301)


What happened?

I have used a manager folder where I put in manager scripts for sowing, fertilisation and harvesting of Maize.
When doing long term simulations, I get crazy results.
When I instead have the manager scripts directly in the Field, it works ok.

What Operating System are you on?

Windows

**Comment by BrianCollinss** [comment]
A fairly similar issue: https://github.com/APSIMInitiative/ApsimX/issues/8885

**Comment by par456** [comment]
Closing this, it's not so much a bug, as a misunderstanding how folders currently work. We'll track the changes to folders in the other linked issue.
