### ISSUE TITLE
Graph limits must account for error bars

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9309]
### What happened?

Would be nice to also consider the size of the markers when determining the vertical limits.

![image](https://github.com/user-attachments/assets/67247f96-19bc-4f3b-9809-281dabf90f19)

![image](https://github.com/user-attachments/assets/ee26f001-1897-4eeb-9d8c-b9bac5b0b8e4)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Until this is fixed, you can manually adjust the axis to get everything into view. But yeah, the automatic sizing should take this into account.
