### ISSUE TITLE
Move to .NET 4.5

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#931]
Any reasons why we shouldn't move to .NET 4.5? I wish to use the BioMA disease model by referencing their .NET 4.5 assemblies. I can't do that from a .NET 4.0 assembly.

**Comment by hol353** [comment]
@zur003 Eric do you see any problems moving to .NET 4.5 for APSIMx?

**Comment by zur003** [comment]
I don't see any problems with that. I would welcome the move.
