### ISSUE TITLE
Filter ObsPred graphs using cultivar

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#935]
For some reason the filter just removes the colors and not all the irrelevant data

**Comment by hol353** [comment]
You need to only use column names (fields), in square brackets, from the predictedobserved table you are graphing from. Cultivar name isn't part of this table. If you add cultivar name to the observed ssheet and the predicted table then it will appear in the predictedobserved table to be used in a filter.
