### ISSUE TITLE
Download the debian file from the APSIM website.- Link not working

### ISSUE THREAD

**Issue by BFLOHR100** [APSIMInitiative/ApsimX#9361]
### What happened?

Hi I want to download latest release of Next Gen, but link to download debian file is not working on instructions.
Cheers 

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
The link seems to be working ok now

![image](https://github.com/user-attachments/assets/2463a880-1671-40eb-9904-e9222087a9d1)

**Comment by par456** [comment]
The site was done briefly last week due to a crash, it may have been when you were trying to access it. Should be right now.
