### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#9362]
### What happened?

The page at https://www.apsim.info/apsim-model/ 
has a broken link toward the bottom of the page for APSIM NG doco.

Similarly, there are several broken links at and https://www.apsim.info/apsim-model/apsoil/
Perhaps a review of pages is required.

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
These specific links have been fixed.
However I'm not sure where Soil Water Express resides? @hol353 is this still available?

**Comment by hol353** [comment]
Nope, I don't think Soil Water Express is available anymore.

**Comment by ric394** [comment]
I've removed the soil water express section .

**Comment by par456** [comment]
There is a page called development plan (accessible from About Us) that just links to a document from 2022: https://www.apsim.info/about-us/reference-panel/development-plan/

What changes are needed here?
