### ISSUE TITLE
Ensure existing model documentation is the same as before

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#9376]
### Describe the new feature

The documentation generated for plant models and some other select models should look the same as the current version and incorporate suggested changes to simplify the documentation.

**Comment by ric394** [comment]
# Documentation check list
> shows documents that have been checked

- [ ] AGPRyegrass
- [ ] AGPWhiteClover
- [ ] Barley
- [ ] Canola
- [ ] Chicory
- [ ] Chickpea
- [ ] Eucalyptus
- [ ] FodderBeat
- [ ] Gliricidia
- [ ] Maize
- [ ] MicroClimate
- [ ] MungBean
- [ ] Nutrient
- [ ] Oats
- [ ] OilPalm
- [ ] Peanut
- [ ] Pinus
- [ ] PlantainForage
- [ ] Potato
- [ ] RedClover
- [ ] SCRUM
- [ ] Slurp
- [ ] SoilArbitrator
- [ ] SoilTemperature (under review)
- [ ] SoilWater
- [ ] Sorghum
- [ ] Soybean
- [ ] Sugarcane
- [ ] Stock
- [ ] SWIM
- [ ] Wheat
- [ ] WhiteClover
- [ ] Climate Controller
- [ ] Life cycle
- [ ] Manager
- [ ] Parameter sensitivity (Morris)
- [ ] Parameter sensitivity (SOBOL)
- [ ] Parameter sensitivity (Factorial ANOVA)
- [ ] Predicted/Observed data handling
- [ ] Report
- [ ] Clock

**Comment by par456** [comment]
Change DocPlant to use IPlant instead of Plant so that it works with the weird crops.

**Comment by ric394** [comment]
# Some bugs

**SoilTemperature**
- [ ] SoilTemperature is showing remarks in bold. 
- [ ] Remarks and summary? should be placed atop memos

**SoilArbitrator**
- [ ] Title page memo under simulations causes issues of duplicate titles

**Comment by ric394** [comment]
This is now complete. resolved by #9433
