### ISSUE TITLE
Simple grazing

### ISSUE THREAD

**Issue by ashehad** [APSIMInitiative/ApsimX#9440]
### What happened?

I have been using simple grazing within the AgPasture module. I set the proportion of N going to Dung as "blank" and C:N ratio of biomass for dung to 0. I am considering grazing every two weeks (HarvestedWt is okay), but for some reason DungN and DungWt gets reported every other harvest. Please see attached. 
![Harvest_DungN](https://github.com/user-attachments/assets/00862324-976a-4209-96be-11ee0b566903)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
Do you have an apsimx file that you could provide that is causing this issue? 

I wonder if something is missing which is causing the report to only happen every other harvest.

**Comment by ashehad** [comment]
Please find the apsimx file (zipped) in the attachment. 
[AgPastureAhaura.zip](https://github.com/user-attachments/files/17713673/AgPastureAhaura.zip)

**Comment by sno036** [comment]
@ashehad  - you are getting the reporting every second grazing because you have difference settings in the two SimpleGrazing components in the simulation.

**Comment by ashehad** [comment]
@sno036 thanks! By having only one script (as you pointed out), it works well.
