### ISSUE TITLE
Slope effects on weather module does not work when implemented at the simulation level above separate zones

### ISSUE THREAD

**Issue by MikeDoddNZ** [APSIMInitiative/ApsimX#9449]
### What happened?

If implemented at the simulation level, with multiple zones having different aspects and slopes, slope effects does not distinguish these params between the zones. If those different aspects/slopes are implemented at the zone level, within separate simulations, it works OK. The attached sim file, with two sims and zones using similar slope/aspect params, demonstrates this. The overlap in output can be seen by viewing the charts using 'vary by sim' or 'vary by zone'.
[test1.zip](https://github.com/user-attachments/files/17759507/test1.zip)

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
There doesn't seem to be any handling in the model for multiple zones in it's current implementation, it will simple use the first Zone it finds.
For the moment I suggest this model has it's ValidParents changed to Zone until a solution is created that allows handling of Simulations with multiple Zones.
