### ISSUE TITLE
Cannot find a match for link Irrigation in model .Simulation.Field.Manager folder.Irrigate to crop PAW at sowing.ScriptSimulationsSimulationFieldManagerfolderIrrigatetocropPAWatsowing If the manager script is within a folder, it's linking scope will be limited to that folder.

### ISSUE THREAD

**Issue by daSilva5** [APSIMInitiative/ApsimX#9450]
### What happened?

Hi,
I am running the Sugarcane example, but with the "Irrigate to crop PAW at sowing" manager. Everything else is default. Simulation runs without this manager script with no problems. 

I get the following error message "Cannot find a match for link Irrigation in model .Simulation.Field.Manager folder.Irrigate to crop PAW at sowing.ScriptSimulationsSimulationFieldManagerfolderIrrigatetocropPAWatsowing If the manager script is within a folder, it's linking scope will be limited to that folder."
[irrigation.zip](https://github.com/user-attachments/files/17792781/irrigation.zip)

I hope you can help!
Thanks

### What Operating System are you on?

Windows

**Comment by par456** [comment]
In the field node, you need to add an Irrigation model underneath it, that is what the manager script is looking for. (use Add Model to do that).

However, I would also recommend moving your manager scripts out of the folder they are currently in as the error message you have suggests, as folders restrict visibility to the rest of your simulation, and when linking, it may even link to the wrong model. 

The script may even work, but it is bad practice in NextGen to structure your manager scripts like that. It's much better to just have them as a child of the field, that way everything it needs to link to is in the same scope.

**Comment by daSilva5** [comment]
> In the field node, you need to add an Irrigation model underneath it, that is what the manager script is looking for. (use Add Model to do that).   

_Oh yes, that works!_
 
> However, I would also recommend moving your manager scripts out of the folder they are currently in as the error message you have suggests, as folders restrict visibility to the rest of your simulation, and when linking, it may even link to the wrong model.  
_The error disappears completely just by adding the irrigation node._

Thank you so much!
