### ISSUE TITLE
"How to contribute" link is broken

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9451]
### What happened?

The page is at "https://apsimnextgeneration.netlify.app/contribute/howtocontribute/howtocontribute/" while the link is to "https://apsimnextgeneration.netlify.app/contribute/howtocontribute". 

![Screenshot_20241118_211614_Chrome](https://github.com/user-attachments/assets/e0815112-8b4b-4321-b0e2-23e74dd0709b)

### What Operating System are you on?

Windows

**Comment by par456** [comment]
We had to restart the apsim server this is hosted on a few times yesterday afternoon, I wonder if that's what caused this. 

It seems to be up for me again now.

**Comment by BrianCollinss** [comment]
It's still the same for me.
