### ISSUE TITLE
CLEM: product harvested not tracked in mixed cropping

### ISSUE THREAD

**Issue by amboara-MDG** [APSIMInitiative/ApsimX#9456]
### What happened?

Hello, 

In the cropping system example, there is an intercropping of tomatoes and cucumbers.
In the reports, I can see the labour performed for tomatoes, and cucumbers. But in the products ledger, I can not see the product harvested for cucumbers.
It also occured when I have built my simulation for intercropping where I am mixing maize and beans as intercropping. And the issue was the same. I could get the amount of maize harvested, but not the beans.  
Does it mean that the activities for the other crop were ignored for harvest?

How may I track the amount harvested for the other crop?

You will see my simulation file attached below. 

[test_mixed_cropping.zip](https://github.com/user-attachments/files/17816833/test_mixed_cropping.zip)

Thank you 

### What Operating System are you on?

Windows

**Comment by lie112** [comment]
The simulation attached does not include any of the intercropping you mentioned (CLEM_EK_Sheep with FileForageOther)
