### ISSUE TITLE
All texts are displayed vertically in new docs website

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9519]
### What happened?

This is on cellphone. 

![Screenshot_20241207_153241_Chrome](https://github.com/user-attachments/assets/4fe5fcdb-dbd8-4e85-a692-d4e9ac78db78)
![Screenshot_20241207_153235_Chrome](https://github.com/user-attachments/assets/ccc2c77e-6ccc-4f39-8faa-f61c9e9726eb)

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
This will be resolved by #9518.

**Comment by ric394** [comment]
This one is now resolved. 
You were too quick for us @BrianCollinss 😄 

![image](https://github.com/user-attachments/assets/5604336b-e01a-4573-960b-af4896a4cbb8)
