### ISSUE TITLE
DCaPST document

### ISSUE THREAD

**Issue by docalexwu** [APSIMInitiative/ApsimX#9522]
### What happened?

Hi Team,

My previous post about uploading the DCaPST science document to the APSIM website seems to have gone missing(?)
The APSIM documentation page currently does not have DCaPST.
Could you please check what's happening.

Thanks.
Alex

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
Hi @docalexwu this has now been resolved. Thanks for being patient.

![image](https://github.com/user-attachments/assets/49d4e474-91d8-4f23-8de5-8ce7165319cf)
