### ISSUE TITLE
Should --csv work with --in-memory-db?

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#9555]
### What happened?

My goal is to avoid a large DB file being written. I use this command with and without the `--in-memory-db` flag:

`APSIMPath --apply ConfigFile --cpu-count 5 --csv`

And get this error with the flag present:

`Unable to make csv file(s) for C:\XYZ\Temp.db`

### What Operating System are you on?

Windows

**Comment by ric394** [comment]
I'll have to investigate this one. No sure if it is compatible.

**Comment by BrianCollinss** [comment]
How can an in-memoryDB be read?

**Comment by BrianCollinss** [comment]
@ric394 It works when no config file is present. (Bangyou also confirmed this).

**Comment by byzheng** [comment]
This command is working:

All commands are run under `C:\APSIM\ApsimX\`

```
bin\Release\net6.0\Models.exe  --in-memory-db --csv Examples\Wheat.apsimx

bin\Release\net6.0\Models.exe  --csv Tests\Validation\Wheat\Wheat.apsimx
```

These commands are not working

```
bin\Release\net6.0\Models.exe  --in-memory-db --csv Tests\Validation\Wheat\Wheat.apsimx

bin\Release\net6.0\Models.exe  --in-memory-db Tests\Validation\Wheat\Wheat.apsimx
```

with first error

```
System.Exception: Error in ExcelMultiInput: file 'C:\APSIM\ApsimX\Observed.xlsx' does not exist
```

The `Observed.xlsx` should locate under `C:\APSIM\ApsimX\Tests\Validation\Wheat\Wheat.apsimx`


It seems `--in-memory-db` can not find the observation files.

**Comment by BrianCollinss** [comment]
On my Windows-operated machine, Models always produces the DB of the same size with and without `--in-memory-db`.

**Comment by BrianCollinss** [comment]
Correction: If the DB already exists, Models does not replace it with an empty DB, hence 100 kB file. Otherwise, it will create a 4 kB (empty) DB.

**Comment by BrianCollinss** [comment]
I close this for now. It works when I run the command via command line. But in R and with

```
sprintf('%s --apply %s --csv %s', shQuote(APSIMPath), 'Config.cfg', paste('--cpu-count', NCPUs))
```

I get that error.
