### ISSUE TITLE
Graph's data point on-click labels extend display to the right

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#957]
When clicking a point in a graph which is on the far right edge, the label (and esp. the y-value) extend out of the display to the right.
This makes it difficult to compare e.g. simulated and observed values.
![apsim_graph_data-value](https://cloud.githubusercontent.com/assets/17924125/17056130/9861d384-5011-11e6-88eb-b7415c8f89d8.jpg)

**Comment by hol353** [comment]
Yes this is a problem but unfortunately not easy to fix. The workaround is to pan the graph by dragging it with the right mouse button so that the graph is away from the right edge of the window, then click on the point.

**Comment by zur003** [comment]
It's a problem in OxyPlot, but that's a open-source project, and it should be possible to create a suitable fix and submit it. I will note that the WPF version of OxyPlot handles this very well, but the Gtk# version is also a problem. I'm not quite sure why, as the basic plotting elements don't differ all that much between versions. I suspect it's really just a question of where time has been invested, and that the WPF version could probably be "ported" to the Windows.Forms and Gtk# versions without too much effort.
